### ISSUE TITLE
buying discounted gear locks you out of the nondiscounted version too

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#73980] opened 2023-03-14 00:18 UTC
Round ID: [201774](https://scrubby.melonmesa.com/round/201774)

Testmerges: https://github.com/tgstation/tgstation/pull/72981

Reproduction: buy a discounted item. attempt to buy another copy of the item under the normal uplink (nondiscounted). it's greyed out

**Comment by Sealed101** [comment] 2023-03-14 07:25
duplicate of #73560
profakos i hope you will deliver

**Closed by Sealed101** 2023-03-14 07:25 UTC
