### ISSUE TITLE
Labor shuttle duplicate console 

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#26399] opened 2017-04-20 13:19 UTC
The stacking console in the secure section of the laborshuttle is a point claim console, instead of a stacking console, therefore the minerals can't be unloaded.

Happens on Boxstation and Meta, probably on serveral others too.

**Comment by ShizCalev** [comment] 2017-10-09 00:44
Believe this was a dupe of #16936

**Closed by ShizCalev** 2017-10-09 00:44 UTC
Labels: Map Issue
