### ISSUE TITLE
Afterattack is not called on decals

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#35176] opened 2018-01-31 18:17 UTC
You can no longer target decals (graffiti, blood, etc.) with items, specifically cleaning objects like soap or mops. If you click on them directly nothing happens. My testing indicates its because the afterattacks of these items simply aren't called when you click on decals now. 

How to reproduce: Click on blood with soap

Soap has an afterattack check for decals that should have you "scrub" that specific decal, instead nothing will happen.

**Comment by Nabski89** [comment] 2018-01-31 21:28
Some fly's were reporting the same issue with being able to eat.

**Comment by ShizCalev** [comment] 2018-02-01 12:16
https://github.com/tgstation/tgstation/blob/9d0e97fc8d73165194462cffbcc6a5f3abff867c/code/game/objects/items/mop.dm#L57-L61

why is this even in mop.dm???

**Comment by lzimann** [comment] 2018-02-01 12:23
I don't think that is the cause of the issue, that has been around for 5 years or so, the problem is decals not calling the `Initialize()` parent

**Comment by AnturK** [comment] 2018-02-01 12:32
Fixed by #35183

**Closed by AnturK** 2018-02-01 12:32 UTC
Labels: Bug, Needs Reproducing
