### ISSUE TITLE
You cannot hide in crates anymore

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50370] opened 2020-04-03 19:48 UTC
## Round ID:
[133831](https://scrubby.melonmesa.com/round/133831)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Spawn in a crate, open it, move onto it, lie down and try to close the crate. It will say 
There's something too large in the crate, preventing it from closing. and you cannot hide.

**Comment by Dorsisdwarf** [comment] 2020-04-05 10:54
Dupe of #50382 and #50236

**Closed by Dorsisdwarf** 2020-04-05 10:54 UTC
