### ISSUE TITLE
Player sprite is occasionally drawn in wrong screen position and rotation

### ISSUE THREAD

**Issue by Eggbertx** [tgstation/tgstation#56310] opened 2021-01-21 03:15 UTC
## Round ID:
[154677](https://sb.atlantaned.space/rounds/154677)

## Reproduction:
This doesn't appear to have a consistent cause, but it seems to usually happen when I attack something or someone. But during the referenced round, I wasn't interacting with anything when it started.
![tgstation issue](https://user-images.githubusercontent.com/76852/105275071-57e57200-5b53-11eb-8c1c-7df7f48756c8.png)

**Comment by dragomagol** [comment] 2021-01-21 17:49
Duplicate of #55842

**Closed by dragomagol** 2021-01-21 17:49 UTC
