### ISSUE TITLE
You can move diagonally in pipes, jump between pipes, jump out of pipe. Plus some render issues

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#34009] opened 2018-01-01 15:16 UTC
[video](https://drive.google.com/file/d/1bn3xEDd400kkeH-31b9XJeh65NQxGtb2/view?usp=sharing)

**Comment by WJohn** [comment] 2018-01-01 18:00
Dupe of #33528

**Closed by WJohn** 2018-01-01 18:00 UTC
