### ISSUE TITLE
Items and machines that open a new window can't be used

### ISSUE THREAD

**Issue by VitorPassos** [tgstation/tgstation#51176] opened 2020-05-19 22:24 UTC
## Round ID: 
[137434](https://scrubby.melonmesa.com/round/137434)

## Testmerges: 
#50963: 'Ports stat browser pane' by actioninja at commit 11d9509caa
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17
#50912: 'tgui: Window Recycling, Simplified DM API' by actioninja at commit 15c39e0a1f
#51071: 'Midrounds and latejoin rulesets now pre-execute' by kriskog at commit 0f2a994ffa
#51148: 'Fix ghosts alt/ctrl clicking atmos devices' by TetraK1 at commit 4dc245c054

## Reproduction: 
Reproduction methods are unknown, but the issue is as follows:
Upon entering a round, be it from the start or latejoining, certain vendors / computers / assorted items that pop in a new window refuse to open said window, and nothing happens at all. Exiting and reloading the game seems to either shuffle which windows will be unable to open or only allow you to interact with certain things once, and then never again. Things that refuse to open include drink dispensers, vendomats, tablets and the self diagnose stations in medical, shuffled randomly. Alt-clicking compatible machines, like the self diagnose stations, will still work normally.

While this was happening, other players were asked to interact with said unresponsive items / vendors, and those were able to use them as normal. Unsure if this a client side issue or not. This issue has been happening for multiple rounds and others did not mention anything of the sorts.

**Comment by nemvar** [comment] 2020-05-19 22:48
Probably caused by #50912

**Comment by kopoba** [comment] 2020-05-20 06:49
I think i encounter same bug in this issue https://github.com/tgstation/tgstation/issues/51122
For me operating computer just stop showing popup window during operation. Click click click him and nothing happens. 
Sometimes i was having same issue in old old days and moving from console and back fix it but not nowadays.

**Comment by Angustmeta** [comment] 2020-05-20 21:04
From testing it seems to be a problem with the "no frills" setting. Changing to "fancy" has fixed it for me every time.

**Comment by stylemistake** [comment] 2020-07-16 19:41
Got fixed with tgui 4.0

**Closed by stylemistake** 2020-07-16 19:41 UTC
Labels: Bug, Test Merge Bug, UI
