### ISSUE TITLE
Bug that let's you get an item in two places at once very easily (infinite energy gun, teleport any item etc)

### ISSUE THREAD

**Issue by Fhaxaris** [tgstation/tgstation#52100] opened 2020-07-08 19:54 UTC
## Round ID:
Not Applicable

It's so general it's hard to explain, but you open the alt menu with the item and:
1. Pick up item.
2. Quickly put the item in something that can receive it.
3. Quickly pick it up again.
here is a visual
![cmWuP6DcnL](https://user-images.githubusercontent.com/13771064/86963083-8f497f80-c129-11ea-986c-ab6bd198ca67.gif)
The disabler is now in my hand, and in the charger at the same time. Meaning it will charge forever while I shoot it, basically meaning I have infinite ammo. This works for so many other things, ID's in a PDA, even computer boards.

**Comment by ATH1909** [comment] 2020-07-08 20:12
oooooooooh

iiiiiiiinteresting.....

**Comment by Fhaxaris** [comment] 2020-07-08 20:13
nuke disc in the destructive analyzer, let's you teleport it to your hands whenever you want. i mean it goes on and on

**Comment by LemonInTheDark** [comment] 2020-07-08 22:11
this smells of a byond issue. Not sure how we could fix this

**Comment by Doosteroni** [comment] 2020-07-08 23:53
> this smells of a byond issue. Not sure how we could fix this

Would it be possible to disable the alt menu? It’s never used as far as I know

**Comment by Fhaxaris** [comment] 2020-07-09 00:06
you can still do the bug without the alt menu if you're lagging hard enough, around 150ms

**Comment by Tlaltecuhtli** [comment] 2020-07-09 04:46
its the same good old bug where transferring items from tile to hand or hand to object with lag takes so long it glitches, nothing new
#43486

**Comment by kopoba** [comment] 2020-07-09 08:49
and this https://github.com/tgstation/tgstation/issues/51429 and this https://github.com/tgstation/tgstation/issues/46737

**Comment by GravitronBlue** [comment] 2020-07-09 15:07
Honestly a dupe of #41363, but it's good to see this issue getting attention.

**Comment by githubuser4141** [comment] 2020-07-10 22:00
> > this smells of a byond issue. Not sure how we could fix this
> 
> Would it be possible to disable the alt menu? It’s never used as far as I know

Eh, it's useful for sorting through a lot of items at once think: a captain/HoS's locker to pick out what's needed rather then either pixel hunting for the right items or using the right-click menu (clunky and takes time) or dumping everything on the floor.

**Comment by callanrocks** [comment] 2020-07-11 08:09
The alt menu is outright superior to right clicking, especially if someone is trolling with huge stacks of items.

**Closed** 2020-07-11 18:25 UTC
Labels: FUCK, In Game Exploit
