### ISSUE TITLE
nightmare lighteater not disabling lights on people

### ISSUE THREAD

**Issue by token-map** [tgstation/tgstation#54675] opened 2020-10-29 04:00 UTC
## Round ID: 
[149265](https://scrubby.melonmesa.com/round/149265)

## Testmerges:
The following pull requests are currently test merged:
#54590: 'Families 3.0: More Gangs, More Problems' by Iamgoofball at commit e2ff880d34
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 1baeff0998

## Reproduction:
title. as nightmare, hitting someone with lights on with the light eater will not disable their lights. possibly related to the lighting rework?

**Comment by ArcaneDefence** [comment] 2020-10-30 01:51
This is a duplicate of this https://github.com/tgstation/tgstation/issues/54638

**Comment by ArcaneMusic** [comment] 2020-11-01 18:29
Resolved.

**Comment by EOBGames** [comment] 2020-11-01 18:50
taking arcane's word for it

**Closed by EOBGames** 2020-11-01 18:50 UTC
