### ISSUE TITLE
raw html in centcom status summary, shift divergencies

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#69113] opened 2022-08-10 08:16 UTC
## Round ID:
[R188248](https://tgstation13.org/parsed-logs/sybil/data/logs/2022/08/10/round-188248/)

## Testmerges:
#69031 
#69079 
#69088

## Reproduction:
![0KrrBrk0FL](https://user-images.githubusercontent.com/85910816/183850690-bafbee91-b5b4-467c-a05a-4d82d70b3473.png)

**Comment by dragomagol** [comment] 2022-08-10 15:01
Duplicate of #69016

**Closed by dragomagol** 2022-08-10 15:01 UTC
Labels: Grammar and Formatting
