### ISSUE TITLE
Some sort of Z-Level or loading error causing me to being put inside of the Necropolis wall from space.

### ISSUE THREAD

**Issue by Dariuscpt** [tgstation/tgstation#29920] opened 2017-08-15 11:11 UTC
Round ID: 74737

Some sort of Z-Level bug causing you to get teleported to inside of the Necropolis wall
![bug1](https://user-images.githubusercontent.com/20743371/29313463-0fe8449c-81b2-11e7-8e30-4bfecfc6118d.png)

I was on the Derelict station with the three sleepers (The one that starts off with a lockdown, and has hivebots on the other part of the station), spawned as the engineer Becky Rader and I used my suit to go around to the prototype lab. 
![location](https://user-images.githubusercontent.com/20743371/29313584-c6160ede-81b2-11e7-8301-5214274a0b36.png)

After grabbing things in there, I accidentally pushed myself off into space going directly down then went to grab a drink as I floated off into space. When I got back, My character and all the items were inside of the necropolis wall with no way of getting out. This might be a loading issue or a Z-level issue and could simply be round specific, however, I'm going to report it here anyway.

**Comment by KorPhaeron** [comment] 2017-08-15 11:13
@Dariuscpt 

Was the clock cult rework testmerged?

**Comment by Dariuscpt** [comment] 2017-08-15 11:16
I'm not sure, however I do believe the clock cult ship was on the map somewhere.

**Comment by Dorsisdwarf** [comment] 2017-08-15 14:53
At least three other people ended up in lavaland when falling through space in that round

**Comment by KorPhaeron** [comment] 2017-08-15 14:57
I think its the clock cult city breaking z transitions

**Comment by ShizCalev** [comment] 2017-08-15 20:31
duplicate of #29875

**Comment by Cyberboss** [comment] 2017-08-15 20:39
Duplicate of #29875

**Closed by Cyberboss** 2017-08-15 20:39 UTC
