### ISSUE TITLE
pAI loudness booster interface bug

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#44608] opened 2019-06-17 22:13 UTC
Issue reported from  Round ID: 110843 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1470

Encountered multiple instances where any attempt to open the loudness booster interface as an instrument would result in it being entirely unresponsive. I was able to change the instrument normally though.

Reconnecting and restarting byond had no effect, only being wiped and reinstalled as a pAI worked, and having done that after playing one song stopping to change the song locked the synth interface up, and it was non-responsive again.

**Comment by ShizCalev** [comment] 2020-07-30 04:38
Duplicate of #51151

**Closed by ShizCalev** 2020-07-30 04:38 UTC
Labels: Bug, Needs Reproducing
