### ISSUE TITLE
You can't steal MODsuits as Spy

### ISSUE THREAD

**Issue by delingar** [tgstation/tgstation#85209] opened 2024-07-23 21:08 UTC
## Issue Summary

You can't steal Modsuits and Microwaves as Spy. They just interact normally, how it have to be. 

## Round ID:

Down-down stream: https://github.com/Fluffy-Frontier/FluffySTG

## Reproduction:
 1. Become Spy
 2. Roll some head of staff MOD / Microwave oven as bounty (Maybe, microwave is not working properly only with PDA uplinks)
 3. Try to steal. (Harm mode is not working)

**Comment by carlarctg** [comment] 2024-07-23 21:09
tg hates downstream reports fyi

i can confirm this happens in tg as well though

cant scan any storage tiems such as medal box. youc can scan modsuits if you strip storage  module

**Comment by SmArtKar** [comment] 2024-07-23 21:15
Duplicate of #84434

**Closed by SmArtKar** 2024-07-23 21:15 UTC
