### ISSUE TITLE
Lava burns items when taken out of inventory and put in hand while over lava

### ISSUE THREAD

**Issue by Chickenmonster1** [tgstation/tgstation#35402] opened 2018-02-07 02:42 UTC
[Round ID]:  Unknown (several hours ago/repeatable I believe)
 
[Testmerges]: None recent, older bug, thought it was fixed long ago.

[Reproduction]:  While in a boat or flying over lava with wings on lavaland, putting an item into your hand from your backpack, pockets, belt slot, or really anywhere will cause the item to begin burning as though it had touched the lava.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by YPOQ** [comment] 2018-02-07 02:45
#25860

**Comment by Repukan** [comment] 2018-02-07 03:23
Dupe

**Comment by AnturK** [comment] 2018-02-07 07:28
Duplicate of #25860

**Closed by AnturK** 2018-02-07 07:28 UTC
