### ISSUE TITLE
Action buttons cant be dragged anymore

### ISSUE THREAD

**Issue by GhostPlayer6942** [tgstation/tgstation#84244] opened 2024-06-22 20:42 UTC
## Issue Summary
You can no longer drag buttons to anywhere you want on the screen, and if you try to they glitch out and dissapear or just wont line up with the other buttons.

## Round ID:
[230963](https://scrubby.melonmesa.com/round/230963)

## Testmerges:
[[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
[Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
[Bitrunning: Tweaks, QoL and removals](https://www.github.com/tgstation/tgstation/pull/84125)

## Reproduction:
equip anything that has buttons (oxygen mask and tank, RCD, ect.)
drag them anywhere on the screen

https://github.com/tgstation/tgstation/assets/72633394/c998455b-f0c1-4923-9780-816eb5e655af

**Comment by Sadboysuss** [comment] 2024-06-22 22:57
duplicate of closed issue https://github.com/tgstation/tgstation/issues/84045
Was supposed to be fixed by https://github.com/tgstation/tgstation/pull/84071

**Comment by PapaMichae1** [comment] 2024-06-23 02:19
this is an outrage revoke the gbp forthwith

**Comment by optimumtact** [comment] 2024-06-24 22:32
the fact it was supposedly fixed but is still occuring means there may be a byond specific version issue at play too.

**Closed** 2024-06-27 03:48 UTC
Labels: Bug, Tested/Reproduced, UI
