### ISSUE TITLE
Bluespace launchpad/abductor emergency teleport bypasses anti teleport area's such as AI Sat

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#68626] opened 2022-07-21 02:57 UTC
Round ID: #187002

## Reproduction:
Despite the AI sat having teleport protection it doesn't work with bluespace launchpads allowing them to bypass any protection it had and kill/card it instantly. Something also related to this, the abductors emergency teleport can also bypass the anti teleportation area.

**Comment by private-tristan** [comment] 2022-07-21 05:43
from looking at PRs (#52718), it seems that the anti teleport for AI core is only supposed to apply for abductors, not any other source of teleportation like hand teles or briefcase launchpads

**Comment by timothymtorres** [comment] 2022-07-21 07:56
Duplicate of #64879

**Closed by timothymtorres** 2022-07-21 07:56 UTC
