### ISSUE TITLE
Using a multitool on an airlock will cause you to try and open the door

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#35022] opened 2018-01-27 19:28 UTC
Issue reported from  Round ID: 82647 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

If you screwdriver a panel off an airlock and use a multitool on the door, the door will open/beep if you don't have access. The menu will open and function like normal.

Normally, the menu would open, and the input would NOT open the door.

#33166 was testmerged when bug occurred

**Comment by YPOQ** [comment] 2018-01-27 21:03
#33166 testmerged? Honestly can't find testmerges in the logs.

**Comment by Anonmare** [comment] 2018-01-27 21:07
Possibly related but this bug has been here for far longer: Using a multitool on an SSU with its maint panel open will make you hit the SSU with it.

**Comment by Qbopper** [comment] 2018-01-27 21:15
@YPOQ yeah, sorry, forgot to add that

**Comment by kevinz000** [comment] 2018-01-27 21:59
on it

**Comment by Tlaltecuhtli** [comment] 2018-03-20 22:24
couldnt reproduce

**Comment by Anonmare** [comment] 2018-12-10 19:00
This is fixed as of #39780

**Closed** 2019-07-20 00:22 UTC
Labels: Bug
