### ISSUE TITLE
fighting the colossus or wendigo lags the ever loving hell out of your game

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#71144] opened 2022-11-06 21:30 UTC
Round ID: [193848](https://scrubby.melonmesa.com/round/193848)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [b7e33e5de1265067957a15f549fdc271c09025f3](https://www.github.com/tgstation/tgstation/commit/b7e33e5de1265067957a15f549fdc271c09025f3)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
## Reproduction:
fight the colossus or wendigo and get to a later stage of the fight. the game lags to shit and is really hard to win due to not being able to see where the hell their bolts are going

**Comment by Sealed101** [comment] 2022-11-06 22:30
remember that high lag is currently occurring the most on highpop shifts on multi-Z maps. from my experience, lowpop rounds barely get any lag even on a multi-Z map, and fighting a colossus on a lowpop round did not lag out the server in any noticeable way

**Comment by timothymtorres** [comment] 2022-11-07 03:19
Duplicate of #49414

**Closed by timothymtorres** 2022-11-07 03:19 UTC
