### ISSUE TITLE
Protect and Kill the Same Person As A Traitor

### ISSUE THREAD

**Issue by BlueNothing** [tgstation/tgstation#36616] opened 2018-03-22 01:46 UTC
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
Round 85343

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
The traitor log reports that Phoenix Perkins (Captain), had three objectives, two of which were: 
Objective #2: Protect Randolph P. Checkers Esq., the Quartermaster. Success!
Objective #3: Prevent Randolph P. Checkers Esq., the Quartermaster, from escaping alive. Success!

**Comment by alexkar598** [comment] 2018-03-22 02:15
Since when can captains be traitor?

**Comment by newfren** [comment] 2018-03-22 02:16
Important to note that prevent someone from escape alive does NOT mean kill. It can also mean to strand on the station. These objectives don't conflict and are a set of objectives I often see malf AIs possess.

**Comment by BlueNothing** [comment] 2018-03-22 02:20
Oops, overlooked that.

**Comment by ShizCalev** [comment] 2018-03-22 03:11
Not a bug, though I'll keep this open until someone checks to make sure that the assassinate and protect objectives can't be assigned to the same target.

**Comment by RandomMarine** [comment] 2018-03-22 04:15
https://github.com/tgstation/tgstation/blob/master/code/modules/antagonists/traitor/datum_traitor.dm
Going by this, only protect can normally be assigned to traitor AIs, and is always coupled with the maroon objective.

If your example was a real case it was probably admin shenanigans, especially if the captain was a traitor in the first place.

**Comment by AnturK** [comment] 2018-03-22 07:43
Admins

**Closed by AnturK** 2018-03-22 07:43 UTC
Labels: Not a bug
