### ISSUE TITLE
Typing in textarea is messed up (tablet computer, bounty app)

### ISSUE THREAD

**Issue by drcatdoctor** [tgstation/tgstation#52130] opened 2020-07-09 19:06 UTC
## Round ID: [141550](https://scrubby.melonmesa.com/round/141550)

on Basil

## Testmerges:

#52085: 'tgui 4.0' by stylemistake at commit 643d0bba36

## Reproduction:

1. install bounty app on tablet computer
2. open app, click on textarea for typing in what the bounty is

you will notice that the cursor doesn't go as quickly as your letters, so you have to put like 0.5sec between every keypress or each keypress overwrites the previous one.

I am on windows if that matters.

**Comment by optimumtact** [comment] 2020-07-09 21:43
@stylemistake

**Comment by optimumtact** [comment] 2020-07-09 21:44
seems to be a duplicate of #52130

**Comment by optimumtact** [comment] 2020-07-09 21:45
#52107

**Closed by optimumtact** 2020-07-09 21:44 UTC
