### ISSUE TITLE
PAI's can *faint but are nonfunctional when they wake up

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#71666] opened 2022-12-02 23:14 UTC
Reporting client version: 514.1589

## Round ID:
[195507](https://scrubby.melonmesa.com/round/195507)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:

Spawn in PAI device/have someone call you.  Use *faint emote.  PAI is unable to function again and has no way to "wakeup" after the normal timer expires. (Note this seems to work fine for borgs but did not test any other silicons)

**Comment by timothymtorres** [comment] 2022-12-03 00:25
Duplicate of #66760

**Closed by timothymtorres** 2022-12-03 00:25 UTC
