### ISSUE TITLE
Surgical drapes not working

### ISSUE THREAD

**Issue by Vect0r2** [tgstation/tgstation#71431] opened 2022-11-22 05:39 UTC
## Round ID:

678151

## Testmerges:

[#71082: 'Adds logic to provide leniency for drag clicks' by LemonInTheDark at commit be6b1f5978](https://www.github.com/tgstation/tgstation/pull/71082)
[#70162: 'Changes our map_format to SIDE_MAP' by LemonInTheDark at commit 22bb532e3b](https://www.github.com/tgstation/tgstation/pull/70162)
[#71232: 'Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time' by Mothblocks at commit 5e1d0ff986](https://www.github.com/tgstation/tgstation/pull/71232)

## Reproduction:

Have somebody get all there shit off and try to use drapes, it seems like the drapes still think they have a jumpsuit on, and can only do wound tending

uhh you are welcome?

**Comment by 117115101114** [comment] 2022-11-22 05:40
edits, figuring out how to use Github markdowns

**Comment by antropod** [comment] 2022-11-22 06:28
duplicate of #71413

**Closed** 2022-11-22 06:57 UTC
