### ISSUE TITLE
Wrapping borked

### ISSUE THREAD

**Issue by kinneb** [tgstation/tgstation#75313] opened 2023-05-09 20:35 UTC
## Testmerges: #73604
l
try to wrap crate with wrapping paper > you CANNOT.

this was on tram

**Comment by SyncIt21** [comment] 2023-05-10 03:30
These are 2 separate issues 

> grab simplebot > activate patrol mode > automatically disables 

Duplicate of #72302 remove this we already know 

> try to wrap crate with wrapping paper > you CANNOT.

This is an actual issue keep only this part.

> but i suspect the testmerge

No the test merge isn't responsible for any of these problems

**Closed** 2023-05-11 14:57 UTC
