### ISSUE TITLE
Bug Report: Xenobiology Cams

### ISSUE THREAD

**Issue by EclipsedSolstice** [tgstation/tgstation#42576] opened 2019-01-28 23:16 UTC
Issue reported from  Round ID: 101014 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

There is an issue in Xenobiology where when the user uses their slime control module, progressively the camera gets covered more and more by static even while the cameras are perfectly intact. The only resolution to this is reconnecting, only for the bug to again occur a few minutes later. This bug can lead to entire slime containment units being invisible to the user (on cameras), making managing the slimes/monkeys of that unit difficult.

**Comment by ShizCalev** [comment] 2019-01-28 23:31
Duplicate of #38926?

**Comment by EclipsedSolstice** [comment] 2019-01-31 17:44
I believe so, though their report isn't exactly descriptive as to what happened.

**Closed** 2019-02-01 16:10 UTC
