### ISSUE TITLE
Dynamic mode can make HOS traitor

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#46738] opened 2019-09-25 11:41 UTC
## Reproduction:
1. Join as HOS
2. Midround become traitor

https://i.imgur.com/nBHViHN.png

**Comment by actioninja** [comment] 2019-09-25 12:03
feature

**Comment by kopoba** [comment] 2019-09-25 12:32
> 
> 
> feature

even if you got only blob and midround antagonist enabled in game preference?
https://i.imgur.com/dSVYlY5.png

**Comment by Ty-the-Smonk** [comment] 2019-09-25 12:52
I think action is memeing

**Comment by Tharcoonvagh** [comment] 2019-09-25 13:37
fix dynamic

**Comment by kriskog** [comment] 2019-09-25 14:16
Guessing it is caused by the low population. 10 total, with a few people dead and two already traitors, I could see how hos might be force chosen.
Getting picked for antag without prefs set on when there are no other options is nothing new, and from my understanding is intentional.

**Comment by Jalleo** [comment] 2019-10-04 13:37
It should be failing really.

**Comment by TheChosenEvilOne** [comment] 2019-10-04 20:49
I have no idea why this is happening but this is caused by the midround traitor ruleset, I am thinking there is something that just lets it go past the job check.

**Comment by Jalleo** [comment] 2019-10-06 09:19
It can happen because the code that decides what job/antag role you get can fail if you are

1: Only person who is on the list for antag (Or one of them that should be failing) 
2: Not selected any jobs you will randomly get one. (Only person on the server does work not sure for multiple people

**Comment by kriskog** [comment] 2019-11-14 00:00
This ruleset was forced, which bypasses the normal role checks and such. Not an issue with normal midrounds.

**Comment by kriskog** [comment] 2019-11-14 04:06
On second thought I will change that.

**Comment by kriskog** [comment] 2019-11-15 20:40
Okay, another look. Even when forced I cannot reproduce this. Lists are trimmed to remove the restricted roles before it rolls, which only leaves misconfiguration or admin shenanigans. Closing this.

**Closed by kriskog** 2019-11-15 20:40 UTC
Labels: Bug
