### ISSUE TITLE
supermatter destabilizes real quick

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#34732] opened 2018-01-21 06:11 UTC
Issue reported from  Round ID: 82288 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

test merges: #34393 #34633 
whatever the fuck happened here, it took about 5 seconds
![capture](https://user-images.githubusercontent.com/35049378/35191422-3fe976a0-fe37-11e7-9c37-3903aa07198d.JPG)

**Comment by SpaceManiac** [comment] 2018-01-21 07:59
#33507 #33982 #28638

Also observed this while attempting to repro:
![image](https://user-images.githubusercontent.com/222630/35192018-ea884fa4-fe3d-11e7-8ce1-6ba454ca8f47.png)

**Comment by Teepeepee** [comment] 2018-01-21 10:32
I saw this very same thing yesterday while observing a round, "...supermatter stability 87%" and not even a second later BOOM. The guy responsible said "I have no clue how this happened, someone just turned it on early and it blew after like the third shot" or something of that sort.

**Comment by Anonmare** [comment] 2018-01-21 17:30
Turning it on roundstart like that always makes it delam ludicrously quick. 

I think it's due to how little gas there is for the heat to be diffused

**Comment by SpaceManiac** [comment] 2018-01-21 22:15
Maliciously vacuuming the room and turning on the emitters is enough to enter "dangerous power level" (lightning and anomalies) instantly and delaminate within five minutes or so, but I have not been able to reproduce this instant 100-to-0 whatsoever.

**Comment by PsyCommando** [comment] 2018-01-22 05:23
I noticed that the SM delaminates incoherently lately as well. It feels like something really wrong is going on with the atmos system. 

So, to try things out, I've been messing around running a server on localhost, and I noticed it did have some random sudden delamination surges. Especially on Delta station.
Poking a hole in the chamber to drain everything and refilling the chamber with nitrogen seemed to help at first. But after a short bit of everything being fine, it would just suddenly go insane again.
And the SM computer and air alarm would show really odd numbers for gas compositions. Like negative % nitrogen and over 100% numbers like in the picture, sometimes even NaN... Also both the air alarm and sm computer would show different gas values.

I also noticed that somehow the shutters around the chamber being closed seems to make things worst for some reasons..

**Comment by DaedalusGame** [comment] 2018-01-22 19:20
do the negative gases happen without the sybil testmerges @PsyCommando ? Or did you manually put those in?

**Comment by PsyCommando** [comment] 2018-01-23 03:47
@DaedalusGame I just pulled and compiled the latest head. Not sure which testmerges you're referring to?
I'm not sure what you mean by manually putting those in? 

And I figured it must have been showing the values for the tile its on, but are the vents and scrubbers linked to that air alarm using the same values for running themselves? Because that might be an issue.

And well, the guide on the wiki for starting the engine mention all scrubbers should be set to siphon and extended range. So incidentally that could result in a low-mole environment?

**Comment by PsyCommando** [comment] 2018-01-23 04:27
Seems like after getting both n2 cannisters in the pipe system, the pipe pressure is a whopping 50kpa and the pressure in the sm chamber is 5kpa according to SM computer..
![2018-01-22 23_23_25-](https://user-images.githubusercontent.com/8772299/35258102-4a452f00-ffcb-11e7-9ed1-0a592838253b.png)
That's with the default setup/operating procedure.

**Comment by PsyCommando** [comment] 2018-01-23 06:18
So today I pulled the latest build from the repo, compiled it, and I don't seem to be able to reproduce it anymore on Metastation. Can anyone else confirm?

**Comment by deranging** [comment] 2018-01-23 21:45
This happened twice on Citadel

**Comment by Shadowlight213** [comment] 2018-01-28 23:13
Had this happen to me on the box setup just now. Was locally testing how long the sm could last when turning off the cooling loop, and after it started shooting lightning, I watched it drop from 90% to 3% on the monitor almost instantly. Had it happen the previous round live on bagil as well.
However, right before that happened I think it consumed a metal rod from the reinforced flooring, so that might be a trigger?

**Comment by DaedalusGame** [comment] 2018-01-28 23:31
if it consumed a metal rod the floor might've been destroyed.

**Comment by Shadowlight213** [comment] 2018-01-29 07:11
Possibly.
Note that this was on a local test. There was no change to the sm made other than just turning off the output pump from the cooling loop to simulate an unwrenched pipe.
So the sm destroyed the floor before it blew up or something.

Also, it went straight to tesla with no lightning when I saw it on live btw. Both times the only thing done was the cooling loop breaking.

**Comment by Poojawa** [comment] 2018-02-01 21:04
I can also confirm the Supermatter being unbelievably temperamental. While I enjoy a challenge, there needs to be some sort of stopgap or control rod type limiter that can fully shut the engine down

**Comment by CPTANT** [comment] 2018-02-03 10:33
#33982
#28638

**Comment by Ordonis** [comment] 2018-02-19 15:16
Yeah, this is still happening, something seriously odd is occuring with low volume SM chamber pressures

**Comment by CPTANT** [comment] 2018-03-24 15:53
Dupe of #28638

**Comment by CPTANT** [comment] 2018-04-04 09:24
@KorPhaeron

**Closed** 2018-04-04 13:58 UTC
Labels: Bug, Needs Reproducing
