### ISSUE TITLE
Free Infinite Metal

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#35569] opened 2018-02-12 00:47 UTC
Trying to cut reinforced metal flooring, IE the tiles outside SM produce infinite metal rods and doesnt remove the floor.

**Comment by YPOQ** [comment] 2018-02-12 00:53
#35280

**Comment by Buggy123** [comment] 2018-02-12 01:01
Can we start updating terry more often? Please?

**Comment by factoryman942** [comment] 2018-02-12 02:03
why would more frequently updating terry reduce duplicate issues?

**Comment by ShizCalev** [comment] 2018-02-12 02:40
Duplicate of #35280

**Comment by ShizCalev** [comment] 2018-02-12 02:40
fix isn't even merged yet so updating would do nothing.

**Closed by ShizCalev** 2018-02-12 02:40 UTC

**Comment by Buggy123** [comment] 2018-02-12 20:01
>fix isn't even merged yet so updating would do nothing.

Wait, what the fuck? It's a simpleish fix and its been over a week.
