### ISSUE TITLE
Kinetic speargun breaks if you click on ground

### ISSUE THREAD

**Issue by collinlunn** [tgstation/tgstation#52178] opened 2020-07-12 07:23 UTC
You can no longer load magspears into a speargun if you hit someone with the speargun in melee or clicking on the ground adjacent to you, making it unusuable. Impacts the traitor special bundle that has the speargun in it.

This is fixed if you respawn as a new human and try to load the harpoon.

**Comment by necromanceranne** [comment] 2020-07-12 23:14
Might be time to rework this into a proper gun rather than a hacky pneumatic cannon, since it seems to constantly break.

We have embedding bullets now after all.

**Comment by nightred** [comment] 2020-07-23 17:23
I am only able to replicate failure to load the speargun on harm intent.

**Comment by Sealed101** [comment] 2024-09-13 19:36
can no longer reproduce, fixed by #75079 maybe

**Closed by Sealed101** 2024-09-13 19:36 UTC
Labels: Needs Reproducing
