### ISSUE TITLE
Vending Uprising is almost guaranteed round-ending now

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#21399] opened 2016-11-07 06:05 UTC
The explosions they cause can create hull breaches, and often do. In addition to being able to kill people in melee, they can throw bombs and cause breaches, which quickly escalates any station situation from calm to "ITS LOOSE".

Needs a nerf badly, it's worse them meteors in severity because it happens all over the station instead of at the edges of it and deprives the station of quite a lot of resources, and the vendors are deadly in melee.

**Comment by PKPenguin321** [comment] 2016-11-07 06:13
Your title makes it sound like this is a recent development when in fact it's always been this way. Not a bug, feedback forum

**Comment by YakumoChen** [comment] 2016-11-07 06:15
Nobody uses the forum

**Comment by PKPenguin321** [comment] 2016-11-07 06:16
Bite me

**Comment by Dorsisdwarf** [comment] 2016-11-07 10:54
I've never seen "throwing bombs" from a vendor, can you elaborate?

**Comment by bgobandit** [comment] 2016-11-07 12:58
maybe if people actually acted on the event instead of twiddling their dicks and waiting for valids it wouldn't end the round

**Comment by PKPenguin321** [comment] 2016-11-07 15:06
not a bug

**Comment by Bawhoppen** [comment] 2016-11-07 16:00
WAD

**Comment by Aloraydrel** [comment] 2016-11-07 18:35
git gud

**Comment by AdamElTablawy** [comment] 2016-11-07 20:28
how to stop vendors-

deconstruct the fucking vendors and reconstruct them
end game weee

**Comment by PKPenguin321** [comment] 2016-11-07 22:15
@phil235 close this

**Comment by optimumtact** [comment] 2016-11-07 23:19
They can throw bombs?

**Comment by optimumtact** [comment] 2016-11-07 23:21
take it to feedback forums please

**Closed by optimumtact** 2016-11-07 23:21 UTC
Labels: Discussion, Not a bug
