### ISSUE TITLE
Lavaland Swarmers dont go out and eat lavaland like they are supposed to

### ISSUE THREAD

**Issue by fluffe9911** [tgstation/tgstation#42793] opened 2019-02-15 17:19 UTC
The lavaland swarmers as far as im aware are supposed to have a gimmick where they go out and eat lavaland and stuff problem is they never actually leave there area unless a player aggros them and makes them move out themselfs (even then they wont do much else after that).

plus they were supposed to have some item you get from it but it got merged early and the original author never actually made anything for it.

I would recommend either fixing this or just simply removing the ruin at this point If it has almost no loot and they never actually go out and eat lavaland like they are supposed to do so miners just avoid them whats the point of them even existing?

**Comment by OverlyGeneric** [comment] 2019-02-15 20:41
What astonishes me is that the swarmers on lavaland are stronger than swarmers that invade the station.

**Comment by ATH1909** [comment] 2019-02-16 00:32
I thought that that ruin wasn't in the rotation- I've never seen it without it being admin-spawned before.

**Comment by wesoda25** [comment] 2019-02-16 04:23
This definitely isn't a thing anymore, I saw it a couple times when it was first merged but not once since then.

**Comment by HomocidlePancakes** [comment] 2019-02-16 08:20
Oh. My. Fucking. God. This is not a bug, this is intended. Swarmers used to liturally eat the entire lavaland by the hour mark. There would be so many of the little shits that you couldn't do anything. And don't even get me started on what happens if they get to the mining base.

**Comment by Firecage** [comment] 2019-10-09 00:22
@HomocidlePancakes Of course, there can probably be a middle ground I guess? Slower expansion and eating, a lot slower. But with them also slowly morphing/forming/turning the area around their ruin into a true Swarmer Hive with the resources they collect? Think like the Replicators from Stargate.

**Comment by SuperNovaa41** [comment] 2022-01-13 18:08
Swarmers have been removed. https://github.com/tgstation/tgstation/pull/63989

**Closed by SuperNovaa41** 2022-01-13 18:08 UTC
Labels: Bug
