### ISSUE TITLE
Cannot Disrespect Hierophant?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#76844] opened 2023-07-15 00:01 UTC
Reporting client version: 514.1589

## Round ID:
[210256](https://scrubby.melonmesa.com/round/210256)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)

## Reproduction:
1. Fight hierophant with style meter active
2. Punch hierophant
3. No +DISRESPECT

**Comment by Sealed101** [comment] 2023-07-15 11:26
Duplicate of #75190

**Closed** 2023-07-15 11:26 UTC
