### ISSUE TITLE
Wheelchairs and PDA's + other items

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43065] opened 2019-03-08 18:02 UTC
Problem Description: Taking the paraplegic quirk prevents the player from using the PDA for sending messages or ejecting a pAI card while buckled into the chair or while on the floor. The player cannot use the instrument deployer if they have taken the Musician quirk.

What did you expect to happen: I expected wheelchair-bound individuals to be able to use their PDA's to send and receive messages.

What happened instead: I'm met with "You can't do that right now!" 

Why is this bad/What are the consequences: It discourages people from using the quirk because it limits play in very non-obvious ways. It also doesn't seem to follow real-life logic, as someone who is buckled into a wheelchair is likely doing so that they may use their hands more.

Steps to reproduce the problem: Spawn a character with the paraplegic quirk. Try sending a message on your PDA. You can't do it while buckled, you can't do it while lying on the floor.

Server: Bagil

**Comment by ShizCalev** [comment] 2019-03-09 03:39
duplicate of #41703

**Closed by ShizCalev** 2019-03-09 03:39 UTC
