### ISSUE TITLE
Chaplain can not offer Organic Sludge

### ISSUE THREAD

**Issue by Castone001** [tgstation/tgstation#78550] opened 2023-09-24 07:09 UTC
## Testmerges:
[#77259: 'Feature: bitrunner, a new supply role (READY)' by jlsnow301 at commit a1132eb371](https://www.github.com/tgstation/tgstation/pull/77259)
[#78457: 'Revert "Resolves parallax harddels" test merge to find lag' by MrStonedOne at commit 720ee4117b](https://www.github.com/tgstation/tgstation/pull/78457)

## Reproduction:
Be chaplain, maintenance sect
Dip rat in welding fuel
Grind rat
remove other reagents leaving just organic slurry
Attempt to offer to your altar
Nothing happens.
Offering the rat on its own doesnt work either, but that never has
Lemon in the Dark attempted to help sort it, and was unable to in the round, so likely a code bug.

**Comment by Sealed101** [comment] 2023-09-24 07:34
Duplicate of #78529

**Closed** 2023-09-24 07:34 UTC
