### ISSUE TITLE
Turrets made using beam rifles do no damage

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#52480] opened 2020-07-25 01:40 UTC
## Testmerges:
#52425: 'Adds Runechat Subsystem - Deprecates Use of Timers for Runechat' by bobbahbrown at commit 26371a1871
#51459: 'Baystruments - I had two tgstation forks for some reason and had to delete one and that nuked the last PR' by silicons at commit b9bf1a03c4

## Reproduction:
1) Make turret shell & build it up
2) At the weapon step place a beam rifle in
3) Hide your identity or do whatever to make it shoot you
4) The turret fires a big fancy beam, causing a fancy explosion, that does no damage, the whole thing is cosmetic.

There's lots of fancy gun + turret combinations (like scatter lasers) that are broken when combined with turrets, but beam rifle is probably the worst because its normally obtainable with research yet clearly broken in a turret.

**Comment by Time-Green** [comment] 2020-07-25 09:20
This is because turrets lack a windup, this is the same with putting one on an emitter.

Good for heart attacks though

**Comment by silicons** [comment] 2020-07-25 22:27
done on purpose to avoid hitscan turrets + circuits

**Comment by silicons** [comment] 2020-07-25 22:27
not necessarily a good solution though

**Comment by Tharcoonvagh** [comment] 2020-07-27 19:49
Dupe, also intended

**Comment by Tharcoonvagh** [comment] 2020-07-27 19:51
#47399

**Comment by Time-Green** [comment] 2020-07-28 07:21
Duplicate of #47399

**Closed by Time-Green** 2020-07-28 07:21 UTC
