### ISSUE TITLE
Changelings can not regenerate lungs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#22520] opened 2016-12-28 02:00 UTC
Reviving stasis and regenerate, neither does it.

**Comment by Armhulen** [comment] 2016-12-28 02:34
the new meta is to cut the chest of a dead changeling until it's organs spill out, which it cannot regenerate

**Comment by jughu** [comment] 2016-12-28 04:05
That always been the meta of every murderboner :^)

**Comment by jughu** [comment] 2016-12-28 04:05
Why do lings need to breathe anyways they are fucking shapeshifters

**Comment by Armhulen** [comment] 2016-12-28 04:51
give changeling  warped alien organs that he can live without

ih and the organs come alive too

**Comment by XDTM** [comment] 2016-12-28 06:07
I swear regenerate used to restore organs too.

**Comment by Armhulen** [comment] 2016-12-28 08:08
tfw too intelligent to regenerate

**Comment by PKPenguin321** [comment] 2016-12-28 08:49
Dupe

**Comment by lzimann** [comment] 2016-12-28 11:52
Dupe of #21408

**Closed by lzimann** 2016-12-28 11:52 UTC
