### ISSUE TITLE
AI camera issue.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#30467] opened 2017-09-06 11:10 UTC
So I've been testing this a few times to make sure it wasn't just a one round thing.  It seems to happen the first time I do it each round for some off reason and no issues after that.

**Comment by GunHog** [comment] 2017-09-06 11:53
So...what is the actual issue?

**Comment by carshalash** [comment] 2017-09-06 11:56
Byond crashing when switching from lavaland cameras to station cameras. Whooooops.

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-09-06 22:39
lol the server crashes or just the client?

**Comment by GunHog** [comment] 2017-09-07 03:29
Client. This happens to me as well, it is obviously a bigger problem for AIs installed on Lavaland rather than ones switching camera networks.

**Comment by ShizCalev** [comment] 2017-10-06 05:55
Duplicate of #28689

**Closed by ShizCalev** 2017-10-06 05:55 UTC
Labels: Bug
