### ISSUE TITLE
Using PDA, vending machines, consoles, and spray cans results in large bluescreen error.

### ISSUE THREAD

**Issue by VtMFan** [tgstation/tgstation#54399] opened 2020-10-14 18:16 UTC
## Round ID:
[148294](https://scrubby.melonmesa.com/round/148294)

## Reproduction: 
   I was the traitor in a round and had opened my PDA to the traitor menu to try and buy some items. My computer shut down due to lack of power at that moment, and when I restarted the program the error was in place. Every time I try to use my PDA, any vending machine, or, for some reason, the silent spraycan, I get a popup blue screen error message saying:

"A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error
   at https://www.tgstation13.download/byond/assets/31/asset.31452f1d6ae37cb213e835e46f4f9330.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; Zoom 3.6.0)

Nanotrasen (c) 2525-2559"

This happens every time I click on any of those items, besides to pick them up. I'm still able to use some functions on the PDA but every time it moves to a different screen (such as home screen to notekeeper) the error message pops up too. I was unable to access the ringtone option so I couldn't do any traitor things.
![Error](https://user-images.githubusercontent.com/72885738/96028884-86023a00-0e1f-11eb-8a85-b95442bbae3e.jpg)

**Comment by VtMFan** [comment] 2020-10-14 18:37
More error messages (I don't know if it's the same error each time but an admin suggested I post multiples):

**Vending Machine**
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error
   at https://www.tgstation13.download/byond/assets/31/asset.31452f1d6ae37cb213e835e46f4f9330.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; Zoom 3.6.0)

Nanotrasen (c) 2525-2559 

**APC**
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error
   at https://www.tgstation13.download/byond/assets/31/asset.31452f1d6ae37cb213e835e46f4f9330.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; Zoom 3.6.0)

Nanotrasen (c) 2525-2559 

**Fridge**
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error
   at https://www.tgstation13.download/byond/assets/31/asset.31452f1d6ae37cb213e835e46f4f9330.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; Zoom 3.6.0)

Nanotrasen (c) 2525-2559 

**Shuttle Console**
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error
   at https://www.tgstation13.download/byond/assets/31/asset.31452f1d6ae37cb213e835e46f4f9330.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS; Zoom 3.6.0)

Nanotrasen (c) 2525-2559

**Comment by stylemistake** [comment] 2020-10-15 20:54
Duplicate of #53997, tgui script error megaissue.

I don't think this brings anything new to the table, but the fact that this is still an issue is a good enough signal that we need to try something different.

**Closed by stylemistake** 2020-10-15 20:54 UTC
