### ISSUE TITLE
Chaos stands leave behind a invisible field of fire after dying.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#41119] opened 2018-10-24 13:17 UTC
RoundID:95978

Kill person with a chaos stand, close a locker where they died, move locker, open locker, stand on where the locker was opened, get set on fire, the whole locker part may be unneeded but i frankly don't know.

I found this bug after i died as a chaos stand, then a sec officer (@kevinz000 ) came and put my user's stuff in a locker, then dragged this to sec, he opened the locker, stood where it was opened, and was set on fire.

**Comment by ShizCalev** [comment] 2018-10-24 16:10
what's a chaos stand?

**Comment by evsey9** [comment] 2018-10-24 16:29
chaos holoparasite

**Comment by Garen7** [comment] 2018-10-24 18:31
Related to #32987?

**Comment by Borisvanmemes** [comment] 2018-10-24 20:31
Right their official names are holoparasites, i just call 'em stands due to the fact that they really are just stands.

**Comment by Barhandar** [comment] 2018-10-24 20:34
Their official name is actually stands; holoparasite is the tech version, magical (wiznerd/tendril deck) is guardian spirit, and there's also carp.

**Comment by KomradeSpectre** [comment] 2019-03-03 17:12
Possibly caused by the forcemove(summoner.loc) in the holopara code that manifests the holopara upon the death of the user and brings them to the remains. Possible missing sanity check for the effect proc activation (which gets cleaned up after a minute? Still have yet to figure out why, but it stops after about a minute.)

**Comment by kriskog** [comment] 2019-06-28 09:48
Don't need the locker, but it lets you move it. Killing the host makes the turf they died on set you on fire when you cross it.

**Comment by Jacquerel** [comment] 2023-01-31 16:04
Fixed by #72049 in that this mob no longer exists so is no longer capable of causing bugs.

**Closed** 2023-02-09 13:07 UTC
Labels: Bug, Tested/Reproduced
