### ISSUE TITLE
Can't photograph basketball hoop scoreboard 

### ISSUE THREAD

**Issue by epochayur** [tgstation/tgstation#77136] opened 2023-07-26 17:12 UTC
## Round ID: 
[211040](https://scrubby.melonmesa.com/round/211040)

## Reproduction:
I was a prisoner on Metastation, I think, and I racked up 69 points on the scoreboard (nice).
I wanted some photo evidence of my accomplishment, so I tried to take a photo of the board.
Clicked the board, clicked the hoop, clicked the wall behind the board, clicked the wall next to the board. None of these caused the scoreboard to show up in the actual photo.

**Comment by timothymtorres** [comment] 2023-07-27 09:29
Duplicate of #70798

**Closed by timothymtorres** 2023-07-27 09:29 UTC
