### ISSUE TITLE
Static overlay after using camera console

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#82147] opened 2024-03-21 16:16 UTC
Reporting client version: 515.1630

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/66640614/92910373-867b-4bf1-aa3c-edd852210881)

## Round ID:
[225869](https://scrubby.melonmesa.com/round/225869)

## Testmerges:
- [[WIP] Spacemen are now Forklift Certified. Adds the Rapid Construction Forklifts to the game.](https://www.github.com/tgstation/tgstation/pull/82100)
- [Canonical Movement](https://www.github.com/tgstation/tgstation/pull/82085)
- [Moves lua off of the timer subsystem and onto its own internal scheduler.](https://www.github.com/tgstation/tgstation/pull/82131)

## Reproduction:
Use a slime console
???
Find a patch of wild static

**Comment by Sealed101** [comment] 2024-10-26 16:03
Duplicate of #68279

**Closed by Sealed101** 2024-10-26 16:03 UTC
