### ISSUE TITLE
If a contractor kidnaps a plasmaman they burn to death in GBJ

### ISSUE THREAD

**Issue by EricZilla** [tgstation/tgstation#60754] opened 2021-08-07 09:39 UTC
Contracting a plasman takes their protection away and has them burn to death, has probably been mentioned before but in case it hasnt, here we are?

Not the best issue report cause I dunno what I'm doing, just trying to help.

**Comment by Couls** [comment] 2021-08-07 16:31
Thanks for your report, it is appreciated even though it doesn't follow the template unfortunately i'm gonna have to close this because it's a duplicate of a previously made issue #49149 but hopefully this doesn't discourage you from making issue reports in the future about any issues you may find

**Closed by Couls** 2021-08-07 16:31 UTC
