### ISSUE TITLE
AI cameras crash the game when you jump from lavaland to the station

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#28689] opened 2017-06-21 22:56 UTC
If you're an AI and you jump to the mining cameras, then jump back by tracking someone or something, the game will crash for some reason. Not entirely sure what causes this and I don't think it's anything to do with any testmerge.

**Comment by GunHog** [comment] 2017-06-21 23:28
This also happens with AIs installed on Lavaland and given cameras in say, a golem ship.

**Comment by Jarektheraptor** [comment] 2017-06-22 00:04
It's worth mentioning that when I do it at least, there seems to be the command to jump to the mob with the cameras written out at the bar at the bottom of the screen.

**Comment by ShizCalev** [comment] 2017-06-22 00:11
I just did it a number of times on meta with no crash
What map are you having the issue on?

**Comment by Jarektheraptor** [comment] 2017-06-22 00:18
IIRC box, possibly meta too but maybe not

**Comment by Ausops** [comment] 2017-07-19 13:43
is happening on box

**Comment by Dorsisdwarf** [comment] 2017-08-01 12:10
Could not replicate on box

**Comment by WJohn** [comment] 2017-11-03 00:03
Had this happen to me when using an advanced camera console spawned in from a template (off station z level). I changed the camera from thunderdome (where it starts) to the station, looking around as normal. The instant I clicked "end camera view" my game completely froze up, waiting for 3-4 minutes didn't do anything at all, had to force close and restart.

**Comment by Jalleo** [comment] 2017-11-03 00:07
This might be related to the issues faced on Aurora with the AI there. https://github.com/Aurorastation/Aurora.3/issues/1820

**Comment by Nitrousoxide** [comment] 2018-01-02 23:12
I'm able to reproduce this every time by switching to the mining network (or clicking to follow anything on the mining network) and then hitting the return to core button at the bottom left as the AI.   Every time it will crash the client and require a restart.

**Comment by Jalleo** [comment] 2018-01-10 00:13
@Nitrousoxide please post https://github.com/tgstation/tgstation/issues/33377#issuecomment-352267023 here with your byond version and when it next happens with the ROUND ID and SERVER NAME. And please inform if it does happen WITH 512. WE NEED DATA.

**Comment by Cyberboss** [comment] 2018-01-10 15:25
Duplicate of #33377

**Closed by Cyberboss** 2018-01-10 15:25 UTC
Labels: Bug, Higgs-Bugson
