### ISSUE TITLE
No way to make chat input always focused

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#47665] opened 2019-11-08 19:05 UTC
## Testmerges:
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 5a7f5622ab

## Reproduction:
1. Join game click chat say some memes
2. Click with mouse anywhere other then chat input
3. Try to say memes again
4. Nothing appears in chat input
4.1 Expected to see text in chat input when you pressing letters on keyboard

**Comment by bobbahbrown** [comment] 2019-11-08 19:16
Allegedly not a bug as of https://github.com/tgstation/tgstation/issues/47643 -- however I disagree.

**Comment by kriskog** [comment] 2019-11-08 20:40
![image](https://user-images.githubusercontent.com/33292112/68508837-b9336500-026f-11ea-99af-456c9997a662.png)
It was discussed at length in the port PR, and left that way purposefully because the fix would be hacky and possibly slow. You can disagree with that decision all you want, but this is still a dupe of #47643

**Closed by kriskog** 2019-11-08 20:40 UTC
Labels: Tested/Reproduced
