### ISSUE TITLE
Burning cards runtime on attempts to check their fire armor

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#23282] opened 2017-01-23 17:05 UTC
[19:56:25]bad index
[19:56:25]proc name: run obj armor (/obj/proc/run_obj_armor)
[19:56:25]  source file: obj_defense.dm,26
[19:56:25]  usr: null
[19:56:25]  src: the CAS deck (black) (/obj/item/toy/cards/deck/cas/black)
[19:56:25]  src.loc: the floor (170,143,1) (/turf/open/floor/wood)
[19:56:25]  call stack:
[19:56:25]the CAS deck (black) (/obj/item/toy/cards/deck/cas/black): run obj armor(10.1278, "fire", "fire", null)
[19:56:25]the CAS deck (black) (/obj/item/toy/cards/deck/cas/black): take damage(10.1278, "fire", "fire", 0, null)
[19:56:25]the CAS deck (black) (/obj/item/toy/cards/deck/cas/black): fire act(506.388, 7249.5)

**Comment by bobbahbrown** [comment] 2019-07-11 00:07
Cannot reproduce, seems to have been unintentionally fixed by another PR.

**Closed by bobbahbrown** 2019-07-11 00:07 UTC
Labels: Bug, Runtime
