### ISSUE TITLE
You can see everything on diffrent z-levels with scanner goggles

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#64033] opened 2022-01-12 17:57 UTC
## Testmerges: 
#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit 8c52016858
#63666: 'makes ai static into images added to obscured turfs to save on maptick' by Kylerace at commit 7d56c359ec

## Reproduction: 
Use scanner goggles and stand next to a wall with a room on the z-level below on the other side.
You can now see everything on that z-level. Not just the room layout

![SS13MesonBug](https://user-images.githubusercontent.com/85312201/149195592-df5a71e5-6dc8-4528-ae0f-4c8941aa922f.png)

**Comment by SuperNovaa41** [comment] 2022-01-12 19:29
Duplicate of https://github.com/tgstation/tgstation/issues/53783

**Closed by SuperNovaa41** 2022-01-12 19:29 UTC
