### ISSUE TITLE
Hydroponics tray plumbing bugs!

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#66359] opened 2022-04-20 22:30 UTC
Reporting client version: 514.1566

## Reproduction:
Hydro trays and plumbing don't interact well.
Let me explain.
First off, get a plumbing constructor and head down to botany. You're looking to build something like this. 
![trays1](https://user-images.githubusercontent.com/46474741/164334784-1834ba1d-1401-43f2-b3a1-0c9a880d6e06.PNG)
Set the synthesizer to 'water' and '5u'.
![trays2](https://user-images.githubusercontent.com/46474741/164334787-e90da25a-0ee0-4522-80f0-e9c419e768e3.PNG)
Take a plant analyzer, and right click to scan any of your connected trays. 
![trays3](https://user-images.githubusercontent.com/46474741/164334788-54468752-e060-49bf-b467-acf13cadaab2.PNG)
Notice how the nutrients are filling up with water? This is bad. This will starve your plants of nutrients/water if you try to pump water into them automatically using plumbing.

Secondly, and this is a very different bug: the plumbing port on hydroponics trays isn't visible unless you pry up the floor. Also, it's offset weirdly; see last screenshot for details.
![image](https://user-images.githubusercontent.com/46474741/164335167-d4f205b9-11dc-4114-87ec-cfe876a0901c.png)
![image](https://user-images.githubusercontent.com/46474741/164335190-5e951417-285d-423d-b888-9f64c8ab0542.png)
![image](https://user-images.githubusercontent.com/46474741/164335282-5f1271fc-3d91-4725-aa3b-9efcfa71aa12.png)
This makes it very hard to position the trays properly so that they're connected to the pipe network, especially when you have to wrench them down to see if they connect and wrench them back up to rotate them if you're wrong.

**Comment by ArcaneMusic** [comment] 2022-04-20 23:37
So, this is a duplicate of #54226. However, I'm going to say we should leave both open because this much more succinctly provides recreation steps and covers the sprite issues with trays from a plumbing perspective, where the older issue has more discussion and possible avenues for a solution.

**Closed** 2022-07-18 01:53 UTC
Labels: Bug, Tested/Reproduced
