### ISSUE TITLE
The Chaplain no longer spawns with a bible and cannot change their null rod form.

### ISSUE THREAD

**Issue by jakeramsay007** [tgstation/tgstation#21660] opened 2016-11-20 21:29 UTC
As said above. It's happened over three rounds now, definitely a recurring bug.

https://gyazo.com/aa811823bc7e806ee32ea3a54ab8fd0c

**Comment by optimumtact** [comment] 2016-11-20 21:48
Dupe of #21659

**Closed by optimumtact** 2016-11-20 21:48 UTC
