### ISSUE TITLE
Bodybags can't be folded

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#68285] opened 2022-07-09 04:51 UTC
Reporting client version: 514.1571

## Round ID:
[186323](https://scrubby.melonmesa.com/round/186323)

## Reproduction:

1. Lay out bodybag
2. Drag the bodybag back on top of you, which should put it back in your hands
3. It doesn't

**Comment by trexter5555** [comment] 2022-07-09 05:09
are you doing this while it's open or while it's closed

**Comment by timothymtorres** [comment] 2022-07-09 10:32
From #67893 

> qol: You fold roller beds and bodybags with a right click instead of click and dragging into you.

Marking this as `Not a bug`

**Comment by Mothblocks** [comment] 2022-07-10 03:28
@MrMelbert @JohnFulpWillard That PR should not have been merged without contextual screentips. The fact this bug report exists is testament to that

**Comment by ArcaneMusic** [comment] 2022-07-10 20:45
Now, bodybags can be folded, that's true.
...But from the same PR, roller beds cannot.
![image](https://user-images.githubusercontent.com/41715314/178161529-b78b208e-1453-4a46-9107-4f539eab937f.png)

**Comment by dragomagol** [comment] 2022-07-27 04:02
Fixed by #68334

**Closed by dragomagol** 2022-07-27 04:02 UTC
Labels: Not a bug, Cleanup Flagged
