### ISSUE TITLE
Destroying tram leaves behind tram walls, which levitate over the lower floor

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#69647] opened 2022-09-01 19:03 UTC
Reporting client version: 514.1585

## Round ID:
[189667](https://scrubby.melonmesa.com/round/189667)

## Testmerges:
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:

1. containment field in palce
2. move tram
3. why walls still exist
4. scream in pain
5. acquire maxcap and remove the walls

y e a

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug
