### ISSUE TITLE
Sometimes letters are missing from RuneChat

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57139] opened 2021-02-23 09:50 UTC
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:

1. Say CLEAN THE FLOOR FUCKO
2. Observe as the U is missing after the linebreak

**Comment by dragomagol** [comment] 2021-02-23 18:37
Duplicate of #55368

**Closed by dragomagol** 2021-02-23 18:37 UTC
