### ISSUE TITLE
[Metastation?] Non-RnD lab circuit imprinters do not work

### ISSUE THREAD

**Issue by Actionb** [tgstation/tgstation#18210] opened 2016-06-03 11:23 UTC
rev 73aec2d8e815d6eb512e0cb5bc6fa26e2fd10805 

Can't print any boards no matter where you put the machine. This also includes the imprinter robotics starts with.
The one in the RnD lab works just fine though.

Not quite sure if the bug is exclusive to metastation, but that's where I ran into it. Haven't tested on box yet, just wanted to post this before I forget.

**Comment by LatD** [comment] 2016-06-03 14:16
What do you mean by cannot print boards? Does it show the printer connected to R&D console? Can you sync it and see the boards? Can you load glass and acid? Does it show either of them missing as a reason not to be able to print?

This might be caused by my R&D remake since it was merged yesterday and some other people were talking about this too but I think I haven't touched the code which affects connecting machines. Even weirder is that it's not working in robotics but works well in R&D.

**Comment by LatD** [comment] 2016-06-03 17:33
Found it with testing, I used a wrong variable

**Closed** 2016-06-03 19:43 UTC
Labels: Bug, Needs Reproducing/Testing
