### ISSUE TITLE
smoker quirk 

### ISSUE THREAD

**Issue by R3nn0c** [tgstation/tgstation#57979] opened 2021-03-27 02:33 UTC
I don't think the smoker quirk is working as intended

I constantly smoke all round an my characters mood gets progressively worse.
when I check mood its always "I crave nicotine" or "I could really go for a smoke" even though I an basically chain smoking these cigarettes
I also tried nicotine gum, I ate 2 packs in a row and I didn't help at all. 
 ^(this didn't just happen for 1 round it happens every round)^ 

please help I want to look cool and smoke again well still being able to run away from the police :(

**Comment by ArcaneDefence** [comment] 2021-03-27 19:47
Duplicate of https://github.com/tgstation/tgstation/issues/57949

**Closed by ArcaneDefence** 2021-03-27 19:47 UTC
Labels: Bug
