### ISSUE TITLE
Implanting Lizard Tails Doesn't Show

### ISSUE THREAD

**Issue by Groxic** [tgstation/tgstation#19641] opened 2016-08-01 16:46 UTC
During one round I had, there was a rogue human. My assistant lizard offered up his tail, so we chopped it off(surgery) and planted it on the human(tail attachment surgery of the groin). It worked, but we couldn't see the tail on the human.

**Comment by PKPenguin321** [comment] 2016-08-01 19:11
I think this is a dupe

**Comment by callanrocks** [comment] 2016-08-02 01:31
This bug has been around for ages so it probably is.

**Comment by WJohn** [comment] 2016-08-02 06:47
dupe of #19350

**Closed by WJohn** 2016-08-02 06:47 UTC
