### ISSUE TITLE
Duplicated json in newscaster.json

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#41904] opened 2018-12-11 18:07 UTC
## Round ID: 97922
Unsure why, but the newscaster.json for 97922 contains the same json, twice: 
https://tgstation13.org/parsed-logs/basil/data/logs/2018/12/01/round-97922/newscaster.json

Statbus can't parse this, obviously: 
https://sb.atlantaned.space/rounds/97922/logs/newscaster.json

**Comment by Jordie0608** [comment] 2018-12-12 00:17
From the runtime logs of that round it seems that SS shutdown was called twice somehow. An admin world restart was issued twice two seconds apart by Imsxz and then Beesting so I guess `world.Reboot()` happened twice.

**Comment by timothymtorres** [comment] 2021-12-21 22:08
Since this was due to admin shenanigans I'm marking this as not a bug.  Thanks to @Jordie0608 detective work.

**Closed** 2022-01-12 09:03 UTC
Labels: Not a bug
