### ISSUE TITLE
Transparent turfs, when placed over ice mineral walls placed on a lower z level, look strange

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63844] opened 2022-01-05 01:01 UTC
Reporting client version: 514.1568

## Round ID:
[176017](https://scrubby.melonmesa.com/round/176017)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/148137041-2baad1f5-9e18-4482-a396-1fc3643577b3.png)

![image](https://user-images.githubusercontent.com/51863163/148136829-2de0bbd0-f7bc-4813-b149-7b5007ea96f8.png)

- Find a location on icebox station where the z-level below your turf is a ice / mineral wall. 
- Place a transparent turf (reinforced glass floor) on your turf.
- The mineral walls from the lower z-level will now add these strange overlays to the upper z-level.

**Comment by timothymtorres** [comment] 2022-01-05 11:37
Duplicate of #63770

**Closed by timothymtorres** 2022-01-05 11:37 UTC
Labels: Bug

**Comment by timothymtorres** [comment] 2022-01-05 11:39
I fixed some problems with the multi z in https://github.com/tgstation/tgstation/pull/62875 and it seems that all the objects/turfs on the lower z level are clipping out of bounds.
