### ISSUE TITLE
Mortal and Pestle create infinite reagents

### ISSUE THREAD

**Issue by SomeoneYouProbablyKnow** [tgstation/tgstation#70073] opened 2022-09-22 12:24 UTC
## Reproduction:
1. Craft Mortar, Craft Pestle
2. Put thing in (tested on match, can, glowstick, metal)
3. Grind
4. Get reagents, object is not deleted from the mortar
5. Remove the object or just simply grind again

Does not work in the normal grinder, does not work with donuts (in the mortar)

**Comment by msgerbs** [comment] 2022-09-22 14:30
Duplicate of #69966

**Closed by msgerbs** 2022-09-22 14:30 UTC
