### ISSUE TITLE
You can no longer store gibtonite in bags of holding

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#27958] opened 2017-06-02 05:50 UTC
Couldn't find any prs that explicitly  said you  can no longer put them in bags of holding so i'm assuming this is a bug. 

I don't see why you would ban it anyway. It's riskier than carrying around a bag full of bombs from toxins because an explosion can actually set the gibtontie off unlike transfer valves

**Comment by AnturK** [comment] 2017-06-02 07:59
Dupe of #27943

**Closed by AnturK** 2017-06-02 07:59 UTC
