### ISSUE TITLE
You can not break down wooden walls with a fireaxe oversight

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31126] opened 2017-09-29 16:53 UTC

**Comment by Bawhoppen** [comment] 2017-09-30 07:48
I mean it could be construed as not a bug but we should probably add it as functionality

**Comment by Penguaro** [comment] 2017-10-01 15:25
Axes chopping wood? What world do you live in???

**Comment by SpaceManiac** [comment] 2018-12-28 19:01
Fixed by #36524

**Closed by SpaceManiac** 2018-12-28 19:01 UTC
Labels: Consistency Issue, Not a bug
