### ISSUE TITLE
Shuttle starts depressurized

### ISSUE THREAD

**Issue by naltronix** [tgstation/tgstation#30810] opened 2017-09-16 16:34 UTC
No idea when this started happening, but every round I latejoin, the shuttle has no air. I have checked and there are no breaches at all.

**Comment by praisenarsie** [comment] 2017-09-16 16:36
dupe of https://github.com/tgstation/tgstation/issues/30780

**Closed** 2017-09-16 16:37 UTC

**Comment by Cyberboss** [comment] 2017-09-16 18:27
Duplicate of #30780
