### ISSUE TITLE
AI Multiview screen occasionally goes static

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#60760] opened 2021-08-07 22:50 UTC
Reporting client version: 513.1542

## Round ID:
[167400](https://scrubby.melonmesa.com/round/167400)

## Testmerges:
- [Fixes circuit component options](https://www.github.com/tgstation/tgstation/pull/60718)
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)

## Reproduction:
1. Open multiview window.
2. Click on something other than camera windows
3. Static on the multiview screen

![image](https://user-images.githubusercontent.com/85206687/128615832-be09a05b-78fb-485a-84bb-3482d8f75f5c.png)
Image from another player having similar issues.

**Comment by dragomagol** [comment] 2021-08-14 02:08
Duplicate of #52562

**Closed by dragomagol** 2021-08-14 02:08 UTC
