### ISSUE TITLE
Mesons allows to see what items people pick up through the walls

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79541] opened 2023-11-06 00:11 UTC
## Reproduction:

Wear mesons, spy on traitors getting their contraband from the bags.

![Screenshot_393](https://github.com/tgstation/tgstation/assets/64209864/59a4501c-faab-4a26-8d68-ea4b14b14f50)

**Comment by Jackal-boop** [comment] 2023-11-06 02:54
This has been a thing for a very long time and I think there's like 5 other issues about this

**Comment by MrMelbert** [comment] 2023-11-06 04:05
Correct: dupe of #39799

**Comment by ZephyrTFA** [comment] 2023-11-08 03:04
Duplicate of https://github.com/tgstation/tgstation/issues/39799

**Closed by ZephyrTFA** 2023-11-08 03:04 UTC
Labels: Cleanup Flagged
