### ISSUE TITLE
Clicking on a spider egg ready to hatch DNRs you even if you don't take the spawn.

### ISSUE THREAD

**Issue by Dezupher** [tgstation/tgstation#75756] opened 2023-05-30 18:30 UTC
## Testmerges:
[#75617: 'Adds a new front end for viewing logs | fixes the manifest log message too' by ZephyrTFA at commit 40714a3c47](https://www.github.com/tgstation/tgstation/pull/75617)
[#75630: 'It's Nice To Be Unique: Adds new quirks to pick up!' by orthography at commit 479c812f6c](https://www.github.com/tgstation/tgstation/pull/75630)

## Reproduction:
Click on a spider egg that is ready to hatch while a ghost. When you pull open the menu to select one of the spider types, you lose your previous body and can no longer re-enter it, even if you don't actually spawn in as a spider.

**Comment by BlueMemesauce** [comment] 2023-05-30 20:21
Related to #74041

**Comment by Sealed101** [comment] 2023-05-31 08:59
sounds more like a duplicate of that issue

**Closed by Sealed101** 2023-05-31 08:59 UTC

**Comment by BlueMemesauce** [comment] 2023-05-31 21:38
Technically not because this is about eggs that are ready to hatch while that one is about spawners that are out of charges
it probably doesnt make a difference though

**Comment by Sealed101** [comment] 2023-05-31 22:29
backing out of a spawn or failing to get a chance at a spawn likely goes through the same order of DNRing your body a tad bit too early, thus the duplicate
