### ISSUE TITLE
Head on a stick goes above blindness layer

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#73660] opened 2023-02-26 02:25 UTC
Reporting client version: 514.1589

## Round ID:
[200805](https://scrubby.melonmesa.com/round/200805)

## Testmerges:
- [important pr oranges asked me to make](https://www.github.com/tgstation/tgstation/pull/73658)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/221388811-99db2ec6-8440-4574-8bba-ea441c49ea85.png)

**Comment by rageguy505** [comment] 2023-02-26 03:57
Duplicate of #59037

**Closed** 2023-02-27 02:55 UTC
