### ISSUE TITLE
Ghosting in VR brings up the real ghosting menu, which can ghost you for real if you accidentally click the wrong button

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#38021] opened 2018-05-23 21:21 UTC
Round 88387, I was trying to investigate a bug involving VR ghost, but ended up misclicking and killing myself permanently

**Comment by SpaceManiac** [comment] 2018-05-24 20:27
Would it make sense to change the override to throw you out of VR but *not* bring up the original Ghost menu? Not sure whether that's really a good idea though.

**Comment by DaxDupont** [comment] 2018-05-24 20:33
I mean I could take that as feature request sure, but it's not a bug.

**Comment by SpaceManiac** [comment] 2018-05-25 09:17
Fixed by #37915

**Closed by SpaceManiac** 2018-05-25 09:17 UTC
Labels: Not a bug, UI, i ded
