### ISSUE TITLE
Emergency shuttle leaves behind tiles that have been replaced

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#83513] opened 2024-05-27 15:19 UTC
## Issue Summary
If part of the emergency shuttle gets destroyed and you replace the tiles they will be left behind when the shuttle moves. This happens both when leaving the station and when arriving at centcomm. This also causes anything on these tiles to get left behind.

## Round ID:
[229538](https://scrubby.melonmesa.com/round/229538)

## Reproduction:
Part of shuttle gets blown up
Use floor tiles to replace the floor while it is still docked at the station
The replaced tiles get left behind on the station z level when the shuttle leaves the station, becoming space tiles again on the shuttle z level.
Replace the floor again while the shuttle is in flight
Floor gets left behind again when the shuttle docks at centcomm

**Comment by Sadboysuss** [comment] 2024-05-28 07:16
this has been an issue for a long time, nobody understands shuttle code which is why it hasn't been fixed yet

**Comment by Sealed101** [comment] 2024-09-16 22:24
Duplicate of #81099

**Closed** 2024-09-16 22:24 UTC
