### ISSUE TITLE
certain code words break traitor highlight scripts

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#53661] opened 2020-09-12 14:48 UTC
if "blue" is chosen as codeword during traitors, it ll break the traitor codewords highlighting script (probably because its a word inside the script itself) making any message with that word gibberish broken <>s 

146029

**Comment by msgerbs** [comment] 2020-09-16 19:55
Duplicate of #49824

**Closed** 2020-09-16 19:55 UTC
Labels: Bug
