### ISSUE TITLE
WASD speech does not get interrupted by being hit.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43567] opened 2019-04-10 00:48 UTC
## Round ID:
105838

## Reproduction:
1. Type while in arrow keys mode.
2. Get hit repeatedly, see how yo-GLORF
3. Press tab and then talk with pop up box on T.
4. Get hit repeatedly, see how your text isn't interrupted. Call out tator tot george melons.

**Comment by nicbn** [comment] 2019-04-10 01:15
Possible solution (not easy): make it so that when you send text, whoever hears it gets a blank text, and the letters fade in one at a time from the beginning.
If you're interrupted, the letters stop rendering for everybody and it prints a glorf
Maybe make it so that radio will only be sent after the letter rendering time is due so the message is sent as a whole and you don't get ethernal fading in radio

**Comment by PKPenguin321** [comment] 2019-04-10 02:09
dupe of an ancient issue report

**Comment by JJRcop** [comment] 2019-04-10 05:15
#8999

**Comment by WJohn** [comment] 2019-04-10 05:59
Wow this bug is fucking ancient.

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-04-10 17:44
It's because hotkeys uses input, good luck

**Closed by ExcessiveUseOfCobblestone** 2019-04-10 17:44 UTC
