### ISSUE TITLE
Duping bug (but not really)

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43486] opened 2019-04-04 07:59 UTC
It’s 3 seperate bugs, but they seem to be related.

1)You can dupe the effects of KA upgrades.
Reproduction: Get KA. Get upgrade. Click on it as fast as possible. Depending on your clicking speed (and ping) you will end up with 2 or 3 upgrades. Using a crowbar on the KA will pop out just one upgrade though.

2)You can dupe (not really) machinery parts.
Reproduction: Have an unfinished machine and the required parts on the same tile. Alt+click the tile. Pick up, insert and pick up the same part before alt+click menu updates. Congrats. Machine thinks it has the part, but in reality you’ve taken it out. It won’t affect the stats though.  So you can have chem dispensers with with 50% percent power efficency (min is 100%) or rechargers with 0 recharging rate.

3)You can dupe ammo in shotguns. 
Reproduction: No fucking idea how. Was able to pull it off once by accident 3 months ago. Had 4 shells and an empty compact shotgun. Reloaded it. Ended up with 5. Went”the fuck”? Unloaded it. Ended up with 4 shots again. Wasn’t able to reproduce it since. No idea what happens with it when you shoot it. 

Keep in mind I play with 220 ping average.

**Comment by HomocidlePancakes** [comment] 2019-04-04 08:00
Also there was a bug with nuke disk and alt+click. May be related.

**Comment by Tlaltecuhtli** [comment] 2019-04-04 09:30
it also happens when putting parts into machine assemblies (item isnt really bugged its just that the machine assembly will think its inside but on refresh part it notices that its some parts  are missing like if it had an stored items = to number of matterbin* 3 and the machine thats supposed to have 3 but the bin bugged and instead it ll count 2 then it ll have 100 items also happens if 2 ppl click on an item at the same time, they ll both have the item which will tele between the users every time its touched




whatever the code that transfer items to other is the cause

**Comment by ATH1909** [comment] 2019-04-04 13:27
Does this mean that you can infinitely upgrade your PKA by using this bug while applying this upgrade to get extra bonuses, taking out the upgrade, then using this bug while reapplying the upgrade to get extra bonuses, then taking out the upgrade, then...

**Comment by ATH1909** [comment] 2019-04-04 17:27
If it does let you stack on as many upgrade effects onto a PKA as you have access to and the time/patience/skill at performing the bug needed to install, could you use AoE and damage upgrades to make a PKA that can "snap" (more like *clap, really, seeing as how almost everyone would die) the station by doing ludicrous amounts of damage to everything in a z-level-sized AoE? Could you survive it by wearing a full bomb suit?

**Comment by HomocidlePancakes** [comment] 2019-04-04 18:23
No. You can’t get more upgrades then you can normally. It will allow to add as long as there is space.

**Comment by HomocidlePancakes** [comment] 2019-04-04 18:23
Also it’s the KA one is super easy to pull off

**Comment by ATH1909** [comment] 2019-04-05 00:29
But can you get the max ranks of every upgrade, or will all of the bugged extra effects of an upgrade go away when you uninstall it?

**Comment by HomocidlePancakes** [comment] 2019-04-05 09:51
They go away after you remove them and it will pop out only one upgrade.

**Comment by Fikou** [comment] 2019-04-07 10:27
the same can happen with borg parts and mech equipment, alt click menu seems to be much slower and slower reacting than previously (might be the dark mode being added?? before that it wasnt as slow i think)

**Comment by timothymtorres** [comment] 2022-07-30 02:39
Pretty sure 2/3 of these were fixed with #52115.

The shotgun glitch is still present in #54771 so I'm going to mark this as a duplicate.

**Comment by timothymtorres** [comment] 2022-07-30 02:40
Duplicate of #54771

**Closed by timothymtorres** 2022-07-30 02:40 UTC
Labels: Bug
