### ISSUE TITLE
Taking a Photograph with the Camera crashes the server

### ISSUE THREAD

**Issue by liquid49** [tgstation/tgstation#51992] opened 2020-07-03 17:02 UTC
## Round ID:
[141053](https://scrubby.melonmesa.com/round/141053), 141054 (if it is linear, otherwise I don't know.)

## Reproduction:
As title, taking a photograph with the Camera caused a server crash on at least two separate occasions. I had the photograph quirk and took a photo with the camera issued with that quirk when it happened.

**Comment by Jared-Fogle** [comment] 2020-07-04 23:17
Can't reproduce this. What were you taking a picture of? At what point did it cxrash?

**Comment by onein50million** [comment] 2020-07-07 06:30
Managed to reproduce this on my local server, looks to be memory related. If you take enough pictures (usually took me 3 refills) using the default focus/zoom setting, the server will run out of memory and crash.

If you increase the zoom to 4x4, each picture uses a lot more memory, but the camera seems to break after the 1.5 gig mark, then it'll only print black pictures (seems to persist even after a world reboot, might also be related to #50848 and #48899)

**Comment by RaveRadbury** [comment] 2020-07-07 16:43
Related to #48899

**Comment by RaveRadbury** [comment] 2020-07-07 16:44
I've recently tried to snap some 4x4's and would just have the SS13 logo when I examined it.
3x3's worked but there was a noticeable lag on trying to view them.

**Comment by optimumtact** [comment] 2020-07-09 21:47
I think we're just going to have to remove them, as shitty as that is, we can't keep trying to work around the engine limitations.

**Comment by TheBonded** [comment] 2020-10-22 21:01
> I think we're just going to have to remove them, as shitty as that is, we can't keep trying to work around the engine limitations.

what if we just replace cameras with a PDA cartridge, and remove the ability to print pictures? Inside the PDA cartridge could be something similar to modular computer chat groups, but they would be photo books, so it wouldn't be losing any functionality, and you could still have the chaplain spawn with a special cartridge that lets their pictures show ghosts.

**Comment by MrStonedOne** [comment] 2021-09-09 19:14
@ninjanomnom do you think the get pixel color fix to gags might help here?

**Comment by MrMelbert** [comment] 2022-03-14 02:56
fixed by #52077

**Closed by MrMelbert** 2022-03-14 02:56 UTC
Labels: Bug, FUCK, Priority: High

**Comment by optimumtact** [comment] 2022-03-14 02:59
thank you hun
