### ISSUE TITLE
There is a jumpsuit with a missing texture

### ISSUE THREAD

**Issue by Urumasi** [tgstation/tgstation#46200] opened 2019-08-28 07:47 UTC
## Round ID:
117232

## Reproduction:

1. Be assistant
2. Get unlucky
3. You now have a jumpsuit with a missing sprite

![on character](https://user-images.githubusercontent.com/8294011/63835866-abf92080-c978-11e9-8d4c-4e6348872938.png)
![in inventory](https://user-images.githubusercontent.com/8294011/63835881-b2879800-c978-11e9-8efa-0489625ef9c0.png)

**Comment by kriskog** [comment] 2019-08-28 10:22
dupe of #45909

**Closed by kriskog** 2019-08-28 10:22 UTC
