### ISSUE TITLE
crash to desktop by pressing key next to enter botton

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55502] opened 2020-12-13 12:02 UTC
byond: .1537 and current update

“à” U+00E0 key freezes the screen or crashes  game on multiple pressing outside of an text  box
tried on different servers, on cm it does nothing on tg based server (fulpstation) it crashes game

changing keyboard language and pressing same key doesnt crash the game

152090

**Comment by TemporalOroboros** [comment] 2020-12-13 14:25
Client or server?

**Comment by Tlaltecuhtli** [comment] 2020-12-13 15:09
client

**Comment by optimumtact** [comment] 2020-12-14 05:53
did you test it on our servers?

**Comment by Tlaltecuhtli** [comment] 2020-12-14 07:52
yes

**Comment by Angustmeta** [comment] 2021-02-07 12:06
Reported this in May:
#51135

It was indeed keys next to enter in that case as well.

**Comment by SuperNovaa41** [comment] 2021-12-02 19:21
Duplicate of #https://github.com/tgstation/tgstation/issues/51135

**Closed by SuperNovaa41** 2021-12-02 19:21 UTC
