### ISSUE TITLE
some open lockers not able to be walked into

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#71629] opened 2022-11-30 12:00 UTC
Round ID: [195344](https://scrubby.melonmesa.com/round/195344)

Testmerges: not sure

Reproduction: open a roundstart grey locker in maint. try to walk into it

Clip: https://streamable.com/a0eby5

It's been doing this for maybe a few days or so. Issue fixes itself after you close and open the locker again. In the clip I'm attempting to walk into the locker but being blocked for some reason, until I close and open it again. I've noticed it happening primarily for grey lockers in maint, roundstart.

**Comment by timothymtorres** [comment] 2022-11-30 12:58
Duplicate of #69779

**Closed by timothymtorres** 2022-11-30 12:58 UTC
