### ISSUE TITLE
AIs can't see C4 being planted on their own core

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#21113] opened 2016-10-21 03:22 UTC
#20962 @phil235

AIs used to receive a combat log message if someone tries to attach c4/x4 to an AI core, they don't after #20962

**Comment by optimumtact** [comment] 2016-10-21 03:26
dupe of the more general #21107

**Comment by phil235** [comment] 2016-10-21 11:16
not the same issue.

**Comment by phil235** [comment] 2016-10-21 12:01
You can't plant c4 on an AI: https://github.com/tgstation/tgstation/blob/4cddd81120b08cada8856576ad2f1d62221dba9b/code/game/objects/items/weapons/explosives.dm#L71

**Closed** 2016-12-27 23:37 UTC
Labels: Bug
