### ISSUE TITLE
Construction is fucked

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#34053] opened 2018-01-03 00:11 UTC
[Round ID]: # not round specific

[Testmerges]: #34005 Reverts Explosion Shaking
[Reproduction]: 
Step 1: Try to build a wall
Step 2: Add metal to girders
Step 3: Its gone

Step 1: Try to build on space
Step 2: Add floor tile to lattice
Step 3:  Its gone

**Comment by Electronics** [comment] 2018-01-03 00:13
+1
If you then add rods to the space that is generated when you add the floor tile, the tile magics into reality with a lattice on top.

**Comment by DaxDupont** [comment] 2018-01-03 00:52
Dupe of #34027 will be fixed when server updates

**Comment by AnturK** [comment] 2018-01-03 10:29
Duplicate of #34027

**Closed by AnturK** 2018-01-03 10:29 UTC
