### ISSUE TITLE
Weird interaction with spawning people and aghost

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26902] opened 2017-05-04 17:52 UTC
1) Accidentally took control of Lisa the corgi.
2) Aghosted out.
3) Offered control to ghosts.
4) Someone else took control.
5) My ghost goes to thunderdome, uses the Ctrl-Shift spawn as human shortcut.
6) They get yanked out of Lisa's body, and into the new human body.

**Comment by KorPhaeron** [comment] 2017-05-04 23:23
I'm almost positive this is a dupe

**Comment by lzimann** [comment] 2017-05-07 01:45
Dupe of #16639

**Closed by lzimann** 2017-05-07 01:45 UTC
