### ISSUE TITLE
There is no way to fix almost every machine affected by the Bot Language Malfunction station trait

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#73100] opened 2023-01-31 12:44 UTC
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Start station with shift divergency **"Bot Language Matrix Malfunction"** (STATION_TRAIT_BOTS_GLITCHED)
Attempt to repair any machine besides a vendor to speak common

This can cause issues such as:
Announcement Console never being understandable
Any console giving an alert, error, or notification will be impossible to ever understand
Players attempting to fix it instead unlinking lathes from the silo or otherwise damaging or unknowningly modifying machinery without wires (like department alert consoles)

**Comment by timothymtorres** [comment] 2023-02-03 13:47
Initially this trait was for the language of station bots.  They did not have wires to reset, nor could you rebuild them to fix it's language since it was determined by RNG.  In line with that, I made all machines that spoke have the same code logic applied.  The vending machines had an existing wire for speaking that I was able to easily convert to make it togglable for languages.  Adding the language wire was because I was already working on language code and it was an easy feature to add for _vending_ machines.

Doing this with all machinery would not be trivial since many of them have different UIs, systems, sprites, and lack any kind of support for wires or panels. Also many of the negative station traits are permanent for the entire round duration.

CC @MrMelbert

**Comment by timothymtorres** [comment] 2023-02-10 12:12
Marking this as `Not a Bug` given the above listed reasons.  Some negative station traits are meant to be permanent.

**Closed by timothymtorres** 2023-02-10 12:12 UTC
Labels: Not a bug
