### ISSUE TITLE
Space cats doing the lay down position have a dead icon

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#16523] opened 2016-03-31 15:24 UTC
![ss 2016-03-31 at 11 22 54](https://cloud.githubusercontent.com/assets/13092039/14180954/183420b8-f733-11e5-89e3-739ec16c01da.png)

**Comment by WJohn** [comment] 2016-03-31 19:53
What's wrong with that cats entire sprite? Is something going on in the background? Also the tail is pointing up so everything should be fine.

**Comment by Aloraydrel** [comment] 2016-03-31 21:02
the helmet is shattered so I assumed it was the dead icon for it.

**Comment by bgobandit** [comment] 2016-04-01 16:48
possibly a dupe of https://github.com/tgstation/-tg-station/issues/16248

**Closed** 2017-11-22 16:47 UTC
Labels: Bug
