### ISSUE TITLE
Reaction chamber is laggy

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80597] opened 2023-12-26 17:25 UTC
## Issue Summary

#80495 seems to have also managed to make reaction chambers laggy.

It can take upwards of several seconds for the reaction chamber to react to being turned on.
The reaction itself isn't delayed, but the heating aspect very much is.

@SyncIt21

## Reproduction:

1. Make 1 batch of 50u lenturi with 50u lithium as a buffer.
2. Make another batch using the same 50u lithium as a buffer.
3. Observe the reaction slowing down due to the endothermic nature of lenturi's reaction.
4. Use the reaction chamber on 1000 K to heat up the reaction, observe a delay of several seconds, threathening to kill the reaction entirely. (delay did not happen before to this extent)

(exact reproduction steps for what I did that round)

**Comment by t3hSurge** [comment] 2023-12-26 18:00
I might have a related example: I make plastic in a tier 1 heater by doing the following:

1. 30u welding/hydrogen/carbon
2. let react
3. subtract 10u
4. add 20u of sulphuric 
5. max chem heater and slap in your beaker

The old behavior was that the oil would convert into ash and make a full beaker's worth of plastic sheets. Now there's some ash and acid left over for some reason.

**Comment by SyncIt21** [comment] 2023-12-26 18:21
> The old behavior was that the oil would convert into ash and make a full beaker's worth of plastic sheets. Now there's some ash and acid left over for some reason.

This old behaviour would never occur because by following your steps you would have 80 units of oil & 20 units of sulphuric acid.
And the requirements for plastic reaction is as follows
![Screenshot (381)](https://github.com/tgstation/tgstation/assets/110812394/a54de0b4-1fcd-4003-bb23-a7a27f738704)

The proportion of your reagents in this reaction are so imbalanced that these is bound to be left over acid & ash(especially since some of the oil converts to ash & some of the oil is used for plastic) Oil is consumed at twice the rate required for plastic therefore there isn't enough left to react completly with acid so it leaves out left over reagents.

**Comment by t3hSurge** [comment] 2023-12-26 18:32
I don't really follow. 8 oil and 2 sulfuric is balanced, but now the reaction order or speed changed. It's not the biggest deal I was just giving an example. I popped on git today because I think this PR broke the chem press somehow too but I wanted to see if it was still broken in another round.
![image](https://github.com/tgstation/tgstation/assets/104752635/498af44f-d426-4b59-9bfc-274f06398fef)

**Comment by SyncIt21** [comment] 2023-12-26 18:35
My PR has nothing to do with the pill press, completly different from reaction chamber and also the pill press was never an issue 
https://github.com/tgstation/tgstation/issues/80576#issuecomment-1869490626

**Comment by t3hSurge** [comment] 2023-12-26 20:16
I think we got some kind of plumber ui fix at the same time that broke the press. I still stand by my point on the plastic sheets. My recipe used to make 10 sheets and now it makes 8.  No idea why two sheets of ash go off after your changes, but they do and I'm not sure where your dismissive confusion came from. 5 + 3 is 8. You can run more than one reaction at the same time dude.

**Comment by dalmationer** [comment] 2023-12-26 21:29
all reagents are like this. I was playing bartender and i noticed many of my reactions didnt update unless i heated them with a lighter in round ID 221177

**Comment by RikuTheKiller** [comment] 2023-12-27 00:39
> When testing locally upon following the wiki steps I get exactly 1 plastic sheet and no left over reagents, so it's a skill issue on your part

This is quite dismissive of the problem they were actually talking about. What you're missing here is that they used a combination that was specifically refined to react the ash at the correct speed to not leave leftovers. (via fine-tuning temperature and whatnot)

After your PR was merged, that behaviour changed even though your PR was intended to only do backend, invisible fixes that don't affect behaviour. Are you sure you're actually well-versed in fermichem or are you just parroting the wiki for whatever reason?

**Comment by SyncIt21** [comment] 2023-12-27 05:19
> I think we got some kind of plumber ui fix at the same time that broke the press. I still stand by my point on the plastic sheets. My recipe used to make 10 sheets and now it makes 8. No idea why two sheets of ash go off after your changes, but they do and I'm not sure where your dismissive confusion came from. 5 + 3 is 8. You can run more than one reaction at the same time dude.

Ok so i finally figured out why all the oil and acid does not get consumed. It's something that was done in [this](https://github.com/tgstation/tgstation/pull/80380) PR, I removed reactions restarting immediately after it ended (this was done to solve that linked issue), for endothermic reactions if it failed when the temps got too low it would immediately restart and then immediately fail again because of the reaction restart causing high tick usage.

Because i removed that restart, what you said

> You can run more than one reaction at the same time

Does not happen as frequently as it used to so that's why you get left over reagents(because not enough reactions occured to completely consume all the reagents) removing the restart not only improved tick usage but also solved the bug but it also comes at a slight inconvenience of not consuming all reagents so yeah it's my bad for not mentioning that in the changelog, sorry, it took me a while to make the connection, a small inconvenience but not a big deal hopefully.

**Comment by SyncIt21** [comment] 2023-12-27 08:40
> I think we got some kind of plumber ui fix at the same time that broke the press. I still stand by my point on the plastic sheets. My recipe used to make 10 sheets and now it makes 8. No idea why two sheets of ash go off after your changes, but they do and I'm not sure where your dismissive confusion came from. 5 + 3 is 8. You can run more than one reaction at the same time dude.

Good news. after back tracking my steps through all my PR's i found the problem. It is now fixed in [this](https://github.com/tgstation/tgstation/pull/80600/commits/9f7e11793791c7a2fbd7df41e25aa84c42b618b7) commit. So you now get 10 plastic sheets again.

> all reagents are like this. I was playing bartender and i noticed many of my reactions didn't update unless i heated them with a lighter in round ID 221177

I think the problem was some of the booze reactions were instant and weren't getting triggered enough during each react step. The above linked PR should fix your issue as well, but if not feel free to create a detailed issue about it with reproduction steps.

Overall thank you everyone for reporting your issues, they should all be resolved by the above PR. see you soon.

**Closed** 2023-12-28 07:48 UTC
