### ISSUE TITLE
Intellicard AI inserted into mechs are unable to use modules

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#65909] opened 2022-04-03 21:05 UTC
Reporting client version: 514.1581

## Round ID:
[181026](https://scrubby.melonmesa.com/round/181026)

## Testmerges:
- [Refactor and improve antimagic to be more robust](https://www.github.com/tgstation/tgstation/pull/64124)

## Reproduction:
If you card an AI in a core and insert them into a mech, they are unable to 
use their weapon modules. This is due to the PR listed below not acknowledging these issues before merge:
https://github.com/tgstation/tgstation/pull/65375

This does seem to be an issue in:
https://github.com/tgstation/tgstation/issues/64112

The latter issue report may not be relevant however due to it being created before the former PR was merged.

**Comment by thgvr** [comment] 2022-04-04 17:35
All AIs can't use mech modules, even thought it states middle click.

**Comment by Fikou** [comment] 2022-04-08 08:31
dupe of #64112

**Closed by Fikou** 2022-04-08 08:31 UTC

**Comment by TheSilverNuke** [comment] 2022-04-08 15:40
I wouldn't think it was a dupe considering that the code for mechs was completely reworked in between now and then.
