### ISSUE TITLE
Deep frying stacked pancakes duplicates them 

### ISSUE THREAD

**Issue by MoonFalcon** [tgstation/tgstation#46193] opened 2019-08-27 22:18 UTC
Deep frying a stack of pancakes creates individual non fried pancakes for each item in the stack, minus one. So deep frying a stack of 3 pancakes produces 2 individual pancakes and the expected stack of 3 deep fried pancakes 

Issue reported from  Round ID: 117196 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1477

**Comment by nemvar** [comment] 2019-08-27 22:55
Duplicate of https://github.com/tgstation/tgstation/issues/44123

**Closed by nemvar** 2019-08-27 22:55 UTC
