### ISSUE TITLE
MAJOR: Picking up white canes permanently disables your legs

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#83653] opened 2024-06-02 09:01 UTC
Reporting client version: 515.1639

## Issue Summary

It seems like crutches also affect canes. You will be unable to walk whatsoever forever if you pick up a white cane. I tested this by handing a white cane to 15 people.

## Round ID:
[229843](https://scrubby.melonmesa.com/round/229843)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)

## Reproduction:

Get 3 iron rods, craft a white cane, observe that your legs have become completely fucked forever, and hand it to other people, because if you cannot rise, then others must fall

**Comment by Time-Green** [comment] 2024-06-02 13:33
Duplicate of #83646

**Closed by Time-Green** 2024-06-02 13:33 UTC
Labels: FUCK
