### ISSUE TITLE
Camera object of advanced camera console gets deleted after mass delete

### ISSUE THREAD

**Issue by Fishimun** [tgstation/tgstation#45138] opened 2019-07-11 23:02 UTC
Issue reported from  Round ID: 112903 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471
While i was looking at an admin spawned area, The admin deleted the area and the camera object was deleted aswell locking me in the console and forcing me to restart the client.

**Comment by Dennok** [comment] 2019-07-12 09:29
Admin abuse/tool issue. If tool implemented to delete ALL, it must to delete ALL.
Only what i see, the camera eye must to disconnect the user from self on deleting.

**Comment by FloranOtten** [comment] 2019-07-12 19:39
I don't see a scenario where a person doing an area delete would also want to make any camera consoles viewing the place nonfunctional. Maybe exempt it from the mass delete?

**Comment by nemvar** [comment] 2019-07-13 09:02
No, the proper solution would be for camera consoles to spawn a new camera mob should their old one get deleted.

**Comment by Dennok** [comment] 2019-07-13 11:54
it spawn it, if dont have, when someone try to use camera console

**Comment by timothymtorres** [comment] 2022-03-31 10:25
I'm closing this since this was caused by admin shenanigans.

**Closed by timothymtorres** 2022-03-31 10:25 UTC
Labels: Bug, Needs Reproducing
