### ISSUE TITLE
some other issues with bloodcrawling

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#15103] opened 2016-01-31 03:18 UTC
1.If you get stunned in bloodcrawling you can't exit even if there's blood around you
2.You still breathe air form the station
3. IF YOU DIE IN IT YOU'RE STUCK IN IT FOREVER

**Comment by PKPenguin321** [comment] 2016-01-31 03:33
3 is intended, 2 is a maybe, 1 definitely sounds like a bug

**Comment by xxalpha** [comment] 2016-01-31 04:06
How do you get stunned while bloodcrawling?

**Comment by kevinz000** [comment] 2016-01-31 07:26
Chemically stunned
I got neurotoxed and flamethrowered. I escaped without the flames touching me. I DIED BECAUSE AYY LMAO BLOODCRAWLING = BREATH AIR :^)

**Comment by KazeEspada** [comment] 2016-02-01 07:08
That's because you can't breath from the blood, so it searches upwards until it finds a turf to breath in.

**Comment by Jalleo** [comment] 2016-02-01 18:34
Probably should get it to work out if you need to breathe.

**Comment by Whoneedspacee** [comment] 2020-03-13 11:25
This isn't an issue, at least anymore, went into bloodcrawl and called Stun(100) on myself, exited freely.

There is an issue though where the do_after for exiting keeps going even if you move away because you're in the mob holders contents though. @PKPenguin321

**Comment by nightred** [comment] 2020-09-11 21:52
Closing this as not reproducible any more.

**Closed by nightred** 2020-09-11 21:52 UTC
Labels: Bug
