### ISSUE TITLE
Tram toxins explosive scanner doesn't work

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#59218] opened 2021-05-21 01:04 UTC
## Reproduction:
Apparently Tram's toxin scanner that gives you points for setting off bombs near it doesn't work because said scanner is on a different z-level than the sci servers, so it just tells you "No available techwebs!"

**Comment by ArcaneDefence** [comment] 2021-05-21 03:43
Duplicate of https://github.com/tgstation/tgstation/issues/58380

**Closed by ArcaneDefence** 2021-05-21 03:43 UTC
