### ISSUE TITLE
Photographs taken with camera do not pick up statues

### ISSUE THREAD

**Issue by GeneriedJenelle** [tgstation/tgstation#65922] opened 2022-04-04 05:01 UTC
## Reproduction:

Make a statue of a person carved with a material, use a camera to take a picture of the statue. Only the base appears in the photo output.
![image](https://user-images.githubusercontent.com/12565163/161476965-a8bae23e-f8bf-4a6f-99ab-6dcf63f62ac6.png)

**Comment by timothymtorres** [comment] 2023-04-07 09:52
Duplicate of #70798

**Closed by timothymtorres** 2023-04-07 09:52 UTC
Labels: Bug
