### ISSUE TITLE
Bruhrand shields keep draining too hard, Spaceheater edition.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84419] opened 2024-06-28 13:55 UTC
I don't have to say more, but Durand with it's crappy shields and by extension Space heaters too, last about 4 seconds on the new bluespace cell. Just an oversight in power consumption. 400kj cell and 100kj power usage rate on both items.

**Comment by Sadboysuss** [comment] 2024-06-28 15:33
in part a duplicate of https://github.com/tgstation/tgstation/issues/84329
The durand shield is an oversight though

**Closed** 2024-08-14 10:31 UTC
Labels: Oversight
