### ISSUE TITLE
Quick-Swapping glasses can cure nearsightedness & stack huds

### ISSUE THREAD

**Issue by Wallemations** [tgstation/tgstation#52788] opened 2020-08-08 01:40 UTC
## Reproduction:
Using the quickswap feature, you are capable of swapping between clothes without needing to take them off. While this is overall a good feature, there are slight bugs which this can entail. The below photos show the process for recreating said issue.
![Starting state 1](https://cdn.discordapp.com/attachments/179339932266004481/741467812849254430/unknown.png)
![Starting state 2](https://cdn.discordapp.com/attachments/179339932266004481/741467857178853456/unknown.png)
![Starting state 3](https://cdn.discordapp.com/attachments/179339932266004481/741468079782887454/unknown.png)
Firstly, you can see that we start with a character who is nearsighted, and requires glasses in order to not have their vision obscured. This is normal.
![Issue state 1](https://cdn.discordapp.com/attachments/179339932266004481/741468167959871538/unknown.png)
![Issue state 2](https://cdn.discordapp.com/attachments/179339932266004481/741468215905091604/unknown.png)
However, if we are to quick-swap from one eye-slot item to another, we suddenly find that our nearsightedness is magically cured, even if we take off the new pair of goggles/glasses. This is _not_ normal.
![Issue state 3](https://cdn.discordapp.com/attachments/179339932266004481/741468318656888903/unknown.png)
Finally, if we are to quick-swap between different HUD items, we see that we suddenly have gained the ability to see every aspect of a person's identity & current state (the diagnostic HUD is similar, however because nothing nearby actually has nanites or is a borg, it doesn't show up properly.)
I am going to assume that the reason nearsightedness is affected is due to the glasses effect being related to it being dropped from the eye slot, which it does not recognize has occurred if quick-swap is used.

**Comment by ATH1909** [comment] 2020-08-08 02:28
known bug

also, this works with most clothing items in the game, including gloves

krav maga with this in particular can get kind of funky

**Comment by ATH1909** [comment] 2020-08-08 02:30
https://github.com/tgstation/tgstation/issues/50798

**Comment by Ryll-Ryll** [comment] 2020-08-08 02:35
I'm on it

**Comment by Tharcoonvagh** [comment] 2020-08-10 07:54
Oh shit krav maga guerrila gloves

**Comment by ShizCalev** [comment] 2020-08-16 20:48
Duplicate of #50798

**Closed by ShizCalev** 2020-08-16 20:48 UTC
Labels: Bug
