### ISSUE TITLE
pubby monastery shuttle cant be sent back from public mining docking area

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#54370] opened 2020-10-13 11:00 UTC
![shuttle bug 6](https://user-images.githubusercontent.com/33834933/95852330-df049c00-0d53-11eb-8585-d469ef7e47b5.PNG)

## Round ID:

[148223](https://scrubby.melonmesa.com/round/148223)

**Comment by Dennok** [comment] 2020-10-13 11:15
This from lavaland console?
what about shuttle console?

**Comment by Tlaltecuhtli** [comment] 2020-10-13 11:51
didnt test shuttle console

**Comment by msgerbs** [comment] 2020-10-13 20:38
Dammit. I tested everything except this when I fixed the pod last time. I will fix.

**Comment by Cartographer-D** [comment] 2020-11-16 18:13
@msgerbs Do you have any intention on doing this in the next few days?

**Comment by msgerbs** [comment] 2020-11-16 18:14
Oh yeah, forgot about this. I'll fix it today.

**Comment by Cartographer-D** [comment] 2020-11-16 18:15
@msgerbs Can you also properly title the monastery shuttle? I went looking for it in the _maps area, but couldn't find it.

**Comment by msgerbs** [comment] 2020-11-16 19:04
It's pod_large I believe. I don't want to rename it because it could easily be used in some other map as well, it's not pubby-specific.

**Comment by msgerbs** [comment] 2020-11-20 03:55
Never mind, I don't have time right now and I'm not really sure what a good way to fix this is. Feel free to fix it. The issue is if we rename the pubby shuttle to mining_common then it won't act like an escape pod at the end of the round. I wish we could override the mining console only for pubby.

**Comment by dragomagol** [comment] 2020-12-10 01:38
Pubby removed via #54588 , is there a concern this will affect other maps or can we close it @msgerbs?

**Comment by msgerbs** [comment] 2020-12-10 01:39
> 
> 
> Pubby removed via #54588 , is there a concern this will affect other maps or can we close it @msgerbs?

I would only see this being a concern if another map uses it as a public mining shuttle. So probably not.

**Comment by msgerbs** [comment] 2020-12-10 01:40
Also RIP and good riddance Pubby.

**Comment by JohnFulpWillard** [comment] 2022-04-26 21:44
This is still a problem. The shuttle computer is still in-code so even with it being unused in-game currently, it will re-become a problem if it ever is used again.

**Comment by msgerbs** [comment] 2022-04-26 21:51
The issue isn't the shuttle computer, it's trying to use the same shuttle as both an escape pod and the mining common shuttle. They are both working as designed, but Pubby was using them in a way they were not intended to be used. The only way I can think to fix this is to refactor how the entire way shuttles are identified works, perhaps to work based on a list of tags or flags rather than a set name, or else perhaps to save the name of the currently docked shuttle when it jumps to another docking bay. I'm not sure.

**Closed** 2023-03-18 00:36 UTC
Labels: Mapping
