### ISSUE TITLE
Goliath tentacles do not disappear properly

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#23070] opened 2017-01-17 11:14 UTC
![bear hub 82 2017-01-17 060814 1](https://cloud.githubusercontent.com/assets/8237862/22018281/0eb7ff30-dc7c-11e6-896f-9c50343e41bc.png)

In addition, only one of the tentacles will actually stun you, the rest just sit there wiggling forever.

**Comment by AnturK** [comment] 2017-01-17 11:18
@MrStonedOne Timer issue ?

**Comment by Hatfish** [comment] 2017-01-17 11:49
That's probably it.
![bear hub 82 2017-01-17 064816](https://cloud.githubusercontent.com/assets/8237862/22019317/0e52d146-dc81-11e6-808b-0020ef8b7ebb.png)
![bear hub 82 2017-01-17 064759](https://cloud.githubusercontent.com/assets/8237862/22019318/11b0baec-dc81-11e6-90de-b8f6c3819b53.png)

**Comment by AnturK** [comment] 2017-01-17 11:53
Was #22933 test-merged during this ?

**Comment by Hatfish** [comment] 2017-01-17 12:20
I have no clue.

**Comment by lzimann** [comment] 2017-01-17 19:25
Was this on sybil or bagil? The addtimer refactor is currently testmerged in Sybil and I don't think anyone touched the server in the meantime.

**Comment by Hatfish** [comment] 2017-01-20 20:16
This still appears to be an issue on Bagil, I'd guess that #22933 is at fault.
![tgstation bagil english 100 free lag capitalist pathsingularity beta 2017-01-20 151342](https://cloud.githubusercontent.com/assets/8237862/22164014/5f4d0a0e-df23-11e6-9deb-dbe077b644ff.png)

![tgstation bagil english 100 free lag capitalist pathsingularity beta 2017-01-20 150008](https://cloud.githubusercontent.com/assets/8237862/22163684/d99131de-df21-11e6-98c1-e141223d6176.png)

**Comment by AnturK** [comment] 2017-01-20 20:17
@MrStonedOne

**Comment by MrStonedOne** [comment] 2017-01-20 22:03
Can at least 1 person attempt to reproduce on master? I can't do everything.

So we can know if its a test merged thing.

Also, i need more details about how to reproduce  this. I know literally 0 about lavaland

**Comment by Hatfish** [comment] 2017-01-20 22:59
I don't think it's just a lavaland thing, weapon aftereffects on the station were being affected the same way.  Doesn't seem to be a round-to-round issue either, and I've only ever noticed it happening later in the round (40 minutes and up would be my guess).

**Comment by MrStonedOne** [comment] 2017-01-20 23:04
again, i still need a set of steps to reproduce.

It's been 6 months since i actually played a round as a player, don't assume i know how to do anything.

**Comment by KorPhaeron** [comment] 2017-01-21 00:18
@MrStonedOne 

When a /mob/living/simple_animal/hostile/asteroid/goliath/beast attacks it has a chance to dig its tentacles into the ground under the offending mob

The code starts on line 462 of mining_mobs.dm

**Comment by Cyberboss** [comment] 2017-01-23 16:29
Fixed in #23239? @MrStonedOne

**Comment by KorPhaeron** [comment] 2017-01-23 16:53
Now instead of the tentacles lasting forever they just take forever to attack in the first place

**Closed** 2017-01-27 01:21 UTC
Labels: Bug
