### ISSUE TITLE
Holodeck carp not doing shit

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#21785] opened 2016-11-27 07:53 UTC
Sic carp on revhead as valadin AI
They sit there and stare at my cameras
Everyone laughs at me
:(

**Comment by jughu** [comment] 2016-11-27 09:33
Earlier yesterday i saw nuke ops use viscerators and they weren't hostile too they werent doung shit either

**Comment by jughu** [comment] 2016-11-27 12:07
legions arent HOSTILE EITHER

**Comment by jughu** [comment] 2016-11-27 12:16
basalisks doesnt either

**Comment by Armhulen** [comment] 2016-11-27 18:25
yeah legion just kind of sit around

**Comment by Cyberboss** [comment] 2016-11-27 18:52
Possibly related to #21688 ? @MrStonedOne ?

**Comment by Kevak** [comment] 2016-11-27 23:37
Syndie and pirate mobs aren't doing anything either in the spaceruin.

**Comment by Armhulen** [comment] 2016-11-28 03:15
WE BROKE IT

**Comment by AnturK** [comment] 2016-11-28 11:29
Dupe of #21806

**Closed by AnturK** 2016-11-28 11:29 UTC
