### ISSUE TITLE
It's the most wonderful freeze of the year, so let's tackle the black sculptures bug

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#63338] opened 2021-12-10 14:05 UTC
## Reproduction:
Some sculptures turn black regardless of material upon completion - it always looks fine during the process. They also retain overlays (or whatever you call them shiny effects) - for instance, the middle-most part of the gravity generator.

What's worse, is that most of the affected objects are the ones with coolest/most exotic sprites. Things like displays, the chaplain altar, some mobs, the **fuk of** sign on icebox, basically anything that goes on a wall... Please, save us.

**Comment by NanoCats** [comment] 2021-12-10 14:16
Pretty sure this has already been reported (#61228) and you're just going to get yelled at by someone who has a molecule of authority any time now.

**Comment by SuperNovaa41** [comment] 2021-12-10 14:30
ahem...
Duplicate of https://github.com/tgstation/tgstation/issues/61228

**Closed by SuperNovaa41** 2021-12-10 14:30 UTC

**Comment by Likteer** [comment] 2021-12-10 15:55
@SuperNovaa41 Doesn't that only mention airlocks, chairs and lockers specifically? From my experience it's like 50% of the objects I tried.
But ye, I didn't notice it before, apologies.

**Comment by SuperNovaa41** [comment] 2021-12-10 17:01
It does, but it's probably safe to assume it's not just those
