### ISSUE TITLE
Sentient disease can't do anything.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#64019] opened 2022-01-12 03:33 UTC
## Testmerges:

#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit 8c52016858
#63666: 'makes ai static into images added to obscured turfs to save on maptick' by Kylerace at commit 7d56c359ec

## Reproduction:

Get sentient disease midround
Infect target
Press cough
No cough, icon doesn't go on cooldown
Ghost immediately.

**Comment by SuperNovaa41** [comment] 2022-01-12 04:04
Duplicate of https://github.com/tgstation/tgstation/issues/63764

**Closed by SuperNovaa41** 2022-01-12 04:04 UTC
