### ISSUE TITLE
blob tiles no work anymore

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55503] opened 2020-12-13 12:06 UTC
bullets pass through blob tiles and hit whatever you clicked (the core for example) and items just pass through like the blob tiles had no density
152090

**Comment by dragomagol** [comment] 2020-12-13 17:08
Duplicate of #55472 (and a fix is up, should be fixed soon)

**Closed by dragomagol** 2020-12-13 17:08 UTC
