### ISSUE TITLE
Tramstation xenobiology slime cells are not 100% covered by cameras

### ISSUE THREAD

**Issue by LarissaMayrink** [tgstation/tgstation#70701] opened 2022-10-21 01:12 UTC
## Round ID:
[192734](https://scrubby.melonmesa.com/round/192734)

## Reproduction:
Tramstation xenobiology slime cells are not 100% covered in camera range, sure it is VISIBLE through the computer but you can't actually pickup slimes or monkeys from all the tiles inside the cells, some give you the message "Target is not near a camera. Cannot proceed."

**Comment by Sealed101** [comment] 2022-10-21 09:50
#70664 dupe because xenobio consoles use ai eye's freelook

**Comment by Mooshimi** [comment] 2022-10-25 16:48
Duplicate of https://github.com/tgstation/tgstation/issues/70664 , which is now fixed. please post here if issue persists and it will be reopenned

**Closed by Mooshimi** 2022-10-25 16:48 UTC
