### ISSUE TITLE
Incorrect Icon name

### ISSUE THREAD

**Issue by FalloutFalcon** [tgstation/tgstation#79754] opened 2023-11-15 04:36 UTC
## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/86381784/236173df-ab1c-452c-8cf1-28b5dac8f4e5)
![image](https://github.com/tgstation/tgstation/assets/86381784/88523d98-e34c-4df4-b5d3-e7fe635dfe85)

Look in lizard.dmi folder. Look at peanutbutter obj.. see incorrect name..

I noticed this while looking through folders to port some stuff to shiptest. I dont code here lol

**Comment by lizardqueenlexi** [comment] 2023-11-15 07:30
![image](https://github.com/tgstation/tgstation/assets/105025397/8a5f0db6-ea93-4daa-9018-2d4eb52144f1)

The icon name is correct, but it looks like the text may have gotten cut off on your end. Dream Maker just... does that if the window size is too small.

**Comment by SyncIt21** [comment] 2023-11-15 08:00
> The icon name is correct, but it looks like the text may have gotten cut off on your end. Dream Maker just... does that if the window size is too small.

Confirmed. the window was just too small, if you expand it you will see the full name
![Screenshot (359)](https://github.com/tgstation/tgstation/assets/110812394/e09cc8ac-66be-4b93-a080-fc8b52ff1bc5)

**Comment by MNPSarchiveAc** [comment] 2023-11-15 13:10
well now i look stupid c:

**Comment by MNPSarchiveAc** [comment] 2023-11-15 13:11
i wish i could close this. I still think its weird to use - when most of the folder used _

**Closed** 2023-11-15 14:00 UTC
