### ISSUE TITLE
Wires broken on most if not all space ruins

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32599] opened 2017-11-10 16:49 UTC
Saw this on the derelict and on the ancient station, here's a pic: https://file.house/oOjl.png

**Comment by BeeSting12** [comment] 2017-11-10 16:50
This occur roundstart

**Comment by praisenarsie** [comment] 2017-11-10 17:39
@ShizCalev @ninjanomnom

**Comment by ShizCalev** [comment] 2017-11-10 17:57
Why are you pinging me there's already another issue and 2 fix prs

Duplicate of #32519

**Closed by ShizCalev** 2017-11-10 17:57 UTC
