### ISSUE TITLE
MMIs in mechs cannot use any equipment

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#27058] opened 2017-05-08 01:08 UTC
kinda makes them useless, actually

**Comment by PKPenguin321** [comment] 2017-05-08 01:39
Dupe

**Comment by Repukan** [comment] 2017-05-08 01:40
Dupe

**Comment by Penguaro** [comment] 2017-05-08 02:39
@lzimann This is a duplicate of #24422.

**Closed** 2017-05-08 02:41 UTC
