### ISSUE TITLE
Split personality took the Changeling datum with them

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#68256] opened 2022-07-07 18:05 UTC
## Reproduction:

1. Be a Changeling
2. Get a Split personality
3. Die
4. Get revived and your split personality cured

They have their Changeling HUD despite not having any hud or datum
![mind](https://user-images.githubusercontent.com/53777086/177839481-b725c5a3-bdec-46cd-baaf-0d4263a5247d.png)

Their split personality (who was a ghost since they were cured out) also had no antag datum

The only way I was able to find it was through Check Antagonists, which showed this (Mind currently owned listed the **split personality**- not the person currently controlling the body, as the owner).
![image](https://user-images.githubusercontent.com/53777086/177839625-cd394058-af78-4d15-81ed-5c651452b713.png)

Despite this, the main body still had their Changeling buttons, though they were entirely unusable. I tried giving them Changeling back, but it gave them 2 sets of buttons instead.
I had to remove the Changeling datum from the aether (view antagonists page) for the action buttons to dissapear.

**Comment by Shadowflame909** [comment] 2022-07-07 18:25
wake up babe new changeling de-conversion meta just dropped. (toolbox to the head until they get a split personality)

**Comment by ATH1909** [comment] 2022-07-08 16:45
something something divorce joke

**Comment by timothymtorres** [comment] 2022-10-05 09:38
Duplicate of #41601

**Closed by timothymtorres** 2022-10-05 09:38 UTC
Labels: Bug
