### ISSUE TITLE
When you examine the cult rune that spawns in lavaland you crash.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#29018] opened 2017-07-03 23:16 UTC
latest Server revision compiled on: 2017-07-03 60a0c8

When you examine the rune that spawns round start sometimes in lavaland it causes a client crash.

**Comment by Tacolizard** [comment] 2017-07-04 21:40
were you able to reproduce this issue, and if so, how many times?

**Comment by JusticeGoat** [comment] 2017-07-04 22:41
I tested it three times in a row and had another test it and same thing happens it crashes you.

**Comment by Xhuis** [comment] 2017-07-05 01:05
Which rune is this referring to? I'm not super up-to-date on lavaland.

**Comment by JusticeGoat** [comment] 2017-07-05 01:20
The only one that allows you to orbit it in the ghost menu, its in the cult ruin.

**Comment by Cyberboss** [comment] 2017-07-05 02:10
If this happens again can you link the round id? I'd like to see the logs

**Comment by Xhuis** [comment] 2017-07-05 02:18
Yeah! I'm kind of curious as to why this is happening. That's just the Nar-Sie rune, but I'll take a look around and see if there's anything that might be causing it.

**Comment by Xhuis** [comment] 2017-07-05 02:35
I've found the issue. It seems like, due to goonchat's method of rendering icons, the rune lacking an icon (due to a known bug) is causing the game to crash. There's a PR that fixes this up already, and I've requested that its creator include the line to automatically close this issue once it's merged.

**Comment by ChangelingRain** [comment] 2017-07-05 03:25
This issue should be converted to a generalized one if that is the case, as my pr only fixes one instance of it.

**Comment by factoryman942** [comment] 2017-07-09 20:54
the rune is so horrific it drives your byond client insane

**Closed** 2017-11-08 11:02 UTC
Labels: Bug
