### ISSUE TITLE
Catatonic humanized monkeys act like monkeys

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55537] opened 2020-12-15 01:06 UTC
## Round ID:
Recent

## Testmerges:
Manuel

## Reproduction:
1. humanize a monkey
2. hit it
3. have it chase you like a monkey,

**Comment by dragomagol** [comment] 2020-12-15 03:06
Will be fixed by #55535

**Comment by Qustinnus** [comment] 2020-12-15 14:02
no it wont, this is not a bug its a feature.

**Closed by Qustinnus** 2020-12-15 14:02 UTC
Labels: Oversight
