### ISSUE TITLE
The hatchet, portable seed extractor, and secateur have incorrect icons in the right-click menu

### ISSUE THREAD

**Issue by dablusniper** [tgstation/tgstation#51898] opened 2020-06-28 15:52 UTC
![Broken icons](https://user-images.githubusercontent.com/61952812/85952198-f451e800-b967-11ea-853f-293d4166e268.png)

## Reproduction:
1. Right click on a tile with a botany hatchet, portable seed extractor, or secateur on it
2. Look at the icon next to the items

Not much more I can say, really.

**Comment by Tlaltecuhtli** [comment] 2020-06-28 19:56
i had this "kind" of bug constantly, its not specifically these items i think anything you touched/put in a inventory slot ( like in bags) will then get their icon pulled to items on rightclick, 
my last experience with this bug was: i had a plant bag full of fruits then i right click on a pile of items and all the fruit icons were  on the items on the pile

**Comment by Taylorkills2** [comment] 2020-06-29 12:10
There are so many items that have this problem.

**Comment by ArcaneMusic** [comment] 2020-07-21 18:42
So I've been noticing this more and more recently, I wonder if there's something in the cache getting overwritten so recently interacted-with objects are replacing existing icons on right click.

**Comment by Mirino97** [comment] 2020-12-06 00:32
Yup, it's not just those items. I have had them for a few months and they happen with EVERYTHING, to the point that I've created the custom to read the name and completely ignore the icons since they're unreliable.

Also, they can happen to items who were just printed or created.

**Comment by timothymtorres** [comment] 2021-08-19 19:06
Duplicate of #59280

**Closed by timothymtorres** 2021-08-19 19:06 UTC
