### ISSUE TITLE
ghouls/voiceless undeads doesn't count torward mansus minions objective

### ISSUE THREAD

**Issue by Singul0** [tgstation/tgstation#75438] opened 2023-05-14 07:45 UTC
## Testmerges:
[#75426: 'Use rust-g compiled with panic hooks' by Mothblocks at commit 557b07f76f](https://www.github.com/tgstation/tgstation/pull/75426)
[#74775: 'Adds TTS to the game. Players can select their own voices in preferences.' by Watermelon914 at commit 5700cf90b2](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:
1.be flesh heretic
2. make ghouls/voiceless undeads
3. try to figure out how to ascend
4. cant figure it out
5. die
6. figure out later that ghouls/voiceless undeads don't count torwards the make mansus monster objectives

**Comment by MrMelbert** [comment] 2023-05-14 08:45
Intended / Not a bug, the objective is to quote "Summon x **monsters** from the Mansus", which creating ghouls is not

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug
