### ISSUE TITLE
Being made Rev Head despite being afk.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#20406] opened 2016-09-08 20:34 UTC
So basically this happened. (Note, it was either a few days ago, or like 2 weeks ago)
1. Latejoined as non-antag assistant(I always doublecheck due to bugs)
2. Does botany for quite some time.
3. Eventually go afk to wash dishes.
4. I come back and its the next round and everyone is yelling at me due to being braindead as the last revhead.

So apparently what happened was this. After I went afk I got converted to a rev. Afterwards RNG made me a revhead despite me being inactive/afk. And thus I ended up being the only remaining rev head, while being afk.

Also, due to rarely playing SS13 the past few weeks, Jalleo said that any admin reading this should pretty please log dive for this incident. Lack any time and date due to crap memory, but the past few weeks should have relatively little Firecage/Zoey Webb in it.

**Comment by MrStonedOne** [comment] 2016-09-08 22:38
It takes 10 minutes of inactivity to be seen as afk.

I need to lower this, but before i can i need to do some refactors to how afk tracking works.

**Comment by Robustin** [comment] 2017-04-19 17:57
Not a buggggggg

**Comment by PraiseRatvar** [comment] 2017-07-31 14:03
@MrStonedOne ?

**Comment by Qustinnus** [comment] 2019-06-24 23:40
@MrStonedOne is this still the case? it seems like a config option now so I'm closing this if this is no longer an issue

**Comment by Dorsisdwarf** [comment] 2019-07-11 22:56
old, not a bug

**Closed by Dorsisdwarf** 2019-07-11 22:56 UTC
Labels: Not a bug
