### ISSUE TITLE
Facehuggers rip off gas masks while your in a hardsuit

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25660] opened 2017-03-30 16:10 UTC
Da fuck

**Comment by XDTM** [comment] 2017-03-30 17:13
dupe

**Comment by optimumtact** [comment] 2017-03-30 22:15
Link to dupe?

**Comment by Kromgar** [comment] 2017-03-30 23:28
@optimumtact i remember seeing a fix pr a week ago but i guess its still broken.

I was in a inquisitors hardsuit wearing a miners gas mask if that matters

**Comment by optimumtact** [comment] 2017-03-31 00:08
fix hasn't been merged yet #25488 perhaps that's what @XDTM was referring to

**Comment by Cyberboss** [comment] 2017-03-31 13:29
So this is a dupe of #25282

**Closed** 2017-03-31 14:12 UTC
Labels: Bug
