### ISSUE TITLE
Delta station SM air filter is bugged

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#27853] opened 2017-05-30 01:36 UTC
The air filter on Delta station SM stop sending the filter gas back into the loop if you change it from the normal O2 to any other gas.

**Comment by ShizCalev** [comment] 2017-05-30 05:45
Working fine ingame for me.

Checked map wise, looks fine. Might've just been an initialization bug or something. If it happens again, just disconnect and reconnect it.

**Comment by Dorsisdwarf** [comment] 2017-05-30 12:20
if this isnt reproduced in a week imma close this

**Comment by ShizCalev** [comment] 2017-06-06 17:45
Week later, no repo?

**Comment by Cyberboss** [comment] 2017-06-18 02:48
I'm going to assume this was fixed by #28380 @shizcalev

**Closed by Cyberboss** 2017-06-18 02:48 UTC
Labels: Bug, Needs Reproducing/Testing

**Comment by ShizCalev** [comment] 2017-06-18 02:58
It was likely the init issue with filters where they (very rarely) randomly don't work at roundstart until reconnected.

**Comment by ShizCalev** [comment] 2017-06-18 03:00
@Cyberboss It was very likely the issue where filters don't work properly at roundstart until they are reconnected. I've seen it happen once in a blue moon (like once a month at most.)

**Comment by Cyberboss** [comment] 2017-06-18 03:01
It's a dupe of that issue then

**Comment by ShizCalev** [comment] 2017-06-18 03:12
What's the actual issue? Haven't seen that one before
