### ISSUE TITLE
the microbomb implant doesnt work when you die in a mauler mech

### ISSUE THREAD

**Issue by shpamy** [tgstation/tgstation#45508] opened 2019-07-26 15:29 UTC
Issue reported from  Round ID: 114184 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1471

**Comment by timothymtorres** [comment] 2023-12-03 21:55
Duplicate of #68076

**Closed by timothymtorres** 2023-12-03 21:55 UTC
Labels: Bug, Needs Reproducing
