### ISSUE TITLE
malf ai detonate machine power didn't produce a warning message when used on an airlock

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#52041] opened 2020-07-06 04:49 UTC
## Round ID:
[141258](https://scrubby.melonmesa.com/round/141258)

## Testmerges:
#51786 
#51879 

## Reproduction:
1. stand next to a door before a malf ai uses it's powers to blow it up
2. have said malf ai use their blow up machine power on door
3. see no warning message appear in chat
4. blow up and die to something that had no warning

**Comment by Wayland-Smithy** [comment] 2020-07-08 10:57
### Unable to reproduce past step 3
Something else must have been at play other than the overload itself.

![image](https://user-images.githubusercontent.com/64715958/86910631-d8b8b100-c0ce-11ea-9a48-9161fea97523.png)

**Comment by Paxilmaniac** [comment] 2020-07-08 22:21
it was on ice box if that changes anything

**Comment by Wayland-Smithy** [comment] 2020-07-08 22:30
I made sure to test on Ice Box (even caught the snowfall message in my screenshot), and specifically the Chief Engineer's airlock and a firelock like was shown in the round log.

Can you recall the circumstances? You sure you weren't deaf? Was the panel screwed open or maybe power issues? Perhaps Overload failed some checks suppressing the message, but still exploding when it was not supposed to.

**Comment by Paxilmaniac** [comment] 2020-07-11 21:27
![image](https://user-images.githubusercontent.com/57122098/87234086-712a8c00-c382-11ea-99d0-19d334f25baf.png)
it was the blue command door on the ice box ai sat, the door was partially damaged, it had power, the panel was closed and none of the wires were tampered with. I was not deaf at the time.

**Comment by nightred** [comment] 2020-07-23 18:43
![aicore airlock explode](https://user-images.githubusercontent.com/6491940/88325094-40cfdf80-ccea-11ea-81e7-20f07bcec860.png)

This exact core after throwing a spear at it several times and then exploding it still cause it to be reported.
This airlock does not have `airlock` in the name but that is not an issue.

**Comment by nightred** [comment] 2020-07-23 18:46
Closing, if you have new reproduction steps please post them.

**Closed by nightred** 2020-07-23 18:46 UTC
