### ISSUE TITLE
Survival knife and flashlight attached to a PKA rotate separately when thrown

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49783] opened 2020-03-07 03:11 UTC
Issue reported from  Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

I'm guessing this happens with all sprite overlays.

https://i.imgur.com/b9sFjCK.gifv

**Comment by timothymtorres** [comment] 2021-12-30 00:04
Duplicate of #37303

**Closed by timothymtorres** 2021-12-30 00:04 UTC
Labels: Bug
