### ISSUE TITLE
You can't eat Salami

### ISSUE THREAD

**Issue by Cowbin** [tgstation/tgstation#55888] opened 2021-01-01 22:15 UTC

**Comment by dragomagol** [comment] 2021-01-01 22:27
I wasn't able to reproduce this on local but I did notice this as a moth unable to eat a janitor's hat (instead just hitting myself with it) the other day.

**Comment by Cowbin** [comment] 2021-01-01 23:14
I was on help intent, a second lizard who was there was also unable to consume the salami slice.  I was just hitting myself with the salami.

**Comment by ShibaInuLord** [comment] 2021-01-02 00:02
might be the same type of issue as #55855

**Comment by ArcaneDefence** [comment] 2021-01-03 02:32
This is a duplicate of https://github.com/tgstation/tgstation/issues/55375

You can reproduce this by making a raw sausage with the monkey meat that starts in the freezer, cooking it, and cutting it. You get two slices of salami that have reagents that can be eaten and four that cannot until further reagents are added.

**Closed by ArcaneDefence** 2021-01-03 02:32 UTC
Labels: Needs Reproducing
