### ISSUE TITLE
Eigenstasium linked lockers cant teleport people

### ISSUE THREAD

**Issue by DarkHunter7756** [tgstation/tgstation#82921] opened 2024-04-28 00:04 UTC
## Reproduction:

 1. Cook pure or almost pure Eigenstasium.

![image](https://github.com/tgstation/tgstation/assets/76823962/d7052bc1-9ddf-458c-8f0d-64b1f4cf2dfe)

2. Splash reagent on tile under 2 lockers. 
![image](https://github.com/tgstation/tgstation/assets/76823962/0ca4f379-7652-4084-a97d-79c18644ea1b)

3. Eigenlockers are linked together, but if you close one, you will not teleport to another

![dreamseeker_Mnx3HpX4SI](https://github.com/tgstation/tgstation/assets/76823962/a89cd426-9462-4526-a92c-2e7a51e74e87)

**Comment by newfren** [comment] 2024-04-28 02:02
those lockers should also be getting a blue tint to them and have not

**Comment by Vect0r2** [comment] 2024-04-28 05:51
dupe of this https://github.com/tgstation/tgstation/issues/82353

**Closed** 2024-04-29 11:45 UTC
