### ISSUE TITLE
Silver Slime Crossbreed Metallic Cookies have references in their tastes

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79364] opened 2023-10-29 03:32 UTC
Reporting client version: 514.1589

## Round ID:
[217716](https://scrubby.melonmesa.com/round/217716)

## Testmerges:
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:
Ate a Metallic Cookie, got:

'You eat the metallic cookie.
Tastes like /datum/reagent/copper.'

**Comment by Jacquerel** [comment] 2023-10-29 16:06
This is very silly, but as far as I can tell also intentional.

**Comment by OuroborusReporter** [comment] 2023-10-30 02:01
On the one hand, the flavor text in the code is _literally_ /datum/reagent/copper
On the other hand, the other cookies have normal, human-experiencable flavors
Either way, it's a funky line of text for a food basically no one ever makes

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug
