### ISSUE TITLE
Linking Filled ORM to new Ore Silo deletes all the materials.

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#65450] opened 2022-03-14 04:32 UTC
Reporting client version: 514.1581

## Round ID:
[179922](https://scrubby.melonmesa.com/round/179922)

## Reproduction:
This happened as a free golem, but I don't think that has a part in the issue
1. Build a new Ore Silo
2. Link the Silo to an ORM with mats already in the ORM.
3. All the mats get deleted
Usually the mats would just eject themselves on top of the ORM but they don't. I also right-clicked around to see if they somehow went invisible or moved somewhere but I didn't see anything.

**Comment by Fryzzie** [comment] 2022-03-14 06:30
If this was on icebox floor two, the roundstart free golem ORM is linked to the stations silo. Its a known issue, but you need to rebuild the ORM before using it.

**Comment by dragomagol** [comment] 2022-03-14 17:36
This appears to have been on Icebox, which makes this a duplicate of #60944 (please feel free to re-open this if the above comment is not the case).

**Closed by dragomagol** 2022-03-14 17:36 UTC
