### ISSUE TITLE
Signallers don't work in button assemblies

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#37655] opened 2018-05-03 23:14 UTC
Reproduction: make wall button, get two matching signallers, put in one signaller, close, press, listen for nonexistent beep from the other

**Comment by Mickyan** [comment] 2018-05-04 14:56
They definitely work, I use them from time to time to make door locks. Were you using a screwdriver to make them attachable? You don't have to do that if you put them in buttons.

**Comment by TheBonded** [comment] 2021-11-02 20:03
I can't seem to reproduce this, so I assume this has been fixed in the past 3 years

**Comment by TheBonded** [comment] 2021-12-08 20:23
Ima just close this now because it seems to no longer be an issue

**Closed by TheBonded** 2021-12-08 20:23 UTC
Labels: Needs Reproducing
