### ISSUE TITLE
Plant bag UI does not display amount of each item properly

### ISSUE THREAD

**Issue by Jewelry-x** [tgstation/tgstation#86916] opened 2024-09-26 17:04 UTC
### Client Version:

515.1462

### Issue Summary:

When you put items in the plant bag (carrots, parsnips, tomatoes, etc.) the number that is supposed to show the amount of each item does not display properly.

![image](https://github.com/user-attachments/assets/ca0bba69-b853-4b4b-845b-722a363f7f3f)

### Reproduction Steps:

1. Grow some seeds in a hydroponics tray
2. Put resulting crops in plant bag
3. Open plant bag
4. The number is not displaying properly

**Comment by the-orange-cow** [comment] 2024-09-26 17:14
It should be noted that I think the size of the number may be linked to the size of the plant, which is based off potency.

So: higher potency, bigger never.  Lower potency, smaller number.

**Comment by MrMelbert** [comment] 2024-09-26 17:23
^ 
The number just uses maptext, and maptext scales based on the item's transform

The only way you'd feasibly fix this is if you put the maptext on another atom, like the storage boxes, or

**Comment by Sealed101** [comment] 2024-09-26 18:05
numbers for ants (doubly funny because we actually have space ants)

**Comment by Sealed101** [comment] 2024-09-26 18:05
Duplicate of #36891

**Closed by Sealed101** 2024-09-26 18:05 UTC
Labels: Bug, UI
