### ISSUE TITLE
Error: Eyeobj not Found | Serverroom Pubbystation

### ISSUE THREAD

**Issue by Blonkz** [tgstation/tgstation#21503] opened 2016-11-12 17:17 UTC
Be AI. Have camerer alarm in Tcoms Server Room! Click link. Recive following error:

ERROR: Eyeobj not found. Creating new eye...
View resets on AI-Core.

To recreate: do it again.

**Comment by PraiseRatvar** [comment] 2017-07-31 14:07
@pubby ?

**Comment by timothymtorres** [comment] 2021-08-23 10:55
Duplicate of #20238

**Closed by timothymtorres** 2021-08-23 10:55 UTC
Labels: Bug
