### ISSUE TITLE
who would win: 1 supermatter shard which could destroy the entire station VS 1 iron boi

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39536] opened 2018-08-03 13:01 UTC
![image](https://user-images.githubusercontent.com/38788538/43644129-4c4def5a-9736-11e8-8d91-5a601699b5b0.png)

ramming into a supermatter while being a borg just damages you a little bit, but not gibs you

the perfect way of triggering admins

**Comment by AnturK** [comment] 2018-08-03 13:33
Duplicate of #39373

**Closed by AnturK** 2018-08-03 13:33 UTC
