### ISSUE TITLE
Bug with human sprites(??)

### ISSUE THREAD

**Issue by tedward1337** [tgstation/tgstation#9074] opened 2015-04-19 23:13 UTC
There was no body but the clothes were still attached? 

![](http://puu.sh/hjWrj/e15259f398.jpg)

**Comment by RemieRichards** [comment] 2015-04-19 23:14
Well, the clothes being there is just because the clothes part of update_icons() worked.

Was it badminnery?

**Comment by tedward1337** [comment] 2015-04-19 23:14
No, no badminnery was in place. This was just standard xenos

**Comment by Miauw62** [comment] 2015-04-20 16:39
I've seen this happen before with broken monkey transformations I think.

**Comment by phil235** [comment] 2015-04-20 17:57
Did anyone check what the human's icon vars were like?

**Comment by phil235** [comment] 2016-05-10 15:15
The issue is that the human's base icon state was changed and did not match the name of a base human sprite anymore. With the introduction of dismemberment this bug will be even harder to reproduce since only a few species still use the base icon state code.

If noone witnessed this bug recently, I think we should close it.

**Closed** 2016-05-26 19:13 UTC
Labels: Bug, Needs Reproducing/Testing, Sprites
