### ISSUE TITLE
Clockwork Proselytizers are sticky.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#28037] opened 2017-06-03 15:39 UTC
I don't know how to go about recreating this, but I've noticed lately, on myself and with other people that they can get the proselytizer stuck in hand as far as sprites, even after putting it away. So. You're walking around permanently with a cult tool in hand. Good luck with that.

**Comment by Militaires** [comment] 2017-06-03 18:42
probably a dupe of the same-second click bug

**Comment by KorPhaeron** [comment] 2017-06-03 19:49
https://github.com/tgstation/tgstation/issues/26703

**Comment by praisenarsie** [comment] 2017-10-22 10:08
Dupe or similar to #26968

**Closed** 2017-10-22 12:03 UTC
Labels: Bug
