### ISSUE TITLE
"Your fingers are too big" without any gloves bug.

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#70509] opened 2022-10-13 23:44 UTC
Reporting client version: 514.1585

## Round ID:
[192295](https://scrubby.melonmesa.com/round/192295)

## Testmerges:
- [Easy's Super Omega  "unarmed strike based species var moved to limbs" refractor, unarmed strike striking with specific body parts rather than it just being flavor, and brain based attacking limb selection extra chunky edition. And also bodypart traits.](https://www.github.com/tgstation/tgstation/pull/70422)

## Reproduction:

0. Wear a krav-maga gloves, shoot all types of guns without any problems.

1. Wear a crafted botany gloves, see "Your fingers are too big" message when trying to shoot egun, crafted ebow or Makarov.

2. Remove gloves and see that message remaining, making you unable to shoot anything

3. Try to wear other, normal gloves, and still see that message

While fighting, at one moment I had in my arms both egun and crafted from parts ebow, and it once shot (while in harm intent). But that was one shot from maybe fifty.

**Comment by itseasytosee** [comment] 2022-10-14 02:58
Ah what the fuck

**Comment by san7890** [comment] 2022-10-14 06:15
> Ah what the fuck. This is a really weird bug, presumably its caused by my thing but I have no idea how considering I don't touch clothing traits.

Does the trait detach properly from the new arms?

**Comment by itseasytosee** [comment] 2022-10-14 16:06
> > Ah what the fuck. This is a really weird bug, presumably its caused by my thing but I have no idea how considering I don't touch clothing traits.
> 
> Does the trait detach properly from the new arms?

Ya see the refractor doesn't even make traits from gloves apply to the arms, they still just apply to the mob with the exact same system they. I didn't touch clothing traits throughout the entire endeavor.

**Comment by itseasytosee** [comment] 2022-10-14 16:25
I was completely unable to reproduce this bug locally.

Were you a hulk?

**Comment by Mothblocks** [comment] 2022-10-15 05:05
Closing as this is not a bug on master but feel free to continue to try to find the issue with the test merge

**Closed by Mothblocks** 2022-10-15 05:05 UTC
Labels: Test Merge Bug

**Comment by itseasytosee** [comment] 2022-10-15 18:43
My confidence that this bug was caused by my PR is waning, has their been any reproduction of this?
