### ISSUE TITLE
Ghostly items stuck in backpack.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#10500] opened 2015-07-09 21:53 UTC
A player reported experiencing ghostly handcuffs that visually appear to be in his backpack, but his actual items are placed on top of those. He's not able to pull them out. When he placed a crowbar in his backpack, the cuffs moved to his pockets. He later experienced this again with zipties.

**Comment by xxalpha** [comment] 2015-07-10 00:43
I've encountered this bug before. I don't remember how to reproduce it.

**Comment by WJohn** [comment] 2015-07-10 03:52
Yeah, I had this happen to me too a long time ago, still no idea how to do it.

**Comment by Tokiko1** [comment] 2015-07-10 08:32
I think it happens when two people somehow manage to grab the same item. I've noticed that when the other person with the item is moving the item around it will also move in your own inventory.

**Comment by Miauw62** [comment] 2015-07-10 08:46
I've also had this happen and reported it. The icon would stay even if I
closed my backpack. This is a dupe but I don't kn the issue number
Op 10-jul.-2015 10:32 schreef "Tokiko1" <notifications@github.com>:

**Comment by RemieRichards** [comment] 2015-07-10 12:53
I've noticed this as a borg oddly enough, I'm going to assume it's the same bug as they're both phantom items that either are or aren't in the contents list appearing *somewhere* in a player's inventory.
But as a borg I frequently see the frame I was constructed with in the background of the 3 modules.
it's stupid weird.

**Comment by xxalpha** [comment] 2015-07-10 12:54
Yeah. And when someone installs an upgrade module.

**Comment by Nitrousoxide** [comment] 2015-07-10 15:45
You get something sorta like this when you get revived as a borg or have your module changed.  But in that case  you get a ghostly image of a circuit board in your action bar.

Maybe it's related?

**Comment by phil235** [comment] 2015-07-10 17:32
Can be reproduced by having two people removing a third person's handcuff. After the first one finishes he must grab the cuffs on the ground and put them in his backpack before the second person finishes.

**Comment by WJohn** [comment] 2015-09-02 01:51
I tested the same method that occurred with handcuffs except with regular clothing, stripping it first (using riot armor so we had time), then backpacking it before he could finish stripping it. We were both doing this to a third person, but no ghosting occurred.

**Comment by ShizCalev** [comment] 2017-06-09 02:19
Fixed by #26980 I'd assume.

**Comment by ShizCalev** [comment] 2017-06-09 02:21
@lzimann I'd assume this can be closed after #26980 fixed the aforementioned item dupe issue.

**Closed** 2017-06-09 11:23 UTC
Labels: Bug
