### ISSUE TITLE
Disposals pipe loops can delete people from existence

### ISSUE THREAD

**Issue by OmegaDarkPotato** [tgstation/tgstation#62364] opened 2021-10-26 19:09 UTC
## Testmerges:
#62348 

## Reproduction:
Go to thunderdome, make pipe loop, toss 6 or so people in, break loop, watch as ~4 people come out. Tested with the basic 5-pipe loop system of a chute, junction, and three curves to go back into the junction.

Encountered this bug on 171974 and ended up having to spawn in two people who had been eradicated from reality by an engi who didn't know what he had done.

**Comment by timothymtorres** [comment] 2021-10-31 15:41
Duplicate of #26512

**Closed by timothymtorres** 2021-10-31 15:41 UTC
Labels: FUCK

**Comment by TheBonded** [comment] 2021-11-01 17:39
holy shit this has been an issue since 2017
