### ISSUE TITLE
Weird zipper sound on the lobby after round-start.

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#47027] opened 2019-10-11 21:45 UTC
## Testmerges:
#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit 81ffdee8da

## Reproduction:
Unsure of how to reproduce, not sure what's causing it, probably a sound issue. I just kept hearing this weird zipper sound while sitting on the lobby screen after the round had started.

**Comment by Iamgoofball** [comment] 2019-10-11 21:51
Asking around, it seems to occur when someone connects to the server and it generates a mob for them to inhabit along with a random jumpsuit. Apparently it's the equip sound for the jumpsuit, this should probably be adjusted to not occur for lobby players.

**Comment by PKPenguin321** [comment] 2019-10-12 01:52
Dupe of https://github.com/tgstation/tgstation/issues/46478 (technically not dupes but they're caused by the same bug)

**Closed by PKPenguin321** 2019-10-12 01:52 UTC
