### ISSUE TITLE
Pride's Mirror nonfunctional

### ISSUE THREAD

**Issue by Alterist** [tgstation/tgstation#63288] opened 2021-12-07 13:28 UTC
Reporting client version: 514.1571

## Round ID:
[174359](https://scrubby.melonmesa.com/round/174359)

## Reproduction:

Pride's Mirror doesn't work, tried it twice with different characters

**Comment by TheBonded** [comment] 2021-12-07 15:31
Duplicate of https://github.com/tgstation/tgstation/issues/63064

**Closed by TheBonded** 2021-12-07 15:31 UTC
