### ISSUE TITLE
Hitting e to equip doesn't work for drones

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35812] opened 2018-02-19 01:34 UTC
[Round ID]: # 83849
be drone
hit e
doesn't equip
keep hitting e all round because you don't learn

**Comment by YPOQ** [comment] 2018-02-21 23:47
#34821

**Comment by ShizCalev** [comment] 2018-03-13 02:18
Duplicate of #34821

**Closed by ShizCalev** 2018-03-13 02:18 UTC
Labels: Bug
