### ISSUE TITLE
Mesons used on an upper Z-level act like X-rays for exposed lower levels

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#63566] opened 2021-12-22 21:10 UTC
## Round ID:
[175242](https://scrubby.melonmesa.com/round/175242)

## Testmerges:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63439: 'test disables ai static to see if it helps maptick enough to justify a refactor of how it works' by Kylerace at commit c55948c9e8

## Reproduction:
Icebox
Wear mesons
Enter maints between xenobiology and medical
You'll be able to see mobs, turfs, and objects on the lower level of xenobiology

![image](https://user-images.githubusercontent.com/44104681/147143926-69c26c0f-0f5e-47a0-842f-eb2ac034ac67.png)

**Comment by SuperNovaa41** [comment] 2021-12-23 13:55
Duplicate of https://github.com/tgstation/tgstation/issues/53783

**Closed by SuperNovaa41** 2021-12-23 13:55 UTC
