### ISSUE TITLE
Walls under ruins etc have weird turf underneath

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33907] opened 2017-12-28 19:33 UTC
Round ID: 80961
Server revision compiled on: 2017-12-28
The following pull requests are currently test merged:
#33888: 'relic teleport no longer recursively calls itself' by optimumtact at commit f69125
Based off origin/master commit: 585674
Server tools version: /tg/station 13 Server v3.2.1.9
Server tools API version: 3.2.0.1

Weld White Ship wall and there's space underneath, not floor. When docked and welded, the Space doesn't become active and suck atmos but when the ship is moved, it starts working as normal. When in this inert state it cannot be replaced with rods and floor, only after the ship has been moved. Similar thing also happened in the Deep Bunker but I didn't test that one

**Comment by ninjanomnom** [comment] 2017-12-29 02:21
All shuttle turfs being space immediately underneath is expected and not a bug but I'll take a look at it being inactive.

We'll be able to have deeper turfing layers once I get the shuttles fully supporting the baseturf change to a list.

**Comment by Marflowerose** [comment] 2017-12-29 08:15
Expected? This must be a recent thing because previously it's been easy to weld off internal walls from the White Ship without suddenly having a hole to space underneath.

**Comment by ShizCalev** [comment] 2017-12-29 08:22
dupe of #33785

**Comment by ninjanomnom** [comment] 2017-12-29 10:00
No, different cause @ShizCalev

**Closed** 2017-12-30 16:09 UTC
Labels: Bug
