### ISSUE TITLE
the AI's foam dispensers only affect the tile they are on

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70256] opened 2022-10-01 23:11 UTC
## Round ID:
 [191561](https://scrubby.melonmesa.com/round/191561)

## Reproduction:

use a foam dispenser as the AI
it only affects it own tile. i could swear these used to affect a larger area right?

**Comment by msgerbs** [comment] 2022-10-02 16:27
Can confirm this occurs on multiple rounds, and yeah they definitely affected a wider range before.

**Comment by TemporalOroboros** [comment] 2022-10-02 20:43
90% certain this got clobbered in the foam rework. It was probably directly creating the foam object instead of using the helper and would have been relying on the default amount value for foam (~4 IIRC). It should be switched over to to the helper if it hasn't been already and the range bumped up to the old value.

**Comment by Baskett55** [comment] 2022-10-02 20:49
this has been broken since july, same issue here #68441

**Comment by TemporalOroboros** [comment] 2022-10-02 20:54
Replace line `code/game/machinery/ai_slipper.dm:40` with
```
var/datum/effect_system/fluid_spread/foam/foam = new
foam.set_up(3, holder = src, location = loc)
foam.start()
```
at 1 tab indentation.

**Comment by TemporalOroboros** [comment] 2022-10-02 21:16
The equivalent should be done for lines
- `code/game/objects/items/clown_items.dm:103`
- `code/modules/clothing/jobs/Plasmaman/civilian_service.dm:135`
- `code/modules/mob/living/simple_animal/bot/cleanbot.dm:358`
- `code/modules/mob/living/simple_animal/bot/hygienebot.dm:56`
- `code/modules/vehicles/cars/clowncar.dm:85`

There's also `code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm` in which a bunch of clowns try to spawn foam floods by dropping foam objects as loot. This needs a spawner object for foam floods to replace the dropped foam objects as it does not spread on its own anymore. Default range used to be 3.

**Comment by timothymtorres** [comment] 2022-10-03 05:21
Duplicate of #70256

**Closed by timothymtorres** 2022-10-03 05:21 UTC
Labels: Bug, Tested/Reproduced
