### ISSUE TITLE
You can't stop chat from autoscrolling by scrolling up

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52258] opened 2020-07-15 11:20 UTC
This is the literal biggest issue with TG, in my opinion. 

## Reproduction:

- Play highpop. 
- Something happens. 
- Scroll up to see what just happened. 

**Result:** Haha autoscroll goes BRRRR

**Expected result:** Same as on Goon. Chat freezes. Text stays completely still. You take a sip of your ice coffee and carefully read the chat at your own pace. Oh I see. Krokodil threw a grenade. 

Goon example:
https://www.twitch.tv/videos/679670356?t=02h36m49s

## Why this is a problem:
Example scenario:
- New player joins highpop. 
- They get flashed. Viva. 
- They get deconverted by sec 2 minutes later. 
- Shitsec: **"WHO FLASHED YOU????"** **"WHO"**     **"FLASHED"**     **"YOU?!!"**     
- They're confused. They scroll up and try to find it. Can barely read shit. Chat spasses out and keeps scrolling down because shitsec and others keep talking, making it tedious as fuck. 
- They say "I'm sorry I don't know". 
- Shitsec: **"WOW"**
- Shitsec:  **"YOU'RE NOW ON MY SHITLIST"**

New player leaves SS13 forever. 

#50036 somewhat related.

**Comment by Wayland-Smithy** [comment] 2020-07-15 11:30
> Play highpop.

Can you recall if it only happens after playing for a while too? I believe your chat buffer may just be filling up and starting to delete the oldest messages to make room for more, so your scroll position is not actually changing, the entire column of messages is always "sliding" upwards.

If that is the case you don't need to restart between rounds to clear it there is a button in the chat options gear.

**Comment by Angustmeta** [comment] 2020-07-15 11:35
I thought it always happened but from testing it seems it doesn't happen near roundstart as you say.

**Comment by Wayland-Smithy** [comment] 2020-07-15 11:38
Could be worth looking into making it work as intended even when old messages start getting removed by checking the before and after scroll position and moving it up the appropriate amount. Perhaps other codebases already do this? We already have detection for if you are not looking at the bottom of the chat window to display the "X New Messages" button.

**Closed** 2020-07-15 11:38 UTC

**Comment by Angustmeta** [comment] 2020-07-15 11:44
Yeah thanks. A solution like that would be nice but for now I just added a note about it somewhere on the wiki.
