### ISSUE TITLE
Unlimited Medical Gauzes

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#31432] opened 2017-10-07 22:21 UTC
see https://github.com/HippieStation/HippieStation/issues/1971

In-Game report from romanozvj:
Revision info:

General description of the issue
You can make unlimited gauzes in holodeck by taking from stack
What you expected to happen
When I threw a piece of gauze I took out of the stack, out of holodeck, it should've disappeared
What actually happened
it didn't
Steps to reproduce if possible
Take gauzes out of stack in medbay holodeck, throw them out of holodeck, turn off holodeck and they still exist

**Comment by ShizCalev** [comment] 2017-10-07 22:41
Duplicate of #26258

**Closed by ShizCalev** 2017-10-07 22:41 UTC
