### ISSUE TITLE
Bone Axe Butchering and Tendril Butchering Issues

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#37723] opened 2018-05-07 07:26 UTC
[Round ID]: # Occured in multiple rounds on Bagil and Sybil

After playing a few rounds as an ash walker I noticed that bone axes failed to butcher any lavaland mobs. When attempted it would appear to work as normal with the correct text and a progress bar, but upon ending the corpse would not butcher. Spears worked as intended.

Next I noticed some issues with the ashwalker tendril's butchering. First it doesnt appear to drop any gibs, this is an issue because the grubbucks nearby cannot eat and produce any milk for healing.

Second it doesn't appear that butchering a goliath with the tendril will ever drop goliath plates, although it does drop goliath meat and bones. Regular butchering produced plates as expected. Butchering a watcher drops tendrils correctly, and butchering humans produced correct heads and organs.

**Comment by Therapist1** [comment] 2018-05-11 02:11
bump

**Comment by ShizCalev** [comment] 2018-05-17 03:15
Fixed by #37850

**Comment by PKPenguin321** [comment] 2019-07-20 23:42
Unable to reproduce

**Closed** 2019-07-20 23:57 UTC
Labels: Needs Reproducing
