### ISSUE TITLE
Virology doesn't work

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#46892] opened 2019-10-04 23:37 UTC
Issue reported from  Round ID: 120714 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488

#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit d8e48494db
#46383: 'UNKNOWN' by UNKNOWN at commit 94b776f043
#46640: 'UNKNOWN' by UNKNOWN at commit 5613476f27

Multiple attempts to make a Radioactive resonance, tissue hydration, eternal youth, inorganic biology, fever (neutered), itching (neutered) virus manifest in both the crew and monkies after verifying that no one had a stealth virus to suppress it yielded no results at all.
Additional attempts were made without inorganic biology, and results were no different. 

Fungal tuberculosis and vaccines made for fungal tuberculosis were functioning normally.

**Comment by ATH1909** [comment] 2019-10-05 06:46
How exactly were you exposing people to the virus?

**Comment by 81Denton** [comment] 2019-10-05 09:20
I can confirm this, OP was trying with syringes, sprays, hell, even an IV drip full of virus juice. I'm gonna test if this occurs sporadically or all the time.

**Comment by 81Denton** [comment] 2019-10-05 09:53
I can't reproduce this on Bagil round 120746 with the same test merges. Seems to have been a one off issue, ping me if it happens again.

**Comment by ArcaneDefence** [comment] 2019-10-05 23:47
Encountered the exact same problem with the same virus mix;

#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit d8e48494db
#46383: 'UNKNOWN' by UNKNOWN at commit 94b776f043
#46640: 'UNKNOWN' by UNKNOWN at commit 5613476f27

 Round ID: 120790 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])
Reporting client version: 512.1488

Have attempted ingesting the virus via pills produced from a pandemic, drinking from the bottle directly, and injecting myself, after putting my blood into a pandemic to verify that once again, I have no stealth virus- No results.

![1](https://user-images.githubusercontent.com/51932756/66262069-a91ef600-e796-11e9-8f84-277eedd2572f.png)
![2](https://user-images.githubusercontent.com/51932756/66262070-a91ef600-e796-11e9-8b7e-e6f131016231.png)

Same attempts were performed on the monkey in the chair, which also yielded no results. 

Really have no idea as to what might cause this, but both rounds were nuclear operatives, in the first I confirmed there was active fungal TB. In this second round I only saw someone call out fungal TB once over common, which I could not confirm, even after ghosting.

**Comment by ATH1909** [comment] 2019-10-06 08:45
Maybe my recent on_stage_change changes screwed things up?

Try a different virus with just sneezing and inorganic biology in it.

**Comment by PKPenguin321** [comment] 2019-10-06 19:50
Dupe of https://github.com/tgstation/tgstation/issues/46408

**Closed by PKPenguin321** 2019-10-06 19:50 UTC
Labels: Bug
