### ISSUE TITLE
Stacks of sheets don't split normally and can be duplicated

### ISSUE THREAD

**Issue by Booji-Boy** [tgstation/tgstation#24071] opened 2017-02-13 18:11 UTC
**Revision:** 2017-02-13 8b4799254f4e03fd79605acea3ea48187876626e 

**Problem Description:** Stacks of sheets cannot be split normally and duplicate themselves.

**What did you expect to happen?:** I expected one piece of plasma/metal to be taken from the stack and put into my other hand, or the entire stack to be transferred to my other hand without increasing. One or the other.

**What happened instead?:** The entire stack of plasma/metal switched to my other hand and the amount was increased by one.

**Why is this bad/What are the consequences?:** This bug makes it incredibly annoying to take a few pieces of plasma/metal out of a stack, and also makes it so you can have infinite amounts of solid plasma/metal.

**Steps to reproduce the problem:** Pick up a piece of solid plasma or metal. Examine it and take note of the amount. Switch hands and click the piece of solid plasma/metal, swapping it to your other hand. Examine it again, note that the amount of sheets in the stack has increased by one.

**Possibly related stuff:** You can split the plasma stack in a variety of ways. I usually make a statue out of it and then break the statue. However, it's still a pretty big inconvenience and unintended advantage. This bug has been around for at least a few days now, so I don't think it's based on anything round specific. I originally thought this was only plasma, as I didn't try it with anything else, but it also does the same thing with metal sheets. I assume it will do the same thing with other materials, too.

Also, the abundance of solid plasma makes it very easy to create humongous fires.

**Comment by lzimann** [comment] 2017-02-13 18:28
Dupe of #24050

**Closed by lzimann** 2017-02-13 18:28 UTC
