### ISSUE TITLE
Mech clamps no longer crush people when on harm intent, instead it just pushes

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#56583] opened 2021-02-02 01:33 UTC
Round ID: [155494](https://scrubby.melonmesa.com/round/155494)

Reproduction:
try to use a hydraulic clamp to crush someone, it doesn't work anymore, it just pushes them.

**Comment by necromanceranne** [comment] 2021-02-07 05:55
This is actually working as of right now, clamping when combat mode is on and pushing when combat mode is off. I tested this and was not able to reproduce this bug. So I'm closing as a result.

![clampharmtest](https://user-images.githubusercontent.com/40847847/107137944-3531c680-6965-11eb-850e-22c1d59732dd.png)

**Closed by necromanceranne** 2021-02-07 05:55 UTC
