### ISSUE TITLE
Mindshield lockboxes start unlocked, but visually appear locked

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#37884] opened 2018-05-17 05:22 UTC
Tested on a recent clone of the server

At round start, the mindshield boxes in armory have a red dot indicating that they are locked, but they are actually unlocked. If you use a security access ID on one, you get the message that they have been locked, and retains the locked icon. Using your id again gives you an unlock message and changes the icon to the unlocked version.

**Comment by YPOQ** [comment] 2018-05-17 05:32
Duplicate of #37086

**Closed** 2018-05-17 05:38 UTC
