### ISSUE TITLE
Golem Ship ORM unable to accept materials inserted from the correct side.

### ISSUE THREAD

**Issue by AuspiciosPerson** [tgstation/tgstation#58344] opened 2021-04-12 04:35 UTC
Reporting client version: 513.1536

## Round ID:
[160106](https://scrubby.melonmesa.com/round/160106)

## Testmerges:
- [[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing](https://www.github.com/tgstation/tgstation/pull/58313)

## Reproduction:
Clueless of a way to reproduce, Golem's ship ORM decided to stop accepting materials from all sides after working fine for several minutes. (it could be inserted manually, however it won't reward any mining points.) aswell had a power issue that was solved by a admin online.

**Comment by ArcaneDefence** [comment] 2021-04-12 06:02
The only issue I can possibly see with this is if you use the blueprints provided to create a new area over the one it starts as, since it's `/area/ruin/powered/golem_ship`.

In the event that you do so you could actually build a powered APC in your new defined area and fully commit to utterly destroying the free power you get from being in that powered golem ship area. 
Additionally, you can screwdriver an ORM's panel open then alt click on it to change the I/O settings.

**Comment by ArcaneDefence** [comment] 2021-04-12 18:24
Since I'm still not seeing anything beyond the power this is just a duplicate of https://github.com/tgstation/tgstation/issues/44927

**Closed by ArcaneDefence** 2021-04-12 18:24 UTC
