### ISSUE TITLE
Celestial gate spark spamming

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#36653] opened 2018-03-23 08:11 UTC
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 85405

Server revision compiled on: 2018-03-22

The following pull requests are currently test merged:
#36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit f025fb

Based off origin/master commit: d9cdd5

Revision: b63b1db3ce074d9803b61807b3635049335300b1

Server tools version: /tg/station 13 Server v3.2.1.15

Server tools API version: 3.2.0.2

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

In a recent cult round, I was fixing a toxins leak with air scrubbers when two celestial gates a tile apart from each spawned, the air scrubber I was moving got pushed into the gate, then the sparks from the gate would enter the other gate and in turn create more sparks. Within seconds both gates were spewing sparks in the quad digits.

1. Have two celestial gates near each other.
2. Push an object through one(in my case it was an air scrubber.

Screenshot:

![dreamseeker_2018-03-23_03-59-54](https://user-images.githubusercontent.com/8280713/37818112-6263ad66-2e4f-11e8-9baa-7a68851b392a.png)

**Comment by AnturK** [comment] 2018-03-23 08:19
Duplicate of #36652

**Closed by AnturK** 2018-03-23 08:19 UTC
