### ISSUE TITLE
Pirates start off with random names & no pirate speak

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#63485] opened 2021-12-18 22:06 UTC
## Reproduction:
spawn in as a pirate and be named with a random name that doesnt involve pirate titles, also find out that you don't know piratespeak

____
- [ ] did armhulen test his PR?

**Comment by MrMelbert** [comment] 2021-12-23 01:29
They also don't gain antag datums.

**Comment by timothymtorres** [comment] 2021-12-28 10:01
Duplicate of #63662

**Closed by timothymtorres** 2021-12-28 10:01 UTC
Labels: Bug
