### ISSUE TITLE
Advanced janitorial eqipment can't be accessed in any way

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35221] opened 2018-02-02 11:36 UTC
Custodial Closet doesn't exactly have a depertment protolathe, and the RnD protolathe does not have access to those designs. This means the crew is completely incapable of getting light replacers, floor buffers, advanced mops, or trashbags of holding.

This would be fixed by RnD getting back access to stuff like that, but I digress.

**Comment by Potato-Masher** [comment] 2018-02-02 11:45
These things are printed at the service protolathe that's usually in between the kitchen and hydroponics. It kinda odd you can't access it as a janitor due to its location, but the stuff is there.

**Comment by Potato-Masher** [comment] 2018-02-02 11:45
So, yes, they can access these things. The only issue is ease of access.

**Comment by AnturK** [comment] 2018-02-02 11:59
Duplicate of #35218

**Closed by AnturK** 2018-02-02 11:59 UTC
