### ISSUE TITLE
Cant eat cooked food

### ISSUE THREAD

**Issue by BumkenBoy** [tgstation/tgstation#58635] opened 2021-04-23 13:44 UTC
## Round ID:

[160850](https://scrubby.melonmesa.com/round/160850)

## Reproduction:

Cook food
Try to eat
Punch yourself with food

Nothing else i really know, maybe when cutting up bread and making slices of bread makes some of them not work?

**Comment by dragomagol** [comment] 2021-04-23 18:04
Were you on combat mode?

**Comment by ArcaneDefence** [comment] 2021-04-23 22:34
Duplicate of https://github.com/tgstation/tgstation/issues/55375

**Closed by ArcaneDefence** 2021-04-23 22:34 UTC
Labels: Bug, Needs Reproducing
