### ISSUE TITLE
Bug with cell chargers and bluespace power cells

### ISSUE THREAD

**Issue by cykl3** [tgstation/tgstation#53318] opened 2020-08-30 01:45 UTC
Issue reported from  Round ID: [145306](https://scrubby.melonmesa.com/round/145306) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

![image](https://user-images.githubusercontent.com/70416968/91649324-67471000-ea38-11ea-80c1-cbf579c4132c.png)
After removing a fully charged bluespace powercell from the cell charger the sprite of the bluespace powercell still remains on the charger.

**Comment by TheVekter** [comment] 2020-08-30 03:39
This is an oooooold bug that has to do with overlays or some shit. I think it happens with any cell, not just bluespace ones.

**Comment by timothymtorres** [comment] 2021-11-12 11:37
Duplicate of #48259

**Closed by timothymtorres** 2021-11-12 11:37 UTC
Labels: Bug
