### ISSUE TITLE
Wawastation topside Cargo Shuttle I AM ERROR tiles

### ISSUE THREAD

**Issue by BHat0451** [tgstation/tgstation#84758] opened 2024-07-07 19:29 UTC
## Issue Summary
The space the Z-Level above the Wawastation's Cargo Shuttle is a mess of "SHIT BE FUCKED Fix ME!!!!" I AM ERROR blocks. This is likely an issue.

## Round ID:
[231764](https://scrubby.melonmesa.com/round/231764)

## Reproduction:
Go to top floor of Wawastation's Cargo hold. IF the I AM ERROR is not present, possibly call and re-send cargo shuttle.

![tgStation Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE  VivI's Swan Song XV 2024-07-07 142240](https://github.com/tgstation/tgstation/assets/35274992/9b382e89-1b30-4f66-8711-8e0b5b052f26)

**Comment by Sadboysuss** [comment] 2024-07-07 19:54
shit be fucked.
dupe of https://github.com/tgstation/tgstation/issues/84597

**Closed by Sadboysuss** 2024-07-07 19:54 UTC
