### ISSUE TITLE
Instant Summons can remove MODsuit backpack but keep MODSuit on

### ISSUE THREAD

**Issue by AxolotlGod** [tgstation/tgstation#65845] opened 2022-04-01 01:37 UTC
Reporting client version: 514.1568

## Round ID:
[180864](https://scrubby.melonmesa.com/round/180864)

## Testmerges:
- [Human code refactor](https://www.github.com/tgstation/tgstation/pull/65839)
- [Resprites Clown](https://www.github.com/tgstation/tgstation/pull/65841)

## Reproduction:
Instant summons any item. Put it in your modsuit backpack. When you summon it while it is in your backpack, the backpack will appear in your hands. You can drop the backpack and still have the modsuit armor on, while losing any functionality of the suit. Found this while playing miner, pretty easy to find if you get the instant summons book from a tendril.

**Comment by Fikou** [comment] 2022-04-02 01:13
dupe of https://github.com/tgstation/tgstation/issues/65226

**Closed by Fikou** 2022-04-02 01:13 UTC
