### ISSUE TITLE
Moths are STILL flashproof

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43530] opened 2019-04-07 10:30 UTC
https://github.com/tgstation/tgstation/issues/43255

This issue was reported over _2 weeks_ ago, and has ruined numerous rev rounds since its creation. I'm saying this as a moth who called out two different revheads who tried and failed to flash me (resulting in their swift lynching) in a single rev round, by the way.

C'mon, guys.

**Comment by ATH1909** [comment] 2019-04-07 10:44
https://github.com/tgstation/tgstation/pull/43261
Epic.

**Comment by ShizCalev** [comment] 2019-04-07 20:44
first part of my move started yesterday, all my things (including my primary comp) will be in storage till i'm in a more permanent location later this month.

Code wise the fix was completed in that PR, so if someone wants to resurrect it with sprites, go ahead.

**Comment by ShizCalev** [comment] 2019-04-07 20:45
Duplicate of #43255

**Closed by ShizCalev** 2019-04-07 20:45 UTC
Labels: Bug, Priority: High
