### ISSUE TITLE
2 Nightmares Cannot Exist In Same Round

### ISSUE THREAD

**Issue by dessysalta** [tgstation/tgstation#72308] opened 2022-12-28 00:30 UTC
Reporting client version: 514.1585

## Round ID:
[197134](https://scrubby.melonmesa.com/round/197134)

## Reproduction:

1. Have 'nightmare' midround occur
2. Have someone spawn as a nightmare (live/dead doesn't matter)
3. Have a second 'nightmare' midround occur some time later
4. Second nightmare does not spawn regardless of initial nightmare's status (unless no one was picked for the initial nightmare midround)

**Comment by dessysalta** [comment] 2022-12-28 00:53
> haven't glanced at the runtimes but probably the same as #69327

This is probably correct. Let me know if they're for sure and I'll close it.

**Comment by Mooshimi** [comment] 2023-04-01 01:33
Looked, yes this is what caused this in that round. 

```
Thrown by generate_ruleset_body (/datum/dynamic_ruleset/midround/from_ghosts/nightmare/generate_ruleset_body) at dynamic_rulesets_midround.dm, line 563

Source: Nightmare (/datum/dynamic_ruleset/midround/from_ghosts/nightmare)
```

**Comment by Mooshimi** [comment] 2023-04-01 01:34
Duplicate of #69327

**Closed by Mooshimi** 2023-04-01 01:33 UTC
