### ISSUE TITLE
CTF allows spawncamping.

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#43552] opened 2019-04-08 15:14 UTC
Issue reported from /tg/Station Terry [EU] [100% LAG FREE] [New-Dedi]

Reporting client version: 512

Stand here
![image](https://user-images.githubusercontent.com/38219334/55735482-b21a4f00-5a21-11e9-9513-9a18820692e7.png)

You can now shoot through spawn protection and kill people that just spawned.

**Comment by HomocidlePancakes** [comment] 2019-04-08 17:24
No you can’t. You can get 2 shots in max

**Comment by PKPenguin321** [comment] 2019-04-08 18:00
Not a bug

**Comment by Teepeepee** [comment] 2019-04-08 20:30
don't reveal the ctf meta bro, noobs will catch up

**Comment by PKPenguin321** [comment] 2019-04-08 20:33
@ExcessiveUseOfCobblestone just close the issue

**Closed** 2019-04-09 06:08 UTC
Labels: Not a bug
