### ISSUE TITLE
Plumbing devices transfer one reagent at a time

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#84699] opened 2024-07-06 00:42 UTC
## Issue Summary
Instead of taking an even split of the stored reagents, plumbing will prioritize emptying a single reagent.

## Round ID:
Local on [master](https://github.com/tgstation/tgstation/commit/a13d142badbcdd9663bbd650c81495f2aa8657d8), no runtimes

## Reproduction:
Hook up an input gate to a botany tray, as a general example 
Transfer a beaker with 25 of reagent A and 25 of reagent B into the input gate, with the beaker set to the full 50 units
Observe the tray only filling with reagent A

**Comment by SyncIt21** [comment] 2024-07-06 05:01
This is the new expected behabiour because the tray does not have enough space for both reagents so only the 1st one got transferred.

The proportional method of transferring reagents has been removed to prevent floating errors and the round robin method has been brought back.

See #84405

**Comment by FlufflesTheDog** [comment] 2024-07-06 05:22
The problem is trying to use this in an automatic way. There's no meaningful way to use plumbing for botany with more than one chemical anymore, because you will never reasonably be able to get exactly enough to fill up one tray at a time. The example with the input gate is not a practical example, because in that case you'd be better off just filling the trays manually.

**Comment by zoomachina** [comment] 2024-07-06 05:52
New expected behavior (tm) from a fix pr

**Comment by SyncIt21** [comment] 2024-07-06 06:18
> There's no meaningful way to use plumbing for botany with more than one chemical anymore, because you will never reasonably be able to get exactly enough to fill up one tray at a time.

You can use multiple chemicals it's just that the receiver should have enough space to accommodate them all. You Don't need to exactly fill it, I never mentioned that was a requirement.

Unfortunately there is no fix here. As you said this example is not practical and people generally fill up trays/beakers from "output gates"(which don't have this problem) so that's your only option.

If I bring back the old behavior then floating point erros would be back so this is maximum I can do.

> New expected behavior (tm) from a fix pr

I have been fully transparent about the drawbacks of my PR, nothing was hidden.

**Comment by FlufflesTheDog** [comment] 2024-07-06 06:36
> You can use multiple chemicals it's just that the receiver should have enough space to accommodate them all. You Don't need to exactly fill it, I never mentioned that was a requirement.

Not being able to go over the capacity of a tray effectively means your only option is to exactly fill it. Which I don't think is at all possible with the new mechanics.

> people generally fill up trays/beakers from "output gates"

huh?
If you're setting up a plumbing factory for botany fertilizers (that's the actual use case that led me to noticing the change) then you're not using gates, you're plumbing reaction chambers directly to trays.

**Comment by SyncIt21** [comment] 2024-07-06 07:03
> Not being able to go over the capacity of a tray effectively means your only option is to exactly fill it. Which I don't think is at all possible with the new mechanics.

I think you misunderstood what I said. What I meant was if you're tray has capacity for only 25u reagents then make only 25u reagents or less in your reaction chamber and you will get all reagents in your tray. 

In no circumstance can you put more reagents into the tray than it's capacity. That's impossible for any reagent holding device

> huh?
> If you're setting up a plumbing factory for botany fertilizers (that's the actual use case that led me to noticing the change) then you're not using gates, you're plumbing reaction chambers directly to trays.

Right I misunderstood what you we're trying to do my bad. But like i said above make sure the amount of reagents you make in your reaction chamber don't exceed the output tray capacity and you won't have any problems.

This isn't a bug because I made it clear this would happen if you made excess reagents. Since players have exact control over how much reagents reaction chambers can take in they can prevent this from happening.

**Comment by FlufflesTheDog** [comment] 2024-07-06 07:36
> I think you misunderstood what I said. What I meant was if you're tray has capacity for only 25u reagents then make only 25u reagents or less in your reaction chamber and you will get all reagents in your tray.

I did not. This is supposed to be an automated system, as in constantly making more.
Say you go through the effort of making sure a reaction chamber makes exactly 20 units of your fertilizer mix, in order to exactly fill up a tray. As soon as those trays start processing, they'll consume 0.5 units every cycle, and just stop requesting the second reagent in the new batch that was made. And alternatively, good luck feeding 20 trays 0.5 units at a time to avoid going over their capacity

> This isn't a bug because I made it clear in my PR this would happen if you made excess reagents. Since players have exact control over how much reagents reaction chambers can take in they can prevent this from happening.

I appreciate the logic, it isn't like you tried to sneak this through without people noticing. But I don't think it's ever that simple. Gleaming the exact consequences of a rather technical PR such as that is neigh impossible, and just because the behavior is expected, doesn't mean it's a good choice- though of course it isn't up to me to say if that's the case here.

**Comment by SyncIt21** [comment] 2024-07-06 08:01
> But I don't think it's ever that simple

Unfortunately you are right. What I did was bought back a behavior that has been around for years so this bug has been around since plumbing became a thing(like 5 or more years ago lol).

I'm surprised you're the 1st one to report on this actually.

It's a trade off between rounding errors and missing reagents and I guess it's boils down to what players prefer more at this point.

Right now you're best bet is to make less reagents to delay the problem from occurring as much as possible before the inevitable until someone comes up with a better "reagent transfer algorithm"

**Comment by SyncIt21** [comment] 2024-07-06 08:29
Ok after some thought I think we can fix this problem but only for botany hydroponic trays(actually I think this is the only machine that has this problem).

Because trays request only 0.5u of reagents per cycle it ends leaving out other reagents if their volumes exceeds 0.5u in the ducts.

I have 2 options.
A)Increase the input rate. Make it 10u(like general plumbing mechs). But this would cause growth instability and other plant problems cause we are dealing with volatile chems
B)Resort back to "proportional transfer" but only for botanic trays. The small floating point inconsistencies that will occur because of it are "insignificant" so it won't be a problem and we will get all reagents.

I'll go with option B. Just to be clear you are talking about "Hydroponics trays" as being the main issue here right?

**Comment by SyncIt21** [comment] 2024-07-06 16:53
> Only downside would be that you can't really use a storage tank to buffer stuff for the tray since the slow drain would propagate to that, and have it draw unevenly as well

This isn't a problem actually. Even though the storage tank uses "round robin" to take in reagents from the ducts, the botany trays still will draw reagents from the tank via "proportional transfer".

Since the tanks have high capacity they don't have the problem of taking in small reagents nor running out of space so the problems of missing reagents will "very rarely happen" inside tanks so you should be able to use it with trays with no issues.

**Comment by FlufflesTheDog** [comment] 2024-07-06 17:22
I don't know for sure but I don't think that's how it'll play out?
Generally, the tank will fill up pretty quickly. Trays don't use a lot, especially since people might not immediately be growing plants in every tray. Once it's full, it'll stop pulling evenly. And even before then, you might have it pull all of reagent A, then a tray will pull from the tank which only has part of the mix, and then the tank will fill with reagent B which will now be missing from the tray.

But, the counter argument is that trays don't use a lot, so you don't *really* need storage. It's perfectly workable with a direct connection to a chamber.

**Closed** 2024-07-08 20:11 UTC
