### ISSUE TITLE
ai survive objective fails regardless of completion.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#31025] opened 2017-09-26 04:21 UTC
i did not shunt or die.
i believe that the survival objective considers being a silicon a failure.

**Comment by AnonymousNow** [comment] 2017-09-26 04:30
I think this is a dupe, but the notion of being alive as a silicon is an interesting one to consider.

**Comment by ShizCalev** [comment] 2017-09-26 08:02
Issue is here
https://github.com/tgstation/tgstation/blob/5b62b51e24d06183ca0764728c8e56af811ab4cb/code/game/gamemodes/objective.dm#L25

Also see #14564

**Comment by BeeSting12** [comment] 2017-09-26 12:53
#30950
#30959
@pubby

**Comment by Cyberboss** [comment] 2017-09-26 16:08
Duplicate of #30950

**Comment by Cyberboss** [comment] 2017-09-26 16:08
#30959 Should have fixed this

**Comment by DoctoreMad** [comment] 2017-09-26 19:20
I believe the PR updated the text to "survive" which is what the OP used. 
Let us guess that the PR itself didn't work in first place.

**Comment by pubby** [comment] 2017-09-26 19:53
It should fix it the server just hasn't updated yet.

**Comment by Cyberboss** [comment] 2017-09-26 19:55
Duplicate of #30950

**Closed by Cyberboss** 2017-09-26 19:55 UTC
