### ISSUE TITLE
Emitter shots randomly disappear

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#32781] opened 2017-11-15 19:14 UTC
It is no longer possible to do emitter loop memes I am sad, is this intentional or a bug?

**Comment by JJRcop** [comment] 2017-11-15 22:33
At the moment all projectiles have a default range of 50 tiles
https://github.com/tgstation/tgstation/blob/98542b359dc22daff7fcf5630c86e0fc6dfcd579/code/modules/projectiles/projectile.dm#L58

This is not overridden in emitter beams, but it could be.

**Comment by Bawhoppen** [comment] 2017-11-16 00:43
Isn't this an ancient bug actually?

**Comment by DaxDupont** [comment] 2017-11-16 00:44
@Bawhoppen Nah, this only seemed to happen after the overhaul.

**Comment by Armhulen** [comment] 2017-11-16 17:54
don't emitter loops break the game anyways? not a bug close it

**Comment by JJRcop** [comment] 2017-11-16 18:16
I don't want to PR this but you can if you want: https://github.com/JJRcop/tgstation/tree/patch-8
If you do PR it, it didn't come from me. I may have committed it, but I won't be responsible.

**Comment by Armhulen** [comment] 2017-11-21 17:21
@ShizCalev this is not a bug, it's there so people can't use reflectors to crash the game i think

**Comment by vuonojenmustaturska** [comment] 2018-03-03 00:01
not a bug

**Closed by vuonojenmustaturska** 2018-03-03 00:01 UTC
Labels: Not a bug
