### ISSUE TITLE
Runed metal on normal girder deletes the girder

### ISSUE THREAD

**Issue by uraniummeltdown** [tgstation/tgstation#27138] opened 2017-05-11 05:20 UTC
Using runed metal on a regular girder starts to add plating as if building a runed wall, but the wall just disappears, no runtime

**Comment by bgobandit** [comment] 2017-05-11 15:44
dupe of https://github.com/tgstation/tgstation/issues/14215 which I thought I fucking fixed, GUESS NOT

did anyone fuck with cult shit to make this not my clowning

**Closed** 2018-03-02 17:22 UTC
Labels: Bug
