### ISSUE TITLE
Cyborgs have shoe walking sounds

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40173] opened 2018-09-08 12:46 UTC
Issue reported from  Round ID: 93608 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Cyborgs have wheels not shoes and/or float like mediborgs.

**Comment by 81Denton** [comment] 2018-09-08 17:30
Dupe of #39970

**Closed** 2018-09-08 21:09 UTC
