### ISSUE TITLE
MMIs take damage weirdly

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#31970] opened 2017-10-21 00:04 UTC
I had an MMI from a blown borg, and at some point it took damage (I think from another blown borg)

It was talking to me normally and it all seemed fine until I tried putting it in a new borg shell, at which point the game told me it was dead and there would be no point

I took the brain out of the MMI and put it back in and this killed it, preventing it from talking about giving the MMI little X eyes

**Comment by RandomMarine** [comment] 2017-10-21 06:23
Dupe of #31843

**Comment by AnturK** [comment] 2017-10-21 10:07
Duplicate of #31843

**Closed by AnturK** 2017-10-21 10:07 UTC
Labels: Bug
