### ISSUE TITLE
Player Panel isn't working with certain actions

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#30721] opened 2017-09-14 02:04 UTC
I have debug admin hrefs enabled. Clicking things such as mute, get, or send to lobby yields no action nor a runtime/feedback.

Other actions such as forcesay work.

**Comment by Poojawa** [comment] 2017-09-14 04:16
transformation, heal, kick/ban/send to lobby All work as well.

**Comment by Poojawa** [comment] 2017-09-14 06:23
oh. Jay should totes look a few touches down. but yee

**Comment by Cyberboss** [comment] 2017-09-14 13:17
Duplicate of #30687

**Closed by Cyberboss** 2017-09-14 13:17 UTC
