### ISSUE TITLE
Space, the final fr- wait we're on a planet.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33021] opened 2017-11-23 03:24 UTC
![image](https://user-images.githubusercontent.com/16315400/33157948-eef27422-cfd3-11e7-86a0-382739359d43.png)

![image](https://user-images.githubusercontent.com/16315400/33158202-ec9a7948-cfd5-11e7-9077-e6b40681b093.png)

**Comment by ShizCalev** [comment] 2017-11-23 03:58
Duplicate of #32990

**Closed by ShizCalev** 2017-11-23 03:58 UTC
Labels: Map Issue
