### ISSUE TITLE
demonic frost miner not reliably spawning still

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#71228] opened 2022-11-12 15:11 UTC
Reporting client version: 514.1589

## Round ID:
[194189](https://scrubby.melonmesa.com/round/194189)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)

## Reproduction:
he wasn't here this round!

**Comment by msgerbs** [comment] 2022-11-12 18:20
Duplicate of #62901. Issue lies with multi-z ruin code not being able to check whether any attached Z-levels are able to spawn in the chosen location.

**Closed by msgerbs** 2022-11-12 18:20 UTC
