### ISSUE TITLE
Hereditary manifold sickness patients can be allergic to sansufentanyl

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#76063] opened 2023-06-15 01:38 UTC
## Reproduction:

1. Have allergies
2. Have hereditary manifold sickness

![image](https://github.com/tgstation/tgstation/assets/86855173/0ca7f695-bdd0-426f-86b8-55284cdb0764)

**Comment by MrMelbert** [comment] 2023-06-15 04:12
Dupe of #75776 , I think they rolled a fix into their pr but it's yet to merge

**Closed** 2023-06-15 04:13 UTC
