### ISSUE TITLE
Mechs can move into their own mining lasers

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#55683] opened 2020-12-22 05:39 UTC
Reporting client version: 513.1538

## Round ID:
[152666](https://scrubby.melonmesa.com/round/152666)

## Testmerges:
- [The Great Radio Rework: NTNET Part 1 of many.](https://www.github.com/tgstation/tgstation/pull/54462)

## Reproduction:

Grab a ripley (or clarke), put a mining laser on it, move forward and fire forward. you'll be hit by the laser

**Comment by dragomagol** [comment] 2020-12-22 06:31
Duplicate of #55641

**Closed by dragomagol** 2020-12-22 06:31 UTC
