### ISSUE TITLE
Whiteship can count as marooned if launched right before evac

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#36161] opened 2018-03-05 00:08 UTC
Happened locally, revision 7ea6424126ce677438a49a92cae20d29415d5d36.

If you launch the whiteship right before the emergency shuttle's ignition, the whiteship will arrive at its destination (such as the station) and count as marooned rather than entering endround transit and counting as escaped.

**Comment by ninjanomnom** [comment] 2018-04-06 02:49
Duplicate of #28432

**Closed by ninjanomnom** 2018-04-06 02:49 UTC
Labels: Bug
