### ISSUE TITLE
Bags of Holding and Reaching Z-Level One

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#51711] opened 2020-06-17 23:21 UTC
## Testmerges:
#51412 
#51515 

## Reproduction:
Done on Delta station,
1. put a teleporter beacon on the white ship, having the ship docked at the station
2. wear a bag of holding
3. go through a teleporter to the white ship, with the bag of holding on
4. somehow end up on z-level one, unable to escape

**Comment by ATH1909** [comment] 2020-06-17 23:43
what is z-level 1?

**Comment by Paxilmaniac** [comment] 2020-06-18 04:08
i think it's centcom, if i remember correctly

**Comment by Doosteroni** [comment] 2020-06-18 10:33
If you go by the wiznerd ship some funhater put a hyperspace border there so being inescapable is inaccurate

**Comment by Paxilmaniac** [comment] 2020-06-26 02:31
i was able to reproduce the bug easily, just teleport to a shuttle in motion while wearing a boh, and you will be teleported to places you arent supposed to go

**Comment by Paxilmaniac** [comment] 2020-07-01 12:06
cv cvdbvbvbdvbfdb cd, v bbscsbddbdvbfscccfabbd. d cd vdbdfdbcbcbd vdvvdbccsvbd cdc d b sex dbbcbbvbd sf vbbv dbddfc d s a d decreed s dds!,;?:! d vf dc ccc ssd d ssd dvsbdnd sddd dds d cdc cdd dad dds f dad dad zac feed  cd ds ssd dad dvbcc db bb dec d d versed cdc dsv deed x frr sfc d cds dress ssd dad d dad dress dressed d cds decreed cdc d d c cdc decreed c dads ds dds c cds d decreed dads dress dress d d  dads drxxxdd BCZcnn

**Comment by GravitronBlue** [comment] 2020-07-12 15:33
Possibly related to #45529

**Comment by Fikou** [comment] 2021-03-22 09:02
Duplicate of #45529

**Closed by Fikou** 2021-03-22 09:02 UTC
Labels: Bug, In Game Exploit
