### ISSUE TITLE
Attack animations can be visible through walls using mesons

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49755] opened 2020-03-06 06:22 UTC

**Comment by Taylorkills2** [comment] 2020-03-06 19:38
To add to this, I'm pretty sure it doesn't require night vision, and there are some other animations that are visible, really any animations using the in-hand sprite of an item.

**Comment by timothymtorres** [comment] 2022-08-21 23:05
Duplicate of #39799

**Closed by timothymtorres** 2022-08-21 23:05 UTC
Labels: Bug
