### ISSUE TITLE
Fire Breath Requires Ability to Speak

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#62697] opened 2021-11-09 08:53 UTC
Reporting client version: 514.1569

As a mime you can't use fire breath. I'm assuming this applies to mute people as well considering that the message you receive when you try to use the ability are "You can't get the words out!"

## Round ID: 
[172754](https://scrubby.melonmesa.com/round/172754)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
- Play as the mime, get fire breath from some lizard, and then try to use it. The fire breath I was using had an energetic chromosome applied as well.

**Comment by timothymtorres** [comment] 2021-11-09 10:19
This is a dupe of #54862 but I'm going to leave it open for now.  Pretty sure Fire Breath is a spell and any spell needs to be spoken outloud to work.

**Comment by SuperNovaa41** [comment] 2021-11-09 18:22
You can probably fix this, and the other issue with whatever method cultist speak uses

**Comment by optimumtact** [comment] 2021-11-10 05:30
the vow of silence is strong

**Closed** 2022-02-10 03:24 UTC
Labels: Consistency Issue
