### ISSUE TITLE
Sleepers cause people to hear emotes globally

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#62709] opened 2021-11-09 20:29 UTC
## Round ID:
[172738](https://scrubby.melonmesa.com/round/172738)

## Testmerges:
 [Revert "Locker based combat, evolved. (#60000)" #62558](https://github.com/tgstation/tgstation/pull/62558)

## Reproduction:
1. Be a changeling(unsure if necessary)
2. Get your powers(I believe in this case, it was the x-ray eyes, armblade, lesser form, transform sting, fleshmend.)
3. Turn on your x-ray eyes.
4. get put into a sleeper by someone else.
5. immediately walk out of sleeper.
6. now you can hear as if you had 'see all emotes' toggled on in your game prefs, and are a ghost.

During this round, Nianjilical spawned sleepers that could only add skeleton mutation toxin to the patient. I didn't get this otherworldly ghost vision until after someone forcibly put me in one and I immediately got out of it. I'm not sure if this is a one-off fluke or not, but given the rarity of sleepers this probably isn't an extremely important issue.

**Comment by TheBonded** [comment] 2021-11-09 20:49
Are you sure you were hearing all emotes, or just ones from the area directly around the sleeper?

As far as I can tell this round occurred about 17 hours ago (statbus and scrubby use UTC as their time zone), which was a few hours before https://github.com/tgstation/tgstation/pull/62632 was merged, which as far as I can tell should have fixed this. This would also make this a duplicate of https://github.com/tgstation/tgstation/issues/60719.

**Comment by timothymtorres** [comment] 2021-11-10 01:43
This was the same round and issue as #62693.  They retested after the PR was merged and it appears to have been fixed.

**Closed by timothymtorres** 2021-11-10 01:43 UTC
