### ISSUE TITLE
Infinite Floortiles

### ISSUE THREAD

**Issue by stonedDiscord** [tgstation/tgstation#54196] opened 2020-10-05 11:47 UTC
The floorbot can create floortiles without a catwalk.

Removing these creates a floortile item but doesn't remove it from the ground.

Spamming crowbar on it creates a ton of floortiles.

Issue reported from  Round ID: [147690](https://scrubby.melonmesa.com/round/147690) (/tg/Station - Terry [EU] [100% LAG FREE])

Reporting client version: 513.1533

**Comment by msgerbs** [comment] 2020-10-06 06:15
Beautiful.

**Comment by msgerbs** [comment] 2020-10-08 05:54
Also duplicate of #54159 probably?

**Comment by kriskog** [comment] 2020-10-10 01:56
Related at least, but this one has reproduction

**Comment by ArcaneMusic** [comment] 2020-11-01 19:24
So, not necessarily infinite persay, but certainly could be used infinitely:
![image](https://user-images.githubusercontent.com/41715314/97812133-550e6b80-1c4d-11eb-825f-86c75b211c1f.png)
More accurate reproductions steps:
Spawn several floorbots, all at once. 
Tell them to add tiles to new hull plating and place floor tiles.
Thrown down a explosive to get your tiles all nice and damaged. Broken floors, removed floors, a few holes to space, the whole nine yards.
Once those several floorbots all move to the task, as they all perform and assign themselves to single floortiles at once, and there's no ability for those assignments to be overridden, you can have multiple floorbots working on the same tile, and they'll begin to stack onto a single task all at once. This can result in getting multiple floor turfs stacked onto each other at one time, so you can pry a single floor turf up, underneath is another turf, and if you dig deep enough you'll get back to the base plating, but it effectively duplicated the metal from the floortiles.

Is this the same infinite floor tile glitch usually associated with floor tiles? Not quite, but is certainly similar.
![image](https://user-images.githubusercontent.com/41715314/97812233-f8f81700-1c4d-11eb-93a4-18cbd9d68700.png)

**Closed** 2021-01-12 02:03 UTC
Labels: Bug
