### ISSUE TITLE
Long-range guns are consistently inaccurate

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#62423] opened 2021-10-28 12:46 UTC
Video depicting the inacurracy (streamable is blocked in russia or something apparently)
https://drive.google.com/file/d/1EWGAq4G-6z8EBkim0EaGZyJgzUA1cFvg/view?usp=sharing

tl;dw pixel differences in aiming will result in the shot going wild and off the intended target yet it is somewhat consistent. this isn't limited to sniper rifles, any gun (or even a wand apparently as seen in the video) will have the same weird trajectory.

**Comment by timothymtorres** [comment] 2022-08-27 12:38
Duplicate of #64129

**Closed by timothymtorres** 2022-08-27 12:38 UTC
Labels: Consistency Issue
