### ISSUE TITLE
Account registration device account creation issue

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#60363] opened 2021-07-21 13:40 UTC
Reporting client version: 513.1542

## Round ID:
[166362](https://scrubby.melonmesa.com/round/166362)

## Testmerges:
- [Fixes a runtime that would leave everyone naked](https://www.github.com/tgstation/tgstation/pull/60327)
- [fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)](https://www.github.com/tgstation/tgstation/pull/60066)

## Reproduction:
Make the machine and get an id without an account linked, use the id with the machine, try to buy something from a vending machine even if you have the required funds and it says this:

The MegaSeed Servitor beeps, "Departmental accounts have been blacklisted from personal expenses due to embezzlement."

**Comment by ArcaneMusic** [comment] 2021-08-03 17:57
Appears to be a duplicate of #57929, but thanks for providing the reproduction steps.

**Closed by ArcaneMusic** 2021-08-03 17:57 UTC
