### ISSUE TITLE
RPD menu pipe sprites are missing.

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#37830] opened 2018-05-13 23:24 UTC
Issue reported from  Round ID: 87895 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

They're just fucking gone.

**Comment by Barhandar** [comment] 2018-05-13 23:38
Duplicate of #37828

**Comment by optimumtact** [comment] 2018-05-13 23:47
dupe

**Closed by optimumtact** 2018-05-13 23:47 UTC

**Comment by OmegaShoots** [comment] 2018-05-14 01:57
shit had this written up a while ago
