### ISSUE TITLE
issues with gang objectives

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49881] opened 2020-03-11 03:24 UTC
I've pinged @Iamgoofball about some of these issues already, but I figured that I'd make them publicly known and add a few more to the list:

* The Ballas are given an objective to keep ALL of Sec alive, which is a monumental task. They're told that they've cut a deal with Sec, but no members of Sec are informed of this, so if a denthead sec officer decides to go validhunting against the Ballas or cremate themselves just to spite the Ballas (or if another gang intentionally ganks and cremates a SINGLE sec officer just to screw over the Ballas), they're kind of fucked. IMO, the objective should be changed to just keeping at least HALF of the Sec team alive.
* Do ghosted people have minds? If not, the Russian Mafia is kind of screwed if a single member of their gang ghosts themselves (or DCs) without telling anyone.
* The Italian Mob's objective implies that they just need to keep one chaplain alive (which would make sense), but they actually need to keep ALL of the chaplains alive.
* The Tunnel Snakes objective is really, really hard to complete without wiping out almost everyone on the station who isn't in your gang, as the clothes that count for the objective are rare and hard to obtain (sure, each gang member gets two pieces of TS clothing upon joining the gang, but that's not really enough unless your gang makes up almost a quarter of the entire living population of the station and the other gangs make up less than half of the station's living population (since they're obviously not gonna rep another gang's colors (voluntarily)). Also, I'm pretty sure that ash lizards and free golems and stuff will count as being living players for this objective, so if the ghosts in the round decided to start a free golem colony, you can kind of get screwed.
* It's almost impossible for the Los Santos Vagos to complete their objective without wiping out almost the entire station, almost every ghost role, and almost all of the cops. First off, their objective lies to them- they need to addict at least **50%** of the living players to crank, but their objective tells them that they only need to addict **25%** of the living players to crank. Second off, even if you've set up a massive drug-production operation, keeping people addicted to crank is basically impossible. The crank addiction deals lethal amounts of damage, and if you have it, you basically need constant medical attention (or a constant amount of crank) to keep from it from killing you. Even if you are receiving medical attention for your crank addiction, you can still just kick it accidentally (or intentionally, since you probably don't have any kind feelings for the people who intentionally addicted you to crank) by going without crank for long enough. This entire objective honestly needs to be scrapped and replaced with something else, because no possible version of it (even a version where you just have to addict people to ANY chem) is ever going to be even remotely feasible to accomplish.
* If there's no RD, the Monarch crew basically get a free objective. They can also get cucked at the last moment by a latejoiner RD, and it doesn't look like you can use the HoP's console to close existing (or open new) RD slots to keep that from happening. The bureaucratic error event also kind of fucks them over if it selects RDs, but that's at least rare. Also, their objective implies that they need to kill or maroon ("ENSURE THAT **HE DOES NOT LEAVE THIS STATION** ALIVE", a similar wording to the one used for "kill or maroon" objectives) just one RD, but the objective requires that they kill (NOT maroon) ALL of the RDs (there usually isn't more than one, admittedly, but still).
* The Tojo clan's objective tells them that they'll fail their objective "If more than **85%** of this station is busted", but the actual mechanics of the objective cause you to fail it if more that **15%** of the station is busted.

Also, if one gang gets entirely wiped out, it looks like all of the other gangs will get cucked by the gang balance cap. This can happen easily if the starting godfather for one of the gangs gets killed (by, say, a rival gang) before they can convert anyone, is new/doesn't know what they're doing, or ghosts, goes SSD, commits suicide, etc. This can also happen if gangs actually initiate gang warfare against one another. Counterintuitively, wiping out another gang actually HURTS your gang. I get that you don't want one gang to snowball ahead of the others, but there's gotta be a solution to this that addresses both issues.

**Comment by ATH1909** [comment] 2020-03-11 03:31
Also, gangs got merged without quite a few of our comments on the code of your PR getting addressed.

**Comment by Iamgoofball** [comment] 2020-03-11 03:36
>The Ballas are given an objective to keep ALL of Sec alive, which is a monumental task. They're told that they've cut a deal with Sec, but no members of Sec are informed of this, so if a denthead sec officer decides to go validhunting against the Ballas or cremate themselves just to spite the Ballas (or if another gang intentionally ganks and cremates a SINGLE sec officer just to screw over the Ballas), they're kind of fucked. IMO, the objective should be changed to just keeping at least HALF of the Sec team alive.

Not a bug. Why is this in a bug report?

>Do ghosted people have minds? If not, the Russian Mafia is kind of screwed if a single member of their gang ghosts themselves (or DCs) without telling anyone.

Dead people or ghosted/logged out people don't count towards objectives.

>The Italian Mob's objective implies that they just need to keep one chaplain alive (which would make sense), but they actually need to keep ALL of the chaplains alive.

>The Tunnel Snakes objective is really, really hard to complete without wiping out almost everyone on the station who isn't in your gang,

Literally not a bug. It's not a hard objective either, I've seen people do it non-violently.

There is only one chaplain by default. I'll adjust the text to account for this.

>they need to addict at least 50% of the living players to crank, but their objective tells them that they only need to addict 25% of the living players to crank.

This is the only actual bug in this statement. Stop putting feedback in bug reports.

>Counterintuitively, wiping out another gang actually HURTS your gang. I get that you don't want one gang to snowball ahead of the others, but there's gotta be a solution to this that addresses both issues.

Have you tried not killing people? Your goal isn't to be the only gang, it's to be the winning gang.

>The Tojo clan's objective tells them that they'll fail their objective "If more than 85% of this station is busted", but the actual mechanics of the objective cause you to fail it if more that 15% of the station is busted.

Re-read the station text. It specifically states if the station's integrity **falls below** 85%.

This is a garbage report packed full of stuff that doesn't need to be here. Take the actual gameplay feedback to the forums.

**Comment by Iamgoofball** [comment] 2020-03-11 03:41
>Also, gangs got merged without quite a few of our comments on the code of your PR getting addressed, but that's not really goofball's fault.

Your comments don't matter. Only maintainer comments do. That's how github works.

**Comment by ATH1909** [comment] 2020-03-11 03:45
> Re-read the station text. It specifically states if the station's integrity **falls below** 85%.

"If more than 85% of this station is busted when we get the hell out of here, it's your ass on the line."

🤔

**Comment by ATH1909** [comment] 2020-03-11 03:46
> > Also, gangs got merged without quite a few of our comments on the code of your PR getting addressed, but that's not really goofball's fault.
> 
> Your comments don't matter. Only maintainer comments do. That's how github works.

It doesn't mean that they weren't still valid comments. I was just reminding you that there were still some unaddressed comments left on the PR that added Families, and that you should come back to/address them at some point.

**Comment by Iamgoofball** [comment] 2020-03-11 03:47
No. They literally are not valid comments until a maintainer agrees with them or demands them fixed.

**Comment by Iamgoofball** [comment] 2020-03-11 03:47
>"If more than 85% of this station is busted when we get the hell out of here, it's your ass on the line."

well shit i cant read

**Comment by ATH1909** [comment] 2020-03-11 03:51
> No. They literally are not valid comments until a maintainer agrees with them or demands them fixed.

Then at least mark them as resolved or something if you aren't going to listen to them.

**Comment by XDTM** [comment] 2020-03-11 09:29
They aren't obligatory, but generally speaking all feedback is valid if done in good faith. Not all feedback can be addressed nor everyone can be pleased, but personally i wouldn't dismiss it by default even if it's not from a maintainer.

**Comment by feemjmeem** [comment] 2020-03-11 18:51
There is no game preference to opt out of this game mode.

**Comment by Iamgoofball** [comment] 2020-03-11 19:37
Being worked on

**Comment by ATH1909** [comment] 2020-03-28 03:39
A few of these issues were fixed/addressed by https://github.com/tgstation/tgstation/pull/49882, but not all of them.

**Comment by Iamgoofball** [comment] 2020-03-28 14:26
thats because they arent bugs, they're opinions, go put them in the feedback thread with the other opinions

**Comment by msgerbs** [comment] 2020-09-08 14:25
@ATH1909 @Iamgoofball Can we agree to close this issue report if all the actual bugs have been addressed then? Seems silly to keep this open if we've determined that this stuff isn't a bug. If not can you at least edit the initial post to reflect which ones are fixed?

**Comment by ArcaneMusic** [comment] 2020-11-22 00:12
Closing for now since it seems like the actual bugs were fixed months ago.

**Closed by ArcaneMusic** 2020-11-22 00:12 UTC
Labels: Bug, Oversight
