### ISSUE TITLE
links in chat (again)

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37746] opened 2018-05-08 13:04 UTC
![download](https://user-images.githubusercontent.com/33834933/39758712-fc149182-52d0-11e8-9418-d43177fa33fc.png)

**Comment by SpaceManiac** [comment] 2018-05-08 18:36
Duplicate of #36924, fix is WIP in #34086.

**Closed by SpaceManiac** 2018-05-08 18:36 UTC
