### ISSUE TITLE
Black carpet looks buggy and cursed.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73561] opened 2023-02-20 14:04 UTC
## Round ID:
[200464](https://scrubby.melonmesa.com/round/200464)

## Reproduction:
Place black carpet on the floor and it will look like this 
![image](https://user-images.githubusercontent.com/93882977/220128679-7bc335e2-9134-416c-a5ad-2fbcd39d338f.png)

**Comment by ZephyrTFA** [comment] 2023-02-20 14:05
Duplicate of #73518

**Closed by ZephyrTFA** 2023-02-20 14:05 UTC
