### ISSUE TITLE
Somehow, plants can enter a state where they can be harvested infinitely, one at a time, also, plant traits can just vanish off the face of earth 

### ISSUE THREAD

**Issue by TheObserver-sys** [tgstation/tgstation#50859] opened 2020-05-04 03:56 UTC
## Round ID:
[136248](https://scrubby.melonmesa.com/round/136248), on Manuel

## Reproduction:
I am not entirely sure what caused it, but what I was doing is as follows:
Was working on a massive healing plant, and started the crossbreeding process, taking the gene shears to plants to reduce the bad results, and using diethylmine to quickly heal off the damage, flipping the plant into a non chem sending state. We attempted to raise it back to the point where it could spread chems again, and ended up erasing all but two genes across all three plants, despite me taking the unwanted chem genes out of only one plant. After all three plants returned to Instability 20+, they were ready for harvest, where we stumbled upon the fact that for some reason, we were able to harvest one plant at a time, but instantly, and infinitely, the harvest-able state never flicking off.

Also: Upon harvesting said plant, you actually can't extract seeds or obtain chems from it, throwing up the error: None of the PLANT left, oh no!

**Comment by ArcaneMusic** [comment] 2020-07-06 20:24
In my initial testing of the botany rework this seemed consistent with situations where a plant had received multiple instances of the repeated harvest trait, resulting in the harvestable proc never going away. It may also be a duplicate of #51193 as well.

**Closed** 2020-07-12 09:23 UTC
Labels: Bug
