### ISSUE TITLE
Explosions on lavaland generate plating and lattices

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#30663] opened 2017-09-12 17:49 UTC
Usually when a bomb, more often than not gibonite, goes off on lavaland, it won't destroy the flooring in any way and will just "dig" the tiles to give you ash, but now when anything explodes on lavaland with enough force it generates broken plating and lattices, which melt into generic lava pools. Also pretty annoying since most of the ore you'd get from explosions like this just burn and turn into piles of ash.

**Comment by Repukan** [comment] 2017-09-12 18:07
Dupe of #30550

**Closed** 2017-09-12 20:02 UTC
