### ISSUE TITLE
Boat from bottled boat does not work properly on icebox

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#54901] opened 2020-11-09 15:14 UTC
Round ID: [149980](https://scrubby.melonmesa.com/round/149980)
BYOND Version: 513.1536
Server revision compiled on: 
Master commit: b6b526a94a58a9590b87d0589d6daec53b2c519b
The following pull requests are currently test merged:
#54379: '[WIP] Remove fusion from reactions, add hypertorus fusion machinery' by Ghilker at commit 4189ab1646
#54588: 'Bring back Kilostation v3.0' by Maurukas at commit f1d177f28c
#54702: 'Add debug info for client time timers' by spookydonut at commit a8042f4583
#54804: '[TM Candidate] Fix a number of atmos-related runtimes through pipeline and SSair tweaks.' by Timberpoes at commit 5b4049551e

It can swim on liquified plasma, but it wont protect you from getting absolutely annihilated by it

**Comment by dragomagol** [comment] 2020-11-09 19:34
Possibly a duplicate of #51505 , although I think in that one it couldn't move at all.

**Comment by ArcaneMusic** [comment] 2020-11-10 08:39
The linked issue above also claims it's not a bug, but instead a consistency issue, as there just isn't a boat capable of sailing across molten plasma.

**Comment by adamkad1** [comment] 2020-11-13 11:47
Eh, whats the difference between lava and molten plasma?

**Comment by timothymtorres** [comment] 2021-11-08 13:51
Duplicate of #51505

**Closed by timothymtorres** 2021-11-08 13:51 UTC
Labels: Consistency Issue
