### ISSUE TITLE
Frozen objects don't unfreeze

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#29791] opened 2017-08-08 23:41 UTC
And frozen turfs do...
@Iamgoofball

**Comment by Iamgoofball** [comment] 2017-08-08 23:43
>maintainer

>didn't use the format

also, not my fault, I didn't code object unfreezing, bug the guy who did

**Comment by nicbn** [comment] 2017-08-09 00:25
> I didn't code object unfreezing

That's the problem.

**Comment by Iamgoofball** [comment] 2017-08-09 00:44
Someone else did.

**Comment by Tokiko1** [comment] 2017-08-09 01:14
I am fairly sure that's because you guys refactored slipping and unfreezing objects was handled in these. As horrifying as that sounds, it was actually pretty cheap low on the processing.

**Comment by Cyberboss** [comment] 2017-08-09 01:57
That hasn't been merged yet I think?

**Comment by WJohn** [comment] 2017-08-09 06:04
Was it test merged, maybe? IDK.

**Comment by AnturK** [comment] 2017-08-09 07:00
This is just lack of feature not a bug.

**Comment by Cyberboss** [comment] 2017-08-09 11:51
@Anturk I did code unfreezing things when they get warm enough.

**Comment by AnturK** [comment] 2017-08-09 11:57
After quick glance at the code i see i was mistaken, they just unfrezee on Entered for some reason

**Comment by duncathan** [comment] 2017-10-12 08:35
begrudgingly applying the atmos tag grr freon

**Closed** 2017-10-15 12:32 UTC
Labels: Atmospherics, Consistency Issue
