### ISSUE TITLE
Make it so the Nuclear ops shuttle turrets can't shoot through shuttle walls.

### ISSUE THREAD

**Issue by Redrover1760** [tgstation/tgstation#58553] opened 2021-04-19 23:53 UTC
At the current moment a person can park the nuke ops shuttle by the escape shuttle and, after the nuke ops lose and die, it'll shoot up the people trying to escape, as it shoots through walls, for some reason.

We got all turned zombies in the round we're in, and it wasn't parked that close, so it only covered the rear area of the shuttle, and so it didn't matter that much as it can't kill us, but it would probably be really obnoxious for an actually evacuating crew otherwise.

**Comment by D4C-420** [comment] 2021-04-20 04:46
Played a small amount of rounds where this happened and I think both where on meta? The nuke ops shuttle can shoot through windows and as a result kill people. For the metastation shuttle that round the back half of the escape was uninhabitable until the shuttle left because the turrets can see you and if I had guess their is no check to see if it collides with window. (Side note the ops shuttle shoots bullets not lasers).

**Comment by Fikou** [comment] 2021-04-20 08:03
it shoots penetrator bullets. this is a deliberate design choice to allow people to hunt the nukie shuttle.

**Comment by D4C-420** [comment] 2021-04-20 13:32
> penetrator bullets

Yea but the issue being described here is that on meta nuke ops can park their shuttle close enough to evac for their turrets to shoot people on shuttle through the window's and those things knock most people down in about 3-5 shots. Having half of a default escape shuttle be unusable for the time it takes to evac because nukies placed their shuttle right next to it seems like an oversight.

**Comment by ATH1909** [comment] 2021-04-20 18:22
I like the idea of bringing the syndicate shuttle around for fire support/a broadside. It's hard to actually abuse this on most maps, as there are few frequently-used public areas that have LoS to a place that the syndicate shuttle can actually park in.

Also, if the shuttle's turrets didn't fire penetration bullets (or something similar to them), you could cheese them by just keeping an unwrenched reinforced plasmaglass window between you and them.

**Comment by D4C-420** [comment] 2021-04-20 18:47
> Also, if the shuttle's turrets didn't fire penetration bullets (or something similar to them), you could cheese them by just keeping an unwrenched reinforced plasmaglass window between you and them.

Fair (not like sending borgos to cover it up the turrets LoS docent work) but I still think its not the best idea to have the back half of an escape shuttle be made unusable because bad parallel parking. Maybe have them ignore wrenched glass but act as they do now with unwrenched glass? would solve the issue of being shot in the back while preventing cheese.

**Comment by timothymtorres** [comment] 2021-08-20 08:54
Closing this since it's confirmed not a bug.

**Closed by timothymtorres** 2021-08-20 08:54 UTC
Labels: Not a bug
