### ISSUE TITLE
It is impossible to add buffer (in a reaction chamber) to a beaker if that beaker is full

### ISSUE THREAD

**Issue by Toparai** [tgstation/tgstation#80831] opened 2024-01-06 20:49 UTC
## Issue Summary 
In a reaction chamber, when attempting to add buffer to a reaction that is occurring in a full beaker, the button will do nothing.

Video below:

https://github.com/tgstation/tgstation/assets/82719198/193373d6-ec9a-4b69-90f4-e8c920ea47c4

(Notice my furious clicking)

## Round ID:
[221763](https://scrubby.melonmesa.com/round/221763) (but has been occuring for more than a month now)

## Testmerges:
n/a

## Reproduction:
Attempt to add chemical buffer to a full beaker via the button in a reaction chamber.

**Comment by ZephyrTFA** [comment] 2024-01-06 20:50
duplicate of https://github.com/tgstation/tgstation/issues/80409

**Closed by ZephyrTFA** 2024-01-06 20:50 UTC
