### ISSUE TITLE
Meson Vision allows you to see lower floors perfectly clearly through walls if they do not have a ceiling.

### ISSUE THREAD

**Issue by ProbablyGreen** [tgstation/tgstation#83929] opened 2024-06-13 01:21 UTC
Reporting client version: 515.1640

## Issue Summary

As an Engineering Cyborg I equipped meson vision on wawastation. When I was on the higher Z levels any lower Z levels without a ceiling/floor in the way were perfectly visible through walls, while meson vision normally only lets you see walls and floors through walls without any idea of what's actually in the room.

## Round ID:
[230451](https://scrubby.melonmesa.com/round/230451)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

## Reproduction:

I am unsure if this is replicable with meson vision goggles, I was a cyborg at the time.
1. Join a station with multiple Z-Levels (Technically I only noticed on wawastation, so maybe it's not every station?)
2. Become an engineering cyborg.
3. Equip meson vision
4. Go to the highest Z-level on station and look for an area with no floor that lets you drop down into the lower Z-level (plenty of those on wawastation)
5. go into maintenance or a closed room so that you need meson vision to see the area. You should be able to see everything that happens in the area despite there being a solid wall in your way.

![image](https://github.com/tgstation/tgstation/assets/69023665/63d21ba8-0dae-4466-9844-65a1348c24e8)
![image](https://github.com/tgstation/tgstation/assets/69023665/e75aa910-24d3-47cc-8aad-2d92d5e42937)

**Comment by mc-oofert** [comment] 2024-06-13 05:15
duplicate of  #53783

**Comment by ZephyrTFA** [comment] 2024-06-13 21:14
Duplicate of https://github.com/tgstation/tgstation/issues/53783

**Comment by ZephyrTFA** [comment] 2024-06-13 21:14
Please remember to do even a cursory search for your issue before opening a new issue report.

**Closed by ZephyrTFA** 2024-06-13 21:14 UTC
