### ISSUE TITLE
Standard cyborgs are unable to build wall girders

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#20737] opened 2016-09-28 20:00 UTC
For some odd reason,standard borgs can't build girders with their metal.
How to reproduce:
Reply PM from-Coiax/(ABDUCTOR): Step 1, be standard cyborg, Step 2, equip cyborg metal,(?|F) Step 3, open the metal construction menu, Step 4,(?|F) click wall girders, Step 5, nothing happens 
Tested it,couldn't build girders either.

**Comment by phil235** [comment] 2016-09-28 21:37
duplicate of #20521

**Closed by phil235** 2016-09-28 21:37 UTC
