### ISSUE TITLE
Tape recorders and holopads can be used to easily lag out the server

### ISSUE THREAD

**Issue by Momo8289** [tgstation/tgstation#79647] opened 2023-11-10 20:38 UTC
## Reproduction:
Find or print a bunch of either station bounced radios, universal recorders, or both. Repeatedly say whatever you want to spam over and over and record it onto the universal recorder(s). Enable the mic on all of your station bounced radios, and finally hit play on the universal recorders. This will cause the messages to be spammed over common comms, and in a high enough volume (easy to achieve, as both recorders and radios are printable), will start lagging out the server, and can possibly cause a crash. This also works with a holopad in place of the recorders, and holopads even let you loop the recording to make things last longer.

This was found on a downstream, where we've been having problems with people using this to grief. Our quick and dirty fix was to make radios ignore tape recorders and holopads. It's not ideal though, as there could be legitimate uses for playing recordings over comms.

[Video demonstration can be found here](https://imgur.com/a/1BG5o2z). Even with a fairly small number of recorders, time dilation spikes significantly. It can and does get MUCH worse.

**Comment by timothymtorres** [comment] 2023-11-10 22:23
Duplicate of #59522

**Closed** 2023-11-10 22:23 UTC
