### ISSUE TITLE
whiteship landed on aux base, chaos insues (i think)

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50299] opened 2020-03-30 03:37 UTC
Issue reported from  Round ID: [133418](https://scrubby.melonmesa.com/round/133418) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1514

So i send the shuttle to the aux base, and it lands inside the whiteship.
PM admins, admin is confused, they send me to the mining base.
Search for the aux base, find some stuff i put near it, but it itself is missing.
I have litteraly no clue what happened

**Comment by Dennok** [comment] 2020-03-30 08:05
Images please.

**Comment by redguy999** [comment] 2020-03-30 13:24
Uh, it appears i forgot to take any. Oops

**Comment by TheBonded** [comment] 2021-12-09 17:30
seems like the whiteship landed on the aux base, crushed it, which destroyed it. landing a ship on a building destroys it. this is only possible if you build the aux base within the area that the whiteship is set to land (south-east of the mining base), as the whiteship cannot set a custom landing location on top of a built area. same thing happens if you build under the emergency shuttle or arrivals shuttle.

intended, not a bug.

**Closed by TheBonded** 2021-12-09 17:30 UTC
Labels: Needs Reproducing
