### ISSUE TITLE
RPD Gas meter will not deploy

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#34307] opened 2018-01-11 06:54 UTC
So about when the RPD UI got updated. When you try to build a gas meter from the RPD it creates something called fitting an invisible non intractable item that you can only see by alt clicking

**Comment by Marflowerose** [comment] 2018-01-11 08:35
dupe of https://github.com/tgstation/tgstation/issues/32920

**Closed** 2018-01-11 10:09 UTC
