### ISSUE TITLE
Thrown bodies can move necropolis tendril nests.

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#40595] opened 2018-09-30 01:32 UTC
Simply aggressive grab a corpse (or a living person, presumably, didn't try it) and throw them at the tendril nest, it will shove it. Likely the same cause as https://github.com/tgstation/tgstation/issues/40590. Could probably compress these into one issue.

**Comment by SpaceManiac** [comment] 2018-09-30 01:33
Duplicate of #40015

**Closed by SpaceManiac** 2018-09-30 01:33 UTC
