### ISSUE TITLE
Wormhole Jaunters dont work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58889] opened 2021-05-04 17:17 UTC
## Reproduction: 
Use a jaunter
Walk thru a wormhole without any effect
https://www.youtube.com/watch?v=MvFnGoX--sw

**Comment by rdragan** [comment] 2021-05-05 01:08
Very likely caused by #58340 which was testmerged at the time.

**Comment by Livrah** [comment] 2021-05-05 19:29
Same issue with hand tele portals.

**Comment by LemonInTheDark** [comment] 2021-05-07 22:02
Pr's merged, so one would hope this isn't a thing anymore

**Closed by LemonInTheDark** 2021-05-07 22:02 UTC
Labels: Test Merge Bug
