### ISSUE TITLE
Tray goggles show lighting in either fullbright or fulldark, not inbetween.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27031] opened 2017-05-07 14:29 UTC
This seems pointless, engineering goggles can swap to meson mode which hides ALL lighting (everything is bright), and tray mode, which makes everything fullbright except places which do not have any light at all. Tray mode shouldn't affect lighting whatsoever. Not sure if a bug or not.
![](http://i.imgur.com/xtUt6nM.png)

**Comment by octareenroon91** [comment] 2017-05-07 18:00
Push down the color and contrast and call it good. Make it more like having to actually use thru-floor radar.

**Comment by WJohn** [comment] 2017-06-03 02:12
@ChangelingRain i think, these are broken again. tray goggles get rid of smooth lighting (they shouldn't affect lighting at all) except only in your immediate surroundings, and this happens on or off.

Engie goggles (which can swap from tray to meson) START dark when first equipped on meson mode, but if swapped to tray and back will become full bright.

**Comment by ShizCalev** [comment] 2017-10-06 06:54
Dupe of #26918?

**Comment by WJohn** [comment] 2017-11-19 10:51
This bug has changed: The "off" mode allows you to see in darkness kind of like thermals with rudimentary night vision, but it's weak. So you see very dark stars everywhere. However, this ONLY happens when you first put these on WITHOUT changing the mode. Changing the mode fixes this bug.

![](https://i.imgur.com/B0V85T2.png)

**Comment by kriskog** [comment] 2019-07-18 08:22
This is fixed.

**Closed by kriskog** 2019-07-18 08:22 UTC
Labels: Consistency Issue, Tested/Reproduced
