### ISSUE TITLE
Action Buttons giving off light again

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#64035] opened 2022-01-12 18:45 UTC
Reporting client version: 514.1571

## Round ID:
[176479](https://scrubby.melonmesa.com/round/176479)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)

## Reproduction:
Get a flashlight and turn it on
Walk around in the dark
Notice light being given off in the corner by the action buttons

**Comment by timothymtorres** [comment] 2022-10-28 23:05
Duplicate of #53481

**Closed by timothymtorres** 2022-10-28 23:05 UTC
Labels: Bug
