### ISSUE TITLE
Demonic frost miner can sometimes spawn without its lower section

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#70985] opened 2022-11-01 16:58 UTC
Reporting client version: 514.1585

## Round ID:
[193529](https://scrubby.melonmesa.com/round/193529)

## Testmerges:
- [(hopefully) improvements to use of scope and kinesis module](https://www.github.com/tgstation/tgstation/pull/70934)

## Reproduction:
![image](https://user-images.githubusercontent.com/36141254/199292030-864b1c9f-57d6-4a7c-96ef-67553e93740d.png)

**Comment by msgerbs** [comment] 2022-11-01 18:25
Duplicate of #62901

Also I hate this ruin so much lol

**Closed** 2022-11-01 18:25 UTC
