### ISSUE TITLE
Light overlay from luminescent eyes is not hidden from right click and alt click menus

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#53765] opened 2020-09-16 08:42 UTC
## Reproduction

1. Get luminescent eyes
2. Turn 'em on
3. Right click the tiles in front of you. You will see "eye lighting".

![dreamseeker_2020-09-15T09-08-08](https://user-images.githubusercontent.com/35135081/93313769-bec9d780-f7bd-11ea-964d-481b62f9eaf1.png)

4. Alt click the tiles in front of you. You will see this.

![2020-09-15T09-08-00](https://user-images.githubusercontent.com/35135081/93313863-e0c35a00-f7bd-11ea-891d-cd5b0381cfda.gif)

**Comment by Tlaltecuhtli** [comment] 2020-09-16 10:09
the icon dump on alt click happens regardless of having eye lights

**Comment by cacogen** [comment] 2020-09-16 13:55
Haven't played since before this bug but maybe it shows the whole .dmi if an atom's icon is undefined?

**Comment by Jared-Fogle** [comment] 2020-09-17 01:58
heh heh. oversight. cause its...forget it

**Comment by timothymtorres** [comment] 2021-12-17 13:41
Duplicate of #53824

**Closed by timothymtorres** 2021-12-17 13:41 UTC
Labels: Oversight

**Comment by Mothblocks** [comment] 2021-12-18 09:20
i was so much funnier back in 2020

**Comment by Mothblocks** [comment] 2021-12-18 09:23
...also my issue was newer

**Comment by timothymtorres** [comment] 2021-12-21 13:06
Aye it was older but the other issue's title was better and it had more detailed information/troubleshooting.  Still, I liked the oversight joke!
