### ISSUE TITLE
Shift start cyborg was not linked to shift start AI

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#87651] opened 2024-11-02 16:52 UTC
### Client Version:

515.1644

### Issue Summary:

I rolled AI (NOT LATEJOIN AI.  SHIFT START)    and noticed there was no cyborgs linked right away. Then one spoke on binary channel and I noticed somebody had indeed rolled cyborg but was not synched. This was within a few seconds of the shift starting, so unless this person somehow became a borg before the round started this should be a bug

### Round ID:

[241245](https://scrubby.melonmesa.com/round/241245)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

not really sure. I rolled ai and the person who rolled borgo wasnt synched at the start of the shift. I

**Comment by Aliceee2ch** [comment] 2024-11-02 18:04
wanted to look into problem but.. icky ocky?

![image](https://github.com/user-attachments/assets/f8ee51b8-8218-489a-b362-ecd5f414a764)

**Comment by DATA-xPUNGED** [comment] 2024-11-02 18:28
Ick Ock, closing issue/s

**Comment by moocowswag** [comment] 2024-11-02 20:34
Probably shouldnt have a button at the top right of the screen that lets people instantly open and submit a bug report without warning them to wait till round end to finish the report or even delaying the submission for them...

**Comment by TagGamerGang22** [comment] 2024-11-03 04:08
This seems to be a consistent issue when I play AI as well. This screenshot is likely also connected to whatever the issue is as this occurred in one of the rounds.
![image](https://github.com/user-attachments/assets/760595c0-6dfc-4292-8bb9-a3327978ceea)

**Comment by Sealed101** [comment] 2024-11-03 21:24
this might be #69812 judging by the image

>![image](https://private-user-images.githubusercontent.com/147560041/382545999-760595c0-6dfc-4292-8bb9-a3327978ceea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjkxODUsIm5iZiI6MTczMDY2ODg4NSwicGF0aCI6Ii8xNDc1NjAwNDEvMzgyNTQ1OTk5LTc2MDU5NWMwLTZkZmMtNDI5Mi04YmI5LWEzMzI3OTc4Y2VlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMTIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTdkODQ0MjdiNDU1YzFjZTc0ZTI4YzA0MTYyOGViYTBjN2U0ZDhkMGFmMDI0NTcxMzYzYzQyOGFiMzZlOGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hHZ9Fp2sVkbHJs2ty1rjh6Nq16PxsuVS31tRvSo1wuw)

unless the laws were displayed lower than the greentext, which is weird
scream at admins if you notice this happening so they can scream at coders that it's #69812 again, and hopefully they'll provide runtimes

**Closed** 2024-11-12 19:05 UTC
Labels: Bug
