### ISSUE TITLE
Radstorm-proof sec hallways on Icebox

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76863] opened 2023-07-15 11:42 UTC
Reporting client version: 514.1589

## Round ID:
[210281](https://scrubby.melonmesa.com/round/210281) although it's mapping so it shouldn't matter

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/9da3e733-e2ac-4fb2-810a-bb3ea899aaaa)
I doubt these are supposed to be considered radiation safe.

**Comment by Sealed101** [comment] 2023-07-15 11:59
did you enter them? could be #75352 again

**Comment by Sealed101** [comment] 2023-07-15 12:16
the area itself doesn't differ from any other security area

https://github.com/tgstation/tgstation/blob/0f47384465c29911fef57a13013337f1ea6a2cb2/code/game/area/areas/station.dm#L1177-L1179

i am assuming this is just a duplicate of #75352

**Closed by Sealed101** 2023-07-15 12:16 UTC

**Comment by AdipemDragon** [comment] 2023-07-15 13:38
The area is indeed The Same Thing, but in the screenie I was the Armski. I moved around in there, between the warden's office and the glass bridge and nothing seemed to update like the other issue, but it might be because I was already In there as the storm started
oh well, might 100% still be related to that other one,

**Comment by Sealed101** [comment] 2023-07-15 14:27
that weather thing is very hard to pin down honestly, but mapping-wise there's no reason that area is rad-exempt
