### ISSUE TITLE
AI is unable to open glass doors

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36369] opened 2018-03-12 20:22 UTC
[Round ID]: # A couple rounds before 84865

[Reproduction]: # 
AI is unable to open glass doors.
1. Be AI
2. Click a glass door and try shift+click.
3. Glass door does not open.

**Comment by ShizCalev** [comment] 2018-03-12 20:27
#33166 @kevinz000

**Comment by RandomMarine** [comment] 2018-03-12 21:03
If you're talking about windoors, dupe of #36358
If you're talking about glass airlocks, **be more specific**.

**Comment by ShizCalev** [comment] 2018-03-12 21:13
Duplicate of #36358

**Closed by ShizCalev** 2018-03-12 21:13 UTC
Labels: Bug, Test Merge Bug
