### ISSUE TITLE
Ash Storm visual delay?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#76843] opened 2023-07-14 23:57 UTC
Reporting client version: 514.1589

## Round ID:
[210256](https://scrubby.melonmesa.com/round/210256)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)

## Reproduction:
1. Fight BDM
2. Storm begins, but visually, you are safe.
3. Realize you are cooking alive anyway.

The storm eventually did become visible in the area, but if I hadn't realized it was killing me already by then, it would've likely been too late.
![image](https://github.com/tgstation/tgstation/assets/44104681/d8ffce73-4fc6-4fe7-9bd0-52d0f33a2244)
Here's my gear. Possibly related to style meter?
![image](https://github.com/tgstation/tgstation/assets/44104681/823133e0-d5aa-420a-92bc-476ec0cf573d)

After the storm ended, the visuals remained outside my small shelter until I stepped outside, which made SOME of them disappear. Strange!
![image](https://github.com/tgstation/tgstation/assets/44104681/05e0f7bf-179b-424d-bd51-59c118008e9c)

**Comment by Likteer** [comment] 2023-07-15 01:17
I'm sure this is not an issue with the style meter, for this happens with radstorms as well.
Radstorms will not show up/disappear until you walk out of/into the area.

**Comment by Sealed101** [comment] 2023-07-15 11:29
Duplicate of #75352

**Comment by Sealed101** [comment] 2023-07-15 11:30
although style meter could employ something that would cause the overlay failure

**Closed by Sealed101** 2023-07-15 11:30 UTC
