### ISSUE TITLE
The "Hide" ability of the alien larva doesn't work.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#70318] opened 2022-10-05 14:49 UTC
## Round ID: [191790](https://scrubby.melonmesa.com/round/191790)
It just doesn't work. It doesn't place you under the table or debris, the larva always stays on the top layer.

**Comment by msgerbs** [comment] 2022-10-05 23:13
Can confirm this as well, noticed it a couple weeks ago I believe.

**Comment by msgerbs** [comment] 2022-10-07 16:36
Yeah so for anyone else looking at this, this is the very definition of non-trivial. The issue is that the FOV PR moved all mobs to GAME_PLANE_FOV_HIDDEN which is plane -6. Everything else is on GAME_PLANE which is -7. So all mobs are always going to be rendered on top of everything else, and there's no simple fix. The proper fix for this would be to add yet another pair of planes _below_ GAME_PLANE for normal and FOV-hidden things. A dirty fix could potentially be to just move larva to GAME_PLANE when they hide but then they'd be visible through FOV which is far from ideal.

**Comment by Shadowflame909** [comment] 2022-10-16 08:14
Should just give larva sentinel camouflage

**Comment by Ghommie** [comment] 2024-03-09 21:34
Fixed by the FoV rework a while ago.

**Closed by Ghommie** 2024-03-09 21:34 UTC
Labels: Bug, Tested/Reproduced
