### ISSUE TITLE
Unable to dump items onto a table.

### ISSUE THREAD

**Issue by BigGrease** [tgstation/tgstation#68660] opened 2022-07-22 16:06 UTC
Reporting client version: 514.1585

## Round ID:
[187089](https://scrubby.melonmesa.com/round/187089)

## Testmerges:
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:

Player is able to dump items from a container such as a box onto the floor, but unable to do so on a table. Frustrating because items like food rot on the floor, but not on a table, so they have to move them. To reproduce this issue, first place a box with items in it onto a table. I first noticed it with an egg box. Try to drag the box sprite onto the table sprite. In my case, **simply nothing happened.** Now, try to drag the box sprite onto a nearby floor tile sprite. It will dump the items and empty the container normally. Previously, emptying boxes was possible on a table, but due to this issue it isn't.

**Comment by Mothblocks** [comment] 2022-07-23 05:33
Duplicate of #68374

**Closed by Mothblocks** 2022-07-23 05:33 UTC
