### ISSUE TITLE
Bluespace shelter capsules are impossible to escape from with Protokinetic Crushers

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26085] opened 2017-04-11 01:08 UTC
Server Revision: 8d1ee2267ad7231824b725baffd96daa643cdfc2 

If you only have the protokinetic crusher and you activate a bluespace shelter capsule, you can become trapped if the shelter's airlock is against rock like this.  There is air in the shelter, so the crusher will click and be unable to mine the rock.

![issue](https://cloud.githubusercontent.com/assets/9963278/24888431/5494e0a8-1e18-11e7-82bb-bcc09b32173e.PNG)

**Comment by Cyberboss** [comment] 2017-04-11 01:27
Not a bug, get a pick

**Comment by KorPhaeron** [comment] 2017-04-11 03:02
Nobody outside the gulag has used a pick for mining since ~2013

**Comment by GunHog** [comment] 2017-04-11 03:22
Add a pickaxe to the storage thing inside the capsule if there is not one already.

**Comment by Repukan** [comment] 2017-04-11 03:28
Why not just carry the free KA you get roundstart as well.

Or the pocket picks. This is easily preventable if you bothered to examine your crusher and understand how it works. Stop hand holding players.

**Comment by Expletive** [comment] 2017-04-11 03:41
@Repukan 

Carrying around a Crusher and an accelerator is extremely awkward. The crusher can only be stored on your back and can't even be carried in one hand. If you want to carry around an accelerator, then you could store in on your explorer suit, except you need an oxygen tank. You could store it on your belt, except you have an explorer's webbing there to hold all your miscellany. You could drag it on the floor behind you, except you have to have an ore box. You could carry it in your hands, but then you have to drop it if you use the crusher, and by that point, you may as well not even have the crusher, because the accelerator is more useful in basically every way.

**Comment by Repukan** [comment] 2017-04-11 03:43
Or you can also

Bear with me

You could grab

Keep reading

The compact pickaxe that you get roundstart

**Comment by octareenroon91** [comment] 2017-04-11 05:11
Kor I carry a pick.

**Comment by Cyberboss** [comment] 2017-04-11 05:40
Not. A. Bug!

**Comment by xxalpha** [comment] 2017-04-11 06:24
Yeah this isn't a bug, be mindful of where you spawn the capsule.

**Comment by Jalleo** [comment] 2017-04-11 08:32
We should make it more clear that this prevents the crusher device from working.

**Comment by xxalpha** [comment] 2017-04-11 11:58
It's perfectly clear, but the capsule isn't a vacuum. This isn't a bug, it's a player getting himself stuck by walling himself intentionally.

**Comment by Dorsisdwarf** [comment] 2017-04-11 12:11
But there should be a way around this. Just add a safety pickaxe or whatever to the storage in it

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-04-11 14:19
>But there should be a way around this. Just add a safety pickaxe or whatever to the storage in it

:u help i'm stuck on lavaland come get me please.

or just carry a pick with you if you're using the crusher.

Using the "hardmode" item and not being prepared is entirely YOUR fault, so I don't understand why we have to handhold here.

**Comment by Jalleo** [comment] 2017-04-11 16:36
Its the capsule at fault. Not the mining item.

**Comment by Repukan** [comment] 2017-04-11 16:51
It's the player at fault, not the capsule

**Comment by xxalpha** [comment] 2017-04-11 17:21
What if the player does this but against a wall? You can't tear down the wall with the pickaxe. Are you going to say the capsule needs to be equipped with a toolbox?

**Comment by Cyberboss** [comment] 2017-04-11 17:37
@KorPhaeron

**Comment by octareenroon91** [comment] 2017-04-11 17:43
An emergency toolbox does have a welder, which puts you closer to breaking out whichever direction you came from

**Comment by FantasticFwoosh** [comment] 2017-04-11 17:50
@KorPhaeron diamond pickaxes from vendor are still pretty good. Drills are expensive, and practically identical to picks. Not carrying one in the times that a bluespace crystal might teleport & lodge you into the middle of a rock wall is suicide on lavaland.

> @octareenroon91 i can see how this IS a problem (IF) you had no digging tools like you suggest but there are other FEATURE ways around it such as equipping a Jaunter or carrying additional tools for deconstructing walls with you.

One possible solution is to VERY SLOWLY and for hand damage, dig the wall out with your hands (a idea off the top of my head) but we are currently in a freeze so no features until it subsides.

**Comment by Repukan** [comment] 2017-04-11 17:59
Or we could just leave the capsules and digging as is since there's no problems with it and these changes only came about because of unpreparedness

**Comment by FantasticFwoosh** [comment] 2017-04-11 18:07
@Repukan true. 

But rock walls don't have destructibility like the rest of objects in the game covered by phil's PR which makes it much less simple than smashing the surface with the PkC or the guitar in storage.

**Comment by Repukan** [comment] 2017-04-11 18:10
Not everything needs to be destroyable

**Comment by FantasticFwoosh** [comment] 2017-04-11 18:46
If only repukan if only... #20793

**Comment by optimumtact** [comment] 2017-04-12 04:22
@Dorsisdwarf if you're gonna tag something not a bug just close it and direct the person to the feedback forum

**Closed by optimumtact** 2017-04-12 04:22 UTC
Labels: Not a bug
