### ISSUE TITLE
If you unwrench the griddle and move it while there's food cooking, there are two instances of the food

### ISSUE THREAD

**Issue by jacklecroy** [tgstation/tgstation#68705] opened 2022-07-24 03:06 UTC
The actual food items don't get moved with the griddle, but it looks like they do. You'll see the items on the floor where the griddle originally was. The fake item on the griddle can't be picked up, but it will cook.

**Comment by CoffeeDragon16** [comment] 2022-07-24 13:20
Couldn't reproduce on local

**Comment by jacklecroy** [comment] 2022-07-30 02:28
![](https://i.imgur.com/XJUUZ3B.png)

Just reproduced it.

**Comment by Mooshimi** [comment] 2022-08-23 00:33
PS: which is the real food???

**Comment by jacklecroy** [comment] 2022-08-27 04:18
On the floor

**Comment by TheBoondock** [comment] 2022-12-03 19:30
Couldnt reproduce this either

**Comment by Sealed101** [comment] 2024-10-23 20:18
can't reproduce; time heals all (and brings more robust code for transferring items and for signal handling)

**Closed by Sealed101** 2024-10-23 20:18 UTC
Labels: Bug, Tested/Reproduced
