### ISSUE TITLE
The glockenspiel sounds real fucken weird

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35053] opened 2018-01-28 09:49 UTC
When you play a song on the glockenspiel the tuning sounds a bit out. Really obvious on Chopin's funeral march.

**Comment by ArcaneMusic** [comment] 2020-11-02 00:58
It seems more or less fine to me. We recently had a rework of the instruments, so I'd like to hear what @silicons thinks if this is resolved or not.

**Comment by timothymtorres** [comment] 2022-03-28 21:37
Marking this as `Not a Bug` and it will autoclose in 7 days.

**Closed** 2022-04-05 05:23 UTC
Labels: Sound, Not a bug, Cleanup Flagged
