### ISSUE TITLE
Papier-Mch Robe spelt wrong

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22609] opened 2016-12-31 07:23 UTC
Papier-Mch Robe spelt wrong

**Comment by Mervill** [comment] 2016-12-31 08:10
Duplicate of #22609

**Comment by lzimann** [comment] 2016-12-31 11:56
It has a special character that acts weird in byond `name = "papier-mâché robe"`

**Comment by optimumtact** [comment] 2017-01-01 10:38
People need to stop using non latin characters

**Comment by Mervill** [comment] 2017-01-01 10:41
Préparez-vous à mourir infidèle!

**Comment by Mervill** [comment] 2017-01-01 16:57
@optimumtact implying that the solution is to change this too `mache`? I swear I've seen non-latin characters in other places. Or is it that older clients can't render them?

**Comment by Jordie0608** [comment] 2017-01-02 04:32
Yes that's really the best answer here.

**Closed** 2017-01-03 18:52 UTC
Labels: Grammar and Formatting
