### ISSUE TITLE
Triangulation objective is borke

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#67852] opened 2022-06-18 05:49 UTC
RoundID 185106

got triangulate objective, went to one of the two spots (robotics lab) and tried to triangulate but it said i already scanned. go to other spot (cargo secpost) same thing. mothblock helped me fix it they are based

**Comment by timothymtorres** [comment] 2022-06-18 14:35
Duplicate of #67838

**Closed by timothymtorres** 2022-06-18 14:35 UTC
