### ISSUE TITLE
Anti-breach shields fly in space

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#76268] opened 2023-06-22 23:44 UTC
## Reproduction:

Raven shuttle, turn on shield in hyperspace
https://youtu.be/5sHWVjJHuuM

**Comment by ZephyrTFA** [comment] 2023-06-23 00:08
duplicate of https://github.com/tgstation/tgstation/issues/76172

Please atleast do a cursory look for the issue already being present

**Closed by ZephyrTFA** 2023-06-23 00:08 UTC
