### ISSUE TITLE
MMIs in mechs do not work

### ISSUE THREAD

**Issue by Nilons** [tgstation/tgstation#35470] opened 2018-02-08 23:52 UTC
Issue reported from  Round ID: 83292 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

When an MMI or positronic is put into a mech it works until you try to move, at which point you get the message that you're climbing out of it every time you try.  Your mech hud disappears when you try to move as well.

**Comment by YPOQ** [comment] 2018-02-09 00:34
#34408

**Comment by AnturK** [comment] 2018-02-09 08:40
Duplicate of #34408

**Closed by AnturK** 2018-02-09 08:40 UTC
Labels: Bug
