### ISSUE TITLE
Backpack contents just randomly became...inaccessible?

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#84968] opened 2024-07-14 23:54 UTC
Reporting client version: 515.1640

## Issue Summary

Despite the bag seemingly accepting objects due to it having a storage component, trying to access or look in that storage would not work whatever. The backpack could be emptied by dumping the contents, but trying to show the inventory was impossible. It was an industrial backpack in the possession of Initiates-the-Lizard in the linked round.

## Round ID:
[232109](https://scrubby.melonmesa.com/round/232109)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

I have absolutely no idea.

**Comment by necromanceranne** [comment] 2024-07-15 00:01
This could be related to https://github.com/tgstation/tgstation/issues/84507, but I believe this isn't an identical bug as the necessary steps to work around that bug were not working to correct this occurrence. There was no visible rendering of the inventory whatsoever, unlike here where the background was the only thing not being rendered.

I checked to see if this bug was related by trying to insert objects into the bag, but I couldn't see anything the bag at all. That bug could be resolved by emptying the contents of the storage and then filling it up again. Here, that wasn't working. It wasn't rendering in the first place.

**Comment by plutori** [comment] 2024-07-15 07:11
Not sure if any of this will help, but the bag did accept items being placed into it, however, when accessing the bag, something strange would happen - it only showed certain items. In this shift I was a flesh heretic engineer (hence the industrial backpack), and I had my extended capacity survival box, a fire extinguisher, an RCD, a bar of soap, and two flesh heretic blades. However, upon accessing the bag, it would only display the sprites for certain items - like the survival box, the RCD, and the fire extinguisher. It did not display my soap and blades, and additionally, I could not remove any items from the bag by the usual method of clicking on them. Additionally, the err... UI element? HUD element? Not sure which of those it is, but whichever one displays the grid for the bag did not load at all, ONLY the sprites of the aforementioned items loaded. Also, this state of affairs continued after dumping all of my items into the ground and re-placing them in the backpack. Doing so did not change or fix anything, and the same items were displayed or not displayed as before.

**Comment by Sadboysuss** [comment] 2024-07-15 08:51
dupe of https://github.com/tgstation/tgstation/issues/84507

**Closed** 2024-07-15 09:09 UTC
