### ISSUE TITLE
Shuttle only half took off

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#55531] opened 2020-12-14 19:11 UTC
Round ID: [152170](https://scrubby.melonmesa.com/round/152170)

![image](https://user-images.githubusercontent.com/609465/102124338-0e14b800-3e40-11eb-9aba-2a7cfeff8e85.png)

Was a service borg, in the upper 2/3 of the shuttle, was left behind, bottom 1/3 of shuttle remained at station.

**Comment by ArcaneMusic** [comment] 2020-12-15 15:29
Duplicate of #47574.

**Closed by ArcaneMusic** 2020-12-15 15:29 UTC
Labels: Bug
