### ISSUE TITLE
Guardian gets ghosted if host exits ash drake form (sometimes?)

### ISSUE THREAD

**Issue by yeeyeh** [tgstation/tgstation#48841] opened 2020-01-17 02:10 UTC
## Round ID:
128325

## Testmerges:
#48583 

## Reproduction:
As a Shaft Miner, acquire a deck of tarot cards and get a Guardian Spirit. Then get dragon blood from an Ash Drake and acquire the Ash Drake form spell. Enter ash drake form and exit it while your guardian isn't active. Presto majesto your guardian is now ghosted (possibly, the miner was able to exit ash drake form once before it ghosted the guardian, but it ghosted the second time.)

**Comment by Taylorkills2** [comment] 2020-01-19 04:56
Usually becoming a simplemob ghosts Guardians/Holos. Interesting it happens the other way around, probably happens with vampires and change form wizards.

**Comment by adamkad1** [comment] 2020-02-17 17:25
> Usually becoming a simplemob ghosts Guardians/Holos. Interesting it happens the other way around, probably happens with vampires and change form wizards too.

Yeah, you are actually still alive when they are drake, but you are buckled to shapeshifed or something and you cant come out

**Comment by SuperNovaa41** [comment] 2021-05-15 21:19
Duplicate of https://github.com/tgstation/tgstation/issues/25287

**Closed by SuperNovaa41** 2021-05-15 21:19 UTC
Labels: Bug
