### ISSUE TITLE
Sentient Disease "Adaptation Menu" stopped responding and wouldn't reopen

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#75017] opened 2023-04-28 10:48 UTC
## Round ID:
[R204564](https://tgstation13.download/parsed-logs/manuel/data/logs/2023/04/27/round-204564/)

At some point during the round, the adaptation menu stopped responding entirely. After closing it, I could no longer reopen it by clicking the button for it. I can't remember if there is also a verb to reopen it in the stat panel, but if there is, then I would've tried that too, and it didn't work.

Relogging or relaunching the game didn't work. Being ghosted and returned into the disease by admin might have worked, but I got cured before we could try that.

Prior to losing the adaptation menu, I also noticed several odd behaviours. Namely being unable to infect some people that seemed eligible for it, such as by coughing or secretions, and my hosts each displaying a different icon of disease state ranging from none(classic medical cross)-blue-green-yellow. It's only my assumption that all my hosts should have identical icon displayed, it's entirely possible the icons changed depending on what stage their infection is at.

**Comment by OneAsianTortoise** [comment] 2023-04-29 13:51
#43830

**Comment by ZAMODA** [comment] 2023-04-30 05:48
had this issue on R204748 as well, why is sentient disease so bugged, its such a good concept

**Comment by Sealed101** [comment] 2023-05-12 14:50
dupe of #43830 as mentioned above

**Closed by Sealed101** 2023-05-12 14:50 UTC
