### ISSUE TITLE
Detonating a parcel'd cardboard box with multiple grenades in it causes multiple odd outcomes

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#63414] opened 2021-12-14 22:44 UTC
A long time ago, i tested on how Box parcel sticky bombs would work, so i put 1 signaller waterpot grenade and 5+ improvised firebombs into the box before wrapping it into a parcel and applying sticky tape, i then threw it at a test felinid i spawned on my test server, it stuck and i detonated the grenade. Only one grenade in the entire parcel went off and didn't cause a chain reaction explosion and on top of that when the parcel fell off of the felinid, which was still intact after the explosion, i unwrapped the parcel and the box was still intact too with all 6 sodacan IEDs in it.

**Comment by timothymtorres** [comment] 2021-12-15 11:23
@tohg7 would you mind doing some more testing for this bug report?

What are the effects on explosions for the following:

- with several IEDs on the floor (same tile)
- with several IEDs in a box on the floor
- with several IEDs in a box being held by a mob

This might be a duplicate of an older issue that was closed.  I also suspect that the sticky tape makes the parcel embed to the mob which may not be getting checked in the explosion code.

**Comment by TheBonded** [comment] 2021-12-16 19:00
>This might be a duplicate of an older issue that was closed

Can you link that issue please?

**Comment by timothymtorres** [comment] 2021-12-16 19:54
It was #27049

**Closed** 2024-10-23 12:06 UTC
Labels: Consistency Issue, Tested/Reproduced
