### ISSUE TITLE
Chameleon guns, when switching to staff of locker, spawn 2 enchanted lockers

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#79277] opened 2023-10-25 22:11 UTC
Reporting client version: 514.1589

## Reproduction:

1. Get a chameleon gun from a chameleon kit
2. Switch to the locker staff
3. Cause a premature shuttle call as people see enchanted lockers and assume theres a wizard

**Comment by nikothedude** [comment] 2023-10-25 22:12
Runtimes: 
![image](https://github.com/tgstation/tgstation/assets/59709059/dde2b3f5-7325-4eeb-833c-c92a7bc67118)

The 3rd runtime is from another cham gun issue I will report

**Comment by MrMelbert** [comment] 2023-10-25 22:50
Dupe of #67618

**Closed** 2023-11-02 00:07 UTC
Labels: Cleanup Flagged
