### ISSUE TITLE
Additional Cloning Pods cannot be added to Cloning Computers

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#45721] opened 2019-08-05 02:19 UTC
Issue reported from  Round ID: 115133 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1475

How to reproduce:

1. make your own cloning computer, scanner, and two or more pods

2. Link both pods to the cloning computer

3. Scan a guy

4. Attempt to empty clone using both pods at once

5. Watch as the first pod starts cloning

5. Initialization error on the second pod

6. Cry

**Comment by Dennok** [comment] 2019-08-05 06:26
Last time as i build cloning it work as intended and i clone 6 bodies at time.
But in one time i find himself unable to empty clone in standard one pod cloner.

**Comment by Time-Green** [comment] 2019-08-05 08:17
Were they all in the same area?

**Comment by Shirbu** [comment] 2019-08-05 16:02
They were all in the same app area, adjacent to one another in the engineering lobby

**Comment by Shirbu** [comment] 2019-08-05 21:18
I highly suspect the issue lies here, but am too stupid to parse much of it.
https://github.com/tgstation/tgstation/blob/master/code/game/machinery/computer/cloning.dm

**Comment by Shirbu** [comment] 2019-08-06 03:22
![bug_in_action](https://user-images.githubusercontent.com/23252965/62509095-b895b900-b7be-11e9-8bd8-407746b42370.PNG)

**Comment by Shirbu** [comment] 2019-08-06 06:38
It turns out the issue persists even with medical's cloning computer now.
![buginactionagain](https://user-images.githubusercontent.com/23252965/62516518-2c918a80-b7da-11e9-9bdf-4de723bbfa81.PNG)

**Comment by PKPenguin321** [comment] 2019-08-07 02:58
You should leave the issue open until the fix is merged

**Comment by Shirbu** [comment] 2019-08-07 05:32
I will remember that for next time, thank you

**Comment by Cyprex** [comment] 2019-08-07 08:07
NOrmally PRs should have "Fixes #45721" "Closes #45721" or similiar too, this automatically closes the listed issues once the PR is merged

**Comment by Shirbu** [comment] 2019-08-07 08:53
Ah, thanks for the info.

**Closed** 2019-08-08 23:29 UTC
Labels: Bug
