### ISSUE TITLE
Fire doesn't seem to work well

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#38660] opened 2018-06-22 09:58 UTC
I've been consistently having trouble getting a good plasma fire going recently, with something as simple as just releasing a canister of plasma and setting it on fire in normal air. Normally, this would result in an inferno, but as of late it seems to be totally ineffective, the fire mostly going out immediately.

**Comment by Tlaltecuhtli** [comment] 2018-06-22 10:09
minimum fire temp changed some months ago

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-06-22 16:24
drastically, might I add.

**Comment by Arianya** [comment] 2018-06-22 17:36
Duplicate of #38251

**Closed** 2018-06-22 18:30 UTC
