### ISSUE TITLE
You can get trapped inside a DNA infuser (in its contents)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72365] opened 2022-12-30 01:09 UTC
Reporting client version: 514.1589

## Round ID:
[197268](https://scrubby.melonmesa.com/round/197268)

## Testmerges:
- [Refactor air alarm TLV and modes.](https://www.github.com/tgstation/tgstation/pull/72315)
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

Spawn a machinery/dna_infuser
Spawn a test human, and yourself
Put human inside infuser
![image](https://user-images.githubusercontent.com/3789327/210024943-f53f0075-d8a0-44be-843d-26810b777831.png)
Close door
Drag yourself onto infuser
You will climb inside
Move out of infuser
Other person stuck inside (can be PP "Get" brought out)
![image](https://user-images.githubusercontent.com/3789327/210024991-c2c9ae8d-e85a-4234-91bc-9f31e4a2d809.png)

**Comment by SyncIt21** [comment] 2022-12-31 13:23
duplicate of #71827

**Closed** 2023-01-14 18:49 UTC
