### ISSUE TITLE
Printing things in autolathes/protolathes/circuit imprinters does not cost money

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40444] opened 2018-09-23 14:43 UTC
A MASSIVE BUG FIX IT PROMPTLY

**Comment by buildmaster668** [comment] 2018-09-23 14:44
No no we gotta make the crew buy ink cartridges for the autolathes!

**Comment by evsey9** [comment] 2018-09-23 15:56
its not a bug

**Comment by Barhandar** [comment] 2018-09-23 16:17
It's absolutely a bug

**Comment by Grazyn** [comment] 2018-09-23 16:30
Fun fact: assistants earn so little, that after 1 hour they are only able to afford 3 tools from the YouTool, assuming they save every penny of their paychecks and don't earn money in other ways.

**Comment by Iatots** [comment] 2018-09-23 18:11
Why should printing cost money? You bring your own materials, and hardware+labor comes either from you, a person in charge of the workplace, or from someone else that let you have access to the hardware. (in exchange for money, I assume).

You could argue for intellectual property, but expect a kneejerk piracy PR that lets you hack printers with circuits.

**Comment by Barhandar** [comment] 2018-09-23 18:15
>comes either from you, a person in charge of the workplace

Because you have to pay for the tools and clothes in the department vendors. Why would tools, and, indeed, anything from the protolathes be free?
>You bring your own materials
 
All materials belong to Nanotrasen. You have to pay them to use these. Check the point 563, sub-point 5 of your contract, in small font.

**Comment by evsey9** [comment] 2018-09-23 19:29
economy was a mistake and it getting merged is a clear sign of tg's maintainers and coders going senile/having brain cancer/having iq below 10/being retarded/being bored out of their mind and wanting to see the codebase burn

**Comment by Iamgoofball** [comment] 2018-09-23 21:15
>printing to cost money

This is actually on the todo list.

**Comment by evsey9** [comment] 2018-09-23 21:51
> > printing to cost money
> 
> This is actually on the todo list.

Don't you fucking dare you sick fuck
Actually make the system not shit before trying to do anything else

**Comment by optimumtact** [comment] 2018-09-23 22:04
assistant main reporting in

**Comment by Barhandar** [comment] 2018-09-23 22:50
>This is actually on the todo list.

poe's law in action, everyone

**Comment by evsey9** [comment] 2018-09-24 02:51
None of those changes would affect me because I don't play a job where money affects me at all because economy is broken but I still know its a bad change

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-09-24 16:03
time to ban from mining so you too must suffer...

**Comment by Barhandar** [comment] 2018-09-24 16:15
@ExcessiveUseOfCobblestone just make miners have to pay $1 per each mining point they get from ore in the ORM

**Comment by Iamgoofball** [comment] 2018-09-24 17:32
https://file.house/jLeb.png

>make money worth shit

>but dont block anything off with it

pick one

**Comment by evsey9** [comment] 2018-09-24 17:35
Making every vendor use cash isn't making it have any worth. Being able to actually get something only using money and not requiring cargo access would.

**Closed** 2019-03-31 23:46 UTC
