### ISSUE TITLE
Hallway tiles are dark on some maps and it looks like a lighting glitch

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#27110] opened 2017-05-10 07:51 UTC
Certain areas in hallways on various maps contain dark portions that don't smoothly transition between tiles.

![example](https://i.gyazo.com/5fc82138a572ef26579a145efdf46538.png)

as you can see the middle of the hallway is suddenly dark, even though smooth lighting is working in other places. I've only seen this happen in hallways, but it can happen on every map it seems.

**Comment by Cyberboss** [comment] 2017-05-10 16:49
@MrStonedOne

**Comment by octareenroon91** [comment] 2017-05-10 17:33
I think it might be an optical illusion on that map.

**Comment by MrStonedOne** [comment] 2017-05-10 18:08
what map is that? meta?

**Comment by Tacolizard** [comment] 2017-05-10 18:39
@MrStonedOne This is deltastation

**Comment by ChangelingRain** [comment] 2017-05-10 19:14
This doesn't look strange, though?

**Comment by RemieRichards** [comment] 2017-05-10 19:15
@ChangelingRain the stripe down the middle, look how close it is to the light fixture.

**Comment by MrStonedOne** [comment] 2017-05-10 19:19
Ya, its the map, not lighting, those are intentionally darker tiles.

Look at the tiles in the firelocks, compare them with the grey tiles in the center going down.

**Comment by RemieRichards** [comment] 2017-05-10 19:20
I mean yes, it's an illusion, but it doesn't mean it's good or should stay.

**Comment by MrStonedOne** [comment] 2017-05-10 19:21
![image](https://cloud.githubusercontent.com/assets/7069733/25916887/16cd8d7c-357b-11e7-94af-9109307cc332.png)
I'm just saying its not a lighting issue caused by my lighting refactor.

**Comment by RemieRichards** [comment] 2017-05-10 19:22
yeah that's fine, and I'm just saying that it doesn't mean it's not still AN issue :P

**Comment by Tacolizard** [comment] 2017-05-10 21:23
how did they make those tiles darker?

**Comment by RandomMarine** [comment] 2017-05-12 00:34
Does a mapper's aesthetic choice need to stay on the issue tracker?

**Comment by ChangelingRain** [comment] 2017-05-12 00:36
these were darker because warning tiles didn't used to come in lighter grey
not a bug

**Closed by ChangelingRain** 2017-05-12 00:36 UTC
