### ISSUE TITLE
Indestructible structures keep exploding by tesla

### ISSUE THREAD

**Issue by yoyobatty** [tgstation/tgstation#40751] opened 2018-10-06 19:55 UTC
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Indestructible structures such as buttons do not get deleted by explosions caused by Tesla, causing continuous and laggy explosions in that area. 

I might suggest making buttons not indestructible or having indestructible items not be affected by Tesla.

**Comment by PKPenguin321** [comment] 2018-10-06 20:38
they probably should not be indestructible in the first place im guessing

**Comment by Barhandar** [comment] 2018-10-06 22:05
Dupe-ish of #40523

**Comment by ShizCalev** [comment] 2018-10-07 04:29
duplicate of #40523

**Closed by ShizCalev** 2018-10-07 04:29 UTC
