### ISSUE TITLE
Body sprite got completely fucked up after getting a leg reattached

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#73362] opened 2023-02-11 15:25 UTC
## Reproduction:
I got my leg shot off with a plasma cutter, took it to medbay to have it reattached, and when it got reattached my sprite got totally fucked up. Hole in chest and leg, both arms appeared attached to my waist.
![image](https://user-images.githubusercontent.com/22856555/218266547-9ee057a9-d0e1-4427-8a86-b3b982b80c78.png)
I had surgery again later on to have an arm replaced with a chainsaw and when my arm was removed the sprite returned to normal and it didn't break again when the chainsaw was attached.

**Comment by itseasytosee** [comment] 2023-02-11 18:01
Are you sure there where no testmerges? This looks like it could possibly come from my PR.

**Comment by ZephyrTFA** [comment] 2023-02-15 16:34
Duplicate of #73154

**Closed by ZephyrTFA** 2023-02-15 16:34 UTC
