### ISSUE TITLE
Posimechs (maybe normal mechs too) cannot go up or down z-levels using the verbs move-upward and move-down. Any attempts to do this will result in your soul being separated from your body.

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#63134] opened 2021-11-29 02:35 UTC
## Round ID:
Skyrat round, the one that started on 11/28/2021, at 6:05 PM EST. 

## Reproduction:
Step 1: Get someone to put you, a posibrain, into a mech.
Step 2: Go to an area of space that has a z-level above it. Not a common thing on TG, but it is on skyrat.
3. Use the go-upward verb. It will say you went up, but your camera remains on the mech and the mech still is active. You can still use it. Your audio will cut out, because your mind has been moved upward-not the posibrain nor mech. The bug is now active.

This bug has a TON of fucky consequences. The first and most obvious is that you can only hear around the mind you left behind, and all speech will be centered on that. Im fairly sure all weapons will also fire from your mind instead of the mech. Also, If you try to eject from the mech, your camera will snap back to your mind, and your posibrain will be left behind-which can be put into a new mech. I also found out that its somehow possible to put the brain into MULTIPLE mechs, the most recent of which you can move... but all of which you can control. Fire the weapons. use abilities. Etc. Etc. Etc.

This bug is also somewhat prseent with carbons. Try to move-upward as a normal pilot-your camera will remain on the mech, but yoru body will move up. Aghosting and reentering will reset camera position.

NOTE. THIS MIGHT BE LOCAL TO SKYRAT IF THE PERSON I ASKED IS WRONG. GoldenAlpharex, a skyrat coder I trust, told me it's an upstream issue, so I'm making an issue report here, not on skyrat.

Also, obligatory silly screenshot.
![image](https://user-images.githubusercontent.com/59709059/143799905-a46a6851-05c8-4619-b4bd-a93543b137dc.png)

**Comment by timothymtorres** [comment] 2022-07-30 02:33
Duplicate of #45691

**Closed by timothymtorres** 2022-07-30 02:33 UTC
Labels: Needs Reproducing
