### ISSUE TITLE
Character Temperature not changing, dealing constant damage

### ISSUE THREAD

**Issue by SkatesMcGates** [tgstation/tgstation#56273] opened 2021-01-19 19:36 UTC
## Round ID:
**154587**

## Reproduction:
Upon entering SM, it was accidentally turned on by someone too early and caught fire. This increased my character's temperature. My temperature remained high and I got constant damage, and upon realizing, I went into the showers. I tried freezing cold showers and regular showers, but my temperature would not change back to normal (though it would change to other drastic temps, such as freezing cold to hot or vice-versa).

I then went to medbay and spent several minutes under normal temperature showers in rooms I knew for certain were at room temperature, yet my temperature didn't go down. I then went into cryo but after exiting, my temperature stayed at extremely cold and did not go down, which ended up killing me.

**Comment by LemonInTheDark** [comment] 2021-01-20 02:47
Potentially related to https://github.com/tgstation/tgstation/pull/55534

**Comment by sqnztb** [comment] 2021-01-20 14:29
Have seen this several times on Manuel yesterday. Was hit with super cold body temps yesterday and chugged a bunch of coffee which worked until it metabolized out. A dose of leporazine was the only thing that seemed to "permanently" fix super cold temps.

**Comment by antropod** [comment] 2021-01-21 01:53
I bet its caused by "Humans have more complicated body temperatures" #54550 by Nightred@
I tested on master without delta_time PR, (#55534), it still reproduces

How to reproduce: take 2u of frost oil, watch your body temp stabilize @ 10C

**Comment by Mothblocks** [comment] 2021-03-10 06:08
Should be fixed by now.

**Closed by Mothblocks** 2021-03-10 06:08 UTC
