### ISSUE TITLE
tramstation xenobio has no slimes at all 

### ISSUE THREAD

**Issue by mrspydereal** [tgstation/tgstation#74068] opened 2023-03-17 08:46 UTC
[Round ID]: all rounds on tramstation 

## Reproductions 

the mapper who remade sci and xenobio in tramstation forgot to put slimes in making it impossible to do xenobio (i dont know if cargo has silmes crate order)
![(null)scrnshot1](https://user-images.githubusercontent.com/128129602/225856194-056fefe8-55a2-4388-8b7e-b0315709e43d.png)

**Comment by Sealed101** [comment] 2023-03-17 08:56
duplicate of #73984 and it has had a fix merged a few hours ago, the servers should update soon

**Comment by mrspydereal** [comment] 2023-03-17 08:57
> duplicate of #73984 and it has had a fix merged a few hours ago, the servers should update soon

good to know

**Closed by Sealed101** 2023-03-17 08:56 UTC
