### ISSUE TITLE
Bodies infected with headslugs eggs that become blob zombies, cuase some strange things to happen.

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#29213] opened 2017-07-12 04:56 UTC
Start by being a headslug. Lay eggs in body. Body is then taken over by blob spore becoming  a blob zombie. When the eggs hatch you will come back as the body you infested before promptly loosing all your organs, and then being alive but unable to move.

**Comment by Armhulen** [comment] 2017-07-12 08:21
edge case

**Comment by Shadowlight213** [comment] 2017-07-13 02:05
Dupe of #27757

**Closed** 2017-07-13 06:50 UTC
