### ISSUE TITLE
Deltastation only has two water coolers in the whole station.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#68237] opened 2022-07-07 01:46 UTC
## Reproduction: The only water coolers there is is one in the genetics->range room in maint and one in the psychs office. Seems like a oversight if the chef wants to make snowcones he'd have to get maint access or psych access instead of going somewhere like dorms.

![image](https://user-images.githubusercontent.com/54517726/177672478-380fa24c-4286-4c5d-9cdb-53f9cf30ce32.png)

![image](https://user-images.githubusercontent.com/54517726/177672519-d69b63b2-782a-4338-81c8-6373d44e4ac0.png)

**Comment by Baskett55** [comment] 2022-07-07 06:09
> Maybe the real oversight is that cooks require a water cooler to get `/obj/item/reagent_containers/food/drinks/sillycup` to make snow cones?
> 
> Probably should have another way to get them, maybe via cargo, the grocery console, or the dining ware vendor.

Turns out the ice cream cart can make paper cups, I'm blaming the wiki since it says you should get them from the water coolers
https://github.com/tgstation/tgstation/pull/65926

**Comment by timothymtorres** [comment] 2022-07-07 22:44
Make them craftable from regular paper?

**Comment by timothymtorres** [comment] 2022-07-07 23:45
Relevant code:

https://github.com/tgstation/tgstation/blob/0500233244a532a6445651695042592ebfb18b50/code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm#L72-L81

https://github.com/tgstation/tgstation/blob/adcfe30c1984c24ae072da690fb5e0487046a5da/code/datums/components/crafting/recipes.dm#L786-L791

I'm marking this as `Not a Bug` since paper is readily available all across the station.

**Closed** 2022-07-14 16:56 UTC
Labels: Not a bug, Cleanup Flagged
