### ISSUE TITLE
Midround Changeling W/O Fine-Tipped Screwdriver

### ISSUE THREAD

**Issue by PrismaticLoop** [tgstation/tgstation#77006] opened 2023-07-21 12:18 UTC
Reporting client version: 514.1589

## Round ID:
[210708](https://scrubby.melonmesa.com/round/210708)

## Reproduction:

Spawned in as a midround changeling with the "Steal the heavily radioactive plutonium core from the onboard self-destruct" Objective, but did not spawn with the necessary "fine-tipped" screwdriver necessary to start the extraction process.

**Comment by Sealed101** [comment] 2023-07-21 20:26
Duplicate of #45296

**Comment by Sealed101** [comment] 2023-07-21 20:27
however that means that the bug is still present, which is not a good tell. thanks for reporting either way

**Closed by Sealed101** 2023-07-21 20:27 UTC

**Comment by distributivgesetz** [comment] 2023-07-24 17:27
This was fixed in https://github.com/tgstation/tgstation/pull/60789, you should get an action button to call in a droppod
