### ISSUE TITLE
Character Preferences menu shows non-plasma-person options on plasma person page

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#86686] opened 2024-09-15 21:55 UTC
### Client Version:

515.1643

### Issue Summary:

When a user opens the character preferences menu and selects a plasma-person character they are shown non-plasmoid options such as moth antennae, lizard body marking and pod person hair style.

![image](https://github.com/user-attachments/assets/b0ea357b-70fb-4894-bfe5-2665d0b9739f)

### Round ID:

[238050](https://scrubby.melonmesa.com/round/238050)

### Test Merge Information:

- [Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. Join a TG server.
2. Open Character preferences.
3. Select a saved plasma person character.
4. Observe non-plasmoid character options.

**Comment by OuroborusReporter** [comment] 2024-09-16 01:30
#86682

**Comment by Time-Green** [comment] 2024-09-16 05:30
Duplicate of https://github.com/tgstation/tgstation/issues/86622

**Closed by Time-Green** 2024-09-16 05:30 UTC
