### ISSUE TITLE
Captain's hardsuit isn't fire immune

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#46551] opened 2019-09-16 04:51 UTC
## Reproduction:

1. make a plasma flood
2. wear atmos suit
3. wear captain suit
4. notice overpressurization and incineration, and take damage

**Comment by carlarctg** [comment] 2019-09-16 04:51
apparently this is also is in a few closed issues so what the fuck

**Comment by carlarctg** [comment] 2019-09-16 04:54
i can't find anything in the code that even does this, both have the exact same vars that protect them from fire

**Comment by ShizCalev** [comment] 2019-09-16 05:51
Duplicate of #42005

**Closed by ShizCalev** 2019-09-16 05:51 UTC
