### ISSUE TITLE
You can delete yourself with a bluespace bodybag

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#68313] opened 2022-07-10 07:25 UTC
## Round ID:
[186393](https://scrubby.melonmesa.com/round/186393)

## Reproduction:

https://imgur.com/a/JTjFPqK

Lay out a bluespace body bag, lie down in it, left click to close it, then right click it from within

**Comment by timothymtorres** [comment] 2022-07-10 08:59
Duplicate of #64631

**Closed by timothymtorres** 2022-07-10 08:59 UTC
