### ISSUE TITLE
Deconversion messages not displaying

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#26742] opened 2017-04-30 19:45 UTC
Server revision compiled on: 2017-04-30
The following pull requests are currently test merged:
#26361: ' Refactors explosions. Removes startup delays' by Cyberboss 

Based off master commit:
69bb2911399a01604ec9a07d6ee2ce5e550c18b1 

During bloodcult, deconversion messages didn't seem to be displaying even after like 150 units of holy water, I am not 100% sure if conversion worked at all but we're seeing them pass out but no messages.

**Comment by Cyberboss** [comment] 2017-04-30 19:47
Dupe of #26741

**Comment by DaxDupont** [comment] 2017-04-30 20:01
Shit, sorry I had this open and wrote it at the start of the round. There wasn't an issue yet.

**Closed** 2017-04-30 20:02 UTC
