### ISSUE TITLE
The new N2O gas overlays heavily degrade its' visual fidelity and make it nearly impossible to see at low concentrations unless you stare intently at it

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#41045] opened 2018-10-21 03:19 UTC
At concentration of just over and around 5 mols in any turf, there's enough gas to knock someone out but not enough for it to be readily obvious what is happening, ESPECIALLY if you're running. This is functionally equivalent to trying to play with N2O when the gas overlays were broken except you'll notice the gotcha if you stare intently at the space around you afterwards. Old N2O was way more visible even when it just stunned you and didn't put you to sleep. When N2O is at around this level it'd help tremendously if it was a LOT more visually obvious.

As a side note, N2O at high concentrations just looks foggy. Aesthetically it's a lot worse than old N2O.

**Comment by nicbn** [comment] 2018-10-21 19:45
Working on it

**Comment by Barhandar** [comment] 2018-10-23 09:47
In reality space is an insulator. In reality there is no plasma. In reality you can't make airtight walls by hand. In reality you can only produce power in space through heat/light conversion.

**Fuck off** with your "reality" arguments, this is a game and everything in it serves that point.

**Comment by timothymtorres** [comment] 2021-12-30 13:22
As others have said this seems intended.  Marking this as `Not a bug` and this will auto close in 7 days.

**Closed** 2022-01-12 09:06 UTC
Labels: Sprites, Not a bug
