### ISSUE TITLE
[reported on fulpstation] ventcrawlers getting stuck while ventcrawling

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52046] opened 2020-07-06 09:03 UTC
![image](https://user-images.githubusercontent.com/42606352/86575962-b4799a80-bf3d-11ea-95ca-490c24a6b8db.png)

**Comment by kriskog** [comment] 2020-07-06 12:49
If you die in vents its likely because the contents are cold, which would prevent slime movement. Thats how slimes work.
Based on all of a screenshot with no reproduction, I assume thats it. Unless you actually get repro steps, Im going to close this.

**Comment by ATH1909** [comment] 2020-07-06 20:02
The problem isn't them dying in a vent, it's them being unable to move in a vent.

**Comment by ATH1909** [comment] 2020-07-06 20:06
The reproduction steps also seem to be pretty clear: Die as a full-grown slime while in a vent, then discover that you can't move after your automatic splitting.

**Comment by ATH1909** [comment] 2020-07-06 20:14
> If you die in vents its likely because the contents are cold, **which would prevent slime movement**. Thats how slimes work.
> Based on all of a screenshot with no reproduction, I assume thats it. Unless you actually get repro steps, Im going to close this.

Ah, hm, that does change things.

**Comment by ShizCalev** [comment] 2020-07-06 20:36
Just finishes reviewing the code. Atmos machines use relaymove() for handling ventcrawling, so as long as you're able to move around normally and you're inside it, it should work. As such, this more than likely due to the slime being too cold inside the vent.

`/obj/machinery/atmospherics/relaymove(mob/living/user, direction)`

**Closed by ShizCalev** 2020-07-06 20:36 UTC
