### ISSUE TITLE
Acid seems to be bugged

### ISSUE THREAD

**Issue by Hikurac** [tgstation/tgstation#21351] opened 2016-11-03 16:57 UTC
If I smash someone over the head with a bottle full of acid, or spray them with it, it seems to do no damage whatsoever until their clothing is fully melted. Chem-resistant clothing should do this to a degree, but even basic clothing seems to resist damage entirely until melted.

**Comment by phil235** [comment] 2016-11-03 17:28
Intended, if each of your limb is covered in clothing (glasses/mask/headgear for the head) you receive no damage.

**Comment by Hikurac** [comment] 2016-11-04 12:40
Yeah but it still occurs if they're not wearing headgear, which is odd considering I smashed the bottle over their head. As for protection, I can see a bio suit, or exosuit preventing harm, but a bandana and a baseball cap?

**Comment by phil235** [comment] 2016-11-05 15:02
it occurs if you're not wearing a mask/headgear/glasses, that's intended.

**Comment by optimumtact** [comment] 2016-11-07 23:23
If it's not a bug, direct them to the feedback forum and close the issue. No point clogging it up with stuff better discussed in the discussion forum

https://tgstation13.org/phpBB/viewforum.php?f=10

**Closed by optimumtact** 2016-11-07 23:23 UTC
Labels: Not a bug
