### ISSUE TITLE
Alt click icons no longer displaying

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#54132] opened 2020-10-01 16:40 UTC
## Round ID:
[147446](https://scrubby.melonmesa.com/round/147446)

## Testmerges:
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4
#53965: 'Tanks have tiers' by Ghilker at commit 8328b2ad36

## Reproduction:
1. alt click tile with items on
2. observe following
![image](https://user-images.githubusercontent.com/17237624/94838227-8ceb7e80-0415-11eb-821d-bef8334e15fa.png)

**Comment by timothymtorres** [comment] 2021-12-17 13:36
Duplicate of #59280

**Closed by timothymtorres** 2021-12-17 13:36 UTC
Labels: Bug
