### ISSUE TITLE
Freon freezing turns shuttle airlocks into external airlocks

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20245] opened 2016-08-31 21:33 UTC
what the fuck goof, how the fuck did you do this
![what](http://puu.sh/qVv7G/397460c03c.png)
notice the light placement. that's a SHUTTLE airlock

**Comment by Iamgoofball** [comment] 2016-08-31 21:37
i DONT EVEN KNOW

**Comment by Jalleo** [comment] 2016-08-31 22:19
This is probably due to mishandled inheritance or sprite handling.

**Comment by xxalpha** [comment] 2016-08-31 22:27
This is probably because you are caching icons by the icon state names and these are not unique and should never be assumed to be unique. Use a key composed of icon file name and icon state name.

**Comment by Iamgoofball** [comment] 2016-09-01 00:32
Couldn't reproduce this locally.

**Comment by xxalpha** [comment] 2016-09-01 15:24
When something like this happens, make sure to save a Var View. For all we know it could have been admin fuckery.

**Comment by XDTM** [comment] 2017-01-04 14:25
If the issue is what i think it is, and it was caused by the airlock icons being varedited, this should've been fixed in #22141

**Comment by ChangelingRain** [comment] 2017-01-04 14:58
I'm pretty sure it's not due to admin varedits, given that I've seen it in a few rounds with admins doing shit all.

**Comment by XDTM** [comment] 2017-01-04 16:31
Not admin vv, if i remember right @Firecage said that maps used normal airlocks with an edited icon for shuttles.

**Comment by Firecage** [comment] 2017-01-04 17:19
Well, I do have a bad memory, but I can't remember saying that?

**Comment by Cyberboss** [comment] 2017-01-04 18:52
This is the code for freezing shit

https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/icons.dm#L1011

Unless the icons have been map/admin edited or some other fuckery, I don't see how this could happen

**Closed** 2017-08-06 17:41 UTC
Labels: Bug
