### ISSUE TITLE
Circuit assemblies can't be broken via weapons

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#32904] opened 2017-11-19 15:28 UTC
Since the circuit assemblies are items instead of objects, this means you can't actually break them short of blowing them up/picking them up and using a crowbar to open it and snatch the cell.

Creates a weird consistency issue as pretty much every bit of machinery on-station can be broken via brute force but these get an exception due to their pathing. Also pretty much required when you have scientists whose creativity only extends as far as a drone that goes around saying "I'M GONNA FUCK YOU" or "AAAAAAAAAAAAAAAAAAAA".

**Comment by alexkar598** [comment] 2017-11-20 01:55
Not a bug

**Comment by praisenarsie** [comment] 2017-11-20 16:43
not a bug but still a consistency issue/oversight

**Comment by DoctoreMad** [comment] 2017-11-24 14:30
Also abusable since you can put guns inside of drones and have them shoot people

**Comment by coiax** [comment] 2017-12-04 16:14
Couldn't you shoot His Grace to kill it? His Grace was an item.

**Comment by MrMaclang** [comment] 2017-12-19 09:59
they're an item, go acid or burn it

**Comment by MMMiracles** [comment] 2017-12-20 01:39
doesn't fix the blatant consistency issue

**Comment by vuonojenmustaturska** [comment] 2018-03-03 00:40
fixed in #35931

**Closed by vuonojenmustaturska** 2018-03-03 00:40 UTC
Labels: Consistency Issue, Not a bug
