### ISSUE TITLE
Construction and Crafting on planet turfs do not work without plating

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#68226] opened 2022-07-06 06:52 UTC
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:
Caused via #65504

When on planet-esque turfs (snow, basalt, asteroid dirt):

Attempting to make snowmen, ore boxes, dirt piles, sandstone doors, and likely much more requires plating to be built first.
Same goes for using chemistry equipment. (plumbing stuff for geysers)
Prior to these changes, you could go out into icebox with a hatchet, cut down trees, and make a cozy little cabin using nothing but wood. Now you need a shit ton of iron to do anything on the planets. Why do I need god damn plating to make a snowman? Huh?

![image](https://user-images.githubusercontent.com/44104681/177488112-1e9a3a29-804b-45e1-adbc-26446bd7d02f.png)

I have personally harassed and harangued LemonInTheDark on behalf of cozy cabin in the snowy forest enjoyers everywhere.

**Comment by VladinXXV** [comment] 2022-07-06 06:52
i accidentally submitted this before typing it out if you see this empty give me like 2 minutes to edit it

**Comment by nemvar** [comment] 2022-07-12 11:43
Duplicate of https://github.com/tgstation/tgstation/issues/67817
Closing the other one in favor of this.

**Comment by LemonInTheDark** [comment] 2022-09-08 08:36
You will need iron to make catwalks for plating, but outside that should be fixed? now

**Closed** 2022-09-12 00:26 UTC
Labels: Bug
