### ISSUE TITLE
Prosthetic legs do not respect other leg layering

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#36272] opened 2018-03-09 04:53 UTC
![image](https://user-images.githubusercontent.com/6209658/37191154-e573fe6a-232b-11e8-9ad9-329ae7a23fa1.png)

![image](https://user-images.githubusercontent.com/6209658/37191151-decfc81e-232b-11e8-97e6-41ef124aa668.png)

**Comment by ArcaneDefence** [comment] 2021-01-31 08:24
This is a duplicate of https://github.com/tgstation/tgstation/issues/20603

**Closed** 2021-04-10 05:14 UTC
Labels: Bug, Sprites
