### ISSUE TITLE
Performing actions had longer, random waiting times, progress bar barely showed up.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#25610] opened 2017-03-29 18:13 UTC
Happened on Sybil.
Server revision compiled on: 2017-03-28
b118dea2667e2086f33ea26e6b82ce552c342c61 

Doing actions like unwrenching girders would take a longer random amount of time, and the progress bar would barely show up. The status tab was also buggy, not showing anything at times, or showing info twice.
Seems like this affected other players as well, someone mentioned that the server was a bit buggy over OOC. 

![status](https://cloud.githubusercontent.com/assets/4581352/24469285/ea6dd522-14b2-11e7-9bc4-cbb675ff3356.png)

Reconnecting didn't fix it, status tab only showed up 30 seconds or so after connecting. The problem only lasted for like, 5 minutes, went afterwards.

**Comment by optimumtact** [comment] 2017-03-30 09:36
Related to 25598 and likely caused by a ticker failing or simlar.

Could also be network lag

**Comment by MrStonedOne** [comment] 2017-03-30 15:51
This is general lag. This would most likely be caused by the byond sleep queue getting overloaded, but could also be a subsystem taking more time then the mc has allocated to it.

**Comment by timothymtorres** [comment] 2021-08-24 11:38
The other linked issues #25598, #32008, #23595, #30589 and #24782 were similar and during the same timeframe.  Whatever was causing this lag appears fixed since I can't find any recent bug reports about it.  Closing this for now.

**Closed by timothymtorres** 2021-08-24 11:38 UTC
Labels: Bug
