### ISSUE TITLE
(Ice) Box Powernet is hell, and there are no issues about it

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#51059] opened 2020-05-11 09:06 UTC
## Round ID:

None, that's the trouble.

## Testmerges:

^

There are no issues about this on the tracker, but people still talk about it as if it is one. There are some steps to fix it, but none to reproduce it, and I can't get it to show up on a local, with any amount of configuration or setups.

The box powernet is "Fucked", but none seems to know what that means. If you have any details about the issue, or round id's, please for the love of god post them here

**Comment by Tlaltecuhtli** [comment] 2020-05-11 12:39
where are these issues? i dont see any after the cable fixing prs

**Comment by LemonInTheDark** [comment] 2020-05-12 07:07
I've seen people discuss it as if it's a problem, and the exact source of the issue was never tracked down afaik, the only things fixed were leftovers of new cables. Something was and I assume still is seriously wrong with powernet code.

**Comment by LemonInTheDark** [comment] 2020-05-14 08:09
![image](https://user-images.githubusercontent.com/58055496/81909464-7edcb480-957f-11ea-83db-2e2928f8c5f0.png)
Round Id:137056
**Look into this you lazy bastard**

**Comment by WarlockD** [comment] 2020-05-14 08:35
Bleh.  There is a dangling SEMS battery in the grav gen.  Not sure if its the issue, but the grid is wired straight to the APC, the incoming of the power storage unit and the gravity gen.  The power unit is outputting 50kW to nothing but still taking in power.  Could this be a mapload issue with a power unit with power going nowhere?

If I think about it, this is the only map with a dangling power unit.  All other maps have the things output pluged into the apc and grav.

**Comment by kriskog** [comment] 2020-05-14 14:49
I observed some box, here's what happens:
Cable is cut/put down somewhere, entire powernet is remade. During remaking the powernet moving all cables and machines into it, something fucks up. I was looking at a cable 20-30 lengths out of the SMES output side, and the powernet associated with it did not have the SMES in the node list. The SMES were connected to the same cable network as the cable I was viewing, but wasnt sending to the correct powernet object. 
I didnt get to check the powernet var of the SMES, but I am guessing its either still hooked to the old one, or something has caused two powernets to be made and  the SMES is trying to feed into the wrong one. The SMES UI said it was outputting somewhere.
The issue is fixed in game by forcing another remake of the powernet, for instance by cutting or placing a new cable.

Issue is likely in propagate_network somewhere, start looking at what happens when a cable is cut.

**Comment by LemonInTheDark** [comment] 2020-05-14 23:28
![image](https://user-images.githubusercontent.com/58055496/81995723-f0f4de00-95ff-11ea-9ecf-0873173d97f6.png)

Another one's gone, another one's gone, another one bites the dust

**Comment by msgerbs** [comment] 2020-09-09 07:02
Has this still been reported since merging that PR?

**Comment by kriskog** [comment] 2020-09-09 09:29
Gonna go with a hopefully not

**Closed by kriskog** 2020-09-09 09:29 UTC
