### ISSUE TITLE
Plasmamen can somehow take toxin damage and can't heal from it

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80598] opened 2023-12-26 17:46 UTC
## Issue Summary

Plasmamen can magically take toxin damage even though they have no means of healing from it.

I have no idea how acid managed to bypass the (previously working and accidental) toxin immunity, but it's likely something fucked with biotypes.

## Reproduction:

1. Inject yourself with Fluorosulfuric Acid.
2. Observe magical toxin damage that you cannot heal from without ahelping.

**Comment by MrMelbert** [comment] 2023-12-26 18:05
plasmamen aren't supposed to be immune from toxin damage, the issue is rather that toxin healing medication does not work on plasmamen, which is probably because they are not `MOB_ORGANIC`

**Comment by RikuTheKiller** [comment] 2023-12-26 18:09
> plasmamen aren't supposed to be immune from toxin damage, the issue is rather that toxin healing medication does not work on plasmamen, which is probably because they are not `MOB_ORGANIC`

they have been for a while and still are for the most part, it just seems acid has somehow managed to bypass that

**Comment by RikuTheKiller** [comment] 2023-12-27 00:24
also @MrMelbert most of the plasmaman balance is, funnily enough, brought about on accident

they weren't even intended to be a hardcore race yet just ended up being that way

I don't really mind keeping their toxin immunity considering how easily plasmamen are killed anyway, it'd just be nice if they were either immune or not immune, not somewhere inbetween

also biotypes suck ass code clarity wise, there's a reason why we have things like golem hearts being able to turn you into an immortal when combined with nooartrium (although going on a quest for a golem heart is kind of funny so i personally wont be fixing that one)

**Comment by Sadboysuss** [comment] 2024-08-05 17:50
closing in favor of https://github.com/tgstation/tgstation/issues/85360

**Closed by Sadboysuss** 2024-08-05 17:50 UTC
