### ISSUE TITLE
You can explode yourself trying to put away a plasma cutter

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#65548] opened 2022-03-18 07:18 UTC
## Testmerges:
65445

## Reproduction:
1. Get an empty ore satchel and have its interface open
2. Plasma in your inactive hand
3. Plasma cutter in your active hand
4. Press e
5. Explode and die

Comes from quickequip that tries to insert into the ore satchel, fails, and triggers the heat check anyway. 

```
var/list/obj/item/possible = list(M.get_inactive_held_item(), M.get_item_by_slot(ITEM_SLOT_BELT), M.get_item_by_slot(ITEM_SLOT_DEX_STORAGE), M.get_item_by_slot(ITEM_SLOT_BACK))
    for(var/i in possible)
        if(!i)
            continue
        var/obj/item/I = i
        if(SEND_SIGNAL(I, COMSIG_TRY_STORAGE_INSERT, src, M))
            return TRUE
```

This explosion was also completely unlogged.

**Comment by RigglePrime** [comment] 2022-03-18 07:25
This was reproduced in rounds 180132 and 180135

**Comment by timothymtorres** [comment] 2022-03-18 10:10
Looks like a dupe of #64958

**Comment by Serxule** [comment] 2022-03-19 06:27
> Looks like a dupe of #64958

did you even read either of them

**Comment by timothymtorres** [comment] 2022-03-19 06:49
They both are triggering a heat check when they shouldn't

**Comment by Serxule** [comment] 2022-03-20 08:30
> They both are triggering a heat check when they shouldn't

they're entirely different though, even if its one code thing

**Comment by vincentiusvin** [comment] 2022-04-24 20:06
Not a dupe, but had tim not linked it i wouldnt have fixed it 😄

**Closed** 2022-04-25 18:46 UTC
Labels: Bug, Logging, Tested/Reproduced
