### ISSUE TITLE
UI can break after client crashes sometimes

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46435] opened 2019-09-10 18:13 UTC
## Reproduction: 
I have no idea apart from the fact that I crashed

![image](https://user-images.githubusercontent.com/12382984/64639095-08d7ea80-d3ff-11e9-991d-c22fa3febce2.png)

**Comment by stylemistake** [comment] 2020-07-16 19:38
Duplicate of #50480

**Closed by stylemistake** 2020-07-16 19:38 UTC
Labels: BYOND Issue, Bug, UI
