### ISSUE TITLE
Using a regen core with a split personality sends the split back to the main menu

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#46966] opened 2019-10-08 16:47 UTC
## Round ID:

120975

## Testmerges:

#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit 07cb01c340

## Reproduction:

Someone took a split personality roll, and was logged out/crashed after a regen core was used on the person who had the split personality trauma. They then logged back in at the main menu and joined the game normally.

I tried to reproduce this with another admin but I was unable to kick them to the main menu by using a core, though it did kick them shortly after taking the split once. All other attempts at using a core just ghosted them.

**Comment by necromanceranne** [comment] 2019-10-09 07:04
They managed to reproduce it in the round and Rusty ended up even becoming a traitor upon arrival. This is 100% a method of rolling antag, so consider it a pretty major bug and not to take this too lightly. We justhave to figure out how it happened.

(Let's not even consider the fact that it's straight up also a respawn)

**Comment by fludd12** [comment] 2019-10-09 11:19
Regen extracts run the same full-heal code that legion cores used to do, so it forcibly cured the trauma. It's weird that doing so didnt run the code that should happen when a trauma is cured, though...

**Comment by 81Denton** [comment] 2019-10-09 11:21
Just so I'm not misunderstanding: Do you mean legion juice or xenobio extracts?

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-10-09 16:30
another admin heal item???

**Comment by fludd12** [comment] 2019-10-09 16:41
Existed since before legion cored were made mostly obsolete.

**Comment by 81Denton** [comment] 2019-10-09 17:56
The split personality shouldn't get kicked to the main screen anywho

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-10-09 18:10
prob something to do with the admin heal and how it interacts with traumas though, IE perhaps using straight delete vs. the appropriate "pre-delete" proc

**Comment by Moonman121** [comment] 2019-10-25 23:02
There has been another reporting of a split being sent back to the main menu, this time with no use of a regen core. 
Round 122200
Split disconnected shortly after they were meant to take over the body of a new split personality, logged in at the main screen and rejoined the game.

**Comment by kriskog** [comment] 2019-11-11 21:25
Closing in favor of #47720

**Closed by kriskog** 2019-11-11 21:25 UTC
Labels: Bug, In Game Exploit, Tested/Reproduced
