### ISSUE TITLE
Heads on spears show up above the blindness overlay.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63074] opened 2021-11-26 06:07 UTC
Reporting client version: 514.1566

## Round ID:
[173697](https://scrubby.melonmesa.com/round/173697)

## Testmerges:
- [Tramstation Perma Genpop](https://www.github.com/tgstation/tgstation/pull/62966)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)

## Reproduction:
1. Put a head on a spear
2. Fall asleep nearby
3. Notice that you can see the head through the sleep-blindness overlay

**Comment by SuperNovaa41** [comment] 2021-11-26 17:32
I know this is a bug, as it's happened to me in the past, but I can't seem to reproduce it on local

**Comment by SuperNovaa41** [comment] 2022-01-06 06:20
Duplicate of https://github.com/tgstation/tgstation/issues/59037

**Closed by SuperNovaa41** 2022-01-06 06:20 UTC
Labels: Bug, Needs Reproducing
