### ISSUE TITLE
Clothes put in CargoDrobe input compartment don't show up in UI

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#54840] opened 2020-11-06 10:17 UTC
## Round ID:
Issue reported from  Round ID: [149776](https://scrubby.melonmesa.com/round/149776) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

## Testmerges:
#54702: 'Add debug info for client time timers' by spookydonut at commit a8042f4583
#54379: '[WIP] Remove fusion from reactions, add hypertorus fusion machinery' by Ghilker at commit e10435e721
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 02225b37e3

## Reproduction:

1. Return unused cargo cap and/or fingerless gloves to CargoDrobe
2. Look at UI and see that the number of those items to vend hasn't increased, and there's no separate section for the input compartment contents

I'm assuming this is true of all AutoDrobes and all returnable objects but I haven't tested it.

**Comment by dragomagol** [comment] 2020-11-08 04:07
Duplicate of #49023

**Closed by dragomagol** 2020-11-08 04:07 UTC
Labels: Bug

**Comment by cacogen** [comment] 2020-11-08 23:21
#49954 AHHHHHH
