### ISSUE TITLE
Stationwide Background Checks make any shift the safest shift in existence.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#86310] opened 2024-09-01 06:56 UTC
Reporting client version: 515.1643

## Issue Summary
I noticed in the latest round that while stationwide background checks was a station trait during the shift, it didn't do what I think it's supposed to do. From what I read from the PR adding it in, it should supposedly cause more midrounds/latejoin antagonists to occur to exchange for the lack of shiftstart antagonists. However the station faced no midrounds or latejoin antagonists despite it being an orange star with 35 threat. The only antagonist to even spawn in this around an hour and a half round was spiders, which had to be spawned by an admin instead of dynamic.

## Round ID:
[236337](https://scrubby.melonmesa.com/round/236337)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
Run a shift with the stationwide background check trait and set a high threat. Then wait an hour or two and you'll notice this happening if its an actual bug. This might just be an unlucky dynamic thing or an actual bug with stationwide background checks.

### Picture for proof
![Screenshot 2024-08-31 234643](https://github.com/user-attachments/assets/c362fa6a-6d0e-46b7-babf-9af62e3b396a)
As noted, spiders were spawned by Dunham.

**Comment by Sadboysuss** [comment] 2024-09-01 07:18
Dupe of https://github.com/tgstation/tgstation/issues/84545

**Closed** 2024-09-03 07:15 UTC
