### ISSUE TITLE
Paradox Clone doesn't take on the original character's TTS voice

### ISSUE THREAD

**Issue by Grayman7000** [tgstation/tgstation#77489] opened 2023-08-09 20:50 UTC
## Round ID:
[212155](https://scrubby.melonmesa.com/round/212155)

## Testmerges:
#77447: 'Trying to qdelete a callback now lags the server instead.' by MrStonedOne at commit e15efd1604
#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb
#77259: 'Feature: bitrunner, a new supply role' by jlsnow301 at commit 9faf80a41f
#77468: 'Fixes some lua problems, specifically with qdeling callbacks and adds lua utility functions' by Watermelon914 at commit 65448788d5

(I believe, don't have the exact ones)

## Reproduction:
Spawn as a Paradox Clone. I latejoined observer, got the prompt for paradox clone, hit yes. My physical appearance and job were the same as the person I was cloning, but my voice was not, seemingly random. I believe this is unintentional behaviour, as a paradox clone is supposed to be a perfect copy of the original.

**Comment by Sealed101** [comment] 2023-08-09 21:08
Duplicate of #76894

**Closed by Sealed101** 2023-08-09 21:08 UTC
