### ISSUE TITLE
runechat sometimes shows only part of  the message

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55542] opened 2020-12-15 09:15 UTC
started happening recently, you write or emote something and runechat outputs only the last word or half of it on top of your head (full message appears in chat) cant confirm if other can see it

**Comment by wesoda25** [comment] 2020-12-15 16:13
Been getting this all the time lately

**Comment by Cyprex** [comment] 2020-12-16 10:09
Seems like the first line is missing or only the last line is printed? Does anyone have a reliable way to reproduce this?

**Comment by dragomagol** [comment] 2020-12-16 23:15
Duplicate of #52483

**Closed by dragomagol** 2020-12-16 23:15 UTC
