### ISSUE TITLE
You can't hit a stunned/knocked out/dead person with a thrown object

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#29806] opened 2017-08-09 14:01 UTC

**Comment by AnturK** [comment] 2017-08-10 07:17
Former is not a bug, only humans can embed the latter is actually a bug.

**Comment by Tacolizard** [comment] 2017-08-10 07:54
@AnturK edit the title to only include the latter half then

**Comment by PraiseRatvar** [comment] 2017-08-12 15:01
turns out it happens with humans as well

**Comment by Jordie0608** [comment] 2021-08-23 18:45
Fixed in #60604

**Closed by Jordie0608** 2021-08-23 18:45 UTC
Labels: Bug
