### ISSUE TITLE
you still bleed even if you are bandaged

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#24391] opened 2017-02-23 23:00 UTC
as in, blood drops, not just the message. I am not sure if this is just a quirk of improvised gauze or not.

**Comment by factoryman942** [comment] 2017-02-24 10:28
Only difference between improv and proper gauze is the stop_bleeding variable (900 for improv, 1800 for normal) which seems to just affect how long the bandage lasts or something when applied

**Comment by Robustin** [comment] 2017-06-09 16:20
Youre probably just seeing some lag in how bleeding is updated. I haven't seen this issue at all beyond the few seconds where bleeding is "healing" but still resolving some blood loss.

**Comment by Qustinnus** [comment] 2019-07-02 23:10
Cannot reproduce.

**Closed by Qustinnus** 2019-07-02 23:10 UTC
Labels: Bug, Consistency Issue, Needs Reproducing
