### ISSUE TITLE
Lizards cannot use certain headset uplink codes due to Lizard tongues changing what they say.

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#80966] opened 2024-01-15 13:45 UTC
## Issue Summary
Lizards can't use their uplink if the word they have to speak is modified by their tongue. Locking them out of using their uplink entirely. This extends to the device that traitors can build to get a new uplink.

## Reproduction:
Be a Lizard
Try to use your headset uplink when it requires an activation phrase that's use an 'X' or 'S'.
If there's an 'S' in the middle of the word, or an 'X' gets converted to "KS' 'ECKS', the phrase will fail.

**Comment by Momo8289** [comment] 2024-01-15 17:28
okay but here me out: this is hilarious

**Comment by RikuLeinonenVuoksi** [comment] 2024-01-15 17:42
its kinda fucked too though since it basically turns your lucky traitor roll into, well, hardcore tot

**Comment by MrMelbert** [comment] 2024-01-15 18:30
Dupe of #71967 

Did you know speaking your native language (draconic) makes you not hiss, so you can actually use your uplink of you say you code in lizard

**Closed by MrMelbert** 2024-01-15 18:30 UTC
