### ISSUE TITLE
storage keeps breaking

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#85259] opened 2024-07-25 20:49 UTC
Reporting client version: 515.1641

## Issue Summary
various storage (mostly backpack) keeps breaking for some reason. UI becomes transparent and any items you put into it become invisible, idk what's causing it.
This runtime appears when the bug is reported
`[20:23:15] Runtime in code/datums/storage/storage.dm, line 1068: Cannot execute null.update position().`

## Round ID:
[232636](https://scrubby.melonmesa.com/round/232636)

## Testmerges:
- [Replaces Auxlua with the byondapi-based Dreamluau](https://www.github.com/tgstation/tgstation/pull/84810)

**Comment by Sadboysuss** [comment] 2024-07-25 20:54
dupe of https://github.com/tgstation/tgstation/issues/84507 but keep it open since the runtime info is useful

**Comment by Sadboysuss** [comment] 2024-07-25 20:54
@SmArtKar

**Comment by Time-Green** [comment] 2024-09-21 19:33
Can fix it by deleting the null from open_ui
Dont actually know how to prevent it from happening

**Comment by TheVekter** [comment] 2024-09-24 18:38
SmArtKar thinks this is being caused by some nulling shenanigans that happen when the following order of operations occurs:

1) Orbit a player with auto-observe on while that player has an open inventory.
2) That player disconnects without closing the inventory.
3) The orbiting player leaves the same screen as the disconnected player before they reconnect.

**Closed** 2024-09-24 19:30 UTC
Labels: Bug, Runtime
