### ISSUE TITLE
Plumbing grinds Slime Extracts

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#84274] opened 2024-06-23 23:15 UTC
## Issue Summary
I put a industrial dark purple slime extract on the conveyor belt for plumbing plasma grind, lose the extract. It worked a month~ ago.

**Comment by SyncIt21** [comment] 2024-06-24 06:21
I'm not understanding the issue correctly. So you put a industrial dark purple slime extract on the conveyor belt, & that conveyor belt leads to a plumbing grinder & the expected output is what?

**Comment by Livrah** [comment] 2024-06-24 08:35
> I'm not understanding the issue correctly. So you put a industrial dark purple slime extract on the conveyor belt, & that conveyor belt leads to a plumbing grinder & the expected output is what?

![Screenshot_155](https://github.com/tgstation/tgstation/assets/64209864/5c2ceb8f-5a35-46d5-8c1e-aeaf886afcec)
This, connected with IV injectors, allowed to make xenobio plumbing. It always grinded only plasma sheets.

**Comment by SyncIt21** [comment] 2024-06-24 12:50
So this is the new expected behaviour. A month ago the grinder chemical would not grind/juice some items even if they had reagents whereas the reagent grinder would do it correctly. Now both their behaviour's have been synced so a reagent grinder will grind the extract & now the plumbing grinder does as well.

It was an bug that players found convenient but now it's been patched up. Not a bug

**Comment by ZeroKelvn** [comment] 2024-06-25 20:39
Man this was the primary component for my Xenobiology ever since IV drips became compatible with industrial extracts
No, literally, I designed a plasma farm setup the same day it was merged
I wouldn't call it a bug as much as it was emergent gameplay that we don't benefit from throwing out

**Closed** 2024-09-17 05:55 UTC
Labels: Not a bug, Cleanup Flagged
