### ISSUE TITLE
Photos do not Display Humanoids with Wings

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/tgstation#69861] opened 2022-09-12 15:42 UTC
## Round ID:
[190355](https://scrubby.melonmesa.com/round/190355)

## Testmerges:
[#69838: 'Micros the lighting subsystem (Saves a second of init)' by LemonInTheDark at commit 9f8144427a](https://www.github.com/tgstation/tgstation/pull/69838)
[#69696: 'Removes overlay queuing, saves 6/7 seconds of initialize. Lightly modifies stat tracking macros' by LemonInTheDark at commit 23d43f7fad](https://www.github.com/tgstation/tgstation/pull/69696)
[#69632: 'Macro optimizes SSmapping saving 50% ' by LemonInTheDark at commit 00d62194a0](https://www.github.com/tgstation/tgstation/pull/69632)
[#69706: 'Completely refactors hallucinations, and also adds a few ' by MrMelbert at commit 3f57b4e72a](https://www.github.com/tgstation/tgstation/pull/69706)

## Reproduction:
Fairly certain this is what's causing it, as the only time I have had people not show in pictures was when they had wings from flight potions (Mining, Xenobio). This has happened to me probably 3-4 times, with different players.

1. Acquire flight potion
2. Drink flight potion
3. Take a picture with camera
4. Examine photo

I am fairly certain none of the test merges are causing this issue, since I had this happen 1-2 weeks ago, without being as sure of the cause.

**Comment by Time-Green** [comment] 2022-09-12 18:29
Doesn't display the humanoid or doesn't display the wings?

**Comment by TemporalOroboros** [comment] 2022-09-13 08:17
If it uses get_flat_icon() that either ignored or cropped icons larger than some size at some point in the past. I don't remember which and I don't remember when. If it's still doing that it might be clobbering their sprites as a result.

**Comment by Breadeagle** [comment] 2022-09-14 17:38
![image](https://user-images.githubusercontent.com/17058929/190224425-9173e8ed-982e-4e9a-9b4a-16c12e8caac3.png)
You can see that it just makes the entire player sprite invisible, but show on the picture description.

**Comment by timothymtorres** [comment] 2023-04-07 09:52
Duplicate of #70798

**Closed by timothymtorres** 2023-04-07 09:52 UTC
Labels: Bug
