### ISSUE TITLE
easel

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#30703] opened 2017-09-13 19:22 UTC
metastation, right above the boxing ring in, near the holodeck
![easel](https://user-images.githubusercontent.com/22112255/30396359-3c18feb6-987e-11e7-9c3d-58fad94b1a0a.PNG)

**Comment by praisenarsie** [comment] 2017-09-13 19:47
easel

**Comment by Cyberboss** [comment] 2017-09-13 20:03
hmmm, no varedited icon states actually

**Comment by BeeSting12** [comment] 2017-09-13 20:23
I made this issue once, someone told me it's a cache issue. I'll try and find the issue

**Comment by BeeSting12** [comment] 2017-09-13 20:25
#17643
#26184

**Comment by Cyberboss** [comment] 2017-09-13 20:41
Duplicate of #26184

**Closed by Cyberboss** 2017-09-13 20:41 UTC
Labels: Bug
