### ISSUE TITLE
service ordering console doesn't work

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67308] opened 2022-05-26 00:23 UTC
## Testmerges:

irrelevant

## Reproduction:

> be mime/bartender/captain/AI
try to use service ordering console to get free stuff
invalid access
cry

**Comment by BlueMemesauce** [comment] 2022-05-26 01:48
duplicate of #67180

**Comment by san7890** [comment] 2022-05-26 04:55
Fixed with #67232. Thank you!

**Closed by san7890** 2022-05-26 04:55 UTC
