### ISSUE TITLE
Grills don't always make "real" food

### ISSUE THREAD

**Issue by Meatstuff882** [tgstation/tgstation#59423] opened 2021-06-01 02:36 UTC
Reporting client version: 513.1542

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:
Occasionally, the grills will start producing inedible food. Using it on yourself simply results in your character hitting themselves with it. I have not been able to reproduce this bug, but I have seen it across multiple rounds. it seems to happen after a certain amount of time has elapsed in a round however.

**Comment by SmArtKar** [comment] 2021-06-02 05:56
Are you sure that their combat mode is off? Because it looks like they just forgot to turn it off before eating

**Comment by TheBonded** [comment] 2021-06-02 15:31
I have seen this as well, with combat mode on or off you cannot eat the food.

**Comment by Yawet330** [comment] 2021-07-29 13:25
This involves the food itself having 0 reagents upon creation IIRC, resulting in the Edible component going "Fuck this", and deleting itself from the entity.

**Comment by timothymtorres** [comment] 2021-12-30 01:11
> This involves the food itself having 0 reagents upon creation IIRC, resulting in the Edible component going "Fuck this", and deleting itself from the entity.

Should probably spawn it as a burned mess then

**Comment by timothymtorres** [comment] 2021-12-30 01:46
Duplicate of #55375

**Closed by timothymtorres** 2021-12-30 01:46 UTC
Labels: Oversight
