### ISSUE TITLE
Alien Alloy can't be researched, even once you scan it

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35102] opened 2018-01-29 14:23 UTC
Reproduction: find abductor ruin, take stuff back to station, reveal abductor base node, notice that it has a prerequisite that you can't see or something (point requirement is red)

**Comment by vuonojenmustaturska** [comment] 2018-01-29 14:54
@kevinz000

**Comment by praisenarsie** [comment] 2018-01-29 17:32
techwebs has been unfinished for how long?

**Comment by Buggy123** [comment] 2018-01-29 17:38
Weird, I've done this before and it works, researched the tech just fine (though, I took multiple tools and revealed all 3 abductor nodes at once).
I've also done it before, and had it not work...

@kevinz000

**Comment by YPOQ** [comment] 2018-01-30 02:14
#33097

**Comment by ShizCalev** [comment] 2018-01-30 07:28
Duplicate of #33097

**Closed by ShizCalev** 2018-01-30 07:28 UTC
