### ISSUE TITLE
If you put a primed flashbang (any other grenade?) inside an evidence bag, it "stays" there after detonation.

### ISSUE THREAD

**Issue by TheSadFox** [tgstation/tgstation#9544] opened 2015-05-17 18:56 UTC
Basically, prime a flashbang, put it inside the evidence bag. After it detonates, grenade is still in the bag, in a primed state (blinking lights). Trying to empty the bag doesn't get rid of it, gotta put something inside and then empty it to get rid of flashbang icon.

Minor thing, yet still a bug, so reporting it here.

**Comment by Fr4gn0st1c** [comment] 2015-05-22 17:46
I noticed the same thing happened with a flashbang when I put it in that special slot drones have.

**Comment by nullbear** [comment] 2016-09-10 03:21
This is a relatively easy fix. If a grenade is in a storage object, call the storage objects 'remove' proc (whatever it is) before it primes. 

If the grenade still exists afterwards (edgecases) re_insert it into the container.

**Comment by PKPenguin321** [comment] 2016-09-10 07:59
I'm not sure evidence bags are real containers though

**Comment by Qbopper** [comment] 2017-04-05 14:33
Still reproducible

If you turn off throwing after arming it, it goes into the bag - the flashbang then goes off as normal, but is still inside the bag in the activated state

Then when I tried removing the flashbang this happened (the sprite is both the empty one and the filled one)

![help](http://i.imgur.com/yaY1o4h.png)

Fixed by putting a new object in and removing it, before or after trying to empty the phantom flashbang - looks like this is purely cosmetic, though it does read "containing the flashbang" when examined in the broken state

**Closed** 2017-09-15 05:17 UTC
Labels: Bug
