### ISSUE TITLE
Cant bang baton on ballistic (maybe ghetto shield too, didnt test) shield

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#81838] opened 2024-03-04 23:23 UTC
Reporting client version: 514.1589

## Round ID:
[225006](https://scrubby.melonmesa.com/round/225006)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
>get ballistic shield
>click baton on it in hand
>no banging
WTF dude, immersion ruined!!!1! >:(((

**Comment by MrMelbert** [comment] 2024-03-05 01:34
They're not subtypes of riot shields, so they don't have this behavior

**Comment by Singul0** [comment] 2024-03-06 12:58
you can component that relatively easily, you know what. i'll try it when I have the time

**Comment by SyncIt21** [comment] 2024-03-11 12:25
After labelling  "not a bug" the next logical thing is to close this issue.

**Closed** 2024-03-18 21:51 UTC
Labels: Not a bug
