### ISSUE TITLE
Dullahans simulataneously do and don't have DNA

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79385] opened 2023-10-29 23:50 UTC
Reporting client version: 514.1589

## Round ID:
[217774](https://scrubby.melonmesa.com/round/217774)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [The Brawlening: Unarmed fighting interactions for shoving, grabbing and nonlethal takedowns (not martial arts)](https://www.github.com/tgstation/tgstation/pull/79362)

## Reproduction:
1. Scan dullahan with a genetic sequence scanner
2. Get given a list of the DNA mutations they innately have
3. Attempt to inject dullahan with an activator/mutator
4. 'It appears that Sono Head does not have compatible DNA.'

This doesn't match what other no DNA races say when you scan them, which is:
'Bones Skeleet has no readable genetic sequence!'

**Comment by MrMelbert** [comment] 2023-10-30 00:43
Same w/ vampires, but not a bug, technically. 
They have DNA, but because they're not `MOB_ORGANIC` biotype (they're undead), they can't have mutators injected into them.

**Comment by Dorsisdwarf** [comment] 2023-10-30 18:08
Should probbably have a better response for undead mobs

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug
