### ISSUE TITLE
Ghost can empty documents from filing cabinets

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#38719] opened 2018-06-25 04:09 UTC
Round ID: 9009

No picture for this one sorry

>Be ghost
>Click filing cabinet
>Click document
>Empty document from cabinet
>Confuse station as to why the secret documents are on the floor

**Comment by SpaceManiac** [comment] 2018-06-25 05:51
Duplicate of #38717

**Closed by SpaceManiac** 2018-06-25 05:51 UTC
Labels: BYOND Issue
