### ISSUE TITLE
Antag status removed after having player's mind/body destroyed

### ISSUE THREAD

**Issue by Leon-Leonardo** [tgstation/tgstation#29619] opened 2017-08-01 06:34 UTC
**Cross-posting from Citadel:**

- What happened: Player antag unintentionally removed from antag status
- How it happened: Player's body and mind were destroyed
- How to recreate it: Assign player to antag status and destroy their body via gibbing or possibly simply deleting

Antag status seems to be removed after a player (ckey "wilchen" in this case) has their body/mind destroyed. Noticed this after someone BoH bombed the super matter crystal and was gibbed. I questioned them about it as they did not appear on the Traitor Panel, but they claimed that they were indeed an antag and had completed all their objectives except the "die a glorious death" objective. I was only able to find out that they were indeed a traitor by checking the game log (see pic 1). At the end of the round they still did not appear in the end of round summary (see pic 2). Unfortunately I don't have an image of the Traitor Panel as the round ended while I was still looking into this.

**Pic 1**
![](https://i.gyazo.com/7e63070d6c96bce57acefb47f7af24a1.png)

**Pic 2**
![](https://i.gyazo.com/f7982924a8bbc114da04f58cee683065.png)

Can provide further logs/info if requested.

**Comment by AnturK** [comment] 2017-08-01 06:42
Duplicate of #22631 , long story short that datum traitor pr shouldn't have been merged without review.

**Comment by AnturK** [comment] 2017-08-01 06:45
Ugh wrong issue.

**Comment by The-clown-known-as-Pepe** [comment] 2017-08-02 08:10
Had this happen to me after I Bohbombed

**Closed** 2017-08-03 14:52 UTC
Labels: Bug
