### ISSUE TITLE
Clicking on items with pop ups attached opens white, unmovable boxes on screen, on personal server

### ISSUE THREAD

**Issue by failedthetutorial** [tgstation/tgstation#60446] opened 2021-07-25 22:41 UTC
![broke](https://user-images.githubusercontent.com/85060703/126915675-bbe95f79-0c7c-4056-8144-a8a0e094d669.png)
![(null)scrnshot1](https://user-images.githubusercontent.com/85060703/126915645-1663c117-6a0c-47f6-9b7e-c034afdd35d0.png)
This problem comes with most things that have interface, expcluding that of the join menu, admin pannel and player panel
https://old.reddit.com/r/SS13/comments/ohvr8u/all_ingame_interfaces_are_white_boxes/ if this post can be trusted it also appears on linux hosted personal servers, and has been in the game at least 15 days
The code i have is of two days before this though im not sure exactly what merge it was
[Reproduction]: 
Newest version of the game, compiled with byond beta dreamaker with build.bat on windows 10

**Comment by Mothblocks** [comment] 2021-07-27 01:02
try clearing your cache

this sometimes happen with tgui and usually restarting fixes it for me

**Comment by timothymtorres** [comment] 2021-08-22 10:44
@Mothblocks is this a BYOND thing?

**Comment by Mothblocks** [comment] 2021-08-22 20:56
honestly i think this guy just didnt build.bat

**Comment by timothymtorres** [comment] 2021-08-23 10:20
@failedthetutorial are you still having this issue?

**Comment by timothymtorres** [comment] 2021-08-24 12:24
Duplicate of #47793

**Closed by timothymtorres** 2021-08-24 12:24 UTC
Labels: Cleanup Flagged

**Comment by Helvetica8563** [comment] 2022-05-09 17:42
im also having this issue have tried clearing IE firefox google and byond cache even switched browsers reinstalled byond reinstalled the server made sure everything was updated including my browser byond tgmaster still cant open anything
