### ISSUE TITLE
Engineering cyborg RTD oversite, no longer can add tiles to lattice over space/make floor plating without rcd.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#87587] opened 2024-10-30 21:21 UTC
### Issue Summary:

After merge of https://github.com/tgstation/tgstation/pull/87465 engineering cyborgs no longer have access to use stacks of tiles.
Its a huge nerf to be stuck only using a rcd to add floor plating as energy runs dry very quickly. The RTD does not have the ability to add tiles to lattice over space.

### Reproduction Steps:

Attempt to add tile with rtd on lattice on tram when on the upper zlevel, or space i assume would do the same thing.

**Comment by Aliceee2ch** [comment] 2024-10-30 22:45
i dont really think i intended rtd as thing to place platings, but what i did is just let borg make fancy floors. 
you still can create tiles and, most importantly, hold them with "material manipulation apparatus". 
dont see reasons to make rtd being able to place platings, since you still can do it.

**Comment by JusticeGoat** [comment] 2024-10-30 23:39
> i dont really think i intended rtd as thing to place platings, but what i did is just let borg make fancy floors. you still can create tiles and, most importantly, hold them with "material manipulation apparatus". dont see reasons to make rtd being able to place platings, since you still can do it.

the "material manipulation apparatus" does not place tiles on space lattice, i tested it.

**Comment by SyncIt21** [comment] 2024-10-31 03:10
> The RTD does not have the ability to add tiles to lattice over space.

This is a feature request and not a bug that won't be implemented because the RCD already does this.
RTD Has a much higher ammo reserve than RCD and giving it the ability to create plating would make the RCD obsolete for this task and make it too OP

> engineering cyborgs no longer have access to use stacks of tiles.

This is an oversight that can be addressed, don't know why that PR removed this ability since it's very useful

**Comment by Aliceee2ch** [comment] 2024-10-31 07:59
> the "material manipulation apparatus" does not place tiles on space lattice, i tested it.

the fuck, now that's a deal, i look what i can do

**Comment by JusticeGoat** [comment] 2024-10-31 09:21
> > the "material manipulation apparatus" does not place tiles on space lattice, i tested it.
> 
> the fuck, now that's a deal, i look what i can do

Thank you that's all i could have hoped for! :)

**Comment by Aliceee2ch** [comment] 2024-10-31 09:39
> Thank you that's all i could have hoped for! :)
> 
> Apologies for the bad communication, I am not always the best at it, i appreciate you all staying civil and having patience.

Alright, i tested this and cant really now get the issue, everything seems ok?


https://github.com/user-attachments/assets/07cad91e-8178-4e08-93f4-fbfc898e5e9f

**Comment by JusticeGoat** [comment] 2024-10-31 10:19
> > Thank you that's all i could have hoped for! :)
> > Apologies for the bad communication, I am not always the best at it, i appreciate you all staying civil and having patience.
> 
> Alright, i tested this and cant really now get the issue, everything seems ok?
> TofuHubWhiskey2024-10-3111-36-05.mp4
> [×<MEDIA>@https://private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/160794176/381899795-07cad91e-8178-4e08-93f4-fbfc898e5e9f.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjg2NDAsIm5iZiI6MTczMDM2ODM0MCwicGF0aCI6Ii8xNjA3OTQxNzYvMzgxODk5Nzk1LTA3Y2FkOTFlLTgxNzgtNGUwOC05M2Y0LWZiZmM4OThlNWU5Zi5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwOTUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjY0YWZmZWNlYjEyOTAxY2Q4NGMyOWYyNDdkZmQ1YjdiMWU4OGVkN2I2ZjE0YjA3YWQzNGQ2OGU2Y2FjMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U0BAuKVhH6qXhvsRobLZf3LStpIckaFM4F8ZHm62GeA)

I tested on the live servers and its broken for me.

**Comment by Sealed101** [comment] 2024-10-31 10:29
gotta be basic floor tiles, not material iron tiles
![изображение](https://github.com/user-attachments/assets/6c583fe2-7862-4cd0-b12e-381fb35ccd82)
![изображение](https://github.com/user-attachments/assets/d346429e-9f8b-4b89-9094-fc0ca367709a)


https://github.com/tgstation/tgstation/blob/e0be65b21f22997dc325f2a561257723dc326c4a/code/game/turfs/open/space/space.dm#L141-L148

**Closed by Sealed101** 2024-10-31 10:29 UTC
Labels: Not a bug

**Comment by JusticeGoat** [comment] 2024-10-31 10:31
User error i had no idea i was using iron material floors not normal flooring. Sorry for the waste of time.
