### ISSUE TITLE
Stickmen Ruin and Robes have issues

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#19656] opened 2016-08-02 15:17 UTC
1) Paper Wizard never stops spawning reinforcements, leading to like 500 fucking mobs sitting in his lair.

2) Paper robes spawn "neutral" stickmen instead of hostile ones. 

Although (2) is a bug, its probably more balanced that way since it has no cooldown and would rapidly wipe the station when spammed.

**Comment by Jalleo** [comment] 2016-08-02 20:04
I think 2 is reported already.

**Comment by MMMiracles** [comment] 2016-08-03 02:00
2 is intended as they're meant more of a buffer that attacks anything that hits them or is hostile to begin with.

I'll look into 1.

**Comment by frtbngll** [comment] 2016-08-03 05:05
Tried to fix 1 by limiting the summons of the Paper Wizard.

https://github.com/tgstation/tgstation/pull/19671

**Comment by Jalleo** [comment] 2016-08-20 07:08
@optimumtact is this fixed or not?

**Comment by Mervill** [comment] 2016-12-31 08:13
@optimumtact closeable - Issue 1 is solved, issue 2 is a duplicate of #19542

**Closed** 2016-12-31 10:00 UTC
Labels: Bug
