### ISSUE TITLE
Resetting thunderdome was shifted up and to the right by 1 tile.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26517] opened 2017-04-24 04:57 UTC
![](http://i.imgur.com/5OhP4Pa.png)

THE TESTING ENVIRONMENT IS BUGGY. ALL IS LOST.

This happened after resetting the thunderdome which had about 6-7 people in it, with remove mobs on YES. There was a small disposal loop in it too, and a few sniper rifles. About 12 human mobs in total. Can't think of anything else that could have caused this, at least from the thunderdome itself.

Further attempts to reset the thunderdome, with mobs on YES and NO didn't change anything, it was still shifted up and to the right by 1 tile.

I swear I'm not making all these bug reports on purpose I just can't STOP FINDING THESE THINGS.

**Comment by AnturK** [comment] 2017-04-24 06:25
Dupe of #26198

**Closed by AnturK** 2017-04-24 06:25 UTC
Labels: Bug, Needs Reproducing/Testing
