### ISSUE TITLE
As the AI, being in a mech that is destroyed by an explosion gibs your core

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#70922] opened 2022-10-30 15:34 UTC
Reporting client version: 514.1589

## Round ID:
[193394](https://scrubby.melonmesa.com/round/193394)

## Testmerges:
- [Fix halloweens races](https://www.github.com/tgstation/tgstation/pull/70874)

## Reproduction:

1. get in AI beacon mech
2. have said mech splode
3. get your core gibbed

**Comment by ShizCalev** [comment] 2022-10-30 21:25
#9792
#23320
Strange, seems this has always been the case

https://github.com/tgstation/tgstation/blob/1fe0a9f60a0f82c53d49440b3906ddd9aa463973/code/modules/vehicles/mecha/mecha_mob_interaction.dm#L105-L135

**Comment by mc-oofert** [comment] 2022-10-31 07:59
> #9792 #23320 Strange, seems this has always been the case
> 
> https://github.com/tgstation/tgstation/blob/1fe0a9f60a0f82c53d49440b3906ddd9aa463973/code/modules/vehicles/mecha/mecha_mob_interaction.dm#L113-L135

im sure that cant be intentional if explosions use "forced" since it literally just gibs my AI core and drops me alive as a MMI

**Comment by timothymtorres** [comment] 2022-11-01 17:21
Duplicate of #68713

**Closed by timothymtorres** 2022-11-01 17:21 UTC
Labels: Oversight
