### ISSUE TITLE
Plumbing Losing Chems due to Rounding Errors(?)

### ISSUE THREAD

**Issue by jehnicat** [tgstation/tgstation#84361] opened 2024-06-26 19:53 UTC
## Issue Summary

When distributing chems throughout a plumbing setup, reagents may be lost - I presume - due to rounding errors. I suspect this to be the cause because this issue began when a PR that changed how reagents flow from machine to machine was pushed. Before this PR (whatever it is) reagents transferred sequentially in 5u intervals. Now, all reagents transfer evenly at a rate of 5u (i.e., if you have two reagents in a given machine, each will be shunted at 2.5u per cycle. Three, 1.6666666...u. Four, 1.25u, etc.). This, of course, leads to problems when you have repeating decimals.

This is a nonissue if you're only synthesizing simple one-reagent outputs, but it's **catastrophic** if you're creating more complex mixes of chems. The dose of each pill/patch/whatever will drift over time and has the potential to overdose (or underdose) patients if left to run for long enough without constant babying with a plunger to keep it _mostly_ consistent.

Here is a link to a video demonstrating the issue: [link](https://www.youtube.com/watch?v=MDBRUCZjq4Q)

## Round ID:

[231177](https://scrubby.melonmesa.com/round/231177) — IDK if the server matters but it was Manuel. This has been going on for ages now, anyhow.

## Reproduction:

Step 1: create a bunch of medicine/poison/whatever using chem factories.
Step 2: send them through your system in such a way that they're muddled together in a single machine (as you would to create an intricate mix or control the flow).
Step 3: observe as your carefully curated ratios are thrown out of whack and you are lynched for giving the Captain a heart attack.

**Comment by GPeckman** [comment] 2024-06-26 19:54
Your video link is broken

**Comment by jehnicat** [comment] 2024-06-26 19:56
Thanx, fixed.

**Comment by SyncIt21** [comment] 2024-06-27 03:20
Duplicate #83719.

**Comment by Sadboysuss** [comment] 2024-06-27 15:15
Thank you for the issue report! This does seem to be a duplicate but this one has a video so keep it open as the video is very helpful. If you could provide more info, info that Syncit asked for. that would be great.

**Comment by Sadboysuss** [comment] 2024-06-27 15:17
>skill issue on your part

@SyncIt21 Let's not antagonise players that take precious time out of their day to make an issue report.

**Comment by SyncIt21** [comment] 2024-06-27 15:34
> @SyncIt21 Let's not antagonise players that take precious time out of their day to make an issue report.

Not antogonizing anyone here. What i'm saying the video that was linked does not have enough information to reproduce the issue. Also there is no issue to report here. I have spent a few hours with large scale plumbing factories before i made the comment and could not reproduce the issue.

It's best to add a "needs reproducing" label and then a "cleanup flag" till someone can create a more detailed report

**Comment by Sadboysuss** [comment] 2024-06-27 15:47
> > @SyncIt21 Let's not antagonise players that take precious time out of their day to make an issue report.
> 
> Not antogonizing anyone here. What i'm saying is the video that was linked does not have enough information to reproduce the issue. Also there is no issue to report here. I have spent a few hours with large scale plumbing factories before i made my analysis and could not reproduce the issue.
> 
> The pill press produces pills/patches & bottles with the correct volumes.
> 
> It's best to add a "needs reproducing" label and then a "cleanup flag" till someone can create a more detailed report

sounds reasonable

**Comment by jehnicat** [comment] 2024-06-27 16:54
> Or you could just wait for the values to become consistent. With such a big plumbing factory it's obviously goanna take time for the reagents to reach the target and becoming impatient and just plunging is a skill issue on your part

You're misinterpreting what I'm saying.

Let me break down what is occurring as thoroughly as possible using the example in my video so there's absolutely no room for confusion.

In my video, [I demonstrate that I have a Reaction Chamber pulling completed reagents from my factory. 5u of Multiver, 5u of Diethylamine, 4.5u of Methamphetamine, 3u of Ephedrine, 7u of Mannitol, and 7u of Neurine.](https://files.catbox.moe/tc9v37.png) These reagents are being sent first through a Layer Manifold to separate them from a secondary line, and then into a series of Chemical Filters to separate them out and deposit them into waiting Chemical Presses.

I then demonstrate the problem. In the Chemical Press I point out in my video, [the attached filter is drawing out the Methamphetamine, Ephedrine, Mannitol, and Neurine](https://files.catbox.moe/ezaggm.png) to combine them into [one 43u pill.](https://files.catbox.moe/51qxot.png) This takes two cycles: (4.5u + 3u + 7u + 7u)*2, for a total of 43u. As we are pulling completely finished reagents that are not reacting in any way whatsoever from my production, the temperature and PH should be entirely irrelevant in this example.

[What is erroneously occuring instead is that minuscule amounts of reagent are lost, seemingly at random, en route from Reaction Chamber to Chemical Press.](https://files.catbox.moe/x68fkv.png) In one observed example (not shown on video), the total amount of each reagent in the Press after two cycles was as follows: 9u Methamphetamine, 6u Ephedrine, 14u Mannitol, and 13.98u Neurine. This grows exponentially more incorrect the longer the Press is allowed to function without corrective plunging. If this were to behave as expected – how it _used_ to behave, prior to whatever plumbing changes caused this – there would be no loss whatsoever, and the product would be consistent across the entire timespan of the shift without any intervention on my behalf.

> 1. What was the temperature and ph of each reaction chamber at the time you took the measurements?
This question is irrelevant in this example for reasons stated above.

> 2. Did the problem resolve itself after some time? In your video you record the values of the pill press and yes that can have incomplete values depending upon the supply in the system but that's not important.
No. And to reiterate from my above explanation: in my particular setup, supply should _never_ be the issue, as the Reaction Chamber preceding the Chemical Presses ensures that a consistent amount of reagents are flowing into each machine every single time. I do this _specifically_ to ratio my medicine mixes and ensure (in theory) that every product is identical to those produced prior.

>    What is important is the final pill/patch/bottle produced by it also have rounding errors? Cause that's what people are consuming
Yes, the final product was incorrectly ratioed due to lost reagents, which led to potentially hazardous overdoses and necessitated a constant vigil to ensure no one poisoned themselves.

> 3. What type of reactions were occurring at the time of your recording? Cause depending on the conditions they can produce incomplete values which will circulate through the system. However, with right conditions they will produce correct results.
As stated above more clearly, no reactions were occuring in the distribution lines. I couldn't say how many were occuring in the factory itself, but the production and distribution in my example are, for all intents and purposes, segregated from one another.

> 4. How did you build the setup? What was the intake volumes of each reaction chamber, output volumes of each synthesizer?
In the left reaction chamber (not shown in the video), the intake is: 9u Libital, 9u Aiuri, 9u Salicylic Acid, 9u Oxandrolone, 9u Seiver, 5u Salbutamol, 5u Mannitol, 5u Neurine, 5u Oculine, 20u Inacusiate, and 15u Synthflesh. In the right, as shown in the video and stated above: 5u of Multiver, 5u of Diethylamine, 4.5u of Methamphetamine, 3u of Ephedrine, 7u of Mannitol, and 7u of Neurine.

The left line fed into a series of Chemical Filters and Chemical Presses constructed identically to the right, just on another layer. One Filter was responsible for taking the first six reagents (9u Libital, 9u Aiuri, 9u Salicylic Acid, 9u Oxandrolone, 9u Seiver, 5u Salbutamol) and turning them into a single 50u pill. The second set turned the next two reagents (5u Mannitol, 5u Neurine) into a 10u pill. The third turned the next two reagents (5u Oculine, 20u Inacusiate) into a 50u pill. The last turned the final reagent (15u Synthflesh) into a 25u patch. I observed inconsistent results _only on the Oculine/Inacusiate mix._

If you need a more thorough explanation, feel free to ask.

**Comment by jehnicat** [comment] 2024-06-27 17:58
> I have not seen you in your video grinding the pill/patch or examining the final bottle "created by the pill press" to display the reagents produced from it. idk what ratio you are talking about.

Is seeing what's in the Press not enough to convince you of the problem? It should be drawing in precisely how many reagents the Reaction Chamber preceding it sends through, and as both the video and the picture I've included demonstrate explicitly, it's not, and thus any medicines produced from it are absolutely borked.

> Sure the plumbing pill press can have values like 42.99u of a reagent but it will wait for that final 0.01u to come in before it makes a 43u patch.

But it won't make them **correctly.** This is the problem I'm encountering. I'm not sure what you're failing to understand about this.

If I have a Press trying to make a very specific mix with very specific values for each reagent, any deviation in that mix is annoying at best and _lethal_ at worst. If the Press is taking in 42.98u of reagents, it'll draw whatever the hell it wants from the next bunch that gets sent through for that last 0.02u from whatever the Filter permits through.

**Comment by SyncIt21** [comment] 2024-06-27 18:12
> Is seeing what's in the Press not enough to convince you of the problem? It should be drawing in precisely how many reagents the Reaction Chamber preceding it sends through, and as both the video and the picture I've included demonstrate explicitly, it's not, and thus any medicines produced from it are absolutely borked.

> But it won't make them correctly. This is the problem I'm encountering. I'm not sure what you're failing to understand about this.

Reagent volumes deviate & and have errors throughout the course of the plumbing setup. It will eventually correct itself overtime. What's important is the pill press will wait for all this errors to clear up before creating the final patch so your end result will have no problems, which is why I'm not concerned about how volumes change in them.

That's how the code works.

**Comment by Sadboysuss** [comment] 2024-06-27 18:39
>we would already have open issues by now

You'd be surprised how long a bug can go without anyone reporting it

**Comment by jehnicat** [comment] 2024-06-27 18:47
> > we would already have open issues by now
> 
> You'd be surprised how long a bug can go without anyone reporting it

**This.** As mentioned in prior posts, this has been going on _since the change._ I just never bothered to report it because I stopped playing Chemist as much and SS13 in general. I figured it'd be fixed by now, but nope. So here I am.

**Comment by SyncIt21** [comment] 2024-06-27 18:47
> You'd be surprised how long a bug can go without anyone reporting it

Fair point on that but i promise you regarding plumbing i remember spending several hours on elaborate setups. I have created several "NO GBP" pr to fix my mistakes and can proudly say it's fixed for good.

**Comment by jehnicat** [comment] 2024-06-27 18:52
> The behaviour has changed but still produces the correct results. What you think should be happening is no longer the case but the end result is still correct

I've provided explicit evidence to the contrary.

**Comment by SyncIt21** [comment] 2024-06-27 18:54
> I've provided explicit evidence to the contrary.

Let's end the discussion here. Your evidence is pointing to what is considered "normal behaviour" for all plumbing setups. Ping me when people actually start dying from overdose but if not then it's best to just close the issue honestly

**Comment by jehnicat** [comment] 2024-06-27 19:00
> Let's end the discussion here. Your evidence is pointing to what is considered "normal behaviour" for all plumbing setups. Ping me when people actually start dying from overdose but if not then it's best to just close the issue honestly

Losing reagents is not normal behavior.

Factory mixes being off is not normal behavior.

This is a bug.

I have shown video proof of it, and explained the exact process leading up to it.

**Comment by SyncIt21** [comment] 2024-06-27 19:03
> Losing reagents is not normal behavior.
> 
> Factory mixes being off is not normal behavior.

At this point i'm just repeating myself so i won't bother. I won't be responding anymore.

**Comment by jehnicat** [comment] 2024-06-27 19:04
> At this point i'm just repeating myself so i won't bother. I won't be responding anymore.

Please don't. Can I get someone who knows what they're talking about to look at this issue, please?

**Comment by Inari-Whitebear** [comment] 2024-06-27 19:20
Tried a small setup
![dreamseeker_DkKjnHaOB1](https://github.com/tgstation/tgstation/assets/1077971/c79f1b22-e5bf-4b78-ae7e-b39c1022318e)

![oABn8eFpku](https://github.com/tgstation/tgstation/assets/1077971/5bda5af9-b3ef-4aaa-b433-669178f293ac)

So should be those ratios in the end, hopefully, but the actual ground up pill:
![nPPhwwjftr](https://github.com/tgstation/tgstation/assets/1077971/fca8d67c-5b1f-486e-8892-8be6667e58a7)

**Comment by jehnicat** [comment] 2024-06-27 20:18
> Tried a small setup ![dreamseeker_DkKjnHaOB1](https://private-user-images.githubusercontent.com/1077971/343925854-c79f1b22-e5bf-4b78-ae7e-b39c1022318e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTk2NTAsIm5iZiI6MTcxOTUxOTM1MCwicGF0aCI6Ii8xMDc3OTcxLzM0MzkyNTg1NC1jNzlmMWIyMi1lNWJmLTRiNzgtYWU3ZS1iMzljMTAyMjMxOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMjAxNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNDE1NDFjMWVjMWYyYTEyZWQ0MGY4YzVmOGVkMGMyMmU2ZDdiODE5NTQyM2FkZTVjZTFlMjc0NmZkODVkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qLFU1eO_SrHMbIEQ9AwtQ4MH0sET9ABZ3hOUliRyAe4)
> 
> ![oABn8eFpku](https://private-user-images.githubusercontent.com/1077971/343925880-5bda5af9-b3ef-4aaa-b433-669178f293ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTk2NTAsIm5iZiI6MTcxOTUxOTM1MCwicGF0aCI6Ii8xMDc3OTcxLzM0MzkyNTg4MC01YmRhNWFmOS1iM2VmLTRhYWEtYjQzMy02NjkxNzhmMjkzYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMjAxNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZlM2YwMzJhYWM5MzkwZWY4YzE4MzFkZmVkODgzMTdmNDQxZGQ2OGEyOWI4NzhhNzc1MGE0MGQwYzMzNTE3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T98fEnu8L5gcrr3ml7g-qQAzVVa5z7l6-26DXCg4Ex0)
> 
> ![GIHO318HCi](https://private-user-images.githubusercontent.com/1077971/343926552-8a7a5033-c038-41a3-a3a5-6143f39c7a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTk2NTAsIm5iZiI6MTcxOTUxOTM1MCwicGF0aCI6Ii8xMDc3OTcxLzM0MzkyNjU1Mi04YTdhNTAzMy1jMDM4LTQxYTMtYTNhNS02MTQzZjM5YzdhMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMjAxNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAxY2EzZmYzZDkwOTRhZTg3NGE1NWU3OGUwOTU1NzlmOWEyZDI4MjFiYWE1MzVhNWI4OTU5NzZhNGMwNzNiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TgjUWHRsOJ3YdVWFk8Yxffn1ay-9cGPengTMmgpfdnI)
> 
> The top filter filters Sugar, Stable Plasma, Oxygen, and Sodium to the right (press) Bottom filter does nothing
> 
> So should be those ratios in the end, hopefully, but the actual ground up pill: ![nPPhwwjftr](https://private-user-images.githubusercontent.com/1077971/343925942-fca8d67c-5b1f-486e-8892-8be6667e58a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTk2NTAsIm5iZiI6MTcxOTUxOTM1MCwicGF0aCI6Ii8xMDc3OTcxLzM0MzkyNTk0Mi1mY2E4ZDY3Yy01YjFmLTQ4NmUtODg5Mi04YmU2NjY3ZTU4YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMjAxNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ1MzdmODI1N2JhM2NlYmJiODEwNDFmYTBlODczNWFmZDMzMzUyOTI4NTRmMGNlZGM3MTYxMjA1YTUzOTJlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZLtPNTvyIz2fD232_W5B0BeYYs6pq7-U0I2MA7jdLkU) When it should be: Sugar 9u Stable Plasma 6u Oxygen 14u Sodium 14u The issue being that if e.g. sugar ODs at anything about 9u, it might end up above 9u
> 
> If it matters, synthesizers are set to: Alu 5u Bromine 3u Sugar 3u Sodium 5u Oxygen 5u Stable Plasma 5u
> 
> The issue author suggests this behaviour didn't appear in the past, because in the past reagents went through machines in increments of 5u. Then at some point this was changed to push all reagents at once, but restrict the overall flow to 5u still, causing decimal splits, which can cause these rounding errors.

Adding on to this: the factory in the video demonstration I shared initially, faithfully recreated on a local server. You can see the entire process from creation to production from beginning to end, and see that it has the exact same problems as I've listed in my issue report. I've also included the faulty products clearly by dissolving them in a beaker. Link [here.](https://www.youtube.com/watch?v=3SnmvZHogkM)

**Closed** 2024-07-03 21:15 UTC
Labels: Bug
