### ISSUE TITLE
Creating floor tiles in space causes wind.

### ISSUE THREAD

**Issue by Childflayer** [tgstation/tgstation#45665] opened 2019-08-02 04:10 UTC
Just what it says in the title. If you are out in space and build floor tiles (I used an RCD) it creates wind that pushes you around. Using the atmospherics scanner, I determined this to be because creating a tile was creating air as well. Not sure if that is an intended function, but it is pretty annoying to keep getting pushed around when I'm trying to build something in space.

**Comment by Dennok** [comment] 2019-08-02 07:21
Not intended. copy of #45209 #44623

**Comment by PKPenguin321** [comment] 2019-08-02 08:02
Duplicate of https://github.com/tgstation/tgstation/issues/44623

**Closed by PKPenguin321** 2019-08-02 08:02 UTC
