### ISSUE TITLE
Rat King abilities dont work

### ISSUE THREAD

**Issue by Hafahya** [tgstation/tgstation#63779] opened 2022-01-02 20:51 UTC
## Round ID:[175880](https://scrubby.melonmesa.com/round/175880)
Terry

## Reproduction:
Rat king abilities dont work, became a rat via changepool, was used royal cheese on , became a king, abilities appeared. When pressed they do nothing. While ahelping talked to a played that changepool'ed into a dragon, who said they also were a ratking sometime ago, and that their abilities also didnt work

**Comment by SuperNovaa41** [comment] 2022-01-03 03:30
Duplicate of https://github.com/tgstation/tgstation/issues/63758

**Closed by SuperNovaa41** 2022-01-03 03:30 UTC
