### ISSUE TITLE
[ASTEROIDSHUTTLE] Asteroid with engines can't launch to centcomm.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#27162] opened 2017-05-12 00:05 UTC
@kevinz000 You may have better logging than me.

Ignition time is locked at 10.

**Comment by kevinz000** [comment] 2017-05-12 00:09
shitloads of high_pressure_movement() runtimes from the mineral turfs from first glance, round ID  70268 for logs.

**Comment by octareenroon91** [comment] 2017-05-12 01:52
It MAY eventually launch if you give it forever.

Maybe we'll be able to find out if the ground turfs get left behind after that.

**Comment by Profakos** [comment] 2017-05-12 08:14
Dupe of #25550, but this report is closer to finding out the reason probably.

**Closed** 2017-12-05 03:12 UTC
Labels: Bug
