### ISSUE TITLE
Airlock Painters don't paint airlocks.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#36245] opened 2018-03-08 04:04 UTC
Issue reported from  Round ID: 84625 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Using an airlock painter on a finished airlock and selecting an option does nothing to the airlock.

**Comment by ShizCalev** [comment] 2018-03-08 12:27
@kevinz000 attack chain issue? #33166

**Comment by Singularbyte** [comment] 2018-03-08 18:08
Duplicate of #35223?

**Comment by ShizCalev** [comment] 2018-03-09 03:12
duplicate of #35223

**Closed by ShizCalev** 2018-03-09 03:12 UTC
Labels: Bug, Needs Reproducing
