### ISSUE TITLE
Touching the Supermatter at range with TK dusts you

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#52848] opened 2020-08-10 21:09 UTC
I cannot for the life of me imagine this is intentional. If it is, _what the fuck_

## Reproduction:

1) Give yourself Telekinesis
2) Click a Supermatter crystal at range
3) magic_charged.ogg

**Comment by TemporalOroboros** [comment] 2020-08-10 21:18
It's supposed to dust your brain, not the whole mob. Otherwise this is intended.

https://github.com/tgstation/tgstation/blob/f84221285897d8f25ec743fb2422ba9f5be7f768/code/modules/power/supermatter/supermatter.dm#L809-L816

I was going to say that this probably has something to do with the PR that makes it possible to mess with intercoms at range, but I can't find it in the recently merged PRs so...

**Comment by nightred** [comment] 2020-08-10 21:29
do you loss your body also? or just the brain?

**Comment by Timberpoes** [comment] 2020-08-11 07:08
Cannot reproduce dusting of the body.

Dusting of the brain is intended.

![sUyVbuTOxJ](https://user-images.githubusercontent.com/24975989/89867927-d3f18c00-dba9-11ea-8689-a1d66422df19.gif)

![image](https://user-images.githubusercontent.com/24975989/89867913-ce944180-dba9-11ea-8e2d-aea4a7e74e52.png)

**Comment by LemonInTheDark** [comment] 2020-08-11 21:51
feature, not a bug. stop tempting fate.

**Closed** 2020-08-11 21:53 UTC
