### ISSUE TITLE
roburger doesn't do anything

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#30928] opened 2017-09-21 12:41 UTC
it's supposed to give you a disease that borgs you but I've tested it multiple times and have yet to become a borg

**Comment by Repukan** [comment] 2017-09-21 12:47
🅱orging disease 🅱roke

**Comment by praisenarsie** [comment] 2017-09-21 15:45
@XDTM i thought it was a reagent rather than a disease

**Comment by YPOQ** [comment] 2017-09-21 21:57
Can't reproduce. Were you a species immune to diseases?

**Comment by bgobandit** [comment] 2017-09-22 01:36
iirc this was specifically removed

**Comment by XDTM** [comment] 2017-09-23 14:47
it wasn't removed, it seems functional from the code

Did you already have a disease/were an immune species?

**Comment by Cyberboss** [comment] 2017-09-23 15:07
Closing this in 24hrs if no one can reproduce. Sounds like the disease just didn't run for some reason

**Comment by YakumoChen** [comment] 2017-09-27 02:49
I was human and I ate the roburger as is. Got it from Silver Slime foods. It's difficult to reproduce due to the difficulty of actually acquiring one.

**Comment by Cyberboss** [comment] 2017-09-30 14:57
Just ate a roburger on sybil and waited, worked fine

**Comment by ShizCalev** [comment] 2018-06-01 18:17
24 hours passed, no repo

**Closed by ShizCalev** 2018-06-01 18:17 UTC
Labels: Bug, Needs Reproducing
