### ISSUE TITLE
Electrified grilles explode things without logging the explosion

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#79312] opened 2023-10-27 14:28 UTC
Reporting client version: 514.1589

## Round ID:
[217550](https://scrubby.melonmesa.com/round/217550)

## Reproduction:

And I can't tell if the grill or the zap exploded because none of it got logged.

1) Run a length of wire under the floor
2) spawn an rtg/debug on one end, var edit it to power_gen=800000
3) shove a full tile non reinforced window in the middle with an RCD (or just make a grille here, saves steps)
4) multitool test the top of the wire to ensure the power is correct (beware shocks)
5) spawn a crowbar/large/emergency
![image](https://github.com/tgstation/tgstation/assets/3789327/9bc37d95-caab-444d-8f33-29c7c3a5aff8)
6) break window down to grille if necessary
7) stand back, throw crowbar at window
8) boom

It seems the RTG explodes from the zap, however, in the example i saw in game its the airlock that got hit and explodes.  I reconstructed the airlock version and the same happens, a hole to space from the exploding airlock.

This is all unexpected but whatever, however, there is zero admin explosion logging for this new hole to space.

**Comment by Isratosh** [comment] 2023-10-27 18:33
Can confirm I have witnessed a grille explosion on Manuel like yesterday with ~2 MW in the grid with no admin log, it made like 6 holes to space. I hope this comment was helpful.

**Comment by Pickle-Coding** [comment] 2023-10-30 12:53
I imagine it's related to #79297. Tesla zaps might have done extra stuff based on power that I did not scale. I'll investigate after I setup git and my repository again.

**Comment by Pickle-Coding** [comment] 2023-10-30 13:29
Actually it doesn't seem like grilles pass zap explosive flags in any scenarios. Zap act for rtg or parents doesn't explode without the flag. tesla_zap() doesn't modify zap flags in any scenarios. No idea what's going on. I'll try to reproduce it.

**Comment by Pickle-Coding** [comment] 2023-10-30 13:48
Okay so for whatever reason zap_flags is a list of objects assigned to numbers. This is causing weird behavior.

**Comment by Pickle-Coding** [comment] 2023-10-30 14:25
Oh I see why this is happening. I added an argument to tesla_zap, but some callers of tesla_zap (the recursive one in tesla_zap, so basically every zap except the first one) relied on positional arguments. Zap_flags got fed shocked_targets due to this.

**Closed** 2023-10-31 17:10 UTC
Labels: Bug, Logging
