### ISSUE TITLE
Using telekinetically held objects on electrified objects electrocutes you.

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#12375] opened 2015-10-13 20:24 UTC
During the latest malf round (as of the time I submitted this issue), I got TK from genetics. I used my powers to try and pry open a door with a crowbar. I got shocked into crit by a door I wasn't even touching.

Steps to replicate:
1) Get TK
2) Electrify Door
3) Telekinetically Manupulate Crowbar
4) Use Crowbar on Door
4.5) Take Off Insulated Gloves
5) Get Shocked

**Comment by Xhuis** [comment] 2015-10-13 20:58
I feel like this is kind of intentional.

**Comment by xxalpha** [comment] 2015-10-13 21:29
I feel like this is a duplicate.

**Comment by CosmicScientist** [comment] 2015-10-13 23:15
#3807 - "Shocked doors will shock you via telekinesis" (Closed)
'Fixed' but I don't know how. @Razharas closed it and I can't find the relevant PR.

**Comment by Jalleo** [comment] 2015-10-14 17:23
Ah this old bug.

**Comment by Tungul** [comment] 2017-03-19 04:20
Sorry for necrobump - just attempted to reproduce this using commit 742fcf0ffea1012ef7906222695461b85b7f9396 (the newest one I had on hand - should still be good enough, yeah?). No luck - I'm assuming it has to do with the new telekinesis setup where you drag things instead of the older ghetto normal-hand-used-at-range.

In order to reproduce this, I activated the electricity on an airlock (on omega station) and shocked myself by cutting the wires at close range. I moved away, activated telekinesis with the telemut injector spawned in, and used a telekinetically moved wirecutter to open the dialog, and another pair of wirecutters in my other hand to actually do the cutting (since you can't do it otherwise.) I'm not sure if this workaround is technically a bug or not, but either way, the door doesn't shock you anymore.

I think this is not a problem anymore.

**Comment by xxalpha** [comment] 2017-03-19 10:43
Ping a maintainer then.

@Cheridan @optimumtact @lzimann @RemieRichards @WJohn

**Closed** 2017-03-19 13:15 UTC
Labels: Bug
