### ISSUE TITLE
Wheelchairs break when you slip while trying to get on one.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#67919] opened 2022-06-21 22:24 UTC
Split from #67912 to keep things tidy

Imagine this. You're on top of the world, you've FINALLY cajoled the scientists into actually upgrading your chair's manipulators and capacitors and such so that you can move faster than a snail pace, and you run across a single tile of space lube.
It fires you off of the chair and along the floor.
You're in a hurry. Maybe the clown who put the lube down is chasing you, I don't know. You drag yourself back onto your chair.
And then you realise your mistake as you immediately slip off the chair a second time... And even once the lube is gone, **you can never use that chair again.**

Currently, wheelchairs are immune to slipping on soap and banana peels and such because of the vehicle code, but space lube still slips you-- that's not the issue. The issue is that if you drag yourself back onto the chair while any slippery object or substance is on the tile, it fucks up the chair and means that even once it's not on a slippery surface, you can never buckle onto it again. I think this might be because the chair still thinks someone's buckled onto it. The only fix I know of for this issue in-game is to disassemble the chair and reassemble it, which is kind of hard as you can't craft things while lying on the ground. This, alongside the next two issues, mean that as a paraplegic character you ALWAYS need to keep a spare manual wheelchair folded in your backpack.
This might also work for normal chairs too.

**Reproduction:**
try to buckle yourself to a chair with a slippery substance such as space lube or water on the tile. You'll slip.
After you've slipped, try again to buckle back into that chair. You will be unable to.

**Comment by VladinXXV** [comment] 2022-06-23 05:19
This happens with other vehicles (namely I've seen it with ATVs)

**Comment by timothymtorres** [comment] 2023-01-01 00:24
Duplicate of #67841

**Closed by timothymtorres** 2023-01-01 00:24 UTC
Labels: Bug
