### ISSUE TITLE
Examing a monkey gives multiple images instead of one.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#28968] opened 2017-07-01 03:47 UTC
When you examine a item you get a small visual of it in the chat but for monkeys it's glitched and will show multiple.

**Comment by PKPenguin321** [comment] 2017-07-01 10:31
Dupe

**Comment by Cyberboss** [comment] 2017-07-05 02:10
Dupe of #28322

**Closed by Cyberboss** 2017-07-05 02:10 UTC
