### ISSUE TITLE
Scuffed missing limbs.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48233] opened 2019-12-13 11:34 UTC
![Снимок](https://user-images.githubusercontent.com/35217076/70797442-97b92200-1db5-11ea-9fc8-99757174c8d8.PNG)
![Снимок1](https://user-images.githubusercontent.com/35217076/70797445-9a1b7c00-1db5-11ea-87c0-615559a76d0f.PNG)

I don't have arms on both pics. The fuck is this?

**Comment by Time-Green** [comment] 2019-12-13 15:31
Ask a doctor for prosthetic replacement surgery

**Comment by HomocidlePancakes** [comment] 2019-12-13 19:29
Yeah, I was talking about the weird red spots.

**Comment by PKPenguin321** [comment] 2019-12-13 19:32
Fairly sure that this is an ancient dupe

**Comment by kriskog** [comment] 2020-01-02 12:34
dupe of #32661

**Closed by kriskog** 2020-01-02 12:34 UTC
