### ISSUE TITLE
heretic circle unclickable in certain areas?

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#81137] opened 2024-01-28 02:23 UTC
roundid 222915

birdshot, was unable to click the rune in these locations, but other locations worked?
![image](https://github.com/tgstation/tgstation/assets/105343481/5b6c756d-c4f6-450a-bcda-dd06776c4476)

this spot on lavaland mining as well
![image](https://github.com/tgstation/tgstation/assets/105343481/89b71fc0-8eae-4095-a71f-c0f9ea91be9f)

**Comment by MrMelbert** [comment] 2024-01-28 02:28
Dupe of #81095 And likely #81074

**Closed by MrMelbert** 2024-01-28 02:28 UTC
