### ISSUE TITLE
Bodybags inside morgue trays are inescapable prisons

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#49080] opened 2020-01-30 02:26 UTC
Place yourself a body bag

Have bodybag put in a morgue tray

Close morgue tray

The player inside is now unable to resist out or move to open the bag and tray

Issue reported from  Round ID: 129223 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

**Comment by ATH1909** [comment] 2020-01-30 03:24
Yep, this is a known issue.

**Comment by Tlaltecuhtli** [comment] 2020-01-30 09:35
dont get buried alive next time

**Comment by dragomagol** [comment] 2020-12-24 03:48
Duplicate of #31656

**Closed by dragomagol** 2020-12-24 03:48 UTC
Labels: Bug
