### ISSUE TITLE
Straight Jackets can't be resisted out of

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#47428] opened 2019-10-27 03:55 UTC
## Reproduction: 
Put on straight jacket
try to resist out
wait 5 minutes for progress bar to complete
nothing happens once bar is complete

I tried this with both straight jacket and cuffs and just a straight jacket. Neither can actually be resisted out of even after waiting 5 mins

**Comment by Timonkeyn** [comment] 2019-10-27 07:07
Is this how houdini died???

**Comment by Time-Green** [comment] 2019-10-27 13:15
This broke about 8 times now?

**Comment by PKPenguin321** [comment] 2019-10-28 01:55
Probably a dupe

**Comment by willox** [comment] 2019-10-28 13:16
old dupe, but this was caused by https://github.com/tgstation/tgstation/pull/45127 only allowing leg/hand cuffs to be removed.

**Comment by kriskog** [comment] 2019-11-10 22:58
dupe of  #46379

**Closed by kriskog** 2019-11-10 22:58 UTC
Labels: Bug
