### ISSUE TITLE
plasmamen are slow again

### ISSUE THREAD

**Issue by gorillion** [tgstation/tgstation#86483] opened 2024-09-04 23:37 UTC
### Client Version:

515.1640

### Issue Summary:

joined as my plasmaman static, palladium xiv
noticeably slower than everyone else, no mood debuffs or abnormal suit
this happened before, it was related to some space suit slowdown but it was fixed a few weeks back, i guess it's returning

### Round ID:

[236687](https://scrubby.melonmesa.com/round/236687)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)

### Reproduction Steps:

1) join as plasmaman
2) go slow

**Comment by deathrobotpunch** [comment] 2024-09-05 00:31
hooray

**Comment by Likteer** [comment] 2024-09-07 00:19
priority: CRITICAL

**Comment by SmArtKar** [comment] 2024-09-07 19:52
slowdown on the helmet is back, hooray

**Comment by SmArtKar** [comment] 2024-09-07 19:54
oh nevermind, closing as a duplicate of #85850 - the original never got fixed

**Closed by SmArtKar** 2024-09-07 19:54 UTC
Labels: Bug, Tested/Reproduced
