### ISSUE TITLE
Pluming using reaction chamber to make plastic breaks the reaciton chamber

### ISSUE THREAD

**Issue by Autisem** [tgstation/tgstation#47220] opened 2019-10-19 09:43 UTC
## Reproduction: 1. Get reaction chamber
2. but the oil, sulp acid, and ash trough it.
3, Heat to oil production
4. After the oil is made. it wont demand any new chems

**Comment by Time-Green** [comment] 2019-10-19 11:49
Duplicate of #47154

Also fixed in #47190

**Comment by kriskog** [comment] 2019-10-19 12:07
dupe

**Closed by kriskog** 2019-10-19 12:07 UTC
