### ISSUE TITLE
Movement is completely broken

### ISSUE THREAD

**Issue by SoSMaster9000** [tgstation/tgstation#54092] opened 2020-09-30 03:30 UTC
Issue reported from  Round ID: [147341](https://scrubby.melonmesa.com/round/147341) (/tg/Station - Terry [EU] [100% LAG FREE])

Reporting client version: 513.1532

Every time I attempt to activate Hotkey mode, it immediately deactivates. As well, when I attempt to move using the arrow keys, the keys do not keep moving me when held down, so that I have to push the key every single time I move a single tile.

**Comment by SoSMaster9000** [comment] 2020-09-30 03:32
Probably should've titled this "Player movement is completely broken" but you can't change the past.

**Comment by Couls** [comment] 2020-09-30 05:26
Should be fixed, i'll close this tomorrow if the issue is still happening please let me know so I can look into it

**Comment by nightred** [comment] 2020-09-30 13:28
Reports that PR #54091  fixed this issue. waiting on server to update files.

**Comment by Couls** [comment] 2020-09-30 13:34
terry updated an hour ago, manuel and sybil updated midnight last night and bagil updated 3 hours ago, movement should work on all servers now

**Closed by Couls** 2020-09-30 13:34 UTC
Labels: Needs Reproducing
