### ISSUE TITLE
Spammy ghost follow links

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#24926] opened 2017-03-10 05:32 UTC
@coiax 
![untitled](https://cloud.githubusercontent.com/assets/8171642/23783361/18ae23ea-0529-11e7-9418-86b8e9f3956f.png)

**Comment by PKPenguin321** [comment] 2017-03-10 05:40
Dupe of https://github.com/tgstation/tgstation/issues/24925

**Closed** 2017-03-10 05:54 UTC
