### ISSUE TITLE
Loaning the shuttle sometimes doesn't loan it

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63047] opened 2021-11-24 14:37 UTC
## Testmerges:
The following pull requests are currently test merged:
#62132: 'multiz movement refactor redux' by Ghommie at commit b69e66961d

## Reproduction:
Hit loan shuttle with some vegetables ordered from "the service console" but I'm pretty sure the chef didn't understand my question or the difference between that and the produce console so it could have been either of them
instead of a bunch of cool spiders showing up 5 minutes later it's just the 2 crates of vegetables and the mail
where are my ninja tabi
where are they

it said "loaned to centcomm" for the rest of the round but the shuttle still worked
https://puu.sh/Ircw6/590b6e8d0f.png

**Comment by SuperNovaa41** [comment] 2021-11-24 19:09
can confirm this has happened to me before

**Comment by Sealed101** [comment] 2024-10-15 20:40
couldn't reproduce; no runtimes or logs tied to this either. possibly fixed by https://github.com/tgstation/tgstation/pull/72998

**Closed by Sealed101** 2024-10-15 20:39 UTC
Labels: Bug, Needs Reproducing
