### ISSUE TITLE
Borgs can buckle mobs to chairs and such, but can't unbuckle them

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43058] opened 2019-03-08 01:56 UTC
Presumably, this is because buckling someone to something uses MouseDrop_T, which borgs CAN do, but unbuckling someone from something uses attack_hand.

This has been reported and marked as an oversight twice before, but still is not fixed:
https://github.com/tgstation/tgstation/issues/42093
https://github.com/tgstation/tgstation/issues/37131

IMO, we should let borgs both buckle AND unbuckle people and not just remove the ability for borgs to buckle people to stuff. Borgs have enough dexterity to free people from cuffs without wirecutters (and even APPLY cuffs, in the case of standard borgs) and drag people; it's logical that they'd be able to loop cuffs through the arms of a chair or something.

**Comment by ShizCalev** [comment] 2019-03-11 10:40
Duplicate of #37131

**Closed by ShizCalev** 2019-03-11 10:40 UTC
