### ISSUE TITLE
Shuttle + Blueprints Issue

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#35005] opened 2018-01-27 07:25 UTC
[Reproduction]: Using blueprints, you can break shuttles permanently or make parts of the station into a 
shuttle.
[Round ID]: 82623
![idgurxg](https://user-images.githubusercontent.com/29403316/35469703-2f3b51bc-0309-11e8-821f-0d591161cb56.png)

EDIT: sorry for wrong format, but it fucking won't work because of copy and paste

**Comment by Jalleo** [comment] 2018-01-27 09:56
I believe this is already reported.

**Comment by ninjanomnom** [comment] 2018-01-27 14:56
duplicate of #33104

**Closed by ninjanomnom** 2018-01-27 14:56 UTC
