### ISSUE TITLE
fireman carrying someone into the portal to escape the cascade does not carry the person with you

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70075] opened 2022-09-22 14:20 UTC
Reporting client version: 514.1585

## Round ID:
[190960](https://scrubby.melonmesa.com/round/190960)

## Testmerges:
- [Micros the lighting subsystem (Saves a second of init)](https://www.github.com/tgstation/tgstation/pull/69838)
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)

## Reproduction:
after an arduous process and with almost no time to spare, revive your ssd blood brother
fireman carry them so you can more easily get them to the portal
step through the conveniently located portal
you arrive at centcomm
they do not

**Comment by Rhials** [comment] 2022-09-22 20:06
I believe this issue persists with most forms of portal transport, such as anomaly wormholes or hand teleporter portals

**Comment by timothymtorres** [comment] 2022-09-23 07:48
Duplicate of #62343

**Comment by timothymtorres** [comment] 2022-09-23 07:49
Also please make sure you are double checking that the issue doesn't already exist by searching the issue tracker since there have been a lot of "duplicate" reports that are getting spammed.

**Closed by timothymtorres** 2022-09-23 07:48 UTC
