### ISSUE TITLE
Computer circuit boards are deleted when the computer is deconstructed

### ISSUE THREAD

**Issue by jaw-sh** [tgstation/tgstation#55131] opened 2020-11-23 14:00 UTC
## Reproduction:
1. Find any computer that has been built to completion
2. Remove the circuit board as you would normally when deconstructing it.
3. The board will not be returned.

This is upstream /tg/ and is currently live on Terry. It's affecting downstream forks. Started happening this morning, I don't remember it happening yesterday.

What I've found:
* The board is completely deleted, it's not simply misplaced in the map.
* Removing the board before the computer has been completed _will_ return the board, but
* Any completed computer (built during the round or spawned during map generation) _will not_ return its board.
* Does not affect machines.

**Comment by jaw-sh** [comment] 2020-11-23 14:12
Map spawned computers contain circuits with a null `loc` property. Computers you build retain their `loc`, but once deconstructing a machine starts, the `loc` turns to null as well. I think this is why they just get deleted. Once `circuit = null` is called, the GC deletes it because it's not been placed in the game.

**Comment by jaw-sh** [comment] 2020-11-23 14:23
I think this has to be an issue with `/atom/movable/proc/forceMove`.

In _computer.dm, this is called when deconstructing a computer (which deletes the computer and replaces it with a frame object).
```
			var/obj/structure/frame/computer/A = new /obj/structure/frame/computer(src.loc)
			A.setDir(dir)
			A.circuit = circuit
			circuit.forceMove(A)
			A.set_anchored(TRUE)
```

And this is when the frame has its board removed in buildandrepair.dm
```
				circuit.forceMove(drop_location())
				circuit.add_fingerprint(user)
				circuit = null
```

In the first instance, `loc` is set to null. In the second, the circuit is simply deleted, probably because `loc` again doesn't change and the only reference to it is deleted.

**Comment by brotherbeyondd** [comment] 2020-11-23 14:32
#55126 should deal with it

**Comment by dragomagol** [comment] 2020-11-23 17:06
#55111

**Comment by Fikou** [comment] 2020-11-23 22:29
Duplicate of #55111

**Closed by Fikou** 2020-11-23 22:29 UTC
