### ISSUE TITLE
Console screens are placed above all other sprites

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40122] opened 2018-09-05 18:13 UTC
![image](https://user-images.githubusercontent.com/38788538/45112505-7bf5b380-b150-11e8-9178-3afa19c6628d.png)

**Comment by Arkvold** [comment] 2018-09-05 18:35
Sounds a lot like #40048, and a symptom of the new luminescent screens implemented in #39973.

**Comment by SpaceManiac** [comment] 2018-09-06 06:39
Duplicate of #40048

**Closed by SpaceManiac** 2018-09-06 06:39 UTC
