### ISSUE TITLE
Mesons can see item pickup transitions through walls

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69363] opened 2022-08-21 22:45 UTC
Reporting client version: 514.1585

## Round ID:
[188980](https://scrubby.melonmesa.com/round/188980)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:

Find a friend
Spawn both in thunderdome
Create a wall between you
Have a player on one side wear meson scanners in meson scanning mode
Have a player on the other side just throw something at the wall, pick it up, throw it etc
You'll be able to see the picking up of the item through the wall, including the ability to identify the item.
This is pretty bad when an engineer sees someone picking up a syndie box in the barkeepers room and moments later the barkeeper walks out (the actual situation that got reported originally, this is the repro)

E.g. while its hard to get a good freezeframe with just printscreeen, my help on the other side of the wall is picking up a plasma internals tank

![image](https://user-images.githubusercontent.com/3789327/185813977-5609ae4c-607e-4387-9f6b-04f2d2f594b8.png)

**Comment by timothymtorres** [comment] 2022-08-21 23:06
Duplicate of #39799

**Closed by timothymtorres** 2022-08-21 23:06 UTC
