### ISSUE TITLE
Sticky Tape can only be printed one at a time in autolathe

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#55882] opened 2021-01-01 16:07 UTC
This is AWFUL and SLOW

**Comment by ArcaneMusic** [comment] 2021-01-04 06:14
Is this a dupe of #55528?

**Comment by Tlaltecuhtli** [comment] 2021-01-04 12:01
no

**Comment by Pugie** [comment] 2021-01-11 14:25
![image](https://user-images.githubusercontent.com/41806499/104194129-d25a1780-5418-11eb-9871-8faa717e21a9.png)
how is this not a bug dragomagol can you explain?

**Closed** 2021-02-11 18:39 UTC
Labels: Not a bug
