### ISSUE TITLE
Putting GBS bottle into Pan.D.E.M.I.C machine breaks UI

### ISSUE THREAD

**Issue by JJtheGerman** [tgstation/tgstation#63229] opened 2021-12-03 16:15 UTC
Reporting client version: 514.1571

## Round ID:
[174117](https://scrubby.melonmesa.com/round/174117)

## Reproduction:

Didn't check repro step, but perhaps putting a GBS bottle that you get from a virus crate always causes the bug?

TypeError: Unable to get property 'length' of undefined or null reference
   at f (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:1109082)
   at Ie (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:179720)
   at Me (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:22106/tmp16248/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"jjg","interface":"Pandemic","window":{"key":"[0x2004877]-main","size":null,"fancy":1,"locked":1}}

**Comment by SuperNovaa41** [comment] 2021-12-03 17:42
Duplicate of #https://github.com/tgstation/tgstation/issues/63155

**Closed by SuperNovaa41** 2021-12-03 17:42 UTC
