### ISSUE TITLE
Some time after opening SS13, all extra windows (consoles, stripping menu, build menu, etc) turn completely white and unusable

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#31745] opened 2017-10-15 03:44 UTC
[Directions]: 77453, but also all the rounds I've played for the past week. As per the title, any window that I try to open is completely white and unusable after a few minutes. The only fix I've found is restarting byond, but that will only solve the problem for a few minutes. I am on the latest BYOND build, latest IE build, etc. Windows 10.

**Comment by Shadowlight213** [comment] 2017-10-15 04:12
This is the same bug myself and a few other people have been having for months.
We haven't been able to track down the cause of it unfortunately.
@MrStonedOne not sure if this is related at all to the bug, but last time It triggered, I got this message whenever I moused over chat.
![](https://puu.sh/xYqTB/93c0123be7.png)
It stayed like that until I restarted the game, after which the bug fixed itself and the message disappeared.

**Comment by newfren** [comment] 2017-10-15 06:22
My cursor does occasionally pop up with the loading symbol like it's trying to load something in but even leaving the window open for 3 or 4 minutes doesn't fix it. The game is borderline unplayable.

**Comment by ShizCalev** [comment] 2017-10-16 23:08
Gonna assume this is a BYOND issue of some kind.

**Comment by newfren** [comment] 2017-10-22 14:48
This stopped happening after I paid for 2 years of BYOND membership so I can only assume that is a fix.

**Comment by Shadowlight213** [comment] 2017-10-22 17:42
I've been a byond member for a few years, so thats unlikely.

**Comment by Shadowlight213** [comment] 2017-11-15 06:15
Ok, so mso and I found out that force reloading goonchat will fix the white screen bug.
Another symptom of the bug seems to be goonchat failing to download images for examining.

**Comment by ShizCalev** [comment] 2017-12-12 03:50
http://www.byond.com/forum/?post=2211145

**Comment by actioninja** [comment] 2019-11-15 01:35
Closing and referring to megathread

**Closed by actioninja** 2019-11-15 01:35 UTC
Labels: BYOND Issue, Bug, Needs Reproducing
