### ISSUE TITLE
Infinite flasks of holy water from personal crafting without required materials

### ISSUE THREAD

**Issue by sotvec** [tgstation/tgstation#48526] opened 2020-01-02 01:32 UTC
Issue reported from  Round ID: 127231 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488

**Comment by swindly** [comment] 2020-01-02 01:41
Dupe of https://github.com/tgstation/tgstation/issues/48518?

**Comment by Krysonism** [comment] 2020-01-02 03:40
I will look into this, maybe i messed up.

Holy water flask crafting was the last flask i added.

**Comment by kriskog** [comment] 2020-01-02 12:20
Likely a dupe, yeah. Leaving this open for now though, someone should test it after #48520 is merged.

**Comment by kriskog** [comment] 2020-01-02 20:08
Crafting the holy water bottle from a bottle of holy water causes this to runtime and not delete the requirements.
```
Runtime in crafting.dm, line 252: Cannot read null.reagents
proc name: del reqs (/datum/component/personal_crafting/proc/del_reqs)
usr: Skoglol/(Scott Smith)
usr.loc: (Bar (131, 130, 2))
src: /datum/component/personal_craf... (/datum/component/personal_crafting)
call stack:
/datum/component/personal_craf... (/datum/component/personal_crafting): del reqs(Holy Water Flask (/datum/crafting_recipe/holybottle), Scott Smith (/mob/living/carbon/human))
/datum/component/personal_craf... (/datum/component/personal_crafting): construct item(Scott Smith (/mob/living/carbon/human), Holy Water Flask (/datum/crafting_recipe/holybottle))
/datum/component/personal_craf... (/datum/component/personal_crafting): ui act("make", /list (/list), /datum/tgui (/datum/tgui), /datum/ui_state/not_incapacita... (/datum/ui_state/not_incapacitated_state))
/datum/tgui (/datum/tgui): Topic("src=%5B0x210094bd%5D&action=ma...", /list (/list))
Skoglol (/client): Topic("src=%5B0x210094bd%5D&action=ma...", /list (/list), /datum/tgui (/datum/tgui))
Skoglol (/client): Topic("src=%5B0x210094bd%5D&action=ma...", /list (/list), /datum/tgui (/datum/tgui))
```

**Comment by Krysonism** [comment] 2020-01-04 13:47
This is my fault. 

These recipes are meant to use the plain bottle subtype instead of the parent bottle type.

**Comment by TheBonded** [comment] 2021-12-09 17:15
better documentation in https://github.com/tgstation/tgstation/issues/49273

**Closed by TheBonded** 2021-12-09 17:15 UTC
Labels: Bug
