### ISSUE TITLE
I spawned into the start location

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59542] opened 2021-06-07 08:23 UTC
Reporting client version: 514.1552

## Round ID:
[163645](https://scrubby.melonmesa.com/round/163645)

## Testmerges:
- [2FA for Admins](https://www.github.com/tgstation/tgstation/pull/59467)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Disables the keybinding conflict message to players DO NOT UNTESTMERGE](https://www.github.com/tgstation/tgstation/pull/59490)

## Reproduction:
1, Latejoin Sybil as a lizard paramedic on Delta Station
2. ![trapped](https://user-images.githubusercontent.com/53582584/120983729-d6236900-c72e-11eb-9685-a60a45cf03bb.png)

**Comment by dragomagol** [comment] 2021-06-07 16:38
Duplicate of #58341

**Closed by dragomagol** 2021-06-07 16:38 UTC
Labels: Bug
