### ISSUE TITLE
Screen randomly freezing

### ISSUE THREAD

**Issue by Balrog-was-here** [tgstation/tgstation#2601] opened 2014-02-02 18:02 UTC
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!):

Multiple (latest is 6908a7194b207a0421dbe2886bfd57beba8b6915)
##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.)

Sybil
###### What did you expect to happen?

The game's icon display to work
###### What happened instead?

Randomly the screen will completely freeze. Text input and output work fine, but the display is completely frozen. Toggling text mode makes the display update but it stays frozen on the new display. The status bar for object names works and reflects the state of the display when it froze.
###### Why is this bad/What are the consequences?

Because it forces you to relog at inopportune times
##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!):
1. Log in
2. Play the game
3. Wonder why you aren't moving
##### Anything else?

This was on BYOND 503.1224

**Comment by laser50** [comment] 2015-01-11 03:17
This has been around for ages and frankly, I believe Lummox or Tom even said they know about this but aren't sure what's going on.

**Comment by freerealestate** [comment] 2015-06-10 00:25
Still a bug

**Comment by Aranclanos** [comment] 2015-06-10 02:25
I need someone to make a thread in byond forums, if I keep annoying him he'll murder me

**Comment by freerealestate** [comment] 2015-06-10 12:53
I can make a thread, if you link me to the appropriate subforum. What does it need to say?

**Comment by Aranclanos** [comment] 2015-06-10 19:18
http://www.byond.com/forum/?forum=5
I think that the info of this issue should be enough, the screen freezes, the text works fine and your actions also work (like moving around)

**Comment by freerealestate** [comment] 2015-06-11 01:24
Okay, done. I expect it to get closed if it's already been reported though.

**Comment by optimumtact** [comment] 2017-01-10 00:18
See also #21264

**Comment by nicbn** [comment] 2017-07-28 21:59
BYOND haven't fixed this yet?

**Comment by Silvaplex256** [comment] 2018-01-10 19:17
No. This is a very, very old known bug that's on BYOND's end. Apparently, it's caused by the client failing to update the viewport and causing a freeze. Current possible workarounds are:

- Clearing your cache
- Turning off hardware rendering
- Turning off stretch-to-fit
- Closing and reopening your client

Only the latter one works 100% of the time, the rest seem to delay the issue.

[Here](http://www.byond.com/forum/?post=1825847)'s the appropriate BYOND forums thread.

**Comment by nicbn** [comment] 2018-11-24 22:51
Should we really keep this issue open? It's not actually an issue with our code

**Comment by theOperand** [comment] 2018-11-24 23:48
i should have closed this 5 years ago tbh, as its certainly not an issue with tg even if it's still a byond issue, so why is it even on the tg issue tracker

let sleeping oldcoders lie

**Comment by optimumtact** [comment] 2018-11-27 01:12
it's still an issue

**Comment by actioninja** [comment] 2019-08-13 08:18
still an issue.

**Comment by coolsurf6** [comment] 2019-11-18 05:33
Not sure, but I think this still is an issue.

**Comment by Tharcoonvagh** [comment] 2019-11-18 22:32
Wow

**Comment by StarSmasher44** [comment] 2019-11-19 00:12
The issue lies somewhere deep within the bowels of BYOND where it just stopt updating the viewport, the rest still works fine and a rejoin always fixes it.

Should be safe to close, you really can't do much about this if it is still even an issue, haven't touched BYOND in years.

**Comment by SweptWasTaken** [comment] 2020-02-03 17:34
issue persists

**Comment by BootlegBow** [comment] 2020-11-09 22:52
mmmmm 2014 issue

**Comment by LemonInTheDark** [comment] 2020-11-09 23:18
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by Putnam3145** [comment] 2020-11-10 02:27
i will join in confirming that this is still a problem

**Comment by Gandalf2k15** [comment] 2020-11-10 02:29
Still an issue.

**Comment by KathrinBailey** [comment] 2020-11-10 02:34
I will also be joining and confirming it is still a problem.

**Comment by Cyberboss** [comment] 2020-11-10 02:35
seen it myself a lot recently

**Comment by optimumtact** [comment] 2020-11-10 02:36
people lets refrain from spamming the ticket with things that don't add much to the conversation, thanks

**Comment by karmakarmakarmakarmakarmakarmakarma** [comment] 2021-01-28 10:56
>he didn't fix this in his cheat

**Comment by AnCopper** [comment] 2021-08-15 22:18
Still an issue, I believe it has something to do with Byond.

**Comment by chizzy376** [comment] 2023-09-01 09:31
issue still persists and happens at random intervals, had to restart launcher to stop the freeze.

**Comment by NexusLeader** [comment] 2024-06-15 00:46
why is this still here

**Closed** 2024-06-22 02:34 UTC
Labels: Bug, BYOND Issue

**Comment by Bawhoppen** [comment] 2024-06-22 03:10
We're finally free.

**Comment by LemonInTheDark** [comment] 2024-09-12 07:53
is this actually fixed? if it keeps happening it seems worthwhile to document it
