### ISSUE TITLE
Cult target being destroyed prevents any summon

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#44917] opened 2019-07-02 02:01 UTC
## Round ID:
#112121

## Testmerges:
#44310

## Reproduction:
chaplain figures out they're target, cremates themself, cult is left unable to do any summon since their body was destroyed by other means.

probably intended tbh but
delet cult

**Comment by necromanceranne** [comment] 2019-07-02 03:54
To elaborate on this I found out I was the target via pretty simple deductive reasoning. I knew the cult had caught all of security and they were coming for me by the time I did it. That, and imsxz gave it away but I already knew.

This is something I'd learned I could do via pure accident. I saw a chaplain once get dunked then soulsharded with his own soulstone by a random greyshit. This however happened to have also caused the cult in that round to be completely unable to summon and therefore lost in exactly the same way.

My action was deliberate. The other one completely incidental. But it isn't entirely impossible for it to just happen on accident. Chaplains have no obligations to stay on the station at all. And so are maybe one of the only targets for cult rounds who can end up getting gibbed irrevocably without it being straight metagaming. Chaplains going down to lavaland can be killed in a permanent manner in a whole host of ways.

There isn't any ingame process to reassign a cult target upon their complete annihilation. There probably should be to avoif aborted rounds like this.

**Comment by HomocidlePancakes** [comment] 2019-07-02 09:36
I thought this was banable.

**Comment by kriskog** [comment] 2019-07-02 09:47
New cult meta. Just cremate the captain, chaplain and all of sec to guarantee victory.
There should just be a repick of target when this happens, among other valid targets.

**Comment by py01** [comment] 2019-07-02 16:55
This has been around for a while, not sure if it's been officially reported before. Usually when it happens an admin just sets a new target or marks the cult as being able to summon. But a non-admin way to resolve this would be good.

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-07-02 17:13
I've always considered it a deterrent for cult to not just bomb (and previously bloodboil) indiscriminately. I don't really consider it a bug, It's just that the player motive is trash.

The same could be said for any objective really. I personally would consider this more of an admin issue than a code one. The code can't really differentiate between accidental destruction of a body and purposefully/malicious destruction of a body.

Push comes to shove though we can replace the mob offer with say the nullrod or librarian tome or something. We can't have the cake and eat it too guys.

**Comment by ATH1909** [comment] 2019-07-02 20:54
> New cult meta. Just cremate the captain, chaplain and all of sec to guarantee victory.

I've known about this trick for a long time and have even suggested to my mindshielded staff as a captain that we should all cremate ourselves before, but for some reason, they didn't want to do it...

**Comment by YakumoChen** [comment] 2019-07-03 03:16
I mean it's essentially the same as hiding out on lavaland or some other mostly-unreachable place. The only problem becomes when the cult delays the shuttle indefinitely while they try and find the target.

**Comment by necromanceranne** [comment] 2019-07-03 06:35
The fact that an incidental destruction of a body can have no metagame reasons but still abort the entire round is a bad problem to leave unfixed. It is actually a pretty major oversight to the game mode even if it is hard to pull off deliberately, and by extention something that might require administrative policy (though I don't understand why we would punish people for taking themselves out of the round. That seems really stupid even if it is to stop the cult winning and I don't think we can properly even enforce that in most cases, like carrying suicide bombs or something. We can't tell the difference between simply being self sacrificing to achieve victory or deliberate metagaming in a situaion like that but it can have the same results, and there are situations that suicide bombings are allowed by the rules.)

While it might allow for the cult to simply bomb their targets without consequence (something that doesn't make a lot of sense to me in the first place as being a bad thing when other similar game modes don't care how the target dies, just that they die),  it at least accounts for these edge cases. Any solution is better than no solution. And frankly I might have opened pandoras box on this and I would be surprised if other people started to do the same thing.

**Comment by 81Denton** [comment] 2019-07-03 08:27
Cremating yourself to prevent cult from winning is honestly Robustin-tier metagaming.

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-07-03 21:05
> The fact that an incidental destruction of a body can have no metagame reasons but still abort the entire round is a bad problem to leave unfixed.

It hasn't been an issue for years and even with a rune that literally deletes people who can see it. It's only an issue now because someone did it advantageously and it wasn't fixed by an admin.

We have other antags who lose due to similar situations as well, is it okay because they don't share an objective? I don't understand where you are trying to draw the line, as losing the offer target doesn't stop cult abilities from working in the same way not finding your traitor item doesn't mean you can't do anything for the rest of the round.

If anything, the issue is that there's too many ways to easily make a situation irrecoverable even though the person(s) involved could be crucial to the game. IMO it should be difficult to ACTUALLY delete things to a point of no return.

**Comment by necromanceranne** [comment] 2019-07-03 21:22
I actually am not following here Cobby are you trying to say you don't want it to be fixed because it's too hard or because any fix is inadequate? Is it really so bad to have a failsafe for an objective that requires specific steps to be completed in a round defining game mode? This isn't just redtexting as a traitor because that affects exactly one person and the whole round continues as normal. Cult is not accommodating to a round continuing as normal, so it should have these failsafes in place to prevent incidental loss/metagaming.

Fuck man, we did it with the nuke disk as well. Why did we add the ability to prevent the nuke disk from being destroyed/moved off z-level if not to prevent the crew from preventing nukie victory?

**Comment by ATH1909** [comment] 2019-07-04 19:13
> Fuck man, we did it with the nuke disk as well. Why did we add the ability to prevent the nuke disk from being destroyed/moved off z-level if not to prevent the crew from preventing nukie victory?

Because nuke ops can declare war, giving the crew plenty of time to just cremate the disk.

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-07-05 14:18
You brought up the nuke disk but what about the nuke itself? It can still be spaced (albeit it's been made much more difficult recently). nukies also don't get a spell where they can ghost at will and find where the nuke is.

I think the nuke disk is only station loving because you ALWAYS know that's what the ops are going for.  You can bet your rear if it didn't exist everyone and their mother would space it as soon as red suits were spotted. The only way you would know if you're the target is if the cult tells you.

IMO the solution is entirely within the admin realm. Either the problem is the cultist who has more/less betrayed the team by openly outting the objective, the person who deleted themselves for no reason but to btfo cult, or it's just considered emergent gameplay and we move on.

If you want to address the issue that's fine, but I want to make sure the "failsafe" can't be a way for cult to make it easier on themselves. I still think the issue isn't cult-explicit, it's the fact that there's too many ways to perma remove stuff easily.

**Comment by necromanceranne** [comment] 2019-07-06 04:53
Well for the nuke itself, we have: 

.1 The shuttle, which minces anyone who gets too close.
.2 This same shuttle is very, very blastproof so it's hard to just nuke the shuttle even if you could.
.3 The fact that the doors all require syndicate ID's to open.
.4 It's locked down up until the disk is inserted so it cannot be moved until it is unlocked. Nobody but the nukies are probably going to be able to do that.

So with all those considerations it's likely you're not spacing the nuke unless the nukies themselves fumbles it. These are all pretty decent failsafes actually. And doesn't remove the completely viable tactic of spacing the nuke but does stop any attempts before the disk is inserted from attempting to space that same nuke. A few steps need to happen before such a fumble can occur.

Also Cobby, nukies get a pinpointer to the nuke disk. That's...that's the same thing as the cult spell. It just gives every cultist a pinpointer.

Also Cobby what do you even mean by there being too many ways to perma remove stuff...that's not at all an issue. That's not even close to being the real issue at hand, that's such a ridiculous misdirection I'm beginning to wonder why you're pushing into our hands instead of handling it code side. Aborted rounds are not emergent gameplay, it's just a dead round up until someone with the keys goes and fixes it, which should be automatic anyway. Because it's entirely possible to just not have anyone come and fix the problem on the off chance no admins are around. That's really all I'm arguing for here. Just some kind of automated solution to this situational but round ruining problem. Any problems with potential metagaming we can handle ourselves as administrators but if we had a simple code solution it'd probably fix itself.

Also if we want to keep going on failsafes:
1. Revheads/Heads that hide in lockers+go off z-level count as dead for rev victory/crew victory. The locker bit explicitly because hiding in a locker would make it near impossible for one side to win.
2. Blob can't be BoH bombed explicitly because it'd force the core off z-level.

If we didn't have these in place would you still call this shit emergent gameplay?

**Comment by Detective-Google** [comment] 2019-07-07 09:20
I'd say this also further emboldens culties to just indiscriminately murderbone instead of converting people

also if this is a real issue then we also have to stop HVT items from being destroyed, ninja protect targets from being destroyed, etc etc

honestly there is a failsafe for these things it's called the _emergency shuttle_ and gamemodes like blob and rev have more failsafes against these is because the shuttle _can not leave_ with them active.

With ops it's because the nuke disk is 
 A:) Not useful at all
B:) Literally everyone knows it is the target and that the enemy knows exactly where it is at all times

with the 'spacing the nuke' arguement there's also a stationside nuke, which can't (normally) be destroyed

cult sac target is well enough hidden that it shouldn't normally be revealed, I'd say this situation 100% falls under emergent gameplay.

**if a tot's target item gets cremated they're fucked, why would cult be any different.**

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-07-08 12:36
@necromanceranne the nuke was only recently changed to have those and I think most of the changes were to stop the syndicate finding shuttle rule (although yes I will agree it's been made difficult as I said earlier, but not impossible).

> nukies get a pinpointer to the nuke disk. That's...that's the same thing as the cult spell. It just gives every cultist a pinpointer.

correct. That's... why I said the nuke and not nuke disk?

> Also Cobby what do you even mean by there being too many ways to perma remove stuff...that's not at all an issue. That's not even close to being the real issue at hand, that's such a ridiculous misdirection I'm beginning to wonder why you're pushing into our hands instead of handling it code side. 

Yes, I fully agree. The issue WE (code-end) have is that there's too many ways to perma remove. I can't have you (admins) fix that. Sorry for not being clear.

It IS your (admins) issue if people misuse features for the sole purpose of btfoing antags OR by outting your objective so that the player can delete themselves, denying your team victory. I'm not sure how that doesn't fall under the harming the team rule to begin with if you're not going to consider that emergent gameplay.

If players are legally able to either delete themselves for the sole purpose of denying a team victory and/or reveal to the target that they need them to win and that's not going to be handled administratively, we can't fix that here without scrapping the player objective entirely. If that's what you want to do then fine, although I'd consider that a feature.

>Revheads/Heads that hide in lockers+go off z-level count as dead for rev victory/crew victory. The locker bit explicitly because hiding in a locker would make it near impossible for one side to win.
Blob can't be BoH bombed explicitly because it'd force the core off z-level.

Yes and those actions are for the sole purpose of BTFOing antags in those contexts. If you can differentiate between an accidental destruction of a body/item vs. antag btfoing be my guest. I'm not arguing we CAN'T have failsafes, I'm just saying it's a nonissue (or perhaps it's a bandaid to the actual issue of having a bunch of convenient ways to fully deny an item/player crucial to the round).

@Detective-Google in defense of "spacing the nuke" argument, the vault nuke and the shuttle nuke do not get the same code. In fact, the ONLY way they can get the same code is if the game is nuke (nukies nuke) AND there's a lone op (station nuke) AND RNG is really good. And badminnery ofc.

**Closed** 2021-12-02 01:07 UTC
Labels: In Game Exploit, Bug
