### ISSUE TITLE
Cannot drag things across Z-levels

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#37947] opened 2018-05-20 08:19 UTC
[Round ID]: # 88211

[Testmerges]: # None relevant

[Reproduction]: # Play as a being that can freely move through space, I was a shade, and try to drag an item across any z-level. The item gets stuck one tile over and is visible, yet it cannot be dragged.

**Comment by SpaceManiac** [comment] 2018-05-20 08:57
Duplicate of #37372

**Closed by SpaceManiac** 2018-05-20 08:57 UTC
