### ISSUE TITLE
Abductors cannot retrieve marked targets

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56098] opened 2021-01-10 23:15 UTC
RoundID 153973 

traded for solo abductor
had double starting items (sci tool, pistol, silencer) which may or may not be unrelated
was beaming down and marking people with the sci tool
went back up couldn't retrieve them, and they were definitely marked because i tried marking someone i already marked and i got the this person is already marked for retrieval message
literally unplayable moment

**Comment by Manybones** [comment] 2021-01-11 14:52
I tested it and retrieving works with with the starting abductor tools. I think its related to the double starting items, but I can't seem to replicate that bug. When I try to turn someone into abductor It only spawns a set

**Comment by trexter555** [comment] 2021-01-12 06:10
roundid 154066 same shit happened, traded for abductor with togopal and got 2 sets of tools, even a 3rd gun

**Comment by Manybones** [comment] 2021-01-12 16:22
Im testing it in local so maybe It's a server issue and thats why I can't replicate it. It's pretty weird

**Comment by timothymtorres** [comment] 2021-12-30 12:05
Duplicate of #52785

**Closed by timothymtorres** 2021-12-30 12:05 UTC
Labels: Bug, Tested/Reproduced
