### ISSUE TITLE
skizo light ring

### ISSUE THREAD

**Issue by theta060** [tgstation/tgstation#66097] opened 2022-04-09 21:26 UTC
Reporting client version: 514.1578

## Round ID:
[181334](https://scrubby.melonmesa.com/round/181334)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:

be in the dark random light that only i can see (that i know of) is off center and around me 
![image](https://user-images.githubusercontent.com/103159114/162591764-9eceb5b6-6edc-4f24-83bc-ee6245152ef0.png)

**Comment by moocowswag** [comment] 2022-04-10 07:45
This happened to me when i was playing with the colors option of a circuit remote and then i dropped it and still faintly had the color around me, I`m wondering if its off centered because you were using a directional light like a pda or flashlight and then when it was turned off the game never registered it for you? idk.

**Comment by ATH1909** [comment] 2022-04-10 08:17
this seems to be the return of a bug from a few months ago, I remember it happening to me when I was trying to dye all of the station's lights red as a mime

**Comment by timothymtorres** [comment] 2022-04-10 09:57
This might be related to whatever is causing #66100

**Comment by Mooshimi** [comment] 2022-10-25 16:41
Duplicate of #64256

**Closed** 2022-10-25 16:41 UTC
Labels: Bug
