### ISSUE TITLE
Mining Satchel of Holding only holds 100 ores

### ISSUE THREAD

**Issue by ElfLeaderMike** [tgstation/tgstation#24279] opened 2017-02-19 07:26 UTC
Server revision compiled on: 2017-02-18
The following pull requests are currently test merged:
#23087: 'Rebases to /vg/station13 code.' by PJB3005 

Based off master commit:
8e13d31f36af078f3b4bfaf27d2ea42aa92aad9e 

Cannot pick up more than 100 ores with the mining satchel of holding. 
Unless I missed a change I don't believe this is intended.

**Comment by PKPenguin321** [comment] 2017-02-19 08:08
Intended, actually. Currently being tweaked further, but intended nonetheless.

**Comment by ElfLeaderMike** [comment] 2017-02-19 08:38
Oh god how horrible, at least science has one less thing to bother making for miners now, its essentially useless now rip

**Comment by PKPenguin321** [comment] 2017-02-19 08:45
Unfortunately the infinite storage could crash the server.

**Comment by Sligneris** [comment] 2017-02-19 11:09
Maybe cap it at a numbers that makes it still useful to miners, like 500?

**Comment by WJohn** [comment] 2017-02-19 17:27
Resolved with #24228, if/when that gets merged.

**Comment by lzimann** [comment] 2017-02-20 01:19
Not a bug/issue.

**Closed by lzimann** 2017-02-20 01:19 UTC
