### ISSUE TITLE
Pizzas were not edible after slicing

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63615] opened 2021-12-25 10:06 UTC
Reporting client version: 514.1571

## Round ID:
[175396](https://scrubby.melonmesa.com/round/175396)

## Testmerges:
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [Untested: Fix outfit equipping not working](https://www.github.com/tgstation/tgstation/pull/63606)

## Reproduction:

1. Order pizza crate
2. Slice pizzas with a knife from the cargo autolathe
3. Eat two of the sliced pizzas just fine
4. Find that neither the sassysage or dank pizza slices are edible

**Comment by Sealed101** [comment] 2021-12-27 09:25
seems to be a common occurrence with food items you can process into slices: sausage into salami, pizza or bread into slices etc. two items get the normal behaviour, and others aren't edible. sometimes only one item gets the full amount of bites, and the second one gets a reduced amount. something to do with allocating bite sizes?

**Comment by timothymtorres** [comment] 2021-12-30 01:46
Duplicate of #55375

**Closed by timothymtorres** 2021-12-30 01:46 UTC
Labels: Bug
