### ISSUE TITLE
Exhaling a large cloud of smoke from your cigarette doesnt actually do that.

### ISSUE THREAD

**Issue by Sonnzer** [tgstation/tgstation#88161] opened 2024-11-23 23:28 UTC
### Client Version:

515.1646

### Issue Summary:

Taking a lit cigar(ette) out your mouth doesnt make a smoke particle effect, like it should.

### Round ID:

[243241](https://scrubby.melonmesa.com/round/243241)

### Test Merge Information:

- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

1. Smoke
2. Grab cigarette/cigar out of mouth to exhale smoke
3. It doesnt exhale smoke
4. My face when I can't look cool taking a big drag of smoke like a sigma from ohio drinking still water (Those who know. Skull emoji.)

**Comment by Sadboysuss** [comment] 2024-11-23 23:34
dupe of https://github.com/tgstation/tgstation/issues/87804

**Closed by Sadboysuss** 2024-11-23 23:34 UTC
