### ISSUE TITLE
Hacked vending machines can throw stuff at hidden revenants, giving them away

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39838] opened 2018-08-21 15:18 UTC
![image](https://user-images.githubusercontent.com/38788538/44411107-7738d900-a56e-11e8-92d6-f811e6785308.png)
No, i wasn't using any abilities.

**Comment by ShizCalev** [comment] 2018-08-22 02:12
probably also does it for jaunting wizards/constructs then

**Comment by SgtxRootbeer** [comment] 2018-08-22 03:55
Not a bug, since most machines can 'see' revanents, such as prox sensors, motion detectors, ai turrets, etc.

**Comment by Kagus** [comment] 2018-08-22 13:14
This also applies to other things people throw or shoot randomly. I wasn't aware that the living actually received the messages.

**Comment by zxaber** [comment] 2018-08-22 19:34
Hidden revs don't get shot at by turrets though, right? I swear I've sent spooky messages to an AI without triggering the turrets before.

**Comment by Iatots** [comment] 2018-08-23 09:25
If it's not a bug it must be an oversight, right? This can't be a deliberate feature.

**Comment by YakumoChen** [comment] 2018-10-13 01:58
seems like it should be a feature, it encourages spooky things

**Comment by PKPenguin321** [comment] 2018-10-13 08:40
yeah just close this and leave it in

**Comment by SpaceManiac** [comment] 2019-01-09 21:44
canonizing that vending machines can detect ghosts

**Closed by SpaceManiac** 2019-01-09 21:44 UTC
Labels: Not a bug
