### ISSUE TITLE
Paradox bag storage overlay can become extremelly annoying.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#37334] opened 2018-04-21 19:45 UTC
Round ID: 86830

Click and drag a bag on the ground to your character, the overlay pops up on the center and has no way to remove it. Extremelly annoying, essentially blocking those tiles.

![overlay](https://user-images.githubusercontent.com/4581352/39088127-920fa152-45a4-11e8-9a31-5e4c84be5993.png)

**Comment by SpaceManiac** [comment] 2018-05-09 21:02
Duplicate of #35285

**Closed by SpaceManiac** 2018-05-09 21:02 UTC
Labels: Bug, UI
