### ISSUE TITLE
Slot machines only take coins.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#41652] opened 2018-11-24 04:30 UTC
title, doesn't take holochips and space cash, only coins.

**Comment by nicbn** [comment] 2018-11-24 22:49
Working as intended
As IRL, retro machines won't accept credit cards and *almost* no machine at all will accept bills

**Comment by Time-Green** [comment] 2018-11-25 16:03
we need to be able to gamble all our money away

**Comment by Potato-Masher** [comment] 2018-11-26 06:43
This is why we need **SPACE** ATMs and not holochips.

**Comment by kriskog** [comment] 2019-06-28 00:48
fixed in #42774

**Closed by kriskog** 2019-06-28 00:48 UTC
