### ISSUE TITLE
ghosts cannot open boxes/bags/etc

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#68330] opened 2022-07-10 20:49 UTC
## Round ID:
[186423](https://scrubby.melonmesa.com/round/186423)

## Reproduction:
go find some storage (bags, boxes, jackboots, you name it), click it, get the "can't reach!" alert
likely its the storage component refactor that is causing this

**Comment by Shadowflame909** [comment] 2022-07-11 01:42
Yeah just noticed this too.

**Comment by magatsuchi** [comment] 2022-07-11 03:21
duplicate of #68290

**Closed by magatsuchi** 2022-07-11 03:21 UTC
