### ISSUE TITLE
Gorillas have long attack delay

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79092] opened 2023-10-18 23:23 UTC
## Reproduction:

Player controlled tot' gorilla has 4~ seconds attack delay on mobs. Normal attack delay on objects.

**Comment by Jacquerel** [comment] 2023-10-19 01:33
Can't reproduce, gorillas spawned locally have the normal mob attack period of 2 seconds.

**Comment by SyncIt21** [comment] 2023-10-19 04:17
Could have been time dilation on the server

**Comment by antropod** [comment] 2023-10-19 14:25
I do confirm that attacking a mob feels weird and has a delay between hits.

How to reproduce:
spawn as geneticics
give yourself a traitor
go to role restricted, buy serrum
transform into gorilla
---
attack a window
attack a monkey
compare attack speeds
attacking a monkey has a delay of like 3 seconds between attacks, also it is impossible to land a hit if monkey is moving

**Comment by Dorsisdwarf** [comment] 2023-10-31 14:59
Fixed by #79238

**Closed by Dorsisdwarf** 2023-10-31 14:59 UTC
