### ISSUE TITLE
Damage isn't transferred properly when transforming into simplemobs

### ISSUE THREAD

**Issue by Kingtrin** [tgstation/tgstation#43015] opened 2019-03-05 00:14 UTC
## Reproduction: As an ashligger I found prides mirror and decided to go vampire. After getting dumped into space I quickly hit my bat transformation and immediately died. I tested the vampire transform on a local server and sat in space as a vampire before transforming. The bat is transformed already damaged but doesn't immediately die. To test this further I let my character get damaged and recorded the health values.

24 brute 5 burn - transform to bat - 12.4 brute - transform to human - 9.8 brute - transform to bat - 4.9 brute - transform to human - full health

The threshold for instant death seems to be 36 damage. Upon transforming into a bat the damage transfered is enough to instantly kill you.

[2019-03-04 21:50:05.722] SAY: 21:50:05.722] SAY: kingtrin/(Numeen-Deeja) "Squeak!" FORCED by spell (Space (191, 182, 9))
[2019-03-04 21:50:05.724] GAME: 21:50:05.724] GAME: *no key*/(Numeen-Deeja) *no key*/(Numeen-Deeja) is no longer owning mob Numeen-Deeja(/mob/living/carbon/human) (Space (191, 182, 9))
[2019-03-04 21:50:05.724] ACCESS: 21:50:05.724] ACCESS: Mob Login: kingtrin/(Space Bat) was assigned to a /mob/living/simple_animal/hostile/retaliate/bat
[2019-03-04 21:50:05.726] GAME: 21:50:05.726] GAME: kingtrin/(Space Bat) Client kingtrin/(Space Bat) has taken ownership of mob Space Bat(/mob/living/simple_animal/hostile/retaliate/bat) (Space (191, 182, 9))
[2019-03-04 21:50:05.727] EMOTE: 21:50:05.727] EMOTE: kingtrin/(Space Bat) stops moving... (Space (191, 182, 9))

I asked an admin at the time I died and they told me that space bats are no longer space proof. What a dum dum!

To solve this I suggest not having damage transfer at all through mob transforms. Decreasing the amount transfered just kicks the can further down the road, and the simple mobs have such a wide variety of health pools that I don't see how you could scale damage without it causing issues like this.

**Comment by ATH1909** [comment] 2019-03-05 00:33
Yeah, shapeshifting is borked. Do note that I'd prefer having the damage transfered be relative to the max health stats of your normal/previous and transformed form (which is NOT how it works now) over them having separate health pools. Sure, rounding (especially if you make the damage always round down, which I think we should do) will allow you to heal a little bit, but I don't see that as being much of a problem (we might want to put a lower limit of one health point above crit (or death for simplemobs) for your health total in your new form so that you'll never instantly die upon transforming into a new form, just in case).

As far as I can tell, there is code to specifically make that health range of "below the crit threshold but above the death threshold" part of your max health total as a carbon and cut the damage transfered to whatever form you transform into in half (and then double it again upon shapeshifting back) upon entering it to account for that. Just cut that stuff out if you add that safety mechanism that I mentioned above.

**Comment by Cyprex** [comment] 2019-03-06 14:05
A better issue title seems "Damage isn't transferred properly when transforming into simplemobs"

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-03-07 19:05
this is most certainly a dupe of an issue

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-03-07 19:06
#43015

**Closed** 2019-03-07 19:06 UTC

**Comment by Cyprex** [comment] 2019-03-07 20:04
You linked...this issue?

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-03-07 20:37
lol'd

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-03-07 20:37
#42362
