### ISSUE TITLE
You cant relock the vault safe

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32323] opened 2017-11-01 20:37 UTC
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by jughu** [comment] 2017-11-01 20:38
I need steps beesting to reproduce!!

**Comment by BeeSting12** [comment] 2017-11-01 20:41
open the vault safe and then try closing it and you cant relock it so it wont open again

**Comment by AnturK** [comment] 2017-11-01 20:47
This is intended, specifically because of what you were trying to do.

**Comment by swindly** [comment] 2017-11-01 22:45
You need to move the tumblers after closing the safe to lock it.

**Comment by BeeSting12** [comment] 2017-11-02 00:06
we tried that

**Comment by swindly** [comment] 2017-11-02 01:49
unable to reproduce

![pic1](https://user-images.githubusercontent.com/22402048/32305864-492c57dc-bf4e-11e7-80e0-6f5486d1885f.jpg)
![pic2](https://user-images.githubusercontent.com/22402048/32305865-494561fa-bf4e-11e7-83df-ac33181af95e.jpg)
![pic3](https://user-images.githubusercontent.com/22402048/32305866-495be61e-bf4e-11e7-82f8-e2361e20a375.jpg)
![pic4](https://user-images.githubusercontent.com/22402048/32305867-49713b9a-bf4e-11e7-8904-7790d9727c86.jpg)

**Comment by ShizCalev** [comment] 2017-11-02 07:08
Unable to repo.

**Closed by ShizCalev** 2017-11-02 07:08 UTC
