### ISSUE TITLE
imitation carp meat cant be used for sushi (and probably nothing else)

### ISSUE THREAD

**Issue by gorillion** [tgstation/tgstation#85710] opened 2024-08-09 02:42 UTC
the template didnt load so im doing this manually. 

**Issue Summary**
painstakingly made koibeans on a dirt plot, injected 5u carpotoxin into tofu to make imitation carp meat, was unable to make any sushi besides vegetarian sushi (doesnt require fish, had other ingredients). carp meat works for sushi regularly.

**Round ID:**
234159

**Testmerges:**
wallening, idk

**Comment by deathrobotpunch** [comment] 2024-08-09 02:49
@Ghommie

**Comment by Ghommie** [comment] 2024-08-09 07:04
I doubt this has anything to do with me, but I will take a look into it and fix the issue once I'm home.

**Comment by Dawnseer** [comment] 2024-08-09 18:51
This hurts me deeply.

**Comment by SmArtKar** [comment] 2024-08-10 23:06
Cannot reproduce, imitation meat seems to work just fine

**Comment by Sadboysuss** [comment] 2024-08-11 09:00
please reproduce the issue by either making a video or adding new reproduction steps, this will be auto-closed in 7 days otherwise.

**Comment by gorillion** [comment] 2024-08-12 22:36
ok i tested this with the help of jane sierpinski in the thunderdome and it seems to work now. i..... don't know what changed. but it sure didn't work when i reported it. guess it's fine!

**Closed** 2024-08-13 11:53 UTC
Labels: Bug, Needs Reproducing, Cleanup Flagged
