### ISSUE TITLE
Disabler/Laser beam thingies stick around for waaaaaaaaaay too long

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#22372] opened 2016-12-21 02:02 UTC
![](http://i.imgur.com/dktc7Mk.png)

**Comment by ChangelingRain** [comment] 2016-12-21 02:06
this is heavily affected by lag because some smart guy decided to move `spawn(time) qdel(thing)` to addtimer, which runs off a subsystem that can slow the fuck down

**Comment by Cyberboss** [comment] 2016-12-21 02:55
Just lag, not a bug, close this

**Comment by lzimann** [comment] 2016-12-21 12:38
Like it was said it's just lag(you probably noticed everything being slow aswell).

**Comment by dannno** [comment] 2016-12-23 17:26
No. I didn't.
The game was moving at regular speed. It's only these that stuck around.

**Comment by ChangelingRain** [comment] 2016-12-23 20:58
The timer subsystem has to handle the deletion timers for these, which is, uh, super not ideal if we want to rely on the timer system for ABSOLUTELY ANYTHING other than these.

**Closed** 2017-01-04 23:20 UTC
Labels: Maintainability/Hinders improvements, Not a bug, Performance
