### ISSUE TITLE
Panic Bunker Interviews Don't Show Responses

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#80390] opened 2023-12-16 12:46 UTC
Reporting client version: 515.1620

## Issue Summary
Basically from what I can tell in this round, interview responses were not sent to us and were just labelled as "No Response"

## Round ID:
[220599](https://scrubby.melonmesa.com/round/220599)

## Reproduction:
1) Be a new player and write a beautifully written work of art trying to get into your new favorite server, Manuel.
2) Cry because it didn't get sent and admins ask if you sent anything.

**Comment by Isratosh** [comment] 2023-12-16 17:22
Dupe of https://github.com/tgstation/tgstation/issues/80378

**Closed** 2023-12-16 18:41 UTC
