### ISSUE TITLE
APCs cannot be constructed or deconstructed properly.

### ISSUE THREAD

**Issue by Constellado** [tgstation/tgstation#85713] opened 2024-08-09 12:16 UTC
## Issue Summary
When you try to screwdrive an apc as part of building and deconstructing it, it instead opens the wire panel. As a result, it ends up being very difficult to screw in or unscrew an APC board.

## Round ID:

[234219](https://statbus.space/rounds/234219) (my borg was having issues building an APC in maintenance)
I THINK as well [234199](https://statbus.space/rounds/234199), I was a curator and I discussed this issue together with an engi. I may have the round ID wrong though.

## Testmerges:
#85491 (wallening. I think this caused this issue but I am unsure on that.)
#85392

## Reproduction:

1. Place APC frame
2. Put board in
3. Add wires
4. Try to screwdrive to allow for putting in a cell...? But instead it opens a wire panel? But the APC is not complete...
5. Engineering woes...

**Comment by Inari-Whitebear** [comment] 2024-08-09 13:20
Duplicate of #85550 ? Kinda?

**Comment by LemonInTheDark** [comment] 2024-08-14 03:35
I think? arcane fixed this, leaving other issue up just in case

**Closed by LemonInTheDark** 2024-08-14 03:35 UTC
Labels: Test Merge Bug
