### ISSUE TITLE
RPD meter placement is broken

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34430] opened 2018-01-14 07:01 UTC
Revision: b413546bc0711faa0400af278236c9911c3d758c

Attempting to place a meter instead places an iconless "fitting" object which runtimes when drilled.

```
Runtime in construction.dm, line 172: Cannot create objects of type null.
proc name: attackby (/obj/item/pipe/attackby)
usr: Vanca Lacunae (spacemaniac) (/mob/living/carbon/human)
usr.loc: The floor (134,113,2) (/turf/open/floor/plasteel)
src: fitting (/obj/item/pipe)
src.loc: the floor (135,114,2) (/turf/open/floor/plasteel)
call stack:
fitting (/obj/item/pipe): attackby(the hand drill (/obj/item/wrench/power), Vanca Lacunae (/mob/living/carbon/human), "left=1")
the hand drill (/obj/item/wrench/power): melee attack chain(Vanca Lacunae (/mob/living/carbon/human), fitting (/obj/item/pipe), "left=1")
Vanca Lacunae (/mob/living/carbon/human): ClickOn( fitting (/obj/item/pipe), "left=1")
fitting (/obj/item/pipe): Click("floor", "statwindow.stat", "left=1")
```

**Comment by Marflowerose** [comment] 2018-01-14 07:40
Dupe of https://github.com/tgstation/tgstation/issues/32920

**Comment by ShizCalev** [comment] 2018-01-15 14:31
Duplicate of #32920

**Closed by ShizCalev** 2018-01-15 14:31 UTC
