### ISSUE TITLE
Smelting ores in lava is hard bugged

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#37057] opened 2018-04-08 17:07 UTC
Throw 50 pieces of any ore in lava, result is 50 pieces of material.
Then repeat previous step, result is 5 pieces of material. 
After that, throwing any material in lava has produce 0 pieces of material.

**Comment by ShizCalev** [comment] 2018-04-10 20:03
Duplicate of #37001

**Closed by ShizCalev** 2018-04-10 20:03 UTC
