### ISSUE TITLE
Free-Golems ore redemption machine is linked to the stations ore silo on Icebox

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#63375] opened 2021-12-12 19:30 UTC
## Round ID:
[174675](https://scrubby.melonmesa.com/round/174675)

## Testmerges:

#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63355: 'documents important MC vars and procs and adds tracking of tick usage when the mc first wakes up' by Kylerace at commit a3ac2561d5

## Reproduction:

1. Spawn as Free-Golem
2. Empty the stations ore Silo
3. Win?

**Comment by SuperNovaa41** [comment] 2021-12-12 19:35
Duplicate of https://github.com/tgstation/tgstation/issues/60944

**Closed by SuperNovaa41** 2021-12-12 19:35 UTC
