### ISSUE TITLE
Exiting and using a advanced camera console will temporarily remove the static from areas not covered by cameras

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#27447] opened 2017-05-20 03:06 UTC
Pretty sure this isn't really much of an issue, but since the camera starts out in the centcomm z level, you could possibly use it to figure out what antagonist is in the round (wizard, abductors, nook awps)

**Comment by lzimann** [comment] 2017-05-20 05:35
Dupe of #14626

**Closed by lzimann** 2017-05-20 05:35 UTC
