### ISSUE TITLE
nitrium doesn't grant sleep immunity

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#72106] opened 2022-12-20 02:16 UTC
Round ID: Tested on local

Testmerges: https://github.com/tgstation/tgstation/pull/66098

Reproduction: Go to sleep on Nitrium. Even if you have Nitryl Plasmide in your bloodstream which should prevent sleep, it doesn't. I think this is because it was refactored into breath code.

**Comment by CCC23** [comment] 2022-12-20 04:49
same things been happening a while you get half immunity where it keeps entering and leaving so it doesnt give the effect consistently but will give it some times

**Comment by private-tristan** [comment] 2022-12-20 04:58
#70456

**Comment by timothymtorres** [comment] 2022-12-20 16:41
Duplicate of #70456

**Closed by timothymtorres** 2022-12-20 16:41 UTC
