### ISSUE TITLE
Inspecting people dead from brain damage does not show them as dead

### ISSUE THREAD

**Issue by iwishforducks** [tgstation/tgstation#55779] opened 2020-12-28 02:55 UTC
## Round ID:

[Round ID]: [153042](https://scrubby.melonmesa.com/round/153042)

## Testmerges:

https://github.com/tgstation/tgstation/pull/55604

## Reproduction:

Have a brain tumor. Die because you didn't drink your mannitol. Anyone walking by your body in the halls and inspecting it does not show them as dead (aka no "is limp and unresponsive, with no signs of life.")

Health analyzers and medHUDs appear to work as expected. As a ghost I scanned and it showed that they were dead (as well as having 200 brain damage), and the medHUD showed a faltering heartbeat line.

**Comment by MrDoomBringer** [comment] 2020-12-28 07:48
my guess is this is a duplicate of #55744

**Closed** 2020-12-28 22:10 UTC
Labels: Bug
