### ISSUE TITLE
Bluespace body bags can delete you out of existence

### ISSUE THREAD

**Issue by whatisthisplace** [tgstation/tgstation#68709] opened 2022-07-24 07:05 UTC
## Round ID:
N/A: Local server

## Reproduction:

1. put yourself in a bluespace body bag
2. right click body bag to fold it
3. get snapped out of existence

You can also delete other people, along with yourself, if you manage to zip the bag up and fold it

**Comment by timothymtorres** [comment] 2022-07-24 09:02
Duplicate of #64631

**Closed by timothymtorres** 2022-07-24 09:02 UTC
