### ISSUE TITLE
Rolling heretic even if in preferences its set to off

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#59087] opened 2021-05-13 14:25 UTC
## Round ID:
[162168](https://scrubby.melonmesa.com/round/162168)

## Testmerges:
#58983: 'Removes bad return from processables that broke cooking ðŸ€' by tralezab at commit 13ad40a59d

## Reproduction:
Set Heretic preference to off, wait for dynamic to roll it roundstart.
Probably no one that round had heretic set to on and it forced it on me randomly
On paper it should work with any roundstart antagonist as well

**Comment by Time-Green** [comment] 2021-05-13 17:57
This is not a bug? If there are no other candidates someone gets forced antag. Anyway I can't check the logs because I think that round crashed

**Comment by FlamingCheese** [comment] 2021-05-13 20:53
> 
> 
> This is not a bug? If there are no other candidates someone gets forced antag. Anyway I can't check the logs because I think that round crashed

I was told by an admin to report this on github, that is just what i did

**Comment by dragomagol** [comment] 2021-05-14 02:28
This is a bug

**Comment by dragomagol** [comment] 2021-05-14 03:17
Should be fixed by #59099

**Closed** 2021-05-15 00:18 UTC
Labels: Bug
