### ISSUE TITLE
Fully charged APCs are black

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49753] opened 2020-03-06 06:20 UTC

**Comment by Dennok** [comment] 2020-03-06 07:26
Yes, sometimes APC window disappears.

**Comment by PKPenguin321** [comment] 2020-03-08 18:45
I might have noticed this happening on rounds where the powernet was bugging

**Comment by SuperNovaa41** [comment] 2021-12-05 18:07
I don't think this is a thing anymore

**Comment by timothymtorres** [comment] 2021-12-17 13:02
Duplicate of #48259

**Closed by timothymtorres** 2021-12-17 13:02 UTC
Labels: Bug, Cleanup Flagged
