### ISSUE TITLE
Mechs pilots while in Strafe mode are unable to hold ALT to overide strafe mode (due to a default hotkey)

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#61390] opened 2021-09-11 07:22 UTC
## Reproduction:
**EDIT: Cause has something to do with the fact that the default hotkey for mech strafing, ALT, is also the default hotkey for locking your character in place. This might be the cause.**

Mechs are able to enter a strafe mode to move side to side without turning, with a hot key bound to ALT that while held down the mech freezes in place, but is able to adjust it's facing to orient itself.

At some point this was broke. Holding ALT and pressing a direction key has no effect. This severely gimps combat mechs even more than than they already are, as to replicate this without the hot key the pilot must manually toggle strafe mode off and back on quickly, which requires the player to reset their cursor to press the action button in the upper left.

**Comment by AlinaStarkova** [comment] 2021-09-11 07:41
this may be related to my interact() refactor, though im not sure why since when your in a mech your 100% in range to interact() and as such should be able to use the ALT hotkey. but ill look into it, maybe it wasnt from my refactor, maybe it was, but ill fix it if i can

**Comment by AlinaStarkova** [comment] 2021-09-11 07:46
Nevermind, it has nothing to do with my interac() refactor since the code doesnt even check for that so its entirely unrelated

```
	var/keyheld = FALSE
	if(strafe)
		for(var/mob/driver as anything in return_drivers())
			if(driver.client?.keys_held["Alt"])
				keyheld = TRUE
				break

	//if we're not facing the way we're going rotate us
	if(dir != direction && !strafe || forcerotate || keyheld)
		if(dir != direction && !(mecha_flags & QUIET_TURNS) && !step_silent)
			playsound(src,turnsound,40,TRUE)
		setDir(direction)
		return TRUE
```

the code looks...... fine... so im actually not sure why its broken, can you reproduce the issue?

**Comment by AlinaStarkova** [comment] 2021-09-11 07:53
@TiviPlus you did a mech refactor 6 months ago that explicitly messed with this code in #57629

particularly things like this, was this tested? I cant think of what else would have broken this function recently, and i dont know mech code much at all
![image](https://user-images.githubusercontent.com/40489693/132940793-52e83f5c-a785-4be6-a19c-1d788816d7ca.png)

**Comment by ArcaneDefence** [comment] 2021-09-11 17:41
https://github.com/tgstation/tgstation/issues/54727
Are you certain your bindings aren't default/conflicting?

**Comment by Sealed101** [comment] 2021-09-11 20:43
conflicting keys causes this
unbind your alt key while this is still an issue

**Comment by timothymtorres** [comment] 2021-09-21 08:37
Duplicate of #54727

**Closed by timothymtorres** 2021-09-21 08:37 UTC
