### ISSUE TITLE
ghost light stuck to player

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#64256] opened 2022-01-19 23:53 UTC
## Reproduction: (ghost light can be seen on me here) https://www.youtube.com/watch?v=0fYhtqOERNQ
 i have no clue, the pka flashlights are off, pda light is off, and it doesnt actually provide any light, it just looks like it does, as items in the dark are still hidden even if the "light" is on it. (items in the video can only be seen due to night vision)

**Comment by SomeDongus** [comment] 2022-01-26 16:11
This happened to me, can confirm you're not crazy.

**Comment by timothymtorres** [comment] 2022-01-31 19:07
Looks like this might be related to #63919

**Comment by Mooshimi** [comment] 2022-07-11 22:20
#186484
very reproducible with circuits via the light comp, three random for the color, and setting it to on or off manually or giving on and off buttons via comparison connected to the inputs (personal disco ball)

**Comment by Mooshimi** [comment] 2022-07-25 21:52
possibly related 
![image](https://user-images.githubusercontent.com/85910816/180880024-5a57bc6a-33e0-411f-9f22-9dd87f512bc3.png)

**Comment by Mooshimi** [comment] 2022-08-12 14:03
#66097

**Comment by Mooshimi** [comment] 2022-10-25 16:43
Fixed by #70578

**Closed by Mooshimi** 2022-10-25 16:43 UTC
Labels: Bug
