### ISSUE TITLE
Phylactery does not respawn you when playing as a wizard

### ISSUE THREAD

**Issue by DoggotheSpessman** [tgstation/tgstation#63065] opened 2021-11-25 18:44 UTC
## Round ID:
[173666](https://scrubby.melonmesa.com/round/173666)
## Reproduction:
Simply spawn in as a wizard, bind yourself to an item using bind soul, and kill yourself, for some reason on round 173666 it did not respawn the wizard after dying.

**Comment by TheBonded** [comment] 2021-11-25 19:21
duplicate of https://github.com/tgstation/tgstation/issues/62507

**Comment by Mothblocks** [comment] 2021-11-25 20:02
@TheBonded please dont leave duplicates up 😛

**Closed by Mothblocks** 2021-11-25 20:02 UTC
Labels: Bug

**Comment by TheBonded** [comment] 2021-11-25 20:05
> @TheBonded please dont leave duplicates up 😛

sorry, forgot I had the power to close prs
