### ISSUE TITLE
Gang turrets useable while stunned.

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#29461] opened 2017-07-23 20:12 UTC
They can also be operated on bare spare tiles.

(I ded, pls nerf)

**Comment by BeeSting12** [comment] 2017-07-24 01:27
dupe #29188 

These things need to be removed until they're fixed.

**Comment by AnturK** [comment] 2017-07-24 09:14
Duplicate of #29188

**Closed by AnturK** 2017-07-24 09:14 UTC
