### ISSUE TITLE
Wizard's can get the steal the plutonium core objective but are provided no tools to steal it

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35887] opened 2018-02-22 02:52 UTC
Issue reported from  Round ID: 84003 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

![image](https://user-images.githubusercontent.com/6778786/36517137-1f868ed0-174f-11e8-9105-54f9cbc33595.png)

Spawned in as wizard

**Comment by timothymtorres** [comment] 2021-12-24 11:53
Duplicate of #45296

**Closed by timothymtorres** 2021-12-24 11:53 UTC
Labels: Oversight
