### ISSUE TITLE
Camera repairs performed while in AI shell not updating when reentering core

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#41494] opened 2018-11-14 07:46 UTC
Gave it a little test on sybil, would have the robotocist repair the camera while I was in my core and I'd be able to get cameras working.

When done by myself in my engineering shell the view would still report as static when in my core as well as if I had robotocist repair the camera while in the hell.

**Comment by timothymtorres** [comment] 2021-12-30 14:44
Duplicate of #41747

**Closed by timothymtorres** 2021-12-30 14:44 UTC
Labels: Bug
