### ISSUE TITLE
HARS debrains fully

### ISSUE THREAD

**Issue by SapphoQueer** [tgstation/tgstation#76710] opened 2023-07-10 10:01 UTC
## Round ID: 
[209970](https://scrubby.melonmesa.com/round/209970)

## Testmerges:
https://github.com/tgstation/tgstation/pull/76381

## Reproduction:
Inject humonkey/self with HARS, instead of moving the brain to the chest cavity, it falls out of your body, causing an instant death. What is supposed to happen is move it to your chest. As a sidenote, a HARS'd brain seems to be unable to be moved to a new body. This would mean that hars, outside of MMI uses, would be a RR.

![image](https://github.com/tgstation/tgstation/assets/94389951/7fb2ef02-eada-4a06-8cc2-cb368b0a0e40)

**Comment by distributivgesetz** [comment] 2023-07-10 10:08
![image](https://github.com/tgstation/tgstation/assets/47710522/4cf7215a-5756-4250-b3ce-d0f62d73e05b)
caused by `remove_from_limb()` being skipped if the brain has an owner
code is in `code/modules/surgery/organs/_organ.dm:262`

**Comment by Time-Green** [comment] 2023-07-10 10:25
@ChungusGamer666 ?

**Comment by ChungusGamer666** [comment] 2023-07-10 15:15
I tried to make hars change the body zone without fucking shit up, but i guess it did not work?

**Comment by ChungusGamer666** [comment] 2023-07-10 15:18
@distributivgesetz thanks dude

**Comment by ChungusGamer666** [comment] 2023-07-10 15:32
this should be fixed, now i need to deal with head reattachment (pain)

**Comment by TheVekter** [comment] 2023-07-11 02:51
This is no longer relevant as the PR this feature was on has been closed.

**Closed by TheVekter** 2023-07-11 02:51 UTC
Labels: Test Merge Bug
