### ISSUE TITLE
dna scanner pops their content when used

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57099] opened 2021-02-21 18:50 UTC
156861

put chimp in machine
transform into humie
dna scanner board and parts poop out

**Comment by rdragan** [comment] 2021-02-23 10:48
Dupe of #56632 but I'm gonna keep this one since these are the actual repro steps.

**Comment by rdragan** [comment] 2021-02-23 15:55
For anyone else looking into this, it seems that the monkey AI is picking up the scanner's internal parts and randomly dropping them. I'm giving up for now.
![image](https://user-images.githubusercontent.com/43266738/108869833-4125b580-7600-11eb-94ad-68826633af4a.png)

**Comment by ArcaneDefence** [comment] 2021-03-11 19:08
Fixed by https://github.com/tgstation/tgstation/pull/57149

**Closed by ArcaneDefence** 2021-03-11 19:08 UTC
Labels: Bug, Tested/Reproduced
