### ISSUE TITLE
Unable to connect Stacking Machine to Stacking Machine Console

### ISSUE THREAD

**Issue by Sonnzer** [tgstation/tgstation#84833] opened 2024-07-09 18:02 UTC
## Issue Summary

 The stacking machine in the recycling room wont connect to the console.

## Round ID: 

 231867

## Testmerges:

 [#84184: 'Offset render relays for non-offsetting planes to match highest matching render plane' by 00-Steven at commit a55bf71bfb](https://www.github.com/tgstation/tgstation/pull/84184)
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84767: '[tm only] Temporary fix on heretic ui' by jlsnow301 at commit 3c78cac75f](https://www.github.com/tgstation/tgstation/pull/84767)

## Reproduction:

 First, go to the recycling room (crusher). The console will not be connected to the stacking machine.  Now, try connect it. Through Ahelping and asking for help, it seems that you need to use a multitool to connect it, which I have tried and can say it does not work. The console is unable to connect to the stacking machine.

**Comment by SmArtKar** [comment] 2024-07-09 18:10
Duplicate of #84794

**Closed by SmArtKar** 2024-07-09 18:10 UTC
