### ISSUE TITLE
pAI instrument synthesizer sometimes breaks randomly

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#48925] opened 2020-01-21 19:08 UTC
Spam opening or closing or sometimes just playing and fiddling with it a bunch sometimes prevents it from opening again, and sometimes if it does open again it no longer plays music.

Dont have roundID or anything

**Comment by ShizCalev** [comment] 2020-07-30 04:38
Duplicate of #50796

**Closed by ShizCalev** 2020-07-30 04:38 UTC
Labels: Needs Reproducing
