### ISSUE TITLE
SM engine doesn't seem to be heating up if there's no incoming airflow

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#42128] opened 2018-12-29 18:02 UTC
Issue reported from  Round ID: 99425 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/17237624/50540865-41e66c80-0b9a-11e9-8b56-953d6ba32768.png)
Supermatter Engine (169, 153, 2): 329.43 K (56.2802 C), 3091.54 kPa
Oxygen: 102.989 mol
Nitrogen: 35.4928 mol
Plasma: 34.2296 mol
Pluoxium: 177.848 mol
Carbon Dioxide: 2472.63 mol
Tritium: 0.0131508 mol
Water Vapor: 0.0529844 mol
![6ap15wf 1](https://user-images.githubusercontent.com/17237624/50540873-62aec200-0b9a-11e9-9eab-3d94f39a2809.png)

The engine seems to be COOLING DOWN with these parameters, even though there's 85%+ CO2 and thus very very very slowly delaminating.

**Comment by Cyprex** [comment] 2018-12-30 14:14
Are you sure there is no actual airflow occurring? Also take note that power is only 3658, POWER_PENALTY_THRESHOLD is 5000, although the pressure does sound high. It seems like there is a lot of gas in the chamber, and pluoxium makes for a decent heat absorber, also, converting co2 to pluoxium might cool down the chamber due to pluoxium having a higher heat capacity.

**Comment by kriskog** [comment] 2019-06-27 23:00
Note that there can be airflow despite gas meters showing as empty. There is a lower limit for meter detection. Seems unlikely to do much at that pressure though.

**Comment by timothymtorres** [comment] 2021-12-29 20:26
Marking this as not a bug since the gas mix wouldn’t necessarily cause heat I don’t think.  CO2 increases the power level to absurd levels and plux absorbs heat.

**Closed** 2022-01-12 09:05 UTC
Labels: Not a bug, Needs Reproducing
