### ISSUE TITLE
Ridiculous amount of gorillas spawned when cube dropped under the shower

### ISSUE THREAD

**Issue by Zorelnam** [tgstation/tgstation#44364] opened 2019-06-06 19:47 UTC
Issue reported from  Round ID: 110025 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

This bug takes place when you drop the gorilla cube under the shower and take out the gorilla cubes individually and drop them while under a shower which is turned on
I don't really understand why it happens, but feel free to ask for more details if you need them

**Comment by nemvar** [comment] 2019-06-06 22:30
I have been able to reproduce this with normal monkey cubes aswell. It seems to only happen with showers.

**Comment by nemvar** [comment] 2019-06-06 22:47
Alright, this is actually a high priority bug.

Basically, if you take a cube out of an inventory while under a shower and then proceed to press drop, the cube will be permanently invisible, yet it will still remain on the tile of the shower and continue to spawn new monkeys/gorillas forever.

**Comment by nemvar** [comment] 2019-06-08 13:33
![monky](https://user-images.githubusercontent.com/47324920/59147979-9ff96480-8a02-11e9-9abd-b6c5e075dcd0.PNG)
help please.

**Comment by YPOQ** [comment] 2019-06-08 23:08
The issue is with how items are removed from storage containers.
This is the line that's causing the problem:
https://github.com/tgstation/tgstation/blob/d39aa2169dc3ecc1f6e53af6042712c9ee291a4f/code/game/objects/items.dm#L291
It removes the item from storage and moves the item to the user's loc, which causes the item to call Crossed() on everything in the loc (the shower in this case). The shower then calls the monkey cube's Expand() which qdel()s the item (moving it to nullspace and making it invisible).

After that we return to the storage container code which puts the item in the user's hand if possible (moving it back out of nullspace). https://github.com/tgstation/tgstation/blob/d39aa2169dc3ecc1f6e53af6042712c9ee291a4f/code/game/objects/items.dm#L301-L302
At this point the user can drop the monkey cube and it will spawn a monkey every time the shower processes, (it will ignore any further calls to qdel() because it's already been marked as deleted).

**Closed** 2019-06-17 23:54 UTC
