### ISSUE TITLE
Radiation can stun you infinitely (even when its source is long since gone)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31746] opened 2017-10-15 04:21 UTC
>See singularity
>Your round is forfeit two minutes from now.

Constant weakening even when the singularity is on the other side of the Z-level is ridiculous. You get spammed by it every second or so, and you literally never get up.

**Comment by DaxDupont** [comment] 2017-10-15 13:08
see #31729

**Comment by ShizCalev** [comment] 2017-10-15 15:18
Duplicate of #31746

**Closed by ShizCalev** 2017-10-15 15:18 UTC

**Comment by AnonymousNow** [comment] 2017-10-15 22:38
>Duplicate of itself

What.

**Comment by ShizCalev** [comment] 2017-10-16 00:25
honk.

Meant #31729
