### ISSUE TITLE
Threw a monkey at a ninja while carrying it instead of hitting the ninja it hit me

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#72500] opened 2023-01-06 04:06 UTC
Reporting client version: 514.1589

## Round ID:
 [197698](https://scrubby.melonmesa.com/round/197698) 

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:
throw a moneky while running sometimes it happens it will hit you

**Comment by Jacquerel** [comment] 2023-01-06 13:06
Things you throw move in the direction you throw them, if it was behind you when you threw it then it will hit you.

**Comment by ArcaneDefence** [comment] 2023-01-06 17:29
Fireman carrying qol was a mistake

**Comment by Sealed101** [comment] 2023-02-27 21:01
basically a dupe of #59926

**Comment by SethLafuente** [comment] 2023-02-27 21:05
Oh that's true gonna close

**Closed** 2023-02-27 21:05 UTC
