### ISSUE TITLE
"Floor" sometimes gets in the way of items so you have to right click or alt-click to interact with them

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54424] opened 2020-10-16 05:10 UTC
## ROUND ID: 
148393 (Manuel) I've seen it a LOT more than often this round
## Reproduction:
I have no idea how it happens or why it happens. Mostly experiencing this in Robotics when printing objects out. Examining this "Floor" often points me in the wrong direction from where I had clicked.
![image](https://user-images.githubusercontent.com/62538745/96214509-3caa0b80-0f41-11eb-9dcf-040fe6a7d887.png)
Happens enough to see it at least every other round. Sometimes it just comes and goes.
![image](https://user-images.githubusercontent.com/62538745/96214730-be9a3480-0f41-11eb-9edb-b284aebbd1be.png)

**Comment by msgerbs** [comment] 2020-10-16 06:22
Duplicate of #54378

**Closed by msgerbs** 2020-10-16 06:22 UTC
