### ISSUE TITLE
eva suit storage radial menu wil keep existing  if not closed

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#53901] opened 2020-09-22 11:04 UTC
## Reproduction:

it should close if you move away

**Comment by nullAdept** [comment] 2020-09-22 15:33
can we just bring back the tgui menu please

**Comment by itseasytosee** [comment] 2020-09-22 15:39
You can also bring up the menu without being next to it.

**Comment by nightred** [comment] 2020-09-22 18:32
On testing I am not able to reproduce this issue,
The menu only open when next to the suit storage.
The menu closes (with a 2-5 second delay) once you step away, or try to interact with the menu.

Please provide further details in a situation where this happens.

**Comment by Jared-Fogle** [comment] 2020-09-22 19:58
> You can also bring up the menu without being next to it.

Were you a borg?

**Comment by itseasytosee** [comment] 2020-09-22 21:08
I was not a borg although I did move away from in via briefcase launchpad. (I was stealing CE boots) It continued to stay there after I was teleported and moved about after.

**Comment by Taylorkills2** [comment] 2020-09-23 00:12
I'll be honest it works just as Tlal described for me, but I don't really care since it's not a big deal.
Be a normal miner doing mining. Go down get whatever you need from container, don't close menu. Walk away, menu stays open.
Go back to station, open up camera console, interact with menu through camera.
I haven't tested it thoroughly so I don't know if you can take items out of it through cams.

**Comment by Jared-Fogle** [comment] 2020-09-23 00:51
>  Walk away, menu stays open.

This is fixed with #53907.

**Comment by Taylorkills2** [comment] 2020-09-23 01:11
That's good, you can take items out of the mright now. IF your quick you can kill someone through cams if they accidentally close eva on themself.

**Closed** 2020-09-24 10:12 UTC
Labels: Bug
