### ISSUE TITLE
Drones cannot weld airlocks shut.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26764] opened 2017-05-01 03:14 UTC
If you don't have an RCD, the main way to fix an emagged door is to decon it.
Deconning requires welding the door shut. Since drones are on help intent, and cannot switch off of it, they cannot deconstruct airlocks this way.

@Cyberboss

**Comment by RandomMarine** [comment] 2017-05-01 04:56
Dupe of #25292

**Closed** 2017-05-01 11:01 UTC
Labels: Bug
