### ISSUE TITLE
broken solar panels on a lower level are missing textures

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#80272] opened 2023-12-12 01:51 UTC
RoundID 220349

meteors happened and i noticed these
missing textures only on the upper layer, and show up like that as both living and as ghost

![image](https://github.com/tgstation/tgstation/assets/105343481/05f2fec0-951d-4788-b6d3-b4138f3dc779)
![image](https://github.com/tgstation/tgstation/assets/105343481/ca88e60a-76c3-4176-a45f-28069efbe88f)

**Comment by MrMelbert** [comment] 2024-04-10 17:12
Dupe of #82301 , preferring that one due to more information

**Closed by MrMelbert** 2024-04-10 17:12 UTC
