### ISSUE TITLE
"Ghost" metal when inserting metal into an exofab

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23640] opened 2017-02-02 19:46 UTC
1) Grab stack of metal, insert into exofab
2) You get an insertion message, but your character is still holding a stack of metal
3) You can throw this "ghost metal", and the throwing will generate a message, but nothing will happen
4) The metal is inside the exofab as it should be 

Server revision compiled on: 2017-02-01
Test merge active of PR #23493 
Test merge active of PR #23605 
Test merge active of PR #23616 
Test merge active of PR #23618 
Based off master commit 1021e93ead4f8ce1cdcc558edbdf6a745c765630

**Comment by Cyberboss** [comment] 2017-02-02 21:38
Dupe of #23557 @lzimann

**Closed** 2017-02-02 21:51 UTC
