### ISSUE TITLE
Circuit Bots Are Immune to Hierophant & Colossus Attacks

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#36010] opened 2018-02-27 07:07 UTC
Issue reported from  Round ID: 84269 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Saw a scientist kill the hierophant with nothing but a bot that threw hatchets. None of the hierophant's attacks did any damage to the bot. Same with the colossus.

**Comment by MMMiracles** [comment] 2018-02-27 07:17
I brought up the issue #32904 here with them being immune to generic attacks, got marked as not a bug. Probably an issue.

**Comment by Potato-Masher** [comment] 2018-02-27 17:24
Gee, I sure do love when items disguised as mobs spam axes and murder everything, up until the point they are picked up.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-02-28 16:03
After that "I can pick up living mobs" pr if it's not closed you could probably easily switch them to mobs.

Semi-related is #35795, Although that's pertaining to the megafauna itself rather than their projectiles.

**Comment by AlexTheSysop42** [comment] 2018-03-25 00:30
pretty sure this was fixed @ShizCalev

**Comment by AlexTheSysop42** [comment] 2018-03-25 00:31
same with #35795

**Comment by ChangelingRain** [comment] 2018-03-25 02:10
#35795 was fixed, but this was not.

**Comment by AlexTheSysop42** [comment] 2018-03-25 02:14
oh right

**Comment by SpaceManiac** [comment] 2018-12-28 18:57
Circuits have been removed.

**Closed by SpaceManiac** 2018-12-28 18:57 UTC
Labels: Bug, Consistency Issue, In Game Exploit
