### ISSUE TITLE
Chaplain's Festival Sect Portable Altar ability does not work.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#80942] opened 2024-01-13 06:42 UTC
## Issue Summary

The Festival Sect chaplain's ability to empower an instrument to let you choose rites to invoke away from your alter appears to be broken. When the holy book is used on it, it simply says 'cannot perform that rite' on every option.

## Reproduction:

-Select Chaplain, choose the Festival Sect
-gain enough favour to invoke the portable altar, use this ability on an instrument (I tested with a synthesiser)
-use the bible on the instrument to select a rite.
-note that you are unable to do so.

**Comment by necromanceranne** [comment] 2024-01-13 07:56
OOPS I'M SORRY ARM I WAS TRYING TO TAG YOU

**Comment by DATA-xPUNGED** [comment] 2024-06-26 12:47
Duplicate of #83997

**Closed by DATA-xPUNGED** 2024-06-26 12:47 UTC
Labels: Bug
