### ISSUE TITLE
Steelpoint's Marine sprites don't work

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#27817] opened 2017-05-28 21:21 UTC
Suit:
- Worn - Broken
- On Ground - Broken
Helmet:
- Worn - Broken
- On Ground - Broken

@Steelpoint

**Comment by Steelpoint** [comment] 2017-05-29 03:07
Are you sure? I tested on my local code and it works fine. I'll do some more checking.

**Comment by Steelpoint** [comment] 2017-05-29 03:16
Hmm, I updated the code and this is interesting. It seems most of the code was removed somehow? I can't find the file, most of the equipment is missing.

Did someone merge a PR that overrode my changes?

I'll have to dig in and fix these issues.

**Comment by Steelpoint** [comment] 2017-05-29 03:24
Ok I tested on the most up to date code and the sprites seem to be fully functional.

**Comment by Steelpoint** [comment] 2017-05-29 08:04
I see the issue in game, I can't find out why it's occurring.

The obj name for the armor is 'uegarmor', while the icon reference for the item is also called 'uegarmor'.

It works on my offline code but it does not work on the server.

**Comment by Steelpoint** [comment] 2017-05-29 08:09
OH I KNOW WHAT'S GOING ON.

We are currently test merging the Lava Dwarf PR, that PR uses a outdated sprite set which does not include the marine armour sprites.

**Comment by Iamgoofball** [comment] 2017-05-29 08:48
yup this is my bad

**Comment by PKPenguin321** [comment] 2017-05-30 17:33
Close this issue then, caused by test merge

**Closed** 2017-05-30 18:15 UTC
Labels: Sprites
