### ISSUE TITLE
Duplicate CE office on Cerestation

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#26423] opened 2017-04-21 02:31 UTC
Server revision compiled on: 2017-04-20
The following pull requests are currently test merged:
#26412: 'Revert "Ghosts call Moved() after Move() (#26183)"' by MrStonedOne 

Based off master commit:
f65fcabcbfa6f019cd412229ba6e3373d6ebc8b1 

On CereStation there is a duplicate CE office that spawns, fully stocked locker included. It appears below atmos 

![](https://puu.sh/vr5dN/a7af2f0f8b.jpg)

**Comment by Kromgar** [comment] 2017-04-21 04:04
This is being fixed right now

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-04-21 14:17
what is the lore of the space office....

**Comment by coiax** [comment] 2017-04-21 14:33
I opened an issue for this already, and citrus closed it...

**Comment by WJohn** [comment] 2017-04-21 23:15
Yeah this is a dupe. Can be closed.

**Closed by WJohn** 2017-04-21 23:15 UTC
Labels: Bug, Map Issue

**Comment by coiax** [comment] 2017-04-22 00:18
It's not a dupe of an OPEN issue, @WJohn, because Citrus hates map issues.
