### ISSUE TITLE
Freefloating Space Plasma; Can't Be SINGULO'D

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#38083] opened 2018-05-26 00:22 UTC
![scrnshot1](https://user-images.githubusercontent.com/6266927/40570469-24ac5b88-6083-11e8-92e4-7edeb0b1db57.png)

I pop into a round for a couple of minutes and I see an issue immediately.

**Comment by Ratvar** [comment] 2018-05-26 01:05
The real issues was the plasma in space, nah?

**Comment by Kromgar** [comment] 2018-05-26 04:06
Plasma interaction is super fucky atm

**Comment by SpaceManiac** [comment] 2018-05-26 06:18
Duplicate of #34861

**Closed by SpaceManiac** 2018-05-26 06:18 UTC
