### ISSUE TITLE
kicked to lobby then allowed to rejoin as a new person.

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#45238] opened 2019-07-17 16:41 UTC
Issue reported from  Round ID: 113369 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1467

died in lavaland as mine bot, was told i was being afk while not, was then kicked to lobby when i clicked the reconnect hyperlink. client did not crash. was then allowed to click the join game button as if i hadn't been in the round.

**Comment by Time-Green** [comment] 2019-07-17 19:49
This is caused by somehow your ckey not being bound to anything

**Comment by joybod** [comment] 2019-07-17 22:08
> This is caused by somehow your ckey not being bound to anything

no clue what that means but ok

**Comment by ShizCalev** [comment] 2019-07-18 06:39
Duplicate of #37674

**Comment by joybod** [comment] 2019-07-18 18:05
in my case instead of being alive when it happened, i was dead. #37674 was still "alive"

**Comment by MrStonedOne** [comment] 2019-07-19 20:38
What is your byond username and IC character name?

**Comment by joybod** [comment] 2019-07-19 20:52
joybod and manuel ackerley

**Comment by MrStonedOne** [comment] 2019-07-19 21:14
Did you report this the same round it happened?

Logs show you were kicked for being afk while you were still in the lobby.

The only mob you ever controlled until the end of that round was the lobby mob and a human mob that you finished the round in.


https://tgstation13.org/parsed-logs/basil/data/logs/2019/07/17/round-113369/game.txt
```
[2019-07-17 15:05:14.805] ACCESS: Login: Joybod from -censored(ip/cid)- || BYOND v512.1467
[2019-07-17 15:05:14.982] ACCESS: Mob Login: Joybod/(Joybod) was assigned to a /mob/dead/new_player
[2019-07-17 15:05:14.985] GAME: Joybod/(Joybod) Client Joybod/(Joybod) has taken ownership of mob Joybod(/mob/dead/new_player) (start area (8, 174, 1))
```

```
[2019-07-17 15:20:34.471] ACCESS: AFK: Joybod/(Joybod)
[2019-07-17 15:20:34.571] ACCESS: Logout: Joybod/(Joybod)
[2019-07-17 15:20:34.571] GAME: Joybod[DC]/(Joybod) Joybod[DC]/(Joybod) is no longer owning mob Joybod(/mob/dead/new_player) (start area (8, 174, 1))
```

```
[2019-07-17 16:00:15.890] ACCESS: Login: Joybod from -censored(ip/cid)- || BYOND v512.1467
[2019-07-17 16:00:16.044] ACCESS: Mob Login: Joybod/(Joybod) was assigned to a /mob/dead/new_player
[2019-07-17 16:00:16.047] GAME: Joybod/(Joybod) Client Joybod/(Joybod) has taken ownership of mob Joybod(/mob/dead/new_player) (start area (8, 174, 1))
```

```
[2019-07-17 16:01:33.399] GAME: *no key*/(Joybod) *no key*/(Joybod) is no longer owning mob Joybod(/mob/dead/new_player) (start area (8, 174, 1))
[2019-07-17 16:01:33.399] ACCESS: Mob Login: Joybod/(Manuel Ackerley) was assigned to a /mob/living/carbon/human
[2019-07-17 16:01:33.401] GAME: Joybod/(Manuel Ackerley) Client Joybod/(Manuel Ackerley) has taken ownership of mob (/mob/living/carbon/human) (start area (8, 174, 1))
```
```
[2019-07-17 16:38:56.537] GAME: Rebooting World. Round ended.
...
[2019-07-17 16:38:57.467] ACCESS: Logout: Joybod/(Manuel Ackerley)
[2019-07-17 16:38:57.468] GAME: Joybod[DC]/(Manuel Ackerley) Joybod[DC]/(Manuel Ackerley) is no longer owning mob Manuel Ackerley(/mob/living/carbon/human) (Starboard Maintenance (155, 114, 2))
```

>died in lavaland as mine bot, was told i was being afk while not

Time loss and confusion over the order of events can be a sign of co2 poisoning. Invest in a co2 detector today:tm:

**Comment by joybod** [comment] 2019-07-19 21:32
could i have been transferred between severs? cause i can't find the things i talked about to the miner that made the minebot sentient.

**Comment by kriskog** [comment] 2019-11-11 21:26
Closing in favor of #47720

**Closed by kriskog** 2019-11-11 21:26 UTC
Labels: Bug, Needs Reproducing
