### ISSUE TITLE
Space Pirates Don't Auto-Update Mob

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#63699] opened 2021-12-30 04:22 UTC
Reporting client version: 514.1572

## Round ID:
[175641](https://scrubby.melonmesa.com/round/175641)

## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)

## Reproduction:

Be Admin
Wait for space pirates to spawn
Space Pirates Spawn
They're listed as their old names in their old mobs, and you can't follow them from the Round Status panel (there's more than two space pirates, and those certainly aren't their names).

![image](https://user-images.githubusercontent.com/34697715/147720139-cbb633b3-365d-4585-85a6-1ad74b6630ec.png)

(This was also accompanied by some other issues in which they weren't given Antagonist status, but still had space pirate stuff. Very odd.)

**Comment by SuperNovaa41** [comment] 2021-12-30 04:25
Probably fixed by https://github.com/tgstation/tgstation/pull/63698

**Comment by dragomagol** [comment] 2021-12-30 05:38
and duplicate of #63662

**Closed by dragomagol** 2021-12-30 05:38 UTC
Labels: Bug
