### ISSUE TITLE
valentine objectives bug

### ISSUE THREAD

**Issue by LetterN** [tgstation/tgstation#35669] opened 2018-02-14 16:56 UTC
Bagil station, Round id: 83607
[Testmerges]:  #35660  #35609  #35535

So, apparently, this can happen

![thank coderbus](https://user-images.githubusercontent.com/24603524/36216869-f0a158c0-11ea-11e8-819b-c4b803e4df6f.PNG)

**Comment by davethwave** [comment] 2018-02-14 17:17
Not a bug I think...

**Comment by PKPenguin321** [comment] 2018-02-14 19:27
This is because being borged counts as dead for objectives, so you can borg your kill target and still have it count when you're a traitor

**Comment by YakumoChen** [comment] 2018-02-15 06:57
dupe of #35663

**Closed** 2018-02-17 06:47 UTC
Labels: Bug
