### ISSUE TITLE
Gulag Machine Doesnt Do It's Job

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#30461] opened 2017-09-06 02:03 UTC
Gulag machine will sometimes teleport the prisoner to the gulag but wont give the proper equipment it does when it normally processes. No prisoner suit, no ID. Has happend multiple times.

**Comment by DoctoreMad** [comment] 2017-09-06 02:11
Send it to gulag.

**Comment by YakumoChen** [comment] 2017-09-06 12:51
they're in an equipment room. Not a bug.

**Comment by Tacolizard** [comment] 2017-09-06 15:38
@Cyberboss close this

**Closed** 2017-09-06 16:05 UTC
