### ISSUE TITLE
Clown maze has a couple issues

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17856] opened 2016-05-22 17:42 UTC
The floors cause confusion now, making it somewhat difficult to slide about properly in the maze. Should use some snowflake non confusion lube or ice or something maybe

You can crowbar up the floors to cheat. Needs a turf you can't do this to.

@Cheridan

**Comment by MMMiracles** [comment] 2016-05-22 17:46
i honestly did not understand the difficulty of the ruin when originally looking at it when observing but now i understand what fresh hell it truly is as a miner.

absolutely awful

**Comment by anconfuzedrock** [comment] 2016-05-22 19:45
its literally impossible to win WITHOUT cheating
>be right at the end, right before the room with the carpet
>open the door
>tile under the door is lubed
>slip on lube
>land in the disposal that kicks you out
its funny but means you can only win by cheating

**Comment by MMMiracles** [comment] 2016-05-22 21:53
@anconfuzedrock I'm actually pretty certain that was intended, as you walk in expecting loot and all you get is an airhorn as you slip straight into the exit disposal.

cheridan is a cruel man

**Comment by optimumtact** [comment] 2016-05-22 23:08
actually honestly this was probably all intended because cheridan is actually just that evil, so @Cheridan let me know if I can close this.

**Comment by Dorsisdwarf** [comment] 2016-05-23 13:53
Crowbarring definitely isnt intended

**Comment by Cheridan** [comment] 2016-05-23 18:53
yeah the confusion and crowbarring aren't intended

**Closed** 2016-05-28 19:35 UTC
Labels: Bug, FUCK, Map Issue
