### ISSUE TITLE
Double Adminhelp verb shows up with Browser Status Panel

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#53264] opened 2020-08-28 04:46 UTC
## Reproduction:

Was playing today and an Adminhelp issue came up. When the adminhelp verb got returned to me after the issue was resolved, I then had two adminhelp verb prompts in the panel. This is most definitely an issue with the newest Browser Status Panel iteration.

Screenshot of the double-adminhelp phenomenon:
![image](https://user-images.githubusercontent.com/34697715/91522235-fb896980-e8b6-11ea-9897-496abea935b8.png)

Both of the verbs show the same box that you would expect from a normal adminhelp entry box, there are just now two of them.

**Comment by Couls** [comment] 2020-08-28 05:09
I can't reproduce this on local, are there any special conditions you're able to mention?

**Comment by san7890** [comment] 2020-08-28 16:31
The flow of the ahelp conversation went something like this:

-I send the initial ahelp ticket.
-The admin in question responds asking for more information.
-I send my response.
-However, a few seconds directly afterwards, I realize I forgot some information they wanted. I then type out and send another response with the additional information.
-A little while later, the admin responds saying that the issue has been dealt with, and the ticket is returned to me in no more than like 2 seconds as they give their final response.

If you need any more clarification, I'm happy to provide it.

**Comment by Couls** [comment] 2020-08-28 18:07
This is enough, I’ll just need to prevent duplicate verbs from showing up on the list

**Comment by Couls** [comment] 2020-08-30 02:53
This should be fixed, please mention me if anybody notices it happening again

**Closed by Couls** 2020-08-30 02:53 UTC
Labels: Bug
