### ISSUE TITLE
Advanced Camera Consoles can ignore static

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#27529] opened 2017-05-22 02:04 UTC
Step 1: Manoeuvre your camera eye into the static
Step 2: Logout of the console
Step 3: Quickly log back in
Step 4: No more static overlay

![image](https://cloud.githubusercontent.com/assets/12382984/26289877/37549594-3e9b-11e7-80d8-cbedd26027fa.png)

**Comment by Anonmare** [comment] 2017-05-22 02:04
I am viewing this via advanced console FYI

**Comment by ma44** [comment] 2017-05-22 13:10
Pretty sure this is a dupe of https://github.com/tgstation/tgstation/issues/27447 and https://github.com/tgstation/tgstation/issues/14626

**Closed** 2017-05-23 18:43 UTC
Labels: Bug, In Game Exploit
