### ISSUE TITLE
Making lizard wine does not reset the sprite whatever contains the ethanol

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31458] opened 2017-10-08 17:44 UTC
1. Make lizard wine with large beaker with ethanol, using the crafting menu.
2. Observe how beaker is empty when examined but the sprite shows it as full.

**Comment by PKPenguin321** [comment] 2017-10-26 23:50
Not sure I understand the bug report. "ethanol using menu"?

**Comment by DaxDupont** [comment] 2017-10-27 17:15
Engrish slightly fixed

**Comment by Cyberboss** [comment] 2018-03-21 21:49
Duplicate of #33619

**Closed by Cyberboss** 2018-03-21 21:49 UTC
Labels: Bug, Sprites
