### ISSUE TITLE
Odysseus Medihud stays after exiting

### ISSUE THREAD

**Issue by MarshyMansSock** [tgstation/tgstation#57904] opened 2021-03-23 00:37 UTC
Reporting client version: 513.1542

## Round ID:
[158754](https://scrubby.melonmesa.com/round/158754)

## Reproduction:
Make Odysseus
Don't wear medihud
Get in
Get out

**Comment by TheBonded** [comment] 2021-03-23 15:27
Nooo why did you have to report this?

**Comment by SuperNovaa41** [comment] 2021-12-19 22:39
Still can't reproduce. Closing.

**Closed by SuperNovaa41** 2021-12-19 22:39 UTC
Labels: In Game Exploit, Bug
