### ISSUE TITLE
Lobby menu sometimes doesnt respond to clicking char setup and join game buttons, but does to observing

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#63405] opened 2021-12-14 08:29 UTC
Round ID: [174766](https://scrubby.melonmesa.com/round/174766)
Server Time: 2021-12-14 08:19:30

Local commit: a50741c103b85e91126d446762c1a2375493ce7f
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

it just kinda happened to me on that round
pressing F12 to hide and show menu back did nothing 
observing and being kicked back into lobby didnt fix it either
(observing took like 20 clicks to trigger)
relogging helped but somehow clicking char setup made it think for like half a minute before it opened
after that it was back to normal

**Comment by timothymtorres** [comment] 2021-12-15 10:31
Duplicate of #48008

**Closed by timothymtorres** 2021-12-15 10:31 UTC
Labels: Needs Reproducing
