### ISSUE TITLE
Harvesters might as well just kill you instantly.

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/tgstation#38791] opened 2018-06-28 18:58 UTC
Disarming a limb, guaranteed, with each attack while moving faster than a person. Might as well just skip two seconds and have them instantly kill you. Who made that stupid change? They were fine when they were shitty minions that slowly brutalized you through sheer numbers, and much more fun to be on the receiving end of an attack by them. 

Yet another thing that didn't need to be changed, yet was, because... I don't know. Impulsiveness?

**Comment by Repukan** [comment] 2018-06-28 20:44
Not a bug

**Comment by Anonmare** [comment] 2018-06-28 20:57
If there are Harvesters, you're fucked either way.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-06-28 21:36
Your chance to fight back was before the cult summoned narnar.

**Comment by zaracka** [comment] 2018-06-29 00:50
The round should just end once Nar'sie is summoned tbh.

**Comment by DaxDupont** [comment] 2018-06-29 09:05
This is not a bug so it belongs on the forums

**Comment by SgtxRootbeer** [comment] 2018-06-29 18:44
This is intended

**Comment by Shadowflame909** [comment] 2018-07-04 09:57
Why do you keep opening up all of these complaints in issues that aren't bugs. Issues is for bugs kiddo. If you have an actual issue post it on the forums.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-07-05 16:11
> issues are for bugs

not always hence the tag vs just closing it.

**Comment by ChangelingRain** [comment] 2018-07-05 18:01
This is literally the intended gameplay you get your limbs ripped off and then dragged off to nar-sie

**Closed by ChangelingRain** 2018-07-05 18:01 UTC
Labels: Not a bug
