### ISSUE TITLE
Infinite Runtimes

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#51030] opened 2020-05-10 05:45 UTC
Issue reported from  Round ID: [136736](https://scrubby.melonmesa.com/round/136736) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Runtime spawns infinitely.
![Runtime Error Hhahaha](https://user-images.githubusercontent.com/33048583/81491769-0c05cd80-924f-11ea-934e-0cd3686fa9c4.PNG)

The game had to be force started by an admin, as secret autostart errored out. I don't know if the two are related, but I'm noting it here just in case.

**Comment by nemvar** [comment] 2020-05-10 22:31
If I should take a guess it's probably related to the make_babies() proc.
Can we describe what kind of cats runtime spawned? Were they adults or babies? How fast was she spawning new cats? Were the new cats also named Runtime?

**Comment by ShizCalev** [comment] 2020-08-02 02:18
:)

**Comment by ShizCalev** [comment] 2020-08-02 02:26
Duplicate of #27550

**Closed by ShizCalev** 2020-08-02 02:26 UTC
Labels: Bug, Needs Reproducing, Runtime
