### ISSUE TITLE
People can be filled with frost oil for no apparent reason, probably related to xenobio.

### ISSUE THREAD

**Issue by rev-benji** [tgstation/tgstation#56256] opened 2021-01-18 21:06 UTC
## Round ID:

[154501](https://scrubby.melonmesa.com/round/154501)
[154506](https://scrubby.melonmesa.com/round/154506)
[154517](https://scrubby.melonmesa.com/round/154517)

## Testmerges:
#55534 

## Reproduction:
So, 2 rounds today I have been filled with frost oil and died.  The first, I was standing in the mining base, nobody was near me or anything.  Suddenly got cold.  I checked atmos, it was normal.   I managed to get back on the station via shuttle before I died. I was revived in medbay, and was still freezing. I had no disease.  I didn't chem scan myself that round but I'm pretty sure it was frost oil.  This is round 154501.

A few rounds later, I was playing AI.  Someone was accused of being a changling (Fixes-the-walls, engineer lizard).  The reason was, someone interacted with them, then a short time later, they got very cold.  Fixes was just chilling in the engineering lobby making borgs and AIs.  It didn't make sense to me that a changling would 1.make asimov AIs, 2. randomly cryo sting someone and not follow up on it. It reminded me of the round I had earlier and I said "this may be a bug." (ock ick, pls no ban) Someone in medical said "COULD A BUG CAUSE THEM TO BE INJECTED WITH FROST OIL AND CRYOXADONE?" Yes, yes it could.  Round end, there were no changlings.  round 154506.

Just now, I was walking in the halls.  It was somewhat cold in areas, but not in the area I was in, and not freezing.  suddenly I got extremely cold and died again.  I chem scanned myself this time, and I was filled with frost oil.  There were changlings that round (154501) but the fact that nobody was near me at the time and the fact that nobody tried to absorb me afterwards makes me think this is a bug.

Looking at the code, the only conclusion I can come to is that this is related to xenobio, some dark blue slime reactions can add both frost oil and cryoxadone.  I guess its adding it to the wrong person? I don't know about the first round, but I know the second and 3rd rounds listed, someone was doing xenobio.  

Please fix soon as this can randomly kill people, inevitably someones antag round will be ruined and the salt will flow.

**Comment by dragomagol** [comment] 2021-01-18 22:19
There have been recent issues (likely with atmos) that appear to be causing people to freeze for no reason. This may be related.

**Comment by Livrah** [comment] 2021-01-19 07:47
Did health scan shows frost oil or just "something bad, must be xenobio"?
With new fast atmos any hull breach makes the station into a fridge.

**Comment by interestingusernam3** [comment] 2021-01-19 10:11
Your "bug" is a shapeshifting bug from space.

**Comment by cacogen** [comment] 2021-01-19 11:06
This happened to me during a round as QM today. Nobody near me. Started freezing randomly. Couldn't figure out why. Moving rooms didn't solve it. The atmosphere was fine (checked with an analyser). I was at the threshold of softcrit when I put on a hardsuit I happened to have in the warehouse and turned on its thermal regulator, which immediately stopped the damage. Still had to heal my burns though.

**Comment by necromanceranne** [comment] 2021-01-19 13:51
Frost Oil and Cryox is actually in fact an effect for Luminescents. So either someone has found a way to transfer that to someone else, which is a bug, or it's somehow affecting other people when one of these Lumi slimepeople activate it.

**Comment by TemporalOroboros** [comment] 2021-01-19 15:52
If someone has figured out how to redirect these effects to other people that could be extremely bad. I'm pretty sure there's one that straight up makes you explode.

**Comment by D4C-420** [comment] 2021-01-19 16:22
> Just now, I was walking in the halls. It was somewhat cold in areas, but not in the area I was in, and not freezing. suddenly I got extremely cold and died again. I chem scanned myself this time, and I was filled with frost oil. There were changlings that round (154501) but the fact that nobody was near me at the time and the fact that nobody tried to absorb me afterwards makes me think this is a bug.

A ling just going around frost stinging people for no reason other than to be a dick is not that odd, Your lack of cryoxadone further supports this idea.  Yes there are ways for a lumi to spread frost oil and cyroxadone to others but this is purely with foam and smoke NOT random teleportation of regents. I'm going to make the bet that this has nothing to do with xenobio and more to do with tempature regulation being out of wack.   In only 2 of those rounds (154501 and 154517) xenobio was actually done and only in round 154501 did someone harvest both a green AND dark blue slime which is needed to get frost oil and cyroxadone.  Yes blue slime cores can be used to make frost oil but then why would the other chem reactions not be broken? Again temp issue and the round you where found with frost oil (which is also the only round with a xenobio getting both greens and dark blues) suggest this has nothing to do with xenobio.

**Comment by necromanceranne** [comment] 2021-01-19 19:17
Importantly were you a lizard person?

**Comment by rev-benji** [comment] 2021-01-20 19:01
i was a human.  The 3rd round it might have been a ling but i think I had i think 70 units of frostoil so thats like 3 stings?  Possible.  

there is a different bug that causes peoples temperature to get stuck on -5 (i just experienced this) so maybe that explains the first round? Really wish I had chem scanned myself that round

**Comment by Qustinnus** [comment] 2021-01-21 17:48
![image](https://user-images.githubusercontent.com/20987591/105390397-49fa2480-5c19-11eb-887d-9cf6353f2384.png)

**Comment by timothymtorres** [comment] 2021-12-27 01:36
Duplicate of #56273 and it appears it was fixed at some point.

**Closed by timothymtorres** 2021-12-27 01:36 UTC
Labels: Bug
