### ISSUE TITLE
Humans... uh. Melt? Look just click on me you'll see.

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73154] opened 2023-02-02 04:34 UTC
Reporting client version: 514.1589

## Round ID:
[199357](https://scrubby.melonmesa.com/round/199357)

## Reproduction:
So basically my body just seems to melt downwards for no reason. It's happened twice in the linked round and once in the round on Manuel before that. I only notice because my hands stick out of my gloves. The first time it happened in the linked round, my entire torso was squished down and my head was just floating. Here's a picture of the second time it happened in that round.
![image](https://user-images.githubusercontent.com/44104681/216228168-bf46b4ca-2501-40ad-b088-7246ce14c863.png)

I can't tell you how to reproduce this, genuinely no fucking idea.

**Comment by san7890** [comment] 2023-02-02 04:56
@MrMelbert those arms look suspiciously... short...

**Comment by timothymtorres** [comment] 2023-02-02 05:09
Whatever is causing this is likely related to #73153 since they both seem to be from dwarf effects.

**Comment by ATH1909** [comment] 2023-02-02 12:07
https://www.youtube.com/watch?v=TM3FF3lOpKo

**Comment by TheVekter** [comment] 2023-02-02 18:05
Someone add this to the fuck-up list

**Comment by Kubisopplay** [comment] 2023-02-02 18:19
First stage of returning to crab

**Comment by VladinXXV** [comment] 2023-02-04 03:54
![image](https://user-images.githubusercontent.com/44104681/216742616-5dd5a4b8-f666-49b6-b373-d08b4ed286a0.png)
![image](https://user-images.githubusercontent.com/44104681/216742642-04e6bba0-81ec-45a6-9dae-c1a9865c536a.png)
![image](https://user-images.githubusercontent.com/44104681/216742649-3658f419-e3ec-45c0-8c3c-fe675df6d3ab.png)
![image](https://user-images.githubusercontent.com/44104681/216742656-c22906dd-0370-4f42-b6a9-8c235f7ee5db.png)
Noticed again in round 199470. Not sure exactly when it started, but I noticed it some time before 30 minutes. Also happened at some point in that round to Petra Fischer, like in the original screenshots.

**Comment by LSommers** [comment] 2023-02-04 06:36
I've had this issue once as well- no round ID unfortunately, but it left both me and the admin I pointed it out to baffled.

**Comment by Time-Green** [comment] 2023-02-04 23:01
I ran into this too, I think while I was restyling my hair a bunch with a mirror

**Comment by LSommers** [comment] 2023-02-05 22:50
> I ran into this too, I think while I was restyling my hair a bunch with a mirror

I believe that I changed my hair a couple times when this happened to me as well. Might be worth looking into.

**Comment by ZephyrTFA** [comment] 2023-02-15 16:35
I'm wondering if this is caused when body overlays get redrawn

**Comment by JohnFulpWillard** [comment] 2023-03-16 18:04
I can replicate it 100% by doing *cry emote as a Monkey

**Comment by Time-Green** [comment] 2023-03-17 06:33
That kinda makes sense then. Crying draws a bodypart_overlay, if it runtimed the bodyparts could lose their offset and “melt”

**Comment by kawoppi** [comment] 2023-03-17 23:26
I have two round IDs where it happened to me: 202010 and 201946. I didn't spot what happened right before my arms dropped but I did so some *cry emotes on both rounds so it could be related to emote_bodypart_overlay maybe?
![huh](https://user-images.githubusercontent.com/94711066/226068961-56fd7009-9c42-492e-810e-d534ed3838b9.PNG)

**Comment by Hardly3D** [comment] 2023-04-22 14:04
Uhh, I'm not sure if it's actually fixed for good? I saw this happen as of recently.
Round ID: 204083
![image](https://user-images.githubusercontent.com/66234359/233789506-e0a66b0c-6920-4c3f-a1e8-cc18ed2da530.png)

**Comment by msgerbs** [comment] 2023-05-05 21:45
> Uhh, I'm not sure if it's actually fixed for good? I saw this happen as of recently. Round ID: 204083 ![image](https://user-images.githubusercontent.com/66234359/233789506-e0a66b0c-6920-4c3f-a1e8-cc18ed2da530.png)

If you see this again please make a new issue for it, it will get more attention that way.

**Comment by timothymtorres** [comment] 2023-05-06 03:06
> If you see this again please make a new issue for it, it will get more attention that way.

We don't want to encourage people to necro an old issue by spamming new issue reports.  When people do this it gets closed as a duplicate.

**Comment by msgerbs** [comment] 2023-05-06 03:08
If somebody's closing as duplicate and citing a closed/fixed issue, they're wrong and should feel bad. On the other hand it can get really confusing having an issue get reopened months later that ends up having had a totally different cause than the first time.

**Comment by BlueMemesauce** [comment] 2023-05-17 20:34
Round 206245 my chest went above my head

![image](https://github.com/tgstation/tgstation/assets/47338680/db17fea5-0c6c-4f11-b127-1b86a7fb66b0)

![image](https://github.com/tgstation/tgstation/assets/47338680/5ab0df99-4928-467b-9100-c18739c66ce4)

**Comment by MrMelbert** [comment] 2023-06-30 03:31
The original issue of this has been fixed, this shouldn't have been re-opened. 

The more recent occurrences are a completely different method of "melting". I'm going to outline the cause of it in a new issue.

**Closed by MrMelbert** 2023-06-30 03:31 UTC
Labels: Tested/Reproduced, Against God and Nature
