### ISSUE TITLE
Chest Cavity Surgery with Advanced Mending Tool

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#47099] opened 2019-10-14 23:42 UTC
Issue reported from  Round ID: 121443 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488

I want to mention something first: This issue had not occurred in the round stated yet. I noticed this round while I was messing around with the server on my test server (using the exact same code).

When performing a Chest Cavity Implant Surgery, attempting to use the Advanced Mending Tool will not mend the site of operation, but instead tries to put the tool inside the patient. That's pretty much all I came here to say.

**Comment by Fikou** [comment] 2019-10-15 12:53
this is an oversight, not a bug
the step is to put something in the body, and if you didnt put anything in it still is on that step, so the mending tool (im pretty sure it applies to normal cautery too) doesnt mend the incision and just puts inside
the way to fix it would be to make the next surgery step happen if the cautery is used as a tool

**Comment by kriskog** [comment] 2019-10-15 13:04
We got a bunch of repeatable surgeries advancing to the alternate closing step if a cautery is used, ie organ manipulation. Probably a good place to look to keep it consistent with the rest.

If anything, it's a consistency issue.

**Comment by Anonmare** [comment] 2019-10-15 14:49
Normally it does stop cauteries being put in a body but only checks if it's a cautery, and not a TOOL_CAUTERY which is why it's not catching the searing tool

**Closed** 2019-10-16 21:13 UTC
Labels: Bug, Consistency Issue
