### ISSUE TITLE
Chat tabs sometimes reset

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#61575] opened 2021-09-19 21:46 UTC
See title, my OOC chat tab has dissapeared several times this day, resetting the main chat tab to default.

**Comment by Mothblocks** [comment] 2021-09-20 01:53
not a new bug but i've been getting this a lot as well, especially recently when i wasnt getting it before

**Comment by Mooshimi** [comment] 2021-09-20 06:07
same

> not a new bug but i've been getting this a lot as well, especially recently when i wasnt getting it before

**Comment by TiviPlus** [comment] 2021-09-21 08:55
Can confirm happens on tgmc too usually after I try to run a tg server locally in the background while being connected to tgmc

**Comment by Sealed101** [comment] 2023-02-02 15:41
dupe of #52997 actually honk honk

**Comment by Mooshimi** [comment] 2023-02-03 15:06
> dupe of #52997 actually honk honk

ok

**Comment by Mooshimi** [comment] 2023-02-03 15:07
Duplicate of #52997

**Closed by Mooshimi** 2023-02-03 15:07 UTC
Labels: Bug, Tested/Reproduced
