### ISSUE TITLE
Items disappears

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#23968] opened 2017-02-11 14:33 UTC
The essence of the bug is that when you take off the bag, pressing on it with the left mouse button and transferred to an object that you have in your hand - bag happens simply disappears. It is no longer in the game and you can not return it.
So I removed the nuclear ldisk authentication and in general - any items that can be put in a bag.
I tested under the scheme: Backpack at the bag in his left hand jetpack from EVA and do what I have described above. (Probably it works with any subject, but I checked with this.)

**Comment by Cyberboss** [comment] 2017-02-11 15:14
dupe of #23794

**Comment by rainbowjose** [comment] 2017-02-11 15:17
Sorry!

**Closed** 2017-02-11 15:42 UTC
