### ISSUE TITLE
Items Icon in dropdown menu appear to be botany bag

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#49879] opened 2020-03-11 02:32 UTC
Issue reported from  Round ID: 131966 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

![image](https://user-images.githubusercontent.com/37246588/76376510-d744cb00-631e-11ea-9666-27402c49e139.png)

i saw it with mop and spear

**Comment by redguy999** [comment] 2020-03-11 03:24
Had this occur but it changes what the incorrect sprite is either between rounds or connections, but I’m not sure which, it wasn’t ever a botany bag for me.

**Comment by cacogen** [comment] 2020-03-11 04:46
I've had this happen with a number of different item sprites during the same round. Thought it might be something on my end so didn't report it.

**Comment by Dennok** [comment] 2020-03-11 07:43
I've had this happen with freezer icon.
And this happens in strange way when one item of one type show right and another in this place show wrong.

**Comment by kriskog** [comment] 2020-03-14 00:46
Clientside thing, fixed with a restart of the client. Heard others having the issue as well

**Comment by wesoda25** [comment] 2020-04-09 05:08
Still have this all the time

**Comment by timothymtorres** [comment] 2021-12-17 13:35
Duplicate of #59280

**Closed by timothymtorres** 2021-12-17 13:35 UTC
Labels: Bug
