### ISSUE TITLE
The three numbers in this atmos warning dialogue are not zero, and have not been zero for a long time.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35092] opened 2018-01-29 02:54 UTC
Round ID: 82727 and many others

![](https://imgur.com/UYZ7qgF.jpg)

This message starts with a allcaps "HEY! LISTEN!" for a reason. This needs to be fixed.

**Comment by DaxDupont** [comment] 2018-01-29 02:55
Those turfs are lavaland generally. 
It's something to do with the cave generator i think

**Comment by Buggy123** [comment] 2018-01-29 02:56
It still needs to be fixed regardless, and I can't do it myself because I'm not remotely experienced enough to find the issue.

**Comment by DaxDupont** [comment] 2018-01-29 02:57
It will probably be fixed with all the template loading going around.

**Comment by RandomMarine** [comment] 2018-01-29 03:41
The major culprits are lavaland ruins that either:
A) Have standard air tiles connected to lavaland air tiles (Ash walker nest has these)
B) Have standard air that's normally sealed by rock tiles, but tunnel generation breaks it open.
C) Whatever happened to replace this R-wall (That _should_ be where my ghost is) with a lavaland lava tile. Next to the lava that has station air.
![2018-01-28 19_38_01-space station 13](https://user-images.githubusercontent.com/6583225/35492639-ed36b620-0462-11e8-896f-5e19021da4ba.png)

**Comment by ShizCalev** [comment] 2018-01-29 07:02
C is caused by #27719

**Comment by vuonojenmustaturska** [comment] 2018-01-29 10:53
There is also a separate issue where a "lava vent"-type harmless walkable turf is randomly generated inside the snow biosphere ruin in lavaland. The lava vent generates with the standard lavaland atmos mix but the biosphere has freezing air inside.

**Comment by Jalleo** [comment] 2018-01-31 23:48
@Cruix did you fix this?

**Comment by Cruix** [comment] 2018-02-02 02:22
No

**Closed** 2018-02-03 18:57 UTC
Labels: Bug, Maintainability/Hinders improvements
