### ISSUE TITLE
Clown bomb simple mob clowns drop mob spawners instead of clown corpses.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#63609] opened 2021-12-24 23:13 UTC
Reporting client version: 514.1556

## Round ID:
[175369](https://scrubby.melonmesa.com/round/175369)

## Testmerges:
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [Untested: Fix outfit equipping not working](https://www.github.com/tgstation/tgstation/pull/63606)

## Reproduction:
Get a simple mob clown from a clown bomb.
Kill it.
Get an immovable mob spawner instead of a corpse.
![image](https://user-images.githubusercontent.com/56049844/147372854-ecd81f01-b1cc-459c-bcec-bb3f77166502.png)

It might be an issue with /obj/effect/mob_spawn/human/clown/corpse.

**Comment by timothymtorres** [comment] 2021-12-25 11:48
Duplicate of #63444

**Closed by timothymtorres** 2021-12-25 11:48 UTC
