### ISSUE TITLE
attack chain exploded and now half the things ingame don't interact properly

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#87854] opened 2024-11-11 17:14 UTC
### Client Version:

n/a

### Issue Summary:

you cant screwdriver destructive analyzers
you cant RPED flatpackers
you need to right click to enter circuit boards into flatpackers
you cant RCD deconstruct tables
probably tons more
(also you cant put a radio jammer inside a destructive analyzer, but i think that's unrelated)

many such cases. i dont know what caused it a few days ago it worked properly

### Round ID:

n/a

### Test Merge Information:

n/a

### Reproduction Steps:

1. do the stuff in summary

**Comment by Time-Green** [comment] 2024-11-11 17:17
Why didnt this set off 10 trillion unit tests 😭

**Comment by carlarctg** [comment] 2024-11-11 17:31
more stuff to report but its ic occ rn

**Comment by MrMelbert** [comment] 2024-11-11 17:39
#87679 , specifically https://github.com/tgstation/tgstation/pull/87679/files#diff-2b7a436c179cd91e18cf8ec1bba05dffd02706bcd20460726ed1565c06d04e71 was redundantly added and prevents you from interacting with tables at all with RCDs (when it should have already functioned as intended)

**Comment by SyncIt21** [comment] 2024-11-11 17:39
These are all separate independent issues & there isn't any core bug with the attack chain.

**Comment by SyncIt21** [comment] 2024-11-11 18:01
> (also you cant put a radio jammer inside a destructive analyzer, but i think that's unrelated)

This was fixed by #87690

> you cant screwdriver destructive analyzers

Use combat mode. See changelog #87690

**Comment by GremlinSeeker** [comment] 2024-11-11 18:07
> > (also you cant put a radio jammer inside a destructive analyzer, but i think that's unrelated)
> 
> This was fixed by #87690
> 
> > you cant screwdriver destructive analyzers
> 
> Use right click. Even the screen tips specify it

doesn't work

**Comment by SyncIt21** [comment] 2024-11-11 18:11
> you cant RPED flatpackers

This was never a feature. It picks up component parts & stacks & flatpack boxes don't fall under either category

**Comment by SyncIt21** [comment] 2024-11-11 18:44
> The machine. You can't upgrade the machine.

Ohhh. Let me test that

**Comment by carlarctg** [comment] 2024-11-11 18:50
![image](https://github.com/user-attachments/assets/bc9f36b2-69aa-405c-9601-574784756046)

**Closed** 2024-11-12 17:13 UTC
Labels: Bug, Tested/Reproduced
