### ISSUE TITLE
Medibots are rapidly resetting and spamming,

### ISSUE THREAD

**Issue by lilahnovi** [tgstation/tgstation#80502] opened 2023-12-22 01:57 UTC
## Issue Summary

Since yesterday, I've noticed that Medibots are acting a bit odd.
They spam the voiceline for someone being totally healed (all patched up/apple a day) over and over after a single injection. They start over, notice you are still not healed, and do it again. (see video: https://www.youtube.com/watch?v=n95zs8hf8B0)
Usually when they are finally done, they will say the "There's always a catch..." voice line.

They will also come to you from their start point (T.R.A.M Unit for example), inject you once. Go back to their start point, and then come right back to you. It looks like the animation is placing the syringe back into itself each time. I didn't get a video of this, but yeah.

## Round ID:

[220904](https://scrubby.melonmesa.com/round/220904)
However, I did start to notice this yesterday (12/20). I originally thought it was a player controlling the medibot, and found out the npc bot is just going wackaloo.

## Testmerges:
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Optimizes the pipeline of basic mobs](https://www.github.com/tgstation/tgstation/pull/79498)

![image](https://github.com/tgstation/tgstation/assets/124811534/512f1a3b-2e9f-44ca-8ed4-59244e4a284c)

**Comment by MrMelbert** [comment] 2023-12-22 02:16
Maybe caused by https://github.com/tgstation/tgstation/pull/79498 , please include test merges

**Comment by lilahnovi** [comment] 2023-12-22 02:35
> Maybe caused by #79498 , please include test merges

Sorry about that, totally slipped my mind.

The Testmerges are: 
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Optimizes the pipeline of basic mobs](https://www.github.com/tgstation/tgstation/pull/79498)

I'll edit my post with them as well.

**Comment by Ben10Omintrix** [comment] 2023-12-22 06:03
they are working fine for me on local, I think this may be caused by the basic mob optimisation test merge

**Comment by DaxDupont** [comment] 2023-12-24 00:42
On 221019 I had a medbot repeating someone in critical condition a mile away from the location and there was noone there.

**Comment by lilahnovi** [comment] 2023-12-24 11:48
> On 221019 I had a medbot repeating someone in critical condition a mile away from the location and there was noone there.

This has been happening for a couple of days for me. Once it finds someone in crit, it doesn't stop announcing it long after they're fine. You have to go and turn their crit announcements off to stop them.

**Comment by ShizCalev** [comment] 2024-06-24 15:02
Still an issue?

**Comment by SmArtKar** [comment] 2024-06-25 07:36
> Still an issue?

Fixed with kobsa's refactors according to them

**Closed by SmArtKar** 2024-06-25 07:36 UTC
Labels: Needs Reproducing, Cleanup Flagged
