### ISSUE TITLE
The blood transfer mechanic from bloody hands/gloves is nonfunctional

### ISSUE THREAD

**Issue by pigeonsk** [tgstation/tgstation#37096] opened 2018-04-10 07:43 UTC
1. Dirty your hands/gloves with blood
2. Wipe your filthy grubby blood hands all over the station and station objects
3. Notice that nothing you touch becomes bloody, view variables to confirm nothing you touch is getting any sort of blood nor is the counter for bloody hands/gloves decreasing
4. Look at code and code comments that say they intend for this to happen
5. Realize no one cares about a niche mechanic for a role that is seldom played properly

**Comment by AlexTheSysop42** [comment] 2018-04-10 13:47
bloody hands also don't wash

**Comment by pigeonsk** [comment] 2018-04-10 20:03
They wash but because of a race condition the blood overlay doesn't update. That particular problem is fixed here #37094.

**Comment by kevinz000** [comment] 2018-04-11 09:30
likely my fault, putting it here now, as i made component forensics. looking into it in a bit.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-11 16:09
@pigeonsk please put `fixes (pr number)` in the changelog body of the PR next time so it'll automatically close.

@KorPhaeron fixed in the above pr

**Comment by pigeonsk** [comment] 2018-04-11 19:51
This is a separate issue, it's not fixed.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-11 20:38
> Look at code and code comments that say they intend for this to happen

Can you link relevant code?

**Comment by pigeonsk** [comment] 2018-04-11 21:00
https://github.com/tgstation/tgstation/blob/master/code/modules/detectivework/detective_work.dm

add_fibers proc

**Comment by timothymtorres** [comment] 2022-05-30 20:45
Duplicate of #38820

**Closed by timothymtorres** 2022-05-30 20:45 UTC
Labels: Bug
