### ISSUE TITLE
Implants var for ghost role spawners is not visible when editing them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27741] opened 2017-05-27 05:59 UTC
All the other vars like pockets, eyes, suit, ID etc function normally and can be overriden by var editing, but implants is the one exception that is not present.

**Comment by Cruix** [comment] 2017-05-29 03:56
The impants list is in the outfit

**Comment by WJohn** [comment] 2017-11-19 11:19
![]()
![]()

**Comment by WJohn** [comment] 2017-11-19 11:20
I'm sure I look like a fucking idiot going back and "confirming" these things are still around *with picture evidence* when it's really obvious. Oh well.

**Comment by fizzle7** [comment] 2019-01-30 20:15
The implant is actually a variable of the outfit object which in itself is a variable of the mob_spawn class, so instead of searching for implant in VV you need to search for outfit, open the outfit and then search for the implant. I don't see an issue here.

**Comment by Jalleo** [comment] 2019-01-30 20:16
The problem is that it doesnt have the datum outfit interactions completly linked to the mob spawber for mappers. What WJohn is annoyed about is that they cannot set up a mob to spawn with implants. This is a consistency and mapping issue.

**Comment by JohnFulpWillard** [comment] 2023-03-09 19:42
I'm gonna close this as it's no longer a consistency issue (all other vars were removed, it's all in the outfit now).

**Closed by JohnFulpWillard** 2023-03-09 19:42 UTC
Labels: Mapping, Consistency Issue, Tested/Reproduced
