### ISSUE TITLE
Space ninjas can't use adrenals while stunned

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28538] opened 2017-06-17 17:55 UTC
@lordpidey

**Comment by KingPhilipIII** [comment] 2017-06-18 16:30
O yea I got wrecked as a ninja once cause of this.

**Comment by Goodstuff123456** [comment] 2017-07-06 21:48
same as #27461

**Comment by Cyberboss** [comment] 2017-08-03 14:20
Duplicate of #27461

**Closed by Cyberboss** 2017-08-03 14:20 UTC
Labels: Bug
