### ISSUE TITLE
hivebot invasion event occurring at .

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#29331] opened 2017-07-18 06:49 UTC
Impact location determined from trajectory to be . Leave the area immediately or risk annihilation.

**Comment by Cyberboss** [comment] 2017-07-19 23:45
Can anyone reproduce this? Because I can't

**Comment by Shadowlight213** [comment] 2017-07-20 07:01
Also should point out it didn't actually land.
@Cyberboss I used the admin trigger event if that helps.

**Comment by Cyberboss** [comment] 2017-07-20 14:05
Funny it always works locally. Time to good servers I guess :/

**Comment by kevinz000** [comment] 2017-07-22 05:48
![wew](https://puu.sh/wPYcG/9c39a52005.png)

**Comment by ShizCalev** [comment] 2017-07-25 23:29
fixed by #29443

**Closed** 2017-07-25 23:31 UTC
Labels: Bug
