### ISSUE TITLE
Berets and Some hats cut off the top of your hair.

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#88006] opened 2024-11-18 17:01 UTC
### Client Version:

515.1644

### Issue Summary:

Wearing berets or some hats like the detective fedora cuts off a bunch of the hair out of the sprite and it looks awful.

### Reproduction Steps:

Put on a hat. Berets I know for sure are doing it.

**Comment by Jacquerel** [comment] 2024-11-18 17:04
If this bug report is just this feature then this isn't a bug.
https://github.com/tgstation/tgstation/pull/87940

**Comment by Sadboysuss** [comment] 2024-11-18 17:07
it's not intended, I will fix it

also duplicate of https://github.com/tgstation/tgstation/issues/87991

**Closed by Sadboysuss** 2024-11-18 17:07 UTC
Labels: Not a bug, Cleanup Flagged
