### ISSUE TITLE
Plasmamen have all species customization options visible at once

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#86622] opened 2024-09-12 19:45 UTC
### Client Version:

515.1643

### Issue Summary:

![obraz](https://github.com/user-attachments/assets/08b4de6f-5556-427e-a355-101ad4781b72)
Tweaking these does not seem to affect anything as long as the character is a plasmaman.

### Test Merge Information:

The following pull requests are currently test merged:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit bfecdb9b39](https://www.github.com/tgstation/tgstation/pull/83227)
[#85512: 'Storage / table interactions at the bottom of the interaction chain' by MrMelbert at commit 1d15010dfc](https://www.github.com/tgstation/tgstation/pull/85512)
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 193bd4f5b3](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. Open character preferences
2. Select plasmaman race
3. Behold

**Comment by deathrobotpunch** [comment] 2024-09-13 00:39
can’t wait to have a plasmaman with moth wings, antennae, cat ears and a lizard tail

**Comment by SmArtKar** [comment] 2024-09-13 05:14
Caused by one of the last 17 merged PRs

**Closed** 2024-09-16 13:01 UTC
Labels: Bug, Tested/Reproduced
