### ISSUE TITLE
Putting in welding shieled eyes still gives the empty eye socket apperance

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25940] opened 2017-04-06 18:39 UTC
- Remove eyes
- (at this point, my operator closed the incision, accidentally, then opened it again)
- Insert welded shielded eyes

I can see, immune to flashes, but it looks like I have no eyes.

**Comment by Armhulen** [comment] 2017-04-09 09:28
dupe of MINE

**Closed** 2017-04-09 09:45 UTC
Labels: Bug
