### ISSUE TITLE
a mech getting destroyed doesnt drop anything in its cargo hold, and instead deletes it all

### ISSUE THREAD

**Issue by MaineTheMan** [tgstation/tgstation#78613] opened 2023-09-26 07:32 UTC

**Comment by Sealed101** [comment] 2023-09-28 14:11
[![parenting](https://user-images.githubusercontent.com/39163353/198381160-f0aa7fc4-4f2d-486f-8b33-44a1965e2ad1.svg)](https://media.oglaf.com/comic/parenting.jpg)

### Please link the branch or the repo of the server that the issue was initially encountered on. Non-master or downstream issues that don't meet this requirement are subject to closing. 
#### Trying to reproduce the issue on the compiled code of our repo's master is strongly recommended as well. 


i am however certain that this would work on our code because mech cargo is stupid much like mech code in general

**Comment by san7890** [comment] 2023-11-14 06:36
![image](https://github.com/tgstation/tgstation/assets/34697715/dd487ab9-18c4-4068-ba01-77c268646bdd)

please come back if this occurs on our codebase

**Closed by san7890** 2023-11-14 06:36 UTC
