### ISSUE TITLE
Shapeshifting with stuff like drake potion causes parasite to be stuck, and become ded when you shift back

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#49285] opened 2020-02-10 20:16 UTC
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49233: 'Paintings icons and persistence.' by AnturK at commit 627a6cc77f
#49098: 'Supports named arguments in AddComponent and AddElement' by ninjanomnom at commit 493d17786a

## Reproduction: 
1-get parasite
2-get drakeform or something
3-shift
4-parasite cant go out
5-shift again
6-parasite ded

**Comment by Couls** [comment] 2020-02-10 21:12
duplicate of #48841

**Closed** 2020-02-10 21:31 UTC
