### ISSUE TITLE
Pai in backpack makes camera jump like crazy

### ISSUE THREAD

**Issue by Kubisopplay** [tgstation/tgstation#63415] opened 2021-12-14 23:23 UTC
Reporting client version: 514.1568

## Round ID:
[174806](https://scrubby.melonmesa.com/round/174806)

## Testmerges:
- [documents important MC vars and procs and adds tracking of tick usage when the mc first wakes up and other stats](https://www.github.com/tgstation/tgstation/pull/63355)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:
- Be PAI
- Be in the backpack of someone who is moving
- Say welcome to headache

While being carried as pAI the camera jumps every step instead of scrolling smoothly, which causes eyestrain

**Comment by TheBonded** [comment] 2021-12-15 18:49
this also happens while in holochassis mode and sitting in their backpack/on their head. It seems like the camera doesn't like being in the inventory of anything else

**Comment by timothymtorres** [comment] 2021-12-16 12:54
Duplicate of #56099

**Closed by timothymtorres** 2021-12-16 12:54 UTC
Labels: Bug
