### ISSUE TITLE
Can't order things as cargo

### ISSUE THREAD

**Issue by CJulien** [tgstation/tgstation#25005] opened 2017-03-11 23:21 UTC
Problem Description: CARGO CANNOT BUY THINGS, YOU PUT THEM IN THE CART AND NOTHING SHOWS UP

What did you expect to happen: Reeee.

What happened instead: REEEEEEEE.

Why is this bad/What are the consequences: Cargo literally cannot function, a definite step up from the conveyor issue where it was just harder.

Steps to reproduce the problem: It never works so it should be easy.

Server: SYBIL

Revision: 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): REEEEEEEEEEE

Thanks for helping us out!

**Comment by jughu** [comment] 2017-03-11 23:40
Sir. Your credit card expired

**Comment by CJulien** [comment] 2017-03-12 00:00
Ha! Even if my bitch ex-wife took everything from me I assure you that we had PLENTY of creds after _repossessing_ some of the science-bound minerals.

**Comment by Penguaro** [comment] 2017-03-12 15:56
In testing, I can only reproduce it on Sybil. Basil orders correctly as does private server testing.

**Comment by Cyberboss** [comment] 2017-03-12 18:46
WHATS THE SERVER REVISIONS???

**Comment by Penguaro** [comment] 2017-03-12 18:53
Let's see here. Sybil is at ...
Server revision compiled on: 2017-03-11
The following pull requests are currently test merged:
#24974: 'Temporal solution to transitioning to nullspace problem' by Razharas 
#24963: 'Fixes lighting of pixel shifted objects and reverts the hacky memleak fix.' by MrStonedOne 
#24941: 'Fixes stack splitting' by AnturK 
#24993: 'Shuttles and Centcom now have dynamic lighting' by ChangelingRain 
#24994: 'Fix for windows being uinteractable.' by AnturK 

Based off master commit:
2062e3610090de55c998b0c8ef8f4b8d3c547448 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 7 of 21 roundtypes
Game Mode Odds for current round:
blob 3.4%
traitorchan 20.3%
double_agents 11.9%
traitor 15.3%
clockwork_cult 6.8%
cult 6.8%
extended 1.7%
nuclear 13.6%
revolution 10.2%
wizard 10.2%
All Game Mode Odds:
blob 3.4%
traitorchan 20.3%
double_agents 11.9%
traitor 15.3%
clockwork_cult 6.8%
cult 6.8%
extended 1.7%
nuclear 13.6%
revolution 10.2%
wizard 10.2%


In spot checking, Basil and my private are the same. I'm curious what makes Sybil different.

**Comment by Cyberboss** [comment] 2017-03-12 19:11
The testmerges, get the list of testmerges from bagil

On Mar 12, 2017 2:53 PM, "Mr Potato Shaman" <notifications@github.com>
wrote:

Let's see here. Sybil is at ...
Server revision compiled on: 2017-03-11
The following pull requests are currently test merged:
#24974 <https://github.com/tgstation/tgstation/pull/24974>: 'Temporal
solution to transitioning to nullspace problem' by Razharas
#24963 <https://github.com/tgstation/tgstation/pull/24963>: 'Fixes lighting
of pixel shifted objects and reverts the hacky memleak fix.' by MrStonedOne
#24941 <https://github.com/tgstation/tgstation/pull/24941>: 'Fixes stack
splitting' by AnturK
#24993 <https://github.com/tgstation/tgstation/pull/24993>: 'Shuttles and
Centcom now have dynamic lighting' by ChangelingRain
#24994 <https://github.com/tgstation/tgstation/pull/24994>: 'Fix for
windows being uinteractable.' by AnturK

Based off master commit:
2062e36
<https://github.com/tgstation/tgstation/commit/2062e3610090de55c998b0c8ef8f4b8d3c547448>
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 7 of 21 roundtypes
Game Mode Odds for current round:
blob 3.4%
traitorchan 20.3%
double_agents 11.9%
traitor 15.3%
clockwork_cult 6.8%
cult 6.8%
extended 1.7%
nuclear 13.6%
revolution 10.2%
wizard 10.2%
All Game Mode Odds:
blob 3.4%
traitorchan 20.3%
double_agents 11.9%
traitor 15.3%
clockwork_cult 6.8%
cult 6.8%
extended 1.7%
nuclear 13.6%
revolution 10.2%
wizard 10.2%

In spot checking, Basil and my private are the same. I'm curious what makes
Sybil different.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/25005#issuecomment-285965747>,
or mute the thread

**Comment by Penguaro** [comment] 2017-03-12 19:14
And from Bagil...

Server revision compiled on: 2017-03-11
The following pull requests are currently test merged:
#24974: 'Temporal solution to transitioning to nullspace problem' by Razharas 
#24963: 'Fixes lighting of pixel shifted objects and reverts the hacky memleak fix.' by MrStonedOne 
#24941: 'Fixes stack splitting' by AnturK 
#24994: 'Fix for windows being uinteractable.' by AnturK 

Based off master commit:
2062e3610090de55c998b0c8ef8f4b8d3c547448 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 7 of 21 roundtypes
All Game Mode Odds:
blob 3.4%
traitorchan 20.7%
double_agents 12.1%
traitor 15.5%
clockwork_cult 6.9%
cult 6.9%
extended 1.7%
nuclear 13.8%
revolution 10.3%
wizard 8.6%

**Comment by ChangelingRain** [comment] 2017-03-13 01:16
Caused by #24993 but now fixed

**Closed by ChangelingRain** 2017-03-13 01:16 UTC
Labels: Bug, Priority: High
