### ISSUE TITLE
CQC disarming people with items that feature snap-back behavior is glitchy

### ISSUE THREAD

**Issue by senjx** [tgstation/tgstation#45543] opened 2019-07-28 06:46 UTC
## Round ID:
114375

## Testmerges:
#45485: '[Test Mergeable] Infection Gamemode' by Whoneedspacee at commit 79cf8b8f47
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 9c3be66b44
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759

## Reproduction:

1. Person X has CQC by any means, such as being a nuclear operative or the chef in the Kitchen.
2. Person X CQC disarms person Y holding an item that features snap-back behavior, such as the janitor's water backpack mister.
3. The item will return to person Y due to the snap-back behavior of the item. However, person X will also have a "ghost" sprite of the item on one hand.

The person I found this out with said she couldn't use the hand that she used to CQC disarm me, but I cannot confirm that until further reproduction is attempted.

**Comment by nemvar** [comment] 2019-07-28 17:16
This is a dupe. Just have to find the original issue.

**Comment by nemvar** [comment] 2019-07-28 17:16
Dupe of #43100

**Closed by nemvar** 2019-07-28 17:16 UTC
Labels: Bug
