### ISSUE TITLE
Building 18 Tesla Engines at once eventually crashes the server

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#25483] opened 2017-03-25 10:03 UTC
OOC: Kevinz000: ok
OOC: Kevinz000: fun fact
OOC: Kevinz000: tesla bolts 
OOC: Hunterh98: That was a fucking awesome round
OOC: Kevinz000: are a drain to process
OOC: Kevinz000: 40 tesla engines spewing tesla bolts every 2 seconds
OOC: Kevinz000: will clog the server.
OOC: Yakumo Chen: BALL SO HARD SERVERS WANNA CRASH ME
OOC: Kevinz000: we should check tick tesla/singulo so they don't process unless there's enough time to process
OOC: Kevinz000: ok so
OOC: Kevinz000: server's cpu was at 
OOC: Kevinz000: 1004
OOC: Kevinz000: that means there's 1/10th the processing power available to process it

https://puu.sh/uXMKt/fff876a63f.webm

**Comment by kevinz000** [comment] 2017-03-25 10:03
@Iamgoofball hi

**Comment by Jalleo** [comment] 2017-03-25 12:55
Wew unintended things. Maybe they should get their own subsystem to manage this?

**Comment by Cyberboss** [comment] 2017-03-25 15:01
We'll tbf, MC is doing the best it can, but it can't prevent the server dying to stupid shit like this.
Having it's own SS would make it worse. If there are any sleeps in tesla processing, get rid of them and use world timers instead.

**Comment by MrStonedOne** [comment] 2017-03-25 17:06
the sleeps in tesla processing is from `TICK_CHECK`

**Comment by Iamgoofball** [comment] 2017-03-25 17:18
I can't do anything about Darwin's laws

**Comment by Jalleo** [comment] 2017-03-25 19:08
Wouldn't giving it its own subsystem make it better by giving us the ability to pretty much turn it down?

**Comment by BeeSting12** [comment] 2017-03-26 00:14
When did you guys make 18 teslas?

**Comment by jughu** [comment] 2017-03-26 00:32
Why would you make 18 teslas

**Comment by octareenroon91** [comment] 2017-03-26 02:58
Does hang. Can confirm.

**Comment by kevinz000** [comment] 2017-03-26 03:09
@jughu because @YakumoChen is going to get triggered if i burn down the station with my mad science instead (i was going to hellburn the sm)

**Comment by YakumoChen** [comment] 2017-03-26 04:06
>Why would you make 18 teslas

Why not?

**Comment by Penguaro** [comment] 2017-03-26 15:57
18 you say? Thank goodness you pointed this out as on forked server we routinely start 17... for science...

**Comment by Bawhoppen** [comment] 2017-03-27 13:29
This seems like a rules issue

**Comment by YakumoChen** [comment] 2017-03-28 03:45
Keep in mind that the round had also gone on for around 2 hours I believe?

**Comment by Dorsisdwarf** [comment] 2017-03-28 08:22
I think there's a limit to shit we have to support. What if it's the CE's autism project to build a device that, I don't know, keeps thousands of turfs processing atmos constantly at once? There's a point where you just have to say "Idiots who are trying their best will always outpace idiotproofing"

**Comment by Iamgoofball** [comment] 2017-03-28 09:23
I'll see if I can reproduce the crash, this is probably going to just be memory related or just sheer processing

**Comment by octareenroon91** [comment] 2017-03-28 14:22
I experienced more of a "hang" than a "crash". The server instance didn't quite max out, but it did become unresponsive.

**Comment by Tacolizard** [comment] 2017-03-28 18:07
what?!? spawning 18 teslas lags the server?!!? who knew?!!

**Comment by Iamgoofball** [comment] 2017-03-28 19:39
About how many balls would you say each tesla had?

**Comment by kevinz000** [comment] 2017-04-07 11:58
@Iamgoofball each was constantly being bombarded by PA on setting 2 or 3 forgot.

**Comment by Iamgoofball** [comment] 2017-04-07 15:16
jesus christ

yeah sorry I can't bugfix the CPU

**Comment by Jalleo** [comment] 2017-04-12 17:12
This is related to the timer issue possibly @Cyberboss.

**Comment by PJB3005** [comment] 2017-04-15 00:49
In other news, making 1000 tabs on chrome causes your PC to run out of RAM. Wow!

**Comment by nicbn** [comment] 2017-06-28 02:18
Now the question is why.

**Comment by MrStonedOne** [comment] 2017-06-28 03:02
>In other news, making 1000 tabs on chrome causes your PC to run out of RAM. Wow!

Hold my beer

**Comment by nicbn** [comment] 2017-07-15 21:42
What if we make one tesla eat another when they collide, summing the energy ball count?

**Comment by Cyberboss** [comment] 2017-07-16 16:50
Not a bad idea actually, mush mush

**Comment by Tacolizard** [comment] 2017-07-20 05:49
In other news, making ~~1000~~ 1 or 2 idk tabs on chrome causes your PC to run out of RAM. Wow!

**Comment by nicbn** [comment] 2017-08-15 00:01
Close this maybe?

**Comment by YakumoChen** [comment] 2017-09-27 12:58
I can confirm that 18 teslas still destroys the server but now in even worse ways

**Comment by Iamgoofball** [comment] 2017-09-27 16:27
>jesus christ

>yeah sorry I can't bugfix the CPU

**Comment by Bawhoppen** [comment] 2017-09-30 09:01
This is the most commented on issue

**Comment by Bawhoppen** [comment] 2017-09-30 09:01
that's currently open I mean

**Comment by PJB3005** [comment] 2017-09-30 09:28
I'm impressed with your ability to keep your drama off GitHub.

**Comment by duncathan** [comment] 2017-12-08 18:32
have you tried pooling the beams?

**Closed** 2019-07-21 22:30 UTC
Labels: Bug
