### ISSUE TITLE
Chemical reactions sometimes yield no product

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#38641] opened 2018-06-21 03:32 UTC
The last reaction yields no product when you react smaller amounts of the final chemical.

[Reproduction]: Seems to happen to all chemical reactions, but successfully reproduced with oil. Add 30u Carbon, 30u Hydrogen to beaker from chem dispenser. Then add 10u Welding Fuel three times. First two reactions work as expected, last reaction happens but does not yield any product. Should have 60u oil in the beaker now, instead of 90u.

**Comment by YPOQ** [comment] 2018-06-21 19:02
Duplicate of #38216

**Closed** 2018-06-21 21:53 UTC
