### ISSUE TITLE
Cult floor tiles fit in chests

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#50978] opened 2020-05-07 21:52 UTC
## Testmerges:

- #50558 
- #50955 

## Reproduction:

- Acquire a chest from a necropolis tendril
- Locate the cult ruin on lavaland
- Use the chest to gather the cult items
- Notice that you are picking up the cult floors too

**Comment by Fikou** [comment] 2020-06-06 09:19
lol is that why the wizard shuttle has an empty floor tile below the crate? the overlay cult flooring goes inside the crate

**Comment by Fikou** [comment] 2020-08-09 22:11
duplicate of #47316

**Closed** 2020-08-09 22:11 UTC
Labels: Bug, FUCK
