### ISSUE TITLE
Strange fingerprint anomaly in a shift, needs investigating and maybe fixing?

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#83681] opened 2024-06-03 10:39 UTC
## Issue Summary

Sorry, there really is no way to "Summarize this in a few plain sentences".

In Manuel shift 229903, I had an issue where I was playing as a detective, I was investigating a theft. 2 sets of prints which were not in the security records came up. I cross checked the security records with the AI's crew manifest, the medical records, and the PDA list, to make sure no one's sec records were missing. They were not. So I started scanning random people in order to try and find those prints, using my forensics scanner. Eventually, I got a hit on Ani Myu, an assistant. I brought Ani Myu back to my office, and manually checked her direct scan data to the security record fingerprint data. They didn't match, at all. Ani said she didn't have an arm replacement or anything, and post game she said she wasn't a ling, and according to the records logs, which DO track fingerprint changes (See: https://tgstation13.org/parsed-logs/manuel/data/logs/2024/06/03/round-229903/records.html) , no one changed Ani's fingerprints in the security records either. Additionally, just to make sure I wasn't being an idiot, the results were also checked by two other people, Ani herself, and the Captain of the shift. Even if I'm blind and dumb, 3 different people can't all be blind and dumb.

The prints in the security records came up as starting with c90bfe, but her direct scan fingerprints were dd240. Unfortunately, it doesn't look like forensics scans are publicly logged anywhere, so I could only pull these print sequences from the text logs of the shift.

So, why exactly did the forensics scan data and the security records data not match? It's an obvious issue for security work in game if sec records and scan data aren't working properly.

Brought this issue up with Fikou and another mod first, both told me to report this here, so I am reporting it.

## Reproduction:

1. Scan catgirl
2. Compare scan results to security records
3. Get confused when they don't match

**Comment by Thunder12345** [comment] 2024-06-05 08:40
Happened again round 230020. Twinleaf's prints changed from `96c1017fec1c0b8dac9ce0d3c82228cd` to `395915ea31b0d803c4c71d4615a83f95`. Prints are generated as the MD5 hash of the `unique_identity` string in their DNA, so this is probably getting changed somehow.

**Comment by 00-Steven** [comment] 2024-06-05 13:04
yeaaaaaaaaaah should probably just slap some logging on there and see what happens

**Comment by 00-Steven** [comment] 2024-06-05 14:06
Aight so I sat down and thought about it- the fingerprints being different it doesn't necessarily mean the dna unique identity was changed later in the shift, but rather that the records have the wrong dna unique identity.
So I compared this to the most common issue I find with records issues, being latejoining- lo and behold, both latejoined.
Then I recalled what I know changes your dna unique identity, and confirmed:
![image](https://github.com/tgstation/tgstation/assets/42909981/f24d2914-2db0-4255-867b-7a6cc86c1bc1)
![image](https://github.com/tgstation/tgstation/assets/42909981/41c91f19-238c-4dbd-a7b8-15934ebfbd43)
This might be a heterochromatic eyes issue.

**Comment by 00-Steven** [comment] 2024-06-05 14:10
Specifically, I think this pr merged a few days ago, may have been the source of the issues: #83452
Because it added this line to heterochromatic:
https://github.com/tgstation/tgstation/blob/b7225d8486476fc4971ef32ed3c83fd778e7e46d/code/datums/quirks/neutral_quirks/heretochromatic.dm#L27

**Comment by 00-Steven** [comment] 2024-06-05 14:14
Finding the actual source of our issues here:
https://github.com/tgstation/tgstation/blob/b7225d8486476fc4971ef32ed3c83fd778e7e46d/code/modules/mob/dead/new_player/new_player.dm#L218-L244
At line 219, injecting latejoiners into the manifest, at line 244, assigning quirks to latejoiners.

**Closed** 2024-06-08 02:07 UTC
Labels: Needs Reproducing
