### ISSUE TITLE
can't create the anti-glow mutation+it's just blue glowy

### ISSUE THREAD

**Issue by Trumpetplaya288** [tgstation/tgstation#46294] opened 2019-09-01 22:13 UTC
## Reproduction:
Combining glowy+void magnet doesn't actually produce the anti-glow mutation even though anti-glow is on the wiki. After I asked for the injector from an admin I was disappointed to find that anti-glowy is literally just blue glowy. Could it be changed to mimic the shadowshroom effect? It would fit the description a lot better than its current state.

**Comment by PKPenguin321** [comment] 2019-09-01 22:17
@nemvar ?

**Comment by nemvar** [comment] 2019-09-01 22:53
Not a bug. Negative light just kinda sucks. Shadowshrooms have and always had the exact same issue. Antiglow won't ever cancel out full room light, it can conceal you in dim areas though.

**Comment by Trumpetplaya288** [comment] 2019-09-01 22:59
wait but you still cant actually get it

**Comment by PKPenguin321** [comment] 2019-09-01 23:08
See above

**Comment by nemvar** [comment] 2019-09-02 00:06
Wait a minute, I missed the part about not being able to mix it.

**Comment by nemvar** [comment] 2019-09-02 01:36
Sorry for prematurely closing this.

**Comment by PKPenguin321** [comment] 2019-09-02 02:27
No worries

**Closed** 2019-09-03 20:36 UTC
Labels: Bug
