### ISSUE TITLE
Multiple printing off autolathe

### ISSUE THREAD

**Issue by Losenis** [tgstation/tgstation#55528] opened 2020-12-14 17:08 UTC
When you search for an item in the autolathe by name, you can only print one at a time. By tool type, you can print by x5 and by x10, but not while using the text bar search function.

**Comment by cacogen** [comment] 2020-12-14 20:58
Not a bug and more a symptom of the outdated UI the autolathe uses than something that should be fixed on its own but I agree, this has always been annoying.

**Comment by interestingusernam3** [comment] 2021-01-13 14:16
Fixed by  #56017, someone please close

**Comment by nightred** [comment] 2021-01-13 20:08
Closing as issue resolved by 56017

**Closed by nightred** 2021-01-13 20:08 UTC
Labels: Consistency Issue, Not a bug
