### ISSUE TITLE
Deconstructing/resetting engineering borgs causes them to drop...at least floor tiles from their selected modules

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#78465] opened 2023-09-20 15:50 UTC
## Reproduction:

When I reset an engineering borg, it dropped (probably from its actual selected modules bar) the floor tiles it had. When I picked those up, it was undroppable, leading me to believe this was their module nodrop floor tiles.

I'm not sure if this is true of all the other stacks/sheets, but it wouldn't surprise me.

**Comment by Sealed101** [comment] 2023-09-20 16:18
Duplicate of #78397

**Closed by Sealed101** 2023-09-20 16:18 UTC
