### ISSUE TITLE
Bodypart sprites render with incorrect layering

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20603] opened 2016-09-20 07:50 UTC
All bodyparts are rendered on the same layer, and always in the same order. This means that whenever you're facing east your right leg renders over your left leg, when logically the opposite should be true.

![d10_icon](https://cloud.githubusercontent.com/assets/4176358/18661653/e6268bda-7ee4-11e6-9ed3-6952f4baf824.png)

In this screen the ordering has been scrambled a bit due to me swapping out bodyparts but the effect can still be seen. While facing left the right leg is rendered on top. No matter what order the parts are in, one leg will render incorrectly in one dir.

The effect is very very hard to tell on the front/back, but on many races you can still tell if the chest is rendering in front or behind the limbs by if you can see the "seems" of the disembodied chest over the limbs.

**Comment by phil235** [comment] 2016-09-20 09:57
The issue in the image shown is that the left leg has an incorrect sprite in the WEST direction, it shouldn't be a showing a full limb.

**Comment by ChangelingRain** [comment] 2016-09-20 12:44
Duplicate of #19598
Also phil no, it has to show a full limb so that you still have a leg if the other leg is removed

**Comment by ChangelingRain** [comment] 2016-09-20 12:45
Though actually this is slightly better of an issue but still.

**Comment by Detective-Google** [comment] 2019-09-09 07:29
![image](https://user-images.githubusercontent.com/48196179/64511280-95709480-d2a9-11e9-969b-9529ad919507.png)
![image](https://user-images.githubusercontent.com/48196179/64511291-9a354880-d2a9-11e9-8d46-c2083dbc79de.png)
still an issue

**Comment by GoldenAlpharex** [comment] 2022-04-27 23:14
I can confirm, this still has not been fixed as of Kapulimbs.

This is a problem with how legs are rendered, and at this point I feel like we'd need some support from Lummox himself, to fix that issue, as otherwise I don't think we can actually resolve it without redrawing the entire body when aiming east or west, which, well, isn't really a good idea.

**Closed** 2022-05-11 06:49 UTC
Labels: Bug, Tested/Reproduced
