### ISSUE TITLE
Able to log in to hop console without proper ID/access

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#46197] opened 2019-08-28 01:51 UTC
Noticed this in multiple rounds, when the ID console is empty, click the slot for modify id, and it automatically logs in, puts your id in,  and you can just give yourself AA. Nice, but at the same time, not nice

**Comment by kriskog** [comment] 2019-08-28 07:38
You aren't logging in, the hop forgot to log out. See #45678.

Also dupe of #45661

**Closed by kriskog** 2019-08-28 07:38 UTC
