### ISSUE TITLE
Slimes mood/face resetting to blank upon z level change.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#75682] opened 2023-05-27 07:05 UTC
## Testmerges:

#75617 

## Reproduction:

Have any of the slime emotes on as a sentient slime
Change z level on a multi z station
Icon defaults to the default faceless slime state.

**Comment by Sealed101** [comment] 2023-05-27 09:06
Duplicate of  #74179

**Closed by Sealed101** 2023-05-27 09:06 UTC
