### ISSUE TITLE
You can have welding helmet on without obscuring vision ?

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#73603] opened 2023-02-23 07:54 UTC
## Reproduction:

So I was working on borgs and I think I clicked fast between closing borg and turning welding helmet on. I'm honestly not sure how I did it for 100 %. I was trying to replicate but didnt manage to do it. 
*I didn't have any night vision quirk nor night vision goggles/xray/thermal eyes on me.

![hmmm](https://user-images.githubusercontent.com/116151419/220849209-fd2ad5ba-4fcb-43a0-81ea-da243398cf29.png)

**Comment by LikesGreen** [comment] 2023-02-23 10:10
It did protect me when I was welding broken borg and mech, didnt test flash

**Comment by BlueMemesauce** [comment] 2023-02-24 01:17
this happened to me sometimes before but its hard to replicate, maybe something to do with server lag

**Comment by Mothblocks** [comment] 2023-02-25 19:19
Duplicate of #52972. This is a BYOND bug with fullscreen UIs. When you get this bug, you also can't see the damage vignettes or anything.

**Closed** 2023-02-25 19:20 UTC
