### ISSUE TITLE
Canary False Fire Alarm Reports 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64431] opened 2022-01-26 02:30 UTC
## Reproduction: Have a canary a few minutes after round start 

![image](https://user-images.githubusercontent.com/84478872/151086179-ec4cbfed-73bb-4047-ba48-aa71036c224a.png)

10 Minutes into the shift all this alarms went on about the same time when I chekced the locations the atmos was fine and there were no fire alarms triggered 

This is really annoying if there is an actual fire

**Comment by NanoCats** [comment] 2022-01-26 19:39
Alarms are super fucky imho, especially when you visualize them with Canary. 

I can enter a room, the alarm is yellow light !-ing at me and nothing is wrong, it's pressurized with ideal air mix at a good temp. And yet "area atmosphere alarm!"  that I can't clear

**Comment by cacogen** [comment] 2022-01-27 03:31
#64335

**Comment by timothymtorres** [comment] 2022-10-10 13:12
Duplicate of #59043

**Closed by timothymtorres** 2022-10-10 13:12 UTC
Labels: Bug
