### ISSUE TITLE
Infinite item duplication in holodeck

### ISSUE THREAD

**Issue by Singularbyte** [tgstation/tgstation#36117] opened 2018-03-03 17:18 UTC
Round ID: 84447

It's possible to infinitely duplicate certain items in holodeck - mainly cloth and cardboard, but there may be a few others.
Essentially, if you change an item enough through crafting or similar, you can end up causing the holodeck to no longer recognise that an item belongs to it, allowing you to remove the item without it vanishing.

The best example I can give of this is cloth. If you active emergency medical, take the scalpel and cut up all the bedsheets, you get cloth. This cloth can then be removed from the holodeck and used to craft various other objects.
The same thing happens if you unfold boxes, or if you use wirecutters on the law book in the courtroom, or if you fill a container with the water from pet park etc.

The worst case of this though is the matchbox in the lounge. Simply changing holodeck map is enough to cause all of the matches to fall out of the matchbox when it vanishes.

**Comment by Jalleo** [comment] 2018-03-03 18:57
Edgecase and Fuck tags seem appropriate.

**Comment by SpaceManiac** [comment] 2018-03-03 23:05
#26258

**Comment by Jordie0608** [comment] 2018-03-04 01:59
Duplicate of #26258

**Closed by Jordie0608** 2018-03-04 01:59 UTC
Labels: In Game Exploit
