### ISSUE TITLE
People can emote in crit

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17905] opened 2016-05-24 12:14 UTC
> Duke Hayka flaps his wings.
> Duke Hayka flaps his wings.

**Comment by MMMiracles** [comment] 2016-05-24 12:54
It's the only way to get medbay to actually notice you dying in the lobby as they keep stepping over your dying body clueless.

**Comment by coiax** [comment] 2016-05-24 13:57
People can shift-click to examine, it's not difficult. But this is still a bug, helpful as it is.

**Comment by TheRealGLH** [comment] 2016-05-24 14:25
If a doctor wasn't smart enough to wear a medical HUD to be able to pinpoint whoever needs their attention the most, I wouldn't trust them with healing me in the first place.

**Comment by XDTM** [comment] 2016-05-24 19:13
Should *deathgasp be usable in crit?

**Comment by GunHog** [comment] 2016-05-24 20:09
Yes, that is one way to let yourself die, as well as triggering your explosive implants.(by dying)

**Comment by coiax** [comment] 2016-05-24 20:28
I've always just death whispered. Also explosive implants should be triggerable even in crit. I'll see what I can do about that.

**Comment by Cheridan** [comment] 2016-05-24 22:33
duplicate of #15399

**Closed by Cheridan** 2016-05-24 22:33 UTC
Labels: Bug, In Game Exploit
