### ISSUE TITLE
Tiles can have a wet overlay without actually slipping people

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#16271] opened 2016-03-21 22:46 UTC
Best observed targeting a tile several tiles away from you on the stream setting of a space cleaner sprayer

**Comment by phil235** [comment] 2016-03-22 11:19
Can't reproduce. I doubt spray cleaners have anything to do with this. What type of tiles are we talking about? Did you spray pure water? Was the tile already looking wet when you sprayed it? Were you wearing no slip shoes?

**Comment by Zilenan91** [comment] 2016-03-22 18:44
I sprayed pure water, I wasn't wearing noslips, a MD wearing white shoes walked over the tile, the tile was not wet looking when I first sprayed it, though I know for a fact it had the overlay when the MD walked over it.

**Comment by phil235** [comment] 2016-03-22 19:03
Was he walking? was he a hulk? Was he on a scooter/janicart/vehicle ? Was he a special species? Was the gravity on?

>the tile was not wet looking when I first sprayed it

So is the spray not working? Did you spray multiple times? Did it work the second time you applied it? Was there something dense or a mob in the way of the spray? How much time passed between the time the turf looked wet and the time the MD ran over it?

**Comment by Zilenan91** [comment] 2016-03-22 19:10
I sprayed using the stream setting, it was several tiles away but the wet overlay still applied. I tried spraying multiple tiles away later after the MD didn't slip on the first tiles and it actually did slip people that time.

He was a human walking on his feet with gravity on early in the round. He walked over the tile as it looked wet.

**Comment by phil235** [comment] 2016-03-22 19:33
Was the floor tile a special type? Tbh I don't see what could cause the bug outside of a runtime happening in the slip code just for the MD.

**Comment by Zilenan91** [comment] 2016-03-22 19:35
I guess it was a runtime, it was a regular floor tile.

**Comment by Cheridan** [comment] 2016-05-24 22:18
Just gonna close this, seems like a one-off runtime or something

**Closed by Cheridan** 2016-05-24 22:18 UTC
Labels: Bug, Cannot Reproduce
