### ISSUE TITLE
Z-level change can cause you to end up on the second floor on donutstation

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50027] opened 2020-03-16 23:58 UTC
## Round ID:
recent manual or bagil

## Testmerges:
The space dragon rework

## Reproduction:
0. Be on donutstation map
1. get EVA suit
2. go to edge of Z-level
3. keep going to the edge until you end up on second floor of donut

**Comment by Fikou** [comment] 2020-03-17 10:12
that doesnt seem like a bug, you travelled through space enough to find the second donut z level, the same way you can find the first one, seems like a good thing

**Comment by redguy999** [comment] 2020-03-17 12:35
what i find the main issue is that you cant go back the way you came

**Comment by Dennok** [comment] 2020-03-17 13:11
you can, just go back

**Comment by redguy999** [comment] 2020-03-17 13:13
the z-level doesnt change when on the second floor, you just get stuck.
or at least, one of the edges wouldnt let me change z-level

**Comment by MMMiracles** [comment] 2020-03-19 11:58
one does not simply escape donut

**Comment by timothymtorres** [comment] 2021-11-22 10:12
Duplicate of #58436

**Closed by timothymtorres** 2021-11-22 10:12 UTC
Labels: Bug
