### ISSUE TITLE
Monkey powder and ice inside something with body heat spawns monkeys in nullspace

### ISSUE THREAD

**Issue by ZealousZeke** [tgstation/tgstation#79483] opened 2023-11-02 20:54 UTC
Reporting client version: 514.1589

## Round ID:
[218009](https://scrubby.melonmesa.com/round/218009)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:  
Put ice and monkey powder inside of a person/monkey. 
Watch as it creates non-existent monkeys that break the monkey limit. 
Cry.
![Monkeybusiness](https://github.com/tgstation/tgstation/assets/85478781/8083a32e-e987-4c8d-9293-ca7c0573138e)

**Comment by ZealousZeke** [comment] 2023-11-02 22:56
> Does this happen if you inject someone with monkey powder and then water? Or only with ice?

probably only with ice since ice melts gradually into water, which then gradually reacts with parts of the monkey powder.

**Comment by MrMelbert** [comment] 2023-11-03 21:45
That would be because it is spawning it at your stomach's turf, and because your stomach is in nullspace - it spawns them in nullspace. 

This is a dupe of #53931, technically.

**Closed** 2023-11-06 21:06 UTC
Labels: Cleanup Flagged
