### ISSUE TITLE
The library can be used to produce INFINITE METAL

### ISSUE THREAD

**Issue by drawsstuff** [tgstation/tgstation#35685] opened 2018-02-15 02:41 UTC
Apologies, this is my first time doing anything on GitHub ever. I think I only made this so some nerd on Pokemon Showdown could acquire permission to use a sprite from me.

[Round ID]: # 83629
[Testmerges]: #35660   #35609   #35535
[Reproduction]: 
1. Go into the library on Metastation (Not sure if it works for others)
2. Use crowbar on the runed floors to acquire **INFINITE METAL** BARS
3. Tag team with the CE to weld it into plates and sacrifice all of it in the chapel because you have too much metal to do anything with.

**Comment by Buggy123** [comment] 2018-02-15 04:59
Also works with reinforced floors. #35629 should fix.

**Comment by ShizCalev** [comment] 2018-02-15 21:05
Yeah it was a subtype of /engine

**Comment by ShizCalev** [comment] 2018-02-15 21:06
Duplicate of #35280

**Closed by ShizCalev** 2018-02-15 21:06 UTC
