### ISSUE TITLE
Disposal chute doesn't take an open crate, closing it cause the chute to become a loose/detached object

### ISSUE THREAD

**Issue by TalinNPeacy** [tgstation/tgstation#66989] opened 2022-05-14 18:29 UTC
Reporting client version: 514.1583

## Round ID: [183144](https://scrubby.melonmesa.com/round/183144)
Closing a crate on the disposals chute in cargo conveyor breaks the chute and seems to make it a loose object.  Not sure if this was due to gloves or if anyone can close a crate over the chute accidentally with the "right" timing.

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Biddle Verbs: Queues the Most Expensive Verbs for the Next Tick if the Server Is Overloaded](https://www.github.com/tgstation/tgstation/pull/65589)

## Reproduction:
didn't have a way to fix the chute but basically I ran the conveyor to send things to disposals and it ate one thing but everything else after stacked on it.  I closed the lid on the crate thinking that was the issue and it just packed the chute into the crate like a loose item.

**Comment by Sealed101** [comment] 2023-03-08 16:05
i don't really understand how or what am i supposed to reproduce here. closing crates on top of the chute didn't do anything. maybe this happened due to lag as someone managed to close the crate as it just entered the chute? i have no clue

**Closed** 2024-10-22 20:20 UTC
Labels: Bug, Needs Reproducing
