### ISSUE TITLE
Deconstructing plating in icebox's lavaland box ruin causes genturf

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#69911] opened 2022-09-14 17:04 UTC
Reporting client version: 514.1585

## Round ID:
[190474](https://scrubby.melonmesa.com/round/190474)

## Testmerges:
- [Fixes weird blank in Watchlist Update Messages when adding a expiration date](https://www.github.com/tgstation/tgstation/pull/69897)
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:
1. become auxbase chadsec
2. land in lavabox ruin (MAKE AUXBASE LIKE ICE)
3. try to RCD down floor for sweet relief
4. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
![image](https://user-images.githubusercontent.com/80979251/190217823-8f7cd92e-53d9-41f0-aa02-b820443c42be.png)

**Comment by ShizCalev** [comment] 2022-09-14 18:43
Duplicate of #57449

**Closed** 2022-09-14 18:44 UTC
Labels: Mapping
