### ISSUE TITLE
Floor Tiles "NO ICON"

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#68098] opened 2022-06-30 02:24 UTC
## Testmerges:
[#67856: 'Updates the sprites for bullets (inflight), adds pellet sprites, redoes the thermal projectile sprites' by necromanceranne at commit 211dd1f01a](https://www.github.com/tgstation/tgstation/pull/67856)
[#65635: '[Ready for Review] Admin lua scripting' by Y0SH1M4S73R at commit a51246c1ab](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:
![dreamseeker-21 15 56 261](https://user-images.githubusercontent.com/85910816/176579161-3f11fc0c-8e22-4bf2-ad9d-4e88990c94b5.png)

**Comment by dragomagol** [comment] 2022-06-30 16:28
Duplicate of #67862

**Closed by dragomagol** 2022-06-30 16:28 UTC
Labels: Sprites, Bug
