### ISSUE TITLE
Some of the top left settings tabs do not work

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#37563] opened 2018-04-29 21:33 UTC
Certain buttons in the top left do not work. Some do work still.

Example:
![image](https://user-images.githubusercontent.com/6510293/39411193-cfb97e34-4bca-11e8-8fa9-de98c5f4d57f.png)
Clicking either option does not expand the menu to the additional options.

**Comment by ThatLing** [comment] 2018-04-29 21:51
Some errors related to this are printed in the "Options and Messages" window.

```
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fSize%2fverb%2ficonstretchtofit: parent element /datum/verbs/menu/Icon/Size was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fSize%2fverb%2ficon96: parent element /datum/verbs/menu/Icon/Size was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fSize%2fverb%2ficon64: parent element /datum/verbs/menu/Icon/Size was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fSize%2fverb%2ficon48: parent element /datum/verbs/menu/Icon/Size was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fSize%2fverb%2ficon32: parent element /datum/verbs/menu/Icon/Size was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fScaling%2fverb%2fNN: parent element /datum/verbs/menu/Icon/Scaling was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fScaling%2fverb%2fPS: parent element /datum/verbs/menu/Icon/Scaling was not found.
Cannot insert new element %2fdatum%2fverbs%2fmenu%2fIcon%2fScaling%2fverb%2fBL: parent element /datum/verbs/menu/Icon/Scaling was not found.
```

**Comment by PKPenguin321** [comment] 2018-04-29 21:56
Duplicate of a recent issue

**Comment by SpaceManiac** [comment] 2018-04-29 22:40
BYOND issue and duplicate of #37317

**Comment by SpaceManiac** [comment] 2018-04-29 22:40
those messages shed some light on it given that that build changed how urlencode works

**Closed** 2018-05-06 12:08 UTC
