### ISSUE TITLE
Reaction in plumbing creates empty chems and gets in reaction loop

### ISSUE THREAD

**Issue by Anko072** [tgstation/tgstation#78890] opened 2023-10-09 17:15 UTC
Complex plumbing factories breaks after some time, the more complex they are the faster they breaks. 
Sometimes there are 0 units of chem that can't be unloaded but reaction chamber tries to do that. Sometimes there are bugged reactions that keep reacting without any chems except in what they reacted into.
About week ago same layout factory worked perfectly fine without a single problem.

Round ID: [216387](https://scrubby.melonmesa.com/round/216387) and 216388

First factory:
  chemical synthesizers: welding fuel, carbon, hydrogen, chlorine, water, nitrogen, sulfuric acid, sodium, oxygen, aluminium, bromine, lithium, potassium.
  Reaction chambers: Oil, ammonia, phenol, seiver, libital, aiuri, salicylic acid, oxandrolone, salbutamol.
  press chamber with 30 units pill consists of 5units of each seiver, libital, aiuri, salicylic acid, oxandrolone, salbutamol.
(screenshot from second round because I forgot to make one in first but layout is same. Reaction chamber on the right just filters out chems for press chamber)
![Main](https://github.com/tgstation/tgstation/assets/130774093/33ef6ebb-cfbc-459f-8752-cc8298e0d466)

Bugged after 2 or 3 cycles, reaction chamber plunging helped with 0 chems for a few cycles until it broke again
Some chemical synthesizers got chemicals above 5 which I also have never seen before.
After multiple tries to make it work by plunging it, unsecuring and wrenching back and rewriting chemical reactions I tried to make simplier factory just for libital and seiver - it worked for more cycles but bugged out in similar way
![Seiver+libital](https://github.com/tgstation/tgstation/assets/130774093/eaf0b482-87de-42ce-bbac-ce7d1b9b05f9)

Tried to make my main pill factory on next map, got same problems with infinite reactions, chem synthesizers overflow and 0 chems.

![5](https://github.com/tgstation/tgstation/assets/130774093/d5af4842-00b4-4731-9d75-d8896e7f9a50)
![1](https://github.com/tgstation/tgstation/assets/130774093/3804d1c4-7652-4f01-9687-c2b29614bc4a)
![2](https://github.com/tgstation/tgstation/assets/130774093/262d94e3-0ef5-4571-b026-a46f81267a09)
![3](https://github.com/tgstation/tgstation/assets/130774093/1ebd6ecc-1343-41f0-9801-f568899242e7)
![4](https://github.com/tgstation/tgstation/assets/130774093/939571ba-5ad1-4d49-940c-58efcea17beb)
![6](https://github.com/tgstation/tgstation/assets/130774093/a4571711-68cc-4261-8e66-907e1e9ae1fa)
![7](https://github.com/tgstation/tgstation/assets/130774093/93541f71-2694-4e15-ad63-4862beebd14a)

Random clown from first round also have seen that there is something wrong with chemical reactions after I asked if I fucked something up or not(Clown didn't mention anything about plumbing though, just chemistry and phantom chemicals. I got this bug only in plumbing, basic chemistry didn't show anything unusual)

**Comment by gueba14** [comment] 2023-10-09 23:23
its also beakers reactions

**Comment by SyncIt21** [comment] 2023-10-10 03:11
So the overflow of chemical will be fixed by the above PR. The 0 unit chems is actually not a bug but an UI rounding error. Chems will now be removed only when  they fall below 0.0001 units but the UI rounds it to only  2 decimal places and displays it at 0. I'll fix that

**Closed** 2023-10-11 19:11 UTC
