### ISSUE TITLE
Monastery shuttle punches a hole in the Syndicate base's terrain on hijack

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#72419] opened 2023-01-02 10:34 UTC
Reporting client version: 514.1585

## Round ID:
[197471](https://scrubby.melonmesa.com/round/197471)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

1. monastery shuttle
2. hijack
<img width="507" alt="image" src="https://user-images.githubusercontent.com/80979251/210220083-e1f0ae7a-d786-4f28-8a54-348f92ed44fe.png">

**Comment by newfren** [comment] 2023-01-02 11:02
good

**Comment by ZephyrTFA** [comment] 2023-01-03 00:31
I personally consider this a skill issue, and not a bug

**Comment by san7890** [comment] 2023-01-03 21:56
did this even work in the first place

**Comment by Zytolg** [comment] 2023-01-25 23:06
If we mapped everything in consideration of the pubby meme shuttle, we'd have to delete Deltastation. The only way to reasonably fix this is to cordon off specific edges of the cathedral or get rid of it entirely. [Given that the latter would generate lashback the likes we've never seen,](https://tgstation13.org/wiki/Byond_the_impossible) and the former would end up obstructing players from boarding the shuttle in some creative ways, we're stuck. Meme shuttles are a mistake.

**Comment by ZephyrTFA** [comment] 2023-01-26 02:03
@san7890 considering closing this as not a bug since it's pretty much the meme of the shuttle to be super fucking large

**Comment by JohnFulpWillard** [comment] 2023-04-26 16:44
when the comically large shuttle is large

**Closed by JohnFulpWillard** 2023-04-26 16:44 UTC
Labels: Mapping
