### ISSUE TITLE
You can duplicate yourself if you crash (maybe disconnect) at round start.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28104] opened 2017-06-05 16:40 UTC
![](http://i.imgur.com/nNp3axz.png)

This player (now played on the right) crashed when the round started. When they rejoined, they had a duplicate clone of themselves  with no ckey. Both had the exact same equipment.

No idea what the exact timing and circumstances are for this.
Round ID: 71440
Server Time: 2017-06-05 16:40:21
Map: Boxstation

**Comment by Expletive** [comment] 2017-06-05 16:50
Yeah, this happens if you disconnect after the server has made you a body but before the game's started properly. The margin is pretty wide for it.

**Comment by WJohn** [comment] 2017-06-05 16:58
I've noticed that it takes upwards of 5 seconds for that to happen, so I imagine fairly easily.

Do you need to reconnect AFTER the game has started properly to get a duplicate body? Or between the body creation and game start?

**Comment by Expletive** [comment] 2017-06-05 17:00
If you disconnect before you get the body, it'll just leave it where it would have spawned you, and you'll be catatonic.  Then if you connect after the game has started, you can pick a job and get a new duplicate body. Then you can pull your old body around and make people think you're a ling, and then get lynched and cremated.

**Comment by Expletive** [comment] 2017-06-05 18:01
#26884 Is a dupe of this, too.

**Comment by BeeSting12** [comment] 2017-06-06 01:01
You can remove the reproducing/testing label, I saw this happen earlier.

**Comment by octareenroon91** [comment] 2017-06-06 03:39
>#28104
>>cat
 
 
>#26884
>>also cat

Is it a coincidence?

**Closed** 2017-06-06 18:27 UTC
Labels: Bug, Needs Reproducing/Testing
