### ISSUE TITLE
NtOS/Tgui errors

### ISSUE THREAD

**Issue by Daggertail** [tgstation/tgstation#78872] opened 2023-10-08 19:28 UTC
## Reproduction: Open tgui for anything character prefs, protolathes, get a blue NtOS error.

This issue has only recently cropped up for me, It started last round, but I was able to fix it by clearing my cache. Now I've tried clearing cache, reinstalling byond, rebooting, trying the refresh tgui buttons got nothing.

![ntos error](https://github.com/tgstation/tgstation/assets/5742277/aafb58e8-d93a-4339-bac9-17bce9b68ada)

**Comment by SyncIt21** [comment] 2023-10-09 06:07
Related #78859

@jlsnow301 maybe it's best to close this and keep #53997 as the core issue since reports like these don't give any reproduction steps and occur randomly so they might end up remaining open indefinitely.

All I can infer is if it's any bug related to assets then its an CDN issue and there is enough discussion on that in #53997 but I'm not sure.

Thoughts?

**Comment by SyncIt21** [comment] 2023-10-09 06:17
And it's not just the issue 
- #71425 
- #71412 
- #71055
- #59956

All of these share the same theme of the asset system failing due to CDN errors so it should be ok to close this along with the rest of the above issues and keep #53997 as the core issues.

Again idk just theorizing here

**Comment by jlsnow301** [comment] 2023-10-09 09:53
> All of these share the same theme of the asset system failing due to CDN errors so it should be ok to close this along with the rest of the above issues and keep #53997 at it's core

agreed. CDN issues represent a majority of the TGUI issues right now

**Closed** 2023-10-09 09:56 UTC
