### ISSUE TITLE
Holy fuck you can trap people in open closets

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#63362] opened 2021-12-11 15:36 UTC
Reporting client version: 514.1569

## Round ID:
[174606](https://scrubby.melonmesa.com/round/174606)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [documents important MC vars and procs and adds tracking of tick usage when the mc first wakes up](https://www.github.com/tgstation/tgstation/pull/63355)

## Reproduction:

1. Have 2 open closets on the same tile.
2. Throw your victim in.
3. They cannot leave without external help.
4. Laugh in shitsec.

**Comment by SuperNovaa41** [comment] 2021-12-11 15:47
Duplicate of https://github.com/tgstation/tgstation/issues/63095

**Closed by SuperNovaa41** 2021-12-11 15:47 UTC
