### ISSUE TITLE
Slappers Breaking windows.

### ISSUE THREAD

**Issue by Jcenderion** [tgstation/tgstation#32138] opened 2017-10-26 22:32 UTC
Issue reported from Round ID: 77982 (Sybil)

So I decided to mess with slapper and found they can break windows on harm intent, not sure how this can be fixed in the code but just reporting it, it could allow inmates to break out of perma or something with nothing else on them but their arms.

**Comment by PKPenguin321** [comment] 2017-10-26 22:59
Duplicate issue

**Comment by Anonmare** [comment] 2017-10-26 23:09
Could we fix this with object deflection?

**Comment by PKPenguin321** [comment] 2017-10-26 23:21
Slappers just shouldn't have force

**Comment by Cyberboss** [comment] 2017-10-27 14:21
@PKPenguin321 what's the dupe issue #?

**Comment by PKPenguin321** [comment] 2017-10-27 21:49
@Cyberboss https://github.com/tgstation/tgstation/issues/31786

**Comment by Cyberboss** [comment] 2017-10-27 22:20
Duplicate of #31786

**Closed by Cyberboss** 2017-10-27 22:20 UTC
