### ISSUE TITLE
Brain Surgery gives incorrect feedback

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#63110] opened 2021-11-27 20:14 UTC
## Round ID: 
It was a couple of days ago, but this is easy to reproduce

## Reproduction:
- Have someone with (or maybe without) brain damage;
- Do Brain Surgery on them

Currently, when you do brain surgery and the brain is fully healed, it will still tell you "[target]'s brain looks like it could be fixed further.". I have honestly not tested this enough, but I have only noticed this happen to corpses, so it may be a dead-related bug.

------
![image](https://user-images.githubusercontent.com/42555530/143720937-c6b43c27-c00d-4b84-b34d-d616fa79f1d0.png)

![image](https://user-images.githubusercontent.com/42555530/143720940-010b6e6e-91f8-4b02-9c69-d9a51c64000b.png)

**Comment by SuperNovaa41** [comment] 2021-11-27 20:29
Duplicate of #62576

**Comment by Justice12354** [comment] 2021-11-28 02:09
@SuperNovaa41 That issue says you are not notified when there is more to fix ("it doesn't notify you when there's more to fix").
In my issue, I explain how you are notified when there is no more to fix. I'm afraid they're not duplicates. Also, I think that issue may have been fixed, since I am notified of when there's more to fix.

**Closed** 2021-12-02 20:13 UTC
