### ISSUE TITLE
Still see revolution HUD after deconversion

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#63295] opened 2021-12-07 19:54 UTC
## Round ID:
Will fill in later today

## Testmerges:
Will fill later today

## Reproduction:
Died earlier in the round as a revolutionary, with catastrophic burns to head. Got revived later and eventually stun baton and mind shielded. Got up and went to get ID from hop as before I had none. Walked by a head rev and realized I could still see the revolutionary hud, with no symbol above myself.

**Comment by Mooshimi** [comment] 2021-12-07 19:56
Any additional info the other person you mentioned had this bug gave? @Mothblocks

**Comment by ProfessorSniff** [comment] 2021-12-07 20:04
possible duplicate of #63113 with different reproduction steps?

**Comment by TheBonded** [comment] 2021-12-07 21:23
Seems like this is the same bug as #63113 but caused in different circumstances

**Comment by Mothblocks** [comment] 2021-12-08 02:23
One of the dudes I talked to said that they got deconverted while dead, which I think should be an easy case to look at.

**Comment by Mothblocks** [comment] 2021-12-08 02:40
Dying + mindshielding works. Another thing I noticed is ghosting out keeps the HUDs, which was not intentional, and likely a clue.

**Comment by Mothblocks** [comment] 2021-12-08 02:41
It means one thing, at the very least--`/datum/antagonist/Destroy()` isn't being called, otherwise the team HUD would be deleted.

**Comment by Mothblocks** [comment] 2021-12-08 02:44
Nevermind, I lose the effect when I go back into my body, this sucks.

**Comment by Mooshimi** [comment] 2022-11-13 03:00
Manley Jyllian experienced this bug round 194226 today

**Comment by MrMelbert** [comment] 2024-02-07 19:53
Dupe of #77530 , Keeping that one open because I just dumped information in it

**Closed by MrMelbert** 2024-02-07 19:53 UTC
Labels: Bug, Needs Reproducing
