### ISSUE TITLE
Initializations are accidentally causing time paradoxes

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35434] opened 2018-02-08 00:02 UTC
![image](https://user-images.githubusercontent.com/16315400/35948203-74d0561c-0c39-11e8-8e44-2b9b2ff546a0.png)
roundid: 83245

**Comment by YPOQ** [comment] 2018-02-08 00:30
Looks similar to #26156 but I'm not sure

**Comment by AnturK** [comment] 2018-02-08 08:53
Duplicate of #26156

**Closed by AnturK** 2018-02-08 08:53 UTC
Labels: Bug
