### ISSUE TITLE
-Duplicate Issue-(Delete)

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#26588] opened 2017-04-25 21:53 UTC
I joined the server late and was unable to understand languages. I sent some PDA messages to talk to others to ensure this wasn't just a stupid admin event, and it appeared not to be. Clicked the language tab and it appeared I didn't know anything.

Chatlog upon joining the round is below:
[Common] Automated Announcement System coldly states, "Iszao guo oulhamiuminheng thwaedchu ru"
Jayne Staymates says, "Forkui"
[Common] Jorge Seelig says, "Sheng"
Jayne Staymates says, "Saime teris"
Gene Ball makes a strange sound.
Jayne Staymates says, "Onion thi"
[Common] Tancred Of Galilee says, "Th waisre. Anourou"
Gene Ball makes a strange sound.
[Common] Leo Demuth says, "Vechua"
[Common] Rebecca Lee says, "All"

**Comment by Bawhoppen** [comment] 2017-04-26 06:23
More info? Were you a human? Antag? Anything else

**Comment by Nabski89** [comment] 2017-04-26 13:28
Yes I was human. No I was not antag.

I late-joined another round in the evening and had it happen again.

I Ahelped it and they commented that latejoins seemed to not be getting languages. Think it was Cobby/Cedar who fixed it. I don't remember.

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-04-26 15:43
What did I do.... hm....

**Comment by Nabski89** [comment] 2017-04-26 22:34
It didn't do it today, so if I could just uhhh, close this and assume it was the round.

**Comment by coiax** [comment] 2017-04-27 10:28
This is a dupe of an existing issue. I don't know why this would happen, granting languages to ghosts runs in their `Initialize`, and nothing changes them after.

**Closed** 2017-04-27 13:06 UTC
