### ISSUE TITLE
Halloween darkness filter is far to strong

### ISSUE THREAD

**Issue by Blacklist897** [tgstation/tgstation#79324] opened 2023-10-27 22:39 UTC
## Testmerges:
[#78857: 'Makes lighting objects objects again' by LemonInTheDark 
[#79316: 'Extends Halloween' by Jacquerel 
 
the lighting filter is overtuned to the point where lavaland and dark rooms are dark to the point of being unplayable even with light sources
 
![058fc39851ee3107dadea3eafd5ccbf9](https://github.com/tgstation/tgstation/assets/149209377/dfc8bb8e-49bc-4e35-ab3b-69bd11a4d600)

![image](https://github.com/tgstation/tgstation/assets/149209377/b60eca7d-2210-4e29-a40f-0304d4939156)

## Reproduction: Go to lavaland or any slightly dark room

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug, Cleanup Flagged
