### ISSUE TITLE
Scooped mice and other pets are view as clothing and can be eaten by moths

### ISSUE THREAD

**Issue by onjec** [tgstation/tgstation#54530] opened 2020-10-21 20:43 UTC
Issue reported from  Round ID: [148795](https://scrubby.melonmesa.com/round/148795) (/tg/Station - Terry [EU] [100% LAG FREE])

Reporting client version: 513.1532

scooping a mouse or any other pet and holding it in your invetory will make the game view the mouse as piece of clothing so the game lets you try to equip it which will fail but it will allow moths to eat the mouse and damage it this way,
![Untitled](https://user-images.githubusercontent.com/59801464/96784815-41156f00-13ee-11eb-8b70-9ba1df6de123.png)
 if you damage the mouse enough it will become shredded and the object name will change to "shredded bugged mob" they will revert to their normal mob form if droped though.
![Untitled2](https://user-images.githubusercontent.com/59801464/96785103-9baecb00-13ee-11eb-879b-a735b9ac1754.png)
this seems to be a problem with the code assigning scooped mobs the clothing tag for some reason thus allowing the moths to eat them.

**Comment by ATH1909** [comment] 2020-10-21 21:32
we know

**Comment by ATH1909** [comment] 2020-10-21 21:33
also, completely eating the mob holder will drop the mob inside of it without harming it.

you can still spook the HoP, though.

**Comment by ATH1909** [comment] 2020-10-21 21:34
https://github.com/tgstation/tgstation/issues/50371

**Comment by msgerbs** [comment] 2020-10-22 00:02
> 
> 
> also, completely eating the mob holder will drop the mob inside of it without harming it.
> 
> you can still spook the HoP, though.

Beautiful.

Sadly, duplicate of #50371

**Closed by msgerbs** 2020-10-22 00:02 UTC

**Comment by ATH1909** [comment] 2020-10-22 01:16
to be fair, #50371 was made months ago and has pretty much been buried.

on the other hand, I like this bug and would prefer it if it wasn't fixed just yet.

**Comment by msgerbs** [comment] 2020-10-22 03:02
That's true, but ideally we only want 1 issue per... issue. Otherwise you have to search through 1700 issues to find any other issues that are duplicates when you close one.
