### ISSUE TITLE
You're always marooned on the station

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34954] opened 2018-01-25 21:55 UTC
https://atlantaned.space/statbus/round.php?round=82539

I made it out, but end round window said I was marooned

**Comment by praisenarsie** [comment] 2018-01-25 22:02
@ninjanomnom

**Comment by ninjanomnom** [comment] 2018-01-25 22:04
I'm not sure why I was pinged here, this is most likely an issue with z level traits.

**Comment by praisenarsie** [comment] 2018-01-25 22:26
i thought it was shuttle related but ok

@SpaceManiac

**Comment by SpaceManiac** [comment] 2018-01-26 00:12
This has been happening since the roundend report refactor which went in before z traits. This is a dupe but I don't have the previous issue # on hand.

**Comment by SpaceManiac** [comment] 2018-01-26 00:46
Duplicate of #33520

**Closed** 2018-01-26 08:48 UTC
Labels: Bug, Priority: High
