### ISSUE TITLE
This specific cryo cell is not working on Wawastation

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84014] opened 2024-06-15 15:43 UTC
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/434f179b-7ef5-492a-9e0a-fba0ece121dc)
The one on the left works fine as intended, but the one on the right: Can't insert a beaker, can't open the interface, but can alt click to open and close the door.

## Round ID:
[230578](https://scrubby.melonmesa.com/round/230578)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
1. Load Wawastation
2. Try using this Cryo cell

**Comment by GoblinBackwards** [comment] 2024-06-15 16:20
Seems to be happening because of this, get_turf_pixel is returning the upper tile of the cryocell since its an even height which means get_turf_pixel defaults to the north turf.
https://github.com/tgstation/tgstation/blob/bce2c0f181a2dba71c681a6292992a7cda6c5a2c/code/_onclick/click.dm#L177-L187

**Comment by SyncIt21** [comment] 2024-06-15 16:27
You just reported this a few days ago #83890

**Comment by MrMelbert** [comment] 2024-06-15 16:30
Dupe of #80983

**Closed by MrMelbert** 2024-06-15 16:30 UTC

**Comment by Sadboysuss** [comment] 2024-06-15 17:45
> Dupe of #80983

it's not, The cryo cell to the left works as intended while the cryo cell to the right does not.
