### ISSUE TITLE
Both regular and tagger graffitis SUCK

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#71841] opened 2022-12-08 14:28 UTC
## Round ID:
[195881](https://scrubby.melonmesa.com/round/195881) (most recent atm, the issue appeared like 2-3 days ago)

## Reproduction:
Appraise a graffiti. Wow, it sucks.

**Comment by Serxule** [comment] 2022-12-08 17:17
already a fix thats been up for a while https://github.com/tgstation/tgstation/pull/71760

**Comment by Dorsisdwarf** [comment] 2022-12-09 10:57
Dupe of #71688

**Closed by Dorsisdwarf** 2022-12-09 10:57 UTC
Labels: Bug
