### ISSUE TITLE
Disassembling Booze-O-Mat yields no machine board

### ISSUE THREAD

**Issue by IanAbstract** [tgstation/tgstation#52877] opened 2020-08-11 19:38 UTC
Issue reported from  Round ID: [144043](https://scrubby.melonmesa.com/round/144043) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1528

When dissasembling the booze-o-mat, no machine board drops when you use a crowbar on it so you cannot put it back together. Also, there is no booze-o-mat vending board in the service protolathe, which may be an oversight.

**Comment by TemporalOroboros** [comment] 2020-08-11 20:13
This is an extension of #52860 and should be fixed by  #52871

**Comment by Time-Green** [comment] 2020-08-11 20:36
Duplicate of #52860

**Closed by Time-Green** 2020-08-11 20:36 UTC
