### ISSUE TITLE
Wallening - Power cable under catwalk invisible when cover removed

### ISSUE THREAD

**Issue by loganuk** [tgstation/tgstation#85720] opened 2024-08-09 22:26 UTC
## Issue Summary

When using a multi tool to check for wires cut or just power load - The current view is this:
![image](https://github.com/user-attachments/assets/58f737eb-497c-4375-8157-b0c4e0074df2)
When you unscrew the catwalk the wire turns invisible - Alt CLICK on the tile reveals the cable is still there - As far as a player is concerned the cable is  invisible. I'd also suggest visually cables and pipes should sit under the catwalk as they were pre-wallening. Mainly created as an issue because can see players getting immensely confused about why they cannot re-lay or check a cable.

On a lot of newer maps catwalks are heavy part of pipe layouts and power wiring in maints.

![image](https://github.com/user-attachments/assets/ed1dc231-af33-4fe8-bd29-15eb15e7538f)

You can reveal it by removing the disposal piping which conceals it - So might be the layering ordering is a little off.

![image](https://github.com/user-attachments/assets/b4876f19-c33c-4087-b402-7c88502a611e)

/turf/open/floor/catwalk_floor

## Round ID:

Spotted on Terry - Tested locally with Wallening.

## Reproduction:

Go to a catwalk tile with cable under it

Unscrew catwak

Be inspired as the once bright visible cable vanishes.

**Comment by Sadboysuss** [comment] 2024-08-10 01:39
It's layering under the disposals pipe
Dupe of https://github.com/tgstation/tgstation/issues/85714

**Comment by DATA-xPUNGED** [comment] 2024-08-11 22:28
As Sadboysuss said, this is a duplicate.

**Closed by DATA-xPUNGED** 2024-08-11 22:28 UTC
