### ISSUE TITLE
Aiming is broken

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#64153] opened 2022-01-16 04:24 UTC
Round ID: [176670](https://scrubby.melonmesa.com/round/176670)

Reproduction: https://streamable.com/1qed19

Aim at something, and the bullet travels away from where you're aiming (sometimes a complete 180 degrees as if you have stormtrooper aim). Most seen when you're shooting right against a wall/point black at something, but as in the first clip it happens in other situations too.

**Comment by Mothblocks** [comment] 2022-01-16 05:01
Duplicate of #64130

**Closed by Mothblocks** 2022-01-16 05:01 UTC
