### ISSUE TITLE
Mining Camp Point Console Doesn't Get Points from Stacking Machine

### ISSUE THREAD

**Issue by Ledwin1233** [tgstation/tgstation#40212] opened 2018-09-10 14:23 UTC
Issue reported from  Round ID: 93707 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Essentially leaves you stuck on the prisoner lavaland camp.

**Comment by AlexTheSysop42** [comment] 2018-09-10 14:55
Did you put the refined materials in?

**Comment by Potato-Masher** [comment] 2018-09-10 18:39
Archaic code strikes again. The machine will give you points if you drop the refined minerals next to the stacker, but not when using it on the machine itself.

Still technically works, but everything about the gulag needs updating tbh.

**Comment by SpaceManiac** [comment] 2018-09-11 02:53
Duplicate of #39506

**Closed by SpaceManiac** 2018-09-11 02:53 UTC
Labels: Consistency Issue
