### ISSUE TITLE
Legions are moving slower then usual, and their head attack is hiding behind player sprites.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#64265] opened 2022-01-20 03:43 UTC
## Round ID:
176911

## Testmerges: 
#64144: 'Adds Thieves, a very low level antagonist.' by tralezab at commit 76cfe95bb3

## Reproduction: 
1. Fight any legion on lavaland. 2. Watch their movement be weird, their ai might not even comprehend the attack and do anything at all, or they'll start moving slowly. 3. When they shoot their head attack, they move super fast and will hide behind your sprite, staying behind your sprite even when you move away from them. Making them impossible to hit.

**Comment by LemonInTheDark** [comment] 2022-01-20 03:57
Skulls moving faster is the result of move loops being used over walk_to I believe. It's strange, because the delay for skulls is literally 1 decisecond, and I think always has been. Not sure why they were moving slower in the past though.

The rest of what you're talking about is I think just the result of layering when moving? some examples would be useful.

**Comment by Serxule** [comment] 2022-01-20 07:30
> The rest of what you're talking about is I think just the result of layering when moving? some examples would be useful.

i can confirm, it happens with every simplemob that can be walked onto(?) (im not actually sure, i've only seen it with stuff like this), like a mouse, etc, it will stand DIRECTLY on your tile, being under you, instead of next to you on a tile, making it **_literally_** impossible to hit

**Comment by Serxule** [comment] 2022-01-20 07:32
also adding onto this, things like goliaths dont walk anymore, they only use their tentacle attack instead of moving towards you, and goliaths dont slow you down when pulling anymore (maybe that was changed?)

**Comment by LemonInTheDark** [comment] 2022-01-20 07:59
> i can confirm, it happens with every mob that can be walked onto(?) (im not actually sure, i've only seen it with stuff like this), like a mouse, etc, it will stand DIRECTLY on your tile, being under you, instead of next to you on a tile, making it **_literally_** impossible to hit

Oh that explains a lot actually. FIx is also pretty simple, thank you for mentioning it

**Comment by LemonInTheDark** [comment] 2022-01-20 08:00
> also adding onto this, things like goliaths dont walk anymore, they only use their tentacle attack instead of moving towards you, and goliaths dont slow you down when pulling anymore (maybe that was changed?)

They move a tile every 4 seconds. It's not great

**Comment by Serxule** [comment] 2022-01-20 08:12
goliaths: https://youtu.be/3o0d0gdPRzI 
legion: https://youtu.be/hZbCbXUwORw

**Comment by LemonInTheDark** [comment] 2022-01-20 08:37
Aight, pushed a fix for skulls trying to move to your tile, rather then the one next to you

**Comment by Serxule** [comment] 2022-01-20 09:15
> Aight, pushed a fix for skulls trying to move to your tile, rather then the one next to you

it also happens with mice, and likely other mobs that can go on a playertile, which i dont know how many there are _(oh god if bees can do it)_

**Comment by LemonInTheDark** [comment] 2022-01-20 09:39
Yeah, it was an issue with how I was detecting range.
Something like
Before a move, if we're further or equal to X distance, keep moving,
If the distance was 1, this was just "Move until you hit one, and then once more", or moving onto the target's tile.

Fixed now

**Closed** 2022-01-22 07:57 UTC
Labels: Bug
