### ISSUE TITLE
Opening and closing an interface makes it inaccessible

### ISSUE THREAD

**Issue by Spess-Rando** [tgstation/tgstation#35714] opened 2018-02-16 07:48 UTC
https://gfycat.com/CrazyPowerlessJenny

**Comment by Jalleo** [comment] 2018-03-19 22:35
Does this still occur @Slignerd

**Comment by XDTM** [comment] 2018-03-25 15:50
needs reproducing

**Comment by PKPenguin321** [comment] 2018-03-25 19:54
Happens to me sometimes with no apparent cause. Can happen with seemingly any tgui window, including the crafting menu, geneticist consoles, bar chem dispensers, sleepers, and vending machines. Can be fixed by reconnecting by going to File -> Reconnect. If it occurs with a machine, it is specific to that particular machine (IE, if you can't access one particular sleeper, other sleepers should still operate properly).

**Comment by Incomptinence** [comment] 2018-04-12 01:11
This bug has happened to me several times.
Reconnects fix it temporarily.

**Comment by MrStonedOne** [comment] 2018-06-25 06:50
@neersighted

**Comment by Cyprex** [comment] 2018-07-06 21:42
Copying my comment from the duplicate issue here:
I was able to work around (most of?) these cases by moving out of range of the machine to the point where the gui would automatically close. For tablets, that meant putting them into a backpack. Afterwards I was able to open the interface again without problems. Is the interface possibly being closed on the client, but not the server?

**Comment by kriskog** [comment] 2019-07-20 01:09
Still happening once in a while, as described by Cyprex.

**Comment by Cyprex** [comment] 2019-07-20 01:57
I get this frequently, like once every round or so, possibly due to being on Linux/Wine/IE8

**Comment by actioninja** [comment] 2019-11-15 01:26
Likely related to #47755 closing and linking there

**Closed by actioninja** 2019-11-15 01:26 UTC
Labels: Bug, UI
