### ISSUE TITLE
Blob spores taking control of the body you laid an egg in as a changeling headslug will be broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31258] opened 2017-10-03 07:13 UTC
![](https://i.imgur.com/5IFvlOe.png)

If you lay an egg inside a corpse as a changeling headslug, then the corpse is taken over by a blob spore, you wake up with a blob spore on your head. If the blob zombie is killed, you leave no body behind, only your organs and limbs.

This does not happen to a regular changeling who already has control of a body, died, and started reviving but was taken over by a blob zombie, although reviving themselves will not give them control back.

**Comment by Armhulen** [comment] 2017-10-03 14:59
Dupe of something!

**Comment by ma44** [comment] 2017-10-04 19:08
Probably a dupe of #27757 , as #29213 was closed because of that

**Comment by timothymtorres** [comment] 2022-08-09 23:40
Duplicate of #49543

**Closed by timothymtorres** 2022-08-09 23:40 UTC
Labels: Bug
