### ISSUE TITLE
The song editor doesn't update properly on pianos/space minimoogs.

### ISSUE THREAD

**Issue by sergeirocks100** [tgstation/tgstation#64516] opened 2022-01-28 21:12 UTC
## Round ID:

none, this was on a local instance

## Reproduction:

Use the piano/spaceminimoog.

Watch as the UI doesn't update when you click most of the buttons, and you have to close and reopen the window for the changes to show up.

**Comment by sergeirocks100** [comment] 2022-01-29 22:19
This is the runtime it shits out when i click one of the buttons:
`[17:17:51] Runtime in asset_transport.dm,87: Invalid argument: client: ``
  proc name: send assets (/datum/asset_transport/proc/send_assets)
  usr: Sergeirocks100/(Roams-The-Forest)
  usr.loc: (Theater (145,127,2))
  src: Simple browse_rsc asset transp... (/datum/asset_transport)
  call stack:
  Simple browse_rsc asset transp... (/datum/asset_transport): send assets(null, /list (/list))
  /datum/asset/simple/namespaced... (/datum/asset/simple/namespaced/common): send(null)
  /datum/browser (/datum/browser): open(1)
  Untitled (/datum/song): ui interact(null)
  Untitled (/datum/song): updateDialog(null)
  Untitled (/datum/song): Topic("src=\[0x21013c5a];tempo=-0.5", /list (/list))
  Sergeirocks100 (/client): Topic("src=\[0x21013c5a];tempo=-0.5", /list (/list), Untitled (/datum/song))
  Sergeirocks100 (/client): Topic("src=\[0x21013c5a];tempo=-0.5", /list (/list), Untitled (/datum/song))
`

**Comment by timothymtorres** [comment] 2022-01-31 19:27
Duplicate of #63646

**Comment by timothymtorres** [comment] 2022-02-17 10:52
This was fixed by #64545

**Closed by timothymtorres** 2022-02-17 10:52 UTC
