### ISSUE TITLE
Changing to a plasmaman to a human as a ling leaves the toxins message up

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31732] opened 2017-10-14 22:29 UTC
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by swindly** [comment] 2018-11-27 23:51
Dupe of https://github.com/tgstation/tgstation/issues/29360?

**Comment by timothymtorres** [comment] 2021-08-20 14:54
I'm certain this is due to polymorph/shapeshifting code not resetting traits when you change your mob type.

**Comment by timothymtorres** [comment] 2021-08-20 14:54
Duplicate of #40040

**Closed by timothymtorres** 2021-08-20 14:54 UTC
Labels: Bug, Consistency Issue
