### ISSUE TITLE
C4 screwdrivering doesn't work

### ISSUE THREAD

**Issue by drynwyn** [tgstation/tgstation#19557] opened 2016-07-28 17:24 UTC
Using a screwdriver on C4 doesn't open the wires menu to reveal the Boom wire as intended- it does nothing at all.

**Comment by TechnoAlchemisto** [comment] 2016-07-30 03:48
This issue gets brought up every week. C4 got repathed to a grenade path, so you attack assemblies to it instead of screwdriving, however it is buggy and lacks much of the functionality of the original path (which is still in the game and working, those c4 are still on the nuke op shuttle) 

I made a PR changing the path to the old one which worked just dandy but it was closed because I was expected to troubleshoot the bug instead of making a feature work as it should.

**Comment by optimumtact** [comment] 2016-12-15 05:53
if it's not a bug you close the issue dorsi

**Closed by optimumtact** 2016-12-15 05:53 UTC
Labels: Consistency Issue, Not a bug
