### ISSUE TITLE
Cult blood spear / blood halberd isn't captured by hand when recalled with "bloody bond"

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#46096] opened 2019-08-23 14:15 UTC
Might as well report this old one as well. 
#### Round ID:
Locally. Been this way a couple of months at least but didn't report until now. 

The blood spear used to get wielded by your hand automatically when you recall it. Now it just lands under your feet. Having throw mode active makes no difference.

**Comment by Sealed101** [comment] 2023-08-26 18:18
can't reproduce - works fine when standing still or moving towards the halberd and moves to your old turf when moving away from it as expected

**Closed by Sealed101** 2023-08-26 18:18 UTC
Labels: Bug
