### ISSUE TITLE
Pixel Scaling setting doesn't save

### ISSUE THREAD

**Issue by Kelenius** [tgstation/tgstation#51283] opened 2020-05-25 15:26 UTC
## Round ID:

N/A

## Reproduction:

Start a round, change Pixel Scaling to Pixel Perfect x2, specifically click on "Save Setup". Next round it's back to default.

**Comment by Time-Green** [comment] 2020-05-25 15:59
Duplicate of #51273

**Closed by Time-Green** 2020-05-25 15:59 UTC
