### ISSUE TITLE
Pod Computers GPS overlay renders for some reason

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#73045] opened 2023-01-29 10:50 UTC
Reporting client version: 514.1589

## Round ID:
[199137](https://scrubby.melonmesa.com/round/199137)

## Testmerges:
- [Don't initialize stack components inside machines](https://www.github.com/tgstation/tgstation/pull/72863)

## Reproduction:

1. use bluespace shelter capsule
2. remove bedsheet
3. 
![image](https://user-images.githubusercontent.com/70376633/215321194-6f2cde49-7147-497c-91b4-acb022e605a5.png)

**Comment by wulfenbach-jpg** [comment] 2023-02-01 23:34
Duplicate of #69607
- #69607

**Closed** 2023-02-02 05:43 UTC
