### ISSUE TITLE
Engiborgs Pseudo circuit doesn't work

### ISSUE THREAD

**Issue by lightcat** [tgstation/tgstation#38260] opened 2018-06-03 04:27 UTC
Airlocks can't be build using them, probably should update the description or fix it.

**Comment by 81Denton** [comment] 2018-06-03 07:39
The airlock part is intended (iirc due to code limitations?), you'll have to use the RCD for it. Let me test the other uses real quick

**Comment by 81Denton** [comment] 2018-06-03 08:00
Works with APCs/air alarms/firelock/fire alarm on Revision: 8e692e6c02786b7b8e605b942d1568af5387abed

**Comment by lightcat** [comment] 2018-06-03 14:16
Here I've updated the description to be more accurate.

**Comment by factoryman942** [comment] 2018-06-03 16:34
according to #31018 not a bug @SpaceManiac

**Comment by AlexTheSysop42** [comment] 2018-06-03 17:09
It still affects windoors but is a dupe of #31047

**Closed** 2018-06-03 19:47 UTC
Labels: Needs Reproducing
