### ISSUE TITLE
Virology - Mutagenic Agar not mixing as expected

### ISSUE THREAD

**Issue by ElfLeaderMike** [tgstation/tgstation#23798] opened 2017-02-07 00:24 UTC
**Problem Description:** When mixing 1u of Mutagenic Agar virus reactions don't occur. This only seems to happen if you make the base mix using 5u beakers.

**What did you expect to happen:** When I add 1u of a virology chemical, I expect the solution to bubble and a symptom to be added.

**What happened instead:** The reaction doesn't occur, when I mix with larger amounts (2u+), the solution bubbles twice and I get 2 symptoms.

**Why is this bad/What are the consequences:** Makes it harder to isolate symptoms, and it definitely isn't intended behavior.

**Steps to reproduce the problem:**
Round start, I grab all of the base modifier chemicals from the fridge, and then set them all to 5u transfer.
Fill up a fresh beaker with Virus Food and set it to 5u transfer
Then mix 5u of Virus Food and 5u of Unstable mutagen to get Mutagenic Agar
Take 1u of Cold virus using a dropper and put it in a fresh beaker.
Then 1u of Mutagenic Agar in the dropper and put it in that beaker.
I expect the solution to mix, but it does not. If you add another drop it will bubble twice as if you had mixed twice.

**Server:** Bagil

**Revision:** 0d3cb5fcaf81f5bb54982afee46d9c649c77a607 

**Possibly related stuff :** I've tested all the chemicals I could and here are the results either "Works" or "Bugged"
Unstable Mutagen - Works
Liquid Plasma - Works
Synaptizine - Works
Virus Food - Works
Mutagenic Agar - If I mix two chemicals with 5u beakers, the 1u dropper doesnt work. If I mix it using a 1u dropper or 10u, then pulling 1u from the beaker works fine.
Virus Plasma - Works
Weakened Virus Plasma - Works
Virus Rations - Works

Also in a extremely inconsistent twist, I tried mixing the two 5u beakers one last time to make Mutagenic Agar and it worked as expected, something fucky is definitely happening but I'm not sure why its so inconsistent. This has happened 2 rounds in a row so there's definitely a bug somewhere, it is not a one time thing.

**Comment by XDTM** [comment] 2017-02-07 00:35
This is something i've had happening rarely; for some reason some chems end up as 0.999 instead of 1 requiring two drops to use.

**Comment by timothymtorres** [comment] 2021-08-20 08:57
> This is something i've had happening rarely; for some reason some chems end up as 0.999 instead of 1 requiring two drops to use.

I've had similar issues related to this and this ONLY tends to happen when I work virology.

**Comment by timothymtorres** [comment] 2021-08-20 09:33
Duplicate of #23798

**Closed by timothymtorres** 2021-08-20 09:33 UTC
Labels: Bug, Higgs-Bugson
