### ISSUE TITLE
Cant be dragged after being killed by a powerfist

### ISSUE THREAD

**Issue by TheAutism** [tgstation/tgstation#23337] opened 2017-01-26 01:33 UTC
I was unable to drag someone killed by a power-fist. The gravgen was off and i'm pretty sure the power-fist was at full power. I asked another onlooker to try and drag the body, but they also were unable to drag them as well. I could still hit the body and open the menu to strip them. When i was inevitably killed by the power-fist as well, people also had trouble dragging me, but it seems they were able to put me in a body bag though. Oddly enough when i was being hit by it it didn't send me flying like power-fists normally do. I'm not sure if it was being killed by the fist or simply hit by it that caused the glitch, although i am fairly certain that the power-fist cause the problem

**Comment by Cyberboss** [comment] 2017-01-26 05:12
Dupe of #22992

**Closed** 2017-01-26 05:22 UTC
