### ISSUE TITLE
Entertainment Screens Do Not Work

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#68333] opened 2022-07-10 21:42 UTC
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Click on an entertainment monitor, and nothing happens.

I actually know what the problem is. They have their interaction_flags_atom set to NONE, according to the comments to circumvent a chain of click checks, to allow normal humans do look at the console from a distance. This is a clever solution, but the issue is, interact has been given a check to see if `interaction_flags_atom & INTERACT_ATOM_UI_INTERACT` is true, before sending an ui_interact signal and calling ui_interact.

However, I don't know how to solve this properly, I was thinking about making the telescreen directly call ui_interact, but then we would be missing out on everything related to interact.

**Comment by ArcaneDefence** [comment] 2022-07-10 22:23
Duplicate of https://github.com/tgstation/tgstation/issues/54607

Relevant conversations involved in https://github.com/tgstation/tgstation/pull/60431
https://github.com/tgstation/tgstation/pull/56970

**Closed by ArcaneDefence** 2022-07-10 22:23 UTC
Labels: Bug
