### ISSUE TITLE
Possible bug with syndicate bomb timers

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#28881] opened 2017-06-27 20:12 UTC
Maxing out the bomb timer with 99999999 shows the timer set for 60000 seconds (ten minutes), but for some reason causes it to explode only 10-20 seconds later.
![bug](https://user-images.githubusercontent.com/29739454/27607829-3e21a3d8-5b53-11e7-99ec-18265152f243.PNG)

**Comment by Tacolizard** [comment] 2017-06-28 15:41
that is... weird. I mean I don't know much about BYOND but I have no clue why that would ever happen.

**Comment by Jalleo** [comment] 2017-07-24 09:31
@MrStonedOne any ideas why this is?

**Comment by ShizCalev** [comment] 2017-09-06 17:48
Can't seem to reproduce this. Setting the timer clamps it properly to 60000 seconds, which sets the bomb's detonation_timer (which is world.time + the timer offset.)

**Comment by vuonojenmustaturska** [comment] 2017-09-14 17:18
I've tried to reproduce this several times using different approaches, not limited to the one listed in the bug report. I cannot reproduce this bug. It's possible for another player to set the timer to 90 after you've set it to 60k, but even then there's a message with the real timer.

Is it possible that another player tried to hack the bomb while you were jetpacking? Pulsing the "proceed" wire will cut the timer to 60 seconds if it's above that, and every pulse after that will cut the timer with 10 seconds to a floor of 10.

Is it possible for AI to hack syndie bombs?

**Comment by ShizCalev** [comment] 2017-09-14 17:20
AI / silicons can't interface with bombs.

**Comment by ma44** [comment] 2017-09-14 17:21
Can possibly be the big red button item.

**Comment by vuonojenmustaturska** [comment] 2017-09-14 17:23
There'd be an admin notice about that, but no round id was supplied

**Comment by ma44** [comment] 2017-09-14 17:25
@OmegaShoots Any idea on what round ID it happened on? If you don't know, provide a date and possible time of when the round happened.

**Comment by praisenarsie** [comment] 2017-09-14 17:27
also tell us if this was downstream too

**Comment by praisenarsie** [comment] 2017-09-14 17:30
https://i.imgur.com/xehe6Eg.png

**Comment by vuonojenmustaturska** [comment] 2017-09-14 17:31
@KorPhaeron close it

[19:50:26]GAME: Alexch2/(Wendy Rader) has remotely detonated a syndicate bomb using a big red button at Starboard Primary Hallway(169,129,2)
[19:50:33]GAME: The syndicate bomb that OmegaShoots/(I Will End You) had primed detonated!
[19:50:33]GAME: Explosion with size (3, 9, 17, 17) in area Space (224,107,4)
[19:50:33]ACCESS: Mob Login: OmegaShoots/(I Will End You) was assigned to a /mob/living/brain
[19:50:33]ACCESS: Mob Login: OmegaShoots/(I Will End You) was assigned to a /mob/dead/observer

**Closed** 2017-09-14 17:32 UTC
Labels: Bug, In Game Exploit, Priority: High

**Comment by OmegaShoots** [comment] 2017-10-20 10:15
huh
was weird because I had thought we killed all the nuke ops that round at that point
