### ISSUE TITLE
Can't use department radio on headsets when implanted with an internal radio implant

### ISSUE THREAD

**Issue by qbmax32** [tgstation/tgstation#36981] opened 2018-04-04 23:16 UTC
Issue reported from  Round ID: 86069 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

A player earlier was having difficulties with their headset and syndicate radio implant, and were unable to see or use their department channel (science) while they were implanted with the radio implant. 

To reproduce: 
1. get a department radio headset
2. implant yourself with a syndicate radio implant (/obj/item/implant/radio/syndicate)
3. attempt to use the department radio

**Comment by iskyp** [comment] 2018-04-05 01:42
repeat of #34136 & #34158

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-05 16:31
not 34158

**Comment by iskyp** [comment] 2018-04-05 22:08
fuck i meant to put 36552, oh well.

**Comment by ShizCalev** [comment] 2018-04-10 19:34
Duplicate of #34136

**Closed by ShizCalev** 2018-04-10 19:34 UTC
