### ISSUE TITLE
Touch Spells don't work via action button

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#37618] opened 2018-05-02 05:28 UTC
Issue reported from  Round ID: 87306 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Testmerges]:
 #37578 
#37587 
#37597 
#37406  

Unable to use Flesh to Stone or Disintegrate via the action buttons on the HUD, they work by clicking the verb under the spell tab, however.

**Comment by ShizCalev** [comment] 2018-05-02 10:30
Duplicate of #37074

**Closed by ShizCalev** 2018-05-02 10:30 UTC
