### ISSUE TITLE
Washing face in sink did not clear cream pie overlay

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57137] opened 2021-02-23 09:45 UTC
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:

1. Have face creampied
2. Wash face with sink
3. Doesn't clear
4. Have to use shower

Maybe this was changed (or was never possible and I'm forgetting) but seems unintentional to me

**Comment by rdragan** [comment] 2021-02-23 10:03
Dupe of #57039

**Closed** 2021-02-23 10:09 UTC
