### ISSUE TITLE
Stomachs Are Not Properly Edible

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54118] opened 2020-10-01 02:13 UTC
## Reproduction:

1). Get a stomach.
2). Eat it.
3). Get the message 'none of the stomach left, oh no!'.
4). Gain nothing, the stomach fades away into nonexistence.
5). Cry.

**Comment by nightred** [comment] 2020-10-01 15:51
It looks like PR #54095 will fix this issue.

**Comment by PKPenguin321** [comment] 2020-10-05 04:54
>It looks like PR #54095 will fix this issue.

Well, did it?

**Comment by PKPenguin321** [comment] 2020-10-05 05:08
This was NOT fixed by #54095, the issue still reoccurs on latest.

**Comment by Hamcha** [comment] 2020-10-05 16:17
From a quick test it seems this is because the total volume of the `reagents` var is taken into account, without regard to `food_reagents`. As a stomach continuously metabolized its contained reagents, an empty stomach will have none (while it should have the 5 nutriment + 5 iron from `food_reagents`).
I made a mob eat as much as possible and then gibbed them and the stomach had enough nutriment left inside to be edible as intended.

**Comment by nightred** [comment] 2020-10-05 22:54
interesting, 
I would expect the amount of bites to remain the same, but the contained reagents be split
The reagents it contained be added to the food value of the organ, not replace it.

**Comment by Hamcha** [comment] 2020-10-05 22:58
Well the reason no bites occur is because the total volumes goes to zero, and triggers this:

https://github.com/tgstation/tgstation/blob/390f33e6220c5207986dea8e9102746278a0ffc9/code/datums/components/food/edible.dm#L267-L268

I noticed all organs just have their `food_reagents` copied to `reagents` when they are initialized:
https://github.com/tgstation/tgstation/blob/08447679d552a98552f92a39b887f861bd09c661/code/modules/surgery/organs/organ_internal.dm#L33-L40

My hunch is that stomachs consume their own nutrition value as soon as they are living, and since it's so small no one really noticed.

**Comment by Qustinnus** [comment] 2020-10-06 07:28
this had nothing to do with #54095 . It's as hamcha says, the organ is metabolizing its own reagents because this broken ass stomach PR was merged without any thought.

**Comment by dragomagol** [comment] 2020-11-26 21:08
Appears to have been fixed.

**Closed by dragomagol** 2020-11-26 21:08 UTC
Labels: Bug
