### ISSUE TITLE
items spin when you leave the shuttle in hyper space and can kill you

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73395] opened 2023-02-12 21:40 UTC
## Round ID:
[200012](https://scrubby.melonmesa.com/round/200012)

## Reproduction:
i dont know. it just randomly happened in this round

![image](https://user-images.githubusercontent.com/61211748/218338878-f0001c82-dc15-49b4-8b2c-248a72897625.png)

**Comment by Time-Green** [comment] 2023-02-13 15:01
It’s not a bug, it happens when you get hit by items in hyperspace since they get constantly thrown. I left it in intentionally since I thought it was cool/made sense, although I didn’t expect it to actually go as far as to kill someone

**Comment by Jackal-boop** [comment] 2023-02-13 19:39
> It’s not a bug, it happens when you get hit by items in hyperspace since they get constantly thrown. I left it in intentionally since I thought it was cool/made sense, although I didn’t expect it to actually go as far as to kill someone

They spin while you hold them and damage you

**Comment by Time-Green** [comment] 2023-02-13 20:37
> > It’s not a bug, it happens when you get hit by items in hyperspace since they get constantly thrown. I left it in intentionally since I thought it was cool/made sense, although I didn’t expect it to actually go as far as to kill someone
> 
> They spin while you hold them and damage you

That’s a pretty big fucking detail

**Comment by Time-Green** [comment] 2023-02-13 20:38
Duplicate of #72727

**Closed by Time-Green** 2023-02-13 20:38 UTC
Labels: Bug

**Comment by Time-Green** [comment] 2023-02-13 20:40
Not exactly the same, but it’s the same bug with a different outcome
