### ISSUE TITLE
Saber Sheaths are showing error sprites on the floor.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#70656] opened 2022-10-19 16:21 UTC
## Reproduction: I came across the captains body post revolutionary execution. I'm unsure if the sheath was still on his belt slot before the execution or not. But after they got ganged up upon and torn into pieces. The sheath was on the floor showing an error sign instead of its floor sprite.

![image](https://user-images.githubusercontent.com/29222521/196748411-a5b9b92b-e194-4e24-9728-521373350f47.png)

**Comment by ShizCalev** [comment] 2022-10-19 16:40
#70459 @lnGoror You marked your PR as closing #70437?

**Comment by VladinXXV** [comment] 2022-10-24 23:44
Can't reproduce
![image](https://user-images.githubusercontent.com/44104681/197650516-c55324a9-5513-426b-bf03-70318205bb3e.png)
![image](https://user-images.githubusercontent.com/44104681/197650561-70807952-054a-4ede-b433-5fecb214c9f4.png)

**Comment by Mooshimi** [comment] 2022-11-01 14:47
Fixed by #70976

**Closed by Mooshimi** 2022-11-01 14:47 UTC
Labels: Sprites, Bug
