### ISSUE TITLE
Cult constructs can't see their spells

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#66486] opened 2022-04-24 19:52 UTC
Reporting client version: 514.1582

## Round ID:
[182094](https://scrubby.melonmesa.com/round/182094)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Makes it possible to speed up the tram](https://www.github.com/tgstation/tgstation/pull/66348)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/164993840-45ed7eda-28f7-4e7c-b3d2-5aa1ed56dd7e.png)

**Comment by dragomagol** [comment] 2022-04-24 19:52
Wasn't able to as both a harvester and a wraith.

**Comment by SuperNovaa41** [comment] 2022-04-24 21:50
Duplicate of https://github.com/tgstation/tgstation/issues/66120

**Closed by SuperNovaa41** 2022-04-24 21:50 UTC
