### ISSUE TITLE
Double-barreled shotgun skins showing as error on wearing

### ISSUE THREAD

**Issue by SteveDream** [tgstation/tgstation#55218] opened 2020-11-28 16:35 UTC
Reporting client version: 513.1536

## Round ID:[151159](https://scrubby.melonmesa.com/round/151159)

That's my first issue-reporting so if there is any something I did wrong, I'm sorry.

The double-barreled shotguns skins show as errors when you wear it on your character 
![image](https://user-images.githubusercontent.com/42705206/100520744-1fa36200-31a8-11eb-8d7e-48a7f803bf7b.png)

to reproduce the issue you have to: Alt-click on the double-barreled shotgun, select a skin from the wheel, and probably you have to re-wear the shotgun and Boom! you got the pink weird thing.

**Comment by dragomagol** [comment] 2020-11-28 17:51
Duplicate of #54363 (you did everything right, it's just that this issue is already on the list)

**Closed by dragomagol** 2020-11-28 17:51 UTC
