### ISSUE TITLE
AI "Toggle Camera Light" ability doesn't follow AI eye

### ISSUE THREAD

**Issue by zkxs** [tgstation/tgstation#70381] opened 2022-10-08 08:48 UTC
Across multiple rounds, I've observed that the toggle camera light function is centered on the AI core, *not* the AI eye. This was particularly annoying in a blackout round where every light on the station was broken.

## Round ID, Testmerges Etc

```
Round ID: [191960](https://scrubby.melonmesa.com/round/191960)
BYOND Version: 514.1588
Server revision compiled on: 
Master commit: [5c2b340a94a3b9f9c15dbffe1c9282ae9a849af4](https://www.github.com/tgstation/tgstation/commit/5c2b340a94a3b9f9c15dbffe1c9282ae9a849af4)
The following pull requests are currently test merged:
[#70273: 'Checks Filters For Cross-Station Messages' by san7890 at commit b7391b8f9a](https://www.github.com/tgstation/tgstation/pull/70273)

Local commit: 4dfc7bcab16de653a4e4b2c7806d795eebbf7e2d
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
```

## Reproduction:

1. Be the AI
2. Toggle camera lights on
3. Observe how your core is now lit, but your eye lives in eternal darkness

**Comment by zkxs** [comment] 2022-10-09 11:21
This may be a duplicate of #70240. I think I missed it in my duplicate search because it was closed for a narrow window, and I was only checking for open issues.

**Comment by timothymtorres** [comment] 2022-10-10 06:55
Duplicate of #70240

**Closed by timothymtorres** 2022-10-10 06:55 UTC
Labels: Bug
