### ISSUE TITLE
MMIs cannot use Exosuit equipement.

### ISSUE THREAD

**Issue by Gousaid67** [tgstation/tgstation#37285] opened 2018-04-18 18:23 UTC
Issue reported from  Round ID: 86694 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
[Round ID]: #86694

[Reproduction]: Shove an MMI with a brain in a mech. And make it try to use the equipement with it, He will not be able to use them.

**Comment by Anonmare** [comment] 2018-04-18 18:31
I have found a workaround in reconnecting to reinitialise the mech. 

Also AIs use middle-mouseclick for their equipment so make sure that's the button you're using

**Comment by Gousaid67** [comment] 2018-04-18 18:32
i see, well il change the title to MMIs only for now, but i will be testing wheter AIs can control it

**Comment by Barhandar** [comment] 2018-04-18 21:26
@Anonmare reconnecting to what exactly? Server? Doesn't work.

**Comment by PKPenguin321** [comment] 2018-04-18 21:40
I think this is a dupe of a very old issue

**Comment by Gousaid67** [comment] 2018-04-19 07:32
Well middleclicking doesnt work for MMIs either, so they are their own problem currently

**Comment by Kromgar** [comment] 2018-04-20 00:36
Weird posibrains work

**Comment by Gousaid67** [comment] 2018-04-23 08:33
i didnt mention posibrains, as they pretty much work like the AI does. but this doesnt Apply to MMIs.

**Comment by SpaceManiac** [comment] 2018-12-28 18:56
Fixed by #41167

**Closed by SpaceManiac** 2018-12-28 18:56 UTC
Labels: Bug
