### ISSUE TITLE
Sending Space credits in a cargo crate doesn't give money to cargo

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#31121] opened 2017-09-29 14:32 UTC
Basically title

**Comment by ma44** [comment] 2017-09-29 18:22
dupe of #19973

Also I believe you export cash only through the ATM now, cargo exports doesn't seem to have anything for space credits.

**Comment by Cyberboss** [comment] 2017-09-29 21:42
Duplicate of #19973

**Closed by Cyberboss** 2017-09-29 21:42 UTC
