### ISSUE TITLE
Motion sickness while playing with wallening

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85697] opened 2024-08-08 14:50 UTC
## Issue Summary
I'm not motion sick myself but a lot of people that suffer from it are getting sick by playing the game with wallening TM'd.
It happens when standing still, and becomes a lot worse when they start moving, so much so that these players absolutely cannot play the game anymore.

### Feedback from a player on discord that experienced this problem (legitgoated):
"Our eyes and brain work together to help us understand the world around us. When we look at something, our eyes send information to our brain about what we're seeing.
In the original top-down view of the game, our brain was used to processing the information in a certain way. It was simple and easy for our brain to figure out what was going on.
But with the new 3/4 perspective, our eyes are sending different information to our brain. It has to work harder to try and make sense of this new angle and figure out the depth and distance of things.
This extra work our brain has to do can make us feel sick to our stomach, kind of like when you're on a spinning ride at the fair. Our brain gets a little confused and overwhelmed, and that makes our body feel nauseous.
It's like our brain and eyes aren't on the same page anymore. The brain is expecting one thing, but the eyes are showing something different. This mismatch is what causes the uncomfortable nauseous feeling for a lot of players.
The simple top-down view just made more sense for our brains to process. The new 3/4 angle is asking our brains to work overtime, and that's why so many people are getting motion sickness from it. Our bodies just don't like that extra mental effort! Essentially, the change in camera perspective is causing sensory conflict between what the eyes see and what the brain expects, resulting in the unpleasant nauseous symptoms. The 2D top-down view was likely better suited to the game's design and more comfortable for the majority of the player base."

### Something of note
Players expressed that the wall-offset version made it less sick-inducing than the mob-offset version

## Testmerges:
wallening

## Reproduction:
1. Suffer from motion sickness
2. Play the wallening
3. Get sick

**Comment by SyncIt21** [comment] 2024-08-08 15:10
There isn't any technical details listed in this issue and it is a very subjective opinion.

Also this has been bought up several times in the wallening PR so its redundant.

Also even after wallening gets merged no one can make a PR that will close this issue cause someone will always complain that enough wasen't done.

Conclusion is this issue don't do anything

**Comment by Time-Green** [comment] 2024-08-08 15:11
@cnleth @Generubi @CoastalCookie
Sorry to ping you from thumbs, but do you know why exactly you're getting motion sick? Maybe there's something we can do about it for you

**Comment by avaster303** [comment] 2024-08-08 15:13
> @cnleth @Generubi @CoastalCookie Sorry to ping you from thumbs, but do you know why exactly you're getting motion sick? Maybe there's something we can do about it for you

Make the walls an optional setting or remove 3/4, make things aligned

**Comment by CoastalCookie** [comment] 2024-08-08 15:16
> @cnleth @Generubi @CoastalCookie Sorry to ping you from thumbs, but do you know why exactly you're getting motion sick? Maybe there's something we can do about it for you

While im generally one not the be extremely affected by motion sickness i do get the feeling i have to slightly vomit _which i don't think is healthy lol_ 

I suspect its cause of the height making it require allot more focus to actually figure out what wall is what. What is going on etc. Instead of flat 2d topdown walls that are as easy to identify as they come

**Comment by cnleth** [comment] 2024-08-08 15:16
> @cnleth @Generubi @CoastalCookie Sorry to ping you from thumbs, but do you know why exactly you're getting motion sick? Maybe there's something we can do about it for you

I experience dizziness while moving in station areas. It's hard to say why, but I compared terry wallening (the "default") and manuel wallening (walls offset instead of objects) and the manuel version seems to have less of a negative effect on me, although I still get dizzy with time. Open areas like lavaland and icemoon are not that bad.

**Comment by Sadboysuss** [comment] 2024-08-08 15:16
> There isn't any technical details listed in this issue

I tried getting more info but the players told me moving or just looking at the screen made them motion sick

> it is a very subjective opinion.

I'm sorry you think a medical condition is a subjective ***opinion***

> Also this has been bought up several times in the wallening PR so its redundant.

Issue tracker is for tracking issues, making it a comment on the wallening pr will get it lost in the sea of other stuff

> Also even after wallening gets merged no one can make a PR that will close this issue.

How do you know that?

**Comment by Generubi** [comment] 2024-08-08 15:37
> @cnleth @Generubi @CoastalCookie Sorry to ping you from thumbs, but do you know why exactly you're getting motion sick? Maybe there's something we can do about it for you

Hii, its hard to explain, but just standing in the station gave me slight motion sick and moving made it a LOT worse. i cant play more than one round before having to stop the game because i get super super dizzy, and when i died i had to run into space as ghost not to look at the walls. :(

**Comment by Inari-Whitebear** [comment] 2024-08-08 15:54
Yeah, it's sadly hard to pinpoint what causes nausea. It's not like anyhting specific stands out to the person.

I get it a bit too and I got to agree the manuel version of shifted walls instead of shifted players helps a bit, but it's still existing.

**Comment by Sadboysuss** [comment] 2024-08-08 15:58
### Feedback from a player on discord that experienced this problem (legitgoated):
"Our eyes and brain work together to help us understand the world around us. When we look at something, our eyes send information to our brain about what we're seeing.
In the original top-down view of the game, our brain was used to processing the information in a certain way. It was simple and easy for our brain to figure out what was going on.
But with the new 3/4 perspective, our eyes are sending different information to our brain. It has to work harder to try and make sense of this new angle and figure out the depth and distance of things.
This extra work our brain has to do can make us feel sick to our stomach, kind of like when you're on a spinning ride at the fair. Our brain gets a little confused and overwhelmed, and that makes our body feel nauseous.
It's like our brain and eyes aren't on the same page anymore. The brain is expecting one thing, but the eyes are showing something different. This mismatch is what causes the uncomfortable nauseous feeling for a lot of players.
The simple top-down view just made more sense for our brains to process. The new 3/4 angle is asking our brains to work overtime, and that's why so many people are getting motion sickness from it. Our bodies just don't like that extra mental effort! Essentially, the change in camera perspective is causing sensory conflict between what the eyes see and what the brain expects, resulting in the unpleasant nauseous symptoms. The 2D top-down view was likely better suited to the game's design and more comfortable for the majority of the player base."

**Comment by Time-Green** [comment] 2024-08-08 19:34
From what I gather, it's the blackness and difficulty telling which tile you're on? I at least know we can add tile aligned shadows to mobs to help with orientation. I'm not sure how much the blackness dizzines can be fixed, it's probably just inherently how sight works with byond. I believe @Jacquerel might be starting work on it? 

![image](https://github.com/user-attachments/assets/a60db1fe-1c43-44e4-b26d-fff81fe81eeb)

**Comment by deathrobotpunch** [comment] 2024-08-09 02:53
I don’t experience sickness per say from the wallening though I do get headaches and also that feeling you get when you play with Covid-19 where you sort of feel like mentally exhausted idk

**Comment by Time-Green** [comment] 2024-08-09 06:11
> I don’t experience sickness per say from the wallening though I do get headaches and also that feeling you get when you play with Covid-19 where you sort of feel like mentally exhausted idk

I kind of need to know why, I can’t prescribe meds but I may be able to help with the visual cause

**Comment by KingkumaArt** [comment] 2024-08-11 01:48
> > I don’t experience sickness per say from the wallening though I do get headaches and also that feeling you get when you play with Covid-19 where you sort of feel like mentally exhausted idk
> 
> I kind of need to know why, I can’t prescribe meds but I may be able to help with the visual cause

I've got a potential reason for it!  tldr: the game pauses for a second each time you move onto a new tile which leads to an inconsistency you dont conciously notice but your brain doesnt like it. It's why I have to framerate cap a lot of games.

https://github.com/user-attachments/assets/0575fe1a-8a92-4ae6-a345-79fcfdba5656

**Comment by KingkumaArt** [comment] 2024-08-11 01:54
https://github.com/user-attachments/assets/7bf87d87-5fb1-4a60-a9d4-1283074c204a

Also heres the above clip played at full speed.

**Comment by milktao** [comment] 2024-08-12 00:01
I am also experiencing nausea with the new update.

A little backstory, I typically experience intense motion sickness and headaches/migraines from first person games, even when switching to 3rd person in games like Minecraft. I've theorised this is due to the harsh FOV (which I can never seem to find a comfortable medium for), tight spaces with low ceilings (such as houses) and the camera being too close to the player. When Palworld came out, I also suffered due to the camera being too close, luckily I was able to use a mod that allowed me to zoom out from the character a bit, and allowed me to play for longer sittings.

Ever since the new update, I've been feeling sick by the end of each round. Sadly, I did not get to try Melbert's shifted wall version to comment on that. In an ideal world, we could have an option to disable it, although I don't expect this to happen.

Like others have said, it is hard to pinpoint what exactly is causing this, but here are the things I have noted:
- I'm having a hard time distinguishing where I am in relation to furniture, machines, computers etc. I can't seem to tell whether I'm standing next to an object or one tile away. Part of this is definitely the walls not fitting neatly onto one tile.
- I've noticed my character's position is sometimes farther away from one object than another, yet I am still adjacent to both. 
- Simple and Large open areas are less nausea inducing, see Inari-Whitebear's example images.

Another thing I have noticed is the darker lines on floor tiles are shifting with each step, so when running it produces a mild flashing effect. I'm not sure if this is a rendering issue or even a new issue, but it's definitely having an effect—at least with figuring out where I am standing.

![floortiles](https://github.com/user-attachments/assets/2dcb4843-5598-46be-8d5c-1a8f3720e032)


I will update this as potential fixes are pushed out, and when I find more potential causes for these nauseous effects when I can attempt playing. It's likely a mix of factors causing this for us, and fixing one thing might not help what's causing it for the rest.

**Comment by LemonInTheDark** [comment] 2024-08-12 05:28
* I'm having a hard time distinguishing where I am in relation to furniture, machines, computers etc. I can't seem to tell whether I'm standing next to an object or one tile away. Part of this is definitely the walls not fitting neatly onto one tile, and a lot of objects are no longer centred on each tile.

We recently added a dropshadow to mobs, I wonder if this will help with things. More things are offset now. IIIIDK if that's enough though.

* I've noticed my character's position is sometimes farther away from one object than another, yet I am still adjacent to both.


This I can do less about, though I do agree it is an issue.  

The ideal solution is giving objects and mobs limited pixel movement (IE steps of like 16) so they can "bump up" against objects above/below them. This is something I want SOMEDAY but it's such a technical difficulty (for context pixel movement is on the scale of a wallening pr) that it may not come in a quick enough time to be impactful (On the order of like years to maybe never).

* Simple and Large open areas are less nausea inducing, see Inari-Whitebear's example images.

This makes sense, since you're further pulled away from the frills. Is it JUST the perspective that bothers you? I added a pref that makes all frills transparent, does that help at all?

Unrelated, I have a feeling part of the issue here is the classic /tg/ brand random movement stutter. Am looking into this atm to see if it's solvable and not just LMAO overtime.

**Comment by SmArtKar** [comment] 2024-08-12 07:35
@Jacquerel shadows helped a ton, but they seem to be offset one or two pixels too low, resulting in a weird look. However, what I found to be of massive help is changing my offset to 8 pixels instead of 12, maybe 10 as middleground could also work. That solved the issues for me completely
![image](https://github.com/user-attachments/assets/965cafe0-ed1d-4e21-871f-8b18b9b43c5f)

**Comment by Inari-Whitebear** [comment] 2024-08-12 11:47
Drop shadows seem to help with motion sickness. It's like.. 90% reduced I'd say. Stiiil slightly there, more noticable in maints where the shadow isn't really visible, and still getting it as a ghost oddly.

May also have to try pixel scaling to see if that has an effect

**Comment by SmArtKar** [comment] 2024-08-12 17:43
Here are current normal and leaning human sprites
![image](https://github.com/user-attachments/assets/620ffac4-9ef2-4da8-a8ee-e5990dba0ee0) ![image](https://github.com/user-attachments/assets/e8c428c3-52c4-41f0-8c47-3a1fe1eb5291)

I propose shifting the shadow one pixel up (PR already up) and changing the offset from 12 to 8 pixels
![image](https://github.com/user-attachments/assets/ce5a1ece-ba00-47e0-9cbc-b9a88825bae0)
![image](https://github.com/user-attachments/assets/32781426-161f-4023-ae43-812bbbd896b5)

**Comment by LemonInTheDark** [comment] 2024-08-13 01:26
from discord

![image](https://github.com/user-attachments/assets/fdd192ee-bfb4-42f8-ae67-b2e6a73c4ff7)

response

![image](https://github.com/user-attachments/assets/559874a5-8573-4db5-8875-f200493a6a3f)

**Comment by milktao** [comment] 2024-08-13 06:50
I just wanted to check in. As above, the drop shadow does help but does not completely fix the issue. I understand that bumping into objects would be a large project in itself, and may even come with its own set of nausea issues.

In general, simple environments are significantly better than complex ones, and long vertical hallways are less nausea inducing than horizontal ones. That leads me to believe that frills are partially involved. That said, the frills pref is confusing. It's hard to tell whether it's having an adverse effect or positive. At this point in time, I believe enabling it improves my experience of the frills on southern walls. I have questioned if the cutaway effect when walking through a frill is causing the 'wall moving' feeling that others have described. So naturally, when those frills are more transparent, the cutaway effect is less noticeable. Now onto the part that confuses me, I believe that northern wall frills with the transparency might be causing the adverse effects i'm experiencing. I think this is due to the northern walls feeling less solid... Which I understand is not feasibly fixable with the current implementation. Potentially, having an option to disable the cutaway effect could be a solution.

However, at this point I feel like it's too early to say for sure, especially when it comes to the frills, and am eager to hear of other people's experience with the wall frills preference in the game options. I apologise in advance if any of this sounds a little too abstract, I have tried my best to put into words what I think I have been experiencing. Further testing and time will tell. (Hope you're having a good day) :)

**Comment by LemonInTheDark** [comment] 2024-08-13 08:17
Posting generally I am curious what your (people with issues) FPS settings are. It isn't the only source of this but because of floating point rounding issues and disconnects with the server tick some values can be kinda funky and could contribute to this problem.

**Comment by LemonInTheDark** [comment] 2024-08-13 08:38
> In general, simple environments are significantly better than complex ones, and long vertical hallways are less nausea inducing than horizontal ones. That leads me to believe that frills are partially involved. That said, the frills pref is confusing. It's hard to tell whether it's having an adverse effect or positive. At this point in time, I believe enabling it improves my experience of the frills on southern walls. I have questioned if the cutaway effect when walking through a frill is causing the 'wall moving' feeling that others have described. So naturally, when those frills are more transparent, the cutaway effect is less noticeable. Now onto the part that confuses me, I believe that northern wall frills with the transparency might be causing the adverse effects i'm experiencing. I think this is due to the northern walls feeling less solid... Which I understand is not feasibly fixable with the current implementation. Potentially, having an option to disable the cutaway effect could be a solution, or having the transparency be a gradient from the bottom of the screen to the top.
> 
> However, at this point I feel like it's too early to say for sure, especially when it comes to the frills, and am eager to hear of other people's experience with the wall frills preference in the game options. I apologise in advance if any of this sounds a little too abstract, I have tried my best to put into words what I think I have been experiencing. Further testing and time will tell. (Hope you're having a good day) :)

It is highly possible to disable your own frill if you wanted that would be as trivial as the other prefs we have for wallening rn.

**Comment by Inari-Whitebear** [comment] 2024-08-13 10:27
I did experiment with FPS settings, but wasn't sure of the results. Usually I just have it set to Recommended (100), with a 144Hz Monitor

**Comment by milktao** [comment] 2024-08-13 17:21
Mine is also at the recommended setting of 100 fps, with a 60Hz monitor.

Being able to completely disable my own frills would be something I'm interested in trying over the transparent version, as it will likely make walls feel more solid in comparison. Similarly, I've noticed that glass walls that are south in relation to my character on screen seem less nausea inducing than walls when running along them (likely due to a reduction in the appearance of the cutout).

For the record, I do play Arknights which is a 3/4? game and have played Dwarf Fortress with the Perspective Walls mod. The only time I've experienced nausea in Arknights was during slow-downs (from a lot of visual effects on screen etc.) where the frames seemed to lurch. But! I do play on an emulator xD I don't remember feeling any nausea with Dwarf Fortress.

Wishing all a good and productive day😁

**Comment by Rheoryn** [comment] 2024-08-14 17:04
For me the shadow has not really changed much that I can tell.  The issue is extremely prevalent for me in any tile sets that are extra bright.  Medbay feels like it's low key flashbanging me when I move around now.  This has always been an issue for me, but something about the wallening tilesets seem to have augmented this effect to a higher level.  There's more bright/dark space being pulsed and redrawn as you move from tile to tile.  

I actually had to pop one of my migraine interuptants this morning while testing this to try to narrow it down.

**Comment by Time-Green** [comment] 2024-08-14 17:53
> For me the shadow has not really changed much that I can tell. The issue is extremely prevalent for me in any tile sets that are extra bright. Medbay feels like it's low key flashbanging me when I move around now. This has always been an issue for me, but something about the wallening tilesets seem to have augmented this effect to a higher level. There's more bright/dark space being pulsed and redrawn as you move from tile to tile.
> 
> I actually had to pop one of my migraine interuptants this morning while testing this to try to narrow it down.

We could maybe add a preference for changing the blackness color? Something like gray?

**Comment by Time-Green** [comment] 2024-08-14 17:55
I'd also be curious to hear suggestions from people with motion sickness, because IIRC we dont have any of them on the team making it somewhat hard to devise a solution

**Comment by Rheoryn** [comment] 2024-08-14 18:00
> > For me the shadow has not really changed much that I can tell. The issue is extremely prevalent for me in any tile sets that are extra bright. Medbay feels like it's low key flashbanging me when I move around now. This has always been an issue for me, but something about the wallening tilesets seem to have augmented this effect to a higher level. There's more bright/dark space being pulsed and redrawn as you move from tile to tile.
> > I actually had to pop one of my migraine interuptants this morning while testing this to try to narrow it down.
> 
> We could maybe add a preference for changing the blackness color? Something like gray?

That might help, this is unfortunately a really complex issue because brains are weird.  I'm not a programmer, so I don't know how hard tinting black to grey would be to test this sort of thing.  Motion sickness is frustrating because it's just sort of feeling for vibes, except the vibes are you're dizzy and tummy upset.

**Comment by CliffracerX** [comment] 2024-08-15 05:40
I primarily get serious headaches of the eye strain variety with this- like trying to read text that's too small or using the wrong glasses for a given distance of focus, just navigating stations with the Wallening eventually causes pain & I have to close my eyes to rest for a bit.

**Closed** 2024-09-08 18:52 UTC
Labels: Priority: High, RED LABEL, Accessibility
