### ISSUE TITLE
if you polymorph into a holopara you can't be killed

### ISSUE THREAD

**Issue by AhmetEfeAkgoz** [tgstation/tgstation#78691] opened 2023-09-30 10:32 UTC
## Reproduction:
1: Find a polymorphic belt
2: Scan a holopara of any kind
3: Polymorph into holopara
4: You are immortal and you have no master

![image](https://github.com/tgstation/tgstation/assets/85807038/170c636b-7080-4a46-891a-4141196a69db)

**Comment by Sealed101** [comment] 2023-09-30 12:05
Duplicate of #78578

**Closed by Sealed101** 2023-09-30 12:05 UTC
