### ISSUE TITLE
Lavaland elites can't damage mechs

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#49814] opened 2020-03-08 11:25 UTC
Round id: I forgot, but it was yesterday on manuel

I was a broodmother and killed my summoner, but then came along a mech who could not be damaged by me at all. All the normal stuff happened, it's just that they didn't take any damage at all. It was a gygax and they didn't have a repair droid

**Comment by Pumpkinoe** [comment] 2020-03-08 20:56
Dupe of #48302 ?

**Comment by Time-Green** [comment] 2020-03-08 21:26
Seems like it

**Comment by ATH1909** [comment] 2020-03-09 09:30
Honestly, I know that lavaland elites were intentionally not given object damage in their original PR, but I think that it'd honestly be fine to give them a reasonable amount of object damage (enough to smash through doors?).

**Comment by Arturlang** [comment] 2020-03-11 19:39
It was intentional for them to not get object damage so they couldnt damage the station, i do think. Should probably do something about them being unable to attack mechs though

**Closed** 2020-06-08 22:07 UTC
Labels: Bug
