### ISSUE TITLE
Organic slurry creation appears to be broken

### ISSUE THREAD

**Issue by capn-monkeypaw** [tgstation/tgstation#69046] opened 2022-08-06 19:39 UTC
Both player and admin attempts to create organic slurry result the elimination of the component ingredients. 
To put it another way, everything in a reagent container goes poof once a dead mouse is added to the welding fuel.
This was observed during round 188039 on Sybil.

**Comment by newfren** [comment] 2022-08-07 00:17
I believe the organic slurry is added to the mouse, which has to then be ground

**Comment by Shadowflame909** [comment] 2022-08-07 10:29
yeah mouse is a sponge that you then grind up

**Comment by Time-Green** [comment] 2022-08-07 14:24
> yeah mouse is a sponge that you then grind up

This does not work though, ran into it yesterday and forgot to make a bug report. It gives welding fuel, blood, mold, nutriment etc but no organic slurry

**Comment by CPTANT** [comment] 2022-08-12 16:16
I am unable to reproduce this.

I did this:
Beaker of 50 welding fuel
dip dead mouse
wait until reaction sound
grind mouse
And I got organic slurry as expected

**Comment by Time-Green** [comment] 2022-08-12 17:32
Should close this then. It might’ve been due to my mice becoming moldy

**Closed by Time-Green** 2022-08-12 17:32 UTC
Labels: Bug, Tested/Reproduced
