### ISSUE TITLE
Airlock hacking menu does not pop up

### ISSUE THREAD

**Issue by Flerpin** [tgstation/tgstation#64439] opened 2022-01-26 04:42 UTC
Reporting client version: 514.1578

## Reproduction: For some odd reason, whenever one tries to go and hack, specifically, an airlock - You can't do it. The menu will not pop up. You can hack other electronic devices such as air alarms, but it seems that you cannot hack airlocks (or, at the very least, the ones in engineering on Ice Box Station).

Steps to reproduce:
Grab a screw driver and open an airlock panel.
Grab a multi-tool or wire cutter and click on airlock. It should open up the hacking menu but it does not.

**Comment by dragomagol** [comment] 2022-01-26 04:42
Duplicate of #64432

**Closed by dragomagol** 2022-01-26 04:42 UTC
