### ISSUE TITLE
Transfering to golems shells after the shell is taken

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#27392] opened 2017-05-18 15:50 UTC
1. As a golem, complete a golem shell
2. Click on it to get a consciousness transfer prompt
3. Let someone take control of the shell
4. Click "Yes" on the prompt.
5. Watch the bizarre results.

Last time I experienced this, I was taken to the error handling room, unable to see anything.

**Comment by WJohn** [comment] 2017-05-18 16:05
Dupe of #27373 come on man it's like 5 issues down.

**Closed by WJohn** 2017-05-18 16:05 UTC
