### ISSUE TITLE
Invisible op tables

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#69661] opened 2022-09-02 09:16 UTC
Reporting client version: 514.1585

## Round ID:
[189702](https://scrubby.melonmesa.com/round/189702)

## Reproduction:

1. go on terry
2. icebox
3. INVISIBLE OPERATING TABLE

**Comment by timothymtorres** [comment] 2022-09-02 09:40
Duplicate of #69657

**Closed by timothymtorres** 2022-09-02 09:40 UTC
