### ISSUE TITLE
Hydroponics dirt plots cannot be dug up

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/tgstation#62894] opened 2021-11-17 05:34 UTC

**Comment by TheBonded** [comment] 2021-11-17 21:53
Are you sure using a spade is supposed to deconstruct these? Did you try using both right click and left click, as well as combat and non combat modes?

>Being unable to recreate dirt plots can potentially create issues for maintenance gardeners, ashwalkers, and prisoners.

I don't see how this could pose an issue for them, unless they had to relocate the plots for some reason, though it would be relatively easy for ashwalkers especially to just make new ones due to the abundance of ash nearby.

**Comment by BangingDonk** [comment] 2021-11-17 22:23
I am nearly certain that the spade was the correct tool for digging up old plots, but now I'm second guessing myself. I did try left and right clicks in both combat and normal mode, as well as combinations of said combined with alt and ctrl.

The main issue in not being able to destroy plots is that if you are extremely low on plant resources, actually getting the plots into a state where they can actually be used (mostly concerned with pest level more than anything else) can be very difficult to remove without access to pest killer or, even more unlikely, diethylamine. For ashwalkers, that's a minimal problem because they have basically all of lavaland to grow stuff. Prisoners who have access to dirt plots, however, can end up either with plots that are overrun with pests or toxins(extremely unlikely but not completely out of the question) or other difficult-to-address issues, with their only recourse being to either just suck it up or start making tons of new plots all over the place.

**Comment by TheBonded** [comment] 2021-11-17 22:27
> I am nearly certain that the spade was the correct tool for digging up old plots, but now I'm second guessing myself. I did try left and right clicks in both combat and normal mode, as well as combinations of said combined with alt and ctrl.

Some digging will have to be done to be sure about this one.

> The main issue in not being able to destroy plots is that if you are extremely low on plant resources, actually getting the plots into a state where they can actually be used (mostly concerned with pest level more than anything else) can be very difficult to remove without access to pest killer or, even more unlikely, diethylamine. For ashwalkers, that's a minimal problem because they have basically all of lavaland to grow stuff. Prisoners who have access to dirt plots, however, can end up either with plots that are overrun with pests or toxins(extremely unlikely but not completely out of the question) or other difficult-to-address issues, with their only recourse being to either just suck it up or start making tons of new plots all over the place.

I believe for prisoners specifically, the botany vendor they are given has pest killer available to be bought, so I don't know how much of an issue that would be. The only time I could think of that prisoners wouldn't have the vendor would be in the gulag, where they have access to near endless levels of ash.

Still, if the spade is indeed the tool used for digging up the plots, this is a bug that should be squashed.

**Comment by BangingDonk** [comment] 2021-11-17 22:32
Update: I have done some minor code diving. It appears that the SHOVEL is the tool for digging up dirt plots, and explicitly not the spade, which has an exclusionary flag in place to prevent you from doing so. I didn't think to check with a shovel instead of a spade, because the number of times you have access to a shovel on-station vs spades is next to nil, and the times I've most needed to do this sort of thing, I've had access to shovels.

I'm not in a position to test this right now due to scheduling, but if this is the case, we can either close this as not a bug, or possibly change shovel behavior universally to dig up plots in combat mode or something.

Thank you for investigating this.

**Comment by BlueMemesauce** [comment] 2021-11-18 17:33
I don't think its a consistency issue. Small shovel digs up just plant while big shovel digs up the whole dirt plot. It makes sense. 

Changing intents or mouse buttons would just make it confusing for no reason.

**Comment by TheBonded** [comment] 2021-11-18 19:30
> Update: I have done some minor code diving. It appears that the SHOVEL is the tool for digging up dirt plots, and explicitly not the spade, which has an exclusionary flag in place to prevent you from doing so. I didn't think to check with a shovel instead of a spade, because the number of times you have access to a shovel on-station vs spades is next to nil, and the times I've most needed to do this sort of thing, I've had access to shovels.
> 
> I'm not in a position to test this right now due to scheduling, but if this is the case, we can either close this as not a bug, or possibly change shovel behavior universally to dig up plots in combat mode or something.

@BangingDonk  No need to test it, that sounds right. The flag in place to prevent you from using a spade was likely added before the intent rework. I think it would make sense to put this on a right click, as you would expect a smaller shovel to still be able to dig up a plot of dirt, and right click is generally designated for secondary interactions such as deconstruction.

> I don't think its a consistency issue. Small shovel digs up just the plant, while big shovel digs up the whole dirt plot. It makes sense.
> 
> Changing intents or mouse buttons would just make it confusing for no reason.

@BlueMemesauce I believe this is a consistency issue, because generally right click is used for deconstructing things. for example, left clicking a table with a wrench or screwdriver will either place the tool on the table or attack the table, depending if you're on combat mode or not. Right clicking a table with either a screwdriver or wrench will deconstruct it, even if combat mode is on. This behaviour is not exclusive to the table, as many things have similar operations, having left click be interact and right click be deconstruct. Another example would be the autolathe, where right clicking with a screwdriver opens the maintenance hatch and gives you access to the wires, while left clicking with a screwdriver recycles the screwdriver into the autolathe.

That being said, if you or @BangingDonk would like, I'm happy to ask for the opinion of the other issue managers. They'll have more experience that I will on this subject.

**Comment by BangingDonk** [comment] 2021-11-18 20:48
At this point, I would personally like to see botany tools have more features than not, so I think that I might like an opinion of another issue manager. That said, I am very much aware that this is a low-priority project for an already obscure action taken in game, and recognize the fact that there are more pressing issues to work on.

In short, I do think it's a good idea but wholly accept and support the decision of it being closed for the time being if that's the path people would rather go.

**Comment by TheBonded** [comment] 2021-11-18 21:06
> At this point, I would personally like to see botany tools have more features than not, so I think that I might like an opinion of another issue manager. That said, I am very much aware that this is a low-priority project for an already obscure action taken in game, and recognize the fact that there are more pressing issues to work on.

Alright, I'll call upon @timothymtorres for a second opinion of whether or not this is a consistency issue or just not a bug. Personally I feel like it's a consistency issue and should be left open to allow the right click functionality to be added.

> In short, I do think it's a good idea but wholly accept and support the decision of it being closed for the time being if that's the path people would rather go.

I do believe it should stay open, since deconstructing things is generally put on right click and a smaller shovel/spade should be able to dig up a pile of dirt. But we'll see what Tim thinks about it

**Comment by timothymtorres** [comment] 2021-11-19 13:06
So I dugup (haha get it?) some old discussion on this in,

https://github.com/tgstation/tgstation/issues/28938
https://github.com/tgstation/tgstation/pull/28942

It is very clear that the intent was to make shovels only dig dirt piles and spades only dig plants.  This issue feels to me like a feature request and not a bug.  However this shouldn't discourage anyone from opening a PR with the suggested changes.  That is the place to have this discussion on whether this feature request has merit, not on the issue tracker which is for bug hunting.

To implement the code should be trivial.  It looks simple enough to just c/p some code to get it to work properly.

**Comment by TheBonded** [comment] 2021-11-19 16:19
> So I dugup (haha get it?) some old discussion on this in,
> 
> #28938 #28942
> 
> It is very clear that the intent was to make shovels only dig dirt piles and spades only dig plants. This issue feels to me like a feature request and not a bug. However this shouldn't discourage anyone from opening a PR with the suggested changes. That is the place to have this discussion on whether this feature request has merit, not on the issue tracker which is for bug hunting.

Fair enough, I'll leave it open for a few hours in case anyone else has anything to add, and close this in about 2-5 hours if not

> To implement the code should be trivial. It looks simple enough to just c/p some code to get it to work properly.

Yknow, I might as well do this, it'd be a great qol change, and a good way for me to learn how right click interactions work in the code. I'll copy paste some table deconstruction and shovel code.

**Comment by timothymtorres** [comment] 2021-11-20 04:21
If you need any help coding it feel free to ping me on discord

**Comment by TheBonded** [comment] 2021-11-20 10:57
I totally forgot about this issue report until now, since I did say I'd close it I'll do that now.

> If you need any help coding it feel free to ping me on discord

Thanks! I've already gotten the pr up and ready, but if anything comes up I'll be sure to ping you.

**Closed by TheBonded** 2021-11-20 10:57 UTC
Labels: Consistency Issue

**Comment by TheBonded** [comment] 2021-11-24 02:11
I would just like to point out that deconstructing the dirt piles doesn't seem to actually give you anything back, as it just qdels it, so removing them doesn't have much of a use anyways.
