### ISSUE TITLE
Error sprite when sitting down in a tram

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87338] opened 2024-10-20 20:06 UTC
### Client Version:

515.1641

### Issue Summary:

![image](https://github.com/user-attachments/assets/b597c5e4-60d2-476d-a8a5-45bcd1e1ec99)

### Round ID:

[240497](https://scrubby.melonmesa.com/round/240497)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

try using whatever I was wearing

**Comment by Profakos** [comment] 2024-10-22 10:12
While #87364 is a duplicate of this, that one is a better description as it seems to apply to all benches.

**Comment by Sealed101** [comment] 2024-10-22 11:10
closed in favor of https://github.com/tgstation/tgstation/issues/87364

**Closed by Sealed101** 2024-10-22 11:10 UTC
Labels: Sprites, Bug
