### ISSUE TITLE
Holopad giving AI vision to non-AI's (Apparently a reoccurring character too!)

### ISSUE THREAD

**Issue by InsaneKatrina** [tgstation/tgstation#41426] opened 2018-11-11 18:45 UTC
Issue reported from  Round ID: 96941 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Basically call using holopad > get answered > exit holopad, tada, you've screwed your vision over and now you can't see where the cameras cant, [giving the caller a static overlay.](https://puu.sh/C03xG/53022e19cc.png) (I'm standing inside a dorm room in the picture)

[This also appears to have happened before, but now its back.](https://github.com/tgstation/tgstation/issues/37272)

**Comment by SpaceManiac** [comment] 2018-11-11 18:53
Duplicate of #39752

**Closed by SpaceManiac** 2018-11-11 18:53 UTC
