### ISSUE TITLE
"removes miasma" pr causes the flu to happen nearly every round (even if there's no rotting bodies)

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58010] opened 2021-03-28 06:05 UTC
Round ID: any since it was added

Reproduction: like the title, it happens almost every round even if there's no rotting bodies, and it causes ONLY the flu, which is incredibly annoying due to dropping items, not to mention hard to cure since anacea purges itself

https://github.com/tgstation/tgstation/pull/57957

**Comment by ATH1909** [comment] 2021-03-28 07:33
how is the flu reaching a cure tier of anacea?

**Comment by Serxule** [comment] 2021-03-28 07:36
> how is the flu reaching a cure tier of anacea?

absolutely no idea

**Comment by TemporalOroboros** [comment] 2021-03-28 08:48
It's probably an advanced disease that's rolling all of the tier 1 symptoms... which are all massive stat boosters... and are probably rocketing it's resistance sky high.

**Comment by brotherbeyondd** [comment] 2021-03-28 13:37
Nah it causes other diseases. I believe I've had a corpse thrown at me as a chef and my windpipe collapsed rapidly. It's a constant state of running to medbay to get disease cures.

**Comment by ChocolateBickie** [comment] 2021-03-28 15:31
Fun fact, because Ash Walkers tendril is usually surrounded by gibs they get infected extremely often which they can't cure due to lack of Health Analyzers and Chem dispensers

Evidence round: 159127

**Comment by D4C-420** [comment] 2021-03-28 16:29
> On a side note some concern's with mining because they produce a large amount of gibs and corpses and do not really have a good way to remove them. This might lead to miners getting sick with dieses they had no way to counteract because who cleans lava land?

Lets also take this time to think of the poor miners.

**Comment by FalkKeegan** [comment] 2021-03-28 20:49
Yeah, this is reaching ridiculous levels, as I've mentioned in the Pull Requests comments.. this is way over the top in terms of virus strength. Anacea cure contact spreading Headaches by minute 15.. regurlarly..

**Comment by ExcessiveUseOfCobblestone** [comment] 2021-03-30 00:08
https://github.com/tgstation/tgstation/pull/57957/files#diff-698761d8e95c0d85782624b71bd0b95f84d588eea8369bfc921a0c381d8d2936R122

just change the prob if the issue is too easily contracting?

**Comment by LemonInTheDark** [comment] 2021-03-30 09:00
Closed by https://github.com/tgstation/tgstation/pull/58034

**Closed by LemonInTheDark** 2021-03-30 09:00 UTC
Labels: Bug
