### ISSUE TITLE
Plant produce stack count scales with icon size

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#69044] opened 2022-08-06 19:11 UTC
Reporting client version: 514.1585

## Round ID:
[188037](https://scrubby.melonmesa.com/round/188037)

## Testmerges:
- [Atmospheric Improvement: Fixing air is now faster and much easier](https://www.github.com/tgstation/tgstation/pull/68325)
- [Prevents NAN amounts infecting the chemistry reagent container system](https://www.github.com/tgstation/tgstation/pull/69017)

## Reproduction:

Instances of produce stacks such as inside plant bags will scale the stack count with the icon size. This becomes an issue with low potency making the icon small and the stack count illegible.

**Comment by timothymtorres** [comment] 2022-08-09 07:14
Duplicate of #36891

**Closed by timothymtorres** 2022-08-09 07:14 UTC
Labels: Sprites, Bug
