### ISSUE TITLE
Mechs cannot open ID-locked doors again

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#55733] opened 2020-12-25 08:21 UTC
Reporting client version: 513.1538

## Round ID:
[152868](https://scrubby.melonmesa.com/round/152868)

## Testmerges:
- [LINDA Reforged](https://www.github.com/tgstation/tgstation/pull/55604)
- [Refactors monkeys into a species](https://www.github.com/tgstation/tgstation/pull/55614)

## Reproduction:

Build a mech, try to open an ID-locked door by moving into it. This was recently fixed with #54595, but appears to have broken again

**Comment by dragomagol** [comment] 2020-12-25 16:58
Duplicate of #55732

**Closed by dragomagol** 2020-12-25 16:58 UTC
