### ISSUE TITLE
You can't deconstruct AI core after it's completion

### ISSUE THREAD

**Issue by Jazaen** [tgstation/tgstation#19799] opened 2016-08-10 22:07 UTC
Not sure if it's a bug or feature, but the deconstruction procedure for AI core doesn't work on completed AI. It means that, once brain is put into the AI core and glass is screwdrivered, there is no way to get the brain back, thus making it a better alternative for captured traitors than borging (since you can retrieve a brain from borgs).

**Comment by GunHog** [comment] 2016-08-10 22:59
It is not a bug. AIs are pure data; they do not actually need a brain to function fully - I presume the brain is simply scanned and transferred to the internal circuit board. 

Once you go AI, you never go back!

**Comment by Shadowlight213** [comment] 2016-08-11 04:38
I swear this is a dupe or something, because I remember complaining about this months ago.
Also @GunHog the inactive ai core is not deconstructable at least to my knowledge.

**Comment by Jordie0608** [comment] 2016-08-11 07:30
I believe this is intentional to prevent one crowbar hit being the ultimate in AI removal technology.

**Comment by Alek2ander** [comment] 2016-08-11 10:45
I CANNOT SELF-TERMINATE

**Comment by Jazaen** [comment] 2016-08-11 14:10
AI can very much self-terminate, mind. AI that suspects it might be forced to do harm could self-terminate to avoid it (as in, it KNOWS traitor has built upload console somewhere, but it is momentarily asimov because upload battle). There are "Kill yourself" traitor laws. And, if AI thinks it is useless in preventing human harm, you could order AI to self-terminate under law two.
Maybe make core disassembly require that AI core is not bolted to the floor?

**Comment by Shadowlight213** [comment] 2016-08-11 19:26
@Jordie0608 wouldn't it be fine to have the AI be deconstructable only if dead?

**Comment by GunHog** [comment] 2016-08-11 19:40
Codewise, the easiest way would be to allow deconstruction of an inactive AI core. Card the AI, then dismantle its core. But, that runs counter to what you requested. In order to do that, the original core that housed the AI would have to store the brain, which would be empty if deconned while the AI is in another location. You would also have to prevent brain-swapping shenaggains for people who would..say...build a second AI, swap cores with the roundstart AI, then stuff them back into each other's brains.

You are starting to see why AIs cannot be deconstructed, yes?

**Comment by PKPenguin321** [comment] 2016-08-11 19:51
there is literally nothing wrong with that gunhog

**Comment by PKPenguin321** [comment] 2016-08-11 19:51
in fact that sounds like a really rad idea

**Comment by Jordie0608** [comment] 2016-08-11 21:09
If it's just to remove the AI core entirely that's fine; however the issue specifically mentions getting the brain back which is, as gun hog said, a fiddly manner.

**Comment by jughu** [comment] 2016-08-11 22:28
Make the brain turn into a famebrain after getting aied

**Comment by jughu** [comment] 2016-08-11 22:28
FAME

**Comment by Faltnor** [comment] 2016-08-20 10:23
If you finish building one without a brain, you cannot take the screen off and put the brain in and that sucks. This is totally a bug.

**Comment by ChangelingRain** [comment] 2016-10-19 02:16
I fixed faltnor's problem recently-ish but it's not actually the bug~

**Closed** 2019-07-11 22:40 UTC
Labels: Consistency Issue, Not a bug
