### ISSUE TITLE
RCDs don't go in containers when you click on them

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63616] opened 2021-12-25 10:49 UTC
Reporting client version: 514.1571

## Round ID:
[175401](https://scrubby.melonmesa.com/round/175401)

## Testmerges:
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [Untested: Fix outfit equipping not working](https://www.github.com/tgstation/tgstation/pull/63606)

## Reproduction:
1. Click on belt or bag with an RCD
2. Won't go in
3. Click on slot in belt or bag with an RCD
4. Goes in

**Comment by Fikou** [comment] 2021-12-25 11:51
rcds override attack() i think

**Comment by MrMelbert** [comment] 2021-12-26 01:48
Dupe of #61576

**Closed** 2021-12-26 02:13 UTC
Labels: Oversight
