### ISSUE TITLE
Blob spores don't aggro through blob tiles

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56051] opened 2021-01-09 00:58 UTC
## Reproduction:
Be a blob, make a factory node. Have a hostile mob outside of the blob. Notice blob spores won't see the hostile until they leave the blob or are right next to it, making them way less useful than when blob wasn't dense.

**Comment by NotRanged** [comment] 2021-02-07 16:31
https://github.com/tgstation/tgstation/pull/55495

"@TemporalOroboros canastarpass checks pass flags it should work"
_narrator: It didn't._

**Comment by interestingusernam3** [comment] 2021-07-28 19:56
Related to #56050

**Comment by Mooshimi** [comment] 2021-10-17 06:18
#56742 dupe of this issue but that one has more info about the issue in the comments even though it was made later

**Closed by Mooshimi** 2021-10-17 06:18 UTC
Labels: Bug
