### ISSUE TITLE
Swapping glasses leaves the effect

### ISSUE THREAD

**Issue by Megadeadly** [tgstation/tgstation#51390] opened 2020-05-30 09:09 UTC
Issue reported from  Round ID: [138328](https://scrubby.melonmesa.com/round/138328) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1524

I don't know what causes this, but quick swapping glasses (default key for this is V), can leave you the effects of the swapped glasses. IE, the one I found to always work, was medhud swapped with anything else. As an example, I could swap from medhud, to NVGs, and have both the NVGs effect, and the medhud's effect at the same time, even though the medhud has been unequipped.

**Comment by ATH1909** [comment] 2020-05-30 21:25
I think I've already reported this, but nobody cared.

This works with non-glasses items too, by the way, including krav maga gloves. Krav maga gloves work in a weird way with this trick, actually: You get to keep your krav maga after using this trick to take them off, but if someone ELSE wears the gloves after that, then you'll lose your special krav maga action buttons... but keep the special krav maga default harm_act() and default disarm_act() moves (making you unable to shove people, because you'll just do that lame krav maga stamina damage hit instead).

**Comment by nemvar** [comment] 2020-06-02 06:19
Dupe of https://github.com/tgstation/tgstation/issues/50798

**Closed by nemvar** 2020-06-02 06:19 UTC
Labels: In Game Exploit, Oversight
