### ISSUE TITLE
Bug: randomly teleported to the debug room from a engineering borg to my MMI?

### ISSUE THREAD

**Issue by latin313** [tgstation/tgstation#71274] opened 2022-11-15 05:39 UTC
Reporting client version: 514.1589

## Round ID:
[194366](https://scrubby.melonmesa.com/round/194366)

## Testmerges:
- [New Station Trait: Cybernetic Revolution + Body Purist Quirk](https://www.github.com/tgstation/tgstation/pull/71229)
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

**Comment by timothymtorres** [comment] 2022-11-15 06:31
Duplicate of #71252

**Closed by timothymtorres** 2022-11-15 06:31 UTC
