### ISSUE TITLE
Box armory is missing its medkit again

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17747] opened 2016-05-17 20:53 UTC

**Comment by Eaglendia** [comment] 2016-05-17 21:03
inb4 "not a bug"

**Comment by Aloraydrel** [comment] 2016-05-17 21:19
A meme of the ages

**Comment by GunHog** [comment] 2016-05-17 21:48
What is it with the armory and that medkit? Seriously. @Steelpoint

**Comment by Steelpoint** [comment] 2016-05-18 08:23
Someone hates it.

I don't know, I haven't touched the map in months. I'm sure if I went through all the merged PR's recently I could find whoever removed the medkit.

**Comment by KorPhaeron** [comment] 2016-05-18 08:29
We already know which PR it got removed in

**Closed** 2016-05-25 00:06 UTC
Labels: Bug, Map Issue
