### ISSUE TITLE
Safe malfunctioning

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#26567] opened 2017-04-25 18:27 UTC
A player asked for help but I really, really don't understand how safes work.

http://puu.sh/vvVG1/ac66f7c24b.png

**Comment by KorPhaeron** [comment] 2017-04-25 20:00
The safe has been able to generate impossible combos for like five years now

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-04-26 15:44
That's why it's /safe/ :^)

**Comment by PKPenguin321** [comment] 2017-04-27 05:15
>The safe has been able to generate impossible combos for like five years now

On that note this issue is a dupe of an accent issue

**Comment by Tacolizard** [comment] 2017-04-27 21:17
the entire safe system needs to be rewritten

**Comment by ShizCalev** [comment] 2017-10-03 22:22
Duplicate of #12474

**Closed by ShizCalev** 2017-10-03 22:22 UTC
Labels: Bug
