### ISSUE TITLE
Art canvases that are drawn on are in some cases invisible to others

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17427] opened 2016-05-06 00:19 UTC
not as in the drawing is invisible, as in 100% invisible. usually to people who were not observing it being drawn on.

**Comment by Incoming5643** [comment] 2016-05-06 08:56
might have something to do with resource caching with fcopy_rsc

**Comment by WJohn** [comment] 2016-06-15 11:41
Can confirm, this is extremely common. I'd say almost 50% of people can't see your art.

**Comment by RemieRichards** [comment] 2016-06-15 12:55
this is Byond's fault, could try forcing a new asset to be sent every 10 or so pixels I guess.

**Comment by SpaceManiac** [comment] 2018-06-01 06:37
Duplicate of #24241

**Closed by SpaceManiac** 2018-06-01 06:37 UTC
Labels: BYOND Issue, Bug
