### ISSUE TITLE
Can't use Telekinesis while cuffed.

### ISSUE THREAD

**Issue by Nebulacrity** [tgstation/tgstation#52175] opened 2020-07-12 06:10 UTC
The title speaks for itself.

## Reproduction:
1) Obtain the Telekinesis mutation. 
2) Have someone cuff you or use zipties on you. 
You will find that you can't use Telekinesis in this state. My assumption is that it's because there are two cuff/ziptie items in your hands, thus making the game think the hands are full.

**Comment by necromanceranne** [comment] 2020-07-12 06:37
This is not a bug? I mean it obviously requires you have an open hand to use telekinesis, but I feel this is vaguely deliberate to prevent things like attacks while you lack handuse.

**Comment by Nebulacrity** [comment] 2020-07-12 07:27
Preventing attacks can be done in a different way without impeding valid use of a mutation.

**Comment by Dennok** [comment] 2020-07-12 07:35
Yes, i think about tin foil hat must block telekinesis and telepaty, and related stuff

**Comment by Nebulacrity** [comment] 2020-07-12 07:45
While that's unrelated, Dennok, it does sound nice.

**Comment by nightred** [comment] 2020-07-23 16:35
This is marked as not a bug, closing.

**Closed by nightred** 2020-07-23 16:35 UTC
Labels: Not a bug
