### ISSUE TITLE
you cant print rpd pipes in places where there is a open airlock

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47193] opened 2019-10-18 14:39 UTC
steps: go in a place with an airlock
open airlock
try print a pipe in that tile
notice nothing happens
drag a pipe there
wrench it
pipe works

**Comment by nemvar** [comment] 2019-10-18 14:53
Duplicate of https://github.com/tgstation/tgstation/issues/47139

**Closed by nemvar** 2019-10-18 14:53 UTC
