### ISSUE TITLE
You cannot change hair color via the character preferences menu. Attempting to seems to default it to black.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#48709] opened 2020-01-10 05:15 UTC
Issue reported from  Round ID: 127830 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by kriskog** [comment] 2020-01-10 05:41
Duplicate of #48666

**Closed by kriskog** 2020-01-10 05:41 UTC
