### ISSUE TITLE
Concealed weapon bay doesn't work

### ISSUE THREAD

**Issue by Tarhalindur** [tgstation/tgstation#55856] opened 2020-12-31 04:08 UTC
Reporting client version: 513.1530

## Round ID:
[153250](https://scrubby.melonmesa.com/round/153250)

## Testmerges:
- [Refactors monkeys into a species](https://www.github.com/tgstation/tgstation/pull/55614)
- [LINDA Reforged](https://www.github.com/tgstation/tgstation/pull/55604)

## Reproduction:

1. Be roboticist
2. Be traitor
3. Order the concealed weapon bay
4. Try to get it to work (ex. insert a weapon into it, insert it into the mech and then insert a weapon into the mech)
5. Fail
6. Give up, bomb the halls

"

**Comment by zxaber** [comment] 2021-01-03 17:57
For clarity, did you attempt to use the weapon bay on a mech with a plasma cutter installed? The code is super fuck, and attempting to attach a weapon to a Ripley with the weapon bay will check if any weapon equipment is already installed. Since the cutter is an energy weapon (even though it does basically no damage and is already allowed on Ripley and Clarke mechs) it is considered to be taking up the weapon bay slot.

If a plasma cutter was not involved, then it's a new bug that's popped up recently.

**Comment by necromanceranne** [comment] 2021-02-07 13:24
Just tested this, and it is in fact as zxaber has suggested. The problem is clearly that the plasma cutter is taking up this same slot, and needs to be differentiated from actual weapons in the code. Otherwise, this probably should be closed as it's somewhat inaccurate now.

**Closed by necromanceranne** 2021-02-07 13:24 UTC
Labels: Not a bug, Tested/Reproduced
