### ISSUE TITLE
Unable to Pull Resources out of Ore Silo Linked Machines

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#45194] opened 2019-07-15 08:36 UTC
## Round ID:
113172 and 113176
## Reproduction:
Unable to pull resources out of machines connected to the ore silo. The one exception is the ORM. Additionally, robo fabricators do not list required resources for building an item.

**Comment by kriskog** [comment] 2019-07-15 14:49
You should be including testmerges. In this case it is caused by one: #45118

**Comment by optimumtact** [comment] 2019-07-16 01:05
if it's a test merged bug please report it on the PR and then close the issue

**Closed by optimumtact** 2019-07-16 01:05 UTC
Labels: Bug

**Comment by Qustinnus** [comment] 2019-07-19 19:04
fixed

**Comment by adamkad1** [comment] 2019-08-18 00:29
its still like this on terry
