### ISSUE TITLE
Space heaters seem to loose all their power instantly if exposed too eextreme of a temptures 

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#84358] opened 2024-06-26 17:55 UTC
## Issue Summary

Basically space heaters will just kill the power in the cells they start out with if they are exposed to air that is colder than 150k or more but I'm not sure if the amount of air in the room will effect it on how much more quickly it'll drain as I noticed that as the air starts to warm up it'll use less and less power and cell with in will last much longer

## Reproduction:
Just cool down a room to bellow 150k or 200k

**Comment by GPeckman** [comment] 2024-06-26 17:57
Duplicate of #84329

**Comment by SyncIt21** [comment] 2024-06-26 18:31
@DATA-xPUNGED there's no need to add a clean up flag. Just close it as a duplicate,

**Closed** 2024-06-26 18:50 UTC
Labels: Cleanup Flagged
