### ISSUE TITLE
voice of god font issue

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#43040] opened 2019-03-06 17:35 UTC
basically if you speak in voice of god and it gets italicized from anything, it will always be italicized whenever you try to speak with it in the future. Not really gameplay affecting but it's annoying to be stuck with italicized text after speaking in low atmos with it once. Only applies to the font voice of god uses from what i saw.

**Comment by Cyprex** [comment] 2019-03-11 12:09
Sounds like someone forgot a closing </i> tag

**Comment by dragomagol** [comment] 2020-12-07 21:26
Unable to reproduce, likely fixed

**Closed by dragomagol** 2020-12-07 21:26 UTC
Labels: Bug
