### ISSUE TITLE
Writing things on paper does not work in most situations

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#52797] opened 2020-08-08 10:17 UTC
## Round ID:
[143784](https://scrubby.melonmesa.com/round/143784) and [143766](https://scrubby.melonmesa.com/round/143766)

## Testmerges:
[READY] Mafia Lobby Reworks, Panel Redesign, Abstaining, and More. #52458

## Reproduction:
When writing on paper the save feature will sometimes clear the paper instead of saving it. I'm under the assumption that the character limit is 5000 characters from what I've been told on discord. The text I was trying to save was 2900. Short text documents will save however attempts to add new text to short documents has varied results, (sometimes works sometimes does not.).

**Comment by NamelessFairy** [comment] 2020-08-09 15:32
Update, this is incredibly inconsistent. I've seen other players try it and experience the same results while other have no issue what so ever. I've also encountered a crash while attempting to put a give or take 1000 character paragraph into paper.

**Comment by timothymtorres** [comment] 2021-12-26 11:32
Duplicate of #51774

**Closed by timothymtorres** 2021-12-26 11:32 UTC
Labels: Bug
