### ISSUE TITLE
Xenobiology Mobs do not ask ghosts before forcing them into sentience

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#27253] opened 2017-05-14 08:41 UTC
This ends up with the mobs being occupied with either busy admins or afk ghosts 90% of the time because there is no prompt for the role.  It merely grabs the ghost and stuffs it into the body.

**Comment by QualityVan** [comment] 2017-05-14 08:46
Is this with sentience potions or something else?

**Comment by cedarbridge** [comment] 2017-05-14 08:55
Yeah, sentience potions.

**Comment by Dorsisdwarf** [comment] 2017-05-14 10:31
dupe of #27133

**Closed by Dorsisdwarf** 2017-05-14 10:31 UTC
Labels: Bug
