### ISSUE TITLE
.310 stripper clips for the Sakhno Precision Rifle that centcom interns get is bugged.

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87580] opened 2024-10-30 13:24 UTC
### Client Version:

515.1645

### Issue Summary:

The .310 strika stripper clips can only load the first round in the entire stripper clip per each clip, then refusing to load any more bullets

manual dropping of the casings and loading them into the rifle while the bolt is open seems to work correctly
which beats the entire point of having a stripper clip in the first place

### Round ID:

[241030](https://scrubby.melonmesa.com/round/241030)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)](https://www.github.com/tgstation/tgstation/pull/87434)

### Reproduction Steps:

1. spawn as centcom intern ERT
2. shoot rifle until its empty
3. open the bolt
4. try to use the stripper clip in your pockets
5. 1 ammo loads, rest refuses to load
6. use the other stripper clip
7. also 1 casing loads, rest refuses to load
8. have to dump out the casings on the floor and manually load the casings one by one to reload

**Comment by SmArtKar** [comment] 2024-10-30 13:27
Duplicate of #87559, fix PR is up

**Closed by SmArtKar** 2024-10-30 13:27 UTC
