### ISSUE TITLE
Exploration drone has one less equipment/cargo slot than displayed

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#67973] opened 2022-06-24 05:35 UTC
RoundID 185457

doing explorer drone stuff, have one open slot in the drone,  but items are getting auto dropped because theres' no cargo space despite the empty spot

**Comment by Sealed101** [comment] 2023-08-07 05:43
Duplicate of #66085

**Closed** 2023-08-07 05:43 UTC
Labels: Bug
