### ISSUE TITLE
fake pipe in pubby sci toxin room

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41675] opened 2018-11-25 17:58 UTC
the output toxin pipe in the wall isnt real

97619

**Comment by 81Denton** [comment] 2018-11-25 19:35
Which one of these?

![weed](https://user-images.githubusercontent.com/32391752/48983631-a886ef00-f0f1-11e8-851b-20f85439c69a.PNG)

**Comment by Tlaltecuhtli** [comment] 2018-11-25 20:57
http://take.ms/dT7Wm
i wasnt unable to wrench unwrench it ( it was hitting instead) and the air wasnt moving trough it i had to break it with a welder and put a new pipe on the wall

**Comment by nicbn** [comment] 2018-11-26 01:46
It is a real pipe
The pipenet "clogging" and making the pipes unable to be unwrenched is an old bug

**Comment by Potato-Masher** [comment] 2018-11-26 06:35
This happened to me and another scientist a while back, basically the same thing that happened here.

**Comment by nicbn** [comment] 2018-11-26 15:52
@SpaceManiac This is not a map issue, there's nothing wrong with the specific pipe, it's a bug that can happen with seemingly any pipenet

**Comment by 81Denton** [comment] 2018-11-26 16:21
Like this one? #36642

**Comment by ShizCalev** [comment] 2018-11-27 16:56
Duplicate of #36642

**Closed by ShizCalev** 2018-11-27 16:56 UTC
Labels: Map Issue
