### ISSUE TITLE
Wizard's rod form and gravgen interaction

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#78664] opened 2023-09-28 11:42 UTC
## Reproduction:
Fly away from gravgen room's 'high gravitation' field with Rod form, keep slowdown status until you go back in and walk away without Rod form.

**Comment by Sealed101** [comment] 2023-09-28 12:25
related, essentially a duplicate of #75480 #76380

**Closed** 2024-12-06 18:05 UTC
Labels: Bug
