### ISSUE TITLE
Extra space after beginning and before ending quotation marks in speech

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#48688] opened 2020-01-08 23:53 UTC
This has been around for a while now. I believe it's caused by Goonchat because they're not there when you switch to old chat. Also saving logs/screenshots with Goonchat sucks compared to old chat.

[Common] Mark Zuckerberg  says, " .a Dumb fucks. " 
The newscaster  beeps, " Breaking news from Fox and Friends! "
H.P. Lovecraft  says, " Damned dirty apes "

**Comment by kriskog** [comment] 2020-01-09 13:01
Duplicate of #28876

**Closed by kriskog** 2020-01-09 13:01 UTC

**Comment by kriskog** [comment] 2020-01-25 15:03
Gone for me after 513, are you still seeing this?

**Comment by cacogen** [comment] 2020-01-25 22:49
Nope

**Comment by kriskog** [comment] 2020-01-25 23:25
Good, thanks
