### ISSUE TITLE
Chameleon thermals don't work

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#33818] opened 2017-12-24 16:31 UTC
Issue reported from Round ID: 80717 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Tried to put chameleon thermals on only to have them turn my entire screen black and not work at all (not even showing anyone in the darkness.)

**Comment by ShiggyDiggyDo** [comment] 2017-12-24 18:44
Dupe #33409

**Comment by Cyberboss** [comment] 2017-12-24 19:50
Duplicate of #33409

**Closed by Cyberboss** 2017-12-24 19:50 UTC
