### ISSUE TITLE
magic invisible uninteractable pipes

### ISSUE THREAD

**Issue by benman347** [tgstation/tgstation#61308] opened 2021-09-08 22:49 UTC
## Round ID:
[169247](https://scrubby.melonmesa.com/round/169247)

## Testmerges:
61246

## Reproduction:

not sure if its caused by the testmerge not sure how to reproduce i was a changeling so that might have been a factor and i was just building pipes. All pipes I made after I think 40 min turned invisible and not interactable turning the rapid to disposals and back fixed the rpd but magic invisible pipes still remained.
These pipes can not be removed or seen but still interact with other pipes.
They therefore block you from placing a different pipe there later.

Also it was on icebox so it might be a problem with only icebox. attached is a screencap of it with "helpful" arrows

![glitch_tg4](https://user-images.githubusercontent.com/62154137/132595566-544e8e88-589a-410e-b883-69626374f8d0.PNG)

**Comment by LemonInTheDark** [comment] 2021-12-04 03:27
Potentially related to https://github.com/tgstation/tgstation/issues/63144

**Comment by Mooshimi** [comment] 2022-08-08 04:55
closing this in favor of #69063 since that issue has reproduction steps

**Closed by Mooshimi** 2022-08-08 04:55 UTC
Labels: Bug, Atmospherics
