### ISSUE TITLE
Runtime in obj_defense.dm,26: bad index

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#24953] opened 2017-03-10 21:42 UTC
[23:37:43] Skipped 1039 runtimes in obj_defense.dm,26.
[23:37:44] Runtime in obj_defense.dm,26: bad index
[23:37:44] Runtime in obj_defense.dm,26: bad index
[23:37:45] Runtime in obj_defense.dm,26: bad index
[23:37:45] Runtime in obj_defense.dm,26: bad index
[23:37:46] Runtime in obj_defense.dm,26: bad index
[23:37:46] Runtime in obj_defense.dm,26: bad index
[23:37:48] Runtime in obj_defense.dm,26: bad index
[23:37:49] Runtime in obj_defense.dm,26: bad index
[23:37:51] Runtime in obj_defense.dm,26: bad index
[23:37:52] Runtime in obj_defense.dm,26: bad index
[23:37:52] Runtime in obj_defense.dm,26: bad index
[23:37:52] Runtime in obj_defense.dm,26: bad index
[23:37:54] Runtime in obj_defense.dm,26: bad index
[23:37:54] Runtime in obj_defense.dm,26: bad index
[23:37:55] Runtime in obj_defense.dm,26: bad index
[23:37:55] Runtime in obj_defense.dm,26: bad index
[23:37:55] Runtime in obj_defense.dm,26: bad index
[23:37:55] Runtime in obj_defense.dm,26: bad index
[23:37:57] Runtime in obj_defense.dm,26: bad index
[23:37:57] Runtime in obj_defense.dm,26: bad index
[23:37:57] Runtime in obj_defense.dm,26: bad index
[23:37:58] Runtime in obj_defense.dm,26: bad index
[23:37:58] Runtime in obj_defense.dm,26: bad index
[23:37:58] Runtime in obj_defense.dm,26: bad index
[23:37:59] Runtime in obj_defense.dm,26: bad index
[23:37:59] Runtime in obj_defense.dm,26: bad index
[23:37:59] Runtime in obj_defense.dm,26: bad index
[23:38:01] Runtime in obj_defense.dm,26: bad index
[23:38:01] Runtime in obj_defense.dm,26: bad index
[23:38:03] Runtime in obj_defense.dm,26: bad index
[23:38:03] Runtime in obj_defense.dm,26: bad index

**Comment by Cyberboss** [comment] 2017-03-10 22:11
This is caused by things not calling the base of Initialize.

I believe the current instance of it was fixed by @AnturK

**Comment by AnturK** [comment] 2017-03-10 22:13
Yeah fixed in #24930

**Comment by Jordie0608** [comment] 2017-04-04 07:40
Fixed I guess

**Comment by Cyberboss** [comment] 2017-04-04 11:54
Not sure about that...

**Comment by Jordie0608** [comment] 2017-04-04 12:03
I can't see it in today's runtimes.

**Comment by Jordie0608** [comment] 2017-04-04 12:04
Nevermind found it in yesterday~

**Comment by AnturK** [comment] 2017-04-04 12:06
Probably some other uninitialized object, this issue is kinda useless to keep track of these.

**Closed** 2019-03-28 04:48 UTC
Labels: Runtime
