### ISSUE TITLE
Nebulastation evac shuttle broken when viewed from z level above

### ISSUE THREAD

**Issue by bl4ckj4ck1924** [tgstation/tgstation#84932] opened 2024-07-13 06:48 UTC
## Issue Summary
When in space a z level above the area where the evacuation shuttle docks on Nebulastation, the space taken up by the evacuation shuttle appears to be filled with 'shit is fucked, yell at mappers' tiles
This was on Manuel while spectating as a ghost, the shuttle was the snappop shuttle
![tgStation Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE  Book Object Rho 2024-07-13 183508](https://github.com/user-attachments/assets/a9ee1cc1-e97d-4dbc-97cc-a9673c54edbb)
![tgStation Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE  Book Object Rho 2024-07-13 183514](https://github.com/user-attachments/assets/d22ac851-205e-4a4d-bb67-4f08edb17607)

## Round ID:
[232040](https://scrubby.melonmesa.com/round/232040)

## Reproduction:
Step 1: Be ghost on Manuel (or maybe just be in space and not blind)
Step 2: Be on upper z level of nebula station in the area just above departures, and able to see space
Step 3: Wait for evac shuttle to dock (but before it leaves)
Step 4: Shuttle may or may not have broken tiles

**Comment by Sadboysuss** [comment] 2024-07-13 07:17
Duplicate of https://github.com/tgstation/tgstation/issues/84597
This is a thing with all multi-z shuttles

**Closed** 2024-07-13 08:01 UTC
