### ISSUE TITLE
unable to crush people with hydraulic clamp

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#71924] opened 2022-12-11 10:45 UTC
## Reproduction: be posibrain, attach hydraulic clamp to ripley, activate combat mode, click on person, get the message "you longingly wish to tear [name]'s arms off" instead of crushing them, now this may not be a bug but i dont know if its been documented at all, or if its related to posibrains/mmi/AI only
![Screenshot_3030](https://user-images.githubusercontent.com/64584757/206898381-17511cbd-9d35-46f1-9de0-0e9edf84affa.png)

**Comment by timothymtorres** [comment] 2022-12-11 11:05
Duplicate of #67580

**Closed by timothymtorres** 2022-12-11 11:05 UTC
