### ISSUE TITLE
Krokodil addiction broke?

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56220] opened 2021-01-17 04:55 UTC
RoundID 154405

i tried this a few weeks ago with the same results but didnt bother posting the issue till now
-take atleast 19u of krokodil
-wait for it all to process
-be disappointed as you cannot become krokodil zombie

overdose effect works fine so i dont know whats going on here

**Comment by nightred** [comment] 2021-01-21 18:09
Duplicate of #55245

**Closed by nightred** 2021-01-21 18:09 UTC
Labels: Bug
