### ISSUE TITLE
Honker projectiles bouncing between directional windows causes client and server crashing lag

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#40283] opened 2018-09-14 18:42 UTC
[Round ID]: #93881 YOU'RE GONNA GET A LOT OF MILEAGE OUT OF THE LOGS FROM THIS ROUND OH BOY

Honker projectiles don't agree with directional windows, or windoors, too well. Reinforced, and normal glass alike. They just bounce and bounce and bounce, creating giant stacks of effects and at one point knocked everyone's ping up to 4000.

They do not have this problem with full tile windows.

One single honker projectile can crash your client, if you shoot it onto a tile completely enclosed in directional windows.

**Comment by Barhandar** [comment] 2018-09-14 18:58
>and at one point knocked everyone's ping up to 4000.

Or rather, basically frozen the game.

**Comment by AnturK** [comment] 2018-09-14 20:47
Duplicate of #39772

**Closed by AnturK** 2018-09-14 20:47 UTC
