### ISSUE TITLE
Using a slot machine seems to lag out the client while it spins

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76273] opened 2023-06-23 03:45 UTC
Reporting client version: 514.1589

## Round ID:
[208903](https://scrubby.melonmesa.com/round/208903)

## Reproduction:
Playing a slot machine, and being at the part while the numbers spin seem to end up lagging your client horribly while they spin, only for it to return to normal after it stops.
1. Find a slot machine
2. Insert Holochips
3. SPIN DA WHEEL.
4. Lag.
5. (Maybe win the slots?)

**Comment by SyncIt21** [comment] 2023-06-23 05:51
Duplicate of #71314

**Comment by Sealed101** [comment] 2023-06-23 09:29
Duplicate of #71314

**Closed by Sealed101** 2023-06-23 09:29 UTC
