### ISSUE TITLE
Genturf under Terrarium

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#76256] opened 2023-06-22 16:14 UTC
Reporting client version: 514.1589

## Round ID:
[208866](https://scrubby.melonmesa.com/round/208866)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Adds shark plushie, removes pickle Rick plushie](https://www.github.com/tgstation/tgstation/pull/76206)

## Reproduction:
1. Explode the Sentient Terrarium with Cherry Bombs at the end of the round
2. Genturf

**Comment by Sealed101** [comment] 2023-08-27 12:08
Duplicate of #57449

**Comment by Sealed101** [comment] 2023-08-27 12:08
in spirit anyway, but getting more ruins with this bug is good anyway

**Closed by Sealed101** 2023-08-27 12:08 UTC
Labels: Mapping
