### ISSUE TITLE
Dropping flesh form via the Ling menu does not return the player to their original identity.

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#58342] opened 2021-04-12 04:09 UTC
Reporting client version: 513.1542

## Round ID:
[160103](https://scrubby.melonmesa.com/round/160103)

## Reproduction:
1) Steal an identity as a ling player
2) Assume that identity
3) Drop Flesh form via the ling menu
4) Observe the player fails to return to their original identity.

**Comment by Y0SH1M4S73R** [comment] 2021-04-12 06:56
I'm no maintainer, but this doesn't sound like a bug. Dropping the flesh disguise removes the fake items that transforming tries to put on you to make you look exactly like the person whose identity you stole at the moment you stole their identity.

**Comment by necromanceranne** [comment] 2021-04-12 09:49
This is indeed not a bug, but more of a consequence of lings having a limited pool of identities that they overwrite as they absorb more.

Which is where but there you go. I'm going to close this one since it is, as @Y0SH1M4S73R explains, not the intent of that ability.

**Closed by necromanceranne** 2021-04-12 09:49 UTC

**Comment by Zargoar** [comment] 2021-04-13 00:06
I reckon it'd be nice if things were called out more clearly.
