### ISSUE TITLE
Lavaland Eskimo Ruin Full of Genturfs

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#63746] opened 2022-01-01 12:31 UTC
Reporting client version: 514.1561

## Round ID:
[173128](https://scrubby.melonmesa.com/round/173128)

## Testmerges:
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)

## Reproduction:
See attached. Exploded a 0 reaction gibtonite chunk to break into the treasure room of the lavaland eskimo ruin (the one full of snow and ice, with 4 skeletons in science hoodies wielding spears), and it looks like every tile it destroyed had a genturf under it

![Ice Dome](https://user-images.githubusercontent.com/88996803/147850606-21630758-59fe-4280-bcaf-c9f5d7ea9620.png)

**Comment by timothymtorres** [comment] 2022-01-01 22:47
Duplicate of #57449

**Closed by timothymtorres** 2022-01-01 22:47 UTC
Labels: Mapping, Bug
