### ISSUE TITLE
There is space on lavaland

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19954] opened 2016-08-18 20:35 UTC
![image](https://cloud.githubusercontent.com/assets/6778786/17789798/c53cf540-6561-11e6-9b43-e0d02d267d9c.png)

I think this is the construction site

**Comment by GunHog** [comment] 2016-08-18 20:46
Oh. God. How do I even fix this. Why does the mining shuttle not do this when blown up? How would I make sure the aux base deconstructs to space on the station, and volcanic floor on lavaland without snowflake checks?

# HELP

**Comment by KorPhaeron** [comment] 2016-08-18 20:48
Baseturfs gunhog

**Comment by GunHog** [comment] 2016-08-18 20:53
It would have to remain set to space while docked at the station, and turned to lavaland base turfs upon landing. What is the best way to do that?

**Comment by bobdobbington** [comment] 2016-08-19 13:44
There's space everywhere, man.

**Comment by TechnoAlchemisto** [comment] 2016-08-20 05:39
everyone knows lavaland is a disk in space fucknuts

**Comment by MrStonedOne** [comment] 2016-08-20 09:48
just make a new mobile type, over ride it's dock, and assign the proper basetype after a ..()

**Comment by Kromgar** [comment] 2016-12-23 23:28
![image](https://cloud.githubusercontent.com/assets/6778786/21447201/2bf0e95e-c89f-11e6-9205-d5261563a436.png)


It happened again

**Comment by Kromgar** [comment] 2017-03-22 23:27
![image](https://cloud.githubusercontent.com/assets/6778786/24225191/975d91ce-0f35-11e7-84ae-9f46d9b0d7db.png)

@Jordie0608  

ITS GETTING WORSE

**Comment by KorPhaeron** [comment] 2017-03-23 02:02
@Cyberboss 

please fix this soon thanks

**Comment by Cyberboss** [comment] 2017-03-23 02:03
Ree

**Comment by Cyberboss** [comment] 2017-03-23 03:39
Dupe of #19954

**Closed** 2017-03-25 19:28 UTC
Labels: Bug, Map Issue
