### ISSUE TITLE
Floor tile was able to be pried up infinitely

### ISSUE THREAD

**Issue by StrawberryMoses** [tgstation/tgstation#47812] opened 2019-11-15 22:47 UTC
## Reproduction:

During this round, at some point there was an explosion in the hall adjacent to the lawyer office and the captains office. Later in the round I went to fix it, and I was able to pry up a floor tile an infinite number of times, giving me an infinite number of floor tiles. An admin tried to fix by placing a wall over it and removing, but I was still able to after. I'm not sure what caused this glitch.

**Comment by ShizCalev** [comment] 2019-11-16 06:11
if this occurs again poke me on discord asap.

**Comment by Tharcoonvagh** [comment] 2019-11-16 08:15
Possible metacomms, ban them all

**Comment by ShizCalev** [comment] 2019-11-17 02:13
![image](https://user-images.githubusercontent.com/6209658/69001983-e1494680-08b5-11ea-9606-a40b5e0ddb54.png)

**Comment by ShizCalev** [comment] 2019-11-17 02:13
broken should be 1 / true, there was a floorbot in the area. initial damage occurred via explosion.

**Comment by ShizCalev** [comment] 2019-11-17 02:22
does seem to be related to floorbots repairing floors.

**Comment by ShizCalev** [comment] 2019-11-17 02:22
likely culprit seems to be floorbots repairing the floors.

**Comment by ShizCalev** [comment] 2019-11-17 02:24
https://github.com/tgstation/tgstation/blob/3d962472a249762f7498f5245519bc3f8dc4fa0a/code/modules/mob/living/simple_animal/bot/floorbot.dm#L339-L344

**Comment by ShizCalev** [comment] 2019-11-17 02:28
https://github.com/tgstation/tgstation/blob/43ebb03e8c974fb6887ecb48bdbb0b462372b6a3/code/game/turfs/open/floor/plasteel_floor.dm#L11-L15

the check for the parent is always 0, so that's why icons aren't updating properly to start with.

**Comment by ShizCalev** [comment] 2019-11-17 02:29
same issue for plating

**Comment by ShizCalev** [comment] 2019-11-17 02:31
https://dl.dropboxusercontent.com/s/mxevremvwx107zt/2019-11-16_21-31-42-firefox-Refactors_screen_object_update_icon_to_call_parent.png

**Comment by ShizCalev** [comment] 2019-11-17 02:32
icon is broken by #47094 @ninjanomnom

**Comment by ShizCalev** [comment] 2019-11-17 03:55
https://dl.dropboxusercontent.com/s/0u5dmbd3ojwnu40/2019-11-16_22-55-06-Code-mineral_floor.dm_-_tg_Workspace__-_Visual_Studio_.png

**Comment by ShizCalev** [comment] 2019-11-17 03:55
![image](https://user-images.githubusercontent.com/6209658/69002801-2c6a5600-08c4-11ea-9a7e-260bf2ed62bf.png)

**Comment by iprice** [comment] 2020-01-12 07:20
Ran into this tonight round 127969 on Terry, engineering got burned out and rather than replace the floor I built a couple of floorbots and left them to it.  Encountered the "infinitely pryable" floor tile which I later reproduced in private on the latest upstream/master branch.

I suspect you already figured this out, but basically burn a room down with plasma or whatever, throw in a few floor bots and then start prying up their work ; it pries infinitely.

**Comment by iprice** [comment] 2020-01-12 07:22
![floor-tile-problems](https://user-images.githubusercontent.com/3789327/72215572-2da6b080-350c-11ea-9393-3aa23c149319.PNG)

Broken floor tile on the left, correct on the right.  I finally found this as the key difference and fixed a few tiles by updating this baseturfs list to match the list on the right, after which the tile would pry as normal.

**Comment by ShizCalev** [comment] 2020-08-07 03:54
Duplicate of #37421

**Closed by ShizCalev** 2020-08-07 03:54 UTC
Labels: In Game Exploit, Needs Reproducing
