### ISSUE TITLE
Unexplained/Inconsistent Supermatter Delamination

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#33507] opened 2017-12-13 13:17 UTC
This has happened twice now both on metastation.

First occasion was a couple days ago (cannot remember the round ID), the round had just started, one projectile from one emitter was fired into the SM accidentally before the cooling loop was properly set up.  Normally this might start to slowly delaminate but give plenty of time to fix it, instead it gave one warning of "Integrity: 97%"  and then exploded a couple seconds after. 

Second occasion, just now, round 80126, the SM was set up correctly, plenty of coolant (N2/N2O mix), very cold, it had not been tampered with (at least as far as I can tell from the logs and through asking people), and it only had 3 emitters firing into it.  It gave one warning of "Integrity: 83.06%" and then exploded a couple seconds after.

Both occasions resulted in a huge explosion (much larger than usually seen with the whole of atmospherics destroyed and more) and creating a very large angry tesla with many balls.

**Comment by praisenarsie** [comment] 2017-12-13 16:50
engine logging has been a due logging revamp since forever

**Comment by CPTANT** [comment] 2018-03-24 15:54
Most likely dupe of #28638

**Comment by CPTANT** [comment] 2018-04-04 09:25
@KorPhaeron

**Closed** 2018-04-04 13:58 UTC
Labels: Consistency Issue, Needs Reproducing
