### ISSUE TITLE
Plague doctor mask no longer supports using oxygen tanks

### ISSUE THREAD

**Issue by TheWolfbringer** [tgstation/tgstation#85007] opened 2024-07-16 06:43 UTC
## Issue Summary
Try using plague doctor mask to breathe from a oxygen tank.
It doesn't let you.

## Round ID:
[232178](https://scrubby.melonmesa.com/round/232178)
## Testmerges:

[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 36f1dfa793](https://www.github.com/tgstation/tgstation/pull/84826)
[#84951: 'Ghosts once again can see people's true names and roundstart jobs' by SmArtKar at commit 67b7238ae2](https://www.github.com/tgstation/tgstation/pull/84951)
[#84964: 'Reworks silicon/ai access checking & fixes some ui_act's' by JohnFulpWillard at commit 3951a2a798](https://www.github.com/tgstation/tgstation/pull/84964)

## Reproduction:
Obtain plague doctor mask. Obtain oxygen tank. Try using the plague doctor mask to breathe from the oxygen tank.

**Comment by Jackal-boop** [comment] 2024-07-16 14:45
Iirc it got changed because people were power gaming it

**Comment by DATA-xPUNGED** [comment] 2024-07-16 18:07
> Iirc it got changed because people were power gaming it

I looked for it and found no PR intentionally removing such a thing, the most recent PR touching it is #71316

**Comment by DATA-xPUNGED** [comment] 2024-07-16 18:10
Do note the description still implies you can use internals with it

**Comment by DATA-xPUNGED** [comment] 2024-07-16 18:17
![image](https://github.com/user-attachments/assets/81c6882d-480e-432d-9787-a8a290374992)
Well, testing on a localhost, it worked just fine?

**Comment by Sadboysuss** [comment] 2024-07-16 18:20
> > Iirc it got changed because people were power gaming it
> 
> I looked for it and found no PR intentionally removing such a thing, the most recent PR touching it is #71316 

Maybe https://github.com/tgstation/tgstation/pull/84953 but it doesn't look like that pr would cause this

**Comment by Sadboysuss** [comment] 2024-07-16 18:21
If you can reproduce this - send a video. Meanwhile this will be cleanup flagged and auto closed in 7 days

**Comment by DATA-xPUNGED** [comment] 2024-07-16 18:23
My apologies; My master was not updated to TG's, pulling it made the bug appears for me

**Comment by GPeckman** [comment] 2024-07-16 19:15
The mask also doesn't actually protect you from facehuggers as far as I can tell.

**Closed** 2024-07-17 18:40 UTC
Labels: Tested/Reproduced, Oversight
