### ISSUE TITLE
You now slap people with surgical drapes when using them on someone

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#52735] opened 2020-08-05 01:50 UTC
When using surgical drapes on someone, along with opening the menu, you will now also slap them with it. This kills my immersion, and didn't happen before.

Likely a result of #52295 .

**Comment by Timberpoes** [comment] 2020-08-05 04:10
Yup. Component system is async.

It's a race condition.

**Comment by ArcaneMusic** [comment] 2020-09-08 14:54
Was this fixed by the above PR?

**Comment by optimumtact** [comment] 2020-09-08 20:20
No I don't believe so, it just makes issues easier to spot.

**Comment by SuperNovaa41** [comment] 2022-01-09 03:09
Cannot reproduce, this probably no longer happens.

**Closed** 2022-01-11 01:46 UTC
Labels: Bug, Cleanup Flagged
