### ISSUE TITLE
Autolathe putting saws under itself.

### ISSUE THREAD

**Issue by Childflayer** [tgstation/tgstation#36594] opened 2018-03-21 07:35 UTC
Circular saws (and maybe other items?) produced by the autolathe are appearing under the autolathe instead of on top of the stack.

**Comment by Jalleo** [comment] 2018-03-21 09:14
Maybe reported already under a different item.

**Comment by ShizCalev** [comment] 2018-03-21 10:42
duplicate of #34405

**Closed by ShizCalev** 2018-03-21 10:42 UTC
