### ISSUE TITLE
Supply Console menu is bugged.

### ISSUE THREAD

**Issue by SkatesMcGates** [tgstation/tgstation#51380] opened 2020-05-29 23:35 UTC
Issue reported from  Round ID: [138303](https://scrubby.melonmesa.com/round/138303) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1508

![Screenshot (43)](https://user-images.githubusercontent.com/17814086/83313300-9c4a8900-a1e3-11ea-84fd-a439655e97b6.png)

This is how it appeared for me, no other players had this issue though so it may have been something on my end.

**Comment by stylemistake** [comment] 2020-07-16 19:31
Duplicate of #50480

**Closed by stylemistake** 2020-07-16 19:31 UTC
Labels: Bug, Needs Reproducing, UI
