### ISSUE TITLE
Pirates don't spawn on icebox

### ISSUE THREAD

**Issue by Pumpkinoe** [tgstation/tgstation#55773] opened 2020-12-27 22:38 UTC
## Reproduction:
Everything works as intended with pirates on icebox until you don't pay them - They just won't spawn at all. The prompt shows up to play as them but no ship is made, no pirates are spawned and nothing further happens.

**Comment by dragomagol** [comment] 2020-12-27 23:52
Related to #53689

**Comment by timothymtorres** [comment] 2021-12-28 10:03
Duplicate of #53689

**Closed by timothymtorres** 2021-12-28 10:03 UTC
Labels: Oversight
