### ISSUE TITLE
Aliens have no inhands for when they are cuffed.

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#3574] opened 2014-04-29 13:24 UTC
if an alien is handcuffed, there's no way to tell at all unless the alien uses the resist button.
It doesn't even show up while examining.

**Comment by phil235** [comment] 2015-08-24 15:10
The handcuffs does appear on the alien humanoid's UI now, and the examine will show if it's handcuffed after my next PR is merged.

The only issue that is hard to solve is the handcuff inmob sprite. The problem is that the regular handcuff sprite doesn't match the alien mob sprite. And even worse, you would need a special handcuff sprite for the resting position since simply rotating the handcuffs looks awful.
You would also need another handcuff sprite for larva, and another one for the large queen.

**Comment by Dorsisdwarf** [comment] 2015-08-27 11:18
Edited to reflect fixing of 2/3rds of issue

**Comment by Jalleo** [comment] 2015-11-03 16:09
@WJohn this is fixable by having a few sprites done by you to reflect this issue

**Closed** 2016-06-09 06:26 UTC
Labels: Not a bug, Sprites
