### ISSUE TITLE
metastation white ship doesnt work

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#35099] opened 2018-01-29 12:16 UTC
Issue reported from  Round ID: 82740 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Reproduction]: # go onto meta white ship
find out it doesnt work
cry

the navigation console was impossible to interact with, the shuttle console said "Status: *Missing*"

**Comment by vuonojenmustaturska** [comment] 2018-01-29 13:28
@coiax @ninjanomnom

**Comment by WJohn** [comment] 2018-01-29 13:48
missing json_key. easy fix.

**Comment by Marflowerose** [comment] 2018-01-29 16:13
Are you sure you weren't at the White Ship Ruin? That one has the broken consoles by design as it's a ruin. The actual ship with hydroponics, kitchen etc was working fine earlier.

**Comment by WJohn** [comment] 2018-01-29 16:30
Yeah I'm not seeing this error as a thing. The guitar white ship isn't an actual ship, so I'm closing this unless something else occurs.

**Closed by WJohn** 2018-01-29 16:30 UTC
Labels: Good First Issue, Map Issue
