### ISSUE TITLE
Volume pumps can stop working and permantently stop being able to move gas.

### ISSUE THREAD

**Issue by esainane** [tgstation/tgstation#56297] opened 2021-01-20 14:33 UTC
## Reproduction:

Spawn or otherwise acquire a canister of nitrogen. Use a RPD to build a connector beneath the canister, then build a volume pump away from the connector. turn the volume pump on, and connect the canister.

Check: Use an analyzer to verify that the volume pump's output node has >9000 kPa (should happen pretty much immediately).

Add a 4-way manifold off the volume pump. Use an analyzer to verify that gas has not moved, at all, from the volume pump's output node.

![ss13-broke-volume-pump-minitestcase](https://user-images.githubusercontent.com/14355175/105187469-b3d1ea00-5b97-11eb-9854-2bc560351251.png)

![ss13-broke-volume-pump-minitestcase-text](https://user-images.githubusercontent.com/14355175/105187472-b59bad80-5b97-11eb-89a0-c4f3e5da2a61.png)

You can come back 5 minutes later, and the volume pump still won't have added anything. Unwrenching and rewrenching the manifold will still not cause any gas to flow into it. Turning the volume pump off and on will not fix it. Unwrenching and rewrenching the volume pump can cause it to work again, at the expense of losing any gas currently inside.

Using VV to inspect the volume pump parents seems to show that the output pipeline correctly lists the manifold as a member, and the volumetric gas pump in other_atmosmch. No null gas_mixture in other_airs or other unusual properties detected.

Admin proc calling update_parents from the volume pump works around the problem, causing gas to flow and quickly settle.

Adding further pipes off the manifold will cause the gas to be distributed as expected. However if the volume pump had previously hit maximum pressure again (it will do this almost instantly if only filling one manifold), it will continue to not pump gas until update_parents is called again. Another call of update_parents will repeatedly pump gas (can confirm this works over multiple updates from one call) until the limit is hit.

This problem isn't necessarily limited to volume pumps, but this seems to be fairly reliably reproduced with them.

**Comment by kopoba** [comment] 2021-01-21 06:23
could not reproduce
![image](https://user-images.githubusercontent.com/5034345/105294155-b9005a80-5bd2-11eb-81c2-48e3f0c00f8c.png)

**Comment by LemonInTheDark** [comment] 2021-01-21 06:27
You've got the order wrong, the issue is that when you place one pipe down, it doesn't tell the attached pipeline to well, do something/wake up. It needs a delicate touch, but it is an issue

**Comment by kopoba** [comment] 2021-01-21 06:35
> 
> 
> You've got the order wrong, the issue is that when you place one pipe down, it doesn't tell the attached pipeline to well, do something/wake up. It needs a delicate touch, but it is an issue

yeh you right was able to reproduce

**Comment by duncathan** [comment] 2021-09-29 17:23
https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm#L67 this line is the cause of the issue; I leave it to the reader to work out the rest

**Comment by esainane** [comment] 2021-09-30 01:37
![ss13-volstop](https://user-images.githubusercontent.com/14355175/135371091-654fa8df-5aeb-4c74-929c-b3133faa6a72.png)
![ss13-volstop-2](https://user-images.githubusercontent.com/14355175/135371189-ddbce4d3-f7ec-4337-9265-f82015177d07.png)
![ss13-volstop-3](https://user-images.githubusercontent.com/14355175/135371192-4051f7ff-ae02-45d5-82b5-b7885457bb2f.png)

the issue is not that you can't pump pressure over 9000kPa, you obviously can't do that
the issue is that the output side of the volume pump is not equalizing into the literally completely empty manifold it is attached to

> Unwrenching and rewrenching the manifold will still not cause any gas to flow into it.

**Comment by esainane** [comment] 2021-09-30 01:47
![ss13-volstop-thebug](https://user-images.githubusercontent.com/14355175/135372112-92b1ffd2-5258-453a-995a-848baf2e4e88.png)

**Comment by duncathan** [comment] 2021-09-30 02:05
Well, since you were uninterested in working it out yourself, I'll explain in more detail:

Since process_atmos() returns, it never calls update_parents(), which is what makes pipenets equalize the air mixtures of attached components with the main mixture. Normally this is desirable, but in this instance when the volume pump is the only component acting on its pipenet, the pipenet never updates, leaving the output port above 9000kPa and the attached pipes empty. That's why manually calling it using VV is resolving it temporarily. The same should be true if you add another component acting on the same pipenet - the volume pump blockage should resolve itself.

The most obvious solution is probably to update the pipenet when adding pipes, but there may be more elegant fixes as well.

**Comment by duncathan** [comment] 2021-09-30 02:09
Also, since we haven't met: Hi, I'm Dunc! I was the lunatic in charge of atmos on this repo for several years. It's very nice to see a newer contributor working on atmos improvements and fixes, best of luck as you keep working on it! If you ever have any questions about the inner workings of atmos systems or whatever, feel free to DM me on discord (duncathan_salt#2403). LemonInTheDark reaches out to me from time to time and I always love helping with atmos stuff even if I'm done contributing actively :)

**Comment by LemonInTheDark** [comment] 2021-09-30 02:47
Honestly we should be updating when adding to a pipeline anyway. there's no use in having a concept of "off" if we don't turn it on at the right times

**Comment by esainane** [comment] 2021-09-30 03:25
Right, avoiding misunderstandings:
- We know that `update_parents` is not being called sufficiently often.
- We'd like to avoid constant calling from components that haven't changed anything, to only cover the case of something else being added somewhere.
- We can't add on pipe placement, as pipes can also be reprogrammed to join networks after the fact.
- We can't update on all cases that make pending connections either. parents remain null until SSair picks us up. There are a bunch of runtimes here if you eg place three pipes in a line quickly enough, but they don't immediately seem relevant here.
- I'd expect some check on when SSair creates or rebuilds a pipenet and members (or even network volume?) change to trigger an update. Splits seem to work fine, so either merging or creation is presumably missing a case somewhere.

**Comment by duncathan** [comment] 2021-09-30 03:59
> We can't add on pipe placement, as pipes can also be reprogrammed to join networks after the fact.

Gotcha, this must be a new addition then.

> I'd expect some check on when SSair creates or rebuilds a pipenet and members (or even network volume?) change to trigger an update. Splits seem to work fine, so either merging or creation is presumably missing a case somewhere.

This is a good idea and might help, but I have another suggestion to add: trigger updates in the procs which add members (at least pipes, possibly components too? unsure if the latter is necessary) to the pipeline

**Comment by LemonInTheDark** [comment] 2021-09-30 04:28
I think the key issue here is pipeline code expects all pipes to have a parent of some sort, and that's not always the case, at least ever since it was moved to an ssair process instead of being instant.

There's two bugs here. One is adding just a pipe to a net not giving the pipe gas, the other is adding just a pipe doesn't make the net update.

Both of those would normally happen in merge(), but because the pipe has no parent at that stage, they don't.
Solving the second issue is easier then the first, assuming the first is noticeable enough to be an actual problem
Dunc's right, no matter what we should always be updating the pipeline when something is added to it, if only because it's volume changes.

![image](https://user-images.githubusercontent.com/58055496/135386879-f7ab3499-9b12-4896-a04e-4016e009b37d.png)

**Comment by Mooshimi** [comment] 2022-08-08 09:43
Is this now an obsolete issue since atmos has had a shit ton of changes recently

**Comment by LemonInTheDark** [comment] 2022-08-08 20:47
test it, I don't think so

**Comment by SyncIt21** [comment] 2023-01-26 14:51
![Screenshot (96)](https://user-images.githubusercontent.com/110812394/214867113-33da0280-859a-4a1c-a568-62aeea9dd85c.png)
So lemon can we close this?

**Comment by Mooshimi** [comment] 2023-02-03 15:14
> 

it appears to have gas in it....

**Closed by Mooshimi** 2023-02-03 15:14 UTC
Labels: Bug, Atmospherics
