### ISSUE TITLE
Ling transform offsets their sec/medhud weirdly

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#86902] opened 2024-09-25 23:16 UTC
### Client Version:

515.1643

### Issue Summary:

![image](https://github.com/user-attachments/assets/ec90433c-9f78-4287-bc39-03c81aeb9f18)
i know there's a lotta ghosts in the way but basically the health and sec bar are at the bottom rather than the top which gives them away to anyone aware of this

### Round ID:

[238971](https://scrubby.melonmesa.com/round/238971)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

I assume just transform and have someone look at your hud?

**Comment by Sealed101** [comment] 2024-09-26 13:24
Duplicate of #60158

**Closed by Sealed101** 2024-09-26 13:24 UTC
Labels: Bug
