### ISSUE TITLE
Clown Ruin pipes are missing or something

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#32314] opened 2017-11-01 14:08 UTC
Dream maker shows the disposal pipes but ingame (some?) disposal pipes seem to be missing, resulting in being thrown out prematurely from the loop.
This also results in not being able to escape cluwne ruin.

**Comment by Repukan** [comment] 2017-11-01 14:35
Dupe

**Comment by AnonymousNow** [comment] 2017-11-02 00:34
Dupe, but ancient dupe.

**Comment by Repukan** [comment] 2017-11-02 02:10
Dupe nonetheless

@Cyberboss mind closing this

**Comment by ShizCalev** [comment] 2017-11-02 07:09
Duplicate of #26674
Caused by #27719

**Closed by ShizCalev** 2017-11-02 07:09 UTC
