### ISSUE TITLE
Tramstation whiteship can only go to Deep Space and custom location docking zones

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#71357] opened 2022-11-19 12:22 UTC
Reporting client version: 514.1583

## Round ID:
[194631](https://scrubby.melonmesa.com/round/194631)

## Reproduction:

1. get tram whiteship
2. go to bridge
3. cannot dock to arrivals, lavaland or KC13
4. use navconsole to perform a shitty bypass
5. fix bug

shorten it

**Comment by Mooshimi** [comment] 2022-11-23 06:49
Doesn't this have to do with how huge it is? This isn't a bug but a complaint about the size limiting the ability to dock right?

**Comment by Mothblocks** [comment] 2023-10-30 21:21
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:21 UTC
Labels: Mapping, Not a bug
