### ISSUE TITLE
[missing sprite] atmos firetank backpack

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#53605] opened 2020-09-10 13:47 UTC
taking the hand sprinkler from the backpack , changing configuration and putting it back makes the whole back sprite go missing

**Comment by msgerbs** [comment] 2020-09-10 17:06
I'm not sure this is a sprite issue @nightred, it sounds like it may be using the wrong icon_state when put back in the backpack.

**Comment by nightred** [comment] 2020-09-10 18:45
Sorry i thought you said that the icon does not show

**Comment by msgerbs** [comment] 2020-09-10 20:45
I didn't make this, and OP did say the icon doesn't show but only after putting it back in. To me that points toward the icon_state being set wrong since it works when first spawned. I'll check it out.

**Comment by msgerbs** [comment] 2020-09-10 22:19
I was unable to reproduce this or find anything that looked like it might cause this. @Tlaltecuhtli can you try it again, maybe make a video or screenshots or something?

**Comment by Tlaltecuhtli** [comment] 2020-09-11 12:58
reproduced by spam clicking while pressing z repatively
![backpack bug](https://user-images.githubusercontent.com/33834933/92928369-453d8c80-f43f-11ea-953d-931384474a16.PNG)

**Comment by msgerbs** [comment] 2020-09-11 14:21
I still can't make this happen. What were you clicking on specifically?

**Comment by Tlaltecuhtli** [comment] 2020-09-11 14:24
pressing z and clicking floor

**Comment by msgerbs** [comment] 2020-09-11 14:28
Adjacent to you or away from you?

**Comment by Tlaltecuhtli** [comment] 2020-09-12 16:17
i dont think it makes a difference

**Comment by nightred** [comment] 2020-09-12 16:52
looks like something is dysynced, does switching it again fix the issue?

**Comment by ArcaneMusic** [comment] 2020-11-01 05:36
I am also unable to reproduce. Spamclicking and activating the nozzle doesn't seem to be changing much here, but I would have to imagine this is some kind of issue with the tank not updating.

**Comment by dragomagol** [comment] 2020-11-26 01:51
Saw this again on Manuel today 
![image](https://user-images.githubusercontent.com/66640614/100298804-e7511900-2f46-11eb-8bf4-f124951ae010.png)

**Comment by ArcaneMusic** [comment] 2020-11-26 05:44
We really just need someone to VV the backpack to see what icon_state it has when it's breaking, though.

**Comment by dragomagol** [comment] 2020-11-26 06:33
I was able to reproduce it again on local (after a lot of clicking) and this is the VV for the tank's icon 
![image](https://user-images.githubusercontent.com/66640614/100315904-4c6c3500-2f6e-11eb-842f-ca8e14edce90.png)

**Comment by dragomagol** [comment] 2020-11-29 05:32
Update: I figured out how to reproduce this quickly. Switch to the spray nozzle and spray the same tile that you're on and the sprite should vanish.

**Comment by dragomagol** [comment] 2020-12-24 04:43
Should be fixed by #55705

**Comment by ArcaneMusic** [comment] 2020-12-24 18:14
Ah, comment it on the actual PR if it's not merged yet

**Closed** 2020-12-26 06:35 UTC
Labels: Bug, Sprites, Tested/Reproduced
