### ISSUE TITLE
Global sound issues

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#24275] opened 2017-02-19 04:19 UTC
So for a while now there's been a number off issues around admin loaded sounds.

The first is that some sounds, such as emitters firing, will interrupt the sound being played, rather like there aren't enough channels to play both sounds at the same time. Its particularly noticeable when multiple emitters are set up and it will make it stutter, due to their short sound length and regular triggering of said effect.

There also seems to be some major issue of lag being created when they are uploaded. It will cause the server to hang for at least 1 second during a full 1mb song with a population of around 60 or higher (havent tried it on low pop).
Its hard to tell if its just a population increase thats effecting it, but Im fairly certain it didnt used to be this bad in terms of lag.

I realise this issue is relatively vague but its more a call to arms to do some further testing and seeing if anyone might know of what might have changed to the code of late (never noticed these issues before number value sound levels became a thing (i.e. when it was just on or off as a pref)

**Comment by MrStonedOne** [comment] 2017-02-19 06:28
Hmm, so for the lag i need to figure out if its the upload that causes the lag or the sending the sound out to people...

I'll make a way to just upload a song without playing it.

Should also let us figure out if its network lag or byond lag.

**Comment by peoplearestrange** [comment] 2017-02-19 17:44
Sounds good.

Still not sure what could be causing the "shutter/interrupt" of sounds whilst they're playing, rather than layering of them like it used to.

**Comment by MrStonedOne** [comment] 2017-02-20 00:37
it seems to be the stream thing. we should remove that since i can't find enough documentation on what it even does other then "uses less memory and has more limitations"

**Comment by timothymtorres** [comment] 2021-08-24 12:06
Duplicate of #29759

**Closed by timothymtorres** 2021-08-24 12:06 UTC
Labels: Performance, Sound, Bug
