### ISSUE TITLE
How to generate 2 MW of power and defeat 15 hooked up power sinks

### ISSUE THREAD

**Issue by Meatman420** [tgstation/tgstation#36769] opened 2018-03-28 13:23 UTC
Issue reported from  Round ID: 85676 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Reproduction]: This was not discovered on a TG server, but rather a privately hosted server with the TG game mode installed running MetaStation. These are the steps I went through to generate well over 2 MW of power and defeat 15 power sinks hooked directly into the power grid indefinitely. You may only get ~1.5 MW if you don't hook up the solars using the same method.

1. Set up the SM generator. I used 8 emitters and N2O as the coolant pumped in from atmos, but I don't think it really matters.

2. Take the wire coming off of the radiation collector arrays and hook it into the wire going into the engineering APC. Do not hook it directly to the terminal, only into the wire going into the terminal.

3. Upgrade the SMES' capacitors with super capacitors, and their cells to super cells.

4. Power the SM up for the first time.

5. Set SMES output to 390KW, and input to 400KW. Notice how the power input doubles as you do this. You have literally hooked the output of the SMES into it's input and created a dead short, which should blow the thing, not generate twice the power. And we haven't even used the most upgraded versions of the parts! This setup is cheap to reproduce and can be done within the first 15 minutes of shift start.

I did this twice, and both times I was able to put as many power sinks down as I wanted without affecting the station. Nothing could bring the grid down except disconnecting the SM output from the main grid. On top of that, the thing generates ~1.2 MW of energy even if you don't have the SM running just by upgrading the SMES' and hooking the output to their input. I am pretty sure that's not by design.

DISCLAIMER: I did not test this on official TG servers. I am convinced that this is a gamebreaking bug for traitors, and as such I didn't even want to test it. If for some reason you guys deem it not a bug, I would really love to know so I can wire it like this every engineering shift I play. Like I said, it defeats power sinks soundly and generates a shit ton of power, so the implications would be huge if it is, for some reason, an intended feature.

**Comment by Spaceinaba** [comment] 2018-03-28 13:30
so tldr dead shorting smeses are not blowing them?
the title doesnt really tell us anything about the bug

**Comment by Barhandar** [comment] 2018-03-28 15:58
Deadshorting SMESes generates power out of nowhere as they use their own output as input. It probably shouldn't actually _blow_ them as it's easy to do by accident, but, say, EMP or zeroing the input with a message would work too.

**Comment by Robustin** [comment] 2018-03-28 20:41
This doesn't even look like a bug.

SMES info is deceptive because the "power available" doesn't acount for the power its consuming.

It certainly don't think its possible to generate power out of nothing, that trick (probably) would've been discovered years ago. You can tell the SMES to generate output a shitload (when upgraded) but you still need that much input or else it'll slowly run out. 

Otherwise this PR just ready "optimal engine and upgraded SMES beat the shit out of powersink, as intended"

**Comment by Meatman420** [comment] 2018-03-28 21:52
According to the power readout on the console, the power sinks were sapping over 10 MW of power, and I was generating 2 MW. Despite this, the lights stayed on indefinitely and nothing was affected. I don't know how to spell this out any better. There's no way this is working as intended.

**Comment by Shadowflame909** [comment] 2018-03-28 22:29
Are you sure that you weren't left with 2 MW in the end? After you put down all the power sinks.

**Comment by kevinz000** [comment] 2018-03-28 23:18
power rework not soon enough.

**Comment by kevinz000** [comment] 2018-03-28 23:18
@ninjanomnom

**Comment by Robustin** [comment] 2018-03-30 19:34
it sounds like you took the sinks off the grid too.

**Comment by Meatman420** [comment] 2018-03-30 20:04
I'll test it and see. This conjecture is pointless.

**Comment by zaracka** [comment] 2018-03-30 23:15
I used roughly the same method to render several (9+) power sinks pointless (I did this on a local server).

CO2 Supermatter setup that produces around 1.7 MW.
Connected the radiation collector wire (which goes to the SMES's) to the main power grid (the cables going to all APC's).
Maxed out the Target Output on all SMES's.

1.7 MW + 3(200) kW = 2.3 MW.

I don't know if this is a feature or not, but I've noticed that once a SMES is full, any amount of power going into it is enough to keep it full. In fact, the power that's "supposed" to be charging it is then transferred to the next SMES's available power and so on.

Also connecting a SMES's output to it's input does in fact increase it's available power.

If you check a power monitor, you'll see that the load increases dramatically (18+ MW) while the available power remains constant (2.3 MW). However, all APC's will continue to charge and the station will not be affected as a result. I haven't waited long enough to see if the power sinks explode, but for the duration of my testing they did not.

**Comment by zaracka** [comment] 2018-03-31 17:49
I did some extensive testing, here's what I found.

Power sinks do not reduce the amount of power in cables. In turn, they do not affect machines that are powered by cables, at least not directly (such as emitters). They do not drain SMES's either. From what I've gathered, power sinks exclusively drain APC's.

var/drain_rate = 1600000	// amount of power to drain per tick

The drain rate, as you can see, is 1.6 MW. Any APC connected to a cable with 1.6 MW or above does not get affected by power sinks and instead continues charging like normal. If an APC is connected to a cable with 1599999 W or below, it is affected by power sinks and gradually drains to zero.

Maybe power sinks should subtract power instead of only working below a threshold.

Whether this is a bug or not is for you to decide.

**Closed** 2018-09-14 11:05 UTC
Labels: Bug, In Game Exploit
