### ISSUE TITLE
The Crafting Recipe for FRAG-12 shotgun shells is bugged.

### ISSUE THREAD

**Issue by Cadunkus** [tgstation/tgstation#77338] opened 2023-08-03 01:41 UTC
## Reproduction:

The crafting recipe for FRAG-12 shotgun shells requires:
 - 1 Unloaded technological shell
 - 5u Glycerol
 - 5u Sulfiric Acid
 - 5u Fluorosulfiric Acid
And a screwdriver which is not consumed in the process.

However, when crafting, it consumes twice as much fluorosulfiric acid and no sulfiric acid. So instead it's more like:
- 1 Unloaded technological shell
- 5u Glycerol
- 10u Fluorosulfiric Acid
And 5u of sulfiric acid and a screwdriver which are not consumed in the process.

**Comment by TheVekter** [comment] 2023-08-03 18:53
This appears to be less a bug with the crafting recipe and more a quirk of crafting - if I spawn all three fluid reagents in a beaker and use that to craft the shell, it works as intended. If I spawn three beakers with 5 units of each fluid in them, it leaves behind the sulfuric acid.

I also couldn't replicate the issue of it consuming twice as much acid, but I was using the specific amounts for the craft I wanted to use.

**Comment by cnleth** [comment] 2023-08-03 19:39
The issue is probably that fluorosulfuric acid is a subtype of sulfuric acid so it counts as both sulfuric *and* fluorosulfuric in the recipe, which makes it possible to craft the shells without using plain sulfuric acid. This could be fixed by disallowing subtypes of sulfuric acid to be used instead of sulfuric acid itself in the recipe, but i don't know if it's possible

**Comment by TheVekter** [comment] 2023-08-03 20:40
I'm probably just going to change the recipe to omit the fluro acid. These don't get used enough for me to worry too much about it.

**Comment by Cadunkus** [comment] 2023-08-05 21:10
Genuinely based. It already takes tons of effort getting Frag-12s in the first place.

> I'm probably just going to change the recipe to omit the fluro acid. These don't get used enough for me to worry too much about it.

**Comment by YakumoChen** [comment] 2023-08-07 06:08
kinda seems like bad consistency since the recipe is just the recipe for nitroglycerin but it sounds more fun so whatever

**Comment by TheVekter** [comment] 2023-08-07 22:04
> kinda seems like bad consistency since the recipe is just the recipe for nitroglycerin but it sounds more fun so whatever

Then why don't we just make nitroglycerin required instead of any of the chems?

**Comment by antropod** [comment] 2023-08-08 13:09
if you put acid reagents in different order it uses proper ones

**Closed** 2023-08-10 16:43 UTC
Labels: Oversight
