### ISSUE TITLE
Turning off cyborg meson vision causes unseeable areas to turn to space

### ISSUE THREAD

**Issue by ileyd** [tgstation/tgstation#31112] opened 2017-09-29 03:00 UTC
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Unknown round ID.

When playing as an engineering cyborg, once meson vision is enabled, turning it off causes all areas beyond your vision to instead appear as space and also causes some random tiles to be replaced with space.

Restarting the client does not resolve this issue.

**Comment by ShizCalev** [comment] 2017-09-29 03:17
dupe #29521, #30510

**Comment by AnturK** [comment] 2017-09-29 06:40
Duplicate of #30510

**Closed by AnturK** 2017-09-29 06:40 UTC
