### ISSUE TITLE
if admins dont press all the buttons how will all the href things be fixed

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#31704] opened 2017-10-14 14:25 UTC
ADMIN LOG: Ausops/(Ausops) set the forced secret mode as traitor.

ADMIN LOG: Ausops/(Ausops) clicked an href with no authorization key!

ADMIN LOG: Debug mode enabled, call not blocked. Please ask your coders to review this round's logs.

**Comment by Cyberboss** [comment] 2017-10-14 14:38
Duplicate of #31006

**Closed by Cyberboss** 2017-10-14 14:38 UTC
