### ISSUE TITLE
Changelings can revive inside Laughter/Blood demons and armblade them forever like a clown car

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#52432] opened 2020-07-23 06:53 UTC
## Round ID:
[142580](https://scrubby.melonmesa.com/round/142580)

## Testmerges:
#51459: 'Baystruments - I had two tgstation forks for some reason and had to delete one and that nuked the last PR' by silicons at commit b9bf1a03c4

## Reproduction:
1) Be a laughter and possibly a blood demon
2) Crit and eat someone who turns out to be a ling
3) Let a minute or so pass
4) You are now being armbladed from the inside, forever

I had a wizard round today where I bought ~6 demons of both types and ran around with the warp whistle to watch it all.

One demon apparently critted and ate a changeling, and was getting armbladed from the inside and there was basically nothing they could do about it other than to stay in blood warp mode so they cant be clicked. They eventually died trying to jump out to grab a body.

Anyways this seems like complete bullshit for the demon so I thought I'd file a bug since it seems kind of scuffed.

Also I forgot the type of demon it was, its possible it affects both unless blood demon does something to destroy the body when eating.

**Comment by Winterous** [comment] 2020-07-23 07:54
This is also the case with Space Dragons, got eaten as a ling and noticed I could revive and hit him. I just hung out in his belly for a while, until another changeling did it and killed him.

Interestingly I seemed to be both adjacent to the dragon, and nowhere near his location, because I couldn't interact with anything else, and I tried a couple of items that should have worked from that location but didn't, but I can't remember what.

Honestly I'm not sure this can be considered a bug, it makes perfect sense, for the dragon at least, since when the dragon dies the bodies are returned, whole.
Slaughter Demon should probably count the bodies as destroyed, since they vanish once the demon is killed. Laughter Demon is a weird case; theoretically they're stored in a separate dimension of tickles, rather than inside the demon themself, and appear in random places around the station on death, already alive.

**Comment by TemporalOroboros** [comment] 2020-07-23 08:47
There's a similar bug with blob spore zombies. Let me find it real quick.

**Comment by PKPenguin321** [comment] 2020-07-23 09:10
Same is true for morphs, last time it came up I think it was ruled not a bug

**Comment by Robustitron** [comment] 2020-07-23 16:25
Thing about clown cars and xenos is they have at least one of these options to deal with it:

A) Prevent it by seeing changelings somehow
B) Be generally protected against it
C) Stop it by ejecting/freeing people, like xenos

If this is considered a feature for morphs, dragons and demons you'd think they'd have one of these options too. Especially laughter demons if they're sending dudes to the prank dimension or whatever

But maybe that's just my opinion, it was a pretty lame way for that demon player to lose their antag.

**Comment by ShizCalev** [comment] 2020-07-25 00:42
Duplicate of #52432

**Closed by ShizCalev** 2020-07-25 00:42 UTC
