### ISSUE TITLE
Trying to emote over binary via an * at the end of the message replaces the message with placeholder text

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#71372] opened 2022-11-19 19:45 UTC
## Round ID:
[194653](https://scrubby.melonmesa.com/round/194653)

## Reproduction:

![изображение](https://user-images.githubusercontent.com/75863639/202868721-58a64f21-ba29-4b38-9e59-1e94115aa3a0.png)

**Comment by Sealed101** [comment] 2022-11-20 06:19
yeah binary only, i didn't see any issues with the other radios so far

**Comment by Holoo-1** [comment] 2022-11-21 06:53
This is an intended thing. (Based on  https://github.com/tgstation/tgstation/pull/62130)

**Comment by NeverDawnedNoz** [comment] 2022-11-21 10:41
This can be reproduced by attempting a custom emote and having a speech module attempt to replicate it.

**Comment by dragomagol** [comment] 2022-11-21 21:27
Duplicate of #62666

**Closed by dragomagol** 2022-11-21 21:27 UTC
