### ISSUE TITLE
You can no longer compost some food / snacks into hydroponics basins for nutriment

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#54279] opened 2020-10-10 01:13 UTC
## Round ID:

[147983](https://scrubby.melonmesa.com/round/147983)

## Reproduction:

Old-food can still be composted, but new-food can no longer be spread into trays for composting.

**Comment by msgerbs** [comment] 2020-10-10 04:56
What's this, bug 136 from the food refactor? Sigh.

**Comment by Qustinnus** [comment] 2020-10-10 07:25
You try remaking 400 items and see if you get any bugs

**Comment by Qustinnus** [comment] 2020-10-10 07:28
This just sounds like a dupe of every single tray issue that's on the github by now too

**Comment by msgerbs** [comment] 2020-10-11 01:55
> 
> 
> This just sounds like a dupe of every single tray issue that's on the github by now too

In what way?

**Closed** 2020-12-04 08:11 UTC
Labels: Oversight
