### ISSUE TITLE
[SQL] Round ID defaults to 0 if data insert fails

### ISSUE THREAD

**Issue by Dunklheit** [tgstation/tgstation#46713] opened 2019-09-23 20:51 UTC
## Round ID:
Not Applicable
## Testmerges:
Not Applicable

## Reproduction:

1. Purposely make the `INSERT` query in [/datum/controller/subsystem/dbcore/proc/SetRoundID()](https://github.com/tgstation/tgstation/blob/673ba39eb8e2e166f88dea9963e757e84917461a/code/controllers/subsystem/dbcore.dm#L128) fail.
2. The query to get the round ID at [Line 131](https://github.com/tgstation/tgstation/blob/673ba39eb8e2e166f88dea9963e757e84917461a/code/controllers/subsystem/dbcore.dm#L131) will **succeed**, but return 0. This is intentional design by many MySQL server derivatives.

It would appear that DreamDaemon is not passing a required value in the query (or is sanitized to NULL). The required columns for the insert to succeed are `initialize_datetime`, `server_ip`, and `server_port` and cannot be NULL.

**Comment by timothymtorres** [comment] 2021-12-06 08:43
I’m marking this as `Not a bug` since you deliberately changed the code to cause it to fail.  

I understand that this is meant to catch errors if something breaks but you could apply this to all of the code logic for this repo.  There are a lot of procs that if they break will cause other stuff to break as well but we generally don’t write bug reports for them _until they break._ 

Thus this bug report is premature IMO.

**Closed** 2021-12-18 04:51 UTC
Labels: Not a bug, SQL, Cleanup Flagged
