### ISSUE TITLE
Deathmatch Underground thunderdome chasms fuck up your ability to use UI speak and use Ahelps

### ISSUE THREAD

**Issue by SomeoneYouProbablyKnow** [tgstation/tgstation#81559] opened 2024-02-18 23:33 UTC
## Issue Summary
If you fall into a chasm in the deathmatch thunderdone tgui and adminhelp all break. its fixed by summoning the person and killing them properly (admins did it a few times). Works consistently

**Comment by Rhials** [comment] 2024-02-18 23:41
Duplicate of #81559, this is apparently an issue with all chasms

**Closed** 2024-02-21 03:22 UTC
