### ISSUE TITLE
mob offset when buckling to beds

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85804] opened 2024-08-14 12:57 UTC
Reporting client version: 515.1641

## Issue Summary

https://github.com/user-attachments/assets/39f2e5b2-c8e5-4237-a995-f70724abf5db

**Comment by GPeckman** [comment] 2024-08-14 13:03
Dupe of #85709?

**Closed** 2024-08-15 18:35 UTC
Labels: Oversight
