### ISSUE TITLE
 Any projectile that can penetrate things is broken, as the bullet will only hit the object or mob who you clicked on, and not all in a line.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#52651] opened 2020-08-01 14:57 UTC
## Round ID:
N/A, tested on local

## Testmerges:
N/A

## Reproduction:
Have any weapon that shoots a piercing projectile, such as Staff of the Honkmother, have a line of carbons that you shoot at, watch as the projectile only hits the person you target by clicking on them, and no one else. 
https://streamable.com/lwmnqv (Video is of Spell cards VV edited to being syndicate shuttle penetrator rounds)

**Comment by ShizCalev** [comment] 2020-08-01 15:53
Duplicate of #50762

**Closed by ShizCalev** 2020-08-01 15:53 UTC
