### ISSUE TITLE
Broom attempts to sweep things it can’t sweep.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49616] opened 2020-02-28 04:43 UTC
This includes intercoms, smugglers satchels (hidden) and maybe other things I haven’t found.

**Comment by trollbreeder** [comment] 2020-02-28 10:01
Looks like a duplicate of #49513

**Comment by kriskog** [comment] 2020-02-28 13:28
duplicate of #49513

**Closed by kriskog** 2020-02-28 13:28 UTC
