### ISSUE TITLE
Window are missing sprites, possibly when damaged?

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26586] opened 2017-04-25 21:31 UTC
![image](https://cloud.githubusercontent.com/assets/609465/25408690/ca1a9a4e-2a06-11e7-8e1e-9174c250383e.png)

There are still windows there.

**Comment by AnturK** [comment] 2017-04-25 21:35
Dupe of #26576

**Closed by AnturK** 2017-04-25 21:35 UTC
