### ISSUE TITLE
Blood stains on items are totally broken

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#53949] opened 2020-09-25 05:58 UTC
## Reproduction:
Get the shit beat out of you. Observe that your equipment's inventory/on ground sprite is covered in blood, but there's no examine message about it and the worn sprite has no blood. Also try washing it off and observe that nothing happens when you try, either with a shower or by washing the individual item. What should happen here is that it should be visible both in the inventory and also on the worn sprite that it's bloody, and there should be an examine message indicating as much. It should also be able to be washed off.

**Comment by Couls** [comment] 2020-09-25 06:35
@TiviPlus could this have to do with the blood element?

**Comment by ATH1909** [comment] 2020-09-25 11:01
I've seen this happen with a baton; washing it in a sink didn't help, and neither did washing it under a shower.

**Comment by msgerbs** [comment] 2020-09-26 14:58
> 
> 
> I've seen this happen with a baton; washing it in a sink didn't help, and neither did washing it under a shower.

Stop harmbatoning 😂

(Good to know that it's not just worn items)

**Comment by timothymtorres** [comment] 2022-05-30 20:42
Duplicate of #38820

**Closed by timothymtorres** 2022-05-30 20:42 UTC
Labels: Bug
