### ISSUE TITLE
Crate duplication

### ISSUE THREAD

**Issue by drderp3635** [tgstation/tgstation#37611] opened 2018-05-01 16:52 UTC
((Found on yogstation using TG code))

Using the skittish trait ability on a cargo drop pod sent in from the express supply console will create a duplicate of the crate that arrived.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-01 17:38
Is it a true dupe or some sort of doubleloc memery?

**Comment by drderp3635** [comment] 2018-05-01 18:08
Crates created had the same form number and contents as the first. The first crate also retained its contents.

**Comment by AlexTheSysop42** [comment] 2018-05-01 18:49
Probably a good thing that express consoles cant order nulls

**Comment by SpaceManiac** [comment] 2018-05-01 19:02
true dupe, the act of opening the pod spawns in the supply crate

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-01 19:06
@Xhuis

**Comment by Xhuis** [comment] 2018-05-01 20:02
I didn't code cargo pods. Skittish just puts you inside of the locker; the only way it changes it is by opening and closing. Whatever the issue is, it lies in cargo code.

**Comment by XDTM** [comment] 2018-05-02 11:37
It probably isn't supposed to close after opening, so manually closing with skittish causes the bug

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-02 14:03
@MrDoomBringer

**Closed** 2018-05-06 12:01 UTC
Labels: Bug, In Game Exploit, Priority: High
