### ISSUE TITLE
Ghost notification icons are broken

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26656] opened 2017-04-27 21:29 UTC
![image](https://cloud.githubusercontent.com/assets/609465/25505252/e4e12c4c-2b98-11e7-9214-2682c7cc84c9.png)
![image](https://cloud.githubusercontent.com/assets/609465/25505258/ec57dd54-2b98-11e7-8313-00ad2c2dbc7a.png)

Should be an egg there.

**Comment by MrPerson** [comment] 2017-04-28 03:12
This is a duplicate of #26621

**Comment by WJohn** [comment] 2017-04-28 04:08
Knew it was a dupe of something but couldn't find it, thanks. Looks like this was fixed already, then.

**Closed by WJohn** 2017-04-28 04:08 UTC
Labels: Bug
