### ISSUE TITLE
Changing into a species that doesn't breathe from one that does in an area with no oxygen causes hud to think you are constantly choking

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#45821] opened 2019-08-09 18:45 UTC
## Round ID:
115536

## Reproduction:
1. Go to an area that has no oxygen
2. Change species to one that doesn't breathe
The hud will continue to show the no oxygen warning and you'll constantly have the can't breathe moodlet. The only way to get rid of it is to get changed back into a race that can breathe in an environment that has oxygen.

**Comment by trollbreeder** [comment] 2019-11-01 18:09
This issue is also with self respiration, if you're unlucky enough to have it activate fully in a no-oxygen zone.

**Comment by timothymtorres** [comment] 2021-08-20 10:29
Duplicate of #40040

**Closed by timothymtorres** 2021-08-20 10:29 UTC
Labels: Bug
