### ISSUE TITLE
Goonchat not working

### ISSUE THREAD

**Issue by 41300** [tgstation/tgstation#28346] opened 2017-06-11 14:31 UTC
Problem Description: i'm can't use or see anything on goonchat but this
![dreamseeker_2017-06-11_10-15-25](https://user-images.githubusercontent.com/29311090/27011683-eba5184a-4e8e-11e7-8acb-65e630d97664.png)
i'm wait like 10 minutes and nothing happen.

What did you expect to happen: the game ruinning cool and games.

What happened instead: i'm can't use the chat properly, i'm can't see my own messages and messages of other players, i'm can still type but nothing happens

Why is this bad/What are the consequences: i'm can't play the game properly.

Steps to reproduce the problem: i'm just enter the server and this happen, every time.

Server: Bagil

Revision: i'm can't use the chat so...

well, i'm can still pick a job and run in the station but im cant see any messages of other players or my own messages, im can't examine or whatever properly, my windows is windows 7 and i'm have adobe flash player enabled in my internet explorer so i'm don't know what do, this started to happen when goonchat was put in /tg/ code.

**Comment by 41300** [comment] 2017-06-11 14:33
some more screenshots
![dreamseeker_2017-06-09_13-28-46](https://user-images.githubusercontent.com/29311090/27011776-546f514a-4e91-11e7-998d-fe56f4e3533e.png)
![dreamseeker_2017-06-09_13-35-05](https://user-images.githubusercontent.com/29311090/27011777-559c1864-4e91-11e7-831f-b7e3f8d716fe.png)
![Uploading dreamseeker_2017-06-09_13-35-53.png…]()
![Uploading dreamseeker_2017-06-09_13-36-47.png…]()

**Comment by Repukan** [comment] 2017-06-11 15:07
Time to play mime lmao

**Comment by lzimann** [comment] 2017-06-11 16:53
This might be related to some asset caches bug we are having(that are, apparently, a byond issue)

**Comment by Cyberboss** [comment] 2017-06-11 17:08
But if he's seeing this much that means the assets are arriving, because they are verified before the html is sent

**Comment by Tacolizard** [comment] 2017-06-11 17:12
>What did you expect to happen: the game ruinning cool and games.

>the game ruinning cool and games.

**Comment by MrStonedOne** [comment] 2017-06-11 23:21
Try it on sybil now

**Comment by Cyberboss** [comment] 2017-06-12 03:22
Dupe of #28277

**Comment by Cyberboss** [comment] 2017-06-16 14:13
@41300 Are you still having this issue?

**Comment by goonchaterrorguy** [comment] 2017-06-18 18:11
not him, but I had and still have the same problem. It's practically impossible to play on tgstation and any downstream servers...

**Closed** 2017-06-23 00:49 UTC
Labels: Bug
