### ISSUE TITLE
you cant use ui botton actions when crawling

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43106] opened 2019-03-12 16:55 UTC
stuff like turning on your hardhat light and welder mask

**Comment by ShizCalev** [comment] 2019-03-12 18:50
Potentially fixed by #42894

**Comment by 4dplanner** [comment] 2019-03-12 19:56
Not fixed by 42894

**Comment by Sealed101** [comment] 2023-08-26 20:28
can't reproduce with a baseline human with no quirks, damage, status effects or other things that may block an action called by a UI button

**Closed by Sealed101** 2023-08-26 20:28 UTC
Labels: Bug
