### ISSUE TITLE
Chameleon mask hides glasses and headset even when it shouldn't

### ISSUE THREAD

**Issue by TheLeopold** [tgstation/tgstation#65488] opened 2022-03-15 11:43 UTC
Reporting client version: 514.1578

## Round ID:
[179982](https://scrubby.melonmesa.com/round/179982)

## Testmerges:
- [MODsuit painting](https://www.github.com/tgstation/tgstation/pull/65445)

## Reproduction:
Wear glasses, headset and normal cigarette.
Examine yourself and note that you can see cigarette, headset and glasses
Replace cigarette with a chameleon mask disguised as cigarette
Examine yourself and note that you can only see a cigarette, but not glasses and headset

**Comment by Serxule** [comment] 2022-03-16 21:58
this is because cham mask lets you change identity to whatever your ID is, so it has to be registered as a full face covering or it wont work correctly

**Comment by SuperNovaa41** [comment] 2022-03-17 22:36
Its because it has the `COVERS_EYES` and `COVERS_MOUTH` flags. This could probably be fixed by using the flags of the selected mask

**Comment by CMDR-Gungnir** [comment] 2022-03-25 04:46
I always imagined this was intentional. It's a full face mask that's just using chameleon technology to look like it's just a cigarette, so it takes on the appearance of your face.

**Comment by SuperNovaa41** [comment] 2022-03-26 22:23
It could be either really

**Comment by TheLeopold** [comment] 2022-07-10 19:55
If it's intentional, why would chameleon glasses and headset come in chameleon kit when said kit contains chameleon mask which makes both of these items unusable?

**Comment by CMDR-Gungnir** [comment] 2022-07-10 20:08
> If it's intentional, why would chameleon glasses and headset come in chameleon kit when said kit contains chameleon mask which makes both of these items unusable?

Because you might not be wearing the mask, or you might take it off, I imagine.

**Comment by Sealed101** [comment] 2023-08-28 08:04
Duplicate of  #60873

**Comment by Sealed101** [comment] 2023-08-28 08:05
Duplicate of https://github.com/tgstation/tgstation/issues/60873

**Closed by Sealed101** 2023-08-28 08:05 UTC
Labels: Consistency Issue
