### ISSUE TITLE
Shuttle loading causes atmos runtimes

### ISSUE THREAD

**Issue by Nirnael** [tgstation/tgstation#42733] opened 2019-02-10 16:42 UTC
Asteroid with engines strapped emergency shuttle produces a load of atmos runtimes when being bought and loading. Runtimes cease after it's fully loaded I believe (can't know for sure, byond decides to not let you control whether you want to read more runtimes and just cuts it for 10 minutes cause it's a fucking atrocious game engine).

From what I can see, it first loads in the middle of centcomm zlevel, causes all the runtimes and then gets deleted and moved over to the centcomm dock waiting to be called.
Runtimes are due to space tiles or asteroid sand tiles having incorrect adjacent turfs. For example, 

Round 101601:
> [2019-02-10 01:55:26.434] runtime error: Cannot execute null.archive().
> - proc name: archive (/turf/open/archive)
>-   source file: LINDA_turf_tile.dm,90
> -   usr: null
> -   src: the asteroid sand (89,216,1) (/turf/open/floor/plating/asteroid)
> -   call stack:
> - the asteroid sand (89,216,1) (/turf/open/floor/plating/asteroid): archive()
> - space (90,216,1) (/turf/open/space): process cell(4851)

> [2019-02-10 01:55:26.438] runtime error: Cannot read null.gases
> - proc name: compare (/datum/gas_mixture/compare)
> -   source file: gas_mixture.dm,378
> -   usr: null
> -   src: /datum/gas_mixture/immutable/s... (/datum/gas_mixture/immutable/space)
> -   call stack:
> - /datum/gas_mixture/immutable/s... (/datum/gas_mixture/immutable/space): compare(null)
> - space (90,216,1) (/turf/open/space): process cell(4851)

Others come from asteroid sand and having closed turfs (which have no air variable and shouldn't be in adjacent "open" turfs because they are closed) such as the rock walls as adjacent turfs.

The main problem I think I see here is atmos is running before the shuttle is properly loaded and fucks everything. This is possibly related to other atmos runtimes where things get registered into SSair before being loaded.
I also do not know why the shuttle has to be loaded at a different place then moved to the centcomm dock. Refactoring would be nice.

Another reason why this might be a shuttle code bug is that it also happens with other shuttles, "asteroid station" shuttle also has runtimes like this when being loaded.

**Comment by Dennok** [comment] 2019-06-19 12:29
still issue?

**Comment by timothymtorres** [comment] 2022-11-05 10:38
Duplicate of #28991

**Closed by timothymtorres** 2022-11-05 10:38 UTC
Labels: Runtime
