### ISSUE TITLE
addictions from crossing addiction thresholds don't work

### ISSUE THREAD

**Issue by thespitfire24** [tgstation/tgstation#56291] opened 2021-01-20 05:18 UTC
## Reproduction: 
1. Inject enough Happiness/Bath Salts/Crank/any other chem with addiction to go over the addiction threshold
2. Wait for the chem to cycle out, notice how withdrawal effects aren't taking place.
3. Scan your test subject/yourself with health scanner, no addictions show up on the scanner.

Notes:
Addictions were working on Manuel as of round #154486
I first noticed that addictions were not functioning on a locally-hosted copy which was compiled at 9:07 PM on the 19th (GMT+11)

**Comment by RaveRadbury** [comment] 2021-01-20 07:01
Dupe of #55764, which is a duplicate of #55245

It's been like this since November of last year... sad!

**Comment by RaveRadbury** [comment] 2021-01-20 07:01
Duplicate of #55245

**Closed by RaveRadbury** 2021-01-20 07:01 UTC

**Comment by RaveRadbury** [comment] 2021-01-20 07:32
Caused by #54797
