### ISSUE TITLE
Medibeams can trigger microbombs and macrobombs

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#30229] opened 2017-08-27 01:33 UTC
Round ID: 75282, Sibyl

Details: Nuke ops. Cayenne's macrobomb implant went off on the base, fucking people over. Then my microbomb implant also went off in the assault pod. Neither of us clicked the button. I wasn't even in crit.

Relevant factors?
- I was actively being medibeamed at the time for a long time. So was the other guy.
- The assault pod was depressurized at the time (due to aforementioned fucking over). I was floating in and out of crit hence the medibeam. But I was at red health when the microbomb went off.
- I had every cybernetic implant in. The reviver had fired at least once.

HREF logs do not appear to have anything useful.

***UPDATE***

I am able to consistently reproduce it. If you use a medibeam on someone with a microbomb/macrobomb and click their sprite too often (toggling beam on/off) you will "lose control of the beam" and they will go boom. I THINK what may be happening is that the old beam does not qdel fast enough and thus it thinks it's crossing streams

EDIT: Confirmed without implant this is 100% what is happening

**Comment by PKPenguin321** [comment] 2017-08-27 01:36
Copied from my dupe issue

Round ID: 75282

![testmerges](https://puu.sh/xkpld/b2eeae6f68.png)

Multiple nuke ops suicide implants were reported to have been self-activated, but none of the ops claimed to have done it, including BGO (who was an OP and is reputable as an admin). Implants seemed to trigger on minor damage or healing, with no cohesive reason for it happening. Could possibly use href log diving.

**Comment by MoreRobustThanYou** [comment] 2017-08-27 01:38
Spacepods don't touch any implant code, so it's not that

**Comment by zaeperry99** [comment] 2017-08-27 01:38
I was also present and on the nukeops squad; I don't recall being medibeamed at the time of my own explosion, nor was I in a depressurized area. It was shortly after another's bomb implant had gone off and put my health status in red. Apologies for the lack of useful input.

**Comment by PKPenguin321** [comment] 2017-08-27 01:40
The carp sent me this image of logs leading up to their macrobomb detonating: http://i.imgur.com/qCVNFEe.png

**Comment by kevinz000** [comment] 2017-08-27 01:40
oh boy

**Comment by bgobandit** [comment] 2017-08-27 01:42
My log looked similar, out of nowhere "You activate the microbomb implant!" and boom

**Comment by nervere** [comment] 2017-08-27 01:43
@zaeperry99 If you were the operative right next to Cayenne as she exploded, you were indeed being medibeam-healed by me at the time of your explosion.

**Comment by bgobandit** [comment] 2017-08-27 02:15
also

>bandit
>reputable as an admin

**Comment by DoctoreMad** [comment] 2017-08-27 14:31
>i ded

This is some sorta joke isn't it

**Comment by bgobandit** [comment] 2017-08-27 15:19
it's not inaccurate

**Comment by bgobandit** [comment] 2017-08-27 15:32
UPDATE: I am able to consistently reproduce it. If you use a medibeam on someone with a microbomb/macrobomb and click their sprite too often (toggling beam on/off) you will "lose control of the beam" and they will go boom.

**Comment by ShizCalev** [comment] 2017-10-15 01:20
Encountered this again.

**Comment by timothymtorres** [comment] 2021-12-29 23:03
Duplicate of #38632

**Closed by timothymtorres** 2021-12-29 23:03 UTC
Labels: Bug, FUCK, Against God and Nature
