### ISSUE TITLE
RCD tiles turn Lavaland tiles into space

### ISSUE THREAD

**Issue by Cirrial** [tgstation/tgstation#25361] opened 2017-03-21 21:40 UTC
https://github.com/tgstation/tgstation/commit/37a325d8971f75136aae2c7f87c74b94ff12d9c9
Playing as an Ash Walker, picked up the RCD to remove a wall. Misclicked a few extra times. Suddenly, space. Fortunately, as ashwalker, suddenly venting what little air existed in the lair to space didn't affect much. Still seems like an oversight?

**Comment by optimumtact** [comment] 2017-03-21 21:42
@Cyberboss you broke baseturfs when you changed maploading

**Comment by Sligneris** [comment] 2017-03-22 01:45
On a related matter, whenever syndicate base gets blown up, it also leaves a hole to space.

**Comment by Cyberboss** [comment] 2017-03-22 18:57
It's not lavaland tiles, it's tiles that were loaded by dmm_suite

**Comment by Cyberboss** [comment] 2017-03-23 03:39
Dupe of #19954

**Closed** 2017-03-25 19:28 UTC
Labels: Bug
