### ISSUE TITLE
Objects/mobs on catwalks don't fall after the catwalk is destroyed

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49966] opened 2020-03-15 13:17 UTC
## Round ID:

Round ID: [132255](https://scrubby.melonmesa.com/round/132255)
BYOND Version: 513.1508
Server revision compiled on: 
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1

## Testmerges:
The following pull requests are currently test merged:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction
1. Put object on second floor catwalk
2. Stand on second floor catwalk
1. Click catwalk with wirecutters
2. Catwalk is deleted, rods are spawned, they don't fall and neither do you or the object

You can pick the rods and the object up and throw them onto the tile to make them fall.

**Comment by Dennok** [comment] 2020-03-16 07:42
Dupe of #49685 but better description.

**Closed** 2020-03-16 21:45 UTC
Labels: Bug
