### ISSUE TITLE
AI's can no longer attach photos to their pda messages

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#70264] opened 2022-10-02 13:34 UTC
Reporting client version: 514.1585

## Round ID:
[191604](https://scrubby.melonmesa.com/round/191604)

## Reproduction:
Used to be able to with old PDA's, no longer the case it seems? At least I haven't found any way to do that.

**Comment by timothymtorres** [comment] 2022-10-03 04:45
Duplicate of #70140

**Comment by JohnFulpWillard** [comment] 2022-10-15 20:15
The other issue is a general issue over tablets, this is a specific issue and I think it's fine to leave up as it's own.

**Comment by Mooshimi** [comment] 2022-10-17 21:10
I don't think anyone can add pictures with pda messages

**Comment by JohnFulpWillard** [comment] 2022-10-17 21:39
![image](https://user-images.githubusercontent.com/53777086/196288843-cc287286-2ef0-4690-b9e4-04a071641e9e.png)

You can and it does work, but it isn't linked in chat, you really have to go in your PDA message history to see it (both the sender and reciever)

**Comment by Mooshimi** [comment] 2022-10-17 22:37
> ![image](https://user-images.githubusercontent.com/53777086/196288843-cc287286-2ef0-4690-b9e4-04a071641e9e.png)
> 
> You can and it does work, but it isn't linked in chat, you really have to go in your PDA message history to see it (both the sender and reciever)
> 
> However, I don't think AIs can even link the image to the messenger, which is a separate issue, but is still an issue

omg there's a way to add pictures to messages now? nice

**Closed** 2023-02-19 21:06 UTC
Labels: Bug, UI
