### ISSUE TITLE
dr hilbert hotel broke

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42805] opened 2019-02-16 14:38 UTC
i was able to get the hotel inside the room by clicking it fast? and then when i chose a room from inside the hotel i got teled in a 3x3 prison http://take.ms/8yj6a
round 101902

**Comment by ATH1909** [comment] 2019-02-17 03:02
forbidden apm techniques

**Comment by TheDreamweaver** [comment] 2019-04-12 05:09
Duplicate of #42191

**Closed** 2019-04-12 05:24 UTC
