### ISSUE TITLE
taser turrets on boxstation can hit people on the other side of reinforced glass

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52782] opened 2020-08-07 23:48 UTC
Round ID: Private test server

<img width="1440" alt="wizardbug" src="https://user-images.githubusercontent.com/42606352/89696644-74139080-d8de-11ea-9198-3f51ad77eb94.PNG">

Note that tasers were hitting me through the glass even before I cast Knock to open that reinforced windoor.

**Comment by Timberpoes** [comment] 2020-08-08 04:53
Confirmed, same in icebox. Taser electrodes pierce through the windows at the AI core.

**Comment by Fikou** [comment] 2020-08-08 07:44
thats the way directional windows work, since they are on the same tile as you youre technically not protected by anything, if they were put there on the external side of the tile it would work

**Comment by Fikou** [comment] 2020-08-08 07:45
i dont know what label to put on this 🥴

**Comment by ATH1909** [comment] 2020-08-08 23:58
You could tweak the map to move those windows outwards slightly, I suppose.

**Comment by necromanceranne** [comment] 2020-08-10 01:42
Don't directional windows block bullets?

**Comment by dragomagol** [comment] 2020-12-13 06:49
Duplicate of #43324

**Closed by dragomagol** 2020-12-13 06:49 UTC
Labels: Bug
