### ISSUE TITLE
AI Beepsky Path Graphic Glitch

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36395] opened 2018-03-13 18:47 UTC
[Round ID]: # 84913

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
As AI you see weird missing textures on Beepsky's explored path.

![](https://i.imgur.com/egwsYLb.png)

1. Be AI
2. Look at Beepsky while he's moving around the station
3. See the missing textures.

**Comment by PKPenguin321** [comment] 2018-03-13 19:05
Pretty sure this is a dupe

**Comment by praisenarsie** [comment] 2018-03-13 21:35
>Pretty sure this is a dupe

**Comment by Jalleo** [comment] 2018-03-13 21:50
It is a dupe.

**Comment by AzureWildfire** [comment] 2018-03-14 02:02
It happens with the medibots too

**Comment by SpaceManiac** [comment] 2018-03-14 02:40
Duplicate of #36223

**Closed** 2018-03-14 07:29 UTC
