### ISSUE TITLE
Reagent metabolism is bugged.

### ISSUE THREAD

**Issue by Ultimate-Chimera** [tgstation/tgstation#18015] opened 2016-05-29 03:13 UTC
I am not sure if this is just after taking meth, but I have taken only 10 units of meth, I get addicted and my reagents freeze, all of them. They never lower. I am not sure if meth is the issue, but metabolism keeps bugging.

**Comment by Shapsy** [comment] 2016-05-29 05:43
The issue is with addictions I believe, Phil said it was supposed to be fixed in some list-related PR Remie made

**Comment by Ultimate-Chimera** [comment] 2016-05-29 06:55
Ah.

**Comment by phil235** [comment] 2016-05-29 11:55
Yeah, the bug is still here.

**Comment by RemieRichards** [comment] 2016-05-30 23:27
We should just split the typecache stuff out of ```is_type_in_list()```, and manually apply them where appropriate.

**Closed** 2016-05-31 22:14 UTC
Labels: Bug, Priority: High
