### ISSUE TITLE
Buckled Objects + Disposals Bugs

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#63517] opened 2021-12-20 08:18 UTC
## Round ID:

current
## Testmerges:
current

## Reproduction:
- Be pushed into disposals while buckled to an object (via chute) 
- The object will disappear, but you are still buckled to it and cannot move
- If the object exits, you will teleport onto it (no matter the time difference)
- If you pull the buckled mob, it rips the bucklee (chair/whatever) out of disposals

**Comment by msgerbs** [comment] 2021-12-21 01:12
Do you know if this used to work in the past?

**Comment by jlsnow301** [comment] 2021-12-21 01:22
I don't think I've ever tried it previously - so no

**Comment by timothymtorres** [comment] 2021-12-21 16:57
Duplicate of #42040

**Closed by timothymtorres** 2021-12-21 16:57 UTC
Labels: Bug
