### ISSUE TITLE
Spaces in all radio messages and outloud speech

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33239] opened 2017-12-03 17:17 UTC
> [Common] Otto Eichmann  says, " VIVA " 
> [Common] Clovis Bunsen  says, " HELLO THERE " 
> [Common] Ethan Dank  buzzes, " VARVA " 
> [Common] Braxton Cherry  exclaims, " D&D or Paranoia starting in the Library Quiet Room! " 
> Braxton Cherry  exclaims, " D&D or Paranoia starting in the Library Quiet Room! " 
> [Common] The Automated Announcement System  coldly states, " CHAD has signed up as Assistant " 
> [Common] Braxton Cherry  says, " Sign up quickly before all the slots are gone " 
> Braxton Cherry  says, " Sign up quickly before all the slots are gone "
> 

Note the space after the first " and before the last "

---

Server revision compiled on:  2017-12-02 

a97b4a 

Server tools version: /tg/station 13 Server v3.2.0.17 

Server tools API version: 3.2.0.1

**Comment by ShizCalev** [comment] 2017-12-15 21:50
Duplicate of #28876

**Closed by ShizCalev** 2017-12-15 21:50 UTC
Labels: Bug
