### ISSUE TITLE
The Arena Shuttle Doesn't spawn an arena

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#45220] opened 2019-07-16 06:27 UTC
Issue reported from  Round ID: 113258 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Yep. If you buy this shuttle, you will be teleported into space and die if you board it. There is no arena. Not going to lie this was pretty dissapointing to discover after finally killing bubblegum and getting a captain who didn't rush the BYOS or something 10 minutes in. Oof.

**Comment by ATH1909** [comment] 2019-07-16 06:36
Amazing.

**Comment by kriskog** [comment] 2019-07-16 14:44
Dupe of #45219

**Closed by kriskog** 2019-07-16 14:44 UTC
Labels: Bug
