### ISSUE TITLE
Infinite 5u syringe

### ISSUE THREAD

**Issue by Amrabol** [tgstation/tgstation#63301] opened 2021-12-08 03:05 UTC
## Reproduction:
Made oculater. Got syringe. Walked around asking people if they want to try bad chem. Notice tha syringe never ends if injected

**Comment by SuperNovaa41** [comment] 2021-12-08 03:32
Duplicate of https://github.com/tgstation/tgstation/issues/63284

**Comment by SuperNovaa41** [comment] 2021-12-08 03:38
This has a better name

**Comment by ATH1909** [comment] 2021-12-08 09:02
lmao

**Comment by SuperNovaa41** [comment] 2021-12-08 15:37
This applies to all methods of consumption (eye dropper, syringe, in food, etc) and also is apparently happening to only inverse chems. 

https://github.com/tgstation/tgstation/issues/63167

**Closed** 2021-12-21 06:41 UTC
Labels: In Game Exploit, Bug, FUCK, Needs Reproducing
