### ISSUE TITLE
Revival using Nooartrium makes the user retain ghost vision

### ISSUE THREAD

**Issue by borb197** [tgstation/tgstation#63839] opened 2022-01-04 22:22 UTC
Reporting client version: 514.1561

## Round ID:
[176018](https://scrubby.melonmesa.com/round/176018)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)

## Reproduction:
First, I'll summarise how Nooartrium (is supposed to) work: Once the chemical enters your blood stream, if your heart is functional and you are dead, you will revive after very briefly dying and stay out of crit up until your heart fails, while it's in your blood stream your heart will recieve heavy damage.

Dying with Nooartrium in your blood stream, and ensuring your ghost was in the body upon being revived causes you to retain ghost vision. You will be able to see through walls (although not in the darkness), see ghosts and even things such as the AI eye.
Note that Nooartrium is listed as /datum/reagent/inverse/penthrite for reproduction purposes.

I have gotten the bug to consistently occur every time I'm revived by the chemical and my ghost does not leave my body, so I think the issue is just something related to what you can see on your screen not being set back to what a living player should be able to see, and remains as what a ghost can see (such as variables like see_invisible not going back to what it should be)

Another thing to note is after aghosting twice to leave and re-enter my body, I could no longer see ghosts or through walls.

Also, testmerges are irrelevant here, I decided to not remove it just in case but I've had this bug occur across various testmerges.

**Comment by SuperNovaa41** [comment] 2022-01-05 00:02
Duplicate of #63816

**Closed by SuperNovaa41** 2022-01-05 00:02 UTC
