### ISSUE TITLE
Elevator song wont stop playing even after leaving.

### ISSUE THREAD

**Issue by NoobWithATie** [tgstation/tgstation#84955] opened 2024-07-14 03:58 UTC
Reporting client version: 515.1641

## Issue Summary

During ops we were in an elevator inside of Nebulastation, and when I left it it kept playing the song, I tried stopping the noises by stopping **All** noises, but that didn't work, after some time an admin fixed the issue, but after I went down a Level (not in elevator) it continued again. 

## Round ID:
[232085](https://scrubby.melonmesa.com/round/232085)

## Testmerges:
- #[Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- #[Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

I was walking into an elevator with multiple people, almost enough to fill the elevator, after I got out a few seconds later the music of the elevator was playing, it was on Nebulastation during Nuclear Operatives

**Comment by Sadboysuss** [comment] 2024-07-15 08:50
dupe of https://github.com/tgstation/tgstation/issues/76043

**Closed** 2024-07-17 09:16 UTC
