### ISSUE TITLE
Experi-scanners are not recognizing objects for experiments

### ISSUE THREAD

**Issue by General-Gaston** [tgstation/tgstation#82452] opened 2024-04-04 13:43 UTC
## Issue Summary

When preforming experiments with scanning objects it continuously says that the object is not related to your currently selected experiment even when it's exactly what it wants for the experiment

## Round ID: 

[226648](https://scrubby.melonmesa.com/round/226648)

## Reproduction:

Step one, make object
Step two, cry as you cannot scan the item required for the experiment

**Comment by Profakos** [comment] 2024-04-04 14:17
Duplicate of #82421? It has a fix underway.

**Closed** 2024-04-04 14:22 UTC
