### ISSUE TITLE
Exosuit Fabricator GUI looks bugged out or has not been made into a "clean" GUI

### ISSUE THREAD

**Issue by CC-4477** [tgstation/tgstation#47942] opened 2019-11-22 19:25 UTC
Round ID not relevant, seen this every game I've played- the exosuit fabricator's GUI is all text and doesn't have proper buttons so it looks a bit weird

**Comment by kriskog** [comment] 2019-11-22 19:45
Its an older ui, functional but just barely. A rather large ui overhaul is underway currently, this one is likely to get replaced soonish.

This is not a bug though, closing.

**Closed by kriskog** 2019-11-22 19:45 UTC
