### ISSUE TITLE
Maints chaplain sect makes you perma blind

### ISSUE THREAD

**Issue by FulpSheets** [tgstation/tgstation#58632] opened 2021-04-23 08:33 UTC
## Round ID:
happened on fulp (tg downstream)

## Reproduction:
The adapted eyes ritual works with seeing in dark, but after being in the light for about 5 seconds you go full blind (working as intended I think) but after re-entering the dark you stay full blind despite flavour text saying your sight is normal.
![image](https://user-images.githubusercontent.com/81964183/115843374-1d48e980-a462-11eb-85a8-5ff247a51782.png)
![image](https://user-images.githubusercontent.com/81964183/115843388-2043da00-a462-11eb-9691-57b17d39accd.png)

**Comment by ATH1909** [comment] 2021-04-23 11:39
I mentioned this before in another issue report, but it's nice to confirm that someone else has encountered it

**Comment by FulpSheets** [comment] 2021-04-23 15:02
Also the greed sect doesnt say how much the vendors cost because it uses money, not favour

**Comment by SuperNovaa41** [comment] 2021-04-28 00:03
Duplicate of https://github.com/tgstation/tgstation/issues/58525

**Closed by SuperNovaa41** 2021-04-28 00:03 UTC
Labels: Bug
