### ISSUE TITLE
Motorised Wheelchair becomes unbucklable because of some slipping shenanigans 

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#67841] opened 2022-06-17 16:30 UTC
## Round ID:
Multiple, 185072 is an example

## Reproduction:
1. Wheelchair enters a slippery tile and you fall out of it.
2. Attempt to buckle to it from an adjacent tile (not sure here if you have to be still laying on the ground for it to happen)
3. Fail and slip past it to another tile
4. The motorised wheelchair is now completely useless, no-one can buckle to it.

**Comment by newfren** [comment] 2022-06-17 16:58
this also happens with regular wheelchairs and is fixable with those by pulling the wheelchair off the tile or scooping it up into your hand

**Comment by Likteer** [comment] 2022-06-17 17:23
> this also happens with regular wheelchairs and is fixable with those by pulling the wheelchair off the tile or scooping it up into your hand

This is not fixable with a pull for motorised wheelchairs and they cant be folded iirc.

**Comment by timothymtorres** [comment] 2022-06-20 12:47
Looks somewhat related to #65070

**Comment by Profakos** [comment] 2023-01-11 15:57
I examined this a few weeks ago, if I recall the cause was the slip component hijacking the program execution, and when buckling resumes, it is in a state it did not expect. But I have to test this again to be sure.

**Comment by Profakos** [comment] 2023-02-08 10:05
I came back to this to see if the problem still persists, and to my astonishment, while slip component still hijacks the execution due to the signals, no slipping occurs and buckling finishes fine, so I guess, something has been fixed in slips to account for this.

**Comment by timothymtorres** [comment] 2023-02-08 14:15
Closing this then

**Closed by timothymtorres** 2023-02-08 14:15 UTC
Labels: Bug

**Comment by Profakos** [comment] 2023-02-08 21:21
Ah, sorry, looks like this is still an issue with lubed tiles that throw you, every other slip like bananas and wet tiles work fine.
