### ISSUE TITLE
Slippery Spraycan doesn't spray lube

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#55845] opened 2020-12-30 19:24 UTC
## Round ID:
[153220](https://scrubby.melonmesa.com/round/153220)

## Testmerges:
#54462: 'The Great Radio Rework: NTNET Part 1 of many.' by WarlockD at commit 0aea50f0dd

## Reproduction:
get a slippery spraycan, spray it, no lube spawns.

**Comment by dragomagol** [comment] 2020-12-30 19:29
Duplicate of #53350 (rip)

**Closed by dragomagol** 2020-12-30 19:29 UTC

**Comment by ShibaInuLord** [comment] 2020-12-30 20:24
wow i totally forgot i already made one
