### ISSUE TITLE
Hotkeys are now always active.

### ISSUE THREAD

**Issue by Summoners** [tgstation/tgstation#47643] opened 2019-11-07 23:57 UTC
#47626 has enforced hotkeys to always be on, disabling the usage of always-active chat fields. I'm a simple man, I need to be able to type and move.

Please give us the option to disable always-active hotkeys in some fashion again, option or a button itself.

**Comment by cacogen** [comment] 2019-11-08 01:34
as it should be

**Comment by AnonymousNow** [comment] 2019-11-08 04:26
Ah, is that why I can't press enter out of hotkey mode to chat any more?

**Comment by kriskog** [comment] 2019-11-08 17:03
This wasn't entirely unintentional, but @Couls might be doing something to this regardless.

**Comment by Takov-Mala** [comment] 2019-11-08 17:15
Not a bug? Jesus, do you have any idea how annoying this is?

**Comment by nemvar** [comment] 2019-11-08 20:41
ok boomer

**Comment by Hanador** [comment] 2019-11-08 23:53
Yeah this sucks, accidentally hit tab while trying to yell at somebody and now everything I memorized over the past however the fuck long I've been here is no longer functioning.
I CAN'T MOVE AND TYPE ANYMORE. I'VE BEEN USING THE SHITTY ARROW KEYS AND HOME/INSTERT/PAGE UP/ETC. FOR YEARS PLEASE SOMEBODY SAVE ME FROM HAVING TO STOP AND PRESS T TO SCREAM AT CATS TO *WAG

**Comment by MCterra10** [comment] 2019-11-09 01:12
hotkey mode is objectively better

**Comment by AnonymousNow** [comment] 2019-11-09 02:38
Hotkey mode IS better most of the time, but being able to tab out of it on the fly is vitally important.

**Comment by spessbandit** [comment] 2019-11-09 03:48
give me back my fucking arrow keys

**Comment by kopoba** [comment] 2019-11-09 07:58
you can rebind arrow keys to move but you cant scream GREIF on the fly because chat input don't get focus when you try face roll keyboard trying to say ;LING IN MAINTACE!HELP!111111111

**Comment by peoplearestrange** [comment] 2019-11-10 22:44
Apparently we can have custom hotkeys, but we can't have the original play method that my monkey brain has got used to and actually finds useful to admin observe with (because switching between asay, ahelps, ooc and other typing text and moving around with ghost, is actually useful on a set of dedicated arrows)

**Comment by Couls** [comment] 2019-11-10 23:00
look at the open PR above dude

**Comment by peoplearestrange** [comment] 2019-11-12 01:22
So I can move around with the arrow keys and still have the hotbar focused like the original method?

**Comment by Couls** [comment] 2019-11-12 01:33
yes once that PR is merged

**Closed** 2019-11-12 01:51 UTC
Labels: Not a bug
