### ISSUE TITLE
Render issue with deadchat controllable singulo

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62451] opened 2021-10-29 20:55 UTC
Reporting client version: 514.1561

## Round ID:
[172165](https://scrubby.melonmesa.com/round/172165)

## Testmerges:
Not applicable

## Reproduction:
1.Get deadchat controllable singulo (12s vote is what happened)
2.Do something (I think it was re-clicking the notification?)
3.OH MY GOD
![image](https://user-images.githubusercontent.com/80979251/139500625-d9f97a95-55cf-4fea-a207-8b83926f14cd.png)

**Comment by timothymtorres** [comment] 2021-10-31 16:00
@Addust are you sure you didn't somehow accidentally teleport the singo to your location?

**Comment by Mothblocks** [comment] 2021-11-01 08:31
I've seen this one before.

It's the action button to tell you when an object is given deadchat control. Singularities just happen to be, well, huge. It goes away after a while (like all action buttons).

**Comment by timothymtorres** [comment] 2021-11-02 09:54
> I've seen this one before.
> 
> It's the action button to tell you when an object is given deadchat control. Singularities just happen to be, well, huge. It goes away after a while (like all action buttons).

So the problem is the button to view the event is just really REALLY big?  Maybe it should be set to be the 1x1 singo

**Comment by timothymtorres** [comment] 2021-11-07 11:46
@Mothblocks is this related to #57264 or is that fixed now?

**Closed** 2022-04-21 18:56 UTC
Labels: Tested/Reproduced
