### ISSUE TITLE
AI Multi-Cam Screen Static

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#52562] opened 2020-07-28 19:27 UTC
When I went onto the multi-cam screen, and clicked onto one of the views (outlining it in green) and then clicked off, the screen was covered in static. 
Reporting client version: 513.1527

**Comment by timothymtorres** [comment] 2021-12-30 13:53
A picture was provided in #63703 of this happening.

**Comment by timothymtorres** [comment] 2022-08-28 09:47
Duplicate of #38307

**Closed by timothymtorres** 2022-08-28 09:47 UTC
Labels: Bug, Tested/Reproduced
