### ISSUE TITLE
Connecting to borgs and mechs as ai is broken

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#70684] opened 2022-10-20 15:07 UTC
Reporting client version: 514.1585

## Round ID:
[192709](https://scrubby.melonmesa.com/round/192709)

## Reproduction:
Have robotics build you an exosuit, be able to enter it once, then after that be unable to enter that exosuit again.
Similar with borgs, you cannot just click on shells to enter them, you have to go into the borg popup menu or click on the reconnect to last shell button after entering it once.

**Comment by ShizCalev** [comment] 2022-10-20 16:20
Likely dupe of #70664

**Closed** 2022-10-21 07:12 UTC
