### ISSUE TITLE
Able to see Revolutionary HUD as non Revolutionary

### ISSUE THREAD

**Issue by Bjarl** [tgstation/tgstation#63113] opened 2021-11-28 01:33 UTC
## Round ID:
[Manuel #173081](https://sb.atlantaned.space/rounds/173801)

## Testmerges:
#63079 

## Reproduction:
During the round, I was experiencing connection issues, during one of my drops from the game I was mindshielded by an unknown and noticed the missing R upon my relogging. However, I could still see the revolutionary HUD on other revolutionaries, including the Headrevs. Disconnecting and Reconnecting, and Forced Revving/Derevving did not solve the issue.

1. Disconnect and close the client
2. have someone mindshield you
3. Reconnect and notice your missing R
4. See everyone else's Rs

**Comment by timothymtorres** [comment] 2021-11-28 13:33
Relevant code:

https://github.com/tgstation/tgstation/blob/a9e73b743c7eee936cde163e8f6ec360f7b2c267/code/modules/antagonists/revolution/revolution.dm#L286-L296

https://github.com/tgstation/tgstation/blob/9bc66991c90d79318eefb24cc87cc4ad40e6d6b0/code/modules/antagonists/_common/antag_datum.dm#L139-L155

Also from the logs it appears that maybe an admin removed your revolution status:

> [2021-11-28 01:01:57.370] ADMIN: JusticeGoat/(Naomi Faulkland) has removed Revolutionary antagonist status from Bjarl/(Lukas Judge).

**Comment by Bjarl** [comment] 2021-11-29 04:08
> Also from the logs it appears that maybe an admin removed your revolution status:

    [2021-11-28 01:01:57.370] ADMIN: JusticeGoat/(Naomi Faulkland) has removed Revolutionary antagonist status from Bjarl/(Lukas Judge).


Justice tried forcerevving and then derevving me to try and remove it after I ahelped the issue.

**Comment by Mothblocks** [comment] 2021-11-29 07:44
The relevant code is all the new alternate_appearance code in #62718

**Comment by Mothblocks** [comment] 2021-12-08 02:37
Can't reproduce by disconnecting, mindshielding, and reconnecting.

**Comment by Mothblocks** [comment] 2021-12-08 02:39
Closing this one in favor of the other one since I found a repro

**Closed by Mothblocks** 2021-12-08 02:39 UTC
Labels: Bug, Needs Reproducing
