### ISSUE TITLE
Airlock cycle dir doesn't change with ship rotations.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32893] opened 2017-11-19 08:25 UTC
Airlock cycle dir is a var added to allow linked doors to start closing immediately if the other one is open. Unfortunately, these don't work with ship rotations. If your ship turns in any direction other than the one it was originally mapped in, these will no longer auto close.

**Comment by Cyberboss** [comment] 2017-12-04 16:50
I'm gonna close this as a dupe of #33103

**Closed by Cyberboss** 2017-12-04 16:50 UTC
Labels: Bug
