### ISSUE TITLE
Gravity Generator is stupidly loud.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#67432] opened 2022-05-31 04:06 UTC
## Testmerges:

#67307
#65791
#67003 
#67385 
## Reproduction:

>Move ghost near gravity gen
>Audio of the engine has reached 200 decibles
>Ear drums burst
>Blood leaking out of my ears
>Scream in pain, unable to hear my own cries
>Sob as I have lost one of my vital senses, clean up the blood
>Make issue report

**Comment by timothymtorres** [comment] 2022-05-31 04:32
Duplicate of #67213

**Closed by timothymtorres** 2022-05-31 04:32 UTC
