### ISSUE TITLE
Monkeys Preemptively Trip

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#69536] opened 2022-08-29 09:32 UTC
Reporting client version: 514.1578

## Round ID:
[189449](https://scrubby.melonmesa.com/round/189449)

## Testmerges:
irrelevant

## Reproduction:
![Sloim](https://user-images.githubusercontent.com/76874615/187169545-0a6e2852-f41d-4c06-a02c-2363c0b5cfd0.gif)

- Walk into a tile that contains both a thin window/door/Something And a monkey
- see as how monkeys expect you to move where they are, so they trip, even if there's something in the way and you never move.

**Comment by AdipemDragon** [comment] 2022-08-29 09:40
It's. Kind of the same issue with people pushing into the table a pAI is sitting on and the game expecting to be able to move that way, but instead they bump, but it still somehow shoves them

**Comment by timothymtorres** [comment] 2022-08-30 08:50
Duplicate of #66983

**Closed by timothymtorres** 2022-08-30 08:50 UTC

**Comment by itseasytosee** [comment] 2022-08-30 21:08
On cross signal :(
