### ISSUE TITLE
blade heretic cable restraints don't count as zipties for "Ritual of Knowledge"

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#67114] opened 2022-05-18 20:40 UTC
Bug: title. Cable restraints are identical to zipties except zipties are named differently and, more importantly, cannot be crafted with cable and need to be bought in a sec vendor.

Merges: https://github.com/tgstation/tgstation/pull/65718

Reproduction: attempt ritual of knowledge as blade heretic. using cable restraints gives "you need zipties to continue!" error.

**Comment by MrMelbert** [comment] 2022-05-19 04:41
not a bug, it asks for zipties exactly, not cable restraints.
it's meant for you to either troll beepsky or break into sec. 

zipties are subtypes of cable ties, but cable ties are not subtypes of zipties. Meaning only zipties work.

**Comment by private-tristan** [comment] 2022-05-21 20:41
only like, 5 people know about zipties, maybe replacing it with handcuffs would be better (able to be looted off of a secoff instead of needing to venture into brig)

also im 99% sure i've failed a ritual of knowledge due to this not counting

**Comment by Redrover1760** [comment] 2022-05-23 05:20
> not a bug, it asks for zipties exactly, not cable restraints. it's meant for you to either troll beepsky or break into sec.
> 
> zipties are subtypes of cable ties, but cable ties are not subtypes of zipties. Meaning only zipties work.

Seems unnecessarily confusing. Maybe add a note or something in the ritual description that cable cuffs do not count?

**Comment by dragomagol** [comment] 2022-06-26 03:59
Closing for cleanup flagged

**Closed by dragomagol** 2022-06-26 03:59 UTC
Labels: Not a bug, Cleanup Flagged
