### ISSUE TITLE
Server freezing for a second every 15s

### ISSUE THREAD

**Issue by Ralms** [tgstation/tgstation#50303] opened 2020-03-30 17:41 UTC
I've installed tgstation on one of my servers to play with friends.
I'm running a 6 core, 12 thread Intel i7 970 with plenty of Ram and a Samsung SSD. 
The server is running Proxmox and tgstation is running on a Ubuntu 19.10 with 2GB Ram, 512 Swap, 4 threads.
My client is running on a high PC on the local network. 

For some reason since the tgstation was started, by just walking around, it will freeze for a couple seconds and recover. This happens every 15s or so.
At first I though it could maybe be due to resources, like maxing out the CPU I've alocated or something, but in Top I see that it will average around 12% usage and when the freeze happens, CPU goes to 0% or 0.1% doing nothing and return normally to 12% when the game recovers.

**It's a very strange behavior, I'm just looking for some guidelines on how to identify the reason.** 

Also, I have a constant Time Dilation between 10% to 20% and ping fluctuates a lot from 1ms to as high as 18ms.
And I've noticed that the "Round Time" is counting time normally, while "Station Time" is going much faster. After leaving the client open for testing, now it says Round Time 3:24:14 with Station Time of 4:52:46

Thanks. 

EDIT: 
 I'm not using any custom configs, I haven't even copied the files from example, so everything is default. And I'm running the latest version.

**Comment by Dennok** [comment] 2020-03-31 06:03
Station Time is faster then real time. 4 times as i see it last time.

**Comment by Ralms** [comment] 2020-04-01 22:21
> Station Time is 12 times faster then real time.
> https://github.com/tgstation/tgstation/blob/e21d213892da4dd02f85f1e5d6e556b47882d7ac/code/controllers/subsystem/ticker.dm#L38
> 
> If you want sure about in what problem, build or machine, try load it with LOWMEMORYMODE
> https://github.com/tgstation/tgstation/blob/e21d213892da4dd02f85f1e5d6e556b47882d7ac/_maps/_basemap.dm#L1

Thanks for the information.

I've tried the LowMemory mode however I don't see any diference with the issue, just less resources being used. 
Instead of an average of 10% CPU usage, now I have around 3.5% and almost half the ram used. Don't feel that simply running in low memory mode would explain the CPU going to 0% usage, essentially the tgstation halting for a couple seconds for no reason. 

Could you please explain to me the Time Dilation metric? 

Thanks.

**Comment by Ralms** [comment] 2020-04-02 01:17
Hi there @Dennok,

Would like to provide an update, I've decided to go ahead and try to install and run the server on a dedicated VM instead of the Proxmox Container and the issue went away. 
So it seems that SS13 has some problem with running with a Linux Container.

Also the performance is way better, I'm getting "Time Dilation: 0% AVG:(0%, 1%, 0%)"
Could you still explain to me a little bit better what this metric represents? 

Thanks.

**Comment by Dennok** [comment] 2020-04-02 05:17
Sorry but i know nearly nothing about time dilation.
You can see how it calculated here https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/time_track.dm

**Comment by Cyprex** [comment] 2020-04-02 18:06
Did you happen to check in the MC tab if there was any particular Subsystem(SS) reporting unusally high numbers when it freezes?

**Comment by timothymtorres** [comment] 2021-08-19 18:20
Duplicate of #2601

**Comment by timothymtorres** [comment] 2021-08-19 18:22
There were similar bug reports of people's screen freezing within a few months of this issue.  I'm going to go ahead and close it unless you think it might be something else.  I can reopen it if needed.

**Closed by timothymtorres** 2021-08-19 18:22 UTC
Labels: Bug, BYOND Issue
