### ISSUE TITLE
/mob/dead/new_player doesn't softdelete

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#32170] opened 2017-10-27 23:27 UTC
using QDEL_HINT_FINDREFERENCE, the remaining references are:
`\## TESTING: Found /mob/dead/new_player [0x3000105] in list World -> Garbage -> list -> list.
\## TESTING: Found /mob/dead/new_player [0x3000105] in /client's movingmob var. World -> Naksuasdf`

The second one seems to be the important one. I don't have enough experience with the client-swapping bits of byond/tg to start untangling it without introducing shittons of bugs that might not be evident in local testing.

[Directions]: 
define TESTING and GC_FAILURE_HARD_LOOKUP, start a new game and join as any job, eventually the /mob/dead/new_player will fail to del. Or use QDEL_HINT_FINDREFERENCE.

**Comment by Cyberboss** [comment] 2017-10-27 23:30
This is actually a parallax thing. @MrStonedOne

**Comment by vuonojenmustaturska** [comment] 2017-10-27 23:39
o hey it's a duplicate of #11365

**Comment by Cyberboss** [comment] 2017-10-27 23:39
Duplicate of #11365

**Closed by Cyberboss** 2017-10-27 23:39 UTC
Labels: Bug
