### ISSUE TITLE
Plant people die in the new lighting system.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#24034] opened 2017-02-13 00:45 UTC
Plant people do not heal or get nutrition in the new lighting, in fact, they outright wither and die.

I imagine something screwy will happen with shadowlings and their followers or faithless or whatever the all black creatures are called that live in darkness.

**Comment by TehPear** [comment] 2017-02-13 02:06
I can confirm that the shadow species actually heals with the new lighting system as it acts if they're not in the light. In essence it's acting as if there isn't any lighting as it's probably tied to the old lighting system and not the /vg/ lighting.

**Comment by Cyberboss** [comment] 2017-02-13 02:13
@WJohn come on, the PR isn't even merged yet mannnn

**Comment by TehPear** [comment] 2017-02-13 02:14
It's test merged. Isn't that the whole point of test merging to find issues and fix it? Unless it's to cause salt...hmm

**Comment by 9600bauds** [comment] 2017-02-13 02:16
in /vg/, this was caused by get_lumcount() essentially imploding thanks to goonlights
just my 0.02$

**Comment by Cyberboss** [comment] 2017-02-13 06:51
Testmerge feedback should be reported in the PR thread. Issues are for
problems on master

**Comment by ChangelingRain** [comment] 2017-02-13 16:18
Post issues ON THE PR JEEZ

**Closed by ChangelingRain** 2017-02-13 16:18 UTC
Labels: Bug

**Comment by PJB3005** [comment] 2017-02-13 16:46
@9600bauds no it's me being a dork and incorrectly porting the shadowpeople code to use `T.get_lumcount()`.
