### ISSUE TITLE
Sometimes Fried Food Can't Be Eaten

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#55855] opened 2020-12-31 03:35 UTC
## Round ID:
/////////

## Testmerges:
//////////

## Reproduction:
Fry anything, and use it on yourself in help mode. sometimes you eat it, sometimes you just "use" it on yourself, which is an attack animation i think.

**Comment by dragomagol** [comment] 2020-12-31 03:36
Fried items also have an error as their right click icon

**Comment by ArcaneMusic** [comment] 2021-01-03 02:22
What species were you eating it as? I wonder if it's related to the above issue. @ShibaInuLord

**Comment by ShibaInuLord** [comment] 2021-01-03 03:00
I was human.

**Comment by timothymtorres** [comment] 2021-12-30 01:45
Duplicate of #55375

**Closed by timothymtorres** 2021-12-30 01:45 UTC
Labels: Oversight
