### ISSUE TITLE
You can leave an id console logged in without the "confirm identity" card in and change access

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#46217] opened 2019-08-28 20:13 UTC
Noticed on round 117270

Log in with the proper ID at an ID console, then remove the card. The console still acts as if the card was in it and allows anybody to place an ID in and change access

**Comment by Learner10** [comment] 2019-08-29 05:28
Is that a bug? It kind of makes it sound like the card is simply there to be used as a sign in... kind of like how you technically don't need to carry your ID with you for the full duration to open and go through a door.

**Comment by Tharcoonvagh** [comment] 2019-08-29 07:45
There is a handy little "log out" button, use that if you don't want people breaking into your office and getting all access. Not a bug.

**Comment by Moonman121** [comment] 2019-08-29 07:52
This was brought to my attention, it's not an issue I've personally had because I always make sure the console is logged out. Wasn't sure if it was intended or not.

**Comment by PKPenguin321** [comment] 2019-08-29 21:19
Dupe of https://github.com/tgstation/tgstation/issues/45661

**Closed by PKPenguin321** 2019-08-29 21:19 UTC
Labels: Bug
