### ISSUE TITLE
Sentient Diseases Unable to make Host Cough

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#63982] opened 2022-01-10 15:06 UTC
## Testmerges:
#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit 7831e746dc
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63939: 'Fixing living_say because I totally didn't accidentally break something' by GoldenAlpharex at commit 2eb77f66b0

## Reproduction:

Spawned as a sentient disease, let the timer run out to get a random host, could not make them cough

**Comment by AdipemDragon** [comment] 2022-01-10 15:22
Oh, this one's the same as https://github.com/tgstation/tgstation/issues/63764 and it's fixed by https://github.com/tgstation/tgstation/pull/63958, just needs to be merged.

**Comment by SuperNovaa41** [comment] 2022-01-10 17:22
Duplicate of https://github.com/tgstation/tgstation/issues/63764

**Closed by SuperNovaa41** 2022-01-10 17:22 UTC
