### ISSUE TITLE
You can't hide in crates anymore

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#50236] opened 2020-03-26 14:36 UTC
Issue reported from  Round ID: [133138](https://scrubby.melonmesa.com/round/133138) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1512

Go rest on top of an open crate, click crate, won't close.

**Comment by Dorsisdwarf** [comment] 2020-04-05 10:54
Dupe of #50382 and #50370

**Closed by Dorsisdwarf** 2020-04-05 10:54 UTC
