### ISSUE TITLE
You can buckle yourself to a chair while not being on it.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#67024] opened 2022-05-15 22:41 UTC
## Round ID:

[Round ID]: #183212

## Testmerges:

#65997
#65791
#67003

## Reproduction:

* Have someone aggro grab you while standing on a chair
* Drag yourself onto the chair

You will now be buckled to the chair on an adjacent tile.

**Comment by timothymtorres** [comment] 2022-05-22 23:47
Duplicate of #67013

**Closed by timothymtorres** 2022-05-22 23:47 UTC
Labels: Consistency Issue
