### ISSUE TITLE
Autolathe drains Cargo's APC when metal is added.

### ISSUE THREAD

**Issue by Pyko1** [tgstation/tgstation#34580] opened 2018-01-18 14:21 UTC
I believe the energy drain amount is much higher than intended by the person who made the changes.

Opening  this issue report here as i believe this is an upstream issue and should be fixed here on tg level than on downstream.

https://github.com/HippieStation/HippieStation/pull/6003
> Whoever coded in the energy drain for the autolathe massively overtuned it. It was set to amount_inserted * 100. Meaning that if you inserted a stack of 50 metal, it would convert the metal to 50,000 and then multiply it by 100, resulting in it draining 5,000,000 from Cargo's APC. This is so much that the admin spawn "infinite battery" gets drained to 0 instantly upon inserting the metal.

**Comment by GunHog** [comment] 2018-01-18 15:58
It should not be taking much of any energy to insert materials, only to fabricate. I would recommend the person fixing this to restrict the drain to fabrication only.

**Comment by Cyberboss** [comment] 2018-01-18 22:40
Dupe of something

**Comment by Cyberboss** [comment] 2018-01-18 22:42
Duplicate of #33522 which was apparently not fixed

**Comment by Cyberboss** [comment] 2018-01-18 22:42
Duplicate of #33522

**Closed** 2018-01-19 14:51 UTC
Labels: Bug
