### ISSUE TITLE
HUD for containers constantly breaking

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#85597] opened 2024-08-03 22:44 UTC
Reporting client version: 515.1642

## Issue Summary

Any given container will randomly have its HUD be broken, making it totally useless for storage because once you put something in it, you can't look inside to see it again. I have a contractor pinpointer in my modsuit here, but it's invisible because I put it inside after the HUD broke.

## Round ID:
[233356](https://scrubby.melonmesa.com/round/233356)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

Open the storage of any random thing and hope it isn't critical that you be able to access items inside when it breaks.
![image](https://github.com/user-attachments/assets/32a92b2d-0423-4cdd-8351-0304bc6610a6)

**Comment by Sadboysuss** [comment] 2024-08-03 23:56
Dupe of https://github.com/tgstation/tgstation/issues/85259
And https://github.com/tgstation/tgstation/issues/84507

**Closed** 2024-08-04 00:05 UTC
