### ISSUE TITLE
Cult Constructs cannot do anything about Purified Shades

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73786] opened 2023-03-05 04:05 UTC
Reporting client version: 514.1589

## Round ID:
[201236](https://scrubby.melonmesa.com/round/201236)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Be cult artificer.
Have a purified shade running about being a nuisance.
Click on Purified Shade to try and kill it.
Nothing happens.

Jugg wasn't able to do anything either, didn't see any wraith encounters.

I was Artificer (713) and the shade was the Purified Shade of Nico DeLuna, for anyone who might log-dive.

**Comment by Sealed101** [comment] 2023-03-05 05:05
duplicate of #39700

**Closed by Sealed101** 2023-03-05 05:05 UTC
