### ISSUE TITLE
ungenerated lavaland turf visible after bombing

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#69846] opened 2022-09-12 02:24 UTC
bomb went off at the lavaland syndicate outpost
![image](https://user-images.githubusercontent.com/6209658/189563029-3af3e568-0542-4b1c-8506-8d65fc959b89.png)

**Comment by timothymtorres** [comment] 2022-09-12 12:04
Duplicate of #57449

**Closed by timothymtorres** 2022-09-12 12:04 UTC
