### ISSUE TITLE
Shunting from your AI core at any point fails protect objectives targeting you

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#35663] opened 2018-02-14 10:02 UTC
Only really applies to Valentines, but I got a borg shell at one point and it failed my partner's protect objective despite me still even being in the AI core at roundend

**Comment by AnturK** [comment] 2018-02-14 12:09
That's more of an issue with protect objective being human specific than shunting.

**Comment by AnturK** [comment] 2018-02-16 08:36
Duplicate of #35669

**Closed by AnturK** 2018-02-16 08:36 UTC
Labels: Consistency Issue
