### ISSUE TITLE
plasma in space after it was on asteroid shuttle

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#36451] opened 2018-03-15 22:51 UTC
round id 85027

https://file.house/_AHQ.png

plasma released on asteroid shuttle, asteroid shuttle leaves, plasma still there

**Comment by SpaceManiac** [comment] 2018-03-16 02:39
Probably a duplicate of #34861

**Comment by ShizCalev** [comment] 2018-03-20 03:04
Duplicate of #34861

**Closed by ShizCalev** 2018-03-20 03:04 UTC
