### ISSUE TITLE
Demonic frost miner doesnt spawn

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70079] opened 2022-09-22 23:35 UTC
I havent seen the demonic frost miner spawn for months, whatsup with that?

**Comment by newfren** [comment] 2022-09-23 06:08
https://github.com/tgstation/tgstation/issues/68579

**Comment by msgerbs** [comment] 2022-09-23 08:57
Duplicate of #68579

**Closed by msgerbs** 2022-09-23 08:57 UTC
