### ISSUE TITLE
Sawn-off double barreled shotgun still displays the default sprite.

### ISSUE THREAD

**Issue by Snerdly** [tgstation/tgstation#17984] opened 2016-05-28 05:30 UTC
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by phil235** [comment] 2016-05-28 13:22
Duplicate of #16049

**Closed by phil235** 2016-05-28 13:22 UTC
Labels: Bug, Sprites
