### ISSUE TITLE
Bubblegum is shy and hides behind walls

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68927] opened 2022-08-01 23:45 UTC
Reporting client version: 514.1583

## Round ID:
[187724](https://scrubby.melonmesa.com/round/187724)

## Testmerges:
- [fixes nuke ops leaders not spawning](https://www.github.com/tgstation/tgstation/pull/68855)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/182263223-7fa13be3-2f91-4833-b709-9a900cc35c74.png)

**Comment by Mooshimi** [comment] 2022-08-02 23:20
Looks like a layering issue

**Comment by Mooshimi** [comment] 2022-08-02 23:23
Was https://github.com/tgstation/tgstation/pull/67902 not testmerged?

**Comment by LemonInTheDark** [comment] 2022-08-03 08:15
Likely? my fault. will test

**Comment by LemonInTheDark** [comment] 2022-08-04 06:42
This was not actually my fault, though I am unsure of how old this is
It's caused by how the above game hidden plane is relayed 
![image](https://user-images.githubusercontent.com/58055496/182780527-fa2335fd-a484-4943-8aa8-b9b13b90f494.png)
it's relayed onto `GAME_PLANE_FOV_HIDDEN`, which has a lower plane value then walls (IE: `GAME_PLANE_UPPER`), so the plane value gets forcibly shifted down.

was caused by https://github.com/tgstation/tgstation/pull/63903

**Comment by Sealed101** [comment] 2024-09-21 17:19
fixed by #69115 or something else after the plane cube

**Closed by Sealed101** 2024-09-21 17:19 UTC
Labels: Bug

**Comment by LemonInTheDark** [comment] 2024-09-21 19:45
I hate fov, you are correct it was likely the unfoving

**Comment by LemonInTheDark** [comment] 2024-09-21 19:46
#80062
