### ISSUE TITLE
Hallucinations crashing my game, permanent while dead

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23338] opened 2017-01-26 01:36 UTC
Just had a game where hallucinations crashed my game 3 times, and whenever I re-entered my corpse the hallucinations would continue indefinitely.

**Comment by BeeSting12** [comment] 2017-01-26 02:09
Dupe of #22777 and #22565?

**Closed** 2017-01-26 08:23 UTC

**Comment by Robustin** [comment] 2017-01-26 22:45
Reopen the other crash is closed, we're losing tons of connections every time a ling does mindbreaker memes.
