### ISSUE TITLE
Losing your legs cancels out being paraplegic

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#81059] opened 2024-01-22 21:38 UTC
Reporting client version: 514.1589

## Issue Summary/Reproduction
Become paraplegic
Lose your legs
Walk freely with no legs

## Round ID:
[222621](https://scrubby.melonmesa.com/round/222621)

## Testmerges:
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

**Comment by SyncIt21** [comment] 2024-01-23 07:42
Duplicate #80396

**Comment by Jackal-boop** [comment] 2024-01-23 21:49
this reminds me i need to add peg legs

**Comment by ZephyrTFA** [comment] 2024-01-24 00:20
duplicate of #80396

**Closed by ZephyrTFA** 2024-01-24 00:20 UTC
