### ISSUE TITLE
Accelerator laser projectiles expand to cover screen after firing

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#81998] opened 2024-03-14 10:41 UTC
## Issue Summary

The heavy accelerator beam, /obj/projectile/beam/laser/accelerator, explodes and massively scales up in sprite size as it flies away from the turret in which it is shot. Imagine somebody just grabbed the corner and dragged to upscale it until it disappears - sometimes not before it takes up the whole screen.

I have no idea why #81956 might affect this and as far as I can tell it shouldn't, but I'm mentioning it because it's the last thing to touch laser turrets as far as I know.

## Testmerges: 

BYOND Version: 515.1633
Server revision compiled on: 
Master commit: [ea3fb047c46c9534d9c0cbddd091af3876ef5794](https://www.github.com/tgstation/tgstation/commit/ea3fb047c46c9534d9c0cbddd091af3876ef5794)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

Local commit: 69159994d4af1c94e3676e27178af116895adcb7
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Shoot accelerator from portable syndicate turret by changing projectile type manually to accelerator projectile path (as it is in some of the space ruins.)
Watch as a multicolored ball takes over the entire screen and disappears into nothing.
Ponder the nice new turret graphics. 
(reproduced in thunderdome with copied/VEdited turrets.)

**Comment by necromanceranne** [comment] 2024-03-14 10:51
Duplicate of https://github.com/tgstation/tgstation/issues/81811

**Closed by necromanceranne** 2024-03-14 10:51 UTC
