### ISSUE TITLE
Players with paralyzed/missing legs can't use interfaces

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42643] opened 2019-02-02 11:07 UTC
If a player has missing or disabled legs, they lose `mobility_flags = MOBILITY_UI`, which keeps them from using interfaces. 
This doesn't make sense in many cases, for example for handheld PDAs or for when a player is buckled to a wheelchair but can't use computers.

From what I can see, this is caused by the `/mob/living/proc/update_mobility()` proc and its canstand/canstand_involuntary vars.

**Comment by ShizCalev** [comment] 2019-02-02 19:45
Duplicate of #41703

**Comment by ShizCalev** [comment] 2019-02-02 19:45
Yes it is caused by that, been thinking of how to fix it for a while.

**Closed by ShizCalev** 2019-02-02 19:45 UTC
