### ISSUE TITLE
Heretic hearts are deleted on species transformation

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#69574] opened 2022-08-31 00:18 UTC
## Reproduction:
Be a heretic. Turn into another species via mutation tox, DNA spread virus, or any other way. This will cause the heretics heart to be deleted. In the case I observed specifically was in where a player turned into a chem zombie.

**Comment by davethwave** [comment] 2022-08-31 01:47
I'll just generalize it to species transformation as the cause then.

**Comment by timothymtorres** [comment] 2022-08-31 07:19
Duplicate of #35539

**Closed by timothymtorres** 2022-08-31 07:19 UTC
