### ISSUE TITLE
Cant relabel canisters properly

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#58534] opened 2021-04-18 20:30 UTC
## Reproduction:
Whenever you try to relabel a canister the name of it changes but the colour/appearance of the canister remains the same.

**Comment by dragomagol** [comment] 2021-04-18 20:51
Duplicate of #58517

**Closed by dragomagol** 2021-04-18 20:51 UTC

**Comment by SuperNovaa41** [comment] 2021-04-18 21:02
Sad
