### ISSUE TITLE
Megafauna - Legion Causes Massive Framerate drop

### ISSUE THREAD

**Issue by peetrj** [tgstation/tgstation#49388] opened 2020-02-16 03:59 UTC
Issue reported from  Round ID: 130308 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1508

Not the exact round maybe the previous one, but as title states both times I've fought legion have caused my framerate to drop to around 5 fps and time dilation to go up to 40% until the moment the last legion skull is destroyed. Computer should be more than able to handle anything SS13 related so I assume something is up code side.

**Comment by peetrj** [comment] 2020-02-16 09:57
Managed to recreate again just by fighting Legion, seemed to only happen when any Legion part was on screen. Once I was away framerate and time dilation returned to normal but once onscreen issue appeared again. Worse part even after finishing Legion the issue returned when fighting an awakened Herald, same behaviour ~5fps and 40% time dilation round ID: 130336.

I'd like to say for sure that the issue got progressively worse the longer I fought Legion but hard to say for certain

**Comment by nemvar** [comment] 2020-02-16 13:47
Can not reproduce locally.

**Comment by Taylorkills2** [comment] 2020-02-17 17:57
I can confirm this has happened to me about a week ago.
The few prior times I've fought Legion(around 2+ months) I never had any problems.
I can't confirm about time dilation but fps heavily suffers, will test on the main servers, see if it affects others when playing.
I thought it was a local issue at the time due to how fighting the Firedrake lags you out.

**Comment by peetrj** [comment] 2020-02-17 18:35
Time dilation I can only confirm 1 time so take it with a pinch of salt. Does not seem to effect ghosts or at least not in the same way, talking to spectators after dying to Herald and one person spectating they did not have the issue but I don't believe I had anyone spectating Legion fight.

I'll try to get a video of it happening, is their any other data I can gather and if so how do I gather it? New to bug reporting

**Comment by peetrj** [comment] 2020-02-17 20:16
Alright recorded it and it did not happen at all, round id 130429. Very strange only differences I noticed we're legion actually dropped chests (4) whereas with previous times when I did see this issue it didn't drop any and I did the fight much sooner that I normally would've and didn't kill all tendrils or fight a drake which would be my usual process, probably fought Legion closer to 1:30 into the round rather than ~50 minutes this time. 

Also might be related to issue #49414 and Ashdrake is the trigger not Legion but Legion just made it more noticeable as its hard to say for sure but I'm pretty confident both times I saw this I fought Ashdrake first.

**Comment by Taylorkills2** [comment] 2020-02-18 01:16
Okay just fought and killed it, I wasn't suffering from any framerate or fps issues before fighting the legion but about halfway through and afterwards I noticed some fps issues, looks like fighting the legion causes the problem to be worse than the firedrakes, but both cause it.

**Comment by timothymtorres** [comment] 2022-11-07 03:18
Duplicate of #49414

**Closed by timothymtorres** 2022-11-07 03:18 UTC
Labels: Performance, BYOND Issue, Needs Reproducing
