### ISSUE TITLE
Ventcrawling bat bug

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#62430] opened 2021-10-28 21:13 UTC
Round ID: [172108](https://scrubby.melonmesa.com/round/172108)

Reproduction: https://streamable.com/td2pxg

Switching to bat and ventcrawling shows all the pipes and lets you travel through them. If you go human in a pipe, you can still ventcrawl but you take pressure and temperature damage. If you switch back to bat in the vents as a human, you stay without the ventcrawl as if you were a human, although you don't take the damage.

tl;dr: There's no way to get out of vents if you switch to human in them.

**Comment by TheBonded** [comment] 2021-10-29 18:54
duplicate of https://github.com/tgstation/tgstation/issues/62424

**Closed** 2021-11-02 21:26 UTC
Labels: Bug
