### ISSUE TITLE
Jitter Animation Bugs Layers/Planes

### ISSUE THREAD

**Issue by Gottfrei** [tgstation/tgstation#85099] opened 2024-07-19 11:22 UTC
## Issue Summary

Proc /mob/living/proc/do_jitter_animation() works incorrectly when traversing Z-levels. Something with layers/planes idk.

[dreamseeker_XMofhqVUf1.webm](https://github.com/user-attachments/assets/dfb743c5-d9ab-4354-b7a2-387e3ce57c54)

**Comment by Sadboysuss** [comment] 2024-07-20 10:48
Dupe of https://github.com/tgstation/tgstation/issues/84327

**Closed** 2024-07-28 14:09 UTC
