### ISSUE TITLE
Jaunter (miner item) fails to actually teleport you out of chasms if you're stunned

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40448] opened 2018-09-23 17:19 UTC
I'll need to get that one player to give me round ID but the test situation is simple: player killed a tendril, got goliath tentacled, fallen into chasm. Saw the message about getting jaunted out (they wore jaunter correctly) successfully but then another about falling into chasm and died.

It should ignore stuns for automatic activation.

**Comment by DaxDupont** [comment] 2018-09-24 14:02
Feature

**Comment by zeroisthebiggay** [comment] 2018-09-25 10:28
hello this is that miner, round ID was [94260](https://atlantaned.space/statbus/round.php?round=94260)
![ebfbb910c8a186264554ae894ab77a95](https://user-images.githubusercontent.com/43571008/46008945-2300a780-c08c-11e8-9e88-88bc44b7bf47.png)

**Comment by timothymtorres** [comment] 2021-09-18 09:41
This is a duplicate of #60196.  The jaunter behavior for chasms was broken and wouldn't save anyone.  https://github.com/tgstation/tgstation/pull/61055 fixed this.

**Closed by timothymtorres** 2021-09-18 09:41 UTC
Labels: Bug
