### ISSUE TITLE
No indication of damage in ash storms as a positronic brain being inside a Ripley

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#33176] opened 2017-11-29 18:47 UTC
Issue reported from Round ID: 79436 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

As an positronic brain being inside a Ripley in an ash storm, there is no indication of taking damage so you will just suddenly die when you reach the threshold.

**Comment by vuonojenmustaturska** [comment] 2017-11-29 21:19
duplicate of #32187 , posibrains are a subtype of MMI

**Comment by AnturK** [comment] 2017-11-30 07:48
Duplicate of #32187

**Closed by AnturK** 2017-11-30 07:48 UTC
