### ISSUE TITLE
Hitboxes for some items seem enlarged

### ISSUE THREAD

**Issue by jegub** [tgstation/tgstation#38067] opened 2018-05-25 09:07 UTC
[Round ID]:
88445 (first noticed ca. Wednesday)

[Reproduction]:
Place item in locker, try to close it - will pick up placed item instead.
Place item on table, try to place other item on adjacent empty space, will fail as hitbox for placed item overlaps.

Items dumped onto a table from a container are not affected.

![hitboxissue](https://user-images.githubusercontent.com/5722250/40536234-613158a4-6003-11e8-9755-fd25471ce3f1.png)

**Comment by SpaceManiac** [comment] 2018-05-25 09:14
Duplicate of #38013

**Closed by SpaceManiac** 2018-05-25 09:14 UTC
