### ISSUE TITLE
Resin floor sprite gets misplaced on shuttles upon launch

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#25410] opened 2017-03-23 10:37 UTC
![obraz](https://cloud.githubusercontent.com/assets/12747768/24243895/0b193762-0fbd-11e7-87c1-8870f2c052c1.png)

**Comment by ShizCalev** [comment] 2017-10-03 22:02
Duplicate of #18519

**Closed by ShizCalev** 2017-10-03 22:02 UTC
Labels: Bug
