### ISSUE TITLE
Donut intruder gases in the tanks

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#49658] opened 2020-03-01 21:39 UTC
![2c](https://user-images.githubusercontent.com/42839747/75634369-8f7ebf00-5c0d-11ea-9357-a829c7d68c96.PNG)
![2b](https://user-images.githubusercontent.com/42839747/75634370-90175580-5c0d-11ea-9731-37b39db82342.PNG)
![2a](https://user-images.githubusercontent.com/42839747/75634371-90afec00-5c0d-11ea-84c7-4bdb62ae80b3.PNG)
![1c](https://user-images.githubusercontent.com/42839747/75634372-90afec00-5c0d-11ea-96c4-52a49b95a4fa.PNG)
![1b](https://user-images.githubusercontent.com/42839747/75634373-91488280-5c0d-11ea-8e34-f32f4c9f8599.PNG)
![1a](https://user-images.githubusercontent.com/42839747/75634374-91488280-5c0d-11ea-97ea-846705d146d6.PNG)

**Comment by Ghilker** [comment] 2020-03-01 21:44
oh also the cyan line to distro has co2 in it and the o2 tank has nitrogen in it

**Comment by MMMiracles** [comment] 2020-03-01 22:45
something weird is happening here because the tanks have their proper subtypes with the only changes being their initial amount per turf

**Comment by Ghilker** [comment] 2020-03-02 09:15
i was thinking, isnt the amount of gases a bit too low?

**Comment by nemvar** [comment] 2020-03-02 12:44
Maybe there's an issue with gasses spawning inside the window tiles?
The trace gases would indicate that it's a normal air mixture that's being released into the tanks.

**Comment by MMMiracles** [comment] 2020-03-02 13:42
Other stations have regular tiling underneath their windows so that can't be the case.

The only way for that to happen right now is if someone changes the filters on the waste loop, as that's the only physical way for gas to be getting into these rooms right now.

**Comment by kriskog** [comment] 2020-03-02 18:41
There is not nearly enough in the tanks either. My bet is you reverted to pre gas miner removal fix, and have map-edited floors with different gasmix.

**Comment by Dennok** [comment] 2020-03-03 08:20
This tanks one z lvl or has 2 lvl with openspace?

**Comment by MMMiracles** [comment] 2020-03-03 20:08
Okay so the problem is openspace has its own initial gas and that's seeping into the tanks below. Will fix in active PR.

**Closed** 2020-03-03 22:35 UTC
Labels: Mapping
