### ISSUE TITLE
Obsessed hugging objective not working correctly

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#64253] opened 2022-01-19 21:54 UTC
## Round ID:
[176893](https://scrubby.melonmesa.com/round/176893)

## Reproduction:

- Roll obsessed
- Do the huggy wuggy
- Redtext

![unknown2](https://user-images.githubusercontent.com/59461590/150216708-004f5360-c8f8-4162-8df5-be843af3dbf1.png)
![unknown1](https://user-images.githubusercontent.com/59461590/150216613-c39c0d35-e713-4003-a550-1be378fc24de.png)

**Comment by JohnFulpWillard** [comment] 2022-01-21 01:47
Duplicate of https://github.com/tgstation/tgstation/issues/60177

**Closed by JohnFulpWillard** 2022-01-21 01:47 UTC
