### ISSUE TITLE
Beepsky not affected by gravity loss

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#26362] opened 2017-04-18 19:35 UTC
Beepsky moves as normal without gravity, I am assuming the other bots do too.

**Comment by coiax** [comment] 2017-04-18 20:04
I think this is a dupe, and it's marked as a feature, because JUSTICE KNOWS NO LIMITS.

**Comment by GunHog** [comment] 2017-04-18 20:21
### F E A T U R E

**Comment by WJohn** [comment] 2017-04-18 22:42
Likely related to #26141, don't know if I should close this or the other.

**Comment by optimumtact** [comment] 2017-04-18 22:57
not a bug, all pathing ai's must do this to prevent pathing lag storm.

**Closed by optimumtact** 2017-04-18 22:57 UTC
Labels: Bug
