### ISSUE TITLE
Clown car can drag people from any distance after starting drag-in animation.

### ISSUE THREAD

**Issue by TorinoFermic** [tgstation/tgstation#42032] opened 2018-12-21 15:33 UTC
Issue reported from  Round ID: 98984 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

The clown car can affect on resting mobs and start the drag-in animation and it can't be stopped up to crawling away as long the clown car does not move.

**Comment by evsey9** [comment] 2018-12-21 19:58
Feature

**Comment by michnia** [comment] 2018-12-21 23:33
😀

**Comment by YakumoChen** [comment] 2018-12-22 02:54
dupe of #41392

**Closed** 2019-01-02 22:14 UTC
