### ISSUE TITLE
Cannot Retreive Sheets with Protolathe

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#47175] opened 2019-10-18 01:37 UTC
## Reproduction:

Load up some materials in the protolathe, then go into its menu and try to eject the sheets; it won't happen.

The reason for this is some incorrect logic with retrieving materials that generates a runtime on something like this:

`cannot read "diamond".sheet_type`

**Comment by AnonymousNow** [comment] 2019-10-18 07:08
Duplicate of #46170

I know, I did the same.

**Comment by kriskog** [comment] 2019-10-19 12:09
@Qustinnus

**Comment by Detective-Google** [comment] 2019-10-20 23:59
this only happens if you try and eject through the console if you use the machine directly it works as intended afaik

**Closed** 2019-11-09 17:15 UTC
Labels: Bug
