### ISSUE TITLE
Plasmamanification denied + more species limb descriptors

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#69354] opened 2022-08-21 09:45 UTC
Reporting client version: 514.1578

## Round ID:
[188947](https://scrubby.melonmesa.com/round/188947)

## Testmerges:
- [Tilening V2 Part 2.5 - Changing colors](https://www.github.com/tgstation/tgstation/pull/69342)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/185785038-5111c4e4-de0a-4f1f-9fd6-e889c7c778db.png)
Throw some poor sod, like yourself, into a plasma river, expecting a fresh new plasmaman straight out of the oven, instead you just get a burnt mess that refuses to turn purple no matter how much its coldbaked.
Also something something it describing the species limb, I remember y'all were on a war path to remove these descriptors from everywhere possible.

**Comment by Mooshimi** [comment] 2022-08-21 16:27
consistency - plasmaman tranform
feedback - the limb descriptions

**Comment by timothymtorres** [comment] 2022-08-31 07:25
Duplicate of #67282

**Closed by timothymtorres** 2022-08-31 07:25 UTC
Labels: Consistency Issue, Feedback
