### ISSUE TITLE
traitors dont show at roundend

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#30576] opened 2017-09-10 14:12 UTC
it happens often, dont have the round id sorry

**Comment by nicbn** [comment] 2017-09-13 22:26
Known issue

**Comment by BeeSting12** [comment] 2017-10-08 06:01
This occurred round 77148.

**Comment by BeeSting12** [comment] 2017-10-08 21:37
77177

Just gonna keep writing round IDs until coders can find the cause

**Comment by ShizCalev** [comment] 2018-01-05 07:49
Duplicate of #34098

**Closed by ShizCalev** 2018-01-05 07:49 UTC
Labels: Bug
