### ISSUE TITLE
Poly repeating say() messages with their span classes in them

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41236] opened 2018-10-30 14:37 UTC
master
https://github.com/tgstation/tgstation/blob/55a768fef109af873291a4383e1b735a5e5969c5/code/modules/shuttle/special.dm#L298

![image](https://user-images.githubusercontent.com/6209658/47725893-cca8fa80-dc2f-11e8-8fa3-4a29c864d6da.png)

**Comment by k-k-karma** [comment] 2018-10-30 18:41
feature

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-10-30 19:33
is this a duplicate of #41177 ?

**Comment by Time-Green** [comment] 2018-10-30 19:44
<span class='gitcomment'> yes</span

**Comment by Time-Green** [comment] 2018-10-30 19:46
'<span class='gitcomment'> yes</span>'

**Comment by Time-Green** [comment] 2018-10-30 19:46
<div size=100> yes </div>

**Comment by Time-Green** [comment] 2018-10-30 19:47
<font size="60">yes</font>

**Comment by Time-Green** [comment] 2018-10-30 19:49
**yes**

**Comment by Time-Green** [comment] 2018-10-30 19:49
### **yes**

**Closed** 2018-10-30 20:19 UTC
Labels: Bug
