### ISSUE TITLE
Heads can move necropolis tendril nests

### ISSUE THREAD

**Issue by Calebc789c** [tgstation/tgstation#40590] opened 2018-09-29 23:25 UTC
Issue reported from  Round ID: 94646 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Apparently, a flying head, thrown either manually or through gibbing, can move the normally-immobile necropolis tendril nest.

**Comment by SpaceManiac** [comment] 2018-09-30 01:34
presumably duplicate of #40015

**Closed by SpaceManiac** 2018-09-30 01:34 UTC
Labels: Bug
