### ISSUE TITLE
Necropolis chest failed to generated loot, didn't return the key.

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#69497] opened 2022-08-27 10:19 UTC
Reporting client version: 514.1585

## Round ID:
[189323](https://scrubby.melonmesa.com/round/189323)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Adds lazyloading to the asset subsystems](https://www.github.com/tgstation/tgstation/pull/69454)

## Reproduction:
Open chest, recieve nothing. https://github.com/tgstation/tgstation/pull/68719/ was supposed to address this.

**Comment by timothymtorres** [comment] 2022-08-27 11:13
That PR didn't fix the problem.  It just added error logging to make it easier to find what was causing the issue.

**Comment by Striders13** [comment] 2022-08-27 11:14
> That PR didn't fix the problem. It just added error logging to make it easier to find what was causing the issue.

according to the description it's supposed to return your skeleton key and let you try again. It doesn't happen.

**Comment by timothymtorres** [comment] 2022-08-27 11:15
Duplicate of #67650

**Closed by timothymtorres** 2022-08-27 11:15 UTC
