### ISSUE TITLE
Engineering (and maybe mining) cyborgs can ghetto NVGs on the station

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28296] opened 2017-06-10 03:26 UTC
First, equip your mesons
Next, de-equip your mesons once the overlay comes up
Now you are blind to darkness and can see as though you had night vision goggles on

**Comment by ShizCalev** [comment] 2017-08-02 11:35
Dupe #26918

**Comment by ShizCalev** [comment] 2017-08-06 01:38
Duplicate of #26918

**Comment by ShizCalev** [comment] 2017-10-03 17:59
Duplicate of #26918

**Closed by ShizCalev** 2017-10-03 17:59 UTC
