### ISSUE TITLE
Explosions should also pause the space drifting subsystem

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#27888] opened 2017-05-31 00:13 UTC
I saw some stuff drift through an active explosion and avoid getting hit at all.

**Comment by MrStonedOne** [comment] 2017-05-31 19:55
It's generally actually space wind (atmos) causing this.

The issue with postpone (that i'll have to look at addressing) is that it doesn't prevent a paused subsystem from resuming.

**Comment by LaharlMontogmmery** [comment] 2017-06-01 12:20
This is merely a symptom of an already existing bombing problem.

With good timing (or pure luck), it is completely possible to ignore the explosion by walking towards the source.

1. Bomb explodes, You are 3 tiles away from it.
2. Subsystems process the bomb until it is done with the second row of tiles around the source
3. As the second row of tiles is done processing, you move onto that second row.
4. Subsystems process the third row, where you just were - you're now in a safe position that already exploded.

Space wind can cause this, because the stuff drifting through the active explosion repeats this behaviour by its nature (pulling thing towards the center). I've seen half the sec team survive a max cap bomb in total devastation range due to this.

**Comment by LaharlMontogmmery** [comment] 2017-06-01 12:31
@MrStonedOne @ChangelingRain  @Cyberboss 

I know nothing about explosion code, but :

I feel like there should be a explosion "buffer" behind the actual explosion, to avoid things casually flying into explosions and not being affected. This probably would have a impact on performance though.

**Comment by Cyberboss** [comment] 2017-06-01 12:34
There is, it doesn't always work though. I'll take another look at it

**Comment by LemonInTheDark** [comment] 2020-08-04 01:15
Fixed by the instant explosions pr?

**Comment by timothymtorres** [comment] 2021-08-24 12:41
Duplicate of #27888

**Closed by timothymtorres** 2021-08-24 12:41 UTC
Labels: Bug

**Comment by LemonInTheDark** [comment] 2021-08-24 21:09
@timothymtorres you marked it as a duplicate of itself

**Comment by timothymtorres** [comment] 2021-08-25 08:20
Whoops I meant it was a duplicate of #49840
