### ISSUE TITLE
the old white ship ruin has consoles that still function and move the real white ship

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#32647] opened 2017-11-12 00:06 UTC
please help me I keep getting ahelps about why the ship isnt moving

**Comment by Marflowerose** [comment] 2017-11-12 04:51
Possibly dupe of https://github.com/tgstation/tgstation/issues/32136

**Comment by ShizCalev** [comment] 2017-11-17 20:43
Duplicate of #32136

**Closed by ShizCalev** 2017-11-17 20:43 UTC
