### ISSUE TITLE
Melon bowls make your maracas go boom-chiky-boom

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84101] opened 2024-06-18 09:31 UTC
Make a fruit melon bowl and the potassium from banana and water from melon equals delicious delimbing.
![Screenshot_198](https://github.com/tgstation/tgstation/assets/109386467/f2c4d0b7-eca2-4f73-9e72-e571ee3ac7c2)
![Screenshot_199](https://github.com/tgstation/tgstation/assets/109386467/5c14ec84-f460-4501-a001-4e010f06e89c)

**Comment by Dawnseer** [comment] 2024-06-18 10:18
Feature. Vegetarian Arnold pizza

**Comment by iansdoor** [comment] 2024-06-18 10:23
> #81226 Same thing as this actually I think, yep

indeed, it is! but no one has a clever title yet for this feature! 3rd time is a try. looked like this was stopped back in feb

**Comment by ATH1909** [comment] 2024-06-19 00:47
https://www.youtube.com/watch?v=aPzVFWxAVGY

**Comment by SyncIt21** [comment] 2024-06-19 04:30
> #81226 Same thing as this actually I think, yep

It's a proper duplicate so close this. We have way too many open issues already

**Comment by DATA-xPUNGED** [comment] 2024-06-20 21:42
As Sync stated, this is a duplicate of #81226

**Closed by DATA-xPUNGED** 2024-06-20 21:42 UTC
Labels: Oversight
