### ISSUE TITLE
sometimes u cant see people health by examinating

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55934] opened 2021-01-03 20:33 UTC
it only shows what they are wearing and not if they are dead  or theyr wounds and hp

**Comment by MrMelbert** [comment] 2021-01-04 01:01
dupe of #55890 i'd reckon

**Comment by dragomagol** [comment] 2021-01-04 02:07
Duplicate of #55890

**Closed by dragomagol** 2021-01-04 02:07 UTC
