### ISSUE TITLE
Can't interact with things in lower Z-Levels

### ISSUE THREAD

**Issue by YackMiller** [tgstation/tgstation#78916] opened 2023-10-10 22:18 UTC
Reporting client version: 514.1589

## Round ID:
[216464](https://scrubby.melonmesa.com/round/216464)

## Reproduction:
When In lower Z-levels of the station, I am unable to interact with things, as in use computers/machines, open lockers/crates, ctrl+click things, open APC or air alarm menu, attack, etc.
This only happen in lower Z-levels as in the bottom layer of Ice Box Station but not in the upper ones.

**Comment by Sealed101** [comment] 2023-10-11 05:45
Duplicate of #78308

**Closed by Sealed101** 2023-10-11 05:45 UTC
