### ISSUE TITLE
Tratior clowns can cuff themselves via clumsiness. 

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#32394] opened 2017-11-03 22:27 UTC
Title.

This is not OK.

**Comment by swindly** [comment] 2017-11-03 22:51
Dupe of https://github.com/tgstation/tgstation/issues/28467 ?

**Comment by PKPenguin321** [comment] 2017-11-03 23:06
Yes, dupe

**Comment by Supermichael777** [comment] 2017-11-04 00:04
feature the syndicate takes no prisoners

**Comment by ShizCalev** [comment] 2017-11-04 02:17
Duplicate of #28467

**Closed by ShizCalev** 2017-11-04 02:17 UTC
