### ISSUE TITLE
You can forcefully delete the default station AI with a newly created AI from anywhere on any zlevel

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#50548] opened 2020-04-19 04:59 UTC
During the time when github was down we found this bug playing around as free golems. But I believe it could work anywhere even on station.

## Testmerges:

instant explosions
## Reproduction:
Create a New AI, set it all up an all that jazz
give it an ai cyborg shell
have the ai leave the shell
start deconstructing the shell
have the ai link into the cyborg shell at the last second when you are deconstructing the shell

the ai will leave its mob core thing wherever it was and instantly take over the default ai on the station, they literally move to their core and everything. I can't remember the exact details but I think they also inherit the default ai's name and I don't know what happens to the default ai player I think they get ghosted

**Comment by ATH1909** [comment] 2020-04-19 05:59
ASSUMING DIRECT CONTROL

**Comment by ATH1909** [comment] 2020-04-19 06:17
Credit to Anonmare for finding this for me: https://youtu.be/YZvbCgnCJoA

**Comment by TheWiznard** [comment] 2020-04-20 00:59
ouch my feelings this isn't my first issue just first in like 3 years

**Comment by zxaber** [comment] 2020-04-20 02:34
Tested in a local server, unable to reproduce issue.

Steps taken:
- Join server, set job to AI and start round
- ghost, spawn empty core, posi, prebuilt borg shell, and a Boris module
- Join with guest account and take the posi
- Follow above steps using first account in a new humanoid body
- Upon deconstructing the shell, the AI's mind is transferred back to their correct AI mob and does not affect the roundstart AI at all

I've done a rough reading of the AI shell connect/disconnect code, and I don't see anything immediately incorrect. That being said, the shell uses its `mainframe` var (a reference to the AI's core mob and set when an AI is controlling a shell) as a return path during the disconnect steps. Deliberately changing this variable to the roundstart AI results in the reported outcome (second AI player takes control of roundstart AI "body"), so perhaps something is causing this variable to "default" to the roundstart AI?

It would be more than the variable just being left as null, as that simply results in the AI being unable to leave the shell.

**Comment by Tekkuni** [comment] 2020-04-23 15:28
I've had this happen to me maybe 1-2 times on station as the roundstart AI. The details are hazy since it was quite a while ago, but if I recall correctly the other AI was fighting in their shell, got killed and forcefully booted out of the shell and going into my core, replacing me entirely. I think robotics made some mixup at the beginning and the shell had been attributed to both AIs at different points in time. I personally don't do robotics, can't remember if it's the BORIS module that has to be meddled with or the cyborg shell, so not sure how plausible that is.

**Comment by TheWiznard** [comment] 2020-04-23 16:05
oh I think that might have been the case too, I remember now after your comment tekkuni that the other golem who made the ai/borg was messing with the shell cause I think he synced it to the wrong ai at first then somehow rewired it because our ai was saying something similar to that and thats how the station ai found out about golems. I normally save logs of important stuff but just didn't this time rip.

**Comment by LZWlzwsG** [comment] 2020-05-01 06:12
> 在github崩溃的时候，我们发现这个bug作为免费的golem在玩。但是我相信它甚至可以在任何地方都可以使用。
> 
> ## 测试内容：
> 即时爆炸
> 
> ## 再生产：
> 创建一个新的AI，将所有爵士乐都设置
> 为一个AI半机械人外壳，
> 让AI离开外壳，
> 开始对外壳
> 进行解构，然后在解构外壳时的最后一秒将AI链接到半机械人外壳中
> 
> ai会在任何地方保留其暴民核心事物，并立即接管工作站上的默认ai，而他们实际上将移至其核心和所有事物。我不记得确切的细节，但我认为它们也继承了默认AI的名称，我也不知道默认AI播放器会发生什么情况，我认为它们会被重影

我想知道我一个想学代码的新手应该怎么入手呢，求教

**Comment by LZWlzwsG** [comment] 2020-05-01 06:16
I want to know what I'm going to do as a newbie who wants to learn code

**Comment by connnywilmeringBA** [comment] 2020-05-02 11:59
https://www.youtube.com/watch?v=uFYQv9HDAXk

**Comment by wayland-ss13** [comment] 2020-05-03 01:44
Possibly related: during a recent AI round at some point I noticed that my cameras had xray as in I could peer into maintenance through walls, and a main halls outage I had disappeared as a result, but it was too dark to really see in maint unless someone was lighting it up.

Upon leaving my shell for the first time I was greeted with the unpleasant surprise that my cams had regressed permanently.

I am actually not sure how my cams were upgraded in the first place I looked at the wiki and R&D console, but saw no obvious cause, and no crew had approached my core or say like "Yo AI I upgraded your cams with some illegal tech" so maybe it was a glitch to begin with and leaving the shell fixed it?

Also 999th star.

**Comment by zxaber** [comment] 2020-05-03 09:12
There is a known bug where the static overlay disappears. It's still technically there, and it stops you from actually interacting with anything, but visually it's gone. Camera Net is a mess and a half and I don't know where to even start with that bug, but it's been around for a long time.

**Comment by wayland-ss13** [comment] 2020-05-05 11:33
Thanks for the info. I will keep that in mind if I ever want a real challenge for a PR. Just a coincidence it happens to be related to AI Shells.

**Comment by Kylerace** [comment] 2020-10-11 19:53
https://sb.atlantaned.space/ticket/31c167be3dd9ba1d
I thought this bug sounded familiar.

**Comment by TheBonded** [comment] 2020-10-22 21:26
What if the two AIs have different lawsets?
AI 1 has lawset A
AI 2 has lawset B
AI 2 takes over the body of AI 1
what lawset does AI 2 have now?

**Comment by timothymtorres** [comment] 2021-08-19 13:56
This issue could be related:  #52551

**Comment by timothymtorres** [comment] 2021-12-10 10:39
This was fixed with https://github.com/tgstation/tgstation/pull/63247

Multiple AIs inheriting a shell is mentioned in #43388

**Closed** 2021-12-10 10:41 UTC
Labels: In Game Exploit, Bug, Tested/Reproduced, Priority: High, Against God and Nature
