### ISSUE TITLE
Missing TGUI icons

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#56227] opened 2021-01-17 15:01 UTC
## Round ID: [154437](https://scrubby.melonmesa.com/round/154437)

[Round ID]: #154437
BYOND version: 513.1539 (Issue also existed in a previous version)

Missing icons on various TGUI elements, the example posted shows missing icons on the ghost orbit menu and in the admin MIDI controls, but I have observed this in other menus, sometimes the only way to know there are buttons there is to hover the mouse over the elements and hope they have a hover effect, or knowing that the buttons are there. I have had this issue for a few weeks now, though previously the icons did show.

![image](https://user-images.githubusercontent.com/22640529/104846867-a20cf000-58d4-11eb-9522-f61330653761.png)

**Comment by actioninja** [comment] 2021-03-01 04:38
What version of windows are you using?

**Comment by jlsnow301** [comment] 2021-12-29 05:18
Closing this due to:
- lack of interaction
- inability to reproduce this
- implausibility. icons are rendered from fontawesome, so it has a high chance of being local.

**Closed by jlsnow301** 2021-12-29 05:18 UTC
Labels: Bug, Needs Reproducing, UI
