### ISSUE TITLE
The pirate cutter's SMES is fucked

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#51513] opened 2020-06-08 09:42 UTC
See above. For whatever reason it won't put out power to the shuttle, so bullshit like coming back from raiding something and everything having no power for _reasons_ happens.

**Comment by msgerbs** [comment] 2020-08-25 03:17
Is this fixed by #53132?

**Comment by msgerbs** [comment] 2020-09-08 06:36
@TheVekter I don't ever do space exploration, can you confirm if this is still an issue?

**Comment by timothymtorres** [comment] 2021-12-28 10:07
This might be related to #47148 and #39405

**Comment by Sealed101** [comment] 2024-09-24 20:17
could not reproduce; no sudden power loss observed when moving/waiting/fucking around the cutter
likely fixed by #53132 or whatever the fuck 4 years have passed someone somewhere fixed those damn wires

**Closed by Sealed101** 2024-09-24 20:17 UTC
Labels: Bug, Needs Reproducing
