### ISSUE TITLE
Placing objects on a table in zero gravity sends them floating off north

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#85155] opened 2024-07-21 04:06 UTC
Reporting client version: 515.1637

## Issue Summary
When in zero gravity, clicking a table with an item, which should gently set it down on it, instead makes it slide off the table and float off north.

## Round ID:
[232410](https://scrubby.melonmesa.com/round/232410)

## Testmerges:
- [Ghosts once again can see people's true names and roundstart jobs](https://www.github.com/tgstation/tgstation/pull/84951)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)

## Reproduction:
1. Break the grav gen
2. Set your handy dandy broken bottle down on a table while you take a swig off a non-broken bottle
3.
![Screenshot 2024-07-20 230421](https://github.com/user-attachments/assets/95f5a18f-c100-40f0-a17e-c16954800280)
![Screenshot 2024-07-20 230432](https://github.com/user-attachments/assets/f72952cb-91d2-4a5d-b260-e9007ad17519)

**Comment by SmArtKar** [comment] 2024-07-21 08:22
Caused by spacemove refactor, should hopefully be fixed once it gets updated on Manuel

**Comment by Sadboysuss** [comment] 2024-07-27 16:03
> Caused by spacemove refactor, should hopefully be fixed once it gets updated on Manuel

fixed now?

**Comment by SmArtKar** [comment] 2024-07-27 19:40
Yep.

**Closed by SmArtKar** 2024-07-27 19:40 UTC
Labels: Test Merge Bug
