### ISSUE TITLE
prettier is outdated

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#70484] opened 2022-10-12 21:13 UTC
```
["INFO" - 5:11:31 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 5:11:31 PM] Extension Version: 9.9.0.
["INFO" - 5:12:16 PM] Attempted to load Prettier module from c:\Development\Git\tgstation\tgui\.yarn\sdks\prettier\index.js
["ERROR" - 5:12:16 PM] Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier.
```

@jlsnow301

**Comment by jlsnow301** [comment] 2022-10-12 21:14
Not a bug, we are aliasing prettierx  (latest version) as prettier

**Comment by SyncIt21** [comment] 2023-01-15 11:40
@jlsnow301 so it should be safe to close this issue? I still get warnings in VS code but it offers me the option to update anyway

**Comment by jlsnow301** [comment] 2023-01-15 12:36
I've just left it open in case anyone else has the same question. It's fine, here is the package we're using

https://github.com/brodybits/prettierx

**Comment by Mothblocks** [comment] 2023-10-30 21:19
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:19 UTC
Labels: Not a bug, Dependencies
