### ISSUE TITLE
can't Alt+click on the SM

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#45985] opened 2019-08-17 14:16 UTC
Issue reported from  Round ID: 116206 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Like the title says, you cant alt+click on the SM crystal to open the floor menu which is used to safely remove the plating

Reporting client version: 512.1477

**Comment by nemvar** [comment] 2019-08-17 15:53
Probably caused by all the people that touched alt-clicking for machines recently.

**Comment by nemvar** [comment] 2019-08-17 18:41
Getting fixed by #45769

**Closed** 2019-08-20 10:40 UTC
Labels: Bug, Tested/Reproduced
