### ISSUE TITLE
Buildmode generator, Asteroid/Hollow/Random/Monster option

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#15035] opened 2016-01-29 14:03 UTC
Buildmode generator with the asteroid/random hollow/monster option bugged out. It would spawn asteroids with random walls/floors inside but it wouldn't spawn monsters.

For whatever it's worth it was a bit laggy and I was turning buildmode on and off constantly.

**Comment by AnturK** [comment] 2016-01-29 19:58
Can't reproduce, might have just been bad luck since they're not guaranteed to actually spawn monsters.

**Comment by Dorsisdwarf** [comment] 2016-02-24 16:25
Closing in 1 week/ next time I see this if not reproduced

**Closed** 2017-01-11 22:16 UTC
Labels: Needs Reproducing/Testing, Not a bug
