### ISSUE TITLE
Sentient Ecosystems Lavaland cant buy Items Vendor

### ISSUE THREAD

**Issue by badlypayedgoon** [tgstation/tgstation#48478] opened 2019-12-30 17:08 UTC
Issue reported from  Round ID: 126958 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1464

"No registered ID card!
Please contact your local HoP!"

**Comment by trollbreeder** [comment] 2019-12-30 20:41
Duplicate of #48437

**Closed** 2020-01-01 13:59 UTC
