### ISSUE TITLE
Service Borg RSF not working.

### ISSUE THREAD

**Issue by Dothal** [tgstation/tgstation#40605] opened 2018-09-30 12:21 UTC
Issue reported from  Round ID: 94674 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

While playing on TG station today, I decided to play as a service borg. However when I attempted to use the rapid service fabricator to make glasses, it stated it had 0/30 fabrication units. After attempting to charge myself to see if that restored the units it still remained at 0.

After adminhelping, I was told to report the issue here.

**Comment by HydroFloric** [comment] 2018-09-30 17:58
According to Gum Disease the econ pr caused this but was never fixed.

**Comment by Barhandar** [comment] 2018-09-30 18:03
Dupe of #40446

**Closed** 2018-09-30 18:11 UTC
