### ISSUE TITLE
Some objects have mostly transparent pixels.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48607] opened 2020-01-05 15:50 UTC
I’ve observed this issue with two objects - SM and light fixtures. Basically, their sprites have mostly transparent pixels that simulate glow. These pixels are still clickable, making the objects hitbox bigger than it appears to be.

**Comment by trollbreeder** [comment] 2020-01-05 18:32
It's a quirk of BYOND, every non-mask (not 0 alpha) pixel is part of an item's hitbox. Like how having an afro makes you a bigger target.

**Comment by HomocidlePancakes** [comment] 2020-01-06 18:22
Cool story bro. I’ve seen people fix Cyrillic years before 513.  Byond didn’t support it, and yet, it didn’t stop anyone. That’s point number 1. Point number 2 - maybe just don’t use non-mask mumbo jumbo?

**Comment by trollbreeder** [comment] 2020-01-06 18:43
That's not how spriting works.
A pixel has an RGB color, and an alpha. Pixels that are completely transparent are part of the "mask". Every pixel that is not part of the mask is part of an item's hitbox.
The SM and light fixtures simulate glow with these near-transparent pixels, correct. But you cannot mark individual pixels as "not part of an item's hitbox". You'll have to edit BYOND itself to implement this feature, which of course isn't allowed. 
You're gonna have to remove the glow pixels to make the hitbox smaller. Which makes these sprites look a lot more flat.

**Comment by HomocidlePancakes** [comment] 2020-01-06 22:29
Why not just have an overlay like with gasses or something?

**Comment by trollbreeder** [comment] 2020-01-07 17:54
Light switch lag machines updating thousands of light glow overlays and station powernet failures slowing the server to a crawl for a second. I don't think it would work well...

**Comment by HomocidlePancakes** [comment] 2020-01-07 23:56
You mean what we have currently on highpop?

**Comment by trollbreeder** [comment] 2020-01-08 17:12
Yes but double worse because you're updating 2 objects per light

**Comment by MrPerson** [comment] 2020-01-14 05:50
This is fixable by changing the glow to a mouse_opacity 0 object in vis_contents. Updating its sprite wouldn't be that bad. We could even double up and make the glow on the lighting plane so the relevant objects glow in the dark.

Probably not worth the effort though, frankly,

**Comment by ArcaneMusic** [comment] 2020-07-21 03:21
Worth looking into now that we have rad glow, if a similar, smaller overlay could be utilized for this.

**Comment by LemonInTheDark** [comment] 2020-07-21 08:30
@ArcaneDefence It's totally possible yeah

**Comment by LemonInTheDark** [comment] 2020-07-21 08:30
The sm thing is just caused by the massive small deviations present on the sm sprite
You can see it if the thing gets irradiated.

**Comment by timothymtorres** [comment] 2021-12-18 01:20
This appears fixed with https://github.com/tgstation/tgstation/pull/52389

**Closed by timothymtorres** 2021-12-18 01:20 UTC
Labels: Sprites, Consistency Issue

**Comment by LemonInTheDark** [comment] 2021-12-18 03:39
It's technically still a thing, but post supermatter resprite it's much less of a big deal 
![image](https://user-images.githubusercontent.com/58055496/146627689-ce13e673-9d3a-459d-87ec-5da15e9a5f47.png)
