### ISSUE TITLE
windows lost damage overlays

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#79082] opened 2023-10-18 16:18 UTC
Reporting client version: 514.1589

## Round ID:
[216960](https://scrubby.melonmesa.com/round/216960)

## Testmerges:
- [Fixes modified MA overlays potentially causing duplicate overlays](https://www.github.com/tgstation/tgstation/pull/78719)
- [Spider Infestation Balance Rebalance Expansion Part 2](https://www.github.com/tgstation/tgstation/pull/78705)

## Reproduction:

1. damage window
2. no cracks

**Comment by SyncIt21** [comment] 2023-10-18 16:51
![Screenshot (323)](https://github.com/tgstation/tgstation/assets/110812394/e59a0192-ab2a-4614-bca0-f575237f6aab)
![Screenshot (324)](https://github.com/tgstation/tgstation/assets/110812394/df16cadd-a12d-4da7-a14b-a4a945b05dc4)
![Screenshot (325)](https://github.com/tgstation/tgstation/assets/110812394/72f7cb7b-4c94-4978-a6fe-a1a53bb9c400)
Cannot Reproduce.

Let me guess this issue was reported on Campbell?

**Comment by mc-oofert** [comment] 2023-10-18 16:55
![image](https://github.com/tgstation/tgstation/assets/70376633/850491cc-d71d-4cb8-bac6-6716db5ec4a8)
![image](https://github.com/tgstation/tgstation/assets/70376633/b867d7fb-edcc-400b-8c10-4b96b692069d)

**Comment by SyncIt21** [comment] 2023-10-18 16:56
Yeah some weirdness is going on downstream. I just tested this locally and everything works.

**Comment by SyncIt21** [comment] 2023-10-22 04:00
Since this cannot be reproduced on local you should close this, nothing we can do here

**Comment by mc-oofert** [comment] 2023-10-22 09:50
i can see this happen regularly on sybil so this is still an issue

**Comment by mc-oofert** [comment] 2023-10-30 12:16
i think the overlay might be below the grille or window?

**Comment by AdipemDragon** [comment] 2023-11-06 19:35
![image](https://github.com/tgstation/tgstation/assets/76874615/5ece65da-7ee4-40c5-9a51-587255c6a2bf)
almost made a dupe issue for this, it's still very much a thing

**Comment by Fikou** [comment] 2023-11-07 17:52
> Since this cannot be reproduced on local you should close this, nothing we can do here, in this code base atleast

this is the codebase for the tgstation servers including sybil and campbell

**Closed** 2023-11-23 03:23 UTC
Labels: Bug
