### ISSUE TITLE
Non-wall objects set to "smooth more" with walls don't smooth with walls unless they're placed before the walls.

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#38691] opened 2018-06-24 03:50 UTC
**[Reproduction]:** Set any object to have walls in its cansmoothwith list and set it so smooth_more, place two walls then the object, the object will not smooth with the walls

**Comment by zaracka** [comment] 2018-06-24 11:51
Wood walls don't connect properly.

![ss13 wall smoothing issue](https://user-images.githubusercontent.com/37943475/41818638-e5756544-7780-11e8-9c0c-42cf17554035.PNG)

Titanium walls don't automatically smooth with removed/added airlocks.

![ss13 wall smoothing issue 2](https://user-images.githubusercontent.com/37943475/41818705-2f191082-7782-11e8-931f-427b1884975e.PNG)

**Comment by timothymtorres** [comment] 2022-06-03 22:52
Duplicate of #32799

**Closed by timothymtorres** 2022-06-03 22:52 UTC
Labels: Bug
