### ISSUE TITLE
shuttle decals have duplicated on move for a bit now and i do not like it

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#78644] opened 2023-09-27 16:35 UTC
Reporting client version: 514.1589

## Round ID:
[215486](https://scrubby.melonmesa.com/round/215486)

## Testmerges:
- [ArCargo: Adds the Galactic Materials Stock Market V1.2 (Free Market Edition)](https://www.github.com/tgstation/tgstation/pull/78500)

## Reproduction:

1. be in shuttle
2. move
3. every time it moves (enter/exit hyperspace) decals duplicate, occasionally changing dir depending on if the shuttle is rotating
<img width="119" alt="image" src="https://github.com/tgstation/tgstation/assets/80979251/73fada3c-1517-4ccb-b51e-c7298cd9710a">

**Comment by Sealed101** [comment] 2023-09-28 12:21
Duplicate of #76382

**Closed** 2023-09-28 12:21 UTC
