### ISSUE TITLE
Crew monitoring console crashes the game

### ISSUE THREAD

**Issue by JarateProductions** [tgstation/tgstation#27987] opened 2017-06-03 01:24 UTC
Basically I used it twice and it crashed the game both times.

**Comment by factoryman942** [comment] 2017-06-03 01:37
yes it causes cancer when too many people are on the server  with suit sensors on

**Comment by octareenroon91** [comment] 2017-06-06 03:45
This is a request for the non-minimap version to be made available.

**Comment by lzimann** [comment] 2017-06-08 14:18
This is a dupe of an older issue.

**Closed by lzimann** 2017-06-08 14:18 UTC
Labels: Bug
