### ISSUE TITLE
Infinite Ice Lube Grenade Bug (NOT PATCHED 2022 CLOWN GLITCH)

### ISSUE THREAD

**Issue by tgent007** [tgstation/tgstation#69495] opened 2022-08-27 01:01 UTC
Reporting client version: 514.1585

## Round ID:
[189299](https://scrubby.melonmesa.com/round/189299)

## Reproduction:
Put Ice, stable plasma, nitrogen into a grenade casing (Make sure they are all below 100 Kelvin) and activate it. The chemicals remain allowing you to reset the trigger and make ice on the floor for all eternity as long as you can keep resetting that trigger.

**Comment by timothymtorres** [comment] 2022-08-27 08:51
Duplicate of #69483

**Closed by timothymtorres** 2022-08-27 08:51 UTC
