### ISSUE TITLE
I heard the sound of an ahelp, but did not see the text

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55130] opened 2020-11-23 13:55 UTC
## Reproduction: https://sb.atlantaned.space/ticket/fe8bfc0103067366

I made the ticket public. I don't know what led to this happening. 

Part of me suspects that maybe this is part of a larger bug with new chat. Sometimes I will say things, both on comms and not, where I see the runescape text, but nothing in the chat box. Don't have any proof for those so they might be caused from something completely different, just throwing it out there.

**Comment by brotherbeyondd** [comment] 2020-11-23 14:10
That's cos of the new chat. I LOVE the new chat but it sometimes voids messages (ahelps or just regular chat). I believe a previous issue was made on this, cant find it though so 🤷.

**Comment by Fikou** [comment] 2020-11-23 19:30
this happens with anything, regular chat, deadchat, ooc

**Comment by LemonInTheDark** [comment] 2020-11-23 22:05
Dupe of #54692

**Comment by Fikou** [comment] 2020-11-23 22:26
duplicate of #54692

**Comment by Fikou** [comment] 2020-11-23 22:26
Duplicate of #54692

**Closed** 2020-11-23 22:25 UTC
Labels: Bug, Priority: High
