### ISSUE TITLE
You can not carry someone up a ladder or stairs if they are buckled to you.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59212] opened 2021-05-20 20:34 UTC
Reporting client version: 513.1536

## Round ID:
N/A

## Reproduction:
Fireman carrying someone and trying to move to a different Z-level causes you to drop the person.

**Comment by dragomagol** [comment] 2021-05-20 21:13
Duplicate of #49968

**Closed by dragomagol** 2021-05-20 21:13 UTC
