### ISSUE TITLE
Simplemobs attacking objects is completely unlogged.

### ISSUE THREAD

**Issue by Timberpoes** [tgstation/tgstation#63272] opened 2021-12-06 04:57 UTC
## Reproduction:

Be a simplemob. Attack an object, such as a plasma or N2O can, or an APC in order to grief the station.

Be amazed at how you get away with your shittery because it's not logged and the admins don't know who to bwoink.

Bonus points if you're plasma flooding as spiders since there'll be so many ghosts recycling bodies that you're guaranteed to slip under the radar and ruin the shift or your money back.

https://gfycat.com/glumconfusedazurevasesponge

**Comment by Timberpoes** [comment] 2021-12-06 05:01
I'm labelling this a high priority issue.

Attack logging is one of the most important types of log entries we've got when it comes to administration.

Something as basic as simplemob attacks not being logged means neither the players nor the admins can trust the attack logs when dealing with simplemobs.

We also have an entire job in Cytology that's designed around giving sentience to grief machines.

**Comment by Mothblocks** [comment] 2021-12-06 07:25
Dupe of #60759 but you wrote more so I'm closing the other one

**Closed** 2022-01-02 22:25 UTC
Labels: Logging, Priority: High
