### ISSUE TITLE
being inside a bileworm when it evolves removes your body from the shift entirely

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#78080] opened 2023-09-02 01:33 UTC
i was conscious when this happened but i assume it happens with normal dead bodies too, when the 30 minute mark hits and the bileworms evolve into vileworms, any body they're digesting straight up dissappears, this doesn't seem like intended behaviour.

**Comment by Ghommie** [comment] 2023-09-02 14:07
Dupe of #76791.

**Closed by Ghommie** 2023-09-02 14:07 UTC
Labels: Bug
