### ISSUE TITLE
Button options are stacked vertically in pop-ups

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#64782] opened 2022-02-09 01:25 UTC
Reporting client version: 514.1575

## Round ID:
[178074](https://scrubby.melonmesa.com/round/178074)

## Testmerges:
- [Fixes layering issues brought by the FoV PR.](https://www.github.com/tgstation/tgstation/pull/63903)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction:
No idea if this is intentional or not
![image](https://user-images.githubusercontent.com/66640614/153103637-b154978c-25b2-4b59-95ea-99247527e7ad.png)
![image](https://user-images.githubusercontent.com/66640614/153103765-7aab05f2-3736-4f0a-be12-93558b9cdf25.png)

**Comment by jlsnow301** [comment] 2022-02-09 03:39
not a bug. buttons just overlapped titles (especially in never for this round).
i wasn't pleased and changed this behavior in #64757

**Comment by jlsnow301** [comment] 2022-02-09 03:42
flagging for cleanup: assuming my PR is merged, this behavior will change. if not, i will just PR the change to alert window itself because stacked buttons is actually ugly

**Closed** 2022-02-15 09:20 UTC
Labels: Not a bug, UI, Cleanup Flagged
