### ISSUE TITLE
Swiping your ID on a CRAB-17 too early explodes it and breaks the economy

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#69953] opened 2022-09-16 08:40 UTC
## Reproduction:

Call in a CRAB-17

Have it land right in front of you

Swipe your ID before the spacecoin market unfolds itself

The market explodes instantly

Funds are not draining

Everybody's bank accounts remain frozen for the rest of the round

**Comment by san7890** [comment] 2022-09-23 18:55
Duplicate of #69045 it seems.

**Closed** 2022-09-25 18:49 UTC
