### ISSUE TITLE
Lava boat doesn't protect items in hand

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#21791] opened 2016-11-27 17:29 UTC
When pulling an item out of inventory slots/backpack, while riding a lava boat over lava, the item will get set on fire as though it were dropped in lava.

Expected behaviour would be for the item to be protected from lava, same as the occupant is protected by the boat.

**Comment by PKPenguin321** [comment] 2016-11-27 18:00
Dupe

**Comment by Arianya** [comment] 2016-11-27 18:53
Can you link the issue? Not seeing any issues open with keyword lava or boat

**Comment by KorPhaeron** [comment] 2016-11-27 19:04
@phil235 

I think

**Comment by optimumtact** [comment] 2016-11-27 21:08
it's because items are technically dropped onto the ground before being picked up.

that behaviour is hardwired into the code and difficult to change

**Comment by optimumtact** [comment] 2016-11-27 21:08
dupe of #20885

**Closed by optimumtact** 2016-11-27 21:08 UTC

**Comment by jughu** [comment] 2016-11-27 21:36
Ots just very hot ok
