### ISSUE TITLE
helmets thrown on your head don't hide your hair

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87497] opened 2024-10-26 20:05 UTC
### Client Version:

515.1642

### Issue Summary:

used a sec helmet

### Round ID:

[240789](https://scrubby.melonmesa.com/round/240789)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. aim head
2. throw helmet at humanoid
3. watch hair isn't hidden
note, the visor may need to be up

**Comment by Jewelry-x** [comment] 2024-10-27 13:13
This behaviour is also present if you put the helmet on with the menu that pops up when you drag someone on to you. 

This menu to be more precise.
![image](https://github.com/user-attachments/assets/d4c632d7-2ac6-4edd-a698-2ad2e7bd28b8)

**Comment by SmArtKar** [comment] 2024-11-26 23:40
Duplicate of #85028 actually

**Closed by SmArtKar** 2024-11-26 23:40 UTC
Labels: Tested/Reproduced, Oversight
