### ISSUE TITLE
Screen keeps freezing on me

### ISSUE THREAD

**Issue by Cuboos** [tgstation/tgstation#20963] opened 2016-10-13 18:34 UTC
This is getting extremely annoying, it's been going on for a month or two now. Right in the middle of game play the screen will completely freeze on me, it's only the screen though, i can still chat and use other buttons and tabs, just not interact with anything on the screen. It's happened several times during combat before and cost me the fight and it just happened when i was a captain in my office. My screen froze and a traitor managed to sneak in and kill me while wasn't even aware of it or able to do anything about it.

**Comment by lzimann** [comment] 2016-10-13 19:31
I'm pretty sure it is a byond issue, I've heard more people complaining about it at least.

**Comment by Tacolizard** [comment] 2016-10-13 19:31
Apparently this is just a BYOND issue and can't really be fixed. It's been around for a while now.

**Comment by WJohn** [comment] 2016-10-13 19:38
Dupe of #2601
Byond issue, it's been around probably since the dawn of time.

**Closed by WJohn** 2016-10-13 19:38 UTC
Labels: Bug
