### ISSUE TITLE
Cell Chargers don't work on whiteships without APCs, but weapon chargers and borg chargers do

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62762] opened 2021-11-11 23:38 UTC
I did not get the round id because I went to sleep instead of making this report last night woops

This was specifically on the alien ufo white ship. 
The prebuilt weapon charger worked, as did another I built myself, and the borg charger charged borgs, but the cell charger I built (then deconstructed and rebuilt later) did not charge a cell.

On a previous round I had this issue even after building and powering a smes and an apc in the ship, so something fucky's going on with the area or whatever.

**Comment by timothymtorres** [comment] 2021-11-12 11:39
Duplicate of #62182

**Closed by timothymtorres** 2021-11-12 11:39 UTC
