### ISSUE TITLE
Items can duplicate if two people pick it up at once.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#26502] opened 2017-04-23 23:36 UTC
This is a dupe but it's also pretty high priority as it's been happening to me a lot lately. If I pick up an item at the same time as someone else, it duplicates the item, causing it to lose funcitonality and act weird. ie, You can't take off duplicated gloves and sometimes they won't appear on your sprite. Toolbelts open and close at random times/won't open at all. Multitools are permanently in the background of your toolbelt in a certain spot. Spears cause you not to be able to pick up anything on your offhand, etc. Tends to happen when in combat and two people go for the same item at once, usually a dropped gun, or at roundstart when people are rushing insuls/tools/toolbelts. By duplicate, I just mean that the game thinks it's in two places at once.
Cause of #25259, #25273.

**Comment by WJohn** [comment] 2017-04-23 23:42
Looks to be a dupe of #25814

**Closed by WJohn** 2017-04-23 23:42 UTC
