### ISSUE TITLE
Lavaland ruins inexplicably sometimes have a tile replaced with lava.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31403] opened 2017-10-07 03:49 UTC
![](https://i.imgur.com/pzXhtAw.png)

Been seeing this for over a week, not sure what causes it. It doesn't happen in the same place, and it doesn't seem to be because of lava rivers. It is a mystery.

**Comment by ShizCalev** [comment] 2017-10-07 04:16
Duplicate of #27719

**Closed by ShizCalev** 2017-10-07 04:16 UTC
Labels: Bug
