### ISSUE TITLE
banana projectles from honk staff get stuck indefinetly into windows

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39772] opened 2018-08-18 11:36 UTC
they get stuck in like those 2x single windows in 1 tile and cause infinite lag and client crashes
92679 bagil

**Comment by RedFoxIV** [comment] 2018-08-18 15:16
It's not a bug, it's a feature to counter people with tasers, you just crash them to desktop

**Comment by kriskog** [comment] 2019-12-31 07:00
Dupe of #39815

**Closed by kriskog** 2019-12-31 07:00 UTC
Labels: Bug
