### ISSUE TITLE
Cursor flickers loading icon while on /tg/ servers, preventing hovering on sprites to see names

### ISSUE THREAD

**Issue by Genesis720** [tgstation/tgstation#34942] opened 2018-01-25 17:39 UTC
[Round ID]: 82530 (and all rounds before)

Issue is as such: When logging on to a /tg/ server, as soon as the game itself opens, the mouse cursor begins to flicker between a normal cursor icon and the normal cursor + loading icon.

Looks like this: [https://img00.deviantart.net/f7fa/i/2012/128/9/1/windows_8_rc_cursors_by_franmonzter-d4yzf3o.png](url)

The loading icon will flicker on and off a few times a second, and it prevents me from mousing over things to view their names, and is generally very annoying and distracting.

I just began playing yesterday after more than a years hiatus. This doesn't happen when the byond launcher or any other SS13 server is open, just /tg/. All my settings are vanilla, nothing has been changed. I have tried reinstalling byond, with no luck. 

I'm hoping you all can point me in the right direction to get this fixed. Thanks!

**Comment by Genesis720** [comment] 2018-01-25 17:42
Update: While I was AFK to write this report, the problem seems to have gone away. There is no cursor flickering and I can hover sprites to view them. Ill update again tonight if the problem returns.

**Comment by praisenarsie** [comment] 2018-01-25 18:17
known

**Comment by epochayur** [comment] 2018-01-25 18:50
#33997

**Comment by ShizCalev** [comment] 2018-01-25 22:18
duplicate of #33997

**Closed by ShizCalev** 2018-01-25 22:18 UTC
