### ISSUE TITLE
Can click-move drag wheeled office chair one is sitting in.

### ISSUE THREAD

**Issue by Treachce** [tgstation/tgstation#85524] opened 2024-08-02 18:03 UTC
## Issue Summary
When sitting in a wheeled swivel office chair, one can drag the office chair then click on the adjacent tile to move the office chair while sitting in it.

## Round ID:
[233188](https://scrubby.melonmesa.com/round/233188)

## Testmerges:
n/a

## Reproduction:
Find a swivel office chair, sit in it, activate drag mode on the office chair while sitting in it, then click on an adjacent tile.

**Comment by SmArtKar** [comment] 2024-08-02 18:27
Is this really a bug/oversight? From a logical perspective it makes sense that you'd be able to do that

**Comment by Treachce** [comment] 2024-08-02 18:33
I am sitting in a swivel office chair right now, and when I try to drag it to a different location while sitting in it, it doesn't move. Something about Newton's laws of motion.

**Comment by Sadboysuss** [comment] 2024-08-02 19:05
it's basically you moving your feet while in the chair to propel yourself, I don't see this being a problem.

**Comment by Sadboysuss** [comment] 2024-08-02 19:06
marked as not a bug, if you have any extra questions you're free to ask them, this is cleanup flagged and will be auto-closed in 7 days

**Closed** 2024-09-08 14:01 UTC
Labels: Not a bug, Cleanup Flagged
