### ISSUE TITLE
White crayon + Gloves = Latex

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#34941] opened 2018-01-25 17:27 UTC
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 82530

Server revision compiled on: 2018-01-25

The following pull requests are currently test merged:
#34793: 'Armor datums' by vuonojenmustaturska at commit 261a5f
#33810: 'Cult Update' by Robustin at commit e83d6d

Based off origin/master commit: 364bc7

Revision: eaac7fd2630f5c875700473c08d7109b05f47fc4

Server tools version: /tg/station 13 Server v3.2.1.11

Server tools API version: 3.2.0.2

See title, when combining a white crayon with a pair of gloves, you'll get latex gloves instead of white ones.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-01-25 19:16
funny enough it's not a bug

https://github.com/tgstation/tgstation/blob/c06390278eab76817ee57e7ae73bfa21f2a612f4/code/modules/clothing/gloves/color.dm#L159-L168

https://github.com/tgstation/tgstation/blob/c06390278eab76817ee57e7ae73bfa21f2a612f4/code/modules/clothing/gloves/color.dm#L178-L183

**Comment by vuonojenmustaturska** [comment] 2018-01-26 15:00
Couldn't this be fixed by just swapping the item_colors?

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-01-26 16:54
yes but mime crayon giving you latex seems silly

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-01-26 17:38
This is actually a really easy fix just set the item_color of the white crayon to "mime" as well.

There's honestly plenty of latex gloves in medbay if you needed them for a particular reason over white gloves. It's not like they're a hot item lol.

**Comment by Bawhoppen** [comment] 2018-01-26 21:39
The whole item_color system needs a revamp

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-01-28 02:30
yeah but that's work

**Closed** 2018-03-03 06:02 UTC
Labels: Consistency Issue
