### ISSUE TITLE
Raptors launch you off them if you're hit with watcher blasts

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#84655] opened 2024-07-05 01:49 UTC
Reporting client version: 515.1641

## Round ID:
[231633](https://scrubby.melonmesa.com/round/231633)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
 #84306 had the unfortunate side effect of making fighting watchers with a raptor an absolute nightmare. I get stationside raptors are a problem but I dont think this was the intention

**Comment by Sadboysuss** [comment] 2024-07-05 07:48
Dupe of https://github.com/tgstation/tgstation/issues/84596

**Closed** 2024-07-07 19:04 UTC
Labels: Oversight
