### ISSUE TITLE
RCD can place walls below girders

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#63727] opened 2021-12-31 20:41 UTC
## Reproduction:
This wasn't done by me but by a borg.
-Reinforced walls got blown up and left only reinforced girder behind.
-Borg tries to repair it with RCD but somehow places a normal wall below the reinforced girder.
- You can't finish the girder now but you can disassemble the girder or the wall normally

**Comment by timothymtorres** [comment] 2022-03-18 10:37
Duplicate of #37162

**Closed by timothymtorres** 2022-03-18 10:37 UTC
Labels: Bug
