### ISSUE TITLE
Dark-mode (#43072) colour issues omnibus 

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#43242] opened 2019-03-21 00:16 UTC
#43072 @carshalash 

hard to read MC and admin ticket panels when disabled.

![image](https://user-images.githubusercontent.com/6209658/54727224-fe721d80-4b4c-11e9-8ce5-c93e564f8936.png)

**Comment by ShizCalev** [comment] 2019-03-21 00:41
admin ticket PM view isn't in dark mode

**Comment by Dorsisdwarf** [comment] 2019-03-21 00:46
Lightmode
- OOC is now pasty light blue
- admin pms are no longer highly-visible red, they're black
-Admin ticket list is light grey and barely readable
Darkmode
 -minor thing, but darkmode background is "too light" according to some players (And annoyingly isnt the same colour as the background of the dark UI panels like borg-panel or traitor-panel)
-Apparently deadchat is super hard to read now (dark purple on dark blue)

**Comment by Dorsisdwarf** [comment] 2019-03-21 00:48
> 
> 
> admin ticket PM view isn't dark when darkmode is enabled.

In general, popups dont have colour but I dont think they're meant to

**Comment by carshalash** [comment] 2019-03-21 01:19
I'm noticing that the font in the textbar was changed too from this. For what purpose?

**Comment by MASMC** [comment] 2019-03-21 02:57
![image](https://user-images.githubusercontent.com/9438930/54731229-79dec980-4b63-11e9-8e4e-8e8c6239768c.png)
Working as intended :ok_hand:

**Comment by optimumtact** [comment] 2019-03-21 03:35
that isn't even related to the theming

**Comment by optimumtact** [comment] 2019-03-21 05:57
#cca300 looks great for ooc in dark mode, but we'll need basically two configs as this is something not usually set by css/skin files

**Comment by Barhandar** [comment] 2019-03-21 06:29
>I'm noticing that the font in the textbar was changed too from this. For what purpose?

Noticing that too, memearrows especially have become daring and bold.
>In general, popups dont have colour but I dont think they're meant to

Admin PMs _are_ meant to be bright red, always were.

**Comment by actioninja** [comment] 2019-03-21 09:44
> ![image](https://user-images.githubusercontent.com/9438930/54731229-79dec980-4b63-11e9-8e4e-8e8c6239768c.png)
> Working as intended 👌

this was broken before because goonchat is a mess

**Comment by actioninja** [comment] 2019-03-21 14:44
> * Admin ticket list is light grey and barely readable

Admin tickets being the wrong colors is actually due to a misunderstanding of how admin PMing works, it's formatted differently depending on whether the sender or receiver is an admin. Admin -> admin isn't red, admin -> non admin is.
![image](https://user-images.githubusercontent.com/5194834/54760354-2abd8680-4bad-11e9-8214-2c6888f7b8b7.png)

**Comment by carshalash** [comment] 2019-03-22 04:29
![image](https://user-images.githubusercontent.com/16896032/54800668-d69acb00-4cae-11e9-8d11-206a43e49d13.png)
I love how you guys made it default to darkmode no matter what now and leaving chat bar like this even in lightmode, very cool.

**Comment by tralezab** [comment] 2019-03-22 05:33
tip of the round is extremely hard to read

**Comment by Barhandar** [comment] 2019-03-22 06:54
Carsh, it's worse. This is how it looks on dark:
![inputdark](https://user-images.githubusercontent.com/2338212/54805579-6e38f300-4c88-11e9-8f41-a8601ef8660a.PNG)

The solution is to _not touch the colors of input bar at all_.

**Comment by actioninja** [comment] 2019-03-22 11:00
> The solution is to _not touch the colors of input bar at all_.

Wow, I've literally never thought about it this way. Thank you for the brilliant insight on development and decision making here.
I'll make sure to inform every issue poster here that the solution to the problem is to just remove whatever is causing the problem.

> tip of the round is extremely hard to read
I didn't find it to be that bad, but it probably could be easier to read.


> I love how you guys made it default to darkmode no matter what now and leaving chat bar like this even in lightmode, very cool.

Both of these are bugs, and are resolved by #43275 Swap in and out of dark mode to fix the chat, hit tab twice to fix the input bar.

**Comment by ShizCalev** [comment] 2019-03-24 19:38
Emojis have white grounds per #43316

**Comment by actioninja** [comment] 2019-03-25 08:48
You gotta be fucking kidding me.

**Comment by actioninja** [comment] 2019-03-25 08:59
EVEN BETTER: It's literally just the crying laughing emoji and the thumbs up and down emojis that have white backgrounds.

**Closed** 2019-05-09 10:30 UTC
Labels: Oversight, Priority: CRITICAL
