### ISSUE TITLE
Dragon sprite invisible

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#77779] opened 2023-08-20 05:14 UTC
Reporting client version: 514.1589

## Round ID:
[212955](https://scrubby.melonmesa.com/round/212955)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
1. A dragon is spawned.
2. Observe it's sprite is mostly invisible.

Picture for context.

![image](https://github.com/tgstation/tgstation/assets/38709973/dec32eac-886d-47d1-b62c-4b6927240ee5)

**Comment by IndieanaJones** [comment] 2023-09-28 22:53
Probably has something to do with the new transparent sprite system, I've noticed that sometimes, SD will be incorrectly offset but I can't reproduce it locally.

**Comment by Sadboysuss** [comment] 2024-06-24 20:37
seems to be working fine on latest version of master

**Closed** 2024-09-17 05:55 UTC
Labels: Needs Reproducing, Cleanup Flagged
