### ISSUE TITLE
AIs taking control of Exosuits cannot use equipment

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#65022] opened 2022-02-19 19:12 UTC
Reporting client version: 514.1578

## Round ID:
[178683](https://scrubby.melonmesa.com/round/178683)

## Reproduction:

1. Put an AI control beacon in a mech
2. Get in the mech (as AI)
3. Attempt to shoot with guns
4. Nothing happens while using any of the mouse buttons
5. Cry

**Comment by Dorsisdwarf** [comment] 2022-02-26 18:03
Duplicate of 64112

**Closed by Dorsisdwarf** 2022-02-26 18:03 UTC
