### ISSUE TITLE
healium only tries to put you to sleep when it starts and stops metabolizing

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#66407] opened 2022-04-21 23:11 UTC
this means that if you're immune to PermaSleeping() when a dose of healium enters your system (due to, say, being inside of an immortality talisman or void magnet field), you can avoid being put to sleep by (but will still be able to be healed by) the healium dose until it fully leaves your system, you get strapped to a stasis bed, etc.

**Comment by ArcaneDefence** [comment] 2022-04-22 04:31
Duplicate of https://github.com/tgstation/tgstation/issues/66399

**Closed by ArcaneDefence** 2022-04-22 04:31 UTC
Labels: Oversight
