### ISSUE TITLE
These are some very strange looking monkies....

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49040] opened 2020-01-27 19:08 UTC
Issue reported from  Round ID: 129053 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

The windoor is labeled as "Monkey Pen"
My cursor is invisible for some reason
![Képernyőfelvétel (12)_LI](https://user-images.githubusercontent.com/54288658/73205186-ccecba00-4140-11ea-8517-a85112424ca5.jpg)

**Comment by trollbreeder** [comment] 2020-01-27 19:19
Is the floor named monkey pen?
Is the door named monkey pen?
Are the monkeys corgis?

I can't tell if the issue is one, more, or all of the above.

**Comment by Jalleo** [comment] 2020-01-28 13:47
copy paste issue

**Comment by kriskog** [comment] 2020-01-28 15:30
Genetics removal issue. I made access changes to it in #48668, Ill fix it next time I touch pubby there.

**Comment by kriskog** [comment] 2020-01-30 04:12
Now fixed in #48668

**Closed by kriskog** 2020-01-30 04:12 UTC
Labels: Bug
