### ISSUE TITLE
Bile/vileworms are not organic

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#77965] opened 2023-08-27 10:07 UTC
## Reproduction:

Found it while testing Polymorph belt
![Screenshot_40](https://github.com/tgstation/tgstation/assets/64209864/00a13b64-5fe7-4e96-b60e-c1d73ac92eb2)

**Comment by Sealed101** [comment] 2023-08-27 10:32
Duplicate of #77756

**Closed by Sealed101** 2023-08-27 10:32 UTC

**Comment by Livrah** [comment] 2023-08-27 10:47
Raw Prophet is not organic too, but looks like the list is too big to bother.
