### ISSUE TITLE
Supply Remote cant access Cargo shuttle

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#70907] opened 2022-10-30 04:58 UTC
Reporting client version: 514.1589

## Round ID:
[193371](https://scrubby.melonmesa.com/round/193371)

## Testmerges:
- [Chefs can now kiss food they make to make it with love. (And a lot of cooking refactoring)](https://www.github.com/tgstation/tgstation/pull/70409)
- [Fix halloweens races](https://www.github.com/tgstation/tgstation/pull/70874)

## Reproduction:
Be QM
Try to use supply remote on the doors of the cargo shuttle
Error: network_error_bad_receiver_id

**Comment by newfren** [comment] 2022-10-30 05:20
https://github.com/tgstation/tgstation/issues/69720 but for every shuttle

**Comment by Mooshimi** [comment] 2022-10-30 18:42
Duplicate of #69720

**Closed by Mooshimi** 2022-10-30 18:42 UTC
Labels: Mapping
