### ISSUE TITLE
turbine will burn wires

### ISSUE THREAD

**Issue by Crosoak** [tgstation/tgstation#51228] opened 2020-05-23 16:34 UTC
## Reproduction:
1. set up turbine
2. wires under turbine chamber's reinforced tiles leading to SMES will burn off
3. smes wont be charged due to broken wires

**Comment by nemvar** [comment] 2020-05-24 18:47
State of the art design from certified NT engineers.

**Comment by nemvar** [comment] 2020-05-24 18:48
Please say which map you are talking about, I'm not going to check them all.

**Comment by spookydonut** [comment] 2020-05-24 18:51
dupe of #51195

**Closed** 2020-05-24 18:50 UTC
Labels: Mapping
