### ISSUE TITLE
Zero gravity lava walk

### ISSUE THREAD

**Issue by Fallen1220** [tgstation/tgstation#76380] opened 2023-06-28 04:00 UTC

**Comment by Sealed101** [comment] 2023-06-28 05:10
?

**Comment by SyncIt21** [comment] 2023-06-28 06:27
!!

**Comment by Sealed101** [comment] 2023-06-28 06:39
fill out the issue template and describe the issue in detail with reproduction steps, otherwise i'm closing this within 3 days

**Comment by Sealed101** [comment] 2023-06-28 12:18
## You MUST fill out the report for clarity, because an issue manager/contributor may not be able to pull enough data out of the round's logs. Here's what I've found, however.

judging by the game logs, the station was experiencing a gravity generator blackout. the player used red/blue cubes linked to a room on lavaland mining station. somehow, the gravity did not update
getting similar vibes to #75480, as both the cubes and the fulton use `forceMove()`

code (__OW__)
https://github.com/tgstation/tgstation/blob/8b258383362c02b820859b0c022e4085d320b5da/code/modules/mining/lavaland/tendril_loot.dm#L319-L352

**Closed** 2024-12-06 18:05 UTC
Labels: Bug
