### ISSUE TITLE
the game told me to make this bug report about resource downloading?

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#81960] opened 2024-03-12 11:53 UTC
Reporting client version: 515.1630

## Issue Summary
something about not accessing asset cache

## Round ID:
[225421](https://scrubby.melonmesa.com/round/225421)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/e9f279e5-6397-444a-b1ab-72151de3635b)
I would do anything some red text told me to

**Comment by san7890** [comment] 2024-03-16 22:11
@MrStonedOne would you happen to have any insights into this (or know who would)?

**Comment by MrStonedOne** [comment] 2024-03-16 23:16
There is a zero width/height browser control embedded into the skin used by the asset cache system to load javascript that handles letting the server know what assets the client has, this message comes up if the game server couldn't access this. control freak should force a skin download so most likely ie or internet security settings is keeping this from loading, or ping could be keeping the messages from arriving in time.

**Comment by newfren** [comment] 2024-03-17 00:04
likely ping, I haven't seen this message since and iirc was having a hard time connecting to the server

**Comment by TheVekter** [comment] 2024-03-20 16:50
Gonna close this since it seems to be working as intended (or at least not a bug).

**Closed by TheVekter** 2024-03-20 16:50 UTC
