### ISSUE TITLE
Chem implants can't be loaded in implanter

### ISSUE THREAD

**Issue by KuzyXD** [tgstation/tgstation#20097] opened 2016-08-25 12:13 UTC
Hi, i am from russian community where use your build. We have faced a problem with your chem implants. I can't load liquid as it is specified in the description and implant others.

**Comment by Jalleo** [comment] 2016-08-25 12:14
Dupe of #19889

**Comment by KuzyXD** [comment] 2016-08-25 12:17
Oh... Sorry for this.

**Comment by AnturK** [comment] 2016-08-25 12:18
It's ok.

**Closed by AnturK** 2016-08-25 12:18 UTC
