### ISSUE TITLE
Lantern wisp prefers the spectral blade.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52615] opened 2020-07-31 14:24 UTC
## Reproduction:

1. Acquire a wisp lantern from a necropolis chest.
2. Use the wisp lantern inhand to gain thermals and a pet wisp.
3. Acquire a spectral blade from a necropolis chest.
4. Put down the spectral blade.
5. Notice that the wisp likes the sword more than you.

![Wisp-sword](https://user-images.githubusercontent.com/53582584/89044032-42a72d80-d2fe-11ea-9e22-0c52b6032c09.PNG)

## Expected Behavior: 

I expected that the wisp would not abandon me for a chunk of shiny metal.

## Notes:

- I expect that this is happening because of the way the spectral blade aggregates ghosts.
- The wisp leaving you does not remove the thermals it grants, effectively granting invisible thermals.

**Comment by timothymtorres** [comment] 2021-11-07 11:32
Duplicate of #47565

**Closed by timothymtorres** 2021-11-07 11:32 UTC
