### ISSUE TITLE
Aux base turrets dont fire at local fauna

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73275] opened 2023-02-06 20:15 UTC
## Round ID:
[199595](https://scrubby.melonmesa.com/round/199595)

## Reproduction:
Drop the aux base near a hostile mob. In this case it was a bile worm, goliath, and legion. Watch as the turrets don't care about the mobs

**Comment by timothymtorres** [comment] 2023-02-08 07:54
Duplicate of #67208

**Closed by timothymtorres** 2023-02-08 07:54 UTC
