### ISSUE TITLE
Engi hardsuit and high capacity powercell

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51078] opened 2020-05-12 16:31 UTC
136937 

I had engi hardsuit. The power cell run out of power. I put a new high capacity power cell from deconstructed SMES. The suit's thermal regulation didnt work and when examined it stated that the suit has "INVALID power left"

**Comment by Archanial** [comment] 2020-05-12 21:09
Dupe of #50265

**Comment by Fikou** [comment] 2020-06-06 09:22
Duplicate of #50265

**Closed by Fikou** 2020-06-06 09:22 UTC
