### ISSUE TITLE
Asteroid sand on lavaland

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#37100] opened 2018-04-10 14:50 UTC
![image](https://user-images.githubusercontent.com/6778786/38564383-08ea1f4c-3cad-11e8-974e-0fbb163cd548.png)

![image](https://user-images.githubusercontent.com/6778786/38634230-e060f9fe-3d8f-11e8-9bdf-d4b67c727cde.png)

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-10 14:53
epic luls

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-10 14:57
https://github.com/tgstation/tgstation/blame/master/code/game/turfs/simulated/floor/plating/asteroid.dm#L54

Something to do with this?

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-10 18:56
@ninjanomnom recent baseturf pr?

**Comment by ninjanomnom** [comment] 2018-04-11 01:03
One day we will just start closing issues with insufficient details.

Did it generate like that? If not what did you do to make that appear? What round id?

**Comment by Kromgar** [comment] 2018-04-11 04:09
It generated like that. i've been seeing quite a bit of asteroid sand the last couple rounds

**Comment by Therapist1** [comment] 2018-04-11 13:25
I’ve seen it too, only about one piece I believe, just in a pre-generated tunnel alone.

**Comment by Barhandar** [comment] 2018-04-11 13:52
Seeing these regularly now and _not_ in the ruins.

**Comment by Kromgar** [comment] 2018-04-11 17:54
@ninjanomnom 
![image](https://user-images.githubusercontent.com/6778786/38634221-db518a32-3d8f-11e8-8540-8a079ed47cba.png)

**Comment by Kromgar** [comment] 2018-04-11 21:32
![image](https://user-images.githubusercontent.com/6778786/38644365-3c7dbea2-3dae-11e8-91b5-cbdca55151ff.png)

**Comment by Barhandar** [comment] 2018-04-13 18:07
![muchfix](https://user-images.githubusercontent.com/2338212/38750769-801e7f28-3f45-11e8-953e-44a4a97938bf.png)

**Comment by ninjanomnom** [comment] 2018-04-13 20:46
You don't need to keep linking images

**Comment by ninjanomnom** [comment] 2018-04-14 23:10
Those asteroid sand turfs aren't getting `SpawnFloor` called on them during the generation process. This is caused by https://github.com/tgstation/tgstation/commit/64eff003068cb85ee5857e140b5e4b23a32d86d2

@Robustin

**Comment by Iatots** [comment] 2018-07-14 20:58
Still happening, also duplicate of #35326

**Comment by kriskog** [comment] 2019-07-11 14:27
duplicate

**Closed by kriskog** 2019-07-11 14:27 UTC
Labels: Bug
