### ISSUE TITLE
Blank GUIs

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#51224] opened 2020-05-23 13:32 UTC
## Reproduction:

1. Open GUIs and observe no anomalous behavior.
2. Open a GUI and observe that it is a blank white square.
  - If you are lucky it has the minimize and close buttons at the top in which case you can close it. Otherwise you need to walk away from the source of the GUI until the game closes it automatically.
  - You're out of luck if you open the ghost role menu and it covers half the verbs.
3. Observe that every GUI you open afterwards is a blank white box.

**Comment by stylemistake** [comment] 2020-07-16 19:33
Duplicate of #47793

**Closed by stylemistake** 2020-07-16 19:33 UTC
Labels: Bug, UI
