### ISSUE TITLE
AI State Laws Function Issue

### ISSUE THREAD

**Issue by hankhillsbizarreadventure** [tgstation/tgstation#26203] opened 2017-04-13 23:32 UTC
The AI State Laws function has a problem where it will only output the first law into the chat if any law is changed to the "No" setting. This leads to a situation where one must state all laws in order to comply with a request for one specific law that isn't Law 1. Please fix.

**Comment by Davidj361** [comment] 2017-04-14 17:07
I'll try to fix this today, a lot of code refactoring is needed with AI laws in general.

**Comment by Profakos** [comment] 2017-04-14 21:19
Duplicate of #25128

**Closed** 2017-04-15 07:38 UTC
Labels: Bug
