### ISSUE TITLE
you can spam purification on soulshards

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#44874] opened 2019-06-29 16:15 UTC
Issue reported from  Round ID: 111905 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

you can spam purification on soulshards

**Comment by DaxDupont** [comment] 2019-06-29 16:15
IE: you can spam purification on soulshards.

**Comment by wesoda25** [comment] 2019-06-29 16:49
Fix pr is already up plus duplicate issue

**Comment by nfreader** [comment] 2019-06-29 17:10
Dupe of #44678

**Closed by nfreader** 2019-06-29 17:10 UTC
