### ISSUE TITLE
Service borgs cant click on tables

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#85220] opened 2024-07-24 12:48 UTC
Reporting client version: 515.1641

## Issue Summary
You cant place a glass on a table by left clicking on it via a beverage apparatus, or spawn a glass on a table by left clicking it with the rapid service fabricator
## Round ID:
[232573](https://scrubby.melonmesa.com/round/232573)

## Testmerges:
- [Replaces Auxlua with the byondapi-based Dreamluau](https://www.github.com/tgstation/tgstation/pull/84810)

## Reproduction:

1. Pick up a glass with the beverage apparatus
2. Try to place it on a table via left clicking
3. Try to spawn a glass on a table with the rsf

**Comment by Sadboysuss** [comment] 2024-07-24 13:27
dupe of https://github.com/tgstation/tgstation/issues/85181

**Closed** 2024-07-24 13:27 UTC
