### ISSUE TITLE
Positronic brains have no access while in mechs

### ISSUE THREAD

**Issue by JohnKiwols** [tgstation/tgstation#69085] opened 2022-08-08 21:02 UTC
## Reproduction:
Construct any mech.
Put in a positronic brain, or board the mech with no ID.  
Attempt to open an access restricted door - hey presto!

## Summary:
Mechs cannot be assigned access - this means positronic brains in mechs cannot open anything except public airlocks.
The wiki says posibrains (and MMI's?) can be assigned access; this doesn't seem implemented.

**Comment by ShizCalev** [comment] 2022-08-08 22:37
hm, should be working...

![image](https://user-images.githubusercontent.com/6209658/183526268-981441a0-6147-4bad-bfff-36a574832f8d.png)

![image](https://user-images.githubusercontent.com/6209658/183526240-4995ce1f-2181-4c6d-ab0d-793804c979ea.png)

![image](https://user-images.githubusercontent.com/6209658/183526228-abdc08b8-5d88-4238-a0e7-b7d8b8dbcba8.png)

![image](https://user-images.githubusercontent.com/6209658/183526206-40a06fb3-1449-4ed9-86a4-c39faa510923.png)

**Comment by JohnKiwols** [comment] 2022-08-08 23:14
i'm not an ss13 coder though I'm considering it - rooted through and here's my two cents:

do positronic brains return true on issilicon? obviously they should
however, my reflex looking at the code with bright, innocent eyes is posibrains are
\mob\living\brain\posibrain
issilicon is looking for \mob\living\silicon:
`#define issilicon(A) (istype(A, /mob/living/silicon))`
posibrain.dm has nothing useful to say on the matter

**Comment by JohnKiwols** [comment] 2022-08-08 23:16
MMI's are also under this umbrella.
do these hierarchies refer to the file structure?
e.g. /mob/living/brain/MMI.dm?

**Comment by timothymtorres** [comment] 2022-08-09 06:43
Duplicate of #62153

**Closed by timothymtorres** 2022-08-09 06:43 UTC
Labels: Oversight
