### ISSUE TITLE
Deconstructed wall on lavaland is acting like pressure sink.

### ISSUE THREAD

**Issue by kisiel090** [tgstation/tgstation#34398] opened 2018-01-13 13:52 UTC
[Round ID]: 81840

[Reproduction]: Deconstruct a wall on lavaland

I was playing a hermit and decided to deconstruct a wall. Lava spawned under it, and every item in my small home got sucked inside the lava after wall girders burned down. I think this is too much of a space wind for one empty tile. 
![image](https://user-images.githubusercontent.com/35222553/34906626-3a09d39a-f871-11e7-9250-a5fef0afb245.png)

**Comment by ninjanomnom** [comment] 2018-01-13 17:05
dupe of #34321

**Closed by ninjanomnom** 2018-01-13 17:05 UTC
