### ISSUE TITLE
Neuuwhine (Inverse Chem) can (not) be consumed

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#63167] opened 2021-11-30 14:40 UTC
## Testmerges:
#63079 
#63098 

## Reproduction:
1. Make Inverted Neurine (Neruwhine) (Supposed to cause temporary brain traumas)
2. Try to consume it in an alcoholic beverage/syringe/using eye drops.
3. The u count does not decrease?
4. Be smart, use a pill
5. See the body never metabolize it. Ever. No traumas created, no nothing.
6. Only trauma gained, that seemed to be related to the chem was Hypnotic_Stupor, which after looking at round stats, could very well have been the random trauma event.

**Comment by ATH1909** [comment] 2021-11-30 19:43
maybe the metabolization rate is getting rounded to 0?

**Comment by SuperNovaa41** [comment] 2021-11-30 19:59
Are you sure you had the right chemical made? I tested with 5u in syringe, pill, mixed into a drink and drinking it straight and got brain damage each time. You might've messed something up

**Comment by necromanceranne** [comment] 2021-12-01 07:34
It could be something breaking with purity here. It'd be a good idea to track this one down, since it's possible that the issue is more broad than just this chem.

**Comment by SuperNovaa41** [comment] 2021-12-01 13:30
I just tried a range of different purities using the debug chem machine, but still had no issues.

**Comment by Vanadiom** [comment] 2021-12-01 21:54
Well, I am one hundred percent sure that It happened the round I mentioned?

The Metabolization rate is also probably not a problem, because it actually just straight up did **not disappear at all**.

Like, I had this drink with 45u blank paper and 5u Neurine (Neruwhine, obviously inversed, checked with the machine. But it did show as Neurine in the Chemglass display) and when a barman and I tried to drink it, the 5u Neurine (Inversed) **never disappeared** out of the glass, It also didn't disappear from the syringe when injecting, nor did it get removed from my dropper when I tried squirting it in eyes.

**Comment by Vanadiom** [comment] 2021-12-01 22:10
Yeah wait, if the inverse threshold has been reached isn't the chem supposed to be fully converted into the inverse?
Is that then supposed to be shown in a 'chemmaster'/'chem goggles'?
Because if that didn't work, could it have completely lost the /datum/ somehow?

**Comment by SuperNovaa41** [comment] 2021-12-21 18:33
This was almost definitely fixed by https://github.com/tgstation/tgstation/pull/63363

**Closed by SuperNovaa41** 2021-12-21 18:33 UTC
Labels: Needs Reproducing
