### ISSUE TITLE
if two people click on one item at the exact same time both of them will have it, but one will be mgsv the phantom pain

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26668] opened 2017-04-28 01:26 UTC
![2017-04-28_03-46-57](https://cloud.githubusercontent.com/assets/16103879/25510700/cdd6412c-2bca-11e7-90cc-691158e78e14.png)

this is only ONE ion rifle, the one i had was the phantom one and was fake, but its inhand appeared 
**AND IT MIRRORED THE SAME SLOT/HAND AS TO WHERE IT WAS ON THE OTHER GUY**

**Comment by PKPenguin321** [comment] 2017-04-28 01:40
Dupe of https://github.com/tgstation/tgstation/issues/25814

**Closed** 2017-04-28 02:09 UTC

**Comment by BeeSting12** [comment] 2017-04-28 15:20
kind speaks to how much of a priority the issue is
