### ISSUE TITLE
Lavaland syndicate base gas miners trap all gas in a 1 by 1 area

### ISSUE THREAD

**Issue by Serusjei** [tgstation/tgstation#47093] opened 2019-10-14 16:53 UTC

**Comment by TheChosenEvilOne** [comment] 2019-10-14 21:07
This should be fixed by just changing the turfs in the syndicate base tanks to the atmos tank variants.

**Comment by kriskog** [comment] 2019-10-15 00:22
Honestly, we could just get rid of the gas miners and replace with the tank floors entirely. That's probably the best solution.

**Comment by Cyprex** [comment] 2019-10-15 16:28
This keeps happening with gas miners, regression that happens a lot. Pretty sure there is also an open bug report for this already. This has also been an issue on Donut at some point. Kilo also uses gas miners so this might need looking into.

**Comment by kriskog** [comment] 2019-10-15 16:42
I have replaced the gas miners in the tanks with gas floors and improved the piping a bit. It was my understanding that gas miners were on their way out, since you know infinite gas.

**Comment by kopoba** [comment] 2019-10-21 06:35
looks like its fixed on bagil or bug happens from time to time
and there is dupe https://github.com/tgstation/tgstation/issues/41279
![image](https://user-images.githubusercontent.com/5034345/67181647-3e082d00-f3ee-11e9-9188-5e710ddbad17.png)

**Closed** 2019-10-22 11:41 UTC
Labels: Atmospherics, Bug
