### ISSUE TITLE
Reconnecting to dead AI core sends you to the void.

### ISSUE THREAD

**Issue by vendingmachine24** [tgstation/tgstation#68567] opened 2022-07-18 22:06 UTC
## Round ID:
[186878](https://scrubby.melonmesa.com/round/186878)

## Reproduction:

AI core destroyed by sm shard electricity while in shell, did not die. Attempting to reconnect to AI core send you to the void where you have the AI hud but cannot use it and can see dead chat but not speak in it

**Comment by timothymtorres** [comment] 2022-07-20 23:49
More than likely this is caused by #68451 or #68063 since these both were merged recently.

**Comment by Sealed101** [comment] 2024-10-23 20:28
can't reproduce; unlikely that this was caused by the runtime fixed in https://github.com/tgstation/tgstation/pull/78816 but in any case when the core dies, the ai dies even if in a shell.

**Closed by Sealed101** 2024-10-23 20:28 UTC
Labels: Bug
