### ISSUE TITLE
MMI's dont work in mechs

### ISSUE THREAD

**Issue by Nilons** [tgstation/tgstation#28268] opened 2017-06-09 14:10 UTC
Server revision compiled on:  2017-06-08 

6f5157 

When you put an mmi in a mech its able to move it but not able to use any equipment or other functions of the mech.  Its only able to walk.  Multiple people have experience this bug and I will link a forum thread regarding it towards the bottom.

https://tgstation13.org/phpBB/viewtopic.php?f=2&t=11564

**Comment by GunHog** [comment] 2017-06-09 16:40
I have isolated the cause (After being screwed over by `world <<` not working any more. Thanks Cyberboss...). Mob clicks have a `loc` check for the mecha type. MMIs however are mobs contained within the MMI object. _The loc of a MMI brainmob is always its MMI object._ They therefore always fail the mecha type check.

https://github.com/tgstation/tgstation/blob/master/code/_onclick/click.dm#L98

**Comment by PKPenguin321** [comment] 2017-06-09 20:48
Dupe of https://github.com/tgstation/tgstation/issues/24422

**Closed** 2017-06-10 18:49 UTC
