### ISSUE TITLE
Client crashes on attacking objects with items

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#17821] opened 2016-05-21 05:43 UTC
1 - the attack overlay stays on top of the object for longer than it should(visually)
2 - after each attack you get a chance of the client crash
3 - the faster you mush the mouse button the more likely is client to crash(doubleclick issue?)

**Comment by Razharas** [comment] 2016-05-21 05:50
@phil235

**Comment by phil235** [comment] 2016-05-21 11:50
Can't reproduce.

**Comment by optimumtact** [comment] 2016-05-21 13:04
Hmm I wonder, @phil235 and @Razharas what version are you byond clients right now?

**Comment by phil235** [comment] 2016-05-21 13:58
I'm on 510.1336, not the most recent one that makes progress bars buggy.

**Comment by Razharas** [comment] 2016-05-21 21:00
Im on the latest beta

**Comment by MrStonedOne** [comment] 2017-08-11 20:39
this would have been fixed with the add_overlay rewrite.

**Closed** 2017-08-11 20:40 UTC
Labels: Bug, BYOND Issue, Needs Reproducing/Testing
