### ISSUE TITLE
Custom vendors are bugged

### ISSUE THREAD

**Issue by notsolot** [tgstation/tgstation#59523] opened 2021-06-06 02:18 UTC
after an item is put in I get this message in the GUI:

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error.
   at https://tgstation13.download/byond/assets/95/asset.958eee5f721c6f93480ddb850dbb2604.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"yungchegg","interface":"Vending","window":{"key":"[0x20381e3]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2525-2561

**Comment by dragomagol** [comment] 2021-06-06 07:11
Duplicate of #59445

**Closed by dragomagol** 2021-06-06 07:11 UTC
