### ISSUE TITLE
manually adminspawning revenants doesnt seem to give them their powers/traits

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#88303] opened 2024-11-30 13:47 UTC
### Issue Summary:

basically as title says, manually spawned a revenant and it was visible and had no spells

this is more of an adminbus bug but it is technically a problem so

### Reproduction Steps:

1. spawn a revenant via spawn menu (basic/revenant)
2. put a player in control of it
3. they are visible and seemingly cant do revenant things

**Comment by SmArtKar** [comment] 2024-11-30 13:51
Unable to reproduce - please provide further details and a round ID, otherwise the issue will be closed in a week.

**Comment by nianjiilical** [comment] 2024-11-30 15:50
okay weird i tried again and it works fine, i guess it was an unrelated issue from the other night, my bad

**Closed** 2024-11-30 16:04 UTC
Labels: Needs Reproducing, Cleanup Flagged
