### ISSUE TITLE
Gold slime reaction to_chat and flashes working through walls

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#27815] opened 2017-05-28 20:57 UTC
Wearing mesons, and in maint, I saw the flash and chat notifications associated with a gold slime reaction that happened somewhere else. I'm pretty sure it happened in Metastation's experimentation room, since the mesons let me see its turfs.

**Comment by lzimann** [comment] 2017-06-01 16:22
Can't reproduce this. No flash or message when the reaction happened.

**Comment by SpaceManiac** [comment] 2018-12-28 20:17
Closing as unreproduced

**Closed by SpaceManiac** 2018-12-28 20:17 UTC
Labels: Bug, Needs Reproducing
