### ISSUE TITLE
Toggle Darkness does not work as a ghost

### ISSUE THREAD

**Issue by Gandalf2k15** [tgstation/tgstation#74287] opened 2023-03-27 04:02 UTC
Reporting client version: 515.1602

## Round ID:
[202585](https://scrubby.melonmesa.com/round/202585)

## Testmerges:
- [New Cosmic Heretic Path DLC](https://www.github.com/tgstation/tgstation/pull/73915)

## Reproduction:

On client version 515.1602 pressing toggle darkness does not remove darkness from the map.

**Comment by YakumoChen** [comment] 2023-03-27 17:58
To be more clear with this since I had the bug

Lighting of any kind aside from wall-mounted lights did not function whatsover. Flashlights, Toggle Darkness, etc. Client-side lighting doesn't work.

This bug only exists in client ver. 515 (current BYOND beta branch), not 514 (current BYOND stable)

**Comment by LemonInTheDark** [comment] 2023-03-28 03:42
dupe of the 515 issue yes https://www.byond.com/forum/post/2859593

**Closed by LemonInTheDark** 2023-03-28 03:42 UTC
