### ISSUE TITLE
New parsnip sabre cannot fit in its sheathe

### ISSUE THREAD

**Issue by General-Gaston** [tgstation/tgstation#85331] opened 2024-07-28 07:00 UTC
Reporting client version: 515.1640

## Issue Summary

its as stated, the parsnip sabre cannot fit within its grass sheathe. It can hold a regular sabre and even has the icon of the parsnip sabre when the captain's sword is in it, but doesn't fit the parsnip variant

## Round ID:
[232771](https://scrubby.melonmesa.com/round/232771)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)

**Comment by Sadboysuss** [comment] 2024-07-28 07:12
Dupe of https://github.com/tgstation/tgstation/issues/85306

**Comment by General-Gaston** [comment] 2024-07-28 07:25
Might be so but It also says its fixed. it is not fixed

**Comment by Sadboysuss** [comment] 2024-07-28 07:45
> Might be so but It also says its fixed. it is not fixed

The issue report is still open. A pull request is open that will close that issue, and then it will be marked as completed.

**Closed** 2024-07-28 09:00 UTC
