### ISSUE TITLE
Bug with toggling Engineering Scanner Goggles

### ISSUE THREAD

**Issue by Blonkz** [tgstation/tgstation#21284] opened 2016-10-30 17:52 UTC
To reproduce:
Equip engineering scanner goggles. Toggle them on via HUD. Then move character.
Shadows from earlier will move with you, until you turn off the goggles.

**Comment by phil235** [comment] 2016-10-30 21:50
Sounds like a byond issue. Which version are you using?

**Comment by phil235** [comment] 2016-10-30 21:53
Most likely a duplicate of #21264

**Closed by phil235** 2016-10-30 21:53 UTC

**Comment by Blonkz** [comment] 2016-11-03 09:48
Was using the stable one. After upgradeing it disapered.
