### ISSUE TITLE
Snappop's (Clown Shuttle) Chasms are broken

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#42356] opened 2019-01-13 19:38 UTC
Poor Snappop shuttle...

**Comment by ATH1909** [comment] 2019-01-13 19:57
Would you mind elaborating on this a bit more?

**Comment by Shadowflame909** [comment] 2019-01-13 20:04
Specifically, there you go.

**Comment by Shadowflame909** [comment] 2019-01-13 20:34
Whatchu talkin bout Time-Green

**Comment by Time-Green** [comment] 2019-01-13 20:58
the moment a shuttle arrives or leaves it instantly becomes a real chasm for one second and kills everyone on it

**Comment by Shadowflame909** [comment] 2019-01-14 00:44
Epic Prank. But its a bug and is not what the shuttle is about

**Comment by MimicFaux** [comment] 2019-01-14 02:43
They were originally real chasms. When was the _fun_ removed?

**Comment by Shadowflame909** [comment] 2019-01-14 04:17
They still half-work. As Time-Green said, it's just buggy.

**Comment by kriskog** [comment] 2019-06-27 22:46
Seen these working lately, still an issue?

**Comment by kriskog** [comment] 2019-06-27 22:53
Actually, dupe of #42160

**Closed by kriskog** 2019-06-27 22:53 UTC
Labels: Needs Reproducing
