### ISSUE TITLE
Rat King rats cant follow Rat King using stairs

### ISSUE THREAD

**Issue by Cutplays** [tgstation/tgstation#77520] opened 2023-08-10 21:26 UTC
Round ID:[212234](https://scrubby.melonmesa.com/round/212234)

Reproduction: Summon rats as rat king, Order rats to follow, Go up or down using a stair case,

**Comment by Jacquerel** [comment] 2023-08-10 22:32
Currently our "follow" AI is too stupid to understand z levels. 
This isn't technically a "bug" because it's a known thing, but it'd be nice if someone took the time to add it.

**Comment by BlueMemesauce** [comment] 2023-08-12 00:21
Same as #73664 then

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug
