### ISSUE TITLE
Spontanious Dezombification.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49678] opened 2020-03-02 19:18 UTC
Round: 131376
IC name: You Are Already Touhou

So this happened near the end of the round. Got bitten, died, became a zambie. Some time after end up going in to crit due to heat and succumb. My body turns back in to a human and I stop being a zombie.

**Comment by XDTM** [comment] 2020-03-03 08:18
the zombie tumor reverts to the old species when destroyed, so maybe organ decay could have been the cause, or maybe the head got dusted if you were burning

**Comment by HomocidlePancakes** [comment] 2020-03-03 14:58
I wasn't on fire, just hot.

**Comment by msgerbs** [comment] 2020-10-11 06:06
I'm going to close this as a duplicate of #51330 even though it's the older issue just because that issue has more detail in it.

**Closed by msgerbs** 2020-10-11 06:06 UTC
Labels: Needs Reproducing
