### ISSUE TITLE
Spray cans do not run out properly

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#38687] opened 2018-06-23 23:44 UTC
After using the spray can a lot, messages will start to appear saying `There is not enough of the spray can left!`, despite still working. After a good while using it still, it does actually run out.

**Comment by spessbandit** [comment] 2019-10-22 22:23
dollars to donuts this is the weird decimal reagent bug striking again

**Comment by timothymtorres** [comment] 2022-10-23 14:24
Duplicate of #31206

**Closed by timothymtorres** 2022-10-23 14:24 UTC
Labels: Bug
