### ISSUE TITLE
cant move or se my hatacter after ayyliens

### ISSUE THREAD

**Issue by gustufus** [tgstation/tgstation#26573] opened 2017-04-25 19:27 UTC
i played as a chaplain then while walking around the station i got hit by a advanced stunbaton and draged into a dorm, then i got teleported to the ayylien space ship they probed me and then sudenly the camera got swithed to the arival shuttle but my character was not there.

**Comment by BeeSting12** [comment] 2017-04-25 23:43
You need to type Cancel-Camera-View in the command line. This happens when you become an abductor sometimes, wizard, etc.

**Comment by PKPenguin321** [comment] 2017-04-26 01:15
Dupe of https://github.com/tgstation/tgstation/issues/25147

**Closed** 2017-04-26 09:52 UTC
Labels: Bug, Needs Reproducing/Testing
