### ISSUE TITLE
Mech's equipment doesn't check for the range after the beggining of an action.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#73559] opened 2023-02-20 13:22 UTC
## Round ID:
Checked on the private server with the current build.

## Reproduction:
1) Install an equipment with the progress bar(i.e. the Hydraulic Clamp) or with a chain of the progress bars(i.e. Drills).
2) Start an action on an any applicable object.
3) Move away from that object, but do not break the line of sight with it.
4) The sequence will complete regardless.
Drill, by the known fact, is a very potent weapon.

**Comment by Ryusenshu** [comment] 2023-02-20 13:37
Ah right, totally forgot about a similar issue i had on a borg RCD
i accidentally double tapped a floor while fixing a breach and a wall started to get made, and was completed even after i moved away

**Comment by Sealed101** [comment] 2023-02-20 14:31
dupe of #66874

**Closed** 2023-02-20 14:46 UTC
