### ISSUE TITLE
You can move in space as long as remain next to someone else

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21406] opened 2016-11-07 22:25 UTC
As long as you're next to someone else who is dense/not being pulled by you, you can move in space.
Or in other words two people that don't happen to have any way of space movement can break physics as long as they're really careful.

**Comment by PKPenguin321** [comment] 2016-11-07 22:31
Could by solved by applying a tiny stun on a human when another human pushes off of them

**Comment by RemieRichards** [comment] 2016-11-07 22:32
Not a stun, should just push them the opposite direction, like what already happens with objects.
that way there'd be a turf gap between them AND they'd both have inertia opposite each other.

**Comment by PKPenguin321** [comment] 2016-11-08 00:46
>Not a stun, should just push them the opposite direction

does it not already do that?

**Comment by factoryman942** [comment] 2016-11-09 13:55
Only with objects like lockers. Other people just stay still

**Comment by KorPhaeron** [comment] 2016-11-22 08:00
This doesn't sound worth fixing

**Comment by TheBonded** [comment] 2021-06-03 03:54
I feel like this isn't a bug anymore, but a feature, as it seems to be a well known thing between anyone who has played in zero g. Does anyone ever wonder why we have 1.8k issue reports?

**Comment by timothymtorres** [comment] 2021-08-23 10:51
> I feel like this isn't a bug anymore, but a feature, as it seems to be a well known thing between anyone who has played in zero g. Does anyone ever wonder why we have 1.8k issue reports?

Agreed.  There are so many duplicates, feature requests, and clutter that a serious effort needs to be made and maintained to reign these issues down.

**Comment by TheBonded** [comment] 2021-12-07 17:12
> > I feel like this isn't a bug anymore, but a feature, as it seems to be a well known thing between anyone who has played in zero g. Does anyone ever wonder why we have 1.8k issue reports?
> 
> Agreed. There are so many duplicates, feature requests, and clutter that a serious effort needs to be made and maintained to reign these issues down.

now that I have the power to, I'm going to mark this as not a bug and cleanup flagged. 

if anything, a fix for this would be to make pushing off someone in space push them away, like with lockers. but that would make this a feature request.

**Comment by SuperNovaa41** [comment] 2021-12-07 17:35
@TheBonded you should check with a maintainer, since even oranges labelled it.. it's probably not actually intended

**Comment by TheBonded** [comment] 2021-12-07 17:37
> @TheBonded you should check with a maintainer, since even oranges labelled it.. it's probably not actually intended

will do, I'm fairly certain this isn't a bug though

**Comment by TheBonded** [comment] 2021-12-07 17:45
@Watermelon914 and another maintainer confirmed this is not a bug.

**Closed by TheBonded** 2021-12-07 17:45 UTC
Labels: Not a bug, Oversight
