### ISSUE TITLE
Modular console bug

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#32836] opened 2017-11-17 10:46 UTC
It has a broken screen sprite:
![bugged](https://user-images.githubusercontent.com/12028974/32943587-a6639590-cb9d-11e7-8f0a-e145f4cfe941.jpg)

**Comment by Jordie0608** [comment] 2017-11-17 10:58
Duplicate of #32802 
Pending #32822

**Closed by Jordie0608** 2017-11-17 10:58 UTC
