### ISSUE TITLE
Sometimes the static in the AI view will just disappear

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#60851] opened 2021-08-14 01:02 UTC
## Round ID: 
[167760](https://scrubby.melonmesa.com/round/167760)

## Testmerges: 
Not relevant

## Reproduction:
Unknown
(This has happened to me before, when the testmerges were totally different or there were no testmerges at all)

I have no idea what triggers this, but out of nowhere you, as the AI, suddenly have no static on the places where you should have it (maint, space, anywhere without a camera really). I managed to record two videos, one of the static gone and one of it suddenly coming back:

Here's one of me showing the non-existent static:

https://user-images.githubusercontent.com/24967815/129429789-9057a67e-590b-4b1a-b6d7-b72d67e53558.mp4

And here's a clip of it just. Coming back. Out of nowhere.

https://user-images.githubusercontent.com/24967815/129429811-89a859fb-d876-4195-8a7d-9cf293cbf0cf.mp4

(The place right besides evac and the place besides science should both be static, but they are not. Once I go up a bit on the latter place suddenly static is back everywhere!)

This has happened to me in the past, but I never got to recording it either activating or coming back, til now.
Don't have to say this, but this is very very very very bad. Not even maint is a good hiding place when this kind of stuff happens.

**Comment by TheSmallBlue** [comment] 2021-08-14 01:18
Judging by this, #60760, #47069, and #41747, I'd say that static code is completely fucked up

**Comment by dragomagol** [comment] 2021-08-14 02:08
Duplicate of #38857

**Closed by dragomagol** 2021-08-14 02:08 UTC
