### ISSUE TITLE
Tramstation elevator button under glass tile

### ISSUE THREAD

**Issue by SirOblivious** [tgstation/tgstation#73344] opened 2023-02-10 01:39 UTC
Reporting client version: 514.1589

## Round ID:
[199841](https://scrubby.melonmesa.com/round/199841)

## Reproduction: load tramstation. go to the elevator to the right of medical leading to engineering. button is under the glass. as a result you cant interact
![image](https://user-images.githubusercontent.com/12487691/217978472-09fecf4d-0b45-4b68-9efb-3c854a645186.png)

**Comment by timothymtorres** [comment] 2023-02-10 11:55
Duplicate of #73341

**Closed by timothymtorres** 2023-02-10 11:55 UTC
Labels: Mapping
