### ISSUE TITLE
Monkeys spawned with monkeymancer spell can hit you with guns from miles away

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85297] opened 2024-07-27 02:54 UTC
Reporting client version: 515.1642

## Round ID:
[232707](https://scrubby.melonmesa.com/round/232707)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)

## Reproduction:
A bunch of monkeymancer monkeys were spawned this shift and the good majority ended up hitting people with guns they were holding despite being nowhere near them

**Comment by SmArtKar** [comment] 2024-07-27 12:28
Duplicate of #85107

**Closed by SmArtKar** 2024-07-27 12:28 UTC
