### ISSUE TITLE
Internal radio implant preventing speaking on departmental radios

### ISSUE THREAD

**Issue by Coconutwarrior97** [tgstation/tgstation#40693] opened 2018-10-04 02:20 UTC
[Round ID]: 94887
Server: Sybil

Having a syndicate internal radio prevents users from using channels which aren't syndicate or common; even when wearing a headset with the correct radio keys.

**Comment by wesoda25** [comment] 2018-10-04 20:52
I've been encountering this forever on bagil.

**Comment by SpaceManiac** [comment] 2018-10-08 04:19
Duplicate of #34136

**Closed by SpaceManiac** 2018-10-08 04:19 UTC
