### ISSUE TITLE
Custom Pizza Slicing Duplicates bowls

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#73299] opened 2023-02-07 18:25 UTC
## Round ID:
[199701](https://scrubby.melonmesa.com/round/199701)-ish

## Testmerges:
73280, doubt its related

## Reproduction:
make a custom pizza with a bowl-based food (I used chilli con carne) then cut the pizza, you will get multiple bowls despite putting only 1 in.

**Comment by ArcaneMusic** [comment] 2023-02-18 04:12
Doing some digging into this, this appears to be rather tricky:
The pizza has the trash-based ingredients alright:
![image](https://user-images.githubusercontent.com/41715314/219829092-be9374ee-8888-4db4-a511-98b9547dd4f0.png)
However, components wise, we don't add any trash components or similar components that DIRECTLY create the trash. Working theory is that the ingredients, when used to generate the pizza slices, are interacting in such a way that they're immediately generating food trash based on the parent-ingredient food.
![image](https://user-images.githubusercontent.com/41715314/219830542-af1b12cb-600f-4a88-9310-090b5fd9c270.png)

**Comment by Sealed101** [comment] 2023-03-02 22:38
duplicate of #69285 - more processable foods spawning excess trash items

**Closed** 2023-03-02 22:39 UTC
Labels: Bug
