### ISSUE TITLE
New Consoles Lights

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#40140] opened 2018-09-06 12:32 UTC
![image](https://user-images.githubusercontent.com/32466328/45157484-ff171800-b1e9-11e8-8b24-f513b29be84f.png)

not a major bug, but looks creepy.

In other. That perfect update.

**Comment by Arkvold** [comment] 2018-09-06 15:55
This is a duplicate of #40048 and #40122, symptom of the new console lighting system implemented in #39973.

**Closed** 2018-09-07 04:47 UTC
