### ISSUE TITLE
Revenant abilities

### ISSUE THREAD

**Issue by Kendrickorium** [tgstation/tgstation#53593] opened 2020-09-10 00:31 UTC
Issue reported from  Round ID: [145999](https://scrubby.melonmesa.com/round/145999) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1532

abilities take like 5 minutes to charge up, this is pretty dumb. please fix, its not worth doing anything except succ as rev

**Comment by msgerbs** [comment] 2020-09-10 03:10
Duplicate of #53595

(I know yours was first the other one got a response first)

**Closed** 2020-09-11 10:44 UTC
Labels: Bug
