### ISSUE TITLE
secret recipes broken again

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#77754] opened 2023-08-19 11:29 UTC
Reporting client version: 514.1589

## Round ID:
[212893](https://scrubby.melonmesa.com/round/212893)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Edits a proc from dynamic.dm to use the actual cumulative formula of the Cauchy-Lorentz distribution."](https://www.github.com/tgstation/tgstation/pull/77728)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/31b23dbe-93ee-48cf-9c7a-de716e7c1c8c)
lmao

**Comment by Sealed101** [comment] 2023-08-19 12:18
Duplicate of #77139

**Comment by Sealed101** [comment] 2023-08-19 12:18
three weeks and nothing changed at all, incredible

**Closed by Sealed101** 2023-08-19 12:18 UTC
