### ISSUE TITLE
Wizard Projectile /obj/projectile/magic/wipe Bugged

### ISSUE THREAD

**Issue by Comxy** [tgstation/tgstation#73769] opened 2023-03-03 20:43 UTC
## Round ID:
[201151](https://scrubby.melonmesa.com/round/201151) but probably any recent rounds.

## Reproduction:
Get hit by a /obj/projectile/magic/wipe projectile as a human. 

A ghost takes over your body and you get send into a black screen without being able to see anything. The imaginary friend actions still appear to the top left but you cannot see anything. You also do not see turfs or entities when pressing right mouse button.

**Comment by timothymtorres** [comment] 2023-03-05 01:24
Duplicate of #67596

**Closed by timothymtorres** 2023-03-05 01:24 UTC
