### ISSUE TITLE
Revenant harvest stopping immediately and not granting essence

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#78925] opened 2023-10-11 08:22 UTC
Reporting client version: 514.1589

## Round ID: 
[216484](https://scrubby.melonmesa.com/round/216484)

## Reproduction:
1. be revenant
2. attempt to harvest (click) a dead/dying human or monkey
3. see
>You search for the soul of Holly Ahmed.
Their soul blazes with life!
Their soul is weak and faltering. It's time to harvest.
Holly Ahmed will yield an average amount of essence.
You begin siphoning essence from Holly Ahmed's soul.
Holly Ahmed suddenly rises slightly into the air, their skin turning an ashy gray.
Holly Ahmed's soul has been drawn out of your grasp. The link has been broken.
Holly Ahmed slumps onto the ground.

the line "soul has been drawn out of your grasp. The link has been broken." happens immediately after siphoning begins, stopping prematurely, revealing you for about 5 seconds, and granting exactly zero essence.

The mob is not functional because you cannot increase your max essence to unlock the abilities

Probably #78782 the refactor to basic mob

**Comment by san7890** [comment] 2023-10-11 20:29
The issue is was that in a refactor, revenants got `TRAIT_INCAPACITATED` and the `do_after() didn't ignore that. this will be fixed in the upcoming PR

> On another note, revenants appear to be failing to generate bodies on roll sometimes.

I think you mean the fact that midround generations are failing? this is because i was stupid and forgot that observers dont' have minds. i wish there was a better way than a `raw` key transfer. regardless this was also patched

**Closed** 2023-10-12 00:24 UTC
