### ISSUE TITLE
weird ass cult mmi mech bug thing.

### ISSUE THREAD

**Issue by HydroFloric** [tgstation/tgstation#34762] opened 2018-01-21 22:23 UTC
Issue reported from  Round ID: 82324 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)82324
[Round ID]: # 82324
[Round ID]: #82324 (not sure why there is 3 of these round ID things)

[Testmerges]: 

[Reproduction]:  So one day I was spawned as a clock cultist. I went to go and try killing the cap but that failed. anyways he took my brain and placed it into a mmi. Afterwards he build a riply mech and placed me in it but for some reason I didnt get the mech hud. I kept my cult one. When I tried to move it kept repeating that I was getting out of the mech. Then this is when it got weird. After the ark started and I got teleported back to the ark it only took my mmi but since that mmi was in the mech I could still control it but when I tried to move it would teleport me back to the station and then back to the ark over and over. at some point the mech enterted rebee and I was then in the mech on the wrong side of rebee. Now things get weirder as someone else climbed into the mech somehow. now when I tried to move I would teleport ontop of the mech. Then the round ended and everything was okay.

[For Admins]: Rustledjimm told me to report this so I have.

**Comment by YPOQ** [comment] 2018-01-21 22:25
Probably the same underlying issue as #34408

**Comment by AnturK** [comment] 2018-01-22 10:08
Actually yes.
Duplicate of #34408

**Closed by AnturK** 2018-01-22 10:08 UTC
Labels: Bug
