### ISSUE TITLE
Headslugs & Blob Spores = Get Fucked

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#32069] opened 2017-10-24 10:02 UTC
If, as a headslug, you bite a body when then gets infested by a blob spore, when you "explode" out of the body, you will be that blob zombie. You can hit things (including yourself), but you can't control your movement. If you get killed, you'll disappear in a puff of smoke, and so will the body you were supposed to be bursting out of.

**Comment by Repukan** [comment] 2017-10-24 10:09
Dupe

**Comment by ShizCalev** [comment] 2017-10-24 12:08
Duplicate of #31258

**Closed by ShizCalev** 2017-10-24 12:08 UTC
