### ISSUE TITLE
Suicides can roll syndie borg

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#54450] opened 2020-10-18 04:29 UTC
## Reproduction:

> I suicide on war ops some times and receive prompts asking if I want to be a syndi borg.

https://tgstation13.org/phpBB/viewtopic.php?f=33&t=27799&p=579458#p579428

The issue here is in regards to antag rolling, which is something we have a general policy against.

**Comment by msgerbs** [comment] 2020-10-18 05:01
Is it a bug? Suicide marks *that character* is ineligible for revive. I've never seen anything to indicate that it's intended for suicide to remove you from ever returning to the round in any way.

**Comment by SkeletalElite** [comment] 2020-10-18 05:35
As I said in that thread, I'm pretty sure this is not a bug. I cannot find any code that makes you ineligible for _any_ ghost role because of a suicide.

**Comment by zxaber** [comment] 2020-10-18 10:50
You can't take positronics if you suicide. The orange has said that the intention is for suiciding to remove the client from the round permanently, and the only reason it's not already the case is that no one has done the code yet.

**Comment by ATH1909** [comment] 2020-10-18 11:05
> You can't take positronics if you suicide. The orange has said that the intention is for suiciding to remove the client from the round permanently, and the only reason it's not already the case is that no one has done the code yet.

That's kind of dumb, IMO, since can't you just bash (and/or space) yourself into crit (and/or succumb) anyway?

**Comment by Pugie** [comment] 2020-10-18 11:10
Suiciding to make you inelligible for ghost roles is a rabbit hole... what if people start toolboxing each other or spacing themselves to die? Do people who lose fights get antag banned should they roll syndie borg? Sounds like a non-issue to me.

**Comment by msgerbs** [comment] 2020-10-18 15:37
Frankly I don't see what issue this is trying to solve and I think implementing it is pointless for the reasons given above. 

For reference, #41336 is the PR that added this functionality to posibrains for... reasons?

**Comment by RaveRadbury** [comment] 2020-10-18 15:43
> Frankly I don't see what issue this is trying to solve and I think implementing it is pointless for the reasons given above.
> 
> For reference, #41336 is the PR that added this functionality to posibrains for... reasons?

I provided a link to the thread that brought up the issue, which should provide context. Please engage the bug report if you're planning on handling and commenting on it.

**Comment by msgerbs** [comment] 2020-10-18 15:53
What? Which rule is it against the rules of to suicide and later take a ghost role?

**Comment by RaveRadbury** [comment] 2020-10-18 16:01
It's an antag rolling issue. You shouldn't be able to suicide because you know its warops and then roll antag from that.

**Comment by msgerbs** [comment] 2020-10-18 16:34
That's an admin issue, not a code issue.

**Comment by ATH1909** [comment] 2020-10-18 18:35
> It's an antag rolling issue. You shouldn't be able to suicide because you know its warops and then roll antag from that.

pretty cringe, imo. some people just hate playing the crew side of war ops, which is why they're willing to risk being unable to play in the round just to have a chance of switching to the op side instead. these people will still self-terminate after this proposed change, so the biggest impact it'll have will be to make reinforcement spam and syndiborg spam op gimmicks less viable, which is sad, IMO.

**Comment by msgerbs** [comment] 2020-10-18 18:38
I'm going to go ahead and close this as it's clear it's not a bug. My personal opinions on the matter aside, this is a feature request and should be on the forums or in a PR.

**Comment by RaveRadbury** [comment] 2020-10-18 20:07
I disagree with your conclusion here. It's a consistency issue and there's code precedent for it.

**Comment by RaveRadbury** [comment] 2020-10-18 20:09
> > It's an antag rolling issue. You shouldn't be able to suicide because you know its warops and then roll antag from that.
> 
> pretty cringe, imo. some people just hate playing the crew side of war ops, which is why they're willing to risk being unable to play in the round just to have a chance of switching to the op side instead. these people will still self-terminate after this proposed change, so the biggest impact it'll have will be to make reinforcement spam and syndiborg spam op gimmicks less viable, which is sad, IMO.

We don't allow self-conversion, you know this. If it's not allowed in revs or cult or any other team mode, it should stand that it shouldn't be allowed here.

**Comment by kriskog** [comment] 2020-10-18 21:47
msgerbs is right, this is not something that was implemented but isnt working. It's a feature request, take it to the forums like usual.

**Closed by kriskog** 2020-10-18 21:47 UTC
Labels: Consistency Issue, Not a bug

**Comment by Pugie** [comment] 2020-10-19 10:34
begun, the close wars have,

**Comment by RaveRadbury** [comment] 2020-11-03 20:18
@kriskog In light of the recent policy thread is this still a feature request?

![image](https://user-images.githubusercontent.com/3204033/98036308-6be4c780-1ddf-11eb-8665-41621b25a5cd.png)

**Comment by msgerbs** [comment] 2020-11-03 20:23
It is still a feature request because it's still not something that was implemented and isn't working. A policy change isn't a bug. Regardless, they didn't say that suicide should never get an op spawned role, just that you shouldn't be rolling for antag. If you just suicide and happen to get syndiborg, that's fine.
