### ISSUE TITLE
Clarke cannot deposit ores in any way and is pretty much just another support mech

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#75837] opened 2023-06-03 19:42 UTC
## Round ID: 
I unfortunately cannot retrieve the Round ID because for some reason the site used to retrieve it is currently down

## Testmerges:
Probably not a testmerge issue

## Reproduction:
After constructing a Clarke and acquiring minerals, there is no way to retrieve the ores from the ore storage module. Getting next to the ORM with the Clarke doesn't work, ejecting the ore storage module doesn't yield ores, nor does dragging the ore storage module in hand onto the spot like an ore bag. This is problematic, as the Clarke also does not support the Cargo Clamp module, and thus cannot pick up ore boxes, and thus cannot deposit ores in ANY way.

**Comment by Sealed101** [comment] 2023-06-03 19:51
Duplicate of #75568 (essentially)
you can drop the ores by pressing the Activate button on the UI. yeah it's dumb but it works. will try to look into renaming the button for it

**Closed by Sealed101** 2023-06-03 19:51 UTC

**Comment by Hotmud9** [comment] 2023-06-03 19:57
There's an activate button for it?

**Comment by Sealed101** [comment] 2023-06-03 20:06
sorry, the `Enabled` button. double stupid
![изображение](https://github.com/tgstation/tgstation/assets/75863639/dcbddf2a-2d50-4dc2-88b9-64c61492e7ba)
