### ISSUE TITLE
Boards don't drop from deconstructed machines.

### ISSUE THREAD

**Issue by FinnDority** [tgstation/tgstation#52811] opened 2020-08-09 04:04 UTC
## Reproduction: Literally just screwdriver + crowbar a machine, this worked on a stasis bed and a chem master so far

Basically, the issue is that when deconstructing a machine, (eg: screwdriver then crowbar) you'll get all the parts out of it but not the machine board itself. This is really annoying, and for most jobs it's kinda a shutdown on whatever machine you just deconstructed until you can print its board again.

**Comment by Jared-Fogle** [comment] 2020-08-09 04:24
Duplicate of #52795.

**Comment by mixzombie** [comment] 2020-08-09 20:55
Can Confirm as of 4 Am today, Boards in Freezers in Toxins delete themselves.

**Closed** 2020-08-10 15:21 UTC
