### ISSUE TITLE
AI's aren't able to see distro pipes on icebox via cameras due to the see through glass tiles.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#62786] opened 2021-11-13 09:20 UTC
## Testmerges:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58a
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550

## Reproduction:
<img width="599" alt="cams" src="https://user-images.githubusercontent.com/56049844/141613227-acdc555d-1373-4bf0-9813-500399717345.PNG">

1. Be an AI and look at Atmos through your cameras.
The see through glass tiles on the floor appear to be creating a camera deadzone for AIs.

**Comment by timothymtorres** [comment] 2021-12-16 12:48
Duplicate of #62851

**Closed by timothymtorres** 2021-12-16 12:48 UTC
Labels: Bug
