### ISSUE TITLE
Lighting bug on new room in space with tiles on top of pre-existing ones

### ISSUE THREAD

**Issue by Jcarr0ndo** [tgstation/tgstation#62993] opened 2021-11-21 14:57 UTC
## Round ID:
[173326](https://scrubby.melonmesa.com/round/173326)

## Reproduction:
Go to space, find location for new room
Use existing lattices on space to make floors
Make a new room with station blueprints
Lighting should now be bugged

Example is BSA room I built during the round, location is west of shooting range, and north of recreation on delta station

![Screenshot_1](https://user-images.githubusercontent.com/8581687/142766916-ea02424b-462f-40bc-8883-92e36312ad11.png)

**Comment by timothymtorres** [comment] 2021-11-22 12:23
This looks like a dupe of #63005.  I also suspect both of these are recent test merge bugs because I don't see any recent bug reports having this problem.

**Comment by TheBonded** [comment] 2021-11-22 22:13
> This looks like a dupe of #63005. I also suspect both of these are test merge bugs because I don't see any recent bug reports having this problem.

I don't think this is a test merge bug, it seems like lighting as a whole has been bugged similarly to this for a while. a lot of times light just won't update, and you end up with tiles like this.

**Comment by Jcarr0ndo** [comment] 2021-11-22 22:17
> This looks like a dupe of #63005. I also suspect both of these are test merge bugs because I don't see any recent bug reports having this problem.

I must say, as TheBonded commented, that this is an issue I've noticed previously happen, just didn't create a bug report those times. Also sorry about not checking for already existing reports.

**Comment by LemonInTheDark** [comment] 2021-11-22 23:44
@Kylerace @TiviPlus one of you did this and I'm not sure who
@timothymtorres check the round id, there's no relevant testmerges

**Comment by timothymtorres** [comment] 2021-11-23 10:24
Both of the issues appeared within a short timespan of each other with different rounds and people so I assumed something got merged recently that broke lighting.  It appears that wasn't the case.

**Closed** 2022-01-31 08:35 UTC
Labels: Bug
