### ISSUE TITLE
triangulation doesnt give you the last zone 

### ISSUE THREAD

**Issue by theta060** [tgstation/tgstation#67603] opened 2022-06-07 17:54 UTC
Reporting client version: 514.1583

## Round ID:
[184505](https://scrubby.melonmesa.com/round/184505)

## Testmerges:
- [Reduces the point reduction on traitor objectives significantly](https://www.github.com/tgstation/tgstation/pull/67385)
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

**Comment by YakumoChen** [comment] 2022-06-10 07:56
it should be written in your objective list?
Currently I only have to triangulate one spot, then I get the bomb location and the bomb spawn.

**Comment by timothymtorres** [comment] 2022-06-19 11:59
Duplicate of #67838

**Closed by timothymtorres** 2022-06-19 11:59 UTC
