### ISSUE TITLE
Atmos Resin Foam is Invisible (Wallening)

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85768] opened 2024-08-12 00:54 UTC
Reporting client version: 515.1641

## Issue Summary

![resin](https://github.com/user-attachments/assets/c9f5e007-41cf-4a03-9112-ca6bb2a78149)

Resin foam is invisible and you can't click on it unless you open your alt menu.

## Round ID:
[234550](https://scrubby.melonmesa.com/round/234550)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Shoot out some resin foam in an area, suddenly get confused as to why you can't move.

**Comment by loganuk** [comment] 2024-08-12 01:02
Duplicate of > https://github.com/tgstation/tgstation/issues/85553

**Comment by SmArtKar** [comment] 2024-08-12 07:01
Closing as duplicate

**Closed by SmArtKar** 2024-08-12 07:01 UTC
