### ISSUE TITLE
Crashing while using the xenobio console (also while beign an AI) on multiple rounds

### ISSUE THREAD

**Issue by Maciekkub** [tgstation/tgstation#34233] opened 2018-01-09 19:43 UTC
Issue reported from Round ID: 81646 (/tg/Station Terry [EU] [100% LAG FREE])

[Round ID]: 81646 (Since it ocurred on multiple rounds it doesn't really matter i reckon)

[Testmerges]: #34061: '[dnm]Fixes compiler errors in the preload_rsc external resource thingy' by MrStonedOne at commit 5e983e

Click on the administrator's name to reply.
[Reproduction]: All in all, whenever i use the console, or be an AI i crash at random. The game freezes and stops working and i gotta restart it and that's basically it.
[For Admins]: I don't believe there was an interferrence of admins to any of the rounds that big it would crash me 4noraisin

**Comment by ShizCalev** [comment] 2018-01-09 20:05
Duplicate of #32907 & #33000

**Closed by ShizCalev** 2018-01-09 20:05 UTC
Labels: Bug

**Comment by ShizCalev** [comment] 2018-01-19 06:21
#33377
