### ISSUE TITLE
Hacked AI Upload Module doesn't work the way it is described.

### ISSUE THREAD

**Issue by CptnCapitalism** [tgstation/tgstation#50434] opened 2020-04-06 15:21 UTC
Issue reported from  Round ID: [134058](https://scrubby.melonmesa.com/round/134058) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

The wiki says that the Purge module doesn't remove traitor laws, but i just learned the hard way that it does. Ill leave it up to you if you want to edit the wiki, or the Hacked AI Upload Module.

**Comment by Tlaltecuhtli** [comment] 2020-04-06 15:49
wiki is probably referring to malf ai law (traitor ai) not hacked laws (traitor item)

**Comment by CptnCapitalism** [comment] 2020-04-06 16:29
From the wiki:

   0. Zeroth Law (Traitor/Malfunction Law)
  @#$# An Ionic Law (Hacked Module)
  @#!# An Ionic Law uploaded afterwards
  1. Core Law
  2. Core Law
  3. Freeform Core Law
  4. Freeform Core Law uploaded afterwards
  5. Sector Law 4 (Safeguard)
  6. Sector Law 6 (Prototype Engine Offline)
  7. Sector Law 15 (Freeform)

Purge: Removes all laws from the AI, except traitor and malf Zeroth Laws.

Hacked: Uploads a law of your choice with ionic priority.



From this it seems like that hacked and ionic laws should behave the same way.

**Comment by Akrilla** [comment] 2020-04-06 21:03
Likely a wiki issue more than a bug

**Comment by Pugie** [comment] 2020-04-07 00:50
How is it an anything issue? It seems pretty damn specific on the wiki to me

**Comment by TheVekter** [comment] 2020-04-08 09:47
That reads just fine to me. I think the issue is that it says "except traitor and malf Zeroth laws", which could be confused as hacked laws = traitor laws.

Purge can remove every law that isn't the malf law (the one that tells you to pursue your objectives).

**Comment by necromanceranne** [comment] 2020-04-08 15:31
I feel it's safe to close this one. If the wiki is confusing it'll simply require updating.

**Closed** 2020-04-08 15:31 UTC
