### ISSUE TITLE
Cannot Exit Tramstation to deep space on second z-level.

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#57710] opened 2021-03-14 09:12 UTC
## Round ID:
N/A, Local Branch

## Testmerges:
N/A, Local Branch

## Reproduction:
Be space exploring as ghostrole, accidentally find the station on z-level 3. Go to leave. Cry because the transitions are fucked with multi-z. Repeat.

**Comment by timothymtorres** [comment] 2021-11-28 12:41
Duplicate of #58436

**Closed by timothymtorres** 2021-11-28 12:41 UTC
Labels: Bug, Against God and Nature
