### ISSUE TITLE
Addictions aren't triggering

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#55764] opened 2020-12-27 07:30 UTC
## Round ID: 
[152988](https://scrubby.melonmesa.com/round/152988)

## Reproduction: 
I took two 10u happiness pills. I didn't get a happiness addiction. This worked like, last month. I added 19u in the thunderdome in the next round, still no addiction.

**Comment by necromanceranne** [comment] 2020-12-27 12:57
Good time for bathsalts.

**Comment by necromanceranne** [comment] 2020-12-27 12:58
@nightred Might be related to your stomach changes

**Comment by dragomagol** [comment] 2020-12-27 17:41
Duplicate of #55245

**Closed by dragomagol** 2020-12-27 17:41 UTC
Labels: Bug

**Comment by RaveRadbury** [comment] 2021-01-20 07:32
Caused by #54797
