### ISSUE TITLE
Shotguns cause lag

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28874] opened 2017-06-27 16:55 UTC
With the new Goonchat, whenever a bunch of lines of text are output at once, it causes quite a bit of client-side lag. A side effect of this is that shotguns, which output a line of text each time a pellet hits something, cause around a half-second of lag.

**Comment by Cyberboss** [comment] 2017-06-28 01:47
Dupe of #28875

**Closed by Cyberboss** 2017-06-28 01:47 UTC
