### ISSUE TITLE
Hoverboards do not work in 0G.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49849] opened 2020-03-09 19:49 UTC
Why on earth does a HOVERBOARD rely on gravity?

**Comment by Mickyan** [comment] 2020-03-09 20:58
because it's an hoverboard not a flyboard

**Comment by Bokkiewokkie** [comment] 2020-03-09 23:30
If anything, without gravity it would just float up up and away.

**Comment by HomocidlePancakes** [comment] 2020-03-10 05:04
>If anything, without gravity it would just float up up and away.

1) Place the board horizontally 
2) Attain infinite velocity
3) ???
4) Crash in to a wall

**Comment by cacogen** [comment] 2020-03-10 05:27
Bokkiewokkie is right, the proper fix for this should be to propel you into the screen, causing you to die instantly

**Comment by PKPenguin321** [comment] 2020-03-10 06:28
Funny idea, but not a bug

**Closed by PKPenguin321** 2020-03-10 06:28 UTC

**Comment by HomocidlePancakes** [comment] 2020-03-10 12:55
@PKPenguin321 Still an oversight.

**Comment by PKPenguin321** [comment] 2020-03-10 16:46
It's got anti-gravity detection and auto-shutoff systems so as to not yeet you into the roof when gravity fails.

**Comment by cacogen** [comment] 2020-03-11 05:51
Just make a PR where it works in zero gravity, @HomocidlePancakes. I'm a retard who knows little about physics but presumably it knows how much force is weighing down on it and adjusts the thrust to match so it can counterbalance it and maintain a consistent height, so in zero G it just wouldn't push down anymore due to the lack of weight bearing down on it (but would still be able to thrust forwards, like jetpacks).
