### ISSUE TITLE
Birdboat spam. Birdboat refuses to eat the detective's flask.x101

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#46863] opened 2019-10-03 11:18 UTC
## Reproduction:
Birdboat refuses to eat the gold cup.x22
Birdboat refuses to eat the gold cup.x41
Birdboat refuses to eat the gold cup.x21
Birdboat refuses to eat the gold cup.x12

**Comment by nemvar** [comment] 2019-10-03 12:45
Cursed birb

**Comment by nemvar** [comment] 2019-10-03 14:02
Dupe of https://github.com/tgstation/tgstation/issues/45030

**Closed by nemvar** 2019-10-03 14:02 UTC
Labels: Bug
