### ISSUE TITLE
Gas mixers and filters changing filter or mixing direction on rotation

### ISSUE THREAD

**Issue by Kartograaf** [tgstation/tgstation#37988] opened 2018-05-22 09:04 UTC
Issue reported from  Round ID: 88313 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Creating a gas filter and rotating it will change it to filter to the eastern direction. Similarly a mixer that mixes gas coming from the south and west will change to mix gas coming from south and east
Reproduction: Create a gas filter that filters gas to the west
Rotate the filter 
Instead of rotating normally, the piece will change to filter gas to the eastern direction

**Comment by ShizCalev** [comment] 2018-05-22 10:45
duplicate of #32184

**Closed by ShizCalev** 2018-05-22 10:45 UTC
