### ISSUE TITLE
Bartender's Bots are broken

### ISSUE THREAD

**Issue by Overuseddart** [tgstation/tgstation#66564] opened 2022-04-28 00:07 UTC
Reporting client version: 514.1581

## Round ID:
[182260](https://scrubby.melonmesa.com/round/182260)

## Testmerges:
- [Remove data/ from /datum/asset/json url mapping](https://www.github.com/tgstation/tgstation/pull/66549)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Keep mutating filenames when the cdn is disabled midround.](https://www.github.com/tgstation/tgstation/pull/66550)

## Reproduction:
The bartenders bots that you serve drinks to are broken. They will constantly ask for drinks at such a rapid pace that it becomes unable to serve them and it will spam the message channel.

**Comment by Serxule** [comment] 2022-04-28 00:52
https://github.com/tgstation/tgstation/issues/66554

**Comment by SuperNovaa41** [comment] 2022-04-28 05:06
Duplicate of #https://github.com/tgstation/tgstation/issues/66554 TBH TBH

**Closed by SuperNovaa41** 2022-04-28 05:06 UTC
