### ISSUE TITLE
deconing any machinery doesnt give circuit back

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#52935] opened 2020-08-14 10:08 UTC
144234

crowbar machine

parts fall out

no circuit

**Comment by TemporalOroboros** [comment] 2020-08-14 10:14
Duplicate of #52860 and should be closed by #52871

**Comment by nightred** [comment] 2020-08-14 17:17
Confirmed issue was resolved in PR #52871
Closing

**Closed by nightred** 2020-08-14 17:17 UTC
