### ISSUE TITLE
Genturf spawning when syndicate lavaland base explodes

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#59833] opened 2021-06-26 15:00 UTC
## Round ID:
[164830](https://scrubby.melonmesa.com/round/164830)

## Testmerges:
#59750 

## Reproduction:
Explode the lavaland base.
![image](https://user-images.githubusercontent.com/68032262/123516950-9cdb7a80-d696-11eb-87c9-a6ac1992440d.png)

**Comment by dragomagol** [comment] 2021-06-27 01:16
Duplicate of #57449

**Closed by dragomagol** 2021-06-27 01:16 UTC
