### ISSUE TITLE
Syndie EVA suit toggle doesn't change sprite anymore

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#58283] opened 2021-04-10 02:41 UTC
Reporting client version: 514.1549

## Round ID:
[159965](https://scrubby.melonmesa.com/round/159965)

## Reproduction:

https://user-images.githubusercontent.com/35135081/114255937-8103ea80-996b-11eb-8486-6c1b1bbc3a38.mp4

**Comment by ArcaneDefence** [comment] 2021-04-10 03:31
Duplicate of https://github.com/tgstation/tgstation/issues/57307

**Closed by ArcaneDefence** 2021-04-10 03:31 UTC
