### ISSUE TITLE
Posters placed can print a square above/below where they were supposed to be placed

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#20579] opened 2016-09-18 21:33 UTC
An issue that may be exclusive to Meta/Meta Maintenance, but an issue nontheless. Several attempts placing a poster resulted in them being placed above or below the wall, depending on where I was standing in relation to the wall.

**Comment by Niknakflak** [comment] 2016-09-19 17:22
Sort of kind of a bug.  Its because they are mapped with a pixel_x or pixel_y changed which doesnt reset and carries over if the posters are snipped from the wall and placed elsewhere

**Comment by Mervill** [comment] 2017-01-05 06:26
Duplicate of #13430

**Closed** 2017-01-07 06:40 UTC
Labels: Bug
