### ISSUE TITLE
A huge amount of skewium messes up ss13.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38088] opened 2018-05-26 04:41 UTC
I got injected with a HUGE amount of skewium. As much as you can fit into one blue space syringe. My computer started to lock up, 6 task managers started to open. Yet, the problem slowly fixed itself. When Dream-Seeker came back. My screen was as black as the "advanced darkness" event. Dreamseeker recovered after deleting my screen!

I've seen this issue appear, but with different sources. Like, let say skewium in that safe chem vent event. YET IT HAPPENED FROM A BLUESPACE SYRINGE! I think skewium is the problem itself. It's just not compatible with the latest version of byond.

**Comment by Iamgoofball** [comment] 2018-05-26 05:09
https://file.house/IcY3.webm

Here's evidence it wasnt skewium.

Can someone close this?

**Comment by PKPenguin321** [comment] 2018-05-26 05:15
>works on my machine!

**Comment by Iamgoofball** [comment] 2018-05-26 05:56
@Shadowflame909 What are your specs, exactly? Include BYOND version and your IE version

**Comment by 81Denton** [comment] 2018-05-26 06:03
#37923

**Comment by Shadowflame909** [comment] 2018-05-26 06:03
Maybe it's serverpop goof?

**Comment by Iamgoofball** [comment] 2018-05-26 06:13
@Shadowflame909 What are your specs, exactly? Include BYOND version and your IE version

**Comment by Shadowflame909** [comment] 2018-05-26 08:56
![specs](https://user-images.githubusercontent.com/29222521/40574496-e05bdd8c-6087-11e8-95ad-e9285dd75c78.png)

The latest Beta version of byond. 512.1425
My internet explorer? Whatever the version your computer starts with is(who uses internet explorer anymore??)

**Comment by Iamgoofball** [comment] 2018-05-26 09:36
we need to know the rest of your specs, exact graphics card, exact memory brand, etc.

**Comment by praisenarsie** [comment] 2018-05-26 13:06
i've tested on latest commit and i got no problems, running .1425, i can provide specs if needed

**Comment by Mickyan** [comment] 2018-05-26 16:33
Should get an admin to test this on the live server instead of local, sometimes it's not the same

**Comment by wesoda25** [comment] 2018-05-26 17:49
I dunno I've had CERTAIN PEOPLE crash me with spewium on multiple occasions. Definitely just a computer issue.

**Comment by SpaceManiac** [comment] 2018-05-27 01:11
Evidently a real bug but duplicate of #37923

**Closed by SpaceManiac** 2018-05-27 01:11 UTC
Labels: Bug
