### ISSUE TITLE
Ghosts can rotate chairs

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#85788] opened 2024-08-13 20:58 UTC
Reporting client version: 515.1642

## Round ID:
[234745](https://scrubby.melonmesa.com/round/234745)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Alt+click a chair as a ghost :)

**Comment by Sadboysuss** [comment] 2024-08-13 21:49
duplicate of https://github.com/tgstation/tgstation/issues/84971

**Closed** 2024-08-14 02:42 UTC
