### ISSUE TITLE
All crafting is broken (both slapcrafting and the old version)

### ISSUE THREAD

**Issue by Annihilit** [tgstation/tgstation#79186] opened 2023-10-22 18:25 UTC

**Comment by Loafin34** [comment] 2023-10-22 18:41
can confirm, slapcrafting doesn't work either.

**Comment by HalfPunch** [comment] 2023-10-22 20:31
Welcome to "No spear" zone
![image](https://github.com/tgstation/tgstation/assets/91390177/107adf99-1e41-4987-b432-a8c3edd54ef1)

**Comment by Hotmud9** [comment] 2023-10-22 22:03
not ALL slapcrafting is broken. Simplebot slapcrafting is still functional, and things like glass shivs can still be crafted with it. Things like HUDSunglasses can't, though.

**Comment by SyncIt21** [comment] 2023-10-23 04:59
> Welcome to "No spear" zone
 ![image](https://user-images.githubusercontent.com/91390177/277190919-107adf99-1e41-4987-b432-a8c3edd54ef1.png)

Unable to reproduce on local
![Screenshot (331)](https://github.com/tgstation/tgstation/assets/110812394/43992d33-8f84-45e9-b534-9588a9ac3863)

This was fixed by #79141 and chances are servers didn't update at the time this issue was reported. Try again now it should work

**Comment by Ghommie** [comment] 2023-10-23 10:46
I can confirm on midday Terry.

**Closed by Ghommie** 2023-10-23 10:46 UTC
