### ISSUE TITLE
[Fulpstation] The "state laws" voice of god command seems to only force you to state your core laws

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55010] opened 2020-11-17 10:56 UTC
<img width="1087" alt="voiceofgodbug" src="https://user-images.githubusercontent.com/42606352/99381801-2f11d980-2891-11eb-802b-478c709afd9f.PNG">

**Comment by LemonInTheDark** [comment] 2020-11-17 21:29
Does this reproduce on our codebase?

**Comment by dragomagol** [comment] 2020-11-24 06:16
I was able to reproduce it on our codebase (it states ion laws as well, just not purple laws)

**Comment by Sealed101** [comment] 2023-06-18 21:08
can't reproduce, probably fixed in 
- #57578

**Closed by Sealed101** 2023-06-18 21:08 UTC
Labels: Bug
