### ISSUE TITLE
Visual Issue Occuring when Xenobio Console powers down mid-use

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#78740] opened 2023-10-03 04:41 UTC
Round ID: R215922 on Sybil

Reproduction:

As a xenobiologist, was using the xenobio console at the start of the shift when power went down- depowering the console and turning it off mid-use. Afterwards when I checked maintenance for cut wires, I noticed the visuals were broken and that everything was covered in static. Reconnecting fixed the issue. Later when xenobio depowered again the visual glitch happened again where most of maint was essentially unviewable. Was requested to submit this as an issue but at least there's a workaround.
![static](https://github.com/tgstation/tgstation/assets/33949475/97db2f8d-97a5-4a4c-bca6-e645a418a850)

**Comment by Sealed101** [comment] 2023-10-03 05:37
Duplicate of #68279

**Closed by Sealed101** 2023-10-03 05:37 UTC
