### ISSUE TITLE
Active industrial slime extracts are destroyed by chemical grinder using conveyor belt setup

### ISSUE THREAD

**Issue by Killerunchie** [tgstation/tgstation#87719] opened 2024-11-06 20:09 UTC
### Client Version:

515.1643

### Issue Summary:

Industrial slime extracts are destroyed by chem grinder when they have been injected with plasma and are actively producing items. Looking back at TG discord logs, this has been an issue for at least a year.

### Round ID:

[241433](https://scrubby.melonmesa.com/round/241433)

### Test Merge Information:

1. Inject industrial (dark purple) extract with plasma
2. Use conveyor belt to move active industrial extract into grinder

### Reproduction Steps:

1. Inject plasma into industrial (dark purple) extract
2. Use conveyor belt to slide extract to chem grinder

**Comment by SyncIt21** [comment] 2024-11-07 02:55
Not a bug as it is the new expected behaviour.

#84274

**Comment by SyncIt21** [comment] 2024-11-07 08:35
> that's a pretty crummy change if you ask me, i think that should have been handled separately from the extract's produce. no reason to grind the industrial crossbreed itself, so i think it's fair to reintroduce that behavior, albeit in a 'legitimate' way

It was a bug that was taken advantage off. The chemical grinder would not grind stuff that did not have reagents but had grind_reagents  list defined so it was unable to grind a lot of stuff and slime extracts was one of them.

It can be fixed by doing a typecheck just for slime extracts which is code smell so I'll let someone else handle that

**Comment by Killerunchie** [comment] 2024-11-07 11:19
While grinding regular slime extracts makes sense to extract reagents from a one-use reaction (i.e. purple+blood=regenerative jelly), it does not make sense for crossbreeds. Crossbreeds either need to be activated in hand after being injected with a reagent, or possess a passive effect. In the case of INDUSTRIAL crossbreeds, they act as fixed reaction chambers that consume plasma to produce items depending on the slime color. 

In my opinion, industrial extracts should not be considered reagent containers; rather, they are effectively fixed reusable reaction chambers in item form. The wiki even states: "The extract is not used up in this reaction, so a clever player can make factories with them."

**Closed** 2024-11-10 09:28 UTC
Labels: Bug
