### ISSUE TITLE
This specific cryo cell isn't working on wawa

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83890] opened 2024-06-11 22:01 UTC
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/27e61acc-0e3b-45b0-ad7a-43dbde95edb5)

## Round ID:
[230385](https://scrubby.melonmesa.com/round/230385)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Significantly increases stamina recovery on most effects that provide it](https://www.github.com/tgstation/tgstation/pull/83556)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [Afterattack is dead, long live Afterattack](https://www.github.com/tgstation/tgstation/pull/83818)

**Comment by MrMelbert** [comment] 2024-06-11 22:07
Dupe of #80983 I believe

**Closed** 2024-06-11 22:07 UTC

**Comment by Sadboysuss** [comment] 2024-06-12 00:26
> Dupe of #80983 I believe

The cell on the left works as intended, but the cell on the right doesn't work and can't be interacted with
