### ISSUE TITLE
You can hear the sound of ash storms when in a bluespace survival pod in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#42179] opened 2019-01-01 18:06 UTC
Round ID: 99592.

1) Deploy bluespace surival pod in space.
2) Be a ghost (maybe)
3) You can hear when lavaland is undergoing an ashstorm.

**Comment by kriskog** [comment] 2019-06-27 22:50
Some other areas do this too, I believe in space ruins. I dont recall specifics currently.

**Comment by timothymtorres** [comment] 2022-11-08 00:55
Duplicate of #58475

**Closed by timothymtorres** 2022-11-08 00:55 UTC
Labels: Bug, Tested/Reproduced
