### ISSUE TITLE
Moving HUD elements out of view scales view size

### ISSUE THREAD

**Issue by sabre7** [tgstation/tgstation#46046] opened 2019-08-20 20:28 UTC
## Reproduction: Take a HUD element. Move it outside of your regular 15x15 view by var editing the screen_loc var. In my case this happened moving them to the east. Easiest way to reproduce, or you could set up a new element in onclick/hud/human.dm and the result is the same.

https://imgur.com/a/rZ0TOTR

I was intentionally trying to fool around with having some HUD elements set up outside of the normal 15x15 view, but when I'd spawn in, my view would be extended outside of 15x15. Typically to 17x15, sometimes 18x15 (after messing around with the binoculars).

**Comment by nemvar** [comment] 2019-08-20 20:58
Is this a bug? This might be an intentional feature of the stretch-to-fit setting.

**Comment by nemvar** [comment] 2019-08-20 21:25
Since this might actually be a feature and it can't really be reproduced without VV, I'm just gonna close this now.

If you are messing with stuff that shouldn't be messed with, except unexcepted results.

**Closed by nemvar** 2019-08-20 21:25 UTC
Labels: Not a bug

**Comment by sabre7** [comment] 2019-08-20 21:35
This happens regardless of the icon scaling options. Other forks don't do this, I tried it on them too. Something was added specifically to /tg/ to make this happen, the view size shouldn't be changing under these circumstances. I guess you could say I'm pulling wires and calling 'bug' when something breaks. The client view remains at 15x15 also, which is what really perplexes me. Change_view doesn't help either.

**Comment by sabre7** [comment] 2019-08-20 23:16
Ended up figuring this out by deleting stuff.

Fullscreen objects in the client, specifically the floor plane master, are improperly moved to adapt to widescreen. When the HUD objects are moved out of the view bounds, these fullscreen objects are moved too, which extends your view.
