### ISSUE TITLE
Floorbots can be abused for infinite materials and shuttle-worthy fires

### ISSUE THREAD

**Issue by ABoxFox** [tgstation/tgstation#49153] opened 2020-02-02 14:49 UTC
So, found this out yesterday, floorbots can be used to create an infinite floor tile of any type, provided its a floor tile that can be pried up, effectively resulting in an infinite amount of that floor tile, thus an infinite amount of most resources which, from what I've tested, includes plasma tiles, normal floor tiles, diamond, titanium, uranium, silver and gold tiles, which can easily make a miner's job redundant. Additionally, I set alight an infinite plasma tile, and the resulting 2 million kPa was a bit broken, which resulted in a shuttle call, and the plasma tile still lived. From what I've seen, there is no way to remove one of these tiles nor break it through means such as an RCD, though I did see a mulebot break one with a cargo pod, though that might've been a coincidence.
To do this glitch, you first get a floor bot, and let's say you wanted to make a normal floor tile, you'd pry up a tile or place the bot in maint, then when it begins to place it's tile, place the same type of tile below it, and an infinite metal generator will be made, whilst with other materials such as plasma and uranium, you'd get at least 2 floor tiles of the material, place one in the floorbot, set it to replace existing floor tiles with custom tiles, then when it goes to replace a tile on the floor, replace the tile with the same material as the floorbot and when the floorbot places the tile it can be pried (or burned) for chaos.

**Comment by PKPenguin321** [comment] 2020-02-02 18:59
Sounds like if you place a tile down and then the floorbot places the tile down it erreneously sets the baseturf to the tile type or something. Basically floorbots need to remember the type of tile that was there when they start replacing, and fail if it has changed when they finish replacing.

**Comment by ShizCalev** [comment] 2020-08-07 03:53
Duplicate of #37421

**Closed by ShizCalev** 2020-08-07 03:53 UTC
Labels: Bug, In Game Exploit
