### ISSUE TITLE
Glorious death and borging - this ruined my greentext :(

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28338] opened 2017-06-11 03:47 UTC
Getting borg means "die a glorious death" is failed. This is inconsistent with traitor targets being borged and counting as dead. No, I didn't ask to be borged, it's just an aftereffect of leaving your severed head out after suicide bombing your target

**Comment by Expletive** [comment] 2017-06-11 04:21
Feature

**Comment by dannno** [comment] 2017-06-11 04:23
ain't nothing glorious about becoming a robot slave.

**Comment by Iamgoofball** [comment] 2017-06-11 04:36
you can always suicide/ghost

**Comment by Durkel** [comment] 2017-06-11 17:41
I pointed this flaw out nearly a year ago after blowing myself up with a bomb that killed multiple people. My brain somehow survived the explosion and I ended up failing despite going out in the most glory filled way possible.

Don't expect anything else to happen besides people to meme at you and shitpost though.

**Comment by BeeSting12** [comment] 2017-06-12 01:07
Basically what happened to Durkel happened to me. At very least, it is a consistency issue seeing as borging your target counts them as dead.

**Comment by bgobandit** [comment] 2017-06-13 18:49
Not a bug, borging is the opposite of glorious

**Comment by BeeSting12** [comment] 2017-06-20 06:51
It is still a consistency issue with the way borging works for kill objectives.

**Comment by timothymtorres** [comment] 2021-12-10 10:02
Relevant code:

https://github.com/tgstation/tgstation/blob/b5f1d2afb622cd6c462ecccd05b85ce9ef9504c7/code/game/gamemodes/objective.dm#L532-L543

**Comment by timothymtorres** [comment] 2021-12-24 13:58
This issue is 6 years old (technically its a dupe of #16590) and looks like it was fixed a while back although I can't pinpoint which PR fixed it since the code has changed spots in various files.  There appears to be no other similar issues that are open.

I'm closing this for now since I would think if it still existed there would be more recent bug reports about it.

**Closed by timothymtorres** 2021-12-24 13:58 UTC
Labels: Good First Issue, Consistency Issue
