### ISSUE TITLE
Everyone is naked, disabled limbs, Unknown, not moving and can't take control of their ghosts.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#76226] opened 2023-06-21 20:20 UTC
## Testmerges:
#75819

## Reproduction:
Start the round. Title happens.

**Comment by Pickle-Coding** [comment] 2023-06-21 23:02
Also for some reason the naked bodies use old spaceman sprite.

**Comment by MrMelbert** [comment] 2023-06-22 02:13
Caused by #76179 on servers with roundstart away mission loading

**Comment by newfren** [comment] 2023-06-22 03:13
LMAO

**Comment by TheVekter** [comment] 2023-06-22 03:37
Fixed by #76241. I hope.

**Closed by TheVekter** 2023-06-22 03:37 UTC
Labels: FUCK
