### ISSUE TITLE
Captain can roll "family head" antagonist (and so can other antags - traitors, wizards, changelings)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#62384] opened 2021-10-27 04:41 UTC
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/139001105-8891ee33-144f-4290-a73d-1dbbf261f66d.png)

**Comment by Seris02** [comment] 2021-11-11 03:59
the issue is this proc (probably) which is run after setup 
https://github.com/tgstation/tgstation/blob/b79dd74fd0aef748a8e54c45402cebb3cd98e1c6/code/modules/antagonists/gang/handler.dm#L154
because it checks for anything that isn't a human within the roles it already selected and if it isn't one, then it rolls for other things using the same candidate list from roundstart (which isn't trimmed via restricted_roles) and doesn't check for restricted roles or other antag datums
so uh
that PR above won't fix this issue unless the implement this

**Comment by JohnFulpWillard** [comment] 2021-12-21 16:03
Seems to have been fixed with https://github.com/tgstation/tgstation/pull/63115

**Closed by JohnFulpWillard** 2021-12-21 16:03 UTC
Labels: Consistency Issue
