### ISSUE TITLE
Bitrunning with Claustrophobia kills you

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#79900] opened 2023-11-23 12:26 UTC
Reporting client version: 514.1589

## Round ID:
[219336](https://scrubby.melonmesa.com/round/219336)

## Reproduction:
- Give yourself claustrophobia quirk
- Enter a bitrunning simulation
- ( I personally did the fishing one for ~20 minutes)
- Exit the pod
You will now suffocate to death.

**Comment by DATA-xPUNGED** [comment] 2023-11-23 18:23
Ohh so that was what that was, it basically "holds" the no oxygen thing until you leave bitrunning, where it will then be unstoppable

**Comment by timothymtorres** [comment] 2023-11-24 08:49
Duplicate of #79226

**Closed** 2023-11-24 08:49 UTC
