### ISSUE TITLE
Internal Syndicate Radio Implant breaks the use of other extra channels via e.g. captains headset.

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#36522] opened 2018-03-19 06:04 UTC
[Round ID]: 85199

[Reproduction]: Get implant, equip captains headset enabled for use on department channels, try to speak on department channel.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-03-19 13:18
@coiax

**Comment by coiax** [comment] 2018-03-19 13:24
Turn the implant off.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-03-19 15:32
Is there anywhere that informs the player they can do that?

**Comment by YPOQ** [comment] 2018-03-21 04:36
#34136

**Comment by coiax** [comment] 2018-03-22 16:08
I did declare that the implant overrides headsets in my PR.

The implant does come in a box, probably could ship a user manual with it.

**Comment by iskyp** [comment] 2018-03-22 20:30
it informs the player that they need to deactivate it to use normal headsets in the uplink
`desc = "An implant injected into the body, allowing the use of an internal syndicate radio. Used just like a regular headset, but can be disabled to use external headsets normally and to avoid detection."`

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-03-29 15:23
Should be seen on the button tbh.

**Comment by ma44** [comment] 2018-04-08 20:38
Technically you can't talk on other channels with the regular 2 tc syndicate key installed, not sure if it's actually a feature or not, but that would be up for discussion.

**Comment by ShizCalev** [comment] 2018-04-10 19:34
Duplicate of #34136

**Closed by ShizCalev** 2018-04-10 19:34 UTC
Labels: Bug, Consistency Issue
