### ISSUE TITLE
Chem Reactions don't always trigger

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41509] opened 2018-11-14 21:25 UTC
Master

Repo:
Be virologist
put 1u of blood in a beaker
dropper 1u of plasma in
nothing happens
put 1u more of plasma
single reaction takes place
![image](https://user-images.githubusercontent.com/6209658/48513441-c6b73a00-e829-11e8-8d70-91584f02c4c0.png)

https://github.com/tgstation/tgstation/blob/70b623ea13b4d1e0bc1bf6636ad77ea18ad2be9f/code/modules/reagents/chemistry/recipes/others.dm#L213-L237

**Comment by Tlaltecuhtli** [comment] 2018-11-15 07:40
shut it down

**Comment by AnturK** [comment] 2018-11-15 10:21
From quick glance it's because reaction cache does not index catalysts.

**Comment by ShizCalev** [comment] 2018-11-15 14:53
I've had it happen both ways, adding plasma first, adding blood first, ect.

**Comment by XDTM** [comment] 2018-11-15 16:02
when it happened to me i usually saw one of the reagents was 0.999997 or something instead of 1, so it might be related to a rounding error (although the vv panel seems to indicate otherwise)

**Comment by nicbn** [comment] 2018-12-07 22:07
Possible solution is to round reagents to the first or second decimal place in reaction checks

**Comment by timothymtorres** [comment] 2021-08-20 09:37
> when it happened to me i usually saw one of the reagents was 0.999997 or something instead of 1, so it might be related to a rounding error (although the vv panel seems to indicate otherwise)

This is exactly the reason why this is happening.  I've seen this happen numerous times as a virologist over the ten years I've played and it's annoying.

**Comment by timothymtorres** [comment] 2021-08-20 09:38
Duplicate of #31206

**Closed by timothymtorres** 2021-08-20 09:38 UTC
Labels: Bug
