### ISSUE TITLE
A whole bunch of things display visible messages to the wrong people.

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#46797] opened 2019-09-29 02:01 UTC
Off the top of my head, you get other people's visible messages ("You do X") if you are in range of:

- Roulette machines
- Shoe snatching

**Comment by Tharcoonvagh** [comment] 2019-09-29 07:26
"You pets Ian."

**Comment by nemvar** [comment] 2019-09-29 08:07
Looks like this is fairly isolated.

**Comment by nemvar** [comment] 2019-09-29 08:18
The issue in the first comment has nothing to do with this really. It got caused by https://github.com/tgstation/tgstation/pull/46388 and will get fixed by https://github.com/tgstation/tgstation/pull/46744

**Comment by Tharcoonvagh** [comment] 2019-09-29 19:27
Nice, I guess

**Comment by cacogen** [comment] 2019-09-30 03:07
Someone shoved me into another person and the message I received said I was the one doing the shoving

**Comment by kingofkosmos** [comment] 2019-10-02 17:49
I'll have a look at these. If others show up, just paste the bugged out message and describe the situation a little and it'll be easy to fix.

**Comment by kingofkosmos** [comment] 2019-10-02 19:23
The shoe stealing was an easy fix but the roulette machine is a little more tricky. Not sure if I figure it out so I might have to leave this issue only half solved.

**Comment by ATH1909** [comment] 2019-10-03 00:13
https://github.com/tgstation/tgstation/issues/46168

**Comment by nemvar** [comment] 2019-10-03 13:27
I will be honest, for a second here I thought I fucked this up with https://github.com/tgstation/tgstation/pull/46499

**Comment by ShizCalev** [comment] 2020-01-30 20:58
fixed by #46744?

**Closed** 2020-01-30 21:01 UTC
Labels: Bug, Good First Issue, Grammar and Formatting
