### ISSUE TITLE
Interactable items not working sometimes

### ISSUE THREAD

**Issue by VonThrust** [tgstation/tgstation#78333] opened 2023-09-14 07:29 UTC
## Round ID:  
[214567](https://scrubby.melonmesa.com/round/214567)

## Testmerges: 
N/A

## Reproduction: 
[https://i.imgur.com/1Dd66ji.gif](url)
Unable to interact with stuff in backpacks or anything else that can hold equipment. 
Additionally, I cannot interact with items in my hand or turn on stuff like batons or PDAs. 
In the gif I am actively pressing on my equipment but it doesn't show anything unless I drag it onto myself.

An admin switched my body with theirs and the admin, using my body during the round, had no issues.
However me, in their body, only SOMETIMES had issues. The issue seemed to trigger if I wanted to take something
out of a backpack or something that can hold items.

**Comment by Sealed101** [comment] 2023-09-14 09:02
very likely a duplicate of #78308

**Closed** 2023-10-11 05:45 UTC
