### ISSUE TITLE
poly machine broke

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42697] opened 2019-02-07 19:43 UTC
`Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>"`

**Comment by imsxz** [comment] 2019-02-07 19:45
<Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>">

**Comment by imsxz** [comment] 2019-02-07 19:46
`Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>"`

**Comment by wesoda25** [comment] 2019-02-07 20:10
Feature

**Comment by ShizCalev** [comment] 2019-02-07 20:30
Duplicate of #36758

**Closed by ShizCalev** 2019-02-07 20:30 UTC
