### ISSUE TITLE
Can't claim personal closets

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75349] opened 2023-05-11 00:23 UTC
## Reproduction:
slap a personal closet with your id
it does not unlock it and assign it to your id
shift click to examine it and see it isn't assigned to anyone

tried on 2 different personal closets so I'm PRETTY SURE it's related to claiming them.

**Comment by SyncIt21** [comment] 2023-05-11 04:47
Not able to reproduce, works fine for me, You cannot unlock a personal closet as an assistant or as any random crewmate, you need to have the correct access levels
https://github.com/tgstation/tgstation/blob/807e11b30be892e14854a9a87f0bfc4886cf0a71/code/game/objects/structures/crates_lockers/closets/secure/personal.dm#L4
It works fine as a captain

https://github.com/tgstation/tgstation/assets/110812394/c13eeec9-9a10-4a27-adeb-d9302bb5b187

But not as a assistant

https://github.com/tgstation/tgstation/assets/110812394/fa3eab7c-406f-449c-867a-5a7b1ab9b9a6

@Time-Green we just discussed this isn't a problem and the one we were facing was something diffrent. Maybe you can close this

**Comment by Time-Green** [comment] 2023-05-11 05:33
> Not able to reproduce, works fine for me, You cannot unlock a personal closet as an assistant or as any random crewmate, you need to have the correct access levels
> 
> https://github.com/tgstation/tgstation/blob/807e11b30be892e14854a9a87f0bfc4886cf0a71/code/game/objects/structures/crates_lockers/closets/secure/personal.dm#L4
> 
> 
> It works fine as a captain
>  Captain.Has.Access.mp4 
> 
> But not as a assistant
> 
>  Not.Assistant.mp4 
> 
> @Time-Green we just discussed this isn't a problem and the one we were facing was something different. Maybe you can close this

I didn’t say it wasn’t a problem, it’s genuinely broken. People cannot use personal closets at all, which is a bug. It’s just not on your branch

**Comment by Time-Green** [comment] 2023-05-11 05:37
> 

I’m really not sure if it’s intended that only the captain can claim a personal closet? And even if it’s intended, it makes no sense

**Comment by SyncIt21** [comment] 2023-05-11 05:54
The  `req_access`  for personal closets wasn't changed in my previous PR,  it has had that value for a long time so it's definitely not a problem on my part.

But it also makes sense that's it's value is ACCESS_ALL_PERSONAL_LOCKERS like we would need a good reason to change it.

What's the solution here?

**Comment by SyncIt21** [comment] 2023-05-11 06:15
Ok so I just looked at the code changes from my previous PR and I did make some suttle changes to the personal closet attackby code .

The closet is meant to unlock  when there is either an ID registered or the person unlocking has ACCESS_ALL_PERSONAL_LOCKERS access I.e. he can override your id protection access. (Like the captain)

I'll fix this.

**Comment by Time-Green** [comment] 2023-05-11 06:16
Thanks!

**Closed** 2023-05-11 14:57 UTC
Labels: Bug
