### ISSUE TITLE
Pipe Disintegration 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64299] opened 2022-01-21 06:18 UTC
Reporting client version: 514.1575

## Round ID:
[176986](https://scrubby.melonmesa.com/round/176986)

## Testmerges:
- [Refactors pay stands + custom vendors](https://www.github.com/tgstation/tgstation/pull/63889)

**Comment by timothymtorres** [comment] 2022-01-21 08:25
Duplicate of #63815

**Closed by timothymtorres** 2022-01-21 08:25 UTC
