### ISSUE TITLE
trays dont equip on belt slot

### ISSUE THREAD

**Issue by BigGrease** [tgstation/tgstation#54058] opened 2020-09-29 00:38 UTC
Issue reported from  Round ID: [147271](https://scrubby.melonmesa.com/round/147271) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1532

simply, trays dont equip on the belt slot, when they used to. Im not sure why, but this limits the ability of cooks to transport foods. instead of being able to have 2 hands free and a tray full of food on your belt, you have to transport food by throwing (bad) or with a tray in your hand (not great). obviously, this is an issue.

**Comment by itseasytosee** [comment] 2020-09-29 00:56
funny

**Comment by rdragan** [comment] 2020-09-29 01:49
Caused by #53305

**Comment by nightred** [comment] 2020-09-29 18:12
without strap how are you carrying a tray in your Pocket? trays carry more then food, and are very large objects (even if not listed as large)

**Comment by BigGrease** [comment] 2020-09-29 18:23
not in your pocket, on your belt. your pocket wouldnt fit a tray

**Comment by PKPenguin321** [comment] 2020-10-05 05:16
Fixed by https://github.com/tgstation/tgstation/pull/54127

**Closed** 2020-10-29 20:13 UTC
Labels: Bug, Good First Issue
