### ISSUE TITLE
Revenant failed to spawn?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#77620] opened 2023-08-14 15:44 UTC
Reporting client version: 514.1589

## Round ID:
[212517](https://scrubby.melonmesa.com/round/212517)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
Ghosts got polled for Revenant.
I said yes, I'm not sure if anyone else did. But it shouldn't matter since Revenant only needs one player?
No revenant ever spawned.

No admins were on at the time to have cancelled it or something.

**Comment by Sealed101** [comment] 2023-08-14 16:53
dynamic log
```
[2023-08-14 14:56:58.007] DYNAMIC: Rolling HEAVY... 0 heavies / 5 lights
[2023-08-14 14:56:58.007] DYNAMIC: Rolling 5 light rulesets
[2023-08-14 14:56:58.008] DYNAMIC: Revenant ruleset executing...
[2023-08-14 14:56:58.008] DYNAMIC: A heavy ruleset was intended to roll, but there weren't any available. 0 heavies / 5 lights
[2023-08-14 14:57:08.067] DYNAMIC: Polling 3 players to apply for the Revenant ruleset.
[2023-08-14 14:57:38.438] DYNAMIC: 1 players volunteered for Revenant.
[2023-08-14 14:57:38.445] DYNAMIC: Injected a Midround ruleset Revenant.
```


runtimes
```
[2023-08-14 14:57:38.442] RUNTIME: runtime error: Cannot read null.key
 - proc name: generate ruleset body (/datum/dynamic_ruleset/midround/from_ghosts/revenant/generate_ruleset_body)
 -   source file: code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm,700
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): generate ruleset body(null)
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
 - 
[2023-08-14 14:57:38.443] RUNTIME: runtime error: Cannot read null.mind
 - proc name: finish setup (/datum/dynamic_ruleset/midround/from_ghosts/proc/finish_setup)
 -   source file: code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm,174
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish setup(null, 1)
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
 - 
[2023-08-14 14:57:38.445] RUNTIME: runtime error: Cannot read null.name
 - proc name: finish applications (/datum/dynamic_ruleset/midround/from_ghosts/proc/finish_applications)
 -   source file: code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm,164
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
```

**Comment by MrMelbert** [comment] 2023-08-14 17:22
I believe this is a dupe of #76100

**Closed by MrMelbert** 2023-08-14 17:22 UTC
Labels: Bug, Runtime
