### ISSUE TITLE
Fire can freeze over

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26697] opened 2017-04-29 01:15 UTC
A COLD DAY IN HELL @Iamgoofball 

![image](https://cloud.githubusercontent.com/assets/6778786/25551756/cdaed244-2c57-11e7-9608-935296410012.png)

Release freon and plasma at the same time start a fire to reproduce

Fire doesn't normally have that rounded look that the ice cube sprite has

**Comment by Armhulen** [comment] 2017-04-29 01:24
And hell froze over

**Comment by Bawhoppen** [comment] 2017-04-29 02:46
the snowflake freon freezing is a bit silly

we need a generalized freezing system

**Comment by Iamgoofball** [comment] 2017-04-29 03:30
this is the 50th time this "issue" hass been reported, it's not a bug

**Comment by duncathan** [comment] 2017-04-29 03:52
it's not a bug so I'm closing it but I want it to be known that I hate freon and this is among the reasons

**Closed by duncathan** 2017-04-29 03:52 UTC

**Comment by Kromgar** [comment] 2017-04-29 04:32
@Iamgoofball @duncathan  HOW IS THIS NOT A BUG? WHY WOULD FIRE FREEZE

**Comment by duncathan** [comment] 2017-04-29 04:36
it's intended behavior, regardless of the fact that it's stupid
