### ISSUE TITLE
How to be Immortal, undying, creature of unlife in only a few easy steps

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#59175] opened 2021-05-18 02:06 UTC
Reporting client version: 513.1542

## Round ID:
[162444](https://scrubby.melonmesa.com/round/162444)

## Testmerges:
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)
- [Toggles harddel searching for use on live [DNM]](https://www.github.com/tgstation/tgstation/pull/59118)

## Reproduction:
1. Be Rob Sterling
2. Get hit with Mayhem in a Bottle.
3. Fall into crit and die.
4. Somehow instantly stand back up after death.
5. You are now immune to stuns, hypnosis, and delimbing.
6. You are unable to speak or emote to the living and cannot move. However you can grab, pickup items, and adjust eqiuped items, attack things and people around you, and shove stuff in and out of your bags and pockets. Somehow.
7. Make Admins scream in frustration and confusion.

**Comment by LemonInTheDark** [comment] 2021-05-18 02:08
I hate players

**Comment by MrMelbert** [comment] 2021-05-18 02:16
More in depth reproduction steps:

- Get adminordrazine in you.
- Die somehow.
- Click rest and get up while dead.
- You now can't move, but can attack, while dead.

**Comment by upsetpanini1337** [comment] 2021-05-18 02:31
classic Rob

**Comment by TheBonded** [comment] 2021-05-18 17:16
Rob moment

**Comment by ATH1909** [comment] 2021-05-19 00:28
if I had to guess, this probably has something to do with `REMOVE_TRAITS_NOT_IN(M, list(SPECIES_TRAIT, ROUNDSTART_TRAIT, ORGAN_TRAIT))`

**Comment by MrMelbert** [comment] 2021-07-22 19:29
This might've been partially or fully fixed by #60344

**Closed** 2021-12-18 03:35 UTC
Labels: Bug, Against God and Nature, Cleanup Flagged

**Comment by LemonInTheDark** [comment] 2021-12-18 03:40
I take it it was fixed?

**Comment by Mooshimi** [comment] 2021-12-18 04:03
> I take it it was fixed?

If https://github.com/tgstation/tgstation/pull/60344 does as intended it should be.

**Comment by LemonInTheDark** [comment] 2021-12-18 04:18
I love this timeline
