### ISSUE TITLE
Space transit visuals broke when custom ship moved off to deep space for end round scenario.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32901] opened 2017-11-19 12:41 UTC
As all ships do, like the white ship, they move on to an "unknown location" forever in order to allow traitors to escape aboard them like a backup emergency shuttle. However, this custom ship had the transit space visuals break when doing that, so they had no indicator they were moving.

Might occur with regular white ship, but I don't know what causes any of this.

@ninjanomnom

**Comment by SpaceManiac** [comment] 2017-11-22 01:22
I suspect the problem is with the parallax code and not with shuttle movement specifically, I've also observed it happening at random on non-shuttle areas with `parallax_dir` set.

**Comment by Dennok** [comment] 2019-06-19 13:48
Still issue?

**Comment by timothymtorres** [comment] 2021-11-15 13:21
I just searched for similar open bug reports and couldn't find anything.  Marking this as cleanup.

**Closed** 2021-12-05 05:01 UTC
Labels: Bug, Cleanup Flagged
