### ISSUE TITLE
resonators fucking suck now

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#22878] opened 2017-01-09 13:41 UTC
The resonating field stays for about a second after detonation, but is invisible. if you walk into the tile during this time (say to pick up the ore that just dropped) you get damaged as if it detonated ontop of you.  In short: resonators fucking suck worse now.

**Comment by RemieRichards** [comment] 2017-01-09 13:42
Sounds like a bug with effects that self-delete, I recall one was recently converted from handling it itself to using the existing system, it was probably resonators then.

**Comment by vcordie** [comment] 2017-01-09 13:59
https://github.com/tgstation/tgstation/pull/22660 broke it. motherfuckers.

**Comment by coiax** [comment] 2017-01-09 15:03
Looking into it

**Comment by Cyberboss** [comment] 2017-01-09 15:25
#22660 only did a refactor, where did it break it?

**Comment by MrStonedOne** [comment] 2017-01-09 15:30
"it changed a line relating to timing, so it must be at fault"

**Comment by coiax** [comment] 2017-01-09 15:32
I can't reproduce this bug. I've already made some minor refactoring changes though, so I guess I'll PR them.

**Comment by optimumtact** [comment] 2017-01-09 21:38
This just sounds like a timing issue, not a bug, unless someone can repro, I'm closing

**Closed** 2017-01-10 23:52 UTC
Labels: Bug
