### ISSUE TITLE
Cult HUD Disappears with Z-level changes

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#70857] opened 2022-10-28 10:42 UTC
Round ID: [193233](https://scrubby.melonmesa.com/round/193233)

Testmerges: Guessing https://github.com/tgstation/tgstation/pull/69115 or https://github.com/tgstation/tgstation/pull/69334

Reproduction: Spawn as a roundstart cultist on a lower Z level. Move up a level, then go back down a level with a ladder. Your cult HUD then disappears. Going back up a level makes your cult HUD reappear. If you use the cult tele to go down a level, your hud stays. More problematically, other cultists' huds are affected by this, making allies sometimes show as noncult.

I've attached a clip that shows the issue. It first shows the cult hud disappearing with a ladder, then cuts to a shot of a fellow paramedic cultist with his hud showing, then a minute later the same paramedic cultist without his hud showing, making me think he wasn't a cultist. I believe he lost his cult hud because of this Z-level interaction.

https://streamable.com/kvnc5k

**Comment by msgerbs** [comment] 2022-10-28 18:21
Duplicate of #68087

**Closed by msgerbs** 2022-10-28 18:21 UTC

**Comment by SinfulBliss** [comment] 2022-10-28 19:32
> Duplicate of #68087

That issue doesn't mention anything about Z-levels and this was as a roundstart cultist, not a midround.
