### ISSUE TITLE
[BUG]New rot system ignores armor and cucks miners

### ISSUE THREAD

**Issue by Yawet330** [tgstation/tgstation#58045] opened 2021-03-29 19:04 UTC
## Reproduction:
>Be Me, Miner
>Gib goliath
>Touch gibs
>Die of lethal disease
>Stop mining

This is seriously an issue.

**Comment by ArcaneDefence** [comment] 2021-03-30 01:06
Duplicate of https://github.com/tgstation/tgstation/issues/58010

**Closed by ArcaneDefence** 2021-03-30 01:06 UTC
