### ISSUE TITLE
BirdBoat suit sensors map icons are misplaced

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#12880] opened 2015-11-06 14:01 UTC
![e6f4d1c3da8adbc426e6dec133a63177](https://cloud.githubusercontent.com/assets/12747768/10998701/3fd19402-8497-11e5-89dc-f505e2ccb496.png)
Everyone is in space, except not.

**Comment by Metacide** [comment] 2015-11-06 14:38
The same occurs on asteroid, but the offset makes half the crew appear south of the station.

No idea why. Think it's OK on MetaStation. Different z-level sizes?

**Comment by Marflowerose** [comment] 2015-11-06 22:26
Not sure if related but similar happens when using handheld crew monitor as a map when exploring other z-levels, usually it shows the correct z-level but for some reason it shows the crew on the station on the map rather than you. As in, the correct z-level shows but the crew dots and names are from the station.

**Comment by Tokiko1** [comment] 2015-11-07 02:18
The minimap suggests that this is an older version of the map, try updating it first. I am not quite sure what causes this issue, birdstation uses the same z-level sizes as box.

Also can't reproduce this locally, atleast with the newest version. Got any more info on how to cause this bug?

**Comment by Sligneris** [comment] 2015-11-07 23:01
Just open the crew monitoring panel on BirdBoat, that's how I did it. Granted, I did that as AI, so it might've been different.

Minimap might look off, because it's zoomed in.

**Comment by Menshin** [comment] 2015-11-21 12:17
Is this always happening ?
Sounds like it has been fixed by #13009...

**Comment by Metacide** [comment] 2016-01-06 12:43
Pretty sure this is still happening on BirdBoat.

**Closed** 2017-03-29 22:12 UTC
Labels: Bug
