### ISSUE TITLE
Mining Berserker hardsuit rage lasts forever

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#63082] opened 2021-11-26 12:42 UTC
## Round ID:
[173711](https://scrubby.melonmesa.com/round/173711)

## Testmerges:
#62132: 'multiz movement refactor redux' by Ghommie at commit b69e66961d

## Reproduction:
Activate rage. Now you are a very fast spaceman hitting at incredibly high speeds forever. Also you can't take it off.

**Comment by Ghommie** [comment] 2021-11-26 19:46
Duplicate of #62607.

**Closed** 2021-11-27 05:49 UTC
