### ISSUE TITLE
Plants stopped growing

### ISSUE THREAD

**Issue by chillbowman** [tgstation/tgstation#33257] opened 2017-12-04 02:45 UTC
Issue reported from Round ID: 79634 (Sybil)

Unknown steps to reproduce issue. After mutating pumpkins into blumpkins, all plants in hydroponics stopped growing or loosing water/nutrients. Happened not long after round start.

**Comment by Cyberboss** [comment] 2017-12-04 03:12
Duplicate of #33254

**Closed by Cyberboss** 2017-12-04 03:12 UTC
