### ISSUE TITLE
No longer able to space drag

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#37802] opened 2018-05-12 02:32 UTC
[Round ID]: #87807

[Reproduction]: Basically, upon trying to drag something towards another z-level, the dragged object/person/etc is lost ahold of upon entering the next z-level. Usually in the past it'd automatically resume the drag and you could keep on with your space stuff just fine; it makes it more tedious for things like having a canister for jetpack refills with the canister being left behind. Plus you can just sorta drift back atop of whatever it was, even if its solid.

![capture](https://user-images.githubusercontent.com/32374784/39952598-f8478d40-554e-11e8-9a0a-a064e152f680.PNG)

**Comment by AlexTheSysop42** [comment] 2018-05-12 02:40
Dupe of #37372

**Comment by SpaceManiac** [comment] 2018-05-12 05:46
unfortunate and annoying but duplicate of #37372 nonetheless

**Closed by SpaceManiac** 2018-05-12 05:46 UTC
