### ISSUE TITLE
Bitrunning Glitch in FNAF zone triggers bear aggro

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#85471] opened 2024-07-31 22:05 UTC
Reporting client version: 515.1642

## Issue Summary

A virtual domain guardian within the FNAF zone triggers the bears aggression and is quickly killed
## Round ID:
232959

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)

## Reproduction:

1. Be bitrunner virtual guardian within FNAF pizza parlor.
2.  Observe bear mobs attack and kill you.

**Comment by SmArtKar** [comment] 2024-07-31 22:05
Duplicate of #85197

**Closed by SmArtKar** 2024-07-31 22:05 UTC
