### ISSUE TITLE
You can get golden wheelchairs in the mail even if you don't have 5000 hc random points

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70367] opened 2022-10-07 12:17 UTC
Reporting client version: 514.1585

## Round ID:
[191908](https://scrubby.melonmesa.com/round/191908)

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)

## Reproduction:
https://github.com/tgstation/tgstation/pull/70091 added the ability to get the golden wheelchair from the mail if you have the paraplegic quirk, but that item was intended to be only for people who have gotten 5000 hc random points

**Comment by msgerbs** [comment] 2022-10-07 16:19
Was it? It's not mentioned anywhere in the PR or the code. Was there a discussion with Tim on Discord where they confirmed this?

**Comment by ShizCalev** [comment] 2022-10-07 21:06
wtf is a hc random point

**Comment by ShizCalev** [comment] 2022-10-07 21:08
wtf is a `hc random point`

**Comment by newfren** [comment] 2022-10-08 02:10
https://github.com/tgstation/tgstation/issues/65045

is the previous issue that brought this up

**Comment by timothymtorres** [comment] 2022-10-08 03:35
This was intended and listed in the PR for the paraplegic quirk.  The golden wheelchair has a 5% spawn chance as a mail item which is pretty rare.  With #65045 MMM was allowed to keep it as an item that can appear in tram maint, so I don't see the big deal here.

I'm marking this as `Not a bug`.

**Comment by msgerbs** [comment] 2022-10-08 05:24
After understand what on earth "hc random points" are I understand the complaint here. What if it was a motorized wheelchair instead? They are craftable, but not super easy if you don't have access to stock parts and cells.

**Comment by Time-Green** [comment] 2022-10-08 12:04
Should probably just add linters to prevent it being abused like this, cause it really will just keep happening

**Closed** 2022-10-09 20:03 UTC
Labels: Not a bug, Cleanup Flagged
