### ISSUE TITLE
Temp visuals stop deleting themselves late into the round

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27937] opened 2017-06-01 11:44 UTC
>2 hour round 

>things won't qdel

Why.

**Comment by Cyberboss** [comment] 2017-06-01 13:24
Sounds like the timer system conked out

**Comment by AnturK** [comment] 2017-06-01 13:27
Seen this happen yesterday on 2h+ round too. Was pretty noticeable with emp blob.

**Comment by Cyberboss** [comment] 2017-06-02 15:34
Let's fold this one into a dupe of #23818

**Comment by RocKeD** [comment] 2017-06-07 05:51
I noticed this too, could this be related to the issue I submitted? #28177

**Comment by Cyberboss** [comment] 2017-06-18 02:46
Dupe

**Closed by Cyberboss** 2017-06-18 02:46 UTC
Labels: Bug
