### ISSUE TITLE
AIs cannot use exosuit equipment due to a runtime and oversight

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#66117] opened 2022-04-10 13:37 UTC
First issue being:
AIs cannot use controlled exosuit due to a runtime on the shift-click thing
```
proc name: on mouseclick (/obj/vehicle/sealed/mecha/proc/on_mouseclick)
usr: X/(AI)
usr.loc: (Central Primary Hallway (107,144,2))
src: the Durand (/obj/vehicle/sealed/mecha/combat/durand)
src.loc: the floor (107,144,2) (/turf/open/floor/iron)
call stack:
the Durand (/obj/vehicle/sealed/mecha/combat/durand): on mouseclick(AI (/mob/living/silicon/ai/spawned), the reinforced window (/obj/structure/window/reinforced/fulltile), "icon-x=21;icon-y=26;middle=1;s...")
the Durand (/obj/vehicle/sealed/mecha/combat/durand): on middlemouseclick(AI (/mob/living/silicon/ai/spawned), the reinforced window (/obj/structure/window/reinforced/fulltile), "icon-x=21;icon-y=26;middle=1;s...")
AI (/mob/living/silicon/ai/spawned): SendSignal("mob_middleclickon", /list (/list))
AI (/mob/living/silicon/ai/spawned): MiddleClickOn(the reinforced window (/obj/structure/window/reinforced/fulltile), "icon-x=21;icon-y=26;middle=1;s...")
AI (/mob/living/silicon/ai/spawned): ClickOn(the reinforced window (/obj/structure/window/reinforced/fulltile), "icon-x=21;icon-y=26;middle=1;s...")
the reinforced window (/obj/structure/window/reinforced/fulltile): Click(the plating (107,142,2) (/turf/open/floor/plating), "mapwindow.map", "icon-x=21;icon-y=26;middle=1;s...")
X (/client): Click(the reinforced window (/obj/structure/window/reinforced/fulltile), the plating (107,142,2) (/turf/open/floor/plating), "mapwindow.map", "icon-x=21;icon-y=26;middle=1;s...")
```
Likely responsible line of code for the runtime (at line 564 _mecha.dm):
```
	if(modifiers[SHIFT_CLICK]) //Allows things to be examined.
		return
```
And the second:
AIs can only use middleclick to use the mech equipment (it probably defaults to left mouse button but about the gear on the right?), while the new changes made it only use left click and right click
## Reproduction:

1. Attach AI Control Beacon to Exosuit
2. Be AI
3. Control exosuit
4. Try to use your fancy guns or punch a window
5. Fail because it runtimes and you can only use left mouse button or right mouse button to interact with the mech

**Comment by mc-oofert** [comment] 2022-04-10 13:40
probably caused by the AI Eye being unable to shiftclick

**Comment by Fikou** [comment] 2022-04-10 20:15
Dupe of #64112

**Closed by Fikou** 2022-04-10 20:15 UTC
