### ISSUE TITLE
Cardboard_cutout doesn't seem repaintable

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#84117] opened 2024-06-18 18:42 UTC
Reporting client version: 515.1640

## Round ID:
[230760](https://scrubby.melonmesa.com/round/230760)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Spawn a /obj/item/cardboard_cutout
Spawn a /obj/item/toy/crayon
Hit the former with the latter.  Nothing happens.  Something should happen.

Note if you fake proc call on the cutout for "attackby([marked crayon],[marked your mob])" then you'll get the radial menu and the decoration takes effect, suggesting something "up-stack" of attackby is probably blocking the call (i'm just trying to educated guess)

**Comment by LSommers** [comment] 2024-06-20 20:58
Crayons also seem to be unable to write on paper- see https://github.com/tgstation/tgstation/issues/84092

**Comment by DATA-xPUNGED** [comment] 2024-06-20 21:45
Duplicate of #84092

**Closed by DATA-xPUNGED** 2024-06-20 21:45 UTC
