### ISSUE TITLE
Thunderdome Reset is broken

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#27375] opened 2017-05-17 19:56 UTC
The admin button that resets the Thunderdome is broken, probbably due to the huge ugly centcom remap moving the Thunderdome and the thunderdome being coded in a really shite way.

**Comment by WJohn** [comment] 2017-05-17 20:54
Dupe of #26198

**Closed by WJohn** 2017-05-17 20:54 UTC
Labels: Administration, Bug, Map Issue
