### ISSUE TITLE
Floorbot broken tile asset bug/impassable tile

### ISSUE THREAD

**Issue by PingyTalk** [tgstation/tgstation#85644] opened 2024-08-06 06:17 UTC
Reporting client version: 515.1642

## Issue Summary
As the Floorbot ghost spawner role when placing a floor in the maintence tunnel to the right of central hallway, it created bug tiles with purple broken asset stuff and they were immovable/impassable.

## Round ID:
[233759](https://scrubby.melonmesa.com/round/233759)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
Play on Metastation, play Floorbot Ghost Role, go to the Central Primary Hallway, far upper right side near the newscaster/cigar machine/disposal. Click to place tiles on the open slots in the maintence hallway, the four tiles closest to that upper right door (adjacent to one empty tile adjacent to the disposal unit). Placement of tiles here causes broken tile assets that are immovable, invincible, and impassable.
![2024-08-06 00_28_05-Window](https://github.com/user-attachments/assets/a8aec6e8-5652-45f1-8cf3-ad62c5c953d8)
Here is an image of it
I can include more images or anything else needed on request

**Comment by Sadboysuss** [comment] 2024-08-06 12:21
dupe of https://github.com/tgstation/tgstation/issues/85102

**Closed** 2024-08-06 17:37 UTC
