### ISSUE TITLE
Chem sprays aren't applying chems when shot at the tile you're standing on

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#66116] opened 2022-04-10 10:15 UTC
## Reproduction:
Spray bottles aren't applying their chems if you shoot them at the tile you're standing on. Makes stuff like Hercuri and spray tan basically unusable.

**Comment by timothymtorres** [comment] 2022-04-11 02:37
Might be a dupe of #62873

**Comment by timothymtorres** [comment] 2022-11-05 08:10
Duplicate of #62873

**Closed by timothymtorres** 2022-11-05 08:10 UTC
Labels: Bug
