### ISSUE TITLE
Pulling a Kinetic Accelerator off your suit storage momentarily drops it.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#20965] opened 2016-10-13 23:12 UTC
Put KA in your suit slot, take it out, notice that it drops for a microsecond before going into your hands.

**Comment by ChangelingRain** [comment] 2016-10-13 23:42
Duplicate of #20885

**Comment by PKPenguin321** [comment] 2016-10-13 23:46
sort of but not really, try dropping a KA, it is MUCH more noticeable for them than other objects. started happening right after coiax's thingy that made them self charge

**Closed** 2016-10-15 15:57 UTC
Labels: Bug, Needs Reproducing/Testing
