### ISSUE TITLE
You can see Hud stats when people are hidden behind plants

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#75268] opened 2023-05-08 15:47 UTC
## Reproduction:
Have any hud that analyzes any mob trait like sec huds or med huds

Realize the killer/criminal is hidding behind a plant thinking they are all sneaky when you can clearly see them 

How can you see their there? It just works 
It sucks to be able to be spotted with a hud during plant hidding it essentially makes trying to hide form sec using a potted plant impossible

**Comment by Sealed101** [comment] 2023-05-12 15:02
it has been around for a long ass time, my gut says it's a feature but who knows

**Comment by Mothblocks** [comment] 2023-10-30 21:23
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:23 UTC
Labels: Not a bug, Bug
