### ISSUE TITLE
Lavaland fauna can see through walls and are performing their moves 2-3x faster

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#86614] opened 2024-09-11 23:51 UTC
### Client Version:

515.1642

### Issue Summary:

The title captures it pretty well.

### Round ID:

[237606](https://scrubby.melonmesa.com/round/237606)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)
- [Storage / table interactions at the bottom of the interaction chain](https://www.github.com/tgstation/tgstation/pull/85512)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

Go down to lavaland, assuming you have any experience with how fast they were previously.

**Comment by LemonInTheDark** [comment] 2024-09-12 00:01
see through walls is #86585 which is resolved.
Unsure about the rest

**Comment by Metekillot** [comment] 2024-09-12 00:17
https://github.com/tgstation/tgstation/pull/86564

It would appear that the parts of this code that were removed for optimization did not account for the fact that planning cooldowns and behavior cooldowns were not the same thing.

**Comment by Ben10Omintrix** [comment] 2024-09-12 02:01
im having a bit of trouble reproducing this. i booted up my local to test brimdemon and goliath speeds this is what i got 

https://github.com/user-attachments/assets/914fd44f-ba9b-4fe1-aed4-8a7ab78c8f7f

https://github.com/user-attachments/assets/c7fa5240-6b9f-4086-8095-bd907e5d83c1

ill try to check deeper into it soon

**Comment by Metekillot** [comment] 2024-09-12 02:11
Brimdemons shooting at you and their beam persisting is supposed to be the opening to hit them without getting bit or beamed again. They aren't meant to cut the beam off and start pathing again.

I may have been incorrect on the goliath speed; I was possibly mistaking unseen goliath tentacles as coming in bursts from the one goliath I could see, since they have xray vision at the moment.

**Comment by Ben10Omintrix** [comment] 2024-09-12 02:24
that makes more sense. i think i know what the issue is now

**Comment by Sadboysuss** [comment] 2024-09-12 10:19
Partial dupe of https://github.com/tgstation/tgstation/issues/85339 ?

**Closed** 2024-09-14 20:25 UTC
