### ISSUE TITLE
Syndicate Base(?) spawns inside/next to White ship

### ISSUE THREAD

**Issue by CJulien** [tgstation/tgstation#27299] opened 2017-05-15 14:51 UTC
Problem Description: Was space exploring, found the whiteship curiously merged with some kind of syndicate thing.

What did you expect to happen: I expect that these are two seperate space encounters that are supposed to be seperate

Why is this bad/What are the consequences: Parts of the whiteship merged around it, and there was no entrance to the syndie bit( I had to cut my way in)

Steps to reproduce the problem: Fuck if I know

Server: Sybil

Revision: Server revision compiled on: 2017-05-15
685309 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Here is a screenshot https://imgur.com/a/QkKGT

Also make it so the gps isn't locked to one screen.

**Comment by CJulien** [comment] 2017-05-15 14:52
launching the whiteship did not bring the syndie bit with

**Comment by Penguaro** [comment] 2017-05-15 14:58
Likely related to or a duplicate of #27233

**Comment by francinum** [comment] 2017-05-15 15:27
@CJulien the GPS is locked to the primary monitor because it is TGUI, this can be changed in your game preferences, in the same window where antag prefs are set, why it isn't all monitors by default I do not know.

**Comment by Penguaro** [comment] 2017-05-15 15:29
@CJulien I didn't even notice the GPS comment. In the future, please try to limit one topic to each issue you post. For example this would be two separate issues and what francinum said should resolve that for you, but if not, feel free to open an issues for it.

**Comment by Jalleo** [comment] 2017-05-15 17:14
Right I need to know which round this was to find out which merged here. Its likely a mapping error occured. @CJulien This is because I think that the ruin locations are logged.

**Comment by CJulien** [comment] 2017-05-15 17:26
@Jalleo I'm pretty sure it was the current(evacing) sybil round, or the previous one.

**Comment by Penguaro** [comment] 2017-05-15 17:40
Just as an aside, I saw this on a local build when I was testing for my own PRs. I don't believe this is part of a test merge.

**Comment by octareenroon91** [comment] 2017-05-18 19:23
Ruins don't have any special protections from later mapping events such as mineral turf/ore seeding and _any later ruin_.

**Comment by Dennok** [comment] 2019-06-20 06:37
Now ruins have protection from random placing another ruins on it.
So this is outdated.

**Closed** 2019-07-18 08:38 UTC
Labels: Bug

**Comment by Addust** [comment] 2023-03-17 23:44
that's the turreted outpost, the 'syndie thing'

also holy shit that whiteship is ancient
