### ISSUE TITLE
Screwdrivers on trays lose their colour

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#32240] opened 2017-10-29 23:34 UTC
[Directions]: # Place a screwdriver on a tray. Observe as the tray sprite has a bone white handled screwdriver where your original screwdriver was probably brown or whatever.
http://puu.sh/yagcC/b49e31094a.png

**Comment by PKPenguin321** [comment] 2017-10-30 01:01
Effectively a dupe of https://github.com/tgstation/tgstation/issues/31871

**Comment by ShizCalev** [comment] 2017-11-02 07:02
Duplicate of #31871

**Closed by ShizCalev** 2017-11-02 07:02 UTC
