### ISSUE TITLE
Fugitives can spawn into space on Delta Station

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#44152] opened 2019-05-26 08:04 UTC
## Reproduction: Spawn fugitives on Delta station through random event.

Upon spawning the fugitives all ended up in space without a clear way into the station and without any protective gear. I am unsure if this is intended but it does not feel as though it was. (I was just observing this round)

**Comment by tralezab** [comment] 2019-05-27 05:13
dupe of #43945

**Closed** 2019-05-27 08:47 UTC
