### ISSUE TITLE
Carving Blocks can't be carved

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#72607] opened 2023-01-10 04:00 UTC
Reporting client version: 514.1582

## Round ID:
[197950](https://scrubby.melonmesa.com/round/197950)

## Reproduction:
Attempting to make a statue from a carving block lets you click it the first time to "prepare to work on the MATERIAL block.", but you can't click a different item afterwards to select a subject, meaning no making a statue. Attempted to make statues with multiple materials (Iron, Glass, Titanium, Sheetzas), as well as to have multiple different people try, but it did not work in any combination.

**Comment by timothymtorres** [comment] 2023-01-10 20:24
Duplicate of #65701

**Closed by timothymtorres** 2023-01-10 20:24 UTC
