### ISSUE TITLE
Placing a brain in a body after being extracted from an MMI puts you in nullspace

### ISSUE THREAD

**Issue by Crimsonerva** [tgstation/tgstation#85324] opened 2024-07-27 22:28 UTC
## Issue Summary

I got gibbed, placed into an MMI, then taken out and placed into a monkey human. Each time my brain was placed in, I got sent to nullspace, then the magic rupee room. I was playing Jessica Walker in the round this occurred in. I got sent to the rupee land multiple times.

## Round ID:

[232744](https://scrubby.melonmesa.com/round/232744)

## Testmerges:

[#84873: 'Block atmos processing on ReservedTurfs\:tm: ' by ZephyrTFA at commit e3480139fa](https://www.github.com/tgstation/tgstation/pull/84873)
[#85137: 'Death of mutant bodyparts AND external organs' by Time-Green at commit fcd5fa0805](https://www.github.com/tgstation/tgstation/pull/85137)

## Reproduction:

1 - Get gibbed
2 - Get placed into an MMI
3 - Get taken out, and put into a monkey-man corpse
4 - Get sent to nullspace

**Comment by Sadboysuss** [comment] 2024-07-28 07:49
Dupe of https://github.com/tgstation/tgstation/issues/85321

**Closed** 2024-07-28 07:50 UTC
Labels: Test Merge Bug
