### ISSUE TITLE
Abductor Agent disguises don't maintain their look properly when teleporting to the station/traversing zlevels.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#72640] opened 2023-01-11 04:12 UTC
Reporting client version: 514.1589

## Round ID:
[197998](https://scrubby.melonmesa.com/round/197998)

## Reproduction:

The abductor agent's disguise frequently bugs out when teleporting to the station and when moving up/down zlevels through any means. It'll maintain parts of the disguises but most of the agent's gear will suddenly show through the disguise rendering it pretty much useless if anyone is paying attention at all.

![dreamseeker_9yHSf35XvM](https://user-images.githubusercontent.com/33107541/211716000-06b86e9f-f834-460b-b11a-0b5bb27ef7a2.png)

The agent can sort of fix this by toggling the disguise off and on again every single time it happens.

**Comment by timothymtorres** [comment] 2023-01-11 21:05
Duplicate of #71176

**Closed by timothymtorres** 2023-01-11 21:05 UTC
