### ISSUE TITLE
N2O is invisible.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33439] opened 2017-12-10 05:37 UTC
round id 79947
commit https://github.com/tgstation/tgstation/commit/e13513ac9d03b5e045940c5c2171b28c5932d6a5
there was enough n2o to knock out but no one could see it, no overlays.
high as 5% from atmos scanners.

**Comment by duncathan** [comment] 2017-12-10 07:12
Are you on 511 or 512? That was a Sybil round so if you're running 511 then this issue can be closed as it's known behavior

**Comment by praisenarsie** [comment] 2017-12-10 08:57
what dunc said

**Comment by ShizCalev** [comment] 2017-12-10 20:07
Tested on 512, overlays functioning as intended.

**Closed by ShizCalev** 2017-12-10 20:07 UTC
