### ISSUE TITLE
Can't drag one container/bag onto another to seamlessly transfer items in between.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30036] opened 2017-08-20 12:26 UTC
1. Drag one bag onto the other
2. contents get dumped on the floor instead

expected:
It transfers contents between old container and new one.
Server revision compiled on: 2017-08-17

The following pull requests are currently test merged:

Based off origin/master commit: 093cb1

**Comment by AnturK** [comment] 2017-08-20 17:17
Duplicate of #30007

**Closed by AnturK** 2017-08-20 17:17 UTC
