### ISSUE TITLE
Xenbio Potion Color not updating

### ISSUE THREAD

**Issue by Helvetica8563** [tgstation/tgstation#68866] opened 2022-07-30 03:43 UTC
round id doesnt really matter because it happens on every tg server and i dont have it anyway

xenbio fireproofing, pressureproofing and lava proofing potions when applied to clothing you are wearing does not apply the color until you update the item (toggle lamp welding mask or style)

**Comment by Mooshimi** [comment] 2022-08-03 00:08
Dupe of #67689

**Closed by Mooshimi** 2022-08-03 00:08 UTC
