### ISSUE TITLE
Radiation storm visual effect does not go away after the event until you enter a room

### ISSUE THREAD

**Issue by PVT-LF** [tgstation/tgstation#76413] opened 2023-06-29 18:24 UTC
## Reproduction:
As seen below, the storm effect stays until you enter a room which updates it.

Pretty minor, but it wasn't listed, just adding it here.
![Screenshot (228)](https://github.com/tgstation/tgstation/assets/63499294/fef2fe37-752d-4970-93d2-4e9377a1ceb4)

**Comment by Sealed101** [comment] 2023-06-29 18:33
Duplicate of #75352
seems like it's a bug both ways - removing and adding or showing the change of the overlay's goofed somewhere

**Closed** 2023-06-29 18:33 UTC
