### ISSUE TITLE
Blindfolds still block vision with xray and thermal eyes.

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#33404] opened 2017-12-08 23:58 UTC
dumbest issue report I've ever done but I feel like reporting it anyways because I cant do funny blind swordsman gimmicks with this

**Comment by praisenarsie** [comment] 2017-12-09 01:35
dupppppppppppppppppppppeeeeeeeeeeeeeeeeeee

**Comment by YPOQ** [comment] 2017-12-09 04:21
#25531

**Comment by ShizCalev** [comment] 2017-12-09 07:30
duplicate of #25531

**Closed by ShizCalev** 2017-12-09 07:30 UTC
