### ISSUE TITLE
Cyborgs can buckle people to chairs, but cannot unbuckle people from chairs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#42093] opened 2018-12-27 15:18 UTC
Round ID: 99318

1) Be borg.
2) Buckle a human to a chair.
3) Attempt to unbuckle.
4) Realise your only method of unbuckling is to deconstruct or destroy the chair.

**Comment by imsxz** [comment] 2018-12-28 22:40
borgs don’t even got hands how are they buckling people lmao

**Comment by ShizCalev** [comment] 2019-03-11 10:40
Duplicate of #37131

**Closed by ShizCalev** 2019-03-11 10:40 UTC
Labels: Consistency Issue
