### ISSUE TITLE
new grindables recipes dont work

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33136] opened 2017-11-27 17:48 UTC
that one pr with new grindables is broken tried grinding glowsticks n shit they didnt get grinded #32107

**Comment by praisenarsie** [comment] 2017-11-28 07:58
Dupeeeeeeer

**Comment by AnturK** [comment] 2017-11-28 08:46
Duplicate of #32532

**Closed by AnturK** 2017-11-28 08:46 UTC
