### ISSUE TITLE
Supply request console cannot print crate access restriction properly.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/tgstation#10225] opened 2015-06-28 10:43 UTC
they just print: "ACCESS RESTRICTION: $Err$ Unknown Error."

**Comment by bgobandit** [comment] 2016-02-07 06:10
I cannot reproduce this, when I try it prints the access text normally

**Comment by Core0verload** [comment] 2017-01-10 23:20
Looks like it was already fixed in one of the cargo refactors.

**Comment by bgobandit** [comment] 2017-02-15 04:22
why is this still open then

**Comment by ShizCalev** [comment] 2017-06-09 02:47
@lzimann can be closed

**Closed** 2017-06-09 06:37 UTC
Labels: Bug
