### ISSUE TITLE
Abductors say ... when using telepathic speak

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25543] opened 2017-03-27 16:23 UTC
This is probably a dupe but I did a brief search and couldn't find one

**Comment by coiax** [comment] 2017-03-27 17:18
Yeah, dupe of #22910. I know that because it 's one of my issues.

**Comment by XDTM** [comment] 2017-03-27 17:35
I also pinpointed the code that causes it, but i don't have a solution yet

**Comment by Armhulen** [comment] 2017-03-27 17:58
It's a dupe but MY GOD DO I HATE THIS

**Closed** 2017-03-27 18:59 UTC
