### ISSUE TITLE
trying to move down stairs on tram causes you to stop dragging whatever you're dragging

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59213] opened 2021-05-20 20:38 UTC
Reporting client version: 513.1536

## Round ID:
N/A

## Reproduction:
- try to drag someone/something down the dorms or engineering stairs
- fail
I don't know if this happens with the science stairs, and you can drag something up the stairs perfectly fine.

**Comment by dragomagol** [comment] 2021-05-20 21:13
Duplicate of #47376

**Closed by dragomagol** 2021-05-20 21:13 UTC
