### ISSUE TITLE
TGUI gets borked upon loading 👨‍💻

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#66548] opened 2022-04-27 00:32 UTC
Reporting client version: 514.1583

## Round ID:
[182210](https://scrubby.melonmesa.com/round/182210)

## Reproduction:
1. Join Manuel station via hyperlink "byond://sybil.tgstation13.org:1448"
2. Observe the following text within the menu option fail to load correctly and displays the following error text:

```
"A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:65206/tmp3408/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x21086861]-main","size":null,"fancy":1,"locked":1}}


```

**Comment by Mothblocks** [comment] 2022-04-27 00:33
Duplicate of #66535

**Closed by Mothblocks** 2022-04-27 00:33 UTC
