### ISSUE TITLE
Ghosts can interact with and arm proximity sensors

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#39817] opened 2018-08-20 14:36 UTC
[Round ID]: # Any round

[Reproduction]: # Be a ghost and find any proximity sensor, stand next to it and you can arm it and mess with its settings.

**Comment by XDTM** [comment] 2018-08-22 14:43
Time to add an ouija sensor for assemblies

**Comment by Anonmare** [comment] 2018-08-23 19:45
Duplicate of #38717

Not sure why that issue was closed

**Closed** 2018-09-26 09:28 UTC
Labels: Bug
