### ISSUE TITLE
Telekinesis interacts with guns very strangely

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61660] opened 2021-09-23 11:27 UTC
## Testmerges:
The following pull requests are currently test merged:
#61467: 'Disable lobby music until sound preferences are re-added to the top bar menu.' by MrStonedOne at commit 6cb5dd1fee
#61400: 'Adds a second Detective slot.' by Iamgoofball at commit 85f60a731c

## Reproduction:
This one's a banger
https://puu.sh/Idoqm/7dca23afd8.png
in this situation, I am holding the laser gun with telekinesis. If I throw it by clicking on a wall or whatever, it just throws, fine, expected. 
If I have combat mode ON and strike the spider with the gun, it just beats up the spider, whatever, sure.
If I have combat mode OFF however, and I strike the spider...
https://puu.sh/Idor4/345a53e5b6.png
it fucking shoots the gun from my current position!

**Comment by necromanceranne** [comment] 2021-09-24 09:46
TK continues to plague us with missed checks.

**Comment by timothymtorres** [comment] 2021-12-29 23:34
Duplicate of #42242

**Closed by timothymtorres** 2021-12-29 23:34 UTC
Labels: Bug
