### ISSUE TITLE
tgui white screen + unability to open windows

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51410] opened 2020-06-01 08:28 UTC
138491
example of not opening window
click vendor window for first time no open
relog it opened slowly

then ALL windows started whitescreening
 RELOADING DIDNT FUCKING FIX IT
HAD TO HARD RESTART THE GAME PAGE

**Comment by Fikou** [comment] 2020-06-01 08:55
had the same issues for a long time, i reinstalled byond and removed cache and it seemed to help

**Comment by stylemistake** [comment] 2020-07-16 19:29
Duplicate of #47793

**Closed by stylemistake** 2020-07-16 19:29 UTC
Labels: UI
