### ISSUE TITLE
RCD Link bug 

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#63977] opened 2022-01-10 02:50 UTC
Reporting client version: 514.1557

## Round ID:
[176333](https://scrubby.melonmesa.com/round/176333)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)
- [Fixing living_say because I totally didn't accidentally break something](https://www.github.com/tgstation/tgstation/pull/63939)

## Reproduction:

Occasionally, for reasons which are not clear to me, my RCD with a silo link will break, it just says "Low ammo" even if the link is off and it's full

![image](https://user-images.githubusercontent.com/14065903/148713042-1d9ed6ff-61aa-48ac-a34c-fb5a48ba70ed.png)

**Comment by timothymtorres** [comment] 2022-01-10 03:40
Duplicate of #63149

**Closed by timothymtorres** 2022-01-10 03:40 UTC
