### ISSUE TITLE
Moth food (or at least pizza) recipes require an entire wheel of firm cheese

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#65159] opened 2022-02-25 11:23 UTC
Try to make moth pizza with firm cheese, which already is a pain to make, cut the firm cheese wheel up, realize you can't use firm cheese slices for the recipe, cry.

**Comment by BallastMonster** [comment] 2022-02-27 09:47
close please?

**Comment by SuperNovaa41** [comment] 2022-03-01 01:53
Dupe of https://github.com/tgstation/tgstation/issues/63998

**Closed by SuperNovaa41** 2022-03-01 01:53 UTC
Labels: Consistency Issue
