### ISSUE TITLE
Cleaner grenades/foam and smoke grenades last *WAY* too long. 

### ISSUE THREAD

**Issue by j-nengel** [tgstation/tgstation#73654] opened 2023-02-25 17:16 UTC
Seriously, they last for like a solid 90 seconds at least. It's absurd.

**Comment by j-nengel** [comment] 2023-02-25 17:22
And that's to say nothing of this shit: 
![image](https://user-images.githubusercontent.com/76132356/221370743-cbd741d5-36a7-4385-ad38-35ff3f5a87ab.png)

**Comment by moocowswag** [comment] 2023-02-26 19:54
Take helgrasp for example, if time dilation is high youll get very few hands over a long period of time, its pretty much the best way to test to see if chemistry balance is skewed for the round.

**Comment by msgerbs** [comment] 2023-05-05 21:30
This is a duplicate of #69943, although it is strange that chemistry and foam are both affected here; Those are totally separate subsystems. Chemistry effects (once the chem is in your system) is handled by life() ticks, whereas foam is handled by a dedicated subsystem can be overwhelmed by large amounts of foam.

**Closed by msgerbs** 2023-05-05 21:30 UTC
