### ISSUE TITLE
Flat dough into pastry bases

### ISSUE THREAD

**Issue by Losenis** [tgstation/tgstation#55118] opened 2020-11-22 23:53 UTC
Issue reported from  Round ID: [150814](https://scrubby.melonmesa.com/round/150814) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

Making a dough (15u flour, 10u water), flattening it, and then slicing it turns into raw pastry bases rather than dough slices.

**Comment by dragomagol** [comment] 2020-11-23 03:15
Duplicate of #55117

**Closed by dragomagol** 2020-11-23 03:15 UTC
