### ISSUE TITLE
Sprite permanently changing into plant

### ISSUE THREAD

**Issue by ThelonTV** [tgstation/tgstation#49984] opened 2020-03-15 20:35 UTC
So after turning myself into a monkey as usual through genetics for RP reasons, I noticed that you can pick up plants with one hand now as a monkey. The next logical step was to pick up another with the empty hand and that's when your sprite changes into the newer plant. Should you drop both plants now your sprite will still remain as the plant you first picked up though. Easily replicarteable and was also replicated by an admin through ahelp. A few screenshots of me replicating it are also attached.

![pic1](https://user-images.githubusercontent.com/62219567/76710095-bc9a9980-6704-11ea-9443-db39f7a5e9fc.PNG)

![pic2](https://user-images.githubusercontent.com/62219567/76710094-bc9a9980-6704-11ea-90a4-ba090710169b.PNG)

![pic3](https://user-images.githubusercontent.com/62219567/76710093-bc020300-6704-11ea-9f57-4b73ee5236c4.PNG)

Issue reported from  Round ID: [132276](https://scrubby.melonmesa.com/round/132276) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1511

**Comment by Pumpkinoe** [comment] 2020-03-17 22:29
extreme stealth
maybe this was caused by the two-handed component thing?

**Comment by NanoCats** [comment] 2020-03-17 23:13
This one doesn't seem that bad considering only monkeys can do it right?

**Comment by ThelonTV** [comment] 2020-03-18 11:51
> This one doesn't seem that bad considering only monkeys can do it right?

Well you could have something like a melee and ranged weapon equipped at the same time while still being stealthed... would save you a few seconds where you usually had to change it with something in your backpack. Also mutadone and access to become a monkey aren't that rare for a geneticist/medbay tator

**Comment by ATH1909** [comment] 2020-03-19 00:31
What happens if you turn back into a human?

**Comment by ThelonTV** [comment] 2020-03-19 11:32
Your plant sprite falls over, disappears and the monkey to human animation starts playing, leaving you with a human sprite again.

**Comment by dragomagol** [comment] 2021-01-21 18:10
Still an issue post-monkey refactor

**Comment by robbertapir** [comment] 2022-04-09 13:47
Fixed by  #56329.

**Comment by Sealed101** [comment] 2023-02-28 19:00
monkeys can not in fact pick up potted plants or other items that force you to wield them with both hands

**Closed by Sealed101** 2023-02-28 19:00 UTC
Labels: In Game Exploit, Bug
