### ISSUE TITLE
Glass tiles render pipes on TOP of them instead of under

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#63263] opened 2021-12-05 05:15 UTC
Reporting client version: 514.1557

## Round ID:
NaN (Easy as fuck to reproduce anyway)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:

Reinforced Glass tiles are a thing now! 
They come with a new design for normal glass tiles that looks less awful!

Great!

But you know what isn't great?

Whatever this is 
![image](https://user-images.githubusercontent.com/14065903/144734563-0ed17df0-91d5-49d9-a9cc-166a12815a0a.png)

According to coders, this is how glass tiles have always been, but mappers just never put pipes and wires under glass tiles, but now users can do that so it should probably be fixed. 

I'm not a coder, but I would wager that they should use whatever technique that the catwalk tiles use?

**Comment by timothymtorres** [comment] 2021-12-05 15:06
So I'm addressing some MultiZ transparency issues in https://github.com/tgstation/tgstation/pull/62875 however pipes/wires/etc. were never intended to be hidden with transparent tiles.  Mappers normally use other tiles when they need to place something under the floor and avoid overlapping them with glass tiles.

Making glass floors behave like catwalks still wouldn't make any sense.  The tile is supposed to be transparent! Even if you did have them underneath the glass floors, it would cause confusion if the pipes were the bottom z level pipes or the current z level ones.

I'm marking this as `Not a bug` since this is intended behavior.

**Closed** 2021-12-07 17:33 UTC
Labels: Not a bug
