### ISSUE TITLE
Various lavaland (and probably space) ruins have tiles exposed to space roundstart after #32860

### ISSUE THREAD

**Issue by deathride58** [tgstation/tgstation#32990] opened 2017-11-22 04:17 UTC
Title. Thought this was a downstream issue for a little while until i actually checked the files in question and saw no diffs.

https://i.imgur.com/WYyeyFl.png screenshot from some dude on Citadel's discord, the file for the ruin downstream matches upstream. cba to hunt down all of the mapping issues introduced by #32860 

The ruins are fucked. Fix em

**Comment by WJohn** [comment] 2017-11-22 08:03
Dupe of #27719

This has been around for a while.

**Comment by deathride58** [comment] 2017-11-22 19:34
This is not a dupe of #27719

This is an issue caused by #32860, a look at the files for the ruins themselves show that they have /turf/open/space/basic tiles in places they shouldn't.

**Comment by ShizCalev** [comment] 2017-11-22 19:35
Not a dupe.

**Comment by WJohn** [comment] 2017-11-23 00:23
Oh! I did not see the space tiles under the tables there. I noticed the lava tile which is another issue.

**Comment by WJohn** [comment] 2018-01-10 11:11
This apparently has cropped back up again? I've been getting players talking about this, but I haven't seen it myself.

**Comment by WJohn** [comment] 2018-01-10 16:39
Oh, mistook this issue for another one, nevermind this one.

**Closed by WJohn** 2018-01-10 16:39 UTC
Labels: Map Issue
