### ISSUE TITLE
Engi cyborg's multitool is not considered a multitool by telecom machines

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#83260] opened 2024-05-16 03:45 UTC
Reporting client version: 515.1636

## Issue Summary
The engineering cyborg's multitool in the omni-tool does not appear to be considered a multitool when trying to link telecom machinery, despite having it held and active.
![image](https://github.com/tgstation/tgstation/assets/85206687/b38a9d94-6ff8-4335-bf57-18eee4b27c21)
![image](https://github.com/tgstation/tgstation/assets/85206687/b35519b2-bd85-4f83-8550-daf26c10aada)
^ There should be a bar that pops up when a multitool is held, which allows you to save things to the multitool's buffer.

## Round ID:
[228939](https://scrubby.melonmesa.com/round/228939)

## Testmerges:
- [Updates to orbit ui](https://www.github.com/tgstation/tgstation/pull/83186)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [lavaland raptors](https://www.github.com/tgstation/tgstation/pull/82537)

## Reproduction:
1. Become an engineering cyborg.
2. Find telecom machinery
3. Activate the multitool on your omni-tools.
4. Interact with the telecom machinery
5. No multitool related options appear.

**Comment by SyncIt21** [comment] 2024-05-16 06:06
Duplicate #83077 , as in no machine recognizes it as a multitool

**Comment by ShizCalev** [comment] 2024-05-18 01:07
Duplicate of #83077

**Closed by ShizCalev** 2024-05-18 01:07 UTC
