### ISSUE TITLE
GPS Directional Pointer only pointing North, not towards signal

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#75326] opened 2023-05-10 06:20 UTC
Reporting client version: 514.1589

## Round ID:
[205409](https://scrubby.melonmesa.com/round/205409)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)

## Reproduction: Get a GPS, view signals. move around and notice they only point north (upwards) instead of towards their signal

![image](https://github.com/tgstation/tgstation/assets/52526271/9d118fd0-67c9-4a7b-b38f-946e0c8f28e8)

**Comment by dragomagol** [comment] 2023-05-10 06:26
Duplicate of #75264

**Closed by dragomagol** 2023-05-10 06:26 UTC
