### ISSUE TITLE
Engiborgs can't add circuits without going into combat mode

### ISSUE THREAD

**Issue by combustor** [tgstation/tgstation#82814] opened 2024-04-22 02:00 UTC
## Issue Summary
If you try to add a circuit to a machine frame without using combat mode you'll get a "can't add that" notification
## Round ID:
Every round

## Reproduction:
Be an engiborg, try to add a circuit to a machine frame and fail, use combat mode to add it.

**Comment by MrMelbert** [comment] 2024-04-22 02:05
Dupe of #82774

**Closed by MrMelbert** 2024-04-22 02:05 UTC
