### ISSUE TITLE
Lich glitch

### ISSUE THREAD

**Issue by sirnat** [tgstation/tgstation#29722] opened 2017-08-04 23:43 UTC
Round ID: 74268

What happened: 
I was a lich wizard, got killed and waited to respawn, when I did respawn I didn't have any of my spells which included: Fireball, jaunt, and magic missle. 

Had my round ruined by this bug and hope a solution can be found, or if it can be explained why it happened.

**Comment by ShizCalev** [comment] 2017-08-04 23:45
How did you die?

**Comment by sirnat** [comment] 2017-08-04 23:48
Got gangbanged but they didnt incin my body. I still respawned at the ensouled object

**Comment by BeeSting12** [comment] 2017-08-05 00:54
hey dat rhymes!

**Comment by MimicFaux** [comment] 2017-08-05 03:57
I've had this happen to me. Lost my spells the first time (was incin'd) was given a second spellbook by admins, subsequent deaths I remembered my spells through death

**Comment by AnturK** [comment] 2017-08-09 07:07
Duplicate of #28846

**Closed by AnturK** 2017-08-09 07:07 UTC
