### ISSUE TITLE
not one camera does not work (on the map metastation)

### ISSUE THREAD

**Issue by Foteboup** [tgstation/tgstation#80742] opened 2024-01-03 00:23 UTC
not one camera does not work (on the map metastation)

here are some screenshots
https://ibb.co/YtGnv24
https://ibb.co/ynh49DD

maybe it's because of some kind of setting?

**Comment by JohnFulpWillard** [comment] 2024-01-03 00:23
Duplicate of https://github.com/tgstation/tgstation/issues/79954

**Closed by JohnFulpWillard** 2024-01-03 00:23 UTC
