### ISSUE TITLE
Making Reinforced plasma glass sometimes makes a zero sheet stack of Plastitanium glass beneath said stack

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#44534] opened 2019-06-15 05:01 UTC
Issue reported from  Round ID: 110626 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Making Reinforced plasma glass sometimes makes a zero sheet stack of Plastitanium glass beneath said stack. Did this at the orm. made 37 sheets of reinforced plasma glass, as well as a single 0 sheet stack of plastitanium glass. Said sheet could not be used to make anything, and disappeared when alt clicked, though could be held, thrown, and examined.

**Comment by AnturK** [comment] 2021-08-10 09:39
Duplicate of #60340

**Closed by AnturK** 2021-08-10 09:39 UTC
Labels: Bug
