### ISSUE TITLE
Smoker quirk is still broken

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#57949] opened 2021-03-25 19:51 UTC
## Round ID: [158936](https://scrubby.melonmesa.com/round/158936)

I rolled smoker quirk on hardcore random as plasmaman. Injecting myself with grounded cigarettes didnt do anything to quench my addiction at all. I had to constantly manage my mood because smoker is still broken
![image](https://user-images.githubusercontent.com/7501474/112535267-5ed76d80-8dac-11eb-803c-6dc4902ad047.png)

**Comment by dragomagol** [comment] 2021-03-30 01:38
Duplicate of #57739

**Closed by dragomagol** 2021-03-30 01:38 UTC

**Comment by Farquaar** [comment] 2021-04-10 23:16
I think smoker is still pretty broken
You have to have a cigarette in your face all the time to not get jitters
Smokers regularly smoke themselves to death because of this.

**Comment by Time-Green** [comment] 2021-04-11 06:57
I have a PR up right now that fixes a lot of issues, but capping lung damage might be a good idea
