### ISSUE TITLE
engineering scanner goggles have different lighting when you toggle them off meson vision for the first time

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#29589] opened 2017-07-31 01:17 UTC
1. put on engi goggles, enjoy seeing through walls but still being able to see lighting level
2. toggle engi goggles to t-ray mode
3. turn goggles back to meson mode, observe mysterious lack of lighting

**Comment by PraiseRatvar** [comment] 2017-07-31 06:07
they have normal/old meson lighting when you do this

**Comment by ShizCalev** [comment] 2017-08-01 04:39
Dupe #28296

**Comment by ShizCalev** [comment] 2017-10-03 18:01
Duplicate of #26918

**Closed by ShizCalev** 2017-10-03 18:01 UTC
