### ISSUE TITLE
Spectral Blades are still fucked

### ISSUE THREAD

**Issue by Kingtrin** [tgstation/tgstation#47302] opened 2019-10-22 07:54 UTC
## Reproduction: Orbit spectral blade, get yoinked back upon trying to fly away or orbiting something else.

This apparently was reported some months earlier but wasn't nailed down. I'd like to further add that it isn't just orbiting thats broken. The blade itself did zero damage with 10+ ghosts orbiting. This was even with the blade having a +5 modifier from event wizard memes. Each strike said it had 0 vengeful spirits despite most of dchat orbiting them. Getting yoinked back did not put you into the orbit animation, but rather forced your icon on top of them. The blade changed owners and the orbit followed the blade and not the previous owner.

**Comment by AnonymousNow** [comment] 2019-10-22 08:05
Can confirm, was a ghost in this round orbiting the blade.

**Comment by carshalash** [comment] 2019-10-22 11:27
![image](https://user-images.githubusercontent.com/16896032/67281400-a4866b80-f512-11e9-9a70-d481d2ec3f5f.png)
Fun photo evidence. Cringe ass nae nae sword.

**Comment by kriskog** [comment] 2019-10-22 13:08
Closing #34135 in favor of this one.

**Comment by Tlaltecuhtli** [comment] 2019-10-22 17:23
is there any opposition on full removal of this item? 
- it gets thrown away every time someone gets it from summon/megafauana because it sucks
- its buggy

**Comment by ATH1909** [comment] 2019-10-22 17:41
> is there any opposition on full removal of this item?
> 
> * it gets thrown away every time someone gets it from summon/megafauana because it sucks
> * its buggy

I'd prefer fixing it and then making it an admin-only item (so people can still TC trade for it and such), but yeah, it is a bottom-tier magic item.

**Comment by TheVekter** [comment] 2019-10-23 03:50
> is there any opposition on full removal of this item?
> 
> * it gets thrown away every time someone gets it from summon/megafauana because it sucks
> * its buggy

Refactor, don't remove. People toss it because it sucks because it doesn't work correctly. It just needs fixing. Can't promise I'm the man to do it, but I'll look at it.

**Comment by Kaffe-work** [comment] 2019-10-24 20:08
It would not be tossed if it worked as intended, because if it works it's actually one of the stronger powergame loot.

**Closed** 2019-10-25 09:35 UTC
Labels: Bug
