### ISSUE TITLE
Holoparsite dies when its host gets turned into ash drake and then to something else

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#60994] opened 2021-08-22 20:41 UTC
## Testmerges:
#60961: 'Enable strictNullChecks on tgui' by Mothblocks at commit 93b42c5d48

## Reproduction: 
1: Give a man a stand.
2.Turn them into assdrake
3.turn them back
4.Holopara get ghosted
I think this was reported back when dragon blood could give you lesser ass drake transformation?

**Comment by timothymtorres** [comment] 2021-08-23 13:55
Duplicate of #59127

**Comment by timothymtorres** [comment] 2021-08-23 13:55
It seems that there are over half a dozen of these types of bugs in regards to polymorphing and edge cases.  I think it all needs to be refactored into one proc

**Closed by timothymtorres** 2021-08-23 13:55 UTC
