### ISSUE TITLE
Shuttle transit space sprites

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#24461] opened 2017-02-26 13:22 UTC
For some reason the shuttle transit sprites were bugged and appeared static.

![obraz](https://cloud.githubusercontent.com/assets/12747768/23340019/e4b7c576-fc2e-11e6-84e9-16153fe8a3bf.png)

**Comment by lzimann** [comment] 2017-02-26 14:29
Dupe of #24457

**Closed by lzimann** 2017-02-26 14:29 UTC
Labels: Bug
