### ISSUE TITLE
Shapeshifting into a drake whilst in a mech will cause you to become stuck even after shapeshifting back.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#54817] opened 2020-11-05 11:14 UTC
## Round ID:
//////

## Testmerges:
//////

## Reproduction:
Hop inside a mech (ripley for example) and decide to unleash your inner drake as a miner.
Become a drake and... get stuck inside the mech.
Regret that instantly and turn back into a human then find out you are still stuck.

With the exceptionally small amount of testing I've done, even destroying the mech will do nothing and they'll remain invisible stuck in whatever state they're in.

**Comment by brotherbeyondd** [comment] 2020-11-06 14:36
breaking the mech kills you and you teleport to the crystal no no room

**Comment by timothymtorres** [comment] 2021-08-19 16:13
Duplicate of #54817

I'm aware that both effects are slightly different but they both come from the same source.  Any kind of polymorph effects while in a mech leads to bad things happening.

**Closed by timothymtorres** 2021-08-19 16:13 UTC
Labels: Bug

**Comment by timothymtorres** [comment] 2021-08-19 16:15
I'm aware that both effects are slightly different but they both come from the same source.  Any kind of polymorph effects while in a mech leads to bad things happening.

**Comment by Sealed101** [comment] 2022-09-18 13:12
probably meant to mark it as dupe of #55153
