### ISSUE TITLE
Modkits for the Kinetic Accelerator can be duplicated with moderate ping

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#59334] opened 2021-05-26 21:52 UTC
Reporting client version: 513.1542

## Round ID:
[162973](https://scrubby.melonmesa.com/round/162973)

## Testmerges:
- [Turns lighting objects into a datum, makes all lighting be performed with an underlay. big maptick fix very good!](https://www.github.com/tgstation/tgstation/pull/58991)

## Reproduction:
Have around 90+ Ping
Put Kinetic Accelerator Modkit on the ground (Cooldown, Damage, Even Lifesteal Crystal works)
Have Kinetic Accelerator In mainhand
Spam click the Modkit on the ground
Modkit will be applied multiple times to the Kinetic Accelerator.
Video: https://www.youtube.com/watch?v=UC4Gs4_2DAM

**Comment by dragomagol** [comment] 2021-05-27 17:27
Duplicate of #50742

**Closed by dragomagol** 2021-05-27 17:27 UTC
