### ISSUE TITLE
cryo tubes are absolutely broken in nearly every way

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#80983] opened 2024-01-16 23:46 UTC
## Issue Summary
Cryotube cannot have beaker inserted into it. (probably can't have it removed either)
Cryotube cannot be crowbarred open without power
Cryotube cannot be deconstructed

## Round ID:
[222299](https://scrubby.melonmesa.com/round/222299)

## Testmerges:
https://github.com/tgstation/tgstation/pull/80887
https://github.com/tgstation/tgstation/pull/80941

## Reproduction:
All it takes to reproduce is try to actually log in and attempt to use it for its intended purpose!

**Comment by Deadgebert** [comment] 2024-01-16 23:47
https://github.com/tgstation/tgstation/pull/80873
likely related to this!

**Comment by Ghommie** [comment] 2024-01-17 01:57
I couldn't replicate it on a local server on the latest commit, though there are a few runtimes with the radio messages. I'll perhaps take a look at the live servers later.

**Comment by SyncIt21** [comment] 2024-01-17 03:25
The radio runtimes are fixed by #80980.

As for my cryo PR something is weird. No downstream server has reflected my PR, it does not even show up in their PR tracker.

So even though my PR is merged here, it isn't merged anywhere downstream so none my fixes were applied there

**Comment by FlufflesTheDog** [comment] 2024-01-17 06:56
Right, so.
I hate this.
It _is_ caused by #80873. Sorta.
(The scrubby/statbus link shows the [commit hash](https://github.com/tgstation/tgstation/commit/9435242acbb4189065f2a0ccffb9e63f1b87697d), which is dated post cryo pr)
Probably more important though is this
https://github.com/tgstation/tgstation/blob/99ca34da10dd3f8b20c44c6318cdff60e14a1680/code/_onclick/click.dm#L184-L194
The issue was filed on, and only seems applicable to, delta station. Delta station has windows to the right of the cryo pods, windows prevent clicking anything under them, and for some reason `get_turf_pixel` thinks that cryo pods are one tile further to the right than they actually are.
Wasn't applicable before now because cryo pods were previously layered above windows.

I don't know what a reasonable fix would be so I'm not currently planning on fixing it myself, just sharing info.

**Closed** 2024-07-11 00:28 UTC
Labels: Bug
