### ISSUE TITLE
It is possible to render the server inoperable with 4 sheets of iron

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#88778] opened 2024-12-28 17:39 UTC
### Client Version:

idk

### Issue Summary:

You can place a wall in the holodeck (apparently when something is selected) then select something else to make the server inoperable

### Reproduction Steps:

1. Set holodeck to whatever
2. make wall
3. Set to whatever
4. profit

**Comment by MrMelbert** [comment] 2024-12-28 20:30
Dupe of #81601

**Closed by MrMelbert** 2024-12-28 20:30 UTC

**Comment by mc-oofert** [comment] 2024-12-28 21:20
How is this not fixed yet it takes like 2 minutes from round start to make the server not functional until a key holder fixes it

**Comment by MrMelbert** [comment] 2024-12-29 07:23
Because you'd get nuked from orbit if caught
