### ISSUE TITLE
Breeze Bay fishing bitrunning sim is missing several important items, such as fish

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79514] opened 2023-11-04 07:05 UTC
Reporting client version: 514.1589

## Round ID:
[218109](https://scrubby.melonmesa.com/round/218109)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Bitrunning content patch: Antag rework (READY)](https://www.github.com/tgstation/tgstation/pull/78997)

## Reproduction:
The Breeze Bay bitrunning sim spawns you in a small staging area surrounded by space. Was unable to check the entire map to see if it was just not placed in the fishing area properly as there were no space suits in the staging area.

![Screenshot 2023-11-04 020311](https://github.com/tgstation/tgstation/assets/88996803/d6a12cf3-2e34-47a3-8faf-ad16d75db394)

**Comment by jlsnow301** [comment] 2023-11-04 21:55
Definitely a runtime somewhere. This should be fixed in the content patch

**Comment by jlsnow301** [comment] 2023-11-04 22:31
Merge artifact - runtime caused by loading an area which was renamed

**Closed** 2023-11-05 21:31 UTC
Labels: Test Merge Bug
