### ISSUE TITLE
Emergency Energy Shields from breach shield projectors get pushed around by external shuttle movement

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76265] opened 2023-06-22 23:03 UTC
Reporting client version: 514.1589

## Round ID:
[208887](https://scrubby.melonmesa.com/round/208887)

## Reproduction:
Those shield pieces from the anti-breach shield projectors get pushed around when outside of the shuttle, so they end up flying off or getting caught on things.
1. Get on the emergency shuttle and launch.
2. Wrench, and activate one of the anti-breach shield projectors.
3. Observe the shields outside of the shuttle.
4. Watch as they fly off.

**Comment by Sealed101** [comment] 2023-06-22 23:13
Duplicate of #76172

**Comment by Sealed101** [comment] 2023-06-22 23:14
wow, the dupe marking has worked for once

**Closed by Sealed101** 2023-06-22 23:14 UTC
