### ISSUE TITLE
Shuttle Insurance can trigger after the shuttle has arrived

### ISSUE THREAD

**Issue by miniusAreas** [tgstation/tgstation#70839] opened 2022-10-27 19:29 UTC
![reported-from-downstream](https://user-images.githubusercontent.com/39163353/198381160-f0aa7fc4-4f2d-486f-8b33-44a1965e2ad1.svg)

## Testmerges:
Reported from Downstream
## Reproduction:
Call shuttle.
Shuttle arrives.
Put people in the shuttle.
Trigger shuttle insurance (the one that, forcibly replaces your shuttle with a different one) while the shuttle is still docked.

Watch an entire Skyrat shifts worth of 80-90 people get qdel, including the AI core eye, in the blink of a fuckin eye.

chaos ensures. This appears to be an oversight in the event code.

**Comment by newfren** [comment] 2022-10-28 00:24
that's so fucking funny

**Comment by LarissaMayrink** [comment] 2022-10-28 00:54
I think its fine because shuttle insurance is not actually insurance. If you've ever read the messages its clear its pirates asking for protection money

**Comment by msgerbs** [comment] 2022-10-28 18:23
Stop breaking shuttles!

Also I'm like 99% sure I verified this can't happen when I was fucking with the BYOS shuttle and midround shuttle purchasing so yeah would love to see this repro'd.

**Comment by LemonInTheDark** [comment] 2022-10-28 18:31
If you can't replicate it upstream, do not report it upstream. especially because your logs are not public
I want to close this so bad

**Comment by msgerbs** [comment] 2022-10-28 19:51
WTF it does happen. Why does this happen?!

**Comment by msgerbs** [comment] 2022-10-28 19:58
Events don't run their checks when spawned by an admin, that is intentional and documented behavior. Has this happened outside of adminbus?

**Comment by Sadboysuss** [comment] 2024-06-24 20:46
looks like this can't be reproduced on the latest /tg/ master

**Comment by msgerbs** [comment] 2024-06-24 20:48
Pretty sure when I dug into this I only ever found it happened with adminbus. So I'm just going to call this Not A Bug. Remember kids, be careful with adminbus.

**Closed by msgerbs** 2024-06-24 20:48 UTC
Labels: Not a bug, Oversight, Cleanup Flagged
