### ISSUE TITLE
Hand teleporters do not function anymore +more.

### ISSUE THREAD

**Issue by Isy232** [tgstation/tgstation#41734] opened 2018-11-30 04:18 UTC
I dont have the time for format, because I need to sleep soon, but here is the issue.

I was trying to use a hand tele, and everything worked like normal, the portal opened to the target correctly, but I could not go through the portal. The portal still creates the spark effect when you try to go through it, but you are not teleported.

Additionally, in the changelog it was noted that:
"Quantum, wormhole and magic teleportation is no longer disrupted by bags of  holding."
However, it still is.

I am kind of pissed because both of these together ruined my greentext.
Someone had emagged the escape shuttle, but I already put a beacon on the pod, so I calibrated the teleporter to the pod and hopped in still wearing my bag of holding, as I had seen this change. Then I was teleported out into space, no problem, I have a hand tele I can use ........ wait ..... oh fuck it isnt working.

**Comment by XDTM** [comment] 2018-11-30 07:47
Hand teles are bugged, but the teleporter is bluespace-based, so the disruption is intended. Quantum teleportation is from quantum pads, wormhole is from wormholes like jaunters or anomalies, and magic is from wizards/cult/lavaland stuff.

**Comment by Jalleo** [comment] 2018-11-30 16:37
Wasnt there a change to prevent teleporting to a escaping shuttle/pod? If so it might of been blocked elsewhere somehow.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-11-30 19:05
Dupe of #41723

**Closed by ExcessiveUseOfCobblestone** 2018-11-30 19:05 UTC
Labels: Bug

**Comment by YakumoChen** [comment] 2018-12-09 06:16
Teleporting to a shuttle has always been a thing though
