### ISSUE TITLE
Random rivet wall on lavaland.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#23979] opened 2017-02-11 21:00 UTC
![](http://i.imgur.com/sR6Byjp.png)

Why?

Coords (x,y,z) are 37, 42, 5.

**Comment by jughu** [comment] 2017-02-11 21:06
This was when lavaland was implemented and only now you notice it?

**Comment by WJohn** [comment] 2017-02-11 21:30
No I knew this was something for a while, I think I just kept ignoring it as a "whatever". It'd be super quick and easy to fix.

**Comment by KorPhaeron** [comment] 2017-02-11 21:31
This is a dupe and also like 6 months old

**Comment by coiax** [comment] 2017-02-11 21:46
I think there used to be a pickaxe embedded in it.

**Comment by jughu** [comment] 2017-02-11 21:47
That was auctaly a bug

**Comment by Arianya** [comment] 2017-02-11 23:00
Can we stop saying "this issue is a dupe!" without linking to the issue it is a dupe of? Its really aggravating spending 15 minutes trying to find the magic combination of keywords that pops up the issue you're talking about, and if you have time to type "This is a dupe" you can just as easily type "This is a dupe _of #19399 _" or whatever

That's the only issue I can find that's tangentially related to this wall, and even then that one is about it being ash-storm excluded, not about the random rivet wall itself.

Is there any reason for the rivet wall or can it be removed without concern?

**Comment by KorPhaeron** [comment] 2017-02-11 23:29
It somehow ended up there when Joan or Xhuis was redoing the necropolis area it's fine if you remove it but I've grown vaguely attached to it

**Comment by coiax** [comment] 2017-02-12 00:36
I should see if it's possible to make soapstones usable on static parts of lavaland and Centcom. This clearly needs some sort of engraving.

**Comment by PKPenguin321** [comment] 2017-02-12 01:13
>Can we stop saying "this issue is a dupe!" without linking to the issue it is a dupe of? Its really aggravating spending 15 minutes trying to find the magic combination of keywords that pops up the issue you're talking about

your second sentence is the reason for the first sentence

**Comment by xxalpha** [comment] 2017-02-12 01:40
It's not our job to search for the dupe, we point out it's a dupe because we remember similar issues from having no life and browsing this place too much.

**Comment by jughu** [comment] 2017-02-12 02:24
You wouldnt take something away what kor grown attached to it would you?

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-02-14 02:25
Quick make lore for it!

**Comment by Arianya** [comment] 2017-02-14 18:47
Sorry a maintainer has asked for it to be removed no lore is good enough now :^)

**Closed** 2017-02-16 20:41 UTC
Labels: Easy Fix, Lavaland, Map Issue
