### ISSUE TITLE
Mech Transport mechs can show up on the Exosuit control console.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#23487] opened 2017-01-30 05:19 UTC
![](https://file.house/dpBS.png)

**Comment by jughu** [comment] 2017-01-30 08:44
@francinum are you sure a area wasnt called like that and which map?

**Comment by Haevacht** [comment] 2017-01-30 10:34
I'm more intrested in that airtank reading, that's either a shitton of air or fuckall and I don;t know enough advanced math to know which.

**Comment by GunHog** [comment] 2017-01-30 13:11
It is using a negative in the scientific notation, it can also be read as: `1.26676 * 10^-6` . It is a tiny value, so the tank is essentially empty. This is not a bug with the console. These mechs are spawned with tracking beacons, which are visible on the RD's console. 

If the mechs are not intended to be visible from the console, then simply remove the tracking beacon from those mechs.

**Comment by Bawhoppen** [comment] 2021-06-29 00:37
In the interest of closing this issue, as the ruin's creator, I'll just say this was intended all along.

**Comment by JohnFulpWillard** [comment] 2021-07-15 03:06
> 
> 
> In the interest of closing this issue, as the ruin's creator, I'll just say this was intended all along.

What a plot twist

**Comment by coiax** [comment] 2021-07-15 07:28
> 
> 
> In the interest of closing this issue, as the ruin's creator, I'll just say this was intended all along.

Intended behaviour.

**Closed by coiax** 2021-07-15 07:28 UTC
Labels: Bug
