### ISSUE TITLE
Placing the white ship on top of itself causes it to collide with itself and land in the shuttle transit z-level

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#43694] opened 2019-04-24 20:08 UTC
Issue reported from  Round ID: 106840 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1447

1. Place white ship somewhere with the camera console and go to that location
2. Once there, move it a tile or two and place it again
3. Send the ship to the new location and watch as it lands on top of itself, gibbing anyone inside and rendering the white ship unusable.
![image](https://user-images.githubusercontent.com/46329759/56682969-a7ef8600-669a-11e9-877c-22fc8d6cece7.png)

**Comment by ATH1909** [comment] 2019-04-24 20:54
Is there a way to avoid the gibbing and remain on the shuttle transit z-level?

**Comment by LegendaryMister151** [comment] 2019-04-24 21:50
Seems like leaving enough room for the cockpit allows for you and the shuttle computers to survive on the shuttle transit z-level

**Comment by ATH1909** [comment] 2019-04-25 10:49
> Seems like leaving enough room for the cockpit allows for you and the shuttle computers to survive on the shuttle transit z-level

Is there anything you can do from there?

If one of your has a teleporter beacon, can you teleport the nuke disk into the "crashed" shuttle (and then throw away the beacon so that the ops can't teleport after you)?

**Comment by AzureWildfire** [comment] 2019-04-25 14:02
Ok, this happend to me once but I thought it didn't gib, I thought it worked like the "build your own shuttle" that doesn't gib, but at the same it also technically lands on it self and doesn't break like this.

**Comment by AzureWildfire** [comment] 2019-04-25 14:02
Oh and also, this is not only a problem with the withe shuttle, it happens with any shuttle with custom landing

**Comment by Dennok** [comment] 2019-06-19 09:47
As i say before, problem in placing shuttle dock marker on the shuttle and moving it with the shuttle in transit and when it landing it lands on himself on transit.

**Comment by dragomagol** [comment] 2020-11-01 22:14
Duplicate of #39906 #44389 #40797 #50097

**Closed by dragomagol** 2020-11-01 22:14 UTC
Labels: Bug, In Game Exploit
