### ISSUE TITLE
things that arent even keybinds get spammed on every time i join game

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56373] opened 2021-01-23 13:51 UTC
![a](https://i.imgur.com/Ow2fRBv.png)

**Comment by RaveRadbury** [comment] 2021-01-24 02:58
Those *are* keybindable emotes now. They are for AI displays. Closing this in favor of #56382 as it's more descriptive of the issue.

**Comment by RaveRadbury** [comment] 2021-01-24 02:58
Duplicate of #56382

**Closed by RaveRadbury** 2021-01-24 02:58 UTC
