### ISSUE TITLE
(Bar) Restaurant portal bot bug

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [tgstation/tgstation#60318] opened 2021-07-19 08:09 UTC
## Reproduction: Over the course of the two hour or so long round, I've ran into an issue with the restaurant portal bots in the Ice Box bar (and perhaps the bars on other maps) where I noticed that certain bots do not actually leave a tip after being served the drink they requested. So far, the only bots to do so that I've noticed are British bots that request an Ale.

**Comment by DAKKA-WAAAGH** [comment] 2021-07-20 18:07
I've tested a few bartender rounds since then and it is definitely British bots that request Ale.

**Comment by StoneMason** [comment] 2021-07-20 19:32
Not many people tip in the UK anyway, I see this as incredible attention to detail :)

**Comment by JohnFulpWillard** [comment] 2021-07-21 01:39
Some foods/drinks dont have a price tag attached to them, so the bots just don't give anything.

**Comment by timothymtorres** [comment] 2021-08-22 12:25
So I code dived and all I found was this:

https://github.com/tgstation/tgstation/blob/92dc123c02121d960f190ba18382b249f30872ea/code/modules/food_and_drinks/restaurant/customers/_customer.dm#L1-L5

And there are like several different files for bot interactions, AI systems, scattered all over the place.

https://github.com/tgstation/tgstation/tree/master/code/datums/ai/robot_customer
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/friendly/robot_customer.dm
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/restaurant.dm
https://github.com/tgstation/tgstation/tree/master/code/modules/food_and_drinks/restaurant

**Comment by atosti** [comment] 2023-03-15 22:06
I attempted to reproduce this in the latest build (commit 4e94c6d0594a8061dc0b41e98c177fc9acfaa338) and it looks like this is now fixed. My tests showed British bots consistently paying 20 creds for their Ale. I tested this on both Ice Box and Meta stations. 

Additionally, to make the testing process faster, I commented out lines 400 through 406 in `_customer.dm`, so that British bots would only ever order Ale.

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/food_and_drinks/restaurant/customers/_customer.dm#L398-L408

Can someone confirm whether this is now fixed and if this issue can be closed?

**Comment by Sealed101** [comment] 2024-08-24 11:43
the ale order was fixed back in #63651
however there are still several items that are missing pricings, such as
- _Gin Garden_ drink
- _chawanmushi_
- _fish poke_
- _meat poke_
- _Cuban nachos_
- _grilled cheese sandwich_
- _Spray Tan_ reagent
- _Strong Basic Buffer_ reagent
- _Strong Acidic Buffer_ reagent

should be trivial enough to set those prices, but implementing a unit test to check for them to always exist on a potential order item in the future would be good

**Closed** 2024-09-28 02:22 UTC
Labels: Bug, Oversight
