### ISSUE TITLE
the berserk hardsuit with a crusher will cause megafauna killed with berserk enabled to not drop their crusher trophy

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#76212] opened 2023-06-21 10:44 UTC

**Comment by Sealed101** [comment] 2023-06-21 20:18
can't reproduce on local
the berserker suit grants no extra damage or anything that would otherwise deal non-crusher damage to the fauna, too

**Comment by Sealed101** [comment] 2023-06-21 20:25
judging by the logs you were fighting a BDM. i'm assuming you've just clicked on the tile he was on too fast and the trophy got attached without you noticing, because after that battle you gain stun absorption from `blooddrunk`
![изображение](https://github.com/tgstation/tgstation/assets/75863639/52dd07a9-f0ac-4000-8e3d-283d427b9021)

closing now, try examining the crusher next time

**Closed by Sealed101** 2023-06-21 20:25 UTC
Labels: Needs Reproducing

**Comment by Serxule** [comment] 2023-06-22 09:32
> judging by the logs you were fighting a BDM. i'm assuming you've just clicked on the tile he was on too fast and the trophy got attached without you noticing, because after that battle you gain stun absorption from `blooddrunk` ![изображение](https://user-images.githubusercontent.com/75863639/247737056-52dd07a9-f0ac-4000-8e3d-283d427b9021.png)
> 
> closing now, try examining the crusher next time

huh, didnt know you can attach by clicking the trophy

**Comment by Sealed101** [comment] 2023-06-22 10:21
the more you kno'
