### ISSUE TITLE
Pipes and Pumps do not show ontop of walls but can be interacted with anyway (Wallening)

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85749] opened 2024-08-10 23:48 UTC
Reporting client version: 515.1641

## Issue Summary
![pipesinwallsdontshow](https://github.com/user-attachments/assets/4dbcfcba-397e-4f81-b867-fd615abe9740)

Pipes inside of walls, whether straight or pumps do not show, even though you can select and interact with them with alt. Old walls would let you look at pumps and pines that were sitting ontop of walls, and given that you can still alt menu interact I believe this was unintended.

## Round ID:
[234433](https://scrubby.melonmesa.com/round/234433)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Put a pump down, place a wall onto of it, then press alt. Notice how despite not being able to see the pump you can still interact with it.

**Comment by Sadboysuss** [comment] 2024-08-10 23:52
Dupe of https://github.com/tgstation/tgstation/issues/85701

**Comment by SmArtKar** [comment] 2024-08-11 03:41
Closing as a dupe

**Closed by SmArtKar** 2024-08-11 03:41 UTC
