### ISSUE TITLE
raw prophet mansus link doesn't handle apostrophes well

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#76238] opened 2023-06-22 01:04 UTC
Reporting client version: 514.1589

## Round ID:
[208742](https://scrubby.melonmesa.com/round/208742)

## Testmerges:
- [Build Mode Preview + better help text](https://www.github.com/tgstation/tgstation/pull/76095)
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Pirate expansion round 2: Adds Ethereal pirates](https://www.github.com/tgstation/tgstation/pull/76128)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/2679e398-36c8-464c-8567-16310879d07c)

**Comment by MrMelbert** [comment] 2023-06-22 01:27
Dupe of #71991

**Closed by MrMelbert** 2023-06-22 01:27 UTC
