### ISSUE TITLE
Spessmen and some chairs appear over the electropack-helmet part

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#77098] opened 2023-07-25 16:26 UTC
![obraz](https://github.com/tgstation/tgstation/assets/68878861/50e5f7c0-6ec1-4e96-b397-1fc13414deab)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/c9279c5b-d067-4678-91fb-5554175c0a4b)
Relatively minor issue, but this did not use to happen.

## Round ID:
[211009](https://scrubby.melonmesa.com/round/211009)

## Testmerges:
null

## Reproduction:
Grab something that falls under "armor/helmet", grab an electropack,
Combine the two. Put on a chair.

**Comment by Sealed101** [comment] 2024-10-19 13:12
fixed by https://github.com/tgstation/tgstation/pull/87228
also what the hell dude imagine opening a duplicate of an issue that you opened yourself
#87221

**Closed by Sealed101** 2024-10-19 13:12 UTC
Labels: Sprites, Bug
