### ISSUE TITLE
TG UI is showing up weirdly

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#51486] opened 2020-06-07 04:51 UTC
Issue reported from  Round ID: [138956](https://scrubby.melonmesa.com/round/138956) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507

TG UI broke
![image](https://user-images.githubusercontent.com/24631139/83960648-9cbae200-a8bd-11ea-86e4-b02a03f3947d.png)

**Comment by stylemistake** [comment] 2020-07-16 19:30
Duplicate of #50480

**Closed by stylemistake** 2020-07-16 19:30 UTC
Labels: UI
