### ISSUE TITLE
Rack kicking while lying down ruins immulsion

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12008] opened 2015-09-25 08:36 UTC
https://www.youtube.com/watch?v=3Jmkt0HWZcc

**Comment by GunHog** [comment] 2015-09-25 13:01
The immersion breaking seems to be more of the character's direction, rather than lying. If the character's feet were facing the rack, it would be plausible for him to still kick things, but a direction check would be silly. So yes, fix it.

**Comment by freerealestate** [comment] 2015-09-25 14:36
Can't interact with anything else lying down, which is why it was labelled a consistency issue

**Comment by PKPenguin321** [comment] 2015-09-25 21:52
>Can't interact with anything else lying down

you can though
like for instance lying down and disarming passerby

**Comment by RemieRichards** [comment] 2015-09-25 21:53
>like for instance lying down and disarming passerby

Thankyou for the issue report, this will be fixed soon. HONK.

**Comment by PKPenguin321** [comment] 2015-09-25 23:30
but it's not a bug..?

**Comment by RemieRichards** [comment] 2015-09-25 23:35
1. I was joking
2. Debatable, 90% of things aren't possible while lying, meaning it's a consistency issue.

**Comment by PKPenguin321** [comment] 2015-09-26 01:43
nah, it's fine, you're able to do things with your bare hands while lying down but not with held objects. that's how it's always been

**Closed** 2017-01-03 18:59 UTC
Labels: Bug, Consistency Issue
