### ISSUE TITLE
roundstart readying up machine broke (can't move if you ready up or something)

### ISSUE THREAD

**Issue by Hatterhat** [tgstation/tgstation#32447] opened 2017-11-05 18:20 UTC
Issue reported from Round ID: 78388 (Sybil)
Joining at shift-start through readying up fucks up again holy shit
[Directions]:
1) just fucking ready up
2) realize you can't move
[For Admins]: 
i blame @kevinz000

**Comment by BeeSting12** [comment] 2017-11-05 18:47
Turning on debug mode might fix it. (debug --> debug-game)

Unconfirmed though. It just seemed to work.

**Comment by AnturK** [comment] 2017-11-06 21:24
DUplicate of #32474

**Closed by AnturK** 2017-11-06 21:24 UTC
Labels: Needs Reproducing/Testing
