### ISSUE TITLE
The Listening Post floor safe is broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#15894] opened 2016-03-03 05:22 UTC
Cracked it, got the three codes, tried to open it, said it was still locked. I've seen other people be unable to hack it as well.

**Comment by Zilenan91** [comment] 2016-03-04 05:51
Might not be a bug but stay tuned, gonna try testing it soon (tm)

**Comment by WJohn** [comment] 2016-12-03 05:53
Not a map issue, it seems. Could possibly be related to #12474?

**Comment by PKPenguin321** [comment] 2016-12-03 09:24
Yep, a dupe

**Comment by Mervill** [comment] 2016-12-17 09:09
@optimumtact duplicate of #12474

**Closed** 2016-12-17 22:15 UTC
Labels: Bug
