### ISSUE TITLE
RCD logs do not have a name

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#82060] opened 2024-03-17 11:19 UTC
## Issue Summary

No ckey for the people who used the RCD on tool.log

## Round ID:

[225669](https://scrubby.melonmesa.com/round/225669)

## Reproduction:

https://imgur.com/tiEiCmy

Logging. Just check the tool.log and there's no ckey for people who used the RCD.

**Comment by SyncIt21** [comment] 2024-03-17 12:17
Not a bug. the mob is stored in json format and separate from the message.

![Uploading Screenshot (404).png…]()

**Comment by Archie700** [comment] 2024-03-18 07:23
> Not a bug. the mob is stored in json format and separate from the message.

I don't think people should be forced to used JSON format to find out the user of the RCD.

**Comment by SyncIt21** [comment] 2024-03-18 08:35
> I don't think people should be forced to used JSON format to find out the user of the RCD.

That's just your openion, and not enough to classify this as a bug as all data is available.

RCD is a tool and It was logged correctly using the log_tool() proc. 

Either way this should be closed as RCD logging is working as intended

**Comment by Pickle-Coding** [comment] 2024-03-18 12:32
It is unintentional. I assumed log_tool() would prepend the user for the message. It looks a little weird if it's just "used tool" without saying what used it.

**Comment by Archie700** [comment] 2024-03-18 13:49
Let's not assume that things are working as intended when the logs look like this in txt.

![chrome_bdGBzzH90Z](https://github.com/tgstation/tgstation/assets/17823321/26309760-1b43-4678-88ff-6f1d25b42337)

**Closed** 2024-03-22 12:24 UTC
