### ISSUE TITLE
inhands sprites sometimes become stuck

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#31524] opened 2017-10-10 00:47 UTC
sometimes when you hold an item the inhands sprite will remain even if you drop the item or even pick up a new item. The overlay does not update to remove the item, and the only way to do it is by admin intervention.

**Comment by WJohn** [comment] 2017-10-10 00:48
Dupe of #26968

**Closed by WJohn** 2017-10-10 00:48 UTC
