### ISSUE TITLE
You can use holopads to summon anyone including the AI core

### ISSUE THREAD

**Issue by Davesalter** [tgstation/tgstation#68743] opened 2022-07-25 22:08 UTC
## Round ID: Round ID: [21380](https://scrubby.melonmesa.com/round/21380)
Fulpstation

## Reproduction:

 if you disassemble a holopad while the other player is in a call with you and moves you can summon their physical body to your location, in the case of this round i had summoned the AI core to my location in the Head of Personnel office followed by us summoning a random sec officer to confirm it

**Comment by ShizCalev** [comment] 2022-07-25 22:54
Duplicate of #68639

**Closed by ShizCalev** 2022-07-25 22:54 UTC
