### ISSUE TITLE
Weird toolbelt phenomena.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#64218] opened 2022-01-18 19:10 UTC
## Round ID:
[176831](https://scrubby.melonmesa.com/round/176831)

## Reproduction:
Not sure. It occurred after getting stripped in a stasis bed, then putting my clothes back on. The result was a toolbelt in the hud that teleports to random inventory slots (on screen, but not in the inventory slots and is persistent whether the inventory slots are open or not). The toolbelt could not be opened, but I can take and put tools back in, but it deleted some of the tools after putting back in. It also got briefly highlighted randomly despite not having highlighting enabled in preferences.

**Comment by timothymtorres** [comment] 2022-01-19 10:02
Duplicate of #64190

**Closed by timothymtorres** 2022-01-19 10:02 UTC
