### ISSUE TITLE
Make Navigation Beacons deconstructable

### ISSUE THREAD

**Issue by Keekenox** [tgstation/tgstation#19174] opened 2016-07-06 16:30 UTC
Make these little buggers able to be taken apart and/or moved.

@coiax 

http://puu.sh/pSpbr/495a97ced3.png

**Comment by Jalleo** [comment] 2016-07-09 21:10
Those things are ancient as well.

**Comment by SpaceManiac** [comment] 2018-06-01 04:55
Duplicate of #38064. Closing in favor of that ticket because it has more details.

**Closed by SpaceManiac** 2018-06-01 04:55 UTC
Labels: Consistency Issue, Not a bug
