### ISSUE TITLE
shuttle walls STILL break to space

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#36164] opened 2018-03-05 02:39 UTC
its been fucking months

**Comment by 81Denton** [comment] 2018-03-05 06:30
![1481297959530](https://user-images.githubusercontent.com/32391752/36960363-05521be6-2047-11e8-8dc5-aa5d7a8d6f39.jpg)

**Comment by vuonojenmustaturska** [comment] 2018-03-05 14:25
well no-one has touched them so... yeah?

**Comment by Buggy123** [comment] 2018-03-05 14:28
_months_

**Comment by Buggy123** [comment] 2018-03-05 14:29
for _months_ you've been able to space a quarter of the people on a shuttle with a welder and that's not okay.

**Comment by ShizCalev** [comment] 2018-03-05 19:15
Duplicate of #35241
Duplicate of #33984

Please stop reopening the same issue.

**Closed by ShizCalev** 2018-03-05 19:15 UTC
