### ISSUE TITLE
His Grace/monkey bug

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#29425] opened 2017-07-21 17:53 UTC
12:20:10: Focarion2/(Madra Tossilan): there is a issue, his grace can kill infinites monkeys only with one monkey and get instakill hit 
12:21:05: PM From Ausops/(Allad Minsa Recucks): I cannot parse your message, you mean his grace is capable of killing monkeys instantly with a single hit? 
12:21:47: Reply PM from-Focarion2/(Madra Tossilan): like i killed a monkey, but HE GOT BACK FROM LIFE SOMEHOW, i eat it again it goes back being another monkey and i eat and then i got INFINITE DAMAGE 

https://pastebin.com/biuTGjxK player logs

**Comment by ChangelingRain** [comment] 2017-07-21 18:20
oh my god I hate monkeys

so what's happening here is his grace is eating a monkey and the monkey is still able to move because AI monkey code is complete shit so it moves out, and then you can eat it again, it moves out, you can etc etc etc etc etc until his grace oneshots.

**Comment by Xhuis** [comment] 2017-07-22 01:23
but isn't the monkey dead...?! how is this even happening?

**Comment by Supermichael777** [comment] 2017-07-22 01:34
his grace is one of goofs shitty memes
of courese its bad

**Comment by Supermichael777** [comment] 2017-07-22 01:34
goap monkies when

**Comment by Xhuis** [comment] 2017-07-22 01:37
Goof didn't make His Grace, I did!
(joan made most of the modern version tho, but mob eating code is mine.)

**Comment by Supermichael777** [comment] 2017-07-22 01:38
its from goon. its goofs shitty meme no matter the hand he possessed while making it

**Comment by DoctoreMad** [comment] 2017-07-22 15:02
Iamgoofball more like Iamgoonball
Goofcode more like Gooncode

**Comment by ohnopigeons** [comment] 2017-07-22 21:56
Is there a reason the monkey is kept alive when eaten

**Comment by Xhuis** [comment] 2017-07-23 01:12
I can't actually reproduce this.

**Comment by vuonojenmustaturska** [comment] 2017-09-13 20:21
I managed to reproduce it after several attempts, the bug caused dead/incapacitated monkeys to flee their attackers as well as escape His Grace, looked fairly silly. @RemieRichards says it's caused by a "lingering background move loop", and that a similar bug affected syndie mecha pilots in the past.

Hopefully fixed in #30709

**Closed** 2017-09-15 05:15 UTC
Labels: Bug
