### ISSUE TITLE
Ore warps to faraway satchel/backpack if not carrying one after dropping it AKA Ore Quantum Tunneling

### ISSUE THREAD

**Issue by LDChillemi** [tgstation/tgstation#37826] opened 2018-05-13 17:30 UTC
[Round ID]: 87862 but can be observed in any round

[Reproduction]:
1. Start as a Shaft Miner in any Station or Gamemode
2. Remove and drop your backpack with the satchel still inside
3. Equip a Crusher and wear it on your back (Unsure if needed)
4. Start mining with the crusher on Lavaland, carrying an ore box for ore (Unsure if box needed)
5. Stop pulling the box, walk over ore

It'll say 'you put your ore in the satchel' even though you are carrying no satchel. Upon returning to your dropped backpack stationside, your ore will have magically warped inside of the satchel INSIDE of the backpack. If the satchel gets full, it starts warping ore to the backpack. Unsure what happens if the backpack is full.

**Comment by SpaceManiac** [comment] 2018-06-02 22:53
Pretty bad, but a duplicate of #37260 nonetheless

**Closed by SpaceManiac** 2018-06-02 22:53 UTC
Labels: Bug, FUCK, In Game Exploit
