### ISSUE TITLE
Things like to flip on their own now

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#61718] opened 2021-09-26 17:02 UTC
## it spin

https://user-images.githubusercontent.com/75863639/134816957-862b03c8-2ed2-450f-8ee1-d88440df24f5.mp4

sometimes things just spin out of control with no input to them

**Comment by interestingusernam3** [comment] 2021-09-28 20:22
Party

**Comment by Fikou** [comment] 2021-10-03 19:28
youre being orbited by an admin i think thats just admin stuff without reproduction im closing it

**Comment by Sealed101** [comment] 2021-10-11 10:43
> youre being orbited by an admin i think thats just admin stuff without reproduction im closing it

i have zero clue how you'd reproduce this items just begin spinning for no raisin sometimes i have absolutely no idea and if it was admin stuff people would at least speak of it over comms which they didnt, i've seen player characters continuously flip with no interruptions and they didn't speak up about it

**Comment by Fikou** [comment] 2021-10-12 20:29
sure

**Comment by Sealed101** [comment] 2021-11-14 18:54
it keeps happening
### round 173045

https://user-images.githubusercontent.com/75863639/141694240-4ff59249-ba81-4768-ad31-e393defe0498.mp4

### round 173050
i fucked up obs excuse this shitty crop
to note is that ive thrown both of these items at some point but they didn't begin to spin infinitely immediately after, they didnt stop spinning when picked up either

https://user-images.githubusercontent.com/75863639/141694250-a8e5066f-e4fd-4320-9e0b-52698f920aba.mp4

**Comment by dragomagol** [comment] 2021-11-19 03:32
Started getting this when I updated my byond, almost certain it's a byond issue.

**Comment by Sealed101** [comment] 2021-11-19 22:15
could very well be a client-side byond issue actually, i kinda remember getting this after an update to byond
round id 173318

https://user-images.githubusercontent.com/75863639/142692547-188f3640-f9df-4a26-9893-5f2d1b68f312.mp4

**Comment by jlsnow301** [comment] 2021-12-29 23:04
This has been happening to me since I upgraded to 514. Complete

**Comment by GoldenAlpharex** [comment] 2022-01-04 20:42
Started happening between 514.1557 (excluded) and like 514.1560 (included), for sure 1557 doesn't have that bug, this also has as a side-effect to stop ghosts from bobbing up and down. I suspect a change in how animations work, and certain animations no longer being up to speed to work with that.

**Comment by Annihilit** [comment] 2022-04-29 09:05
I've noticed that this usually happens after the SM blows up. Objects that were flung are just kind of spinning on the spot forever

**Comment by timothymtorres** [comment] 2022-12-21 10:44
Pretty sure this was fixed at some point.  Haven't seen this bug at all in a long time.

**Closed** 2023-02-26 00:06 UTC
Labels: BYOND Issue, FUCK, Needs Reproducing, Against God and Nature, Cleanup Flagged
