### ISSUE TITLE
Find station weak point objective can cause arrivals to be depressurized

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68904] opened 2022-08-01 00:21 UTC
Reporting client version: 514.1585

## Round ID:
[187667](https://scrubby.melonmesa.com/round/187667)

## Testmerges:
- [fixes nuke ops leaders not spawning](https://www.github.com/tgstation/tgstation/pull/68855)

## Reproduction:

Traitor gets objective to find station weak point
Station weak point is at customs, you know, right by arrivals
Tot sets explosive
Explosive goes off
Arrivals gets vented from explosion right next door. Resulting in late either getting stuck on the shuttle so as to not die of exposure until such a time as a member of the crew or admin intervene make arrivals safe. We don't let traitors spawn camp arrivals or really grief/destroy/vent it for a reason. Having an objective that can do that when completed seems rather counter productive. 

Perhaps customs shouldn't be a weak point

**Comment by Mothblocks** [comment] 2023-10-30 21:19
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:19 UTC
Labels: Not a bug, Quality of Life
