### ISSUE TITLE
Custom vendors don't show hand labeler labels

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#84937] opened 2024-07-13 11:34 UTC
Reporting client version: 515.1641

When an item with a label on it is put on sale into a custom vendor, it's label will dissapear.
This makes it difficult to specify what the item you are trying to sell is.

## Round ID:
[232048](https://scrubby.melonmesa.com/round/232048)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

1. Use a hand labeler on any item.
2. Add a price tag to the item using an universal scanner
3. Place the item in a vendor.
4. Notice the label for the item you previously applied to it is missing.

**Comment by Sadboysuss** [comment] 2024-07-13 11:41
Dupe of https://github.com/tgstation/tgstation/issues/83151

**Closed** 2024-07-15 08:49 UTC
