### ISSUE TITLE
vendors are borked

### ISSUE THREAD

**Issue by kuricityy** [tgstation/tgstation#86906] opened 2024-09-26 02:24 UTC
### Client Version:

515.1636

### Issue Summary:

vendors are completely borked
![image](https://github.com/user-attachments/assets/9b801910-e2db-4c52-bfa5-88dd73cd9e39)
when trying to buy something it gives you this error message ^ also quotes that you have no occupation, and also you dont get your paycheck.

### Round ID:

[238986](https://scrubby.melonmesa.com/round/238986)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

spawn in
go to vendor (sec tech vendor for me specifically)
try to buy something
get called an embezzeler
dont get paid

**Comment by 00-Steven** [comment] 2024-09-26 02:33
duplicate of #86887, pr is up

**Closed** 2024-09-26 05:51 UTC
