### ISSUE TITLE
FIX THE NUKE CORE BOX

### ISSUE THREAD

**Issue by FIXTHERADBOXPLEASE** [tgstation/tgstation#17804] opened 2016-05-20 09:24 UTC
I took the nuke core out at round start, put it in nuke core box, and it was still leaking loads of rads when the round ended. I wasn't wearing a radsuit when I took the core out, if that matters.

**Comment by Dorsisdwarf** [comment] 2016-05-20 10:23
How were you _alive?_ Removing the rad core without a radsuit's always been rapidly fatal in my experience

**Comment by xxalpha** [comment] 2016-05-20 11:25
>I wasn't wearing a radsuit when I took the core out, if that matters.

I agree there's a bug here, you should have collapsed within seconds and died shortly after that.

**Comment by Jalleo** [comment] 2016-05-20 12:13
Okay I need to ask did you take it out of the box and that was when it was leaking rads?
Because that is intended. If you are saying the BOX you store it in isn't stopping the leaking of rads then that is a bug.

**Comment by PKPenguin321** [comment] 2016-05-20 13:51
You have to close the box once the core is in

**Comment by xxalpha** [comment] 2016-05-20 13:53
It closes automatically, I am sure.

**Comment by PKPenguin321** [comment] 2016-05-20 13:55
No it does not

**Comment by xxalpha** [comment] 2016-05-20 14:00
Have you ever done that objective?

**Comment by PKPenguin321** [comment] 2016-05-20 14:03
Yes

**Comment by PKPenguin321** [comment] 2016-05-20 14:03
The box has a retarded delay where you use it and it says "The box starts closing..." For a gorillion years before actually closing

**Comment by Jalleo** [comment] 2016-05-20 14:56
ugh @Cheridan intended or should we remove this?

**Comment by coiax** [comment] 2016-05-20 15:00
Um, radiation will take at least 66 ticks to kill a full health person.
Damage is done [here](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/life.dm#L276) which is 3 toxic damage per tick, assuming you're being kept in the red zone faster than your system currently purges it.

Hitting the 100 rad maximum level will unconcious/weaken you though, and you're unlikely to be able to do anything if the dose is strong. I've been meaning to overhaul radiation to make it more realistic (eg. more deadly) at some point.

**Comment by FIXTHERADBOXPLEASE** [comment] 2016-05-21 00:14
The box was closed. I was saved by other people.

**Comment by FIXTHERADBOXPLEASE** [comment] 2016-05-21 00:16
But it was still leaking rads when closed, obviously.

**Comment by xxalpha** [comment] 2016-05-21 00:45
It bombards you with 40 radiation at a time, it was probably just still stacked and damaging you.

**Comment by PKPenguin321** [comment] 2016-05-21 00:47
what could have broken this? i did it not too long ago and the box stopped radiating people after i closed it.

**Comment by FIXTHERADBOXPLEASE** [comment] 2016-05-21 08:50
No idea what could have caused it, other than not wearing the radsuit, or maybe passing out just as I closed the box. I don't think it was just stacked on me, as it was affecting other people, but not me, when I finally put on a radsuit.

**Comment by xxalpha** [comment] 2016-05-21 10:12
It's possible the core wasn't removed from processing somehow.

**Comment by xxalpha** [comment] 2016-05-21 15:25
I attempted to reproduce this and I couldn't. The core inside the container does not leak radiation.

**Comment by Supermichael777** [comment] 2016-05-21 21:17
ah the box that prevents you from weapons ingredients the core

**Comment by Man-Shroom-** [comment] 2016-05-21 21:51
@Supermichael777 
you wanna run that by me again dawg

**Closed** 2016-05-23 09:01 UTC
Labels: Bug, Cannot Reproduce
