### ISSUE TITLE
Taking an item out over lava as a plastitanium golem ignites it

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#38392] opened 2018-06-09 22:03 UTC
Issue reported from  Round ID: 89223 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

If you're standing on a lava tile and take a crusher off your back (for example) it will light on fire and eventually be destroyed in your hands. However, walking onto the lava with it out will not ignite the item.

Additionally, putting it back onto your back on a normal tile will put the fire out.

**Comment by PKPenguin321** [comment] 2018-06-09 22:33
Dupe, and not exclusive to being a plastitanium golem

**Comment by SpaceManiac** [comment] 2018-06-10 00:09
removing an item from storage involves dropping it to the ground and then picking it back up again because of reasons

**Comment by PKPenguin321** [comment] 2018-06-10 01:06
this is a dupe of a very old issue but i really cant be assed to find it

**Comment by XDTM** [comment] 2018-06-10 08:27
Didn't we fix that with stuff like transferitemtoloc?

**Comment by ShizCalev** [comment] 2018-06-12 17:41
duplicate of #25860

**Closed by ShizCalev** 2018-06-12 17:41 UTC
Labels: Bug
