### ISSUE TITLE
Deltastation Bar Tourist-bots Don't Face The Bar

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#63114] opened 2021-11-28 01:40 UTC
Reporting client version: 514.1561

## Round ID:
[173805](https://scrubby.melonmesa.com/round/173805)

## Testmerges:
- [Fixes tend wounds being inacessible without an operating table + computer](https://www.github.com/tgstation/tgstation/pull/63079)

## Reproduction:
Just what the title says, if they face south, they only drink a drink to their south. Normally not an issue, but on Delta specifically, they tend to face either south or east when standing at the bar, despite it being to their north. If there was a way to force tourist-bots to face a table, or if they could eat/drink from any tile around them instead of just the one they were facing, it would fix this issue.

**Comment by LemonInTheDark** [comment] 2021-11-28 03:14
So the issue is less with only drinking in the direction they face, and more that they don't face the counter

**Comment by OuroborusReporter** [comment] 2021-11-28 03:23
That is correct, but I couldn't think of a better way to title it mid-round. I'll make it more accurate now

**Comment by MrMelbert** [comment] 2021-11-29 18:39
> If there was a way to force tourist-bots to face a table, or if they could eat/drink from any tile around them instead of just the one they were facing, it would fix this issue.

There is a way - it depends on the direction of the seat they're sitting at. This means the stools in deltastation's bar are backwards (again?)

**Comment by MrMelbert** [comment] 2021-12-01 04:19
This is fixed now / not an issue, as deltastation bar was revamped

**Comment by LemonInTheDark** [comment] 2021-12-01 04:38
Trusting you on this

**Closed by LemonInTheDark** 2021-12-01 04:38 UTC
Labels: Consistency Issue
