### ISSUE TITLE
Lava generated in mining base

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19311] opened 2016-07-14 04:42 UTC
On top of where the windows should be near suit holders. I opened a suit pod and got spacewinded into the lava and so did the other miner

**Comment by Bawhoppen** [comment] 2016-07-14 06:48
Dupe of issue

**Comment by optimumtact** [comment] 2016-07-14 07:50
@Bawhoppen if you're calling it a dupe either spend the time to find the issue it's a dupe of or don't bother commenting, it's just issue noise that serves no purpose.

Dupe of #19111

**Closed by optimumtact** 2016-07-14 07:50 UTC

**Comment by Bawhoppen** [comment] 2016-07-14 09:23
thats not what it's a dupe of, it's a dupe of https://github.com/tgstation/tgstation/issues/17450
close https://github.com/tgstation/tgstation/issues/19111
