### ISSUE TITLE
this is the most dumb shit i heard incode

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#36685] opened 2018-03-24 09:18 UTC
Bluespace harmonics prevent the spawning of more than 20 monkeys on the station at one time!

**Comment by YakumoChen** [comment] 2018-03-24 09:20
yeah because I sure to love seeing the non-antag botanists fill the hallways with griffmonkeys every single round

**Comment by praisenarsie** [comment] 2018-03-24 09:24
there's a limit though that limit looks extremely low to me

**Comment by Jordie0608** [comment] 2018-03-24 09:32
Duplicate of #36656

**Closed by Jordie0608** 2018-03-24 09:32 UTC
