### ISSUE TITLE
Navigation Computer Outlines are Missing

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#63413] opened 2021-12-14 17:48 UTC
## Round ID:
N/A, Local Branch

## Testmerges:
N/A

## Reproduction:
Byond Version: 514.1568

When using navigation computers, the green outline of the shuttle is completely missing, as is the blue outline of a marked location. This makes precise navigation rather obtuse. (Especially with smaller shuttles, like the trade route syndicate cutter)

**Comment by SuperNovaa41** [comment] 2021-12-14 18:13
Duplicate of https://github.com/tgstation/tgstation/issues/62099

**Closed by SuperNovaa41** 2021-12-14 18:13 UTC

**Comment by unit0016** [comment] 2021-12-14 19:22
Hell, searched "Navigation Computer" and didn't see that issue. My bad.
