### ISSUE TITLE
Monkies can steal items trough directional windows using monkey magick

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#56341] opened 2021-01-22 09:38 UTC
## Reproduction:
go to gene
have item in hand
monke tries to steal your item
fail to notice the small warning
monke bypasses physics and steals your item
cry that you cannot take it back because you have no access

**Comment by Sealed101** [comment] 2024-09-09 21:12
Duplicate of #59244

**Closed by Sealed101** 2024-09-09 21:12 UTC
Labels: Bug, Consistency Issue
