### ISSUE TITLE
Revival of Sentient mob removes ability to move.

### ISSUE THREAD

**Issue by delaron** [tgstation/tgstation#41242] opened 2018-10-30 20:41 UTC
Any sentient mob that is resurrected via staff of healing, Lazarus shot or other revive effect looses the ability to move. They can speak, activate abilities, and even change the direction they face but are locked out of movement.

Happened to several players over several rounds round.  Can easily reproduce with a staff of change and staff of healing.

The quick fix is to reapply a sentience potion or have your form changed again.

**Comment by Barhandar** [comment] 2018-10-30 21:33
Technically a duplicate of #41120, but has more info

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-10-30 21:53
they are having their resting set to `TRUE` btw, admins can fix this by setting it to `FALSE (AKA 0)` and using the get verb.

**Closed** 2018-11-17 08:06 UTC
