### ISSUE TITLE
You can bola people that lay on the ground

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#61772] opened 2021-09-29 13:09 UTC
Reporting client version: 514.1568

## Round ID:
[170451](https://scrubby.melonmesa.com/round/170451)

## Reproduction:

lay down
get bola'd
skill issue

**Comment by necromanceranne** [comment] 2021-09-29 21:39
This is actually not a bug

https://github.com/tgstation/tgstation/pull/60604

It's really up to @Ghommie to decide if this is intended or not but as far as I can tell this is intended. I'll let them come in and say more before closing the issue.

**Comment by Ghommie** [comment] 2021-09-29 21:59
Intended. The person who threw the bola at you was robust enough to aim for your mob (like how guns worked against targets  without density, be it a mouse or a prone spessman, before the tactical resting removal). If he hadn't the bola would have flew past you.

**Comment by necromanceranne** [comment] 2021-09-30 00:34
Yeah I was even saying that would be a good pr to bring it up in.

**Closed by necromanceranne** 2021-09-30 00:34 UTC
Labels: Not a bug

**Comment by Colovorat** [comment] 2021-09-30 06:59
@Ghommie whatchu mean intended, it wasn't a thing before, and it's overall pretty stupid how you can bola a human laying on the ground

**Comment by Ghommie** [comment] 2021-09-30 13:23
The fact mobs lying on the ground couldn't be targetted by thrown things `no matter what` was actually a lack of foresight from whoever first developed it, not an intended feature but actually an ancient issue (see #29806).

**Comment by Colovorat** [comment] 2021-09-30 14:13
It's just plain stupid that you can bola resting people, sure with shooting, but bola, just think how stupid this is

**Comment by Ghommie** [comment] 2021-09-30 14:17
If you want to PR a change that makes bolas not ensnare horizontal spessmen, be my guest. I was talking about throwing in general.
