### ISSUE TITLE
IV drips stopped working mid round

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#38906] opened 2018-07-04 10:52 UTC
Issue reported from  Round ID: 90461 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

In the middle of the round IV drips suddenly stopped working for all players (or at least myself and the ones I asked to try it). It became impossible to add beakers or bags to the IV drip, even at help intent. Instead it showed the animation as if you were on harm intent (as if you punched the IV drip with the beaker). 

We tried spawning in new IV drips but that did not help.

**Comment by Daundra** [comment] 2018-07-04 11:20
I know this probably isn't my right to say as a noncoder but this seems far too similar to #38880 to be a coincidence.

My reasons being 
1) they both relate to objects having other objects put in them 
2) they break for some reason after having worked perfectly before (which is why several people in the issue I posted couldn't reproduce it)

again, sorry if this doesn't help much but there's gotta be a connection there.

**Comment by Mickyan** [comment] 2018-07-04 15:36
Related or dupe of #38720?

When it happened I noticed that if you right click on it and click "remove container", a menu will pop up with a list of all the mobs in sight. Doesn't do anything, though.

**Comment by SpaceManiac** [comment] 2018-07-04 23:01
The mob menu issue was fixed by #38911. "Clicking attacks instead" is a duplicate.

**Closed by SpaceManiac** 2018-07-04 23:01 UTC
Labels: Bug
