### ISSUE TITLE
Anti-breach shields float away in hyperspace.

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#76369] opened 2023-06-27 14:56 UTC
Reporting client version: 514.1589

## Round ID:
[209184](https://scrubby.melonmesa.com/round/209184)

## Testmerges:
- [A small pile of borg combat changes](https://www.github.com/tgstation/tgstation/pull/75819)
- [TTS Improvements: Improved Audio Quality, Pitch Adjustment, Preference Silicon Voices, Per-Character Voice Disable Toggle, Tongue Voice Filters, Reworked Silicon and Vending Machine Filters](https://www.github.com/tgstation/tgstation/pull/76129)

## Reproduction:
Use an anti-breach shielding projector on a shuttle, might need to be activated first or be activated in hyperspace. Then watch in delight as the shields just float away.

**Comment by Rex9001** [comment] 2023-06-27 14:56
![Skärmbild 2023-06-27 165606](https://github.com/tgstation/tgstation/assets/120136161/fdecc75d-58d7-4c99-96a5-eb7205655435)
Image

**Comment by SyncIt21** [comment] 2023-06-27 16:12
https://github.com/tgstation/tgstation/issues/76268#issuecomment-1603459366

**Comment by Jackal-boop** [comment] 2023-06-27 16:52
possibly related. lasers and projectiles seem to flip every which way when shot in hyper space

**Comment by TheVekter** [comment] 2023-06-27 17:10
Yeah this is a duplicate of #76172.

**Closed by TheVekter** 2023-06-27 17:10 UTC
