### ISSUE TITLE
hand tele portals fix your camera in place sometimes for no discernible reason

### ISSUE THREAD

**Issue by cyclowns** [tgstation/tgstation#34205] opened 2018-01-09 02:12 UTC
[Round ID]: sybil #81605

![image](https://user-images.githubusercontent.com/19853115/34701633-94bfbe68-f4a6-11e7-8699-e3afd7e54db0.png)

![image](https://user-images.githubusercontent.com/19853115/34701730-0b8212c6-f4a7-11e7-8ede-174635daa7d8.png)

as you can see from the images, my camera doesn't move at all from the point where I entered the portal but I can walk around and talk like normal and do pretty much everything I normally could

if it helps, gravity was off when I went through the portal and I was moving at kind of an odd diagonal angle.

i'm aware this is fixable by just clicking cancel camera view in the ooc tab but it still shouldn't happen regardless

**Comment by ShizCalev** [comment] 2018-01-09 04:08
Duplicate of #34011

**Closed by ShizCalev** 2018-01-09 04:08 UTC
