### ISSUE TITLE
Monkeys chase after death

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61480] opened 2021-09-15 17:39 UTC
## Round ID: [166818](https://scrubby.melonmesa.com/round/166818) 
(I looked in scrubby logs for an hour+ to find this)

## Testmerges:
https://github.com/tgstation/tgstation/pull/60450
https://github.com/tgstation/tgstation/pull/60432
https://github.com/tgstation/tgstation/pull/60488

## Reproduction:
1 - Have a monkey be agro'd onto you. 
2 - Have it be killed. (By someone else or yourself, not sure if this is relevant. I was playing pacifist and had to have someone else kill it for me.)
3 - After it's dead, it's body will scoot on the floor after you without hitting you, but like it's tracking you in order to hit you.

**Comment by TheBonded** [comment] 2021-09-15 21:04
duplicate of https://github.com/tgstation/tgstation/issues/57372

**Comment by Mooshimi** [comment] 2021-09-15 21:12
> duplicate of #57372

I'll keep it open in case they want the round to compare to the first one

**Closed** 2021-09-15 21:13 UTC
