### ISSUE TITLE
Stacking machine at gulag shuttle doesen't give points

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#85790] opened 2024-08-13 21:04 UTC
Reporting client version: 515.1642

## Issue Summary
Stacking machine at gulag shuttle doesen't give points when you load mats into it. Prisoner basically has to either deal with secs, or ask borgs to retrieve items.

## Round ID:
[234745](https://scrubby.melonmesa.com/round/234745)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

1. Get gulagged
2. Farm mats
3. try to put them into stacking machine
4. watch them being eaten without actually giving you any points
5. cope

**Comment by Sadboysuss** [comment] 2024-08-13 21:18
duplicate of https://github.com/tgstation/tgstation/issues/85789

**Closed** 2024-08-14 08:16 UTC
Labels: Cleanup Flagged
