### ISSUE TITLE
you can jump into other pipe nets while moving trought them

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34007] opened 2018-01-01 15:02 UTC
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:) bagel
[Round ID]: # (**INCLUDE THE ROUND ID**) round id 81188
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
The following pull requests are currently test merged: 
#33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e 
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0 

Based off origin/master commit: e84a7f 

Server tools version: /tg/station 13 Server v3.2.1.9 

Server tools API version: 3.2.0.1 

Current Informational Settings: 

video of jump tricks:
http://take.ms/yvBVL

**Comment by Potato-Masher** [comment] 2018-01-01 16:38
From previous rounds, the issue seems to stem from trying to move diagonally through a pipe. You can jump into a different pipe network if there is one at the tile you are moving to, otherwise, you just exit the network outright.

**Comment by WJohn** [comment] 2018-01-01 18:00
Dupe of #33528

**Closed by WJohn** 2018-01-01 18:00 UTC
