### ISSUE TITLE
Borg cant move diagonally in space

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#68067] opened 2022-06-28 23:24 UTC
## Round ID:
[185722](https://scrubby.melonmesa.com/round/185722)

## Testmerges:
#65791
#67083

## Reproduction:
> Try to move SW into space, drifting
> Moves one tile then goes straight W

**Comment by LemonInTheDark** [comment] 2022-06-28 23:32
none can move diagonally in space, caused by #66657, fixed by #68033

**Closed** 2022-07-17 04:44 UTC
Labels: Bug
