### ISSUE TITLE
Passing through the vomi/tg/oose makes you able to pass through others without moving them, until someone moves the goose, making you teleport back to it and regain tangibility

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#44884] opened 2019-06-30 03:00 UTC
Issue reported from  Round ID: 111943 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by PKPenguin321** [comment] 2019-06-30 03:06
holy shit what
how did they even mess that up

**Comment by Shirbu** [comment] 2019-06-30 03:29
I don't really know

**Comment by Shirbu** [comment] 2019-06-30 03:29
It prally has something to do with the mechanics of switching places with a mob

**Comment by Shirbu** [comment] 2019-06-30 03:30
Until something moves vomi/tg/oose, it is as if it has only completed half of the switching places.

**Comment by SpacePrius** [comment] 2019-06-30 03:32
This is the most specific issue I have ever seen in my life.

**Comment by Shirbu** [comment] 2019-06-30 04:42
I think I know what is causing it. When you walk into the goose, the goose moves to your position but you do not move. Then, when someone else walks into the goose, that happens to them, but YOU move to the goose's position. So there is a delay in the switching places thing

**Comment by Borisvanmemes** [comment] 2019-06-30 16:45
Just tested this on bagil in the thunderdome, it is in fact bugged.

**Comment by ATH1909** [comment] 2019-06-30 22:16
https://www.youtube.com/watch?v=2djx83-4XNQ

This is almost like an SCP.

**Comment by SpaceManiac** [comment] 2019-07-01 00:26
the problem is calling `stoplag` from inside `Moved`

**Comment by plapatin** [comment] 2019-07-01 01:51
what the fuck

**Comment by wesoda25** [comment] 2019-07-05 01:22
Why was this merged again

**Comment by Detective-Google** [comment] 2019-07-17 01:20
I thought it was intended and the goose was just cursed because its such an odd fuckup

**Comment by Cw3040** [comment] 2019-07-17 21:30
Vomi/tg/oose confirmed SCP

**Comment by tralezab** [comment] 2019-08-16 21:06
confirmed fixed by my fix

**Closed** 2019-08-17 22:52 UTC
Labels: Bug
