### ISSUE TITLE
Engineering borgs inducers non-fuctional

### ISSUE THREAD

**Issue by Strazyplus** [tgstation/tgstation#88244] opened 2024-11-27 03:48 UTC
### Issue Summary:

Engineer cyborgs have a inducer upgrade module, this module does not function, it states it is missing a battery and will not charge anything and is not possible to insert a battery into am module.

### Round ID:

[6073](https://scrubby.melonmesa.com/round/6073)

### Reproduction Steps:

Become engineer cyborg
obtain inducer upgrade
Slap a APC
cope

**Comment by Sadboysuss** [comment] 2024-11-27 03:56
Was supposed to be fixed by https://github.com/tgstation/tgstation/pull/87953

**Comment by SyncIt21** [comment] 2024-11-27 06:03
Cannot reproduce on local

**Comment by Sadboysuss** [comment] 2024-11-27 06:27
> If you are reporting an issue found in another branch or codebase, you must link the branch or codebase repo in your issue report or it will be closed.
For branches, If you have not pushed your code up, please either reproduce it on master or push your code up before making an issue report.
For other codebases, if you do not have a public code repository you will be refused help unless you can completely reproduce the issue on our master branch.

**Closed by Sadboysuss** 2024-11-27 06:27 UTC
Labels: Bug
