### ISSUE TITLE
Alt+tabbing permanently toggles movement mode

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#25547] opened 2017-03-27 19:07 UTC
Holding alt will toggle the movement mode only for the duration that you are holding it, and upon releasing the alt key the movement mode is toggled back to what it was. However if you alt+tab it doesn't change back to what it was, it remains in the alternative mode, I am guessing the button release code is not triggered because the game window loses focus.

**Comment by Cyberboss** [comment] 2017-03-27 19:11
Dupe of #23537

**Closed** 2017-03-27 20:20 UTC
