### ISSUE TITLE
PDAs effectively lost upgrade capabilities in storage

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67338] opened 2022-05-27 16:32 UTC
## Reproduction:
Try to save notekeeper and messenger to a data disk so you can move them back onto your PDA after upgrading from an SSD to a HDD.
Messenger will not save.
Be unable to upgrade your PDA storage space without giving up one of the main functions of a PDA.
Thanks, #67223!

Saving from SSD to Data Disk:
![image](https://user-images.githubusercontent.com/44104681/170740810-7dc3bc8c-18e7-44fa-ba43-0be63c058c35.png)

PDA after changing to HDD and uploading notekeeper from the disk:
![image](https://user-images.githubusercontent.com/44104681/170740922-24717292-5631-4b31-8ab3-f9f285c21d37.png)

Before #67223, both programs could be transferred via data disk, allowing you to make the upgrade to your PDA storage without losing the main function of the PDA. I know this because I was doing it. I enjoyed the little room for upgrades I had.

**Comment by JohnFulpWillard** [comment] 2023-02-02 20:45
HDD and SSD were removed
Notepad can be file transfered with disks, PDA messenger app is not meant to transfer over between PDAs, so I'm closing this as not a bug.

**Closed by JohnFulpWillard** 2023-02-02 20:45 UTC
Labels: Consistency Issue
