### ISSUE TITLE
The spare captains ID is not exempt from the lathe tax

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#67084] opened 2022-05-17 23:22 UTC
This feels like an over sight, the captain of the station should be able to print from any lathe for free

## Reproduction:
be acting cap CE, grab spare cap id, try to print atmos holo fan, cry

**Comment by tnekohue** [comment] 2022-05-17 23:24
You have to add your account to the id, goto IC>Memories
Alt click the ID, enter the number. Be able to use the lathe now.

**Comment by timothymtorres** [comment] 2022-05-21 05:31
As tnekohue said, the captain's spare ID doesn't have an account registered.  You just need to link the ID to your account and it works.  Marking this as `Not a bug` and this will autoclose in 7 days.

**Comment by tnekohue** [comment] 2022-05-21 07:50
This in in fact still a problem, if for example, I am the acting captain, its not possible for me to use science lathes if I started as the chief engineer.

**Comment by timothymtorres** [comment] 2022-05-21 08:41
Why wouldn't it be possible?  You still have access to the science lathe with the captain's spare ID.  Just link the ID to the account with Alt-Click and pay the credits

**Comment by Redrover1760** [comment] 2022-05-23 05:23
The issue is that job changes do not affect Arconomy Lathe Taxes. Your Cap ID linked to CE account will charge for anything but engineering protolathe still due to hurr durr

**Comment by dragomagol** [comment] 2022-06-26 03:59
Closing for cleanup flagged.

**Closed by dragomagol** 2022-06-26 03:59 UTC
Labels: Not a bug, Cleanup Flagged
