### ISSUE TITLE
MC crash

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29248] opened 2017-07-14 00:27 UTC
Round 73242, Bagil

Someone flooded freon into distro, and the server immediately shat it self once it had spread around a fair bit. At the time it crashed, my character refused to move and acted as if she had no arms (when she did), and when I reloaded the game it was all white and crashed immediately and completely fucked. Server was under heavy player load because it was prime time.

![untitled](https://user-images.githubusercontent.com/10399117/28193308-a4d166dc-6809-11e7-8f85-905f052fcfec.png)

**Comment by Tacolizard** [comment] 2017-07-14 03:26
literally zero proof freon did this

**Comment by kevinz000** [comment] 2017-07-14 10:08
we look at freon and sigh.

**Comment by Anonmare** [comment] 2017-07-14 11:58
@Tacolizard I was in the round and the lag started not minute after freon started getting released by vents.

**Comment by DoctoreMad** [comment] 2017-07-14 13:47
~~Well, we could remove freon and add alternative engines other than supermatter to maps to alleviate this issue until someone discovers what is wrong with Freon.~~ who am I fucking kidding, Freon is probably some head dev's pet project considering the horseshit that has passed just to justify having it around. The metaclub could announce itself right now and MrStonedOne would roll around while the whole server went "We know m8, fuck off".

**Comment by Cyberboss** [comment] 2017-07-14 13:51
Link to the associated runtime log: https://tgstation13.org/parsed-logs/basil/data/logs/2017/07/14/round-73242/runtime.txt.gz

As you memes can see, freon had nothing to do with this

**Comment by Cyberboss** [comment] 2017-07-14 13:52
@MrStonedOne

**Comment by Armhulen** [comment] 2017-07-14 19:16
that looks fucking sweet tho

**Comment by Armhulen** [comment] 2017-07-14 19:16
and i'm positive it's freon this exact same thing happened a minute after a griff drone dumped freon on the shuttle

**Comment by Tacolizard** [comment] 2017-07-14 23:18
>Freon is probably some head dev's pet project

how new are you

**Comment by lzimann** [comment] 2017-07-15 00:14
While freon might not be the direct cause, it is very likely it is triggering something.

**Comment by Iamgoofball** [comment] 2017-07-15 00:23
>[00:09:43]Cannot read /obj/item/weapon/storage/box/s... (/obj/item/weapon/storage/box/syndie_kit/imp_adrenal).icon

**Comment by Iamgoofball** [comment] 2017-07-15 00:23
this is weird

also seeing bicon issues

**Comment by MrStonedOne** [comment] 2017-07-16 17:59
This is likely a OoM(Out of Memory) issue.

The moment byond triggers an OoM, all lists, files, and icons lose their reference, so at that point, byond would have stopped logging anything for the round because the reference to the runtime log would have gone away.

My hint is the "You look at your arm and sigh", this generally means the limbs list went null, and generally OoM is what causes that.

**Comment by Jalleo** [comment] 2017-07-24 09:27
I wonder what caused the OoM

**Comment by DoctoreMad** [comment] 2017-08-02 16:53
(Freon)

**Comment by Cyberboss** [comment] 2017-10-12 13:03
Duplicate of #26453

Plus the bright light issue was fixed

**Comment by Cyberboss** [comment] 2017-10-12 13:03
Duplicate of #26453

**Closed by Cyberboss** 2017-10-12 13:03 UTC
Labels: Bug, Needs Reproducing/Testing, Priority: High
