### ISSUE TITLE
Paper code macros don't behave as expected

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55101] opened 2020-11-22 06:20 UTC
## Round ID:
[150766](https://scrubby.melonmesa.com/round/150766)

## Testmerges:
#54588: 'Bring back Kilostation v3.0' by Maurukas at commit df4d220

## Reproduction:

Pulling a sheet off of the wiki's old guide and seeing how to do things now I did a quick exercise to see how functional things were.

![image](https://user-images.githubusercontent.com/51932756/99896615-6eed0e00-2c4f-11eb-872d-78f5249bd8fd.png)
![image](https://user-images.githubusercontent.com/51932756/99896629-89bf8280-2c4f-11eb-9dd1-4fdaca8e5a4f.png)

In the second line in the header the expectation would be that it would be in bold, but it does not.

In the body of this form the signature attempt is completely missed.

At the very end an attempt to have three repeated signatures only the last one was caught.

**Comment by stylemistake** [comment] 2020-11-23 01:05
Markdown not working inside tags is not a bug.

Signatures need fixing though.

**Comment by stylemistake** [comment] 2020-11-24 16:09
Was fixed in #55129, reopen if signatures are still problematic.

**Closed by stylemistake** 2020-11-24 16:09 UTC
Labels: Bug, UI
