### ISSUE TITLE
Bomb cores and c4 seem to be acting weirdly. 

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#26547] opened 2017-04-25 03:18 UTC
Testmerges are #26465 and #26493. 0a1107a91b87e156a6f18a7461bfd90f3a26a36c is the commit, I think.

Used c4 on a bomb core in my satchel, didn't do anywhere near the usual explosion range. In fact, it didn't even gib me. Not sure if this was a hidden nerf, so I made an issue.

**Comment by ShizCalev** [comment] 2017-11-21 05:38
Duplicate of #22035

**Closed by ShizCalev** 2017-11-21 05:38 UTC
Labels: Bug
