### ISSUE TITLE
Duplicating Bluespace Bag

### ISSUE THREAD

**Issue by emudumburemu** [tgstation/tgstation#58664] opened 2021-04-24 20:49 UTC
## Round ID:
[Round ID]: # 160930

## Reproduction:

You can pick up folded bluespace bodybag you are in, if it gets thrown on the floor while folded. That lets you use it in your hand, and for some reason the bag doesn't disappear from your hand, the sprite disappears but you can keep spamming the USE hotkey, unfolding infinite bodybags, unless something knocks it out of your hand. The duped bags are also, apparently, the same item, because, it seems, under some conditions I don't know, after you fold one of these duped bags with people in it, unfolding the glitchy bag thing in your hand that you got makes all the contents of that other bag eject right there, supposedly just works with any duped bags.
That had been pretty much what I did that round, after discovering it, until someone asked me to stop, which, not sure why, led me to put the invisible glitchy bag I kept unfolding in my backpack instead of dropping it on the floor. I also lost the glitchy bag and then picked up another bag I got folded into, one of the other, duped ones, to start spamming them again, which happened before the backpack thing. There was also a void heretic doing void jaunt with one of the bluespace bags. These are the only things I can think of as having caused it.
After the backpack thing something happened to the buggy teleportation thing and people would just get put in the "void", with their POVs allegedly jumping between all the bags, instead of them reemerging at the unfolded ones.
Then the server crashed, shortly after the void jaunt happened, I was told, and after I reconnected the bagged people got booted back to the lobby, and couldn't connect.

**Comment by timothymtorres** [comment] 2021-11-20 20:23
Duplicate of #44902

**Closed by timothymtorres** 2021-11-20 20:23 UTC
