### ISSUE TITLE
Buildmode ghosts can teleport now for some reason

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#41552] opened 2018-11-17 04:23 UTC
Reproduction: Give yourself buildmode through view variables dropdown menu and left/right click around. You'll teleport if you double click or more.

Normally, you don't teleport when using buildmode as a ghost. For some reason I do now, though. It's really annoying.

**Comment by Barhandar** [comment] 2018-11-17 10:45
@ninjanomnom

**Comment by RedFoxIV** [comment] 2018-11-18 07:46
https://github.com/tgstation/tgstation/issues/40451
f t s
i h h
x i i
  s t

**Comment by AnturK** [comment] 2018-11-21 17:21
Duplicate of #40451

**Closed by AnturK** 2018-11-21 17:21 UTC
