### ISSUE TITLE
VV runtimes when opened on mobs

### ISSUE THREAD

**Issue by Jacquerel** [tgstation/tgstation#79264] opened 2023-10-25 14:55 UTC
## Reproduction:

Right click a human
Open VV panel

![image](https://github.com/tgstation/tgstation/assets/7483112/222a3b79-9028-4cff-9bc9-d035146c73c9)
![image](https://github.com/tgstation/tgstation/assets/7483112/8810296f-57d2-4774-8ef6-18d8725cb143)

Seems like `_debug_variable_value` is being passed `1` as a name which is being treated as an index into the assoc list `vv_special_lists` because it's a number and not a string.
This then causes this code to treat things which aren't lists as lists, and runtime when fetching their length.
Might not be the cause, but seems suspicious to me.

I didn't get this runtime when opening VV on a turf or an object but I did on a player and a corgi.

**Comment by GPeckman** [comment] 2023-10-25 19:35
Probably caused by #79154. It was merged shortly before the bug started showing up and it touched the code where the error occurs.

**Closed** 2023-10-27 03:46 UTC
