### ISSUE TITLE
Genetics broken

### ISSUE THREAD

**Issue by Dingus997** [tgstation/tgstation#85131] opened 2024-07-20 04:36 UTC
Reporting client version: 515.1641

## Issue Summary
Genetics consoles only enables seeing and modifying the monkified mutation on monkeys with the intention of disabling it and "uncorrupting" the dna, which makes all other mutations visible. However it currently shows every mutation, including monkified, as invisible on monkeys, making it impossible to humanize them which completely disables the main function of genetics.

## Round ID:
[232364](https://scrubby.melonmesa.com/round/232364)

## Testmerges:
- [Ghosts once again can see people's true names and roundstart jobs](https://www.github.com/tgstation/tgstation/pull/84951)

**Comment by SmArtKar** [comment] 2024-07-20 04:38
Duplicate of #85100?

**Comment by Dingus997** [comment] 2024-07-20 04:42
> Duplicate of #85100?
oops

**Comment by Time-Green** [comment] 2024-07-20 09:03
Duplicate of #85100

**Closed by Time-Green** 2024-07-20 09:03 UTC
