### ISSUE TITLE
When Ventcrawling Everything Is Dark.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50444] opened 2020-04-07 00:51 UTC
## Round ID:
[134086](https://scrubby.melonmesa.com/round/134086)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
As anything that can ventcrawl, Crawl into a vent, and when inside everything will be dark, no matter how bright it is outside the vent.
![image](https://user-images.githubusercontent.com/56656478/78618079-632b1380-7847-11ea-814f-d8f5063d17c7.png)

**Comment by Trumpetplaya288** [comment] 2020-04-07 04:44
this makes sense what

**Comment by Iamgoofball** [comment] 2020-04-07 12:15
this is definitely a bug but goddamn, good accidental feature tbqh

**Comment by TemporalOroboros** [comment] 2020-04-07 20:53
Can we figure out how this works and keep it?

**Comment by Iamgoofball** [comment] 2020-04-07 22:27
agreed

**Comment by LemonInTheDark** [comment] 2020-04-08 07:07
Yeah uh this is my fault, I know what caused it too.

You see that black overlay there? That's not default, we need to apply that at the hud level.
We used to only do this for humans, because god hates me.
I moved it to default, because I wanted to stay as far away from hud code as I could.

This means a lot of things that used to be well darkish are now black. Nothing out of scope I don't think, I kinda expected something like this, wasn't too sure on what it would cause though.
#49919

**Comment by ShibaInuLord** [comment] 2021-01-27 00:03
i think this has been fixed already

**Comment by ShibaInuLord** [comment] 2021-02-04 16:12
never mind, this is not fixed, slimes have the same issue

**Comment by distributivgesetz** [comment] 2023-09-22 20:51
cannot reproduce anymore @Sealed101 
![image](https://github.com/tgstation/tgstation/assets/47710522/7da42c29-249f-4845-84f6-5f33da03bad6)

**Closed** 2023-09-22 21:06 UTC
Labels: Oversight, Cleanup Flagged
