### ISSUE TITLE
Double-barreled shotgun sprite still doesn't update properly

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#15799] opened 2016-02-27 21:09 UTC
### What revision did the problem happen on? (Helpful, but not required)

I'm not filling this out because this was supposed to be fixed

**Comment by Shapsy** [comment] 2016-02-27 21:22
Assuming this is about sawing them off, they don't work for riot shotguns either

**Comment by Zilenan91** [comment] 2016-02-27 21:23
It's not. I never sawed mine off and it reverted to the default skin.

**Comment by Zilenan91** [comment] 2016-02-27 21:45
I also don't remember the exact moment this happened, only that I set it to the Ash Gray skin and then a while passed and when I looked back again it was on the default.

**Comment by bgobandit** [comment] 2016-02-27 23:21
Could you be specific about which sprites and skins this involves?

**Comment by Zilenan91** [comment] 2016-02-28 00:00
Ash Grey double barreled shotgun, I think it happened when I reloaded it.

**Comment by Cheridan** [comment] 2016-05-24 22:19
duplicate of that other one

**Closed by Cheridan** 2016-05-24 22:19 UTC
Labels: Bug, Sprites
