### ISSUE TITLE
TTV + Health Sensor doesn't work, buggy

### ISSUE THREAD

**Issue by 13spacemen** [tgstation/tgstation#85629] opened 2024-08-05 14:38 UTC
## Issue Summary
A person with a health sensor set to ON and DEAD attached to a TTV

TTV is cavity implanted in chest

kill person, TTV does not go off

if you take the TTV out via surgery and put it in him while he's dead, it WILL activate and blow

but it's supposed to process constantly and check your health, so this is a bug

## Round ID:
N/A happens on local too

**Comment by Runi-c** [comment] 2024-08-05 19:41
I couldn't reproduce this on local, the health sensor blew up the TTV as expected

<details>

<summary>Logs</summary>

```
[2024-08-05 19:27:31.681] ATTACK: Raconitrus/(Grover) (mob_3011) attached a health sensor to a ttv - tank transfer valve at Grand Surgery Theatre (46,72,2). (Grand Surgery Theatre (46,73,2))
[2024-08-05 19:27:43.069] GAME-COMPAT: ADMIN: Raconitrus/(Grover) healed / Revived *no key*/(Vistha-Xal).
[2024-08-05 19:28:14.547] ATTACK: *no key*/(Vistha-Xal) (mob_3084) suffered: Open Laceration to head | Damage: 15 (rolled 31/44.3127) | WB: 15 | BWB: 10 (Grand Surgery Theatre (46,75,2))
...murder snipped...
[2024-08-05 19:28:26.600] GAME-EMOTE: *no key*/(Vistha-Xal) (mob_3084) seizes up and falls limp, her eyes dead and lifeless... (Grand Surgery Theatre (46,75,2))
[2024-08-05 19:28:26.604] ATTACK: Raconitrus/(Grover) (mob_3011) attacked *no key*/(Vistha-Xal) with circular saw (COMBAT MODE: 1) (DAMTYPE: BRUTE) (NEWHP: -110.4)  (Grand Surgery Theatre (46,74,2))
[2024-08-05 19:28:27.577] GAME: Bomb valve opened in Grand Surgery Theatre (46,75,2) with the health sensor attached by <a href='?priv_msg=raconitrus'>Raconitrus</a>/(Grover) - Last touched by: <a href='?priv_msg=raconitrus'>Raconitrus</a>/(Grover)
[2024-08-05 19:28:29.582] GAME: /obj/item/tank/internals/oxygen exploded with a power of 231.346 and a mix of "TEMPERATURE: 1544.11K, QUANTITY: 197.675 mols, VOLUME: 140L; o2=179.56 mols;plasma=16.4251 mols;co2=1.26777 mols;water_vapor=0.422589 mols;"
[2024-08-05 19:28:29.583] GAME: Explosion with size (5, 10, 20, 0) in (Grand Surgery Theatre (46,75,2)).  Possible cause: the oxygen tank. Last fingerprints: *null*.
```

</details>

**Comment by Sadboysuss** [comment] 2024-08-05 19:51
please reproduce your issue by making a video or providing new reproduction steps, it will be auto closed in 7 days, unless you can do that since we can't reproduce it.

**Comment by Artemchik542** [comment] 2024-08-07 09:42
Everything works fine, but when you connect the health sensor to the TTV, it somehow deactivates it, so you have to activate it again and only then implant it.
I also found that some devices (including health sensors) are not showing up on TTV (as green squares). I'm going to report a new issue.

**Closed** 2024-09-17 05:57 UTC
Labels: Bug, Needs Reproducing, Cleanup Flagged
