### ISSUE TITLE
twohanded items fuck with extra hands

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#45983] opened 2019-08-17 09:40 UTC
## Reproduction: 1. give yourself 4 hands 2. spawn a fire axe/ other 2handed item 3. wield it 4. try to change hands to your other 2 spares 5. watch as it doesnt work

![image](https://user-images.githubusercontent.com/53100513/63209638-d6fe8d00-c0b9-11e9-9598-e0d484955719.png)

**Comment by timothymtorres** [comment] 2022-12-21 11:17
So multihand support is a _stagnate feature_ that requires admin hacks to enable in game.  Some of the code in our codebase supports it, other parts do not.  Allowing bug reports for stuff like this is a slippery slope, especially considering we have +1700 bug reports for things that need to be fixed for **normal gameplay**.

Marking this as `Not a bug` since this feature is not obtainable under normal circumstances and requires hacks to work.

**Closed** 2022-12-29 00:05 UTC
Labels: Not a bug, Cleanup Flagged
