### ISSUE TITLE
Borg panel scrambled codes and unsyncing from AI does not remove it from AI synced borgs

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37467] opened 2018-04-26 21:48 UTC
Issue reported from  Round ID: 87068 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Still shows up under the AI status tab.

Also still shows up in camera list.

**Comment by DaxDupont** [comment] 2018-04-26 21:50
@vuonojenmustaturska

**Comment by Anonmare** [comment] 2018-04-27 00:34
>if(!R.shell)
>				R.UnlinkSelf()
>R.module.rebuild_modules()

Wouldn't that do the trick?

**Comment by timothymtorres** [comment] 2021-08-19 13:30
Duplicate of #44349

**Closed** 2021-08-19 13:30 UTC
Labels: Bug
