### ISSUE TITLE
Secret sauce recipe didn't work

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62971] opened 2021-11-20 12:07 UTC
## Testmerges:

The following pull requests are currently test merged:
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit dc963ca82a

## Reproduction:
https://puu.sh/Iqofu/4cb6f89b05.png
https://images-ext-1.discordapp.net/external/y9CfB9O8bRD7xdsp83IfbYF4Qw8B5g-FN5gPzdJch7M/https/puu.sh/IqoeJ/fcb146e71f.png

Exact recipe gotten in the same round as it was attempted. heated 1 degree above 579 then cooled 1 degree below with all required chems in a bucket and no secret sauce resulted. It might not be possible to make any recipes?

**Comment by SuperNovaa41** [comment] 2021-11-20 13:58
WOAHHH THIS GUYS LEAKING THE SECRET SAUCE???

**Comment by timothymtorres** [comment] 2021-11-20 20:13
Duplicate of #62824

**Closed by timothymtorres** 2021-11-20 20:13 UTC
