### ISSUE TITLE
Xenobio Blobbernauts can harm blobs, but not vice versa.

### ISSUE THREAD

**Issue by RogueSteampunker** [tgstation/tgstation#32440] opened 2017-11-05 14:51 UTC
Issue reported from Round ID: 78379 (Sybil)

#78379
Turns out that Blobs can't harm xenobio created Blobbernauts, allowing the xenobio Blobbernaut to destroy Blob turf with ease, and travel straight to the blob core.

**Comment by Jordie0608** [comment] 2017-11-05 14:57
Duplicate of #32439

**Closed by Jordie0608** 2017-11-05 14:57 UTC
