### ISSUE TITLE
Cyborg Omnitools Don't Work On Door Wires And Can Be Lathed

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#84600] opened 2024-07-03 00:14 UTC
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/3894717/96d948e2-0010-4fd2-afa4-71201b95bc10)

![image](https://github.com/tgstation/tgstation/assets/3894717/054c8cfe-ebec-44b7-8f86-ecb678b5d51d)

Not sure if #84341 moving it onto the attack chain or what, but it :b:roke. 

Also, cyborg omnitools like screwdrivers/wires/multis can be fed to a lathe. Seems like surgery tools are missing some interactions as well. 

## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [231520](https://scrubby.melonmesa.com/round/231520)
BYOND Version: 515.1637
Server revision compiled on: 
Master commit: [24c3fcc47467d135edb88d3d9aa7701af4d83995](https://www.github.com/tgstation/tgstation/commit/24c3fcc47467d135edb88d3d9aa7701af4d83995)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:

1. Be cyborg.
2. Try to use wirecutters/multitool on wires in door with an open panel with the omnitool active.
3. "You need X."

also

1. Use omnitool on lathe.
2. Goodbye omnitool.

**Comment by dalmationer** [comment] 2024-07-03 00:19
Quick clarification, the omnitool bug is even stranger-- it actually eats specifically the tool you were using, not the whole omnitool. E.g. in the round above, I used my screwdriver tool on the machine to open it, and it left a 'ghost' screwdriver tool in my inventory. when I opened my two omnitool arms, I found that the screwdriver tool was missing from both, but the other tools were there.

**Comment by SyncIt21** [comment] 2024-07-03 03:01
These are 2 seperate issues.

For the airlock wires it's a duplicate of #84359.

So remove that and keep only the lathe issue.

**Closed** 2024-07-05 18:00 UTC
Labels: Bug
