### ISSUE TITLE
It's possible to put a bluespace bodybag in itself

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#38629] opened 2018-06-20 17:49 UTC
Issue reported from  Round ID: 89779 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Reproduction: 
Get bluespace bodybag and backpack
Place backpack over bodybag
Clickdrag backpack to yourself to open its storage
Close and pick up bodybag
Put it in the storage you're viewing (the backpack)

**Comment by Cyberboss** [comment] 2018-06-20 18:07
@kevinz000

**Comment by DaxDupont** [comment] 2018-06-20 18:57
Related to #38189?

**Comment by SpaceManiac** [comment] 2018-06-20 20:30
not exactly a duplicate but the fix would be the same, perform a .loc check during storage insertion to make sure you're not putting an item inside itself

**Comment by Dennok** [comment] 2018-06-21 00:31
Just need close UI of all what moved to container.

**Comment by SgtxRootbeer** [comment] 2018-06-21 16:23
![eve_knowledge](https://user-images.githubusercontent.com/22112255/41732012-c300696c-7534-11e8-9167-d5a0eb3bc02d.jpg)

**Comment by Notamaniac** [comment] 2018-06-24 10:15
Such a topological exercise

**Comment by AlexTheSysop42** [comment] 2018-06-30 13:47
Pretty sure this was fixed

**Comment by moonheart08** [comment] 2018-11-05 14:11
That would be an interesting topological exercise --Nethack
Feature, bluespace is magic. /s

**Comment by ArcaneMusic** [comment] 2021-08-06 17:17
I have confirmed... on August 6th, the year of our lord 2021, on the /tg/station github, that this issue appears to have been fixed by some of the previous issues caused by backpacks and bodybags closing their inventory screen when placed in sub level contents.
@silicons I'm happy to say... you have finally fixed all your shit.

**Closed by ArcaneMusic** 2021-08-06 17:17 UTC
Labels: Bug
