### ISSUE TITLE
Welding Damaged Plating Doesn't Remove Damaged Overlay

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#68609] opened 2022-07-20 18:19 UTC
Reporting client version: 514.1585

## Round ID:
[186982](https://scrubby.melonmesa.com/round/186982)

## Testmerges:
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:
See title. Weld damaged plating. Damaged appearance isn't reverted, but still functionally works.

**Comment by timothymtorres** [comment] 2022-07-20 23:06
Duplicate of #68133

**Closed by timothymtorres** 2022-07-20 23:06 UTC
