### ISSUE TITLE
Poly said something odd

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#48591] opened 2020-01-05 01:13 UTC
Overheard Poly say this while playing as AI:

`[Engineering] Poly (Unknown) says, "[02:31] <span class='game say'><span class='name'>Flowunk</span> <span class='message'>flutters, "<span class=' '>Three tier of suit sensors</span>"</span></span>`

That is to say, it was left unformatted by my client

Issue reported from  Round ID: 127456 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

**Comment by spessbandit** [comment] 2020-01-05 03:03
same issue as https://github.com/tgstation/tgstation/issues/36758

**Comment by PKPenguin321** [comment] 2020-01-05 03:08
Dupe of #36758

**Closed by PKPenguin321** 2020-01-05 03:08 UTC
