### ISSUE TITLE
Bluespace crystals can be used on the centcomm z-level

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46802] opened 2019-09-29 10:34 UTC
Issue reported from  Round ID: 120340 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1485

To reproduce:

Be nukie

Buy a briefcase launchpad for 6 tc

Shoot it apart after deploying it with your pistol

get a free bluespace crystal

Use it inhand

Get lucky and get out of the ship

Rinse and repeat until you are inside of centcomm

**Comment by spessbandit** [comment] 2019-09-29 17:55
can't reproduce

**Comment by Tharcoonvagh** [comment] 2019-09-29 19:25
Close issue, dupe

**Comment by Tharcoonvagh** [comment] 2019-09-29 19:26
Dupe

**Comment by Detective-Google** [comment] 2019-09-30 02:20
I'll give this a test real quick and close if necessary.

**Comment by Detective-Google** [comment] 2019-09-30 02:28
![image](https://user-images.githubusercontent.com/48196179/65845474-054dca00-e300-11e9-8f8e-8cbf8552ede3.png)
this totally does work but you would have to spend a lot of TC/be very lucky

**Comment by Detective-Google** [comment] 2019-09-30 02:29
closing this PR since it's a dupe of #31429

**Closed** 2019-09-30 02:29 UTC
Labels: Bug, In Game Exploit, Needs Reproducing
