### ISSUE TITLE
Strange shadow effect with statues

### ISSUE THREAD

**Issue by JohnFuckingMooney** [tgstation/tgstation#61257] opened 2021-09-05 18:13 UTC
Reporting client version: 514.1566

## Round ID:
[169062](https://scrubby.melonmesa.com/round/169062)

## Testmerges:
- [FAMILIES 4.0: "fuck it, MRP only this time"](https://www.github.com/tgstation/tgstation/pull/61123)

## Reproduction:

-When a statue is carved from the goliath statue found on the mining base it creates a strange shadow overlay. This overlay is linked to the actual way the original statue is facing

![image](https://user-images.githubusercontent.com/33187585/132137113-30228101-c28c-42bb-8af1-2e5d5abc72c8.png)

![image](https://user-images.githubusercontent.com/33187585/132137117-ffba1805-7c73-4515-9474-28202cb17969.png)

![image](https://user-images.githubusercontent.com/33187585/132137118-ccb4a484-4891-428c-b9fc-682316a7a6ff.png)

![image](https://user-images.githubusercontent.com/33187585/132137124-da002b37-c499-42e7-a054-1fbd946528e6.png)

**Comment by benman347** [comment] 2021-09-05 18:18
might be caused by the same thing as https://github.com/tgstation/tgstation/issues/61228

**Comment by benman347** [comment] 2021-09-05 18:20
hmm on second thought might even be the exact same problem

**Comment by ArcaneDefence** [comment] 2021-09-05 18:23
Duplicate of https://github.com/tgstation/tgstation/issues/61228

**Closed by ArcaneDefence** 2021-09-05 18:23 UTC
