### ISSUE TITLE
Microwaves stuck on "cooking" when power is lost

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#51915] opened 2020-06-29 15:23 UTC
Hi!

On the off-chance that you're using the microwaves in the kitchen as soon as there is a power loss, the microwave will remain active and cooking that item forever, without being able to unload it or turn it off, even if power is restored. Tools also don't seem to work.

Sorry, I have no pictures of this as it didn't occur to me how to show the passage of time in this case.

**Comment by rdragan** [comment] 2020-07-02 09:54
Dupe of #51866

**Closed by rdragan** 2020-07-02 09:54 UTC
