### ISSUE TITLE
Some things can't be seen with cameras

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23342] opened 2017-01-26 03:06 UTC
Read: Windows for one.
Also it's mob detection is a crappy text string but that's not a bug. Honk.

**Comment by PKPenguin321** [comment] 2017-01-26 03:11
Can almost guarantee this is a dupe, it has been around since the dawn of time itself

Some things also have their rotation broken, such as crayon drawings

**Comment by kevinz000** [comment] 2017-01-26 03:56
Hmmmm.....

**Comment by Cyberboss** [comment] 2017-01-26 05:11
Dupe of #7092

**Closed** 2017-01-26 05:22 UTC
