### ISSUE TITLE
The Requisite to Buy The "The Arena" Shuttle Cannot Be Met

### ISSUE THREAD

**Issue by ripandtearr** [tgstation/tgstation#41265] opened 2018-10-31 19:48 UTC
## Reproduction:

Spawn in, kill bubblegum. Get $10,000 in the station budget and try to buy the shuttle called "The Arena", which is meant to be unlocked by killing Bubblegum.
Observe as the game spits out: "You have not met the requirements for purchasing this shuttle."

The code that is supposed to do this is:
`/mob/living/simple_animal/hostile/megafauna/bubblegum/grant_achievement(medaltype,scoretype)
	. = ..()
	if(.)
		SSshuttle.shuttle_purchase_requirements_met |= "bubblegum"`

I'm not a coder, dunno what the problem is exactly.

**Comment by ripandtearr** [comment] 2018-11-01 00:52
Also, another possible bug (?) is the fact that bubblegum is not a guaranteed spawn on lavaland

**Comment by Borisvanmemes** [comment] 2018-11-01 00:53
hi this is just a guess but i think the issue might be that one puzzle ruin that was added a while back, after killing bubblegum and solving it he respawns afaik, he might count as alive before the puzzle is even solved, which is why you might not be able to buy the arena.

**Comment by ripandtearr** [comment] 2018-11-01 00:54
Not sure about that, I tried on like 4 different reboots.

**Comment by Barhandar** [comment] 2018-11-01 12:54
Dupe of #41218. Also, the puzzle ruin is not relevant to this because the shuttle is for killing him, not for having him be dead.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-11-01 15:40
so is this a bug on the server or just on the local repo where medals don't exist

**Comment by ripandtearr** [comment] 2018-11-01 19:54
I tried this on the server and can confirm the shuttle is buyable there

**Comment by SpaceManiac** [comment] 2018-11-02 19:41
Duplicate of #41218

**Closed by SpaceManiac** 2018-11-02 19:41 UTC
