### ISSUE TITLE
Console screen overlays can be placed/open above screen height, and are consequently impossible to close or move

### ISSUE THREAD

**Issue by C0NTR** [tgstation/tgstation#19481] opened 2016-07-24 21:28 UTC

**Comment by C0NTR** [comment] 2016-07-24 21:31
http://imgur.com/a/cF47u
screenshot of problem

**Comment by AnturK** [comment] 2016-07-25 06:49
Temporary solution : Enable no frills when playing on low resolution.

**Comment by timothymtorres** [comment] 2021-08-23 10:43
Duplicate of #5193

**Closed by timothymtorres** 2021-08-23 10:43 UTC
Labels: Bug
