### ISSUE TITLE
Cyborgs can be selected for changeling identity theft objectives

### ISSUE THREAD

**Issue by actioninja** [tgstation/tgstation#45977] opened 2019-08-17 00:26 UTC
Issue reported from  Round ID: 116166 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

This was reported and then instantly closed a while ago, not sure why because this just happened in a live round.
![image](https://user-images.githubusercontent.com/5194834/63204279-e692bd00-c04a-11e9-81ae-b1c353b2c512.png)

**Comment by kriskog** [comment] 2019-08-17 02:23
This is just on round end right? The changeling should still have the human name as their objective.
Anyhow, this is a dupe of #40667.

**Closed by kriskog** 2019-08-17 02:23 UTC
