### ISSUE TITLE
PREVENT_CONTENTS_EXPLOSION_1 flag doesn't work for nested storage (i.e. photo albums in inventory)

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#49986] opened 2020-03-15 21:14 UTC
The PREVENT_CONTENTS_EXPLOSION_1 flag is supposed to protect items inside of the object against explosions.

This works correctly if the object is on the floor but **if the item is contained within any other inventory (inside a backpack on the floor, in the hands of a mob, in a backpack worn by a mob etc.) the contents will still be damaged.**

How to replicate:
1. Take a picture and put it in a photo album
2. Put photo album in backpack
3. Light up an IED and wait for it to explode (keep it in your hands or at least on the same tile)
4.Check the integrity of the photo, if it still exists

**Comment by Mickyan** [comment] 2020-03-23 15:41
It seems like the flag is only checked on atoms that are directly affected, so if you get hit by an explosion while the album is in your inventory the flag is only checked on the mob itself

https://github.com/tgstation/tgstation/blob/6401ba57081efb3db2f39320eeefeb13c1be4d8c/code/datums/explosion.dm#L197-L206

**Comment by kriskog** [comment] 2020-03-23 16:51
GetAllContents would also get the contents of contents, and act on it. So even if one of the storages inside for example your backpack is flagged, GetAllContents would already have gotten it.

Probably need to write a new proc to replace GetAllContents here, that takes this into account.

**Comment by ShizCalev** [comment] 2020-04-04 23:33
duplicate of #49232

**Closed by ShizCalev** 2020-04-04 23:33 UTC
Labels: Bug
