### ISSUE TITLE
Pubbystation EMS shuttle docking with Delta Station causes purest form of comedy

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62922] opened 2021-11-18 01:22 UTC
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [173214](https://scrubby.melonmesa.com/round/173214)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: a41c00426dbb63f1e88b512fd9270b29ff1e4926
The following pull requests are currently test merged:
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit dc963ca82a

Local commit: 46c7e5c4f6d3f0b859b9fdd5dbf315382e8a8ecd
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:
1. Have Pubby EMS shuttle dock with Delta station
2. Listen for the [laugh track](https://www.youtube.com/watch?v=J83lw0eFIJA) as it gibs an innocent chemist upon docking because it intersects the station (I feel like unless the station is rocking a meme shuttle that it should be avoided to have the shuttle crush parts of the station, no?)
![image](https://user-images.githubusercontent.com/14065903/142333451-017f60ad-5e58-4e34-abf1-37cef791511c.png)

**Comment by Sealed101** [comment] 2021-11-18 21:19
the map is delta, not icebox

**Comment by NanoCats** [comment] 2021-11-18 21:20
> the map is delta, not icebox

I could swear I typed Delta, maybe I really do have dementia, forgive me.

**Comment by Zytolg** [comment] 2021-11-20 04:28
Unfortunately this is just one of the intrinsic problems of using a different shuttle from the station default. That being said, Delta Departures should probably be remapped so long as the remap doesn't prohibit other shuttles from spawning.

**Comment by Son-of-Space** [comment] 2022-04-24 02:48
This is not an issue. Some shuttles do crash into the station.

**Comment by timothymtorres** [comment] 2022-05-12 05:11
@NanoCats based on what others are saying I'm marking this as `Not a bug` and `Cleanup` that will autoclose this in 7 days.

**Closed** 2022-05-20 00:16 UTC
Labels: Not a bug, Cleanup Flagged
