### ISSUE TITLE
Trying to Open Crafting Menu gives the following error

### ISSUE THREAD

**Issue by CAPTTLasky** [tgstation/tgstation#48200] opened 2019-12-10 17:41 UTC
Issue reported from  Round ID: 125508 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

yntaxError: Syntax error
   at Anonymous function (http://127.0.0.1:63549/tmp2756/tgui.bundle.js:1:81958)
   at window.initialize (http://127.0.0.1:63549/tmp2756/tgui.bundle.js:1:81804)
   at eval code (eval code:1:1)

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

Nanotrasen (c) 2525-2559

**Comment by CAPTTLasky** [comment] 2019-12-10 17:41
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm, get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation.

**Comment by spookydonut** [comment] 2019-12-10 18:09
Duplicate of #48198

**Closed by spookydonut** 2019-12-10 18:09 UTC
