### ISSUE TITLE
Derelict drone isn't included in ghost spawners menu

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36657] opened 2018-03-23 11:13 UTC
Revision: 80f6e451fc297d5adb3c443862bbcec8ea2c360b

The russkie derelict drone (/obj/item/drone_shell/dusty) doesn't show up in the ghost spawners menu.

**Comment by YPOQ** [comment] 2018-03-23 14:53
#30379

**Comment by ShizCalev** [comment] 2018-03-25 05:28
Duplicate of #30379

**Closed by ShizCalev** 2018-03-25 05:28 UTC
