### ISSUE TITLE
Cult Spells are all invisible

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#43061] opened 2019-03-08 05:08 UTC
## Reproduction:
Title. _Every_ cultist has an invisible stunhand/other spells now so you can't even differ them from regular crew before they reach red eyes/halos or obvious loud cult gear.

**Comment by py01** [comment] 2019-03-08 08:22
dupe #42605

**Comment by AnturK** [comment] 2019-03-08 10:34
Duplicate of #42605

**Closed by AnturK** 2019-03-08 10:34 UTC
