### ISSUE TITLE
New areas (created with station blueprints) have an aura of impenetrable darkness

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#63637] opened 2021-12-26 13:36 UTC
## Round ID:
[175470](https://scrubby.melonmesa.com/round/175470)

## Testmerges:
?

## Reproduction:
Conditions: new area created on station, in space, with atmos holofans instead of airlocks as the border of the room. The darkness appeared immediately upon creating the area, even before the holofans were removed.
![dark](https://user-images.githubusercontent.com/68878861/147409708-55d617f6-8b44-4863-bceb-12b4f2fc5278.png)
**Area is functionally broken for anyone without mesons or maybe night vision.**
![dark2](https://user-images.githubusercontent.com/68878861/147409740-a67ff4b1-1e5f-482f-84a9-e3ccaf2a336f.png)
This can be fixed neither by introducing a regular lightsource (floodlight, even if wrenched and activated inside) nor glowing floor tiles (2nd image).

![obraz](https://user-images.githubusercontent.com/68878861/147409899-fef7e122-8ea9-4717-bb55-e71d5fceffd5.png)
It can however, be partially fixed with items projecting light in a cone,

**Comment by LemonInTheDark** [comment] 2021-12-26 19:30
the fuck

**Comment by interestingusernam3** [comment] 2021-12-26 20:52
How

**Comment by Likteer** [comment] 2021-12-26 22:02
Reproduced a few more times in the same spot

**Comment by Serxule** [comment] 2021-12-27 04:10
this has been happening pretty much everywhere, not specifically new areas

**Comment by LemonInTheDark** [comment] 2021-12-27 04:20
I assume you mean #60443, which isn't this

**Comment by timothymtorres** [comment] 2021-12-27 11:09
It could be related to #62993 (and tbh that issue might be a dupe of #60443)

**Comment by LemonInTheDark** [comment] 2021-12-27 21:08
I think they're separate troubles? #60443 seems to be somehow something like a client side issue, and it goes away when the tile is updated. This is totally the same as #62993 though, in that it happens when an area is created over space

**Comment by Mooshimi** [comment] 2021-12-28 17:24
>This is totally the same as #62993 though, in that it happens when an area is created over space

Consider this merged with the above issue then, if it's the same

**Closed by Mooshimi** 2021-12-28 17:24 UTC
Labels: Bug
