### ISSUE TITLE
PAI Linear Sustain/Exponential Sustain Settings broken for the Loudness Booster.

### ISSUE THREAD

**Issue by Redrover1760** [tgstation/tgstation#67566] opened 2022-06-06 03:17 UTC
## Round ID: 
[184421](https://scrubby.melonmesa.com/round/184421)

## Testmerges:
https://github.com/tgstation/tgstation/pull/67307
https://github.com/tgstation/tgstation/pull/67385

## Reproduction:

Import a song, any song, and then attempt to adjust the linear sustain or exponential sustain.
For linear sustain
IF you attempt to change it to something with a decimal (like .2) it will instead make it 2. In fact, just try to mess around with it and cry as it fails to recognize decimals at all and how annoyingly you have when your only options for sustain is 0, 1, 2, 3, 4, or 5. Outside it default starting at .5, you can't change it to any other decimal based number.

**Comment by timothymtorres** [comment] 2022-06-19 11:52
Duplicate of #64992

**Closed by timothymtorres** 2022-06-19 11:52 UTC
