### ISSUE TITLE
Surgery operating computers dont work on box

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51722] opened 2020-06-18 08:53 UTC
## Round ID:
#139858

## Testmerges:
#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#51515: 'A New Medbay for Boxstation' by Maurukas at commit 987b7a9a22

## Reproduction:
See title, both surgery room consoles weren't detecting the corpse while it was on the surgery table. Nor did resetting the console with a screwdriver work either.
![Capture](https://user-images.githubusercontent.com/32374784/84999310-d681b900-b105-11ea-8855-85ceb5b878fb.PNG)

**Comment by Maurukas** [comment] 2020-06-18 17:39
I'm not able to immediately reproduce this locally, but I will try again after I resolve the current merge conflicts.

**Comment by ShizCalev** [comment] 2020-06-18 23:11
@Maurukas try with #51515 merged

**Comment by Maurukas** [comment] 2020-06-19 00:03
@ShizCalev I am doing so, that is my PR.

**Comment by ShizCalev** [comment] 2020-06-19 19:35
@Maurukas Er, sorry, meant #51412

**Comment by dragomagol** [comment] 2020-11-22 21:57
Unable to reproduce.

**Closed by dragomagol** 2020-11-22 21:57 UTC
Labels: Bug
