### ISSUE TITLE
Forcefeeding is instant.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#73255] opened 2023-02-05 17:04 UTC
## Testmerges:

[#73206: 'the inevitable Revert "Refactors admin verbs from giant ass lists into datums" in case stuff breaks' by Mothblocks at commit 21d1f6f0f9](https://www.github.com/tgstation/tgstation/pull/73206)

## Reproduction:
1) Take a bottle with whatever you want.
2) Use the bottle on a victim of your own choice.
3) There is a very fast progress bar, that does not matter at all.
4) Congratulations, you have forcefed a person!

**Comment by Sealed101** [comment] 2023-02-05 17:10
dupe of #73198

**Closed** 2023-02-05 17:11 UTC
