### ISSUE TITLE
Can not eject equipment out of mechs.

### ISSUE THREAD

**Issue by CreationPro** [tgstation/tgstation#39200] opened 2018-07-18 00:45 UTC
Issue reported from  Round ID: 91178 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

While inside an exosuit, click "detach" next to a piece of equipment. Doesn't work.
Checked in a Ripley, firefighter ripley, Gygax, Durand AND Phazon.

**Comment by SpaceManiac** [comment] 2018-07-18 03:21
Duplicate of #39137

**Closed by SpaceManiac** 2018-07-18 03:21 UTC
