### ISSUE TITLE
TTS audio appears to not account for Z coordinates

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#76142] opened 2023-06-18 20:42 UTC
Reporting client version: 514.1589

## Round ID:
[208495](https://scrubby.melonmesa.com/round/208495)

## Testmerges:
- [A small pile of borg combat changes](https://www.github.com/tgstation/tgstation/pull/75819)
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)

## Reproduction:

1. Be ghost or any other TTS-hearing mob
2. Be on a tile that has a commonly-travelled equivalent on say, Z-4 or Z-1, on the main station at the same position
3. Hear conversations that are quite literally on the other side of the universe
4. how the fuck did you not account for position

**Comment by Y0SH1M4S73R** [comment] 2023-06-19 08:12
Duplicate of #75770

**Closed** 2023-06-21 16:14 UTC
