### ISSUE TITLE
+potency anti-glow makes you glow

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51367] opened 2020-05-29 09:07 UTC
![image](https://user-images.githubusercontent.com/42606352/83242352-df641800-a161-11ea-9c17-ca0cd480738a.png)

test your PRs, nemvar

**Comment by ATH1909** [comment] 2020-05-29 09:08
this isn't the best example, but even in maint tunnels with all of my lights off, I was actively emitting light, IIRC

**Comment by ArcaneDefence** [comment] 2020-05-29 09:09
https://github.com/tgstation/tgstation/issues/51364
This was also posted literally 2 issues ago.

**Comment by Time-Green** [comment] 2020-05-29 09:14
Duplicate of #51364

**Closed by Time-Green** 2020-05-29 09:14 UTC
