### ISSUE TITLE
Can't Eject Materials from Charlie Station Lathe

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#46235] opened 2019-08-29 17:51 UTC
## Round ID: 117351

You can't eject materials. I put too much metal and glass in, and had to just spam make a ton of stock parts to free up space for other mats. If you click eject nothing happens.

**Comment by kriskog** [comment] 2019-08-30 02:41
dupe of  #45505

**Closed by kriskog** 2019-08-30 02:41 UTC
