### ISSUE TITLE
Trays are unable to carry Normal Sized items, when in the past they could. 

### ISSUE THREAD

**Issue by BigGrease** [tgstation/tgstation#54207] opened 2020-10-06 03:50 UTC
Issue reported from  Round ID: [147743](https://scrubby.melonmesa.com/round/147743) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1532

I don't know if its a bug or something someone changed intentionally, but it limits the actual function of the tray. Botanists deserve plant bags, so I don't know why cooks get the short end of the stick with a barely functioning item to carry bulk items when we have to process and move a similar number of items to do our job right.

**Comment by PKPenguin321** [comment] 2020-10-06 04:12
Dupe of https://github.com/tgstation/tgstation/issues/54113

**Comment by BigGrease** [comment] 2020-10-06 04:29
oh yeah. also, I talked to flyod and he said he'd make some items smaller so they can fit on trays so depending on how extensive that is i guess i'd be happy

**Comment by msgerbs** [comment] 2020-10-06 06:13
Duplicate of #54113

**Closed by msgerbs** 2020-10-06 06:13 UTC
Labels: Oversight
