### ISSUE TITLE
BoH Bombing eats Nar'sie

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#48017] opened 2019-11-27 05:20 UTC
I'm like 99% sure this is unintentional because the round's effectively over once Narnar is summoned. That being said it *does* force a shuttle call/Delta and effectively ends in success for the cult anyway, so... I dunno. It's funny but kinda lame for the cult. Thoughts?

**Comment by PKPenguin321** [comment] 2019-11-27 05:42
Dupe of https://github.com/tgstation/tgstation/issues/48012

**Closed by PKPenguin321** 2019-11-27 05:42 UTC

**Comment by Taylorkills2** [comment] 2019-11-27 05:43
No, BoH bombing killing it is intentional, or at least it's the desired outcome according 
 to PKPenguin321.
Though if Narsie is deleted/dies it should probably cancel the nuke but still force a shuttle call since it can have Harvesters running around. And it should count as a Major Defeat for the Blood Cult, as the deity was banished back to it's realm if not outright killed(though if it was completely defeated all the cult constructs should die and soulstoned cultists should lose their cultist alignment and cult soulstones become the Lavaland Equivalent Soulstone.
Also I believe from the fact cult constructs were still getting the "Summon Narsie" objective Narsie could probably be summoned again if normal cultist was revived.
That actually sounds like a good bit a changes though.

Also if Narsie is BoH bombed it'll keep spawning Harvesters after it's death(though I believe only for a short time), probably for the best it doesn't do that if it gets changed to be a loss for the cult.
