### ISSUE TITLE
Mechs in maintenance are unable to drop capacitors and scanners

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#71577] opened 2022-11-28 02:17 UTC
Reporting client version: 514.1589

## Round ID:
[195209](https://scrubby.melonmesa.com/round/195209)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:
When you put a mech into maintenance mode there's an ability to swap out the previous scanner and capacitor for a different one, however dropping the two parts doesn't seem to work. Only the power cell seems to drop properly.

1. Get a mech.
2. Toggle maintenance mode and toggle stock part replacement
3. Wrench, crowbar.
4. Click on the corresponding button to drop the parts.
5. Succeed in dropping the power cell
6. Fail to drop the scanner and capacitor.

**Comment by SyncIt21** [comment] 2022-11-29 10:45
After you eject the power cell use crowbar to close the hatch to the power cell unit, then you can eject the capacitor & scanning module. To insert it back use crowbar to again open the power hatch unit & then you can insert all 3 components. 

In other words, you can remove other components while the power cell is still inside as you will get electrocuted [that was the idea] so after removing the cell & closing the unit you can remove other components.

Not a bug

**Comment by Ryusenshu** [comment] 2022-11-29 21:56
Mechs were changed in [#65375](https://github.com/tgstation/tgstation/pull/65375)

From a quick glance i found no notice of this change in the pr itself, only in code
![Screenshot_1](https://user-images.githubusercontent.com/95751821/204655615-f5034460-0e90-4dae-b714-ff928399dac6.png)
Its a undocumented change and i found no hint on some discussion for a reason to change this

So yes, I say its a bug

**Closed** 2023-04-04 04:16 UTC
Labels: Oversight
