### ISSUE TITLE
Glorfing Triggers word filter

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#80231] opened 2023-12-10 05:44 UTC
Reporting client version: 515.1620

## Round ID:
[220249](https://scrubby.melonmesa.com/round/220249)

## Testmerges:
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:

![image](https://github.com/tgstation/tgstation/assets/26270704/70041074-eddc-40c6-b847-999cbf7f2563)

**Comment by newfren** [comment] 2023-12-10 07:16
https://github.com/tgstation/tgstation/issues/78181 related? it also happens to social anxiety

**Comment by optimumtact** [comment] 2023-12-10 21:11
yeah this is a dupe of #78181

**Closed by optimumtact** 2023-12-10 21:11 UTC
