### ISSUE TITLE
Lavaland ate spawned explorer suits

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#19111] opened 2016-07-03 20:15 UTC
Seems that Lavaland generation caused the windows of the mining base to be breached, instantly burning roundstart Explorer suits.
This happened on Basil at around 21:15 GMT

![bug lavaland eats suits](https://cloud.githubusercontent.com/assets/7211040/16547373/41c87b70-4163-11e6-8b62-1bc0bd504657.png)

**Comment by MMMiracles** [comment] 2016-07-03 21:00
hardcore mode.

**Comment by Bawhoppen** [comment] 2016-07-14 06:49
Also a dupe

**Comment by optimumtact** [comment] 2016-07-14 09:27
dupe of #17450

**Closed by optimumtact** 2016-07-14 09:27 UTC
Labels: Bug, Map Issue
