### ISSUE TITLE
when a lightning stand dies while zapping someone it can potentially zap across the map

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#32987] opened 2017-11-22 02:12 UTC
![2017-11-21_19-08-56](https://user-images.githubusercontent.com/20155238/33104779-8aeb0686-ceef-11e7-8030-e6ffd9f067dc.png)
this was electrocuting people after the wizard and the stand were dead

**Comment by calzilla1** [comment] 2017-11-22 02:19
10/10

**Comment by MoreRobustThanYou** [comment] 2017-11-24 18:31
feature

**Comment by AverageJoe82** [comment] 2018-01-15 01:13
Is this possible to test with only one person?

**Comment by Ordonis** [comment] 2018-01-19 02:07
If the lightning is tied to the mob that fired it, then I could see how it might get stuck if it loses its instructions to fade out while active because the mob supplying it with that code is dead. That might be solved by turning lightning into its own object so that it can read its own instructions if the owner dies.

**Comment by KomradeSpectre** [comment] 2019-03-03 17:09
Potentially caused by the fact the holoparasite is manifested and moved to the user's remains upon death, but no sanity checks for stopping the effect proc from firing (until about a minute after the user's death? Something cleans it up after a minute, still have yet to figure what). The holoparasite is tied to a null client when it is moved via forcemove(summoner.loc), so the lightning chain goes to 0,0 from the location the holopara was qdel'd.

**Comment by kriskog** [comment] 2019-06-28 09:58
Fixed in #44278

**Closed by kriskog** 2019-06-28 09:58 UTC
Labels: Bug
