### ISSUE TITLE
Stone of flesh Hud shortcut staying red.

### ISSUE THREAD

**Issue by redpepperphoenix** [tgstation/tgstation#37660] opened 2018-05-04 04:03 UTC
Had a round as a wizard and wanted to make the crew into living statues. went in and noticed the button on the hud didn't work. was told that it works in verb. don't have the stuff needed to verify but you may test it.

Side note that I did have the gear on. could cast time stop.

**Comment by redpepperphoenix** [comment] 2018-05-04 04:05
thought it was a hand charge spell, said so on the spell book... is it not a hand charge spell and just a instant cast nearby?

**Comment by ShizCalev** [comment] 2018-05-04 20:02
Duplicate of #37074

**Closed** 2018-05-04 20:03 UTC
