### ISSUE TITLE
Examining IDs examines the associated player

### ISSUE THREAD

**Issue by MegaEmpirical** [tgstation/tgstation#43303] opened 2019-03-23 22:59 UTC
Exactly as title says, as if examining oneself. Potentially works on other people.

**Comment by 4dplanner** [comment] 2019-03-24 01:20
Seems to work fine on localhost

**Comment by Barhandar** [comment] 2019-03-24 07:15
Same problem as examining heads with the body in sight, BYOND gets the shortest match starting from beginning (i.e. if you have "George Melons" and "George Melons's Head" visible and examine head, it will examine the body). The ID thing is caused by the economy, and IIRC reported there too several times.

**Comment by MegaEmpirical** [comment] 2019-03-24 13:20
I was HoP at the time but I have seen this whilst playing as other jobs. I will note that I am a downstream server (Yogs).

**Comment by MegaEmpirical** [comment] 2019-03-24 14:25
I was able to replicate it, slightly. Examining it in my ID slot produced a self examine but previously I've been able to do it while it was on the floor.

**Comment by MegaEmpirical** [comment] 2019-03-24 14:40
Got it, Examines self when ID is in ID slot as well as when the PDA is in the ID slot but your ID is not.

**Comment by MegaEmpirical** [comment] 2019-03-24 15:50
Tested HoP downstream and it doesn't matter where my PDA is for it to act as self examine (this issue was not present when I was testing as assistant so it does seem to change with jobs). Not sure how it behaves upstream in TG.

**Comment by SpaceManiac** [comment] 2019-03-27 04:16
Duplicate of #40988

**Closed by SpaceManiac** 2019-03-27 04:16 UTC
Labels: Bug, In Game Exploit, Oversight
