### ISSUE TITLE
Clothing vendor colouring BSOD

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#77254] opened 2023-07-31 00:28 UTC
Reporting client version: 514.1589

## Round ID:
[211417](https://scrubby.melonmesa.com/round/211417)

## Testmerges:
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Screentip images](https://www.github.com/tgstation/tgstation/pull/76889)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/85206687/5e5e0e30-eadf-4b8e-9e70-904421b953eb)
Occurred after pressing the colour pallet button for an item to recolour it.

**Comment by Sealed101** [comment] 2023-07-31 05:27
Duplicate of #77246

**Closed** 2023-07-31 05:28 UTC
