### ISSUE TITLE
Shuttle walls STILL break into space

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35241] opened 2018-02-02 21:16 UTC
Its been weeks, can someone please fix this shit already?

**Comment by praisenarsie** [comment] 2018-02-02 21:44
@ninjanomnom lol

**Comment by Kromgar** [comment] 2018-02-03 02:57
It was kinda funny but now its awful

**Comment by ninjanomnom** [comment] 2018-02-04 07:28
dupe of #33984

**Closed by ninjanomnom** 2018-02-04 07:28 UTC
Labels: Bug, Consistency Issue
