### ISSUE TITLE
Bio bags don't seem to register Monkey cubes inside of them when applied to reproductive extracts

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#69699] opened 2022-09-04 02:12 UTC
Reporting client version: 514.1585

## Round ID:
[189810](https://scrubby.melonmesa.com/round/189810)

## Testmerges:
- [Moves "catch this var/flag" code from obj/init and datum/new into the types that use it ](https://www.github.com/tgstation/tgstation/pull/69634)
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:
So in this shift I had a science bag filled with monkey cubes, trying to use it on the Reproductive Grey extract. But for some reason it would keep saying "There are no Monkey cubes in the bio bag"

https://gyazo.com/f54d7e486437bf2c88f59a3caee58b59
https://gyazo.com/a1c1bbfbe611a591c88d91268b4db075xx

**Comment by the-orange-cow** [comment] 2022-09-04 10:29
Dupe of #68363

**Comment by ZeroKelvn** [comment] 2022-09-04 19:18
It keeps popping up, but at least https://github.com/tgstation/tgstation/pull/69518#issue-1353312357 is trying to fix it

**Comment by Sealed101** [comment] 2022-09-18 17:57
fixed in #69518, also a dupe of the issue stated above

**Closed** 2022-11-20 20:15 UTC
Labels: Bug
