### ISSUE TITLE
Ability to rejoin the game through split personality.

### ISSUE THREAD

**Issue by duckay** [tgstation/tgstation#41102] opened 2018-10-23 20:14 UTC
TGSTATION Sybil
Round ID: 95941
Byond version: 512.1453
[2018-10-23 17:20:33.603] duckay \ Barney Endsley \ Assistant \ NONE \ ROUNDSTART
[2018-10-23 17:30:29.066] Duckay \ Barney Endsley \ Assistant \ NONE \ LATEJOIN
The series of events that happened is as follows: killed in space, waited a while 'Do you wish to play as Syd Echards' split personality?' press yes, get onto Syds screen, but it's frozen and thinking byond fucked up, I reconnected, which put me in the lobby, I rejoined soon after being in the lobby for a prank.

**Comment by wesoda25** [comment] 2018-10-24 00:52
I basically already reported this: #37674

**Comment by duckay** [comment] 2018-10-24 02:15
god dammit dorisdorf

**Comment by Time-Green** [comment] 2018-10-27 13:33
this is what happens when at any point in time there exists no mob with a players key assigned to it
``
var/ckey2 = Bert.ckey
Bert.ckey = Ernie.ckey
Ernie.ckey = ckey2
``
this is enough to kick bert and return him to the lobby

**Comment by kriskog** [comment] 2019-06-28 10:11
Duplicate of #37674

**Closed by kriskog** 2019-06-28 10:11 UTC
