### ISSUE TITLE
Cyborgs cannot interact with false walls

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84893] opened 2024-07-11 17:46 UTC
Reporting client version: 515.1641

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/ce88a642-6aec-48f2-ae01-829b0240c7c4

## Round ID:
[231962](https://scrubby.melonmesa.com/round/231962)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: Loads icon refs at boot](https://www.github.com/tgstation/tgstation/pull/84853)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

**Comment by Rhials** [comment] 2024-07-11 18:23
Were they able to in the past? I assumed it was only for mobs with hands.

**Comment by Sadboysuss** [comment] 2024-07-11 18:28
> Were they able to in the past? I assumed it was only for mobs with hands.

I'm not sure if they were able to in the past but an engi cyborg can't repair a wall like that cause it's open and still counts as a wall

**Comment by SyncIt21** [comment] 2024-07-12 10:12
Not a bug. Both borgs & humans cannot tighten a false wall with a screwdriver when it is open. You must close it to tighten its bolts so it becomes a real wall.

**Comment by Sadboysuss** [comment] 2024-07-12 14:22
> Not a bug. Both borgs & humans cannot use a screwdriver on a falsewall when it is open. You must close it & then tighten its bolts so it becomes a real wall.
> 
> Just tested locally & when the falsewall is closed both borgs & humans can use the screwdriver on it.
> 
> Even in your video if you look at the chat it says to close the wall first ![Screenshot (434)](https://private-user-images.githubusercontent.com/110812394/348224723-1c314539-f7d9-49ea-b577-537a2afbd764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTQzNTksIm5iZiI6MTcyMDc5NDA1OSwicGF0aCI6Ii8xMTA4MTIzOTQvMzQ4MjI0NzIzLTFjMzE0NTM5LWY3ZDktNDllYS1iNTc3LTUzN2EyYWZiZDc2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxNDIwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZThjZWYzZTA2MjI0ZTU4NWI3ZDc5ZGM4MWM4N2I5ODZkMzQ2MDBjNzJlOTRkZjkyNjZiYWIyODQ5MmIxNDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZoUP3fgjwAihqIdcQoXNGy_ofY425hYZ_Z-Bfr_N698)

that's not what I meant by this issue report, it is impossible for an engiborg to close the false wall, but if you try to build over it, it says: "already a wall there"

**Comment by SyncIt21** [comment] 2024-07-12 14:53
> that's not what I meant by this issue report, it is impossible for an engiborg to close the false wall, but if you try to build over it, it says: "already a wall there"

Then borgs must be given the ability to close walls and that's a feature request not a bug report. Borgs find it impossible to do most things mobs with hands can do by design

**Closed** 2024-07-12 15:09 UTC
Labels: Oversight
