### ISSUE TITLE
Microwave is behaving poorly.

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#47257] opened 2019-10-20 22:45 UTC
Issue reported from  Round ID: 121872 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

I'd call this a P2 issue. Certainly not game-breaking but not great UX.

The Microwaves seem to be acting up. 4/4 of the last few cook rounds I have played the microwave stays orange as if it was still being used way longer than it ought to. This does not appear to be by design and interrupts the flow of cooking. Sometimes I put things into the microwave and activate it but they are not cooked. 

![image](https://user-images.githubusercontent.com/38709973/67167577-7e18d280-f350-11e9-9a0d-7d0f2df7d189.png)

**Comment by TheVekter** [comment] 2019-10-22 04:14
#47184 was supposed to fix this, dunno if it's related to that or not.

Is it happening every time on every round? On only certain foods?

**Comment by Zargoar** [comment] 2019-10-22 07:26
It was every round I played chef last weekend so roughly 4/4.

**Comment by TheVekter** [comment] 2019-10-22 07:36
By last weekend, do you mean this last Saturday or a little over a week ago? Because that was merged on the 18th.

**Comment by Zargoar** [comment] 2019-10-22 07:57
This last Saturday/Sunday.

**Comment by willox** [comment] 2019-10-22 12:13
I can't reproduce this on master and can see from the logs that Sybil did not have the fix for the microwave during that round.

**Comment by TheChosenEvilOne** [comment] 2019-10-22 12:14
> 
> 
> I can't reproduce this on master and can see from the logs that Sybil did not have the fix for the microwave during that round.

Yep, I think the server was just out of date.

**Comment by kriskog** [comment] 2019-11-12 03:11
Yeah seems to be working fine on master

**Closed by kriskog** 2019-11-12 03:11 UTC
Labels: Bug, Needs Reproducing
