### ISSUE TITLE
Changelings permanently die if beheaded

### ISSUE THREAD

**Issue by collinlunn** [tgstation/tgstation#51408] opened 2020-06-01 07:26 UTC
If you get beheaded as a ling, all your powers stop working and you cannot revive.

**Comment by Fikou** [comment] 2020-06-01 08:54
dupe of #50633 #49802

**Comment by ExcessiveUseOfCobblestone** [comment] 2020-06-02 12:46
I didn't look into this too much but i'm willing to bet it's 1:1 with the issue i fixed in #50174

**Comment by Doosteroni** [comment] 2020-06-03 07:03
pls fix very angry this makes me

**Comment by AU518987077** [comment] 2020-06-08 05:26
Issue reported from  Round ID: 139027 (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

so after testing a few things i thought this was related to specific items used to decap, as i had gotten a consistency with the esword versus  the captains saber and circular saw that did nto cause the players soul to attach to the head in my test the morning of the 7th, a test just now in this round, resulted in a different outcome, where instead of being decapped by the esword which was my 5th decap, after having been decapitated 4 times earlier this morning, this time i was in the decapitated head after only the second decap and could not reviving stasis as said head.

i will be testing this more with others later but i am now thinking it is random chance that a decapped ling is the head and not the body. no idea as to why yet.

**Comment by AU518987077** [comment] 2020-06-08 08:57
so i just tested with multiple guest clients on my server, the first time the head pops off, the revival stasis works as intended, but the second time and subsequent the players soul is attached to the head with what i just experimented with.

**Comment by AU518987077** [comment] 2020-06-08 11:58
the pattern is definitely first decap works as intended, player is with body, but subsequent decaps and surgical reattachment's ends up as player is in the head. i would like another party to see about reproducing this

https://github.com/tgstation/tgstation/commit/b11b3ae7a9ad91d6340f85c512662283d69f7a56

BYOND Version: 513.1521
Server revision compiled on: 2020-06-07
Master commit: b11b3ae7a9ad91d6340f85c512662283d69f7a56
Local commit: e76844709a5d907731a1389de51a6a4c9a3a391c

**Comment by Pugie** [comment] 2020-06-09 13:59
A couple days back on Terry I got beheaded as ling after I died and I left my body and attempting to reenter put me in my head. RoundID was 138682

**Comment by tralezab** [comment] 2020-06-24 03:30
fix comin up

**Comment by Valtosin** [comment] 2020-07-17 07:18
Issue happens after using regenerate ability. Probably someone should dig here:
https://github.com/tgstation/tgstation/blob/7e9785e4365f1634ba7c020d4f8f0191bd113f7f/code/modules/antagonists/changeling/powers/regenerate.dm#L27-L36

**Comment by AU518987077** [comment] 2020-07-27 03:49
just tested on bagil 142879 still ended up in head after first regen stasis

**Comment by Exavere** [comment] 2020-07-27 03:50
Admin that AU tested with, can confirm the second behead puts you back into the head.

**Comment by ExcessiveUseOfCobblestone** [comment] 2020-08-04 18:14
I tested my PR by force-linging > removing head > ling regenerate ability (revival should use the same procs) > remove head with VV again and it worked.

**Comment by AU518987077** [comment] 2020-08-04 18:22
> I tested my PR by force-linging > removing head > ling regenerate ability (revival should use the same procs) > remove head with VV again and it worked but i'll double check.

we used an axe and i used a surgical saw on my own server before i tested this last

**Comment by ExcessiveUseOfCobblestone** [comment] 2020-08-04 18:27
im at work, ill boot up local when i get home.

**Comment by AU518987077** [comment] 2020-08-04 20:41
> im at work, ill boot up local when i get home.

here, have a video
[Uploading github tgstation issues 51408 2020.08.04 - 14.03.24.07.zip…]( clownling decap)

**Comment by Doosteroni** [comment] 2020-09-05 20:28
Lings are cursed

**Comment by dragomagol** [comment] 2020-12-03 21:16
It would appear that being decapitated as a ling essentially turns you into a dullahan now. I was able to revive without a head (and gain the head back using regenerate) so I think, hope, pray this is fixed

**Comment by redguy999** [comment] 2020-12-11 20:23
I believe that whatever allows you to stay in your body after getting HARS may be able to be used here.

**Comment by SethLafuente** [comment] 2023-03-08 19:48
This is no longer an issue if it was people would be doing it to kill lings easily and lings would complain

**Closed** 2024-09-13 20:09 UTC
Labels: Bug
