### ISSUE TITLE
hitting silicons causes your clothes to be covered in blood

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47295] opened 2019-10-21 23:25 UTC
Affects borgs, AI

**Comment by spessbandit** [comment] 2019-10-22 03:29
dupe https://github.com/tgstation/tgstation/issues/41439

**Comment by PKPenguin321** [comment] 2019-10-22 03:59
Duplicate of https://github.com/tgstation/tgstation/issues/41439

**Closed by PKPenguin321** 2019-10-22 03:59 UTC
