### ISSUE TITLE
Weird Luxury Shuttle bugs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24843] opened 2017-03-08 17:52 UTC
![image](https://cloud.githubusercontent.com/assets/609465/23715905/33bfbc7e-0426-11e7-991a-e1400bb7fe4f.png)

I don't even know where to begin. But I blame @Cyberboss, of course.

**Comment by Cyberboss** [comment] 2017-03-08 17:53
Is anything testmerge?

**Comment by coiax** [comment] 2017-03-08 17:59
No.

**Comment by PKPenguin321** [comment] 2017-03-10 05:45
From the other issue,

>That's where the swimming pool is.

probably a sprite issue

**Comment by KorPhaeron** [comment] 2017-04-06 16:04
@Cyberboss you already fixed templates right

**Comment by Cyberboss** [comment] 2017-04-06 20:46
Wouldn't have fixed this I think. Is it still happening?

On Apr 6, 2017 12:04 PM, "KorPhaeron" <notifications@github.com> wrote:

@Cyberboss <https://github.com/Cyberboss> you already fixed templates right

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/24843#issuecomment-292222464>,
or mute the thread

**Comment by Buggy123** [comment] 2017-07-27 19:40
Didn't we get rid of shuttle variants? Can't we close this now?

**Comment by KorPhaeron** [comment] 2017-07-27 19:42
We did not

**Comment by ninjanomnom** [comment] 2017-10-05 02:10
I can't reproduce this and this should be fixed by my dock rewrite. It can be closed now

**Closed** 2017-10-05 02:45 UTC
Labels: Bug
