### ISSUE TITLE
Halloween Race Dullahan cannot do any jobs

### ISSUE THREAD

**Issue by LarissaMayrink** [tgstation/tgstation#70938] opened 2022-10-31 05:32 UTC
## Round ID:
irrelevant, went through multiple, affects all of them

## Reproduction:
Dullahans cannot take off handcuffs and other things off people, have no radio, cannot interface with any computers, vendors, consoles, cannot use health scanners and others except the little atmospheric reader one, can't fire guns, can't fire staffs, can't get spaceproofed because without the helmet you still take pressure damage, can't wear modsuits

Dullahans can't be cheffs because they can't even vent their tools
Cant be bartender because they can't use the dispenser
Can't be botanist because they can't read the trays nor use the vendors
Can't be engineers because they can't spaceproof nor use many of the tools
Can't be chemists because they can't interface with any machine, including the plumbing tool
Can't be doctors because they can't use the health scanner nor surgery computer
Can't be cargo techs because they can't use the console nor the taggers
Can't be atmos because they can't use the pipe dispenser, nor the alarms, nor the pumps
Can't be scientist nor roboticists because they cannot do absolutelly anything in there
Can't be security because no hud and no guns
Can't be geneticists because computers
Can't be miners because you can't fire the kpa
Can't be chaplain because you can't chose your rod form nor order your armor
Can't be miner because you can't use the janitor cart nor the lights replacer

So what can dullahan do?
Tide
Be bullied

**Comment by Sealed101** [comment] 2022-10-31 07:01
good

**Comment by Mooshimi** [comment] 2022-10-31 20:18
Duplicate of #70938

**Closed by Mooshimi** 2022-10-31 20:18 UTC
