### ISSUE TITLE
Dying on tram ties your ghost to the tram.

### ISSUE THREAD

**Issue by Meanslicer43** [tgstation/tgstation#82994] opened 2024-05-01 05:02 UTC
## Issue Summary
Suicide on Tramstation, while inside the tram, leads to ghost being tied to it Permanently. Every time tram moves, ghost is forced to move as well.  Unsure if only suicide or Dying in general.

**Comment by lessthnthree** [comment] 2024-05-01 08:40
Duplicate of https://github.com/tgstation/tgstation/issues/77722

**Comment by msgerbs** [comment] 2024-05-01 23:52
Are we going to get the first issue that is fuckup of the year for 2 years?

**Comment by lessthnthree** [comment] 2024-05-02 08:06
The bug has been around for months before it had an issue logged, so probably.

**Comment by Dawnseer** [comment] 2024-05-05 09:51
Part of the ship, part of the crew

**Comment by msgerbs** [comment] 2024-05-05 15:49
Duplicate of #77722

**Closed by msgerbs** 2024-05-05 15:49 UTC
