### ISSUE TITLE
Bubblegum's blood drag range is way too much, also picks targets they have not seen EVER.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#37083] opened 2018-04-09 21:18 UTC
Round ID: I think 86289

I was standing here.
![standing here](https://user-images.githubusercontent.com/4581352/38523349-17f94d9c-3c43-11e8-9d85-df996d59f26d.png)

I got dragged here.
![teleported here](https://user-images.githubusercontent.com/4581352/38523355-1d5575ae-3c43-11e8-90a4-f245d73fab12.png)

This is fucking ridiculous, getting dragged by bubblegum almost 2 screens away from you and instantly killing you because my reflexes weren't fast enough for the 0.23 second necessary to dodge bubblegum's charge and a miner's kinetic accelerator, I got into the middle of it
I hope you enjoy the one second the ash walker hotel was open for business.

Also i ded tag please.

**Comment by Repukan** [comment] 2018-04-09 21:26
Not a bug, intended.

**Comment by PKPenguin321** [comment] 2018-04-09 21:39
I dunno, being instakilled by something waaay offscreen that had no reason to even be aware of your existence and phased through any obstacle to get to you sounds kind of iffy

**Comment by Repukan** [comment] 2018-04-09 21:42
Want to take out bombs too then

**Comment by Repukan** [comment] 2018-04-09 21:42
And meteors

**Comment by Repukan** [comment] 2018-04-09 21:42
Singulo, tesla

**Comment by Tlaltecuhtli** [comment] 2018-04-09 21:45
this is the reason cleaning is important so slaugher demons from hell dont get u

**Comment by Onule** [comment] 2018-04-09 21:46
Cool, never seen meteors and teslas in lavaland tho, they'd probably make a shit ton of noise too. Meanwhile stompy mcblood over the other side of the road can silently drag you into an instant kill, sounds balanced, especially when you never even knew they were around your area.
Boy I can't wait for mister "lavaland must be harsh" over here to tell me that stun gloves were definitely balanced and tries to bring them back, maybe even give the user telekinesis so they can tickle people's bum from beyond the walls, only difference here being it's a stun and they're within the screen, and they're a player, but we all know stuns means deaths. Hey next time tell me how to avoid bubblegum in-game maybe next time I'll be safe oh wait.

**Comment by Kromgar** [comment] 2018-04-09 21:51
@Onule One time bubblegum dragged me FROM THE STATION back to lavaland as i had jaunted out.

It was insane

**Comment by Barhandar** [comment] 2018-04-09 21:51
You sound salty.

Bubblegum should require uninterrupted blood trail for the drag.

**Comment by PKPenguin321** [comment] 2018-04-09 22:16
you cant tell me you honestly dont see the differences between all of those and bubblegum, repukan

**Comment by MMMiracles** [comment] 2018-04-10 02:03
@Kromgar tbh the visual of a miner using a jaunter to escape from bubblegum, only for him to reach out from a station blood pool as a 'where the fuck you think you going' before dragging your ass back sounds amazing.

**Comment by Kromgar** [comment] 2018-04-10 02:09
@MMMiracles yeah i had landed in a pool of blood it can happen if the station is really bloody

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-11 20:50
Singulo doesn't lol nope you from across 2 screens nor does bombs? There are obvious tells they're coming  if you are at that distance....

Not even sure if that's true with tesla anymore, but I haven't seen it in so long I couldn't accurately tell you without looking at the code (hah!)

**Comment by PKPenguin321** [comment] 2018-04-11 21:26
You can definitely hear the tesla before it gets to you
Bombs are the closest but they must be used maliciously and deliberately and even then you can still often dodge/outrun them if you've got enough distance when they go off

**Comment by Barhandar** [comment] 2018-04-12 19:43
The only thing that comes close to this is severe lag rendering you unable to dodge anything.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-04-12 20:26
If you're at the same range as Onule is compared to bubblegum then the bomb probably won't even crit you should you fail to outrun it.

**Comment by Rinoka** [comment] 2018-04-15 22:42
really i think we have the answer, here: bubblegum should be able to draw a mostly contiguous blood trail to its target

(and let him grab targets that have come within a certain range if they step on any blood for 5s even after teleporting, to maintain that "GET OVER HERE" hilarity)

**Comment by kriskog** [comment] 2019-06-30 16:28
Old behaviour, bubble has changed.

**Closed by kriskog** 2019-06-30 16:28 UTC
Labels: Not a bug
