### ISSUE TITLE
UI can be minimized, and the pop up button to put it back to normal state does not work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26644] opened 2017-04-27 12:06 UTC
![](http://i.imgur.com/sJp41dC.png)

If you push the minimize button on most conventional UIs (this was done with a wall intercom), it will minimize into that box shown above. The only button that works there is the close button.

Opening the wall intercom UI again will turn it into that tiny box once more, making it impossible to use it. You can fix this either by reconnecting (after closing the window), by using the right click -> restore button, or by spending a good long while fiddling with the maximize button in the split second you have before the html window is turned into that.

**Comment by 4dplanner** [comment] 2017-04-27 15:28
Right click->restore isn't really almost impossible, is it?

**Comment by lzimann** [comment] 2017-04-27 20:38
Yea just right click, it's nowhere near impossible. But yea, it is really annoying.

**Comment by WJohn** [comment] 2017-04-28 02:07
Sorry I hadn't changed the title when I learned about these other methods.

**Comment by WJohn** [comment] 2017-11-19 10:46
While right click restoring is still a way to fix it, why even have a minimize button at all if it's buggy and there isn't really a need for it?

**Comment by lzimann** [comment] 2017-11-19 12:25
Because I am not sure if we can even remove the minimize button.

**Comment by msgerbs** [comment] 2020-09-08 07:03
Anyone still able to reproduce this? I minimize tgui all the time with no issues.

**Comment by timothymtorres** [comment] 2021-08-18 10:10
@WJohn have you still been experiencing this issue?  TTGUI has had a lot of merged PRs that have improved it in the last few years.  I don't see any other issues mentioning this problem so this bug might have been fixed at some point.

**Comment by timothymtorres** [comment] 2021-08-19 08:13
So I went and tested this today.  A lot of TGUI menus cannot be minimized anymore. (including the radio one)  I'm closing this for now but feel free to ping me to reopen this if you experience the same problem.

**Closed by timothymtorres** 2021-08-19 08:13 UTC
Labels: Bug, Tested/Reproduced, UI
