### ISSUE TITLE
Psykers (or at least the pirate psykers) consistently crash you

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#75003] opened 2023-04-27 01:46 UTC
Reporting client version: 514.1589

## Round ID:
[204517](https://scrubby.melonmesa.com/round/204517)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
I once again dont know enough about the backend of this game to even begin to tell you whats happening here, but all three psyker pirates were crashing nonstop, myself included. Im once again hopping round logs have an answer for why this is happening.

**Comment by Jackal-boop** [comment] 2023-04-27 11:41
I'm really thinking about removing psykers for how many head aches they cause

**Comment by optimumtact** [comment] 2023-05-01 22:23
dupe of #74958

**Closed by optimumtact** 2023-05-01 22:23 UTC
