### ISSUE TITLE
Some weird lighting corners

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#59179] opened 2021-05-18 07:18 UTC
## Testmerges:
#58991 

https://user-images.githubusercontent.com/35135081/118608500-9dffba80-b76e-11eb-9203-914891d14bbf.mp4

![dreamseeker_2021-05-18T00-17-27](https://user-images.githubusercontent.com/35135081/118608506-9fc97e00-b76e-11eb-9bea-97c54cd5268d.png)

**Comment by Kylerace** [comment] 2021-05-18 09:39
probably not subtracting the underlay properly, the way to tell would be if the turfs underlays list is longer than 1 for a turf that doesnt use underlays by itself

**Comment by dragomagol** [comment] 2021-05-18 16:29
I'm not sure about the second one, but I think to reproduce the first one you can just pry up a tile and put it back down. Lighting also reacts strangely with newly built walls.

**Comment by Kylerace** [comment] 2021-05-18 23:54
i think the issue here was that the lighting underlays didnt have the RESET_COLOR appearance flag so they were darkened if a turf had a dark atom.color var, now it should be fixed

**Comment by Mothblocks** [comment] 2021-05-19 01:34
if u say so

**Comment by Kylerace** [comment] 2021-05-19 02:48
wait that cant be the issue, that tile on meta is just a normal iron floor without any atom.color changes. i'll need to try and reproduce it again

**Comment by Kylerace** [comment] 2021-05-21 01:01
![Screenshot_193](https://user-images.githubusercontent.com/15794172/119066466-b2250100-b994-11eb-9e88-78a606614a61.png)
![Screenshot_194](https://user-images.githubusercontent.com/15794172/119066467-b2bd9780-b994-11eb-9c91-55334eb0622e.png)
ok i found two instances on a sybil round that most closely resembles this problem. I was the only person who saw these dark tiles (after setting me to view darkness normally as a ghost, setting it to the brightest level makes the tiles be normally lit). updating the light source affecting it fixed the first tile on the top but nothing i could do seemed to fix the dark tiles on the bottom image. updating the lighting objects, or the lighting corners, or the lighting source via admin proc calls didnt seem to do anything, and turning the light switch off and on again also didnt do anything. 

it appears to be an intermittent client issue that as far as i can tell only happens on live so there might not be a solution we can directly fix. also the byond version didnt seem to matter, lemon couldnt see the same tiles as dark when he was on a different version than me nor when he was on the same byond version as me.

**Comment by Kylerace** [comment] 2021-05-23 23:02
update on the weird lighting in the escape shuttle: shuttles rotate their turfs when moving to somewhere with a different direction port, lighting objects didnt used to be rotated with this but since lighting is an underlay now they get rotated with their turf so lighting looks weird. now this is fixed since lighting objects look identical in all 4 directions

**Closed** 2021-12-17 04:56 UTC
Labels: Needs Reproducing, Test Merge Bug
