### ISSUE TITLE
Someone blew a hole into space on lavaland at the mining base.

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22408] opened 2016-12-23 04:36 UTC
Northwest is where the shuttle lands. 

![image](https://cloud.githubusercontent.com/assets/6778786/21447201/2bf0e95e-c89f-11e6-9205-d5261563a436.png)

**Comment by Jordie0608** [comment] 2016-12-23 05:24
Dupe of #22408, unclear why that was closed.

**Closed by Jordie0608** 2016-12-23 05:24 UTC

**Comment by Mindustry** [comment] 2016-12-23 22:17
I was able to produce this about a week ago by placing three of the station self destruct bombs around a badmin payload (acquired from said self destruct bombs) and shooting the payload with a sniper.
