### ISSUE TITLE
beakers are double transferring reagents

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#72620] opened 2023-01-10 14:34 UTC
Reporting client version: 514.1589

## Round ID:
[197967](https://scrubby.melonmesa.com/round/197967)

## Reproduction:
put 20u of something in a beaker set to 10u transfer
click another beaker
it double transfers, all liquid ends up in new beaker

the message in chat also double sends, so I'm pretty sure the action is happening twice

**Comment by Profakos** [comment] 2023-01-10 14:58
It was very likely caused by the double afterattack issue (now fixed).

**Comment by timothymtorres** [comment] 2023-01-10 21:13
Fixed by #72617

**Closed by timothymtorres** 2023-01-10 21:13 UTC
Labels: Needs Reproducing, Cleanup Flagged
