### ISSUE TITLE
Attempting to lay down meters with the RPD only lays down invisible "fittings"

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/tgstation#33866] opened 2017-12-26 19:58 UTC
How to repeat:

grab RPD
Select the meter option while "lay pipes" is selected.
attempt to produce a meter
Only an invisible "fitting" which can be seen from the right click on the square you attempted to lay down the meter.

Issue reported from Round ID: 80851 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by praisenarsie** [comment] 2017-12-26 21:32
Dupe of https://github.com/tgstation/tgstation/issues/32920

**Comment by Cyberboss** [comment] 2017-12-26 23:59
Duplicate of #32920

**Closed by Cyberboss** 2017-12-26 23:59 UTC
