### ISSUE TITLE
GPS Signals Broken

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#75430] opened 2023-05-14 01:09 UTC
Reporting client version: 514.1589

## Round ID:
[205632](https://scrubby.melonmesa.com/round/205632)

## Reproduction:

The Arrows in the GPS are nonfunctional and constantly point upwards/north for any signals on a given z-level regardless of location of the user.

**Comment by SyncIt21** [comment] 2023-05-14 03:54
Duplicate of #75264 and was just fixed by #75367. Wait for servers to update. 
@jlsnow301 please close

**Comment by jlsnow301** [comment] 2023-05-14 03:55
Feel free to reopen this if the issue persists

**Closed** 2023-05-14 03:55 UTC
