### ISSUE TITLE
camera consoles crashes me constantly

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#33823] opened 2017-12-24 20:49 UTC
STOP DOIN THAT YOU FUCK

**Comment by cyclowns** [comment] 2017-12-25 01:49
im pretty sure all camera consoles do this
i crash a lot using the clockcult teleport console

**Comment by arsserpentarium** [comment] 2017-12-25 07:40
Me too.
Looks like,problem is 512 version of byond

**Comment by praisenarsie** [comment] 2017-12-25 09:01
> im pretty sure all camera consoles do this
i crash a lot using the clockcult teleport console

**Comment by WJohn** [comment] 2017-12-26 13:50
Dupe of #33377 it's been around for months now. Seems to be a byond issue.

**Closed by WJohn** 2017-12-26 13:50 UTC
Labels: Bug, UI
