### ISSUE TITLE
Airlock painter broke

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#37591] opened 2018-04-30 21:01 UTC
[Round ID]: # 87253

[Reproduction]: # Attempt to paint an airlock with the airlock painter

How am I supposed to make my department look swanky now?

**Comment by Barhandar** [comment] 2018-05-01 10:39
#35223
#37430
#36245

**Comment by ShizCalev** [comment] 2018-05-01 14:40
Duplicate of #35223

**Closed by ShizCalev** 2018-05-01 14:40 UTC
