### ISSUE TITLE
AI Multicamera Window Becomes Completely Static

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#63703] opened 2021-12-30 06:54 UTC
Reporting client version: 514.1568

## Round ID:
[175647](https://scrubby.melonmesa.com/round/175647)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:
I attempted to use multicamera to it's fullest potential this shift, but ran into trouble quickly. Clicking on the turf that makes up the background of the multicamera room makes it entirely the no camera static overlay. Entirely - thus completely locking me out of using it, covering even windows I've placed.

This is.. annoying, as you can imagine.

**Comment by timothymtorres** [comment] 2021-12-30 11:33
Can you provide pictures?

**Comment by unit0016** [comment] 2021-12-30 12:03
> Can you provide pictures?

Yeah, here's one I've thrown together quickly to showcase. I only clicked one turf in the top-left.
![image](https://user-images.githubusercontent.com/50649185/147750253-d52556b2-4dba-4b83-a82f-c3e70767369f.png)

**Comment by timothymtorres** [comment] 2021-12-30 12:20
Wow that’s bad.  The picture will hopefully help someone solve this quickly.

**Comment by timothymtorres** [comment] 2021-12-30 13:52
Duplicate of #52562

**Closed by timothymtorres** 2021-12-30 13:52 UTC
Labels: Consistency Issue

**Comment by unit0016** [comment] 2021-12-30 14:51
Darn! I did a search and everything. At this point I'm beginning to suspect github's search system's a little too strict.
Oh well, hopefully me rediscovering it will renew interest in it.
