### ISSUE TITLE
Plasma Fixation symptom does not activate when breathing plasma from a tank

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#54367] opened 2020-10-13 03:01 UTC
The Plasma Fixation symptom works when standing in a room filled with plasma, but not when breathing it from a tank. I also haven't been able to get it working when playing a plasmaman and injecting plasma, though that's probably because they have no blood anyway. 

#46055 says that this was fixed, so maybe it broke again recently?

**Comment by Winterous** [comment] 2020-10-13 10:10
It's not supposed to work from breathing plasma; I think it should, but it doesn't.

**Comment by InvalidArgument3** [comment] 2020-10-13 11:09
> It's not supposed to work from breathing plasma; I think it should, but it doesn't.

The PR makes it seem like it was, or should have been, affecting it previously. Reading into it more I see that a concern was brought up of plasmemes being able to heal from it but it's quite slow and they take 50% more damage anyway.

**Comment by Winterous** [comment] 2020-10-13 15:10
What PR?

**Comment by msgerbs** [comment] 2020-10-13 16:18
This one #46151

**Comment by Winterous** [comment] 2020-10-14 03:19
Nothing in that PR indicates the intent was that breathing plasma should activate the symptom. It's simply fixing that it didn't work from standing in an environment with plasma.

**Comment by InvalidArgument3** [comment] 2020-10-14 10:48
Yeah taking another look at it now I realize I was referring to ATH's lung code PR that closed. I guess this is a feature request now. Could plasma Fixation be changed to allow for breathing plasma?

**Comment by ATH1909** [comment] 2020-10-14 17:45
The bigger here concern here is that Invalid's attempt to heal with plasma fixation by "injecting plasma" didn't work.

Were you at stage 4+? What damage type did you use to test it? Were you using actual plasma or stable plasma?

**Comment by InvalidArgument3** [comment] 2020-10-14 19:20
> Were you at stage 4+? What damage type did you use to test it? Were you using actual plasma or stable plasma?

I was at stage 5, and injected regular plasma into my 
character, which is a plasmaman. I hit myself with an object to cause brute damage to test. Since plasmamen don't have blood, I thought it not healing me was intentional. I'll try it again to make sure.

**Comment by Winterous** [comment] 2020-10-15 09:29
Just to confirm, the virus DID have Inorganic Biology, right? Without that symptom it cannot infect plasmamen and golems.

**Comment by InvalidArgument3** [comment] 2020-10-16 03:00
Okay just tested it. An inorganic biology + plasma fixation virus at stage 5, injected liquid plasma as plasmaman, no healing.

**Comment by Winterous** [comment] 2020-10-16 06:07
Does it work on non-plasmamen?

**Comment by timothymtorres** [comment] 2021-11-08 13:44
Duplicate of #46055

**Closed by timothymtorres** 2021-11-08 13:44 UTC
Labels: Consistency Issue
