### ISSUE TITLE
No traitor info in roundend report with traitors in the round

### ISSUE THREAD

**Issue by Holoo-1** [tgstation/tgstation#87922] opened 2024-11-14 22:30 UTC
### Client Version:

515.1645

### Issue Summary:

Title

### Round ID:

[242186](https://scrubby.melonmesa.com/round/242186)

### Test Merge Information:

#87742
#87754
#84280

### Reproduction Steps:

IDK (I didn't test locally)
1. Roll roundstart traitor
2. Get converted to revolution
3. Die in heretic shadow realm
4. Round ends when body lies on lower tramstation level

**Comment by Sadboysuss** [comment] 2024-11-15 08:06
Duplicate of https://github.com/tgstation/tgstation/issues/82128

**Closed** 2024-11-16 17:20 UTC
