### ISSUE TITLE
Converting the race of monkeys bypasses the monkeycube cap

### ISSUE THREAD

**Issue by Zonespace27** [tgstation/tgstation#68066] opened 2022-06-28 21:38 UTC
## Reproduction:

- Spawn enough monkeycubes to hit the monkey cap
- Convert to monkeys
- Apply a mutation toxin (gondola was used in reproduction)
- Wait for them to become gondolas
- Spawn more monkey cubes
- Have the ability to create more monkeys even though you are technically at the cap
![image](https://user-images.githubusercontent.com/41448081/176303568-63da1f83-241f-41c8-bcc3-b47a5508475d.png)

**Comment by timothymtorres** [comment] 2022-06-29 08:01
The purpose of the monkeycube cap was to prevent normal players under normal circumstances from lagging up the server.  I can see that you performed your testing on Runtime station with admin tools, which does not mirror actual gameplay conditions so I'm marking this as not a bug.

Also Gondolas don't have the same AI patterns as monkeys.

**Comment by nemvar** [comment] 2022-06-30 10:37
Monkeys have a cap because they have an expensive AI, converting them to gondolas removes the need for the cap.

**Closed by nemvar** 2022-06-30 10:37 UTC
Labels: Not a bug, Cleanup Flagged
