### ISSUE TITLE
headless ling bug

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#43313] opened 2019-03-24 16:53 UTC
https://i.gyazo.com/f290951b299e8b8686cce8e641655333.png

revived headless, had no eyes ears tongue and i could still see ghosts. maybe some of this is intentional but surely seeing ghosts isn't.

**Comment by ShizCalev** [comment] 2019-03-24 17:21
Duplicate of #27408

**Closed by ShizCalev** 2019-03-24 17:21 UTC

**Comment by imsxz** [comment] 2019-03-24 17:36
@ShizCalev that issues from 2017 i dont think anyones gonna see it ever
