### ISSUE TITLE
Xenobiology "Heroine Bud" can be taken off by the wearer by drag clicking.

### ISSUE THREAD

**Issue by Redrover1760** [tgstation/tgstation#59121] opened 2021-05-15 01:53 UTC
I was a scientist who turned myself into a slimeperson and I made a Heroine Bud for fun. I went to play with it and accidently equipped it onto my head. I clicked on it to get it off and it didn't work. 3 minutes later I drag click it off and it works. Then I put it back on again and then drag clicked it off again.

**Comment by dragomagol** [comment] 2021-05-15 18:52
Duplicate of #55313

**Closed by dragomagol** 2021-05-15 18:52 UTC
