### ISSUE TITLE
Chat Bluescreened

### ISSUE THREAD

**Issue by yeoldecoot** [tgstation/tgstation#67148] opened 2022-05-20 02:17 UTC
Round ID: [183444](https://scrubby.melonmesa.com/round/183444)

Chat crashed towards the end of the round when we were all in the escape shuttle

Paste Bin: https://pastebin.com/6tQGSkfJ

**Comment by timothymtorres** [comment] 2022-05-20 03:28
Duplicate of #67147

**Closed by timothymtorres** 2022-05-20 03:28 UTC
