### ISSUE TITLE
splitter makes two chemicals instead of splitting them into decimals

### ISSUE THREAD

**Issue by c420-o** [tgstation/tgstation#56432] opened 2021-01-26 00:54 UTC
## Round ID:
n/a

## Reproduction:

make a chemical synthesizer that produces 1u of any chemical, and connect it to a splitter. make 2 chemical tanks connected to the splitter. you'll notice it will go up by 2 instead of .5

**Comment by TemporalOroboros** [comment] 2021-01-26 02:52
Amazing.

**Comment by ATH1909** [comment] 2021-01-26 06:21
> ## Round ID:
> n/a
> 
> ## Testmerges:
> ## Reproduction:
> make a chemical synthesizer that produces 1u of any chemical, and connect it to a splitter. make 2 chemical tanks connected to the splitter. you'll notice it will go up by 2 instead of .5

can this dupe other chems, including can_synth = FALSE ones?

**Comment by Time-Green** [comment] 2021-01-26 19:37
> ## Round ID:
> n/a
> 
> ## Testmerges:
> ## Reproduction:
> make a chemical synthesizer that produces 1u of any chemical, and connect it to a splitter. make 2 chemical tanks connected to the splitter. you'll notice it will go up by 2 instead of .5

im gonna cry because its my job to fix that and that sounds like hell

**Comment by HumanNugget** [comment] 2021-01-27 15:09
![image](https://user-images.githubusercontent.com/42466182/106010315-bcb04780-60d2-11eb-92dd-16ef4f621ce4.png)
doesnt dupe
inputting 1u of chemicals into a 1/1 splitter doesnt net more than was previously inputted

**Comment by c420-o** [comment] 2021-01-27 18:04
> > ## Round ID:
> > n/a
> > ## Testmerges:
> > ## Reproduction:
> > make a chemical synthesizer that produces 1u of any chemical, and connect it to a splitter. make 2 chemical tanks connected to the splitter. you'll notice it will go up by 2 instead of .5
> 
> im gonna cry because its my job to fix that and that sounds like hell
> 
> I’d also really like a round ID because the new chem changes could’ve been testmerged

I used the latest github repo for it on a testserver

**Comment by c420-o** [comment] 2021-01-27 18:05
> ![image](https://user-images.githubusercontent.com/42466182/106010315-bcb04780-60d2-11eb-92dd-16ef4f621ce4.png)
> doesnt dupe
> inputting 1u of chemicals into a 1/1 splitter doesnt net more than was previously inputted

can you reword that?

**Comment by Time-Green** [comment] 2021-01-31 14:28
I can't reproduce it either, and without a round ID I am going to close it. If it's indeed from a testmerge, we'll find out soon enough.

**Closed by Time-Green** 2021-01-31 14:28 UTC
