### ISSUE TITLE
Russian Revolver is broken

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#44910] opened 2019-07-01 18:31 UTC
## Reproduction:
Spawn/get a Russian revolver. 
Shoot once - *BANG*
Click the gun to spin the barrel - No flavour text or sound is given showing that you've spun the barrel.
Try to shoot again - *click*
Spin barrel - No flavour text or sound
Try to shoot again - *click-

This now loops forever, even with 5 bullets in it will never shoot again.

If you remove all the bullets before firing and insert just one the same thing happens.

This happened on both a spawned revolver and a round start found revolver.

**Comment by Nickkoranda** [comment] 2019-07-01 18:53
Duplicate of https://github.com/tgstation/tgstation/issues/43563

**Closed by Nickkoranda** 2019-07-01 18:53 UTC
