### ISSUE TITLE
AI is completely unable to use mech modules

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#65471] opened 2022-03-14 22:20 UTC
Reporting client version: 514.1581

## Round ID:
[179955](https://scrubby.melonmesa.com/round/179955)

## Testmerges:
- [MODsuit painting](https://www.github.com/tgstation/tgstation/pull/65445)

## Reproduction:
Hop in mech through your preferred method as AI
Be unable to use modules that require you to click and despair.

**Comment by Serxule** [comment] 2022-03-14 23:02
its middle click to use mech modules, same with punching, if that doesnt work then its bugged

**Comment by SuperNovaa41** [comment] 2022-03-16 11:11
Dupe of https://github.com/tgstation/tgstation/issues/64112

**Closed by SuperNovaa41** 2022-03-16 11:11 UTC
Labels: Bug
