### ISSUE TITLE
Holoparasite can't manifest if user turns into ash drake, ghosts the holo upon user rehumanizing

### ISSUE THREAD

**Issue by jimmstar** [tgstation/tgstation#25287] opened 2017-03-19 20:25 UTC
This issue occurred as a support holoparasite on healing mode. Apparently the user had no idea that the holo was ghosted, either.

**Comment by Repukan** [comment] 2017-03-20 04:44
Can confirm, was drake

**Comment by PKPenguin321** [comment] 2017-03-20 05:26
I'd imagine this happens with anything that transforms you into a non-human, like the xeno or borg nanites or the borging machine

**Comment by ChangelingRain** [comment] 2017-03-20 15:15
Uuuuugh. This happens because holos manifest at user.loc, to at least discourage some abuse cases, like having a holo in a mech/locker/etc

**Comment by InsaneHyena** [comment] 2017-03-24 14:30
Also happens if you're a changeling, and you monkey yourself.

**Comment by timothymtorres** [comment] 2021-08-19 16:18
Duplicate of #59127

**Comment by timothymtorres** [comment] 2021-08-19 16:19
> Also happens if you're a changeling, and you monkey yourself.

Anykind of polymorph spell, ability, or effect all have different procs they use to transform, which is really really bad.

**Closed by timothymtorres** 2021-08-19 16:19 UTC
Labels: Bug
