### ISSUE TITLE
Pandemic Machines Vaccine Production is broken, again

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#33068] opened 2017-11-24 06:11 UTC
Round ID: 79192

During a Nuke Op Round, procured a blood sample with Fungal TB antibodies from a cured crew member. The Holodeck Pandemic machine I then used did not produce any vaccine with the sample, only producing empty bottles, despite listing the identified vaccines in the machine UI.

**Comment by Potato-Masher** [comment] 2017-11-24 06:20
I also can confirm this.

I also confirm that the round this happened on was total and absolute aids. The ops didn't even win somehow, even with a Mauler and over half the crew down with TB. The only chemist in sight went and made **_SPRAY TAN_** instead of treatment for TB, and proceeded to spray the TB infected people in medbay lobby with said spray tan.

**Comment by praisenarsie** [comment] 2017-11-24 16:01
@XDTM

**Comment by DaxDupont** [comment] 2017-11-24 20:02
This is a dupe from more than a month ago, https://github.com/tgstation/tgstation/issues/31534 
Thanks for fixing it @AnturK

**Comment by Chocodaemon** [comment] 2017-11-25 04:02
It was broken, then fixed. I'm noting that it's broken again.

**Comment by Chocodaemon** [comment] 2017-11-25 07:14
Round 79238, Pandemic machines still do not produce vaccine. Virus was GBS this time.

**Comment by ShizCalev** [comment] 2017-11-25 21:23
Duplicate of #31534

**Closed by ShizCalev** 2017-11-25 21:23 UTC
Labels: Bug
