### ISSUE TITLE
Cyborg multitool cannot link with tcomms objects

### ISSUE THREAD

**Issue by IsaacExists** [tgstation/tgstation#84234] opened 2024-06-22 13:48 UTC
Reporting client version: 515.1640

## Issue Summary
New cyborg omnitool cannot use multitool to link tcomms objects. It allows you to change the network and the identification strings, but not link any of the machinery together or access the rest of the options such as removing existing links.

## Round ID:
230956

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

## Reproduction:
Be a cyborg, break the telecomms hub (Or don't) and then rebuild it, try to interact with it with the cyborg's multitool.

**Comment by Sadboysuss** [comment] 2024-06-22 13:50
duplicate of https://github.com/tgstation/tgstation/issues/83077 and https://github.com/tgstation/tgstation/issues/83537

**Comment by Sadboysuss** [comment] 2024-06-22 13:51
also already being fixed

**Closed** 2024-06-22 13:51 UTC
