### ISSUE TITLE
Left clicking anything forces you back into hotkeys mode

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#47652] opened 2019-11-08 04:59 UTC
Chat mode is in an absolutely awful state right now, pressing enter in an empty bar no longer refreshes  say ", examining or peoples or tiles with alt or shift clicking forces people into hotkeys mode (and fucks with run for the default run being alt now).

**Comment by ATH1909** [comment] 2019-11-08 05:24
_sigh_

**Comment by Couls** [comment] 2019-11-08 06:26
duplicate of #47643

**Comment by carshalash** [comment] 2019-11-08 08:25
This also applies to action buttons and huds, so that sure is something.

**Comment by Couls** [comment] 2019-11-08 08:34
yeah, anywhere in the game window will change focus to the game

**Comment by kriskog** [comment] 2019-11-08 17:02
Dupe of #47643

**Closed by kriskog** 2019-11-08 17:02 UTC
Labels: Not a bug
