### ISSUE TITLE
Adminhealing a golem causes them to drop two adamantine resonators.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43548] opened 2019-04-08 09:33 UTC
## Round ID:
105741

## Reproduction:
1. Spawn in golem
2. Adminheal them
3. See two adamantine resonators on the floor. (Ears for golems)

Happens with seemingly any golem.

**Comment by HomocidlePancakes** [comment] 2019-04-08 14:05
Wat. This was fixed at some point.

**Comment by Daxxed** [comment] 2019-04-17 17:44
Yep had this happen to me with sand golems aswell, which shouldn't even have the resonators.
I think all golem types have to be fixed individually ?

**Comment by tralezab** [comment] 2019-08-15 21:57
dupe of #41949

**Closed by tralezab** 2019-08-15 21:57 UTC
Labels: Consistency Issue
