### ISSUE TITLE
Some vending machines fail to accept items when trying to refill them

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#54867] opened 2020-11-07 20:25 UTC
## Round ID:
[149866](https://scrubby.melonmesa.com/round/149866)

## Testmerges:
#54588 #54702 #54804 

## Reproduction:

Be a jannie and have a spare binbag or watertank at your vending machine.
Wish to refill the vendor with said items and do so by clicking on the vendor with the binbag or watertank.
Have the vendor accept the item as expected.
Wish to buy the item back later and see that it did in fact not refill the item given to it.

Dunno if it helps but it's stored inside the vending machine itself and not in the refill machine box cube thing.

**Comment by dragomagol** [comment] 2020-11-07 23:27
Looks like a duplicate of #49023

Is it just some vending machines or every one that you noticed?

**Closed** 2020-11-08 04:07 UTC
