### ISSUE TITLE
Manifold pipes don't seem to work in mapping

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/tgstation#85776] opened 2024-08-12 20:32 UTC
## Issue Summary
While mapping with the smart manifold pipes, they acted as 4ways, instead of the expected T junction.

## Round ID:

N/A

## Reproduction:

Place manifold smartpipe in Strong DMM (I used a standard layer 3, green variety).
Save, compile map, load in. See that the manifold acts as 4way.

**Comment by MrMelbert** [comment] 2024-08-12 20:34
The subtypes of pipes in the mapping tools are purely visual, all pipes are ultimately 4-way pipes / "smart pipes".

**Comment by Shadow-Quill** [comment] 2024-08-12 20:36
> The subtypes of pipes in the mapping tools are purely visual, all pipes are ultimately 4-way pipes / "smart pipes".

Why do the manifold/straight pipes exist in the first place then? It seems like the intent is to allow to have mapped pipes that won't connect to pipes outside of their directions.

**Comment by MrMelbert** [comment] 2024-08-12 20:42
fmpov they exist so you can visualize what more complex atmos setups (like atmos proper) looks like in-editor, where using 4w manifolds everywhere would look hideous

**Comment by Shadow-Quill** [comment] 2024-08-12 20:44
Fair enough, albeit moderately confusing at first glance.

**Comment by actioninja** [comment] 2024-08-14 08:00
Closing as not planned, not a bug

**Closed** 2024-08-14 08:00 UTC
Labels: Not a bug, Cleanup Flagged
