### ISSUE TITLE
Secure Airlocks (vault doors) cannot be hacked open

### ISSUE THREAD

**Issue by OHJ4Y** [tgstation/tgstation#65444] opened 2022-03-13 20:27 UTC
Reporting client version: 514.1575

## Round ID:
[179896](https://scrubby.melonmesa.com/round/179896)

## Testmerges:
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:

1. Attempt to slice vault door with set of default tools
2. Screwdriver cover, wirecut the grille, weld through the plasteel plating
3. Attempt to use crowbar 
4. It doesn't work
5. cry (optional)

You can hack up until the crowbar step, then it just ceases to function

**Comment by MrMelbert** [comment] 2022-03-13 20:55
Duplicate of #65391

**Comment by SuperNovaa41** [comment] 2022-03-13 21:08
Close duplicates you fool @MrMelbert

**Closed by SuperNovaa41** 2022-03-13 21:08 UTC
