### ISSUE TITLE
Doubled railings can't be climbed over.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54066] opened 2020-09-29 02:55 UTC
## Reproduction:
1. Acquire metal rods.
2. Construct two sets of railings back-to-back.
3. Attempt to climb over either of the railings.
4. Get blocked by the other railing.

**Comment by timothymtorres** [comment] 2021-12-17 12:40
You shouldn't even be able to build double railings on the same tile.  Were both railings on the same dir?

**Comment by timothymtorres** [comment] 2022-02-18 04:55
If that's the case then this really isn't a bug.  Should you be able to jump over the 2nd railing if a directional window was blocking the way?  You are wanting a way for someone to leap over two adjacent railings and this doesn't make sense.  Just deconstruct one of them or if this is a mapping issue that needs to be remapped... but for now I'm marking this as `Not a Bug`

**Closed** 2022-03-02 15:53 UTC
Labels: Not a bug
