### ISSUE TITLE
Rechargers are seemingly nonfunctional, attempting to use them attacks them instead

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#38880] opened 2018-07-03 00:08 UTC
Round ID: 90379
based off ecf60367ab

Title gives you the general idea. Rechargers seem to have stopped working. I have unwrenched them and move them to several different rooms, all with fully functional APCs, and every attempt to put an item in instead causes me to attack it. Picture related.
![dreamseeker_2018-07-02_20-00-01](https://user-images.githubusercontent.com/5360736/42191845-267eedb8-7e33-11e8-8fdd-3085ada535fb.png)

EDIT: If it's any further clarification, I have tried with multiple entirely seperate rechargers and multiple entirely seperate items such as energy guns and laser guns with the same result.

**Comment by newfren** [comment] 2018-07-03 04:18
You've tried with multiple intents as well?

**Comment by Jared-Fogle** [comment] 2018-07-03 15:17
you were probably on harm intent

**Comment by Cyprex** [comment] 2018-07-03 21:21
Are you using weapon chargers or cell chargers?

**Comment by Daundra** [comment] 2018-07-03 23:03
I have tried multiple intents. None of them worked.
This bug seemingly went away after this round. I don't understand why.
I was using weapon chargers. NOT cell chargers. I know the distinction.

**Comment by fnordfnord** [comment] 2018-07-03 23:13
I can confirm this happening

![confirmed problem](https://user-images.githubusercontent.com/40809917/42248701-de1c069c-7edb-11e8-96be-5f44f422cc51.png)

All attempts done on help intent, tried multiple rechargers with different guns all ended up smacking the charger.

**Comment by Jared-Fogle** [comment] 2018-07-04 03:35
Can't reproduce

**Comment by Cyprex** [comment] 2018-07-04 13:34
Are cell chargers also affected or is this limited to weapon chargers?

**Comment by Kromgar** [comment] 2018-07-04 15:31
Maybe this is similar to that fire extinguisher glitch?

**Comment by Stickymayhem** [comment] 2018-07-04 16:42
Just encountered this bug again. My first thought was it has the same root cause as the IV drip issue

**Comment by SpaceManiac** [comment] 2018-07-04 23:03
The fire extinguisher thing (#38597) was a real bug with a real fix.

This appears to be a BYOND issue and is probably the same as #38720.

**Comment by SpaceManiac** [comment] 2018-07-05 00:21
I can confirm this is NOT an intent problem. Guns are supposed to insert into rechargers even on harm intent.

Cannot reproduce trivially; I'm assuming something is going wrong later in the round.

**Comment by optimumtact** [comment] 2018-07-07 01:52
This is happening on sybil now

**Comment by rustledjimm** [comment] 2018-07-07 13:19
This is really becoming a major issue. Nothing can be charged in rechargers.

**Comment by Jared-Fogle** [comment] 2018-07-07 18:15
Medical is struggling as well, every shift we need to make bottles of saline glucose because the IV drips don't work.

**Comment by Hathkar** [comment] 2018-07-08 16:38
I've had this happen with the recharger in the Kobayashi Maru holodeck setting. I tried turning the holodeck on/off again, no dice.

**Comment by AnturK** [comment] 2018-07-08 16:50
Okay so this was most likely caused by holodeck trying to copy static vars with that static read bug. So the new static would be overridden by wrong (null) value. If this happens again after 1435 i'll be surprised.

**Comment by AnturK** [comment] 2018-07-08 16:53
Actually i'll just close this because this is easily replicated.

**Closed by AnturK** 2018-07-08 16:53 UTC
Labels: BYOND Issue
