### ISSUE TITLE
tgui interfaces break when minimized

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35592] opened 2018-02-12 18:30 UTC
https://gfycat.com/SandyNeedyJellyfish

**Comment by praisenarsie** [comment] 2018-02-12 19:06
they don't break for me unless this is recent, needs reproducing

**Comment by ike709** [comment] 2018-02-12 19:41
This has happened to me pretty much ever since TGUI was added.

**Comment by Slignerd** [comment] 2018-02-12 19:43
You need to use the 'Fancy' tgui style to reproduce the bug.

**Comment by Cyberboss** [comment] 2018-02-12 22:31
The workaround is right-click -> restore

**Comment by ShizCalev** [comment] 2018-02-13 01:34
Duplicate of #26644

**Closed by ShizCalev** 2018-02-13 01:34 UTC
