### ISSUE TITLE
PLEASE ANSWER IN 10 SECONDS! DO YOU WANT TO PLAY AS RED ADULT SLIME (435)? PLEASE ANSWER IN 10 SECONDS! DO YOU WANT TO PLAY AS ORANGE ADULT SLIME (754)? 

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40242] opened 2018-09-12 09:14 UTC
Issue reported from  Round ID: 93781 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

There is no way to block these _utterly obnoxious_ popups generated by overloading Supermatter Engine and nobody ever plays the insta-dying SME slimes anyway.

Best solution: add preference choice to them.  
Good solution: remove sentience from SME slimes so they don't do popups.  
Good solution: remove spontaneous slime spawns from SME entirely.

**Comment by Vidiveni** [comment] 2018-09-12 09:46
DO YOU WANT TO PLAY AS TIDER McTIDER'S DEFECTIVE CLONE?
DO YOU WANT TO PLAY AS TIDER McTIDER'S DEFECTIVE CLONE?
DO YOU WANT TO PLAY AS TIDER McTIDER'S DEFECTIVE CLONE?

This one too please. A preference option would be fine.

**Comment by kriskog** [comment] 2018-09-12 12:08
I would prefer a preference, as it is possible to get away from the SME before it blows.

Also, shades got no button. I've seen the chaplain spam this quite a bit. They may be included under constructs in notification preferences though.

**Comment by ShizCalev** [comment] 2018-09-17 20:58
duplicate of #15583

**Closed by ShizCalev** 2018-09-17 20:58 UTC
