### ISSUE TITLE
Dying boots player back to lobby occassionally

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#38898] opened 2018-07-03 20:28 UTC
Issue reported from  Round ID: 90430 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Sometimes on death, an individual is booted back to the lobby as opposed to being made an observer. Happened once during round reported with a magikarp getting booted to lobby after dying, and if memory serves correctly, I've had similar ahelps in the past about people dying and getting booted back to lobby.

**Comment by MrStonedOne** [comment] 2018-07-03 22:10
Please edit this issue report

All mobs types handle death differently

Do not make this a generic "dieing does this" issue report

The title and content should focus around what mobs are doing this.

This issue report will be closed in 3 days if this is not fixed.

**Comment by AnturK** [comment] 2018-07-04 05:29
Yeah, needs bit more information. What mob, how did you get control of it , how did you die.

**Comment by Tlaltecuhtli** [comment] 2018-07-04 07:04
i was one of the affected and i ll descripe what happened:
my stats: win 10 byond 1426 round id 90430
> be me obeserving
> "want to be magicarp" pops up
> accept
>fireball carp
>suicide
>new carp appears
>message "want to be magicarp" pops up
>press accept (not sure if it crashed before or after i accept)
>game freezes
>crash
>re enter server
>i m in the lobby

**Comment by Ignies** [comment] 2018-07-06 08:10
I've had this happen to me, if you are in the middle of spawning in, and your game crashes or hang, your body is spawned but you are returned to the lobby.

To sum it up,
1. Ready up / spawn
2. Disconnect while spawning
3. Boot the game and confirm that you returned to the lobby
4. Spawn again to meet your evil twin

**Comment by AzureWildfire** [comment] 2018-07-06 14:42
This happens when you die/spawn while crashing/disconnecting, I suppose is a problem with the client not getting registered in the server because of the sudden disconnect or crash. 
When you open byond again, the server detects you as a new player and asks you to join like if you were a new player for the round.
I think this is a known bug, I don't really know why you are not still registered when you die, but is not limited to a mob.

**Comment by optimumtact** [comment] 2018-07-25 10:15
Reprod steps from #39297 

[Reproduction]: # Die and dc before your body is sacrificed, without ghosting.

Priority critical. Holy fuck.

**Comment by Cyprex** [comment] 2019-09-10 12:15
This is still relevant, I'm not sure if this should be in it's own ticket, but
1. Be alive
2. DC
3. While disconnected, have a cult member shard you.
4. When reconnecting I was a ghost in thunderdome, where I died, and also made this menu show up:
![Screenshot_20190910_141319](https://user-images.githubusercontent.com/35031555/64612926-39a32a00-d3d5-11e9-9e6b-eb1eef4b556e.png)
Trying to press any buttons gave me "The mulebot #1 makes a sighing buzz"

ID:118155 on Terry, screenshot is at 00:37:49 round time

**Comment by optimumtact** [comment] 2019-09-10 20:54
`The mulebot #1 makes a sighing buzz`

what on earth

**Comment by kriskog** [comment] 2019-11-11 21:26
Closing in favor of #47720

**Closed by kriskog** 2019-11-11 21:26 UTC
Labels: Bug
