### ISSUE TITLE
Traitors getting only free objectives, steal X, and escape

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20017] opened 2016-08-21 21:59 UTC
Mikey555 was Rachel Baskett the Assistant and died
Objective #1: Steal a functional AI. Fail.
Objective #2: Steal the station blueprints. Fail.
Objective #3: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Forest3r was Vishnu the AI and survived as Ulysses
Objective #1: Free Objective Success!
Objective #2: Free Objective Success!
Objective #3: Stay alive until the end. Success!
The traitor was successful!

AutisticToaster was Gary Enderly the Roboticist and had their body destroyed
Objective #1: Steal the head of security's personal laser gun. Fail.
Objective #2: Steal the chief engineer's advanced magnetic boots. Fail.
Objective #3: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Multiple rounds this is happening.

**Comment by optimumtact** [comment] 2016-08-21 22:06
I cannot find any recent pr that would explain this. Check config on the server perhaps?

**Comment by optimumtact** [comment] 2016-08-21 22:16
@AnturK maybe related to #19937

**Comment by PKPenguin321** [comment] 2016-08-21 22:45
make a revert PR for that and testmerge it so we can find out
i would do it but im not a fancy shamncy maintainer like @optimumtact is

**Comment by Shadowlight213** [comment] 2016-08-21 22:53
@optimumtact I can't find any config setting that would explain it.

**Comment by RemieRichards** [comment] 2016-08-21 22:55
@PKPenguin321 maintainers can't testmerge.
we have to beg for that too. you're equal to oranges in power over getting a revert testmerged.

**Comment by MrStonedOne** [comment] 2016-08-21 23:04
i think #20009 is test merged and could cause this

**Comment by Shadowlight213** [comment] 2016-08-22 00:31
@MrStonedOne this occurred on bagil. 20009 isn't testmerged there.

Also, I testmerged #20021 and for some reason it still failed to give targets. However, when I called the proc manually it seemed to work fine.

**Comment by MrStonedOne** [comment] 2016-08-22 00:40
Try 20020 just to see if we even have the causing pr right

**Comment by Shadowlight213** [comment] 2016-08-22 00:55
k

**Comment by Shadowlight213** [comment] 2016-08-22 02:00
@MrStonedOne Reverting fixed it. Traitors got assassinate objectives. It's definitely that pr.

**Comment by AnturK** [comment] 2016-08-22 06:22
Hmm, the first fix should have worked.

**Comment by Jalleo** [comment] 2016-08-22 08:11
Right the issue is there are no crew members when the roundstart antags are picked. We have to go via the old method first since there shouldn't be any ashwalkers by the start of the round.
@AnturK reason for this is the whole players in sec then have a chance of antag instead of being told nope due to jobs then being picked before antags now all antags are picked first.
The solution to this is have all antags picked then have them cycle through to get jobs. Then give it a few seconds for the manifest to fill. Then give the objectives.

**Comment by Shadowlight213** [comment] 2016-08-22 17:52
@Jalleo the thing is, we checked the controller sequence. Making the manifest is called before post_setup() where forge_objectives is called.

**Comment by AnturK** [comment] 2016-08-22 19:45
It's because somone though it was prudent to just throw in a sleep in in the proc instead of doing this properly. I'll fix this in a moment.

**Closed** 2016-08-23 21:43 UTC
Labels: Bug
