### ISSUE TITLE
Wizard reviving as a lich loses their spells

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#29701] opened 2017-08-04 00:47 UTC
At least the first time I did. After given a second spellbook by an admin, subsequent deaths I kept my new spells.

**Comment by Armhulen** [comment] 2017-08-04 01:04
dupe of something but still really annoying and horrible

**Comment by ShizCalev** [comment] 2017-08-04 01:24
#28846

**Comment by AnturK** [comment] 2017-08-04 06:29
Duplicate of #28846

**Closed by AnturK** 2017-08-04 06:29 UTC
