### ISSUE TITLE
Printing a Laptop Frame in the autolathe completely locks it up.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#19950] opened 2016-08-18 13:03 UTC
The autolathe will be permanently stuck busy, making it impossible to use or deconstruct.

**Comment by optimumtact** [comment] 2016-08-19 09:17
@Shadowlight213

**Comment by Shadowlight213** [comment] 2016-08-19 17:53
Odd. I'll look into it.
Also who the fuck made it so you can't decon a busy autolathe? Seriously.

**Comment by Shadowlight213** [comment] 2016-08-20 01:05
Ok. I think I know what the issue is. The laptop frame is a machine. The autolathe seems to assume that it will be building an item.
I'll see what I can do.

**Comment by Jalleo** [comment] 2016-08-25 12:00
This is fixed please close it https://github.com/tgstation/tgstation/pull/20003

**Closed** 2016-08-25 12:16 UTC
Labels: Bug
