### ISSUE TITLE
[WHY DID NO ONE GET IRKED ABOUT THIS YET] wall mounts stay floating if the wall they're on is destroyed

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26164] opened 2017-04-13 00:40 UTC
convicts: posters, fire axe displays, mirrors and intercoms.

let us END THIS please just make them deconstruct or delete or something fuck my emulsions
![dreamseeker_2017-04-13_03-38-52](https://cloud.githubusercontent.com/assets/16103879/24985153/fb52f5fe-1ffa-11e7-804f-3126ee265d04.png)

**Comment by optimumtact** [comment] 2017-04-13 02:35
Mostly due to the fact they're nto actually on the wall.

**Comment by PKPenguin321** [comment] 2017-04-13 03:27
dupe i think

**Comment by Militaires** [comment] 2017-04-13 03:35
@PKPenguin321 i dont think so i searched

**Comment by RandomMarine** [comment] 2017-04-13 05:29
Dupe of  #22283

**Closed** 2017-04-13 05:37 UTC
Labels: Bug
