### ISSUE TITLE
Lava does not burn objects

### ISSUE THREAD

**Issue by frayedition** [tgstation/tgstation#39981] opened 2018-08-28 22:11 UTC
I burn and things don't burn, like plasma and ore and stuff like that.

**Comment by frayedition** [comment] 2018-08-28 22:12
fix this please

**Comment by kingoftheautism** [comment] 2018-08-29 01:46
Just to let you know guys, we both playing on same /tg/ based server that wasn't merging for like month for specific reason (host isn't home so he cannot merge), and it's probably was neither already fixed or only our-side issue

**Comment by DfourC** [comment] 2018-08-29 13:31
This is the same issue as #39066

**Comment by SpaceManiac** [comment] 2018-08-29 18:02
Duplicate of #39066

**Closed by SpaceManiac** 2018-08-29 18:02 UTC
Labels: Bug, Tested/Reproduced
