### ISSUE TITLE
Getting stunned while using a Bar Dispenser makes it unusable

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#16960] opened 2016-04-18 17:43 UTC
Booze Dispenser in question had a drinking glass in it, I vomited, and then I couldn't use it

**Comment by KazeEspada** [comment] 2016-04-18 20:10
Walk away and come back, TGUI failed to properly remove the UI from your active UIs.

**Comment by kriskog** [comment] 2019-07-11 20:21
Cant reproduce, should be fixed.

**Closed by kriskog** 2019-07-11 20:21 UTC
Labels: Bug
