### ISSUE TITLE
Crowbaring a floor tile opens a hull breach!

### ISSUE THREAD

**Issue by ftoxs** [tgstation/tgstation#54855] opened 2020-11-07 09:33 UTC
Issue reported from  Round ID: [149831](https://scrubby.melonmesa.com/round/149831) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

Right, so what I found was that crowbaring up a floor tile that spawned with the station by default works just fine. However, I can pry up a tile, replace that tile with the one that came up, crowbar it again, and it's a hull breach. This is an actual hull breach that sucks out atmosphere and makes things super cold. I repeated it in several areas, all around the station. Unknown if it works in custom areas or in space, though.

Another anomaly is that atmos and wiring remain unaffected, but invisible. When the breach is repaired with rods and a floor tile, the atmos and wiring bits become visible again and don't seem to suffer damage. Hope this helps!

**Comment by TemporalOroboros** [comment] 2020-11-07 10:43
@LemonInTheDark :eyes:

**Comment by cacogen** [comment] 2020-11-07 10:44
Fuckin' based. I may be wrong but I'm guessing it was #54250.

**Comment by TemporalOroboros** [comment] 2020-11-07 10:55
@cacogen I doubt it was #54250 because that was merged a couple days ago and I think people would have noticed this by now. I think it was caused by lemon in #54277.
Just in case @Qustinnus, do you think this is you?

**Comment by Ghommie** [comment] 2020-11-07 11:18
Definitely #54277.
Despite converting baseturfs to cached lists with string_lists(), he seems to have forgotten to remove this line:
https://github.com/tgstation/tgstation/blob/c102ad7e96512321eb423ad8bbb73e56398c75ba/code/game/turfs/change_turf.dm#L201

**Comment by Dennok** [comment] 2020-11-07 13:04
> Definitely #54277.
> Despite converting baseturfs to cached lists with string_lists(), Lemon seems to have forgotten to remove this line:
> https://github.com/tgstation/tgstation/blob/c102ad7e96512321eb423ad8bbb73e56398c75ba/code/game/turfs/change_turf.dm#L201

Not here


Something in PlaceOnTop

**Comment by Ghommie** [comment] 2020-11-07 14:21
> Not here
> 
> Something in PlaceOnTop

Yea, I noticed when reproducing it locally.

**Comment by LemonInTheDark** [comment] 2020-11-07 19:18
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ~thank you dennok/ghommie~

**Closed** 2020-11-08 10:19 UTC
Labels: Bug, FUCK, Needs Reproducing
