### ISSUE TITLE
DmIcons Easily Exceed Client Topic Limit

### ISSUE THREAD

**Issue by RimiNosha** [tgstation/tgstation#88152] opened 2024-11-23 20:01 UTC
### Client Version:

515.1637

### Issue Summary:

Surprised this hasn't been reported.

![image](https://github.com/user-attachments/assets/fb5bdba5-96f2-4ccd-bb3f-3c1cf8b071e9)

This shouldn't be happening.

### Round ID:

N/A (latest TG master as of issue creation)

### Test Merge Information:

None

### Reproduction Steps:

(Make sure you deadmin first!)

1. Go into loadout or the vendor.
2. Switch tabs once or twice.
3. O b s e r v e

**Comment by SyncIt21** [comment] 2024-11-24 03:07
This has been reported #87745. 

Do you have proof this is caused by DMIcon?

**Comment by RimiNosha** [comment] 2024-11-24 04:54
87745 is not the same issue.

DmIcon makes a topic call to get the icon ref to use to display the item/icon/whatever.

**Comment by AnturK** [comment] 2024-11-24 15:38
This was fixed in 515.1638

**Closed by AnturK** 2024-11-24 15:38 UTC
Labels: BYOND Issue

**Comment by RimiNosha** [comment] 2024-11-24 17:25
At least it's documented in a public place now, thanks for the heads up.
