### ISSUE TITLE
Crew manifest is blank.

### ISSUE THREAD

**Issue by fizzle7** [tgstation/tgstation#29115] opened 2017-07-07 13:09 UTC
Join as CE late in round, look at PDA crew manifest, blank. Refresh, blank, reenter, blank, reinsert id card, blank, look at console manifest then look at pda, blank.

**Comment by ohnopigeons** [comment] 2017-07-16 04:52
Can't reproduce. Probably fixed with https://github.com/tgstation/tgstation/pull/28989. Good meme reporting this bug RIGHT after the fix was merged.

**Closed** 2017-07-22 14:52 UTC
Labels: Bug
