### ISSUE TITLE
Default emgerency shuttle not arriving to the station

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/tgstation#25335] opened 2017-03-21 00:47 UTC
For whatever reason the default shuttle won't go to the station and instead will launch the tiny 'backup shuttle'

**Comment by optimumtact** [comment] 2017-03-21 05:16
Map?

**Comment by StuAhpla** [comment] 2017-03-21 05:45
Delta and Ceres

**Comment by optimumtact** [comment] 2017-03-21 05:57
Seems map specific I think.

might be related to their shuttle ports being too big or small.

Thanks for the report.

**Comment by BeeSting12** [comment] 2017-03-21 14:22
I'm pretty sure this happened on ceres so might want to look at that @MMMiracles

**Comment by MMMiracles** [comment] 2017-03-21 14:40
This is a recent issue, as I didn't run into this before when local testing or the past tests on basil/sybil.

**Comment by Penguaro** [comment] 2017-03-22 00:34
Must be part of a testmerge since locally I don't have Ceres yet.

**Comment by octareenroon91** [comment] 2017-03-29 16:26
More data: Sybil shift ending 03-29, at 16:25 server time:
Backup shuttle was sent to the station, even though the standard shuttle was ready and waiting at Centcom. The dock (and whatever ship, I can only guess at backup) was eaten by a singularity by the time I was checking.

**Comment by optimumtact** [comment] 2017-03-29 20:04
Okay so there's definitely a bug happening then.

Thanks

**Comment by StuAhpla** [comment] 2017-03-29 22:12
There was a war ops round on delta that had no shuttle arriving at all, not even the backup. Also when the shuttle was supposed to 'arrive' to centcom the server soft locked and required a round restart. The crusier shuttle got ordered that round.

**Comment by octareenroon91** [comment] 2017-03-30 03:00
#25550 : also shuttle bug.

**Comment by WJohn** [comment] 2017-06-02 13:12
I can't reproduce it on either map. I think this was fixed with the "shuttles are broken" bug.

**Closed by WJohn** 2017-06-02 13:12 UTC
Labels: Bug, Map Issue
