### ISSUE TITLE
Pirate Crew can't spawn on icebox

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#62919] opened 2021-11-18 00:01 UTC
## Reproduction:
Observe a ninja see him hack comms console wait a bit see pirate crew get announced wait 40 minutes nothing happens because THEY can't spawn in icebox pretty big oversight I would say so myself

**Comment by NanoCats** [comment] 2021-11-18 01:34
You might wanna edit this title to can'**t*

**Comment by SuperNovaa41** [comment] 2021-11-18 12:34
Yes, fix your title.

**Comment by SethLafuente** [comment] 2021-11-19 00:08
> Yes, fix your title.

I mean the issue is the fact that they get called in to icebox when they should hens the title "they can spawn" 

Unless the actual Issue is that they can only spawn in space which icebox doesn't have and their meant to be on icebox then the  title should be "they can't spawn"

I would rather them not spawn at all since icebox is absolute cancer when it comes to ship landing but adding them would be alright

**Comment by NanoCats** [comment] 2021-11-20 04:00
> > Yes, fix your title.
> 
> I mean the issue is the fact that they get called in to icebox when they should hens the title "they can spawn"
> 
> Unless the actual Issue is that they can only spawn in space which icebox doesn't have and their meant to be on icebox then the title should be "they can't spawn"
> 
> I would rather them not spawn at all since icebox is absolute cancer when it comes to ship landing but adding them would be alright

There's no reason in my mind that pirates would be unwilling to attack Icebox stations specifically.

**Comment by timothymtorres** [comment] 2021-12-28 10:03
Duplicate of #53689

**Closed by timothymtorres** 2021-12-28 10:03 UTC
Labels: Oversight
