### ISSUE TITLE
pAI's can block bullets

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#44578] opened 2019-06-16 23:12 UTC
Round ID: 110773

pAI's can be used as free bullet sponges with no downside.

**Comment by kriskog** [comment] 2019-06-17 00:53
The downside is they take damage and lose holochassis for a while.

**Comment by HomocidlePancakes** [comment] 2019-06-17 06:32
Dupe of #44143

**Comment by OmegaShoots** [comment] 2019-06-18 05:46
@kriskog that's not a downside that's just a timelimit on how much they can troll you and protect their master
They should not be able to interact with things physically, it's a reason why they can't drag

**Comment by Dorsisdwarf** [comment] 2019-06-19 15:17
This is kind of a dupe, they're meant to be small objects but crawling ruined everything forever

**Closed by Dorsisdwarf** 2019-06-19 15:17 UTC
