### ISSUE TITLE
Stuff in suit slot sometimes invisible

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#66844] opened 2022-05-10 00:36 UTC
Reporting client version: 514.1583

## Round ID:
[182903](https://scrubby.melonmesa.com/round/182903)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:

I spawned in as a security officer and my disabler did not appear in my suit slot. I clicked the slot and it popped into my hands, suddenly visible. When I put it back it was visible.

I observed this with the fish doctor on my local a couple days too.

**Comment by wesoda25** [comment] 2022-05-10 01:11
Update: I later got an energy gun. That would always turn invisible when I put it into my suit slot

**Comment by TemporalOroboros** [comment] 2022-05-10 08:55
I've noticed this happening semi-consistently when e-equipping chem bags.

**Comment by Palpetinus** [comment] 2022-05-11 07:41
I only know that re-equipping the suit item (so the armor, coat or such) usually fixes the issue. It's also not only roundstart clothing, I had it on MD before after swapping the coat for a winter coat, although far rarer.
I can say for sure though, that once it's fixed it won't break anymore and if it's broken and doesn't display, even pulling the item out and putting it back in might not fix it.

**Comment by dragomagol** [comment] 2022-06-26 03:57
#67048 is a duplicate of this, but that issue has the fix PR linked to it

**Closed by dragomagol** 2022-06-26 03:57 UTC
Labels: Bug
