### ISSUE TITLE
Mechs and Space Travel

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#30366] opened 2017-09-03 01:22 UTC
Not sure if this is a bug or a feature, but I figured I'd put it up here and find out.

Build a RIPLEY and added a Heavy Plasma Cutter and Fire Extinguisher. Headed out into space, thinking I would be able to move myself around with those tools. Turns out, No matter how many plasma cutter shots or extinguisher blasts I used, I kept moving forward. And I couldn't turn my mech to face any different directions in space, but I'm pretty sure that's intentional.

**Comment by GunHog** [comment] 2017-09-03 01:37
You are big, and massive (physics mass, known as "m")! Your extinguisher and cutter do not have the force necessary to significantly counter your fat machine's inertia. You could move if you had thrusters installed, but this not the case for crew made mechs.

**Comment by Repukan** [comment] 2017-09-03 02:02
Not an issue, there's mech thrusters for that.

Also sweet MMZ avatar

**Comment by GunHog** [comment] 2017-09-03 03:08
Well, mech thrusters only applies to the Syndicate mechs which are restricted to Nuke Ops. That option is not ever available to other mechs or normal crew. 

Anyway, I am sure that non-Syndie mechs being unaffected by firing weapons or extinguisher squirts is intended. Your only way to avoid this issue to avoid being spaced in a mech.

**Comment by pubby** [comment] 2017-09-03 12:15
Dupe of #9282

**Comment by YakumoChen** [comment] 2017-09-04 06:48
@GunHog Excuse me but what is Newton's Third Law

**Comment by FantasticFwoosh** [comment] 2017-09-04 07:29
Asking for thrusters isn't a bug, its a suggestion and probably doesn't belong here, you could try other weaponry not least the firefighter ripley's extinguisher but i doubt that'd work.

- Mech's are entirely independent of space wind and you could atleast say they are bulky enough & gravitationally attached to the floor (even when there is no floor) given you can stand in extremely strong void vacuum's and your mech won't move a inch.

**Comment by AnturK** [comment] 2017-09-04 11:49
Realism is irrelevant to the issue here.  Also don't believe adding free space movement to every mech would make them any better.

**Comment by Cyberboss** [comment] 2017-09-05 17:35
Duplicate of #9282

**Closed by Cyberboss** 2017-09-05 17:35 UTC
Labels: Balance/Rebalance
