### ISSUE TITLE
Bed Rotations and character placement don't align

### ISSUE THREAD

**Issue by Cyber-Finn** [tgstation/tgstation#86521] opened 2024-09-06 22:20 UTC
### Client Version:

515.1637

### Issue Summary:

Description of issue:
When buckled to beds, the character will sometimes be strapped with their legs on the pillow, instead of their heads on the pillow. 
The rotation and placement are slightly broken, so the character rotation doesn't match to the bed's rotation and gets strapped in with a different orientation to the bed.

## Media of the issue:
This is an ingame (Within a round on TG/Terry) screenshot of a bed where the pillow is on the left-hand side:
![image](https://github.com/user-attachments/assets/29f5dc18-3418-4b4e-9911-2816f49cc1ab)
Incorrect character placement when buckled: (I should be laying on the pillow, but have my legs on it instead)
![image](https://github.com/user-attachments/assets/01d93da6-a645-4c4b-b367-eb68f08aa116)

ingame (Within a round on TG/Terry) screenshot of bed with right-hand pillow:
![image](https://github.com/user-attachments/assets/a36b68d1-e85a-4a92-b2c4-d7cde167f59f)
Incorrect character placement when buckled: (I should be laying on the pillow, but have my legs on it instead)
![image](https://github.com/user-attachments/assets/cd323c16-7d80-4b63-bf9d-a949de8c6ecd)

### Round ID:

[236925](https://scrubby.melonmesa.com/round/236925)

### Test Merge Information:

There was recently a pull request that affected beds, which read something like "players now use bed pillows when buckled", I'm not sure if that caused this issue, or if this happened beforehand, but it may be a good place to start investigating.

### Reproduction Steps:
Buckle yourself to a bed (Medical or Regular beds -> crafted or existing) 
Test with different bed rotations (pillows on the right or left-hand side)

**Comment by 00-Steven** [comment] 2024-09-06 22:28
???? wait what i could SWEAR i fixed this

**Comment by 00-Steven** [comment] 2024-09-06 22:28
lemme go take a look again

**Comment by 00-Steven** [comment] 2024-09-06 22:40
I cannot reproduce this on dev, wawastation, with both the roundstart beds and beds in all four possible directions
![image](https://github.com/user-attachments/assets/e210c638-6637-48cf-b6fe-172d7bc9fca4)
![image](https://github.com/user-attachments/assets/1711345e-23a4-44c4-ac15-ee85c7da942d)

![image](https://github.com/user-attachments/assets/401b87e4-5ffa-4545-b861-48aa7089bf44)
![image](https://github.com/user-attachments/assets/005848f1-80b1-4b47-a160-94fa9a80a816)
![image](https://github.com/user-attachments/assets/e9da813b-65d2-4c1a-9cf5-1f28b2bdcf0d)
![image](https://github.com/user-attachments/assets/f52e7e92-3a76-42d4-8d98-08a704dd45f3)

Notably roller beds are a bit of an exception due to being movable, so there's some jank behaviours that are known

**Comment by 00-Steven** [comment] 2024-09-06 22:46
Do you have any more information regarding the context of the first non-rolled bed?

**Comment by Cyber-Finn** [comment] 2024-09-07 18:17
Hi, I dont know these stations very well, but I was luckily recording at the time.

Station was: Delta Station

For the first 2x screenshots: 
I was in Dorms. The room at the top-right, where it leads into the South Sec maints. The carpet looks different because someone made that foam that creates carpets everywhere.

Here's a video of where I was first in the room, and buckling worked fine (This also shows exactly which room it was)
https://github.com/user-attachments/assets/0e83c2d5-1b1c-4334-b6c4-1d911f05cd8f

I then recreated the bed and buckled myself in, but got strapped the wrong way:
https://github.com/user-attachments/assets/96198983-a1bc-4ceb-9efa-3e1a0627601a
Immediately after this, I went into github to report the issue, and someone flooded all the scrubbers with those carpet bombs lol

This is another video of where I was in med (also ingame) where the same happened - this was actually when I first noticed the issue:
https://github.com/user-attachments/assets/8114277f-1832-49ca-a69a-6e38bf39bb3b

**Comment by Cyber-Finn** [comment] 2024-09-07 18:27
This bed in med seems to have affected a few players:
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/b1663fa6-39d3-4afb-8edc-2d1707d448a7">

This was from a round today on MetaStation (round ID is 237021):
![image](https://github.com/user-attachments/assets/aa3884b2-7256-4ac3-9ab4-6c9688867317)
This was a bit later into that round:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/ba1b6ae9-415c-4a5c-be77-20aac3efea95">
https://github.com/user-attachments/assets/6c88b23c-c06a-42fb-9829-e389c23eb367

**Comment by 00-Steven** [comment] 2024-09-07 23:23
Right so, took another quick look based on what you sent and, while I'm still trying to reproduce the stasis bed or regular bed issues, I think I know why it's wonky with medical/roller beds.
So, there's two issues with roller beds and buckling, one I knew (and thought was at play) and one I didn't know and learnt from that final video buckling to the roundstart medical bed.

The first one which I already knew about and _thought_ was at play is that it currently doesn't always update the buckle angle of the human lying atop of it properly when you're moving it.
However, the secondary issue that I now think is _actually_ at play here is, well:
![image](https://github.com/user-attachments/assets/11e45b65-5543-4b54-ac3c-b43d17eec401)
The medical/roller beds and the regular bed in these picture have the same direction, but as you can see the headrest is located differently:
![image](https://github.com/user-attachments/assets/686387f9-dfa8-4426-baac-a1dee74286cf)
So before the change to make bed buckles consistently, both regular and roller/medical beds would buckle correctly on half of these directions, just different halves! But now, because it's coded to be consistent to regular beds (theoretically), it's always wrong on roller/medical beds.

I can probably put a fix for that part in tomorrow, at least,

**Comment by 00-Steven** [comment] 2024-09-07 23:23
Thanks for the additional information!

**Comment by Cyber-Finn** [comment] 2024-09-08 08:43
Ah tht's awesome! Thanks so much for the help! Really appreciate your time and effort that went into investigating this 😄⭐

**Comment by 00-Steven** [comment] 2024-09-10 23:28
That should be the roller/medical bed part of this fixed, though I'm unsure whether it's up on Terry yet.

**Comment by lessthnthree** [comment] 2024-09-20 17:07
https://github.com/tgstation/tgstation/pull/86003
https://github.com/tgstation/tgstation/pull/86556

**Closed** 2024-09-20 18:15 UTC
Labels: Bug, Cleanup Flagged
