### ISSUE TITLE
Icon dump upon roundend item purchase showing

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#37397] opened 2018-04-23 22:52 UTC
Issue reported from  Round ID: 86930 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/12734451/39157117-5af8ce8a-4727-11e8-9f97-f5c1c73508e4.png)

[Reproduction]: It happened upon viewing the round-end report on a nuke ops round.

**Comment by SpaceManiac** [comment] 2018-04-24 02:48
Duplicate of #37392

**Comment by ShizCalev** [comment] 2018-04-24 02:51
Duplicate of #37392

**Closed by ShizCalev** 2018-04-24 02:51 UTC
