### ISSUE TITLE
gubbucks and guthins have stopped eating stuff again

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56059] opened 2021-01-09 11:42 UTC
![image](https://user-images.githubusercontent.com/42606352/104088269-20a9c380-522b-11eb-93b1-d5c49c9402b2.png)

**Comment by cacogen** [comment] 2021-01-09 18:48
Did you try attacking them to get them to eat?

**Comment by RaveRadbury** [comment] 2021-01-09 21:23
Should probably add hand-feeding like with cows

**Comment by Potato-Masher** [comment] 2021-01-09 21:53
The other day I was able to get them to eat once I dragged them a bit closer to the organ pile. Seems they only start once interacted with?

**Comment by ATH1909** [comment] 2021-01-09 22:56
> The other day I was able to get them to eat once I dragged them a bit closer to the organ pile. Seems they only start once interacted with?

I tried dragging one of them closer to the organs, but that didn't seem to help.

**Comment by timothymtorres** [comment] 2021-10-08 12:10
Duplicate of #47568

**Closed by timothymtorres** 2021-10-08 12:10 UTC
Labels: Bug
