### ISSUE TITLE
Lavaland plants are unharvestable

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#68718] opened 2022-07-24 20:03 UTC
## Round ID:
[187216](https://scrubby.melonmesa.com/round/187216)

## Testmerges:
n/a

## Reproduction:
1. Go down to lavaland looking for some cactus or mushrooms or whatever
2. attempt to harvest
3. nothing works, cry

**Comment by dragomagol** [comment] 2022-07-25 05:20
Duplicate of #68158

**Closed by dragomagol** 2022-07-25 05:20 UTC
