### ISSUE TITLE
Goldgrubs can fly

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61425] opened 2021-09-12 09:46 UTC
## Testmerges:
The following pull requests are currently test merged:
#61123: 'FAMILIES 4.0: "fuck it, MRP only this time"' by Iamgoofball at commit 5c69a20cbd

## Reproduction: 
https://puu.sh/IaLZP/4afcb2b517.png

Found this goldgrub while I was flying around. Possible it was spawned here? No idea! Definitely should be falling down, though.

**Comment by TemporalOroboros** [comment] 2021-09-12 11:06
Not a bug. The turf below it is a solid ice/rock wall and you can stand on those.

**Comment by ATH1909** [comment] 2021-09-13 07:56
they fly now?

they fly now.

**Comment by Time-Green** [comment] 2021-09-14 18:26
thanks for the report and keep up the good work, but it's not a bug (sadly no flying goldgrub)

**Comment by TheBonded** [comment] 2021-09-16 19:53
if this is marked as not a bug, sadly, why is it still open? we have so many open issue reports, no need to have non bugs clogging it up

**Comment by Time-Green** [comment] 2021-09-17 04:07
I thought I closed it, oops

**Closed by Time-Green** 2021-09-17 04:07 UTC
Labels: Not a bug
