### ISSUE TITLE
Icebox's lavaland ruin's floors regain icebox's default atmos when floors are placed on them.

### ISSUE THREAD

**Issue by Toastgoats** [tgstation/tgstation#65648] opened 2022-03-23 21:57 UTC
## Reproduction:

To explain a bit further, the lavaland ruin's atmos seems to be designed to be tolerable without cold protection gear, however, after placing some floors on the ground to settle in after I fell two z levels into an inescapable pit, it seemed to reactivate the normal icebox ice wastes atmos.

![lavaland](https://user-images.githubusercontent.com/63932673/159799236-20e2b46c-23fe-4e55-8f39-8bfc792c9567.JPG)

**Comment by GoblinBackwards** [comment] 2022-03-24 18:57
Are you sure it wasn't just cold because the air leaked out into the upper z levels through the hole?

**Comment by timothymtorres** [comment] 2022-03-29 00:50
Duplicate of #46696

**Closed by timothymtorres** 2022-03-29 00:50 UTC
