### ISSUE TITLE
Buttons for Coat Hoods, Flashlights, Internals, etc. Not Appearing

### ISSUE THREAD

**Issue by PrismaticLoop** [tgstation/tgstation#76405] opened 2023-06-29 07:52 UTC
Reporting client version: 514.1589

## Round ID:
[209296](https://scrubby.melonmesa.com/round/209296)

## Reproduction:
Top-left icons for buttons not appearing when wearing apparel that can change (i.e. coat/cloak hoods/welding masks/goggles), toggleable objects (i.e. flashlights/RPED and bag gathering modes) and most importantly, INTERNALS. Tried restarting, resetting the buttons

**Comment by SyncIt21** [comment] 2023-06-29 09:49
Duplicate of #75578

**Comment by Sealed101** [comment] 2023-06-29 11:14
this is recent and it seems to have been reported to be an issue for multiple people, there may be something else at play here

**Comment by SapphoQueer** [comment] 2023-06-29 11:30
Don't think it's a duplicate, been happening server-wide, atleast for manuel, for the past couple of shifts.

**Comment by Rex9001** [comment] 2023-06-29 14:22
This has been happening to everyone multiple shifts in a row on Terry.

**Comment by TheVekter** [comment] 2023-06-29 16:29
We've got another one lads

**Closed** 2023-06-30 11:19 UTC
Labels: Bug, FUCK
