### ISSUE TITLE
UI windows turning solid white

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#32806] opened 2017-11-16 09:44 UTC
Can someone tell me what I can do to fucking fix this because it is turning me insane. I can't reproduce it, it just happens from time to time, UI windows from machines turn white and I can only fix it by relogging, and even then it will just happen again randomly.

**Comment by lzimann** [comment] 2017-11-16 09:50
Sadly this is a byond issue: http://www.byond.com/forum/?post=2211145

**Comment by WJohn** [comment] 2017-11-16 20:25
Yep, had this happen to me too. Had to relog.

**Comment by Shadowlight213** [comment] 2017-11-22 16:32
You can fix it temporarily by using the fix chat verb and forcing a reload of goonchat.

**Comment by ShizCalev** [comment] 2017-12-12 03:49
Duplicate of #31745

**Closed by ShizCalev** 2017-12-12 03:49 UTC
Labels: BYOND Issue

**Comment by MegaRhinoKing** [comment] 2018-07-21 20:21
I have no experience so I don't know what shadowlight meant by his most recent post. Can someone guide me through this?
