### ISSUE TITLE
Grinder pulverizes items

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#31216] opened 2017-10-01 21:46 UTC
> put 1 plasma bar in the grinder
> eject ingredients
> no plasma bar

**Comment by vuonojenmustaturska** [comment] 2017-10-02 16:20
probably related to/duplicate of #30316

**Comment by AnturK** [comment] 2017-10-02 16:23
Duplicate of #30316

**Closed by AnturK** 2017-10-02 16:23 UTC
Labels: Bug
