### ISSUE TITLE
Borg flashlight overlays missing

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#71223] opened 2022-11-12 05:42 UTC
Reporting client version: 514.1585

## Round ID:
[194171](https://scrubby.melonmesa.com/round/194171)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)

## Reproduction:
Be a borg.
Turn on your light, the colored glow overlay seems to be gone. 
![image](https://user-images.githubusercontent.com/81882910/201459211-20df23e3-c599-41a4-9ab1-1e00868665ec.png)
Older example of overlay working: 
![image](https://user-images.githubusercontent.com/81882910/201459245-42525d02-0d21-40b4-a8fe-aef50da9fa28.png)

**Comment by ShizCalev** [comment] 2022-11-12 16:44
Duplicate of #71036

**Closed by ShizCalev** 2022-11-12 16:44 UTC
