### ISSUE TITLE
Roundstart freezing issue

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#32474] opened 2017-11-06 19:31 UTC
At the start of a round on either bagil or sybil, most recently round 78433 on bagil, people are unable to move.

The effects are:
1. Most importantly, people who joined at roundstart are completely unable to move. Latejoiners are able to move normally.
2. Their mobs are not selectable in the mouse2 menu
3. Their name is null of null type (not a string containing null). Pastebin of VV available https://pastebin.com/YyscAxKS , though i've already tried varediting things like name and mouse opacity stuff

![image](https://user-images.githubusercontent.com/20017308/32459798-767066b8-c339-11e7-8af2-102b97b4bfeb.png)

**Comment by kevinz000** [comment] 2017-11-06 19:34
Lemme add that
1. Ticker subsystem has a client time timer for release characters that never fire. This is what I'm assuming is causing the actual freezing but not the other stuff.
2. I directly called release_characters on ticker, nothing happened.
3. I could fix the name thing by sdql calling prefs.copy to on every mob to force a transfer from prefs to mob.
4. I could fix the freezing by updating everyone's notransform to 0


As I type this I just realized that if release characters proccall didn't work that I probably found why it's broken, but I'll need another broke round when I'm on to confirm... (Maybe the player list or whatnot is null/empty...)

**Comment by kevinz000** [comment] 2017-11-06 19:35
Also if I do service restart it usually starts working for the next round after that.

**Comment by MrStonedOne** [comment] 2017-11-06 19:37
So, to be clear, once it triggers, a normal restart won't fix it, but a service reboot will?

**Comment by kevinz000** [comment] 2017-11-06 19:38
@MrStonedOne so far every time I service restarted it fixed but I'm not gonna say it's for sure.
I know it's broke after an immediate normal restart though.

**Comment by kevinz000** [comment] 2017-11-06 19:42
Also
5. I noticed there's no runtimes but turf decals every time it's broken and I've been on to check.

**Comment by YPOQ** [comment] 2017-11-06 19:54
#32447

**Comment by AnturK** [comment] 2017-11-06 21:27
What's interesting is mouse_opacity is set to 0 even besides the name problem

**Comment by vuonojenmustaturska** [comment] 2017-11-06 21:58
yeah that's a varedit

**Comment by LetterJay** [comment] 2017-11-12 16:09
Downstream here, just had this happen as well.

**Comment by Jalleo** [comment] 2017-11-12 18:59
@LetterJay Antur is trying to locate the cause. Could you let Antur know what things your downstream has merged recently to help locate the possible issue?

**Comment by bunny232** [comment] 2017-11-13 05:06
Fyi Being hit by a thrown object fixes it

**Closed** 2017-11-14 19:15 UTC
Labels: Bug, Priority: CRITICAL
