### ISSUE TITLE
Zero Gravity Float Drift doesn't work on station

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#53909] opened 2020-09-22 19:57 UTC
## Testmerges:
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
Cut the gravity to the station, push yourself off a wall into the middle of the room. Watch as you fail to drift, and shooting/throwing objects will not move you, leaving you stuck in the middle of the room unless you can fly, create mobs to push off of, or create walls to push off of.

**Comment by LemonInTheDark** [comment] 2020-09-23 00:58
Space movement runs off a subsystem, it was most likely just lagging at the time. I can't reproduce this locally

**Comment by Taylorkills2** [comment] 2020-09-23 01:47
Perhaps, but it was completely non-functional for multiple people in the round despite what would be average/normal day in terms of lag. If that's the case the subsystem needs a higher priority.

**Comment by Dennok** [comment] 2020-09-23 06:01
Betest way, make special spacedrifting for mobs(players) with hight priority.

**Comment by msgerbs** [comment] 2020-09-23 17:56
Idk if this is related but this round has a bunch of this runtime in the logs:

`movable_glide_size overridden. Use override = TRUE to suppress this warning `

**Comment by TheBonded** [comment] 2021-12-09 20:04
this was unable to be replicated at the time it was reported, and it seems like it is working now. closing this unless it still occurs

**Closed by TheBonded** 2021-12-09 20:04 UTC
Labels: Needs Reproducing
