### ISSUE TITLE
revert 512

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34459] opened 2018-01-15 08:43 UTC
its worse and unstable, it crashes and sometimes your windows turn white and you have to relog

**Comment by Buggy123** [comment] 2018-01-15 09:10
Also I'm 92% sure it's the cause of a incredibly annoying layer issue where sometimes vending machines vend items and they're _below_ the machine, so you have to right click to pick them up.

**Comment by ShizCalev** [comment] 2018-01-15 14:29
Duplicate of #31745

**Closed by ShizCalev** 2018-01-15 14:29 UTC
Labels: BYOND Issue
