### ISSUE TITLE
Sidings don't move with the shuttle when it moves

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#54156] opened 2020-10-02 21:20 UTC
## Round ID: 
On local

## Reproduction:
1) Use sidings on an escape shuttle
2) Load the shuttle into Centcom

For whatever reason after moving the shuttle to Centcom or moving the ferry, these decals don't show up.

**Comment by Fikou** [comment] 2020-10-02 21:22
Duplicate of #54053

**Closed by Fikou** 2020-10-02 21:22 UTC
