### ISSUE TITLE
Light sources keep shining after being turned off

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#68889] opened 2022-07-31 07:17 UTC
Reporting client version: 514.1575

## Round ID:
[187612](https://scrubby.melonmesa.com/round/187612)

## Testmerges:
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [fixes nuke ops leaders not spawning](https://www.github.com/tgstation/tgstation/pull/68855)
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)

## Reproduction:
Honestly don't know what causes it, but if you have a flashlight on, there's a chance that when you turn it off you'll keep a cone of "fake light" shining at the direction you were facing, so if it was east it'll keep facing east and there's no way to turn it off. It doesn't illuminate tiles but it makes visible tiles much easier to see, and this is especially noticable in a dark room with your flashlight off.

**Comment by Mooshimi** [comment] 2022-08-02 23:37
Dupe of #64256

**Closed by Mooshimi** 2022-08-02 23:37 UTC
Labels: Bug
