### ISSUE TITLE
Pipes (the ones used for smoking) continue burning when there's nothing to smoke and become unusable if left in this state for too long

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#59206] opened 2021-05-20 11:34 UTC
## Round ID:
n/a (tested locally)

## Testmerges:
None

## Reproduction:
1. Get a pipe or cob pipe
2. Put a small dried tobacco leaf in it, wear, ignite (not necessarily in this order)
3. Wait
4. Notice you ceased taking lung damage despite the pipe still being lit
5. Put the pipe on the ground
6. Wait for it to spawn ashes (it will take ages)
7. It will continue burning
8. If you extinguish it you will not be able to empty it (no message), light it ("There is nothing to smoke!") or put anything in ("It is already packed!")

**Comment by RaveRadbury** [comment] 2021-05-20 15:51
There's something similar going on with suckers and bubble gum, where you can wear it on your face until all the reagents are gone, and when they are you can no longer chew them in-hand to finish them off (pretty sure that before that they actually disappeared 🤷 )

**Comment by timothymtorres** [comment] 2021-11-02 10:30
Duplicate of #49637

**Closed by timothymtorres** 2021-11-02 10:30 UTC
Labels: Bug
