### ISSUE TITLE
Station cyborgs have "full" access to Nukeop Shuttle, including outer blast doors, and immunity to turrets.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#56577] opened 2021-02-01 17:39 UTC
## Round ID:
Any round for the last year or so

## Reproduction:

1) Be a station borg

2) Nuclear ops arrive 

3) Simply hunt and enter the shuttle when no ops are around, the turrets wont target you, you have access to the blast door and all interior doors.

4) You are now free to mess with the shuttle targeting, build walls to seal out the nukies, build walls to seal in the nuke, or just fill the entire shuttle with walls, you can just use their borg rechargers to re-juice and repeat.

Alternatively stay outside and wall off the entrance, the turrets, or try entombing the whole thing like chernobyl, and finally seal it off the door when you don't need the nukeop rechargers anymore. The turrets won't mind.

The only thing you cant do is specifically hit the "depart" button to send the shuttle away (unless theres something else I haven't found), but you can still deconstruct the computer so they cant escape.

5) Nukies lose because they trusted all their locks and blast doors and didnt keep half their team in the shuttle to defend against an engie borg rush.

My understanding is the nukeop shuttle turrets are balanced to make shuttle hunting impractical, instead of bannable, which it used to be.

Considering that, its kind of weird that all station cyborgs have full access to the shuttle and friendlyness with its turrets.

**Comment by ATH1909** [comment] 2021-02-01 19:46
> but you can still deconstruct the computer so they cant escape.

Are you sure about this? I could've sworn that I've tried it myself... Perhaps I just tried to do it the wrong way, though.

**Comment by ShibaInuLord** [comment] 2021-02-01 22:08
you can set the turrets to shoot borgs but I think i heard that it makes them shoot your borgs as well

**Comment by Serxule** [comment] 2021-02-01 23:13
> > but you can still deconstruct the computer so they cant escape.
> 
> Are you sure about this? I could've sworn that I've tried it myself... Perhaps I just tried to do it the wrong way, though.

yeah I can confirm, I watch borgs do this shit often if they're competent enough

**Comment by ShibaInuLord** [comment] 2021-02-02 02:25
i remember the console is indestructible but they can just break the door button to cuck ops

**Comment by Robustitron** [comment] 2021-02-02 06:59
> > but you can still deconstruct the computer so they cant escape.
> 
> Are you sure about this? I could've sworn that I've tried it myself... Perhaps I just tried to do it the wrong way, though.

I tried it offline before I posted, as an engie borg with a new server version. I was able to deconstruct it with tools, though I didn't think to try attacking it.

**Comment by zxaber** [comment] 2021-02-02 09:22
The biggest bug here is that the turrets don't target non-syndicate borgs. They certainly used to, and did so much damage that even getting to the outer airlock alive was a challenge.

Fixing the console being deconstructable should be fairly simple; just override screwdriver_act on that specific console and optionally throw in text to the user about being unable to find the screws.

**Comment by AlinaStarkova** [comment] 2021-08-02 15:12
> 
> 
> The biggest bug here is that the turrets don't target non-syndicate borgs. They certainly used to, and did so much damage that even getting to the outer airlock alive was a challenge.
> 
> Fixing the console being deconstructable should be fairly simple; just override screwdriver_act on that specific console and optionally throw in text to the user about being unable to find the screws.

i believe they changed it so they dont shoot borgs by default since if you, or a syndie borg, emagged a station borg, they would be shot dead due to the station borgs not getting flagged as a nukie 

we could probably refactor the syndie turrets to target borgs that are not syndicate borgs, so technically this means a traitor on station could emag a borg on station and tell it to drag a maxcap to the nukie shuttle, but tbh thats such a niche issue that its not an issue

**Comment by zxaber** [comment] 2021-08-02 17:13
We could also make emagging give the syndicate faction to the borg, which should make them immune to turret aggro like the syndi borgs.

**Comment by AlinaStarkova** [comment] 2021-08-02 19:24
> 
> 
> We could also make emagging give the syndicate faction to the borg, which should make them immune to turret aggro like the syndi borgs.

problem is that not all traitors are loyal to nukies, syndicate are a homogenous group, and a traitor could emag a station borg to then send to the nukie ship to cause mayhem

i suppose we could just add a check on emag to see if the emagger is a nukie, and if so make the emagged borg part of the nukie team, and have the turrets target borgs that arent on nukies team

ill see about coding this later tonight or tomorrow

**Comment by timothymtorres** [comment] 2021-08-19 15:57
Duplicate of #47994

**Comment by timothymtorres** [comment] 2021-08-19 16:03
I marked the wrong issue as a duplicate.  This one contains more info and has other important details that should probably get fixed including the blast doors.

**Comment by AlinaStarkova** [comment] 2021-08-19 16:45
> 
> 
> I marked the wrong issue as a duplicate. This one contains more info and has other important details that should probably get fixed including the blast doors.

if you can, give this issue the oversight label, it isnt a bug as it works as intended, but that intended function causes station borgs to easily fuck over the syndie shuttle, hence an oversight

**Comment by Victor239** [comment] 2022-03-24 11:34
Fixed https://github.com/tgstation/tgstation/pull/64650

**Closed** 2022-05-06 07:34 UTC
Labels: Oversight
