### ISSUE TITLE
Despite double ear damage catpeople seem to get up from those types of stun faster.

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#35380] opened 2018-02-06 09:45 UTC
Title.

**Comment by AlexTheSysop42** [comment] 2018-02-06 13:32
pretty sure flashbangs have stronger effects the closer you are

**Comment by Tlaltecuhtli** [comment] 2018-02-06 13:48
no

**Comment by YPOQ** [comment] 2018-02-06 23:08
Doubled ear damage doesn't mean longer stuns, unfortunately. And as Alex said, the closer you are the longer the stun.

**Comment by OmegaShoots** [comment] 2018-02-07 05:04
Ear damage only means you go deaf easier/for longer

**Comment by DaxDupont** [comment] 2018-02-07 20:22
four flashbangs is already can't hear for a round

**Comment by Ordonis** [comment] 2018-02-08 00:18
This needs to be thoroughly tested by repeatedly flashbanging all catpeople until we can determine the success rate.

**Comment by MoreRobustThanYou** [comment] 2018-02-16 11:55
close this, not a bug

**Comment by PKPenguin321** [comment] 2018-03-20 22:07
I'm practically certain this is a non issue and can be closed

**Comment by AlexTheSysop42** [comment] 2018-03-20 22:09
@ShizCalev

**Closed** 2018-03-21 03:50 UTC
Labels: Consistency Issue, Needs Reproducing
