### ISSUE TITLE
YOU CAN'T INSERT MATERIALS INTO PROTOLATHES

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33379] opened 2017-12-07 23:30 UTC
I'VE RECEIVED 100114819481 AHELPS ABOUT THIS, TOLD EACH OF THEM TO REPORT IT ON GITHUB AND NOONE DID SO I'M MAD AND I'M GONNA DO THIS IN ALL CAPS

Server revision compiled on: 2017-12-07

The following pull requests are currently test merged:
#33098: '[ready]Timer queuing tweaks: binary sorted inserts and rolling buckets.' by MrStonedOne at commit 4bb7cc
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a

Based off origin/master commit: 765d77

Server tools version: /tg/station 13 Server v3.2.1.4

Server tools API version: 3.2.0.1

**Comment by Jordie0608** [comment] 2017-12-07 23:45
Duplicate of #33321

**Closed by Jordie0608** 2017-12-07 23:45 UTC
