### ISSUE TITLE
ship navigation computer doesn't show ship outline

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62635] opened 2021-11-07 01:17 UTC
Reporting client version: 514.1557

## Round ID:
[172626](https://scrubby.melonmesa.com/round/172626)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
get the pirate ship from trade route, go to navigation computer, use it and observe how you can't see the outline of where the ship is going to land

**Comment by Addust** [comment] 2021-11-07 13:31
This happens to all other shuttles too, not just the pirate cutter

**Comment by Googles-Hands** [comment] 2021-11-26 16:17
This really needs a fix, it makes pirates/nukies way less effective

**Comment by SuperNovaa41** [comment] 2021-12-06 20:18
Duplicate of #https://github.com/tgstation/tgstation/issues/62635

**Closed by SuperNovaa41** 2021-12-06 20:18 UTC
Labels: Bug
