### ISSUE TITLE
Facehuggers print messages twice.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26428] opened 2017-04-21 23:14 UTC
The alien leaps at Sal Bousum's face!
The alien leaps at Sal Bousum's face!
The alien falls limp after violating Sal Bousum's face!
The alien falls limp after violating Sal Bousum's face!

This is not a case of me standing on the same tile as the infected, either, you see this at range.

Consequently it also appears to deal 10 brute instead of 5. You only have this happen if you didn't already have a facehugger on your face, otherwise those only print 1 message and deal 5 brute as normal when attempting (and failing) to replace the one on your face.

It may quite literally be running this twice.

**Comment by coiax** [comment] 2017-04-24 22:06
This is a dupe of one of my issues.

**Comment by coiax** [comment] 2017-04-24 22:07
#25650

**Closed** 2017-04-24 22:40 UTC
Labels: Bug
