### ISSUE TITLE
Emergency Lights Have Infinite Power

### ISSUE THREAD

**Issue by Joseph-Case** [tgstation/tgstation#33394] opened 2017-12-08 12:57 UTC
Issue reported from Round ID: 79849 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Server Revision: 2017-12-08
Based off origin/master commit: f8e061

Emergency lights do not depower, isntead of hitting 0%, they stay at 0.000568454%

![image](https://user-images.githubusercontent.com/25063394/33766865-58675108-dc17-11e7-8d8c-4651be422b34.png)

**Comment by ShizCalev** [comment] 2017-12-08 16:02
@Xhuis

**Comment by praisenarsie** [comment] 2017-12-08 16:54
>math

@ninjanomnom could be the one at fault here 🕵️

**Comment by Xhuis** [comment] 2017-12-08 17:24
I had this issue reported to me before, but on a local server, I was unable to reproduce it; lights would tick down to 0 successfully. I don't have an answer for why this is happening.

**Comment by grubstank** [comment] 2017-12-08 18:09
I would be really interested to learn what's causing this - I couldn't think of a reason why this is happening.

**Comment by Xhuis** [comment] 2017-12-08 18:20
I've done some diagnosing, and I *might* have found what *lets* the issue happen, but not what's causing the issue itself. I think that the power cell is somehow losing the charge without emergency lights (like with EMP or some such) then it never checks to see if it has the correct amount of charge, but the emergency lights stay on because it detects that they do. I'm working on a patch right now.

**Comment by Anonmare** [comment] 2017-12-08 18:43
Looks like you managed to create Zeno's Paradox @Xhuis

**Comment by Xhuis** [comment] 2017-12-08 18:46
I actually managed to track the bastard down! It took some time, but I had left out an argument in one of the procs, so this'll be fixed now with the PR I just put up.

**Closed** 2017-12-09 21:08 UTC
Labels: Bug
