### ISSUE TITLE
MMIs in Ripleys can't use equipment or interact

### ISSUE THREAD

**Issue by Tsuchigumo550** [tgstation/tgstation#24702] opened 2017-03-05 05:47 UTC
Hash: 59ed05ed5101a49553fef7be10fb0ab221e91085
Testmerges: #24211

A convoluted string of events happened where I was:
1. Killed and husked by a ling
2. Had brain removed
3. Had brain placed in a humanized monkey
4. Was cloned
5. Was removed from cloning early, apparently ODed on Cryox, missing at least lungs, unable to see or talk
6. Pray for death, admins gib, head is taken, brain is again removed
7. Placed in a Ripley, cannot use equipment or interact with the world around me, cannot clamp or drill, clicking functions did not work, could not examine

Additionally:
I think the issue was ongoing before I was hit with an ion gun, although I cannot remember.

**Comment by PKPenguin321** [comment] 2017-03-05 07:00
Dupe

**Comment by lzimann** [comment] 2017-03-05 12:25
Dupe of #24422. Also @PKPenguin321 if you are going to say dupe at least link the other issue.

**Closed by lzimann** 2017-03-05 12:25 UTC

**Comment by PKPenguin321** [comment] 2017-03-05 17:46
I was on my phone
