### ISSUE TITLE
Venus Human Flytrap can Attack through dense objects

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#29148] opened 2017-07-08 22:23 UTC
See the title. It's pretty obvious why this is problematic.

A related issue is they can attack things off screen they lack vision of:

![img](https://i.gyazo.com/c4bf9cf6d6ae3d6ca17cdaf3bc7b0e33.png)
![img](https://i.gyazo.com/18d7a2d844e902ebb911e630f2776158.png)
![img](https://i.gyazo.com/ec63084a01e3f1bf4e5a2f21c67c8485.png)

**Comment by GunHog** [comment] 2017-07-08 22:32
RemiePlants are hilariously deadly.

**Comment by Fox-McCloud** [comment] 2017-07-08 22:52
separate issue, but yeah, probably too strong; they hit you twice and you can't run; 25 brute per hit is a bit ridiculous.

**Comment by Repukan** [comment] 2017-07-08 23:14
The damage is a feature.

You're not supposed to let it get that big.

**Comment by Armhulen** [comment] 2017-07-09 22:24
nahhhhh don't change it!

**Comment by Armhulen** [comment] 2017-07-14 22:40
not a bug tho

**Comment by factoryman942** [comment] 2017-07-26 04:19
there's actually a 1.5 year old issue for this
https://github.com/tgstation/tgstation/issues/13757

**Comment by ChangelingRain** [comment] 2017-07-30 02:30
Duplicate of #13757

**Closed by ChangelingRain** 2017-07-30 02:30 UTC
Labels: Bug
