### ISSUE TITLE
Some overlays arnt deleting properly

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#23316] opened 2017-01-24 22:53 UTC
![Imgur](http://i.imgur.com/8zcFO1G.png)

the health symbols and the point were around for at least 10 min

**Comment by XDTM** [comment] 2017-01-24 23:40
maybe related to the pooling pr? all these overlays used PoolOrNew

**Comment by ChangelingRain** [comment] 2017-01-24 23:50
The timer system might be getting overloaded for some reason, which would prevent these from disappearing.

**Comment by MrStonedOne** [comment] 2017-01-24 23:52
Same issue as [23070]

SStimer is getting overloaded because a bug is causing timers to not qdel. (and i'm almost pretty sure its a byond bug because i can't see how this could be happening)

**Comment by xxalpha** [comment] 2017-01-25 11:31
Why pooling still beeing used, I thought it didn't really help.

**Comment by lzimann** [comment] 2017-01-25 15:45
Dupe of #23070

**Closed by lzimann** 2017-01-25 15:45 UTC
