### ISSUE TITLE
Burning plasma hotspots invisible under certain conditions

### ISSUE THREAD

**Issue by joonoro** [tgstation/tgstation#12530] opened 2015-10-20 10:35 UTC
Burning plasma appears to have an invisible hotspot under certain conditions.

If you burn plasma in the turbine burn chamber and vent it to space, then refill the chamber with the same gas and press the igniter again, the plasma will burn without a hotspot. The gas is burning fine but it just doesn't look like it.

Steps to reproduce:
1. Spawn as atmos tech
2. Pump any burnmix into the turbine burning chamber (e.g. 33% Oxygen, 66% Plasma)
3. Press the igniter button, gas burns as expected
4. Turn off the igniter and pumps, vent all the gas into space
5. Once empty, close the vent and pump more of the same burnmix into the room
6. Press the igniter
7. Notice that the gas does not appear ignite a second time
8. Check the turbine computer and notice that it is actually burning fine
9. Open the exterior airlock in the turbine, notice that the burning spreads out of the "inert" plasma

All the plasma gas in this screenshot is burning, but the bottom half will not appear to be burning:

![Atmos broke](https://i.imgur.com/N2YXnHI.png)

**Comment by PKPenguin321** [comment] 2015-10-20 23:05
iirc igniters are on a toggle, plus if you try to burn plasma with no oxygen it wont ignite
there's a lot of room for error here so before we can call this a bug we'd need somebody to reproduce this

**Comment by joonoro** [comment] 2015-10-21 08:11
Okay after some research I've found out it's not the igniter. The gas ignites fine, it just doesn't have the burning sprite for some reason.

**Comment by MrStonedOne** [comment] 2015-10-22 06:20
Plasma doesn't have "a burning sprite" that is called a hotspot, and its an entirely different and seperate thing. Plasma is an overlay on the turf while hotspot is an obj on the turf

**Comment by duncathan** [comment] 2017-10-14 07:12
Cannot reproduce with the steps provided. This may have been fixed by a number of things. Closing unless it can be reproduced again.

**Closed by duncathan** 2017-10-14 07:12 UTC
Labels: Atmospherics, Bug
