### ISSUE TITLE
round end does not display who was cult

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#27023] opened 2017-05-07 09:52 UTC

**Comment by YakumoChen** [comment] 2017-05-07 09:52
@Robustin

**Comment by Cyberboss** [comment] 2017-05-07 23:41
Dupe of #27040

**Comment by YakumoChen** [comment] 2017-05-08 06:59
mine was first tho

**Comment by Cyberboss** [comment] 2017-05-10 02:48
The other was fixed though

**Closed** 2017-05-10 02:51 UTC
Labels: Bug
