### ISSUE TITLE
Open Space is not treated as Space.

### ISSUE THREAD

**Issue by Timberpoes** [tgstation/tgstation#56563] opened 2021-02-01 03:45 UTC
## Reproduction:

Tramstation revealed that Open Space turfs are not treated as Space. A group of Engiborgs was able to walk across them as if they were any other corporeal turf (without ion thrusters) like they were ordinary plating turfs, as well as Z-move up and down through the IC tab's movement verbs.

[Edit]
I could walk across with magboots.

It also overly excites atmos.

**Comment by Timberpoes** [comment] 2021-02-01 04:19
Addendum - Also works with magboots.

**Comment by LemonInTheDark** [comment] 2021-02-01 05:42
The atmos thing could only really be solved by making a snowflake repath of normal space to open space, or perhaps giving openspace an immutable gasmixture. I think just making it planetary for the map will do, since that'll prevent some of the hell spreading

**Comment by timothymtorres** [comment] 2021-11-24 17:23
I just finished testing this.  While on the upper z level of tram in open space, magboots on a human mob and cyborgs, with and without, ion thrusters fell through the z-level.  

The caveat is that this only happens while on the station.  Any tiles OUTSIDE the station ignore falling to bottom z-level.  This is because there is no gravity (which has been a feature since SS13 began)

@Timberpoes @LemonInTheDark I'm marking this as not a bug and this will auto-close in 7 days.

**Comment by LemonInTheDark** [comment] 2021-11-24 23:50
We are talking about outside the station. The atmos problem is also still relevant

**Comment by timothymtorres** [comment] 2021-11-25 00:00
I tested this both on and off the station.  Off the station has no gravity and the player shouldn’t "fall” to the bottom.

I don’t know what it means by overly excites atmos.  What exactly am I looking for when I’m testing?  The gas spreading? I’d assume that’s how gas would behave in space.

**Comment by LemonInTheDark** [comment] 2021-11-25 00:05
The issue isn't not falling down, it's being able to walk across the tiles with magboots engaged. Like literally walk

Atmos exciting is still a problem because open space tiles are planetary, rather then actually just being space. S a bit of a headache to deal with tho, and may not be worth it.
It's less of a big deal now that they're not just normal open space tiles, used to be and god I died

**Closed** 2021-12-07 07:13 UTC
Labels: Not a bug, Bug
