### ISSUE TITLE
CONVEYORS BROKEN

### ISSUE THREAD

**Issue by CJulien** [tgstation/tgstation#24808] opened 2017-03-08 00:08 UTC
Problem Description: Conveyors in cargo(and whole station) don't work

What did you expect to happen: For the conveyors to move when I flipped a switch.

What happened instead: THEY DIDNT DO SHITv

Why is this bad/What are the consequences: Cargo's job is like a million times harder.

Steps to reproduce the problem: Happens everytime

Server: SYBIL (30tick)

Revision: Server revision compiled on: 2017-03-07
The following pull requests are currently test merged:
#24253: '[READY]Area based gravity and directional gravity! - MOB MOVEMENT FIXED!' by kevinz000 
#24764: 'Cuts out a chunk of map loader time for maps with a lot of space' by Cyberboss 

Based off master commit:
3177ddd52a244025099e941a05ac53c28d3d7a62 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Multitool doesnt do anything to either the belt or the switch

Thanks for helping us out!

**Comment by PKPenguin321** [comment] 2017-03-08 00:29
Dupe of https://github.com/tgstation/tgstation/issues/24772

**Comment by kevinz000** [comment] 2017-03-08 07:58
my gravity bullshit is not related ty.

**Comment by PKPenguin321** [comment] 2017-03-08 08:04
Report issue button auto includes test merged PRs calm down Kevin

**Closed** 2017-03-08 14:47 UTC
