### ISSUE TITLE
using the flightsuit zoom breaks the damage vignettes.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#23650] opened 2017-02-03 03:38 UTC
![](https://file.house/DnUF.png)

**Comment by francinum** [comment] 2017-02-03 03:38
@kevinz000

**Comment by PKPenguin321** [comment] 2017-02-03 03:38
probably a dupe

**Comment by Haevacht** [comment] 2017-02-03 07:06
This happens with all viewrange fuckery, gotta be a dupe of it somewhere.

**Comment by AnturK** [comment] 2017-02-03 07:52
Dupe of #20618

**Closed by AnturK** 2017-02-03 07:52 UTC
Labels: Bug
