### ISSUE TITLE
Issue with a Sprite on the Janicart.

### ISSUE THREAD

**Issue by Coreth74112** [tgstation/tgstation#27931] opened 2017-06-01 05:26 UTC
Sprite showed up as somewhat off to the side, while on the janicart. Only showed up while the sprite was facing down, or to the right. Not sure what caused it, but getting off of it and getting back on didn't fix it.
![7aefa2bbd58c3d42ec89d59ef5b75fcd](https://cloud.githubusercontent.com/assets/29114068/26665668/4f3e48a0-4669-11e7-87f5-28eb389ffb78.png)

**Comment by QualityVan** [comment] 2017-06-01 05:30
Dupe of #27828

**Closed** 2017-06-01 06:27 UTC
