### ISSUE TITLE
the new pop ups are giving me brain tumours and ear bleeding

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#14463] opened 2016-01-07 02:06 UTC
They jump to the front obscuring important shit like other windows or most irritatingly adminpms, they are less responsive than the old one and they make a godawful earsplitting fucking noise at max volume every three seconds near the end of rounds and that shit needs to either be removed or given a clear preference to turn off.

I get they were implemented to solve other problems but they have their own and stuff like the responsiveness and obscuring all other windows with their new bulky size is worse than the focus stealing from before and far more intrusive.

**Comment by WJohn** [comment] 2016-01-07 13:08
They've always been annoying like this. I suppose I never quite mentioned how annoying the noise was in their issue report, but now's a good time as any.

**Comment by Stickymayhem** [comment] 2016-01-07 14:00
God yes a UI option would be fucking fantastic

**Comment by Stickymayhem** [comment] 2016-01-07 14:00
I mean action button can't seem to edit on mobile

**Comment by KazeEspada** [comment] 2016-01-07 15:34
Can I have the option for always yes?

**Comment by Stickymayhem** [comment] 2016-02-01 08:55
Can this please have something fucking fixed

It steals focus, makes a godawful sound you can't turn off and is fucking terrible.

**Comment by Stickymayhem** [comment] 2016-02-01 08:59
Please fucking please I'd literally rather never see one of those pop-ups again and gladly just not get any antag. Even never see again options dont work on the pai so you just get spammed when some dick hits the find pai button over and over in unlogged griefery

**Comment by Stickymayhem** [comment] 2016-02-04 15:32
Please I'll give you money an antag tokens

**Comment by Cheridan** [comment] 2016-05-24 23:44
basically a dupe of #14689

**Closed by Cheridan** 2016-05-24 23:44 UTC
Labels: Not a bug, Sound, UI
