### ISSUE TITLE
multiz rendering past a single level below is outstandingly bad

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#68372] opened 2022-07-12 20:27 UTC
## Reproduction:
Let's say, theoretically, you make a multiz map that allows people to see floor one from floor three.
Let's say you then load this map and see what it looks like from above, only to be met this this:

![fix this shit](https://user-images.githubusercontent.com/82386923/178587843-c50638bf-46f7-45a2-8716-f94b59361d76.png)

You may be wondering what's wrong here, let me add some lines and numbers and maybe you'll see.
In this case, the numbers indicate the floors, 1 for the bottom, 3 for the top.
Matching colors between number and outlines represents the border for that level, with the number being inside the area it represents.
Having said that, take a look at the same image now with those lines added:

![image](https://user-images.githubusercontent.com/82386923/178587753-12d39344-01f3-4a75-bbfc-bfb139d567d9.png)

Due to how multiz rendering past one level down works (it doesn't), the bottom level almost appears as if it's the second, and the second appears as if its the first due to the lack of additional shadowing and lack of any lighting at all.

In most cases this is never noticed as a problem because we only have one multiz map with three levels, icebox, but there are a few points on icebox (like the chaplain's plasma lake pit) where you can notice the effect.

**Comment by Valtosin** [comment] 2022-07-12 22:40
you guys should try bitmask openspaces 
![image](https://user-images.githubusercontent.com/10297716/178609587-0bee9239-6d9e-46fb-9a32-05febdcc2fd0.png)
it can solve two main problems:
1. all turf edges are now visible, lmao
2. you don't need to use three monstrous filters for whole plane, that eats your framerate a bit (or a lot in some cases)
https://github.com/tgstation/tgstation/blob/ec23a0117084e9f69f93e965420c7f192331164a/code/_onclick/hud/rendering/plane_master.dm#L48-L50

**Comment by timothymtorres** [comment] 2022-07-13 10:20
This is technically a dupe of #63202 but I want to see what @LemonInTheDark thinks of @Valtosin solution before closing this.

**Comment by LemonInTheDark** [comment] 2022-07-13 10:58
That's actually pretty interesting. it wouldn't solve everything in this issue, but it would help with client lag. I might steal that I think.
Need a good way to test client performance

**Comment by timothymtorres** [comment] 2022-07-13 22:29
Duplicate of #63202

**Closed by timothymtorres** 2022-07-13 22:29 UTC
Labels: Bug

**Comment by timothymtorres** [comment] 2022-07-14 02:50
Would you prefer me to reverse this then?  I can close the other issue since it lacks information and keep this one open?
