### ISSUE TITLE
No HUD for construct's spells

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#66641] opened 2022-05-01 17:55 UTC
## Reproduction:

Wizard's constructs didn't have HUD buttons for their spells.

**Comment by castawaynont** [comment] 2022-05-01 18:26
This is a result of the test merge of new action buttons. Alt click the action button drop down to restore the spells.

**Comment by private-tristan** [comment] 2022-05-01 21:06
this also applies to the nar'sie harvesters that people are converted into by nar'sie, dunno about cult constructs because I haven't been one recently.

**Comment by moocowswag** [comment] 2022-05-01 21:45
it applies to cult construct too but I ran into that like weeks ago (why is this still a test merge)

**Comment by IllotAFV** [comment] 2022-05-02 14:21
Duplicate of https://github.com/tgstation/tgstation/issues/66120?

**Comment by magatsuchi** [comment] 2022-05-09 18:02
duplicate of #66120

**Closed by magatsuchi** 2022-05-09 18:02 UTC
