### ISSUE TITLE
Engraved floors can be moved by crates

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#52557] opened 2020-07-28 14:18 UTC
![Screenshot_20200728-081301](https://user-images.githubusercontent.com/51932756/88677334-5f4b2780-d0aa-11ea-9711-864f18b3a0a0.jpg)

## Reproduction:

Put crate atop funny floor, open and close crate.

Believe this works with actual cult floors too as I've seen that in the past, but I don't recall too much, but I'm a degenerate phoneposter that can't test locally to confirm anything.

**Comment by TemporalOroboros** [comment] 2020-07-28 14:33
Dupe of #50978

**Closed** 2020-07-30 01:55 UTC

**Comment by nightred** [comment] 2020-07-30 01:57
Closed as duplicate is linked.
