### ISSUE TITLE
Sentient Statues can stuck in jaunt

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#73059] opened 2023-01-29 22:01 UTC
## Reproduction:
Flesh-to-Stone animated statues have 10~ minutes before they will turn back to human - if this happens while in jaunt form, you can't go back from it.

**Comment by TheVekter** [comment] 2023-06-22 14:49
73062 is a duplicate of this but with better information so we're keeping that one

**Closed by TheVekter** 2023-06-22 14:49 UTC
