### ISSUE TITLE
The screen will sometimes freeze for no reason.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34538] opened 2018-01-17 15:34 UTC
round id 82082

See title. Client will occasionally visually freeze, sprites are still interactive (if you're holding a item you can put it in your backpack, you can click things near you, etc) but don't visually update. The chatbox and such is unaffected. The only fix is to restart the client, which is a mandatory 30 second wait period if you aren't a byond donator.

Needless to say, effectively being randomly stunned for 30 seconds is a GOD DAMN BIG DEAL. Client is 511.

**Comment by Jordie0608** [comment] 2018-01-17 15:44
This is an way old BYOND issue duplicate of #2601

**Closed by Jordie0608** 2018-01-17 15:44 UTC

**Comment by Buggy123** [comment] 2018-01-17 15:58
But in my experience this only happens on 512, or at least it happens _far_ more frequently on 512.
