### ISSUE TITLE
Dead pirates are totally white and skin colorless.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39288] opened 2018-07-22 10:40 UTC
What it says on the tin. Dead syndicates and russians do not suffer from this, and pick a skin color. Pirates are always colorless and pure white.

**Comment by Tlaltecuhtli** [comment] 2018-07-22 11:01
they are SKELETONS

**Comment by ShizCalev** [comment] 2018-07-22 15:00
Duplicate of #34856

**Closed by ShizCalev** 2018-07-22 15:00 UTC

**Comment by WJohn** [comment] 2018-07-24 14:46
whoops duplicate of my own issue lol
