### ISSUE TITLE
Item cloning

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51429] opened 2020-06-02 14:58 UTC
Terry RID: 138583
With my backpack closed, I picked up an item from miner's locker and quickly used E hotkey to equip it. The item was cloned. It appeared in my inventory and was still in locker.

**Comment by Cyberboss** [comment] 2020-06-02 14:59
What was the item?

It's possible this isn't a real dupe but just reference mishandling

**Comment by Cyberboss** [comment] 2020-06-02 15:06
This is real and works with any item

**Comment by Cyberboss** [comment] 2020-06-02 15:08
@tgstation/commit-access, I'm working and haven't been around since before storage components existed. Also I have no idea where the fuck to start looking.

**Comment by Ikoden** [comment] 2020-06-02 15:10
Maybe start looking at the hotkey E (quick equip)? Just a thought

**Comment by nemvar** [comment] 2020-06-02 15:29
I remember similar reports of desyncs when two people were accessing the same storage at the same time. I don't think that was ever fixed but the item did not actually get duplicated.
Can't seem to find the issue though.

**Comment by kriskog** [comment] 2020-06-02 15:30
Probably #44762 @nemvar

**Comment by Ikoden** [comment] 2020-06-02 16:33
Okay, so when that bug could be reproduced, the shuttle subsystem broke as the shuttle didn't arrive. The two things may be connected.

**Comment by ATH1909** [comment] 2020-06-02 23:53
can you use this to dupe wizard spellbooks?

**Comment by PKPenguin321** [comment] 2020-06-03 00:05
no because it's not a dupe, it's a desync

**Comment by ATH1909** [comment] 2020-06-03 00:08
so what CAN it do?

if you do this with krav maga gloves, can both people know krav maga at the same time?

what about HUD eyewear?

**Comment by ATH1909** [comment] 2020-06-03 00:10
if a storage container gets desynced, and someone puts an item into said storage container, can someone else with a desynced copy of that storage container pull out that item?

**Comment by ATH1909** [comment] 2020-06-03 00:10
> This is real and works with any item. I checked the refs, they are all different.

also, we have this quote

**Comment by PKPenguin321** [comment] 2020-06-03 00:23
oh, wack

**Comment by optimumtact** [comment] 2020-06-03 02:23
there's absolutely no way it can be a clone, there's no new's in storage at all

**Comment by Ikoden** [comment] 2020-06-03 11:13
There's absolutely no way? How about Cyberboss seeing me do it and seeing the clones?

**Comment by ExcessiveUseOfCobblestone** [comment] 2020-06-03 12:54
Clone as in it made a complete duplicate of the old item.

It is likely to be the same item in 2 places at once. which isn't a true clone.

**Comment by Ikoden** [comment] 2020-06-03 14:00
Shame we didn't test it during that round  to be sure.

**Comment by kopoba** [comment] 2020-06-03 15:31
probably same issue https://github.com/tgstation/tgstation/issues/46737

**Comment by Cyberboss** [comment] 2020-06-04 09:24
The refs at the objs I looked at were different, I can say that much

**Comment by Jalleo** [comment] 2020-06-04 17:25
I have been unable to reproduce it locally. I know that the three landing designators are the ones that mining starts with. One in each locker. If there were MORE than three its likely legitimate.

**Comment by msgerbs** [comment] 2020-10-12 05:14
Has anyone seen this since #52115 was merged?

**Comment by SpaceManiac** [comment] 2020-10-15 23:35
Closing on the fingers-crossed that #52115 fixed it, reply here if you have evidence otherwise

**Closed by SpaceManiac** 2020-10-15 23:35 UTC
Labels: In Game Exploit, Priority: High
