### ISSUE TITLE
couldnt load apiary on mulebot

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55361] opened 2020-12-05 18:16 UTC
i could load myself but not the apiary (unwrenched)

**Comment by Ewwmewgewd** [comment] 2020-12-19 17:19
You can load apiary onto hacked mulebot.
![image](https://user-images.githubusercontent.com/60656530/102695299-a935d500-4226-11eb-8a2c-9c58928c94a3.png)

**Comment by timothymtorres** [comment] 2022-08-20 03:37
Marking this as `Not a bug` and it will autoclose in 7 days.

**Comment by Mooshimi** [comment] 2022-08-27 18:01
cleanup flag is broken again it seems

**Closed by Mooshimi** 2022-08-27 18:01 UTC
Labels: Not a bug, Cleanup Flagged
