### ISSUE TITLE
When you press cancel in the succumb menu you die.

### ISSUE THREAD

**Issue by Baby1991** [tgstation/tgstation#63961] opened 2022-01-09 16:41 UTC
## Round ID:
176308

## Reproduction:
Be in critical condition, press succumb, then cancel. You will die.

**Comment by SuperNovaa41** [comment] 2022-01-09 19:51
Duplicate of https://github.com/tgstation/tgstation/issues/63802

**Closed by SuperNovaa41** 2022-01-09 19:51 UTC
