### ISSUE TITLE
Kilo Public Mining Shuttle is a one way trip

### ISSUE THREAD

**Issue by Capsandi** [tgstation/tgstation#55655] opened 2020-12-21 00:13 UTC
Reporting client version: 513.1524

## Round ID:
[152586](https://scrubby.melonmesa.com/round/152586)

## Testmerges:
- [The Great Radio Rework: NTNET Part 1 of many.](https://www.github.com/tgstation/tgstation/pull/54462)

Expected behavior is that the public mining shuttle moves both ways like the rest of them.

## Reproduction:
Space walk to the abandoned freight station situated above kilo station. 
Use the public mining shuttle which is attached to the outpost
Try to return to the cool abandoned freight station from the mining outpost
Find that the public mining shuttle is 'Locked', requiring you to bother a miner to get off of the planet

**Comment by dragomagol** [comment] 2020-12-23 00:30
Will be fixed by #55657

**Comment by AlinaStarkova** [comment] 2020-12-23 22:48
yes, it will be fixed by removing public mining, i spoke to the mapper and he actually didnt intend for public mining to exist yet, i believe he is working on properly adding it, the issue is that the dock public mining exists at currently is actually a white ship dock :)

**Closed** 2020-12-29 02:21 UTC
Labels: Mapping, Oversight
