### ISSUE TITLE
Microwave will occasionally break

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#52215] opened 2020-07-13 18:41 UTC
## Round ID:
[141859](https://scrubby.melonmesa.com/round/141859)

## Testmerges:
None

## Reproduction:
In the round linked, the second time I used the microwave in the courtroom it kept microwaving forever. I don't know what triggers it exactly or if it's even halfway consistent.

**Comment by ShizCalev** [comment] 2020-07-13 19:00
duplicate of #51866

**Closed by ShizCalev** 2020-07-13 19:00 UTC
