### ISSUE TITLE
Can't pull thermomachines units

### ISSUE THREAD

**Issue by JohnKiwols** [tgstation/tgstation#74479] opened 2023-04-03 09:38 UTC
## Reproduction:
TG Basil server; Thermomachines  / temperature control units:  unscrew the panel on one, then unbolt it from the floor.  Attempting to pull it (ctrl+left click) would normally allow it to be pulled, but it instead says the panel needs to be shut first.  Attempting to close the panel or perform other actions out of order didn't work (so, uh, behaved as expected).  Attempting to pull other objects worked as expected.  Pushing the units worked normally.  I was also having problems going into/out of a trance, so that may have affected it?
"You suddenly feel extremely dizzy...   /   You feel your thoughts slow down...
. . . 
You snap out of your trance!"

**Comment by Ryusenshu** [comment] 2023-04-03 10:47
Duplicate of [#74431](https://github.com/tgstation/tgstation/issues/74431)

**Closed** 2023-04-03 11:26 UTC
