### ISSUE TITLE
Positronic brains duplicate people occupying them/bugged sprite

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#27061] opened 2017-05-08 02:33 UTC
Positronic brains can have two people take over them at the same time, when placed in a cyborg body, one ckey will have control with their designated name and the other will be in the body with the name of the positronic brain and only be able to talk

When positronic brains are occupied, the sprite no longer displays correctly, instead, the light is yellow and stays in one place rather than being green and flashing

**Comment by YakumoChen** [comment] 2017-05-08 06:51
item dupe bug?

**Comment by AnturK** [comment] 2017-05-08 12:26
Unrelated.

**Comment by timothymtorres** [comment] 2021-12-17 11:09
Duplicate of #62716

**Closed by timothymtorres** 2021-12-17 11:09 UTC
Labels: Bug, Needs Reproducing, Cleanup Flagged
