### ISSUE TITLE
Custom vending machines throwing up NTOS errors once something is placed in them.

### ISSUE THREAD

**Issue by coolspace44** [tgstation/tgstation#59447] opened 2021-06-02 03:59 UTC
Reporting client version: 513.1542

## Round ID:
[163341](https://scrubby.melonmesa.com/round/163341)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:
A custom vending machine throws up a bluescreen error (NTOS) once something has been placed inside of it. I linked my account to the vending machine once it was built, I then labelled a full pet carrier for 500 credits then loaded it into the machine at which point I couldn't access it.

The error code it gave me is:

Script error.
   at https://tgstation13.download/byond/assets/d5/asset.d58eb06f0199593446dce71b7f91cf8f.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"NAME","interface":"Vending","window":{"key":"[0x2037dfd]-main","size":null,"fancy":1,"locked":1}}

**Comment by dragomagol** [comment] 2021-06-02 05:02
Duplicate of #59445

**Closed by dragomagol** 2021-06-02 05:02 UTC
Labels: UI
