### ISSUE TITLE
Screwdrivering a computer twice deletes it

### ISSUE THREAD

**Issue by joonoro** [tgstation/tgstation#32975] opened 2017-11-21 19:19 UTC
Using a screwdriver twice on a computer (to disconnect and reconnect the monitor) deletes the computer.

See pic: https://i.imgur.com/612s6WA.png

```
Server revision compiled on: 2017-11-20
The following pull requests are currently test merged:
#32835: 'Revert "Server tools API v3.2"' by MrStonedOne at commit d9f88a
Based off origin/master commit: fc3558
Server tools version: /tg/station 13 Server Service v3.1.6.4
Server tools API version: 3.1.0.2
```

**Comment by Cyberboss** [comment] 2017-11-21 19:37
Duplicate of #32936

**Closed by Cyberboss** 2017-11-21 19:37 UTC
