### ISSUE TITLE
Bodybags negate all projectile damage done to the person enclosed / Health of the body bag is too high

### ISSUE THREAD

**Issue by sydemix** [tgstation/tgstation#88000] opened 2024-11-18 05:00 UTC
### Issue Summary:

Apparently this has been around for a while and no one has reported it. It doesn't seem intentional, and there's no reason bodybags would be able to block any energy/ballistic/whatever projectile from hitting the person within. I've watched people with ranged weapons lose to someone with a bodybag multiple times, as they are forced to approach and engage in melee distance.

EDIT: I have learnt that the body bags do have health, however it does seem disproportionately high for how easy they are to use. It should be reduced either way, since isn't it literally just a thin layer of cloth?

### Reproduction Steps:

1. Enclose yourself in a body bag
2. Have someone shoot any projectile weapon at you
3. Take no damage and be completely fine

**Comment by necromanceranne** [comment] 2024-11-18 06:02
Testing it, bodybags also don't carry over their integrity across being picked up and put back down. That might be an oversight worth resolving.

However, they're still effectively cupboards more or less, so this isn't really a bug at all and it's technically working all as intended. I don't think this need remain open.

**Comment by Sadboysuss** [comment] 2024-11-18 09:02
Maybe they shouldn't have so much health

**Comment by MrMelbert** [comment] 2024-11-18 16:47
Feel free to make a PR lowering the health, or even allow bullets to pass through the bag and hit anyone inside under certain conditions

**Closed by MrMelbert** 2024-11-18 16:47 UTC
Labels: Not a bug, Cleanup Flagged
