### ISSUE TITLE
safe snow is not, in fact, safe

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#44042] opened 2019-05-19 04:24 UTC
how to reproduce:
step 1: spawn safe snow
step 2: tile floor with safe snow
step 3: monitor air temperature

**Comment by Barhandar** [comment] 2019-05-19 09:42
Mmmm ex nihilo atmosia.

**Comment by Daxxed** [comment] 2019-05-19 22:49
This was changed recently I think.
Noticed I get the cold warning when inside the snowman ruin on lavaland too, that didn't happen before.

**Comment by timothymtorres** [comment] 2022-03-29 00:50
Duplicate of #46696

**Closed by timothymtorres** 2022-03-29 00:50 UTC
Labels: Bug
