### ISSUE TITLE
Strange Object (Duplicator) and Electric Grilles

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#25027] opened 2017-03-12 17:14 UTC
I used the strange object that throws out a bunch of duplicates near a window with electric grilles under it. I assume the new objects being thrown hit the grille underneath rather than the glass, and it threw out a bunch of shocks.

(Actually it looks like this can be any thrown object)

**Comment by lzimann** [comment] 2017-03-12 17:32
Dupe of #25013

**Closed by lzimann** 2017-03-12 17:32 UTC
Labels: In Game Exploit
