### ISSUE TITLE
Vital organs placed within patients disappear into the void

### ISSUE THREAD

**Issue by Tuckatk** [tgstation/tgstation#85323] opened 2024-07-27 22:25 UTC
## Issue Summary

This round, after my lungs died, a doctor tried to give me a set of new lungs where it just got consumed into nothingness. Same thing happened when they tried to replace my heart too. Other patients in medbay were also experiencing similar issues. No idea if it's the same with other organs, but I assume it is happening with every one in the chest at least. 

## Round ID: 

Manuel Round 232746

## Testmerges:

[#84873: 'Block atmos processing on ReservedTurfs\:tm: ' by ZephyrTFA at commit e3480139fa](https://www.github.com/tgstation/tgstation/pull/84873)
[#84869: 'Spacemove refactor - Newtonian physics' by SmArtKar at commit ecf1d02f51](https://www.github.com/tgstation/tgstation/pull/84869)
[#85264: 'fuck' by LemonInTheDark at commit fe4f4e9139](https://www.github.com/tgstation/tgstation/pull/85264)
[#85137: 'Death of mutant bodyparts AND external organs' by Time-Green at commit fcd5fa0805](https://www.github.com/tgstation/tgstation/pull/85137)

## Reproduction:

Remove a vital organ and try to place it back into the patient. It not will enter the body and will still be missing.

**Comment by Sadboysuss** [comment] 2024-07-28 07:49
Dupe of https://github.com/tgstation/tgstation/issues/85321

**Closed** 2024-07-28 07:51 UTC
Labels: Test Merge Bug
