### ISSUE TITLE
Going up with atrocinator while piggybacked causes weirdness

### ISSUE THREAD

**Issue by Teleported-Bread** [tgstation/tgstation#76740] opened 2023-07-11 01:59 UTC
## Round ID:
[210015](https://scrubby.melonmesa.com/round/210015)

## Testmerges:
Not 100% sure, but almost definitely [#76381: 'SPECIES NUKING 2023: TOTAL EXTERNAL ORGAN DEATH' by ChungusGamer666 at commit 297d0c1022](https://www.github.com/tgstation/tgstation/pull/76381)

## Reproduction:

1. Activate Atrocinator modsuit 
2. Have friend piggyback onto you
3. Go up a z-level
4. Uhh 

https://github.com/tgstation/tgstation/assets/28495609/cf9a85ba-1a4f-4f08-8359-a6a5a25fc763

 This was from my friend who was piggybacking on me's POV, to me the entire map was black until I got hit by the tram

**Comment by Sealed101** [comment] 2023-07-11 07:40
Duplicate of #76379

**Comment by Sealed101** [comment] 2023-07-11 07:40
although thanks for the video, that clarifies some things

**Closed by Sealed101** 2023-07-11 07:40 UTC
