### ISSUE TITLE
Sometimes, parts of runechat will get cut off.

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#52483] opened 2020-07-25 03:08 UTC
Not related to #52479, this can be reproduced on the current master.

Saying AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA results in:
![image](https://user-images.githubusercontent.com/35135081/88447516-06993780-cde9-11ea-94a6-07eb9b167741.png)

This also happened to me when slurring from being drunk on a production server. I said "I remember you telling me about that guy", which resulted in this:

![2020-07-24T07-26-10](https://user-images.githubusercontent.com/35135081/88447550-4e1fc380-cde9-11ea-927b-7781b106bf7b.png)

Notably, when saying what the output was manually, it does not produce the same effect.

![](https://media.discordapp.net/attachments/326831214667235328/736321712257368114/unknown.png)

**Comment by bobbahbrown** [comment] 2020-07-25 03:14
Cannot reproduce on 513.1527, could this be related to the new changes in 513.1528?

![image](https://user-images.githubusercontent.com/10467687/88447638-d1eaa780-ce0b-11ea-8095-c9c2a4abf01d.png)

**Comment by Jared-Fogle** [comment] 2020-07-25 03:15
Yes, I am on 1528.

**Comment by bobbahbrown** [comment] 2020-07-25 03:22
Confirmed, this is an issue with 513.1528

**Comment by bobbahbrown** [comment] 2020-07-25 04:11
BYOND bug with 1528, I've submitted a bug report for this.

http://www.byond.com/forum/post/2593487

**Comment by Mooshimi** [comment] 2021-12-18 05:40
Fixed by BYOND ver 153

**Closed by Mooshimi** 2021-12-18 05:40 UTC
Labels: Bug, BYOND Issue, Tested/Reproduced
