### ISSUE TITLE
Emissives do not change when the wearer lays down

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#64098] opened 2022-01-14 09:03 UTC
## Round ID:
Any/irrelevant; tested on Local.

## Reproduction:
Wear emissive suit; atmos firesuit is the best, as its emissives stand out.

Lay down.

Note that the emissive overlay doesnt change to lay down with you.

![image](https://user-images.githubusercontent.com/76465278/149488396-ada45438-a452-44ad-80f6-bd9a2193ccf7.png)
![image](https://user-images.githubusercontent.com/76465278/149488347-04def46e-9d34-4c63-939b-18278ccd45e3.png)

**Comment by timothymtorres** [comment] 2023-12-05 12:50
Duplicate of #67336

**Closed by timothymtorres** 2023-12-05 12:50 UTC
Labels: Oversight
