### ISSUE TITLE
Emags no longer work on lockers

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#45740] opened 2019-08-05 22:09 UTC
## reproduction:
1) Have an emag
2) Click a locker with it
3) Get "Access denied." instead of emagging the locker

Airlocks etc. work fine, probably has to do with the ID changes
@actioninja

**Comment by nemvar** [comment] 2019-08-05 22:21
Did you use harm intent?

**Comment by nemvar** [comment] 2019-08-05 22:22
Anyways, even if you did, this is a dupe of #41249

**Comment by nemvar** [comment] 2019-08-05 22:26
Yep, emags still work on crates and lockers if you use harm intent.

**Comment by optimumtact** [comment] 2019-08-05 23:26
this is not a bug, and if you make another issue like this I will git ban you.

If you don't like the current functionality change it

**Closed by optimumtact** 2019-08-05 23:26 UTC
Labels: Consistency Issue
