### ISSUE TITLE
tracking someone in a camera dead zone as ai crashes game

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31438] opened 2017-10-08 04:09 UTC
12:12:09: Reply PM from-Gameguru09/(B.Y.O.N.D.): Tracking someone who is in a camera(?|F) dead zone crashes the game

**Comment by WJohn** [comment] 2017-10-08 10:06
This is gonna need some confirmation, AI players should be screaming and hollering over this so I expect we'll find out quickly.

**Comment by ShizCalev** [comment] 2017-10-19 01:56
Not able to reproduce.

**Comment by BeeSting12** [comment] 2017-10-19 15:07
Might be just that guy

**Comment by ShizCalev** [comment] 2017-10-24 03:20
Unable to reproduce, likely just a client issue. Closing since there's been no other reports.

**Closed by ShizCalev** 2017-10-24 03:20 UTC
Labels: Bug, Needs Reproducing/Testing, Priority: High
