### ISSUE TITLE
Nukeops isn't roundending properly.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#30869] opened 2017-09-18 19:44 UTC
I've seen this issue about in game before and basically when nuke triggers SUCESSFULLY, IN THE STATION, it decides to give no animation of station blowing up, just static screen of station being fine and once the static screen disappears, round ends but there is NO INFO, nothing about nuke ops, their members, their equipment and other stuff indicating round end apart from credits I believe?

@AnturK i swear you told me on irc that you were going to investigate this

https://atlantaned.space/newSS13tools/round.php?round=76152 this has been happening for a while now but can't remember how long.

**Comment by praisenarsie** [comment] 2017-09-18 19:49
found the oldest round of this happening - https://atlantaned.space/newSS13tools/round.php?round=71539

**Comment by nicbn** [comment] 2017-09-18 22:01
Probably this is a dupe of like one thousand previous issues

**Closed** 2017-09-26 09:20 UTC
Labels: Bug
