### ISSUE TITLE
Submenus in protolathe, techfab and autolathe do not do anything when clicked

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#80931] opened 2024-01-12 14:19 UTC
Reporting client version: 515.1626

## Issue Summary

Submenus in protolathe/techfab/autolathe when clicked do not move the viewing area / scroll bar to that subcategory

## Round ID:

I'm not actively in a round when reporting this but it's happened every round for a while now both in beta byond version and normal

## Reproduction:

Open a protolathe/techfab/autolathe menu
Open a category such as 'Tools'
Click onto a subcategory such as 'Engineering Tools'
Viewing area does not move / scrollbar doesn't scroll.

**Comment by jlsnow301** [comment] 2024-01-12 20:26
Related: DesignBrowser L366 
```tsx
 onClick={
        depth === 0
          ? /* For top-level categories, set the selected category. */
            () => setSelectedCategory(category.title)
          : /* For deeper categories, scroll the subcategory header into view. */
            () => {
              document.getElementById(category.anchorKey)?.scrollIntoView(true); // < ------ here
            }
      }
 ```

Would be valid to see if it's actually getting the element. if it is, perhaps the issue is with section

**Comment by SyncIt21** [comment] 2024-01-13 03:23
Is it caused by VirtualLists by any chance in #80743 ?

With thus merged subsections are only loaded when we scroll to it, but if we don't scroll then it never get's loaded and so the scroll would fail to find that element?

Just a theory

**Closed** 2024-03-13 19:34 UTC
Labels: Bug
