### ISSUE TITLE
Sci bags unable to directly transfer monkey cubes to reproductive extracts

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#69508] opened 2022-08-27 22:16 UTC
Round ID: [189352](https://scrubby.melonmesa.com/round/189352)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [b24e0291479fc292ef89efe29708340e42f1e71f](https://www.github.com/tgstation/tgstation/commit/b24e0291479fc292ef89efe29708340e42f1e71f)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Sci bags are unable to directly transfer monkey cubes to reproductive extracts.  You get a red message saying that the bio bag does not contain any monkey cubes.  Note, the message refers to a bio bag even when using a sci bag.

**Comment by ZeroKelvn** [comment] 2022-08-27 22:48
Dupe of https://github.com/tgstation/tgstation/issues/68363#issue-1301527545

**Closed** 2022-08-27 23:19 UTC
