### ISSUE TITLE
abductor retrieval is broken

### ISSUE THREAD

**Issue by massa100** [tgstation/tgstation#26667] opened 2017-04-28 01:23 UTC
The abductor role as scientist doesn't work.

I got it as a ghost, I sent my boy in ready to tag and bag. He bagged, I came down to tag, and then went back to the ship. I couldn't retrieve either of them despite me tagging them for retrieval on MARK mode with the science tool. Cobby took over, pressed some buttons, confirmed it's bork.

**Comment by BeeSting12** [comment] 2017-04-28 01:32
dupe

**Comment by WJohn** [comment] 2017-04-28 02:08
Dupe of #26593

**Closed by WJohn** 2017-04-28 02:08 UTC
