### ISSUE TITLE
Bounty cubes don't work at all, no money made selling them.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#63947] opened 2022-01-09 03:40 UTC
## Round ID:
[176277](https://scrubby.melonmesa.com/round/176277)

## Testmerges:

#63558: 'makes hud images only show to mobs on the same z level to save on maptick' by Kylerace at commit 58446d9dc9
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit b9fdbd265a

## Reproduction:

Put cube on shuttle.
It go to centcomm
No money

**Comment by SuperNovaa41** [comment] 2022-01-09 04:02
Duplicate of https://github.com/tgstation/tgstation/issues/63921

**Closed by SuperNovaa41** 2022-01-09 04:02 UTC
