### ISSUE TITLE
Crayon powder breaks metabolism

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#52371] opened 2020-07-20 19:02 UTC
## Round ID:
[142394](https://scrubby.melonmesa.com/round/142394)

## Reproduction:
When it happened to me it was due to the mime crayon and invisible powder

Eat crayon, crayon doesn't fix hunger, try to eat something else, too full on crayon.
Go to the medical kiosk for a chem scan, find out that you are full of crayon, but it's not metabolizing and neither is anything else.

Likely related to #52289, hopefully fixed by #52339

**Comment by ShizCalev** [comment] 2020-07-21 06:21
Duplicate of #52289

**Closed by ShizCalev** 2020-07-21 06:21 UTC
