### ISSUE TITLE
Nightmares can't hit Arcades

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#69388] opened 2022-08-22 21:43 UTC
Reporting client version: 514.1585

## Round ID:
[189033](https://scrubby.melonmesa.com/round/189033)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:
- As a nightmare, attempt to break an Orion Trail (or any other Arcade) with your light eater;
- Get a fancy message;
- Try to hit it again; Nothing happens.
![image](https://user-images.githubusercontent.com/42555530/186018757-420fdc6f-5fe8-4432-b1cd-5433c89c4f75.png)

**Comment by Mooshimi** [comment] 2022-08-22 23:55
Feedback - The confirmation message you go in chat shouldn't show up if it's not effective

Bug - At least the feedback message, should probably also darken the machine's light overlay if it has one that you're talking about it not effecting?

**Comment by Justice12354** [comment] 2022-08-26 01:23
> Feedback - The confirmation message you go in chat shouldn't show up if it's not effective
> 
> Bug - At least the feedback message, should probably also darken the machine's light overlay if it has one that you're talking about it not effecting?

Uh... I totally forgot about this issue, sorry for the delay. I am gonna see if it affects the machine's light overlay as soon as I can (after I figure out who I'm voting for in the headmin elections) and give some feedback

**Comment by Justice12354** [comment] 2022-08-30 19:51
So, here's a funny one... I tried it in a local with the commit [c2b86b5be76ca8d40eda9e7824600faf977328c7](https://www.github.com/tgstation/tgstation/commit/c2b86b5be76ca8d40eda9e7824600faf977328c7) and I no longer get the feedback message (the machine doesn't lose its light overlay either), just nothing happens at all

**Comment by Justice12354** [comment] 2022-08-30 20:01
Okay, so... I tested it now on the live servers (Terry), and the feedback message does show up and the light overlay disappears. The Arcade still has the screen overlay. This feels like the mix of a bug and an oversight. @Mooshimi

**Comment by Mooshimi** [comment] 2022-09-14 16:45
https://github.com/tgstation/tgstation/blob/1ef0ffb63bdbf8102045d521177461e2bc07676e/code/datums/elements/light_eater.dm#L41-L65
as intended by the code, correct about the screen staying on being wonky which would be an oversight

**Comment by Justice12354** [comment] 2022-09-14 23:56
> https://github.com/tgstation/tgstation/blob/1ef0ffb63bdbf8102045d521177461e2bc07676e/code/datums/elements/light_eater.dm#L41-L65
> 
> 
> as intended by the code, correct about the screen staying on being wonky which would be an oversight

Would the nightmare not being able to break the Arcade at all also be considered an oversight?

**Comment by Mooshimi** [comment] 2022-09-15 12:48
> > https://github.com/tgstation/tgstation/blob/1ef0ffb63bdbf8102045d521177461e2bc07676e/code/datums/elements/light_eater.dm#L41-L65
> > 
> > 
> > as intended by the code, correct about the screen staying on being wonky which would be an oversight
> 
> Would the nightmare not being able to break the Arcade at all also be considered an oversight?

If that's true, yes

**Comment by Sealed101** [comment] 2024-10-26 17:31
fixed by https://github.com/tgstation/tgstation/pull/83818 or followup attack chain PRs

**Closed by Sealed101** 2024-10-26 17:31 UTC
Labels: Oversight
