### ISSUE TITLE
Materials can't be removed from the protolathe (the usual way)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#47045] opened 2019-10-12 09:55 UTC
The protolathe has an option to remove its materials by clicking on the materials submenu within the R&D console, and then the materials themselves. The past few rounds I've tried this, it's been completely ineffective, doing nothing but refreshing the page and not giving out (or losing) any such materials (yes, the amounts were above one sheet in value).
Sybil, ongoing.

**Comment by nemvar** [comment] 2019-10-12 12:20
Duplicate of https://github.com/tgstation/tgstation/issues/46170

**Closed by nemvar** 2019-10-12 12:20 UTC
