### ISSUE TITLE
Footprints show every icon for footprints at once in the floor tab

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#69946] opened 2022-09-15 23:34 UTC
Reporting client version: 514.1585

## Round ID:
[190556](https://scrubby.melonmesa.com/round/190556)

## Testmerges:
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:

Step in blood
Step off blood
Alt-click tile with bloody footprints
![image](https://user-images.githubusercontent.com/36141254/190526490-b93e79be-6c11-4769-8493-ab43e65a6268.png)

**Comment by timothymtorres** [comment] 2022-09-16 00:40
Duplicate of #53824

**Closed by timothymtorres** 2022-09-16 00:40 UTC
