### ISSUE TITLE
You can't cast spells with anti-magic items.

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#42633] opened 2019-02-01 17:45 UTC
You can't cast spells with any anti-magic item, which really goofs over chaplains and miners.
Reproduction:
1. Become Chaplain on MetaStation
2. Take Null Rod
3. Read the cloud chasing book, get smoke spell
4. Try casting the spell

**Comment by QualityVan** [comment] 2019-02-01 19:01
In what possible sense is this not working as intended

**Comment by Fikou** [comment] 2019-02-01 19:31
in the sense that it worked before, and makes spells incompatible with anti magic items chaplains and miners get

**Comment by XDTM** [comment] 2019-02-01 19:56
intended

**Comment by ATH1909** [comment] 2019-02-02 02:41
> intended

I was explicitly told by XDTM that this wouldn't happen and that null rods would still let you cast lesser smoke.

I believe that changing the parameters of the addcomponent function that's called by the initialize function of null rods to the following would make null rods not block your own spells, but still protect you from magic:
AddComponent(/datum/component/anti_magic, TRUE, TRUE, null, FALSE)

If I knew how to make PRs, I'd do it myself, but alas, I'm too afraid of breaking everything to try.

Unfortunately, even though it's a single-line fix that'd undo an unnecessary and unwanted nerf to chaplains if merged, I doubt that anybody will bother making a PR about it....

The relevant bits of code, for reference:
https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/game/objects/items/holy_weapons.dm
https://github.com/tgstation/tgstation/blob/9ad022090468c8dea38c88e3c6521e78146c7d9c/code/datums/components/anti_magic.dm

**Closed** 2019-02-04 03:05 UTC
