### ISSUE TITLE
Certain animations cause you to change layers

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86843] opened 2024-09-22 16:10 UTC
### Client Version:

515.1643

### Issue Summary:

I feel like I've seen this when manifest as an actual in game mob at some point but...  and sorry no repro steps...

Me (cat in the middle)
![image](https://github.com/user-attachments/assets/c9b3489b-8a12-41c6-89ad-c02a0786441e)

Me doing a *flip or whatever it is
![image](https://github.com/user-attachments/assets/d189c2d1-19c0-4247-bb4c-4cb8ecb92d99)

Notice how i'm on a lower level now ???  If you do this over a floor tile you just go invisible.  Pops back up when it ends though.

### Round ID:

[238678](https://scrubby.melonmesa.com/round/238678)

### Reproduction Steps:

e

**Comment by Sadboysuss** [comment] 2024-09-22 16:39
was the station currently without gravity? likely a dupe of https://github.com/tgstation/tgstation/issues/84327

**Comment by iprice** [comment] 2024-09-22 16:53
Hmm, not sure, in this case, I feel like i've seen it on top floor north star when grav wasn't out, can close this if you like and i'll post on the other ticket if i get a non grav related reproduction since they probably /are/ the same thing to some degree

**Comment by Sadboysuss** [comment] 2024-09-22 17:14
well ghosts are probably not affected by gravity anyways so yeah, most likely. I'll let another issue jannie close this if that's the case.

**Closed** 2024-09-23 20:42 UTC
