### ISSUE TITLE
Proto-Kinetic Crusher no longer fits on the back

### ISSUE THREAD

**Issue by Leon9621** [tgstation/tgstation#22550] opened 2016-12-29 05:37 UTC
Multiple times I've tried to store the crusher on my back and make do with the webbing you get, but all it does is fall to the ground.

**Comment by Mervill** [comment] 2016-12-29 05:49
dosen't look like it was my recent refactor of `w_class`

**Comment by Mindustry** [comment] 2016-12-29 06:11
Duplicate issue

**Comment by Mervill** [comment] 2016-12-29 07:37
@Mindustry of what issue, please

**Comment by lzimann** [comment] 2016-12-29 15:52
Dupe of #22536

**Closed by lzimann** 2016-12-29 15:52 UTC
