### ISSUE TITLE
Burnt/Exploded Tiles do not get their original paint back after replacing.

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#52502] opened 2020-07-25 13:42 UTC
There might be consistency issues with this because it doesn't always have issues.

**Comment by Dennok** [comment] 2020-07-27 09:21
I see this for all tiles.
Just tiles do not get their original paint back after replacing.

**Comment by legoscape** [comment] 2020-07-27 09:37
This bug has been around for as long I've been playing so. Seven years. Maybe we can finally fix it?

**Comment by Dennok** [comment] 2020-07-27 11:06
Wtf, i code it in #49773

**Comment by Dennok** [comment] 2020-07-27 11:08
We have floor painter to paint paintings on floor.
But yes, this disappointing to lost painting when you just want replace tile to place cable.

**Comment by legoscape** [comment] 2020-07-27 23:33
I am not aware of any such thing as a "floor painter" That paints map spawned tiles back into existance.

**Comment by legoscape** [comment] 2020-07-28 10:17
> We have floor painter to paint paintings on floor.
Maybe we could turn a bug into a feature. RTP (Rapid Tile Painter)
Allows you to turn titles into default or allows you to paint 1 to all 4 quarters of a tile what ever color you want.

**Comment by nightred** [comment] 2020-07-30 16:32
Some tiles are not craft able, and placed tiles are not replaced with the default of the area.
This does not sound like a bug as placing new floor tiles will place the type placed

**Comment by legoscape** [comment] 2020-07-30 18:47
Destroyed tiles with specific presets, Such as the Space Station 13 logo on the floor cannot be replaced or redone. White tiles in the kitchen during a fire turn grey after repair. This is not how it should be.

**Comment by ArcaneMusic** [comment] 2020-11-10 08:46
What you're describing is 2 different things, clue me in on which you're going for:
There's turf decals (EG: The SS13 floor sign in the main hallways), which breaks upon being crowbarred off the floor.
Then there's just recolored turfs, (EG: ya know those ugly kinda pseudo carpets you find by metastation arrivals, and in some offices? Those) which when pried off the floor, will spawn a default metal floor tile, but will in all likelyhood replace itself with the given floor tile skin when replaced.

If the latter is broken, that could probably be fixed in a similar way to the titanium floor turf reskinning that was added a few weeks ago.
If the former is broken, that's not a bug, because that can be fixed with the decal painter item, it looks like an airlock painter in blue.

**Closed** 2021-03-31 20:38 UTC
Labels: Not a bug
