### ISSUE TITLE
Post-nuke leaves screen too big

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23189] opened 2017-01-20 23:00 UTC
![image](https://cloud.githubusercontent.com/assets/609465/22168392/3602e2ae-df64-11e6-8f83-cd027629645e.png)

You can see that the view range is bigger than the HUD.

**Comment by Mervill** [comment] 2017-01-20 23:37
This miiiight be a duplicate of an Issue @WJohn posted a while back

**Comment by PKPenguin321** [comment] 2017-01-21 03:21
Yeah this bug is ancient, I'm almost sure it's been reported before

**Comment by callanrocks** [comment] 2017-01-21 08:03
Its been around literally forever but I don't think anybodies ever bothered to fix this since the round ends a few seconds later anyway.

**Comment by Kromgar** [comment] 2017-01-21 16:44
Coiax is gonna add the station entirely getting blown up by nuke for funsies which is why hes trying to get this fixed

**Comment by Cyberboss** [comment] 2017-01-21 16:49
No, that's me #22586

**Comment by Cyberboss** [comment] 2017-01-21 16:49
WE DON'T LOOK THE SAME DAMMIT!!!

**Comment by Cyberboss** [comment] 2017-01-21 16:52
might have something to do with this line maybe? https://github.com/Cyberboss/tgstation/blob/5f0b403b47561e7a0dd1c940aaf8828abded6dae/code/controllers/subsystem/ticker.dm#L231

Disclaimer: I don't understand screen code

**Comment by coiax** [comment] 2017-01-21 17:05
why are people confusing us? because our avatars are blue?

**Comment by PKPenguin321** [comment] 2017-01-21 19:28
Yes and your names start with c

**Comment by Cyberboss** [comment] 2017-01-21 19:31
>Not even same case

**Comment by Kromgar** [comment] 2017-01-21 22:46
You blues all look the same to me.

**Comment by Cyberboss** [comment] 2017-01-21 22:49
This is @coiax's image: ![](http://www.allgeek.tv/wp-content/uploads/2010/Eve-Huge.jpg)
This is my image: ![quantum_space_617](https://cloud.githubusercontent.com/assets/8171642/22178353/e3ec9ae8-e001-11e6-8181-d66a23bc7672.jpg)

How can you not tell the difference?

**Comment by XDTM** [comment] 2017-01-21 22:51
That's two images of a blue planet coiax

**Comment by coiax** [comment] 2017-01-21 23:04
XDTM, you don't even have a gravatar

**Comment by MrPerson** [comment] 2017-01-22 04:18
@Cyberboss Try changing that screen_loc="1,0" to screen_loc="1,1" and see if the problem goes away.

**Comment by Cyberboss** [comment] 2017-01-22 04:31
@XDTM REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Kromgar** [comment] 2017-01-22 13:58
Calm down Coiax

**Comment by XDTM** [comment] 2017-01-22 17:41
I joined the blue tide

**Comment by Kromgar** [comment] 2017-01-22 21:49
We are one we are many

**Comment by Cyberboss** [comment] 2017-01-23 00:55
...

**Comment by Kromgar** [comment] 2017-01-23 01:25
All shall join the blue tide

**Comment by coiax** [comment] 2017-01-23 04:00
Wow this is a meme now?

**Comment by Cyberboss** [comment] 2017-01-23 16:15
@coiax Just turn it around on them wherever you see them

**Comment by Kromgar** [comment] 2017-01-23 19:04
I will XDTM

**Comment by WJohn** [comment] 2017-05-22 10:44
Yep, this is a dupe of #8171

Also recently to further add to this: Ghost view range is a thing now, and if you have your screen set to stretch-to-fit, you can momentarily gain extra tile vision as your screen is enlarged to roughly 10 tiles.

I'll close the other issue, but this one IS from mid 2015.

**Closed** 2017-09-26 09:20 UTC
Labels: Bug
