### ISSUE TITLE
White Ship glitch

### ISSUE THREAD

**Issue by azraelknightquest** [tgstation/tgstation#30655] opened 2017-09-12 12:45 UTC
The white ship now has two rooms that act as if there is a hull breech when there isn't.

**Comment by pubby** [comment] 2017-09-12 18:31
Which map?

**Comment by BeeSting12** [comment] 2017-09-13 16:44
@azraelknightquest 
Which map? Was the ship in roundstart condition? Had you opened airlocks and released air?

**Comment by AnturK** [comment] 2017-09-18 10:55
Duplicate of #30780

**Closed by AnturK** 2017-09-18 10:55 UTC
Labels: Bug
