### ISSUE TITLE
PDA interface is a blank window

### ISSUE THREAD

**Issue by Angustine** [tgstation/tgstation#31215] opened 2017-10-01 21:22 UTC
ROUND ID:76870
WHEN I OPEN THE PDA SCREEN IT ONLY APPEARS BLANK WHITE, AND IT HAPPENS REGULARLY.
FIX IT!

**Comment by praisenarsie** [comment] 2017-10-01 21:47
@Cyberboss @Supermichael777 @TungstenOxide

**Comment by TungstenOxide** [comment] 2017-10-01 22:02
Shit shit shit. Why couldn't this happen gradually? Okay, uhh. Fuck. Someone undo the patch and I'll rebuild my original **not** fucked up code that I know actually worked.

**Comment by AnonymousNow** [comment] 2017-10-01 22:24
TO, are you responsible for the PDA interface change? Can you make clickable text/elements a little more distinct from non-clickable text/elements, if possible?

**Comment by TungstenOxide** [comment] 2017-10-01 22:30
I am responsible for the PDA changes. It's working fine on my end. I'm experimenting rn. I'm probably going to make a new pull request for the build I have on file RIGHT NOW because that one works. I apologize profusely for any inconveniences this has caused.

**Comment by praisenarsie** [comment] 2017-10-05 14:42
btw it works for me 2, i don't know what's the guy's problem

**Comment by Electronics** [comment] 2018-01-03 00:15
Possible extension of the problem outlined here: http://www.byond.com/forum/?post=2211145
I used to have this bug but tried downgrading to a bunch of different revisions until I found one that worked for me.

**Comment by ShizCalev** [comment] 2019-02-08 08:39
Duplicate of #31745

**Closed by ShizCalev** 2019-02-08 08:39 UTC
Labels: Bug
