### ISSUE TITLE
You can become magicly stuck in holopads

### ISSUE THREAD

**Issue by nigtmoth** [tgstation/tgstation#85092] opened 2024-07-19 04:35 UTC
Reporting client version: 515.1640

## Issue Summary

You can become stuck inside holopads

## Round ID:
[232303](https://scrubby.melonmesa.com/round/232303)

## Reproduction:

1. Attempt hit rat that has been eating wires in maints
2. Run into kitchen while chasing said rat
3. Accidentally hit the icebox kitchen's holopad
4. Magicly get transported inside said holopad with no escape
5. Scream for help

![image](https://github.com/user-attachments/assets/1e64128c-8d1b-467a-84e9-ccee2787eb5b)

**Comment by SmArtKar** [comment] 2024-07-19 04:40
Duplicate of #80183

**Closed by SmArtKar** 2024-07-19 04:40 UTC
