### ISSUE TITLE
Bomb Test Site Monitor doesn't function

### ISSUE THREAD

**Issue by Spacebutterman** [tgstation/tgstation#43410] opened 2019-03-30 03:48 UTC
Issue reported from  Round ID: 105016 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Using the Bomb Test Site monitor doesn't pull up an associated window and will not do anything.

**Comment by SpaceManiac** [comment] 2019-03-30 05:22
Map was Box Station

**Comment by Barhandar** [comment] 2019-03-30 08:19
Duplicate of #43309

**Closed** 2019-03-31 08:49 UTC
Labels: Map Issue
