### ISSUE TITLE
Plasmamen can spawn in deathmatch however they lack proper equipment to not die

### ISSUE THREAD

**Issue by Blockaboo** [tgstation/tgstation#81905] opened 2024-03-09 02:08 UTC
Reporting client version: 515.1630

## Issue Summary
Plasmamen can spawn into deathmatch mode, however they won't have a air tight suit unless said arena gives players an airtight suit, even if they did it's likely they would still suffocate from a lack of plasma tank

## Round ID:
[225230](https://scrubby.melonmesa.com/round/225230)

## Reproduction:
Change your species to plasmaman, join a deathmatch arena, have deathmatch arena start, burst into flames and suffocate because you lack a suit and a tank of plasma

**Comment by ArcaneDefence** [comment] 2024-03-09 02:11
Duplicate of https://github.com/tgstation/tgstation/issues/81858

**Closed by ArcaneDefence** 2024-03-09 02:11 UTC
