### ISSUE TITLE
Right-click on the Genetics computer doesn't work anymore.

### ISSUE THREAD

**Issue by CaioFrancisco** [tgstation/tgstation#80228] opened 2023-12-10 03:02 UTC
Reporting client version: 514.1589

## Issue Summary

Right-click on the Genetics computer doesn't work anymore. It opens a droplist that only has "Copy" and "Select all". It's supposed to cycle in reverse, as the GUI says.

## Round ID:
[220244](https://scrubby.melonmesa.com/round/220244)

## Testmerges:
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:

1. Put a monkey in the DNA Scanner.
2. Open the DNA Console.
3. Go to the Sequencer tab, click on a proper gene, and try to right-click any genome.
4. Discover that clicking on the genome, instead of reversing it, opens this droplist menu.

**Comment by Jacquerel** [comment] 2023-12-10 03:03
Duplicate of #80200 (but thanks for posting your ticket anyway, more rounds and repro steps is useful)

**Closed by Jacquerel** 2023-12-10 03:03 UTC
