### ISSUE TITLE
Attempting to use a cell charger in the manner it is intended to be used breaks the APC.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#54976] opened 2020-11-15 01:56 UTC
Issue reported from  Round ID: [150327](https://scrubby.melonmesa.com/round/150327) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])
(this also occured last round, admin had to do admin stuff to fix it)

Reporting client version: 513.1536

1. find or make a cell charger
2. put a cell in the cell charger
3. wait for APC to run out of power
4. APC will get stuck saying it is at full power, while having no power, meaning it won't charge.
5. ahelp to get admins to fix the APC

**Comment by dragomagol** [comment] 2020-11-15 04:18
I believe this is a duplicate of #54919

**Comment by Dorsisdwarf** [comment] 2020-11-15 11:25
You are correct, this is a duplicate report of #54919

**Closed by Dorsisdwarf** 2020-11-15 11:25 UTC
