### ISSUE TITLE
Screen shake may be broken?

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29341] opened 2017-07-18 16:05 UTC
![](http://i.imgur.com/u6fa22B.png)

Seems to happen when meteors are striking. Notice how it's shifted to the top right?

EDIT: Continues for the duration of the round, or a really long time after, at least.

**Comment by Cyberboss** [comment] 2017-07-18 18:48
Dupe of #29342

**Closed** 2017-07-18 18:48 UTC
Labels: Bug
