### ISSUE TITLE
Turbine Compressor Bug

### ISSUE THREAD

**Issue by killerbrochen** [tgstation/tgstation#36530] opened 2018-03-19 15:03 UTC
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm
Round ID: 85214
Server revision compiled on: 2018-03-18
68b333
Revision: 68b3339d16586ca2e0953a4eeb3a6f8423fdbd94
Server tools version: /tg/station 13 Server v3.2.1.15
Server tools API version: 3.2.0.2
Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 9 of 20 roundtypes
Allow Midround Antagonists: 7 of 20 roundtypes
Game Mode Odds for current round:
traitor 90%
secret_extended 10%
All Game Mode Odds:
traitorchan 24.5%
traitor 18.4%
clockwork_cult 8.2%
nuclear 16.3%
cult 8.2%
secret_extended 2%
revolution 12.2%
wizard 10.2%

When taken apart and rebuilt, the turbine power compressor will always be broken and nonfunctional. Used all new parts and metal.

**Comment by Jalleo** [comment] 2018-03-19 21:57
I believe this is already reported

**Comment by redmoogle** [comment] 2019-02-22 13:37
I had the same issue I think its caused by the rotation facing away from eachother

**Comment by Sealed101** [comment] 2023-03-03 16:55
seems to no longer be the case, probably resolved in #65586

**Closed by Sealed101** 2023-03-03 16:55 UTC
Labels: Bug
