### ISSUE TITLE
Split personality is resulting in the original mind being ghosted at random

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#72570] opened 2023-01-08 21:20 UTC
Reporting client version: 514.1589

## Round ID:
[197868](https://scrubby.melonmesa.com/round/197868)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

As a ghost, take over a split personality as it appears from a brain trauma. Wait for the personality to swap to you, then play as normal. Silently the original host will suddenly be ghosted some time later it seems rather than swapping back.
![2MLrTZqd0j](https://user-images.githubusercontent.com/33107541/211219726-d9cf6398-dcc9-4e28-a5fb-5357b53cb601.png)

**Comment by Profakos** [comment] 2023-01-09 12:42
Duplicate of #68573, looks like it.

**Comment by Sealed101** [comment] 2023-03-15 18:33
correct

**Closed by Sealed101** 2023-03-15 18:33 UTC

**Comment by Profakos** [comment] 2023-03-15 19:01
Thank you for cleaning up all of these 👍
