### ISSUE TITLE
valentines are in the antag list

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42762] opened 2019-02-13 07:07 UTC
>wiz dies
round still goes on because valentines

i need my antag reroll

**Comment by davethwave** [comment] 2019-02-13 16:02
Just thinking imsxz, but I think the problem is that the valentines event causes rounds that should end on death of x antag, not end. So even if they were removed from the valentines list they would still cause the round to not end if the wizard dies, or if all the ops die or something.

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-02-13 17:24
They are allowed to forgo escalation if someone harasses their date, I don't see the issue as calling them out in the panel.

That said, the mulligan system should check for a variable on the antag to signal that it can not count those as delaying round end tbh.

**Comment by imsxz** [comment] 2019-02-13 23:13
the issue is that *everyone* in the round becomes an antag cobby, everyone on the f6 list is antag and such. Also it clogs the hell out of end round report with a massive list that people dont really care about

**Comment by ATH1909** [comment] 2019-02-14 00:28
> the issue is that _everyone_ in the round becomes an antag cobby, everyone on the f6 list is antag and such. Also it clogs the hell out of end round report with a massive list that people dont really care about

... I care about whether or not I succeeded in my Valentine's Day objective...

**Comment by tralezab** [comment] 2019-02-14 02:51
Just list the people who failed!

**Comment by tralezab** [comment] 2019-02-14 03:39
alright here's both of the problems fixed

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-02-14 16:48
This won't fix the check antags issue

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-02-14 16:49
> the issue is that _everyone_ in the round becomes an antag cobby, everyone on the f6 list is antag and such. Also it clogs the hell out of end round report with a massive list that people dont really care about

If we make it hidden admins will have to be cognizant of this exception and not ban people because they're not in the antag checker.

**Comment by imsxz** [comment] 2019-02-14 19:58
i trust the common sense of any admin team on any server to check someones notes if they justify their killing with "im supposed to protect x" especially when valentines day is an announced event that affects every living mob

**Comment by tralezab** [comment] 2019-02-15 05:23
they could just not show in antag panel but have an antag hud

**Closed** 2019-02-21 15:26 UTC
Labels: Not a bug
