### ISSUE TITLE
Lich Phylacetery will not revive while in a container

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#37808] opened 2018-05-12 16:52 UTC
**Issue:** A wizard's lich phylactery will fail to revive if it is in any kind of container (backpack, wall safe, etc). Some people have advised me that this is intended, but neither the phylactery or the spell description give you any indication that you should avoid putting the phylactery in a bag.

**Suggestions:** Add text to the spell and the phylactery itself suggesting not to put it in a container, or simply make any item turned into a phylactery too large to fit in containers.

**Comment by YPOQ** [comment] 2018-05-13 03:38
Can't reproduce this. Do you remember what item you were using as a phylactery?

**Comment by YakumoChen** [comment] 2018-05-13 05:44
I've put mine in a box before and revived just fine

**Comment by Arianya** [comment] 2018-05-13 09:13
@YPOQ Original player report came from using a antag token (from wizard shuttle) in a wall safe, was then reproduced by putting a blue wizard hat in a secure briefcase. Both were locked, so possibly an issue with lockable containers?

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-15 12:05
secure briefcase and wall safe are of the same type

**Comment by interestingusernam3** [comment] 2020-04-03 10:55
Toolboxes work fine

**Comment by timothymtorres** [comment] 2021-12-21 11:25
Relevant code:

https://github.com/timothymtorres/tgstation/blob/1a5f5250e8337d7cb8f60c72afb6bfeae5aefddd/code/modules/spells/spell_types/lichdom.dm#L116-L122

I wonder if the `item_turf` check is causing it.

**Comment by ExcessiveUseOfCobblestone** [comment] 2022-01-01 21:57
Honestly just elevate it to a feature, being able to respawn with full powers is pretty strong

**Comment by MrMelbert** [comment] 2022-05-17 23:10
fixed by above, turns out

**Closed by MrMelbert** 2022-05-17 23:10 UTC
Labels: Bug, Needs Reproducing

**Comment by timothymtorres** [comment] 2022-05-17 23:22
Nicely done! 👍
