### ISSUE TITLE
Quirks that spawn you with an item now always spawn in your hands instead of in your bag like they use to.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#60341] opened 2021-07-20 01:36 UTC
## Round ID:
Irrevelant

## Reproduction:
Before, quirk items would usually start in your bag, now however, they will always spawn in your hands. This wouldn't be an issue, however, if you have 2 quirks that both cause you to spawn with an item, and then choose a job that normally starts with an item in their hand, the item that should be in their hand because of the job does not spawn. 

Example: having both the musician quirk (which spawns you with a beacon), and the family heirloom quirk (which spawns you with another item), and then taking the job of MD (which normally spawns you with a aid kit in your hands), causes the aid kit to not spawn.

**Comment by Mothblocks** [comment] 2021-07-20 04:57
duplicate of #60291

**Closed by Mothblocks** 2021-07-20 04:57 UTC
