### ISSUE TITLE
pAI intergrated flashlights don't follow the pAI

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#68119] opened 2022-06-30 21:43 UTC
Reporting client version: 514.1585

## Round ID:
N/A (Noticed this a few rounds in a row, just posting a report now)

## Testmerges:
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Completely rewrites the orbit screen](https://www.github.com/tgstation/tgstation/pull/68054)

## Reproduction:
The pAI's "Toggle integrated light" feature only lights up the immediate area from when it was toggled, but won't follow the pAI itself. The only way around this is to keep spamming it on and off as you move.

**Comment by nemvar** [comment] 2022-07-01 07:55
Duplicate of https://github.com/tgstation/tgstation/issues/68089

**Closed by nemvar** 2022-07-01 07:55 UTC
