### ISSUE TITLE
Bubblegum can become lodged inside a pAI if a miner is wearing it in their head slot when they are gibbed

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#75804] opened 2023-06-02 01:08 UTC
## Round ID: 

[207374](https://tgstation13.download/parsed-logs/sybil/data/logs/2023/06/01/round-207374/)

## Testmerges:

#75617 Adds a new front end for viewing logs | fixes the manifest log message too

## Reproduction:

- Wear a pAI in your helmet slot
- Get gibbed by Bubblegum

I'm not joking, this is a new one for me.

![image](https://github.com/tgstation/tgstation/assets/7019927/24d30899-48a3-4929-8c55-0e5ef1f3067d)

**Comment by TheVekter** [comment] 2023-06-02 01:15
I'm actually not sure Bubblegum is _inside_ the pAI, but orbiting Bubblegum orbits the pAI (or whomever has it) and the loc is set to, well.

![image](https://github.com/tgstation/tgstation/assets/7019927/53f6ea0b-b361-44bc-ade5-61adc02fcc7e)

Something's fucky.

**Comment by LemonInTheDark** [comment] 2023-06-02 04:14
yeah it was in there

**Comment by newfren** [comment] 2023-06-02 04:18
holy fuck what

**Comment by TheVekter** [comment] 2023-06-02 04:54
oranges thinks it might have something to do with BB's blood attack but he couldn't make heads or tails of it.

**Comment by the-orange-cow** [comment] 2023-06-02 06:48
Does destroying the pAI release bubbles or banish him to the shadow realm?

**Comment by MrMelbert** [comment] 2023-06-02 08:19
could not reproduce in testing, which really makes me wtf

**Comment by MrMelbert** [comment] 2023-06-02 08:20
if I were to guess something really goes wrong when it goes from item (`mob_holder`) -> mob (`silicon/pai`) -> item (`pai_card`)
as the order is `devour()` -> `gib()` -> `qdel(miner)` -> `qdel(pai mob older)` -> release pai as mob -> ???

**Comment by timothymtorres** [comment] 2023-06-02 09:05
This is such a cool mystery bug also I could see this being used to grief stations if you can somehow release bubblegum from the pAI prison.

**Comment by TheVekter** [comment] 2023-06-02 15:13
> This is such a cool mystery bug also I could see this being used to grief stations if you can somehow release bubblegum from the pAI prison.

Good luck figuring out a reliable way to do it.

**Comment by necromanceranne** [comment] 2023-06-03 07:41
> This is such a cool mystery bug also I could see this being used to grief stations if you can somehow release bubblegum from the pAI prison.

pAI becomes the ultimate stand user.

**Comment by IndieanaJones** [comment] 2023-06-03 22:35
My theory: Bubblegum can teleport directly to targets when it comes to devouring them, can't he? What if he tried teleporting to the location of the mob portion of the PAI after aggroing onto it somehow in order to consume it, but since the PAI was in its item form at the time of the teleport, when Bubblegum teleported to the PAI's location, it teleported him inside the item, since that's where his target was located.

**Comment by lizelive** [comment] 2024-07-08 03:37
close as won't fix.

**Comment by TheVekter** [comment] 2024-07-08 04:22
I don't even think I've seen this happen again, but I'm loath to close it and lose Indie's investigation into in case it does happen again.

**Comment by SmArtKar** [comment] 2024-10-12 10:34
Indirectly fixed by #85655, what was happening is that bubblegum teleports to a loc but checks for blood in get_turf. Absolutely cursed.

**Closed by SmArtKar** 2024-10-12 10:34 UTC
Labels: Bug, FUCK, Against God and Nature
