### ISSUE TITLE
Please revert umbras

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18746] opened 2016-06-20 00:19 UTC
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
The most they can do is stun someone for a few seconds at a cost of being visible and dying their whisper doesn't work they can't talk to other umbras they're godawful

**Comment by Zilenan91** [comment] 2016-06-20 00:49
Why did so many of their powers get removed in the first place?

**Comment by Incoming5643** [comment] 2016-06-20 00:56
Under the guise of a rewrite they were essentially gutted and left with a pair of new powers that essentially boiled down to "you can push someone over and read the notes they didn't set" and "You can ride around with a mob but can't actually do anything in this state"

Their objective is to push over 20% of the station's population.

It's preeeeeeeetty underwhelming

**Comment by Firecage** [comment] 2016-06-20 04:38
Incoming, whyd it even get merged then in the first place. It would be like beginning a rewrite of cult, gutting everything, re-adding only a stun rune and observe rune, and then having the maintainers merge that.

**Comment by Incoming5643** [comment] 2016-06-20 05:00
Don't ask me, ask @Xhuis and to a vaguely lesser extent @optimumtact

**Comment by optimumtact** [comment] 2016-06-20 06:01
No

**Comment by Incoming5643** [comment] 2016-06-20 06:01
Oy

**Comment by Xhuis** [comment] 2016-06-20 06:06
You could just, y'know, _propose actual changes that I could make to them instead of pressing for a kneejerk revert?_

**Comment by Incoming5643** [comment] 2016-06-20 06:07
It's hard to say what to add because I'm pretty confused what the theme is supposed to be here.

All roads in my head just point back to grief ghost.

**Comment by Xhuis** [comment] 2016-06-20 06:12
#18755

**Comment by optimumtact** [comment] 2016-06-20 06:27
This is not a bug

**Comment by Xhuis** [comment] 2016-06-20 06:27
It is tbh, re-open :older_man: :

**Comment by optimumtact** [comment] 2016-06-20 06:28
It's not a bug

**Closed by optimumtact** 2016-06-20 06:27 UTC
Labels: Not a bug

**Comment by Zilenan91** [comment] 2016-06-20 06:29
That's why this part of Github is called issues

**Comment by optimumtact** [comment] 2016-06-20 06:31
Luckily as maintainers we get to define what the tracker is for, and we chose to make it for bug reports, not feature requests

**Comment by YakumoChen** [comment] 2016-06-20 07:51
But coders don't read the feedback forum

**Comment by optimumtact** [comment] 2016-06-20 08:45
They are bad wrong and you should send me their details so I can put them on my shitlist and blacklist their changes

**Comment by ChangelingRain** [comment] 2016-06-21 21:03
instructions unclear removed umbras instead
