### ISSUE TITLE
[Downstream Server] Timer subsystem and Add_overlay have incredible CPU usage

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#23818] opened 2017-02-07 15:59 UTC
Howdy, so for the past while, we've been having some serious issues with the timing system and, upon investigating it, have found that both ignite and add_overlay are gumming up the works for the MC as well.

https://gyazo.com/e36cc6b5b3ed21911f29cdb925318607

The timer system also steadily accrues Crew Monitor updates for wet floors and AfterChange updates and repeats the fun of #23070 until we smack the MC to hard restart.

https://gyazo.com/406335657623452e9aab554b659f983b

This is the queue immediately after an MC reset

We're running slightly modified TG live code as of around midnight, Central time 2/5/17. Compiled on 511.1372

I suppose this is more a question of what can be done to mitigate/resolve these. I'll see about nabbing whatever logs are needed as well, if further info is required.

**Comment by Cyberboss** [comment] 2017-02-07 16:05
If you could get us the server runtime logs that'd be great

**Comment by Poojawa** [comment] 2017-02-07 16:09
Will do. Though it's probably 75% filled with simple mob runtimes of the lovely null.loc

**Comment by Poojawa** [comment] 2017-02-07 17:17
Also you've been doing absolutely amazing work chipping away at all the issues. I'm going to be rounding up the majority of your runtime fix PRs and throwing 'em in to see if it helps

**Comment by Cyberboss** [comment] 2017-02-07 17:25
Thanks 😄

**Comment by xxalpha** [comment] 2017-02-08 00:11
i told you about the add overlay 🐙

**Comment by Poojawa** [comment] 2017-02-08 13:23
http://pastebin.com/8gMt8dVb Here we go, runtime logs

Also, have updated our code since then from like, half an hour after the last commit.

**Comment by Cyberboss** [comment] 2017-02-08 15:59
@MrStonedOne

**Comment by Cyberboss** [comment] 2017-02-08 15:59
also probably related to #23536

**Comment by MrStonedOne** [comment] 2017-02-08 19:09
the cause is some bug with the timer linked list causing a recursive reference that doesn't include the linked list head so it's not getting detected.

A timer thats already been ran is getting deleted and other things aren't accounting for this properly.

I haven't been able to narrow it down further and i got sidetracked by something else.

**Comment by MrStonedOne** [comment] 2017-02-08 19:13
when it happens, an admin can regenerate the list by vv'ing the timer subsystem's bucket_resolution to anything else, 0 works

**Comment by RemieRichards** [comment] 2017-02-08 19:16
@MrStonedOne use my totally inefficient linked list datum u shit

**Comment by xxalpha** [comment] 2017-02-08 23:30
pointers in byond when lummex

**Comment by LetterJay** [comment] 2017-02-28 23:37
Still seems to be ongoing.

**Comment by MrStonedOne** [comment] 2017-03-01 02:03
oh ya

**Comment by LetterJay** [comment] 2017-03-13 15:43
Ahhhh! Make it stop!!

```Runtime in timer.dm, line 85: Invalid timer: timer.timeToRun=63163||QDELETED(timer)=63176||world.time=63176.5||head_offset=62605||practical_offset=1117||timer.spent=1
proc name: fire (/datum/subsystem/timer/fire)```

**Comment by LetterJay** [comment] 2017-03-21 22:07
@MrStonedOne VV the timer and setting the bucket res to 0 from 0.5 then restarting the MC doesn't seem to do anything. The timer continues to hang, resulting in floating effects not deleting and doors not closing.

**Comment by Cyberboss** [comment] 2017-04-28 15:12
We've pushed a couple things in relation to this, let us know if it's still happening

**Comment by RocKeD** [comment] 2017-06-07 05:54
This might be of help, #28177

**Comment by ohnopigeons** [comment] 2017-06-08 16:36
That is 99.999% probably not related

**Closed** 2017-12-08 21:02 UTC
Labels: Bug
