### ISSUE TITLE
Nanotrasen bedsheets are invisible when worn

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26500] opened 2017-04-23 18:58 UTC
Server revision compiled on: 2017-04-23
The following pull requests are currently test merged:
#26465: 'Fixes Advanced Proc Call' by Cyberboss 
#26493: '[DNM] Revert "Speeds up lighting initialization"' by Cyberboss 

Based off master commit:
0a1107a91b87e156a6f18a7461bfd90f3a26a36c

**Comment by XDTM** [comment] 2017-04-23 19:49
Back to 800 issues!

**Comment by coiax** [comment] 2017-04-23 20:03
Issues are not bad. A lack of issues is not good.

**Comment by octareenroon91** [comment] 2017-04-23 20:26
There's a signal-to-noise issue though

**Comment by WJohn** [comment] 2017-04-24 04:47
Dupe of #24468 
This is slightly more detailed so I'll close the other one.

**Closed** 2017-06-22 16:03 UTC
Labels: Bug, Sprites
