### ISSUE TITLE
Clock cult progression seriously needs to be redone

### ISSUE THREAD

**Issue by Stealthkibbler** [tgstation/tgstation#22245] opened 2016-12-16 04:09 UTC
A problem I've noticed with clock cult is that it's too heavily reliant on rng, there can be times where you are just standing there doing nothing waiting for parts to generate and sometimes you just dont get the parts you need AT ALL even with caches and teamwork. Then there's the whole problem with needing geis components with recruiting. Had a round where I didnt get a single geis component for 30+ minutes, I finally got one when the shuttle was in transit; meanwhile another guy gets like 5 geis components before being promptly captured and put into perma. 

Meanwhile on the flipside we look at blood cult, if they need a talisman they can make it at will without any need of resources but a pint of blood. They can delay the escape shuttle multiple times and not only that but each cultists gets access to 3 free greater talismans allowing for them to jumpstart into the round while clockwork only gets 1 alloy, 1 geis and that's it.

Granted once you get to tier 3 its a cake walk from there on out, but the early game just gets fucked so hard purely because of the random generation of components. 

More often than not the best way to fight a clock cult is to just call the shuttle, had 2 rounds in a row where the heads of staff just called the shuttle on red alert and deconstructed the comms consoles and took the boards.

also a great depiction of cult difficulty and progression by keekenox.
http://puu.sh/sR4aq/601418a8f4.png

**Comment by TechnoAlchemisto** [comment] 2016-12-16 04:11
You should post this in the feedback forum, as it will be seen by a greater audience, also this will be closed as it is not a bug!

**Comment by ChangelingRain** [comment] 2016-12-16 04:11
Random component generation isn't a problem for any cult that shares components, either through a tinkerer's cache or just by hitting each other with slabs.
You need to do actual teamwork. Yes. Actual teamwork, not lone-wolfing off.

**Comment by ChangelingRain** [comment] 2016-12-16 04:12
also yeah this isn't a bug use the feedback forum

**Closed by ChangelingRain** 2016-12-16 04:12 UTC
Labels: Not a bug

**Comment by Stealthkibbler** [comment] 2016-12-16 04:13
Where might I find the feedback forum, i am partially braindead atm.

**Comment by TechnoAlchemisto** [comment] 2016-12-16 04:15
https://tgstation13.org/phpBB/viewforum.php?f=10

**Comment by Stealthkibbler** [comment] 2016-12-16 04:15
Thank you.
