### ISSUE TITLE
Head Rev Antag token lost after flashing lizard with no glasses???

### ISSUE THREAD

**Issue by TreehouseTech** [tgstation/tgstation#73540] opened 2023-02-19 20:44 UTC
Reporting client version: 514.1589

## Round ID:
[200422](https://scrubby.melonmesa.com/round/200422)

## Reproduction:

English is not my first language so bear with me.
OKAY so I was head rev and I was doing good, until I flashed a lizard called "Praise-The-Sun" and my blue antag token disappeared. 
He was not turned into a rev (he also wasn't wearing glasses) and got mad at me. I AdminHelp-ed and told Trexter555 but he didn't care, so I tried reconnecting and still nothing. I then died trying to reason with the admin for another antag token to no avail.
What happened? Can I have an antag token to replace this round?
My byond name is ThyNiceAnon, 
Thanks.

**Comment by ZephyrTFA** [comment] 2023-02-19 21:29
After reading through the game logs and dynamic log, you were selected for Provacateur.
You failed to flash the lizard because they were immune to flashes, you cannot convert someone who cannot be flashed.
You were still a Head Rev, you simply lost the hud due to a z-level transition.
And github is not the place to ask for an antag token.
This is a duplicate of https://github.com/tgstation/tgstation/issues/73134

**Closed by ZephyrTFA** 2023-02-19 21:29 UTC

**Comment by TreehouseTech** [comment] 2023-02-19 21:33
The lizard wasn't immune to flashes? It acted normally
