### ISSUE TITLE
Portable Song Tuning rite nonfunctional.

### ISSUE THREAD

**Issue by NoselessCanine** [tgstation/tgstation#83997] opened 2024-06-14 22:46 UTC
Reporting client version: 515.1640

## Issue Summary
When using the festival chaplain rite Portable Song Tuning, the instrument used gains a rite menu for tuning, but when a rite is selected, the tuning rite is not conducted  and a failure message is displayed, reading "This cannot perform that kind of rite."

## Round ID:
[230545](https://scrubby.melonmesa.com/round/230545)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Flatpacker](https://www.github.com/tgstation/tgstation/pull/83836)

## Reproduction:
Become chaplain. Choose festival. Cast portable song tuning on an instrument. Smack instrument with bible. Attempt to use a song tuning rite. Observe the rite fail.

**Comment by DATA-xPUNGED** [comment] 2024-06-16 17:07
On instrument_rites.dm:
```
/datum/religion_rites/portable_song_tuning/invoke_effect(mob/living/user, atom/movable/religious_tool)
	..()
	var/obj/item/instrument/empower_target = instrument_target
	var/turf/tool_turf = get_turf(religious_tool)
	instrument_target = null
	if(QDELETED(empower_target) || !(tool_turf == empower_target.loc)) //check if the instrument is still there
		to_chat(user, span_warning("Your target left the altar!"))
		return FALSE
	empower_target.visible_message(span_notice("[empower_target] glows for a moment."))
	playsound(tool_turf, 'sound/effects/pray.ogg', 50, TRUE)
	var/list/allowed_rites_from_bible = subtypesof(/datum/religion_rites/song_tuner)
	empower_target.AddComponent( \
		/datum/component/religious_tool, \
		operation_flags = RELIGION_TOOL_INVOKE, \
		force_catalyst_afterattack = FALSE, \
		after_sect_select_cb = null, \
		catalyst_type = /obj/item/book/bible, \
		charges = 5, \
		rite_types_allowlist = allowed_rites_from_bible, \
	)
	return TRUE
```
It passes all subtypes of `song_tuner` as a list to `rite_types_allowlist` but it asks for a typecache on the actual check. I've tried passing a typecache instead by using `var/list/allowed_rites_from_bible = typecacheof(/datum/religion_rites/song_tuner, FALSE, TRUE)` But it still reacted the same way. Here is the chef that gives the fail message, on `religious_tool.dm`
```
if(rite_types_allowlist && !is_path_in_list(path, rite_types_allowlist))
	to_chat(user, span_warning("This cannot perform that kind of rite."))
	return
```

**Comment by Profakos** [comment] 2024-06-26 12:08
Duplicate of #80497 and #80942, but I think this one has the most information.

**Comment by Profakos** [comment] 2024-06-26 12:29
For reference, the rite  list of the sect in question:

```	
rites_list = list(
		/datum/religion_rites/holy_violin,
		/datum/religion_rites/portable_song_tuning,
		/datum/religion_rites/song_tuner/evangelism,
		/datum/religion_rites/song_tuner/light,
		/datum/religion_rites/song_tuner/nullwave,
		/datum/religion_rites/song_tuner/pain,
		/datum/religion_rites/song_tuner/lullaby,
	)
```
The `/datum/religion_rites/song_tuner` tuner subtypes are in here, so this is very strange.

**Comment by Profakos** [comment] 2024-06-26 20:16
Found the reason, the path variable was a string instead of an actual path.

**Closed** 2024-07-03 21:24 UTC
