### ISSUE TITLE
Blowgun darts can hit through directional windows

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#77983] opened 2023-08-28 12:38 UTC
## Round ID:

213555

## Testmerges:

[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)
[#77813: '[TEST-MERGE FIRST] Allows all limbs to be dismembered and significantly refactors wounds' by nikothedude at commit bed7906764](https://www.github.com/tgstation/tgstation/pull/77813)
## Reproduction:

Fire a blowgun dart (regular syringe) at a directional window and it will hit the object behind the window. In the picture, there was a water tank behind the directional r-window that ruptured from being hit by blowgun darts.

![Blowgun](https://github.com/tgstation/tgstation/assets/2476001/9eef7624-522d-4755-a85a-8ea87a65b5da)

**Comment by Sealed101** [comment] 2023-08-28 13:53
Duplicate of #77914

**Closed by Sealed101** 2023-08-28 13:53 UTC
