### ISSUE TITLE
You can (kind of) duplicate items with fishing rods

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#77265] opened 2023-07-31 17:40 UTC
Reporting client version: 514.1589

## Round ID:
[211457](https://scrubby.melonmesa.com/round/211457)

## Testmerges:
- [Bumps rust-g to `3.0.0` ](https://www.github.com/tgstation/tgstation/pull/76663)

## Reproduction:

1) With a fishing rod, click on any item.
2) Have someone else pick up the item
3) Use the fishing rod (press Z)

This duplicates the item in kind of a weird quantum state. Does really weird shit with guns, in that if the person with the rod drops the copy they made and the person who has the original fires, the bullets come out of the duplicated gun.

**Comment by Jacquerel** [comment] 2023-07-31 23:16
I _think_ this might actually be a duplicate of #73014

**Closed** 2023-09-14 22:00 UTC
Labels: In Game Exploit
