### ISSUE TITLE
Saving chat log causes NtOS in the chat log

### ISSUE THREAD

**Issue by captainfrost20** [tgstation/tgstation#69190] opened 2022-08-13 19:54 UTC
## Round ID:
I cant remember which round I noticed it but its sorta not needed

## Reproduction:
Literally just hit save chat log.

I've had about 5 to 6 different people now reproduce this. I thought it was just me but its apparently not. Its an issue with TGUI I think as I launched goon to test it and it didn't break over there.

**Comment by dragomagol** [comment] 2022-08-13 21:28
Duplicate of #69097

**Closed by dragomagol** 2022-08-13 21:28 UTC
