### ISSUE TITLE
thermals broke

### ISSUE THREAD

**Issue by RobustAndrun** [tgstation/tgstation#33411] opened 2017-12-09 04:03 UTC
Issue reported from Round ID: 79889 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: 
thermals don't give thermal vision, they just make it look really dark

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment] 2017-12-09 07:29
duplicate of #33409

**Closed by ShizCalev** 2017-12-09 07:29 UTC
