### ISSUE TITLE
Admin Ghosts can pickpocket living mobs

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#30604] opened 2017-09-11 05:53 UTC
Can't affect anyone with pockets obscured, but just casual pick-pocketing drops the item to the floor.

Regular ghosts cannot pickpocket.

Mobs receive the occasional warning of 'someone is trying to pickpocket you' as normal.

**Comment by YPOQ** [comment] 2017-09-11 07:21
Duplicate of #19114

**Closed** 2017-09-11 07:39 UTC
