### ISSUE TITLE
Staff of Storms doesnt work properly

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58475] opened 2021-04-16 12:42 UTC
## Reproduction:

When staff used on the station, you get the message and sound of incoming storm, but nothing happens in the room you ve used the staff. That round AI reported storm was somewhere in space instead. Staff works fine on Lavaland.

**Comment by timothymtorres** [comment] 2021-08-25 12:32
This sounds like #28228

My guess is that the tile or area you used the staff on was a nearspace area or some engineering messed with the blueprints causing this.

**Comment by timothymtorres** [comment] 2022-08-18 00:35
So after code diving, it appears `/area/space/nearstation` is a subtype of `/area/space` and gets checked in the blacklist.  This needs to be reproduced.

**Comment by timothymtorres** [comment] 2022-11-08 00:56
This issue has existed since at least 2019 in #42179 but I'm keeping this one open since it has more information.

**Comment by Sealed101** [comment] 2023-08-27 10:08
ash storm staff can't cause an ash storm anymore but it can end weathers in an area it's used in. while this issue is no longer applicable, the bug may have moved to the weather stopping property. needs further testing

**Comment by Sealed101** [comment] 2023-09-22 18:29
i was extensively using the storm staff to stop storms so i can attest that it works fine

**Closed by Sealed101** 2023-09-22 18:29 UTC
Labels: Bug, Needs Reproducing
