### ISSUE TITLE
Research console icons got swapped by random ones

### ISSUE THREAD

**Issue by AzureWildfire** [tgstation/tgstation#38838] opened 2018-06-30 23:17 UTC
Issue reported from  Round ID: 90286 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

No relevant test merges

The icons on the normal view of research are swapped by others, I think it might be thanks to the teg fix, that added the teg to research.

https://prnt.sc/k1avnu

**Comment by PKPenguin321** [comment] 2018-06-30 23:38
Clear your byond cache?

**Comment by SpaceManiac** [comment] 2018-07-01 00:07
The logs suggest you played 90284 on bagil and stayed connected over the round change to 90286, is this true?

**Comment by AzureWildfire** [comment] 2018-07-01 00:08
yes, i will check clearing the cache

**Comment by SpaceManiac** [comment] 2018-07-01 00:31
Clearing the cache would fix it with certainty, I suspect that closing out of BYOND and reconnecting would also have been sufficient. Basically the issue is that the asset is sent on one round, and then the server has updated the next round so the asset has changed, but the client simply sees this as a temporary connection blip, doesn't know that the old asset is invalid, and keeps using it.

**Comment by AzureWildfire** [comment] 2018-07-01 00:40
cache clearing didn't do it for me

**Comment by SpaceManiac** [comment] 2018-07-01 00:51
Could you try exiting BYOND completely and deleting the entire `My Documents\BYOND\cache` folder?

**Comment by AzureWildfire** [comment] 2018-07-01 01:02
Still happening and is not random is always the same icons, if it's just me then maybe is my byond and I will try reinstalling.

**Comment by SpaceManiac** [comment] 2018-07-01 01:39
Turns out this is an actual bug

**Closed** 2018-07-02 20:18 UTC
Labels: Bug
