### ISSUE TITLE
Mapping shit be FUCKED on tramstation

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#84634] opened 2024-07-04 03:24 UTC
Reporting client version: 515.1637

## Issue Summary
The evac area where the shuttle lands in Tramstation had a LOT of Error tiles labelled Shit Be Fucked. No clue how it happened

## Round ID:
[231583](https://scrubby.melonmesa.com/round/231583)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cytology without plumbing](https://www.github.com/tgstation/tgstation/pull/84235)
- [Flattens The Floor Plane (Camera Update Too)](https://www.github.com/tgstation/tgstation/pull/84350)

## Reproduction:
1. Be on glorious Tramstation
2. Yell at a mapper I guess

![Screenshot 2024-07-03 222257](https://github.com/tgstation/tgstation/assets/88996803/967befc2-ebe9-425f-be98-828e8965fedc)

**Comment by OuroborusReporter** [comment] 2024-07-04 03:27
Update: Some of them just... Flew off into space? When the shuttle arrived. Like, they slid off into the horizon

**Comment by SpaceLoveSs13** [comment] 2024-07-04 08:44
Seems like nearstation errors.

**Comment by norsvenska** [comment] 2024-07-05 15:20
it's above the wawa supply dock too
![image](https://github.com/tgstation/tgstation/assets/73006946/064c5b51-eb55-4bee-a107-f254c0d15c5f)
round 231662

**Comment by Sadboysuss** [comment] 2024-07-05 15:55
dupe of https://github.com/tgstation/tgstation/issues/84597 actually
And this isn't really mapping cause there's not much mappers can do about this

**Comment by TheVekter** [comment] 2024-07-05 17:07
Closing as dupe, please add info about these bugs on other maps to the above issue.

**Closed by TheVekter** 2024-07-05 17:07 UTC
Labels: Mapping, FUCK
