### ISSUE TITLE
No hunters spawning for fugitives

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#44052] opened 2019-05-19 22:35 UTC
## Reproduction:
Both of these rounds had no hunter spawning after fugitives popped. 108752 I can confirm had no ghost roll for hunter either, so its probably not a missing ghosts thing.

**Comment by kriskog** [comment] 2019-05-19 22:37
@tralezab

**Comment by tralezab** [comment] 2019-05-20 16:28
More bugs your grace?

Dont worry this was already reported and fixed in my latest pr, I just gotta finish ship movement and we're good

**Comment by AnturK** [comment] 2019-05-21 10:42
Duplicate of #43945

**Closed by AnturK** 2019-05-21 10:42 UTC
