### ISSUE TITLE
rotating the white ship (send to the same place but in different dir) causes problems

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44389] opened 2019-06-08 10:21 UTC
Round ID: 110116

![image](https://user-images.githubusercontent.com/222630/59299709-2a7bd700-8c42-11e9-99e6-cd647187518e.png)

**Comment by SpaceManiac** [comment] 2019-06-11 19:12
Did it go through transit first?

**Comment by Tlaltecuhtli** [comment] 2019-06-12 06:34
yes

**Comment by Dennok** [comment] 2019-06-19 10:27
still #43694 
but shuttles created bu this have some charm.

As i say before, problem in placing shuttle dock marker on the shuttle and moving it with the shuttle in transit and when it landing it lands on himself on transit.

**Comment by dragomagol** [comment] 2020-11-01 22:11
Duplicate of #43694 #39906 #40797 #50097

**Closed by dragomagol** 2020-11-01 22:11 UTC
Labels: Bug
