### ISSUE TITLE
Assembling a new camera can't be upgraded with xray

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#79583] opened 2023-11-07 21:57 UTC
Round ID: [218336](https://scrubby.melonmesa.com/round/218336)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [e54bfa3d47afc36254c336dcd431f8971c3ffebe](https://www.github.com/tgstation/tgstation/commit/e54bfa3d47afc36254c336dcd431f8971c3ffebe)
The following pull requests are currently test merged:
[#79316: 'Extends Halloween' by Jacquerel at commit 9cc0f029d3](https://www.github.com/tgstation/tgstation/pull/79316)
[#79340: 'Changes how halloween lighting works slightly' by LemonInTheDark at commit 615818d8d1](https://www.github.com/tgstation/tgstation/pull/79340)

Local commit: 9bb47249fd350e365730479498c0360caec7fa89
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

1.  Using a camera assembly, set up a new camera to the stations network, and add a gas analyzer as part of the process.
2. Check the camera network via some means, and notice xray is NOT enabled.  Also note the camera isn't showing the xray enabled sprite.
3. Also also notice that whatever you named the camera doesn't seem to be on the camera list(not fully tested).

The camera seems to be a part of the system, as the AI was able to see me when I set one up in maint, but they said no xray and I think the camera name wasn't listed on the camera list.

**Comment by timothymtorres** [comment] 2023-11-08 00:39
Duplicate of #79019

**Closed by timothymtorres** 2023-11-08 00:39 UTC
