### ISSUE TITLE
Direlict drones cannot access R&D console and power consoles.

### ISSUE THREAD

**Issue by coolmanabdul** [tgstation/tgstation#67419] opened 2022-05-30 16:58 UTC
Reporting client version: 514.1583

## Round ID:
[184046](https://scrubby.melonmesa.com/round/184046)

## Reproduction:Join round on basil(don't know if it affects other servers) spawn in as a derelict drone power the old power console, vault power console and R&D console left click on each it should say something to vain of "you cannot comprehend anything this computer is saying." The issue is all of these consoles are given to Derelict drones and are key to making the spawner playable without them the derelict drone is severely restricted.

Apologies if this wasn't done correctly I've never done a bug report for /TG/

**Comment by timothymtorres** [comment] 2022-05-30 21:11
Duplicate of #67350

**Closed by timothymtorres** 2022-05-30 21:11 UTC

**Comment by timothymtorres** [comment] 2022-05-30 21:12
Thanks for the bug report, I'll be fixing this sometime today.  The cause is the illiterate quirk causing several mobs not being able to read and write.

**Comment by coolmanabdul** [comment] 2022-05-30 21:29
Alright thanks for your time.
