### ISSUE TITLE
Using Spy scanner on clothing being worn by yourself bugs out.

### ISSUE THREAD

**Issue by DrDoomson** [tgstation/tgstation#86569] opened 2024-09-09 06:52 UTC
### Client Version:

515.1642

### Issue Summary:

When a spy scans clothing they are wearing (in my 1 case, the reflective sec trenchcoat) it properly gives the item but the clothing is still worn in a broken state, it appears to be worn on the model, the slot is filled and CANNOT be taken off and is otherwise non-funcitonal, including hood button. Ahelped with Gameadmin Dunham.

### Round ID:

[237302](https://scrubby.melonmesa.com/round/237302)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)

### Reproduction Steps:

1. Be a spy with a scanner
2. Wear something that can be scanned for spy reward
3. Scan the item.

**Comment by MrMelbert** [comment] 2024-09-09 06:56
Dupe of #83742

**Closed by MrMelbert** 2024-09-09 06:56 UTC
