### ISSUE TITLE
Exploration drone cargo space is STILL bugged

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#77412] opened 2023-08-07 00:35 UTC
i remember making an issue report about this atleast a year ago, but it hasnt been fixed and i cant find the issue report, so heres another one

any round
do the exploration drone thing
the drone clearly shows six cargo slots, but if you have four filled and try to take anything from an anomaly/site, it wont get deposited onto the drone

**Comment by Sealed101** [comment] 2023-08-07 05:41
Duplicate of #67973

**Comment by Sealed101** [comment] 2023-08-07 05:42
man these drones are sad

**Closed by Sealed101** 2023-08-07 05:42 UTC
