### ISSUE TITLE
Purple raptors can't be mounted

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#84152] opened 2024-06-19 20:03 UTC
Reporting client version: 515.1636

## Issue Summary

Click chain stuff seems to have messed this up too. You can't drag yourself onto a purple raptor to mount them.

## Round ID:
[230814](https://scrubby.melonmesa.com/round/230814)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Bitrunning: Tweaks, QoL and removals](https://www.github.com/tgstation/tgstation/pull/84125)
- [Adds a new power storage type: The Megacell. Drastically reduces power cell consumption/storage. [MDB Ignore]](https://www.github.com/tgstation/tgstation/pull/84079)

## Reproduction:

Click drag yourself onto a purple raptor

**Comment by Moonlit2000** [comment] 2024-06-19 22:31
it looks like they literally don't have a rideable component for some reason

**Comment by SmArtKar** [comment] 2024-06-22 09:58
They do have a ridable component, and work just fine on the current version. Either this was fixed by one of the later PRs, or was caused by something else in that specific round.

**Closed by SmArtKar** 2024-06-22 09:58 UTC
Labels: Bug
