### ISSUE TITLE
Meth exploding in body

### ISSUE THREAD

**Issue by H3skan** [tgstation/tgstation#77909] opened 2023-08-24 13:47 UTC
Reporting client version: 514.1589

## Round ID:
[213245](https://scrubby.melonmesa.com/round/213245)

## Reproduction:
- make meth
- load meth into a syringe gun, cooling it just below 300K
- fire syringe gun at clown
- clown delimbed and crit since the body temperature raises the temperature of the meth enough to cause explosion
-> meth explodes in body even with said feature being supposed to not work for obvious balancing reasons

**Comment by Angustmeta** [comment] 2023-08-24 14:34
Has different reproduction steps and round ID. The wizard-farming, Terry meta instakill-mix seems to be: 

10 units:
• 2.7 units of Diethylamine
• 3.1 units of Ephedrine
• 2.7 units of Mercury
• 0.5 units of Hydrogen
• 0.5 units of Phosphorus
• 0.5 units of Iodine

I've been told this makes lipolicide which triggers the meth impurity (fermichem) explosion. 

I assume it can be fixed with a `mob_react = FALSE` in the right spot. Other methsplosion types already have that tag.

**Comment by mikederkan** [comment] 2023-08-26 09:52
just a heads up, you need all ingredients to be cooled to 99k for it to not react before being shot. easily replicatable

**Closed** 2023-08-31 18:51 UTC
