### ISSUE TITLE
Carried humanoids are not brought up a ladder - only pulled ones are

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53825] opened 2020-09-18 18:32 UTC
Issue reported from  Round ID: [146563](https://scrubby.melonmesa.com/round/146563) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

**Comment by dragomagol** [comment] 2021-05-20 21:12
Duplicate of #49968

**Closed by dragomagol** 2021-05-20 21:12 UTC
Labels: Bug
