### ISSUE TITLE
Zombies are Busted (Normal Movespeed, Headless Revival)

### ISSUE THREAD

**Issue by AlamoTurtle** [tgstation/tgstation#76509] opened 2023-07-03 05:15 UTC
Reporting client version: 514.1589

## Round ID:
[209543](https://scrubby.melonmesa.com/round/209543)

## Reproduction:
Step 1. Zombify with Romerol
Step 2. Run at max speed into a threat that can decapitate you (remember the PR that moved speed to legs? Still default carbon legs on you)
Step 3. Die. Just die. Get decapped.
Step 4. Be shocked when you come back with no head.
Step 5. Realize this is a result of the Species Nuking PRs (Extremely likely)

**Comment by SyncIt21** [comment] 2023-07-03 05:29
@ChungusGamer666 thoughts?

**Comment by ChungusGamer666** [comment] 2023-07-03 06:05
@SyncIt21 
Movespeed is 100% a fuckup on my part, but headless memery is most likely not.

**Comment by ChungusGamer666** [comment] 2023-07-03 06:07
Related to https://github.com/tgstation/tgstation/issues/73425 which was filed before well, most of the species nukings.

**Comment by ChungusGamer666** [comment] 2023-07-03 06:13
> @SyncIt21 Movespeed is 100% a fuckup on my part, but headless memery is most likely not.

I've figured out the issue with movespeed and will pr a fix, but uhhh, headless stuff will be more complicated...

**Comment by SyncIt21** [comment] 2023-07-03 13:49
> @SyncIt21 Movespeed is 100% a fuckup on my part, but headless memery is most likely not.

After you fix the Movespeed bug we can close this issue because everything else is just a duplicate of #73425

**Comment by Sealed101** [comment] 2023-07-03 16:56
i'm gonna take a wild guess and say that the tumor tried to and succeded in revivin the decapped zombie as a zombie again. something broke, this ain't a dupe

**Comment by ChungusGamer666** [comment] 2023-07-03 16:57
> i'm gonna take a wild guess and say that the tumor tried to and succeded in revivin the decapped zombie as a zombie again. something broke, this ain't a dupe

besides for the movespeed modifier stuff, yes this is a dupe

**Comment by Sealed101** [comment] 2023-07-03 17:06
the linked issue described reviving a decapped zombie by a different method, here the tumor seems to have revived the player as it tried to zombify them again. unless that is also present in the linked issue, this is a different bug. cause could be similar, maybe the tumor just doesn't really ever stop reviving dead players into zombies. just that usually a zombie doesn't die from damage, so it never triggers

also have some hard deletes and a runtime from the round
```
[2023-07-03 04:45:34.877] RUNTIME: runtime error: Cannot read null.real_name
 - proc name: update limb (/obj/item/bodypart/head/update_limb)
 -   source file: head.dm,194
 -   usr: NUCLEAR APRATIVE (/mob/living/carbon/human)
 -   src: Axle Brady\'s head (/obj/item/bodypart/head/zombie)
 -   usr.loc: the floor (92,117,2) (/turf/open/floor/iron)
 -   src.loc: the floor (93,118,2) (/turf/open/floor/iron)
 -   call stack:
 - Axle Brady\'s head (/obj/item/bodypart/head/zombie): update limb(null, null)
 - Axle Brady\'s head (/obj/item/bodypart/head/zombie): drop organs(NUCLEAR APRATIVE (/mob/living/carbon/human), 1)
 - Axle Brady\'s head (/obj/item/bodypart/head/zombie): attackby(the zombie claw (/obj/item/mutant_hand/zombie), NUCLEAR APRATIVE (/mob/living/carbon/human), "icon-x=16;icon-y=20;left=1;but...")
 - the zombie claw (/obj/item/mutant_hand/zombie): melee attack chain(NUCLEAR APRATIVE (/mob/living/carbon/human), Axle Brady\'s head (/obj/item/bodypart/head/zombie), "icon-x=16;icon-y=20;left=1;but...")
 - NUCLEAR APRATIVE (/mob/living/carbon/human): ClickOn(Axle Brady\'s head (/obj/item/bodypart/head/zombie), "icon-x=16;icon-y=20;left=1;but...")
 - Axle Brady\'s head (/obj/item/bodypart/head/zombie): Click(the floor (93,118,2) (/turf/open/floor/iron), "mapwindow.map", "icon-x=16;icon-y=20;left=1;but...")
 - Axle Brady\'s head (/obj/item/bodypart/head/zombie):  Click(the floor (93,118,2) (/turf/open/floor/iron), "mapwindow.map", "icon-x=16;icon-y=20;left=1;but...")
 - /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
 - world: push usr(NUCLEAR APRATIVE (/mob/living/carbon/human), /datum/callback/verb_callback (/datum/callback/verb_callback))
 - /datum/callback/verb_callback (/datum/callback/verb_callback): InvokeAsync()
 ```

29 total zombie organ hard deletes
```
[2023-07-03 04:46:14.016] RUNTIME: ## TESTING: GC: -- [0x201b761] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:46:14.016] RUNTIME: ## TESTING: GC: -- [0x201fba9] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:46:14.017] RUNTIME: ## TESTING: GC: -- [0x201ffb4] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:49:03.449] RUNTIME: ## TESTING: GC: -- [0x20196b8] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:49:03.450] RUNTIME: ## TESTING: GC: -- [0x201ad09] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:49:03.450] RUNTIME: ## TESTING: GC: -- [0x201acff] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:50:46.587] RUNTIME: ## TESTING: GC: -- [0x201e864] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 4)
[2023-07-03 04:50:46.587] RUNTIME: ## TESTING: GC: -- [0x20207a4] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 2)
[2023-07-03 04:50:46.588] RUNTIME: ## TESTING: GC: -- [0x20207b3] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 2)
[2023-07-03 04:50:56.539] RUNTIME: ## TESTING: GC: -- [0x20205db] | /obj/item/organ/internal/ears was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:50:56.539] RUNTIME: ## TESTING: GC: -- [0x201b1db] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:50:56.540] RUNTIME: ## TESTING: GC: -- [0x201fd84] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:50:56.540] RUNTIME: ## TESTING: GC: -- [0x201ea34] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:51:51.713] RUNTIME: ## TESTING: GC: -- [0x201b996] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:51:51.714] RUNTIME: ## TESTING: GC: -- [0x201fbb8] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:52:09.102] RUNTIME: ## TESTING: GC: -- [0x201d7a8] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 2)
[2023-07-03 04:52:09.103] RUNTIME: ## TESTING: GC: -- [0x201bc76] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 2)
[2023-07-03 04:52:09.104] RUNTIME: ## TESTING: GC: -- [0x20208ba] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 2)
[2023-07-03 04:52:20.069] RUNTIME: ## TESTING: GC: -- [0xd009ca8] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:52:30.494] RUNTIME: ## TESTING: GC: -- [0x201b656] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:52:30.494] RUNTIME: ## TESTING: GC: -- [0x20204a4] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:52:30.495] RUNTIME: ## TESTING: GC: -- [0x2006f3d] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:53:09.478] RUNTIME: ## TESTING: GC: -- [0x201ccc1] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:09.478] RUNTIME: ## TESTING: GC: -- [0x201bb8d] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:09.479] RUNTIME: ## TESTING: GC: -- [0x201bb91] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:21.255] RUNTIME: ## TESTING: GC: -- [0xd064acf] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:33.284] RUNTIME: ## TESTING: GC: -- [0xd064054] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:35.622] RUNTIME: ## TESTING: GC: -- [0xd06652d] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:53:59.684] RUNTIME: ## TESTING: GC: -- [0xd065342] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:54:01.807] RUNTIME: ## TESTING: GC: -- [0x20200da] | /obj/machinery/camera was unable to be GC'd -- (ref count of 7)
[2023-07-03 04:54:06.060] RUNTIME: ## TESTING: GC: -- [0xd065918] | /image was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:54:12.729] RUNTIME: ## TESTING: GC: -- [0x201b2b8] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:54:12.730] RUNTIME: ## TESTING: GC: -- [0x2020246] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:54:12.730] RUNTIME: ## TESTING: GC: -- [0x202026a] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)

[2023-07-03 04:59:27.624] RUNTIME: ## TESTING: GC: -- [0x201dbbd] | /obj/item/organ/internal/brain/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:59:27.625] RUNTIME: ## TESTING: GC: -- [0x2020970] | /obj/item/organ/internal/eyes/zombie was unable to be GC'd -- (ref count of 3)
[2023-07-03 04:59:27.625] RUNTIME: ## TESTING: GC: -- [0x2020946] | /obj/item/organ/internal/tongue/zombie was unable to be GC'd -- (ref count of 3)
```

**Comment by ChungusGamer666** [comment] 2023-07-03 17:22
@Sealed101 I looked at zombie code and I am 90% sure that both issues are caused by the zombie "gland" organ having basically no proper checks before setting the species (and healing)

**Closed** 2023-07-04 16:43 UTC
Labels: Bug
