### ISSUE TITLE
Ruins can spawn ontop of the bridge to the necropolis and if the blocks near the bridge are destroyed it creates a hole into space

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18825] opened 2016-06-22 01:47 UTC
![image](https://cloud.githubusercontent.com/assets/6778786/16252134/aa943df6-37f9-11e6-8d63-cfd9161761da.png)

Uh and apparently you can destroy the blocks to create a hole into space

**Comment by ChangelingRain** [comment] 2016-06-22 02:00
Indestructible turfs getting replaced and destroyed causes problems what a shocker

**Comment by Kromgar** [comment] 2016-06-22 02:10
They didnt get replaced. The dude bombed them and they got destroyed

**Comment by Kromgar** [comment] 2016-06-22 02:46
Either way ruins shouldnt spawn on top of the bridge

**Comment by xxalpha** [comment] 2016-06-22 12:34
This is a duplicate of https://github.com/tgstation/tgstation/issues/16246

**Comment by Dorsisdwarf** [comment] 2016-06-22 13:44
dooplicat i guess

**Closed by Dorsisdwarf** 2016-06-22 13:44 UTC
Labels: Bug
