### ISSUE TITLE
Boil Blood doesn't deplete holymelon anti-magic charges

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50816] opened 2020-05-02 10:20 UTC
#### Reproduction:
Invoke spam several 'Boil Blood' runes near a dude holding a holymelon. It does nothing even if used 10+ times. 

#### Expected result
Since a single boil blood deals damage multiple times it should probably spend several antimagic charges per invoke. Holymelons get 1 antimagic per 20 potency iirc. 

Hallucination spell doesn't spend antimagic charges either. Stun spell works as expected. 

![200502 1218 42](https://user-images.githubusercontent.com/46400996/80861489-2f3ce580-8c6f-11ea-9c4e-a53be8529523.png)

**Comment by XDTM** [comment] 2020-05-04 09:25
This is intentional, due to the high tick rate it would deplete charges far more quickly than other more powerful spells.

A possible solution might be having granular antimagic charges and customized charges consumed on each spell, although that'd take some balancing and a bit of a refactor.

**Comment by timothymtorres** [comment] 2022-02-08 07:04
https://github.com/tgstation/tgstation/blob/8f3121454b65e79994d8920b83784fe1950d5fbb/code/modules/antagonists/cult/runes.dm#L746-L757

This is intended.  Cursing someone also does not deplete charges.  Marking this as `Not a Bug` and `Cleanup` which will autoclose this in 7 days.

**Closed** 2022-02-18 04:57 UTC
Labels: Not a bug, Cleanup Flagged
