### ISSUE TITLE
A talking mirror

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#77512] opened 2023-08-10 17:22 UTC
## Round ID: 

 212220

## Reproduction:

1. Stand in front of a mirror.
2. Speak
3. See below

![dreamseeker_MTJtV4Mc0Q](https://github.com/tgstation/tgstation/assets/5195984/a3481221-82cf-4c40-b919-757c8840165d)

**Comment by Ghommie** [comment] 2023-08-10 18:40
Duplicate of #77431, which the fix for has been merged recently.

**Comment by distributivgesetz** [comment] 2023-08-10 19:15
Reported round happened 8 hours before the fix was merged, so we can assume this was fixed. Closing as duplicate of #77431.

**Closed by distributivgesetz** 2023-08-10 19:15 UTC
