### ISSUE TITLE
if a monkey wears a bedsheet around their neck and faces south, the leg gaps in the south-facing bedsheet sprites are painfully obvious

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56030] opened 2021-01-08 08:26 UTC
![image](https://user-images.githubusercontent.com/42606352/103991853-e839b500-5158-11eb-80ea-c7b7506e9812.png)

This is similar to the moth wing issue that Arcane had to deal with.

**Comment by dragomagol** [comment] 2021-01-08 18:11
Duplicate of a vintage issue #34956

**Closed by dragomagol** 2021-01-08 18:11 UTC
Labels: Bug, Oversight, Sprites
