### ISSUE TITLE
RPD can't make half the disposals junctions it needs to

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22875] opened 2017-01-09 05:45 UTC
Disposals pipes can only face one direction. T shaped junctions will sort right, for example. There is no way to flip them, such as making them sort left but still be T shaped. Same with Y junctions. You can't pick up disposals pipes (for whatever fucking reason) so you can't flip them.

**Comment by Core0verload** [comment] 2017-01-09 06:12
Try RMB menus, alt-click, shift-click. Then close this.

**Comment by PKPenguin321** [comment] 2017-01-09 06:42
Maybe related to https://github.com/tgstation/tgstation/issues/22248

**Comment by ShadowDeath6** [comment] 2017-01-09 07:38
Can't you pull it around to make it change directions?

**Comment by YakumoChen** [comment] 2017-01-09 07:42
pulling it can't ''flip'' the pipe to mirror it.

**Comment by YakumoChen** [comment] 2017-01-09 09:39
alt click is the first thing I tried and it does the same thing as dragging it. RMB has no discernible difference, either

**Comment by Core0verload** [comment] 2017-01-09 11:20
rgb menu has a fucking "Flip Pipe" button in it

**Comment by optimumtact** [comment] 2017-01-09 21:38
This is not a bug

**Closed by optimumtact** 2017-01-09 21:38 UTC
Labels: Consistency Issue
