### ISSUE TITLE
dead mice disappear when put in buns

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#57284] opened 2021-02-28 14:51 UTC
issue reported by a player so needs reproduction

## Reproduction:

1. have a dead mouse
2. put it in a bun to make burger
3. they disappear

**Comment by ArcaneDefence** [comment] 2021-02-28 18:48
Duplicate of https://github.com/tgstation/tgstation/issues/56544

**Closed by ArcaneDefence** 2021-02-28 18:48 UTC
Labels: Bug, Needs Reproducing
