### ISSUE TITLE
Silver IDs cannot hold heads of staff trim

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#69412] opened 2022-08-23 18:06 UTC
Reporting client version: 514.1585

## Round ID:
[189086](https://scrubby.melonmesa.com/round/189086)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:

Silver ID's cannot be trimmed as heads of staff ID's.

1. Pick a silver card
2. Try to apply any head of staff trim (warden is working)
3. See a message like this: The trim you selected could not be added to Syndi Kate's ID Card (Head of Personel). You will need a rarer ID card to imprint that trim data.

**Comment by Mooshimi** [comment] 2022-08-27 17:37
can anyone snip a vid of them testing this bug Im currently busy

**Comment by Sealed101** [comment] 2023-06-01 20:17
trying to trim a roundstart silver ID to a head role seems to be the issue - trimming to a lower rank then to a head role seems to be working fine


https://github.com/tgstation/tgstation/assets/75863639/2de7deb2-f8ca-4ebc-a6c1-771036d51dfe



related code:

https://github.com/tgstation/tgstation/blob/0a273ce37ea6c71db4a3ec5438827e95bd982dcd/code/game/machinery/PDApainter.dm#L339-L351

it's returning FALSE here
https://github.com/tgstation/tgstation/blob/0a273ce37ea6c71db4a3ec5438827e95bd982dcd/code/controllers/subsystem/id_access.dm#L392-L397

and as it tries to assign new wildcards, it can't, as they are all assigned already. but setting it to a role with less wildcard access lets it pass through, and from there you can reassign it to a higher tier head role
https://github.com/tgstation/tgstation/blob/cb4a836d416c3f616438be0b9ef2d1ce73ea2168/code/game/objects/items/cards_ids.dm#L162-L194

**Comment by Hoolny** [comment] 2024-10-21 02:39
Without doing any alternative things
![LhvQkcZ](https://github.com/user-attachments/assets/2807b560-a7cf-4a60-9c2e-85c76966959c)
Manage to get all the silver ID's ascribed into head of staff positions only didn't work with captain which is working as intended, as far as I am able to tell this is no longer a bug

**Closed by Hoolny** 2024-10-21 02:39 UTC
Labels: Bug, Consistency Issue
