### ISSUE TITLE
Eating good food makes me grossed out

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29669] opened 2017-08-03 06:09 UTC
![image](https://user-images.githubusercontent.com/2003111/28908282-a94de252-77d7-11e7-8a6a-7fdf3a4aa2dd.png)

**Comment by PraiseRatvar** [comment] 2017-08-03 10:36
@Qustinnus

**Comment by AnturK** [comment] 2017-08-03 12:10
Duplicate of #29672

**Closed by AnturK** 2017-08-03 12:10 UTC
