### ISSUE TITLE
Protolathes wont accept minerals!

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#33338] opened 2017-12-06 17:20 UTC
Testmerge might be responsible: #33082: 'tweaks techwebs' by Dorsisdwarf at commit 418f9e

But yea, can't put jack shit into the protolathes, rendering them useless.

**Comment by Cyberboss** [comment] 2017-12-06 17:23
R O U N D I D

**Comment by Robustin** [comment] 2017-12-06 17:40
Uh current round on Bagil, where do I get round ID

**Comment by Spaceinaba** [comment] 2017-12-06 18:01
in the status tab
you know
where it says round id

**Comment by vuonojenmustaturska** [comment] 2017-12-06 20:44
dupe of #33321

**Closed** 2017-12-07 14:29 UTC
Labels: Bug

**Comment by Cyberboss** [comment] 2017-12-07 15:57
Duplicate of #33321
