### ISSUE TITLE
Trophy Racks clip through the head when facing away from camera

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#44714] opened 2019-06-21 05:45 UTC
Pretty self explanatory. When facing away from the camera the trophy rack's spikes should be on the back of your head but they instead vanish and reappear once they pass your head.

Issue reported from  Round ID: 111117 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by nemvar** [comment] 2019-06-21 09:23
Got a picture of it?

**Comment by NoxVS** [comment] 2019-06-23 04:36
![Screenshot (748)](https://user-images.githubusercontent.com/41690870/59971683-f1e7d180-954e-11e9-95f4-3f122c566836.png)

**Comment by timothymtorres** [comment] 2022-08-09 06:40
Duplicate of #37990

**Closed by timothymtorres** 2022-08-09 06:40 UTC
Labels: Sprites
