### ISSUE TITLE
Screen froze

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#52813] opened 2020-08-09 06:00 UTC
# Testmerges 
#52426 

Was flying about as a ghost, and my screen just.... froze? 
Chat and stat panel still worked, but the main display just stopped. Relogging fixed it
![image](https://user-images.githubusercontent.com/58055496/89725699-e95a9080-d9c6-11ea-9551-e32e0f643c5e.png)

**Comment by Jared-Fogle** [comment] 2020-08-09 08:27
This happens to me frequently, I think it's just a BYOND issue. I have to completely restart my game (not just reconnect) to fix it.

**Comment by ShizCalev** [comment] 2020-08-09 18:23
Duplicate of #2601

**Closed by ShizCalev** 2020-08-09 18:23 UTC
