### ISSUE TITLE
Changeling last resort is broken

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#64110] opened 2022-01-14 21:23 UTC
## Round ID:
[176590](https://scrubby.melonmesa.com/round/176590)

## Testmerges:
#63666 

## Reproduction:
Be a ling, get last resort, use it fully and revive with it, notice your chemical reserve hud element is gone and unable to use any ability because of "You are only capable of using this in a human form!" or similar message, mutadone fixes being unable to use powers but the chemical hud is still gone

**Comment by MrMelbert** [comment] 2022-01-14 22:41
maybe a dupe of #56314

**Comment by JohnFulpWillard** [comment] 2022-05-06 08:46
Closed by https://github.com/tgstation/tgstation/pull/66052

**Closed by JohnFulpWillard** 2022-05-06 08:46 UTC
Labels: Bug
