### ISSUE TITLE
Carvings turn black when fully built and can no longer be colored

### ISSUE THREAD

**Issue by benman347** [tgstation/tgstation#61228] opened 2021-09-03 23:25 UTC
## Round ID: 
[168960](https://scrubby.melonmesa.com/round/168960)

## Reproduction: 
Carve an airlock or chair completely

Chair or airlock carvings turn black on completion and are no longer colorable non finished (99%) ones behave as expected.
attached is a picture of it the right ones are built to 99% the left ones are built completely.
Its very easy to reproduce and seems to not be caused by a testmerge.
For chairs only their podest turns Color.
![glitch_tg](https://user-images.githubusercontent.com/62154137/132073817-ba8e3005-7d1f-41c4-b906-a97bc3003cd7.PNG)

**Comment by benman347** [comment] 2021-09-04 12:38
different round same result (ID:168994)
![glitch_tg2](https://user-images.githubusercontent.com/62154137/132094673-1d473699-640c-41dd-beeb-cb9db4872e58.PNG)

**Comment by necromanceranne** [comment] 2021-09-04 23:04
Pretty sure the icon that pops up when you hit sonething also turns black.

**Comment by TemporalOroboros** [comment] 2021-09-04 23:18
I am going to go out on a limb here and say that statues have `KEEP_TOGETHER`.

**Comment by timothymtorres** [comment] 2023-01-11 13:47
Duplicate of #60464

**Closed by timothymtorres** 2023-01-11 13:47 UTC
Labels: Bug

**Comment by timothymtorres** [comment] 2023-01-11 21:28
![dreamseeker_sGtAQuLoy2](https://user-images.githubusercontent.com/5195984/211921544-c5b035b0-5207-4a63-991f-f044fb7c6d27.png)

Also whatever was causing the black void bug appears to have been fixed.
