### ISSUE TITLE
Gunpowder Grenades don't work.

### ISSUE THREAD

**Issue by Thunderfleece** [tgstation/tgstation#62506] opened 2021-11-01 09:25 UTC
Reporting client version: 514.1561

## Round ID:
[172303](https://scrubby.melonmesa.com/round/172303)

## Reproduction:
Blackpowder heated to the point that they'd spark when a grenade is armed never explodes due to the grenade deleting itself before the delayed explosion triggers. 

I found this out a month ago but only remember to post it now but Trauf on discord checked it on a private server before and it apparently causes runtime errors when this happens.
![Trauf gunpowder test](https://user-images.githubusercontent.com/58954436/139650621-63951c9c-6072-478a-9919-6c31fcb89497.png)

**Comment by ArcaneDefence** [comment] 2021-11-01 16:31
Duplicate of https://github.com/tgstation/tgstation/issues/54986
Related to https://github.com/tgstation/tgstation/issues/42097

**Closed by ArcaneDefence** 2021-11-01 16:31 UTC
