### ISSUE TITLE
You can move while sliding from freon ice

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20349] opened 2016-09-05 22:18 UTC
THIS MIGHT BE BAD

**Comment by Jalleo** [comment] 2016-09-06 10:22
@Iamgoofball

**Comment by phil235** [comment] 2016-09-06 11:49
Is this going to be #5441 all over again?

**Comment by Iamgoofball** [comment] 2016-09-06 13:11
I need more details and reproduction information.

**Comment by ChangelingRain** [comment] 2016-09-06 13:34
While sliding press a movement key(wow woah)

**Comment by Iamgoofball** [comment] 2016-09-06 14:35
Fucking how

**Comment by Durkel** [comment] 2016-09-06 20:13
Sad part is when the server shit itself during a freon test with people hulked out I pointed out that this may be problem since the slipping bug was never actually fixed, it just removed slipping from hulk.

Honk honk

**Comment by XDTM** [comment] 2016-09-06 22:22
Stun removing chems maybe

**Comment by ChangelingRain** [comment] 2016-09-06 22:28
The actual lag behind hulk slipping never got fixed, no.

**Comment by Iamgoofball** [comment] 2016-09-07 00:18
# REMOVE HULK

**Comment by Jalleo** [comment] 2016-09-07 08:40
Or do the same sort of fix Phil did for lube hulk slip.

**Comment by Cyberboss** [comment] 2017-01-18 16:48
Fixed in #22490 @lzimann

**Closed** 2017-01-18 18:16 UTC
Labels: Bug
