### ISSUE TITLE
Janiborgs cannot auto-wash

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#77623] opened 2023-08-14 18:38 UTC
Reporting client version: 514.1589

## Round ID:
[212529](https://scrubby.melonmesa.com/round/212529)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
Be a Janiborg
Get water from a water tank into your bucket
Press the "Activate Auto-Wash" button
It starts channeling and instantly stops, putting the action on cooldown

**Comment by Sealed101** [comment] 2023-08-14 19:48
Duplicate of #73287

**Closed by Sealed101** 2023-08-14 19:48 UTC
