### ISSUE TITLE
Borgs can't complete Stomach Pump or Cavity Implant surgeries

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#48941] opened 2020-01-22 15:16 UTC
Issue reported from  Round ID: 128714 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1507

Reported by Panvxv, says that whenever he tries to finish either of these surgeries it just results in him trying to implant whatever he has selected, usually the cautery.

I was able to replicate on live servers.

**Comment by kriskog** [comment] 2020-01-25 01:35
@ArcaneMusic

**Comment by ArcaneMusic** [comment] 2020-01-26 22:39
Well, stomach pump requires a hand to do the "pump stomach" step. Should be able to give a medborg tool a way to finish the step as well.

**Comment by Guestratem** [comment] 2020-01-30 01:16
both surgeries require hands so realistically a borg cant actually do it unless they have a hand module

**Comment by Waseemq1235** [comment] 2020-01-30 22:23
Same thing for dental implants.
Thing is, I dont believe that cyborgs should be able to do cavity/dental implants. But I do believe that they should get a module for stomach pumping.

**Comment by ArcaneMusic** [comment] 2020-09-24 08:20
Now, in an ironic twist of fate, the above PR would have closed this issue, as the subject of the stomach pump PR and cavity implant surgeries were settled on. HOWEVER, it would seem that the NEW stomach changes broke this again, meaning it's mutated into a NEW issue now.

**Comment by dragomagol** [comment] 2020-12-24 03:49
I was able to reproduce this, up until finishing the surgery it works as intended.

**Comment by ArcaneDefence** [comment] 2021-04-10 04:11
You can finish the either of these surgeries by using drapes on them with a cautery in an inactive module slot while on combat mode.

This is not communicated to the player at all.

**Comment by Mooshimi** [comment] 2022-08-12 14:15
Adding feedback tag bc of the above comment.

**Comment by Sealed101** [comment] 2023-06-12 06:52
the issue is that when a surgery step can accept a hand as a tool, it will automatically succeed if the surgeon is a silicon

https://github.com/tgstation/tgstation/blob/65b168af718b69b79b4762e619a3df751a4ff03f/code/modules/surgery/surgery_step.dm#L16-L27

the previously mentioned method to stop a surgery is a global method for all surgeries and yeah it's a bit of a secret but otherwise not in the scope of this particular issue

**Closed** 2024-01-20 19:44 UTC
Labels: Tested/Reproduced, Oversight
