### ISSUE TITLE
supermatter engine input/output pipes freeze at a temperature and stay there even in the total absence of cooling. engine does not overload.

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#25130] opened 2017-03-15 10:42 UTC
Server revision compiled on: 2017-03-15
acb141bf7129267f21e9b4724bf11bac1e436130 

this morning i had both the input/output pipes on the SM engine frozen at a certain temperature for over half an hour. despite the constant injection of a 50/50 plasma/oxygen mix the supermatter stayed at a permanently constant temperature of about 18,000C and did not once overload (or even overheat) after a while i shut off the cooling entirely (no spaceloop or freezers) and it still stayed that way for 15+ minutes. the actual pipes around the supermatter (IE, past the filter to canisters, the near and far sides of the spaceloop) did change temperatures as expected. 

kind of silly and no idea what caused it. earlier in the round it was working fine, then it just froze probably 20 minutes into the round and remained that way forever.

**Comment by Razharas** [comment] 2017-03-15 11:29
https://github.com/tgstation/tgstation/issues/11566
Related?

**Comment by Jalleo** [comment] 2017-03-16 10:06
Unlikely but someone needs to check the code first.

**Comment by Tokiko1** [comment] 2017-03-16 21:50
I'm pretty sure this is not a bug. This happens if there is too much pressure and pumps stop being able to handle it. This doesn't just apply to regular pressure pumps, even volumetric ones stop working at around 8000 kPA. The suppermatter not taking damage has been fixed though.

**Comment by duncathan** [comment] 2017-04-01 22:25
this sounds very much like a matter of too few moles to move. remember that just because something is high pressure, it's not necessarily a lot of gas.

**Comment by duncathan** [comment] 2017-10-15 21:11
closing for the reasons I mentioned above

**Closed by duncathan** 2017-10-15 21:11 UTC
Labels: Atmospherics, Not a bug
