### ISSUE TITLE
Biogenerator blue screens when pressing on Chemicals

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#83634] opened 2024-06-01 17:17 UTC
Reporting client version: 515.1639

## Issue Summary
Bio generator brings up NTos blue screen when pressing on chemicals

## Round ID:
229804

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)

## Reproduction:
Open biogenerator and press chemicals tab. Blue screens every time for multiple people

**Comment by Jacquerel** [comment] 2024-06-01 17:18
Duplicate of #83571

**Closed by Jacquerel** 2024-06-01 17:18 UTC
