### ISSUE TITLE
Rolling wizard with die of fate as monkey doesnt give you the spellbook.

### ISSUE THREAD

**Issue by Nexofas** [tgstation/tgstation#58920] opened 2021-05-06 16:11 UTC
Reporting client version: 513.1542
Rolled 20 with die of fate as monkey ( which was a 6 roll from the same die), became a wizard without a spellbook.

## Round ID:
[161718](https://scrubby.melonmesa.com/round/161718)

## Testmerges:
- [(code bounty) refactors all uses of Crossed() and Uncrossed() into signals sent to loc, tracked by connect_loc](https://www.github.com/tgstation/tgstation/pull/58340)

**Comment by timothymtorres** [comment] 2021-12-10 11:09
Duplicate of https://github.com/tgstation/tgstation/issues/57953

**Comment by timothymtorres** [comment] 2021-12-10 11:11
Also this appears to be fixed with https://github.com/tgstation/tgstation/pull/60506

**Closed** 2021-12-10 11:12 UTC
