### ISSUE TITLE
You can empty peoples storages as ghost

### ISSUE THREAD

**Issue by soyconsumer** [tgstation/tgstation#35538] opened 2018-02-11 12:59 UTC
1. Be ghost
2. Use observe verb to observe someone
3. alt click their backpack/belt/whatever storage
4. their shit falls on the ground

**Comment by evsey9** [comment] 2018-02-11 13:02
dupe of https://github.com/tgstation/tgstation/issues/35450

**Closed** 2018-02-11 13:03 UTC
