### ISSUE TITLE
You can crash everyone around you by doing somethign that spams chat messages under goonchat

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#31052] opened 2017-09-27 12:41 UTC

**Comment by ExcessiveUseOfCobblestone** [comment] 2017-09-29 14:57
sounds like a high priority bug!

**Comment by DaxDupont** [comment] 2017-09-29 21:57
Yeah that was the cause of the pressure plate crasher

**Comment by PKPenguin321** [comment] 2019-07-23 09:56
This issue was opened about 3 months after goonchat was merged, and has remained open for the last 2 years or so. Have we had any instances of goonchat spam outright crashing the game lately?

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-07-23 17:18
funny enough yes

**Comment by notfrying1pans** [comment] 2019-07-28 17:42
goonchat can cause the game to lag for a few seconds but i havent crashed due to it

**Comment by kriskog** [comment] 2020-07-19 12:07
SSChat limits the amount of goonchat messages over time now, this should be fixed

**Closed by kriskog** 2020-07-19 12:07 UTC
Labels: Bug, In Game Exploit, Needs Reproducing
