### ISSUE TITLE
Dragon's blood gibbing

### ISSUE THREAD

**Issue by ISwearToStonedImNotGod** [tgstation/tgstation#88080] opened 2024-11-21 19:13 UTC
### Client Version:

515.1645

### Issue Summary:

When I used the dragon's blood loot from an ash drake, I was immediately gibbed when turned into a lizard. Station was Delta, and I had the divine vocal cords implanted at the time. Not sure if that made a difference. Might also be worth noting that I had internals on from an O2 tank in my suit storage

My logs when I used the blood and died:
"Your appearance morphs to that of a very small humanoid ash dragon! You get to look like a freak without the cool abilities.
Your internals disconnect from the oxygen tank and the valve closes.
Randy Baum has died at Cargo Bay.
You have died. Barring complete bodyloss, you can in most cases be revived by other players. If you do not wish to be brought back, use the "Do Not Resuscitate" verb in the ghost tab."

The admin log I was given after ahelping in game:
"ADMIN LOG: ISwearToStonedImNotGod/(Randy Baum)(?) (FLW) was gibbed after their chest teleported to Cargo Bay (172,173,2) (JMP)."

### Round ID:

[242953](https://scrubby.melonmesa.com/round/242953)

### Test Merge Information:

- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

1. Start shift as human shaft miner
2. Get divine vocal cords implanted
4. acquire and use dragon's blood, see if it gibs you

**Comment by Sadboysuss** [comment] 2024-11-21 19:15
did you perhaps have over 100 damage to your character at the time of transforming?

**Comment by ISwearToStonedImNotGod** [comment] 2024-11-21 19:18
> did you perhaps have over 100 damage to your character at the time of transforming?

I do not know

**Comment by Sadboysuss** [comment] 2024-11-21 19:20
could be dupe of https://github.com/tgstation/tgstation/issues/87990

**Comment by mc-oofert** [comment] 2024-11-21 19:20
absolutely irrelevant because that interaction sets your species

**Closed** 2024-11-21 20:56 UTC
Labels: Bug, Needs Reproducing
