### ISSUE TITLE
changeling can get objective to kill another changeling when only one exists

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41472] opened 2018-11-13 11:14 UTC

**Comment by ShizCalev** [comment] 2018-11-13 20:09
The absorb objective I'm assuming?

**Comment by ShizCalev** [comment] 2018-11-13 20:14
@AnturK

**Comment by ShizCalev** [comment] 2018-11-13 20:15
Duplicate of #38753

**Closed by ShizCalev** 2018-11-13 20:15 UTC
Labels: Bug
