### ISSUE TITLE
AI Camera *static* disappears allowing AI to view maintainance normally

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#49631] opened 2020-02-29 07:29 UTC
Issue reported from  Round ID: 131197 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

For a temporary period of time, the camera *static* as seen by the AI player vanished, permitting full vision of maintainance as well as live occurances within. After about 2 minutes, the situation remidied itself. Immediately prior to this, I was accessing my AI shell for the first time. 

Reporting client version: 513.1511

**Comment by Tharcoonvagh** [comment] 2020-02-29 08:26
Dupe

**Comment by Dorsisdwarf** [comment] 2020-02-29 11:29
Dupe of #49623, thanks for reporting the issue though.

**Closed by Dorsisdwarf** 2020-02-29 11:29 UTC
