### ISSUE TITLE
Slimeperson transformation completely fucks over heretics.

### ISSUE THREAD

**Issue by hyperjll** [tgstation/tgstation#86681] opened 2024-09-15 15:04 UTC
### Client Version:

515.1641

### Issue Summary:

Becoming a slime person causes a heretic to lose their living heart, and trying to perform the living heart ritual to regain it is impossible.

### Round ID:

[238021](https://scrubby.melonmesa.com/round/238021)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

1. Roll heretic.
2. Use green slimes to become a slime person.
3. "You've lost your living heart!"
4. Attempt the living heart ritual and fail cause "you have no heart!"

**Comment by Sealed101** [comment] 2024-09-15 19:18
Duplicate of #71451

**Closed by Sealed101** 2024-09-15 19:18 UTC
