### ISSUE TITLE
Hunters ship for Waldo is incomplete

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#49487] opened 2020-02-21 22:02 UTC
Issue reported from  Round ID: 130696 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

The hunters ship for the waldo event is lacking a lot.
1. The ship has no o2 bottles. There are suits and canisters and masks, but no way to supply them.

2. The ship is made of steel walls, can we at least map it with shuttle walls? Looks like a flying brick right now.

3. The ships direction in flight is orientated wrong, so it "flies" sideways.

Picture for proof of ugly.
https://i.imgur.com/1MOn5fO.png

**Comment by bobbahbrown** [comment] 2020-02-23 13:26
Only point 3 is bug-like, marking as not a bug.

**Comment by cacogen** [comment] 2020-02-24 03:29
Actually doesn't look as bad as I was expecting. Still should be changed.

**Closed** 2020-07-09 20:21 UTC
Labels: Mapping, Not a bug
