### ISSUE TITLE
Chloral hydrate seems to be broken

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#29402] opened 2017-07-20 19:45 UTC
Round ID 73562. Chloral hydrate does not process, have any effects, etc. It also does not metabolize, so it just sits in your system forever.

**Comment by Iamgoofball** [comment] 2017-07-20 19:53
Nice

**Comment by Supermichael777** [comment] 2017-07-20 20:30
wait realy?
Does this still fucking happen? Because this should not be happening.

what was the server revision?

**Comment by Supermichael777** [comment] 2017-07-20 22:03
could not reproduce in private testing.

**Comment by Supermichael777** [comment] 2017-07-20 22:10
@maintainers Resolved in current build, server needs to be updated

**Comment by AnturK** [comment] 2017-07-21 07:09
Duplicate of #27983

**Closed by AnturK** 2017-07-21 07:09 UTC
