### ISSUE TITLE
Pressing alt+direction key makes you stop moving

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#33665] opened 2017-12-18 23:03 UTC
> Server revision compiled on: 2017-12-18
> 
> The following pull requests are currently test merged:
> #33656: 'Mi-go skin that hopefully has nothing to do with copyright and stuff' by Armhulen at commit a2b4d0
> 
> 
> Based off origin/master commit: 588230
> 
> Server tools version: /tg/station 13 Server v3.2.1.9
> 
> Server tools API version: 3.2.0.1

Move around with WASD
Press and hold alt-key to walk
Stop moving until you either repress the direction key or release alt.

**Comment by SpaceManiac** [comment] 2017-12-18 23:58
Possible dupe of #33648? The revision you list is from before that fix.

**Comment by ninjanomnom** [comment] 2017-12-20 01:10
Duplicate of #33648 and fixed in most recent version.

**Closed by ninjanomnom** 2017-12-20 01:10 UTC
Labels: Bug
