### ISSUE TITLE
Bluespace body bag self pick up weirdness (feat. Super Secret Room)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69952] opened 2022-09-16 04:03 UTC
Reporting client version: 514.1585

## Round ID:
[190568](https://scrubby.melonmesa.com/round/190568)

## Testmerges:
- [Fixes weird blank in Watchlist Update Messages when adding a expiration date](https://www.github.com/tgstation/tgstation/pull/69897)
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

Have yourself folded into a bluespace body bag and dropped (folded).
While inside the folded body bag, pick up your folded body bag.
Have someone else let you out (or break out)
Your hand seems empty but if you left click on the floor you can dupe the bluespace body bag indefinately.

While these items seem to be actual copies of bluespace body bags, they all also share the same "folded_instance"

You can do some wierd things with this like teleporting items by putting them in one bag, folding it, dropping it, then folding a different copy to call the folded_instance to your hand and then unwrap it.

If, however, you fold one of them up and then destroy it completely, e.g. supermatter sword it, then anything you put into the other bags and fold will be nullspaced, notably a cliented player will end up in Super Secret Room due to having a null location, and everything else gets deleted (i presume).

EDIT:  It seems the nullspacing only happens for a period of time (until the object is fully cleared - references or something?), after which folding the bag will create a new folded bag, and a wholely duped bluespace body bag.

**Comment by Mooshimi** [comment] 2022-10-17 22:31
Duplicate of #44902

**Closed by Mooshimi** 2022-10-17 22:31 UTC
