### ISSUE TITLE
Wheelchairs absolutely fucked

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44151] opened 2019-05-26 02:23 UTC
Round ID: 109234

So this plasmaman had a wheelchair, and long story short I stole it and was wheeling away in it. People tried to unbuckle me and pull me away, but after about a second of being out of the chair I'd magically teleport back into it. This happened several times, no explanation for it. Then, it, stopped. The wheelchair was stuck, you couldnt get in it, and if you tried to drag it, it'd slow you down to walk speed, but the chair itself wouldn't move. Then somehow someone (Larry Spankenheimer) put ME into the chair, at which point I started teleporting back into it. And thats the story.

**Comment by wesoda25** [comment] 2019-05-26 02:24
Oh my apparently it doesn't end there, after the chair went through a portal I stopped teleporting to it, and 5 minutes later I teleport back into it and cant leave.

**Comment by wesoda25** [comment] 2019-05-26 02:24
ok now the chair is teleporting to me

**Comment by wesoda25** [comment] 2019-05-26 02:32
ok and now I was like 200 tiles away and just randomly teleported to the chair again, I think whenever someone tries to pull the chair it puts me back in it.

**Comment by 4dplanner** [comment] 2019-05-26 12:28
oh DEAR

**Comment by wesoda25** [comment] 2019-05-28 04:57
> oh DEAR

I agree its quite alarming

**Comment by MegaEmpirical** [comment] 2019-05-28 15:21
I went through a portal with a wheel chair once and the wheel chair ditched me (it went through) and left my bitch ass on the floor.

**Comment by DingleFlop** [comment] 2019-05-29 03:32
..........................


Feature..?

**Comment by evsey9** [comment] 2019-05-29 23:20
not a bug, the wheelchair uses bluespace technology to make sure the disabled person doesn't fall out on accident

**Comment by kriskog** [comment] 2019-07-01 08:49
Probably related to #42924 and #42040 too

**Comment by wesoda25** [comment] 2019-12-18 01:09
wasnt this fixed by bgos pr that fixes chair based teleportation?

**Comment by timothymtorres** [comment] 2021-11-20 20:36
I'm pretty sure this was fixed with #58230 and have seen no recent bug reports about this for several years.

**Comment by SuperNovaa41** [comment] 2021-11-23 00:33
Cleanup flagged still not working properly :)

**Closed** 2021-11-23 00:33 UTC
Labels: Bug, Cleanup Flagged

**Comment by timothymtorres** [comment] 2021-11-23 10:08
> Cleanup flagged still not working properly :)

@Ghommie any idea what went wrong with #62138?  This has happened for several issues in the tracker.

**Comment by Ghommie** [comment] 2021-11-23 14:06
> > Cleanup flagged still not working properly :)
> 
> @Ghommie any idea what went wrong with #62138? This has happened for several issues in the tracker.

The cleanup flagged label works (as long as the stale action, github actions and github in general do), but it only autocloses issues after 7 days. Plus it seems it wasn't programmed to keep track of issues that had target labels before the PR was merged.

**Comment by timothymtorres** [comment] 2021-11-23 14:20
Ahh makes sense.  Any issues that were labeled before the PR was made will need to be manually closed.
