### ISSUE TITLE
When processing a sausage if you don't select an option it runtimes

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#66256] opened 2022-04-17 15:33 UTC
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Spawn a knife, spawn a sausage, hold the knife, open the radial menu to pick which result, then walk away or click the x 

[09:31:21] Runtime in atoms.dm, line 1452: bad index
proc name: StartProcessingAtom (/atom/proc/StartProcessingAtom)

**Comment by SuperNovaa41** [comment] 2022-04-25 18:18
Can't reproduce

**Comment by SuperNovaa41** [comment] 2022-04-25 18:19
Closed by https://github.com/tgstation/tgstation/pull/66382

**Closed by SuperNovaa41** 2022-04-25 18:19 UTC
Labels: Runtime, Needs Reproducing
