### ISSUE TITLE
Drones cannot interact with electrified doors using tools

### ISSUE THREAD

**Issue by daplanman12** [tgstation/tgstation#62051] opened 2021-10-11 04:09 UTC
Reporting client version: 514.1566

## Round ID:
[171109](https://scrubby.melonmesa.com/round/171109)

## Reproduction:
A door that is electrified simply sparks when a drone interacts with it using a tool, and closes any tool menu.

1) RETURN TO DRONE
2) Cut electro wire. easier said than done, since drones also don't identify wires, and don't have plans.
3) use your integrated wirecutters and watch the sparks fly... and do no damage.

**Comment by Mooshimi** [comment] 2021-10-15 01:12
This looks to be unintended, an oversight then.

**Comment by Sealed101** [comment] 2023-06-04 17:57
same as #72249

**Comment by Mooshimi** [comment] 2023-07-22 16:04
Duplicate of #72249

**Closed by Mooshimi** 2023-07-22 16:04 UTC
Labels: Oversight
