### ISSUE TITLE
Printing wanted posters doesn't work right 

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#64115] opened 2022-01-15 00:31 UTC
Reporting client version: 514.1557

## Round ID:
[176595](https://scrubby.melonmesa.com/round/176595)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)

## Reproduction:

1. Print a wanted poster
2. wanted poster is called () and has no image

I have no idea why this happened, and I promise that I tried searching first. 

![image](https://user-images.githubusercontent.com/14065903/149597330-7d0e71cd-9466-437f-9ea3-1a5de27870e9.png)

**Comment by jlsnow301** [comment] 2022-01-15 05:14
this might be due to #63354

**Comment by Sealed101** [comment] 2024-10-15 12:51
very little details for reproduction but runtime logs suggest it was due to the issues fixed by https://github.com/tgstation/tgstation/pull/69956 - i see the base poster object has appeared there

(runtime logs are still down, runtime shittily copied from [scrubby](https://scrubby.melonmesa.com/round/176595/runtimes))
```
[23:17:04] bad icon operation 
1 | /icon (/icon): New(the wanted poster (VivI Fanter... (/obj/structure/sign/poster/wanted), null, 2, null, null)
-- | --
2 | the  wanted poster () (/obj/structure/sign/poster/wanted): Initialize(0, the  wanted poster (VivI Fanter... (/obj/structure/sign/poster/wanted),  null, null, null, "#FF0000", "wanted_background", "wanted poster", "A  wanted poster for")
3 | Atoms (/datum/controller/subsystem/atoms): InitAtom(the wanted poster () (/obj/structure/sign/poster/wanted), 0, /list (/list))
4 | the  wanted poster () (/obj/structure/sign/poster/wanted): New(0, the wanted  poster (VivI Fanter... (/obj/structure/sign/poster/wanted), null, null,  null, "#FF0000", "wanted_background", "wanted poster", "A wanted poster  for")
5 | the  poorly coded poster (/obj/item/poster/wanted): Initialize(0, the wanted  poster (VivI Fanter... (/obj/structure/sign/poster/wanted), null, null,  null)
6 | Atoms (/datum/controller/subsystem/atoms): InitAtom(the poorly coded poster (/obj/item/poster/wanted), 0, /list (/list))
7 | the poorly coded poster (/obj/item/poster/wanted): New(0, the wanted poster (VivI Fanter... (/obj/structure/sign/poster/wanted))
8 | the  wanted poster (VivI Fanter... (/obj/structure/sign/poster/wanted): roll  and drop(the floor (125,108,3) (/turf/open/floor/iron/white))
9 | the  wanted poster (VivI Fanter... (/obj/structure/sign/poster/wanted): roll  and drop(the floor (125,108,3) (/turf/open/floor/iron/white))
10 | the  wall (125,107,3) (/turf/closed/wall): place poster(the wanted poster  (VivI Fanter... (/obj/item/poster/wanted), Kat Blu  (/mob/living/carbon/human))
11 | the  wall (125,107,3) (/turf/closed/wall): try wallmount(the wanted poster  (VivI Fanter... (/obj/item/poster/wanted), Kat Blu  (/mob/living/carbon/human), the floor (125,108,3)  (/turf/open/floor/iron/white))
12 | the  wall (125,107,3) (/turf/closed/wall): attackby(the wanted poster (VivI  Fanter... (/obj/item/poster/wanted), Kat Blu (/mob/living/carbon/human),  "icon-x=16;icon-y=18;left=1;scr...")
13 | the  wanted poster (VivI Fanter... (/obj/item/poster/wanted): melee attack  chain(Kat Blu (/mob/living/carbon/human), the wall (125,107,3)  (/turf/closed/wall), "icon-x=16;icon-y=18;left=1;scr...")
14 | Kat Blu (/mob/living/carbon/human): ClickOn(the wall (125,107,3) (/turf/closed/wall), "icon-x=16;icon-y=18;left=1;scr...")
15 | the  wall (125,107,3) (/turf/closed/wall): Click(the wall (125,107,3)  (/turf/closed/wall), "mapwindow.map",  "icon-x=16;icon-y=18;left=1;scr...")
```

**Closed by Sealed101** 2024-10-15 12:51 UTC
Labels: Bug
