### ISSUE TITLE
library console can easily lag server

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47948] opened 2019-11-23 01:24 UTC
reproduction:
1. open library console
2. look at the window that has the search settings (it opens 2 windows at first, yes)
3. press start search without entering any parameters
4. ???
5. profit stuck

**Comment by ShizCalev** [comment] 2019-11-23 01:27
@actioninja since you've been fixing these

**Comment by kriskog** [comment] 2019-11-23 01:50
Dupe of  #45284
This is the visitors console only afaik, and it pulls the entire library.

**Comment by nemvar** [comment] 2019-12-01 01:15
since it's a dupe

**Closed by nemvar** 2019-12-01 01:15 UTC
