### ISSUE TITLE
Exploding a person's brain inside their own head with attached C4 destroys the brain but doesn't kill or harm the person.

### ISSUE THREAD

**Issue by Timberpoes** [tgstation/tgstation#51231] opened 2020-05-23 19:20 UTC
## Reproduction:
Organ manipulate head.
Remove brain.
Attach C4 with signallers to brain.
Re-insert brain.
Revive.
Activate signalers.
Subject has no brain but is still alive and seems to suffer no negative side effects at all.

Shoutouts to Airi Ixo who discovered the bug and Rhials Duffy who brought it to my attention.

![image](https://user-images.githubusercontent.com/24975989/82738840-b4795e80-9d32-11ea-817f-50c0eaf20d71.png)

**Comment by ATH1909** [comment] 2020-05-24 01:28
holy shit that's amazing

feature

**Comment by Kaffe-work** [comment] 2020-05-24 17:17
honestly, I wouldn't be surprised if half of the crew operates without a brain anyway

**Comment by nemvar** [comment] 2020-05-24 18:35
That's because ``special`` is set to true which prevents death if an inserted organ gets deleted.
If the comment above that is to be believed it's related to oddness in the transform code.

**Comment by BeeSting12** [comment] 2020-05-25 01:44
Issue of the year

**Comment by TemporalOroboros** [comment] 2020-05-25 16:10
Does this make people immune to brain damage?

**Comment by Ryll-Ryll** [comment] 2020-05-26 04:09
Head empty no thoughts

**Comment by trollbreeder** [comment] 2020-05-27 19:38
your brain gets smart but your head gets dumber

**Comment by gonenoculer5** [comment] 2020-06-05 20:40
brainless assistant go brr

**Comment by timothymtorres** [comment] 2021-12-28 13:37
Duplicate of #52103

**Closed by timothymtorres** 2021-12-28 13:37 UTC
Labels: Bug, FUCK, Against God and Nature
