### ISSUE TITLE
Body bags cant be closed even with nothing in.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#59729] opened 2021-06-18 21:50 UTC
Reporting client version: 513.1526

## Round ID:
[164364](https://scrubby.melonmesa.com/round/164364)

## Testmerges:
- [add variables to SSgarbage allowing hard deletes to be disabled in vv for testing](https://www.github.com/tgstation/tgstation/pull/59712)
- [Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount](https://www.github.com/tgstation/tgstation/pull/59676)
- [Do not look at this pr, do not speak of this pr, do not think of this pr](https://www.github.com/tgstation/tgstation/pull/59720)

## Reproduction:
Get a body bag and place it down.
Close it and try to drag it unto yourself.
"There are too many things inside of the body bag to fold it up!" even with nothing in.

**Comment by dragomagol** [comment] 2021-06-19 06:13
Duplicate of #59704

**Closed by dragomagol** 2021-06-19 06:13 UTC
