### ISSUE TITLE
tgui: Error: Access is denied (during stylesheet loading)

### ISSUE THREAD

**Issue by magicaltheonething** [tgstation/tgstation#59021] opened 2021-05-10 20:24 UTC
## Reproduction: Basically you join into the game and if you have dark mode enabled the UI will be all white, then the chatbox will have an option to refresh, clicking it does the NtOS error thing and says this 

   at isStyleSheetLoaded (http://127.0.0.1:56148/tmp17592/browseroutput.html:190:7)
   at node.onload (http://127.0.0.1:56148/tmp17592/browseroutput.html:283:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
 OldUI works fine but the NewUI(?) doesnt work and if you try and reconnect it does the same thing, this was on basil dont know if that would have anything to do with it either.

**Comment by dragomagol** [comment] 2021-05-12 16:12
Is this still happening, or was it fixed? I think this was around the time everyone was having UI issues.

**Comment by tnekohue** [comment] 2021-06-03 11:58
It just happened to me, so im going to say: NOT FIXED.
NTOS BlueScreen, Text is as follows
```
Error: Access is denied.

   at isStyleSheetLoaded (http://127.0.0.1:56134/tmp1168/tgui-window-1.html:198:7)
   at node.onload (http://127.0.0.1:56134/tmp1168/tgui-window-1.html:291:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
```

**Comment by tnekohue** [comment] 2021-06-03 12:02
I tested all the byond versions from 513.1530 up to 5.14.1554 and on both manuel and basil.
Seems to happen regardless of the running round.

**Comment by newfren** [comment] 2021-06-03 14:41
important information for the above, this did happen immediately after a ddos attack and mso having to move manuel onto a different port

**Comment by dragomagol** [comment] 2021-06-03 16:39
The original was after a DDoS as well, so it's likely related.

**Comment by Iamgoofball** [comment] 2021-06-03 20:46
Nope, this is a recurring issue with Russia and Cloudflare being crappy.
https://github.com/tgstation/tgstation/issues/55482

Closing as a duplicate.

**Comment by Iamgoofball** [comment] 2021-06-04 02:13
Turns out this is a separate issue!

**Comment by timothymtorres** [comment] 2021-12-21 23:00
Duplicate of #53997

**Closed by timothymtorres** 2021-12-21 23:00 UTC
Labels: UI
