### ISSUE TITLE
Sec/Admin huds no longer show implanted status

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38688] opened 2018-06-24 00:17 UTC
Issue reported from Round ID: 89946 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

![nyeetd1 1](https://user-images.githubusercontent.com/17237624/41814657-9a08a8ea-7754-11e8-8356-cbb4eb5c6143.png)
I'm very much implanted.

Maybe related to #37922?

**Comment by SpaceManiac** [comment] 2018-06-24 00:31
Duplicate of #38676

**Closed by SpaceManiac** 2018-06-24 00:31 UTC
Labels: Test Merge Bug
