### ISSUE TITLE
Blank tgUI "say" bar jumpscares me upon every reconnect

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#76383] opened 2023-06-28 10:00 UTC
![obraz](https://github.com/tgstation/tgstation/assets/68878861/bd281842-7e36-4f95-8e26-3c846cdefe54)

## Round ID:
[209197](https://scrubby.melonmesa.com/round/209197) 
is the latest for me

## Testmerges:
#75819 #76129 

## Reproduction:
Connect to a /tg/station server. Idk if it's actually worth anyone's time.
I feel like it's taunting me.

**Comment by Sealed101** [comment] 2023-06-28 10:29
- Duplicate of #75716

**Comment by Sealed101** [comment] 2023-06-28 10:29
Duplicate of #75716

**Closed by Sealed101** 2023-06-28 10:29 UTC
