### ISSUE TITLE
Ling readapt bugged after absorbing another one

### ISSUE THREAD

**Issue by xyawux** [tgstation/tgstation#52625] opened 2020-07-31 17:25 UTC
## Round ID:
> happened on fulp so irrelevant
caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request
## Reproduction:
After absorbing a ling i got the chemicals/evolution points readapted cause i didnt need pheromon receptors anymore, i only got 5 evolution points back and i failed my objective, and failed the objective
This was my third absorbtion, i got my chemicals, and bonus adapt points properly, but i wanted to readapt, clicked once got way less than i should, i've tried to readapt again, but i kept getting 5 points, i guess its a bug cause is hould be getting 15 instead? and it kept giving me 10 less than i should

**Comment by Kaffe-work** [comment] 2020-08-04 14:25
I think i fixed this a while ago, please confirm on /tg/station if this issue is still around.

**Comment by dragomagol** [comment] 2020-11-30 05:48
Duplicate of #51341

**Closed by dragomagol** 2020-11-30 05:48 UTC
