### ISSUE TITLE
monkey AI getting stuck in loop after failing to resolve target during combat/SelectBehaviors()

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#69048] opened 2022-08-06 21:24 UTC
https://github.com/tgstation/tgstation/blob/4c444712b972016a7137d99d06747665e14f5ba2/code/datums/ai/monkey/monkey_subtrees.dm#L40-L42
we sanity checked if there was a target ref, but not if we actually ended up with a target
```
[21:15:46] Runtime in monkey_subtrees.dm, line 42: Cannot read null.stat
proc name: SelectBehaviors (/datum/ai_planning_subtree/monkey_combat/SelectBehaviors)
src: /datum/ai_planning_subtree/mon... (/datum/ai_planning_subtree/monkey_combat)
call stack:
/datum/ai_planning_subtree/mon... (/datum/ai_planning_subtree/monkey_combat): SelectBehaviors(/datum/ai_controller/monkey (/datum/ai_controller/monkey), 0.5)
/datum/ai_controller/monkey (/datum/ai_controller/monkey): SelectBehaviors(0.5)
AI Controller Ticker (/datum/controller/subsystem/ai_controllers): fire(0)
AI Controller Ticker (/datum/controller/subsystem/ai_controllers): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop(2)
Master (/datum/controller/master): StartProcessing(0)
```
![image](https://user-images.githubusercontent.com/6209658/183266505-de4cffd0-aa84-4a09-9019-3c6284c47bba.png)

**Comment by timothymtorres** [comment] 2022-08-07 10:56
Is this related to or a duplicate of #68771?

**Comment by ShizCalev** [comment] 2022-08-07 16:25
Not related.

**Closed** 2022-10-22 20:10 UTC
Labels: Bug, Runtime
