### ISSUE TITLE
Serious screen glitches

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#21109] opened 2016-10-21 01:01 UTC
Details: So. For a couple days now my screen has a severe issue where certain things will trigger what I can only describe as byond having a seizure. Parts of the screen freeze up, others start swapping pixels willynilly while a small part remains entirely unharmed. I know it's not an issue with my computer either because certain things, once I desist doing them will stop causing my screen to spazz out.

How to replicate: There are several things that cause the problem, I hope they occur for others so I don't look like an idiot. Vision altering eyeware causes it, in a less severe form such as mesons and nightvision goggles. Moving shuttles causes an especially bad glitch where it freezes entirely even though life moves on. Moving in vents as well will trigger it.

This is honestly making it near impossible for me to play, and it's only occuring on TG so I'm once again certain something merged gave the server screen cancer.

**Comment by Bawhoppen** [comment] 2016-10-21 01:04
Are you on byond 511 or 510?

**Comment by KingPhilipIII** [comment] 2016-10-21 01:06
511.

**Comment by ChangelingRain** [comment] 2016-10-21 01:15
I'm going to bet my fucking house that it's planes, at least if the number of days is <= 3.

**Comment by KingPhilipIII** [comment] 2016-10-21 01:29
Okay, it's a bet. If it isn't I get your house.

**Comment by optimumtact** [comment] 2016-10-21 03:20
dupe of #21099

**Comment by optimumtact** [comment] 2016-10-21 03:20
we should probably revert the plane change for now

**Closed by optimumtact** 2016-10-21 03:20 UTC

**Comment by MrStonedOne** [comment] 2016-10-21 03:57
https://github.com/tgstation/tgstation/issues/21066#issuecomment-255004914

**Comment by MrStonedOne** [comment] 2016-10-21 06:49
For anybody affected: Open pager/hub (the main byond application where you log in) And click the white gear/cog icon in the top right and go to preferences (or press control+p). Go to games then make sure that "Use graphics hardware for displaying maps" is checked.

Reconnect to the game and that SHOULD fix it
