### ISSUE TITLE
drakes move and attack so fucking fast holy shit

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#64453] opened 2022-01-26 13:55 UTC
## Testmerges:
The following pull requests are currently test merged:
#64449: 'Revert "Make more use of <tool>_act"' by MrStonedOne at commit aa6dd5b874
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9

## Reproduction:
shoot a drake
it starts fucking booking it directly at you, far faster than drakes used to be able to move
additionally, it shoots fire with a much greater frequency, often shooting such that two volleys of fire exist at the same time
https://puu.sh/IF5Ln/343c1931ca.png
^this shit happened in the space of about a second, as soon as a I stepped close to it it hit me twice with no delay, then stepped forwards (at light speed and now undodgeable thanks to slowdown), used all three of its radial fireattacks in swift succession, then double hit me again to murder me

**Comment by SuperNovaa41** [comment] 2022-01-26 14:24
Duplicate of https://github.com/tgstation/tgstation/issues/64349

**Closed by SuperNovaa41** 2022-01-26 14:24 UTC
