### ISSUE TITLE
Kinetic accelerators can sometimes be unable to recharge

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#28802] opened 2017-06-24 23:47 UTC
VV of the KA at the time this happened. It happened once previously on the asteroid. This is a new admin-spawned KA, the KA that happened on the asteroid had modkits for damage, range and cooldown, but this does not:

 The proto-kinetic accelerator
<< east >>  

/obj/item/weapon/gun/energy
/kinetic_accelerator  Refresh 
 Select option ---Call ProcMark ObjectDelete---Add reagentTrigger EM pulseTrigger explosionFollowDelete all of type  

--------------------------------------------------------------------------------
E - Edit, tries to determine the variable type by itself.
C - Change, asks you for the var type first.
M - Mass modify: changes this variable for all objects of this type.

--------------------------------------------------------------------------------
Search:    

--------------------------------------------------------------------------------

(E) (C) (M) acid_level = 0 
(E) (C) (M) acted_explosions = null 
(E) (C) (M) actions = null 
(E) (C) (M) actions_types = null 
(E) (C) (M) active_timers = null 
(E) (C) (M) admin_spawned = 0 
(E) (C) (M) alight = null 
(E) (C) (M) allowed = null 
(E) (C) (M) alpha = 255 
(E) (C) (M) alternate_appearances = null 
(E) (C) (M) alternate_worn_icon = null 
(E) (C) (M) alternate_worn_layer = null 
(E) (C) (M) ammo_type = /list (1) 
1 [0x203029f] = the energy weapon lens /obj/item/ammo_casing/energy/kinetic
(E) (C) (M) ammo_x_offset = 2 
(E) (C) (M) ammo_y_offset = 0 
(E) (C) (M) anchored = 0 
(E) (C) (M) animate_movement = 2 
(E) (C) (M) appearance = 
(E) (C) (M) appearance_flags = 768 
(E) (C) (M) armor = /list (9) 
1 = "melee" 
2 = "bullet" 
3 = "laser" 
4 = "energy" 
5 = "bomb" 
6 = "bio" 
7 = "rad" 
8 = "fire" 
9 = "acid"
(E) (C) (M) armour_penetration = 0 
(E) (C) (M) atom_colours = null 
(E) (C) (M) attack_verb = /list (3) 
1 = "struck" 
2 = "hit" 
3 = "bashed"
(E) (C) (M) automatic = 0 
(E) (C) (M) automatic_charge_overlays = 1 
(E) (C) (M) azoom = null 
(E) (C) (M) bayonet = null 
(E) (C) (M) being_shocked = 0 
(E) (C) (M) blend_mode = 0 
(E) (C) (M) block_chance = 0 
(E) (C) (M) blood_DNA = null 
(E) (C) (M) body_parts_covered = 0 
(E) (C) (M) bottom_left_corner = null 
(E) (C) (M) bottom_right_corner = null 
(E) (C) (M) bounds = "32,32" 
(E) (C) (M) bound_height = 32 
(E) (C) (M) bound_width = 32 
(E) (C) (M) bound_x = 0 
(E) (C) (M) bound_y = 0 
(E) (C) (M) breakouttime = 0 
(E) (C) (M) buckled_mobs = null 
(E) (C) (M) buckle_lying = -1 
(E) (C) (M) buckle_prevents_pull = 0 
(E) (C) (M) buckle_requires_restraints = 0 
(E) (C) (M) burst_size = 1 
(E) (C) (M) CanAtmosPass = 1 
(E) (C) (M) canMouseDown = 0 
(E) (C) (M) canSmoothWith = null 
(E) (C) (M) can_bayonet = 1 
(E) (C) (M) can_be_unanchored = 0 
(E) (C) (M) can_buckle = 0 
(E) (C) (M) can_charge = 1 
(E) (C) (M) can_flashlight = 1 
(E) (C) (M) can_suppress = 0 
(E) (C) (M) can_unsuppress = 1 
(E) (C) (M) cell [0x2030641] = the EMP-proof cell /obj/item/weapon/stock_parts/cell/emproof 
(E) (C) (M) cell_type = /obj/item/weapon/stock_parts/cell/emproof 
(E) (C) (M) chambered = null 
(E) (C) (M) charge_delay = 4 
(E) (C) (M) charge_sections = 4 
(E) (C) (M) charge_tick = 0 
(E) (C) (M) client_mobs_in_contents = null 
(E) (C) (M) clumsy_check = 1 
(E) (C) (M) cold_protection = 0 
(E) (C) (M) color = null 
(E) (C) (M) container_type = 0 
(E) (C) (M) contents = /list (3) 
1 [0x2017d0d] = the electronic firing pin /obj/item/device/firing_pin 
2 [0x2030641] = the EMP-proof cell /obj/item/weapon/stock_parts/cell/emproof 
3 [0x203029f] = the energy weapon lens /obj/item/ammo_casing/energy/kinetic
(E) (C) (M) crit_fail = 0 
(E) (C) (M) current_skin = null 
(E) (C) (M) damtype = "brute" 
(E) (C) (M) dangerous_possession = 0 
(E) (C) (M) density = 0 
(E) (C) (M) desc = "A self recharging, ranged mining tool that does increased damage in low pressure." 
(E) (C) (M) dir = 4 
(E) (C) (M) dog_fashion = null 
(E) (C) (M) embedded_fall_chance = 5 
(E) (C) (M) embedded_fall_pain_multiplier = 5 
(E) (C) (M) embedded_impact_pain_multiplier = 4 
(E) (C) (M) embedded_pain_chance = 15 
(E) (C) (M) embedded_pain_multiplier = 2 
(E) (C) (M) embedded_unsafe_removal_pain_multiplier = 8 
(E) (C) (M) embedded_unsafe_removal_time = 30 
(E) (C) (M) embed_chance = 45 
(E) (C) (M) empty_state = "kineticgun_empty" 
(E) (C) (M) equip_delay_other = 20 
(E) (C) (M) equip_delay_self = 0 
(E) (C) (M) explosion_block = 0 
(E) (C) (M) fingerprints = null 
(E) (C) (M) fingerprintshidden = /list (1) 
Bgobandit = "First: Spends-the-Fortune[23:46:13](gloves). Ckey: bgobandit Last: Spends-the-Fortune[23:46:58](gloves). Ckey: bgobandit"
(E) (C) (M) fingerprintslast = "bgobandit" 
(E) (C) (M) fire_delay = 0 
(E) (C) (M) fire_sound = 'sound/weapons/kenetic_accel.ogg' 
(E) (C) (M) firing_burst = 0 
(E) (C) (M) flags = 64 
(E) (C) (M) flags_cover = 0 
(E) (C) (M) flags_inv = null 
(E) (C) (M) flight_x_offset = 15 
(E) (C) (M) flight_y_offset = 9 
(E) (C) (M) floating = 0 
(E) (C) (M) force = 5 
(E) (C) (M) force_blueprints = 0 
(E) (C) (M) force_moving = null 
(E) (C) (M) force_string = null 
(E) (C) (M) force_string_override = null 
(E) (C) (M) gas_transfer_coefficient = 1 
(E) (C) (M) gc_destroyed = null 
(E) (C) (M) gender = "neuter" 
(E) (C) (M) glide_size = 8 
(E) (C) (M) gun_light = null 
(E) (C) (M) heat = 0 
(E) (C) (M) heat_protection = 0 
(E) (C) (M) hidden_uplink = null 
(E) (C) (M) hitsound = "swing_hit" 
(E) (C) (M) hit_reaction_chance = 0 
(E) (C) (M) holds_charge = 0 
(E) (C) (M) hooded = 0 
(E) (C) (M) hud_list = null 
(E) (C) (M) hud_possible = null 
(E) (C) (M) icon = /icon (icons/obj/guns/energy.dmi) 
(E) (C) (M) icon_state = "kineticgun" 
(E) (C) (M) inertia_dir = 0 
(E) (C) (M) inertia_last_loc = null 
(E) (C) (M) inertia_move_delay = 5 
(E) (C) (M) inertia_moving = 0 
(E) (C) (M) inertia_next_move = 45754.5 
(E) (C) (M) infra_luminosity = 0 
(E) (C) (M) inhand_x_dimension = 32 
(E) (C) (M) inhand_y_dimension = 32 
(E) (C) (M) initialized = 1 
(E) (C) (M) initial_language_holder = /datum/language_holder 
(E) (C) (M) integrity_failure = 0 
(E) (C) (M) invisibility = 0 
(E) (C) (M) in_inventory = 1 
(E) (C) (M) in_use = 0 
(E) (C) (M) isprocessing = 0 
(E) (C) (M) item_color = null 
(E) (C) (M) item_state = "kineticgun" 
(E) (C) (M) knife_x_offset = 15 
(E) (C) (M) knife_y_offset = 13 
(E) (C) (M) language_holder = null 
(E) (C) (M) last_force_string_check = 0 
(E) (C) (M) last_high_pressure_movement_air_cycle = 8632 
(E) (C) (M) last_move = 0 
(E) (C) (M) layer = 20 
(E) (C) (M) lefthand_file = /icon (icons/mob/inhands/guns_lefthand.dmi) 
(E) (C) (M) level = 2 
(E) (C) (M) light = null 
(E) (C) (M) light_color = null 
(E) (C) (M) light_power = 1 
(E) (C) (M) light_range = 0 
(E) (C) (M) light_sources = null 
(E) (C) (M) loc [mob_428] = Spends-the-Fortune /mob/living/carbon/human 
(E) (C) (M) locs = /list (1) 
1 [0x1041d1f] = the floor /turf/open/floor/plasteel
(E) (C) (M) luminosity = 0 
(E) (C) (M) maptext = null 
(E) (C) (M) maptext_height = 32 
(E) (C) (M) maptext_width = 32 
(E) (C) (M) maptext_x = 0 
(E) (C) (M) maptext_y = 0 
(E) (C) (M) master = null 
(E) (C) (M) materials = /list (1) 
$metal = 2000
(E) (C) (M) max_buckled_mobs = 1 
(E) (C) (M) max_heat_protection_temperature = null 
(E) (C) (M) max_integrity = 200 
(E) (C) (M) max_mod_capacity = 100 
(E) (C) (M) min_cold_protection_temperature = null 
(E) (C) (M) modifystate = 0 
(E) (C) (M) modkits = /list (0) 
(E) (C) (M) mouse_drag_pointer = 1 
(E) (C) (M) mouse_drop_pointer = 1 
(E) (C) (M) mouse_drop_zone = 0 
(E) (C) (M) mouse_opacity = 1 
(E) (C) (M) mouse_over_pointer = null 
(E) (C) (M) moving_diagonally = 0 
(E) (C) (M) name = "proto-kinetic accelerator" 
(E) (C) (M) needs_permit = 0 
(E) (C) (M) obj_integrity = 200 
(E) (C) (M) on_blueprints = 0 
(E) (C) (M) opacity = 0 
(E) (C) (M) orbiters = null 
(E) (C) (M) orbiting = null 
(E) (C) (M) origin_tech = "combat=3;powerstorage=3;engineering=3" 
(E) (C) (M) our_overlays = /list (2) 
1 = 
2 = 
(E) (C) (M) overheat = 1 
(E) (C) (M) overheat_time = 16 
(E) (C) (M) overlays = /list (2) 
(E) (C) (M) override = 0 
(E) (C) (M) parent_type = /obj/item/weapon/gun/energy 
(E) (C) (M) pass_flags = 1 
(E) (C) (M) permeability_coefficient = 1 
(E) (C) (M) persistence_replacement = null 
(E) (C) (M) pin [0x2017d0d] = the electronic firing pin /obj/item/device/firing_pin 
(E) (C) (M) pixel_step_size = 8 
(E) (C) (M) pixel_w = 0 
(E) (C) (M) pixel_x = 0 
(E) (C) (M) pixel_y = 0 
(E) (C) (M) pixel_z = 0 
(E) (C) (M) plane = 20 
(E) (C) (M) pressure_resistance = 4 
(E) (C) (M) priority_overlays = /list (0) 
(E) (C) (M) proximity_monitor = null 
(E) (C) (M) pulledby = null 
(E) (C) (M) randomspread = 1 
(E) (C) (M) reach = 1 
(E) (C) (M) reagents = null 
(E) (C) (M) recharge_timerid = 1.03537e+006 
(E) (C) (M) recoil = 0 
(E) (C) (M) req_access = null 
(E) (C) (M) req_access_txt = "0" 
(E) (C) (M) req_one_access = null 
(E) (C) (M) req_one_access_txt = "0" 
(E) (C) (M) resistance_flags = 0 
(E) (C) (M) righthand_file = /icon (icons/mob/inhands/guns_righthand.dmi) 
(E) (C) (M) rpg_loot = null 
(E) (C) (M) sawn_desc = null 
(E) (C) (M) sawn_state = 0 
(E) (C) (M) screen_loc = "CENTER+0:16,SOUTH+0:5" 
(E) (C) (M) secondary_flags = null 
(E) (C) (M) select = 1 
(E) (C) (M) selfcharge = 0 
(E) (C) (M) semicd = 0 
(E) (C) (M) shaded_charge = 0 
(E) (C) (M) sharpness = 0 
(E) (C) (M) siemens_coefficient = 1 
(E) (C) (M) slot_equipment_priority = null 
(E) (C) (M) slot_flags = 512 
(E) (C) (M) slowdown = 0 
(E) (C) (M) smooth = 0 
(E) (C) (M) species_exception = null 
(E) (C) (M) spread = 0 
(E) (C) (M) step_size = 32 
(E) (C) (M) step_x = 0 
(E) (C) (M) step_y = 0 
(E) (C) (M) strip_delay = 40 
(E) (C) (M) suffix = null 
(E) (C) (M) suittoggled = 0 
(E) (C) (M) suit_fibers = /list (1) 
1 = "Material from a pair of black gloves."
(E) (C) (M) suppressed = 0 
(E) (C) (M) tag = null 
(E) (C) (M) text = "p" 
(E) (C) (M) throwforce = 5 
(E) (C) (M) throwhitsound = null 
(E) (C) (M) throwing = null 
(E) (C) (M) thrownby = null 
(E) (C) (M) throw_range = 5 
(E) (C) (M) throw_speed = 3 
(E) (C) (M) tip_timer = null 
(E) (C) (M) toolspeed = 1 
(E) (C) (M) top_left_corner = null 
(E) (C) (M) top_right_corner = null 
(E) (C) (M) transform [0x21035226] = /matrix 
(E) (C) (M) trigger_guard = 1 
(E) (C) (M) type = /obj/item/weapon/gun/energy/kinetic_accelerator 
(E) (C) (M) ui_screen = "home" 
(E) (C) (M) underlays = /list (0) 
(E) (C) (M) unique_frequency = 0 
(E) (C) (M) unique_rename = 1 
(E) (C) (M) unique_reskin = null 
(E) (C) (M) upgrades = /list (0) 
(E) (C) (M) usesound = null 
(E) (C) (M) use_cyborg_cell = 0 
(E) (C) (M) vars = /list (0) 
(E) (C) (M) var_edited = 0 
(E) (C) (M) verbs = /list (2) 
1 = /obj/item/verb/verb_pickup 
2 = /obj/item/verb/move_to_top
(E) (C) (M) verb_ask = "asks" 
(E) (C) (M) verb_exclaim = "exclaims" 
(E) (C) (M) verb_say = "says" 
(E) (C) (M) verb_whisper = "whispers" 
(E) (C) (M) verb_yell = "yells" 
(E) (C) (M) visibility = 1 
(E) (C) (M) weapon_weight = 1 
(E) (C) (M) wires = null 
(E) (C) (M) worn_x_dimension = 32 
(E) (C) (M) worn_y_dimension = 32 
(E) (C) (M) w_class = 3 
(E) (C) (M) x = 0 
(E) (C) (M) y = 0 
(E) (C) (M) z = 0 
(E) (C) (M) zoomable = 0 
(E) (C) (M) zoomed = 0 
(E) (C) (M) zoom_amt = 3 
(E) (C) (M) zoom_out_amt = 0

**Comment by bgobandit** [comment] 2017-06-24 23:51
More details: I adminspawned a new PKA on the thunderdome, it didn't charge at all
Round id 72350, this happened at roughly 1 hour, 15 minutes

**Comment by Repukan** [comment] 2017-06-25 02:45
Was there freon, or forever lasting effects on station?

I think it had something to do with timer or ticker subsystems

**Comment by ChangelingRain** [comment] 2017-06-25 03:35
This is the timer subsystem but I don't know why it happens.

**Comment by Repukan** [comment] 2017-06-25 03:39
I think this used to happen too when you used recharge with a KA

Mind you this was something I noticed a long ass time ago (when we had super and hyper instead of modules.)

**Comment by bgobandit** [comment] 2017-06-25 04:27
Dumb bit of possibly irrelevant data: I went into red hunger JUST as this stopped working. I don't know what was going on on station at the time.

**Comment by WJohn** [comment] 2017-06-25 15:05
Yeah, last time this happened the timer subsystem was broke.

**Comment by Cyberboss** [comment] 2017-06-27 13:44
Dupe of #23818

**Closed by Cyberboss** 2017-06-27 13:44 UTC
