### ISSUE TITLE
Mech projectiles fire in random directions

### ISSUE THREAD

**Issue by Memesaredreams** [tgstation/tgstation#44107] opened 2019-05-23 06:15 UTC
Issue reported from  Round ID: 109023 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1468

Found with a Durand, firing the solaris laser cannon shoots in a random direction in strafing mode, sometimes shooting dead behind the mech and straight up most of the time.

**Comment by HomocidlePancakes** [comment] 2019-05-23 08:04
#44102 is related. Seems it’s not just mechs

**Comment by Altoids1** [comment] 2019-05-23 10:11
Over on Yogs, we're seeing similar bugs with disabler beams and other projectiles.

**Comment by Barhandar** [comment] 2019-05-23 10:55
@Altoids1 does Yogs run updated tg and/or latest byond?

**Comment by AnturK** [comment] 2019-05-23 12:34
This is client-side issue, 1468 messed with mouse pixel-x/y which are used to calculate projectile targets.

**Comment by AnturK** [comment] 2019-05-23 12:36
Duplicate of #44102 - This one is just more specific

**Closed by AnturK** 2019-05-23 12:36 UTC
Labels: BYOND Issue
