### ISSUE TITLE
Beepsky also can control the flow of time.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35893] opened 2018-02-22 05:43 UTC
Found this while testing on local. Beepsky is seemingly immune to the time stop spell. Not sure if this is the case on the master.

![dreamseeker_2018-02-22_00-40-34](https://user-images.githubusercontent.com/33107541/36522212-467d1ac6-1769-11e8-89ab-72715cb4ed5f.png)
![dreamseeker_2018-02-22_00-40-55](https://user-images.githubusercontent.com/33107541/36522216-4c140c88-1769-11e8-9310-ae1217ee4f6b.png)

**Comment by Ratvar** [comment] 2018-02-22 10:52
Beepsky is supreme, not a bug

**Comment by Anonmare** [comment] 2018-02-22 13:52
If you can't do the crime, don't do the time

**Comment by LetterN** [comment] 2018-02-23 11:38
[ feature ]

**Comment by YakumoChen** [comment] 2018-02-26 15:26
NO, YOU FREEZE, SCUMBAG

**Comment by Ordonis** [comment] 2018-02-27 13:41
THREE SECONDS HAVE PASSED.

**Comment by AverageJoe82** [comment] 2018-03-06 15:00
FOUR SECONDS HAVE PASSED.

**Comment by nemvar** [comment] 2019-07-21 02:03
Fixed by #42933

**Closed by nemvar** 2019-07-21 02:03 UTC
Labels: Bug
