### ISSUE TITLE
Ling, after being decapitated twice, could no longer revive

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68270] opened 2022-07-08 13:20 UTC
Reporting client version: 514.1584

## Round ID:
[186277](https://scrubby.melonmesa.com/round/186277)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:
I wasn't the ling in question this round, just making a report for them, as they don't have a github account
they were decapitated once and revived from the body just fine, growing a new head
they were then decapitated again but this time their soul followed their head instead of staying in their body to allow for another revival

**Comment by timothymtorres** [comment] 2022-07-08 22:40
Duplicate of #51408 and #58138

**Closed by timothymtorres** 2022-07-08 22:40 UTC
