### ISSUE TITLE
Ghostroles (Namely Charliestation and Free Golems) are severely hindered in research now

### ISSUE THREAD

**Issue by Palpetinus** [tgstation/tgstation#84166] opened 2024-06-20 07:37 UTC
## Issue Summary

Due to the changes in research by #84024 you now NEED ordnance for a lot of the tech, like a third of the entire tech tree. Ghost role locations don't have ordnance and no way to make an ordnance setup.

## Round ID:

Irrelevant, but 230843 I suppose

## Testmerges:
Also irrelevant but:
#83227
#84003

## Reproduction:

As mentioned, due to the changes made in #84024, a lot of the tech tree now needs experiments to be done as a hard requirement. Some of the experiments need ordnance (the simplest being Plasma Gas Shells), some need other players (like Human Field Research: Augmented Organs) and some are very tedious to do for golems and charliestation, like having to build at least 8 machines for T2 scans, a problem the main station doesn't suffer from due to having all departments fully stocked with their machines. 
Both Charlie and Free Golems have absolutely no way of getting an ordnance setup. Trust me, I have searched high and low to find an ordnance disk; at best you can do the gas compression, but you're not able to publish papers. The new tech tree is entirely station-centric, which can also be seen nicely by doing the "Experimental Dissection" on Charlie giving you 2500 research points. Yes, still. 

To add a little bit of conjecture because no oversight report would be complete without it: this is why required experiments were removed a while back. Nobody likes to make BZ, nobody likes to fiddle with some cans for essential station equipment and others literally can't do these things. I don't know why #84024 - a change that affects literally everyone severely - was merged without a testmerge first or at least without making sure that everything works 100%, but it has made Charliestation and Free Golems far less enjoyable and in some aspects downright impossible to play.

**Comment by MTandi** [comment] 2024-06-20 09:34
There are no oversights, please explore the game. Added ntnet relay to #84086 for convenience, but it was doable on Charlie regardless - there is a modular console on Beta Station.

>Some of the experiments need ordnance (the simplest being Plasma Gas Shells), some need other players (like Human Field Research: Augmented Organs) and some are very tedious to do for golems and charliestation, like having to build at least 8 machines for T2 scans, a problem the main station doesn't suffer from due to having all departments fully stocked with their machines.

There are plenty of machines on Charlie and the Golems have some machines too. Also the number is reduced to 4 in #84086.

>Both Charlie and Free Golems have absolutely no way of getting an ordnance setup. Trust me, I have searched high and low to find an ordnance disk; at best you can do the gas compression, but you're not able to publish papers.

You don't need ordnance for experiments. The disks were always available in the imprinter. And I've added NTNet relay to away imprinter. You have the compressor, you can make the plasma gas by grinding plasma material and heating it up. BZ is doable too. But you don't have to do BZ, since it locks advanced tools and HFR. 

>Field Research: Augmented Organs

Why would you need this tech on Golems? It's doable on Charlie when you have buddies. If you don't, then xenobiology, or  you can't do any surgery anyway.

>Nobody likes to make BZ

Then don't do it. It doesn't lock anything crucial, live without the HFR and advanced tools.

> nobody likes to fiddle with some cans for essential station equipment and others literally can't do these things.

Why do you need to research parts if you have no machinery? What are you gonna use them for? Just don't do it then.

>but it has made Charliestation and Free Golems far less enjoyable and in some aspects downright impossible to play.

False statement. Charlie has a plasma tank, modular computer and all the resources. Please let me know which experiment you have problems with.

Summary: This is not an issue. All experiments are doable, and ghostroles can just skip those they find troublesome to do, since the branches are now specialized.

**Comment by Palpetinus** [comment] 2024-06-20 19:14
> But you don't have to do BZ
> Why would you need this tech on Golems?
> Then don't do it
> Just don't do it then.

So your entire answer to "things are really to do now unless you know 100% of the mechanics of the game" is just "lmao don't do it"? Am I getting that one right?

**Comment by MTandi** [comment] 2024-06-20 20:34
> So your entire answer to "things are really hard to do now unless you know 100% of the mechanics of the game" is just "lmao don't do it"? Am I getting that one right?

Essentially, yes. These nodes are not mandatory on ghost roles, there are plenty of other things to research and play with.

But because some of the experiments are hard to do, you have something to explore and figure out. Take this as a challenge, not as an issue. 

The experiments don't require 200 IQ, you just need to connect the puzzle pieces if you want to unlock certain nodes now. Once you figure it out, it won't be a mystery.

If bursting a plasma tank is a challenge to you, I don't know what you're going to do with HFR.

**Comment by Palpetinus** [comment] 2024-06-20 21:47
The issue is that a veteran player knows all these things (and still finds them tedious), but a new player won't know to print a NT relay, get to the modular computer, download a specific program, build a machine, get plasma into a tank, setup a small ordnance setup (connect ports to the machine), print/get a data disk, fill a tank with gas to be able to get the tank to burst, do the experiment, upload it to the disk, get the disk to the PC and publish a paper.
All to print a god damn _plasma cutter_.

The point is not how things are now, the point is that _compared to previously_ a lot of items and tech feels nigh unobtainable now, _especially_ since shifts are just barely long enough to get the station running. As someone who used to play Charliestation a lot and almost never seeing anyone else playing on it, this is just the final nail in the coffin for Charlie.

**Comment by MTandi** [comment] 2024-06-20 21:55
You have the modular console on Charlie, install an app on it, it doesn't need NTRelay. 

We discuss how to simplify things.

I've already made the Compressor and Paper Publisher UIs more user-friendly, added hints here and there, simplified some experiments. Please try playing with the recent changes.

We consider to get rid of the Paper Publishing software as it is indeed not very intuitive, or improve it in some way, like making it upload from disks, but we do this gradually.

See my playthrough on YouTube, I mined the whole Charlie with the mod suit drill even before TechTree changes. Search for alternatives for what you need. This is a sandbox game.

**Comment by Palpetinus** [comment] 2024-06-20 22:11
> This is a sandbox game.

And taking away options limits that exact aspect.
It's not that mining is hard, that part even got easier since you can print an upgraded resonator earlier. I could compile an entire list of things that got harder to do though, and if things keep getting more and more difficult over time, power being another thing that got a lot harder to manage on Charlie recently, thing will lead to necessary metas forming and the sandbox aspect vanishing into the background. 

> You have the modular console on Charlie, install an app on it

And where does the app come from? You don't have a connection to NTnet, which you need to download apps, unless you've gotten very lucky and spawned with the bunker ruin on the same z-level which has a full telecomms setup. 

> We consider to get rid of the Paper Publishing software as it is indeed not very intuitive

It's entirely unnecessary. The difficulty in the process is getting the conditions for the experiments right, whether that's a specific explosion or a specific required gas. Anything between the experiment being done and the experiment being validated for the techweb is entirely unnecessary fluff that doesn't exist anywhere else in the game, from scanning machines with the experiscanner to destructive scans for for example botany.
To put it into perspective, let's take botany experiments. You need to get a specific plant, put it in a machine, select the experiment and you're done.
Compare that to the plasma gas shells. You need a plasma can and put it in a machine. That part is straightforward and simple, but after that you need to insert a disk, upload the data, eject the disk, carry it to a PC, install the ordnance program on that PC (which it doesn't have roundstart because..???), upload the data to the PC, open the program and publish a paper. You now have to do this about 5 more times (Low-Yield, High-Yield, Reactionless, BZ shells, N2O shells to name all the simple ones) to get all the experiments done for the station. That's about 20 minutes of effort you now _have_ to do _every single shift_ compared to it being optional previously.

**Comment by Sadboysuss** [comment] 2024-06-22 10:32
This is a design choice and technically not a bug or oversight. You may talk to MTandi some more to see if there is anything that could be done to address your concerns

**Comment by SyncIt21** [comment] 2024-06-24 03:09
@Sadboysuss please add a clean up flag as well to this so it auto closes within 7 days. We have too many open issues at the moment

**Comment by MTandi** [comment] 2024-06-28 23:47
Will be partially resolved in #84379

**Closed** 2024-09-08 14:01 UTC
Labels: Not a bug, Cleanup Flagged
