### ISSUE TITLE
bioscrambler + MI-GO = FUUUUCKED

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#81257] opened 2024-02-03 03:36 UTC
Reporting client version: 514.1589

## Issue Summary
REALLY BIG FUCK, the biomscrambler belt (at least when used on a MI-GO corpse) will stop you from controlling the morph, and also completely disconnect your ghost from your body once you die, so if you get killed to fix it, you will be soulless, and you will be FUCKED

## Round ID:
[223261](https://scrubby.melonmesa.com/round/223261)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

![image](https://github.com/tgstation/tgstation/assets/130595499/13fb3588-bb36-462f-8fd3-521a344d926d)

**Comment by Jacquerel** [comment] 2024-02-03 17:28
I am having trouble reproducing this, did anything else notable happen before or during this issue?

**Comment by Admiral-Gigaton** [comment] 2024-02-05 02:15
> I am having trouble reproducing this, did anything else notable happen before or during this issue?

Let's see... I pulled it off a corpse of an RD who suicides, I was on a shuttle at the current time (not in transit) I have ninja katana, we just visited the meat lab though nothing happened as the previous guy already robbed it... otherwise nothing special? Oh and I was det

**Comment by Sadboysuss** [comment] 2024-08-06 12:25
unable to reproduce, please reproduce the issue with a video or new reproduction steps, this will be auto-closed in 7 days otherwise

**Closed** 2024-09-09 00:18 UTC
Labels: Needs Reproducing, Cleanup Flagged
