### ISSUE TITLE
Going downstairs removes your cultist icon

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#70731] opened 2022-10-22 08:25 UTC
I got converted to cult on Icebox, the events leading to realizing this bug went roughly as follows:

1) Started on main station layer
2) Lured downstairs, converted to cult, went back up
3) At some point while I had meson goggles on, I went back downstairs and when I went back UP, I realized that my cult icon disappeared. Not just for me, but for other cultists as well. This led to two hilarious situations where a cultist tried to funnyhand me and was really confused as to why it wasn't working.
4) Every time I went downstairs, the cult icon reappeared. Every time I was on main station layer upstairs, it disappeared. I did not make it all the way to bottom layer to see what happens there.
5) Near round end while sitting on the shuttle, I also discovered that taking off my meson goggles made my cult icon reappear when on the main station layer, disappearing again when I put them back on.

I only put the meson goggles on when I got the "your eyes are glowing red" announcement, but I can not say for certain if the bug was indeed related to having my eyes covered or if it was present already before that.

Being unable to tell who is your cultist friend makes playing cult a little bit impossible.

## Round ID:
[192784](https://scrubby.melonmesa.com/round/192784)

## Testmerges:
https://github.com/tgstation/tgstation/pull/70409

## Reproduction:
Be on Icebox, be a cultist, walk downstairs and back up, wear meson goggles, experiment.

**Comment by JohnFulpWillard** [comment] 2022-10-22 10:16
this is a lot more obvious with admin hud enabled

**Comment by msgerbs** [comment] 2022-10-22 22:13
I believe this is technically a duplicate of #68087. That issue doesn't specify but the map on that round was Ice Box and I believe it's been known for a while that antag huds are broken when moving between z-levels.

**Comment by Mooshimi** [comment] 2022-10-25 16:23
> I believe this is technically a duplicate of #68087. That issue doesn't specify but the map on that round was Ice Box and I believe it's been known for a while that antag huds are broken when moving between z-levels.

So right,
Duplicate of #68087

**Closed** 2022-10-25 16:24 UTC
