### ISSUE TITLE
You can flip up the welding helmet while welding and avoid eye damage

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#28728] opened 2017-06-23 04:37 UTC
By flipping the helmet down, starting to weld, and flipping it back up, you can weld without damaging your eyes while also foregoing the reduced vision of the helmet.

**Comment by Sligneris** [comment] 2017-06-23 04:41
Can't we just make it so that they eye damage gets applied over time, each time with eye protection check, instead of the instant you click on anything with a lit welder, anyway?

**Comment by dannno** [comment] 2017-06-23 04:53
That would make more sense.

**Comment by ShizCalev** [comment] 2017-06-23 18:07
dupe #15472

**Comment by AnturK** [comment] 2017-07-23 12:43
Duplicate of #15472

**Closed by AnturK** 2017-07-23 12:43 UTC
Labels: Consistency Issue
