### ISSUE TITLE
Liberated Golems have severe issues with airflow

### ISSUE THREAD

**Issue by Imagebard** [tgstation/tgstation#18710] opened 2016-06-18 14:51 UTC
Every time a ash storm starts, the air is reset, right?
Well it so happens that this causes you have giant amounts of airflow going out of the ship whenever you open it after a ash storm. You have metals and shit flying around out of the ship. Same for Ash Lizards.

Not sure if lavaland botany has the same issue because I didn't test, its possible that it doesn't because of the tiny fan.

**Comment by PKPenguin321** [comment] 2016-06-18 19:25
tiny fan mvp

**Comment by ChangelingRain** [comment] 2016-06-18 19:36
That PR didn't get merged.

**Comment by Imagebard** [comment] 2016-06-18 19:51
Well, I got airflow issues still exist regardless. Will probably get worse once it is.

**Comment by optimumtact** [comment] 2016-06-20 06:34
This is not a bug and should go on the feedback forums

**Closed by optimumtact** 2016-06-20 06:34 UTC
