### ISSUE TITLE
pre-set glass floors being pried makes a empty tile (some shit like that idk)

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#65323] opened 2022-03-07 07:40 UTC

**Comment by timothymtorres** [comment] 2022-03-07 21:05
There is different behavior between the mapping glass floors and the ones you can make as material tiles. One of these spawns plating when it is crowbarred and the other creates openspace. (the one Serxule is talking about I believe)  One also has any piping related undertile stuff appear on top of the glass and the other hides it like normal floor tiles.

It would be nice if you could share screenshots of this behavior @Serxule

**Comment by MrMelbert** [comment] 2022-03-07 21:16
Dupe of #63868

**Comment by optimumtact** [comment] 2022-03-07 22:21
yeah it is.

**Closed by optimumtact** 2022-03-07 22:21 UTC
Labels: Bug, Consistency Issue
