### ISSUE TITLE
Meson module in engiborg turns non visible tiles to spess tiles and can't be turned off.

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#30510] opened 2017-09-08 06:40 UTC
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Round ID: 75843 (I am reporting this after the end of the round I meant to do it, so its not this one but the one that happened before in Basil)

This happened multiple times to me, but I'm unsure if its on my end or on yours.

I played engiborg a few times, and everytime I put the meson module on, it never gets turned off. Not only that, but any tiles I should see as dark/shadow/not seeing anything behind turns into a space tile. I tried putting the mesons back in storage, using the module (with y, hotkeys on) and reconnecting.

Its not something too big, but it is jarring to me, look into it if you can.

Note: I'm using the stable version of BYOND and not the beta as is recommended somewhere in the forums or wiki or something, I don't know, that may be it

**Comment by ShizCalev** [comment] 2017-09-08 06:56
Duplicate of #29589, #28296, #26918, #29521

**Comment by TerceraPosicion** [comment] 2017-09-08 07:13
Shiet, sorry for not checking if it was already reported.

Is it an issue then? or an intended feature?

**Comment by ShizCalev** [comment] 2017-09-08 08:43
Issue.

**Closed** 2017-10-01 20:15 UTC
Labels: Bug
