### ISSUE TITLE
TEG parts cannot be rotated

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#40666] opened 2018-10-03 00:43 UTC
[Round ID]: 94829

[Testmerges]:
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit 7cdd61c1ed 
#40662: 'Stops using the rad insulation component to provide default rad insulation features in order to save a bit of memory' by vuonojenmustaturska at commit 69989a1790 
#40665: 'Revert "Improve youtube-dl subsystem (#40396)"' by subject217 at commit e2d232b3a5 
[Reproduction]: 
build teg parts (circulator)
says alt click to rotate
no alt click rotation

**Comment by ShizCalev** [comment] 2018-10-03 00:49
Duplicate of #40634

**Closed by ShizCalev** 2018-10-03 00:49 UTC

**Comment by Barhandar** [comment] 2018-10-03 08:49
Alt click actually should still work for location.
