### ISSUE TITLE
ethereals will ethereal revive with their head missing, replacing the head but not reinserting the soul

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#78635] opened 2023-09-27 12:35 UTC
Reporting client version: 514.1589

## Round ID:
[215473](https://scrubby.melonmesa.com/round/215473)

## Testmerges:
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [adds boxes of bandages, and bandages to go in them](https://www.github.com/tgstation/tgstation/pull/78406)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/e345cd50-592b-4c28-bf9d-c8141d7bcafa)
![image](https://github.com/tgstation/tgstation/assets/12635164/d260c305-758d-47cb-a32c-e8ddc8f4dfdf)
pictured: my body reviving without my head
pictured: seconds later my living body, which I cannot enter, with a fresh new head
reenter corpse will take me to the decapitated head
que?
![image](https://github.com/tgstation/tgstation/assets/12635164/aa8309be-3e05-4530-899e-f665c1155a9e)
examining both

**Comment by Profakos** [comment] 2023-09-28 07:51
Duplicate of #73514

**Comment by Sealed101** [comment] 2023-09-28 14:08
^

**Closed by Sealed101** 2023-09-28 14:08 UTC
