### ISSUE TITLE
Ashwalkers can't talk

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29762] opened 2017-08-07 06:21 UTC
Recent Basil round, ashwalkers who spoke would only see speechbubbles above their head to indicate this. Nothing actually was spoken; no "you hear someone talking" like deafness, no nothing.

**Comment by AnturK** [comment] 2017-08-09 07:01
Duplicate of #29776

**Closed by AnturK** 2017-08-09 07:01 UTC
