### ISSUE TITLE
Foam staying permanently

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29118] opened 2017-07-07 15:14 UTC
That has been there for ten minutes. We're 2hr 15 min into the round so possibly related, I've seen issues where the game doesn't run as well after a couple hours. 

https://file.house/unbl.png

**Comment by Cyberboss** [comment] 2017-07-07 15:41
Dupe of #23818

**Closed by Cyberboss** 2017-07-07 15:41 UTC
