### ISSUE TITLE
Paralax texture. background issue. Crash & lag.

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#38917] opened 2018-07-04 20:02 UTC
Issue reported from Round ID: 90486 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

 Whenever i turn on paralax, which i found today, there'll be big white, pixelated spot's on the background. Tried reverting back to 1429 and clearing cache, nothing has been fixed.
https://gyazo.com/537124e5eb1d71e4241311ec9da791d9
Not only is this the issue but i have been constantly lagging and crashing in the TG servers, in other servers i haven't been crashing and connection works fine, so im believing its a TG issue with me and the server and probably windows blocking something, very sure because my old laptop was borked a few days ago, windows 7, and the gameplay was very fine, no crashing in TG, now in this laptop with windows 10 it constantly crashes and lag. Im pretty sure the only person with this issue.
EDIT:The lag and white spots has been happening the past few days till i started using this new laptop.

**Comment by SpaceManiac** [comment] 2018-07-05 05:54
Try updating your graphics drivers

**Comment by bigfatbananacyclops** [comment] 2018-07-05 07:09
@SpaceManiac  Updated graphics drivers, still got those big white spots.

**Comment by bigfatbananacyclops** [comment] 2018-07-05 23:06
EDIT: I tested oracle station, which has Paralax too, i have the same issue there too, white spots.

**Comment by yoyobatty** [comment] 2018-07-06 02:19
This sounds crazy but try restarting your computer, sometimes graphics drivers will silently fail and cause issues like this.

**Comment by bigfatbananacyclops** [comment] 2018-07-06 02:21
@yoyobatty  Wont work, i have this every day, every time i play TG, i also had to restart my laptop when i was updating graphic drivers

**Comment by Jalleo** [comment] 2018-07-06 16:33
NVIDIA or AMD card type? @MrStonedOne

**Comment by bigfatbananacyclops** [comment] 2018-07-07 18:14
EDIT: I found another bug which also isnt normal, in the darkness, wearing mesons, i see this shadow circle around me.
https://i.gyazo.com/thumb/1200/ed6c63741e122040598c3e5bce329c68-png.jpg

**Comment by MrStonedOne** [comment] 2018-07-08 04:49
please post your shader-debug in this forum thread http://www.byond.com/forum/?post=2382060#comment24207533

**Comment by bigfatbananacyclops** [comment] 2018-07-08 17:45
@MrStonedOne  Done. thanks

**Comment by bigfatbananacyclops** [comment] 2018-07-30 02:38
I still have no solution to the bug on my paralax, please i beg for some help.

**Comment by Dennok** [comment] 2020-02-24 11:19
Still issue?
I think it can be fixed by update of BYOND version.

**Comment by timothymtorres** [comment] 2021-08-24 11:39
Duplicate of #24782

**Closed by timothymtorres** 2021-08-24 11:39 UTC
Labels: Bug, BYOND Issue
