### ISSUE TITLE
An interrupted ollie will set and never unset `BLOCK_Z_OUT_DOWN` on the "vehicle"

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#67557] opened 2022-06-05 23:55 UTC
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/172075797-3ec62d2b-7c43-4797-a963-b54e330c8a23.png)

Ollies will set `BLOCK_Z_OUT_DOWN` on the vehicle of choice when it initiates. 

However, if the ollie is interrupted for some reason - like crashing - the action will early return and, as a result, leave `BLOCK_Z_OUT_DOWN` set. 

This means you can use the vehicle over openspace and not fall.

**Comment by timothymtorres** [comment] 2022-06-06 00:44
Duplicate of #61437

**Closed by timothymtorres** 2022-06-06 00:44 UTC
Labels: Bug
