### ISSUE TITLE
Space ninjas dont get a space insulated suit and start dying 

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation#49415] opened 2020-02-17 19:52 UTC
## Round ID:
130430

## Testmerges:

#48579: 'Port of Replays from Yogstation' by actioninja at commit 69e734d65e
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49370: 'Revert "Random mineral spawning (mostly) no longer change turfs"' by tralezab at commit 99a680ec41
#49274: '[READY]The Families Gamemode. Home. At least it was 'till I fucked everything up.' by Iamgoofball at commit f320129d4e

## Reproduction:

Spawn in as a ninja in spess
Start dying to the cold

**Comment by Tharcoonvagh** [comment] 2020-02-17 21:31
doop

**Comment by nightred** [comment] 2020-02-17 23:10
oh um i will get this added to the fixes i have running.

**Comment by Couls** [comment] 2020-02-18 17:46
dupe of #49381

**Closed** 2020-02-18 18:18 UTC
