### ISSUE TITLE
interfaces sometimes break and cant be opened anymore

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38695] opened 2018-06-24 09:46 UTC
if you click too fast, or open and close a window there is a chance of the interface not being able to be opened until you relog  happens for computers, dispensers, any machine that opens an interface on click 
if it breaks for 1 machine other machines work fine

**Comment by DaxDupont** [comment] 2018-06-24 10:53
This also happens with admin interaction and closing an air alarm and reopening it.

**Comment by zaracka** [comment] 2018-06-24 12:04
This is true, but not currently reproducible. I have no idea what causes it.

**Comment by MrStonedOne** [comment] 2018-06-24 20:06
@neersighted 

This seems to only happen with tgui interfaces, It's likely a case of tgui thinking the window is open when its not.

**Comment by Cyprex** [comment] 2018-06-24 20:06
I was able to fix (most of?) these cases by moving out of range of the machine to the point where the gui would automatically close. For tablets, that meant putting them into a backpack.

**Comment by SpaceManiac** [comment] 2018-06-24 21:57
Duplicate of #35714

**Closed** 2018-06-25 06:32 UTC
