### ISSUE TITLE
ascended knock heretics lose access to all of their spells while human apart from ascended shapechange after using it

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#79713] opened 2023-11-13 21:56 UTC
Reporting client version: 514.1589

## Round ID:
[218720](https://scrubby.melonmesa.com/round/218720)

## Testmerges:
- [Adds more bitrunning antagonists + fixes (READY)](https://www.github.com/tgstation/tgstation/pull/79522)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

**Comment by Profakos** [comment] 2023-11-14 11:39
Duplicate of #79525

**Closed** 2024-02-14 00:02 UTC
Labels: Bug
