### ISSUE TITLE
Wall igniters failing to ignite gasses in the toxins burn chamber.

### ISSUE THREAD

**Issue by Isy232** [tgstation/tgstation#41670] opened 2018-11-25 02:46 UTC
I have done toxins quite a few times and have found that the wall igniters almost always fail to ignite the gasses inside the burn chamber. There are wall igniters on meta and box station. The floor igniters on delta station work however and I have never seen them take more than 3 tries to ignite the burn mix when the wall igniters take up to hundreds. I think it would only require a small change to fix, but it is very annoying.

**Comment by improvedname** [comment] 2018-11-25 02:57
Its a issue with the sparks

**Comment by Barhandar** [comment] 2018-11-25 14:42
Dupe of #41647 and it's an issue with sparks all right.

**Closed** 2018-11-25 23:38 UTC
