### ISSUE TITLE
Syndicate comms agent cam can see the syndicate shuttle's light fixtures, despite having no vision there.

### ISSUE THREAD

**Issue by DingleFlop** [tgstation/tgstation#36351] opened 2018-03-12 03:54 UTC
Issue reported from  Round ID: 84830 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Round ID]: # 84830
https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # Probably not caused by testmerged content.

[Reproduction]: # Move nukeops shuttle to a known location, use the syndicate comms agent camera console to view that area. The light fixtures and lighting will change as you move through it, even if the console should have no vision of that area.

**Comment by Jalleo** [comment] 2018-03-13 21:56
@deathride58 this to do with your light layer reworks?

**Comment by DingleFlop** [comment] 2018-03-18 00:02
As a followup, this works with the syndicate comms agent cam on ANY out-of-cam-view light fixtures.

**Comment by Jalleo** [comment] 2018-03-22 20:36
Can someone confirm this is the same woth the AI?

**Comment by YPOQ** [comment] 2018-03-23 03:49
Not able to reproduce on 63c226ae693386f1e2b03919e7d01eb5dd878870
Possibly fixed by #36383

**Closed** 2020-07-19 14:07 UTC
Labels: Bug, Needs Reproducing
