### ISSUE TITLE
Escape-Pod Recovery Ship Bridge Access

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#74676] opened 2023-04-12 06:43 UTC
## Reproduction:

What is says on the tin, the Recovery Ship got remade here #74257.
Unlike it's predecessor, the Bridge of this ship does not require CentCom access to enter. Considering the big vault doors designed to keep undesirables out, this seems like an oversight.

**Comment by Jacquerel** [comment] 2023-04-12 10:08
What’s the benefit to it working the way you propose, other than that it used to? What’s in there that is worth protecting, and why is it better to have less of the fluff map accessible?

**Comment by msgerbs** [comment] 2023-04-19 00:32
Going to close this as not a bug, I don't see any reason the map you can only get to at round end needs protecting and a maintainer seemingly agrees it's not a problem.

**Closed by msgerbs** 2023-04-19 00:32 UTC
Labels: Not a bug
