### ISSUE TITLE
AI chamber foam dispensers spew only 1 tile of foam

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71096] opened 2022-11-05 12:50 UTC
Reporting client version: 514.1589

## Round ID:
[193759](https://scrubby.melonmesa.com/round/193759)

## Testmerges:
- [Remove ELEMENT_DETACH on everything that doesn't need it, rename to ELEMENT_DETACH_ON_HOST_DESTROY + a PSA (about 0.2s init time savings)](https://www.github.com/tgstation/tgstation/pull/70972)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [JSON Savefiles | Player Saves use JSON](https://www.github.com/tgstation/tgstation/pull/70492)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:

1. Be AI
2. attempt to use AI chamber foam dispensers to slip intruders
3. 1 tile foam

**Comment by timothymtorres** [comment] 2022-11-05 13:35
Duplicate of #68441

**Closed by timothymtorres** 2022-11-05 13:35 UTC
