### ISSUE TITLE
Multiver doesn't heal toxin damage in the stomach

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#54816] opened 2020-11-05 10:59 UTC
## Round ID:
//////

## Testmerges:
////// NO TESTMERGES OK

## Reproduction:
Drink some lovely toxin.
Take a multiver tablet (some starting in the chem fridges roundstart in Metastation).
Nothing happens apart from your lungs don't feel too good.

Alternatively, inject some lovely toxin.
Inject multiver into you straight after.
Watch as the toxin is purged from your blood and toxin damage is healed.

^^Edited due to comments.

**Comment by nightred** [comment] 2020-11-05 16:23
Toxins in the stomach are not purged by design.

**Comment by brotherbeyondd** [comment] 2020-11-05 21:31
Theres a new stomach testmerge? No, no test merge. If toxins in the stomach arent purged by design maybe the design needs to change??

**Comment by nightred** [comment] 2020-11-05 22:43
the stomach pump surgery is able to be done on living mobs for this reason.

**Comment by brotherbeyondd** [comment] 2020-11-05 23:26
So uh, why is multiver in pill form?

**Comment by Winterous** [comment] 2020-11-05 23:56
It still WORKS when taken as a pill, just that chemical purging reagents only purge the bloodstream, not the stomach.

**Comment by brotherbeyondd** [comment] 2020-11-06 00:36
No, it doesn't heal toxin damage when taken as a pill whilst it DOES heal toxin when injected.

**Comment by Winterous** [comment] 2020-11-06 09:25
Oh my god you're right; that's a serious issue.
Multiver only checks the mob's blood for medicines, NOT their stomach; without any medicines in their blood, it doesn't heal any toxin damage whatsoever.

This would be fixed by the stomach contents -> blood contents change, @nightred but currently it's an issue that ought to be fixed, somehow.

**Comment by brotherbeyondd** [comment] 2020-11-06 11:53
Oho cos before multiver counted as one of the medicines so it healed 0.5! I'm a genius you don't have to tell me don't worry.

**Closed** 2020-11-14 03:28 UTC
Labels: Not a bug
