### ISSUE TITLE
Trashbags attached to Janicards wont accept trash

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#84867] opened 2024-07-10 23:50 UTC
Reporting client version: 515.1637

## Issue Summary

When you attach trash to a Janicart (Pimpin' ride), you cannot put trash inside. Trashbags still work properly as long as it's not attached to the Janicart.

## Round ID:
[231929](https://scrubby.melonmesa.com/round/231929)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: Loads icon refs at boot](https://www.github.com/tgstation/tgstation/pull/84853)

## Reproduction:

1. Get trashbag
2. Attach the trashbag onto the Janicart (Pimpin' Ride)
3. Attempt to put trash in the cart's bag and cry

**Comment by 00-Steven** [comment] 2024-07-11 00:28
Seems to be a duplicate of #84653.

**Closed** 2024-07-13 05:24 UTC
