### ISSUE TITLE
Donut Station Space Bug

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#49666] opened 2020-03-02 08:39 UTC
Issue reported from  Round ID: 131347 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Apparently you can fly to the "top" layer of the new donut station map from space, but you can't fly out, you are forced to enter the station if you want to head back to another layer.

**Comment by MMMiracles** [comment] 2020-03-04 11:46
Sounds like an issue with the map traits, which is weird considering the crosslink traits are set in the .json file.

**Comment by Dennok** [comment] 2020-03-04 14:06
You can use move up/down verb to change level with no station.

Its strange think, seems like all set right and last test (before map PR merge) by map test verb show correct crosslink.

**Comment by EOBGames** [comment] 2020-11-01 18:15
duplicate of #50027

**Closed by EOBGames** 2020-11-01 18:15 UTC
Labels: Needs Reproducing
