### ISSUE TITLE
Changelings can't open mail addressed to the person they're disguised as

### ISSUE THREAD

**Issue by VioletN** [tgstation/tgstation#68439] opened 2022-07-15 05:06 UTC
## Reproduction:

1. Become a changeling.
2. Transform into someone.
3. Get given mail addressed to the person you're disguised as.
4. Try to open it. Fail, because "that would be illegal!"
5. Cry.

This technically isn't a bug, but it does feel like a bit of an oversight. In the round in question, I had stealthily absorbed someone in maint and transformed into them, and it was a bit awkward being handed mail and then being unable to open it. (The implication that changelings are fine with murder but draw the line at mail fraud is very funny.) Fortunately no one I was playing with knew about this, and they wouldn't be the type of people to metagame with this information anyway, but it does feel like something that's undesirable to keep in the game, especially since you can steal every _other_ part of a person's identity.

**Comment by timothymtorres** [comment] 2022-07-15 05:28
Relevant code:

https://github.com/tgstation/tgstation/blob/4a35cfb49e0ddc8c48bf310ab50d6a375db905b5/code/game/objects/items/mail.dm#L111-L118

**Comment by LemonInTheDark** [comment] 2022-07-16 05:00
If people are using it as a ling test, we'd want that to be solved by admins rather then us.
It's a very niche thing, and solving it means losing some behavior that we don't want.

See https://discord.com/channels/326822144233439242/326831214667235328/997471402749870121 from oranges

**Comment by timothymtorres** [comment] 2022-07-18 02:49
Maintainers have talked about it and decided it should be something the admins should handle.  Marking it as `Not a bug` and it will auto close in 7 days.

**Closed** 2022-07-26 00:19 UTC
Labels: Not a bug, Cleanup Flagged
