### ISSUE TITLE
Deafening catpeople removes radio access

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#42599] opened 2019-01-30 09:34 UTC
Round ID: 101090 (Basil)
Testmerges: None

- Reproduction: As a catperson, be deafened, typically with a flashbang or something else, your earpiece-radio will cease to function afterwards, though im not sure if its just relative to myself that i can hear but not transmit messages. 

This bug is extremely inconvenient for anybody playing legacy felenids, and doesn't pertain but definitely adds to the difficulty of playing the race. One instance of being deafened and you're excluded from partaking in the chatter of the round.

**Comment by DaxDupont** [comment] 2019-01-30 10:41
are you sure it's not just the hearing damage, it lasts for a long while

**Comment by FantasticFwoosh** [comment] 2019-01-30 14:48
All other sound was working normally. I could hear radio-chatter messages clearly through the ear-piece and i checked my radio thoroughly turning it off and on and even attempting to switch with another ear-piece with no change to the situation. Neither departmental or general communications worked on my end with ; or :h inputs into the text box.

**Comment by wesoda25** [comment] 2019-01-31 15:37
Feature

**Comment by Cyprex** [comment] 2019-01-31 16:07
Go map permabrig so it's actually usable wesoda

**Comment by wesoda25** [comment] 2019-01-31 17:18
Catmain identified

**Comment by kriskog** [comment] 2019-11-15 00:46
As a cat main I havent seen this once in the past year. Potentially caused by a radio implant? Either way, cant repro, closing this.

**Closed by kriskog** 2019-11-15 00:46 UTC
Labels: Bug, Needs Reproducing
