### ISSUE TITLE
Wood is invisible.

### ISSUE THREAD

**Issue by SnekMcSnek** [tgstation/tgstation#31361] opened 2017-10-06 00:57 UTC
Issue reported from Round ID: 77040 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Wood cannot been seen, has no sprite or something.

**Comment by Repukan** [comment] 2017-10-06 01:38
I'll show you some wood

**Comment by SnekMcSnek** [comment] 2017-10-06 01:44
I want your wood.

**Comment by ShizCalev** [comment] 2017-10-06 03:22
Duplicate of #31360

**Closed by ShizCalev** 2017-10-06 03:22 UTC
