### ISSUE TITLE
Both Kilo and Tram White Ships are stuck on hyperspace Z-level

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#63239] opened 2021-12-03 21:12 UTC
Reporting client version: 514.1569

## Round ID:
[174132](https://scrubby.melonmesa.com/round/174132)

## Reproduction:

1. Roll or force Kilo or Tram whiteship
2. Observe the ship - it is in hyperspace.
3. Console is also in an error state.
It's likely caused by invalid dock setup.
Recommended fixes are:
Kilo: Replace the ship. I expect NO compatible dock designs for it.
Tram: Rotate it to face to the right. Also add a new airlock for it to dock to the station with.

![image](https://user-images.githubusercontent.com/80979251/144673459-0a0d5c96-0162-4d3f-b5be-375be8fc8511.png)

Sidenote:
Tram whiteship can also randomly despawn, this needs investigating
Another image of kilo whiteship for context:
![image](https://user-images.githubusercontent.com/80979251/144673899-b269f39b-e205-4543-a48c-958379937b68.png)

**Comment by newfren** [comment] 2021-12-05 05:29
Sometimes the ship isn't there at all. I've observed rounds, checked the teleport list for "abandoned ship bridge" or whatever and tried to teleport to it, which just throws an error. ALSO, the ships used to be in hyperspace during actual rounds and they still had gps signals, but recently I haven't seen a gps signal in the hyperspace z, just a lack of white ship.

**Comment by Addust** [comment] 2021-12-05 19:34
That happens mainly with tram whiteship or on rounds where they just don't spawn at all.
I've still had those gps-Z-12 instances though

**Comment by Mooshimi** [comment] 2021-12-06 16:22
Dupe of #60959

**Closed by Mooshimi** 2021-12-06 16:22 UTC
Labels: Bug
