### ISSUE TITLE
Cable Coil Disappearing after adding more cables

### ISSUE THREAD

**Issue by Dastion** [tgstation/tgstation#23772] opened 2017-02-06 05:51 UTC
PR Number?: 0d3cb5fcaf81f5bb54982afee46d9c649c77a607 

Cable coil (pink) appears to disappear sometimes when adding new cables of the same color to it. Was a drone when this happened.

**Comment by PKPenguin321** [comment] 2017-02-06 05:52
dupe of https://github.com/tgstation/tgstation/issues/23651

**Closed** 2017-02-06 08:26 UTC
