### ISSUE TITLE
Odd output of say messages containing * characters

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#80315] opened 2023-12-14 12:23 UTC
## Reproduction:

Press T and say `Yeah that does not seem *right* at all`
The output in chat is as follows: 
Travis Kanaga Yeah that does not seem , "Right* at all"

`testing something *fusdireid test` becomes `Travis Kanaga testing something , "Fusdireid test"`
I'd expect a normal say- i. e. Travis Kanaga says: "testing something *fusdireid test* "

Pressing M to pull up a Me prompt behaves normally- messages are printed to chat exactly as entered, without any odd transformations

This seems fairly odd- *fusdireid is obviously not a valid emote, and I wouldn't expect those to get parsed in the middle of a message anyways- I'm inclined to think this is errenous behavior, but I'm not sure.

Originally discovered on bubberstation, reproduced on tg(live, basil)

**Comment by distributivgesetz** [comment] 2023-12-14 12:41
This is normal behaviour, say code uses an asterisk as a separator for the "speaking emote" and the "spoken message" when parsing messages to give people the option of customizing the speaking emote further. For example

`stutters*H-he-he-eelp!`

will result in

`John Doe stutters, "H-he-he-eelp!`

I'm marking this as `not a bug` and `accessibility`, because we have tgui say now and the option for *message syntax highlighting* is available for someone to implement. 

Oh, and you wanna surround your text with `|` if you want it to be cursive.

**Comment by Cyprex** [comment] 2023-12-14 14:04
huh- that makes a lot of sense, actually- and I had no idea that | for cursive was a tg feature! Thanks!

**Closed** 2023-12-14 14:04 UTC
Labels: Not a bug, Accessibility
