### ISSUE TITLE
bubblegum does not attack

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#67873] opened 2022-06-19 11:30 UTC
## Testmerges:
The following pull requests are currently test merged:
[#67796: 'Mining Outpost Overhaul: Island Living Edition' by Thunder12345 at commit fc92e70aa9](https://www.github.com/tgstation/tgstation/pull/67796)
[#67669: 'Lemon attempts to optimize lighting [TM]' by LemonInTheDark at commit 9913284f94](https://www.github.com/tgstation/tgstation/pull/67669)
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67083: 'Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ' by MrMelbert at commit 4219c79a58](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:
shoot bubbles
he never once attempts to charge you just ambling around
occasionally he turns red and walks at you then goes back to ambling
free heck suit

**Comment by timothymtorres** [comment] 2022-06-19 12:12
Duplicate of #56128

**Comment by newfren** [comment] 2022-06-20 08:04
bubblegum had attacked me in between these two issue reports being made, and he was moving as if he were about to attack me, but simply never did

**Comment by timothymtorres** [comment] 2022-06-20 08:58
Whatever was causing bubblegum to not attack is likely from the same problem.  It doesn't appear to happen every round, but it's something with the mob AI being funky.

**Comment by newfren** [comment] 2022-06-21 11:07
This has happened again

**Comment by StrangeWeirdKitten** [comment] 2022-07-08 04:08
So I did a little bit of digging through the callbacks and I'm pretty sure I narrowed down the exact issue with this chunk of code.

![image](https://user-images.githubusercontent.com/95130227/177914397-1d1c935a-f65b-4578-9dc1-490f80a0acdb.png)

With some testing, I've determined the issue doesn't fall under the abilities themselves. Instead, 3/4 of bubblegums abilities relies on targetting mobs on `get_bloodcrawlable_pools`. The abilities do work, but the bubblegum AI litterally does not *have* a target to use them against with its list constantly returning null. That's why bubblegum is only using blood teleport and not any of its other abilities.

**Comment by ShizCalev** [comment] 2022-07-08 17:42
Caused by #63520

**Comment by timothymtorres** [comment] 2022-07-15 12:22
From #68443 

> Reproduction:
> attack bubbles
> he will successfully try to kill you with a charge once
> then he's broken again as in https://github.com/tgstation/tgstation/issues/67873
> 
> it's possible that you HAVE to stay off blood to avoid him charging again, as I did that round

**Closed** 2023-04-27 19:29 UTC
Labels: Bug
