### ISSUE TITLE
Supermatter delamination in low mole environment

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#33982] opened 2017-12-31 11:50 UTC
**Issue**:
The Supermatter engine delaminates extremely fast once its chamber contains low amounts of (but more than 0) gas moles.
I was only able to test this on localhost since I can't just blow up the engine as a non antag.

**How to reproduce**:
Power up a regular N2 engine setup. 
Now, disable vent output and/or delete the chamber floors with an RCD.
Within seconds, the crystal will now rapidly start delaminating and discharging electric bolts.
>12:34:40 [0x2008c7b] (169,154,2) || the supermatter crystal has been powered for the first time.
>12:41:01 [0x2008c7b] (169,154,2) || the supermatter crystal has reached the emergency point for the first time.
>12:42:04 [0x2008c7b] (169,154,2) || the supermatter crystal has exploded.
>ADMIN LOG: Explosion with size (12.4611, 26.9221, 28.9221, 0) in area: Supermatter Engine (169,154,2) (JMP)

**Expected result**:
My best guess is that SM delamination only checks for heat, but not the amount of moles present; a tiny amount of moles will heat up very rapidly.
If this is intended behavior, it allows for foolproof, extremely fast engine sabotage with three mouse clicks.
Other types of sabotage are either less effective or require a bunch of atmos knowledge and prep work.

**Comment by arsserpentarium** [comment] 2017-12-31 18:38
That's not a bug.
What do you think would happen if you'll dump off coolant from IRL nuclear reactor?or even vacuumize it?
It will rapidly overheat and blow up.

**Comment by arsserpentarium** [comment] 2017-12-31 18:39
Maximum it's map bug. Reactor scheme must be more secure.

**Comment by 81Denton** [comment] 2017-12-31 20:42
That would be a valid point if depressurizing the chamber took any kind of time, effort or skill. It's a simple case of "turn vents off, crystal blows up in 6 minutes".

**Comment by XDTM** [comment] 2018-01-01 00:12
@arsserpentarium The comparison isn't accurate since the standard behaviour for vacuuming the SM is for it to completely stop. The overheating should take moles into account somehow, it's unreasonable to believe that a few very hot atoms have the same effect as a ton of burning plasma with the same heat.

**Comment by arsserpentarium** [comment] 2018-01-01 21:43
No,reasonable. Because hot burning gas can be cold,compared to SM shard.
Vacuuming is basically equals to put this thing into thermos. This way only radiation heat transfer is allowed.
So shard will rapidly overheat.
Also,if you count ,that SM is emitting gasses,vacuum can cool shard. I'll put formula,describing cooling of object,which emitting gas in vacuum or low pressurized enivronment.

**Comment by XDTM** [comment] 2018-01-01 23:03
Doesn't the shard completely deactivate in space, though? If it used the air around it to cool off, it would, well, heat the air around it, which it doesn't do. The shard doesn't heat up by itself nor shed internal heat.

It does generate plasma, but only when energized by an external source, and it gets energized (and destabilized) by heat (and lasers). The bug here is that it's getting energized by temperature alone, which does not reflect the thermal energy in the air, as a few atoms can have the same temperature as a burning plasmafire while having a fraction of its energy.
It should use thermal energy instead of temperature, taking into account the mass of the gas along with the temperature. Someone experienced with atmos would probably be better than me at designing the formula.

**Comment by PsyCommando** [comment] 2018-01-02 02:20
So yeah, I'm not a maintainer, and Idk what is the exact lore idea behind the SM, but maybe taking this into consideration could help? https://en.wikipedia.org/wiki/First_law_of_thermodynamics

If there is no more energy entering the now isolated system, it shouldn't result in more heat in the crystal itself, because heat is energy, and there is nothing transferring or reacting to create more heat to/in the shard.

Also, here I'm assuming what seems to happens in SS13 is more like a meltdown https://en.wikipedia.org/wiki/Nuclear_meltdown 
Because delamination is nothing like that. Its just a material's layers splitting and causing it to weaken due to repeated stress. But its a crystal, which is the purest state of matter, so it having layers sounds kinda odd.. I'm no geologist or anything though..

Just leaving my 2 cents. Because I feel like syphoning the chamber would be intuitively how you'd keep it from going out of control, since its pretty established that it works from reacting with gasses.

**Comment by 81Denton** [comment] 2018-01-02 06:28
>Doesn't the shard completely deactivate in space, though?
The behavior is a little odd, last time I exposed it to space it stopped reacting to anything at 0% integrity with ~3°K temp. No explosion either.

>I feel like syphoning the chamber would be intuitively how you'd keep it from going out of control, since its pretty established that it works from reacting with gasses
I'm assuming that it's a gameplay thing - supermatter takes a while to delaminate from sabotage; if lack of gases/pressure completely deactivate it, most kinds of sabotage would be very easy to stop by just siphoning all gases or RCDing a floor tile away.

**Comment by XDTM** [comment] 2018-01-02 08:47
The shard stops processing in space, so rcding it into space already is a solution, the issue being that you have to wade into a plasmafire and risk bumping into the sm.
Syphoning _should_ help stabilize the SM, your job as a saboteur is also to avoid people fixing it

**Comment by 81Denton** [comment] 2018-01-02 12:05
That's true, I can't disagree with siphoning gases since it's part of atmospherics.
I don't know how I feel about RCDing floors though - space tiles inside the chamber work like magical vacuums that delete gases, cool the shard and eventually shut it down. You don't have to deal with managing gas properties, pressure and heat, vent/pump settings and so on.
Getting close to a delaminating SM is fairly easy if you have access to an atmos hologram projector or other tools like the CE hardsuit, magboots, fire extinguisher etc.

**Comment by Electronics** [comment] 2018-01-03 00:14
I've seen it multiple times that people have managed to delam the SM in under 1 minutes at the beginning of a round. Seems a bit OP.

**Comment by PsyCommando** [comment] 2018-01-03 21:00
To be honest, I've rarely seen anyone being able to stop delamination due to sabotage. Its one thing to allow traitors to blow it up, but it should also be counter-able. Plus its not like its not hard for a traitor to just shoot any engineer that tries getting close, or just literally blow up the pipes/air alarm.

Also Removing the floor under the sm is kinda really hard when the place is filled with extreme radiations and a super hot plasma fire, and well all those anomalies that pulls you in all directions and emits electricity all around and can basically kill you as well.. 

The worst part though is that you can't get any gear that protects from radiation, electricity and extreme temp and pressures all at once as a regular engineer. And the CE tends to just run away in their hardsuit or die.

At the end of the day, blowing up the engine itself isn't all that rewarding, its more like a distraction/bait most of the time. So just having it delaminate for a while already serves its purpose at least partially. At least, from my point of view. If the point was to blow up the station, there are other more efficient ways to do it already (bluspace backpacks being at the top of my head at the moment). 

Also, space is actually a magical vacuum confirmed XD

**Comment by davethwave** [comment] 2018-01-05 16:20
The main purpose of exploding the SM in this game is to entertain the ghosts really because who doesn't love a good explosion ripping through engineering when your a ghost.

**Comment by PsyCommando** [comment] 2018-01-06 21:17
Its also great to shutup poly XD

**Comment by Archemagus** [comment] 2018-01-12 19:42
Another way to reproduce:
1) Be traiter with task to steal SM's sliver
2) Steal SM's sliver
3) Start to setting up SM
4) If there is no skilled engineers SM destroys SMES's room.
5) Station falled in darkness in 10-20 minutes from round start.

**Comment by CPTANT** [comment] 2018-03-24 15:54
dupe of #28638

**Comment by CPTANT** [comment] 2018-04-04 09:25
@KorPhaeron

**Closed** 2018-04-04 13:58 UTC
Labels: Atmospherics, Bug
