### ISSUE TITLE
trait picks don't respect character slots

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#36211] opened 2018-03-06 20:24 UTC
@Xhuis 
Got a bug report via ahelp:
"If you swap characters, the one you loaded on connection's traits apply to whoever you pick; to change, you have to change charslot, then reconnect  If you simply select a different slot and join game, it'll apply the other charslot's trait picks "

**Comment by DaxDupont** [comment] 2018-03-06 20:31
Dupe of like 3 bug reports

**Comment by Xhuis** [comment] 2018-03-06 20:34
Duplicate of #36119

**Closed** 2018-03-06 20:58 UTC
