### ISSUE TITLE
Custom vending machine - Trying to place a chainsaw in a custom vending machine does weird stuff.

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#65897] opened 2022-04-03 05:25 UTC
## Round ID:
[180991](https://scrubby.melonmesa.com/round/180991)

## Reproduction:

1) build a custom vending machine
2) use your id on it so it gets set up
3) craft a chainsaw
4) price the chainsaw
5) try placing the chainsaw inside the vending machine

you get gui feedback in text indicating you placed the chainsaw in the vending machien slot, the chainsaw just drops on the floor, an item named chainsaw gets created inside teh vending machine but it has an empty bottle sprite and you can't get it out, not sure if it charges people when they try to buy it.

![image](https://user-images.githubusercontent.com/38957322/161413053-022c4db7-f85c-4aef-8717-a296c1122770.png)

**Comment by Sealed101** [comment] 2023-03-08 18:13
can't reproduce the bottle icon appearing, and the ghost saw thing seems to have been fixed by #71370

**Closed by Sealed101** 2023-03-08 18:13 UTC
Labels: Bug
