### ISSUE TITLE
Snakes On A Plane: Space Edition

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#56416] opened 2021-01-25 08:34 UTC
1. Order 3 snake crates and 2 carpet crates.
2. One of the snake crates spawns on the engines of the cargo shuttle, adjacent to space.
3. The cargo shuttle is now unusable without spacewalking because there are motherfucking snakes on the motherfucking shuttle and it won't launch while there are living things on it.

**Comment by interestingusernam3** [comment] 2021-01-25 08:51
emergent gameplay

**Comment by Tlaltecuhtli** [comment] 2021-01-25 10:34
dupe of #56370

**Comment by dragomagol** [comment] 2021-01-29 19:53
Duplicate of #56370

**Closed by dragomagol** 2021-01-29 19:53 UTC
