### ISSUE TITLE
Changing the owner of an AI shell fuckery.

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#43388] opened 2019-03-29 06:06 UTC
Issue reported from  Round ID: 104935 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

>BE AI 1
>ALSO BE AI 2
>AI 2 has a shell but is not within it
>Shell is desynced from AI 2 in the middle of the deconstruction process allowing other AIs to enter it
>AI 1 enters shell
>Shell is deconstructed while AI 1 is in AI 2's original shell
>AI 1 is now in AI 2's core with their name and everything
>AI 2 is currently in a different shell at the time of this happening
>A 2 returns to it's core with AI 1 in it
>AI 1 is booted to the ghost realm
>AI 2 is in it's core just fine but really confused

**Comment by ATH1909** [comment] 2019-03-31 03:10
Time for AI identity theft.

**Comment by timothymtorres** [comment] 2021-08-19 13:11
Duplicate of #50548.  Yes, I know this issue is _technically_ the oldest, but the other issue has more details and a video linked to show the process.

**Comment by timothymtorres** [comment] 2021-08-19 13:14
Duplicate of #50548

**Closed** 2021-08-19 13:15 UTC
Labels: Bug
