### ISSUE TITLE
Mediborgs cannot complete surgeries with a cautery, or extract organs during organ manipulation

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#84638] opened 2024-07-04 09:08 UTC
## Issue Summary

As it says in the title..

## Reproduction:

Step 1: Attempt an organi manipulation on someone.

Step 2: Get to the step where you pull out their organs.

Step 3: Try to get those organs out.

Step 4: Fail. Try to end the surgery.

Step 5: Fail. 

Before anyone says 'already fixed', the current server update is as recent as today. This is not fixed.

**Comment by Sadboysuss** [comment] 2024-07-04 09:11
Was supposed to be fixed by https://github.com/tgstation/tgstation/pull/83860
Sigh

**Comment by necromanceranne** [comment] 2024-07-04 09:34
If that is true, I would like to know whether or not it was tested because https://github.com/tgstation/tgstation/issues/84393 is definitely not fixed.

**Comment by SyncIt21** [comment] 2024-07-04 09:41
Unable to reproduce on local so yes my PR did fix it.

https://github.com/tgstation/tgstation/assets/110812394/2a6ede03-c8f3-4e85-b974-72b02a8657fa

> the current server update is as recent as today. This is not fixed.

Clearly this isn't the case. please check again

**Comment by ZephyrTFA** [comment] 2024-07-04 09:46
Not only do you not have a round id, which is now a requirement for issues. There is a video demonstrating that it is fixed on latest master.

**Closed** 2024-07-04 09:45 UTC
Labels: Bug

**Comment by necromanceranne** [comment] 2024-07-04 10:01
Turns out I just played on the literal last round before the server was merged to add the fix. I just checked the changelog and saw it was there.

**Comment by necromanceranne** [comment] 2024-07-04 10:39
> Not only do you not have a round id, which is now a requirement for issues. 

Just to clarify this, if I do actually find something outside of a round, would I need to at least provide evidence to demonstrate the existence of an issue?
