### ISSUE TITLE
The latest version of byonds unstable build makes ventcrawling a laggy pain

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#39004] opened 2018-07-09 08:44 UTC
Your client will nearly crash at every move you make. Then you'll find yourself at the other side of the hall.

Scrubbers are a bit better though, this happened a few days ago when I was playing as a morph. So I dont know the round ID. But recent morph players have also reported this being such a bad case.

**Comment by SpaceManiac** [comment] 2018-07-11 06:00
Cannot reproduce locally

**Comment by ninjanomnom** [comment] 2018-07-13 05:40
Was having this issue earlier and can confirm it's still present in 1437

**Comment by Jalleo** [comment] 2018-07-16 08:33
Probably needs to be reported to Lummox.

**Comment by ninjanomnom** [comment] 2018-07-16 08:35
Oh right I forgot to close this, this seems to be fixed in 1438

**Closed by ninjanomnom** 2018-07-16 08:35 UTC
Labels: BYOND Issue
