### ISSUE TITLE
[Cerestation]There are very few places to place a gang dominator

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#27164] opened 2017-05-12 05:16 UTC
There seems to be very few places to place it with enough room.

**Comment by GunHog** [comment] 2017-05-12 11:25
>Biggest station with the highest population restriction
>> Few suitable places to install a dominator

Just....wow!

**Comment by MMMiracles** [comment] 2017-05-12 14:43
I mean, can't you just, like, take down a few walls at worst? Whoever added a restriction with walls next to doms is dumb tbh.

**Comment by Cyberboss** [comment] 2017-05-12 15:15
No, @Robustin made the area too big. Dupe of #27177

**Closed** 2017-05-12 15:21 UTC
Labels: Map Issue, Oversight
