### ISSUE TITLE
Deepfrying kitchen knives infinitely

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#45102] opened 2019-07-10 04:49 UTC
Deepfrying a kitchen knife then putting it in a bowl to make a custom salad instantly spawns the un deepfried knife back under you, enabling people to make infinite knife salads as long as they have enough bowls

Step 1
Deepfry knife
Step 2
Put knife in bowl to make salad

**Comment by ATH1909** [comment] 2019-07-12 01:59
https://github.com/tgstation/tgstation/issues/44123

**Comment by Qustinnus** [comment] 2019-07-13 01:46
duplicate of above

**Closed by Qustinnus** 2019-07-13 01:46 UTC
Labels: Bug, Oversight
