### ISSUE TITLE
Ashdrake Armor is Uncraftable

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#52204] opened 2020-07-13 00:10 UTC
## Testmerges:
#52085: 'tgui 4.0' by stylemistake at commit d7ca619a9a

## Reproduction:
Get the materials necessary to craft the armor, open crafting menu, notice how the option remains greyed out no matter how many materials you have.
Was reproduced during the same round when an admin tried to craft the armor.

**Comment by ShizCalev** [comment] 2020-07-13 00:10
Duplicate of #52190

**Closed by ShizCalev** 2020-07-13 00:10 UTC
