### ISSUE TITLE
Last resort is kinda shit as a last resort.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35523] opened 2018-02-11 01:29 UTC
Step 1: Be ling.
Step 2: Dying horribly.
Step 3: Press Last Resort at the last possible second while in crit.
Step 4: Nothing happens, die, gibbed within 0.2 seconds.

I didn't even see the confirmation dialogue pop up. Can we make it remotely functional as a "OH FUCK ABORT ABORT" button, skipping the confirmation while in crit, and maybe even having it be a toggle or short duration which automatically activates if you die/get gibbed in the next few seconds?

Also I'm not remotely exaggerating about "0.2 seconds". Welcome to Lavaland, enjoy your free dust.

**Comment by Repukan** [comment] 2018-02-11 02:17
Ided

**Comment by Kromgar** [comment] 2018-02-11 03:01
Did... did you try to do it while fighting a megafauna?

Also Idedplzfix

**Comment by Buggy123** [comment] 2018-02-11 03:15
Yes.

I mean, ling is actually not really helpful on lavaland. At best it lets you skip out on getting healing items. Thought last resort might be useful for avoiding getting gibbed to a mega, it wasn't.

**Comment by Repukan** [comment] 2018-02-11 03:16
Lmaoing @ ur life rn tbqh

**Comment by Kromgar** [comment] 2018-02-11 03:21
You should just close this buggy to protect your tbh already awful image. FYI the Megafauna would of totally killed your headslug too

**Comment by Buggy123** [comment] 2018-02-11 08:55
Maybe, maybe not. I'd like the opportunity to see if it would.

**Comment by Repukan** [comment] 2018-02-11 11:42
There's no maybe not chuckleshit it would immediately aggro on your slug.

**Comment by Kromgar** [comment] 2018-02-11 14:33
Stop embarrassing yourself @Buggy123 Your making yourself look like a fool

**Comment by KorPhaeron** [comment] 2018-02-11 15:55
This is not a bug its a balance issue

**Closed by KorPhaeron** 2018-02-11 15:55 UTC
