### ISSUE TITLE
Away missions don't seem to initialize cable wires properly

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#34364] opened 2018-01-12 15:52 UTC
Inside the editor:
![away1](https://user-images.githubusercontent.com/9276171/34883035-5cd953b4-f786-11e7-9f2b-443814499935.png)

In-game:
![away2](https://user-images.githubusercontent.com/9276171/34883039-62092116-f786-11e7-8606-e799d8ea543d.png)

The cables themselves should be fine as they're taken directly from Boxstation. Pipes don't share this issue.

**Comment by Cyberboss** [comment] 2018-01-12 15:55
Duplicate of something @AnturK ?

**Comment by AnturK** [comment] 2018-01-12 16:51
Yep, duplicate of #32694. I'll put up a fix in a moment.

**Closed by AnturK** 2018-01-12 16:51 UTC
Labels: Bug

**Comment by Cyberboss** [comment] 2018-01-12 17:02
Duplicate of #32694

**Comment by Cyberboss** [comment] 2018-01-12 17:02
github is retarded
