### ISSUE TITLE
Landing a monster tackle while stun immune doesn't grab properly

### ISSUE THREAD

**Issue by Momo8289** [tgstation/tgstation#78441] opened 2023-09-19 12:25 UTC
## Reproduction:
When you land an expert or monster tackle, you're supposed to grab/aggressive grab the target and get up immediately. However, if the tackling individual has the `TRAIT_STUNIMMUNE` trait, then they will instead stay on the ground for the normal amount of time, and will not grab the target. If it was a monster tackle, they will still be slowed like they have something aggressive grabbed. This slow lasts until they grab and release something. 

### Steps to reproduce:
1. Gain the `STUN_IMMUNITY` trait
2. Land a monster or expert tackle on someone (You can make it guaranteed by var editing the value of `skill_mod` on the tackle component or gloves to 10, but this isn't required)
3. See how you don't actually grab them properly

**Comment by GPeckman** [comment] 2023-09-21 18:23
There seems to be a runtime at this line when I tested the bug:

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/game/atoms_movable.dm#L1593-L1597

The runtime does not occur without `TRAIT_STUNIMMUNE`. It seems that `pulling' isn't properly set if you do have the trait. I suspect that this line is involved, due to the async:

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/datums/components/tackle.dm#L238

**Comment by GPeckman** [comment] 2023-09-21 19:23
Alright, I've finally tracked the issue down. It wasn't the line I thought it was. First, I'll explain how the code works without `TRAIT_STUNIMMUNE`. As soon as a tackle is begun, the user is set to be lying down. This gives the user `TRAIT_PULL_BLOCKED` and 'TRAIT_FLOORED', which will be relevant later. When a monster tackle is landed, this whole block of code is executed:

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/datums/components/tackle.dm#L231-L236

The first relevant line is `user.SetKnockdown(0)`. This is the relevant part of that function: 

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/modules/mob/living/status_procs.dm#L104-L112

The code progresses all the way to `qdel(K)`. When the knockdown status effect is qdeleted, it removes `TRAIT_FLOORED` from the user. Then we get to the line after `user.SetKnockdown(0)`, `user.get_up(TRUE)`. Note this check in that function:

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/modules/mob/living/living.dm#L611-L612

If the user has `TRAIT_FLOORED`, then the function early returns. Otherwise, the function continues and removes `TRAIT_PULL_BLOCKED`

That was all when the user didn't have stun immunity. If the user does, then things go a little different. First of all, `user.SetKnockdown(0)` early returns due to this check: 

https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/modules/mob/living/status_procs.dm#L107-L108

Obviously, the user is stunimmune so the if statement is true. This means that the knockdown status effect is not created and qdeleted. This, in turn means that `TRAIT_FLOORED` is not removed from the user. This causes `user.get_up(TRUE)` to early return, meaning that `TRAIT_PULL_BLOCKED` isn't removed either. This is the cause of the `pulling` variable I mentioned being set to null and causing a runtime.

**Closed** 2023-09-25 17:49 UTC
