### ISSUE TITLE
go down the shute and be turned into a box

### ISSUE THREAD

**Issue by patatas36** [tgstation/tgstation#64505] opened 2022-01-28 11:14 UTC
## Reproduction:  this happened in solitaire station or whatever its called its the new map on fulpstation

ok so  a guy gets stuck in the sci delivery shute pipes and we tried to find him i gues ah it might be a good ideal to go into the shute myself and find him, i go and get stuck, then a guy comes and takes us out and we instantly turn into ghosts and default crates named monkeycube crate spawn that are locked for sci delivery i dunno how it happens and i dont know if it can be reproduced it was the first time ive seen something like this. In the end after both of us being turned into crates i got respawned by an admin i dunno about the other guy tho he seemed pretty salty

**Comment by SuperNovaa41** [comment] 2022-01-30 19:00
He took you out how? As in deconstructed/destroyed the disposal pipe?

**Comment by Pepsilawn** [comment] 2022-01-30 19:10
Sounds like the crate might have already been in the disposal pipe with the trapped people. If I understand the issue it was already fixed with https://github.com/tgstation/tgstation/pull/64236 which Fulp does not have yet and the issue is a duplicate of https://github.com/tgstation/tgstation/issues/63815.

**Comment by patatas36** [comment] 2022-01-30 19:21
I believe it was a welder i dont know how pipes are unsecured but he
definetly used a welder

**Comment by JohnFulpWillard** [comment] 2022-01-30 20:59
> Sounds like the crate might have already been in the disposal pipe with the trapped people, only the people were deleted while the crate was released upon the pipe being broken. If I understand the issue it was already fixed with #64236 which Fulp isn't up to date with.

That was merged 1 day after Fulp last updated, so I’m going to assume it’s a Fulp issue and close this.

**Closed by JohnFulpWillard** 2022-01-30 20:59 UTC
