### ISSUE TITLE
Civ bounties aren't giving out credits

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#52387] opened 2020-07-21 05:43 UTC
roundid 142432, was doing bounties in rnd and after checking my balance after doing a bounty i didnt get any money, scammed moment

was doing it again in a different round, after doing a few bounties and getting credits from them, did 2 bounties and didnt get any credits from either

**Comment by ArcaneMusic** [comment] 2020-07-21 18:28
Duplicate of #52343, and fixed by the same fix PR.

**Comment by nightred** [comment] 2020-07-22 14:30
Please close as duplicate.

**Closed** 2020-07-22 23:17 UTC
Labels: Bug
