### ISSUE TITLE
The GC doesn't call Destroy(), which can cause issues

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15469] opened 2016-02-12 17:07 UTC
When we added qdel(), a lot of stuff was moved from Del() over to Destroy(). You might think that this is fine and nothing changes, but in reality Destroy() is a proc that we defined, and so during natural collection won't have it. This wouldn't be an issue if we only used Destroy() for its purpose (cleaning up leftover references), but we do a lot more side-effects (such as the ghostize() in soul stones or brainmobs). What this means is that, for instance, if a human gets gibbed and everything in his contents gets GC'd, any brainmobs/shades in soul stones will get kicked to lobby due to not having their ghostize() called. This is a tricky issue to approach because just calling Destroy() on /datum/Del() incurs a fair bit of overhead, while just renaming Destroy() to Del() would mean the references get cleaned up too late and the GC will fail its loop.

I've talked about this with @RemieRichards and @duncathan on IRC, and they seem to agree that the right way to tackle this would be offloading the Destroy() side-effects to another proc, and having that be called on Del() (or alternatively, offloading the side effects to Del() itself to cut down on overhead). This would, of course, require some not very sane person to go through all overrides of Destroy() and cherrypick what should stay and what should go over to the new proc. I'm still making this issue, though, because I'd like the input of more people on this, specially @MrPerson.

**Comment by duncathan** [comment] 2016-02-12 17:09
Going through every override of Destroy() is easier than you might think; it's deciding which ones need to be split up that will be difficult

**Comment by MrStonedOne** [comment] 2016-02-12 20:22
GC calls Del() so something could define a delete for itself.

>if a human gets gibbed and everything in his contents gets GC'd, any brainmobs/shades in soul stones will get kicked to lobby due to not having their ghostize() called.

This will never happen, as a mob having ckey assigned prevents GC'ing, something else is preventing ghostize from getting called.

**Comment by JJRcop** [comment] 2016-10-17 04:25
I volunteer to be this not very sane person, what will this proc be called?

**Comment by Cyberboss** [comment] 2017-02-12 02:48
@RemieRichards @Fox-McCloud didn't you guys yell at me for defining _a_ `Del`? If it's as bad as you say, this should probably be closed

**Comment by duncathan** [comment] 2017-04-02 07:46
@Cyberboss it's more complicated than just that. This issue represents an innate failure of our garbage collection system as a whole, but until it's fixed nothing should have a `Del()` defined

**Comment by MrStonedOne** [comment] 2017-04-02 23:14
This is a non-issue. if something has no references pointing to it, it is a non-factor and it not having it's Destroy() ran is a non-issue since nothing knows about it anyways.

**Comment by Cyberboss** [comment] 2017-04-03 00:25
So can we close this?

**Comment by Cyberboss** [comment] 2017-04-28 15:26
ayy

**Comment by MrPerson** [comment] 2017-05-04 07:05
Toss in a comment to the default Destroy() to make sure people are aware this is ONLY called if you call qdel() on the object. If something absolutely, 100% needs to do something on Del() (logging?), then sure, define it there, but 99.9% of the time, if something is garbage collecting, whatever it wanted to do wasn't of relevance anyway. Think about it, it's in nullspace with no references and only being referenced by other things which are also being garbage collected. What on earth could it want to do?

**Comment by MrStonedOne** [comment] 2017-05-04 09:06
actually, we can't define any Del()s (except for world and client because they are special)

Defining any Del()s puts a non-trivial overhead on **every** soft deletion, not just ones for that type.

**Comment by MrStonedOne** [comment] 2017-05-04 09:07
but close this anyways, the "issue" it caused wasn't actually caused by this behavior.

I can not think of anything use case where this is an issue that isn't a symptom of bad design.

**Comment by duncathan** [comment] 2017-05-04 13:16
I've come to agree with mso

**Closed by duncathan** 2017-05-04 13:16 UTC
Labels: Maintainability/Hinders improvements, Priority: High
