### ISSUE TITLE
Bleeding with no way to fix it

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63381] opened 2021-12-13 02:58 UTC
Reporting client version: 514.1571

## Round ID:
[174699](https://scrubby.melonmesa.com/round/174699)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:

Examining tells you the patient is bleeding from a specific body part:
![](https://i.imgur.com/Ps51sG6.png)

When you attempt to bandage it with medical gauze, nothing happens:
![](https://i.imgur.com/cM8fTbF.png)

If you let them go, they bleed all over the floor, losing blood. Eventually it stops by itself.

Players assume it needs to be fixed before a patient can be released. Releasing a patient who is losing blood and bleeding everywhere making a huge mess seems like the wrong thing to do.

You used to be able to use bandages to stop bleeding but I think it only checks for wounds now which prevents you stopping the bleeding.

@Ryll-Ryll 
https://github.com/tgstation/tgstation/pull/50558

**Comment by Ryll-Ryll** [comment] 2021-12-13 04:40
Yeah this is from the generic bleedstacks that were a holdover from old surgery before wounds. I agree this should be resolved at some point, but there's 3 options that come up in my mind that i don't really see strong ties towards either one

1. Remove the bleeding entirely on incision, which loses some fluff flavor, but isn't really that bad
2. Let generic bleedstacks still tick down while stasis'd, which has some precedent with how I have a specific proc for wounds, on_stasis(), that lets them still check if they've been cured each tick while on stasis
3. Replace the generic bleedstacks with a special surgery wound that represents incision, and would be removed upon cauterizing at the end of the surgery. This would add a fair bit of complexity and possibly cause confusion of its own though, so I don't like this either.

In the end I may just go with #1, or maybe just remove a flat amount of blood upon opening the incision

**Comment by cacogen** [comment] 2021-12-13 05:39
What about setting generic_bleedstacks to 0 when a surgery is completed successfully or when it's cancelled with a cautery partway through? And in cases where it's set by something other than a surgery, have medical gauze absorb the blood like it does with wounds?

**Comment by TheBonded** [comment] 2021-12-13 22:09
you could create a special bleed wound subtype for the incision, so you can wrap it up with gauze, or just close it with a cautery.

**Comment by Mothblocks** [comment] 2023-10-30 21:19
Closing as "Not a bug" is expected to be only closed issues

**Closed by Mothblocks** 2023-10-30 21:19 UTC
Labels: Not a bug, Oversight
