### ISSUE TITLE
Magical monkeys

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#42521] opened 2019-01-25 20:25 UTC
Items snatched by monkeys seem to dissapear, sometimes. i once had a scanner snatched, tried to point it but im not pointing at anything

**Comment by adamkad1** [comment] 2019-01-26 00:46
> Items snatched by monkeys seem to dissapear, sometimes. i once had a scanner snatched, tried to point it but im not pointing at anything.

**Comment by SpaceManiac** [comment] 2019-01-27 06:40
Duplicate of #37645

**Closed by SpaceManiac** 2019-01-27 06:40 UTC
