### ISSUE TITLE
trying to VV the lobby screen freezes my client

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#33092] opened 2017-11-26 00:51 UTC
reconnecting fixes it but trying to open vv still freezes
also happening to citrusgender so its not just me

**Comment by Cyberboss** [comment] 2017-11-26 04:51
Dupe of that VV crash @AnturK

**Comment by AnturK** [comment] 2017-11-26 10:58
Duplicate of #26688

**Closed by AnturK** 2017-11-26 10:58 UTC
