### ISSUE TITLE
Plasmamen have an emergency oxygen tank in their backpack box

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/tgstation#19433] opened 2016-07-22 18:52 UTC
In the little internals box that all plasmamen start with, there is a breath mask, an epipen, and an oxygen tank.

Please note that plasmamen explode when exposed to oxygen.

WARNING: FEATURE REQUEST

**Comment by Jalleo** [comment] 2016-07-22 22:09
That would require possibly a lot of work probably not much.

**Comment by Dorsisdwarf** [comment] 2016-08-03 22:04
Dupe of #16183

**Closed by Dorsisdwarf** 2016-08-03 22:04 UTC
Labels: Consistency Issue, Not a bug
