### ISSUE TITLE
Humans appear to be space immune

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#65883] opened 2022-04-02 11:16 UTC
## Testmerges:

#65795
#65841 
#65860 

## Reproduction:

>See other assistant in space
>Get curious
>They yell at me to put oxygen on and walk out with them
>Holy fuck it works
>Set up a couch with the boys
>Be space assistants, assistants in space.

Only oxygen is necessary to be completely space immune as an assistant because of this.

**Comment by robbertapir** [comment] 2022-04-02 12:52
honestly quite incredible

**Comment by GolfinhoVoador** [comment] 2022-04-02 14:59
could be a missed april fools joke leftover

**Comment by Kapu1178** [comment] 2022-04-02 16:20
Cannot reproduce locally

**Comment by TheBonded** [comment] 2022-04-02 17:11
duplicate of https://github.com/tgstation/tgstation/issues/65696

**Closed by TheBonded** 2022-04-02 17:11 UTC
