### ISSUE TITLE
You Can Get Spaced by Pubby Shuttle at Launch (probably bc one sided windows)

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#42824] opened 2019-02-17 20:53 UTC
## Round ID: 101978 (bagil, it was probably this round)

>stand on pubby shuttle
>no holes to get breached by
> shuttle launches, I get spaced
> was told it was probably bc of directional windows.

**Comment by ShizCalev** [comment] 2019-02-17 20:57
Duplicate of #42624

**Closed by ShizCalev** 2019-02-17 20:57 UTC
