### ISSUE TITLE
Leaving the Z-Level with the nuke disk gives you a spooky phantom disk

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68085] opened 2022-06-29 16:50 UTC
Reporting client version: 514.1583

## Round ID:
[185775](https://scrubby.melonmesa.com/round/185775)

## Reproduction:
Put disk in internals box.
Use handtele to go to lavaland.
Weird floating disk in bottom corner of screen that follows you around.

![image](https://user-images.githubusercontent.com/66640614/176492134-6fe0630e-e5e1-4c09-afea-2b36a10a341a.png)

![image](https://user-images.githubusercontent.com/66640614/176492163-6e94414b-b15c-483f-bba2-3b87f40975b1.png)

**Comment by nemvar** [comment] 2022-06-30 09:53
Wouldn't surprise me if this is a duplicate, but haven't checked.

**Comment by Sealed101** [comment] 2024-10-23 17:29
can't reproduce; possibly fixed by https://github.com/tgstation/tgstation/pull/70496 or uh elsewhere.

**Closed by Sealed101** 2024-10-23 17:29 UTC
Labels: Bug
