### ISSUE TITLE
Syndicate infiltrator turrets don't target cyborgs

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47994] opened 2019-11-26 07:45 UTC
No further description necessary. Put cyborg next to turret. Doesnt shoot.

Issue reported from  Round ID: 124494 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by kriskog** [comment] 2019-11-26 08:14
Okay but there is also #46775. So which is it?

**Comment by NoxVS** [comment] 2019-11-26 08:17
I have no fucking clue but we had a borg just walk onto the shuttle and fuck everything up.

**Comment by kriskog** [comment] 2019-11-26 08:17
Round ID? Those matter

**Comment by Firecage** [comment] 2019-11-26 13:40
Could it be a syndicate cyborg which was captured, module reset, and synced to the AI?

**Comment by NoxVS** [comment] 2019-11-26 18:25
> Could it be a syndicate cyborg which was captured, module reset, and synced to the AI?

Nope just a normal cyborg. Not emagged, not a syndiborg, just a cyborg that walked onto the shuttle and then bolted everything shut

Round ID was 124494

**Comment by TheVekter** [comment] 2019-11-26 21:10
I'll reproduce this when I get to work tonight if no one else has.

**Comment by IndieanaJones** [comment] 2019-11-27 03:44
Yeah, the syndie ship turrets never shoot at borgs from my experience.  I always board their ship and sabo it.

**Comment by TheVekter** [comment] 2019-11-27 05:03
Are we talking about the assault pod or the ship itself?

**Comment by PKPenguin321** [comment] 2019-11-27 07:24
Test both just in case

**Comment by TheVekter** [comment] 2019-11-27 07:58
Yeah, they don't give a shit about borgs. They'll murder almost anything else but just don't pay any attention to silicons. Blaming this on poor implementation but it's a bit out of my scope to fix.

**Comment by Taylorkills2** [comment] 2019-11-28 00:51
I can confirm this is a glitch, the Nuke Op shuttle was not firing on at least two different Station Aligned Cyborgs on round# 124619
I was one of the cyborgs, came from a positronic brain.

**Comment by TheVekter** [comment] 2019-11-28 04:51
Source doesn't seem to matter since it'll do it with admin spawned borgs, too.

I'll look into it.

**Comment by Firecage** [comment] 2019-11-28 12:05
@TheVekter It is kind of poor implementation. Now, they don't fire shoot borgs by default, which is sort of understandable since that is a fairly recent feature. The problem is, if you enable it so they do shoot at borgs, they also shoot at Syndiborgs despite them sharing the same faction.

Will probably need a separate option and flag for 'Enemy Cyborgs'/'Unauthorized Cyborgs'.

As a side note, I think only the mob path syndicate cyborgs have the syndicate faction.(Aka the spawned ones, either via uplinks, admemes, and such). If they are changed into the syndicate borgs from normal borgs, they don't get the syndicate faction.

**Comment by timothymtorres** [comment] 2021-08-19 15:58
Duplicate of #56577

**Closed by timothymtorres** 2021-08-19 15:58 UTC
Labels: Needs Reproducing
