### ISSUE TITLE
Trying to follow speakers while viewing mining level crashes game

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33158] opened 2017-11-28 22:42 UTC
1) Be AI.
2) Switch to Mining Level camera net.
3) Try to follow a speaker on station.
4) Crash.

---

Server revision compiled on: 2017-11-28

The following pull requests are currently test merged:
#33147: 'Lavaland dwarfs 4(?): He does it for free edition.' by Shadowlight213 at commit d5cc56

Based off origin/master commit: 395c0e

Server tools version: /tg/station 13 Server v3.2.0.14

Server tools API version: 3.2.0.1

**Comment by ShizCalev** [comment] 2017-11-28 23:44
Duplicate of #28689

**Closed by ShizCalev** 2017-11-28 23:44 UTC
