### ISSUE TITLE
Player wasn't getting the tgUI for a canister

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21491] opened 2016-11-11 20:55 UTC
Happened at about 2016-11-11 20:50 maybe a little earlier, the player, Pdgamer wasn't getting the tgUI for an oxygen canister but could still open the tgUI for a nearby plasma canister, and it worked when I tested it.

Weird issue, ho.

**Comment by Cyberboss** [comment] 2016-11-28 20:24
I'd close this, purely because it sounds exactly like it was minimized

**Comment by lzimann** [comment] 2016-12-19 00:45
Sometimes the tgui for something simply won't open(it will open a first time but after you close it won't), happened to me a few times, I don't have reprodution steps though.

**Comment by optimumtact** [comment] 2017-01-11 21:48
zero chance we'll reproduce this successfully

**Closed** 2017-01-11 21:48 UTC
Labels: Bug
