### ISSUE TITLE
Clown ruin is ruined

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#29219] opened 2017-07-12 13:36 UTC
The clown ship on lavaland has had its disposal chutes uprooted somehow, causing all of the chutes to spit their contents out on the other side of the wall they're next to, meaning there's no escaping the ruin once inside, and looting the place is completely pointless.

![sybil condom city 2017-07-12 143158](https://user-images.githubusercontent.com/20377602/28120170-277713a8-670f-11e7-8da6-29346bd32ea3.png)
Where things from the chute with the bananium airlock end up

![sybil condom city 2017-07-12 143203](https://user-images.githubusercontent.com/20377602/28120224-4c5f2192-670f-11e7-8e21-716b5f64f795.png)
Where things from the early escape room chute end up

**Comment by AnturK** [comment] 2017-07-12 13:56
Dupe of #26674

**Closed by AnturK** 2017-07-12 13:56 UTC
