### ISSUE TITLE
Got rads while wearing rad suit

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#46004] opened 2019-08-18 14:23 UTC
Issue reported from  Round ID: 116404 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Ok so i was working on fusion, when after i activated it i instantly got radiation on me (5k rads) while wearing the radiation suit, no particle hit me (i dont know if those can bypass the 100 rads protection) so i have no idea how it got me, unless one particle got me and it didnt registered

Reporting client version: 512.1477

**Comment by kriskog** [comment] 2019-08-18 20:14
Particles add exactly 5k rads, you likely got hit by one. They are currently penetrating rad armor, dupe of #45576

**Closed by kriskog** 2019-08-18 20:14 UTC
Labels: Bug, Needs Reproducing

**Comment by Ghilker** [comment] 2019-08-18 20:24
problem is that i didnt got hit by a particle, so this isn't a dupe of the other issue

**Comment by YPOQ** [comment] 2019-08-19 00:22
`[2019-08-18 14:08:40.316] ATTACK: Ghilker/(Ghilker Mabara) has been shot by  with the nuclear particle (Incinerator (151, 89, 2))`
https://tgstation13.org/parsed-logs/sybil/data/logs/2019/08/18/round-116404/attack.txt
I think byond still has an issue which causes messages to occasionally not get sent to the client
