### ISSUE TITLE
Hulks slip on lube, but only if they're buckled to a vehicle

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24049] opened 2017-02-13 06:01 UTC
- Have lube on the ground
- Be a hulk
- Walk on it and notice nothing happens
- Buckle into any vehicle (scooter, skateboard, janicart, etc.)
- Ride over lube
- >You slipped!
- Don't actually get stunned by fly off in a direction and spin around

**Comment by XDTM** [comment] 2017-02-13 08:29
Makes sense tbh

**Comment by Cyberboss** [comment] 2017-08-02 19:07
Duplicate of #23558

**Closed by Cyberboss** 2017-08-02 19:07 UTC
Labels: Bug
