### ISSUE TITLE
Jump boots set you on fire when jumping over lava

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#34257] opened 2018-01-10 16:12 UTC
When you jump over lava it still burns you, even when you wouldn't land on lava

I don't know the round ID or remember anything about the round because this was a while ago

To reproduce: get jump boots, stand next to a lava river small enough that you'll land on ground, face lava river, use jump boots (recommended but not part of reproduction steps: use extinguisher and burn patch after you get set on fire)

Might be a bug, might be intentional, but you should really be able to jump over lava

**Comment by WJohn** [comment] 2018-01-10 16:15
Guess this is broken again.

**Comment by praisenarsie** [comment] 2018-01-10 16:52
@kevinz000 
probably broke it when he ""fixed"" lava boats

**Comment by RandomMarine** [comment] 2018-01-10 17:41
The fix was never merged in the first place.
#33526
#25858

This is the third time this was posted and I doubt it'll be the last.

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-01-10 19:32
Not a bug.

**Comment by optimumtact** [comment] 2018-01-10 20:35
I'm gonna fix this

**Closed** 2021-08-31 21:07 UTC
Labels: Bug

**Comment by optimumtact** [comment] 2021-08-31 22:18
turs out I did not fix it

**Comment by LemonInTheDark** [comment] 2021-08-31 22:49
better yet, someone fixed it for you
