### ISSUE TITLE
Floor is lava doesn't seem to work

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31148] opened 2017-09-30 08:08 UTC
Didn't actually happen after it being randomly triggered by a summon events.
Needs testing

**Comment by Bawhoppen** [comment] 2017-09-30 08:12
Also the button in secrets doesn't even seem to work properly

**Comment by Bawhoppen** [comment] 2017-09-30 08:36
Seems to just be visual.

**Comment by YPOQ** [comment] 2017-09-30 16:56
#28344

**Comment by Cyberboss** [comment] 2017-09-30 18:08
Duplicate of #28344

**Closed by Cyberboss** 2017-09-30 18:08 UTC

**Comment by ShizCalev** [comment] 2017-09-30 19:24
Dupe #28344
