### ISSUE TITLE
Welding hard hat doesn't blind

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#54551] opened 2020-10-23 04:10 UTC
## Testmerges:

general issue tracker:
#54517: 'fix fix chat' by actioninja at commit 9dd0d3d4f3
#54318: 'Add language icon to runechat' by Jared-Fogle at commit 3b98580816
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 818d43b75b

## Reproduction:

I got a welding hard hat out of the engi vendor, it started with the mask down but didnt blind me. It stayed this way when i toggled it on and off. it actually protected my eyes

**Comment by Potato-Masher** [comment] 2020-10-23 04:40
Seems that normal welding helmets also don't have any vision obscuring effects like they should.

**Comment by msgerbs** [comment] 2020-10-23 06:03
This is sort of a duplicate of #52972

**Comment by necromanceranne** [comment] 2020-10-23 09:56
Actually I've noticed that blindness is really finicky at the moment. I entered crit today and ended up having no blinding effect whatsoever so I was utterly baffled as to what was happening until I realized I was actually in crit dying. This might be wider issues with blindness overlays?

**Comment by msgerbs** [comment] 2020-10-23 13:06
You know, now that you mention it, I didn't get any overlay on that same round when I was crit either.

**Closed** 2020-10-23 13:45 UTC
Labels: Bug, UI
