### ISSUE TITLE
Ash walkers has no access to leather

### ISSUE THREAD

**Issue by Amrabol** [tgstation/tgstation#63180] opened 2021-12-01 01:48 UTC
## Reproduction:
Start as ash walker. Kill goliath. Use sharp object on goliath plate. Wash hide. Place it on grill(Grill made by placing rods on bonfire). Hide wont change to leather. Drying rack does not works too. Talked with admin about it. Tried few ways. Finally after change to drying rack(admin change something in code) we were able to make leather. From what i understand something must have been wrong with grill. We were also told that drying rack needs access to power too.

**Comment by TheBonded** [comment] 2021-12-01 22:31
might have to wait for january to fix drying racks requiring power, but the second pr should allow you to tan the hide on a bonfire

**Comment by Sealed101** [comment] 2021-12-04 17:20
with #63198 merged this is no longer an issue. skin goliath hide -> splash a bucket of water -> burn over a campfire

**Comment by TheBonded** [comment] 2021-12-04 19:17
> with #63198 merged this is no longer an issue. skin goliath hide -> splash a bucket of water -> burn over a campfire

this bug report also mentions the fact that wooden drying racks require power to function, which is a separate issue on it's own

**Comment by Fikou** [comment] 2021-12-05 12:40
they have been coded to require power, so its not a bug

**Closed by Fikou** 2021-12-05 12:40 UTC
Labels: Bug, Consistency Issue

**Comment by TheBonded** [comment] 2021-12-05 19:52
> they have been coded to require power, so its not a bug

fair enough, just seems really weird that they would be like that considering a drying rack made of wood normally wouldn't need power to run, at least not in the real world.
