### ISSUE TITLE
You don't know if there is plasma in the air

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55530] opened 2020-12-14 18:04 UTC
Reporting client version: 513.1536

## Round ID:
[152168](https://scrubby.melonmesa.com/round/152168)

## Reproduction:
 The alert just doesn't apear. You'll quietly take toxin damage

**Comment by Ghilker** [comment] 2020-12-15 10:18
Both the too much toxin alert and the too much pressure alert are not working

**Comment by Pugie** [comment] 2020-12-16 08:45
Feature

**Comment by dragomagol** [comment] 2020-12-24 03:46
Reincarnation of #51138

**Comment by timothymtorres** [comment] 2021-08-19 17:15
Duplicate of #51138

**Closed by timothymtorres** 2021-08-19 17:15 UTC
Labels: Bug, Feedback
