### ISSUE TITLE
Iron Hawk gear missing sprites

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#27961] opened 2017-06-02 08:52 UTC
The sprites for the Iron Hawk Marine's armour and carbine seem to be missing most of their sprites. The carbine has an in-hand sprite but no other representation at all, and the armour is missing most of its sprites, instead appearing as some kind of strange grid. Activating the helmet on the armour causes it to hide the player's mask and hair, making them appear bald as well as naked.
![sybil timestation13 2017-06-02 094025](https://cloud.githubusercontent.com/assets/20377602/26718420/e11ef02a-4778-11e7-90b1-9dc770ef7012.png)

**Comment by Armhulen** [comment] 2017-06-02 15:19
@Steelpoint

**Comment by Steelpoint** [comment] 2017-06-02 15:25
Once again, this is a issue with the lava dwarf PR using a outdated sprite set which does not include the newer sprites.

I confirmed a hour ago that, when the PR was not being test merged, that all the marine sprites are working properly.

**Comment by Mark9013100** [comment] 2017-06-24 14:12
Is this even an issue anymore?

**Comment by Steelpoint** [comment] 2017-06-24 14:15
As I said, the sprites were missing due to the Lava Dwarf PR.

The actual hardsuit sprites are still in the game, and I imagine they are functional if anyone associates the sprites to a object.

**Closed** 2017-07-26 22:17 UTC

**Comment by ShizCalev** [comment] 2017-07-27 01:57
All this was removed with #28041, please close

**Comment by Steelpoint** [comment] 2017-07-27 03:52
Technically the Iron Hawk armor sprites are in game but they remain unused.

**Comment by dannno** [comment] 2017-07-27 07:40
good name OP I scoped it
