### ISSUE TITLE
Selling large amounts of minerals directly on cargo shuttle generates infinite money.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#79245] opened 2023-10-24 22:49 UTC
## Round ID:
Reported indirectly through this Skyrat PR https://github.com/Skyrat-SS13/Skyrat-tg/pull/24529

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/10399117/d40955a4-741f-4d68-826a-683f0edba7b0)
Selling materials in bulk directly on the cargo shuttle (more than 400 sheets) generates effectively infinite credits. Most easily done with iron and glass, obviously.

**Comment by SyncIt21** [comment] 2023-10-25 03:09
Merge this  information with #79247. This is a duplicate of that

**Comment by YakumoChen** [comment] 2023-10-25 08:36
Its unrelated?

**Comment by SyncIt21** [comment] 2023-10-25 09:11
> and selling when prices are high makes it too easy to generate absurd amounts of credits

You made this statement in #79247. This issue illustrates that statement so you should post it there and so it's  ery much related

**Comment by Iajret** [comment] 2023-10-25 10:52
Arcane already reported this in https://github.com/tgstation/tgstation/issues/79114
Though, i still surprised no one (even me) reported anything about this bugs.

**Comment by YakumoChen** [comment] 2023-10-25 16:19
> > and selling when prices are high makes it too easy to generate absurd amounts of credits
> 
> You made this statement in #79247. This issue illustrates that so you should post it there and so it's very much related

I was talking about selling materials on the GMM, because its easy to multiply credits with it.

This is an unrelated bug with selling materials on the cargo shuttle, not the GMM

**Comment by jlsnow301** [comment] 2023-10-28 07:51
just looking through the code, it looks like adding a barcode adds the price tag component to every single item in the crate, which then calls on_parent_sold every time. Seems terribly inefficient, wonder if the component could just tally these figures once it's applied

**Closed** 2023-11-18 22:19 UTC
