### ISSUE TITLE
Exploding reagents In stomachs explode at a nonexistent location rather than in the player

### ISSUE THREAD

**Issue by iloveusername** [tgstation/tgstation#54017] opened 2020-09-27 21:04 UTC
Round ID: Tested On An Offline Server Using TG Code

If you were to have someone ingest Nitrous oxide, then light them on fire to heat them up, once the explosion happens, all it does, no matter the amount, is purge the chems and leave a log stating that an explosion has occurred at a non existent location. No damage is done to the player, besides the whole being set on fire part. Chems explode normally in the blood stream, but just not the stomach.

**Comment by TemporalOroboros** [comment] 2020-09-27 21:32
This is being fixed in #53934

**Comment by Dorsisdwarf** [comment] 2020-09-27 21:34
Dupe of #53931 regarding a bug undergoing a fix

**Closed by Dorsisdwarf** 2020-09-27 21:34 UTC
