### ISSUE TITLE
C20 SMG won't fire

### ISSUE THREAD

**Issue by ShadowDimentio** [tgstation/tgstation#31892] opened 2017-10-19 01:06 UTC
The nuker C20 SMG refuses to fire. It had ammo, active hand, everything. I lost a nuker round because my primary weapon straight refused to work. Pretty pissed, fix quickly.

**Comment by Anonmare** [comment] 2017-10-19 01:16
Was it straight up not registering your input or was it saying implant check failure?

**Comment by ShadowDimentio** [comment] 2017-10-19 01:19
It just refused to fire.

**Comment by DaxDupont** [comment] 2017-10-19 08:51
Perhaps this was before the server updated? I put in a fix to fix automatic guns and it was only updated right before I went to bed. 
I just tested it with a local compile and it works fine.

**Comment by DaxDupont** [comment] 2017-10-19 09:02
@ShizCalev I am unable to reproduce, and op didn't put in a server revision.

**Comment by DaxDupont** [comment] 2017-10-19 09:14
Nevermind, found it. Should've been merged and updated. However I still cannot duplicate it.

**Comment by DaxDupont** [comment] 2017-10-19 09:20
Actually I cannot find a single round that has David273 as ckey in it and is nuke ops after the update.
I need more specifics.

**Comment by Bawhoppen** [comment] 2017-10-19 10:08
Sounds like you experienced our now patented JAM feature

**Comment by bgobandit** [comment] 2017-10-20 02:13
@DaxDupont this was yesterday, probably around 9PM-2AM EST, on Sybil

**Comment by DaxDupont** [comment] 2017-10-20 11:24
I am pretty sure this was before the update, since I looked at every nuke ops round after the update and cannot find this ckey.

**Comment by DaxDupont** [comment] 2017-10-20 11:33
Anyways aside from this incident, has anyone else have an issue since this was reported?

**Comment by bgobandit** [comment] 2017-10-21 19:23
@DaxDupont their ckey is david273

**Comment by DaxDupont** [comment] 2017-10-22 21:52
@ShizCalev Since I can't find the round and since there's no more complaints regarding this issue I am gonna guess this was before the update and you can close this since local testing is fine and people would probably be screaming if this was still happening.

**Closed** 2017-10-22 21:53 UTC
Labels: Bug, Needs Reproducing/Testing
