### ISSUE TITLE
Produce Console Deletes Credits on Slow Orders Below the Minimum

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/tgstation#74645] opened 2023-04-10 14:50 UTC
Round: 203506

#The following pull requests are currently test merged:
[#73502: 'Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]' by Zytolg at commit 7ea114086b](https://www.github.com/tgstation/tgstation/pull/73502)
[#74371: 'The North Star Expeditionary Vessel - A Second Wind' by Cheshify at commit 1535edfd36](https://www.github.com/tgstation/tgstation/pull/74371)

Reproduction: Use the produce console, make an order for less than 200 credits on snail mail. 
Expected result: The order fails, but you retain your credits.
Actual result: Your order fails, and you spend your credits as well.

This only happens on orders worth less than your stored credits, otherwise the order will fail, but it will say you don't have enough money to make the order and not remove any. 
For those who care, this specific order was 1 rice, 1 soy sauce, 6 fish filet, and 7 pumpkin. 
This bug happened to me a few other times but I think i forgot to hit post on them lol. 

![image](https://user-images.githubusercontent.com/17058929/230925698-8a1bbbce-e3c6-462b-a850-f5221d1efe2a.png)

**Comment by SyncIt21** [comment] 2023-04-10 17:46
Possibly related to or duplicate of #72536

**Closed** 2023-04-20 00:21 UTC
