### ISSUE TITLE
Reuseable antag items break if a ghost doesn't use them

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#87134] opened 2024-10-09 21:20 UTC
### Client Version:

515.1643

### Issue Summary:

had this one reported to me but apparently if you use a bottle of blood, or a syndicate monkey phone and nobody takes it you can't activate it again for any reason

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Fixes multiple players being picked for the same single-slot command job roundstart.](https://www.github.com/tgstation/tgstation/pull/87005)

### Reproduction Steps:

Spawn in as a wiz
Use a bottle of blood
Nobody takes it
It can no longer be used

**Comment by iprice** [comment] 2024-10-09 22:56
Yeah, this is probably the same issue as this #86760 in that anything that takes a singular ghost tends to break horribly if no-one takes it, usually spawning a catatonic result and marking the items used.  Someone really should fix this one of these days, it's kinda important.

**Comment by deathrobotpunch** [comment] 2024-10-10 02:01
I’m pretty sure you can refund it by inserting it into the uplink

**Comment by Sealed101** [comment] 2024-10-10 06:43
Duplicate of https://github.com/tgstation/tgstation/issues/86760

**Closed** 2024-10-10 06:43 UTC
