### ISSUE TITLE
Check Antagonist panel shows disconnected players as having ghosted

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#17550] opened 2016-05-10 11:59 UTC
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
This is understandably kind of a problem, it should only show *actually ghosted* players as having ghosted, not players who have actually disconnected.

**Comment by bgobandit** [comment] 2016-05-10 14:43
Dupe of https://github.com/tgstation/-tg-station/issues/7482 with more information

**Comment by SnipeDragon** [comment] 2016-06-24 07:14
I'm testing a fix for this now.

**Closed** 2016-08-21 02:20 UTC
Labels: Administration, Priority: High, Usability
