### ISSUE TITLE
Borgs created in a borg factory get the wrong laws in their chat

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#61727] opened 2021-09-27 01:36 UTC
## Round ID:

[170310](https://sb.atlantaned.space/rounds/170310)

## Testmerges:

#61440

## Reproduction:

During this round, I was thrown into a borg factory.

The following laws were printed to my chat: https://i.imgur.com/aqTQFmA.png
The following laws were listed in Robotact: https://i.imgur.com/VvsNpep.png

Given that I was on stock asimov, I opted to immediately kill the borg that just killed me, which likely would be the standard response for any silicon encountering this problem.

**Comment by scriptis** [comment] 2021-09-27 02:08
Also, this seems to have happened because I was at first synced to a second AI on the station (listed in the first screenshot), but then was synced to the malfunctioning AI in the second, without being notified my laws had changed from that transition.

**Comment by timothymtorres** [comment] 2021-09-27 10:07
Duplicate of #44349

**Closed by timothymtorres** 2021-09-27 10:07 UTC

**Comment by hannahscript** [comment] 2022-09-12 18:44
This also happened in round 190361 just now. It led to me killing my fellow borgs who were clearly not asimov, unlike me (not), oops.

**Comment by timothymtorres** [comment] 2022-09-12 18:49
Report it in issue #44349
