### ISSUE TITLE
trying to put a specified amount of a material to the exosuit lathe just puts the entire stack in

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#47543] opened 2019-11-02 07:12 UTC
## Reproduction:
get 50 of a material, slap on exosuit lathe and select a number like 1, see it puts the whole 50 sheets

**Comment by ATH1909** [comment] 2019-11-04 03:59
I like how no one noticed this before because everyone always wants to put the entire stack (that they're holding) in anyway.

Seriously, that menu is kind of annoying.

**Comment by TheVekter** [comment] 2019-11-05 15:21
Reproduced on my end.

**Comment by TheVekter** [comment] 2019-11-18 05:18
I think we can close this? I removed that menu when I converted the mech fab over to work with the ore silo. If you don't want to throw the whole stack in, just use the stack on it and remove what you don't want to use.

**Closed** 2019-12-18 06:28 UTC
Labels: Bug
