### ISSUE TITLE
Nuke's spam admins to hell and back.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#47034] opened 2019-10-12 01:48 UTC
My entire screen is 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Captain's Quarters (115, 128, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Captain's Quarters (115, 129, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Captain's Quarters (115, 131, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Captain's Quarters (115, 132, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Bridge (115, 133, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Bridge (115, 135, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Bridge (115, 137, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Bridge (115, 138, 2) ( JMP ) 
ADMIN LOG:  Explosion with size (0, 0, 0.008, 0) in Courtroom (115, 157, 2) ( JMP ) 

Please for the love of god let me turn it off so i can see chat.

**Comment by PKPenguin321** [comment] 2019-10-12 01:50
Dupe of https://github.com/tgstation/tgstation/issues/47005

**Closed by PKPenguin321** 2019-10-12 01:50 UTC
