### ISSUE TITLE
Vortex Talisman crusher trophy not working

### ISSUE THREAD

**Issue by onjec** [tgstation/tgstation#48751] opened 2020-01-12 17:12 UTC
Issue reported from  Round ID: 128013 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

the barriers spawned by crusher with Vortex Talisman trophy are fully passable by hostile lavaland mobs including megafauna namely Blood drunk miner (didnt had chance to test on others since i died to the Blood drunk), watchers and goliaths

Reporting client version: 513.1505

**Comment by HomocidlePancakes** [comment] 2020-01-12 17:14
Dupe

**Comment by onjec** [comment] 2020-01-12 17:29
picture of goliath walking through a vortex barrier

**Comment by kriskog** [comment] 2020-01-13 09:35
Duplicate of #48712

**Closed by kriskog** 2020-01-13 09:35 UTC
