### ISSUE TITLE
Meatspiked monkey attacked with kitchen knife causes crashes

### ISSUE THREAD

**Issue by ChuckTheSheep** [tgstation/tgstation#35314] opened 2018-02-04 18:44 UTC
[Round ID]: # 83073
[Round ID]: # 83073
[Round ID]: # 83073

[Reproduction]: Strung up a dead monkey onto the meat spike, with friendly intent attacked it with a kitchen knife, instantly crashed twice.

**Comment by 81Denton** [comment] 2018-02-04 20:14
Had the same issue when attacking a non-restrained monkey with a kitchen knife. Pretty inconsistent since I crashed twice but nothing happened afterwards.

**Comment by DaxDupont** [comment] 2018-02-05 13:12
What version of byond, this is important to mention when crashing

**Comment by 81Denton** [comment] 2018-02-05 20:42
512.1401 for me

**Comment by DaxDupont** [comment] 2018-02-05 20:43
512 crashes constantly

**Comment by DaxDupont** [comment] 2018-02-05 20:43
https://github.com/tgstation/tgstation/issues/34862

**Comment by ChuckTheSheep** [comment] 2018-02-06 02:45
512.1403 for me.

**Comment by Jalleo** [comment] 2018-03-19 22:52
@MrStonedOne I presume this is fixed now?

**Comment by kriskog** [comment] 2019-07-20 01:17
Can't reproduce, havent seen or heard of it live. Assume fixed.

**Closed by kriskog** 2019-07-20 01:17 UTC
Labels: Bug, Needs Reproducing
