### ISSUE TITLE
Detective Gun turned invisible

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#28867] opened 2017-06-27 05:30 UTC
I had the det gun on a gold trim and renamed, and it turned invisible at some point after I slipped on soap while holding it. I saw a renamed barman shotgun turn invisible the other shift too.

**Comment by AnturK** [comment] 2017-06-27 07:22
Dupe of #28699

**Closed by AnturK** 2017-06-27 07:22 UTC
