### ISSUE TITLE
Nars-Ian can consume other pets while dead

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53517] opened 2020-09-07 06:30 UTC
![image](https://user-images.githubusercontent.com/42606352/92355332-a107be80-f0a9-11ea-8959-1ee679df4a9c.png)
![image](https://user-images.githubusercontent.com/42606352/92355368-b11f9e00-f0a9-11ea-84d2-a4f9f30574dd.png)

**Comment by Tharcoonvagh** [comment] 2020-09-07 10:22
Fucking cursed

**Comment by Orchian** [comment] 2020-10-27 01:57
What if I made this into a feature, rather than a bug?

**Comment by Neonyxia** [comment] 2021-01-05 19:26
That could actually work. Just add a few lines of dialogue acknowledging it and it would do nicely.

**Comment by timothymtorres** [comment] 2021-08-20 14:44
Duplicate of #57372

**Closed by timothymtorres** 2021-08-20 14:44 UTC
Labels: Bug, Good First Issue

**Comment by Sealed101** [comment] 2023-07-25 14:08
this is not handled by AI, it's a `Life()` proc for him
i am turning this into a feature because butter dog pr clearly doesn't have enough
