### ISSUE TITLE
Imaginary Friend to Dead NPC

### ISSUE THREAD

**Issue by SynnGraffkin** [tgstation/tgstation#45645] opened 2019-08-01 04:58 UTC
Issue reported from  Round ID: 114750 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1463

I accepted a prompt for Imaginary Friend and it was to a dead NPC named Lilliana Powell, according to the Admin Kiteme.

**Comment by Coconutwarrior97** [comment] 2019-08-01 05:55
Duplicate of #45628, imaginary friend is included as a brain trauma.

**Closed by Coconutwarrior97** 2019-08-01 05:55 UTC
