### ISSUE TITLE
Broom + JaniDrobe = NO BROOM

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#50201] opened 2020-03-25 01:10 UTC
## Round ID:
[133011](https://scrubby.melonmesa.com/round/133011)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Take broom from JaniDrobe
Left click on JaniDrobe with broom
BROOMM GONE
NO MORE STOCK OF BROOM

**Comment by Mickyan** [comment] 2020-03-25 01:17
Listen I know the broom was (probably is) a buggy piece of shit but this is a duplicate of #49023 and not broom related

**Comment by dragomagol** [comment] 2020-11-07 23:23
Duplicate of #49023

**Closed by dragomagol** 2020-11-07 23:23 UTC
Labels: Bug
