### ISSUE TITLE
Cyborgs are Unable to See Which Team to Obey on Overthrow

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#40579] opened 2018-09-29 00:08 UTC
In Overthrow, if a team subverts the AI to their side the cyborgs slaved to the AI are unable to tell who to obey. All they get is the SyndOS lawset (Emagged laws minus the law 0 telling you who the syndicate are) and have to rely entirely on the AI to tell them who to obey. Without an AI the borgs are unable to tell who they are supposed to obey or even if the team they are converted to changes.

Issue reported from  Round ID: 94596 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

**Comment by zxaber** [comment] 2018-09-29 02:13
It might be worth also figuring out how the silicons are supposed to fit into the mode. Unless it has changed, the AI becomes a traitor with new laws an everything, but if the laws are reset it doesn't lose its traitor status. So the AI is in a funky position of having objectives, but being unable to really work towards them. Should the AI continue to be a traitor after being reset? Should resetting the AI be impossible (in that it gets malf-level law)? Or is this an intended interaction?

The reason the borgs don't get the objectives told to them is that they're straight up not made into traitors. So there's a disconnect between how the AI and the cyborgs are treated.

I think a better overall system would be that the AI and borgs are all _not_ made into full traitors, but instead get the standard syndi law zero that specifies the leaders of their team as the agents.

**Comment by octareenroon91** [comment] 2018-09-29 02:48
I'm here to support a Law Zero solution.
Can we use ion laws to carry the objectives?

Examples:
````
@@@@. THE SYNDICATE WISHES TO STEAL 28 MOLES OF PLASMA
$$$$. THE SYNDICATE INCLUDES PEOPLE WITH THE FOLLOWING NAMES: [ ...]
````

**Comment by ShizCalev** [comment] 2018-09-29 03:05
Duplicate of #40336

**Closed by ShizCalev** 2018-09-29 03:05 UTC
