### ISSUE TITLE
Megafauna are attacking too frequently

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#64509] opened 2022-01-28 13:17 UTC
## Testmerges:
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9
#64280: 'Ballistic to Energy: Autorifles for Thermal Pistols' by necromanceranne at commit 0b61cefe06

## Reproduction:
get charged by bubblegum
notice in the chat logs:
https://puu.sh/IFwOi/d36c8151e0.png
die immediately because bubbles is dealing double damage

ALSO

get swooped by a drake in its first phase
when it lands it breathes fire, then immediately breathes fire again

**Comment by Striders13** [comment] 2022-01-29 13:04
#63886
Me when refactor pr

**Comment by timothymtorres** [comment] 2022-01-31 19:20
Duplicate of #63886

**Closed by timothymtorres** 2022-01-31 19:20 UTC
