### ISSUE TITLE
Portable chem dispenser won't allow you to dispense select chemicals from beakers with multiple reagents

### ISSUE THREAD

**Issue by RazorManager89** [tgstation/tgstation#67654] opened 2022-06-09 19:25 UTC
## Testmerges
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67385: 'Reduces the point reduction on traitor objectives significantly' by Watermelon914 at commit 9a9f35340b](https://www.github.com/tgstation/tgstation/pull/67385)
[#67116: 'TGUI Say: Upgrades chat input with modern features' by jlsnow301 at commit 9edb8d8709](https://www.github.com/tgstation/tgstation/pull/67116)
[#67615: 'Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to' by Mothblocks at commit 28b5169054](https://www.github.com/tgstation/tgstation/pull/67615)

## Reproduction
Have a beaker inside the portable chem dispenser (obtainable from the medical techfab) with more than 1 reagent in it.  The dispenser will show up as if the beaker had 90u of a single chem, when it's a mix of several healing chems. I expected to be able to select from the mix.
![image](https://user-images.githubusercontent.com/37266586/172927832-9ece9a2b-90c3-43d1-a785-098a8b16a2ff.png)
![image](https://user-images.githubusercontent.com/37266586/172927901-dc0fc25e-e924-4344-ad70-e30f87345550.png)

**Comment by antropod** [comment] 2022-06-10 10:47
Maybe an oversight, but there is a wiki entry for that
https://tgstation13.org/wiki/Guide_to_chemistry#Portable_Chemical_Mixer
`A container with more than one chemical inside will be represented by the most dominant chemical in it. (Try to avoid adding beakers with more than one chemical in them, if you want to stay on the safe side)`

**Comment by timothymtorres** [comment] 2022-06-20 02:06
The wiki specifically says there shouldn't be more than one type of chem in an individual beaker.  Marking this as `Not a bug` and it will be auto-closed in 7 days.

**Closed** 2022-06-28 00:22 UTC
Labels: Not a bug, Cleanup Flagged
