### ISSUE TITLE
Gang members can have implanted status on their SecHUD

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#27005] opened 2017-05-06 23:34 UTC

**Comment by PKPenguin321** [comment] 2017-05-06 23:44
dupe of https://github.com/tgstation/tgstation/issues/27003 ?

**Comment by LanCartwright** [comment] 2017-05-06 23:50
Possibly. Atlanta-ned asked me if i was broken implanted which leads me to suspect there might be a bug all together (if I wasn't showing up as implanted).

**Comment by DaxDupont** [comment] 2017-05-07 23:03
I had someone who was implanted that was listed as gang on round end and was showing as implanted at that time.

**Closed** 2017-09-05 22:57 UTC
Labels: Bug
