### ISSUE TITLE
Syndie MMI + No Law Sync (?) = Duplicating borg shells + MMI loss

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#62199] opened 2021-10-19 00:15 UTC
## Round ID:
[171548](https://scrubby.melonmesa.com/round/171548)

## Testmerges:
Master commit: 6b81b9415b193aba540faab42c897f661a715e67

## Reproduction:

It's a little hard to reproduce, normally I'd do it a second time and document it step by step, however this requires a second "soul" to enact.

Get a soul-ed brain and shove it in a Syndicate MMI

In both actual test cases, the borg was then normally built, MMI-ed, and then dismantled properly (wrench approach).  I doubt this step is important but it might be.

Create a new borg shell and multitool it, In my test I enabled the top two settings, whatever they were, and enabled the AI binding with "Auto" (was done in centcom so didn't find an AI to bind to), and the law sync option was DISABLED.

Once the syndicate MMI was inserted into this new shell, the shell duplicates with no power (you now have two shells, one default-cyborg with no soul attached, shows standby or whatever, as well as the original pre-MMI shell).

The MMI its self becomes part of the contents of the person who inserted it into the borg shell ; not actually in any container or anywhere the player can access, but still inside their contents list, speaks from within the person and thoroughly confuses them.  Get-key can be used to deposit the MMI back on the floor.

In the in game example of this that ocurred I had the player replace the syndie MMI with a normal MMI and it would borg normally after that (some four duplicated shells later).

There seems to be this relevant runtime in the logs too:

>[2021-10-18 23:49:21.160] runtime error: Cannot read null.id
 proc name: attackby (/obj/item/robot_suit/attackby)
   source file: robot_parts.dm,287
   usr: Bob Stange (/mob/living/carbon/human)
   src: the cyborg endoskeleton (/obj/item/robot_suit)
   usr.loc: the floor (166,48,1) (/turf/open/floor/iron)
   src.loc: the floor (166,47,1) (/turf/open/floor/iron)
   call stack:
 the cyborg endoskeleton (/obj/item/robot_suit): attackby(the Syndicate Man-Machine Inte... (/obj/item/mmi/syndie), Bob Stange (/mob/living/carbon/human), "icon-x=16;icon-y=10;left=1;scr...")
 the Syndicate Man-Machine Inte... (/obj/item/mmi/syndie): melee attack chain(Bob Stange (/mob/living/carbon/human), the cyborg endoskeleton (/obj/item/robot_suit), "icon-x=16;icon-y=10;left=1;scr...")
 Bob Stange (/mob/living/carbon/human): ClickOn(the cyborg endoskeleton (/obj/item/robot_suit), "icon-x=16;icon-y=10;left=1;scr...")
 the cyborg endoskeleton (/obj/item/robot_suit): Click(the floor (166,47,1) (/turf/open/floor/iron), "mapwindow.map", "icon-x=16;icon-y=10;left=1;scr...")
 Iain0 (/client): Click(the cyborg endoskeleton (/obj/item/robot_suit), the floor (166,47,1) (/turf/open/floor/iron), "mapwindow.map", "icon-x=16;icon-y=10;left=1;scr...")

**Comment by Sealed101** [comment] 2024-10-03 21:39
could not reproduce, fixed by https://github.com/tgstation/tgstation/pull/66633 or https://github.com/tgstation/tgstation/pull/66636 perhaps?
@iprice any other insight perhaps? i don't think the code changes were actually related, maybe i'm missing a step?

**Comment by iprice** [comment] 2024-10-05 01:53
Tried this the other day too and couldn't get it to reproduce, probably fixed randomly in the last 3 years, fine with this being closed off, cheers.

**Closed** 2024-10-05 01:58 UTC
Labels: Bug, Needs Reproducing, Cleanup Flagged
