### ISSUE TITLE
Proximity Sensors, Signalers, and ect. can all be activated by ghosts.

### ISSUE THREAD

**Issue by RogueSteampunker** [tgstation/tgstation#38718] opened 2018-06-25 04:04 UTC
Issue reported from  Round ID: 90009 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Proximity sensors can be triggered on and off by ghosts, and signalers can be actively changed and signaled with.

**Comment by SpaceManiac** [comment] 2018-06-25 05:51
Duplicate of #38717

**Closed by SpaceManiac** 2018-06-25 05:51 UTC
Labels: Bug
