### ISSUE TITLE
AI shell duplication

### ISSUE THREAD

**Issue by Okshi91** [tgstation/tgstation#46737] opened 2019-09-25 11:20 UTC
Issue reported from  Round ID: 120052 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1485

So, I was playing AI, and someone made me a shell. They put the shell on the floor, and put a B.O.R.I.S. module in, as normal, but instead of deleting the unfinished shell, it made a new functioning AI shell without a cell.
To reproduce:
Build cyborg shell
Insert B.O.R.I.S. module
An AI shell will then spawn in that tile without a power cell, and the cyborg shell will remain on the floor, ready to have another B.O.R.I.S. module or MMI put in.

**Comment by ATH1909** [comment] 2019-09-25 19:13
👀

**Comment by Firecage** [comment] 2019-09-25 21:48
I tested this and was unable to reproduce this.

**Comment by kopoba** [comment] 2019-09-26 06:57
> 
> 
> I tested this and was unable to reproduce this.

its rarely event. But ive seen it before. I think there is another related bug(or same) he looks like this
When you start constructing machine and all parts is under machine frame you alt-click title under frame so you see list of stuff on that tittle in right top window. If you start picking part and insert then in machine fast enough in top right window you will end up with constructed machine that don't require parts and you can finish with screwdriver and PARTS that must be in machine but didn't goes in cause game thinks its already full with this part. When you try to check with parts in machine with rped it will say that it has only stock parts that you really insert. 
So same will work with endoskeleton construction if you start attaching borg limbs/parts to chassis  fast enough you will end up with spare parts and completed cyborg body.

**Comment by Chessus** [comment] 2019-10-04 08:14
Can confirm this happened to me an AUStation an hour ago. but I think my AI shell had a powercell and cyborg didnt

**Comment by timothymtorres** [comment] 2021-08-19 14:06
I believe this was fixed with #52544 and looks like a duplicate of #52542.

**Closed by timothymtorres** 2021-08-19 14:06 UTC
Labels: Bug
