### ISSUE TITLE
Food cart deployed segments invisible if deployed before launch and redeployed after

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#71308] opened 2022-11-16 21:01 UTC
Reporting client version: 514.1588

## Round ID:
[194459](https://scrubby.melonmesa.com/round/194459)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)

## Reproduction:
1. Open the food cart before the emergency shuttle takes off.
2. Witness the food cart break itself upon launch
3. Try to open the food cart again after the shuttle has launched
4. The food cart deploys, but is invisible.

**Comment by timothymtorres** [comment] 2022-11-18 01:41
Duplicate of #61862

**Closed by timothymtorres** 2022-11-18 01:41 UTC
