### ISSUE TITLE
Instant summon spell lets you use marked items as any type of mob.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#22616] opened 2016-12-31 19:56 UTC
Mark an item and change/get changed into a different mob like an alien hunter or an ash drake, summon the item and bam, you can use that item.

**Comment by lzimann** [comment] 2016-12-31 20:09
Should probably drop the item on the floor if the mob doesn't have hands.

**Comment by PKPenguin321** [comment] 2016-12-31 20:11
High priority

**Comment by Mindustry** [comment] 2016-12-31 20:30
It also allows you to hold two handed things in one hand, but I'm not sure if #22457 fixed that

**Comment by Incoming5643** [comment] 2017-01-01 05:10
This is wonderful

**Comment by PKPenguin321** [comment] 2017-02-06 01:21
Reopened why? Was this not actually fixed by those two PRs?

**Comment by kriskog** [comment] 2019-06-26 07:15
Can't reproduce, should be fixed.

**Closed by kriskog** 2019-06-26 07:15 UTC
Labels: Bug, In Game Exploit
