### ISSUE TITLE
Positronic with a hearing problem

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#73624] opened 2023-02-24 12:04 UTC
Reporting client version: 514.1589

## Round ID:
[200697](https://scrubby.melonmesa.com/round/200697)

## Reproduction:
Be a positronic brain, get put into a Gygax mech. (the type might not matter but in this round it was this)
Get that mech destroyed, dropping you on the floor
Be unable to hear, get spammed with "... You can almost hear something ..." instead
(reporting this for someone else in the round who doesn't have a github, they got back to me with extra details but I definitely don't know the reason why it happens)

**Comment by mc-oofert** [comment] 2023-02-25 07:14
#57217 probably duplicate of

**Closed** 2023-02-26 06:46 UTC
Labels: Bug, Tested/Reproduced
