### ISSUE TITLE
Mech walikng on the turfs with lights in them breaks the lightning

### ISSUE THREAD

**Issue by Core0verload** [tgstation/tgstation#17271] opened 2016-04-30 07:02 UTC
1. Have a stompy mech.
2. Walk it to the tile with wall-mounted light
3. See the light darken.
4. Walk away.
5. Light is still dark.

Looks like opaque moveable objects annoy the fuck out of our lightning system.

**Comment by phil235** [comment] 2016-04-30 10:17
Duplicate of #16927

**Comment by phil235** [comment] 2016-05-25 18:21
Probably not the same issue after all, since I can't reproduce the smoke bug, but the mech bug is still there.

**Closed** 2016-06-24 09:57 UTC
