### ISSUE TITLE
Could not purchase gas canisters at cargo terminal

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#58026] opened 2021-03-29 03:39 UTC
Reporting client version: 514.1548

## Round ID:
[159162](https://scrubby.melonmesa.com/round/159162)

## Testmerges:
- [Layer overhaul](https://www.github.com/tgstation/tgstation/pull/57915)

## Reproduction:
1. Open up the cargo ordering console
2. Navigate to the "Canisters and Materials" subsection
3. Attempt to order any of the gas canisters on offer.
4. Realize that none of them are being registered as orders.

**Comment by TemporalOroboros** [comment] 2021-03-29 03:41
I suspect that this was caused by #57844 @ninjanomnom

**Comment by MrMelbert** [comment] 2021-03-29 05:30
dupe of #57954

**Closed** 2021-03-31 06:48 UTC
