### ISSUE TITLE
Dynamic midround ruleset runtime causes threat to be spent but no mob to be spawned

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69327] opened 2022-08-20 01:09 UTC
## Round ID:
[188860](https://scrubby.melonmesa.com/round/188860)

## Testmerges:
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ](https://www.github.com/tgstation/tgstation/pull/69084)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/185723097-58b215a9-6516-452c-8485-f5e0542166a7.png)

Spawn revenant rolled, and two people definitely said yes to it. But it seems like it runtime error'd when creating a mob, causing the threat to spend but no mob to be created.

**Comment by iprice** [comment] 2022-08-20 23:24
Seems I filed a dupe of this probably

Round: [188924](https://scrubby.melonmesa.com/round/188924)

```
[2022-08-20 22:55:53.195] runtime error: Cannot read null.key
 - proc name: generate ruleset body (/datum/dynamic_ruleset/midround/from_ghosts/revenant/generate_ruleset_body)
 -   source file: dynamic_rulesets_midround.dm,822
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): generate ruleset body(null)
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
 - 
[2022-08-20 22:55:53.196] runtime error: Cannot read null.mind
 - proc name: finish setup (/datum/dynamic_ruleset/midround/from_ghosts/proc/finish_setup)
 -   source file: dynamic_rulesets_midround.dm,179
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish setup(null, 1)
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
 - 
[2022-08-20 22:55:53.196] runtime error: Cannot read null.name
 - proc name: finish applications (/datum/dynamic_ruleset/midround/from_ghosts/proc/finish_applications)
 -   source file: dynamic_rulesets_midround.dm,169
 -   usr: null
 -   src: Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant)
 -   call stack:
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): finish applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): review applications()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): send applications(/list (/list))
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute midround latejoin rule(Revenant (/datum/dynamic_ruleset/midround/from_ghosts/revenant))
 - /datum/callback (/datum/callback): InvokeAsync()
```

**Closed** 2023-06-18 03:40 UTC
Labels: Bug, Runtime
