### ISSUE TITLE
Alternate Human Names do not implement 

### ISSUE THREAD

**Issue by jeanlafite** [tgstation/tgstation#61792] opened 2021-09-30 06:47 UTC
## Round ID: 
[170485](https://scrubby.melonmesa.com/round/170485)

## Reproduction:
When selecting a Head of Staff position; Captain, CE, HOP, etc; from a lizard character alternate human name will not apply. Game instead gives lizard or other nonhuman name to the human mob.

**Comment by Mooshimi** [comment] 2021-09-30 17:44
Yes, I've seen this with plasmamen as well

**Comment by dragomagol** [comment] 2021-10-01 03:04
Duplicate of #60795

**Closed by dragomagol** 2021-10-01 03:04 UTC
