### ISSUE TITLE
Sec Starting w/out Tasers

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#38714] opened 2018-06-25 02:27 UTC
[Round ID]: # 90007

[Reproduction]: Started round as sec, I didn't have a taser. Dunno if the others officers had one or not.

**Comment by wesoda25** [comment] 2018-06-25 02:32
Update: no officers had a taser

**Comment by wesoda25** [comment] 2018-06-25 02:35
Update pt 2: issue with armor. Upon getting a taser, I couldn't equip it to my armor vest. (same for an energy gun)

**Comment by AlexTheSysop42** [comment] 2018-06-25 02:43
Dupe of #38706

**Comment by SpaceManiac** [comment] 2018-06-25 03:17
Duplicate of #38706

**Closed by SpaceManiac** 2018-06-25 03:17 UTC
