### ISSUE TITLE
Fat Speed Debuff is delayed

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#51158] opened 2020-05-18 19:09 UTC
Eat some food and get fat, walk around for a while without the debuff even though you're fat until it eventually kicks in. Then once you are no longer fat, it once again takes a long time for your speed to return to normal as the debuff will stay for some time after no longer being fat.

**Comment by HomocidlePancakes** [comment] 2020-05-21 12:37
Seems intentional. It even sends a message in chat once the debuff kicks in/out.

**Comment by timothymtorres** [comment] 2021-12-30 01:27
Marking this as not a bug and it will auto close the issue in 7 days.

**Closed** 2022-01-12 09:06 UTC
Labels: Not a bug
