### ISSUE TITLE
suiciding in a way that gibs you while wearing a hardsuit produces a hardsuit helmet item

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#53021] opened 2020-08-17 23:32 UTC
![image](https://user-images.githubusercontent.com/20996272/90453781-73060e80-e0e9-11ea-846b-e3159b38c489.png)
![image](https://user-images.githubusercontent.com/20996272/90453817-874a0b80-e0e9-11ea-8b2c-fb000e7e897f.png)
it seems to retract out of existence when clicked or when the hardsuit is picked up, but it existing at all when the suit isn't worn is weird

**Comment by Fikou** [comment] 2020-08-19 09:43
i think gibbing does not call dropped() on the items so the retract proc is never called

**Comment by nightred** [comment] 2020-08-20 02:12
I am not able to reproduce this.
I have tried all the suicides I could find.
Please provide the exact suicide type.

**Comment by factoryman942** [comment] 2020-08-20 07:06
hardsuit w/ helmet worn, oxytank suicide

**Comment by nightred** [comment] 2020-08-20 13:24
Gib() does call dropped().
Unable to reproduce on current build.
![image](https://user-images.githubusercontent.com/6491940/90775540-9504ba00-e2be-11ea-9bc7-dcc01497b094.png)

**Comment by Couls** [comment] 2020-09-18 15:18
closing since this hasn't been reproduced

**Closed by Couls** 2020-09-18 15:18 UTC
Labels: Bug, Needs Reproducing
