### ISSUE TITLE
you lose  your ghost and a whole load of shit goes haywire when you're a sentient pirate/space and you die

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#23863] opened 2017-02-08 15:55 UTC
- `(/mob/living/simple_animal/hostile/pirate/space)
- [18:53:08]  src.loc: null
- [18:53:08]  call stack:
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): update sight()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): reset perspective(null)
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/dead/observer): Re-enter Corpse()
- [18:53:08]Space Pirate (/mob/dead/observer): DblClickOn(Space Pirate (/mob/living/simple_animal/hostile/pirate/space), "icon-x=14;icon-y=19;left=1;scr...")
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): DblClick(the floor (94,141,1) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=14;icon-y=19;left=1;scr...")
- runtime error: 
- [18:53:08]Cannot execute null.get remote view fullscreens().
- [18:53:08]proc name: reset perspective (/mob/living/reset_perspective)
- [18:53:08]  source file: mob.dm,256
- [18:53:08]  usr: (src)
- [18:53:08]  src: Space Pirate (/mob/living/simple_animal/hostile/pirate/space)
- [18:53:08]  src.loc: null
- [18:53:08]  call stack:
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): reset perspective(null)
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/dead/observer): Re-enter Corpse()
- [18:53:08]Space Pirate (/mob/dead/observer): DblClickOn(Space Pirate (/mob/living/simple_animal/hostile/pirate/space), "icon-x=14;icon-y=19;left=1;scr...")
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): DblClick(the floor (94,141,1) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=14;icon-y=19;left=1;scr...")
- runtime error: 
- [18:53:08]Cannot read null.prefs
- [18:53:08]proc name: Login (/mob/dead/observer/Login)
- [18:53:08]  source file: login.dm,4
- [18:53:08]  usr: (src)
- [18:53:08]  src: Space Pirate (/mob/dead/observer)
- [18:53:08]  src.loc: null
- [18:53:08]  call stack:
- [18:53:08]Space Pirate (/mob/dead/observer): Login()
- runtime error: 
- [18:53:08]Cannot read null.len
- [18:53:08]proc name: update client colour (/mob/proc/update_client_colour)
- [18:53:08]  source file: client_colour.dm,64
- [18:53:08]  usr: (src)
- [18:53:08]  src: Space Pirate (/mob/living/simple_animal/hostile/pirate/space)
- [18:53:08]  src.loc: null
- [18:53:08]  call stack:
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): update client colour()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- [18:53:08]Space Pirate (/mob/living/simple_animal/hostile/pirate/space): Login()
- runtime error: 
- [18:53:11]Cannot read null.z
- [18:53:11]proc name: params2turf (/proc/params2turf)
- [18:53:11]  source file: unsorted.dm,896
- [18:53:11]  usr: Space Pirate (/mob/living/simple_animal/hostile/pirate/space)
- [18:53:11]  src: null
- [18:53:11]  usr.loc: null
- [18:53:11]  call stack:
- [18:53:11]params2turf("8:7,9:1", null)
- [18:53:11] (/obj/screen/click_catcher): Click(null, "mapwindow.map", "icon-x=16;icon-y=17;left=1;scr...")
- Stopped server.`

**Comment by RandomMarine** [comment] 2017-02-09 03:49
Those fucking pirates shit out runtimes in general whenever their ruins spawn in my test sessions.

**Comment by Cyberboss** [comment] 2017-02-13 17:33
Fuck pirates I can never solve their shit

**Comment by timothymtorres** [comment] 2021-08-24 09:29
Duplicate of #22796

**Closed by timothymtorres** 2021-08-24 09:29 UTC
Labels: Runtime
