### ISSUE TITLE
tgui/popup Whitescreen Megaissue

### ISSUE THREAD

**Issue by actioninja** [tgstation/tgstation#47793] opened 2019-11-15 01:23 UTC
This is a pretty common issue with unknown causes, and happens on both legacy tgui and tgui-next, as well as sporadically on browser windows.

Likely some kind of byond issue but if the cause could be nailed down it would be extremely useful.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/5194834/68909332-ce424500-0702-11ea-915c-702bdea14768.png)

Close issue and link them here if it's the same whitescreen issue. Comment with relevant conditions if you figure something out.

Dupe issues:
#44350
#46660
#31745

## Reproduction:

Unknown what conditions cause it

**Comment by Tlaltecuhtli** [comment] 2019-11-15 16:35
for me, it triggers almost every time i press a botton in the id changing console (white internet explorer window with 1.0.0.127:1234 cant reach website) and sometimes in rnd console, i dont remember it happenning anywhere

**Comment by Tlaltecuhtli** [comment] 2019-11-15 16:37
on a window or whole screen? it happens almost every time i press a botton on id console window

**Comment by Chessus** [comment] 2019-11-17 10:26
> on a window or whole screen? it happens almost every time i press a botton on id console window

I've only experienced this about 2 days ago and today. Never had it before. Closing/reconnecting doesn't help.

**Comment by Chessus** [comment] 2019-11-19 09:54
http://www.byond.com/forum/post/2211145&page=2 

According to this using the Fix Chat option helps. I can say it does but only a temp fix. I do not know if the next screen will be correct or not. 

Also spamming the Changelog could help but I have not tested that yet. I started only getting this issue on the 16th/17

**Comment by Chessus** [comment] 2019-11-22 02:35
Okay so clearing my IE cache seemed to fix this issue.

**Comment by spookydonut** [comment] 2019-11-24 15:19
This might have happened recently on tgmc

**Comment by Pugie** [comment] 2020-04-07 21:46
This is getting really bad now it's basically 90% of all tgui tabs that are opened white screen now, been having this problem on both EU servers.

**Comment by optimumtact** [comment] 2020-04-09 04:08
```
Reproduction:

Unknown what conditions cause it
```

**Comment by stylemistake** [comment] 2020-04-20 18:44
We have a lot of countermeasures for whitescreens now. If whitescreen-causing bug happens, it should be a bluescreen now instead (with proper stack traces).

**Comment by actioninja** [comment] 2020-05-02 01:16
> We have a lot of countermeasures for whitescreens now. If whitescreen-causing bug happens, it should be a bluescreen now instead (with proper stack traces).

This is a bug that doesn't just happen due to clientside errors it's also some kind of byond issue as well unfortunately.

**Comment by stylemistake** [comment] 2020-05-02 01:27
Mmmmyes, possibly assets get stuck and don't appear in the cache.

**Comment by stylemistake** [comment] 2020-09-05 19:22
Related to #50480

**Comment by stylemistake** [comment] 2020-11-23 01:37
Related PRs: #54895, #54971

An attempt to make TGUI more robust in regards to whitescreens.

**Comment by timothymtorres** [comment] 2021-12-21 22:48
I just searched for relevant open white screen issues and I haven’t seen any newly opened ones since https://github.com/tgstation/tgstation/pull/54895 was made.  I’m marking this with the `Cleanup` label that should auto close it in 7 days.

**Closed** 2021-12-29 03:42 UTC
Labels: Bug, Higgs-Bugson, BYOND Issue, UI, Cleanup Flagged

**Comment by KILLAKAN10** [comment] 2023-11-12 00:59
I think it's happening again, any window become solid white, no borders, unmovable, uninteractable, lobby buttons work otherwise, windows like policy, discord verify, fix chat, seem to function as intended. I'm vaguely aware that Internet explorer is used for the ui, on this box it's been permanently disabled as of an edge update in 2022.
