### ISSUE TITLE
Null became heretic

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#76969] opened 2023-07-20 02:00 UTC
Reporting client version: 514.1589

## Round ID:
[210603](https://scrubby.melonmesa.com/round/210603)

## Reproduction:

No idea, check the round logs, fingers crossed and all that

Relevant
```
[2023-07-19 22:35:47.472] RUNTIME: runtime error: Cannot execute null.playsound local().
 - proc name: on gain (/datum/antagonist/heretic/on_gain)
 -   source file: code/modules/antagonists/heretic/heretic_antag.dm,181
 -   usr: null
 -   src: Heretic (/datum/antagonist/heretic)
 -   call stack:
 - Heretic (/datum/antagonist/heretic): on gain()
 - /datum/mind (/datum/mind): add antag datum(Heretic (/datum/antagonist/heretic), null)
 - /datum/mind (/datum/mind): add antag datum(Heretic (/datum/antagonist/heretic), null)
 - Heretics (/datum/dynamic_ruleset/roundstart/heretics): execute()
 - /datum/game_mode/dynamic (/datum/game_mode/dynamic): execute roundstart rule(Heretics (/datum/dynamic_ruleset/roundstart/heretics))
 - /datum/callback (/datum/callback): InvokeAsync()
 - Timer (/datum/controller/subsystem/timer): fire(1)
 - Timer (/datum/controller/subsystem/timer): ignite(1)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
```

and

![image](https://github.com/tgstation/tgstation/assets/3789327/49c47cb1-2e2e-4643-8b0c-bc3d6fbd22b0)

**Comment by MrMelbert** [comment] 2023-07-20 04:33
Perhaps related to #57977

**Comment by distributivgesetz** [comment] 2023-07-23 11:12
![image](https://github.com/tgstation/tgstation/assets/47710522/a7886e1e-4aad-4774-a169-42b96b097378)
I'd say this is very likely the same as #57977, as the same confusing log is also appearing for this error

**Comment by distributivgesetz** [comment] 2023-07-23 11:42
Yeah, I can confirm that this is a duplicate of #57977, so I'll close this issue for now

**Closed by distributivgesetz** 2023-07-23 11:42 UTC
