### ISSUE TITLE
Syndicate Radio Implant prevents you from talking over non-common channels.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#37047] opened 2018-04-08 04:54 UTC
After installing the implant, I was unable to speak over any channels besides common. Even with a captain level headset. 

There's no way of disabling this, and from what I know of the implant can't be surgically removed.

**Comment by factoryman942** [comment] 2018-04-08 07:01
#36522 #36981 #34136 aaaaaaaaaaaa

**Comment by AlexTheSysop42** [comment] 2018-04-10 13:53
@ShizCalev dupe(s)

**Comment by ShizCalev** [comment] 2018-04-10 19:34
Duplicate of #34136

**Closed by ShizCalev** 2018-04-10 19:34 UTC
