### ISSUE TITLE
Custom Shuttle Placement with White Ship Gone Wrong (Gone Sexual!)

### ISSUE THREAD

**Issue by Neuroplasty** [tgstation/tgstation#31485] opened 2017-10-09 02:45 UTC
Issue reported from Round ID: 77188 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Upon rotating the white ship with the custom console and sticking us backwards in the aux docks, the ship was spun 180 degrees and after that only the outermost 1 wide layer of walls and airlocks on the docking side of the ship would move, and the rest of the ship was left marooned.

**Comment by ShizCalev** [comment] 2017-10-09 03:01
@ninjanomnom

**Comment by ninjanomnom** [comment] 2017-10-13 07:18
duplicate of #31486 and also I can't replicate it

**Comment by AnturK** [comment] 2017-10-13 08:04
Duplicate of #31486

**Closed by AnturK** 2017-10-13 08:04 UTC
Labels: Bug
