### ISSUE TITLE
Multiple bombs going off in a small area can incorrectly set a turf's explosion_level

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#25798] opened 2017-04-02 02:13 UTC
Nothing makes sure affected turfs have the same explosion_id as the explosion that's setting their explosion_level to 0.

**Comment by Cyberboss** [comment] 2017-04-19 14:26
I'm not sure if this is really a bug, the way it's designed is if two explosions come across each other. The explosion_level will be first set to the most devastating explosion, then they will both try to unset it at some point. If you're between two explosions it should be impossible to dodge them either way.

**Comment by timothymtorres** [comment] 2021-08-24 12:40
Duplicate of #49840

**Closed by timothymtorres** 2021-08-24 12:40 UTC
Labels: Bug

**Comment by timothymtorres** [comment] 2021-08-24 12:44
Also #57493 removed explosion_ids
