### ISSUE TITLE
All languages other than Galactic Common are prone to not working

### ISSUE THREAD

**Issue by tortellinitony** [tgstation/tgstation#29776] opened 2017-08-07 22:20 UTC
This has occurred with several languages, but I initially spotted it with Beachtongue. Someone on Hippie Station just reported that it is happening with drones now, too. I tested it and found that no language other than Galcom works. When you speak in the language, nothing appears in the chat (but you do get a speech bubble)! Radio, normal, whisper, and any other type of speech does not work! Switching to the old chat instead of Goonchat does not work either!

See also:
#28498
#29762

**Comment by Darkgenerallord** [comment] 2017-08-08 03:13
Just had it happen with some ashwalkers.

**Comment by PraiseRatvar** [comment] 2017-08-09 10:10
dronespeak works

**Comment by AnturK** [comment] 2017-08-09 11:28
Likely caused by #29690 (language icons)

**Comment by MrStonedOne** [comment] 2017-08-10 03:12
as somebody who has never worked with languages and never plays

I need steps on reproducing, and on debug tools to fuck around with languages so i can figure this out

**Comment by Iamgoofball** [comment] 2017-08-10 17:51
@MrStonedOne 
admins can grant languages to themselves from the language button in the bottom-middle-right of your hud

**Comment by MrStonedOne** [comment] 2017-08-13 15:30
this should be fixed

**Closed** 2017-08-13 15:33 UTC
Labels: Bug
