### ISSUE TITLE
Uranium Carving Blocks Put Out Obscene Radiation 

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54141] opened 2020-10-02 01:23 UTC
## Reproduction:

1). Craft a **uranium** carving block
`/obj/structure/carving_block`
2). Drag it around.
3). Create stupid levels of radiation.

I don't like this PTSD I'm experiencing get me off this ride.

![radiation](https://user-images.githubusercontent.com/46318638/94878521-aa2b4780-042b-11eb-8554-e4f0f3fcbbb1.png)

**Comment by TemporalOroboros** [comment] 2020-10-02 06:23
Uranium carving blocks generate just barely enough radiation to contaminate objects. Actually, I think they generate exactly enough to do so.

**Comment by TemporalOroboros** [comment] 2020-10-02 06:30
The number you're seeing in VV is how irradiated the mob is, not how radioactive the mob is. The mob is probably not actually that radioactive.

**Comment by Misdoubtful** [comment] 2020-10-02 13:05
Oh yeah I completely understand, its more so a show piece that the rad strength at work here is a bit OTT.

**Comment by Barhandar** [comment] 2020-10-03 12:19
>Oh yeah I completely understand, its more so a show piece that the rad strength at work here is a bit OTT.

You clearly missed the original radiation, where a single engineer leaving CO2 SME chamber and going to station was absolute fuckdeath to everyone.

The problem isn't **only** uranium blocks irradiating like hell, the problem is that all of the ways of dealing with radiation suck big time. You need absolute BOATLOADS of potiod to drop radiation levels to safety. Per person per rad encounter. And if people are getting irradiated, you'll get an entire crew with rads and lots of contaminated objects all over the place re-radiating them.

Also I don't know of any ways but time for dealing with contaminated objects.

**Comment by Misdoubtful** [comment] 2020-10-03 13:50
> > Oh yeah I completely understand, its more so a show piece that the rad strength at work here is a bit OTT.
> 
> You clearly missed the original radiation, where a single engineer leaving CO2 SME chamber and going to station was absolute fuckdeath to everyone.
> 
> The problem isn't **only** uranium blocks irradiating like hell, the problem is that all of the ways of _dealing_ with radiation suck big time. You need absolute BOATLOADS of potiod to drop radiation levels to safety. Per person per rad encounter. And if people are getting irradiated, you'll get an entire crew with rads and lots of contaminated objects all over the place re-radiating them.
> 
> Also I don't know of any ways but time for dealing with contaminated objects.

You have successfully missed the point by quoting an old fixed issue from a long time passed, that has no bearing on the rad strength of uranium and items made out of uranium. Nor is this issue about curing radiation, it is about the radiation strength of a uranium carving block, and by extension the radiation brought by the materials crafting datum.

**Let me clarify the issue here:**

A uranium sheet provides 1 radioactive strength.

Even as a full 50 stack of sheets the radiation provided stays at 50 strength. This does not result in a gain of rads for mobs nearby.

A standard created statue made of uranium does not possess the radioactive component at all.

A chair made of uranium for 1 sheet provides 100 strength.

And when 5 uranium are put into a uranium carving block the radioactive strength jumps to 500 strength.

**The system works as intended with 100 strength per sheet put into the crafted object with the recent material datums crafting, but why is this gain of 100 per sheet attached?** 

**Does this mean if a crafting recipe gets added that required 10 sheets that an easy 1000 rad strength item will also exist? Jumping from 5 rad strength to 500 is incredibly over tuned.**

**Comment by Mickyan** [comment] 2020-10-03 15:11
This is indeed a bug/oversight, just so we're abundantly clear. Balance concerns about radiation in general are irrelevant.

![Screenshot_1](https://user-images.githubusercontent.com/38563876/94994774-3bb8c780-059a-11eb-9f62-2ccf6056d7c7.png)
![Screenshot_2](https://user-images.githubusercontent.com/38563876/94994929-0cef2100-059b-11eb-83f3-2ce8ffbf27e8.png)

We had similar issues in the past with uranium items but I can't remember the details or how they were solved, maybe @Qustinnus knows

**Comment by TemporalOroboros** [comment] 2020-10-04 01:46
Uranium sheets have a 0.01 multiplier for rad strength, so that a stack of 50 isn't more radioactive than the supermatter.

**Comment by TemporalOroboros** [comment] 2020-10-04 01:48
If this wasn't used a single uranium sheet would have a rad strength of 100 and a stack of 50 would have a radiation strength of 5000.

**Comment by TemporalOroboros** [comment] 2020-10-04 01:54
To clarify: the uranium material, by default, adds 0.05 units of radiation power per unit of material to any object it is applied to. Any stack multiplies the effect of any material they are made of by 0.01. The radiant power of objects made of uranium, such as furniture and statues is the intended radioactive strength of uranium. Sheets are just reduced in power so you can't cart around a bluespace bodybag full of two dozen 50 stacks of uranium sheets and irradiate the fabric of space and time.

**Comment by Misdoubtful** [comment] 2020-10-04 02:00
Thanks for the clarification on this, I didn't really take the time to dig too far into this, just surface level stuff.

**Comment by Qustinnus** [comment] 2020-10-04 11:38
Sheets provide lower radiation because otherwise you could not move uranium in any way possible without making an overly radioactive item. This isn't a bug, it's how datum materials work. Sheets are not supposed to be the base-line of how much materials should do because a 50 stack sheet would have 100k of a material in it, which would be completely ridiculous if it had the full effects of 100k materials. If you want to lower it you can make a PR that lowers how much effect materials have on statues, but it shouldn't be as little as sheets.

**Comment by ArcaneMusic** [comment] 2020-11-02 16:55
Was this resolved in #54178?

**Comment by Qustinnus** [comment] 2020-11-02 17:39
yhes

**Closed by Qustinnus** 2020-11-02 17:39 UTC
