### ISSUE TITLE
Some gas miners don't distribute moles properly

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35529] opened 2018-02-11 07:10 UTC
![image](https://user-images.githubusercontent.com/16315400/36070797-b8ba384a-0ed0-11e8-87dc-970258efff3f.png)
This one is in the cat SAW space ruin. The tile with the miner is at 6000kpa, the other 3 are at vacuum.

**Comment by YPOQ** [comment] 2018-02-11 09:38
#34000

**Comment by ShizCalev** [comment] 2018-02-11 17:23
duplicate of #34000

**Closed by ShizCalev** 2018-02-11 17:23 UTC
