### ISSUE TITLE
[quin materials] cant eject minerals from lathe feature or bug?

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45196] opened 2019-07-15 10:39 UTC
minerals dont get ejected from lathe
#45118

**Comment by nemvar** [comment] 2019-07-15 11:06
What lathe? What material? Details?

**Comment by kriskog** [comment] 2019-07-15 14:49
You issue report is bad. No round ID, lacking information, and even if you think reproduction is obvious you should be including a few words on it. Follow the template, I'll be closing all of yours that dont from now on.

If you need an example of how to do it, see #45194. This is also a dupe of that.

**Closed by kriskog** 2019-07-15 14:49 UTC
