### ISSUE TITLE
Rusted tiles and walls created by Rust Heretics don't actually look rusty, and leave behind small "runelets"

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#61421] opened 2021-09-12 07:03 UTC
## Reproduction:

As a Rust Heretic, using the mansus grasp or really anything that spreads rust successfully makes things rusty, but both plating and walls don't visually update to reflect the fact they are rusty. Examining the surface confirms that they are rusted. Rust Heretics can heal off of rusted plating just fine as well.

Additionally, it looks like what I think the last frame of the rusting animation seems to linger on the tile, which can look a little odd, looks like little circles.

Example below. Tiles are rusted but don't appear as such, and the little runes that linger from the animation.
![dreamseeker_baAVwzJd8e](https://user-images.githubusercontent.com/33107541/132977103-6997897e-fb88-42ad-9038-408228e6afc6.png)

**Comment by timothymtorres** [comment] 2021-09-12 08:21
Duplicate of #58846

**Comment by Potato-Masher** [comment] 2021-09-12 17:48
How is this a duplicate of that issue??? This is about visibility of rust on objects!

**Comment by timothymtorres** [comment] 2021-09-12 17:50
I thought it was the same bug involving rust objects since in both cases the rust doesn’t display.

**Comment by Potato-Masher** [comment] 2021-09-12 17:55
Perhaps, but that issue was logged before this PR #59977 which I suspect to be part of the issue here. In the picture in that issue, the rusted tiles below the rune itself are actually visibly rusted.

**Closed** 2022-01-07 11:42 UTC
Labels: Sprites, Bug
