### ISSUE TITLE
You can crowbar yourself into unpowered holopads

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#84745] opened 2024-07-07 16:18 UTC
## Issue Summary
If a holopad in unpowered you can crowbar it while standing on top to go inside the holopad.

## Reproduction:
Stand on top of a holopad in an unpowered room and crowbar it

**Comment by GPeckman** [comment] 2024-07-07 16:22
Duplicate of #80183

**Closed** 2024-07-07 16:55 UTC
