### ISSUE TITLE
You are unable to use resist button or hotkey to unbuckle yourself

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#82645] opened 2024-04-13 13:13 UTC
Reporting client version: 515.1633

## Round ID:
[227139](https://scrubby.melonmesa.com/round/227139)

## Testmerges:
- [Admin Verb Datums MkIII | Now with functional command bar](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:
buckle, press B, it doesnt unbuckle

**Comment by Dorsisdwarf** [comment] 2024-04-13 13:58
Duplicate of #82634 , fix is already up

**Closed by Dorsisdwarf** 2024-04-13 13:58 UTC
