### ISSUE TITLE
Liches that are gibbed seem to lose their spells on respawn

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25490] opened 2017-03-25 15:13 UTC
Gotta test this locally, I swear it didn't happen when I tested, but I did test with SM disintegration.

**Comment by Incoming5643** [comment] 2017-03-26 03:30
Coiax this is exactly why the mechanic was the way it was. Spells are body attached AND mind attached, you can't do what you did without refactoring spells to not be body attached.

**Comment by Jalleo** [comment] 2017-04-06 18:36
@Incoming5643 I am trying to fix this at the moment but there are problems such as needing to make sure everything prevents spells being carried over to a new body that isnt the lich (It seems like you may be able to be a non wizard with spells by doing this I need to work out how to prevent it)

**Comment by AnturK** [comment] 2017-08-04 06:29
Duplicate of #28846

**Closed by AnturK** 2017-08-04 06:29 UTC
Labels: Bug
