### ISSUE TITLE
Ethereal Body Revived, but player/ghost isn't

### ISSUE THREAD

**Issue by Purgatory63** [tgstation/tgstation#74128] opened 2023-03-20 05:03 UTC
## Reproduction:
Play as Ethereal, get beheaded without taking too much damage to the rest of the body. Wait, get crystalized. When you are revived, your ghost will not return to your body, instead still being in the dismembered head. The new body is catatonic and you cannot enter it.

What specifically happened is I was beheaded quickly in a fight. My body was being dragged around trying to be saved, I dont know if my head had been picked up too at that time. Eventually my body got encased in a crystal, but my head was being sent to medical to try and save me. 
When my body revived, it had a new head, but was catatonic. Someone in dead chat said it was most likely a bug because the body didnt register as brainless. Meanwhile, my dismembered head had been attached on another body.
My former body was taken to try and be used on a 'revive' rune by cultists since I was formerly one too, but nothing happened. Eventually they sacrificed me, but my soulshard was empty. Later, my head on the new body was revived and I continued in the round as that body.

**Comment by Sealed101** [comment] 2023-03-20 05:17
duplicate of #73514

**Closed by Sealed101** 2023-03-20 05:17 UTC

**Comment by Purgatory63** [comment] 2023-03-20 17:05
> duplicate of #73514

Ah, sorry! Should of looked around first, my bad.
