### ISSUE TITLE
Instruments "Staggering" & Muting All Sound

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#32088] opened 2017-10-24 20:47 UTC
Issue reported from Round ID: 77894 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Instruments tend to cut out/stop ALL Sound from playing when more complex songs are played. This can be partially fixed by using Stop All Current Sounds, but if the song is still playing, sound will cut out again in a few seconds.

**Comment by ShizCalev** [comment] 2017-10-25 06:13
Duplicate of #29759

**Closed by ShizCalev** 2017-10-25 06:14 UTC
