### ISSUE TITLE
Loaned Shuttle event bug

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#71131] opened 2022-11-06 09:24 UTC
Reporting client version: 514.1585

## Round ID:
[193814](https://scrubby.melonmesa.com/round/193814)

## Reproduction:
1. Loan the shuttle to CentCom (angry russian party in my case).
2. When 5 min countdown started, order some stuff (one security crate and one goody crate in my case).
3. After loanage time expires, see how your ordered goodies arrive, but no angry russians will appear at all (with any signs of their presence).
3a. See that loan message also stuck.
![image](https://user-images.githubusercontent.com/106118256/200161169-274faea4-e668-47e0-8251-38a9e8f837c3.png)
3b. No matter how many times you will send it back and forth, event will not end

**Comment by WarerBrow** [comment] 2022-11-06 09:25
Needless to add, that a couple of days ago I did the same thing but during the "eco-activists freeing bees" loaned shuttle event, and both my goodies and event stuff arrived as they should've been.

**Comment by Sealed101** [comment] 2023-03-13 15:43
seems like a dupe of that issue mentioned above

**Closed by Sealed101** 2023-03-13 15:43 UTC
