### ISSUE TITLE
Androids who get defibbed are stuck in permanent crit due to oxygen damage.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#77346] opened 2023-08-03 14:43 UTC
Reporting client version: 514.1589

## Round ID:
[211700](https://scrubby.melonmesa.com/round/211700)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
1) Become a robot using android mutation toxin 
2) Die to the ion gun
3) Repair said robot
4) Defib the robot
5) Get stuck in permanent crit due to oxygen damage

**Comment by MrMelbert** [comment] 2023-08-03 18:40
Dupe of #76804

**Closed by MrMelbert** 2023-08-03 18:40 UTC
