### ISSUE TITLE
The RPD can't print meters.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#36189] opened 2018-03-05 23:13 UTC
Meter buton dont set "mode" var  to METER_MODE

**Comment by Dennok** [comment] 2018-03-05 23:19
Duplicate of https://github.com/tgstation/tgstation/issues/32920

**Comment by ShizCalev** [comment] 2018-03-07 20:13
Duplicate of #32920

**Closed by ShizCalev** 2018-03-07 20:13 UTC
Labels: Bug
