### ISSUE TITLE
YOU CAN'T DEEP FRY JACKBOOTS!!!!!

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#81649] opened 2024-02-23 20:25 UTC
Reporting client version: 514.1589

## Issue Summary

YOU CAN'T DEEP FRY JACKBOOTS!!!!!

## Round ID:
[224466](https://scrubby.melonmesa.com/round/224466)

## Testmerges:
- [bindable action buttons](https://www.github.com/tgstation/tgstation/pull/81371)

## Reproduction:

1. Steal secoff's jackboots
2. Attempt to deep fry them
3. It won't let you, just does the animation of hitting the deep fryer with the shoes
4. Break into tears

**Comment by moocowswag** [comment] 2024-02-23 20:49
![image](https://github.com/tgstation/tgstation/assets/62126254/b70e2815-0899-4ad7-b52b-1f0ef407624a)
Please we need this

**Comment by ArcaneDefence** [comment] 2024-02-24 05:32
This is present in shoes that can act as containers for small items like emergency medipens, rather than shoes in general.
https://github.com/tgstation/tgstation/blob/92f85653bd3bef56aa979904377d20b66557b5da/code/modules/food_and_drinks/machinery/deep_fryer.dm#L119-L124
Someone decided we shouldn't fry containers at some point though, so iunno.
![png-clipart-man-wearing-red-sweater-shrug-emoji-old-man-people-men](https://github.com/tgstation/tgstation/assets/51932756/fe150741-4b6a-477d-bcf6-b2f1cf83a03a)

**Comment by distributivgesetz** [comment] 2024-02-24 08:16
> Someone decided we shouldn't fry containers at some point though, so iunno.

grounds for closing as wontfix then imo

**Comment by Iamgoofball** [comment] 2024-02-24 16:43
I did it and I don't remember why. Maybe someone was doing something with turning storage into food arbitrarily.

**Comment by Hoolny** [comment] 2024-10-21 02:13
> This is present in shoes that can act as containers for small items like emergency medipens, rather than shoes in general.
> 
> https://github.com/tgstation/tgstation/blob/92f85653bd3bef56aa979904377d20b66557b5da/code/modules/food_and_drinks/machinery/deep_fryer.dm#L119-L124
> 
> Someone decided we shouldn't fry containers at some point though, so iunno.
> ![png-clipart-man-wearing-red-sweater-shrug-emoji-old-man-people-men](https://private-user-images.githubusercontent.com/51932756/307498096-fe150741-4b6a-477d-bcf6-b2f1cf83a03a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzY0NTgsIm5iZiI6MTcyOTQ3NjE1OCwicGF0aCI6Ii81MTkzMjc1Ni8zMDc0OTgwOTYtZmUxNTA3NDEtNGI2YS00NzdkLWJjZjYtYjJmMWNmODNhMDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAyMDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZmZlNTA5NTU1ZjE3NTBmMzMzZWFmZmZlMmNjN2Y5ODU2MWE5N2ZlNjhlMTYwNDY0NTI1YTM5NDBlY2E1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DwH4XgBhEL13B4YBigBjwokrv3rm0sBKLOZpCeYEd4E)


Still, an issue extends to anything with storage capabilities.

![dreamseeker_4v5jD7pMRE](https://github.com/user-attachments/assets/e31ba23f-62e5-422f-8158-cee51f046c01)

This is code working as intended, a blacklist was made to prevent storage items from being fried jackboots are storage items.

This is very much just a feature.

**Closed by Hoolny** 2024-10-21 02:13 UTC
