### ISSUE TITLE
Speech runtiming

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#27438] opened 2017-05-19 18:47 UTC
[18:41:21] Runtime in say.dm, line 227: Cannot read null.stat
proc name: send speech (/mob/living/send_speech)
usr: Kashindra Kalcronk (bobbahbrown) (/mob/living/carbon/human)
usr.loc: The floor (148,90,1) (/turf/open/floor/plasteel/whitepurple/corner)
src: Kashindra Kalcronk (/mob/living/carbon/human)
src.loc: the floor (148,90,1) (/turf/open/floor/plasteel/whitepurple/corner)
call stack:
Kashindra Kalcronk (/mob/living/carbon/human): send speech("Borg", 7, Kashindra Kalcronk (/mob/living/carbon/human), "default", /list (/list), /datum/language/common (/datum/language/common), null)
Kashindra Kalcronk (/mob/living/carbon/human): say("Borg", null, /list (/list), 1, /datum/language/common (/datum/language/common))
Kashindra Kalcronk (/mob/living/carbon/human): Say("Borg")

@coiax

**Comment by lzimann** [comment] 2017-05-19 19:22
This is not a problem with languages. Something in the `GLOB.player_list` is becoming null for some unknown reason.

**Comment by lzimann** [comment] 2017-06-01 00:31
I believe I managed to get this fixed with #27812

**Comment by lzimann** [comment] 2017-06-06 14:59
This is still happening. Can't reproduce with a pAI though, so something is preventing a `mob/Logout()` call somewhere.

**Closed** 2017-07-15 15:07 UTC
Labels: Bug, Runtime
