### ISSUE TITLE
Internals On/Off Icon Visuals Glitch

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#35124] opened 2018-01-30 02:44 UTC
Issue reported from  Round ID: 82771 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Internals this round had a strange toggle icon for when you went to turn them on...

![internals are broke](https://user-images.githubusercontent.com/33048583/35545536-7b881772-053d-11e8-8482-2b3f661aceaf.JPG)

**Comment by Zytolg** [comment] 2018-01-30 02:45
UPDATE: 

It would appear that the icon can't sit still either.
![internals are broke it s changing too](https://user-images.githubusercontent.com/33048583/35545584-c5cee7b6-053d-11e8-83b2-60354a54cf0c.JPG)

**Comment by ShizCalev** [comment] 2018-01-30 06:38
Duplicate of #33403

**Closed by ShizCalev** 2018-01-30 06:38 UTC
