### ISSUE TITLE
humanized monkeys still flee when beheaded

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55638] opened 2020-12-19 22:19 UTC
152473

**Comment by dragomagol** [comment] 2020-12-20 02:26
Duplicate of #55544, although it looks like #55515 was supposed to fix this

**Comment by dragomagol** [comment] 2020-12-23 19:47
Saw another dead (non-humanized) monkey fleeing yesterday, even when strapped to a roller bed

**Comment by spessbro** [comment] 2021-01-08 19:57
i guess it's here to stay then

**Comment by Qustinnus** [comment] 2021-02-22 03:32
i havn't heard of this bug in ages i think i fixed it a while ago

**Closed** 2021-02-22 03:32 UTC
Labels: Bug, Needs Reproducing
