### ISSUE TITLE
Auto reconnect does no longer reconnect at end of round

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#54131] opened 2020-10-01 16:37 UTC
## Round ID:
[147446](https://scrubby.melonmesa.com/round/147446)

## Testmerges:
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4
#53965: 'Tanks have tiers' by Ghilker at commit 8328b2ad36

## Reproduction:
1. end round
2. reconnect doesn't happen

Auto reconnect does no longer reconnect at end of round

**Comment by msgerbs** [comment] 2020-10-08 19:01
Duplicate of #53213

**Closed** 2021-02-07 10:43 UTC
Labels: Bug
