### ISSUE TITLE
Ghosts can trigger portals

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#31292] opened 2017-10-04 03:28 UTC
They spark and it teleports the ghost
You can check the logs 
@ sybil round id 76953 station time 13:59:30(aroundish)
Mainly Lumi Pharon and me (Sherrie Williams) used them for a bit

No clue who touched portals code last so @kevinz000 since he reworked hand-teles

**Comment by YPOQ** [comment] 2017-10-04 03:37
Duplicate of #28667

**Comment by ShizCalev** [comment] 2017-10-04 04:24
Duplicate of #28667

**Closed by ShizCalev** 2017-10-04 04:24 UTC
