### ISSUE TITLE
Can't move on Sybil (All keys write in chat instead)

### ISSUE THREAD

**Issue by AnActualDog** [tgstation/tgstation#32774] opened 2017-11-15 14:31 UTC
Hey, first time reporting a bug like this, using Github, **I know fuckall** so please excuse if I make some sort of mistake. Was told to contact the coders by the admins since we couldn't solve the problem ingame.

Apparently due to some coding things the new version being tested on Sybil makes it so that some players - or maybe just me, who knows? - have all their keyboard inputs go into the chat. Doesn't matter if the chat button in the lower right corner is pressed or not. Pressing Tab didn't help, restarting didn't help, resetting my character didn't help, of course I tried googling this issue which also didn't give me any helpful info. So I am pretty sure it is a coding thing. (I know this should usually go into Pull requests but I have no idea which branch would be the correct one to select.)

I don't really know how to reproduce that issue since all I did was start up my game as I always did and as it always worked. So yeah, hope you know what causes this weirdness and can fix it, else I can't play on Sybil anymore...

**Comment by nicbn** [comment] 2017-11-15 14:46
Caused by #32751

**Comment by Cyberboss** [comment] 2017-11-15 14:59
Duplicate of #32766

**Closed by Cyberboss** 2017-11-15 14:59 UTC

**Comment by MrStonedOne** [comment] 2017-11-15 19:55
no it is not.

its a bug in byond.

**Comment by nicbn** [comment] 2017-11-15 22:13
I don't think so @MrStonedOne . I was playing just fine on Bagil with the beta client.
