### ISSUE TITLE
Using the signature code ("%s") when writing on paper does not function

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#69730] opened 2022-09-06 02:38 UTC
## Round ID: 189951
(round ongoing at time of writing)

## Testmerges:

https://www.github.com/tgstation/tgstation/pull/69115

## Reproduction:

When using a pen to write on a piece of paper, adding the code to input a uniquely italicized signature (%s) does not work, and instead of replacing the command, remains as "%s". Was told to report this issue via the github and here we are.

![we974PO6oy](https://user-images.githubusercontent.com/5360736/188534957-c4f2682f-fbdc-495f-9084-3dd47bc92b07.png)

**Comment by msgerbs** [comment] 2022-09-06 02:53
Can confirm this, I tested in the same round.

**Comment by Baskett55** [comment] 2022-09-06 03:37
You can only put signatures into a field like [__________________]

**Comment by Daundra** [comment] 2022-09-06 03:55
If this is intentional behavior then I am sorry, I play very infrequently and was not used to or aware of this requirement.

**Comment by Palpetinus** [comment] 2022-09-06 06:41
Pretty sure it doesn't work in fields either, I played warden the other day and handed out guns to assistants requiring their signature for tracability, only to find out they cannot sign my form. Literally had them ask me "is it not %s???" and such

**Comment by Baskett55** [comment] 2022-09-06 07:12
seems to work fine, and its intended to only work in fields
![image](https://user-images.githubusercontent.com/54517726/188569833-d2a1ceab-4318-44a3-a2c0-c0e4e8fa0b63.png)
From the papercode PR:
![image](https://user-images.githubusercontent.com/54517726/188569957-f718f5d2-73f5-45aa-b11c-ce77a2563199.png)

**Comment by msgerbs** [comment] 2022-09-06 14:44
I was not aware that it was intended to only work within input fields. I just tested that and it did indeed work, although you do need to make sure you hit save. You have to click on the yellow fillable field on the top half of the paper, not the bottom half. It seems this is working, but the wiki at least could be a bit more clear. Not sure what could be done within the game itself to make it more clear but I'm open to ideas.

**Comment by msgerbs** [comment] 2022-09-06 16:34
I updated the wiki for this, I'm still open to ideas to improve the ingame experience but this seems acceptable at least now. Closing since it's not actually a bug.

**Closed by msgerbs** 2022-09-06 16:34 UTC
Labels: Not a bug
