### ISSUE TITLE
Turning off an APC's breaker will prevent interaction with it

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#15784] opened 2016-02-27 04:46 UTC
edited
### What is the problem?

I stopped being able to interact (open UI) with the robotics APC after I turned its main breaker off and closed the window.
### How can the problem be reproduced?

I tried reproducing this with other APCs but I never had any trouble interacting with them, it happened just with the Robotics APC and I can't be sure if turning off the main breaker had anything to do with it (but the problem started immediately after).
### What revision did the problem happen on? (Helpful, but not required)

Server revision compiled on: 2016-02-26
c49a4b71a36ac1f41b91679643cdb64757082617

**Comment by tkdrg** [comment] 2016-02-27 10:41
I've had a bunch of ahelps about similar stuff before, but it's always worked for me. It's probably tgui-related, as SStgui's list showed that the player still had the APC window open, despite closing it. @neersighted

**Comment by xxalpha** [comment] 2016-02-27 16:43
Shit I forgot to mention, I was a cyborg.

**Comment by neersighted** [comment] 2016-02-28 14:19
I've been unable to reproduce this. It's definitely a bug but I can't seem to replicate it. In the future, admins can call close() on the /datum/tgui to reset it (by VVing the tgui subsystem).

**Comment by Cyberboss** [comment] 2017-01-18 16:15
Tguis are notoriously hard to close if you minimize them

**Comment by ShizCalev** [comment] 2017-11-20 09:56
Will close in a week without any other reports of repo.

**Closed** 2017-11-27 00:10 UTC
Labels: Bug, Needs Reproducing
