### ISSUE TITLE
Performance of Turf Decals is critically terrible

### ISSUE THREAD

**Issue by actioninja** [tgstation/tgstation#53798] opened 2020-09-17 16:26 UTC
Making this issue report to collect discussion about said issue in the title.

It can be broke down into two core issues:

# Memory Usage 

Currently turf decals create a new component for each and every decal placed, along with a new image.

This results in over 21k decal component datums on a live game server running metastation.

This should be at most one component per turf with decals. Ideally it should be something more like a bespoke element, where only each unique combo of decals gets a new component/entry.

# Maptick Usage

Currently on a live server with nothing else happening, removing all decals results in maptick usage going from around 30% to around 15%

At the moment, each decal exists as an overlay that is added to each tile.

This is a lot more mysterious and difficult to solve of of an issue due to the underlying opaque systems in play.

Potential solutions:
- use blend to crush each decal into a unique image for each unique combo of decals
- use vis_contents instead of overlays

Further elaboration on pros and cons of said methods will be made later.

**Comment by Couls** [comment] 2020-09-17 19:02
Lowering the maptick is something really important to me especially because it's a likely contributor to the lag issues seen during the testmerges of #52478 that said I think it'd be a good idea to try out both solutions and see which one plays out best for lowering the Sendmaps() cost

**Comment by LemonInTheDark** [comment] 2020-09-18 01:41
oh jesus he's moving

**Comment by TheVekter** [comment] 2020-09-18 04:14
Okay maybe decals _were_ why Kilo was breaking

**Comment by optimumtact** [comment] 2020-10-08 03:24
@TiviPlus did your thing improve this?

**Comment by cacogen** [comment] 2020-10-22 21:54
Do all the shitty soapstone messages nobody reads or even notices count as decals? Because they should auto-delete based on score after a certain time.

**Comment by Dennok** [comment] 2020-10-23 09:33
Problems not in "shitty soapstone messages" Problem in strip/warning lines, blood, corner coloring, etc.

**Comment by TiviPlus** [comment] 2020-10-28 21:55
Late response but I only fixed the memory usage, the maptick issue still stands

The problem is I dont really see any easy way to fix it

Blend is awfully slow and a cached viscontents atom is worse on maptick than overlays
I tried fucking around more with other ideas I had but nothing useful has come of it yet

**Comment by LemonInTheDark** [comment] 2021-02-26 09:43
@actioninja is this still the case? They're not like, great, and kilo is a bit higher in terms of maptick per player, but it's not **that** bad

**Comment by LemonInTheDark** [comment] 2021-02-26 09:50
For context, here's a running average of the average maptick per player per round globally, and per map.
![maptick2](https://user-images.githubusercontent.com/58055496/109284149-6408c300-77d4-11eb-9d0a-0476c2037f7f.png)
![maptick3](https://user-images.githubusercontent.com/58055496/109284150-6408c300-77d4-11eb-833e-a2e2d1efedf1.png)

The visualization here might be a bit deceiving, as A: This is a running average over the scope of 250 rounds, and since some maps are played less, they both react slower and take longer to react. This is a flaw in my algorithm. This is also what causes the high starting values, and the drop over time.

I'm also curious to do some more playing around with this stuff, since I have a feeling that taking a sample of low/highpop here would produce different values, as can be seen by pubby down there in the bottom left. However I think this is at least partially valid, and while there is a delta between icebox and kilo, it's not **all** that high

**Comment by Kylerace** [comment] 2021-04-25 08:58
thanks to @LemonInTheDark for providing the data here
https://github.com/tgstation/tgstation/pull/58496 this was testmerged on manuel for 5 days for a total of 65 rounds. data is from both the rounds with the testmerge on manuel and the 65 rounds before the testmerge on manuel.

according to lemon, the 65 rounds with double decals had an average maptick per player of 0.94, and the 65 rounds with normal decals had an average maptick per player of 0.882, a 7% difference here is not as large as this issue would imply, i dont believe it makes sense to call turf decals critically terrible at all.

**Comment by Kylerace** [comment] 2021-07-17 02:42
thanks again to @LemonInTheDark for all stats gathered from both test merges and general stats beyond that. 

this test merge multiplied all turf decals by 6 times, 3 times more than the last one and went on for 106 rounds from 7/7/21 to 7/15/21 (round ids starting at 165545 and ending at 166036, note however that round 165536 was the first one with the pr test merged, however i made a mistake and it was only 2x'ing decals, that was the only wrong one though as i fixed it within 3 hours) as opposed to 65 for the last test. since maptick is overall lower now with less movables in view, maptick variance is much smaller now than during the last test 
![image](https://user-images.githubusercontent.com/15794172/126017745-62c38961-29ad-4b9c-858c-2083ca0e2b38.png)
ignoring that megaspike which was an error with map_cpu carrying over to other rounds without actually affecting maptick (since time dilation doesnt increase with it). 

![image](https://user-images.githubusercontent.com/15794172/126017924-e3766afb-8b7c-43a9-9af4-067be1635599.png)
here is the raw 2 week data with the first round of the test merge being in about the middle and everything before that is normal non test merge data. this is useless and the megaspike is caused by map_cpu carrying over to other rounds for unknown reasons as shown earlier. here for example is the first round (round id 165856) of the spike
![image](https://user-images.githubusercontent.com/15794172/126018498-dc5d4db9-3c74-452b-83bc-3e4686eab538.png)
maptick is 80-90% but time dilation is < 5% for 20-25 players which is pretty unlikely but i doubt impossible, so i looked at the sendmaps profiler for this round https://tgstation13.org/parsed-logs/manuel/data/logs/2021/07/13/round-165856/sendmaps.json and still no obviously hyper expensive part of it showed up, average movables per tile is 2.097 which is in the right range for most rounds ive seen (movables examined / (look for movable changes calls * (widescreen dimensions + 1 which is 21*17))) and (look for movable changes cost / sendmaps total cost) = 80% which is also reasonable. also this was the round before where maptick suddenly shot from ~10 to ~90 which is the level seen in the spike 
![image](https://user-images.githubusercontent.com/15794172/126022177-1046a9d4-a538-4a67-a5b4-03234766e2ce.png)
so the following stats will filter out the deathspike

	ACTUAL READABLE RESULTS

![image](https://user-images.githubusercontent.com/15794172/126022202-0643e302-b6dd-4ef4-ab03-29da6b7a09f0.png)
this is the maptick / player count for each round in the 2 week range excluding the deathspike. with the start of the tm being in the middle, hard to see any difference
![image](https://user-images.githubusercontent.com/15794172/126022219-588653cf-e54e-499e-a514-67db6d87043b.png)
this is a moving average of the same data 60 rounds wide, you can see a small but noticeable increase in the second half and here
![image](https://user-images.githubusercontent.com/15794172/126022262-bb5a7087-5bdb-48e7-8024-08fffa3006f0.png)
is a zoomed in graph of the uptick, the maximum range here is from 0.458 to 0.488 which is a difference of 0.03 maptick per person for literally 6 times the number of turf decals, thats an increase of 6.5%. there is no way to classify this as a critical performance issue. sendmaps cost scales mostly with movable count, that is the absolute number one scaling cost of the process, and overlays are not movables. i no longer believe the observed cost of the test merge's are fake because it doesnt make sense at this point but lummox is explicitly clear here that overlays are not processed themselves unlike movables, any cost with them is with changing appearance which i believe is what we're observing.
![Screenshhgjkhjbkjhot_10](https://user-images.githubusercontent.com/15794172/126022780-f04e4dbf-3bfe-4786-8fb5-8f73f86e1e79.png)

**Closed by Kylerace** 2021-07-17 02:42 UTC
Labels: FUCK, Performance
