### ISSUE TITLE
some issues with custom hotkeys

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47621] opened 2019-11-06 19:37 UTC
1. the ooc/say boxes dont have a cancel/X button, pressing escape doesnt close out of them either
2. maybe unrelated to custom hotkeys but definitely wasnt a thing in the past: playing on a server with 200 ping, i notice a considerable delay from pressing T or O until i'm able to type. in the past, i would be able to type instantly, regardless of ping, this is annoying for obvious reasons. i play on servers with this ping frequently, and have not noticed it at all before.
3. pressing M just says "unusable emote: me" in chat.

**Comment by kriskog** [comment] 2019-11-06 20:06
2 isnt new, always been that way with lag.
3 is fixed on current master. Go bug a keyholder for updates.

**Comment by Couls** [comment] 2019-11-06 20:19
3 works when you're ingame, it doesn't work in the lobby

**Comment by Tharcoonvagh** [comment] 2019-11-06 23:02
2: i noticed some delay too, it was a lot faster before

**Comment by kriskog** [comment] 2019-11-06 23:15
Yeah the delay has since been confirmed as a thing. There is a PR up to revert the custom binding of say/ooc/me.

**Comment by imsxz** [comment] 2019-11-07 00:00
ive never had nearly as severe lag unless my mind is fucking with me. seems to always miss the first couple letters now though unless i wait for it to pop up.

**Comment by AnonymousNow** [comment] 2019-11-07 01:20
Suddenly couldn't jump straight into talking by pressing tab-enter any more. Severely hampers talking.

**Comment by PKPenguin321** [comment] 2019-11-07 03:11
temp workaround would be to use non-hotkey mode and just type "say [your message here]"

**Comment by Couls** [comment] 2019-11-07 03:37
can also have IC tab open in verbs and click on say to type

**Closed** 2019-11-07 23:07 UTC
Labels: Bug
