### ISSUE TITLE
Silicon time only counts for roundstart Cyborgs

### ISSUE THREAD

**Issue by ArthuroPep** [tgstation/tgstation#71278] opened 2022-11-15 14:49 UTC
## Round ID:
[194380](https://scrubby.melonmesa.com/round/194380) 

## Reproduction:
I have been struggling to unlock AI, as it seems to exclusively only count when I spawn in as a roundstart Cyborg. I have, one time, been borged immediately, played for two hours, and the counter did not decrease. This is not an issue that happened in one round but has been plaguing me for weeks now.
To reproduce:
-Use an account that has not unlocked AI
-Be borged on roundstart, play for at least an hour
-Counter, which should decrease, doesn't.

**Comment by msgerbs** [comment] 2022-11-15 15:00
Unfortunately, this is a duplicate of #51707. Thank you for making an issue report though.

**Closed by msgerbs** 2022-11-15 15:00 UTC
