### ISSUE TITLE
You are no longer able to lie down to hide inside crates

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#50382] opened 2020-04-04 07:54 UTC
In the past you could lie down to shut yourself into a crate. Trying to do it standing up gave you a message that something large in the crate prevents it from closing. This message now shows up even if the person is laying down, preventing you from shutting it with someone inside.

Issue reported from  Round ID: [133883](https://scrubby.melonmesa.com/round/133883) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

**Comment by LemonInTheDark** [comment] 2020-04-04 08:38
More clear dupe of #50236, #50370, fixed by #50348

**Comment by Akrilla** [comment] 2020-04-04 10:27
pls read existing issues before making a new one

**Comment by Dorsisdwarf** [comment] 2020-04-05 10:59
Allowed to survive because its better worded than the old ones

**Comment by Dennok** [comment] 2020-04-06 09:23
This must be closed by #50348

**Comment by Akrilla** [comment] 2020-04-06 09:23
It is

**Comment by LemonInTheDark** [comment] 2020-04-08 07:09
ISSUE JANNIESSSS@@@@@@!@#!$%%!@$_@($

**Comment by ShizCalev** [comment] 2020-07-25 07:54
Ping me directly on discord in the future.

**Closed** 2020-07-25 07:54 UTC
Labels: Bug
