### ISSUE TITLE
Condiment packs are broken on most foods

### ISSUE THREAD

**Issue by gitbirb** [tgstation/tgstation#55017] opened 2020-11-17 18:20 UTC
## Reproduction:

get a food such as a steak
try using condiment pack on it or syringe to inject it

unable and cry when chef no longer has his main traitor gimmick of poisoning food.

---
also it's notable that it works on certain small foods (not organs though) such as Soy Dopes, but not on medium foods such as Steaks, Spaghetti, or most other finished meals since almost everything is medium sized now for some reason.

**Comment by brotherbeyondd** [comment] 2020-11-17 19:02
Medium foods = refactored foods.

The c*ders have a plan to destroy the kitchen.

**Comment by ArcaneDefence** [comment] 2020-11-17 20:32
Failed to reproduce in any of things mentioned here after https://github.com/tgstation/tgstation/pull/54937, where did you test this?

**Comment by Pugie** [comment] 2020-11-18 09:01
I tried to put ketchupp on fish and chips 2 days ago on terry, couldn't

**Comment by ArcaneDefence** [comment] 2020-11-18 20:46
![image](https://user-images.githubusercontent.com/51932756/99585997-573e2d00-29a4-11eb-96a6-6348750e56f1.png)
Even in that case off of master, here's applying it and tasting the reagent.
Still sounds like an outdated report.

**Comment by Pugie** [comment] 2020-11-19 00:03
Maybe you have to be british to unlock no ketchup fish and chips

**Comment by Dorsisdwarf** [comment] 2020-11-19 10:57
If nobody can reproduce this in the next 2 days on live, yell at me on discord to close the issue

**Comment by Dorsisdwarf** [comment] 2020-11-22 20:04
Could Not Reproduce

**Closed by Dorsisdwarf** 2020-11-22 20:04 UTC
Labels: Bug, Needs Reproducing
