### ISSUE TITLE
Emitters sometimes don't work

### ISSUE THREAD

**Issue by SpacePrius** [tgstation/tgstation#45015] opened 2019-07-06 10:39 UTC
## Testmerges: 
#44945: 'Properly fixes smart cable lag issues and also fixes the awful connection issues.' by actioninja at commit ce0c4696c8
#44310: 'Removes Hygiene' by Garen7 at commit 3a37d0322c

## Reproduction: 

Turn on emitters, pray to space jesus that they actually work, sometimes they just decide not to.

**Comment by actioninja** [comment] 2019-07-08 06:54
I am pretty sure this is related to the issues with smeses connecting to themselves that were fixed in #44971 Going to tentatively say this is fixed, but I am not 100% sure on that.

**Comment by kriskog** [comment] 2019-07-11 15:27
The behaviour of not firing is almost doubtless caused by there being no excess power for the emitters to fire in the powernet. Starting the emitter puts them at the end of the queue for power use, behind all the apc's charging and shit like that. Scanning a cable with a multitool should support this, as excess should be 0 or the cable should show as unpowered.

This isnt strictly a smart cable issue, but was more noticeable for a few days when smes were hogging the power as well.

If you come across this again and there is excess power in the net, open a new issue specifying that.

**Closed by kriskog** 2019-07-11 15:27 UTC
Labels: Bug, Needs Reproducing
