### ISSUE TITLE
Facial hair preferences bug

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#26057] opened 2017-04-10 09:40 UTC
Your facial hair choice gets randomly set to a type of hairstyle rather than a type of proper facial hair, making you appear clean-shaven unless you use a mirror. 
Even when changed in preferences and saved, it will still reset every round.

![ss 2017-04-10 at 04 36 38](https://cloud.githubusercontent.com/assets/6510293/24855504/6bd2a4ec-1da7-11e7-8c40-631ff181476e.png)

I assume this is @Cyberboss's doing

**Comment by AnturK** [comment] 2017-04-10 09:57
Dupe of #26010

**Closed by AnturK** 2017-04-10 09:57 UTC

**Comment by Bawhoppen** [comment] 2017-04-10 10:03
mine was more explanatory though
