### ISSUE TITLE
Mechs cant drill walls anymore.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35925] opened 2018-02-23 15:18 UTC
[Reproduction]: I was using APLU Firefighter with diamond drill. I wasted 10 minutes drilling a normal wall and nearly the same ammount of time doing that with a reinforced wall. And i didnt drill them, even when i probably should be able to. Maybe this is intended.

**Comment by Buggy123** [comment] 2018-02-23 23:02
#34426

**Comment by ShizCalev** [comment] 2018-02-24 19:59
Duplicate of #34426

**Closed by ShizCalev** 2018-02-24 19:59 UTC
