### ISSUE TITLE
Setting equipment to admin outfit spills mats everywhere

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#82871] opened 2024-04-24 20:01 UTC
Reporting client version: 515.1635

## Round ID:
[227764](https://scrubby.melonmesa.com/round/227764)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/3f4d4f2a-ce81-49c2-92fc-e5cbbf23c7e7)

Change outfit to admin
All of the mats in your pockets spill out

**Comment by msgerbs** [comment] 2024-04-26 02:40
Also Duplicate of #82705

**Closed by msgerbs** 2024-04-26 02:40 UTC
