### ISSUE TITLE
Engineer deployable turret turns invis

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#60956] opened 2021-08-20 22:08 UTC
Step 1 buy toolbox
step 2 deploy
step 3 buy agent id
step 4 turn turret off
step 5 turret is now invis and can't be interacted with

**Comment by timothymtorres** [comment] 2021-08-21 05:06
This looks like it might be something from #60554.  @Paxilmaniac can you take a look at this?

**Comment by timothymtorres** [comment] 2021-08-21 05:33
Also this might be a dupe of #53032 but I'm not sure

**Comment by projectkepler-ru** [comment] 2024-07-10 08:08
N/A @timothymtorres

**Comment by Sealed101** [comment] 2024-09-16 13:43
can no longer reproduce; turrets are still decrepit code though sadly

**Closed by Sealed101** 2024-09-16 13:43 UTC
Labels: Bug
