### ISSUE TITLE
Any PDA message sends "datamessage"

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#34054] opened 2018-01-03 00:17 UTC
All rounds in the last few days have had broken PDA messaging with all messages ending up as "datamessage" no matter what the actual original message contains.

i.e. 
`(F)  Johan Scherer PDA Message  --> William Dornan (Botanist) : "datamessage" `

Server revision (has been on earlier revisions than this as well):
```
Round ID:  81277 
Server revision compiled on:  2018-01-01 
The following pull requests are currently test merged: 
#34005: 'Reverts explosion shaking' by praisenarsie at commit 56a19a 
Based off origin/master commit: c06390 
Server tools version: /tg/station 13 Server v3.2.1.9 
Server tools API version: 3.2.0.1 
```

**Comment by DaxDupont** [comment] 2018-01-03 00:51
dupe of #34023, will be fixed when the server updates.

**Comment by AnturK** [comment] 2018-01-03 10:26
Duplicate of #34018

**Closed by AnturK** 2018-01-03 10:26 UTC
