### ISSUE TITLE
Pickaxes are spawning inside the walls of the necropolis bridge.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#19127] opened 2016-07-04 19:42 UTC
![the black pearl 2016-07-04 154025](https://cloud.githubusercontent.com/assets/8237862/16568904/daf6f084-41fd-11e6-9f10-7adab6d65300.png)

**Comment by Zilenan91** [comment] 2016-07-04 21:18
Are you sure this wasn't admins because this is really bizarre

**Comment by Imagebard** [comment] 2016-07-04 21:38
Uh, I thought it was intentional.
This seems to be happening consistently.

**Comment by Hatfish** [comment] 2016-07-04 22:24
Nope, it definitely wasn't admins because I saw it on both Sybil and Basil after a bit of serverhopping.

**Comment by coiax** [comment] 2016-07-05 01:41
Caused by a map merger bug, this was fixed in #19122

**Closed** 2016-07-05 20:32 UTC
