### ISSUE TITLE
Beepsky can move and act in wizard's timestop field

### ISSUE THREAD

**Issue by PatchouliKnowledge** [tgstation/tgstation#37294] opened 2018-04-19 08:06 UTC
Issue reported from  Round ID: 86729 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Reproduction]: During a wizard round, a wizard used timestop, but Beepsky was able to enter the field and move around and stun/cuff people. The sprite did have inverted colours, but he didn't seem otherwise affected. Beepsky's harm prevention system was turned off by the AI as it was called to a specific location (the Vault), it was reporting lv10 infractions.

To try and reproduce:
- get Beepsky
- cast timestop
- turn off Beepsky's harm prevention system

**Comment by PKPenguin321** [comment] 2018-04-19 20:05
Dupe of https://github.com/tgstation/tgstation/issues/35893

**Closed** 2018-04-19 21:11 UTC
