### ISSUE TITLE
RPD pipe images not showing up

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37924] opened 2018-05-19 06:57 UTC
![image](https://user-images.githubusercontent.com/10399117/40265972-e8cda5d2-5b31-11e8-8bde-fb49f4f8a5ab.png)

**Comment by SpaceManiac** [comment] 2018-05-19 07:45
Duplicate of #37828.

**Closed by SpaceManiac** 2018-05-19 07:45 UTC
