### ISSUE TITLE
Taking off your outer suit doesn't drop items from its suit storage

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#87141] opened 2024-10-10 02:35 UTC
### Client Version:

515.1637

### Issue Summary:

Taking off an item in the suit slot (eg, an Explorer Suit) doesn't seem to make anything in it drop anymore. Possibly related to the recent PR that changed slots to just grey out when unusable?

Before taking off suit:
![Screenshot 2024-10-09 213343](https://github.com/user-attachments/assets/705b27ad-d887-400a-9de0-1bc5edbd3d8f)

After taking off suit:
![Screenshot 2024-10-09 213351](https://github.com/user-attachments/assets/1620f4ed-6e0e-43bf-9079-16c2cfef3911)

### Round ID:

240055

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)

### Reproduction Steps:

1. Put on an outer suit
2. Hang something off it
3. Take the suit off
4. The item is now floating somewhere in front of your chest, presumably

**Comment by MrMelbert** [comment] 2024-10-10 02:37
Dupe of #87129

**Closed by MrMelbert** 2024-10-10 02:37 UTC
