### ISSUE TITLE
[Metastation] Modular computer in meta's RD office blocks off request console and AI restore console

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23540] opened 2017-01-31 13:27 UTC
low effort implementation to be honest.

**Comment by jughu** [comment] 2017-01-31 13:31
@latots already being worked on

**Comment by lzimann** [comment] 2017-01-31 13:56
Being fixed by #23491. 
Next time please include which map the issue is happening.

**Comment by Iatots** [comment] 2017-01-31 17:09
------>meta's RD office
              ^
               |
               |

**Comment by lzimann** [comment] 2017-01-31 17:30
Also I'm blind sometimes so there's that.

**Comment by Tofa01** [comment] 2017-02-02 22:52
Will be fixing my bad placement shortly

**Closed** 2017-02-04 11:21 UTC
Labels: Map Issue
