### ISSUE TITLE
An entire dmi is showing up in the stat panel instead of just an item's icon

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#80349] opened 2023-12-15 09:53 UTC
## Issue Summary

When looking at the list of things on a tile with alt-click, what normally has the icon for the items, some have an entire dmi.

![image](https://github.com/tgstation/tgstation/assets/83487515/dde0fd59-5f61-4986-a067-ee768e5f15b6)

## Round ID:
[220524](https://scrubby.melonmesa.com/round/220524)

## Testmerges:

None

## Reproduction:

Alt-click a tile and look at the items list

![image](https://github.com/tgstation/tgstation/assets/83487515/53e6ab4f-d8a2-4264-b3fd-4e1eb831ab8f)

**Comment by LemonInTheDark** [comment] 2023-12-15 10:03
Dupe of #53824

**Closed by LemonInTheDark** 2023-12-15 10:03 UTC
