### ISSUE TITLE
/obj/docking_port/stationary/transit has an expensive Destroy

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#30588] opened 2017-09-10 19:07 UTC
````
/obj/docking_port/stationary/transit
    qdel() Count: 104
    Destroy() Cost: 10049ms
    Total Hard Deletes 52
    Time Spent Hard Deleting: 25019ms
````

@Cyberboss

**Comment by MrStonedOne** [comment] 2017-09-11 09:19
#30589 likely the cause or other wise related

**Comment by Cyberboss** [comment] 2017-09-13 15:43
This is a side effect of transit lighting bs yeah

**Comment by Cyberboss** [comment] 2017-09-13 15:44
Duplicate of #30589

**Closed by Cyberboss** 2017-09-13 15:43 UTC

**Comment by MrStonedOne** [comment] 2017-09-20 03:51
https://tgstation13.org/parsed-logs/sybil/data/logs/2017/09/18/round-76293/qdel.txt

Still an issue, not a duplicate
