### ISSUE TITLE
Feature request: Add antag on/off buttons

### ISSUE THREAD

**Issue by wingy** [tgstation/tgstation#21533] opened 2016-11-13 19:23 UTC
There are rounds where I want to play only non-antag. To my knowledge there is no easy way to turn them all of, you have to do it one by one. It would be useful if we had "Antag: Yes No" buttons (preferably in the lobby menu).

**Comment by PKPenguin321** [comment] 2016-11-13 19:37
Not a bug and should be closed

That aside though I agree this would be handy

**Comment by xxalpha** [comment] 2016-11-13 21:43
He didn't say it's a bug.

**Comment by Iamgoofball** [comment] 2016-11-13 22:16
Not a bug. Close it.

**Closed** 2016-11-14 06:24 UTC
