### ISSUE TITLE
Unwelding shuttle walls makes a hole into space

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#34740] opened 2018-01-21 10:18 UTC
[Round ID]: #82298

Welding the walls on the emergency shuttle on metastation, where the entrance area to the Command EVA on the shuttle meets the wall of the brig section causes a hole into space to form where the wall was previously.

More tests are needed

**Comment by Marflowerose** [comment] 2018-01-21 10:36
Probably a dupe of https://github.com/tgstation/tgstation/issues/34172 https://github.com/tgstation/tgstation/issues/33907 https://github.com/tgstation/tgstation/issues/33968 https://github.com/tgstation/tgstation/issues/33984

**Comment by ninjanomnom** [comment] 2018-01-21 11:03
That 4th linked pr yes

**Closed by ninjanomnom** 2018-01-21 11:03 UTC
