### ISSUE TITLE
Can't push dead borgs down stairs

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#49686] opened 2020-03-03 03:12 UTC
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49579: '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe at commit 1d517bd8b5
#49476: 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll at commit 32fad5b299

## Reproduction:
If a borg dies on an upper level, you can't push them down the stairs and seem to have to shove them over the side of a ledge. Players inform me that borgs can't push other borgs at all, and I'm not sure if you can do the ctrl+click thing to move them off a ledge, so it's extra problematic for them

**Comment by HomocidlePancakes** [comment] 2020-03-03 07:18
Dupe of #47376

**Comment by HomocidlePancakes** [comment] 2020-03-03 07:19
Wait, no, this is a bit different, but still.

**Closed** 2021-12-07 07:13 UTC
Labels: Consistency Issue
