### ISSUE TITLE
Breaking a /obj/structure/grille yields an invisible stack of zero iron rods

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#71203] opened 2022-11-10 20:26 UTC
Reporting client version: 514.1589

## Round ID:
[194084](https://scrubby.melonmesa.com/round/194084)

## Testmerges:
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)
- [Imaginary friend refactor](https://www.github.com/tgstation/tgstation/pull/71058)

## Reproduction:

Spawn /obj/structure/grille
Punch it until it breaks
![image](https://user-images.githubusercontent.com/3789327/201198559-23747738-1601-45c6-9e20-6dcc7acbc688.png)
![image](https://user-images.githubusercontent.com/3789327/201198638-8879474b-e860-46c3-8ee9-15bff224d4a5.png)

**Comment by timothymtorres** [comment] 2022-11-11 01:30
Duplicate of #60340

**Comment by timothymtorres** [comment] 2022-11-11 02:37
Both bugs result in the same problem - a zero stack of material.  The only difference is the reproduction steps.

**Closed** 2022-11-27 07:43 UTC
