### ISSUE TITLE
Magic Bible-disappearing monkey.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#37913] opened 2018-05-18 11:46 UTC
Issue reported from  Round ID: 88114 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: #88114

[Reproduction]: I was beating a monkey over the head with my bible as a chaplain, the monkey was Bubbles, the one that spawns in the bar. He wasn't hostile, but he snatched it from my hands, and then the next click was hugging him instead of bibling him. At that point, from everything I can tell, the bible simply ceased to exist. I tried to strip it from him, but he wasn't holding or wearing anything. I tried disarming him, and it didn't drop.

**Comment by Barhandar** [comment] 2018-05-18 12:58
#37645

**Comment by ShizCalev** [comment] 2018-05-18 13:53
Duplicate of #37645

**Closed by ShizCalev** 2018-05-18 13:53 UTC
