### ISSUE TITLE
Ballistic Weapons with Bolts do not properly update icon states

### ISSUE THREAD

**Issue by ErdinyoBarboza** [tgstation/tgstation#67074] opened 2022-05-17 11:12 UTC
## Reproduction:
Take any weapon that is BOLT_TYPE_STANDARD (or any bolted weapon)
Use in hand to rack bolt open
Check sprites and realize it is not overlaying _bolt or _bolt_locked icons on the original sprite.

![image](https://user-images.githubusercontent.com/25566633/168798112-98112da5-4489-40f5-b745-e9345c62a414.png)
Now very visible on mosins but when trying to make double barrels and more dynamic sprites it becomes unusable
![image](https://user-images.githubusercontent.com/25566633/168798214-ac0b0991-1af0-4c2a-a3a3-68264b0e7171.png)
As only the original sprite part is visible

**Comment by timothymtorres** [comment] 2022-08-27 04:23
Relevant code:

https://github.com/tgstation/tgstation/blob/1eb1fc93699d3fd2b84b493b496c6cbfcffc592b/code/modules/projectiles/guns/ballistic.dm#L177-L183

This may have been fixed by #59580

**Comment by itseasytosee** [comment] 2023-02-04 05:17
Unable to reproduce. Probably fixed and should be closed.

**Comment by Sealed101** [comment] 2023-03-08 15:42
fixed in #72448
![image](https://user-images.githubusercontent.com/75863639/223759166-0cbff09d-1d5d-4d1e-b9bd-ef73361d1884.png)

**Closed by Sealed101** 2023-03-08 15:42 UTC
Labels: Sprites, Bug
