### ISSUE TITLE
Syndicate channel is not working

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33757] opened 2017-12-22 15:35 UTC
1) Get syndicate headset
2) ":t what is the plan operatives"
3) Nothing happens, you just hear yourself talk in italics.

Present in commit edef11f0944e1365f28a30489420f8f0eba8e327

**Comment by coiax** [comment] 2017-12-22 16:14
This is caused by #33647, @SpaceManiac.

Please fix immediately.

**Comment by imsxz** [comment] 2017-12-22 16:16
I've had syndicate radio working for me since this was merged. Are you sure the headset wasn't EMP'd, the syndicate comms relay wasn't destroyed, and the headset didn't have its encryption key removed?

**Comment by coiax** [comment] 2017-12-22 16:18
This is on raw straight up testing on a private server.

**Comment by coiax** [comment] 2017-12-22 17:16
BUT I REPRODUCED IT MYSELF!!

**Comment by BeeSting12** [comment] 2017-12-22 18:35
This has been reproduced round ID 80619. Spawning an all-in-one telecomms mainframe on the station zlevel fixes it, but that also makes everyone say everything on comms twice which is annoying. 

Nuke op headsets work because they're on the channel 121.3

**Comment by Electronics** [comment] 2017-12-22 23:31
+1

**Closed** 2017-12-25 22:47 UTC
Labels: Bug, Needs Reproducing
