### ISSUE TITLE
Thermal Imaging Glasses just blind you

### ISSUE THREAD

**Issue by PLISKINN** [tgstation/tgstation#33826] opened 2017-12-24 22:19 UTC
basically what the title says
just buy the thermal glasses and put them on, and this happens
![90a9f7780a0b8fbe2cf69f8c8db9cae2](https://user-images.githubusercontent.com/27116073/34329439-deea1dcc-e8c5-11e7-885c-e5a6d7bbf46f.png)

They aren't even thermal either, just makes you blind

(the round id is 803735 if anyone really cared)

**Comment by Cyberboss** [comment] 2017-12-25 00:00
Duplicate of #33818

**Closed by Cyberboss** 2017-12-25 00:00 UTC
