### ISSUE TITLE
Silicon version of door control visible as a Carbon

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#63345] opened 2021-12-11 01:58 UTC
Reporting client version: 514.1566

## Round ID:
[174565](https://scrubby.melonmesa.com/round/174565)

## Reproduction:
While I was attempting to unbolt an airlock in the engine room, by hacking it as an engie, I screwdrivered(hand drilled) open the airlock by clicking on the turf selection portion of the UI. When I did this, I was shown a greyed-out version of the silicon interface panel. While I was then able to hack the door afterwards, I figured I should report this as a bug. Potentially relevant is that it was under an atmos holofan.
![image](https://user-images.githubusercontent.com/25726397/145660066-58203baf-5328-45d8-984d-9d97d4a8123f.png)

**Comment by newfren** [comment] 2021-12-11 04:04
I find this happens sometimes when I alt click the tile the door is on although often that is under a holofan

**Comment by SuperNovaa41** [comment] 2021-12-11 05:50
Duplicate of https://github.com/tgstation/tgstation/issues/61997

**Closed by SuperNovaa41** 2021-12-11 05:50 UTC
