### ISSUE TITLE
remote door sparking

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47502] opened 2019-10-31 15:12 UTC
0. Be shockproof(? I'm not sure if that's necessary to reproduce this bug, and I'm not in a position to test this right now).
1. Use a screwdriver on a door and then use a multitool to open up the hacking menu.
2. Pulse the shock wire.
3. While the hacking menu is still open, walk away from the door.
4. The door will emit sparks (as if it was shocking you) until you close the hacking menu.

**Comment by kriskog** [comment] 2019-11-12 02:26
If it wasnt clear, you can make the door spark by hitting the buttons while not next to it. Needs a range check.

**Comment by Jewelry-x** [comment] 2024-10-13 23:53
If the shock wire is currently named "High Voltage Ground", I tried reproducing and I was not able to, so I will have to assume it has been fixed indirectly by some PR through the years. I will put a cleanup flag for the time being since I think it has been fixed. Please inform me if that is not the case.

**Closed** 2024-10-15 19:56 UTC
Labels: Bug, Cleanup Flagged
