### ISSUE TITLE
You can't order canisters from cargo anymore

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57954] opened 2021-03-25 21:55 UTC
## Reproduction:

I'm guessing as a consequence of #57844, but all canisters in cargo are no longer purchasable. They're still in the supply console UI and in the NT IRN app, but clicking on them from the UI does nothing (no credits subtracted, no adding to cart) and throws no runtimes in game. 

If it's intended that gas should be collected from the bluespace vendors instead of cargo, the listings should be removed from the UI. Otherwise the canister packs just do nothing.

**Comment by dragomagol** [comment] 2021-03-30 01:36
Technically #58026 is a duplicate of this, but that one is linked in the PR

**Closed by dragomagol** 2021-03-30 01:36 UTC
