### ISSUE TITLE
Due to the fact that you can no longer fit pets in backpacks, #52918 is fuck

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#54021] opened 2020-09-27 23:34 UTC
## Round ID:
[147195](https://scrubby.melonmesa.com/round/147195)

## Testmerges:
#53329
#53596

## Reproduction:
Pick up bee (passive grab then drag unto self).
Try to put in bee box or bee backpack to make a bee trap. Fail because you cant put pets in backpacks anymore.
Fuck PETA.
Bring back bee bombs #52918

**Comment by MrMelbert** [comment] 2020-09-28 07:37
duplicate of #53872 but you're based for doing bee bombs

**Comment by msgerbs** [comment] 2020-09-28 16:29
Closing as a duplicate of #53872. But I agree, this is a tragedy and must be fixed!

**Closed by msgerbs** 2020-09-28 16:29 UTC

**Comment by brotherbeyondd** [comment] 2020-09-28 16:48
unbeelievable
