### ISSUE TITLE
Manly Dorf cannot be made, period.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#49981] opened 2020-03-15 18:06 UTC
Issue reported from  Round ID: [132269](https://scrubby.melonmesa.com/round/132269) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1511

As a consequence of this Bacchus Blessing cannot be made either. Beer and Ale don't mix into Manly Dorf.

**Comment by carshalash** [comment] 2020-03-16 00:47
Thank god.

**Comment by ArcaneDefence** [comment] 2020-03-16 00:50
I just updated my local, and cannot reproduce. 
Mind describing the situation in depth?

**Comment by kriskog** [comment] 2020-03-16 06:35
Cant reproduce this on latest master either.

**Comment by redguy999** [comment] 2020-03-17 00:01
maybe it was just some code decided not to work correctly?

**Comment by RiskySikh** [comment] 2020-03-17 06:02
weird, I was able to make manly dorf

**Comment by necromanceranne** [comment] 2020-03-17 07:02
I have no idea why it occurred if it can't be reproduced. I suppose I'll give it another attempt at reproducing later but straight up I couldn't get it to be created in the given round.

**Comment by kriskog** [comment] 2020-03-17 16:36
Were you using the ingredients from the booze dispenser?

**Comment by necromanceranne** [comment] 2020-03-17 17:15
I was using debug tools but someone in the game was using standard booze dispenser.

**Comment by necromanceranne** [comment] 2020-03-17 17:15
@nemvar also this isn't my first issue what the hecc QwQ

**Comment by kriskog** [comment] 2020-03-17 18:41
Issue jannie fell for the good first issue trap 🤡
![image](https://user-images.githubusercontent.com/33292112/76890259-51c59b80-6887-11ea-9d57-f8c6ebf0671c.png)

**Comment by lordpidey** [comment] 2020-03-18 00:53
Is it possible you were trying to use the wrong type of beer as an ingredient?  Hacked service borgs can make a toxic beer that is very hard to distinguish between regular beer.

**Comment by nemvar** [comment] 2020-03-19 13:48
I be closing this now

**Closed by nemvar** 2020-03-19 13:48 UTC
Labels: Bug, Good First Issue, Needs Reproducing
