### ISSUE TITLE
All IED sprite are bugged

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28182] opened 2017-06-07 12:57 UTC
![dreamseeker_2017-06-07_13-51-49](https://user-images.githubusercontent.com/28678854/26879395-d3a0031c-4b88-11e7-8e7f-317ff5d8e3bf.png)
http://i.imgur.com/1KVJC8f.png

issue: Thirteen Loko IED/firebomb sprite is misaligned completely.

how to reproduce: I crafted the IED using the thirteen loko in the MetaStation engineering.

edit: the beaker i used for the welding fuel consumed the welding fuel but the sprite looks like it still has welding fuel in it - http://i.imgur.com/nzIm4DG.png http://i.imgur.com/c2U47bY.png

**Comment by PraiseRatvar** [comment] 2017-06-07 13:50
and all ied sprites are broken btw round id is 71519 if that helps

**Comment by Tacolizard** [comment] 2017-06-07 19:50
This has been known for a while. Also please change the title to say that all IED sprites are bugged.

Thanks for the report

**Comment by bgobandit** [comment] 2017-06-08 02:40
this also happens with ass copies, weird shit

**Comment by WJohn** [comment] 2017-06-08 07:58
Dupe of #19809, but since this provides a pic I'll close the old one.

**Closed** 2017-06-11 22:28 UTC
Labels: Bug, Sprites
