### ISSUE TITLE
There is an ERROR node in the tech web R&D console

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#40973] opened 2018-10-16 21:12 UTC
Round ID: 95572

![image](https://user-images.githubusercontent.com/12382984/47047791-857f2c00-d190-11e8-8c30-3a57ac90be06.png)

Everything but weapons research and illegal/abductor had been researched up to this point.

**Comment by ShizCalev** [comment] 2018-10-16 21:37
Duplicate of #40783

**Closed by ShizCalev** 2018-10-16 21:37 UTC
