### ISSUE TITLE
Blob Spores ignore Rally attempts

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#58999] opened 2021-05-09 20:11 UTC
Reporting client version: 513.1542

## Round ID:
[161941](https://scrubby.melonmesa.com/round/161941)

## Reproduction:
Drop a factory down as a blob and attempt to rally your spores. 
Be sad that your spores ignore every attempt to rally so long as they are on a blob tile.
Remove blob tiles just to order your spores.

**Comment by RaveRadbury** [comment] 2021-05-09 20:16
duplicate of #56742

**Closed** 2021-05-12 16:12 UTC
