### ISSUE TITLE
Jittering causes people to render on a lower z level

### ISSUE THREAD

**Issue by NotACoderSorry** [tgstation/tgstation#87823] opened 2024-11-10 15:55 UTC
### Client Version:

515.1642

### Issue Summary:

On multiz maps, jittering on a floor will make you periodically render as if on the lower z level, sometimes making you invisible

### Round ID:

[241817](https://scrubby.melonmesa.com/round/241817)

### Test Merge Information:

- [[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is](https://www.github.com/tgstation/tgstation/pull/87742)
- [(TM ONLY) (THIS IS A TEST PR) Batons have their stamina damage reduced by armor, but get stun armor penetration based on some factors (THIS IS A TEST PR)](https://www.github.com/tgstation/tgstation/pull/87754)

### Reproduction Steps:

Load multiz map
Don't be on the bottom floor
Start jittering
Observe
May be a BYOND issue

**Comment by Sadboysuss** [comment] 2024-11-10 15:56
duplicate of https://github.com/tgstation/tgstation/issues/84327

**Comment by NotACoderSorry** [comment] 2024-11-10 16:13
That's an issue with *flip this is an issue with jittering

**Closed** 2024-11-12 14:59 UTC
