### ISSUE TITLE
Non functioning livers when combined with higadrite make infinite chems

### ISSUE THREAD

**Issue by Castone001** [tgstation/tgstation#78992] opened 2023-10-14 05:22 UTC

**Comment by gueba14** [comment] 2023-10-14 16:38
Ive seen it be done with plama fixation viruses but not with higadrite, also having a dead liver slowly kills your other organs

**Comment by timothymtorres** [comment] 2023-10-15 23:14
Did you test to see if the reagent effects function with a dead liver?  The reagent code skips processing for most chems if the mob doesn't have a liver so it stays inside them without getting metabolized. (although a dead liver might still count as having a liver) 

Do the chem effects still trigger? (like healing damage, etc.)

**Comment by Castone001** [comment] 2023-10-15 23:21
> Do the chem effects still trigger? (like healing damage, etc.)
I am unsure if all chem effects still trigger, but chems such as bath salts, ephedrine, and methamphetamine still work, and are not consumed due to having a non functioning liver. This combined with higadrite prevents you from taking tox damage from the liver, and allows you to have these effects forever as all chems in your system, including the higadrite is not consumed. Another user mentioned that you take organ damage for having a dead organ, and im not sure if that is functioning as intended as i do not believe you take any other organ damage.

**Comment by gueba14** [comment] 2023-10-15 23:39
> > Do the chem effects still trigger? (like healing damage, etc.)
> > I am unsure if all chem effects still trigger, but chems such as bath salts, ephedrine, and methamphetamine still work, and are not consumed due to having a non functioning liver. This combined with higadrite prevents you from taking tox damage from the liver, and allows you to have these effects forever as all chems in your system, including the higadrite is not consumed. Another user mentioned that you take organ damage for having a dead organ, and im not sure if that is functioning as intended as i do not believe you take any other organ damage.

You do take organ dammage it just takes time

**Comment by MGOOOOOO** [comment] 2023-10-16 05:17
> Did you test to see if the reagent effects function with a dead liver? The reagent code skips processing for most chems if the mob doesn't have a liver so it stays inside them without getting metabolized. (although a dead liver might still count as having a liver)
> 
> Do the chem effects still trigger? (like healing damage, etc.)

I've experimented with this before the bug report was made so I'll provide what I learned about this.

The idea is to get all of the reagents to start working in your bloodstream, then killing your liver before the reagents get completely used up. Reagents that apply effects on begin and end consumption, like Bath Salts and Happiness, will never end as the dead liver prevents the reagent from being used up. However, healing chems that apply an effect per metabolized tick like Libital will not work in a dead liver, so only specific chems work with the dead liver strat. Chems that also purge on their own don't care for dead livers either, like Gravitum. Higadrite is necessary because your other organs will start failing without it, and you will take constant toxin damage as well.

The only way to really outlive the damage caused either by the liver and/or combat is to create a virus or use medkits, Plasma Fixation/Water Healing are good choices as you can permanently restore health by using them. Plasma Fixation can heal up to 12 damage per tick if you have plasma internals and have plasma in your bloodstream (which the dead liver won't process). Water healing is not as good, but is an adequate second choice.

I'm not exactly sure how this is supposed to be fixed, maybe another check for begin/end reagents to look for dead livers maybe?

**Comment by timothymtorres** [comment] 2023-10-16 05:24
We might need to add the begin/end consumption effects when the liver dies or is removed.

**Comment by Castone001** [comment] 2023-10-16 05:24
> I'm not exactly sure how this is supposed to be fixed, maybe another check for begin/end reagents to look for dead livers maybe?

Probably just remove higadrite entirely, i have never once seen it used as its much more of a pain to produce than a cyber liver, surgery, and basic tox meds. No higadrite=liver and other organ damage so if you want you can still hulk out on bathsalts without them depeleting, but your organs will fail and you would eventually die as a result. Alternatively give higadrite an independent consumption rate like gravitum

**Comment by MGOOOOOO** [comment] 2023-10-16 05:37
> > I'm not exactly sure how this is supposed to be fixed, maybe another check for begin/end reagents to look for dead livers maybe?
> 
> Probably just remove higadrite entirely, i have never once seen it used as its much more of a pain to produce than a cyber liver, surgery, and basic tox meds. No higadrite=liver and other organ damage so if you want you can still hulk out on bathsalts without them depeleting, but your organs will fail and you would eventually die as a result. Alternatively give higadrite an independent consumption rate like gravitum

I'd really like to see the dead liver strat still be a thing as it's pretty funny, but the biggest drawback of it should stay. Removing Higadrite sounds like the quickest way to fix this, however it can still be somewhat mitigated. Adding Sensory Restoration to your virus as well, at least so your eyes and ears won't die before your other organs do.

**Comment by RikuTheKiller** [comment] 2024-01-02 13:20
Ah this is a problem of us not using the goddamn proper procs (or triggering those procs properly) for certain chems.
Stuff like bath salts wouldn't work with a dead liver if the buffs were removed when consumption stops, regardless of the cause. (not just when its removed from the mob)

We have procs for that and I THINK they work, but not sure and I don't know if bath salts specifically use them, either.
But yeah, a fix for this is basically already in place, it's a matter of just going through chems and making everything consistently use those procs.

**Comment by RikuTheKiller** [comment] 2024-01-02 13:22
So the solution to fixing this definitely isn't something stupid like removing higadrite.

Also fun fact I actually had to use higadrite a couple times when people were spamming alcohol nades and pens.

**Comment by gueba14** [comment] 2024-04-13 18:13
so was this fixed in the end?

**Comment by RikuTheKiller** [comment] 2024-04-13 23:09
Probably not. I haven't played for a while but I'm pretty sure it's rarely if ever used.

**Comment by Chappyfart** [comment] 2024-05-11 17:05
to my knowledge this is still in the game.

**Closed** 2024-07-23 19:38 UTC
Labels: In Game Exploit, Bug
