### ISSUE TITLE
Custom Burger sprites broke

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#38529] opened 2018-06-16 14:55 UTC
[Round ID]: # 89565

[Testmerges]: # #38098: 'Transit space refactor' by kevinz000 at commit f6564b51f4
#38329: '[READY] [TESTED] Fusion Rework Episode V: The Phantom Fusion' by cyclowns at commit 7ef2165c90

[Reproduction]: # Make a custom burger. It just looks like the bottom bun!

**Comment by bgobandit** [comment] 2018-06-16 15:31
dupe https://github.com/tgstation/tgstation/issues/38433?

**Comment by SpaceManiac** [comment] 2018-06-16 18:59
Duplicate of #38433

**Closed by SpaceManiac** 2018-06-16 18:59 UTC
