### ISSUE TITLE
Energy Sword has no sprite when equipped to suit slot

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#86587] opened 2024-09-10 03:58 UTC
### Client Version:

515.1643

### Issue Summary:

Equipping an energy sword, whether on or off, to your suit slot displays the purple error sprite instead of any actual sprite
![NVIDIA_Share_xaQQhZGqRc](https://github.com/user-attachments/assets/24f9972b-0bb0-4c4e-b071-6e59616073b6)
![NVIDIA_Share_BZEBVgmB9L](https://github.com/user-attachments/assets/3e7b37f8-23af-41c3-80d2-92035e456d4b)
![NVIDIA_Share_MVv7fueSsZ](https://github.com/user-attachments/assets/0632eefe-bbc4-42b8-b2a1-9f7868a53fa7)

### Test Merge Information:

BYOND Version: 515.1642
Server revision compiled on: 1994-09-10T23:59:35+00:00
Master commit: [3bed86ad5f4409a421efa9ada1582d9ebabb35ed](https://www.github.com/tgstation/tgstation/commit/3bed86ad5f4409a421efa9ada1582d9ebabb35ed)
The following pull requests are currently test merged:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit bfecdb9b39](https://www.github.com/tgstation/tgstation/pull/83227)
[#85947: '[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.' by Timberpoes at commit 5129320ea0](https://www.github.com/tgstation/tgstation/pull/85947)
[#85512: 'Storage / table interactions at the bottom of the interaction chain' by MrMelbert at commit 781afd4d26](https://www.github.com/tgstation/tgstation/pull/85512)

### Reproduction Steps:

Equip energy sword to any suit slot that allows it (Infiltrator mod, Syndicate mod, probably others)
Observe your characters sprite has the purple colouring on it when there should be an e-sword sprite

**Comment by Sealed101** [comment] 2024-09-22 05:31
Duplicate of #69938

**Closed by Sealed101** 2024-09-22 05:32 UTC
Labels: Sprites, Good First Issue, Consistency Issue
