### ISSUE TITLE
Skeletons can't drink or "digest" milk

### ISSUE THREAD

**Issue by oether-ch4** [tgstation/tgstation#69887] opened 2022-09-13 15:33 UTC
Reporting client version: 514.1568

## Round ID:
[190416](https://scrubby.melonmesa.com/round/190416)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

* be a skeleton
* try to drink milk
* milk falls out as you don't have a stomach
* try to use a milk patch
* milk doesn't get processed, stays in your system indefinitely
* try to get a stomach + liver
* nothing changes except you can now ingest reagents (they only get transferred from your stomach to your "bloodstream")
* syringes, sutures, and mesh also don't work obviously

This makes healing as a skeleton incredibly difficult, wiki still says you should drink milk, and I've not seen any commits recently that pertain to skeletons specifically.

**Comment by itseasytosee** [comment] 2022-09-13 15:40
this is related to my pr which messes with stomachs an NO_HUNGER

**Comment by msgerbs** [comment] 2022-09-13 17:51
Duplicate of #69777

**Closed by msgerbs** 2022-09-13 17:51 UTC
