### ISSUE TITLE
wrong color for acid

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#18554] opened 2016-06-14 01:18 UTC
[Note]: # sulfuric acid is green and not orange

**Comment by coiax** [comment] 2016-06-17 13:18
Sulfuric acid (alternative spelling sulphuric acid) is a highly corrosive strong mineral acid with the molecular formula H2SO4 and molecular weight 98.079 g/mol. It is a pungent-ethereal, colorless to slightly yellow viscous liquid that is soluble in water at all concentrations.[6] Sometimes, it is dyed dark brown during production to alert people to its hazards.[7] The historical name of this acid is oil of vitriol.[8]

**Comment by bgobandit** [comment] 2017-01-05 23:19
close this meme issue, not a bug

**Comment by coiax** [comment] 2017-01-05 23:53
Also, I think acid /is/ green now.

**Comment by kilkun** [comment] 2017-01-06 01:11
not a meme, yes its a bug

**Comment by XDTM** [comment] 2017-07-27 18:29
not a bug

**Closed** 2017-07-27 19:12 UTC
Labels: Bug
