### ISSUE TITLE
Plumbing grinder is broken

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#78409] opened 2023-09-17 16:05 UTC
## Reproduction:

Build plumbing grinder, wrench it, throw a sheet of material in it. It deletes the sheet and gives no reagents.

**Comment by SyncIt21** [comment] 2023-09-17 16:43
You need to connect the grinder to an duct or output gate to collect the reagents. Also as per #78268 the grinder will grind as many sheets as possible till it gets filled to max capacity and will stop grinding the remaining sheets afterwards


https://github.com/tgstation/tgstation/assets/110812394/26c61fcd-90b2-430b-9f02-cf26b2e118d7

Not a bug. everything works

**Comment by Livrah** [comment] 2023-09-17 16:54
> You need to connect the grinder to an duct or output gate to collect the reagents. Also as per #78268 the grinder will grind as many sheets as possible till it gets filled to max capacity and will stop grinding the remaining sheets afterwards
> 
>  It.Works.mp4 
> Not a bug. everything works

![Screenshot_230](https://github.com/tgstation/tgstation/assets/64209864/414bdae6-b7f4-4128-bb4d-740dd9f63315)
Full setup, with duct under the conveyor. Grinder is empy after eating a sheet, with or without duct connection.

**Comment by SyncIt21** [comment] 2023-09-17 17:05
Your setup is wrong there is no duct or output gate connected to the grinder blue output pipe.
![Screenshot (299)](https://github.com/tgstation/tgstation/assets/110812394/ec71949f-26ec-4d50-8f62-938b6b392c72)
Also you need to place the conveyer belt near the grinder and not put the grinder on top of it. There is so many wrong things going on here

**Comment by Livrah** [comment] 2023-09-17 17:44
> Your setup is wrong there is no duct or output gate connected to the grinder blue output pipe. ![Screenshot (299)](https://user-images.githubusercontent.com/110812394/268516870-ec71949f-26ec-4d50-8f62-938b6b392c72.png) Also you need to place the conveyer belt near the grinder and not put the grinder on top of it. There is so many wrong things going on here

duct under the conveyor sprite, if first message wasn't clear. 
If this somehow doesn't work because of conveyor belt, than I should edit issue title. Automathic plumbing is broken, you need a conveyor belt onver the grinder. It worked few weeks ago.

**Comment by Livrah** [comment] 2023-09-17 17:48
Looking at the PR, looks like many things doesn't work as intended. You can't walk into grinder or out materials from 3 directions, can't put sheets by hand, it wastes entire stack of material even if it gives nothing.

**Comment by SyncIt21** [comment] 2023-09-17 17:59
Just as i suspected. Not only is your plumbing setup broken but you also have no idea what your talking about. None of the problems you stated exist. Re read the PR thoroughly before you comment blindly.

Also with conveyer belts the grinder works as expected. 

> it wastes entire stack of material even if it gives nothing

The stack is still on the tile even after grinding. It only grinded what was necessary and preserved the rest. Look at the video below carefully

https://github.com/tgstation/tgstation/assets/110812394/974e95ee-c1e7-40a8-a8e6-c949979af1be

**Comment by SyncIt21** [comment] 2023-09-17 18:01
> You can't walk into grinder

Again this was intentional. I explicitly stated why i removed this ability in the PR body and in the changelog. Again re read the PR before you make any further comments

**Comment by Livrah** [comment] 2023-09-17 18:03
> Just as i suspected. Not only is your plumbing setup broken but you also have no idea what your talking about. None of the problems you stated exist. Re read the PR thoroughly before you comment blindly.
> 
> Also with conveyer belts the grinder works as expected.
> 
> > it wastes entire stack of material even if it gives nothing
> 
> The stack is still on the tile even after grinding. It only grinded what was necessary and preserved the rest. Look at the video below carefully
> 
>  Again.It.Works.mp4

Report was about yday round. Admin confirmed grinder did runtimes. Tested it now, "my broken setup" is working fine again. It was something in [214753](https://scrubby.melonmesa.com/round/214753)


> > You can't walk into grinder
> 
> Again this was intentional. I explicitly stated why i removed this ability in the PR body and in the changelog. Again re read the PR before you make any further comments

I meant I could still walk in the grinder from one direction.

**Comment by SyncIt21** [comment] 2023-09-17 18:08
> can't put sheets by hand

Just for the record


https://github.com/tgstation/tgstation/assets/110812394/dc79a6d9-33af-4996-b519-9cbcf83bf995


> I meant I could still walk in the grinder from one direction.

I mean i couldn't

https://github.com/tgstation/tgstation/assets/110812394/b44bcfb1-b835-4eb7-803b-f8ad3d52183e

The only possible explanation is that the server you were playing in wasn't updated with my PR. cause all of this works in local.
Anyway close this issue since you said it works now

**Comment by HalfPunch** [comment] 2023-09-17 18:08
#78268 was supposed to fix this, but I don't see it in Terry's changelog
![image](https://github.com/tgstation/tgstation/assets/91390177/1d9cb579-78c1-4451-97ad-7afad24b0e07)

**Comment by Livrah** [comment] 2023-09-17 18:10
> #78268 was supposed to fix this, but I don't see it in Terry's changelog ![image](https://user-images.githubusercontent.com/91390177/268520261-1d9cb579-78c1-4451-97ad-7afad24b0e07.png)

It was 17.09 on Manuel

**Comment by SyncIt21** [comment] 2023-09-17 18:10
Yeah just as i suspected my name and PR isn't mentioned in the changelog so the server isn't updated. Wait a few hours and you should see my name there

**Closed** 2023-09-17 18:15 UTC
