### ISSUE TITLE
Weird wallet business

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#28420] opened 2017-06-13 06:57 UTC
OOC: Whypop:  my jumpsuit caught on fire and fell apart, causing my wallet in my ID slot to fall off, when i picked it up, inside was money instead of the two ID cards I had inside

He said that the items inside were definitely not on the floor, and it was definitely not a different wallet

Items inside were interactable

**Comment by Jalleo** [comment] 2017-06-13 12:19
Sounds like a swap occurs or duplication of a different wallet.

**Comment by FantasticFwoosh** [comment] 2017-06-16 16:53
Wallets start pre-loaded when they are generated with the map, sounds like a similar instance to the now fixed chemistry smartfridges that used to fill up when they were reset. it must have generated a new wallet for you.

Practically just take the same approach and have all wallets that start privately be "preloaded" with some loot weight would be a fast fix, and have newly crafted or broken wallets as this bug alludes to be regular empty wallets (stuff got burned?) or the very same wallet you had.

EI -
```
/obj/machinery/smartfridge/chemistry/preloaded
	initial_contents = list(
		/obj/item/weapon/reagent_containers/pill/epinephrine = 12,
		/obj/item/weapon/reagent_containers/pill/charcoal = 5,
```

**Comment by Xhuis** [comment] 2017-06-19 20:00
I can't reproduce this on the latest master. When my jumpsuit burns off with a wallet equipped, the contents of the wallet don't change.

**Comment by AnturK** [comment] 2018-04-15 13:45
Can't reproduce, going to assume this was something fixed with interaction changes in meantime.

**Closed by AnturK** 2018-04-15 13:45 UTC
Labels: Bug, Needs Reproducing
