### ISSUE TITLE
Glass floor tiles dropping a glass sheet when crowbared

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#52802] opened 2020-08-08 15:58 UTC
Issue reported from  Round ID: [143800](https://scrubby.melonmesa.com/round/143800) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1525

crowbaring a glass floor tile will give you a glass sheet that contains 0 sheets of glass

**Comment by ShizCalev** [comment] 2020-08-08 22:44
Duplicate of https://github.com/tgstation/tgstation/issues/52707

**Closed by ShizCalev** 2020-08-08 22:44 UTC
