### ISSUE TITLE
Life bringers cant vend seeds, dont have money or ID card

### ISSUE THREAD

**Issue by Autisem** [tgstation/tgstation#48475] opened 2019-12-30 10:35 UTC
## Reproduction: Play as a life bringer

The life bringer eco system on lavaland has a seed vendor, but these vendors need both valid ID card and money. As a life bringer you have neither so you cant vend seeds so you cant really do much

Maby add a ID card with money on request until this is fixed?

**Comment by HomocidlePancakes** [comment] 2019-12-30 15:08
They don't need an ID to be operated.

**Comment by Autisem** [comment] 2019-12-30 16:22
> 
> 
> They don't need an ID to be operated.

They do now due to the new GUI. They also have prices attached now

**Comment by trollbreeder** [comment] 2019-12-30 16:32
Duplicate of https://github.com/tgstation/tgstation/issues/48437

**Comment by HomocidlePancakes** [comment] 2019-12-30 16:38
They always had prices attached, even though it was free.

**Comment by Autisem** [comment] 2019-12-30 16:39
> 
> 
> They always had prices attached, even though it was free.

Yeah but now they cost money, and ofcourse still the issue you need a card to use the GUI

**Comment by Autisem** [comment] 2019-12-30 16:39
> 
> 
> Duplicate of #48437

Sorry didnt know it was there

**Closed** 2020-01-01 13:59 UTC
