### ISSUE TITLE
all in one grinder not working

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#31867] opened 2017-10-18 07:27 UTC
Issue reported from Round ID: 77609

All-in-one Grinder is not working for some stuff, tried the one in botany, in the bar and in chemistry. When grinding nutriment filled wheat it gives flour as intended, when I put pottasium into the wheat and grind it it does the grinding animation but it doesn't consume the wheat nor give pottasium

**Comment by AnonymousNow** [comment] 2017-10-18 07:57
Tried this with Space Twinkies and nothing happened. Xenobiology's plasma grinding escaped the worst of it even as other departments lamented their grinders, but that might have changed.

**Comment by ShizCalev** [comment] 2017-10-18 15:37
Duplicate of #31697

**Closed by ShizCalev** 2017-10-18 15:37 UTC
