### ISSUE TITLE
Defibrillator paddles stuck in hand

### ISSUE THREAD

**Issue by JannisKuckei** [tgstation/tgstation#32513] opened 2017-11-07 22:01 UTC
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

It just happened to me again, this time weirder than ever. Sadly I can't tell you how this happens, but I can say what happens. Sometimes when I use defibrillators, the paddles appear to leave my hand. However, the game behaves as if one of my hands was still holding the paddles. This is invisible in the GUI, but you will not be able to pick up items.
Now it just happened to me, so I told another player to take the defib off me and use it. Magically, while HE was holding the defib, the paddles started appearing in MY hands (in the GUI) as he used it.
Reconnecting will not fix any of this. Sometimes it resolves itself, this time I had to just leave because I was basically playing without arms.

So based on my rudimentary knowledge there's probably some event that's not caught properly

**Comment by ShizCalev** [comment] 2017-11-08 00:42
Dupe of #20602 ?

**Comment by JannisKuckei** [comment] 2017-11-08 01:07
Related I guess but this is different. Nobody died, and the paddles were invisible in my hand until someone else picked it up and used it. More importantly, the one who used it after me did not have any issues with it.

**Comment by ShizCalev** [comment] 2018-06-01 18:29
I believe I fixed this.

**Closed by ShizCalev** 2018-06-01 18:29 UTC
Labels: Bug, Needs Reproducing
