### ISSUE TITLE
Snow tiles are space?

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#42546] opened 2019-01-27 14:54 UTC
Snow tiles dont have air on them, and they dont take air from surroundings, they kinda act like pressurized space?

**Comment by imsxz** [comment] 2019-01-28 00:16
they should have air on them, just cold lower pressure air. they have planetary atmos and will constantly try to regulate their own air to be cold and at a certain pressure.

**Comment by FantasticFwoosh** [comment] 2019-01-30 14:53
Snow tiles have atmospherics like basalt lavaland tiles do, by default they're set to a temperature and gas composure that makes them regulate the gas mixes ontop of them, leading to voids sucking in air and lots of them changing the localised atmosphere when put together into a clump.

In short the snow tiles you might be referencing were never made for the station but for use on away missions, the biodome's snow tiles might be different though. Go complain to your resident admin for spawning the wrong type.

- Feel free to add your own compatible snow tiles, snow items are not maintained at all.

- Not a bug.

**Comment by adamkad1** [comment] 2019-01-30 15:27
i should have mentioned it was from genetic mutation. also someone fixed it apparently
Thanks for your really constructive criticism tho

**Comment by adamkad1** [comment] 2019-01-30 15:34
https://github.com/tgstation/tgstation/commit/52b19df3216e4acedd54f479283bce7784e7c2e8

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-01-30 18:42
wasn't there a fix for this

**Comment by ExcessiveUseOfCobblestone** [comment] 2019-01-30 18:43
#42563

**Closed by ExcessiveUseOfCobblestone** 2019-01-30 18:43 UTC
Labels: Bug
