### ISSUE TITLE
Cat ear customization option is missing

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#86544] opened 2024-09-07 22:12 UTC
### Issue Summary:

When I open the character preferences menu, I do not see any options to edit felinid ears. It is supposed to be a real pref, attached to the felinid ear organ.

### Reproduction Steps:

- Open character preferences
- Notice that there is no felinid ear type selection option

**Comment by SmArtKar** [comment] 2024-09-08 07:15
Duplicate of #86452

**Closed by SmArtKar** 2024-09-08 07:15 UTC
