### ISSUE TITLE
Ungenerated Turfs after Comms Agent Lavaland Ruin Explosions

### ISSUE THREAD

**Issue by DragonTrance** [tgstation/tgstation#59338] opened 2021-05-26 22:34 UTC
I'm unsure what the exact reason for this is, I saw this when the round was almost over
Round ID: [162973](https://scrubby.melonmesa.com/round/162973)

![image](https://user-images.githubusercontent.com/26515331/119733776-da967a80-be2e-11eb-9228-48ae05da8703.png)
![image](https://user-images.githubusercontent.com/26515331/119733798-dff3c500-be2e-11eb-9c9d-1891899c5ac2.png)
![image](https://user-images.githubusercontent.com/26515331/119733885-fbf76680-be2e-11eb-93aa-fdeceea976bc.png)
![image](https://user-images.githubusercontent.com/26515331/119733919-0ade1900-be2f-11eb-9bfb-744ec3b40361.png)

**Comment by Qustinnus** [comment] 2021-05-27 09:08
this is a mapping bug, those areas on the non gen turfs should be passthrough

**Comment by dragomagol** [comment] 2021-05-29 01:03
Duplicate of #57449

**Closed by dragomagol** 2021-05-29 01:03 UTC
