### ISSUE TITLE
Goof's Ion Law changes makes ion laws able to delete Law 0 Malf

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37661] opened 2018-05-04 08:57 UTC

**Comment by optimumtact** [comment] 2018-05-04 09:04
Abusive language is unacceptable

**Comment by Arianya** [comment] 2018-05-04 09:07
Goof's changes are pretty handicapable.

**Comment by optimumtact** [comment] 2018-05-04 09:12
The github terms of service are clear, please don't break them

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-04 17:47
@Iamgoofball

**Comment by Iamgoofball** [comment] 2018-05-04 18:38
i dont think I've touched ion laws in like 2 years

**Comment by ExcessiveUseOfCobblestone** [comment] 2018-05-05 15:56
That just makes this issue even more funny.

**Comment by optimumtact** [comment] 2018-05-05 21:15
I'm gonna close this, it has no actual steps to reproduce, round id's or information and unfairly attacks someone who is unlikely to to be the culprit.

**Closed by optimumtact** 2018-05-05 21:15 UTC

**Comment by DaxDupont** [comment] 2018-05-05 21:26
@optimumtact it's @Jordie0608's code and seems very much intended. 
https://github.com/tgstation/tgstation/blob/6ec0feeb55ca9188212ba50a25b2c6f2ab46ecc9/code/datums/ai_laws.dm#L318

**Comment by Jordie0608** [comment] 2018-05-06 04:01
#36463 only affected the handling of hacked laws so I believe this would've been pre-existing, but I can't see how yet. I'll try and catch it happening.
