### ISSUE TITLE
dismembered felinid heads have no cat ears

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42397] opened 2019-01-17 06:58 UTC
how can i immerse myself while doing gods work if the beheaded catpeople magically lose their ears?

**Comment by PKPenguin321** [comment] 2019-01-17 09:12
genetically engineered catgirl ears are held up by contorted muscles in the arms. when the head is detached from the body, these horrifically grotesque mutant-muscles are severed, and the ears fall down flat. this is why they are not visible on the severed head; they are actually pressed up flatly against the top of it.

not a bug. please close

**Comment by Mooshimi** [comment] 2021-12-28 19:51
Dupe of #32229

**Closed by Mooshimi** 2021-12-28 19:51 UTC
Labels: Consistency Issue
