### ISSUE TITLE
Flight suits allow you to slip past closed blast doors

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#38856] opened 2018-07-02 04:39 UTC
How to reproduce: If an airlock is closed on the same turf that a blast door is closed on, you can slip through it with a flight suit as if it was just the airlock there. It only works on blast doors.

**Comment by SpaceManiac** [comment] 2018-07-02 05:02
Could have sworn this was fixed, but apparently not.

Duplicate of #36112.

**Closed by SpaceManiac** 2018-07-02 05:02 UTC
Labels: Bug
