### ISSUE TITLE
Augmentions and android race are STILL invinsible

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#24683] opened 2017-03-04 20:58 UTC
I know this is a dupe but considering its still not fixed and litteraly turns you invinsible which can be used for abuse without knowing the bug existing

**Comment by KorPhaeron** [comment] 2017-03-04 22:20
I can't reproduce this. Every time I do augment sugery in the thunderdome it works out fine, with either kind of arm (surplus or regular)

**Comment by jughu** [comment] 2017-03-04 22:28
No kor its augmentions

**Comment by KorPhaeron** [comment] 2017-03-04 22:33
Robot limbs right?

**Comment by jughu** [comment] 2017-03-04 22:57
Yea robot limbs

**Comment by jughu** [comment] 2017-03-04 22:58
And the green slime mutation toxins for the android one

**Comment by Incoming5643** [comment] 2017-03-04 23:20
That's the crux of it, putting on limbs manually seems like it works however magic mirror/mutation toxin gives android race doesn't work correctly.

**Comment by TalkingCactus** [comment] 2017-03-08 12:17
With the left arm replaced with `Augmentation` and the right replaced with `Amputation` -> `Prosthetic Replacement`, the left arm turns out invisible with the render key of `l_arm-robotic-robotic` and the right arm with `r_arm-robotic` while being visible.
Full render key:
`icon_render_key = "human-coloured-african1-female-chest-organic-human-head-organic-human-l_arm-robotic-robotic-r_leg-organic-human-l_leg-organic-human-r_arm-robotic"`
Picture:
![pic](http://image.prntscr.com/image/e5ea6f2eab594cb48f1720a54621f86b.png)

**Comment by TalkingCactus** [comment] 2017-03-08 12:19
A simple fix for this would be to physically replace the limb with the robotic variant rather than just changing the status var on the augmented limb.

**Comment by RemieRichards** [comment] 2017-03-08 12:33
That's not the fix we want however, you've done good tracing it to the render key, but why is it doubling up on the "-robotic" subkey, I wrote that system so I'd be very pleased to know who broke it!

**Comment by TalkingCactus** [comment] 2017-03-08 12:39
Haven't located the problem yet, but I'm also seeing instances where if you just do one augmentation without an amputation on the same person it will give you this key for the augmented limb: `l_arm-robotic-human`

**Closed** 2017-03-25 13:01 UTC
Labels: Bug
