### ISSUE TITLE
Infinite Super Melatonin injections from limited chemicals

### ISSUE THREAD

**Issue by CinzaFalso** [tgstation/tgstation#63284] opened 2021-12-07 03:16 UTC
## Round ID:
[174331](https://scrubby.melonmesa.com/round/174331)

## Reproduction:
I put up 5u Super Melatonin on a normal 15u syringe and injected myself with it, after the injection, which was successful, the 5u super melatonin remained on the syringe while I had 5u on my system. I also tested a 15u injection, the problem remained, the syringe was still full and I got 15u of Super Melatonin on my system

**Comment by MrMelbert** [comment] 2021-12-08 02:03
This may be a bug with syringes in general instead of just Super Melatonin.

**Comment by SuperNovaa41** [comment] 2021-12-08 03:36
Duplicate of https://github.com/tgstation/tgstation/issues/63301
the other one has a better name

**Closed by SuperNovaa41** 2021-12-08 03:36 UTC
Labels: In Game Exploit, Bug, FUCK
