### ISSUE TITLE
Purple suit, purple suit

### ISSUE THREAD

**Issue by conk444** [tgstation/tgstation#62743] opened 2021-11-11 05:42 UTC
Reporting client version: 514.1557

## Round ID:
[172850](https://scrubby.melonmesa.com/round/172850)

## Testmerges:
- [multiz movement refactor redux](https://www.github.com/tgstation/tgstation/pull/62132)
- [Departmental Security Rework: Department First, Security Second](https://www.github.com/tgstation/tgstation/pull/62727)

## Reproduction:
step one: wear Orderly (medical security) suit casually
step two: purble suit.

**Comment by ArcaneDefence** [comment] 2021-11-11 17:25
The name of this issue sucks and forces you to open it to know what is happening.
It's just that outfit shouldn't be adjustable/needs an adjusted sprite

**Comment by ArcaneDefence** [comment] 2021-11-11 17:36
This is from https://github.com/tgstation/tgstation/pull/62727
The various `/obj/item/clothing/under/` types do not have an adjusted sprite, and do not prevent you from attempting to wear them casually, as `can_adjust` is not changed.

**Comment by ArcaneDefence** [comment] 2021-11-11 17:41
Duplicate of https://github.com/tgstation/tgstation/issues/62736

**Closed by ArcaneDefence** 2021-11-11 17:41 UTC
Labels: Sprites, Bug, Test Merge Bug
