### ISSUE TITLE
Photographs don't show janicart nor windows

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/tgstation#7092] opened 2015-01-15 14:26 UTC
Photographs do not show whole-tile windows.

They also do not capture the janicart.

They also do not get fire lights.

Nor Plasma.

Fix that shit.

**Comment by Chocobro** [comment] 2015-01-15 15:42
photographs don't show a lot of things, i've been compiling an image for quite some time but no better time than this to post it.
http://i.imgur.com/jnLmrsX.png

**Comment by Jalleo** [comment] 2015-01-16 10:36
Chocobro what is the reason for the photographs to not work so well?

**Comment by Miauw62** [comment] 2015-01-16 15:49
photographs are weird magic, i don't know how they work exactly.

**Comment by RemieRichards** [comment] 2015-01-16 15:50
it's a LOT of dark getFlatIcon() magic.

**Comment by Chocobro** [comment] 2015-01-17 05:28
jalleo I don't know the slightest about dm code I cannot tell you how this bug is caused

**Comment by Jalleo** [comment] 2015-01-17 09:57
thats fine RemieRichards explained it

**Comment by tedward1337** [comment] 2016-10-29 05:04
Fixed by #8658

**Comment by phil235** [comment] 2016-10-30 22:53
fulltile windows still do no appear.

**Comment by Cyberboss** [comment] 2017-01-17 14:41
Janitorial cart definitely does not appear. I did a VV on a janitorial cart vs a grille (both are direct subtypes of obj/structure). They had virtually no differences. So I checked the icons the only difference I can tell is grilles have a green alpha background, while carts have a grey alpha background. Does that mean anything?

**Comment by octareenroon91** [comment] 2017-04-21 23:47
This issue persists. It seems also that closets stop showing up after they've been moved.

**Comment by Alek2ander** [comment] 2017-05-21 19:52
It seems that getFlatIcon just fails on windows. Possibly caused by #23922?
On the other hand getFlatIcon only fails on a few specific space turfs, like 147,76,1 on box, but photos fail to show any space turf, possibly caused by parallax.

**Closed** 2018-01-16 13:32 UTC
Labels: Bug, Sprites
