### ISSUE TITLE
anomalies can spawn in places where they shouldnt 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38680] opened 2018-06-23 13:34 UTC
bagil 89920
it spawned in the holodeck -1218 which is an emagged holodeck place and the holodeck wasnt emagged so it was unaccessible

**Comment by AnturK** [comment] 2018-06-23 13:51
Duplicate of #38677

**Closed by AnturK** 2018-06-23 13:51 UTC
