### ISSUE TITLE
New red sec uniform does not display properly when worn casually

### ISSUE THREAD

**Issue by bolien** [tgstation/tgstation#19874] opened 2016-08-14 05:57 UTC
So this new sec uniform, the red one with the yellow stripe on the arm, does not appear properly in game when you wear it casually.

When worn casually it disappears completely and red letters appear near your character that say SUIT.

**Comment by PKPenguin321** [comment] 2016-08-14 07:00
Technically not a bug since the PR isn't merged yet

**Closed** 2016-08-14 07:04 UTC
