### ISSUE TITLE
Stepping on minuscule amounts of blood without shoes covers the entire body in blood. 

### ISSUE THREAD

**Issue by Sandmoney** [tgstation/tgstation#53300] opened 2020-08-29 08:04 UTC
## Round ID:[145254](https://scrubby.melonmesa.com/round/145254)

Any amount of blood on the ground while not wearing shoes seemingly fully coats the person in blood. Sometimes even when there isn't any visible blood on the ground. Most of the time it doesn't make sense for the feet to even be bloodied from the ridiculously small amounts of blood present, let alone the entire body to get soaked in it. Should be noted I play a digi lizard.

**Comment by Donkie** [comment] 2020-08-30 10:57
This is caused by my https://github.com/tgstation/tgstation/pull/53109 PR. I assume you were wearing a hardsuit or similar that covers your feet? Previously, your shoes would get bloody underneath the hardsuit, but with my PR the hardsuit get bloody now instead as it should be, which makes the entire suit bloody.

However I understand that this can be annoying so I'll consider some way to make this act better

**Comment by Sandmoney** [comment] 2020-08-30 13:57
Even when I'm not wearing a hardsuit, it'll coat the entire body in blood. Granted this only seems to occur when you aren't wearing shoes. Though my main gripe is stepping in any amount of blood will cause you to become bloody, even if you can barely even see the stuff.

**Comment by Donkie** [comment] 2020-08-30 17:53
Cannot recreate you getting all bloody without wearing any jumpsuit/suit that has built-in feet, tried with digiliz. However I am working on a patch that prevents you from picking up any blood if it's too little on the ground.

**Comment by Sandmoney** [comment] 2020-09-01 02:20
Recreated it in a round.
![dreamseeker_2020-08-31_18-25-31](https://user-images.githubusercontent.com/66013112/91787405-a30be200-ebbe-11ea-9291-12ad8b40bdd6.png)
![dreamseeker_2020-08-31_18-25-40](https://user-images.githubusercontent.com/66013112/91787413-a901c300-ebbe-11ea-95f9-80868f856fbe.png)

As you can see, simply stepping in the faded footprints will fully cover me in blood.

**Comment by TheBonded** [comment] 2021-12-09 20:01
fixed by https://github.com/tgstation/tgstation/pull/57085 I believe

**Closed by TheBonded** 2021-12-09 20:01 UTC
Labels: Bug, Tested/Reproduced
