### ISSUE TITLE
CAN'T EAT MUH SWEETROLL!!1

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#81929] opened 2024-03-10 03:35 UTC
Reporting client version: 515.1633

## Issue Summary

Everybody loves sweet rolls!
![image](https://github.com/tgstation/tgstation/assets/106118256/72177ab2-52eb-408a-a712-7cb355b38f51)
Well, except for those who never tried them.. And there are probably a lot of these people on /tg/, because when cooked honey sweetrolls are unavailable for consumption!

## Round ID:
[225284](https://scrubby.melonmesa.com/round/225284)

## Reproduction:

1. Prepare a honey sweetroll.
2. Try to eat it.
3. See how it does nothing. You can try to "hit" yourself with it by clicking in a "Harm" mode, but when you simply try to eat it - nothing happens. Literally nothing.

**Comment by WarerBrow** [comment] 2024-03-10 03:37
It also produces zero reagents when grinded.

**Comment by Vermidia** [comment] 2024-03-10 07:41
This appears to be caused by the potassium and water in the sweet roll blowing up all the other reagants in the food. You can inject bananas with water and they also lose all their reagents. It's in small enough amounts you don't explode, at least.

**Comment by TheVekter** [comment] 2024-03-20 16:52
Closing this as a duplicate of the above bug.

**Closed by TheVekter** 2024-03-20 16:52 UTC
Labels: Bug
