### ISSUE TITLE
Engiborgs can‘t create airlock electronics

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35766] opened 2018-02-17 17:26 UTC
As the title says: Engiborg adaptive pseudocircuits don‘t include airlock electronics.

**Comment by Xhuis** [comment] 2018-02-17 18:54
This was intentional, since airlock electronics require configuration and so aren't "simple" circuits. They also have inbuilt RCDs which can already create airlocks.

**Comment by ShizCalev** [comment] 2018-02-17 19:24
Intentional
Duplicate of #31018

**Closed by ShizCalev** 2018-02-17 19:24 UTC
