### ISSUE TITLE
Money value wont change when stacked

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#32348] opened 2017-11-02 14:37 UTC
Money stacks say for example:

 That's some space cash.
It's worth 2000 credits
They are a tiny item.
There are 6 one thousand credit bills in the stack.

When I looked last time 6x1000 wasnt 2000. The value is still the one before they were stacked.

**Comment by WJohn** [comment] 2017-11-02 19:47
Dupe of #31928

**Closed by WJohn** 2017-11-02 19:47 UTC
Labels: Bug, Consistency Issue
