### ISSUE TITLE
Bug Report: Rechargers

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#38924] opened 2018-07-05 05:44 UTC
Issue reported from  Round ID: 90511 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

All the rechargers on Meta Station appeared to not be working for anyone, regardless of intent. This resulted in being unable to recharge energy weapons and stun prods.

**Comment by ninjanomnom** [comment] 2018-07-05 05:48
duplicate of #38880

**Closed by ninjanomnom** 2018-07-05 05:48 UTC
