### ISSUE TITLE
Delta Station Cryo Tube UI unusable unless windows removed

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#81346] opened 2024-02-08 01:21 UTC
## Reproduction:
Load Delta station and spawn yourself in (important because UI works as ghost, but not as living mob)
Cryo tubes will be unusable.
Use buildmode to remove windows directly to the right of cryo tubes and UI will work.  Also work with walls in place, but UI cannot be opened by clicking on the tube while in a mob if the windows are directly to the right of the tube.
This has been happening for a while now and may be related to https://github.com/tgstation/tgstation/issues/80983

**Comment by MrMelbert** [comment] 2024-02-08 01:28
This is actually a dupe of #81095 - `get_turf_pixel` for the cryo tube is returning the turf to the right of the tube, which, if obscured by a window, will be obscured, and thus you cannot click on it. 

However it does not use pixel_z while the heretic rune does so this is ... adjacent issue, I guess? Not sure

**Comment by MrMelbert** [comment] 2024-02-08 01:52
I can confirm #80873 caused this though, by changing the layer that cryo cells sit on

**Closed** 2024-02-09 01:36 UTC
