### ISSUE TITLE
Mob AI not responding

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#56128] opened 2021-01-12 11:52 UTC
## Testmerges:
https://github.com/tgstation/tgstation/pull/55956

## Reproduction:
The bubblegum and legion megafauna did not do their attack patterns properly when i and another miner fought them, and didn't move during the "fight." the regular legion mobs also did not spawn skulls or move, even when i attacked them. I also fought the hierophant, whose attacks seemed to work correctly.

**Comment by Ryll-Ryll** [comment] 2021-01-12 23:27
After testing, this seems to be constant across all hostile mobs, even when attacked and provoked, it might even be an issue with mob AI in general.

I spawned a variety of hostile mobs in the thunderdome and couldn't get them to pay any attention to me, but while I was writing up an issue report for it, some of them would randomly attack me once then return to dormancy, several minutes after being spawned. It seemed to me like their AI was asleep for long periods of time, then they'd randomly wake up for a tick and act, then go back to sleep. I ran these tests about an hour into the round, and the Mob Controller was running at around 200%.

Here's a profile I took:
[![](https://i.imgur.com/KyeU68pl.jpg)](https://i.imgur.com/KyeU68p.png)

**Comment by optimumtact** [comment] 2021-01-12 23:56
someone broke the wakeup code for off station z's most likely

they're supposed to wake up if you move onto the z within their vicinity

**Comment by Timberpoes** [comment] 2021-01-13 00:27
Similar behaviour with on-station simplemobs. The NPC Pool and Idling NPC Pool subsystems were in an almost permanent state of pause, meaning MC_TICK_CHECK kicked in and paused them.

If you can replicate/witness this again, check to see if NPC Pool and Idling NPC Pool subsystems are [P]

**Comment by LemonInTheDark** [comment] 2021-01-13 03:14
perhaps related to #55965

**Comment by ShizCalev** [comment] 2022-07-08 17:43
Caused by #63520

**Comment by LemonInTheDark** [comment] 2022-07-08 20:09
I'm not sure this is actually a dupe of #67873 
This issue looked a LOT like the issues we had with time distribution post "the subsystem fuckup" https://github.com/tgstation/tgstation/pull/64500, so subsystems not receiving the proper allotment of cpu time, due to tivi's attempt to revive a harsh change that limited background subsystem cpu time.
Also it was opened a year before the mob abilities refactor

**Closed by LemonInTheDark** 2022-07-08 20:09 UTC
Labels: Priority: High
