### ISSUE TITLE
Borgs cant restock metal.

### ISSUE THREAD

**Issue by TheLeopold** [tgstation/tgstation#55116] opened 2020-11-22 21:15 UTC
Engineering (probably others too) borg cannot restock metal, wires and other stackable things by clicking on in.

Reporting client version: 513.1532

**Comment by dragomagol** [comment] 2020-11-22 21:42
Duplicate of #54931 (it has a PR up, should be fixed soon!)

**Closed by dragomagol** 2020-11-22 21:42 UTC
