### ISSUE TITLE
Infinite food creation

### ISSUE THREAD

**Issue by ZaccharyBlaize** [tgstation/tgstation#45986] opened 2019-08-17 15:29 UTC
Prepare a bowl and a sheet of runed metal. I had 3 sheets in my stack
Deep fry the metal and add it to the bowl
It makes a salad
But also drops the metal on the floor ready to be re-fried and repeat the process.

**Comment by kriskog** [comment] 2019-08-17 16:31
Duplicate of #44123

**Closed by kriskog** 2019-08-17 16:31 UTC
Labels: Bug, In Game Exploit
