### ISSUE TITLE
shapeshifting + holoparasite bugs

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#59127] opened 2021-05-15 10:45 UTC
acquiring a holoparasite, shapeshifting, and then returning to your normal form kills your holoparasite.

acquiring a holoparasite, shapeshifting, and then damaging your holoparasite damages your original form inside of you, not your shapeshifted form. acquiring a holoparasite, shapeshifting, and then damaging your shapeshifted form does not damage your holoparasite's host, according to its status panel.

acquiring a holoparasite, shapeshifting, and then casting mind transfer on your holoparasite puts you in control of your original body inside of your shapeshifted one. casting fireball while in this state makes you shout ONI SOMA, but doesn't appear to actually fire any projectile. knock appears to be uncastable while in this state. casting shapeshift again while in this state kills you. I haven't tested what happens if you try to cast blink or jaunt while in this state.

**Comment by SuperNovaa41** [comment] 2021-05-15 21:19
semi duplicate of and related to https://github.com/tgstation/tgstation/issues/25287

**Comment by timothymtorres** [comment] 2021-08-19 16:24
So I had to fix polymorph code for pAIs not too long ago and one thing I noticed is that the polymorph code is not universal.  There are several different procs for polymorph, changeling monkeys, shapeshifting, malf robo factories, etc.  all using their own separate code to get the desired effect.  The problem then results in stuff like this issue here.  Each part of the code that transforms a mob is different.  We really need just one `polymorph` proc that handles everything and we can squeeze in all the extreme edge cases like holoparasites, mechs, etc. into it a lot easier.

**Comment by timothymtorres** [comment] 2021-08-19 16:28
Another related edge case involving shapeshifting/polymorphing with mechs at #55153

**Comment by timothymtorres** [comment] 2021-09-23 19:51
Putting a list here of all polymorph methods:

Polymorph code
Monkey turning into a gorilla from rads
Pride's mirror
Envy's knife
Ling monkey shapeshift
Ling transform sting
Wizard shapeshift spell
Vampire shapeshift spell
Lesser Ash drake lootdrop spell
Injecting genetics UE change into monkey
Malf AI robo factory
Polymorph staff (wabbjack)

**Closed** 2022-09-01 21:44 UTC
Labels: Bug, Consistency Issue
