### ISSUE TITLE
Titanium isn't smeltable at the mining furnace.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#26205] opened 2017-04-14 00:15 UTC
In the mining base with the mining furnace, you can't smelt titanium. Normally this would be irrelevant to most people but the gulag prisoners can only smelt ores via the furnaces, thus giving them useless ores to work with.

**Comment by KorPhaeron** [comment] 2017-04-14 01:42
Titanium should be removed and replaced by a silver/plasma alloy

**Comment by Profakos** [comment] 2017-04-14 07:45
Duplicate of #25166

**Comment by duncathan** [comment] 2017-04-14 07:55
Other issue is more accurate

**Closed by duncathan** 2017-04-14 07:55 UTC
