### ISSUE TITLE
Thrown welding helmet does not obscure vision

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#87573] opened 2024-10-30 05:38 UTC
### Client Version:

515.5164

### Issue Summary:

If a welding helmet(up) is thrown onto your head, you can toggle it down with no obscured vision

### Round ID:

[241005](https://scrubby.melonmesa.com/round/241005)

### Test Merge Information:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit bfecdb9b39](https://www.github.com/tgstation/tgstation/pull/83227)
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit aac758d4e5](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. Get welding helmet
2. Toggle up as to not obscure vision
3. Throw at someone's head
4. That person toggles it down
5. Free flash protection without the obscured vision

**Comment by Sealed101** [comment] 2024-10-31 16:24
is it a consistent problem or is it https://github.com/tgstation/tgstation/issues/52972

**Comment by Deadgebert** [comment] 2024-11-03 09:32
it is a consistent problem. 
you cannot replicate it on your own in round, you must have someone throw the helmet onto you, but it works 100% of the time.

**Comment by SmArtKar** [comment] 2024-11-26 23:40
Duplicate of #85028 actually

**Closed by SmArtKar** 2024-11-26 23:40 UTC
Labels: Bug
