### ISSUE TITLE
Slot machines say "FUCK" on them

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58370] opened 2021-04-13 00:50 UTC
Reporting client version: 513.1536

## Round ID:
[160164](https://scrubby.melonmesa.com/round/160164)

## Testmerges:
Manuel
- [[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing](https://www.github.com/tgstation/tgstation/pull/58313)

## Reproduction:
title says it all, slot machines say FUCK on their sprite currently for some reason.

**Comment by dragomagol** [comment] 2021-04-13 01:26
Duplicate of #58286

**Closed by dragomagol** 2021-04-13 01:26 UTC
