### ISSUE TITLE
You can't buy a detective special goodie crate as non-captain/hos

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#72750] opened 2023-01-16 05:36 UTC
Reporting client version: 514.1589

## Round ID:
[198312](https://scrubby.melonmesa.com/round/198312)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
Try to buy one, get told you have "insufficient access". Get a captain or HoS id and it would work. Weirdly the warden or QM id does not work.

**Comment by Sealed101** [comment] 2023-01-16 05:53
#72125

**Comment by private-tristan** [comment] 2023-01-16 06:07
just checked, detrevolvers/thermal pistols weren't intended to be purchasable by assistants? there goes one of the final reasons to do bounties.

https://github.com/tgstation/tgstation/blob/64522da1e7677d7b7108c2ae55403a693e37a3ca/code/modules/cargo/goodies.dm#L29-L33

**Comment by necromanceranne** [comment] 2023-01-19 07:23
There is actually a bug here, if it isn't checking access attached to the goodie item itself but requires a head access. That should probably be resolved.

**Comment by Baskett55** [comment] 2023-01-19 21:10
I only tested buying it with a warden and QM id and it failed, not sure if the warden has ACCESS_FORENSICS_LOCKERS or if its something else.

**Comment by necromanceranne** [comment] 2023-01-20 12:54
They do not have that access. I'll probably need to reproduce this as a detective then.

**Comment by Xander3359** [comment] 2023-01-24 23:18
![image](https://user-images.githubusercontent.com/66163761/214442411-46da94e9-4594-46f3-8cbc-afc1d2005af2.png)
Colt requires ACCESS_DETECTIVE to purchase.
High pop Warden does not have ACCESS_DETECTIVE
![image](https://user-images.githubusercontent.com/66163761/214442539-285548b8-71af-456b-a50a-39e8b42f9591.png)
And the QM never has this access.
I would close this as not a bug.

**Comment by Xander3359** [comment] 2023-01-24 23:28
In fact, per this PR https://github.com/tgstation/tgstation/pull/72125 you, as non-sec, are not even supposed to be able to see revolvers on the console at all. The fact that you can be denied access is, in itself, a bug.

**Comment by Xander3359** [comment] 2023-01-24 23:36
> just checked, detrevolvers/thermal pistols weren't intended to be purchasable by assistants? there goes one of the final reasons to do bounties.
> 
> https://github.com/tgstation/tgstation/blob/64522da1e7677d7b7108c2ae55403a693e37a3ca/code/modules/cargo/goodies.dm#L29-L33

Pretty much all guns now require you to have some sort of sec/brig/armory access now.

**Closed** 2023-02-02 23:40 UTC
Labels: Bug, Needs Reproducing
