### ISSUE TITLE
Fishing minigame always results in a fail.

### ISSUE THREAD

**Issue by remuluson2** [tgstation/tgstation#73585] opened 2023-02-21 20:23 UTC
## Round ID:
[200543](https://scrubby.melonmesa.com/round/200543)

## Reproduction:

1. Try to fish with any rod, any type of reel or hook.
2. finish minigame
3. positive minigame result doesnt trigger, you fail to catch the fish.

**Comment by necromanceranne** [comment] 2023-02-22 04:36
@AnturK @GoldenAlpharex We've had a reversion I guess, might be worth a unit test

**Comment by Sealed101** [comment] 2023-03-13 15:24
kinda a dupe of #70067 ?

**Comment by Ghommie** [comment] 2023-09-03 12:12
Dupe, and I believe we're gradually fixing the issue.

**Closed by Ghommie** 2023-09-03 12:12 UTC
Labels: Bug, Needs Reproducing
