### ISSUE TITLE
Humanized syndicate monkey reinforcements go go go.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84711] opened 2024-07-06 13:53 UTC
Issue Summary:
So they were added back in here
https://github.com/tgstation/tgstation/pull/79012

The current issue with them now is You can freely give mutadone to humanize the monkey person, gaining 3 humans that are loyal to you and are no longer bound by monkey things.

**Comment by ATH1909** [comment] 2024-07-09 07:00
have you seen this actually happen? is https://github.com/tgstation/tgstation/pull/83720 not preventing this?

**Comment by Profakos** [comment] 2024-07-19 14:11
Duplicate of #84701

**Comment by Sealed101** [comment] 2024-09-16 21:43
^

**Closed by Sealed101** 2024-09-16 21:43 UTC
