### ISSUE TITLE
Humans on the derelict are killed by a nuclear explosion

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#7424] opened 2015-01-29 15:38 UTC
pretty sure this doesn't happen for the centcomm and shuttle transit z-levels. not 100% certain.

**Comment by PKPenguin321** [comment] 2015-01-30 03:21
Killed or knocked down indefinitely?

**Comment by SconesC** [comment] 2015-02-10 19:49
also happens to mining

**Comment by Dorsisdwarf** [comment] 2015-03-09 17:13
dupe/parent dupe of #7778 

One of these needs to be closed.

**Comment by phil235** [comment] 2015-03-09 19:40
The other one has already been closed.

**Comment by Dorsisdwarf** [comment] 2016-05-20 12:08
Is this still in effect?

**Comment by Jalleo** [comment] 2016-08-20 12:21
Is this connected to the honk nuke going off by any chance? As in everyone is actually buckled to a invisible bed which dosent exist on any z?

**Comment by Chocobro** [comment] 2016-08-23 13:47
@Jalleo not that i'm aware of. consider that this issue report is ancient

**Comment by KorPhaeron** [comment] 2017-01-03 18:59
This doesn't happen anymore

**Closed by KorPhaeron** 2017-01-03 18:59 UTC
Labels: Bug
