### ISSUE TITLE
The Hierophant can't kill assemblies

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#36184] opened 2018-03-05 20:25 UTC
small issue, all of its attacks only deal damage to mobs and mechs

**Comment by factoryman942** [comment] 2018-03-05 20:45
#36010

**Comment by arsserpentarium** [comment] 2018-03-07 00:26
Collossus surely can kill circuit bots.Have you tested it with hierophant?He have meele attack.

**Comment by ShizCalev** [comment] 2018-03-07 20:29
Duplicate of #36010

**Closed by ShizCalev** 2018-03-07 20:29 UTC
