### ISSUE TITLE
Lavaland syndicate base genturf

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#82039] opened 2024-03-16 12:48 UTC
Reporting client version: 515.1630

## Issue Summary
Title explains it all

## Round ID:
[225618](https://scrubby.melonmesa.com/round/225618)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
Wander into the syndicate lavaland base because you have your lava treads. Check the bomb for shits and giggles, see it's actively armed and flee. Come back after boom and have immersion RUINED.

![GENTURF MOMENT](https://github.com/tgstation/tgstation/assets/16981475/2734a159-4f54-4591-892e-71cf6d7db095)

**Comment by OuroborusReporter** [comment] 2024-03-16 17:40
Duplicate of #57449. Syndicates just be carpeting their homes with genturfs

**Closed** 2024-03-16 23:47 UTC
