### ISSUE TITLE
Flyperson vomit doesn't stack on tiles

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#15879] opened 2016-03-02 03:31 UTC
This means that if you eat real food you only leave one vomit puddle, meaning you can't refill your nutriment unless you find a ton of vomit somewhere.

**Comment by phil235** [comment] 2016-03-02 12:31
The stacking is intended, we don't want multiple decals of the same type on a single tile. The issue is that the new vomit that is merged with the old one doesn't give it its nutriment (or reagent or whatever).

**Comment by lordpidey** [comment] 2017-06-30 19:04
@Cyberboss this is no longer an issue now that flypeople projectile vomit.

**Comment by Cyberboss** [comment] 2017-06-30 19:06
Does the projectile vomit stack like phil said?

**Comment by lordpidey** [comment] 2017-06-30 19:07
No, a floor either has vomit or it doesn't.  If you think that's a problem, feel free to leave this up.

**Closed** 2018-06-01 14:58 UTC
Labels: Bug
