### ISSUE TITLE
fugitive issues

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#44345] opened 2019-06-06 00:21 UTC
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Here's a bunch of things wrong with fugitives I've found.

-Spacepol spawn with no means to arrest prisoners, their ship doesn't have handcuffs or stun batons, all they have is a very lethal gun when to get the best possible greentext you need to be nonlethal.
-The Spacepol (and presumably russians) space ship spawn in deep space with a console that can't fly to the station. Essentially they're stranded.
-Spacepol (and also presumably the russians) spawn with no radio though this might just be a feature.
-The hunters and the hunted both have an identical antag hud. Spacepol literally can't tell if one of their allies is a fugitive or an actual officer. This also completely fucks over stealth as the fugitives always have a target next to their head but that's more of a gameplay choice.
-Probably some other things i'm missing.

**Comment by wesoda25** [comment] 2019-06-06 03:45
@tralezab fix yo shit

**Comment by tralezab** [comment] 2019-06-06 03:52
The spacepol and russians have a working ship, let me double check

the rest is intentional, the antag hud sharing means fugitives can't put on the assistant jumpsuit and disappear. Something about having to search through all the crew to find the fugitives leads to some very shitty play

**Comment by tralezab** [comment] 2019-06-06 03:59
![image](https://user-images.githubusercontent.com/40974010/59006010-b8843780-87d4-11e9-87b3-aa7a19bfc7d3.png)
I was able to get the ships to move?

**Comment by ATH1909** [comment] 2019-06-07 01:32
> the rest is intentional, the antag hud sharing means fugitives can't put on the assistant jumpsuit and disappear. Something about having to search through all the crew to find the fugitives leads to some very shitty play

I think the issue here is that a fugitive looks identical to an officer on that HUD, and you should probably differentiate between the two with two separate icons for that HUD.

**Comment by tralezab** [comment] 2019-06-08 02:48
I can probably do that?

**Comment by Dorsisdwarf** [comment] 2019-06-19 15:44
@tralezab How resolved/nonexistant  are these issues?

**Comment by tralezab** [comment] 2019-07-25 20:14
the only thing that isn't fixed here is a dupe of #45156

**Closed** 2019-07-25 20:14 UTC
Labels: Bug
