### ISSUE TITLE
Hyperspace ripples don't appear prior to shuttle docking

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33534] opened 2017-12-14 11:04 UTC
title.

**Comment by ShizCalev** [comment] 2017-12-14 19:22
server revision? 

#33497

**Comment by ShizCalev** [comment] 2017-12-14 19:24
servers don't look to be updated yet.

**Comment by Cyberboss** [comment] 2017-12-14 21:55
Duplicate of #33479

**Closed by Cyberboss** 2017-12-14 21:55 UTC
Labels: Bug, Needs Reproducing
