### ISSUE TITLE
Can't put items into secure safe

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#20808] opened 2016-10-03 22:01 UTC
It's impossible to put any kind of items into secure safe. Clicking the safe with an item in hand does not deposit the item inside.

While secure safe's interface can be opened by dragging the safe sprite onto the player sprite, you can only use it to remove items from the safe, not to put them in.

**Comment by PKPenguin321** [comment] 2016-10-03 22:48
i believe this is a dupe

**Comment by phil235** [comment] 2016-10-04 02:28
duplicate of #20761

**Closed by phil235** 2016-10-04 02:28 UTC
Labels: Bug
