### ISSUE TITLE
White ship walls have no floors beneath

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#33968] opened 2017-12-30 21:27 UTC
**Round ID**: # 81077 (Terry)
**Test merged PRs**: #33908
**Issue**: 
The titanium walls of the white ship do not have floor panels or lattices beneath. 
Exposing the space tiles underneath the walls does not immediately cause a hull breach/drain gases (this only seems to happen once the shuttle enters transit). When players are on top of the tile, they lose footing/take damage as on regular space tiles. If they step on the exposed tile during transit, they get spaced.
Attempting to place lattices on these tiles does nothing (no error message). I wasn't able to test if RCDs can place floors.
**Expected result**:
Walls should have floors beneath them.
**How to reproduce**:
Deconstruct a white ship wall by using a welder or sonic jackhammer on it.

**Comment by Marflowerose** [comment] 2017-12-30 23:58
Dupe of https://github.com/tgstation/tgstation/issues/33907

**Closed** 2017-12-31 00:10 UTC
