### ISSUE TITLE
Exosuit Extinguisher doesn't redirect Exosuit in space.

### ISSUE THREAD

**Issue by McRex007** [tgstation/tgstation#30443] opened 2017-09-05 15:39 UTC
All I wanna do is have mech fights in space guys. Come on.

**Comment by FantasticFwoosh** [comment] 2017-09-05 15:52
See issue #30366

Or feel free to drop a [suggestion](https://tgstation13.org/phpBB/viewforum.php?f=9) or [feedback about this not meeting your expectations](https://tgstation13.org/phpBB/viewforum.php?f=10) on our forums.

**Comment by Repukan** [comment] 2017-09-05 17:18
Dupe

**Comment by Cyberboss** [comment] 2017-09-05 17:35
Duplicate of #9282

**Closed by Cyberboss** 2017-09-05 17:35 UTC
