### ISSUE TITLE
Wizards cant spawn

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#25147] opened 2017-03-15 21:43 UTC
The screen centered to a shuttle

![b092a67b96 1](https://cloud.githubusercontent.com/assets/6819554/23972064/7b701da0-09e1-11e7-98e0-ff7db1b44570.png)

**Comment by PKPenguin321** [comment] 2017-03-15 22:10
Type cancel-camera-view as a temporary fix.

**Comment by Cyberboss** [comment] 2017-03-15 22:15
@PKPenguin321 do you know why that works?

**Comment by PKPenguin321** [comment] 2017-03-15 22:16
No, just that 99% of bugs that involve seeing where your character isn't is fixed by that.

**Comment by Cyberboss** [comment] 2017-03-15 22:17
Hmm, ignore my fix then, I don't know why it's happening

**Comment by Jordie0608** [comment] 2017-04-04 07:35
@Cyberboss It seems like you never PR'd that last commit as a fix, did it not work?

**Comment by Cyberboss** [comment] 2017-04-04 11:55
Another maintainer asked me to find the root cause

**Comment by ShizCalev** [comment] 2017-10-09 17:37
Still an issue?

**Closed** 2017-11-22 21:54 UTC
Labels: Bug
