### ISSUE TITLE
Putting the Nuclear Authentication Disk in a custom vendor causes a tgui BSOD

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#59737] opened 2021-06-19 07:13 UTC
## Reproduction:
1) Price the disk using a price tagger.
2) Place disk in custom vendor.
3) BSOD

Script error.
   at https://tgstation13.download/byond/assets/7d/asset.7de576a0448fc623062a7619976dbd3f.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"vekter","interface":"Vending","window":{"key":"[0x2003bb2]-main","size":null,"fancy":1,"locked":1}}

I saw this on >reddit and thought to reproduce it. This is one hell of an edge case but it's a fun tactic to hide the disk so I figure we should enable it if we can.

**Comment by dragomagol** [comment] 2021-06-19 16:10
Duplicate of #59445 , but this appears to be a more significant consequence of the custom vendors breaking

**Closed by dragomagol** 2021-06-19 16:10 UTC
