### ISSUE TITLE
Cytology Research Plumbing Constructor's Machines wont connect

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#67843] opened 2022-06-17 16:34 UTC
## Reproduction: 
1. Grab the Research Plumbing Constructor. 
2. Plop down two machines in RND which had its floortile redone to metal flooring. The Input Gate and the Vat 
3. Go to the autolathe to grab a wrench, RD wrenches the two machines down. 
 4. Put your Cytology goop from your petri-dish into the vat. 4. After collecting your required chems, put it into the input gate. 
5. Watch as no matter how much you re-wrench it, move it, make new machines, change piping levels and colors the input gate and vat wont connect. 6. Scream as all your effort was for nothing and you cannot make mobs

![image](https://user-images.githubusercontent.com/29222521/174340063-b1265395-8fdd-4048-8d16-caebb9db31c9.png)

**Comment by Time-Green** [comment] 2022-06-19 08:42
Ehm, they’re obviously on different layers (I’m assuming you did try right, but just took the screenshot at an inopportune time). Did this continue into later rounds?

**Comment by Shadowflame909** [comment] 2022-06-19 08:53
Yeah I put all my reagents in that input gate so I tried every layer and Omni to try to connect with it. I also tried to connect two new ones on the same layer and that didn't work either

I haven't tried it again after this round though

**Comment by Time-Green** [comment] 2022-06-19 08:57
Oh god

**Comment by SyncIt21** [comment] 2023-10-29 12:35
> Omni layer

There is no such thing. Only omni color which still won't work if you have different color's

> Edit: one thing I neglected to mention is that the input gate would connect with a fluid duct. But no other machine, not even a holding tank which I tried to use to retrieve my reagents.

Also, unable to reproduce. For retrieving your reagents, you use an output gate not input(which is used for putting reagents into the system which is why it's called input)
![Screenshot (341)](https://github.com/tgstation/tgstation/assets/110812394/1ec48aec-fd1f-4c31-b137-8e2948e70e64)

@Time-Green you can close this

**Comment by Time-Green** [comment] 2023-10-29 14:15
and thusly it is done

**Closed by Time-Green** 2023-10-29 14:15 UTC
Labels: Bug
