### ISSUE TITLE
Instant cure to Paraplegia(Doctors hate him)

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#64122] opened 2022-01-15 05:04 UTC
## Round ID:
[176615](https://scrubby.melonmesa.com/round/176615)

## Reproduction:
Be Paraplegic, go through tele that isn't calibrated yet. Become a walking flyman.

**Comment by SuperNovaa41** [comment] 2022-01-15 05:05
lol

**Comment by NanoCats** [comment] 2022-01-15 06:25
> species changes remove all brain traumas... paraplegic is a brain trauma? 🤔

Pretty sure that yes, it is. It's a brain thing, there's nothing actually wrong with your legs themselves(?)

**Comment by timothymtorres** [comment] 2022-01-15 12:35
This is related to #40040

**Comment by Time-Green** [comment] 2022-01-15 13:23
> This is related to #40040

I don’t see how. Quirks are body specific, and while those methods in that issue create a new body, species changes do not.

**Comment by timothymtorres** [comment] 2022-01-15 13:48
Read the comments in that issue.  It doesn't just cover mindswapping, but transformations and polymorph.  That's why I said it's related and didn't mark it as a duplicate.

I do think we need to split up quirks into MIND / BODY / SOUL sources because right now they are all jumbled up from different sources.  The polymorph code is also a nightmare.  There are about 6 different transformation procs that handle it differently each time.

**Comment by Artemchik542** [comment] 2024-08-07 05:04
Can't reproduce this bug anymore, maybe fixed in https://github.com/tgstation/tgstation/pull/84805

**Comment by Artemchik542** [comment] 2024-08-07 05:17
https://github.com/tgstation/tgstation/issues/82546
https://github.com/tgstation/tgstation/issues/81651
looks same fixed, can't reproduce too

**Comment by Time-Green** [comment] 2024-08-07 05:34
Fixed in #84805

**Comment by Time-Green** [comment] 2024-08-07 05:35
Thank you for checking!

**Closed by Time-Green** 2024-08-07 05:34 UTC
Labels: In Game Exploit, Bug
