### ISSUE TITLE
Ice Box Multi Z Departments Immune To Rad Storms

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54313] opened 2020-10-11 05:54 UTC
## Reproduction:

1). Rad storm
2). Any ice box multi z department
3). Does not get rad stormed
4). Uh
5). Yes

**Comment by msgerbs** [comment] 2020-10-11 06:18
Is this in lower xenobio?

**Comment by msgerbs** [comment] 2020-10-11 06:20
Looks like this is because the upper and low Z levels of Ice Box are not station z-levels and rad storms only affect station z-levels.

**Comment by Misdoubtful** [comment] 2020-10-11 06:22
Yeah I failed to clarify, it encompasses both sections.

**Comment by msgerbs** [comment] 2020-10-11 06:57
So you didn't get a radstorm in the xenobio area on the main z-level? That's bizarre. Yeah, I was able to reproduce that as well. I'm at a bit of a loss here but I'll keep losing.

**Comment by msgerbs** [comment] 2020-10-11 07:47
Ugh this is so dumb. The lower Ice Box z-level is not set as a station z-level and the xenobio area is being considered as being on the lower z-level.

**Comment by MrMelbert** [comment] 2020-10-11 17:57
upper and lower botany on icebox are also immune to rad storms.

**Comment by msgerbs** [comment] 2020-10-11 18:02
Yeah, this likely affects any area which is on multiple z-levels.

**Comment by Whoneedspacee** [comment] 2020-10-29 01:00
feature lower z levels are safe 😎

**Comment by dragomagol** [comment] 2020-11-13 22:27
Fixed by #54779

**Closed by dragomagol** 2020-11-13 22:27 UTC
Labels: Bug
