### ISSUE TITLE
Vaping, smoking (and presumably ingesting) tiny amounts of chems that set a status flag will cause you to gain that flag and never lose it.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#36699] opened 2018-03-24 20:49 UTC
[Round ID]: N/A I tested this on hippie and a locally hosted version of tg.

[Testmerges]: None

[Reproduction]: put 1u of bathsalts in an ecig, top the rest up with water, vape it for a few seconds then take it out your mouth.

Congrats you're now unstunnable forever with none of the bathsalts downsides.

Same works for meth and its speed boost.

**Comment by PKPenguin321** [comment] 2018-03-24 20:51
Duplicate, and there's already a fix up

**Comment by ShizCalev** [comment] 2018-03-24 22:10
Duplicate of #36152

**Closed by ShizCalev** 2018-03-24 22:10 UTC
