### ISSUE TITLE
Wizard's spell cards don't have homing anymore

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#72040] opened 2022-12-16 13:28 UTC
Wizards have a spell called spell cards which was added in this PR https://github.com/tgstation/tgstation/pull/36147 Which has the intention for the cards to have homing against their targets with slight accuracy

This got closed in #48510 saying it was intentional(this is not the case if you look at its code)

Reproduction.
Step.1 Be a wizard and pick spell cards
Step. 2 have a genuine pig trying to dodfe
Step. 3 use your spell against him and see how nothing has homing against your target
step. 4 cry yourself to sleep as it only do 5 brute since everything else missed

**Comment by tralezab** [comment] 2022-12-17 00:59
@TheBonded don't close this one, this is a real issue!

**Comment by timothymtorres** [comment] 2022-12-17 09:40
Duplicate of #52946

**Closed by timothymtorres** 2022-12-17 09:40 UTC
Labels: Bug
