### ISSUE TITLE
Swarmers decimate mechs

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#29998] opened 2017-08-17 22:45 UTC
Any melee attack from a swarmer delimbs mech driver.

**Comment by Sartorius7** [comment] 2017-08-17 22:46
This is probably related to the issue with swarmers de-limbing people in closets.

**Comment by Dorsisdwarf** [comment] 2017-08-17 23:04
probbably because they call ex_act on object contents or something dumb

**Comment by RandomMarine** [comment] 2017-08-18 00:48
Someone make a NON-EXPLOSIONS CALLING EX_ACT label.

**Comment by Ergovisavi** [comment] 2017-08-18 15:50
As the creator of Swarmers I declare this a non issue because fuck mechs

And yes I'm entirely serious. If swarmers cannot identify you, they can't prevent themselves from harming you via deconstruction, anyway.

**Comment by MimicFaux** [comment] 2017-08-20 10:21
Not unreasonable. They are tools, albeit sentient ones. Sticking your fingers near a buzzsaw is gonna get glove shopping real hard.

**Comment by The-clown-known-as-Pepe** [comment] 2017-08-20 10:23
same thing happens when you get hit by collosus death bolts, probably because they delete walls too and mechs are treated as one?

**Comment by DoctoreMad** [comment] 2017-08-20 19:31
Of course while the Swarmers thing might not be seen as a issue the Colossus one definitely is, because MAKE RIPLEY GREAT AGAIN.

**Comment by Supermichael777** [comment] 2017-08-24 03:32
Ergo fix your shit, piggybacking off a specific implementation for a different system leads to this crap.  Its like the extreme opposite of copy pasting, trying to use a function like its static and generalized. It harms code improvement by creating bugs, impeding granular balance, and creating work duplicating shit in the future into its own procs for the behavior you want.  Its exactly as lazy as copy-pasta, just in the other direction..

**Comment by The-clown-known-as-Pepe** [comment] 2017-08-26 12:16
@Ergovisavi 
swarmers decimating mechs = TOTALLY A INTENDED FEATURE GUIS
swarmers doing 0 damage to borgs = TOTALLY A INTENDED FEATURE GUIS

**Comment by Ergovisavi** [comment] 2017-08-27 19:25
>Fix your shit

Fix what? What is there to fix? As far as I'm concerned this is not a bug, and therefore, it is not a bug. Let me know where this is causing a behavior that I do not want, and I'll fix it.

@The-clown-known-as-Pepe 
Yes, those are both not features. What's your point?

**Comment by DoctoreMad** [comment] 2017-08-27 21:29
~~Borgs are not biological components so swarmers should be able to damage them.~~ Wait don't borgs usually have brains inside of them?

**Comment by ktccd** [comment] 2017-08-30 00:02
Surely, a swarmer somehow DELIMBING the driver of a mech is a bug? Destroying the mech, sure, alright, I can totally see that being a thing. Somehow tearing apart the person inside through the mech? That really does sound like a bug...

**Comment by PKPenguin321** [comment] 2017-08-30 19:29
This is likely a duplicate

**Comment by XDTM** [comment] 2017-09-02 12:10
using ex_act is a bad idea anyway, since this also causes issues with lockers and is in general unreliable.

**Comment by YPOQ** [comment] 2018-06-02 02:38
Duplicate of #21116

**Comment by kriskog** [comment] 2019-07-18 04:40
Not true anymore

**Closed by kriskog** 2019-07-18 04:40 UTC
Labels: Bug
