### ISSUE TITLE
Disposal pipe launcher not working correctly

### ISSUE THREAD

**Issue by chesse20** [tgstation/tgstation#36618] opened 2018-03-22 05:44 UTC
[Round ID]: # 85353

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: #
![image](https://user-images.githubusercontent.com/9161779/37753258-4040857a-2d59-11e8-96f4-2f77fe776aa1.png) Before launch

![image](https://user-images.githubusercontent.com/9161779/37753336-a88d8b6e-2d59-11e8-8ccf-4b27cc166aae.png)
After Launch
I made a pipe network like this, and everytime i would try to launch out of it, it would destroy the floor and rods underneath where i launch out of causing a breach

**Comment by RandomMarine** [comment] 2018-03-22 08:44
Cannot reproduce.

**Comment by chesse20** [comment] 2018-03-23 01:14
![image](https://user-images.githubusercontent.com/9161779/37806365-cb94edfc-2dfc-11e8-9fce-eb996444d434.png)
reproduced it on round 85390

**Comment by DaxDupont** [comment] 2018-03-23 01:18
https://lithi.io/file/9nQ5.mp4

**Comment by YPOQ** [comment] 2018-03-23 01:59
#36633 is testmerged in round 85390

**Comment by ninjanomnom** [comment] 2018-03-29 05:59
Fixed in the testmerged pr this is introduced in.

**Closed by ninjanomnom** 2018-03-29 05:59 UTC
Labels: Bug
