### ISSUE TITLE
Server not rendering action menu

### ISSUE THREAD

**Issue by Lordxan** [tgstation/tgstation#77560] opened 2023-08-12 14:11 UTC
Having issue with self-hosted server as you can see from the screenshot i don't have any action menu
![image](https://github.com/tgstation/tgstation/assets/52027483/cc4b6cd9-ea49-48fb-972e-1145f131dbe4)
Server env:
- Ubuntu 22.04
- Docker version 24.0.5, build ced0996
- Commit: bcddf197e27ee5d339a4e03779645794e45e9051

**Comment by SyncIt21** [comment] 2023-08-12 15:32
This usually fixed itself when you 
- Clear cache on the server side before hosting
- Clear cache on the client side before connecting
- Clear cache & reconnect on the client side
Another weird issue that is resolved by these steps is TGUI windows being blank white and not closing.

**Comment by Lordxan** [comment] 2023-08-12 15:38
> This usually fixed itself when you
> 
> * Clear cache on the server side before hosting
> * Clear cache on the client side before connecting
> * Clear cache & reconnect on the client side
> 
> Another weird issue that is resolved by these steps is TGUI windows being blank white and not closing.
Thanks for the reply, I already tried to clear the cache on the client side but it did not work also how do you exactly clear the cache on the server side? The thing is I hosting it via docker container so the only persistent info is data and config dirs

**Comment by Lordxan** [comment] 2023-08-12 15:40
I also tried setting up a new env in VM and still got the same issue on the client even with fresh byond installation

**Comment by SyncIt21** [comment] 2023-08-12 15:56
Why do you host using docker? You can use Byond for client & server. By clearing cache for server i mean clear Byond cache before hosting the server on Byond

To host a server on Byond start a dream Daemon
![Screenshot (287)](https://github.com/tgstation/tgstation/assets/110812394/647f9d79-ff38-436b-b087-ac443d53f8d4)
Then select the dmb file inside your download by clicking on the `...` button
![Screenshot (288)](https://github.com/tgstation/tgstation/assets/110812394/a9c0f5e3-4600-455d-9997-718c1bc6c7e1)

Now to build the `dmb` file you need to first run the `clean.bat` file inside `bin` directory of your download to clear all logs & stuff & finally run `build.bat` in the order given in the pictures
![Screenshot (291)](https://github.com/tgstation/tgstation/assets/110812394/127ce25b-4126-4879-84c3-163a4243f1ff)

If you are using VM just run Byond server in VM and save the VM to resume Byond another day. I use HyperV in windows cause that's pre installed

**Comment by Lordxan** [comment] 2023-08-12 16:03
I using it for the convinience. So docker is not supported anymore?

**Comment by SyncIt21** [comment] 2023-08-12 16:05
I am not sure about docker cause i don't use it, I guess most people don't use it so it wasn't updated in a while causing bugs

**Comment by Lordxan** [comment] 2023-08-12 16:07
I guess i need to update it then lol

**Comment by SyncIt21** [comment] 2023-08-12 16:10
I meant docker by itself is highly relavent and has no problems, Its just that this code base Docker build might not run well on a container. Since docker is highly memory intensive and requires technical knowledge its an overkill for self hosted servers. Stick with Byond it sucks but you know atleast it works

**Comment by Lordxan** [comment] 2023-08-12 16:12
I mean i need to update dockerfile i kind of wanna to create a small footprint setup without spreading files all over the server

**Comment by Lordxan** [comment] 2023-08-12 16:16
Meanwhile, I wrote a quick docker file for Bay and it is working fine so I guess there is something wrong with the dependencies of tg

**Comment by SyncIt21** [comment] 2023-08-12 16:20
That's your personal preference then.  Its difficult to reproduce your issue so it will mostly be closed. It maybe related to rust dependencies as it was recently updated in this repo but idk just speculating. 

Now goona wait for more knowledgeable people to come across this. Signing out

**Comment by Lordxan** [comment] 2023-08-12 22:37
Update, basically i fix this issue by modifying `tools/deploy.sh`. I think this is related to `html` folder not being copied in final build but not sure. Here is the temp patch if someone find this issue later:
```
diff --git a/Dockerfile b/Dockerfile
index a27c64574f1..3e26ca7c7c2 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -39,6 +39,8 @@ RUN apt-get install -y --no-install-recommends \
 
 COPY . .
 
+RUN apt install -y rsync
+
 RUN env TG_BOOTSTRAP_NODE_LINUX=1 tools/build/build \
     && tools/deploy.sh /deploy
 
@@ -51,6 +53,7 @@ RUN apt-get install -y --no-install-recommends \
 
 # rust_g = base + rust_g compiled to /rust_g
 FROM rust AS rust_g
+ENV RUSTFLAGS="-C target-cpu=native"
 WORKDIR /rust_g
 
 RUN apt-get install -y --no-install-recommends \
diff --git a/tools/deploy.sh b/tools/deploy.sh
index b91eee1331e..32395fae0c5 100755
--- a/tools/deploy.sh
+++ b/tools/deploy.sh
@@ -9,43 +9,5 @@ if [[ $# -eq 2 ]] ; then
   cd $2
 fi
 
-mkdir -p \
-    $1/_maps \
-    $1/icons/effects \
-    $1/icons/mob/clothing \
-    $1/icons/mob/inhands \
-    $1/icons/mob/simple \
-    $1/icons/obj \
-    $1/icons/runtime \
-    $1/sound/runtime \
-    $1/strings \
-    $1/tgui/public \
-    $1/tgui/packages/tgfont/dist
-
-if [ -d ".git" ]; then
-  mkdir -p $1/.git/logs
-  cp -r .git/logs/* $1/.git/logs/
-fi
-
-cp tgstation.dmb tgstation.rsc $1/
-cp -r _maps/* $1/_maps/
-cp -r icons/effects/* $1/icons/effects/
-cp -r icons/mob/clothing/* $1/icons/mob/clothing/
-cp -r icons/mob/inhands/* $1/icons/mob/inhands/
-cp -r icons/mob/simple/* $1/icons/mob/simple/
-cp -r icons/obj/* $1/icons/obj/
-cp -r icons/runtime/* $1/icons/runtime/
-cp -r sound/runtime/* $1/sound/runtime/
-cp -r strings/* $1/strings/
-cp -r tgui/public/* $1/tgui/public/
-cp -r tgui/packages/tgfont/dist/* $1/tgui/packages/tgfont/dist/
-
-#remove .dm files from _maps
-
-#this regrettably doesn't work with windows find
-#find $1/_maps -name "*.dm" -type f -delete
-
-#dlls on windows
-if [ "$(uname -o)" = "Msys" ]; then
-       cp ./*.dll $1/
-fi
+mkdir -p $1/
+rsync -avz --exclude=".git" ./* $1/
\ No newline at end of file
```

**Closed** 2023-08-12 22:37 UTC
